### PR TITLE
mod_wsgi: update to 4.7.1, change to python 3

### PR DESCRIPTION
**Pull request by sgn**

### CODE REVIEW

**Comment by sgn** [comment]
@Chocimier Would we run into any problems with this change to python3.
I've a cross-compile ready, but it depends on python3 (I wouldn't want to change python2-config) and #22167

**Comment by sgn** [comment]
Accidental pushed to repo :/

**Comment by sgn** [comment]
Not pushed yet.

**Comment by Chocimier** [comment]
I do not use it, but looks fine.

**Pull request merged**
