### PR TITLE
terminus-font: Include OTB files

### PR DESCRIPTION
**Pull request by faulesocke**

### CODE REVIEW

**Comment by Chocimier** [comment]
Can you ask upstream will they provide that variant as well? They release rarely but steady.

**Comment by leahneukirchen** [comment]
fontforge must be hostmakedepends

**Comment by faulesocke** [comment]
Fixed this and cleaned the PR up a little bit.

**Comment by ahesford** [comment]
I believe you mentioned on IRC that you have requested that upstream either include the OTB files directly or provide a build target to convert other formats to OTB. If upstream obliges, a version bump will address this. If they refuse, I don't think Void should assume responsibility for converting font formats during packaging. Users can always convert fonts should the need arise.

**Comment by faulesocke** [comment]
Upstream replied yesterday and is aware of the problem. A new release offering multiple conversion methods was promised to come this year. I'll open a new PR then.

**Pull request closed without merging**
