### PR TITLE
Set `MOZ_ENABLE_WAYLAND` to launch firefox in wayland

### PR DESCRIPTION
**Pull request by concatime**
See https://bugzilla.mozilla.org/show_bug.cgi?id=1522780 for reference.

### CODE REVIEW

**Comment by Gottox** [comment]
Please increase the revision. Good to merge afterwards

**Comment by Johnnynator** [comment]
I'm not sure if a this small change actually justifies a full rebuild. It is probably soon enough if we have it in the next firefox update.

**Comment by Gottox** [comment]
Okay. I'd like to also set `MOZ_USE_XINPUT2=1` for firefox too. Is there any reason not to?

**Comment by Gottox** [comment]
ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1207700

**Comment by Gottox** [comment]
merging this for now.

**Comment by concatime** [comment]
@Gottox hey, first time I hear about `MOZ_USE_XINPUT2`, thank you.

**Pull request merged**
