### PR TITLE
[NEEDS TESTING]  common: point ELF interpreter to /usr/lib

### PR DESCRIPTION
**Pull request by CameronNemo**

### CODE REVIEW

**Comment by CameronNemo** [comment]
Welp, that throws a wrench in my attempt ahah...

I think my initial instinct to define this in build_profiles is a good one based on what I see in common/shlibs.

**Comment by CameronNemo** [comment]
Handled the glibc paths. musl is always the same. Still needs more testing.

**Comment by q66** [comment]
since we're already patching linker paths in gcc on 64-bit archs, i think a better way would be to simply create a unified patch altering the builtin linker path on all architectures we support, should be more reliable generally

**Comment by CameronNemo** [comment]
With musl we can always use `/usr/lib/libc.so`, right?

**Comment by q66** [comment]
yeah, musl uses a single linker plus symlinks

**Comment by leahneukirchen** [comment]
What even is the point of this?

**Comment by q66** [comment]
It also does not handle ppc64 BE. Also, on a second thought, making musl use libc.so seems like a pretty bad idea after all.

**Comment by CameronNemo** [comment]
@leahneukirchen main intention is to avoid the requirement of configuring the `/lib -> /usr/lib` symlink prior to invoking binaries in a chroot environment. Currently you will get an ENOENT if you try to use the chroot without configuring base files. Patching compilers to use /usr/lib for the linker path would solve that issue, and in my opinion it would make the usrmerge more complete.

**Comment by leahneukirchen** [comment]
It would also make Void use a different ELF interpreter than all other distros, sounds bad.

**Comment by CameronNemo** [comment]
@leahneukirchen if we just change from /lib to /usr/lib, usrmerged distros would still be compatible. e.g. Arch, Ubuntu, some Debian installs. Plus one could argue that internal validity is more important than external validity. Has Void ever supported using void packages/binaries on non-void distros? Note that I ack q66's recommendations in this PR: a compiler patch is ideal and pointing to libc.so.6 for musl is unnecessary / potentially troublesome. I think the compiler patch could even be upstreamed -- using the /lib prefix for the ELF interpreter is far from universal, as evidenced here.

**Comment by q66** [comment]
I think sticking with `/lib` is good. What we could do instead is just ship a bunch of those symlinks by default, without having `base-files` set them up (I can't seem to remember why this isn't being done already in the first place?)

**Comment by CameronNemo** [comment]
I have proposed some related changes to base-files in #17009 .

**Pull request closed without merging**
