### PR TITLE
milkytracker: update to 1.03.00.

### PR DESCRIPTION
**Pull request by rc-05**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (ARCH-LIBC)
- [ ] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [ ] aarch64-musl
  - [ ] armv7l
  - [ ] armv6l-musl

### CODE REVIEW

**Comment by ericonr** [comment]
They are looking for SDL2 in the wrong place for cross, it seems :/

Since it used to work, you probably need to make a patch reverting some commit in their build system.

**Comment by ericonr** [comment]
Maybe https://github.com/milkytracker/MilkyTracker/commit/87d0f55cd8868d91472f96cccafaf6fdb9e0cbbc ? But then we need to fix SDL2 / Cmake instead.

**Comment by rc-05** [comment]
> They are looking for SDL2 in the wrong place for cross, it seems :/
> 
> Since it used to work, you probably need to make a patch reverting some commit in their build system.

I'll fix it as soon as possible. I simply need to apply the patch exclusively to the cross targets: the question is how do I patch the cross targets?

**Comment by ericonr** [comment]
Nah, you should be able to apply it for all.

**Comment by rc-05** [comment]
> Nah, it should be ok to apply it for all.
> 
> Still, I'd prefer to figure out what CMake is doing wrong.

I do not understand why this error pops up in the first place: the source tarball is the same for all targets and yet on non-ARM architectures this builds correctly.

**Comment by ericonr** [comment]
How CMake (and other tools) search for dependencies can change (and have flaws) when cross building. That's the main difference. The upstream commit works on native builds, but it broke something for cross.

**Comment by Johnnynator** [comment]
Imo just revert the commit. Fixing the SDL2 provided stuff is far more pain.

**Comment by rc-05** [comment]
> Imo just revert the commit. Fixing the SDL2 provided stuff is far more pain.

Maybe I can restrict the number of architectures in the mean time so at least this package can be pushed forward, then when a fix is found (or upstream fixes this problem), I can push a new revision

**Comment by rc-05** [comment]
I've opened an issue to upstream, maybe they'll look into it and fix it

**Comment by ericonr** [comment]
I'm not sure upstream will want to fix it. The issue is how SDL2's cmake files are created, because they are using the correct way of finding the dependency.

Have you tried adding a patch that reverts the commit I linked?

**Comment by rc-05** [comment]
Sorry to say this but I am not using Void Linux anymore: it's not a problem if someone wants to maintain milkytracker in my place.

**Pull request closed without merging**
