### PR TITLE
php: update to 7.4.27

### PR DESCRIPTION
**Pull request by uhohspaghetios**
- I tested the changes in this PR: YES
- I built this PR locally for my native architecture, (amd64-glibc)

### CODE REVIEW

**Comment by paper42** [comment]
could you also fix these warnings with this update?
```
2021-12-10T05:25:01.5532389Z configure: WARNING: unrecognized options: --with-freetype-dir, --with-icu-dir, --with-jpeg-dir, --with-libzip, --with-pcre-regex, --with-png-dir
...

2021-12-10T05:25:27.3139125Z Configuring PEAR
2021-12-10T05:25:27.3141391Z checking whether to install PEAR... yes
2021-12-10T05:25:27.3144285Z configure: WARNING: The --with-pear option is deprecated
```

**Comment by uhohspaghetios** [comment]
> could you also fix these warnings with this update?
> 
> ```
> 2021-12-10T05:25:01.5532389Z configure: WARNING: unrecognized options: --with-freetype-dir, --with-icu-dir, --with-jpeg-dir, --with-libzip, --with-pcre-regex, --with-png-dir
> ...
> 
> 2021-12-10T05:25:27.3139125Z Configuring PEAR
> 2021-12-10T05:25:27.3141391Z checking whether to install PEAR... yes
> 2021-12-10T05:25:27.3144285Z configure: WARNING: The --with-pear option is deprecated
> ```

Fixed the unknown flags warning.  The --with-pear option is needed if you still want PEAR as PEAR/PECL is not enabled by default.  I imagine PEAR is still being used by more than a handful of PHP users.  Perhaps rolling out PHP8, PEAR support should be removed from Void?  FYI, PHP does not have an official replacement for PEAR/PECL.

https://www.php.net/manual/en/migration74.other-changes.php

**Comment by paper42** [comment]
Could you update to .27?

**Comment by paper42** [comment]
and squash the commits, we only want one in this PR

**Comment by uhohspaghetios** [comment]
> and squash the commits, we only want one in this PR

I honestly have no idea how to do that without ruining things despite a bunch of reading on the subject just now.

**Comment by paper42** [comment]
ping @uhohspaghetios

**Pull request closed without merging**
