### PR TITLE
Mediainfo

### PR DESCRIPTION
**Pull request by gspe**
This fix a thread safety problem present in  `libzen`
https://github.com/sbraz/pymediainfo/issues/105
https://github.com/MediaArea/ZenLib/commit/70868fe21d8c58373389dd318a76695136580a4b

### CODE REVIEW

**Comment by q66** [comment]
remove the revbumps

**Comment by ericonr** [comment]
Their fix doesn't work...

```
~ ➜ xbps-query -o /usr/lib/libzen.so.0
libzen-0.4.38_1: /usr/lib/libzen.so.0 -> /usr/lib/libzen.so.0.0.0 (link)
~ ➜ nm -D /usr/lib/libzen.so.0 | grep gmtime
                 U gmtime
```

The library is still using `gmtime`, not `gmtime_r`.

**Comment by ericonr** [comment]
They should have `#define _POSIX_C_SOURCE` at the top of the file and before any `#include`, so `gmtime_r` would be exposed. Keeping their `#ifdef` forest would still work, I guess, but isn't really necessary.

**Comment by ericonr** [comment]
Ok, this probably worked for you on glibc. Since this is C++, what happens (on Linux) is that `_GNU_SOURCE` is defined. On glibc, this means a bunch of other macros (including some which that ifdef forest tests for) are defined. On musl, `_GNU_SOURCE` being defined just stays that way, so none of the macros expected by the ifdefs are there, and it ends up using `gmtime`. The patch suggestion above should fix it.

**Comment by ericonr** [comment]
Ping

**Comment by JeromeMartinez** [comment]
> They should have #define _POSIX_C_SOURCE at the top of the file and before any #include

IIUC doing that will make `gmtime_r` available in your case but will at the same time create issues on platforms not having `gmtime_r`, something we are actually trying to avoid.
We would like to have a method which is fine for you but at the same time fine for platforms not having `gmtime_r` (and also as multithread is not always used, if we can avoid a mutex... I am aware that it is a lot of conditions).

Checking autoconf, looks like there is a posibility to do:
AC_CHECK_FUNCS([gmtime_r])
in configure.ac
then adding `#ifdef HAVE_GMTIME_R >=1` in the test should work.
If you are able to test it, I am fine for adding it in the upstream source code.

**Comment by ericonr** [comment]
> We would like to have a method which is fine for you but at the same time fine for platforms not having gmtime_r (and also as multithread is not always used, if we can avoid a mutex... I am aware that it is a lot of conditions).

It would be pretty complicated (and error prone) to build one version of the library for the MT or not case, so always using `gmtime_r` is the least bad alternative. It also shouldn't use a mutex, since the second argument allows it to simply not use any globals.

> IIUC doing that will make gmtime_r available in your case but will at the same time create issues on platforms not having gmtime_r, something we are actually trying to avoid.

Do you know of any platforms that don't have it, besides Windows? (For which you already have an ifdef block).

**Comment by ericonr** [comment]
Anyway, https://github.com/MediaArea/ZenLib/pull/126

**Pull request closed without merging**
