### PR TITLE
New package: clapboard-0.1.1

### PR DESCRIPTION
**Pull request by lz-coder**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-GLIBC)

### CODE REVIEW

**Comment by icp1994** [comment]
License is MIT and using /archive/refs/tags/ is recommended for distfiles

**Comment by lz-coder** [comment]
> License is MIT and using /archive/refs/tags/ is recommended for distfiles

Done

**Comment by icp1994** [comment]
If you overwrite do_install() from the cargo build style, the actual binary won't be in the package if you don't put it in the destdir manually. So your package currently contains only the LICENSE file. You can check this with [xls from xtools](https://man.voidlinux.org/xtools). So you need post_install() instead of do_install().

**Comment by lz-coder** [comment]
> 



> If you overwrite do_install() from the cargo build style, the actual binary won't be in the package if you don't put it in the destdir manually. So your package currently contains only the LICENSE file. You can check this with [xls from xtools](https://man.voidlinux.org/xtools). So you need post_install() instead of do_install().

**Comment by lz-coder** [comment]
> > 
> 
> > If you overwrite do_install() from the cargo build style, the actual binary won't be in the package if you don't put it in the destdir manually. So your package currently contains only the LICENSE file. You can check this with [xls from xtools](https://man.voidlinux.org/xtools). So you need post_install() instead of do_install().

Thanks for the tip, I didn't know xls

**Pull request closed without merging**
