### PR TITLE
libgit2: update to 1.7.2

### PR DESCRIPTION
**Pull request by tranzystorekk**
[ci skip]

#### Testing the changes
- I tested the changes in this PR: **briefly**

Todos:

- [x] cargo-edit
- [x] cargo-outdated

Related pending PRs:

- #45829 
- #45972
- #45853 Ping @cinerea0 
- #46043

### CODE REVIEW

**Comment by icp1994** [comment]
What are the blockers here? Is it still `cargo-edit` & `cargo-outdated`?

**Comment by tranzystorekk** [comment]
> What are the blockers here? Is it still `cargo-edit` & `cargo-outdated`?

Yeah, those two are real PITAs with the way they grab the whole `cargo`/`crates` crates as deps, those can't be easily patched up and I haven't had much time to sit down and think up a workaround.

**Comment by leahneukirchen** [comment]
And these things break when we update the cargo inside them too?

**Comment by tranzystorekk** [comment]
I'd have to revisit the whole topic, but in a glance:

- `cargo-edit`: uses git2 as both a regular dependency and a transitive dependency of `cargo-test-support` (pinned to a git commit) and `crates-index` (versioned, but in the package at 0.19 while there have been giant leaps to 1.x and 2.x that most probably cannot be easily bumped to)
- `cargo-outdated`: v0.14 uses git2 as a transitive dependency of `git2-curl` and `cargo`, both versioned so it should be easier, but I'm not sure how compatible `cargo` is between its versions

**Comment by leahneukirchen** [comment]
Alternatively, one could let those two packages use the vendored version instead of holding everything back...

**Comment by leahneukirchen** [comment]
FTR, Arch seems to build those packages without issues with libgit 1.7.

**Comment by tranzystorekk** [comment]
> FTR, Arch seems to build those packages without issues with libgit 1.7.

I did a quick check and apparently these packages depend on libgit2 in name only, ldd shows they're not dynlinked to it

**Pull request merged**
