### PR TITLE
gstreamer1: update to 1.18.4

### PR DESCRIPTION
**Pull request by kawaiiamber**
Update `gstreamer1` and plugins to 1.18.4

### CODE REVIEW

**Comment by ericonr** [comment]
This should be one commit per affected package.

**Comment by kawaiiamber** [comment]
> This should be one commit per affected package.

Okay, `git reset HEAD~` and added each package to their seperate tracking index - each package affected has their own commit. While we're here - I was wondering if it would be possible to change `gstreamer1` to just `gstreamer`? Upstream is just `gstreamer`, idk y one wants the 1 at the end - only resulting in having to get rid of it - e.g. `${pkgname/1/}`

**Comment by travankor** [comment]
>(this does not fix this from my testing)

Can you remove the fixes to not autoclose the issue?

**Comment by kawaiiamber** [comment]
> > (this does not fix this from my testing)
> 
> Can you remove the fixes to not autoclose the issue?

oops - ya, removed

**Comment by ericonr** [comment]
This is missing `gstreamer-vaapi`, `gst1-editing-services` and `gst1-python3`, I believe.

**Comment by kawaiiamber** [comment]
> This is missing `gstreamer-vaapi`, `gst1-editing-services` and `gst1-python3`, I believe.

Okay, I added those three.

**Comment by kawaiiamber** [comment]
I'm still wondering if it's possible (either on this PR or future one) to change `gstreamer1` stuff to just `gstreamer` stuff - this would allow for a big cleanup in `shlibs` in `common`, as well, I believe. That way, you don't need a bunch of `<gstreamer-stuff>.so <gstreamer1-stuff>` lines.

**Comment by ericonr** [comment]
> change gstreamer1 stuff to just gstreamer stuff - this would allow for a big cleanup in shlibs in common, as well, I believe. That way, you don't need a bunch of <gstreamer-stuff>.so <gstreamer1-stuff> lines.

You still need the item in the list; it isn't calculated automatically by package name.

**Comment by kawaiiamber** [comment]
Ah ok. Can the PR still be open for the update? Why did it close?

**Comment by ericonr** [comment]
I had to merge locally, GH UI is bugged. You can find the commits in master.

**Pull request closed without merging**
