### PR TITLE
gcc: update to 8.2.0

### PR DESCRIPTION
**Pull request by pullmoll**
It seems that most packages build ok with the update, no major fallout so far.
The failing packages will probably be fixed with coming updates (efl is one example).

I'm not sure if it is better to merge the cross compilers and isl15 update first, then gcc and the rest, or vice versa, or if it is okay to merge the whole bunch at once. Perhaps disable the cross builders until x86_64 is and x86_64-musl is done?

### CODE REVIEW

**Comment by travankor** [comment]
some hardening options to consider:

`--enable-cet=auto` : for Intel (shadow stack and indirect-branch tracking)
`--enable-secureplt`: for PowerPC
`--enable-vtable-verify`: C++ hardening, not sure if this breaks things (the docs say no ABI change so hopefully not)

**Comment by pullmoll** [comment]
@travankor IMO we should first test and then add hardening in a later update. I built several thousand pkgs w/o these options and enabling them just before merging may have unexpected side effects. @void-linux/pkg-committers ?

**Comment by chneukirchen** [comment]
ack, these are only relevant for a small subset of supported machines anyway.

**Comment by maxice8** [comment]
On Sat, Aug 11, 2018 at 07:46:46AM -0700, Jürgen Buchmüller wrote:
> @travankor IMO we should first test and then add hardening in a later update. I built several thousand pkgs w/o these options and enabling them just before merging may have unexpected side effects. @void-linux/pkg-committers ?
>  
> 
> -- 
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/1650#issuecomment-412279723

ack, will remove the additions

**Comment by travankor** [comment]
Agreed, you guys are doing the heavy lifting in this area ;)

Perhaps, some of these can be tentatively added in the next round of compiler updates?

**Comment by Gottox** [comment]
@pullmoll thanks for you awesome work.

If you're sure about compile failure feel free for do the isl update at once.

**Comment by pullmoll** [comment]
@Gottox I think it's not relevant if the cross builders are built with gcc 7.2.0 or 8.2.0, while we could avoid to have the cross builders build gcc-8.2.0 for the host on their own, if the x86_64 and x86_64-musl builders finished gcc-8.2.0 first. That is: merge as is, but disable the cross builders for a couple of hours.

**Comment by pullmoll** [comment]
@chneukirchen please build cross-aarch64-linux-{gnu,musl} for the host on the aarch64 builds, ty :)

**Comment by pullmoll** [comment]
Argh.. staging because of cross-arm-none-eabi being broken. I think I'll revert that one to 7.3.0 for now.

**Comment by maxice8** [comment]
> Argh.. staging because of cross-arm-none-eabi being broken. I think I'll revert that one to 7.3.0 for now.

also need to clean gcc-gcj from repos

**Comment by pullmoll** [comment]
I added a isl16 for solving the old dependency. It of course didn't happen here because I started from scratch. Anyway, things should settle soon.

**Comment by pullmoll** [comment]
Packages which depend on libgfortran.so.4 and need a rebvump after gcc-8.2.0 is built:
- [ ] arpack-ng-3.6.2_1
- [ ] blas-3.8.0_1
- [ ] hdf5-1.10.1_2
- [ ] julia-0.6.4_3
- [ ] lapack-3.8.0_1
- [ ] libgiac-1.4.9r59_1
- [ ] libmitlm-0.4.2_2
- [ ] med-3.3.1_2
- [ ] octave-4.4.0_2
- [ ] openblas-0.2.20_2
- [ ] python-scipy-1.1.0_1

**Comment by pullmoll** [comment]
currently hexchat is blocking / staging the builds on cross builders. See #1784

**Comment by freshprince** [comment]
kernels should be rebuilt with new gcc to fix dkms.

**Comment by pullmoll** [comment]
Oh well, yes @freshprince ... another day or two of busy builders ;-P

**Pull request closed without merging**
