### PR TITLE
linux4.17: update to 4.17.8.

### PR DESCRIPTION
**Pull request by zdykstra**
[ci skip]

### CODE REVIEW

**Comment by zdykstra** [comment]
Ahh, damn it. [ci skip] has to be in the commit message not the PR. I'd kill the build if I could.

**Comment by cr6git** [comment]
4.17.9 is out

**Comment by zdykstra** [comment]
Bumped to 4.17.9

**Comment by cr6git** [comment]
Closing  PR was wrong.
You should have updated it, by using `git commit --amend` and `git push -f`

**Pull request closed without merging**
