### PR TITLE
higan: add a new implementation of libco for ppc64 ELFv2

### PR DESCRIPTION
**Pull request by q66**
Void uses ELFv2, and thanks to this we no longer need to fall back to the slow sjlj portable implementation.

The patch has been upstreamed: https://github.com/byuu/higan/pull/9

### CODE REVIEW

**Comment by pullmoll** [comment]
Since upstream already merged the patch perhaps let's just wait for the next release?

**Comment by q66** [comment]
Last stable release was 2017, it is unknown when a newer release will be made.

**Comment by pullmoll** [comment]
Ok. We can then use the latest git commit d70522f… (v106.185) and just revbump the package.

**Comment by q66** [comment]
I'd suggest we stick with what we have for now, because the git version completely revamped the user interface, and it's a tad strange to use now...

**Comment by pullmoll** [comment]
Okay then. Testing the build here.

**Pull request merged**
