### PR TITLE
common/profiles: introduce XBPS_{,TARGET_}WORDSIZE

### PR DESCRIPTION
**Pull request by pullmoll**
The host and target word size can be used to determine whether cross compiling certain packages is possible.
One example is qt5 webengine which can be built for e.g. armv7l iff the host environment is 32 bit also.

N.B. for armv6l* cross compiling fails anyway because of missing neon support for some part of webengine.

### CODE REVIEW

**Comment by Anachron** [comment]
`export XBPS_TARGET_WORDSIZE="$XBPS_TARGET_WORDSIZE"` is this correct? Imo it should either be `export XBPS_TARGET_WORDSIZE` or the declaration to a new value.

**Comment by pullmoll** [comment]
I copy-pasted the style of the `export XBPS_TARGET_QEMU_MACHINE` line.
I believe that in both cases the assignment is redundant.

**Comment by pullmoll** [comment]
Updated `Manual.md` as well. If noone objects I'm going to merge this.

**Comment by xtraeme** [comment]
+1

**Pull request merged**
