### PR TITLE
godot: update to 3.5

### PR DESCRIPTION
**Pull request by Relected**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by abenson** [comment]
Please don't open and close commits, it makes it harder to track PRs; just squash the commits and force push.

**Comment by Relected** [comment]
@abenson I'm very sorry I didnt know that this feature exists, I will try to not do that next time

**Comment by Relected** [comment]
@classabbyamp also do you have alsa-pipewire installed by any chance? some people are saying that there is no error upon launch, some do, and i dont know which one is right.

**Comment by classabbyamp** [comment]
I have alsa-pipewire-0.3.54_2 installed

**Comment by Relected** [comment]
i dont know what just happend

**Comment by Relected** [comment]
@codingHahn would you like to help update the engine? since you were the previous maintainer

**Comment by Relected** [comment]
@classabbyamp this new update should fix the audio issue some people are talking about

**Pull request merged**
