### PR TITLE
Update Waybar to 0.11.0

### PR DESCRIPTION
**Pull request by trolljoe**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86-64-glibc)

### CODE REVIEW

**Comment by ericonr** [comment]
Please fix the commit message :)

**Comment by trolljoe** [comment]
sorry about that, fixed

**Comment by ericonr** [comment]
@trolljoe you need to rebase your PR to remove the merge commit and have a single commit updating the package.

**Comment by ericonr** [comment]
Closed in favor of #52621

**Pull request closed without merging**
