### PR TITLE
starship: update to 0.50.0

### PR DESCRIPTION
**Pull request by FollieHiyuki**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by FollieHiyuki** [comment]
Tests failed, but it is working fine on my end for a few hours.
@olafmersmann might be interested in this, since he knows more than I do.

**Comment by olafmersmann** [comment]
> Tests failed, but it is working fine on my end for a few hours.
> @olafmersmann might be interested in this, since he knows more than I do.

I've been running it for the last couple of hours without any problems and the test failures are expected at the moment.

**Comment by FollieHiyuki** [comment]
New version just came out

**Comment by FollieHiyuki** [comment]
Same cross build failure as #28341 with crate libgit2-sys

**Comment by ericonr** [comment]
@FollieHiyuki we are having a similar issue with #28380 , but with a different library

Tagging @jnbr and maybe @q66, if they have any idea what could be going wrong with our cargo and/or other things.

**Pull request closed without merging**
