### PR TITLE
nodejs: update to 13.2.0.

### PR DESCRIPTION
**Pull request by k4leg**
[ci skip]

### CODE REVIEW

**Comment by k4leg** [comment]
I don’t know why "[ci skip]" did not work.
I can’t check on other platforms, since my PC is not very powerful and it takes about ~4 hours on my PC. Also, I will soon send a request to update nodejs-lts. If you also do not have the opportunity to verify this, I can probably do it within a few days.
- Compiled successfully on x86_64.

**Comment by Johnnynator** [comment]
`[ci skip]` needs to be added to the commit message, not the PR post.

**Comment by k4leg** [comment]
@Johnnynator thank!

**Comment by k4leg** [comment]
Also added a new package: `nodejs-devel`. Perhaps this package will be needed to update _Atom_, which I'm currently trying to update.

**Comment by k4leg** [comment]
Deleted files from `usr/include/node/openssl`. Conflicts added.

**Pull request merged**
