### PR TITLE
xbps, xbps-static: update to 0.57.1

### PR DESCRIPTION
**Pull request by q66**

### CODE REVIEW

**Comment by xtraeme** [comment]
I would prefer to wait until 0.48

**Comment by q66** [comment]
Well, @Duncaen said it should be safe and there is also a patch that is accidentally not being applied rn (missing from series)

**Comment by xtraeme** [comment]
The issue with xbps-src skipping first dep due to xbps upgrade still exists... but ok.

**Comment by q66** [comment]
That will happen even if we bump xbps revision, which we should either way to get the alternatives patch applied

**Comment by xtraeme** [comment]
can't find commit 56ae190.patch in the xbps repo...

**Comment by xtraeme** [comment]
@q66 I pushed this to the xbps repo, now it's a proper commit. Please sync

**Comment by q66** [comment]
Okay, I'm not at home today so I'll do it in the evening

**Comment by q66** [comment]
Why didn't you fix the -Werror related failure while at it?

**Comment by xtraeme** [comment]
how did you find the issue? (CFLAGS, arch, etc)

**Comment by q66** [comment]
gcc  9.2:

```
main.c:195:8: error: ignoring return value of 'fread', declared with attribute warn_unused_result [-Werror=unused-result]
```

Arch etc. should not matter

**Comment by q66** [comment]
Also fix-missing-sh.patch should also get applied

**Comment by xtraeme** [comment]
I can't reproduce it...

**Comment by xtraeme** [comment]
i'm on x86_64/musl. maybe glibc related?

**Comment by q66** [comment]
Surely, musl probably does not declare fread with warn_unused_result

**Comment by xtraeme** [comment]
ok, I can now set a good commit msg.

**Comment by xtraeme** [comment]
ok, pushed to master

**Comment by q66** [comment]
We're down to 1 patch not in the repo then...

**Comment by xtraeme** [comment]
looking into it

**Comment by xtraeme** [comment]
Pushed, see https://github.com/void-linux/xbps/commit/bc59d0b407e644c0d75e5fa7fead4393e904f51e

**Comment by q66** [comment]
Alright, maybe we could spin a 0.58.1 or something to get rid of the patches?

**Comment by xtraeme** [comment]
0.57.1 ? heh

**Comment by xtraeme** [comment]
Did that. Now to update NEWS

**Comment by xtraeme** [comment]
I've tagged 0.57.1 just now

**Comment by q66** [comment]
Yeah, probably better that way, considering the only changes since 0.57 itself were fixes

**Comment by q66** [comment]
currently doing a massive rebuild (all the kde5 stuff etc... :/), once that's done i'll get back to this and bump it to 0.57.1

**Comment by q66** [comment]
Updated to 0.57.1, tested and working

**Pull request merged**
