### PR TITLE
thunderbird: update to 78.11.0

### PR DESCRIPTION
**Pull request by dkwo**
- thunderbird: update to 78.11.0
- thunderbird-i18n: update to 78.11.0

builds fine on x86_64

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
I think there's a high chance we'll get a new release in a few days, so it might make sense to hold off the update... Not sure.

**Comment by dkwo** [comment]
I'm fine either way.

**Comment by dkwo** [comment]
Btw, I do not yet see any updates.

**Comment by ericonr** [comment]
Right the one time I decide to purposefully delay, they don't make releases :p

**Comment by dkwo** [comment]
This is finally outdated :)

**Comment by ericonr** [comment]
@dkwo are you going to open another PR? Otherwise I can get started on doing the update here.

**Comment by dkwo** [comment]
@ericonr I wasn't planning to, so you can do it here if you want.

**Pull request closed without merging**
