### PR TITLE
vanitygen: update to 0.22.

### PR DESCRIPTION
**Pull request by Chocimier**

### CODE REVIEW

**Comment by maxice8** [comment]
needs https://github.com/samr7/vanitygen/issues/104

**Comment by maxice8** [comment]
please rebase your changes on top of master

**Comment by Chocimier** [comment]
rebased

**Comment by Hoshpak** [comment]
Do we really need to wait for a dead upstream project to tag before merging? I understand the reason for not packaging random git revisions but in this case the commit has been declared by upstream as an release (although not by adding a tag) and we have a tarball which can be cached. I would be inclined to just merge as is.

Btw, does AGPL really need vlicense?

**Comment by maxice8** [comment]
xlint says AGPL needs to be vlicensed, never found a rationale though

On Jan 17, 2019 17:49, "Helmut Pozimski" <notifications@github.com> wrote:

Do we really need to wait for a dead upstream project to tag before
merging? I understand the reason for not packaging random git revisions but
in this case the commit has been declared by upstream as an release
(although not by adding a tag) and we have a tarball which can be cached. I
would be inclined to just merge as is.

Btw, does AGPL really need vlicense?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/void-linux/void-packages/pull/5690#issuecomment-455308215>,
or mute the thread

**Comment by ARTEMKA-STOM** [comment]
5md--sha

**Pull request merged**
