### PR TITLE
qtractor: update to 0.9.21.

### PR DESCRIPTION
**Pull request by Clyybber**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by sgn** [comment]
```diff
diff --git a/srcpkgs/qtractor/template b/srcpkgs/qtractor/template
index 9c868ea8b0..fa64e6de8a 100644
--- a/srcpkgs/qtractor/template
+++ b/srcpkgs/qtractor/template
@@ -4,8 +4,9 @@ version=0.9.20
 revision=1
 wrksrc="qtractor-qtractor_${version//./_}"
 build_style=gnu-configure
-configure_args="--enable-debug"
-hostmakedepends="automake pkg-config"
+build_helper=qmake
+configure_args="--enable-debug ac_qmake=${XBPS_WRAPPERDIR}/qmake"
+hostmakedepends="automake pkg-config qt5-qmake qt5-host-tools"
 makedepends="dssi-devel jack-devel ladspa-sdk liblo-devel libmad-devel
  libsamplerate-devel lilv-devel qt5-tools-devel qt5-x11extras-devel
  rubberband-devel sratom-devel suil-devel vamp-plugin-sdk-devel"
@@ -18,9 +19,6 @@ changelog="https://raw.githubusercontent.com/rncbc/qtractor/master/ChangeLog"
 distfiles="https://github.com/rncbc/qtractor/archive/qtractor_${version//./_}.tar.gz"
 checksum=6b317e1b24ce99f354fc083aa0055228c6a9bd90c5a3d8abcb280af5014fd5c3
 
-# configure fails to find qt5 headers
-nocross="https://build.voidlinux.org/builders/armv7l-musl_builder/builds/3458/steps/shell_3/logs/stdio"
-
 pre_configure() {
 	autoreconf -if
 }
```

**Comment by sgn** [comment]
```diff
diff --git a/srcpkgs/qtractor/template b/srcpkgs/qtractor/template
index 9c868ea8b0..5a76db16ca 100644
--- a/srcpkgs/qtractor/template
+++ b/srcpkgs/qtractor/template
@@ -4,8 +4,10 @@ version=0.9.20
 revision=1
 wrksrc="qtractor-qtractor_${version//./_}"
 build_style=gnu-configure
-configure_args="--enable-debug"
-hostmakedepends="automake pkg-config"
+build_helper=qmake
+configure_args="--enable-debug ac_cv_qmake=${XBPS_WRAPPERDIR}/qmake
+ ac_cv_libsuil_gtk2_in_qt5=yes ac_cv_libsuil_x11_in_qt5=yes"
+hostmakedepends="automake pkg-config qt5-qmake qt5-host-tools"
 makedepends="dssi-devel jack-devel ladspa-sdk liblo-devel libmad-devel
  libsamplerate-devel lilv-devel qt5-tools-devel qt5-x11extras-devel
  rubberband-devel sratom-devel suil-devel vamp-plugin-sdk-devel"
@@ -18,9 +20,6 @@ changelog="https://raw.githubusercontent.com/rncbc/qtractor/master/ChangeLog"
 distfiles="https://github.com/rncbc/qtractor/archive/qtractor_${version//./_}.tar.gz"
 checksum=6b317e1b24ce99f354fc083aa0055228c6a9bd90c5a3d8abcb280af5014fd5c3
 
-# configure fails to find qt5 headers
-nocross="https://build.voidlinux.org/builders/armv7l-musl_builder/builds/3458/steps/shell_3/logs/stdio"
-
 pre_configure() {
 	autoreconf -if
 }
```

**Comment by ericonr** [comment]
@Clyybber ping

**Comment by ericonr** [comment]
Had to rebase locally, thanks!

**Pull request closed without merging**
