### PR TITLE
[WIP] linux5.11: try to build scripts/ for cross targets.

### PR DESCRIPTION
**Pull request by ericonr**
Since we are here, clean up unused args and add a few comments.

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

[ci skip]

Relevant for DKMS modules on cross archs, like aarch64.

### CODE REVIEW

**Comment by ericonr** [comment]
I can't make it not rebuild `fixdep` using the new `HOSTCC`. One plan was to build it for host first, build the others programs and finally rebuild it for the target.

See `make -d` output:

```
Updating goal targets....
Considering target file '__build'.
 File '__build' does not exist.
  Considering target file 'scripts/basic/fixdep'.
    Considering target file 'scripts/basic/fixdep.c'.
     Looking for an implicit rule for 'scripts/basic/fixdep.c'.
     Trying pattern rule with stem 'fixdep.c'.
     Trying implicit prerequisite 'scripts/basic/fixdep.c_shipped'.
     Trying pattern rule with stem 'fixdep.c'.
     Trying implicit prerequisite 'scripts/basic/fixdep.c_shipped'.
     Looking for a rule with intermediate file 'scripts/basic/fixdep.c_shipped'.
      Avoiding implicit rule recursion.
     No implicit rule found for 'scripts/basic/fixdep.c'.
     Finished prerequisites of target file 'scripts/basic/fixdep.c'.
    No need to remake target 'scripts/basic/fixdep.c'.
    Considering target file 'FORCE'.
     File 'FORCE' does not exist.
     Finished prerequisites of target file 'FORCE'.
    Must remake target 'FORCE'.
    Successfully remade target file 'FORCE'.
   Considering target file 'FORCE'.
   File 'FORCE' was considered already.
   Finished prerequisites of target file 'scripts/basic/fixdep'.
   Prerequisite 'scripts/basic/fixdep.c' is older than target 'scripts/basic/fixdep'.
   Prerequisite 'FORCE' of target 'scripts/basic/fixdep' does not exist.
  Must remake target 'scripts/basic/fixdep'.
Putting child 0x55fc06c6f1c0 (scripts/basic/fixdep) PID 9052 on the chain.
Live child 0x55fc06c6f1c0 (scripts/basic/fixdep) PID 9052
  HOSTCC  scripts/basic/fixdep
/bin/sh: line 1: scripts/basic/fixdep: cannot execute binary file: Exec format error
```

I have no idea how to bypass this `FORCE` thing.

**Comment by ericonr** [comment]
And then they delete `fixdep`: `make[1]: *** Deleting file 'scripts/basic/fixdep'` :(

**Comment by sgn** [comment]
Debian has a set of Makefile to build those tools.
My bigger concern is the tools usage:
- Is it for using natively on cross-target?
- Is it usable for cross-compiling an OOT module (let's say with -mklive)?

**Comment by ericonr** [comment]
Will be fixed for 5.12 using leah's patch for 5.10. Should be imported into rpi-kernels once those are updated.

**Pull request closed without merging**
