### PR TITLE
New package: pdfarranger-1.8.2

### PR DESCRIPTION
**Pull request by hervyqa**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)

### CODE REVIEW

**Comment by Duncaen** [comment]
Don't open new PRs for the same package, you can just force push to the same branch, you are spamming notifications and the whole review history is lost.

**Comment by rivanfebrian123** [comment]
Why didn't some jobs pass the test? Is there any problem with CI/CD config or something?
```
=> pdfarranger-1.8.0_1: running do_check ...
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
creating pdfarranger.egg-info
writing pdfarranger.egg-info/PKG-INFO
writing dependency_links to pdfarranger.egg-info/dependency_links.txt
writing entry points to pdfarranger.egg-info/entry_points.txt
writing requirements to pdfarranger.egg-info/requires.txt
writing top-level names to pdfarranger.egg-info/top_level.txt
writing manifest file 'pdfarranger.egg-info/SOURCES.txt'
reading manifest file 'pdfarranger.egg-info/SOURCES.txt'
adding license file 'COPYING'
writing manifest file 'pdfarranger.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "/builddir/pdfarranger-1.8.0/pdfarranger/pdfarranger.py", line 455, in do_activate
    self.uiXML = self.__build_from_file(DOMAIN + '.ui')
  File "/builddir/pdfarranger-1.8.0/pdfarranger/pdfarranger.py", line 308, in __build_from_file
    b.add_from_file(f)
gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/usr/local/share/pdfarranger/pdfarranger.ui”: No such file or directory (4)
[Errno 2] No such file or directory: '/builddir/pdfarranger-1.8.0/test'
Error: The operation was canceled.
```

**Comment by hervyqa** [comment]
> Don't open new PRs for the same package, you can just force push to the same branch, you are spamming notifications and the whole review history is lost.

oh, sorry about that. my git branch signature is broken. failed to git checkout.

**Comment by rivanfebrian123** [comment]
@hervyqa Could you please just remove the tests? It's problematic on x86_64 platform (which is the most popular one), surprisingly.
```
post_extract() {
	rm pdfarranger/tests/test.py
}
```

**Comment by hervyqa** [comment]
@rivanfebrian123  Thanks. I tried by deleting `test.py` like `python3-Werkzeug` package.
https://github.com/void-linux/void-packages/blob/ac6deeea0b266f6b5318708ba42ee56f87144142/srcpkgs/python3-Werkzeug/template#L17-L22

be like this and it worked. 
```
do_check() {
	rm -f tests/test.py
}
```

**Pull request closed without merging**
