### PR TITLE
[RFC] Ayatana indicators

### PR DESCRIPTION
**Pull request by tibequadorian**
`libappindicator` hasn't seen a release since 2012 (almost 10 years!)
Debian has removed it in buster and switched to [libayatana-appindicator](https://ayatanaindicators.github.io/).
This PR is intended to prepare void linux for it. Let me know what you think...

I successfully built and tested all changed packages.

#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

### CODE REVIEW

**Comment by ericonr** [comment]
I think if we are doing this it'd make more sense to replace libappindicator entirely, maybe?

Do you think there are downsides?

**Comment by tibequadorian** [comment]
> I think if we are doing this it'd make more sense to replace libappindicator entirely, maybe?

That's right. Currently 5 packages use libappindicator, but some need to be patched to use libayatana-appindicator instead.

- droidcam: not supported, [issue](https://github.com/dev47apps/droidcam/issues/182)
- gromit-mpx: [supported](https://github.com/bk138/gromit-mpx/commit/2a838303154df4a90495c4f93741846cbd63d37f), but not released yet
- network-manager-applet: supported
- psensor: not supported
- remmina: [supported](https://gitlab.com/Remmina/Remmina/-/commit/a34133add92c217943acad64bb0e41de0f2f619c)

**Comment by tibequadorian** [comment]
I would replace the dependency in all packages that support it, and leave the other packages untouched. I don't want to create unnecessary overhead by adding patches. (except for gromit-mpx, where the patch will be obsolete in the next release anyway)

**Comment by tibequadorian** [comment]
Ok i've revised it now and removed libappindicator completely and patched the necessary packages, otherwise it doesn't make any sense. I'll leave the PR open if you eventually decide to merge :) I'm not sure myself if it's right thing to do because so many (ok actually four) patches needed :P but the debian folks probably have a point by saying that libappindicator upstream is a mess...

**Comment by ericonr** [comment]
Sorry for the lack of activity here :/

It would be nice if the patches were upstreamed :/

**Comment by ericonr** [comment]
(by debian)

**Comment by tibequadorian** [comment]
No problem. Yes I know so currently I don't want this PR to be merged. May reopen it if patches are upstreamed.

**Comment by paper42** [comment]
libappindicator is now preventing us from removing quite a big python2 dependency chain, would you be interested in continuing the work here or should I take it over?

**Comment by tibequadorian** [comment]
@paper42 still relevant?

**Comment by paper42** [comment]
> @paper42 still relevant?

yes

**Pull request closed without merging**
