### PR TITLE
Komikku: update to 0.39.0.

### PR DESCRIPTION
**Pull request by Nathan-MV**
#### Testing the changes
- I tested the changes in this PR: **YES**

Sorry for the spam, btw.

### CODE REVIEW

**Comment by classabbyamp** [comment]
please don't close/reopen PRs. you may want to make your changes locally instead of using using github web (this also makes it possible to test your changes)

**Comment by Nathan-MV** [comment]
> please don't close/reopen PRs. you may want to make your changes locally instead of using using github web (this also makes it possible to test your changes)

I tested the changes in a cloned fork, but i have not configured my github-cli to push my changes, so i edited it thought github web, the thing that i don`t know now is why xlint is failing here?

**Comment by classabbyamp** [comment]
take a look at [the log](https://github.com/void-linux/void-packages/runs/7485935637?check_suite_focus=true#step:7:9)

**Comment by hervyqa** [comment]
change your commit message according to the guidelines. make one commit.

**Pull request closed without merging**
