### PR TITLE
discount: update to 3.0.0d

### PR DESCRIPTION
**Pull request by MIvanchev**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (X86_64-GLIBC)

### CODE REVIEW

**Comment by MIvanchev** [comment]
CC @leahneukirchen: I added make install.everything to make sure `makepage` is also available.

**Comment by leahneukirchen** [comment]
You also need to revbump all reverse dependencies:

```
% xbps-query -R --regex -p shlib-requires -s libmarkdown
Minder-1.14.0_2: libmarkdown.so.2 (https://repo-default.voidlinux.org/current)
cutemarked-0.11.3_8: libmarkdown.so.2 (https://repo-default.voidlinux.org/current)
kdepim-addons-24.08.0_1: libmarkdown.so.2 (https://repo-default.voidlinux.org/current)
libpurple-mattermost-1.2_1: libmarkdown.so.2 (https://repo-default.voidlinux.org/current)
notes-up-2.0.6_2: libmarkdown.so.2 (https://repo-default.voidlinux.org/current)
okular-24.08.1_1: libmarkdown.so.2 (https://repo-default.voidlinux.org/current)
pdfpc-4.6.0_2: libmarkdown.so.2 (https://repo-default.voidlinux.org/current)
```

**Comment by leahneukirchen** [comment]
cutemarked is broken.

**Comment by MIvanchev** [comment]
@leahneukirchen cutemarked is broken without a big chance of recovery, seems to be incompatible with the newest changes. Please advise.

**Comment by MIvanchev** [comment]
@leahneukirchen Let me patch it.

**Comment by MIvanchev** [comment]
@leahneukirchen Do you have an idea about `libokular5-23.08.5_1: broken, unresolvable shlib `libmarkdown.so.2'` ?

**Comment by leahneukirchen** [comment]
That's an obsolete package we need to remove from the builders.

Else LGTM, I'll merge when this issue is resolved. Thanks!

**Pull request merged**
