### PR TITLE
poco: update to build with openssl3

### PR DESCRIPTION
**Pull request by dkwo**
- I tested the changes in this PR: no
- I built this PR locally for my native architecture, (x86_64-musl)

required to build with openssl3 #37681

### CODE REVIEW

**Comment by dkwo** [comment]
@juliendehos

**Comment by juliendehos** [comment]
I don't use void-linux anymore, sorry. Please, feel free to remove me from the maintainers of these packages.

**Comment by dkwo** [comment]
Not sure why it complains about SHA256 mismatch, as here it builds fine.

**Comment by Johnnynator** [comment]
You probably have a old version of the tarball cached locally (or did fetch it from sources.voidlinux.org).
The content of the tarball didn't change at all, only the compression changed. Can you update the checksum in the template to reflect the new file that github delivers.

```
1a6e5057dbb798d1d2259125651ee4425b58d69bea481e0f255bc30bc8c4df94  new.tar
1a6e5057dbb798d1d2259125651ee4425b58d69bea481e0f255bc30bc8c4df94  old.tar
d410fd8416f4e05b0bf6c0eeedac8dcfda1f1d960bed6cb69a9ddf8d4c04e803  new.tar.gz
1a6e5057dbb798d1d2259125651ee4425b58d69bea481e0f255bc30bc8c4df94  old.tar
87f14a611e3ae9f9babe2dff8e4a6c4f5495fa2883393edb36e796af3f19fb30  old.tar.gz
```

**Comment by dkwo** [comment]
@Johnnynator Thank you!

**Comment by Johnnynator** [comment]
https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/

🤔 seems like they also reverted it again

**Pull request merged**
