### PR TITLE
iwd: update to 1.9.

### PR DESCRIPTION
**Pull request by pbui**
Also update ell.

### CODE REVIEW

**Comment by ericonr** [comment]
Upstream recommends not setting `UseDefaultInterface` in the config, and instead configuring `udev` to not rename network interfaces. (our workaround in https://docs.voidlinux.org/config/network/iwd.html is _not_ the recommended solution).

They have a drop-in `.link` file for udev, but I haven't managed to get the time to test if it solves the issue for us, since the file goes in some systemd-y folders. And enabling it in the build isn't easy, because it checks for systemd in the system.

What do you think, should we try to follow upstream recommendation here?

**Comment by pbui** [comment]
As discussed on IRC, I think we should keep our current recommended workaround since we do not have systemd and thus cannot take advantage of the drop-in `.link` file.

**Comment by nathanblair** [comment]
This is broken for me with the `linux` mainline kernel (`5.8`) in the `musl` repos.

Starting it (via `/usr/libexec/iwd`) throws a complaint about not having the `CONFIG_CRYPTO_USER_API_SKCIPHER` option and a few others enabled in the kernel.

Does anyone know of a kernel that is supported?

**Comment by ericonr** [comment]
Try downgrading the package or using an older kernel. Alternatively, download the kernel package offline and transfer via USB.

**Comment by ahesford** [comment]
I use `iwd` with `linux5.8` and have no problems.

**Comment by sgn** [comment]
All 5.8 have `CONFIG_CRYPTO_USER_API_SKCIPHER=m`

**Pull request merged**
