### PR TITLE
dolphin-emu: update to 2409, refactor template

### PR DESCRIPTION
**Pull request by chrysos349**
@Hnaguski 

this app was last updated a year ago.

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86-64)

### CODE REVIEW

**Comment by Vinfall** [comment]
Just wanna say this works perfectly on my machine👍🏼

**Comment by Vinfall** [comment]
You probably need to rebase on master now that #51368 (i.e. https://github.com/void-linux/void-packages/pull/51368/commits/70a5b415d210f3104912160272b1f21df45f15e2) is merged.

**Comment by Hnaguski** [comment]
Looks good to me, thanks for updating

**Comment by zlice** [comment]
seems to work for me too

but why the patch whitespace v-v

**Comment by Vinfall** [comment]
Hmmm, [2409 released with RetroAchievements support](https://dolphin-emu.org/blog/2024/09/04/dolphin-progress-report-release-2407-2409/), yet 2407 update is still not merged :(

Tried to update but eventually gave up as the submodule commits are very confusing to me.

**Comment by classabbyamp** [comment]
rebase please

**Comment by chrysos349** [comment]
@classabbyamp done

**Pull request merged**
