### PR TITLE
musl: update to 1.1.24 + matching crosstoolchain updates

### PR DESCRIPTION
**Pull request by q66**
Updating the crosstoolchains as there have been header changes.

This also adds two backports from current musl git master, which fix some compatibility issues with glibc headers on powerpc(64) which should allow us to greatly reduce the musl-specific patches we have in the tree.

TODO/ongoing:

- [x] test crosstoolchain builds

### CODE REVIEW

**Comment by q66** [comment]
Tested building crosstoolchains. Everything seems to be alright

**Comment by mobinmob** [comment]
Should musl-bootstrap be updated? It is currently orphaned.

**Comment by q66** [comment]
I guess it should. It's likely been broken since the last update (patches dir symlinks to musl patches but version was already mismatched)

**Comment by q66** [comment]
Done.

**Comment by xtraeme** [comment]
Is this ready?

**Comment by q66** [comment]
yeah

**Comment by Johnnynator** [comment]
> yeah (well, as long as it works on x86_64, haven't tested on that)

At least I didn't run into anything so far.

**Comment by q66** [comment]
Yeah, wouldn't expect to. It's a fairly incremental release, and plenty of people are running it on x86_64 systems elsewhere.

**Pull request merged**
