### PR TITLE
python-guessit: update to 3.1.1.

### PR DESCRIPTION
**Pull request by cpixl**

### CODE REVIEW

**Comment by Chocimier** [comment]
Please add checkdepends. Now tests fail because they use more-itertools from pip in version that do not work in py2.

**Comment by cpixl** [comment]
I can't see the `more-itertools` dependency on this package, and I couldn't reproduce this error as this package doesn't contain any tests... are you sure you referred to the right PR @Chocimier ?

**Comment by Chocimier** [comment]
python-module provides do_check phase.

> => python-guessit-3.1.1_1: running do_check ...
running pytest
...
Searching for more-itertools>=4.0.0
Reading https://pypi.org/simple/more-itertools/
Downloading https://files.pythonhosted.org/packages/16/e8/b371710ad458e56b6c74b82352fdf1625e75c03511c66a75314f1084f057/more-itertools-8.3.0.tar.gz#sha256=558bb897a2232f5e4f8e2399089e35aecb746e1f9191b6584a151647e89267be
Best match: more-itertools 8.3.0
...
  File "/tmp/easy_install-3PHeUQ/more-itertools-8.3.0/more_itertools/__init__.py", line 1, in <module>
  File "/tmp/easy_install-3PHeUQ/more-itertools-8.3.0/more_itertools/more.py", line 482
    yield from iterable
             ^
SyntaxError: invalid syntax
=> ERROR: python-guessit-3.1.1_1: do_check: 'python${pyver} setup.py ${make_check_target:-test} ${make_check_args}' exited with 1


```

**Comment by cpixl** [comment]
I removed python-guessit as it was only a dependency of `python-subliminal` (now `subliminal` with only Python 3 support), so it should solve the test issues.

**Comment by Chocimier** [comment]
Merged with removed noarch, which is deprecated now.

**Pull request merged**
