### PR TITLE
rpi-base: don't install snd_bcm2835.conf module file, move udev rules to separate file

### PR DESCRIPTION
**Pull request by amak79**
- Don't install the `snd_bcm2835.conf` module file. The current template only installs this file for `armv6l` (rpi 1, zero). RPi audio should instead be enabled via the device tree parameter `dtparam=audio=on` in `/boot/config.txt`. RPi audio is disabled by default.
- Move udev rules from template to `files/71-raspberrypi.rules` file.
- Fix xlint warnings.
- Add `dtparam=audio=on` to `rpi-frmware/files/config.txt`

Built for armv6l, armv7l, aarch64.
Tested on armv6l, armv7l.

### CODE REVIEW

**Comment by ericonr** [comment]
@pbui @fosslinux does this look good to you?

**Comment by fosslinux** [comment]
I use my pis headless so can't test. But looks sound.

Something to the effect of `dtparam=audio=on` should be either added or added commeted out to `rpi-frmware/files/config.txt`.

**Comment by pbui** [comment]
LGTM.  Audio works on armv6l pi with `dtparam=audio=on` in `/boot/config.txt`

**Comment by amak79** [comment]
> Something to the effect of `dtparam=audio=on` should be either added or added commeted out to `rpi-frmware/files/config.txt`.

I will make this change. Should audio be on by default?

**Comment by fosslinux** [comment]
LGTM

**Comment by Johnnynator** [comment]
Please also increase the revision in `rpi-firmware/template`

**Comment by amak79** [comment]
> Please also increase the revision in `rpi-firmware/template`

Fixed. Also replaced `noarch` with `armv6l* armv7l* aarch64*` as xlint was complaining.

**Comment by amak79** [comment]
Are there any remaining issues with this PR?

**Comment by the-maldridge** [comment]
No remaining changes, please rebase and @ me for merge.

**Comment by amak79** [comment]
@the-maldridge Rebased.

**Pull request merged**
