### PR TITLE
.travis.yml: update masterdirs

### PR DESCRIPTION
**Pull request by the-maldridge**
Resolves void-linux/void-infrastructure#54.

Prerequisite of void-linux/void-packages#17969.

### CODE REVIEW

**Comment by xtraeme** [comment]
thanks. can this be applied right now?

**Comment by the-maldridge** [comment]
Should be safe, but generally its better to test it by rebasing something small on top of this and making sure travis still works.  I haven't got anything small at the moment to rebase.

**Comment by xtraeme** [comment]
I can test this with base-chroot-v2, let's see

**Comment by xtraeme** [comment]
hmm for some reason, the bsdtar-3.4.1_1 and xbps-0.57.1_7 packages are not in the alpha.us repo for i686.

https://travis-ci.org/void-linux/void-packages/jobs/632864516?utm_medium=notification&utm_source=github_status

**Comment by the-maldridge** [comment]
```
[maldridge@vm1-a-mci-us ~]$ stat /repo/current/bsdtar-3.4.1_1.i686.xbps
  File: /repo/current/bsdtar-3.4.1_1.i686.xbps
  Size: 422724    	Blocks: 832        IO Block: 4096   regular file
Device: fc04h/64516d	Inode: 43600311    Links: 1
Access: (0644/-rw-r--r--)  Uid: (  998/reposync)   Gid: (  998/reposync)
Access: 2020-01-04 03:49:15.144834208 -0600
Modify: 2020-01-04 03:39:44.285627328 -0600
Change: 2020-01-04 03:38:42.972911852 -0600
 Birth: -
[maldridge@vm1-a-mci-us ~]$ stat /repo/current/xbps-0.57.1_7.i686.xbps
  File: /repo/current/xbps-0.57.1_7.i686.xbps
  Size: 89776     	Blocks: 176        IO Block: 4096   regular file
Device: fc04h/64516d	Inode: 43600426    Links: 1
Access: (0644/-rw-r--r--)  Uid: (  998/reposync)   Gid: (  998/reposync)
Access: 2020-01-04 06:49:35.847906919 -0600
Modify: 2020-01-04 06:13:54.167068396 -0600
Change: 2020-01-04 06:14:51.221594810 -0600
 Birth: -
```

They're present on disk, and I would have assumed that after building they'd be indexed as long as xbps-rindex didn't explode.  The linked failure though looks like they didn't make it into the chroot filesystem.  This makes sense, as base-chroot doesn't depend on bsdtar so it wouldn't have been added to the container.

**Comment by xtraeme** [comment]
The issue is not that bsdtar is not available in the container, rather it's not available in the alpha.us i686 repo. It tries to build it and then fails because it's not in PATH.

**Comment by xtraeme** [comment]
Maybe we could check for both (bsdtar and tar) and use the first one available.

**Comment by the-maldridge** [comment]
Very circular indeed.  I can run a clean across i686 which will blind re-register everything if you want.

**Comment by xtraeme** [comment]
I think i686-repodata wasn't updated yet, isn't it?

**Comment by xtraeme** [comment]
Anyway, I think it's better to support both. Can be modified easily

**Comment by xtraeme** [comment]
With preference for bsdtar, because does not need external binaries, unlike GNU tar.

**Comment by the-maldridge** [comment]
OK.  I'll wait for you to modify and try that.  I don't think the repodata wouldn't have updated by now, the longest the sync can drift by without something being broken is 10 minutes.

**Comment by the-maldridge** [comment]
Something funny is going on here:

```
maldridge@theGibson:~$ curl https://xq-api.voidlinux.org/v1/query/i686?q=bsdtar|jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   310  100   310    0     0    443      0 --:--:-- --:--:-- --:--:--   442
{
  "data": [
    {
      "name": "bsdtar",
      "version": "3.4.0",
      "revision": 2,
      "filename_size": 421664,
      "repository": "current",
      "short_desc": "BSD utilities using libarchive"
    },
    {
      "name": "bsdtar-dbg",
      "version": "3.4.1",
      "revision": 1,
      "filename_size": 2333960,
      "repository": "debug",
      "short_desc": "BSD utilities using libarchive (debug files)"
    }
  ]
}
```

**Comment by xtraeme** [comment]
Works great after  https://github.com/void-linux/void-packages/pull/17969/commits/37470cfc1587478693d11890c935f4b544fb8a33

i686 build:
https://travis-ci.org/void-linux/void-packages/jobs/632869809?utm_medium=notification&utm_source=github_status

**Comment by the-maldridge** [comment]
sgtm, merge whenever you're ready.

**Comment by xtraeme** [comment]
But this xq-api seems to be using obsolete data, at least for i686... or did you fix this already?

**Comment by the-maldridge** [comment]
xq-api uses the repo indexes and is refreshed on a 5 minute interval.  It should have been updated quite a while ago, so I'm inclined to believe there is still an unrelated issue with the i686 repo having stale versions in it.

**Comment by xtraeme** [comment]
can't help here, but would be nice to find what's the issue

**Comment by the-maldridge** [comment]
I'm pretty sure that i686 has been staged since the 30th:

```
[void-repomaster@a-hel-fi ~]$ XBPS_ARCH=i686 xbps-rindex --add /hostdir/binpkgs/bsdtar-3.4.1_1.i686.xbps                                                                         
index: skipping `bsdtar-3.4.1_1' (i686), already registered.                                                          Inconsistent shlibs:                                       
  libprocps.so.7 (provided by: procps-ng; used by: CPU-X)
```

On the 30th commit d77455bfca52ad290b67dec0a6d5deda80a60919 made this package 64-bit only.  I'm not sure what the best course of action is here.  I suppose we could remove the package on i686, but that likely would break user installs.

**Comment by xtraeme** [comment]
please remove CPU-X on i686. This is it.

**Comment by xtraeme** [comment]
We need to be more careful when **removing** or **disabling** pkgs.

**Comment by the-maldridge** [comment]
I have removed the package, but I'm not familiar enough with xbps-rindex to get it to unstage.  Is there some magic invocation to get it to re-evaluate the stagedata?

**Comment by the-maldridge** [comment]
nvm, just realized that after removing a package I need to run an on-demand clean to drop it from the index.  Its late here...

**Comment by xtraeme** [comment]
just use `xbps-rindex -af *.{i686,noarch}.xbps` this should dtrt

**Comment by xtraeme** [comment]
9:05 AM here :-)

**Comment by xtraeme** [comment]
`xbps-rindex -c` is ok too :-)

**Comment by the-maldridge** [comment]
Its slowly chewing on the index now.

**Comment by xtraeme** [comment]
I hope the host tools in that machine are also up-to-date

**Comment by the-maldridge** [comment]
lolno.  As a root mirror this machine does not get updated enough.  In fact the update on it is currently broken due to incompatible shlibs.

```
[maldridge@a-hel-fi ~]$ sudo xbps-install -Su
libcrypto45-3.0.2_1 (update) breaks installed pkg `libressl-2.9.2_1'
libcrypto45-3.0.2_1 (update) breaks installed pkg `libtls19-2.9.2_1'
libssl47-3.0.2_1 (update) breaks installed pkg `libressl-2.9.2_1'
libssl47-3.0.2_1 (update) breaks installed pkg `libtls19-2.9.2_1'
Transaction aborted due to unresolved dependencies.
```

**Comment by the-maldridge** [comment]
Ok, had to add those explicitly to the transaction.  I would have thought xbps would do that when updating itself.

**Comment by xtraeme** [comment]
xbps-0.57.1_7 fixes exactly this issue while xbps needs to be updated.

**Comment by the-maldridge** [comment]
Ah.  The clean is now running again with an up to date host xbps.

**Comment by xtraeme** [comment]
The correct way to update your system with xbps (unattended) is (as of 0.57.1_7):

```
# xbps-install -Syu xbps
# xbps-install -yu
```

**Comment by the-maldridge** [comment]
Makes sense.  I'm up to date for xbps-only.  I'll try to make some time tomorrow to take the box offline and update the rest.  It needs to go down for a kernel and lvm update.

**Comment by xtraeme** [comment]
xbps update is enough, thanks

**Comment by the-maldridge** [comment]
```
[void-repomaster@a-hel-fi ~]$ XBPS_ARCH=i686 xbps-rindex -c /hostdir/binpkgs/
```

has been running for several minutes now.  Is that expected to take a long time?  I remember this being much faster a few years ago.

**Comment by xtraeme** [comment]
no idea what's going on... maybe try with -d ?

**Comment by the-maldridge** [comment]
Good point.  Trying with -d informed me I had a lockfile lying around I hadn't removed.  Doing that gets me to a missing props.plist:

```
[void-repomaster@a-hel-fi ~]$ XBPS_ARCH=i686 xbps-rindex -afv /hostdir/binpkgs/
index: failed to read props.plist metadata for `/hostdir/binpkgs/', skipping!
index: 0 packages registered.
```

**Comment by xtraeme** [comment]
`-a` (add) need at least one .xbps file

**Comment by xtraeme** [comment]
`xbps-rindex -afv /hostdir/binpkgs/*.{i686,noarch}.xbps`

**Comment by the-maldridge** [comment]
Point.

**Comment by the-maldridge** [comment]
Clear and unstaged.

**Comment by xtraeme** [comment]
Cool! are we sure the other archs are ok too? would be nice to see logs of them.

**Comment by the-maldridge** [comment]
Nothing else currently has a stagedata file:

```
[void-repomaster@a-hel-fi ~]$ ls /hostdir/binpkgs/*stagedata*
ls: cannot access '/hostdir/binpkgs/*stagedata*': No such file or directory
[void-repomaster@a-hel-fi ~]$ ls /hostdir/binpkgs/*repodata
/hostdir/binpkgs/armv6l-repodata  /hostdir/binpkgs/i686-repodata
/hostdir/binpkgs/armv7l-repodata  /hostdir/binpkgs/x86_64-repodata
[void-repomaster@a-hel-fi ~]$ ls /hostdir/binpkgs/musl/*repodata
/hostdir/binpkgs/musl/armv6l-musl-repodata  /hostdir/binpkgs/musl/x86_64-musl-repodata
/hostdir/binpkgs/musl/armv7l-musl-repodata
[void-repomaster@a-hel-fi ~]$ ls /hostdir/binpkgs/musl/*stagedata*
ls: cannot access '/hostdir/binpkgs/musl/*stagedata*': No such file or directory
[void-repomaster@a-hel-fi ~]$ ls /hostdir/binpkgs/aarch64/*stagedata*
ls: cannot access '/hostdir/binpkgs/aarch64/*stagedata*': No such file or directory
[void-repomaster@a-hel-fi ~]$ 
```

xq-api also returns the correct data as well now:

```
maldridge@theGibson:~$ curl https://xq-api.voidlinux.org/v1/query/i686?q=bsdtar|jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   310  100   310    0     0    313      0 --:--:-- --:--:-- --:--:--   312
{
  "data": [
    {
      "name": "bsdtar",
      "version": "3.4.1",
      "revision": 1,
      "filename_size": 422724,
      "repository": "current",
      "short_desc": "BSD utilities using libarchive"
    },
    {
      "name": "bsdtar-dbg",
      "version": "3.4.1",
      "revision": 1,
      "filename_size": 2333960,
      "repository": "debug",
      "short_desc": "BSD utilities using libarchive (debug files)"
    }
  ]
}
```

**Comment by xtraeme** [comment]
great, thanks.

I'll merge base-chroot-v2 soon. Don't apply or close this one, I'll take care of it.

**Comment by the-maldridge** [comment]
noted.  I'm going to bring the glibc builders back online and then call it a night.

**Comment by xtraeme** [comment]
yeah, good night :-)

**Comment by xtraeme** [comment]
#17969 has been applied, this one can be closed.

**Pull request closed without merging**
