### PR TITLE
foomatic-db{,-nonfree}: update to 20210104. 

### PR DESCRIPTION
**Pull request by fosslinux**
These two packages are essentially non-versioned databases but need to be bumped every so often.

### CODE REVIEW

**Comment by ericonr** [comment]
Can we switch to pulling a specific commit from git? https://github.com/archlinux/svntogit-packages/blob/packages/foomatic-db/trunk/PKGBUILD

**Comment by Chocimier** [comment]
Updates can be detected each month with 

    site="https://www.openprinting.org/download/foomatic/"
    pattern=$pkgname'-[\d.]+-\K[\d]+'
    ignore="${version:0:6}*"

**Comment by Anachron** [comment]
foomatic-db template version has a typo in the year.

**Comment by fosslinux** [comment]
@ericonr complete.
@Chocimier insufficient for the new git-based check which is what really should occur, but i did not have luck making a regex for github... any tricks?
@Anachron thanks

**Comment by Chocimier** [comment]
Something like that maybe. 

    site="https://github.com/OpenPrinting/foomatic-db"
    version="${version:0:4}.${version:4:2}.${version:6:2}"
    pattern="relative-time datetime=\"\K\d{4}-\d{2}-\d{2}"

We usually use date of commit as version, but 2021 is fine here, to avoid going back.

**Pull request merged**
