### PR TITLE
brltty: fix build w/ musl-1.2.1 (time64)

### PR DESCRIPTION
**Pull request by pullmoll**

### CODE REVIEW

**Comment by ericonr** [comment]
Looks very similar to what upstream has: https://github.com/brltty/brltty/blob/0f312feaece1956faa3f2ddba4096bd2c47b6626/Programs/system_linux.c#L1190

We can remove the patch once it gets a new release :)

**Comment by ericonr** [comment]
I'm rather unsure if this needs a revbump... The current behavior shouldn't change, right?

**Comment by pullmoll** [comment]
@ericonr behaviour should not change. Would the PR have been built w/o the revbump? I can undo it anyway.

**Comment by ericonr** [comment]
> Would the PR have been built w/o the revbump?

It seems not, but it would have been nice if it did. Will try to fix this!

**Pull request merged**
