### PR TITLE
go: don't ship build cache, fix maintainer

### PR DESCRIPTION
**Pull request by ebfe**

### CODE REVIEW

**Comment by the-maldridge** [comment]
I'd rather not see a revert commit in this chain and c98c679 needs to be split into two commits.  I'm away from my computer with keys until late this evening, so if another @void-linux/pkg-committers member has time and the above issues are fixed before I get back, feel free to merge.

Policy around package maintainer changes will need to be drafted and posted, referencing this pull.

**Comment by Gottox** [comment]
@ebfe can you comment on the maintainer revert? Iirc you told me and even stated publicly that you left void.

**Comment by ebfe** [comment]
> @ebfe can you comment on the maintainer revert? Iirc you told me and
> even stated publicly that you left void.

Define "left" void.

I said i didn't want to join the new organization because I felt how the
whole move to "void-linux" was kinda dishonest/unethical from my point
of view (no need to discuss further, you disagree and it's fine).

I said I won't be on IRC anymore because too much bullshit.

I said I disagree with a lot of the decision making (in particular the
randomly made up policies that serve no real purpose), that I am tired
of the endless discussion of the same 3-year old issues that then result
in a 5-minute pseudo fix which ignores all previous discussion and 
breaks something else, that I'm pretty annoyed by the huge gap of what
is communicated about "testing" and "quality" and what happens in reality
and don't want any deeper involvement at this point in time.

I probably (semi-)publicly stated that I don't spend much time on void
anymore, that I kind of lost hope in it and that I moved important
servers to something else because I don't really trust it anymore.

If that means I can't maintain packages anymore (new policy?), so be
it...

**Comment by ebfe** [comment]
And just to get this out of my system before I move on and to answer your
question. I reverted the maintainer because I de facto maintain these package(s)
since 18 months. Someone pushed a sloppy update, sloppy rebuild, didn't bother to
check whether the update breaks builds to at least mark stuff broken. In short,
skipped the whole actually "maintaining" the package part, yet felt compelled
to slap his name on it. No big problem I just fixed the stuff, but apparently 
that can't be merged now because, somehow, in the few hours since the update
commit, we can't have a maintainer change and a fix in the same commit anymore.
Oh, and revert commits are disallowed now as well (git log --grep Revert).
Seriously?

As maintainer change policy I'd suggest "use common sense and an email client"
(hint: there's already a "maintainer= needs a valid email address" policy).

**Pull request closed without merging**
