### PR TITLE
neovim: update to 0.7.0.

### PR DESCRIPTION
**Pull request by kartikynwa**
#### Testing the changes
- I tested the changes in this PR: **briefly** (been using it for five minutes)

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc

#### Notes

From reading the changelog: https://github.com/neovim/neovim/releases/tag/v0.7.0

I don't see any new dependencies or feature flags. So I have bumped the package version and changed the name of the LICENSE file as was needed. Working fine on my system. If any changes need to be made feel free to let me know.

### CODE REVIEW

**Comment by kartikynwa** [comment]
If anyone has any tips for the failing crossbuilds, feel free to let me know. Meanwhile I will ask on their discourse about it.

**Comment by kartikynwa** [comment]
I am thinking it will need some patches to fix the crashes on aarch64.

**Comment by kartikynwa** [comment]
Build succeeds with LuaJIT branch v2.1 HEAD (ddb95537645746) with these patches ported over to the updated code: `enable-debug-symbols.patch  fix-bcsave-ppc64.patch  get-rid-of-luajit-version-sym.patch`

But the repository has seen a lot of commits after the latest patch we have downstreamed:

```
luajit on  v2.1
❯ git log --since="2018-06-24T14:09:00" --grep=ARM --grep=arm64 --oneline | wc -l
31
```

Closing this since I am not sure what to do here.

**Comment by kartikynwa** [comment]
@Johnnynator sorry for pinging you. You pushed some patches in LuaJIT to fix neovim crashes. If you can tell me how you picked those patches I can do that step myself.

**Comment by Johnnynator** [comment]
> @Johnnynator sorry for pinging you. You pushed some patches in LuaJIT to fix neovim crashes. If you can tell me how you picked those patches I can do that step myself.

I just used `git bisect` to find the commit that fixed it.
But there is also currently a discussion in #xbps on IRC whether we should just switch the LuaJIT package fuy to some newer git commit.

**Comment by kartikdc** [comment]
> But there is also currently a discussion in #xbps on IRC whether we should just switch the LuaJIT package fuy to some newer git commit.

LuaJIT seems to not be doing releases so this could be the easier option.

**Comment by kartikynwa** [comment]
> But there is also currently a discussion in #xbps on IRC whether we should just switch the LuaJIT package fuy to some newer git commit.

@Johnnynator For what it's worth, the neovim developers always test against the HEAD of the v2.1 branch because LuaJIT seem to not be doing any releases for the past couple of years. If neovim is the only package that is using LuaJIT, you can update it whenever there a new neovim release.

Don't have a strong opinion on this. Just laying out what I have found from pestering the neovim developers.

**Comment by gbrlsnchs** [comment]
> If anyone has any tips for the failing crossbuilds, feel free to let me know. Meanwhile I will ask on their discourse about it.

For my custom packages, I'm using the following in order to build Neovim to ARM64:
```sh
pre_configure() {
	vsed -i runtime/CMakeLists.txt \
		-e "s|\".*/bin/nvim|\${CMAKE_CROSSCOMPILING_EMULATOR} &|g"

	if [ "$CROSS_BUILD" ]; then
		# https://github.com/neovim/neovim/pull/16722#issue-1084168744
		configure_args+=" -DCOMPILE_LUA=OFF"
	fi
}
```

**Comment by kartikynwa** [comment]
https://github.com/void-linux/void-packages/pull/36704#issuecomment-1101686958 is also what gpanders suggested to me on the neovim forum.

**Comment by LinArcX** [comment]
Guys, we need neovim 0.7.0

Please submit a PR if it doesn't have any issue for building in different architectures.

**Comment by kartikynwa** [comment]
@gbrlsnchs can you confirm that after compiling with `-DCOMPILE_LUA=OFF`, neovim actually works on arm64 or not? I don't the hardware to test it.

**Comment by gbrlsnchs** [comment]
> @gbrlsnchs can you confirm that after compiling with `-DCOMPILE_LUA=OFF`, neovim actually works on arm64 or not? I don't the hardware to test it.

I'm also unable to test it right now, unfortunately. I just had it compiled for future usage.

Still, I don't think that breaks anything; it seems to turn off a Lua optimization where Neovim's Lua API code is compiled ahead of time instead of interpreted during runtime.

**Comment by CameronNemo** [comment]
FYI: https://github.com/void-linux/void-packages/pull/36790 and https://github.com/CameronNemo/void-packages/commit/7ec696e5d77d8dca95677e92b6ba63f2728dbd13

**Comment by LinArcX** [comment]
I have void-linux for more than 3 years, but recently i'm thinking more to switch to another distro,(that let me do whatever i want without any stupid limitations).

The main reason is that i still don't understand why maintainers of void insist on release versions of applications.

In my opinion, there's no single direction between "no-bug" and "high-quality" software with having "releases".

Stop this annoying policy and let people be more free.

**Pull request closed without merging**
