### PR TITLE
New package,:zerotier-one

### PR DESCRIPTION
**Pull request by wallabra**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**|**NO**

#### Local build testing
- I built this PR locally for my native architecture, x86-64

### CODE REVIEW

**Comment by wallabra** [comment]
Still have to figure out the Rust build error. It might be an issue with that particular package, and not Zerotier / this config. But we are blocked until that issue is resolved.

**Comment by wallabra** [comment]
As for the checksum, oops!

**Comment by wallabra** [comment]
In the first workflow run:

> /bin/sh: line 1: cargo: command not found

That's odd, considering I have it in `makedepends` already and it works just fine on my end. (Using chroot/foreign build workflow)

**Comment by wallabra** [comment]
The error messages are very interesting. Some of the ARM builds fail because there's no cargo(???), others because there's no /usr/sbin.

**Comment by wallabra** [comment]
> Still have to figure out the Rust build error. It might be an issue with that particular package, and not Zerotier / this config. But we are blocked until that issue is resolved.

So this happens only on x86 hosts. Wow, each architecture has a different issue? I'm having a headache already...

**Comment by chrysos349** [comment]
```diff
diff --git a/srcpkgs/zerotier-one/files/zerotier-one/run b/srcpkgs/zerotier-one/files/zerotier-one/run
new file mode 100644
index 000000000..fdde52177
--- /dev/null
+++ b/srcpkgs/zerotier-one/files/zerotier-one/run
@@ -0,0 +1,3 @@
+#!/bin/sh
+exec 2>&1
+exec zerotier-one
diff --git a/srcpkgs/zerotier-one/template b/srcpkgs/zerotier-one/template
new file mode 100644
index 000000000..9e26d7f69
--- /dev/null
+++ b/srcpkgs/zerotier-one/template
@@ -0,0 +1,24 @@
+# Template file for 'zerotier-one'
+pkgname=zerotier-one
+version=1.14.0
+revision=1
+build_style=gnu-makefile
+short_desc="Smart Ethernet Switch for Earth"
+maintainer="chrysos349 <chrysostom349@gmail.com>"
+license="custom:BSL-1.1"
+homepage="https://github.com/zerotier/ZeroTierOne"
+changelog="https://raw.githubusercontent.com/zerotier/ZeroTierOne/dev/RELEASE-NOTES.md"
+distfiles="https://github.com/zerotier/ZeroTierOne/archive/refs/tags/${version}.tar.gz"
+checksum=7191623a81b0d1b552b9431e8864dd3420783ee518394ac1376cee6aaf033291
+repository=nonfree
+
+pre_configure() {
+	vsed -i "s/sbin/bin/g" make-linux.mk
+	# disable SSO
+	vsed -i "/ZT_SSO_SUPPORTED=/s/1/0/g" make-linux.mk
+}
+
+post_install() {
+	vsv zerotier-one
+	vlicense LICENSE.txt
+}
-- 
2.46.0
```

**Comment by wallabra** [comment]
Ahh okay, makes sense.

**Pull request closed without merging**
