### PR TITLE
[TESTERS NEEDED] empathy: update to 3.25.90.

### PR DESCRIPTION
**Pull request by Piraty**
Upon startup, i get
```
Error contacting the Account Manager

There was an error while trying to connect to the Telepathy Account
Manager. The error was:

The name org.freedesktop.Telepathy.AccountManager was not provided by any .service files
```
I suspect the issue is rooted in missing dbus / elogind/consolekit session on my machine.

If anyone could test, I'd be happy.

### CODE REVIEW

**Comment by shahab-vahedi** [comment]
This is due to a missing package: `telepathy-mission-control`. This dependency must be added to `empathy`.

**Comment by Piraty** [comment]
thanks @shahab-vahedi , can you try the updated template now?

I suspect there more brokenness to it as
- it doesn't display some icons on my (minimal) system
- it doesn't show any type of connection to add during account setup

**Comment by shahab-vahedi** [comment]
`adwaita-icon-theme` provides some icons --> not necessary.

**Comment by shahab-vahedi** [comment]
Now I cannot add an account anymore: neither with the test version nor the stable version. Account setting is just empty. I remember that the stable version allowed me adding accounts, once I installed some _optional_ dependencies:

```
xbps-install telepathy-{gabble,idle,haze,salut}
```

But that does not work anymore.

**Comment by Piraty** [comment]
ok, after installing the packages you mentioned (you forgot `xbps-install -S`) it seems to works.
Some icons are still not shown for me (desprite adwaita-icon-theme being installed), but I'll leave that for someone else to fix.

**Comment by xtraeme** [comment]
isn't this a development version? (curious to know why it's necessary)

**Comment by Piraty** [comment]
you're right, it's a development version: tagged two years ago... and development stalled.
In fact i wanted to help out @k4leg here https://github.com/void-linux/void-packages/pull/16892#discussion_r358814716.
Hence my request for testers.
@xtraeme  so you `-1` on this one?

**Comment by xtraeme** [comment]
@Piraty there might be exceptions, if the stable version is way out-of-date I wouldn't be against it.

**Comment by xtraeme** [comment]
@Piraty I'm not against it, simply I wanted to make you aware that GNOME software has even numbers for stable versions and odd for development.

**Comment by Piraty** [comment]
both 3.12.14 and 3.25.90 are tagged at a similar date (August 2017), and a quick test doesn't show any broken behavior to me.
Closing this, as i consider the current version stable enough.
Efforts will continue to live in my branch for later reference: https://github.com/Piraty/void-packages/tree/empathy-3.25.90

**Pull request closed without merging**
