### PR TITLE
asio: update to 1.18.0

### PR DESCRIPTION
**Pull request by ev-ermakov**
Note: vdrift works fine.

screenshot

### CODE REVIEW

**Comment by ericonr** [comment]
Please remove `archs=noarch` from the template.

**Comment by ev-ermakov** [comment]
Done.

**Comment by ev-ermakov** [comment]
> Is rebuilding vdrift necessaury?

I think no. But I can't check it right now.

**Comment by ev-ermakov** [comment]
> Is rebuilding vdrift necessary?

I'll reply a little later.

**Comment by ev-ermakov** [comment]
> Is rebuilding vdrift necessary?

It turned out that `vdrift` does not require `asio`.

**Pull request closed without merging**
