### PR TITLE
backport meson patch to set lxc-user-nic suid bit

### LINKED ISSUE #38682: users running unprivileged lxc container no worky no more.
### Is this a new report?

Yes

### System Info

5.18.17_1 #1 SMP PREEMPT_DYNAMIC Fri Aug 12 13:53:18 UTC 2022 x86_64 GNU/Linux musl.

### Package(s) Affected

lxc-5.0.1_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

_No response_

### Expected behaviour

It working like it did before the update. All I did was XBoxPlayStation-install -Su and init 6. 

### Actual behaviour

lxc-start: alpina: ../src/lxc/network.c: lxc_create_network_unpriv_exec: 2990 lxc-user-nic failed to configure requested network: ../src/lxc/cmd/lxc_user_nic.c: 802: create_db_dir - Permission denied - Failed to create /run/lxc

../src/lxc/cmd/lxc_user_nic.c: 1125: main: Failed to create directory for db file
lxc-start: alpina: ../src/lxc/start.c: lxc_spawn: 1840 Failed to create the network
lxc-start: alpina: ../src/lxc/start.c: __lxc_start: 2107 Failed to spawn container "alpina"
lxc-start: alpina: ../src/lxc/tools/lxc_start.c: main: 306 The container failed to start
lxc-start: alpina: ../src/lxc/tools/lxc_start.c: main: 311 Additional information can be obtained by setting the --logfile and --logpriority options

and if i mkdir /run/lxc, chown lxcuser /run/lxc i get this:

lxc-start: alpina: ../src/lxc/network.c: lxc_create_network_unpriv_exec: 2990 lxc-user-nic failed to configure requested network: ../src/lxc/cmd/lxc_user_nic.c: 474: instantiate_veth - Operation not permitted - Failed to create veth1003_cv7j-veth1003_cv7jp

../src/lxc/cmd/lxc_user_nic.c: 529: create_nic: Error creating veth tunnel
../src/lxc/cmd/lxc_user_nic.c: 720: get_nic_if_avail: Failed to create new nic
../src/lxc/cmd/lxc_user_nic.c: 1206: main: Quota reached
lxc-start: alpina: ../src/lxc/start.c: lxc_spawn: 1840 Failed to create the network
lxc-start: alpina: ../src/lxc/start.c: __lxc_start: 2107 Failed to spawn container "alpina"
lxc-start: alpina: ../src/lxc/tools/lxc_start.c: main: 306 The container failed to start
lxc-start: alpina: ../src/lxc/tools/lxc_start.c: main: 311 Additional information can be obtained by setting the --logfile and --logpriority options

### Steps to reproduce

Have a working lxc user + container.
Update the system.
Reboot.
Try and start it with: lxc-start -n nameofyourcontainer -F

Thanks for reading.

### PR DESCRIPTION
**Pull request by CameronNemo**
Switch to meson had a small casualty.
Rebuild with patched meson.
Also simplify the docbook2x patch.

https://github.com/mesonbuild/meson/pull/10702
https://github.com/lxc/lxc/pull/4177

Closes #38682

#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by eli-schwartz** [comment]
As mentioned in the linked issue, I believe this is a Meson bug and have PRed a patch to fix it that does not require running INSTALL scripts.

**Comment by CameronNemo** [comment]
I have re-built LXC using meson with the patch and verified that the packaged lxc-user-nic has the setuid bit set.

**Comment by paper42** [comment]
Could you mention simplifying the docbook patch in the commit message?

**Comment by CameronNemo** [comment]
@paper42 done

**Pull request merged**
