### PR TITLE
tzutils: tzdata provides py3:tzdata

### PR DESCRIPTION
**Pull request by classabbyamp**
according to the [Python documentation][1], the `zoneinfo` module uses the system timezone data if available, and also provides an installable `tzdata` library on PyPi. Some Python packages (like pandas) spuriously always depend on this library. By having `tzdata` provide this py3: package, it would work around Python packages that make this mistake, and avoid needing to package `python3-tzdata` or set `noverifypydeps` (which would be overkill).

@sgn, this is your package, what do you think?

[1]: https://docs.python.org/3/library/zoneinfo.html

#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by sgn** [comment]
It doesn't matter anyway, since our python3-tzdata is almost empty and uses system zoneinfo.

**Comment by classabbyamp** [comment]
oh, `python3-pytzdata`?

**Comment by classabbyamp** [comment]
that's not the same thing as [tzdata](https://pypi.org/project/tzdata/) i think

**Comment by sgn** [comment]
Ah yes! Anyway, what is different between: `provides="python3-tzdata-${version}_1"` and `provides="py3:tzdata-${version}_1"`?

**Comment by sgn** [comment]
/me removes `pytzdata` too! https://github.com/void-linux/void-packages/pull/53609

**Comment by classabbyamp** [comment]
> what is different between: `provides="python3-tzdata-${version}_1"` and `provides="py3:tzdata-${version}_1"`?

`py3:` will get used by the python dependency verification hook, but we could have it provide both

**Pull request merged**
