### PR TITLE
ccache: update to 4.10.2.

### PR DESCRIPTION
**Pull request by dataCobra**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86_64-musl
  - i686

### CODE REVIEW

**Comment by dataCobra** [comment]
Upcoming downloads and the issues did not happen while building locally. :thinking:

**Comment by meator** [comment]
It looks like `doctest-devel` is missing in `makedepends`. I would also add `-DDEPS=LOCAL` to `configure_args`.

Also, [the compiler can't be `cc`, it must be set to `gcc` instead](https://github.com/ccache/ccache/blob/v4.10.1/test/run#L547-L559). This issue should be pretty easy to fix upstream, maybe it's worth reporting.

**Comment by dataCobra** [comment]
Hey @meator,

thank you for the help.

Could you explain to me a bit further what you mean with the link to the line you added? I don't see the use of `cc` there.

**Comment by meator** [comment]
> I don't see the use of `cc` there.

Well that's the problem. The test runner tries to run `$CC --version` which resolves to `cc --version` under current circumstances so this gets outputted:

```
cc (GCC) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Only the first line is important (thanks to `head -1`). `gcc` is actually mentioned in the first line, but it's `GCC` and the [glob I've linked](https://github.com/ccache/ccache/blob/v4.10.1/test/run#L547-L559) is case sensitive, so it falls back to `*` default branch which **skips and invalidates all tests**.

The first branch (`*gcc*|*g++*|2.95*`) should be run here. This means that either `test/run` has to be modified or `$CC` has to be modified. If I were responsible for this update, I would try to set `$CC` to `gcc` in the template (this isn't a breaking change because `cc` = `gcc`, `cc` is a symlink to it[^1]) and I would make an issue in the upstream repository requesting to add `*GCC*` to the first branch (or some similar solution).

[^1]: This means that `cc` and `gcc` are _almost_ identical. One of the few factors that separate them, program name (the zeroth argument of the command line `$0`) is unfortunately the one causing trouble here.

**Comment by dataCobra** [comment]
Thank you for the detailed explanation.

I've changed the template accordingly and testing does work now.

**Pull request closed without merging**
