### PR TITLE
New package: limine-4.20230215.0

### PR DESCRIPTION
**Pull request by mintsuki**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86_64-musl
  - i686
  - i686-musl
  - aarch64
  - aarch64-musl

### CODE REVIEW

**Comment by mobinmob** [comment]
Thank you for (re)submiting a PR @mintsuki !
limine is an **realy nice** bootlader, it is ideal for live cds IMHO.

**Comment by mobinmob** [comment]
Just 2 suggestions:
- It may be a good thing to provide some documentation in the package. README.md, PROTOCOL.md and CONFIG.md can be installed with vdoc.
- Please provide a sample limine.cfg in the package. The one under test/ will be fine.

**Comment by Vaelatern** [comment]
This is attractive, though I personally have no use for it (being a heavy ZFS user)...

Do you have an idea as to if the cross built artifacts successfully boot a piece of hardware?

**Comment by mobinmob** [comment]
> This is attractive, though I personally have no use for it (being a heavy ZFS user)...

I am planing to use limine with zfs in my main machine. Limine will act as an boot manager for uefi to load zfsbotmenu and as a chainloading bootloader.

I found 'limine.cfg' to be really straightforward. Barry Kawler, the creator of Puppy Linux and EasyOS has done work on a script that discovers any os on local disk and generates a proper configuration file, but have not studied it yet.

**Comment by mintsuki** [comment]
I wouldn't go as far as to chainload another bootloader for ZFS... that isn't really the point of Limine, but if you wanna use it in that fashion that's okay.

I would suggest reading the newly added `PHILOSOPHY.md` file in the root of the Limine repo for an idea behind the design and usage philosophy of the bootloader.

**Comment by mintsuki** [comment]
> This is attractive, though I personally have no use for it (being a heavy ZFS user)...
> 
> Do you have an idea as to if the cross built artifacts successfully boot a piece of hardware?

I wouldn't be able to tell you for sure, but what I *can* tell you is that it is exceedingly rare (never witnessed) a successful Limine build (regardless of environment) misbehave, bar actual Limine bugs, of course.

**Comment by mintsuki** [comment]
@Vaelatern @classabbyamp
Is there anything wrong with the PR? Alternatively, is there an ETA for merge?

If Limine's notoriety is the issue blocking this PR, it may help to know it is packaged upstream for Alpine Linux, and it is the bootloader used to boot EasyOS (made by the Puppy Linux creator) which ranks 22nd on DistroWatch at the time of writing this.

**Comment by fungilife** [comment]
limine.cfg

I packaged limine for the joborun linux distro and recently upgraded.  I still find the limine.cfg sample lacking and haven't yet reached a level of expertise to create one of my own (and possibly share it here),  I would think a good sample .cfg would utilize the maximum of options available and not be a minimal functional .cfg.  Guessing what the correct syntax for the variables/fields have become a hopeless and endless guestwork experiment.

I find your philosophy.md rather contradictory and I do not share much of this same philosophy, which is not a problem for either one of us but contradiction is for both of us.  One the one hand you adopt the industrial motion (I wouldn't call every choice industry makes either progress or development) for non-bios non-legacy booting, on the other hand you reject it in the fashion of filesystem selection.  Either drop ext(n) all together and limit your scope in Fat32, dropping the linux marketing approach all together, or do add other common linux fs support.  Maybe as modules that can be configured at build-time whether to be included or not.

I wouldn't make an argument for zfs or btrfs, as I despise one and never used the later,  but xfs is a close cousin of ext in philosophy and functionality with significant advantages (i.e resizing a mounted system partition, strict accuracy on writing data).  Since the distant past xfs had a minor advantage in speed over ext mainly due to its journaling outside the partition ability.  This small advantage with the continuous development of speed of read/write of SSD/M2 technology and multitasking/multiprocessing has become a measurable significant advantage.   Hence the resurrection of interest in that fs.  

Where the limine sw is located and to what fs it can be written may be both a system and policy issue, but dictating to what fs the kernel should be written and whether it should be separated from the partition of the remaining system is a bit beyond the scope of a bootloader.  It borderlines the dictatorial approach of systemd/ibm legacy.

Then there is the issue of people multibooting MS systems that seem to be moving to strict NTFS efi partitions which is an additional mess a bootloader must deal with, if it is not to alienate all those users who must be able to boot MS-w for work requirements.

Hence the characterization of contradictory in reference to philosophy.  I'd say drop the ext support as it was never there as an easy route.  And so goes industrial trends of calling themselves evolution and development when they are accumulating one mess on top of another to enforce their products and displace those of "competing" interests.

Legacy in terms of booting should be perceived strictly as bios with mbr/dos table where nothing other than text configuration files of a bootloader can exist within the "system".  It is getting harder and harder to distinguish wolves in sheep''s clothing and Trojan horses in FOSS.

Where would "the industry" be if unix/linux wasn't able to boot anymore on their new toys?  Why is everyone rushing to comply so much to "development"?  So MS/IBM/Google/Facebook/Oracle  engineers can write and compile code on FOSS?  F* them!

**Comment by classabbyamp** [comment]
please take your rants elsewhere

**Pull request merged**
