### PR TITLE
goocanvas: update to 3.0.0.

### PR DESCRIPTION
**Pull request by Wesley-Chan**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86-64-musl)

### CODE REVIEW

**Comment by Wesley-Chan** [comment]
The failure in CI is due to this package: gpredict

It specifically requires goocanvas 2 in configure.ac, but as discussed in [this issue](https://github.com/csete/gpredict/issues/246), gpredict can use goocanvas 3 as well. [Changes to adapt to it](https://github.com/csete/gpredict/blob/master/configure.ac#L52-L65) was also merged into its master but gpredict has no new version released after that change.

In our case, it is one package that is blocking our advancement. Is the normal way to resolve conflicts to make a newer version of goocanvas in Void Linux, or make custom patch to gpredict?

Please advice. Thank you very much.

**Comment by classabbyamp** [comment]
if you can find the upstream commit(s)/pr that added goocanvas3 support for gpredict, you can export it as a patch by adding `.patch` to the url and download it to srcpkgs/gpredict/patches

**Comment by Wesley-Chan** [comment]
Hey, @classabbyamp. Thank you for your quick reply.

Sorry, I don't quite understand what you meant by "`perl-GooCanvas2` is the only other package that depends on goocanvas". Doesn't `gpredict` also depend on goocanvas by linking to it?

The motivation of mine to update goocanvas is to bring [Akira](https://github.com/akiraux/Akira) to Void, which does depend on goocanvas 3. If I understand correctly, if other packages like `gpredict` or `perl-Goocanvas2` refuse to move on, `Akira` could never land on Void Linux, right?

Thank you very much.

P.S. How do I verify the GitHub action `Verify repository state` locally? Is it documented anywhere? Thanks again.

**Comment by classabbyamp** [comment]
> Sorry, I don't quite understand what you meant by "`perl-GooCanvas2` is the only other package that depends on goocanvas". Doesn't `gpredict` also depend on goocanvas by linking to it?

only package other than gpredict is what I meant

> The motivation of mine to update goocanvas is to bring [Akira](https://github.com/akiraux/Akira) to Void, which does depend on goocanvas 3. If I understand correctly, if other packages like `gpredict` or `perl-Goocanvas2` refuse to move on, `Akira` could never land on Void Linux, right?

in this case, we'd want to have a versioned package for the time being, like `goocanvas2` and `goocanvas`. however, it seems that akira removed goocanvas? (https://github.com/akiraux/Akira/pull/652)

> How do I verify the GitHub action `Verify repository state` locally? Is it documented anywhere?

that ci step:
https://github.com/void-linux/void-packages/blob/2cb7f280f8fbded19d8f4fc22813dd47336665a0/.github/workflows/build.yaml#L120-L126
runs this script:
https://github.com/void-linux/void-packages/blob/master/common/travis/check-install.sh
I would not recommend running it locally outside of a container.

**Comment by newbluemoon** [comment]
There is also #31159 which worked for me (i.e. the `pre_configure`-fix). I tested it with all depending packages just didn’t pursue it any further, because there didn’t seem to be much interest at that time. ;)

**Pull request closed without merging**
