### PR TITLE
gnome-builder: update to 3.30.0.

### PR DESCRIPTION
**Pull request by Cogitri**
Builder needs gtksourceview4, so I put it in the same PR

### CODE REVIEW

**Comment by Cogitri** [comment]
Needs https://github.com/void-linux/void-packages/pull/2450

**Comment by maxice8** [comment]
libdazzle was updated, please rebase and re-push for travis ci

**Comment by Cogitri** [comment]
Also needs the glib bump, like lots of other stuff

**Comment by Cogitri** [comment]
Should compile now

**Pull request closed without merging**
