### PR TITLE
mate-desktop: update to 1.22.1.

### PR DESCRIPTION
**Pull request by thomas-t-w**

### CODE REVIEW

**Comment by thomas-t-w** [comment]
I am not sure why this is failing but I will keep looking. I did have to add the librsvg-utils package as a dependency. It seems like it has something to do with cross building. I am making sure these build and run locally before I submit a pull request but I only have x86 based hardware.

**Comment by jnbr** [comment]
cross builds fail because configre can't find `rsvg-converts`, so add `librsvg-utils` to hostmakedepends

**Comment by thomas-t-w** [comment]
Oh I think I understand. Because rsg-convert is a program that is run during the build as opposed to a library that is being linked in, it needs to be the same as the host archetecture not the target architecture being built for. Thanks for the help on this. This is my first time working with cross compiling so I am wrapping my head around how it works still.

**Comment by xtraeme** [comment]
Right. This is how it works. Been watching at you and it's amazing, keep up
the good work

**Comment by congdanhqx** [comment]
Is it better to group all update to mate into one merge request? (With separated commit, of course)
Right now, there're a lot of PRs for Mate's components.

**Comment by Hoshpak** [comment]
I don't mind having a lot of PRs. Having them separated makes it easier to review one by one and also allows travis to pass. However packages that depend on each other should better be in the same PR. I have seen at least one component that depends on mate-desktop and won't build without a current version of it.

**Pull request merged**
