### PR TITLE
New package: fiss-0.1.1

### PR DESCRIPTION
**Pull request by friedelschoen**
The old request did not cross-compile and conflicts with `runit`/`runit-void`
- above packages are added to `removes`
- cross-compiling still failed by stripping the binaries

Anyways:
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-musl)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - only x86_64-* works, as cross-compile-strip will fail (unrecognized file-format)

### CODE REVIEW

**Comment by friedelschoen** [comment]
Sorry for resubmitting this PR. I'm fairly new into contributing via GitHub and could not forcibly recommit. I'll keep that in mind on my next PR 😄 !

**Comment by Chocimier** [comment]
Stripping fails because makefile ignore value of CC and compile for host. nocross is not a fix. Please patch/vsed makefile to `CC ?= gcc` and cross could work.

**Comment by ahesford** [comment]
The upstream package is not yet a month old. I think packaging this is premature. Let things stabilize for awhile.

**Comment by friedelschoen** [comment]
Alright! Thanks for letting me know.

I'll come back if there's a stable release.

I appreciate your work and thanks for your time 🙌🏼

**Pull request closed without merging**
