### PR TITLE
New package: linux5.13-5.13.0

### PR DESCRIPTION
**Pull request by leahneukirchen**
WIP, will queue until 5.13.1.

- [x] arm64-dotconfig
- [x] i386-dotconfig
- [x] ppc-dotconfig
- [x] ppc64-dotconfig
- [x] ppc64le-dotconfig
- [x] x86_64-dotconfig

I had to remove `include/config/dvb` but the headers seem to be in `drivers/media/dvb-frontends` anyway, if someone knows how to test that help is welcome.

### CODE REVIEW

**Comment by newbluemoon** [comment]
Tested on i686, DVB-C works just as with all previous kernels (if that’s what you mean).
nvidia390 also works without any modification. :)
However, nfs doesn’t work anymore and nothing in the logs... :(

**Comment by leahneukirchen** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ff4b2b4014cbffb3d32b22629252f4dc8616b0fe

**Comment by leahneukirchen** [comment]
@newbluemoon would be cool if you could test NFS on .1.

DVB is about external modules I think, not sure which ones there are.

**Comment by newbluemoon** [comment]
NFS works again with 5.13.1! :) No problems encountered so far; will report if something comes up.
As for DVB, I don’t have hardware that requires external modules so I can’t help with that, sorry.

**Pull request merged**
