### PR TITLE
Add cifsd, a new alternative SMB server.

### PR DESCRIPTION
**Pull request by CMB**

### CODE REVIEW

**Comment by Anachron** [comment]
This looks promising, is this tested with v3 shares from a windows host?

**Comment by CMB** [comment]
> This looks promising, is this tested with v3 shares from a windows host?

It's only the server side (I.E., an smbd replacement).  I've connected
to it with Linux boxes and an iPhone.  The Linux clients used the
in-kernel CIFS client.  Everything worked out of the box.  I have no
Windows clients with which to test.

I went looking for this because I wanted to be able to mount shares with
my iPhone.  You can do that with Samba 3's smbd, though you have to edit
the config file and set "max protocol = SMB2".  Otherwise it just fails
cryptically, with no indication of why.  Also with Samba 3 I had to
force mounting with SMB1 (passing -o vers=1.0 to mount), on at least one
of my Linux clients.

**Comment by Anachron** [comment]
Ok thanks for the info, I'll see if I can get it working and test it between win and void.

**Comment by the-maldridge** [comment]
@CMB this looks good, but I'd like to get a current CI result before merging.  Can you rebase against master so you'll get a github actions build?

**Comment by CMB** [comment]
Sorry for not getting back to this sooner.  There is a new version
of this, so I'll update to it when I rebase.

Also I think I might have found a serious bug, so I want to try and reproduce
/ report that before doing anything more with the package.

**Comment by CMB** [comment]
Closing this for now, as I'm not all that sure it's ready for prime-time.
I've found at least one fairly easy to reproduce crash that I need to
report.

**Comment by Anachron** [comment]
So, did you report this upstream?

**Pull request closed without merging**
