### PR TITLE
teamspeak3: update to 3.5.2.

### PR DESCRIPTION
**Pull request by HadetTheUndying**
32-bit might be failing to build. Had it happen once then build the second time(No idea why), but since this isn't a repo package i decided to push anyway.

### CODE REVIEW

**Comment by Piraty** [comment]
please replace `makedepends="tar"` with `hostmakedepends="tar"`

**Comment by HadetTheUndying** [comment]
Done.

**Comment by Johnnynator** [comment]
Pls squash both commits into one

**Comment by HadetTheUndying** [comment]
@Johnnynator I don't know if i did that right, would you mind walking me through the proper procedure for squashing two commits together, I tried doing it with `git rebase -i HEAD~2 ` then using squash on the second commit but i don't know what it's supposed to do after that. I went ahead and rebased and pushed but it doesn't appear to have changed anything. 
Sorry I just don't work with git very often.

**Comment by Johnnynator** [comment]
Yeah `git rebase -i HEAD~2`, than either `fixup` or `squash`. Than continue (aka save and close in the editor you are). After that both commits should be one, and you need to do a force push (`git push -f`)

**Comment by HadetTheUndying** [comment]
Okay thanks man, Really appreciate it. I was just forgetting the --force

**Pull request merged**
