### PR TITLE
dhcpcd: update to 9.3.0.

### PR DESCRIPTION
**Pull request by ailiop-git**

### CODE REVIEW

**Comment by sgn** [comment]
Please skip 9.3.0

**Comment by ailiop-git** [comment]
> Please skip 9.3.0 https://roy.marples.name/archives/dhcpcd-discuss/0003214.html

argh.. thanks, yeah let's wait for v9.3.1.

**Comment by sgn** [comment]
And please skip `9.3.1` too, `9.3.{0,1}` has problem with powerpc32

**Comment by ericonr** [comment]
.2 is out

**Comment by sgn** [comment]
On 2020-11-05 14:07:04-0800, Érico Nogueira Rolim <notifications@github.com> wrote:
> .2 is out

I'm using .2 in local machine, I'll wait until this weekend to update
it, finally. I don't think I've heard any complain with our current
version (and neither with .9.3.2)

**Pull request closed without merging**
