### PR TITLE
python3-PyJWT: update to 2.0.1 + fix information

### PR DESCRIPTION
**Pull request by FollieHiyuki**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

There are test failures with ssl. I have no idea what to do with it though.

### CODE REVIEW

**Comment by ericonr** [comment]
You can probably disable tests temporarily, but leave a comment that they can be re-enabled once the switch to OpenSSL happens.

**Comment by FollieHiyuki** [comment]
Done

**Comment by FollieHiyuki** [comment]
The other tests still run, and now we get locale failures

**Comment by ericonr** [comment]
Could you fix the commit message? Dropping python2 isn't correct, because it being there was wrong.

Maybe "depend on correct python package"

**Comment by FollieHiyuki** [comment]
I was panic there for a moment :)
I also removed the `checkdepends` line. We can add it back again when tests can be run

**Pull request merged**
