### PR TITLE
getmail: remove package

### PR DESCRIPTION
**Pull request by paper42**
uses Python 2: https://pyropus.ca./software/getmail/documentation.html#python3

### CODE REVIEW

**Comment by dmarto** [comment]
There is a fork (https://github.com/getmail6/getmail6) that uses python3, I have had a template and used it for some time (https://github.com/dmarto/void-packages/blob/3bf8c1bfb203eeac8ad2ab908d189edbab749c2d/srcpkgs/getmail6/template), but I never got to making a PR as I am not sure what is better, making it a different package or updating this one.

**Comment by paper42** [comment]
According to https://pyropus.ca./software/getmail/documentation.html#python3, we should not replace getmail by getmail6 and I am not sure if we should even package it.

**Comment by dmarto** [comment]
oof I hadn't seen the `getmail6` section there (I just read the mailing list long time ago); for the record debian has `getmail6` (with `getmail` as transitional dummy pkg), and long ago I remember fedora were wondering what to do with the name (currently, I think they don't ship neither)

**Comment by paper42** [comment]
> Debian has apparently agreed to remove the "getmail6" package, and it should happen soon. I originally suggested they keep distributing it, but simply rename the package and executable, given that its maintainer outright refuses to do so. But apparently they'd rather drop it.

**Comment by dmarto** [comment]
Again just for the record for anyone reading this.

I rechecked the bug report in debian (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=996569) looks like, it is not actually being removed until `getmail` releases a python3 version, only the transitional package was removed in `debian bookworm`.

From Sudip Mukherjee, maintainer of `getmail{,6}` in debian:
> Not just Debian but all the distros need to have a Python3 version of
> getmail and getmail6 is the only alternative available now. I will be
> very very happy to remove getmail6 when you release a Python3 version
> of getmail. But until then I will only remove the transitional
> package.

**Pull request merged**
