### PR TITLE
fatsort: unmark broken on musl

### PR DESCRIPTION
**Pull request by ndowens**
Closes: #27635

### CODE REVIEW

**Comment by ndowens** [comment]
Seems tests fail, so will see about fixing those

**Comment by tibequadorian** [comment]
> Closes: #27635
why can't your PR be handled independently of mine?

**Comment by ndowens** [comment]
> > Closes: #27635
> 
> why can't your PR be handled independently of mine?

Figure it would be simple to handle both in one, while you still get credit if you look at commit, shows you as well.

**Comment by ndowens** [comment]
I will close and redo later; after I can figure out test issue.

**Pull request closed without merging**
