### PR TITLE
texlab: update to 3.0.1. (3.2.0 is available)

### PR DESCRIPTION
**Pull request by gbrlsnchs**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by alberdingk-thijm** [comment]
Is this still held up on rust being updated? Looks like the latest texlab is now 3.2.0 (as of this post).

**Comment by ericonr** [comment]
Ping :)

**Comment by gbrlsnchs** [comment]
Folks, I'm not on Void right now, thus I can't tackle this. Would any of you please take this over? :smile:

**Comment by ericonr** [comment]
I added a label so people cans see it, but won't tackle myself.

**Pull request closed without merging**
