### PR TITLE
postgresql

### PR DESCRIPTION
**Pull request by Chocimier**
#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by Chocimier** [comment]
Hi @sgn,

the recursive symlink `/usr/share/zoneinfo/posix` breaks parsing of zones by postgres. Can we change tzdata? Last time that occured - [gentoo, 2015](https://bugs.gentoo.org/show_bug.cgi?id=486532) - it was solved by removing recursive symlink. I haven't found a distro that install zones that way.

**Comment by sgn** [comment]
I see, the symlink was meant to keep backward compatibility, I will fix them, then.

**Comment by sgn** [comment]
A new version has been pushed.

**Comment by Chocimier** [comment]
Thanks, @sgn.

**Pull request merged**
