### PR TITLE
New package: python3-youtube-search-python-1.6.3

### PR DESCRIPTION
**Pull request by Eloitor**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86-64

New PR for https://github.com/void-linux/void-packages/pull/32587 as I deleted the previous branch.

### CODE REVIEW

**Comment by abenson** [comment]
python3-youtubesearch?

**Comment by Eloitor** [comment]
I understand that they are different packages...

https://pypi.org/project/youtube-search/
https://pypi.org/project/youtube-search-python/

I'm packing this because it is a dependency of ytmdl: https://github.com/deepjyoti30/ytmdl/blob/master/setup.py

**Comment by abenson** [comment]
Yes,  https://pypi.org/project/youtube-search-python/ is already packaged as python3-youtubesearch and is in the ytmdl template.

**Comment by abenson** [comment]
https://github.com/void-linux/void-packages/blob/master/srcpkgs/python3-youtubesearch/template

**Comment by Eloitor** [comment]
Oh I'm sorry I'm closing this.

**Pull request closed without merging**
