### PR TITLE
tuxc: remove package

### PR DESCRIPTION
**Pull request by tibequadorian**
It's just a bunch of aliases for xbps and other package managers written in (bad) C.
I think void shouldn't endorse this if there are better ways to do it.

e.g. shell script replacement:
```sh
tux() {
    case "$1" in
        i|install)    sudo xbps-install "${@:2}" ;;
        ri|reinstall) sudo xbps-install -f "${@:2}" ;;
        r|remove)     sudo xbps-remove "${@:2}" ;;
        s|search)     sudo xbps-query -Rs "${@:2}" ;;
        p|purge)      sudo xbps-remove -R "${@:2}" ;;
        u|upgrade)    sudo xbps-install -Su "${@:2}" ;;
        c|clean)      sudo xbps-remove -O "${@:2}" ;;
        su|sup)       sudo xbps-install -Su "${@:2}" ;;
        *) echo -e "\n\nTux: a drop in package manager wrapper\n
Usage: tux [options] [packages]\n
\t[Options]       [Description]\n
\ti  | install    Install Package(s)
\tri | reinstall  Reinstall Package(s)
\tr  | remove     Remove Package(s)
\ts  | search     Search for Packages
\tp  | purge      Remove package(s) and associated files
\tu  | upgrade    Perform System Upgrade
\tc  | clean      Clean Package Cache
\tsu | sup        Sync and Upgrade\n" ;;
    esac
}
```

### CODE REVIEW

**Review by sgn — APPROVED** [review]

**Comment by sgn** [comment]
You may need to update `removed-packages`, too.

**Comment by ericonr** [comment]
What's the policy for removed-packages? Should it also be revbumped? @Chocimier 

If so, it should be a separate commit.

**Comment by Chocimier** [comment]
Yes, as package changes, it needs to be revbumped - to greater than in master by now.
Please also save alphabetical order of packages.

**Comment by sgn** [comment]
Merged. Thanks!

**Comment by logenkain** [comment]
Yup, that was my (bad) C from a long time ago. I probably should go ahead and rewrite that.

Though now than I'm thinking about it, it would be nice if xbps had a built in wrapper for some of the more common commands. I think the first thing I did way back when I first used void was write a quick script to alias xbps commands to pacman commands.

**Comment by tibequadorian** [comment]
hey nothing personal :D mine is no better ... a compiled language is just probably not the right choice in this case.
When I deploy a new void linux installation I always install `xtools` first because it has most aliases I need and if not I can easily create them. Creating your own aliases is much more simple and extensible in my opinion and this is what I would recommend.

**Pull request closed without merging**
