### PR TITLE
New package: openjdk16-bin-16+36

### PR DESCRIPTION
**Pull request by tibequadorian**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)
***(The latest Minecraft version requires Java 16)***

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by daerich** [comment]
Small question: Shouldn't the binary package version be a GA(general availability) release? The one in the template is a reference implementation aimed at implementers of the language and platforms spec afaik. Arch by comparison also uses the 16.0.2 version in its [PKGBUILD](https://github.com/archlinux/svntogit-packages/blob/packages/java-openjdk/trunk/PKGBUILD)

**Comment by tibequadorian** [comment]
You're probably right...
tbh I more or less just copied the template from https://github.com/void-linux/void-packages/blob/master/srcpkgs/openjdk11-bin/template and it works for me.
The analog to archs PKGBUILD would be the one without "-bin" https://github.com/void-linux/void-packages/blob/master/srcpkgs/openjdk11/template but it looked too complicated for me...

Am 28. Juli 2021 16:01:05 MESZ schrieb DaErich ***@***.***>:
>Small question: Shouldn't the binary package version be a GA(general
>availability) release? The one in the template is a reference
>implementation aimed at implementers of the language and platforms spec
>afaik. Arch by comparison also uses the 16.0.2 version in its
>[PKGBUILD](https://github.com/archlinux/svntogit-packages/blob/packages/java-openjdk/trunk/PKGBUILD)

**Comment by q66** [comment]
i'm against this, either package it from source code as it should be, or don't at all

**Comment by tibequadorian** [comment]
i can accept that

**Comment by q66** [comment]
16 is not an LTS version, so you should probably wait for 17 (then bootstrap versions of 12-16 will need to be packaged, and non-bootstrap 17)

**Pull request closed without merging**
