### PR TITLE
python3-keyring: update to 23.13.1.

### PR DESCRIPTION
**Pull request by icp1994**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture: **x86_64**

### CODE REVIEW

**Comment by paper42** [comment]
This looks like the wrong path
```diff
+/usr/lib/python3.11/site-packages/keyring/backend_complete.zsh
```

**Comment by icp1994** [comment]
Yeah, I wasn't sure what to do with that. It is only supposed to work with [`shtab`](https://github.com/jaraco/keyring/blob/v23.13.1/setup.cfg#L67-L68) installed.

**Comment by paper42** [comment]
That seems to be used for generating the bash and fish one, but not the zsh completion. The zsh completion is installed always to the wrong destination and it's a simple file in the source https://github.com/jaraco/keyring/commit/ded09d94efac8089e12ee4d089074e7549dfcbe8.

**Comment by icp1994** [comment]
Doesn't [this line](https://github.com/jaraco/keyring/blob/v23.13.1/keyring/completion.py#L39) mean it's needed at that path?

**Comment by paper42** [comment]
> Doesn't [this line](https://github.com/jaraco/keyring/blob/v23.13.1/keyring/completion.py?rgh-link-date=2022-12-19T19%3A56%3A39Z#L39) mean it's needed at that path?

oh, I didn't notice that, it's fine then

**Pull request merged**
