### PR TITLE
wireplumber: update to 0.4.0, split -devel.

### PR DESCRIPTION
**Pull request by ericonr**
Remove reallocarray patch because we backported the functionality into
musl.

Add changelog.

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by prez** [comment]
I just tried the version of wireplumber in the repos, got this: 

```
$ wireplumber 
W 16:07:28.267036          wp-device ../lib/wp/device.c:588:wp_spa_device_new_from_spa_factory: SPA handle 'api.v4l2.enum.udev' could not be loaded; is it installed?
C 16:07:28.267077              wplua (null):(null):(null): wplua_pushobject: assertion 'G_IS_OBJECT (object)' failed
W 16:07:28.267119              wplua ../lib/wplua/wplua.c:49:_wplua_errhandler: [string "v4l2.lua"]:134: attempt to call a nil value (method 'connect')
stack traceback:
        [string "v4l2.lua"]:134: in local 'chunk'
        [string "sandbox.lua"]:95: in function 'sandbox'
M 16:07:28.267788        wireplumber ../src/main.c:400:main: Runtime error while loading 'v4l2.lua'
```

Maybe something is missing that could be handled in this update too?

**Comment by ericonr** [comment]
I think that's new, I'm seeing it with 0.4.0 as well... It might be due to pipewire version...

**Comment by ericonr** [comment]
Ok, for *reasons* it requires `libspa-v4l2`, which we can add as a dependency. Or change the configuration to not try and launch the v4l2 part of wireplumber,.

**Comment by ericonr** [comment]
Pending on toolchain rebuilds to pick up reallocarray in musl.

**Pull request merged**
