### PR TITLE
vscode: update to 1.40.2

### PR DESCRIPTION
**Pull request by shizonic**

### CODE REVIEW

**Comment by obunden** [comment]
Is anything holding the update back? I thought vscode was more popular than this

**Comment by Hoshpak** [comment]
vscode is an electron app which means it can't be built from source, requires fetching massive binaries, workaorunds for vendored shared libraries and so on. This makes it very unpopular with the project members. Frankly, if it were up to me, I would just throw every electron app out of the repository and tell people to install them via flatpak or another mechanism.

That being said, while the package is here, there is no reason not to update it. For this particular PR the following things have to be resolved to merge it:

* squashing of the commits, we don't need every version in between the current and the previous version, just the latest should remain
* travis shows the build fails on x86_64. Someone has to confirm that this is just a travis issue and the build works in fact

**Comment by shizonic** [comment]
@Hoshpak Just squashed the commits and built it successfully on my x86_64 system. I am asking myself why travis still tries to build it even if I put `ci skip` inside my commit messages?

**Comment by Hoshpak** [comment]
It needs square brackets.

**Pull request merged**
