### PR TITLE
gstreamer1, gst{1,}-*: update to 1.24.3

### PR DESCRIPTION
**Pull request by voidisnull**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by chrysos349** [comment]
@voidisnull 

could you add `python3-devel` to the dependencies of `gst1-editing-services-devel`?

**Comment by voidisnull** [comment]
@chrysos349 
The package `python3-devel` is already present in the `makedepends`. 
Shall I add it to `hostmakedepends` too?

**Comment by chrysos349** [comment]
i meant a `depends` section of the subpackage.

actually, gst-plugins-base1-devel is also required.

```diff
diff --git a/srcpkgs/gst1-editing-services/template b/srcpkgs/gst1-editing-services/template
index 7a020eea1..ae2a76112 100644
--- a/srcpkgs/gst1-editing-services/template
+++ b/srcpkgs/gst1-editing-services/template
@@ -28,7 +28,8 @@ do_check() {
 
 gst1-editing-services-devel_package() {
 	short_desc+=" - development files"
-	depends="${sourcepkg}>=${version}_${revision}"
+	depends="${sourcepkg}>=${version}_${revision} gst-plugins-base1-devel
+	 python3-devel"
 	pkg_install() {
 		vmove usr/include
 		vmove "usr/lib/*.so"
```

**Comment by voidisnull** [comment]
Done!!
And thanks for helping me out.

**Comment by cinerea0** [comment]
Superseded by d65cc6a1df16d16e93cddec3e0a9817514fb0d40 though dbf79262a9a83665fcbfea122c01699f7b1495b2; closing.

**Pull request closed without merging**
