### PR TITLE
[WIP] icu: update to 67.1; Claim maintainer

### PR DESCRIPTION
**Pull request by rmccask**
There are 99 packages that will need to get a revbump because of this.  I have the list of packages in a file.  How do you want me to include all of those?

### CODE REVIEW

**Comment by ericonr** [comment]
I'd do a single commit for the revbump, at most. Otherwise it will fill up the log too much. And all in this PR.

**Comment by pullmoll** [comment]
First be sure to have `[ci skip]` in the commit message body of `icu: update to 67.1; Claim maintainer` or Travis will be hogged for days. Then you can use `xrevbump "revbump for icu-67.1" <list of packages>` and finally `git push -f`. 

Each revbump should be a single commit in this PR.

**Comment by rmccask** [comment]
I have marked this as [WIP] while I test build all the packages.

**Comment by q66** [comment]
one commit per each revbumped package, please; that's the standard way

**Comment by rmccask** [comment]
qt5-webengine 5.14.2 is using getAllFieldPositions in their latest version.  This function is gone in ICU 67.1.  I am changing this PR to ICU 66.1.  I will reattempt 67.1 later.

**Comment by q66** [comment]
let's not update to an already old version, ICU is too rebuild-heavy not to it all at once

if needed, patch things to build

**Comment by Johnnynator** [comment]
You can take a look arch arch for patches. E.g. qt5-webengine https://git.archlinux.org/svntogit/packages.git/plain/trunk/icu67.patch?h=packages/qt5-webengine

**Comment by ericonr** [comment]
@rmccask you need to fix the icu-libs sub-package function, it's copying the `lib*.so` files to icu-devel instead of icu-libs.

**Comment by ericonr** [comment]
Any reason we aren't building the static libs as well? 

```
diff --git a/srcpkgs/icu/template b/srcpkgs/icu/template
index cc72b96d92..c1c7c499c8 100644
--- a/srcpkgs/icu/template
+++ b/srcpkgs/icu/template
@@ -8,7 +8,7 @@ wrksrc=icu
 build_wrksrc=source
 build_style=gnu-configure
 # use archive data instead of .so data for correct cross-compiling
-configure_args="--with-data-packaging=archive"
+configure_args="--with-data-packaging=archive --enable-static"
 hostmakedepends="pkg-config"
 short_desc="Robust and fully-featured Unicode libraries"
 maintainer="Orphaned <orphan@voidlinux.org>"
@@ -103,6 +103,7 @@ icu-devel_package() {
 		vmove usr/bin/icu-config
 		vmove "usr/share/man/man1/icu-config*"
 		vmove "usr/lib/*.so"
+		vmove "usr/lib/*.a"
 	}
 }
 icu-libs_package() {
```

**Comment by q66** [comment]
superseded by https://github.com/void-linux/void-packages/pull/22334

**Pull request closed without merging**
