### PR TITLE
New package: gmime3-3.2.3

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by Cogitri** [comment]
Depends on #5905

**Comment by Cogitri** [comment]
Would appreciate it if you could test (S/)MIME functionality:

notmuch: Seems like you two touched notmuch last: @crater2150 @travankor
astroid: @bitmeise

**Comment by bitmeise** [comment]
I really appreciate being notified here.
Smoke tested your gmime3 with the libidn2 branch and astroid seems to work fine.

**Comment by travankor** [comment]
sorry for the late response
notmuch-emacs works fine with gmime3

**Comment by crater2150** [comment]
notmuch commandline and neomutt integration works fine too :+1:

**Comment by Cogitri** [comment]
Thanks for testing!

**Pull request merged**
