### PR TITLE
ghq: update to 1.1.5

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Comment by smorimoto** [comment]
Can anyone review this?

**Comment by smorimoto** [comment]
ping

**Comment by smorimoto** [comment]
Can anyone review this? There's no rush, but it would be great if someone could review this.

**Comment by ericonr** [comment]
Thanks for pinging!

**Comment by smorimoto** [comment]
@ericonr Thank you, too! I've been a hidden active user of Void Linux for a long time, so please let me know if there is anything I can do for you all. I used to maintain several Brew packages, so I know the pain of maintaining such projects :)

**Pull request merged**
