### PR TITLE
Obtain devpdf fonts from ghostscript

### PR DESCRIPTION
**Pull request by anddam**
cfr. https://lists.gnu.org/archive/html/groff/2019-02/msg00080.html

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by abenson** [comment]
Change the commit message to `groff: obtain devpdf fonts from ghostscript`

**Comment by abenson** [comment]
Also, you probably want to bump the revision

**Comment by ericonr** [comment]
Cross builds are missing the new files :/

Can you try adding `ghostscript` to `hostmakedepends` instead?

**Comment by anddam** [comment]
> Cross builds are missing the new files :/
> 
> Can you try adding `ghostscript` to `hostmakedepends` instead?

It's a big effort but I'll do my best.

**Comment by anddam** [comment]
> > Can you try adding `ghostscript` to `hostmakedepends` instead?

> It's a big effort but I'll do my best.

And done. CI is running but I have faith.

**Pull request merged**
