### PR TITLE
libbluray: update to 1.2.1.

### PR DESCRIPTION
**Pull request by skmpz**

### CODE REVIEW

**Comment by ericonr** [comment]
Has it been working fine?

**Comment by skmpz** [comment]
> Has it been working fine?

Do you mean testing on actual bluray disc?

**Comment by ericonr** [comment]
> Do you mean testing on actual bluray disc?

Yes.

**Comment by skmpz** [comment]
> > Do you mean testing on actual bluray disc?
> 
> Yes.

No :\

**Comment by ericonr** [comment]
Do you have any way of testing? I don't love merging this without at least one data point saying it's working fine. Staying out of date isn't a great option either; if you could take a look at upstream issues to see if anything has shown up, that'd be great.

If it hasn't, I can merge this at the end of the day.

**Comment by abenson** [comment]
I can try and test.

**Comment by skmpz** [comment]
> Do you have any way of testing? I don't love merging this without at least one data point saying it's working fine. Staying out of date isn't a great option either; if you could take a look at upstream issues to see if anything has shown up, that'd be great.
> 
> If it hasn't, I can merge this at the end of the day.

Unfortunately no way of testing.. No issues have been reported until now.

**Comment by abenson** [comment]
It works with my one non-copy-protected Bluray.

**Pull request merged**
