### PR TITLE
vscode: update to 1.47.3. [ci skip]

### PR DESCRIPTION
**Pull request by shizonic**

### CODE REVIEW

**Comment by atk** [comment]
vscode-1.47.1 just came out.

**Comment by shizonic** [comment]
> vscode-1.47.1 just came out.

Updated. Thanks!

**Comment by atk** [comment]
And we're up to 1.47.2 ;-)

**Comment by shizonic** [comment]
> And we're up to 1.47.2 ;-)

Thanks again. But FYI: I get notified about updates immediately  from my feed. ;-) I just don't have always the time to update immediately. I work every day.

**Comment by atk** [comment]
Sorry, won't bother you again. By the way, how are you creating those diffs?

**Comment by shizonic** [comment]
> Sorry, won't bother you again. 
No proplem. I'm just on vacation...
> By the way, how are you creating those diffs?
Which diffs? `git diff`?

**Comment by shizonic** [comment]
update

**Comment by shizonic** [comment]
bump version

**Pull request merged**
