### PR TITLE
linux-firmware: update to 20210511.

### PR DESCRIPTION
**Pull request by absrd**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Will be testing locally for a while, would appreciate ok from others.

**Comment by noarchwastaken** [comment]
Just tested on my laptop, worked as expected.

@ericonr BTW, should we consider a continuous approach for `linux-firmware` like Arch and Ubuntu?

I'm thinking about it because I almost have to wait two months for `linux-firmware` to tag and enable my RX 6700XT on Void (thankfully I don't have to since I can tinker with the package.)

**Comment by ericonr** [comment]
It's a big package to be continuously updating and downloading, so I'm not super in love with that idea...

**Comment by noarchwastaken** [comment]
> It's a big package to be continuously updating and downloading, so I'm not super in love with that idea...

Or we can mirror the repo, tag it ourselves more frequently and when someone asks for hardware support that is in master but not tagged upstream yet...

**Comment by ericonr** [comment]
A tad simpler would be adding plumbing to support pulling from a specific commit hash and use the date of said commit as package version.

No need to have our own repo :p

**Comment by noarchwastaken** [comment]
> A tad simpler would be adding plumbing to support pulling from a specific commit hash and use the date of said commit as package version.
> 
> No need to have our own repo :p

Great :D

**Pull request merged**
