### PR TITLE
New package: airshipper-0.7.0.

### PR DESCRIPTION
**Pull request by teldra**
solves https://github.com/void-linux/void-packages/issues/36127

#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-musl

### CODE REVIEW

**Comment by teldra** [comment]
> Is it possible to move do_install() to post_install() and remove the vbin line?

Sadly it seems, it is not possible. The error when changed: `error: found a virtual manifest at /builddir/airshipper-v0.7.0/Cargo.toml instead of a package manifest`

Or am I missing something?

**Comment by teldra** [comment]
I add this launcher, because Veloren needs rust with nightly featureset we not provide. And Veloren is updated quite frequently.

**Comment by tibequadorian** [comment]
Alright, I don't think you're missing something. Thanks for testing :)

**Comment by tibequadorian** [comment]
`airshipper` works fine for me.
I'm not sure about `airshipper-server` though. It should not be confused with the Veloren server.

**Comment by tibequadorian** [comment]
Can you say how you tested `airshipper-server`, @teldra?

**Comment by tibequadorian** [comment]
If we can't test it properly and it's of no use for us, there's no point in shipping it.
It also looks like the server urls are [hardcoded](https://gitlab.com/veloren/airshipper/-/blob/master/client/src/profiles.rs#L93) in the client.

**Comment by tibequadorian** [comment]
>Is it possible to move do_install() to post_install() and remove the vbin line?

If you set `build_wrksrc=client` this^ should be possible and avoids building the server for nothing.

**Comment by teldra** [comment]
I think, this template is mergeable, now. :)

**Review by tibequadorian — APPROVED** [review]
Yes, thank you :)

**Pull request closed without merging**
