### PR TITLE
pd: update to 0.49

### PR DESCRIPTION
**Pull request by CameronNemo**

### CODE REVIEW

**Comment by Hoshpak** [comment]
@thypon

**Comment by thypon** [comment]
The 0 version is hard coded, it is probably breaking the update-check script

**Comment by CameronNemo** [comment]
Leaving it as is broke the distfiles. Anything I can do to fix both?

**Comment by jnbr** [comment]
leave `_ver` as it was before and change the version to `0.49.0`

**Comment by Johnnynator** [comment]
@CameronNemo Did you check if the symlinks are actually correct? The current version does link `/usr/lib/pd/bin/pd -> /destdir//pd-0.48.2/usr/bin/pd`

**Comment by CameronNemo** [comment]
I fixed the version, but the broken symlink that Johnnynator pointed out is still there. Any ideas short of just ripping it out and recreating it?

**Pull request merged**
