### PR TITLE
xfce4-4.16

### PR DESCRIPTION
**Pull request by pbui**
Updated core xfce4 packages to 4.16.0 as listed here: https://gitlab.xfce.org/xfce.  [ChangeLog](https://xfce.org/download/changelogs/4.16/)

Built and tested on x86_64.  Also built for x86_64-musl (but didn't test).

### CODE REVIEW

**Comment by marmeladema** [comment]
`xfconf` tests appear to have failed:
```
FAIL: t-set-string
FAIL: t-set-int
FAIL: t-set-uint64
FAIL: t-set-double
FAIL: t-set-arrayv
FAIL: t-set-boolean
FAIL: t-set-stringlist
============================================================================
Testsuite summary for xfconf 4.16.0
============================================================================
# TOTAL: 7
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  7
# XPASS: 0
# ERROR: 0
============================================================================
See tests/set-properties/test-suite.log
Please report to https://gitlab.xfce.org/xfconf/xfconf
============================================================================
```

**Comment by pbui** [comment]
@marmeladema That test failure is not new... it also fails with the current 4.14.4 package.  Previously, the CI did not automatically run the check and so it was never an issue.

@ericonr What is the current policy with failed checks?  Is it a blocker if a package fails the checks?

**Comment by pbui** [comment]
It looks like the tests require dbus and an X11 display... this is the message I get when I run it manually:

```
** (process:7923): CRITICAL **: 08:47:25.090: Failed to connect to D-Bus: Cannot autolaunch D-Bus without X11 $DISPLAY
```

**Comment by ericonr** [comment]
No need to let these tests block the PR :) 

```
diff --git a/srcpkgs/xfconf/template b/srcpkgs/xfconf/template
index 2d8924741c..2c712efd3e 100644
--- a/srcpkgs/xfconf/template
+++ b/srcpkgs/xfconf/template
@@ -7,6 +7,7 @@ build_style=gnu-configure
 configure_args="--enable-gsettings-backend"
 hostmakedepends="pkg-config intltool glib-devel vala-devel"
 makedepends="libxfce4util-devel vala-devel"
+checkdepends="dbus xvfb-run"
 short_desc="Xfce hierarchical (tree-like) configuration system"
 maintainer="Orphaned <orphan@voidlinux.org>"
 license="GPL-2.0-only, LGPL-2.0-only"
@@ -16,6 +17,10 @@ checksum=652a119007c67d9ba6c0bc7a740c923d33f32d03dc76dfc7ba682584e72a5425
 build_options="gir"
 build_options_default="gir"
 
+do_check() {
+	dbus-run-session xvfb-run make check
+}
+
 xfconf-devel_package() {
 	depends="dbus-glib-devel ${sourcepkg}>=${version}_${revision}"
 	short_desc+=" - development files"
```

I would say the policy is to fix tests, if possible/simple. But we aren't blocking merges on complicated tests.

**Comment by sgn** [comment]
```
xfce4-mailwatch-plugin-1.2.0_5: broken, unresolvable shlib `libexo-1.so.0'
xfce4-kbdleds-plugin-0.0.6_3: broken, unresolvable shlib `libxfce4panel-1.0.so.4'
xfce4-mailwatch-plugin-1.2.0_5: broken, unresolvable shlib `libxfce4panel-1.0.so.4'
xfce4-notes-plugin-1.8.1_4: broken, unresolvable shlib `libxfce4panel-1.0.so.4'
xfce4-windowck-plugin-0.4.6_2: broken, unresolvable shlib `libxfce4panel-1.0.so.4'
xfce4-kbdleds-plugin-0.0.6_3: broken, unresolvable shlib `libxfce4ui-1.so.0'
xfce4-mailwatch-plugin-1.2.0_5: broken, unresolvable shlib `libxfce4ui-1.so.0'
xfce4-notes-plugin-1.8.1_4: broken, unresolvable shlib `libxfce4ui-1.so.0'
xfce4-windowck-plugin-0.4.6_2: broken, unresolvable shlib `libxfce4ui-1.so.0'
```

**Comment by pbui** [comment]
Thanks @ericonr.  I've made those changes to `xfconf`.

**Comment by pbui** [comment]
@sgn Did you need me to do anything regarding the plugins?  Also, how did you get a list of broken plugins (for future reference)?

**Comment by sgn** [comment]
On 2020-12-23 08:07:16-0800, Peter Bui <notifications@github.com> wrote:
> @sgn Did you need me to do anything regarding the plugins?

Probably needs to update xfce4-mailwatch-plugin, I think.
I'll remove other plugins, they're very old, and not updated to new
shlib. I may see if I can patch those plugins to use new ABI, sometime
later.

exo provides both shlib for a long time for transitioning, if they
don't act, I think it's safely remove them.

> how did you get a list of broken plugins (for future reference)?

Mainly because I'm lazy and I have xfce4-plugins installed, which
pulls all of those plugins.

You can see the dependencies list with xrevshlib <pkgname>

Anyway, there's some entry for old SONAME is common/shlib,
Some cleanup will be welcome.

Thanks,

-- 
Danh

**Comment by sgn** [comment]
Anyway, running on x86_64-musl now, no issue so far.

**Comment by marmeladema** [comment]
@sgn @pbui is there anything else that needs to be taking care of to get this merged?
I am willing to help, I just don't know the status of things.

**Comment by sgn** [comment]
I'm fine with this update. I guess some more testing is needed.
And until pbui removed the `[RFC]`, we probably won't merge :-p

**Comment by pbui** [comment]
@sgn I think it is good to go.

**Comment by sgn** [comment]
Thanks, I'll merge when builder is free again (I guess not less than 10 hours, since electron is being built :-p)

**Comment by sgn** [comment]
Hm, I need to take attention to CI the next time. xfce4-dev-tools was failed to build on cross. 8c32d557442b33c3747ddddd75f6c272064e6953

**Pull request merged**
