### PR TITLE
New package: python3-docker-compose-1.29.2

### PR DESCRIPTION
**Pull request by SpidFightFR**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x64-GlibC)

Hey guys, just a new little package: python3-docker-compose.

Funny side note: i made the template cuz i needed that package for a personal project lol :smile:

### CODE REVIEW

**Comment by fanyx** [comment]
why not just use `docker compose` from the official implementation?

**Comment by SpidFightFR** [comment]
> why not just use `docker compose` from the official implementation?

Good question.
I used ansible for my project, and ansible doens't quite like the default implementation.
It seeks a python3 module docker compose...

**Comment by fanyx** [comment]
https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_v2_module.html#ansible-collections-community-docker-docker-compose-v2-module

there is a community.docker module that has support for the official `docker compose v2` plugin

**Comment by SpidFightFR** [comment]
> https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_v2_module.html#ansible-collections-community-docker-docker-compose-v2-module
> 
> there is a community.docker module that has support for the official `docker compose v2` plugin

ooh... neat!
Sorry i'm new to ansible stuff, i've mainly stick to python-related stuff...
Imma test this out ASAP. Thanks for the heads up !

**Comment by fanyx** [comment]
No worries!
Good luck out there o/

**Comment by SpidFightFR** [comment]
> No worries! Good luck out there o/

Thank you. It means a lot! :pray:

**Pull request closed without merging**
