### PR TITLE
meson: update to 0.58.2

### PR DESCRIPTION
**Pull request by paper42**
meson 0.58 was previously reverted because it broke mutter and other GNOME packages which use generate_gir, I bisected it and reverted the commits that made it fail, I also created an upstream issue https://github.com/mesonbuild/meson/issues/8999.

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by paper42** [comment]
updated with a proper patch that should be in 0.59.1

**Comment by ericonr** [comment]
Awesome, thanks for tracking this down!!

**Comment by paper42** [comment]
0.58.2 was released with the fix

**Comment by st3r4g** [comment]
Installed this update and it fixed an issue where unrelated targets were rebuilt every time `meson test` was run.
However, there is an issue with tab completion:
Type `meson test` and then `Tab` twice:
```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ericonr** [comment]
What shell is that? I assume something broke the completions, then?

**Comment by st3r4g** [comment]
Sorry, the completion thing was present before the update too.
It's the bash completion, which is a bit sloppy:
```
python3 -c 'import sys, json;
for test in json.load(sys.stdin):
  for suite in test["suite"]:
    print(suite)
    ' <<< "$(meson introspect "$dir" --tests)"
```

**Comment by paper42** [comment]
@st3r4g I can reproduce this issue, could you contact upstream?

**Comment by st3r4g** [comment]
yeah, trying to figure out how to patch it. Otherwise, I'll open an issue

**Comment by st3r4g** [comment]
Opened an issue upstream, but I think this shouldn't block the update

**Pull request merged**
