### PR TITLE
nvidia340: fix issues after libglvnd introduction

### LINKED ISSUE #17251: nvidia340 broken, unresolvable shlib `libnvidia-ml.so.1'
### System

* xuname:  
Void 5.3.12_1 i686 GenuineIntel uptodate rrDDFFF
* package:  
  - nvidia340-340.107_6

### Expected behavior
Being able to update the system

### Actual behavior
The system update fails with the error mentioned above. I manually updated all nvidia340-* packages to the current revision.
### Steps to reproduce the behavior
1. Install nvidia340
2. Try to update the system

If I manually remove the nvidia340 package and try to update, xbps wants to remove nvidia340-libs and install libglvnd instead. Since nvidia340 does not support glvnd, I don't want that. libnvidia-ml.so.1 is in fact listed in the shlib_provides of the nvidia340-libs package so xbps should be able to resolve it.

### PR DESCRIPTION
**Pull request by st3r4g**
Hope this fixes #17251. Not 100% sure about xorg config file provided, I have an alternative in case this doesn't load the correct GLX.

### CODE REVIEW

**Comment by xtraeme** [comment]
@Hoshpak please provide Xorg.0.log after this

**Comment by st3r4g** [comment]
We must fix `=> ERROR: nvidia340-libs-340.107_7: cannot guess required shlibs, aborting!`

**Comment by Hoshpak** [comment]
Looks like libnvidia-glsi.so.340.107 needs to be installed and added to comm/shlibs.

**Comment by st3r4g** [comment]
No symlinks required, right?

**Comment by xtraeme** [comment]
Nope, internal library

**Comment by xtraeme** [comment]
maybe Nvidia will bring us a big surprise soon. Who knows? Heh

**Comment by xtraeme** [comment]
Would be nice if they would release fw for nouveau... It's about time.

**Comment by st3r4g** [comment]
it builds now. So should I remove those symlinks?

**Comment by xtraeme** [comment]
In these times I would buy AMD. Free stuff with fw

**Comment by xtraeme** [comment]
Yeah

**Comment by st3r4g** [comment]
done

**Comment by st3r4g** [comment]
The alternative config, in case the one provided doesn't work, is:
```
Section "Files"
    ModulePath "/usr/lib/nvidia/xorg"
    ModulePath "/usr/lib/xorg/modules"
EndSection
```

**Comment by xtraeme** [comment]
@st3r4g  for president. You are friend of @pullmoll? Haha

**Comment by Hoshpak** [comment]
I haven't gotten around to test if xorg still works yet. Installing the packages now removes libEGL however updating the system is still not possible. New xbps log: https://gist.github.com/Hoshpak/ebbfc43dbd14a710aafbc855ee6839f0

**Comment by xtraeme** [comment]
I see. The symnlink is till necedssry

**Comment by st3r4g** [comment]
I think the problem here is that `libglvnd` is still preferred, what about `replaces=libglvnd`?

**Comment by xtraeme** [comment]
No, thr symlinks are missing for this lib really

**Comment by xtraeme** [comment]
.so.1

**Comment by xtraeme** [comment]
@st3r4g see the error from xbps-install

**Comment by xtraeme** [comment]
It's the SONAME remember

**Comment by st3r4g** [comment]
But we already create the symlinks for that lib in the template...

**Comment by st3r4g** [comment]
I set up a chroot, with the changes here one can install `nvidia340` from current repo state. The problem is for who has `nvidia340` already installed, `libglvnd` wants to replace it.

**Comment by st3r4g** [comment]
The problem may also be the `libglapi` temporary fix (dependency on `libglvnd` was added).

**Comment by xtraeme** [comment]
Right he has both Mesa and nvidia340 installed... Good luck. Going to sleep

**Comment by st3r4g** [comment]
Previous state was also weird tbh

**Comment by st3r4g** [comment]
@Hoshpak what if you manually remove `libglapi` before updating?

**Comment by st3r4g** [comment]
Maybe it's wrong for `libglapi` to hard depend on `libglvnd`, it was actually added just to fix the update of `-32bit` packages.

**Comment by Hoshpak** [comment]
That fixed it indeed, thanks. However I had to remove the xorg meta-package and all drivers to make it work which will leave most of the xorg stuff as orphans. Installing them again pulls libglapi which pulls glvnd.

**Comment by Hoshpak** [comment]
Also xorg does not work any more. It tries to load swrast_dri.so and fails to start. Will post the detailed logs tomorrow.

**Comment by st3r4g** [comment]
well yes it's because you had to remove the dri drivers.

**Comment by st3r4g** [comment]
The mesa dri drivers shouldn't be needed, and `swrast_dri.so` is mesa stuff, maybe xorg picks up the wrong GLX. Tomorrow pls attach list of installed packages and `Xorg.0.log`

**Comment by st3r4g** [comment]
@xtraeme to fix the update process here it is necessary to revert the temporary workaround 927f17347f9c646047c65312c8e8ce1ad88b7832 which was to fix the `-32bit` update process.

**Comment by Hoshpak** [comment]
This is the Xorg log after installing the updated package with the included configuration file:

https://gist.github.com/Hoshpak/3be50dbfc6933fdaa0bd0ccf8545f759

Looks fine so far. The issue I have now doesn't seem to come from Xorg but rather the nvidia libEGL. I launche kodi in the xorg session and it fails to start because it cannot initialize egl. Haven't found out yet why.

**Comment by st3r4g** [comment]
Nah it's bad it's not finding glx. Try replacing the provided configuration file with the alternate one I posted in a comment above.

**Comment by Hoshpak** [comment]
This is the Xorg.0.log with the alternate configuration file:

https://gist.github.com/Hoshpak/d9e364aec16a4212a1de9628ae1d7cd0

Kodi seems to segfault in libnvidia-glsi or at least that is what the crashlog looks like to me:
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib32/libthread_db.so.1".
Core was generated by `/usr/lib32/kodi/kodi-x11 --standalone'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x524f5252 in ?? ()
[Current thread is 1 (Thread 0xaf95da00 (LWP 4106))]
...
Thread 1 (Thread 0xaf95da00 (LWP 4106)):
#0  0x524f5252 in ?? ()
#1  0xaff175ce in ?? () from /usr/lib32/libnvidia-glsi.so.340.107
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
...
2019-12-10 22:08:25.674 T:2945833472  NOTICE: Checking resolution 16
2019-12-10 22:08:25.927 T:2945833472   ERROR: failed to initialize egl
```

**Comment by st3r4g** [comment]
Still has no effect:
```
[   613.636] (==) ModulePath set to "/usr/lib/xorg/modules"
```
It should say:
```
[  3118.875] (**) ModulePath set to "/usr/lib/nvidia/xorg,/usr/lib/xorg/modules"
```
Try copying it as `/etc/X11/xorg.conf`

**Comment by st3r4g** [comment]
A user reported that deleting that block makes GL work.

**Comment by xtraeme** [comment]
What block? Logs better than words

**Comment by st3r4g** [comment]
If one has a `/etc/X11/xorg.conf` created by `nvidia-xconfig`, the file contains the following block:
```
Section "Files"
EndSection
```
which overrides the correct path provided in the drop-in configuration of the package.

**Comment by xtraeme** [comment]
This is not something we have to care of

**Comment by xtraeme** [comment]
Foreign artifacts is nor our responsability

**Comment by st3r4g** [comment]
Still I think a post-install message at least would be very useful, I think this is also the problem in Hoshpak's case.

**Comment by xtraeme** [comment]
OK, sounds good

**Comment by Hoshpak** [comment]
I can confirm that removing that section also resolved the issue for me. Thanks a lot for your great work on this! I think putting in an install message is warranted since the xorg.conf I had been using was generated by nvidia-xconfig an never touched manually. Current versions don't add that section it seems but every user with an old enough configuration file will be bitten by this.

**Comment by st3r4g** [comment]
There is still a problem with people coming from the old weird mixed mesa/nvidia state, the same error as in the issue title will be met (this is because I didn't revert 927f173, which will break again the `-32bit` transition process). However now it can be easily worked around:
```
sudo xbps-remove nvidia340
sudo xbps-install -Su
sudo xbps-install nvidia340
```
A similar thing must be done to go back to nouveau:
```
sudo xbps-remove nvidia340 nvidia340-dkms
sudo xbps-install libglvnd
```

**Comment by st3r4g** [comment]
> Current versions don't add that section it seems but every user with an old enough configuration file will be bitten by this.

A user generated one today and it was affected.

**Comment by st3r4g** [comment]
@xtraeme 927f173 was introduced only to deal with the `-32bit` bug right? Can we change that depends= into lib32depends? I think that will unblock the upgrade for nvidia340.

**Comment by xtraeme** [comment]
Yes

**Comment by st3r4g** [comment]
Actually this seems enough as it is, the fact that I changed nvidia340-libs to provide libglvnd also fixed the upgrade transition from the old state. I tested this by:

- making a new voidstrap chroot
- building old libGL and xorg-server and installing xorg in chroot with those old packages
- installing nvidia340 (now I should be in old state)
- updating when I add local repo with nvidia340 revision 7 is possible

maybe I can test a bit more later.

**Comment by st3r4g** [comment]
@xtraeme I think this is ready, should allow to update.

**Pull request merged**
