### PR TITLE
[nomerge] New package: metamath-0.178

### PR DESCRIPTION
**Pull request by xelxebar**

### CODE REVIEW

**Comment by xelxebar** [comment]
Oh boy. It looks like upstream's url to the source is getting ninja edited.

**Comment by leahneukirchen** [comment]
Changing tarballs are bad for us, they break rebuilds. Perhaps instead use githashes and assemble the repo yourself?

**Comment by Piraty** [comment]
in case the exact same contents get repackaged, you could prepend `@` do the checksum, see Manual.md

**Comment by xelxebar** [comment]
Thanks @leahneukirchen and @Piraty. Unfortunately, the tar contents are changing. There are "source" files that the "interpreter" reads, and it is these "source" files that are getting periodically updated and refreshed in the tar.

Instead of rolling forking upstream and packaging, I am just talking to them directly. Apparently, Debian is also interested in packaging this up, so making upstream friendly to package managers seems like a good approach.

Unless someone objects, I will just leave this pull request alone until we get something situated upstream.

**Pull request closed without merging**
