### PR TITLE
Fix the SDL2 gles stuff on arm*

### PR DESCRIPTION
**Pull request by xtraeme**
There's no need to propagate the gles settings from SDL2.

@pullmoll why did you add those? AFAIK only SDL2 is enough.

### CODE REVIEW

**Comment by xtraeme** [comment]
@pullmoll please test, should dtrt afaik

**Comment by pullmoll** [comment]
@xtraeme I don't remember why it was necessary while I think the `SDL2_...` packages could just not be built before the switch to the libglvnd stuff.

**Comment by xtraeme** [comment]
I've got my old rpi3 but no microsd card writer... so can't test

**Comment by pullmoll** [comment]
I cannot test arm* either. All hardware is somewhere in a dusty corner and not ready to be powered up.

**Comment by pullmoll** [comment]
Travis thinks it's okay and I think the same so please merge.

**Pull request merged**
