### PR TITLE
update zig to `0.9.0`

### PR DESCRIPTION
**Pull request by AliChraghi**
**General**
 - [ ] This is a new package and it conforms to the quality requirements

**Have the results of the proposed changes been tested?**
- [X] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by abenson** [comment]
Please edit the commit message to follow convention.  It should read "zig: update to 0.9.0"

**Comment by abenson** [comment]
@ifreund

**Review by ifreund — COMMENTED** [review]
`llvm13` hasn't been packaged for void yet. Until then, zig cannot be updated. Unless you intend to update LLVM I'd recommend just closing this PR. The zig update will be included in the LLVM update PR when someone gets around to it.

**Comment by kotajacob** [comment]
Additionally, I don't believe the patch `0001-std.build-fix-handling-of-Dcpu.patch` is required any longer. It appears to have been merged into 0.9.0.

**Pull request closed without merging**
