### PR TITLE
New package: linux-pinebook-pro-5.4.0

### PR DESCRIPTION
**Pull request by CameronNemo**
[ci skip]

### CODE REVIEW

**Comment by jnbr** [comment]
You can remove most of the `*-dotconfig`.

**Comment by renatoaguiar** [comment]
Could you rename it to pinebookpro-kernel, so it matches naming convention used on kernels for other platforms?

**Comment by renatoaguiar** [comment]
Also, manjaro is now using commit 799b9141e48783a0844187ad00855b3d53f77998. We should probably use the same.

**Comment by travankor** [comment]
Is this still relevant? @renatoaguiar has packaged `pinebookpro-kernel`.

**Comment by CameronNemo** [comment]
FWIW I had trouble booting the latest pbp kernel, 5.6rc4.

**Pull request closed without merging**
