### PR TITLE
New package: mlton-20210117

### PR DESCRIPTION
**Pull request by ii8**
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-musl

### CODE REVIEW

**Comment by Bnyro** [comment]
Ref #44416

**Comment by leahneukirchen** [comment]
Good to see bootstrap via PolyML is possible; do you know if on non-x86 the C code generator is used/

**Comment by ii8** [comment]
Yes mlton selects C codegen for non x86(_64) targets.

I'm creating cross builds of mlton: https://github.com/ii8/mlton-builds/actions/runs/6785420672
If you were ok with using those to bootstrap, when they all work, then polyml isn't needed which means the 21kloc patch isn't needed either.

**Comment by leahneukirchen** [comment]
From a distro maintainer standpoint, I prefer bootstrapability from C.

**Comment by leahneukirchen** [comment]
But the 20k C file probably should be hosted somewhere else.

**Comment by ii8** [comment]
I don't mind either way, just mentioning the options. But I should mention that bootstrapping mlton with itself is recommended by the author and polyml fails for x86.
Where should it be hosted? Though it's several files of generated sml, just all in one patch.

**Comment by leahneukirchen** [comment]
You can hotlink `https://github.com/MLton/mlton/commit/f074a9a41b5338303271cd50f17078595fef35ff.patch`

**Comment by ii8** [comment]
The build failure with glibc is because it ran out of memory looks like.

**Comment by leahneukirchen** [comment]
Sorry, that wasn't super clear.  Add the patch to distfiles= and add it to noextract, then apply it in post_patch.

**Comment by leahneukirchen** [comment]
Also, how much RAM is needed to compile it?

**Comment by ii8** [comment]
> Sorry, that wasn't super clear. Add the patch to distfiles= and add it to noextract, then apply it in post_patch.

This is what I did at first, but I noticed the manual specifically says that distfiles must be in a compressed format. Is that not right?
I'd like to do it in pre_patch if possible so the other patches are unaffected. Is that a problem?

6Gi should be safe.

**Comment by leahneukirchen** [comment]
pre_patch is okay too. we use diffs as distfiles in other packages as well (I think you should use the compressed format if one is available, but if there is none, well.)

**Comment by leahneukirchen** [comment]
@ii8 any idea why this breaks now? https://build.voidlinux.org/builders/x86_64-musl_builder/builds/50236/steps/shell_3/logs/stdio

**Comment by leahneukirchen** [comment]
Indeed.  I forgot to clean it before trying `disable_parallel_build=yes`...

**Pull request merged**
