### PR TITLE
Rust 1.78

### PR DESCRIPTION
**Pull request by tranzystorekk**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by tranzystorekk** [comment]
Results of `build_style=cargo` rebuild for x86_64-gnu:

## New failures since 1.77

### Misc

- `gcsf` https://0x0.st/XX4-.txt cc @benalb
- `zet` https://0x0.st/XX4o.txt cc @icp1994

## Known failures

- `cargo-crev`
- `cargo-geiger`
- `fool`
- `gping` #49676
- `ion`
- `lapce`
- `spotifyd`
- `spotify-tui`
- `wasmtime`

**Comment by dkwo** [comment]
Do you know whether this breaks rust for linux drivers?
Lately, there was this sweet spot where e.g. asahi linux gpu driver in 6.8 series kernel could be built using our current rust 1.77.

**Comment by tranzystorekk** [comment]
No idea, anything that brought up that impression?

**Comment by dkwo** [comment]
just the fact that rust for linux has no stabilty guarantees yet.

**Comment by dkwo** [comment]
Nothing to worry about on the asahi side, it seems:

> Tagging asahi-6.8.9-3
> 
> - rust-1.78 build fixes

**Pull request merged**
