### PR TITLE
python-dateutil: update to 2.8.0.

### PR DESCRIPTION
**Pull request by CameronNemo**

### CODE REVIEW

**Comment by maxice8** [comment]
Need to test these packages to see if they can use the new python-dateutil

```
srcpkgs/beancount/template
srcpkgs/eolie/template
srcpkgs/khal/template
srcpkgs/pdd/template
srcpkgs/python-Arrow/template
srcpkgs/python-dateutil/template
srcpkgs/python-icalendar/template
srcpkgs/python-jupyter_client/template
srcpkgs/python-pandas/template
srcpkgs/python-ripe-atlas-cousteau/template
srcpkgs/python-ripe-atlas-sagan/template
srcpkgs/python-vobject/template
srcpkgs/python-alembic/template
srcpkgs/python-guessit/template
srcpkgs/ripe-atlas-tools/template
srcpkgs/python3-aniso8601/template
srcpkgs/radicale2/template
srcpkgs/python3-matplotlib/template
srcpkgs/python3-pykeepass/template
srcpkgs/python3-pykwalify/template
srcpkgs/tryton/template
```

**Comment by jnbr** [comment]
The diff between 2.7.5 and 2.8.0 is relatively small, no structural changes.
ripe-atlas-tools and pdd are working, any specific concerns @maxice8 ?

**Comment by CameronNemo** [comment]
I will try to stand up Radicale 2 this weekend so I can test that. Shouldn't be too hard to find the motivation.

**Comment by maxice8** [comment]
@jnbr i use this script to check setup.py for specific version requirements when updating. My only concern is updating to an incompatible version


```
#!/bin/sh
# Generate python dependencies
# Requires python3
[ -z "$1" ] && set -- "$(git rev-parse --abbrev-ref HEAD | 
						 sed 's|python-||g' |
						 sed 's|python3-||g')"

while [ $# -gt 0 ]; do
	cd masterdir/builddir/*"$1"* || exit 1

	result="$(find . -maxdepth 3 -iname requires.txt -exec cat '{}' +)"

	if [ -z "$result" ]; then
		# Generate requires.txt
		python3 setup.py egg_info >/dev/null 2>&1
	else
		printf "%s\\n" "$result"
	fi

	shift

done
```

**Pull request merged**
