### PR TITLE
open-vm-tools: update to 12.0.0.

### PR DESCRIPTION
**Pull request by Piraty**
#### Testing the changes
- I tested the changes in this PR: **NO**

I don't run vmware guests anymore, so testers are welcome

### CODE REVIEW

**Comment by tranzystorek-io** [comment]
I noticed that compared to Arch we're missing a service for `vmware-vmblock-fuse`: https://github.com/archlinux/svntogit-community/blob/master/open-vm-tools/trunk/vmware-vmblock-fuse.service

**Comment by Piraty** [comment]
if you have a use case, would you mind testing the trivial runit service for this then (for example , copy the whole cmdline)

**Comment by tranzystorek-io** [comment]
I did a quick prototype, but I'm not sure how to emulate systemd's `RuntimeDirectory` parameter, to create the `/run/vmblock-fuse` dir

**Comment by tranzystorek-io** [comment]
@Piraty I guess I could add this service in a spearate PR to make this update easier

**Comment by Piraty** [comment]
did you test this PR too?

**Comment by tranzystorek-io** [comment]
> did you test this PR too?

I made the service change on top of this PR and tested it out, I guess that counts?

**Comment by tranzystorek-io** [comment]
Tested the latest changes - all services run correctly when enabled, and the new `vmware-vmbock-fuse` allows copying files between host and guest

**Pull request closed without merging**
