### PR TITLE
wine: Update to 9.14

### PR DESCRIPTION
**Pull request by fvalasiad**
@Hoshpak

### CODE REVIEW

**Comment by zlice** [comment]
Can you add this to post_patch?

`sed '18,41d' -i ../wine-staging-9.13/patches/server-Stored_ACLs/0004-server-Temporarily-store-the-full-security-descripto.patch`

Someone was trying to build staging and it wasn't getting past this. Seems to be wine staging issue?

**Comment by zlice** [comment]
more appropriate replacement...if it builds

```diff
--- ./wine-9.13/dlls/advapi32/tests/security.c	2024-07-30 08:24:06.217640930 -0400
+++ ./wine-9.13/dlls/advapi32/tests/security.c.new	2024-07-30 08:24:29.989188060 -0400
@@ -3658,7 +3658,6 @@
     ok(error == ERROR_SUCCESS, "GetNamedSecurityInfo failed with error %ld\n", error);
     bret = GetAclInformation(pDacl, &acl_size, sizeof(acl_size), AclSizeInformation);
     ok(bret, "GetAclInformation failed\n");
-    todo_wine
     ok(acl_size.AceCount == 0, "GetAclInformation returned unexpected entry count (%ld != 0).\n",
                                acl_size.AceCount);
     LocalFree(pSD);
@@ -3672,7 +3671,6 @@
     {
         bret = GetAclInformation(pDacl, &acl_size, sizeof(acl_size), AclSizeInformation);
         ok(bret, "GetAclInformation failed\n");
-        todo_wine
         ok(acl_size.AceCount == 0, "GetAclInformation returned unexpected entry count (%ld != 0).\n",
                                    acl_size.AceCount);
         LocalFree(pSD);
@@ -3737,7 +3735,6 @@
     ok(error == ERROR_SUCCESS, "GetNamedSecurityInfo failed with error %ld\n", error);
     bret = GetAclInformation(pDacl, &acl_size, sizeof(acl_size), AclSizeInformation);
     ok(bret, "GetAclInformation failed\n");
-    todo_wine
     ok(acl_size.AceCount == 0, "GetAclInformation returned unexpected entry count (%ld != 0).\n",
                                acl_size.AceCount);
     LocalFree(pSD);
@@ -3751,7 +3748,6 @@
     {
         bret = GetAclInformation(pDacl, &acl_size, sizeof(acl_size), AclSizeInformation);
         ok(bret, "GetAclInformation failed\n");
-        todo_wine
         ok(acl_size.AceCount == 0, "GetAclInformation returned unexpected entry count (%ld != 0).\n",
                                    acl_size.AceCount);
         LocalFree(pSD);
```

**Comment by fvalasiad** [comment]
@zlice I am kinda confused, wine 9.14 builds, what seems to be the issue, what is that patch for?

**Comment by zlice** [comment]
staging doesn't build. the base package is fine.

**Comment by fvalasiad** [comment]
Ah, so the option to apply wine-staging patches on top in the template results in build failure, is that right?

**Comment by zlice** [comment]
yes me and a couple people in irc had the same issue. looks like they have a patch that needs updating. made a winehq report https://bugs.winehq.org/show_bug.cgi?id=57016

**Comment by fvalasiad** [comment]
I see, maybe I will be irresponsible tomorrow and actually try to debug this instead of focusing on my responsibilities. Can't tell, as of now I am fried so can't really help!

You can definitely open a PR since this one was merged though! I will probably try to fix it upstream if I get the chance anyways so yeah.

**Pull request merged**
