### PR TITLE
New package: dijo-0.2.3

### PR DESCRIPTION
**Pull request by cinerea0**
[dijo](https://github.com/NerdyPepper/dijo) is a curses-based habit tracker that runs in your terminal. It is currently available via nixpkgs.

### CODE REVIEW

**Comment by cinerea0** [comment]
After taking a look at the build errors, it looks as if this program fails to build on ARM architectures due to a dependency on [ncurses-rs](https://github.com/jeaye/ncurses-rs). This crate has not had updates since late October 2019, and issues filed both [before](https://github.com/jeaye/ncurses-rs/issues/184) and [after](https://github.com/jeaye/ncurses-rs/issues/193) that point refer to this as a known problem. Solutions proposed there seem to require modifying the source code in ways I'm not comfortable with. Is the best course of action in cases like these to restrict the architecture to non-ARM?

**Comment by cinerea0** [comment]
After discussion on IRC, I have altered the template so that it doesn't attempt to build on ARM architectures. That should clear up any issues that would prevent this from being merged.

**Comment by ericonr** [comment]
Any reason this wasn't assumed as simply nocross?

**Comment by cinerea0** [comment]
Issues with `ncurses-rs` seem to indicate that it doesn't work on ARM regardless of the architecture it was compiled on. Should I push an update to change it to a nocross package?

**Comment by ericonr** [comment]
Oh I saw https://github.com/jeaye/ncurses-rs/issues/193 now. Afaik that makes it `archs="i686* x86_64*"`

**Comment by ericonr** [comment]
It's similar to https://github.com/ftilde/unsegen_terminal/issues/1 , not sure how accepting it into the repo will work.

**Comment by cinerea0** [comment]
> Afaik that makes it archs="i686* x86_64*"

Fixed in the most recent push. Also, I opened [an issue in dijo about the failure to compile on ARM](https://github.com/NerdyPepper/dijo/issues/63).

**Comment by ericonr** [comment]
As a general rule, you don't want to use such impositive language. Instaed, suggest a solution, ask what they think, potentially offer to do some of the necessary work if they need it ;)

**Comment by cinerea0** [comment]
Sorry about that, I'm used to writing in a very indirect manner. I've updated the template to use version 0.2.3, and the Travis builds show that it compiles on all architectures.

**Comment by ericonr** [comment]
Heh, it happens. That's great! Have you tried using it too?

**Comment by cinerea0** [comment]
Yes, I've used dijo for a couple weeks prior to this PR. The package provides the same functionality as installing the program from cargo. Granted, my test only applies to x86_64-glibc systems, but I hope that's enough.

**Pull request merged**
