### PR TITLE
Htop: enable sensors support

### PR DESCRIPTION
**Pull request by Mek101**
Enables optional sensors support via `libsensors`, see https://github.com/htop-dev/htop/issues/358

From what I've been able to gather, the `libsensors` lib is linked in only at [runtime](https://github.com/htop-dev/htop/blob/master/linux/LibSensors.c), therefore the temperature sensors will be enabled only in systems with `libsensors` and cause no issue on systems without.

### CODE REVIEW

**Comment by Mek101** [comment]
Why immidiate closure?

**Comment by the-maldridge** [comment]
Because it was merged?

**Comment by Mek101** [comment]
I checked the recent commits and I confirm the merge, however here it says "Closed with unmerged commits": and now I'm just confused

**Comment by Duncaen** [comment]
This shouldn't have been merged, the commit message is wrong, it does not increase the revision resulting in no rebuild.
From the CI build logs its clear that the commit actually does not enable this feature, meaning you did not test it.
```
checking sensors/sensors.h usability... no
checking sensors/sensors.h presence... no
checking for sensors/sensors.h... no
```

**Pull request closed without merging**
