### PR TITLE
prosody: update to 0.11.2

### PR DESCRIPTION
**Pull request by ndowens**

### CODE REVIEW

**Comment by Duncaen** [comment]
Did you test it or just updated the version?

**Comment by ndowens** [comment]
It seems to run but I am not able to  connect though I think it is a configure error on my part. Will try again when I’m not at work

**Comment by jnbr** [comment]
works for me

**Comment by ndowens** [comment]
Thanks I tried to but couldn’t get it setup correctly

**Comment by maxice8** [comment]
Please rebase

**Comment by ndowens** [comment]
Done

**Comment by jnbr** [comment]
Please do not update software which provides infrastructure without prior testing.

Since version 0.11.0 lua52 is recommended: https://prosody.im/doc/release/0.11.0#lua-5.2

**Comment by ndowens** [comment]
Reading that, seems 5.1 is still supported, as the 0.11.x series will be the last to support Lua 5.1, unless I am mistaken?

**Comment by jnbr** [comment]
yes, 5.1 is still supported but on the way to be deprecated. I'm not familiar enough with lua to tell if there is any reason to stay with 5.1.

**Pull request merged**
