### PR TITLE
pango: update to 1.44.7.

### PR DESCRIPTION
**Pull request by xtraeme**
Removed `gir` build option, now that cross compilation works we ship defaults (enabled).

### CODE REVIEW

**Comment by ndowens** [comment]
Looks it can’t find the manpage to install on cross

**Comment by D-Nice** [comment]
this update breaks a bunch of apps (rofi, dunst so far from what I've noticed) for me. It replaces all text with unknown character codes. Downgrading to `pango-1.42.4_5` alleviates the issue.

What I'm referring to as unkown char codes is what's seen here: https://github.com/davatorium/rofi/issues/977#issuecomment-501898657

except it occurs with every character.

**Comment by NeelChotai** [comment]
@D-Nice seems to be related to [Pango 1.44 dropping support for bitmap fonts](https://www.phoronix.com/scan.php?page=news_item&px=Pango-No-More-Bitmap-Fonts), converting the BDFs to OTF/TTF should fix this too.

Seems like an odd decision but the issue has since been [closed](https://gitlab.gnome.org/GNOME/pango/issues/386).

**Comment by D-Nice** [comment]
@NeelChotai appreciate you linking that info, I was unaware, and presumed it is likely a bug in the package, since that is a major breaking change imo, and only a minor version change...

I've had time to read more through all this, and aside from completely dropping true bitmap fonts, it also seems to cause various spacing and hinting issues even with supposedly supported fonts, with pango pointing at harfbuzz being the culprit and harfbuzz vice versa...

I'm biased as I use bitmap fonts, and will not switch to non-bitmap, but would request reverting this, at the very least until pango is working properly with the supposedly supported fonts. There's other users running into these issues as well ofc... https://www.reddit.com/r/voidlinux/comments/cr9ovo/issues_with_font/

A fair compromise may be creating a pango-bitmap pkg targetting 1.43 pango, akin to how fontawesome has multiple pkgs due to similar breakages.

**Comment by D-Nice** [comment]
Little guide for anyone loving their bitmap fonts and wanting to stick with them:

Install xtools if you don't have it already
`sudo xbps-install -S xtools`

Downgrade to the latest 1.42 version of pango in your cache
`sudo xdowngrade /var/cache/xbps/$(ls /var/cache/xbps/ | grep -P pango-1.42.+xbps$ | tail -1)`

And to finally ignore updates to pango until there is a resolution
`sudo xbps-pkgdb -m hold pango`

**Comment by jfriesse** [comment]
Filled an issue https://github.com/void-linux/void-packages/issues/17595, because I think locking package is not a really solution.

**Pull request merged**
