### PR TITLE
picom: update to 12.4.

### PR DESCRIPTION
**Pull request by pondichys**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64
  - armv7l
  - i686
  - x86_64-musl

### CODE REVIEW

**Comment by classabbyamp** [comment]
cc maintainer @0x5c

it's kinda rude to PR an update to an actively maintained package when it's been available for less than a few days

**Comment by pondichys** [comment]
Aaah sorry my bad
Will pay more attention next time

**Comment by 0x5c** [comment]
Especially since this version only brings a minor performance improvement and a patch we already have

**Comment by pondichys** [comment]
While I do understand your point and take note of the criticism, I assure you I was simply a bit too enthousiast on that one and only wanted to bring back my contribution to the community. No pun intended and no bad intention from my part.
I've learned the lesson though. Thanks for the work you do but know that your reaction was also rude to me. Personal beings here. Both side of the discussion. Anyway no hard feelings I hope.

**Pull request closed without merging**
