### PR TITLE
zfs: update to 2.1.2.

### PR DESCRIPTION
**Pull request by zdykstra**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by zdykstra** [comment]
`python310.patch` was dropped due to [zfs#12636](https://github.com/openzfs/zfs/pull/12636)

**Comment by zdykstra** [comment]
Ping @Vaelatern @ahesford

**Comment by ericonr** [comment]
Test failures on musl are because `SEEK_DATA` and `SEEK_HOLE` are defined in glibc headers, but not in musl ones. The values can be had from `<linux/fs.h>`, but that header brings in a lot of cruft too, idk if it's acceptable for upstream. If musl accepts the constants, we can just use that instead.

**Comment by Vaelatern** [comment]
This is very brand new, only 2 hours. We prefer to wait at least a few days, so I'll ask that we put this on pause to see if upstream fixes musl.

My zfs-on-root machine is in fact a musl box, so the musl failures obviously are relevant to me :)

**Comment by zdykstra** [comment]
> This is very brand new, only 2 hours. We prefer to wait at least a few days, so I'll ask that we put this on pause to see if upstream fixes musl.
> 
> My zfs-on-root machine is in fact a musl box, so the musl failures obviously are relevant to me :)

Yup, just getting the ball rolling. I'm dog-fooding it locally because I live the YOLO lifestyle.

**Comment by ericonr** [comment]
@Vaelatern fwiw this isn't inhibiting functionality, it's just a test for the mmap issues they had with file seeking. Disabling or fixing the tests should be equivalent, given that almost no one runs them :P 

I'm looking into the musl side to see if we can define the constants, otherwise I can open an issue with ZFS upstream.

**Comment by ericonr** [comment]
https://inbox.vuxu.org/musl/20211217075943.2167-1-ericonr@disroot.org/T/#u

**Comment by ahesford** [comment]
Even if the musl patch is accepted, the patch would need to be backported to our version indefinitely. Would it be better just to patch the tests here (or disable them)?

Maybe defining these constants in make_build_args is sufficient...

**Comment by ericonr** [comment]
Fwiw the patch is likely to be accepted, from IRC discussion.

I'm okay with backporting, and we can remove it when updating musl.

**Comment by zdykstra** [comment]
I've pulled in https://github.com/openzfs/zfs/pull/12891 - upstreams patch-of-choice for the `musl` build issue.

**Comment by ericonr** [comment]
LGTM, I can install on musl and reboot to test things.

**Comment by Vaelatern** [comment]
not opposed to backporting the zfs musl patch to fix this.

**Comment by ericonr** [comment]
Tested and seems to be working fine here.

Thanks for the update!

**Pull request merged**
