### PR TITLE
node_exporter: Send output to syslog.

### PR DESCRIPTION
**Pull request by raindev**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (x86_64, GNU libc)
- [ ] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [ ] aarch64-musl
  - [ ] armv7l
  - [ ] armv6l-musl

### CODE REVIEW

**Comment by raindev** [comment]
Is anything else needed to get the changes merged?

**Comment by Duncaen** [comment]
`logger(1)` is bad as it just sends logs to the void if the first time it tries to connect to the syslog socket fails. This should use `vlogger(1)`.

**Comment by raindev** [comment]
Thanks for the feedback Duncan. Have I missed this preference for `vlogger` over `logger` documented somewhere I missed?

**Comment by raindev** [comment]
Just wanted to follow up on getting the changes in.

**Comment by raindev** [comment]
Thank you Duncan!

**Pull request merged**
