### PR TITLE
firefox: disable telemetry

### PR DESCRIPTION
**Pull request by teldra**

### CODE REVIEW

**Comment by jnbr** [comment]
Firefox is too big to be built by travis ci, I canceled the job.

According to the [docs](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/internals/preferences.html), `MOZ_TELEMETRY_REPORTING` must be defined to enable telemtry. We don't define it so it should be off already. In `about:preferences#privacy`
I see `Data reporting is disabled for this build configuration`.

Is there anything, besides the setting you changed, that makes you think telemetry is enabled in our builds?

**Comment by teldra** [comment]
toolkit.telemetry.enabled in about:config is true and locked.

**Comment by jnbr** [comment]
I get that. But I have reasons to believe that this has no effect on our build (see my first answer). Hence the question:

> Is there anything, besides the setting you changed, that makes you think telemetry is enabled in our builds?

**Comment by teldra** [comment]
No, besides the changed setting, there is nothing I think that it is enabled.

**Comment by teldra** [comment]
Err, this https://github.com/void-linux/void-packages/issues/11493

**Comment by Duncaen** [comment]
Telemetry is disabled and this config flag doesn't even disable it. It controls whether it sends a extensive telemetry (which is enabled only for pre-release channels if firefox is build with telemetry enabled).

**Pull request closed without merging**
