### PR TITLE
voidlinux.eu -> voidlinux.org

### PR DESCRIPTION
**Pull request by fosslinux**
Where applicable, this pull request changes voidlinux.eu to voidlinux.org, as per the news item posted recently. This was got from a search for voidlinux.eu and going through that. Emails were not changed (has that infrastructure been migrated yet)?

HTH.

### CODE REVIEW

**Comment by maxice8** [comment]
1. revbump packages with non-cosmetic changes
2. Packages that have "Christian Neukirchen" as maintainer= should be changed to "Leah Neukirchen <leah@vuxu.org>"
3. I don't see a point in changing for build logs since they are redirected
4. There are changes that conflict with https://github.com/void-linux/void-packages/pull/2305, change so it doesn't

**Comment by fosslinux** [comment]
1, 2, 4: ok sure.
3. Yes but voidlinux.eu is not guaranteed to work in the future.

**Comment by Vaelatern** [comment]
5. Maybe format commit messages with $pkgname: instead of $pkgname

@the-maldridge do we want to make alpha.de.voidlinux.org the new repo.voidlinux.eu? I'm sure the question of "how far is auto.voidlinux.org" is an annoying one.

**Comment by the-maldridge** [comment]
Yes, I'd also point out that https://github.com/void-linux/void-packages/pull/2305 is already open and should be merged first changing just the mirrors since we may need to revert it quickly. This should sit on top of that to change the non-functional stuff.

The answer to how far away is 'auto.voidlinux.org'  is just as annoying as you might expect: after dxpb.

**Comment by Vaelatern** [comment]
Ah. After dxpb is a plenty annoying timeline. @fosslinux do you write any C?

**Comment by fosslinux** [comment]
@Vaelatern a little bit, I have general knowledge of C and a bit on OOP and pointers, etc.

**Comment by Vaelatern** [comment]
@fosslinux https://gitlab.com/dxpb/dxpb

**Comment by fosslinux** [comment]
@Vaelatern ... right ... so why is that relevant to this pull request?

**Comment by the-maldridge** [comment]
All the commits starting with "revert" need to be dropped.

**Comment by fosslinux** [comment]
@the-maldridge uh... why? those changes fix the conflicts with #2305

**Comment by the-maldridge** [comment]
Yes, you should drop those changes and the original commits that caused the conflict.  You need to rebase this on top of that change, or wait until that change is pushed and then rebase on top of master.

**Comment by fosslinux** [comment]
@the-maldridge @Vaelatern @maxice8 This pull request has turned into a mess due to my inexperience with Void Linux contributing and git. I will close this, wait for #2305 to be merged and then make a new, clean, pull request adhering to what @maxice8 wanted.

**Pull request closed without merging**
