### PR TITLE
Update Rust toolchain to 1.60.0

### PR DESCRIPTION
**Pull request by subnut**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-musl)

### CODE REVIEW

**Comment by subnut** [comment]
Hey @q66, the following packages need to be built _"unofficially"_ -
```
cargo-1.59.0-ppc64le-unknown-linux-gnu.tar.xz
cargo-1.59.0-ppc64le-unknown-linux-musl.tar.xz
cargo-1.59.0-ppc64-unknown-linux-gnu.tar.xz
cargo-1.59.0-ppc-unknown-linux-gnu.tar.xz
rustc-1.59.0-ppc64le-unknown-linux-gnu.tar.xz
rustc-1.59.0-ppc64le-unknown-linux-musl.tar.xz
rustc-1.59.0-ppc64-unknown-linux-gnu.tar.xz
rustc-1.59.0-ppc-unknown-linux-gnu.tar.xz
rust-std-1.59.0-ppc64le-unknown-linux-gnu.tar.xz
rust-std-1.59.0-ppc64le-unknown-linux-musl.tar.xz
rust-std-1.59.0-ppc64-unknown-linux-gnu.tar.xz
rust-std-1.59.0-ppc-unknown-linux-gnu.tar.xz
```
After you've done your magic and uploaded them to `alpha.de.repo.voidlinux.org`, please paste the checksums here (in a comment), and I will update them in the templates.

**Comment by subnut** [comment]
@q66 Just wanted to ping you that the above list for packages that need unofficial building has been reduced.

**Comment by subnut** [comment]
Also, I haven't changed `make_check` because two tests are failing

Here are the commands that are failing, if anybody is interested -
- This one fails with "**error: the option \`Z\` is only accepted on the nightly compiler**" -
  ```
  "/builddir/rustc-1.59.0-src/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/builddir/rustc-1.59.0-src/build/x86_64-unknown-linux-gnu/stage1/lib" "--run-lib-path" "/builddir/rustc-1.59.0-src/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/builddir/rustc-1.59.0-src/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "--src-base" "/builddir/rustc-1.59.0-src/src/test/ui" "--build-base" "/builddir/rustc-1.59.0-src/build/x86_64-unknown-linux-gnu/test/ui" "--stage-id" "stage1-x86_64-unknown-linux-gnu" "--suite" "ui" "--mode" "ui" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/bin/FileCheck" "--linker" "cc" "--host-rustcflags" "-Crpath -O -Cdebuginfo=0  -Lnative=/builddir/rustc-1.59.0-src/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--target-rustcflags" "-Crpath -O -Cdebuginfo=0  -Lnative=/builddir/rustc-1.59.0-src/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python3" "--lldb-python" "/usr/bin/python3" "--llvm-version" "12.0.1" "--llvm-components" "aarch64 aarch64asmparser aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils aggressiveinstcombine all all-targets amdgpu amdgpuasmparser amdgpucodegen amdgpudesc amdgpudisassembler amdgpuinfo amdgpuutils analysis arm armasmparser armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter avr avrasmparser avrcodegen avrdesc avrdisassembler avrinfo binaryformat bitreader bitstreamreader bitwriter bpf bpfasmparser bpfcodegen bpfdesc bpfdisassembler bpfinfo cfguard codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfogsym debuginfomsf debuginfopdb demangle dlltooldriver dwarflinker engine executionengine extensions filecheck frontendopenacc frontendopenmp fuzzmutate globalisel hellonew hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo instcombine instrumentation interfacestub interpreter ipo irreader jitlink lanai lanaiasmparser lanaicodegen lanaidesc lanaidisassembler lanaiinfo libdriver lineeditor linker lto mc mca mcdisassembler mcjit mcparser mips mipsasmparser mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmparser msp430codegen msp430desc msp430disassembler msp430info native nativecodegen nvptx nvptxcodegen nvptxdesc nvptxinfo objcarcopts object objectyaml option orcjit orcshared orctargetprocess passes powerpc powerpcasmparser powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata remarks riscv riscvasmparser riscvcodegen riscvdesc riscvdisassembler riscvinfo runtimedyld scalaropts selectiondag sparc sparcasmparser sparccodegen sparcdesc sparcdisassembler sparcinfo support symbolize systemz systemzasmparser systemzcodegen systemzdesc systemzdisassembler systemzinfo tablegen target textapi transformutils vectorize webassembly webassemblyasmparser webassemblycodegen webassemblydesc webassemblydisassembler webassemblyinfo windowsmanifest x86 x86asmparser x86codegen x86desc x86disassembler x86info xcore xcorecodegen xcoredesc xcoredisassembler xcoreinfo xray" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--channel" "stable"
  ```
- This one fails with "**Error: cannot match crt-static**"
  ```
  "/builddir/rustc-1.59.0-src/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/builddir/rustc-1.59.0-src/build/x86_64-unknown-linux-gnu/stage1/lib" "--run-lib-path" "/builddir/rustc-1.59.0-src/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/builddir/rustc-1.59.0-src/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "--rustdoc-path" "/builddir/rustc-1.59.0-src/build/x86_64-unknown-linux-gnu/stage1/bin/rustdoc" "--rust-demangler-path" "/builddir/rustc-1.59.0-src/build/x86_64-unknown-linux-gnu/stage1-tools-bin/rust-demangler" "--src-base" "/builddir/rustc-1.59.0-src/src/test/run-make-fulldeps" "--build-base" "/builddir/rustc-1.59.0-src/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps" "--stage-id" "stage1-x86_64-unknown-linux-gnu" "--suite" "run-make-fulldeps" "--mode" "run-make" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/bin/FileCheck" "--linker" "cc" "--host-rustcflags" "-Crpath -O -Cdebuginfo=0  -Lnative=/builddir/rustc-1.59.0-src/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--target-rustcflags" "-Crpath -O -Cdebuginfo=0  -Lnative=/builddir/rustc-1.59.0-src/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python3" "--lldb-python" "/usr/bin/python3" "--llvm-version" "12.0.1" "--llvm-components" "aarch64 aarch64asmparser aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils aggressiveinstcombine all all-targets amdgpu amdgpuasmparser amdgpucodegen amdgpudesc amdgpudisassembler amdgpuinfo amdgpuutils analysis arm armasmparser armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter avr avrasmparser avrcodegen avrdesc avrdisassembler avrinfo binaryformat bitreader bitstreamreader bitwriter bpf bpfasmparser bpfcodegen bpfdesc bpfdisassembler bpfinfo cfguard codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfogsym debuginfomsf debuginfopdb demangle dlltooldriver dwarflinker engine executionengine extensions filecheck frontendopenacc frontendopenmp fuzzmutate globalisel hellonew hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo instcombine instrumentation interfacestub interpreter ipo irreader jitlink lanai lanaiasmparser lanaicodegen lanaidesc lanaidisassembler lanaiinfo libdriver lineeditor linker lto mc mca mcdisassembler mcjit mcparser mips mipsasmparser mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmparser msp430codegen msp430desc msp430disassembler msp430info native nativecodegen nvptx nvptxcodegen nvptxdesc nvptxinfo objcarcopts object objectyaml option orcjit orcshared orctargetprocess passes powerpc powerpcasmparser powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata remarks riscv riscvasmparser riscvcodegen riscvdesc riscvdisassembler riscvinfo runtimedyld scalaropts selectiondag sparc sparcasmparser sparccodegen sparcdesc sparcdisassembler sparcinfo support symbolize systemz systemzasmparser systemzcodegen systemzdesc systemzdisassembler systemzinfo tablegen target textapi transformutils vectorize webassembly webassemblyasmparser webassemblycodegen webassemblydesc webassemblydisassembler webassemblyinfo windowsmanifest x86 x86asmparser x86codegen x86desc x86disassembler x86info xcore xcorecodegen xcoredesc xcoredisassembler xcoreinfo xray" "--system-llvm" "--llvm-bin-dir" "/usr/bin" "--cc" "cc" "--cxx" "g++" "--cflags" "-ffunction-sections -fdata-sections -fPIC -m64 -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -pipe -fdebug-prefix-map=/builddir/rustc-1.59.0-src=." "--ar" "ar" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--channel" "stable"
  ```

**Comment by subnut** [comment]
I don't know how to fix the tests, so anybody willing to help is welcome.

Else, we can keep it as-is (`make_check=no`).

**Comment by subnut** [comment]
@q66 Just wanted to ask if you are working on the powerpc64le bootstrap packages :)

**Comment by subnut** [comment]
Pinging @q66 for review

**Comment by q66** [comment]
update this to 0.60

**Comment by subnut** [comment]
@q66 Done.

**Comment by subnut** [comment]
Mistakenly closed.

**Comment by tranzystorek-io** [comment]
Is any help needed with this PR, apart from the tests?

**Comment by cinerea0** [comment]
1.61.0 has just been released today.

**Comment by subnut** [comment]
@cinerea0 Sorry, I don't have enough time nowadays to keep this PR updated. Someone else will have to pick it up.

**Comment by tranzystorek-io** [comment]
I wanted to take a stab at this, but I'm not sure where to look for patches, I'd appreciate some pointers 😄

**Comment by subnut** [comment]
@tranzystorek-io Try building it with the patches included in this PR.  
If it doesn't build, try determining which file/module is failing.

More patches can be found in the repos of other distros, like
- Alpine Linux - https://git.alpinelinux.org/aports/tree/community/rust
- Chimera linux - https://github.com/chimera-linux/cports/tree/master/main/rust/patches

etc.

Avoid my mistake - **DO NOT PATCH BLINDLY**

Good luck :slightly_smiling_face:

**Pull request closed without merging**
