### PR TITLE
imlib2: update to 1.8.0.

### LINKED ISSUE #27597: Package request: imlib2-heic
https://github.com/vi/imlib2-heic

Loader for HEIC for Imlib2 (i.e. for Feh). Based on libheif.

### PR DESCRIPTION
**Pull request by tibequadorian**
imlib2 contains a HEIF loader since 1.8.0
- closes #27814
- closes #27597 

#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by tibequadorian** [comment]
I'm willing to take over maintainership.

**Comment by q66** [comment]
we have build options for things that make sense, this does not

**Comment by tibequadorian** [comment]
> we have build options for things that make sense, this does not

does everyone agree?

https://github.com/void-linux/void-packages/blob/master/srcpkgs/emacs/template

**Comment by q66** [comment]
that's been that way since 2013 and nobody bothered to change it https://github.com/void-linux/void-packages/commit/62fbe8ca051be8d960e4cf9dd57b9cf8678e8f35

void is not gentoo, we don't put build options in places unless they are either 1) required (e.g. a feature not building for cross-compiling) or 2) provide a thing that should be off by default but people might have a use for anyway or 3) there some other really good reason to have it

**Comment by q66** [comment]
(notably, "it introduces a dependency on a runtime library" is not considered a "really good reason" in general, since if it was the number of build options around the place would explode and the maintenance effort and number of unnecessary bug reports would inevitably go up)

**Pull request merged**
