### PR TITLE
Cataclysm-DDA: update to 0.D.

### PR DESCRIPTION
**Pull request by Johnnynator**

### CODE REVIEW

**Comment by pltrz** [comment]
Crashes for me.

Same error for `cataclysm` and `cataclysm-tiles`

```
$ cataclysm
Failed to read from "data/names/en.json": opening file failed
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: /home/pltrz/.cataclysm-dda/config/crash.log
VERSION: NULL
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:

        /bin/cataclysm(_Z21debug_write_backtraceRSo+0x38) [0x55d6f8044598]
        /bin/cataclysm(+0x3cdad2) [0x55d6f8042ad2]
        /bin/cataclysm(+0x3cdf38) [0x55d6f8042f38]
        /usr/lib/libc.so.6(+0x3a410) [0x7f9dd01c2410]
        /usr/lib/libc.so.6(gsignal+0x10b) [0x7f9dd01c238b]
        /usr/lib/libc.so.6(abort+0x121) [0x7f9dd01ad535]
        /bin/cataclysm(+0x256406) [0x55d6f7ecb406]
        /bin/cataclysm(_Z12realDebugmsgIJPKcS1_EEvS1_S1_S1_S1_DpOT_+0x32e) [0x55d6f810d2ae]
        /bin/cataclysm(+0x32fc62) [0x55d6f7fa4c62]
        /bin/cataclysm(_Z19read_from_file_jsonRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt8functionIFvR6JsonInEE+0x3d) [0x55d6f89da76d]
        /bin/cataclysm(_ZN4Name14load_from_fileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x44) [0x55d6f8c03304]
        /bin/cataclysm(_Z12set_languagev+0x3b2) [0x55d6f87fc7b2]
        /bin/cataclysm(main+0xaf5) [0x55d6f7fd2cf5]
        /usr/lib/libc.so.6(__libc_start_main+0xeb) [0x7f9dd01aeb6b]
        /bin/cataclysm(_start+0x2a) [0x55d6f802cf3a]

        Attempting to repeat stack trace using debug symbols...
        sh: 1: addr2line: not found
        backtrace: addr2line failed
```

And on another note we should strongly consider adding the `USE_XDG_DIR=1` flag to the defaults, and I think the backtrace flag is useful for debugging, but shouldn't be the default for users.

**Comment by Johnnynator** [comment]
`USE_XDG_DIR=1` is not a flag that can be passed to cmake and their `Makefile` was way to broken for our use case.
Also pls open an Issue instead of commenting on an already merged PR.

**Comment by Johnnynator** [comment]
Also the backtrace flag on is default for cataclysm-dda, I only disabled it for musl.

**Comment by Johnnynator** [comment]
@pltrz I pushed an update to the repo, it should work fine now.

**Pull request merged**
