### PR TITLE
iwd: update to 0.3.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by Johnnynator** [comment]
You can remove also the remaining part of the musl patch. I resolved that issue differently in the patch I sent to upstream.

**Comment by maxice8** [comment]
> You can remove also the remaining part of the musl patch. I resolved that issue differently in the patch I sent to upstream.

i removed the whole patch but it still failed on aarch64-musl, did they commit after releasing the 0.3 version ?

**Comment by Johnnynator** [comment]
The commits got added like a month ago. The aarch64-musl compilation error look more a conflict of the kernel headers with the musl libc on aarch64.

**Comment by maxice8** [comment]
On Fri, Jun 15, 2018 at 01:43:38PM -0700, John Zimmermann wrote:
> The commits got added like a month ago. The aarch64-musl compilation error look more a conflict of the kernel headers with the musl libc on aarch64.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/6#issuecomment-397736852

also happened on x86_64-musl

**Comment by Johnnynator** [comment]
It compiles fine for me on x86_64-musl.

**Comment by maxice8** [comment]
On Fri, Jun 15, 2018 at 01:47:48PM -0700, John Zimmermann wrote:
> It compiles fine for me on x86_64-musl.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/6#issuecomment-397737843

works on native compilation, fails on cross.

oh well *shrugs*

**Comment by Johnnynator** [comment]
I can take a look at it tomorrow. `kernel-libc-headers` probably just needs additional patching  for arm.

**Comment by Johnnynator** [comment]
Ok. The reason that the musl cross build fail is that they do not use the `kernel-libc-headers` package but the `cross-$arch-linux-musl` packages. I'm rebuilding `cross-aarch64-linux-musl` locally now. Will report back later.

**Comment by maxice8** [comment]
cross still failing for me

**Comment by Johnnynator** [comment]
@maxice8 have you run `bootstrap-update`? (Or just `zap` and `binary-bootstrap` idk how xbps-src handles updates of cross packages)

**Pull request merged**
