### PR TITLE
Signal-Desktop: update to 5.6.2.

### PR DESCRIPTION
**Pull request by reedts**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ScrelliCopter** [comment]
Works for me :)
Please squash your second commit into your first and rebase on master.

**Comment by reedts** [comment]
@ScrelliCopter Done :)!

**Comment by Veganizer** [comment]
Can you bump version from 5.4.1 to 5.6.2 maybe? :-)

**Comment by ericonr** [comment]
There is a failing patch, probably because of the change to default patching args. Please fix :)

**Comment by reedts** [comment]
@Veganizer @ericonr Bumped version to 5.6.2, fixed patch and rebased to current master

**Comment by ScrelliCopter** [comment]
Builds & runs on my end. Don't forget to update the version in the PR title.

**Pull request merged**
