### PR TITLE
sway: updated to 1.4. wlroots: updated to 0.10.0. wlroots-devel: updated to 0.10.0. wayfire: update to 0.3.1.

### PR DESCRIPTION
**Pull request by leonardlorenz**
This updates the sway package and the necessary dependencies (wlroots, wlroots-devel).

### CODE REVIEW

**Comment by leonardlorenz** [comment]
Removed some commits which weren't related.

**Comment by Johnnynator** [comment]
Pls split this into one commit per package. Also since the soname of wlroots changed, you need to bump the revision of other packages that link against it so they get rebuild (`cage` and `wayfire`)

**Comment by damneq** [comment]
Isn't this a duplicate of #18432 ?

**Comment by leonardlorenz** [comment]
It seems like it is. A more descriptive title for the other pull request would've helped. I'll close this since #18432 already has more atomic commits than mine.

**Pull request closed without merging**
