### PR TITLE
[NOMERGE] alsa-ucm-conf: update to 1.2.5.1

### PR DESCRIPTION
**Pull request by cinerea0**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
I think it'd be best to get some testing before merging, right?

**Comment by cinerea0** [comment]
@ericonr This commit just updates a few configuration files, but if you think so, sure. I can confirm that the new version provided by this commit works on my comet lake system.

**Comment by ericonr** [comment]
Right, but it can affect audio so I want people to have the opportunity to complain a bit before I merge.

**Comment by cinerea0** [comment]
Yeah, that makes sense. Any potential candidates for testing come to mind?

**Comment by cinerea0** [comment]
I just thought to check for my microphone, and it turns out this update breaks it. I'm closing this PR now and I'll be filing an issue upstream.

**Comment by ericonr** [comment]
Can you reopen and leave as nomerge? That way people searching for it will know not to update... I did similar for #31286

**Comment by cinerea0** [comment]
Sure thing.

**Pull request merged**
