### PR TITLE
New package: iridium-browser-2019.04.73

### PR DESCRIPTION
**Pull request by austinriddell**
Iridium is a Chromium based web browser with a focus on privacy. May be nice for people who like Chromium/Chrome without Google!

### CODE REVIEW

**Comment by Chocimier** [comment]
See #7562.

**Comment by austinriddell** [comment]
@Chocimier Thank you for letting me know! So just to clarify it's because of the release cycle per #7562? Just wondering since I was using Falkon before which uses the same major version of Chromium (73.0) and seems to have even longer release cycles (2+ months between 3.0.0-3.0.1 and 9+ months between 3.0.1 and 3.1.0).

Also from looking a little further it seems that the recommendation to avoid Google is Firefox (#10664) which kind of creeps me out because of the `about:mozilla` page that remains even in forks.

Also also thank you for your quick response!

**Comment by Johnnynator** [comment]
Falkon uses qt5-webengine, which is needed as a dependency by quite a few packages (~30+) and therefore is more or less required to be packaged. So Falkons release cycle has nothing to do with how up to date the used chromium version in it is.

**Comment by austinriddell** [comment]
Okay got it! Thank you so much!!

**Pull request closed without merging**
