### PR TITLE
New package: symlinks-1.4.3

### PR DESCRIPTION
**Pull request by Logarithmus**

### CODE REVIEW

**Comment by Anachron** [comment]
Whats dwl and why is it included in this PR?

**Comment by Logarithmus** [comment]
@Anachron sorry, it was my mistake, `dwl` is `dwm` fork for Wayland. I work on it in another branch and accidentally added it to this one

**Comment by ericonr** [comment]
This application hasn't been updated in a few years and it's a single C file... I'm not sure it's worth turning it into a package that we have to carry :/ 

Could be convinced otherwise.

**Comment by Logarithmus** [comment]
@ericonr what's wrong with the program being contained in a single C file? It's even better: almost instant builds, no extra load on the build server.
`symlinks` is very useful in tandem with `rdfind`. `rdfind` can be used to recursively search for duplicate files (based on size & hashsum) insie directory and then replace them with symlinks. The thing is that `rdfind` sometimes create absolute symlinks instead of relative ones, which prevents you from sharing this directory with someone else. `symlinks` can correct such symlinks, as well as remove broken ones if you want so.
IMO, it's always better to install a package than manually run `make && sudo make install`. Your system will be quickly filled with garbage left from partially uninstalled software. That's what package managers were created for.

**Comment by Piraty** [comment]
burden on the repo is low

**Pull request merged**
