### PR TITLE
firefox: fix sandbox for fcntl

### LINKED ISSUE #26639: firefox 83.0 won't load pages on aarch64-musl
### System

* xuname:  
  `Void 5.7.0_1 aarch64-musl Unknown uptodate hold rrFFFFF`
* package:  
  `firefox-83.0_1`

### Expected behavior

```
$ firefox 'http://example.com'
```
example.com loads

### Actual behavior

```
$ firefox 'http://example.com'
```
white screen, loading icon never goes away

### Steps to reproduce the behavior

I uninstalled all my extensions; the behavior was unchanged. I created a new profile; even the "Welcome to Firefox" page that opens on first launch did not load.

### PR DESCRIPTION
**Pull request by jnbr**
fixes #26639 

[ci skip]

### CODE REVIEW

**Comment by q66** [comment]
this is not entirely correct, as the value is not `0100000` on all platforms

the block should look like this:

```
#if defined(__x86_64__) || defined(__i386__) || defined(__mips__)
#define O_LARGEFILE_REAL 0100000
#elif defined(__powerpc__)
#define O_LARGEFILE_REAL 0200000
#else
#define O_LARGEFILE_REAL O_LARGEFILE
#endif
```

**Comment by jnbr** [comment]
Thanks, updated.

**Comment by pullmoll** [comment]
This same patch applies and is certainly required for `firexfox-esr` and thus also `icecat` as well.
I'll add it and push the updates once the builders are done with `firefox`.

**Comment by jnbr** [comment]
Good point. Same for thunderbird.

**Comment by q66** [comment]
why would it be required? these are all ESR, i.e. 78, and the patch was not needed until 83 (I have 82 still running on aarch64 with no issues)

**Comment by jnbr** [comment]
In general, it is mostly a problem on musl because musl passes O_NONBLOCK to fcntl().
On glibc, this is (usually?) not the case, so the bug won't be triggered there.
Only because the bug was not triggered as reliable before doesn't mean it's not there.
Patching the esr versions won't hurt, not sure if we need rebuilds, we could also do it with the next round of minor bumps

**Comment by q66** [comment]
let's add the patch (for correctness) in the esr stuff, but i don't think there are issues with 78.x on aarch64 (even musl, iirc i tested it a while back), so we don't need to bump

**Pull request merged**
