### PR TITLE
RFC: common/build-style/cargo.sh: use --locked for build and check as well

### PR DESCRIPTION
**Pull request by jcgruenhage**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by jcgruenhage** [comment]
We don't handle that at all yet. We're building rust packages with [`cargo auditable`](https://github.com/rust-secure-code/cargo-auditable) to get some visibility on such issues, so that we can detect rustsec issues from a running system and not only at build time, but we don't have a clear process for monitoring this yet.

With regards to patching the Cargo.lock file: We current patch that file in 19 packages, but we don't do that by manually patching in the lockfile, we do that by running `cargo update --package <package we're updating>@<version we're updating from> --precise <version we're updating to>`. This has the slight disadvantage of not including a checksum, but crates.io does not allow changing versions so it's not a big drawback, but at the same time it's way easier to handle than Cargo.lock diffs.

**Comment by icp1994** [comment]
Another tangent: is it worth adding a `make_build_args` to the command under `do_build()`? There's been at least a few times where I wanted to add `--package <spec>` for cargo build but putting it in `configure_args` breaks `do_install` since cargo install doesn't accept that option.

**Comment by jcgruenhage** [comment]
@icp1994 what good is building only a specific package in the build phase?

**Comment by icp1994** [comment]
Some packages have quite a few things under their `crates/` (workspace) for easier dev setup, for example benchamrks. But we don't need to build those for packaging. I mean we can but it's a lot of extra compile time for maintainers.

**Comment by classabbyamp** [comment]
I think this is good to do

**Comment by jcgruenhage** [comment]
@icp1994 wouldn't it be possible to use `build_wrksrc` for that usecase? Aside of that, yeah, for `cargo install` limiting is done with `--path`, where `cargo build` takes `--package`, agreed that separate arg vars might be useful.

**Comment by jcgruenhage** [comment]
But aside of these two tangents, I think this is good to go as well.

**Comment by classabbyamp** [comment]
i'm interested in merging this if CI is fixed

**Comment by jcgruenhage** [comment]
As I mentioned on IRC: I don't really get why/how ugdb is broken now vs how it was before, so I'm inneed of some assistance here. @leahneukirchen , you fixed that the last time, right?

**Comment by classabbyamp** [comment]
> I don't really get why/how ugdb is broken now vs how it was before

the patch adds `ndarray = "0.15.4"`, so I think just restoring that patch is the way to do it

**Comment by jcgruenhage** [comment]
I don't see how that changes anything tbqh. After doing so, `Cargo.lock` contains 4 references to ndarray:
 - Definition of `ndarray@0.8.4`, this is what was in the dependency tree previously
 - Definition of `ndarray@0.15.6`, which we've just added
 - Dependency from `ugdb` to `ndarray@0.15.6`
 - Dependency from `unsegen` to `ndarray@0.8.4`
 
 Aside of that, there's also not much else changing here. I've committed that now to check, but I don't think it'll do anything.

**Comment by jcgruenhage** [comment]
Okay, now that's interesting: I've built both variants locally, and adding the `ndarray` dep does indeed fix it, but I really, really, really don't understand how.

**Comment by jcgruenhage** [comment]
Okay, I've dug a bit deeper, and I now do understand why adding `ndarray` makes it compile. Adding `ndarray` enables the `i128` feature on `num-traits`, which enables using `i128` in places where `num_traits::Num` is expected. Making `ugdb` depend on `num-traits` with the feature enabled explicitly instead of making it depend on a new-ish version of `ndarray` makes the patch a lot smaller though and easier to understand.

**Comment by jcgruenhage** [comment]
One last push to mark svgcleaner as broken on musl, then this should be good to go?

**Pull request merged**
