### PR TITLE
ed: Update to 1.20

### PR DESCRIPTION
**Pull request by indeededa**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by leahneukirchen** [comment]
Please bump to 1.20.2.

**Comment by indeededa** [comment]
> Please bump to 1.20.2.
Okay

**Comment by leahneukirchen** [comment]
Keep revision=1 and squash to a single commit.

**Comment by indeededa** [comment]
okay then

> Keep revision=1 and squash to a single commit.

**Pull request closed without merging**
