### PR TITLE
empathy: remove package.

### PR DESCRIPTION
**Pull request by ericonr**
Has been abandonware for at least three years, as seen in [1].
This is not great for a network exposed messenger, though it hasn't
received any CVEs as far as I could find.

It is also a blocker for enchant 1.x removal, though this is easy to fix
with the patch from [2]. I decided not to go with this option for the
reason listed above.

[1] https://gitlab.gnome.org/GNOME/empathy/-/commit/37976f61d8dddc950a9b7d3b1417d784b331927f
[2] https://gitlab.gnome.org/GNOME/empathy/-/merge_requests/3

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by Gottox** [comment]
I would keep it for now. I would guess, that there are a bunch of users that are still using it.

Just to get an idea, I set up a twitter poll: https://twitter.com/VoidLinux/status/1363622828457811970

**Comment by ericonr** [comment]
Will be pushing a patched package in a bit, closing.

**Comment by ericonr** [comment]
@Gottox I can't get this to build with the patch, here is my commit:

I'd ask that you please try to fix it or merge this removal PR.

```
commit 0c32821443a30a49cd158078825fe9a5e1c820aa
Author: Érico Nogueira <erico.erc@gmail.com>
Date:   Wed Mar 10 00:42:54 2021 -0300

    empathy

diff --git a/srcpkgs/empathy/INSTALL.msg b/srcpkgs/empathy/files/README.voidlinux
similarity index 76%
rename from srcpkgs/empathy/INSTALL.msg
rename to srcpkgs/empathy/files/README.voidlinux
index de8e50ea3d..090705a407 100644
--- a/srcpkgs/empathy/INSTALL.msg
+++ b/srcpkgs/empathy/files/README.voidlinux
@@ -1,8 +1,6 @@
 Some optional packages must be installed for additional functionality:
 
-	- telepathy-butterfly for MSN support
 	- telepathy-gabble for XMPP/jabber support
 	- telepathy-haze for libpurple support
 	- telepathy-idle for IRC support
-	- telepathy-rakia for SIP support
 	- telepathy-salut for link-local XMPP support
diff --git a/srcpkgs/empathy/patches/enchant-2.patch b/srcpkgs/empathy/patches/enchant-2.patch
new file mode 100644
index 0000000000..c2b3a50c03
--- /dev/null
+++ b/srcpkgs/empathy/patches/enchant-2.patch
@@ -0,0 +1,79 @@
+Source: https://gitlab.gnome.org/GNOME/empathy/-/merge_requests/3
+Upstream: no, because upstream is completely abandoned
+
+From f42c415154c797a1b3fbddde60ad8fedb2eda988 Mon Sep 17 00:00:00 2001
+From: Laurent Bigonville <bigon@bigon.be>
+Date: Tue, 7 Jan 2020 11:09:26 +0100
+Subject: [PATCH 1/2] libempathy-gtk: Stop using deprecated enchant function
+
+Replace enchant_dict_add_to_pwl() by enchant_dict_add() and bump minimal
+version accordingly
+---
+ configure.ac                   | 2 +-
+ libempathy-gtk/empathy-spell.c | 2 +-
+ 2 files changed, 2 insertions(+), 2 deletions(-)
+
+diff --git a/configure.ac b/configure.ac
+index 7aeb6b31c..4bf2d4d0c 100644
+--- a/configure.ac
++++ b/configure.ac
+@@ -72,7 +72,7 @@ WEBKIT_REQUIRED=2.10.0
+ GOA_REQUIRED=3.5.1
+ 
+ # Optional deps
+-ENCHANT_REQUIRED=1.2.0
++ENCHANT_REQUIRED=1.4.0
+ GEOCLUE_REQUIRED=2.1.0
+ GEOCODE_GLIB_REQUIRED=0.99.1
+ ISO_CODES_REQUIRED=0.35
+diff --git a/libempathy-gtk/empathy-spell.c b/libempathy-gtk/empathy-spell.c
+index 27f27f902..bb0159fd8 100644
+--- a/libempathy-gtk/empathy-spell.c
++++ b/libempathy-gtk/empathy-spell.c
+@@ -424,7 +424,7 @@ empathy_spell_add_to_dictionary (const gchar *code,
+ 	if (lang == NULL)
+ 		return;
+ 
+-	enchant_dict_add_to_pwl (lang->speller, word, strlen (word));
++	enchant_dict_add (lang->speller, word, strlen (word));
+ }
+ 
+ #else /* not HAVE_ENCHANT */
+-- 
+GitLab
+
+
+From 6c12a411274acf86e494b36704abb8e18b56642e Mon Sep 17 00:00:00 2001
+From: Laurent Bigonville <bigon@bigon.be>
+Date: Tue, 7 Jan 2020 11:38:13 +0100
+Subject: [PATCH 2/2] configure.ac: Switch to enchant-2
+
+---
+ configure.ac | 4 ++--
+ 1 file changed, 2 insertions(+), 2 deletions(-)
+
+diff --git a/configure.ac b/configure.ac
+index 4bf2d4d0c..14f83c852 100644
+--- a/configure.ac
++++ b/configure.ac
+@@ -72,7 +72,7 @@ WEBKIT_REQUIRED=2.10.0
+ GOA_REQUIRED=3.5.1
+ 
+ # Optional deps
+-ENCHANT_REQUIRED=1.4.0
++ENCHANT_REQUIRED=2.1.1
+ GEOCLUE_REQUIRED=2.1.0
+ GEOCODE_GLIB_REQUIRED=0.99.1
+ ISO_CODES_REQUIRED=0.35
+@@ -307,7 +307,7 @@ AC_ARG_ENABLE(spell,
+ if test "x$enable_spell" != "xno"; then
+    PKG_CHECK_MODULES(ENCHANT,
+    [
+-      enchant >= $ENCHANT_REQUIRED,
++      enchant-2 >= $ENCHANT_REQUIRED,
+       iso-codes >= $ISO_CODES_REQUIRED
+    ], have_enchant="yes", have_enchant="no")
+ 
+-- 
+GitLab
+
diff --git a/srcpkgs/empathy/template b/srcpkgs/empathy/template
index 4e01bad39a..5504b68466 100644
--- a/srcpkgs/empathy/template
+++ b/srcpkgs/empathy/template
@@ -1,21 +1,22 @@
 # Template file for 'empathy'
 pkgname=empathy
 version=3.12.14
-revision=2
+revision=3
 build_style=gnu-configure
 configure_args="
  --enable-gst-1.0=yes --enable-gudev=yes --enable-spell=yes
  --disable-schemas-compile --disable-static --enable-goa=no
  --enable-ubuntu-online-accounts=no --enable-geocode=yes
  --enable-location=yes --enable-nautilus-sendto=no --enable-map=yes"
-hostmakedepends="pkg-config intltool itstool glib-devel libxslt geoclue2"
+hostmakedepends="pkg-config intltool itstool glib-devel libxslt geoclue2
+ autoconf automake libtool gettext-devel"
 makedepends="
  libcanberra-devel clutter-gst-devel clutter-gtk-devel
  telepathy-glib-devel telepathy-logger-devel libnotify-devel
  telepathy-farstream-devel telepathy-mission-control-devel
  evolution-data-server-devel geocode-glib-devel folks-devel
  webkit2gtk-devel libgudev-devel pulseaudio-devel cheese-devel
- enchant-devel NetworkManager-devel libchamplain-devel
+ enchant2-devel NetworkManager-devel libchamplain-devel
  gnutls-devel gsettings-desktop-schemas-devel geoclue2-devel iso-codes"
 depends="gsettings-desktop-schemas>=3.12 iso-codes"
 short_desc="GNOME instant messaging client using the Telepathy framework"
@@ -24,8 +25,14 @@ license="GPL-2.0-or-later, LGPL-2.1-or-later"
 homepage="http://live.gnome.org/Empathy"
 distfiles="${GNOME_SITE}/$pkgname/${version%.*}/$pkgname-$version.tar.xz"
 checksum=7d86942ce97edd10ade0e6ae6a210d35e4d627fe4d223377d71fd1840bc6e3a3
+patch_args=-Np1
 disable_parallel_build=yes
 
 pre_configure() {
 	CFLAGS+=" -I$wrksrc/telepathy-account-widgets"
+	autoreconf -fi
+}
+
+post_install() {
+	vdoc $FILESDIR/README.voidlinux
 }
```

**Comment by ericonr** [comment]
Closed in #29598

**Pull request closed without merging**
