### PR TITLE
New package: rnote-0.11.0

### LINKED ISSUE #44229: Package request: Rnote
### Package name

rnote

### Package homepage

https://rnote.flxzt.net/

### Description

Rnote is an open-source vector-based drawing app for sketching, handwritten notes and to annotate documents and pictures. It is targeted at students, teachers and those who own a drawing tablet and provides features like PDF and picture import and export, an infinite canvas and an adaptive UI for big and small screens.

Written in Rust and GTK4.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

### PR DESCRIPTION
**Pull request by chrysos349**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-LIBC)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64
  - armv6l-musl
  - i686

Closes #44229

### CODE REVIEW

**Comment by chrysos349** [comment]
Build check for i686 failed due to the `LLVM ERROR: out of memory`. Any ideas on how to fix the error?

**Comment by 0x5c** [comment]
I have already started work on packaging rnote, and I can say that this PR is not mergeable as is.
Rnote's build system dodges many of the rust/cargo settings that xbps-src sets, and completely breaks [`cargo-auditable`](https://github.com/void-linux/void-packages/pull/40272).

I'm also very doubtful that rnote truly is out of pre-release, and I'm not sure the file format is even stable yet.

**Comment by chrysos349** [comment]
`rnote-0.8.1` and later requires `cairo>=1.17`

**Comment by chrysos349** [comment]
Updated to `0.9.4`

**Comment by chrysos349** [comment]
Bump

**Comment by chrysos349** [comment]
updated to `0.10.0`

**Comment by chrysos349** [comment]
bump

**Comment by xeroxslayer** [comment]
> Build check for i686 failed due to the `LLVM ERROR: out of memory`. Any ideas on how to fix the error?

Does the same when I try to build natively in i686, but has no problems when building through x86_64.

**Pull request closed without merging**
