### PR TITLE
 boost: update to 1.70.0. 

### PR DESCRIPTION
**Pull request by Johnnynator**
Slic3rPE: https://github.com/prusa3d/PrusaSlicer/issues/2150
same with gnuradio and monero

broken:
```
Aegisub
LGOGDownloader
Lucene++
SMC
Slic3rPE
facter
freeorion
gnuradio
litecoin
monero
musikcube
rstudio
supercollider
synfig
wesnoth
```

### CODE REVIEW

**Comment by Gottox** [comment]
@Johnnynator stalled?

**Comment by Johnnynator** [comment]
> @Johnnynator stalled?

didn't work much on it lately, some packages requires patches and I'm waiting for some more upstream patches/updates. I do have a more up to date branch somewhere locally.

**Comment by Johnnynator** [comment]
@Gottox Just checked my local branch. The main reason that it is stalled is blender and I'm not motivated enough to write a patch while the latest release should work (if we finally update python 3) and I wouldn't consider a boost update urgent enough.

**Comment by amak79** [comment]
After the recent Blender update, are there any other major blockers for adding Boost 1.70?

**Comment by q66** [comment]
There is 1.72 already

**Comment by Johnnynator** [comment]
I will add boost 1.72 soon :tm:

**Pull request closed without merging**
