### PR TITLE
blender: enable support for GNU Multiple Precision library.

### LINKED ISSUE #36751: blender doesn't have GMP compiled in
blender-3.0.0_4

### Expected behavior
able to do things like CSG without the mesh getting messed up (using "exact" CSG solver) This makes blender significantly less useful for practical modeling.

### Actual behavior
can only CSG with the fast solver (often resulting in broken meshes)

### Steps to reproduce the behavior
do a CSG operation between two meshes, ensure the "exact" button is pressed and take note of the warning

### PR DESCRIPTION
**Pull request by Idesmi**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, x86_64

Closes #36751

### CODE REVIEW

**Comment by paper42** [comment]
increase the revision to make sure this is built and people get this update.

**Comment by Idesmi** [comment]
ping

**Comment by Duncaen** [comment]
Please squash the commits

**Comment by biopsin** [comment]
Merged #39402
Please close

**Pull request closed without merging**
