### PR TITLE
New package: arti-1.0.0

### PR DESCRIPTION
**Pull request by daniel-eys**
The Tor Project is re-implementing Tor in Rust.

https://gitlab.torproject.org/tpo/core/arti
https://blog.torproject.org/arti_050_released/

Not yet production ready, nor feature-parity with C Tor but basic SOCKS proxy support via
```
$ arti proxy -p 9150
```
is usable.

When arti is production ready, I'm planning to add a proper runit service.

#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by jcgruenhage** [comment]
@daniel-eys Arti 1.0.0 has been released, see https://blog.torproject.org/arti_100_released/

Aside of that: Would be happy if we could move this forward some time.

**Comment by daniel-eys** [comment]
updated to 1.0.0

**Review by Piraty — CHANGES_REQUESTED** [review]
as this depends on `ring`, better put the appropriate arch restrictions here

**Comment by daniel-eys** [comment]
apologies for the delay.

afaik, the `ring` crate is only used when building with the `rustls` TLS backend, not with the default `native_tls`.

see https://gitlab.torproject.org/tpo/core/arti/-/tree/main/crates/arti#additive-features

**Pull request merged**
