### PR TITLE
New package: hunspell-sl_SI-2020.12.31

### PR DESCRIPTION
**Pull request by chloris-pale-green**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

### CODE REVIEW

**Comment by classabbyamp** [comment]
it's unfortunate that there's no versioning in the distfile URL, but I don't see a way around that.

to allow for detection of available updates, please add a `srcpkgs/hunspell-sl-SI/update` with the contents `pattern='<span>\K[\d.]+(?=</span>)'`

**Comment by chloris-pale-green** [comment]
> to allow for detection of available updates, please add a `srcpkgs/hunspell-sl-SI/update` with the contents `pattern='<span>\K[\d.]+(?=</span>)'`

Thank you for the improvement suggestion. I have added the `update` file and incremented the package revision number.

**Comment by paper42** [comment]
> and incremented the package revision number.

Don't do that and squash the commits.

**Comment by chloris-pale-green** [comment]
I've reverted the revision to 1 and squashed the three commits since "New package," but had issues when pushing them back to `origin` (Updates were rejected because the tip of your current branch is behind). I've had to merge and ended up with an ugly commit history.

If desired, I can just fork the repo again, make a "clean" package in a single commit, and issue another pull request.

**Comment by sgn** [comment]
> I've reverted the revision to 1 and squashed the three commits since "New package," but had issues when pushing them back to `origin` (Updates were rejected because the tip of your current branch is behind).

```
git push -f origin master
```

**Comment by chloris-pale-green** [comment]
Thanks for the advice, @sgn! It worked. The package should now be in a single tidy commit.

**Pull request merged**
