### PR TITLE
ansible: switch to python3

### PR DESCRIPTION
**Pull request by steinex**

### CODE REVIEW

**Comment by asergi** [comment]
Except more bugs, but other than that +1.

**Comment by the-maldridge** [comment]
I've been running on python3 for about a year now and haven't seen any more bugs, can you share an example?

**Comment by asergi** [comment]
Mainly encoding issues with modules maintained by the community. OK to merge.

**Comment by the-maldridge** [comment]
A good to know, I don't use many modules beyond the core set.  I'll keep an eye out for any breakage with other modules.

**Pull request merged**
