### PR TITLE
mesa: update to version 24.0.2.

### PR DESCRIPTION
**Pull request by SpidFightFR**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x64-GlibC)

This is it, the new version of mesa, 24.0.0.
Do keep in mind that it requires [libdrm-2.4.119](https://github.com/void-linux/void-packages/pull/48170) to work.
**As a consequence, this PR will stay as draft for as long as libdrm hasn't been updated.**
Edit: Also please check out the [23 branch](https://github.com/void-linux/void-packages/pull/48172) as Void lacks several bugfixes for this branch.

I removed the patch to fix meson builds as it doesn't seem to be necessary anymore.

This version of mesa brings a lot of good stuff, Ray tracing performance improvements and such !

### CODE REVIEW

**Comment by SpidFightFR** [comment]
Note: the builds (currently) fail because of libdrm, don't mind them, i'll force a push to re-try those when libdrm will be updated.

**Comment by classabbyamp** [comment]
just put libdrm in this pr

**Comment by SpidFightFR** [comment]
> just put libdrm in this pr

But there's already another PR opened for that (https://github.com/void-linux/void-packages/pull/48170)...

**Comment by SpidFightFR** [comment]
@classabbyamp hey sorry for the ping, but in either cases, we should integrate the [23 branch latest patches](https://github.com/void-linux/void-packages/pull/48172) before getting our hands in mesa 24, void still runs 23.3.2 as of now, and thus misses a lot of bugfixes from upstream. :sweat_smile: 

As for libdrm, i can add it in this PR if you want to, it's up to you to tell me if maintainers want to merge [lbdrm](https://github.com/void-linux/void-packages/pull/48170) PR then mesa 24 or both all together. :smile:

**Comment by SpidFightFR** [comment]
Updated the template to include changes made [here](https://github.com/void-linux/void-packages/commit/78bd2012335012841c016ac88a0d813ec6760fc9).

**Comment by zlice** [comment]
hey, 24.0.1 hit - f387192b08c471c545590dd12230a2a343244804b5fe866fec6aea02eab57613

**Comment by SpidFightFR** [comment]
> hey, 24.0.1 hit - f387192b08c471c545590dd12230a2a343244804b5fe866fec6aea02eab57613

Working on it, we still need that [libdrm](https://github.com/void-linux/void-packages/pull/48170).

**Comment by zlice** [comment]
if it's easier to put in here, w/e i'll close mine

**Comment by SpidFightFR** [comment]
> if it's easier to put in here, w/e i'll close mine

Copy that.
I'll port your changes here.

**Comment by SpidFightFR** [comment]
#### Testing the changes
- I tested the changes in this PR: **briefly**


#### Local build testing
- I built this PR locally for my native architecture, (x64-GlibC)

Modified PR for mesa 24.0.1.
I kept the removal of the patch to fix meson builds as it isn't necessary anymore.
Also thank you @zlice for your libdrm fix.

**Comment by SpidFightFR** [comment]
> libdrm is now at 120, maybe you can rebase?

Yeah imma do this tomorrow, it's 1 AM at my place and i didn't get much sleep lately 🥲

Thanks for reminding me tho 👌

**Comment by SpidFightFR** [comment]
Nope, the aarch64 and arm builds are still broken, that reminds me of mesa 23...

**Comment by zlice** [comment]
i see `build-helper/rust.sh : 28` has `export BINDGEN_EXTRA_CLANG_ARGS+=" --sysroot=${XBPS_CROSS_BASE} -I${XBPS_CROSS_BASE}/usr/include"`

not sure how or where that's used? 1 or 2 other templates seem to have the var.

try this in mesa template? idk rust really but quick search points to the bindgen cross build var

```sh
  if [ "$CROSS_BUILD" ]; then
    BINDGEN_INCLUDE_FLAGS=$( $CPP -x c++ -v /dev/null -o /dev/null 2>&1 | \
      sed -n '/#include <...> search starts here:/,/End of search list./p' | \
      sed '1,1d;$d' | sed  's/^ /-I/' | paste -s )

    # fix compiler detection for botan:
    # https://github.com/randombit/botan/blob/63d51cb1ab08849d8ece329811b61f8c9abebbcf/configure.py#L2888
    export CXX="${XBPS_CROSS_TRIPLET}-g++"

    export BINDGEN_CFLAGS="--target=$XBPS_CROSS_TRIPLET \
      --sysroot=${XBPS_CROSS_BASE} ${BINDGEN_INCLUDE_FLAGS}"
```

**Comment by zlice** [comment]
> Strangely `aarch64-musl` builds, but `aarch64-glibc` fails with

oh ya, that is weird. i only looked at 1 of the errors but saw the last 1 was musl. fun

**Comment by SpidFightFR** [comment]
> i see `build-helper/rust.sh : 28` has `export BINDGEN_EXTRA_CLANG_ARGS+=" --sysroot=${XBPS_CROSS_BASE} -I${XBPS_CROSS_BASE}/usr/include"`
> 
> not sure how or where that's used? 1 or 2 other templates seem to have the var.
> 
> try this in mesa template? idk rust really but quick search points to the bindgen cross build var (may want to do for only musl??? dont think it would matter but)
> 
> ```shell
> post_configure() {
>   if [ "$CROSS_BUILD" ]; then
>     find -iname "*.ninja" -exec sed -i "{}" \
>       -e "/rustc/s; --sysroot ${XBPS_CROSS_BASE}/usr;;g" \
>       \;
>     BINDGEN_CFLAGS="--target=$XBPS_CROSS_TRIPLET \
>       --sysroot=${XBPS_CROSS_BASE} ${BINDGEN_INCLUDE_FLAGS}"
>   fi
> }
> ```

trying that... let's see how this turns out.

**Comment by zlice** [comment]
naw it wont like dkwo just pointed out...thinking right above that checking for musl and unsetting or something

**Comment by zlice** [comment]
ok so this works for x86, a64, a7l

```sh
post_configure() {
  if [ "$CROSS_BUILD" ]; then
    find -iname "*.ninja" -exec sed -i "{}" \
      -e "/rustc/s; --sysroot ${XBPS_CROSS_BASE}/usr;;g" \
      -e "s|-isystem/usr/include||g" \
      \;
  fi
}
```
it looks like ninja.build has `-isystem/usr/include` for everything, so aarch64 gets x86_64's gnu stub.h ... which wants -32, which a64 doesn't have.

<details>
<summary>screenshot ninja build llvm_bindings</summary>

systeminclude

</details>

**Comment by SpidFightFR** [comment]
> ok so this works for x86, a64, a7l
> 
> ```shell
> post_configure() {
>   if [ "$CROSS_BUILD" ]; then
>     find -iname "*.ninja" -exec sed -i "{}" \
>       -e "/rustc/s; --sysroot ${XBPS_CROSS_BASE}/usr;;g" \
>       -e "s|-isystem/usr/include||g" \
>       \;
>   fi
> }
> ```
> 
> it looks like ninja build has `-isystem/usr/include` for everything, so aarch64 gets x86_64's gnu stub.h ... which wants -32, which a64 doesn't have.
> screenshot ninja build llvm_bindings
> 
> systeminclude

Noice imma try that once back at home.

How do you manage to see all that? 😅
Like how do you do to make these patches and stuff?

**Comment by zlice** [comment]
i was looking at rust related stuff and cross args but none of that made a difference. then i saw `-isystem...` and thought it looked out of place just from doing build stuff over the years.

**Comment by SpidFightFR** [comment]
> i was looking at rust related stuff and cross args but none of that made a difference. then i saw `-isystem...` and thought it looked out of place just from doing build stuff over the years.

Wow...

I'm a noob at compiling stuff, it's always impressive to see other's experience, not gonna lie.

**Comment by zlice** [comment]
> @zlice Do you think this line in
> is ignored, or somehow not passed over from meson to ninja?

there's sysroot and targets to aarch64 after configure. maybe the system includes happened to work last time? or the new rust update to 69 is just doing stuff different idk rust enough

**Comment by SpidFightFR** [comment]
> ok so this works for x86, a64, a7l
> 
> ```shell
> post_configure() {
>   if [ "$CROSS_BUILD" ]; then
>     find -iname "*.ninja" -exec sed -i "{}" \
>       -e "/rustc/s; --sysroot ${XBPS_CROSS_BASE}/usr;;g" \
>       -e "s|-isystem/usr/include||g" \
>       \;
>   fi
> }
> ```
> 
> it looks like ninja build has `-isystem/usr/include` for everything, so aarch64 gets x86_64's gnu stub.h ... which wants -32, which a64 doesn't have.
> screenshot ninja build llvm_bindings

You just fixed mesa 24 on void, thanks !

**Comment by SpidFightFR** [comment]
If by chance a maintainer sees this, we should push [23.3.6](https://github.com/void-linux/void-packages/pull/48767) first before mesa 24.0.1, as it's the last bugfix release of the 23 branch according to the calendar, it's a 90%+ guarantee of it just working. :smile:

**Comment by SpidFightFR** [comment]
#### Testing the changes
- I tested the changes in this PR: **briefly**


#### Local build testing
- I built this PR locally for my native architecture, (x64-GlibC)

Modified PR for mesa 24.0.2.
Same as the previous edits.

**Comment by zlice** [comment]
looks the same on A770 for me :+1:

**Comment by SpidFightFR** [comment]
Hello, @classabbyamp, i hope you're doing great. :smile: 

Looks good on our sides, please, may you take a look at the PR ? :pray:

**Comment by SpidFightFR** [comment]
@Duncaen Hello, my apologizes for the ping, i feel like an a-hole, pinging you and bothering you all the time. :sweat:  
I'm unsure what to do what to do in such a case, is everything good with this PR ? nothing missing ? :sweat_smile: 

Welp, sorry again for the ping, may you take a look at it please ? :pray:
Wish you, and the maintainer team, a great day!

**Comment by Daxot** [comment]
> @Duncaen Hello, my apologizes for the ping, i feel like an a-hole, pinging you and bothering you all the time. 😓 I'm unsure what to do what to do in such a case, is everything good with this PR ? nothing missing ? 😅
> 
> Welp, sorry again for the ping, may you take a look at it please ? 🙏 Wish you, and the maintainer team, a great day!

i think you will get a better luck to get maintainers attention to this PR in #xbps IRC-channel

**Comment by SpidFightFR** [comment]
> > @Duncaen Hello, my apologizes for the ping, i feel like an a-hole, pinging you and bothering you all the time. 😓 I'm unsure what to do what to do in such a case, is everything good with this PR ? nothing missing ? 😅
> > Welp, sorry again for the ping, may you take a look at it please ? 🙏 Wish you, and the maintainer team, a great day!
> 
> i think you will get a better luck to get maintainers attention to this PR in #xbps IRC-channel

Agreed, i'll try here.

**Comment by SpidFightFR** [comment]
Just added a patch as advised [here](https://gitlab.freedesktop.org/mesa/mesa/-/issues/10613#note_2290167).

**Pull request merged**
