### PR TITLE
budgie-desktop: update to 10.5.2.

### PR DESCRIPTION
**Pull request by not-chicken**
Removed patches taken from upstream, limited lines to about 80 columns, and added runtime dependency, `gnome-themes-extra`.

### CODE REVIEW

**Comment by not-chicken** [comment]
Gonna need help to fix cross builds. [Logs from CI](https://github.com/void-linux/void-packages/pull/26911/checks?check_run_id=1491088068).

**Comment by not-chicken** [comment]
Interesting. Reverting changes in https://github.com/void-linux/void-packages/pull/26676 fixes cross builds.

@sgn Any idea what could be wrong here?

**Comment by sgn** [comment]
> Interesting. Reverting changes in #26676 fixes cross builds.
> @sgn Any idea what could be wrong here?

Reverting #26676 skips valac from looking into correct vapidir, thus it couldn't found polkit-gobject-1 bindings in system vapidir.
And uses vendored polkit-gobject-1 bindings.
See https://github.com/void-linux/void-packages/blob/b9331f9e5ec72e8a663c4f46cfd61911070d7ad3/srcpkgs/vala-panel-appmenu/template#L21

I probably need to rework on `valac` wrapper.

**Comment by not-chicken** [comment]
Oh I see. Thanks for looking into it.

**Pull request merged**
