### PR TITLE
file: update to 5.45.

### PR DESCRIPTION
**Pull request by Bnyro**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc

### CODE REVIEW

**Comment by Bnyro** [comment]
I'd be thankful if anyone has an idea how to fix the i686 checks - they do pass on my machine when cross compiling, and I don't have an i686 device.

**Comment by leahneukirchen** [comment]
Breaks in my i686 rootdir.

**Comment by leahneukirchen** [comment]
Other tests break too so this needs fixing.

**Comment by leahneukirchen** [comment]
You need to cherry pick https://github.com/file/file/commit/218fdf813fd5ccecbb8887a1b62509cd1c6dd3a1

**Comment by Bnyro** [comment]
thanks!

**Pull request merged**
