### PR TITLE
pinebookpro-kernel: update to 5.7

### PR DESCRIPTION
**Pull request by thallian**
python_version needs to be set, same as in the normal kernel package

### CODE REVIEW

**Comment by thallian** [comment]
takes too long for travis to compile, it builds for me locally (running the updated package myself)

**Comment by sgn** [comment]
For your future contribution, please add `[ci skip]` to a change that likely to take a long time, e.g. kernel, firefox :)

**Comment by thallian** [comment]
Ok, will do :)

**Comment by q66** [comment]
broken on musl: https://build.voidlinux.org/builders/aarch64-musl_builder/builds/27109/steps/shell_3/logs/stdio

**Comment by thallian** [comment]
Hm, I built it myself on aarch64-musl (using it on that arch too), no errors there, I will try a cross compile and see what happens. Is there a recommended way to do the same as the builder is doing?

**Comment by sgn** [comment]
On 2020-06-16 01:24:30-0700, Sebastian Hugentobler <notifications@github.com> wrote:
> Hm, I built it myself on aarch64-musl (using it on that arch too),
> no errors there, I will try a cross compile and see what happens. Is
> there a recommended way to do the same as the builder is doing?

aarch64-musl is cross-built from x86_64-musl in server.

You need to:

- find an x86_64 machine.
- clone the repository
- ./xbps-src binary-bootstrap x86_64-musl
- ./xbps-src -a aarch64-musl pkg <pkgname>

-- 
Danh

**Pull request merged**
