### PR TITLE
[wip/rfc] perl: change config

### PR DESCRIPTION
**Pull request by dkwo**
At least when not cross-compiling, using `Configure` instead of `configure` gets rid of test errors on musl and i686.
Only one error left, the same for everybody:
```
Failed 1 test out of 2534, 99.96% okay.
	porting/checkcase.t
```
Do you think this is worth changing? @leahneukirchen

### CODE REVIEW

**Comment by leahneukirchen** [comment]
I'm not a big fan as this will change behavior between native and cross builds too much... can you diff the config.h to see why perl-cross results in test failures?

**Comment by dkwo** [comment]
Sure, that's an option, but let me first see what happens if I use Configure for everything.

**Comment by dkwo** [comment]
Ok, that does not work, so I'll try what you suggested.

**Comment by dkwo** [comment]
This is the diff between using `configure --prefix=/usr` and `Configure -des` on `x86_64-musl` (the rest being unchanged):

[diff.log](https://github.com/void-linux/void-packages/files/7228539/diff.log)

**Comment by dkwo** [comment]
Also, quoting perl-cross homepage :)
> If you can use Configure from the vanilla distribution, you probably should use Configure;
> perl-cross is for the cases when Configure just can't make it.
> The configure script from perl-cross is essentially a 100 kB long session of severe sh(1) abuse.

**Comment by dkwo** [comment]
I think that using `perl-cross` for everything means sacrificing too much in favor of cross-compiling.
This is what gentoo does, similar to what I proposed:
```
if tc-is-cross-compiler; then
		./configure \
			--target="${CHOST}" \
			--build="${CBUILD}" \
			-Dinstallprefix='' \
			-Dinstallusrbinperl='undef' \
			-Dusevendorprefix='define' \
			"${myconf[@]}" \
			|| die "Unable to configure"
	else
		sh Configure \
			-des \
			-Dinstallprefix="${EPREFIX}"'/usr' \
			-Dinstallusrbinperl='n' \
			"${myconf[@]}" \
			|| die "Unable to configure"
	fi
```
I can investigate the only remaining failure (a very minor one)
```
Failed 1 test out of 2534, 99.96% okay.
	porting/checkcase.t
```
if we decide to go that way. If you prefer to keep the status quo, that's also fine, in which case just close this PR :)

**Comment by leahneukirchen** [comment]
The problem is that if we mix native and cross compiling scripts, you get different packages if you recompile perl locally... Ideally perl-cross would yield a test passing build too, of course (I wonder why not more people complain it doesn't?)

Further, we want MULTIPLICITY for the next Perl rebuild, and perl-cross never enables it afaics.  So perhaps we need more patching around indeed.

**Comment by dkwo** [comment]
> The problem is that if we mix native and cross compiling scripts, you get different packages if you recompile perl locally...
True, but simpler than chasing bugs and patching perl-cross imho.
> Further, we want MULTIPLICITY for the next Perl rebuild, and perl-cross never enables it afaics.
In the setup I propose, it's as easy as enabling the option, and one would not encounter issues like #32857 to begin with.
(I tried that and it passess all checks.)

**Comment by dkwo** [comment]
I'll close this for now, just keep in mind the alternative :)

**Pull request closed without merging**
