### PR TITLE
linux6.x: backport fix for kexec regression

### PR DESCRIPTION
**Pull request by ahesford**
All of our `linux6.x` kernel series include a change that breaks `kexec` on certain hardware, notably AMD CPUs using various iterations of the Zen microarchitecture. I can reproduce the issue on my Zen 3 CPU, while [other reports](https://github.com/zbm-dev/zfsbootmenu/discussions/598) reveal that this problem affects ZFSBootMenu users on other iterations. I bisected the problem and confirmed that it is caused by the same commit that [seems to impact users more generally](https://lore.kernel.org/all/3a1b9909-45ac-4f97-ad68-d16ef1ce99db@pavinjoseph.com/). Consequently, the current upstream fix is to [just revert the change](https://lore.kernel.org/linux-kernel/8142c0de-e3a4-4e78-aa1b-f5e6503752e4@intel.com/T/#m674760504b865936068602efca9a10fb72e7102e).

While I was backporting the reversion, I took the liberty of updating `linux6.1` as well.

I'm in the process of building and testing kernels with these patches to confirm that it fixes the ZFSBootMenu problem I observed and, assuming so, plan to bump our kernels to include the fix.

cc: @sgn @Duncaen 

[ci skip]

#### Testing the changes
- I tested the changes in this PR: **in process**

### CODE REVIEW

**Comment by sgn** [comment]
Yes, that commit should be reverted, seeing that in urgency, I think there'll be a stable release soon, no?

**Comment by ahesford** [comment]
I've built these kernels for aarch64 and x86_64 and confirm that the revert fixes booting with ZFSBootMenu for every kernel series in this PR.

We can wait a day or two to see if new kernels are forthcoming. I see some announcements for 6.1 and 6.6 RC windows, but the revert does not appear in the changelog. We should make sure this is included in the next release, or we'll have to carry patches for awhile.

**Comment by dkwo** [comment]
New kernels today, but I can only see that patch in linux-next.

**Comment by ahesford** [comment]
Bumped all kernels, currently testing builds on all of them to make sure there are no surprises.

**Comment by ahesford** [comment]
Currently all kernels fail to build on musl: https://bugzilla.kernel.org/show_bug.cgi?id=218647

**Comment by ahesford** [comment]
Looks like Alpine found a fix, so I'm build-testing all of them again.

**Pull request merged**
