### PR TITLE
Math package: mpfi-1.5.3

### PR DESCRIPTION
**Pull request by tornaria**
C library for interval arithmetic.

### CODE REVIEW

**Comment by dkwo** [comment]
Looks good to me.

**Comment by tornaria** [comment]
@ericonr: rebased with only style changes. Tested with sage-9.4.rc2.

**Comment by Eloitor** [comment]
I get the following error when running `./xbps-src pkg mpfi`

```
=> xbps-src: updating repositories for host (x86_64)...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/nonfree/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/debug/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/multilib/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/multilib/nonfree/x86_64-repodata' ...
=> xbps-src: updating software in / masterdir...
=> xbps-src: cleaning up / masterdir...
=> mpfi-1.5.3_1: removing autodeps, please wait...
=> mpfi-1.5.3_1: building [gnu-configure] for x86_64...
   [target] mpfr-devel-4.1.0_1: found (https://alpha.de.repo.voidlinux.org/current)
   [runtime] mpfi-1.5.3_1: not found (self, ignored)
=> mpfi-1.5.3_1: installing target dependencies: mpfr-devel-4.1.0_1 ...
=> mpfi-1.5.3_1: running do-fetch hook: 00-distfiles ...
=> mpfi-1.5.3_1: fetching distfile 'mpfi-1.5.3.tar.bz2'...
SSL certificate subject doesn't match host gforge.inria.fr
https://gforge.inria.fr/frs/download.php/file/37331/mpfi-1.5.3.tar.bz2: Operation not permitted
=> ERROR: mpfi-1.5.3_1: failed to fetch mpfi-1.5.3.tar.bz2.
```

**Comment by tornaria** [comment]
It seems gforge.inria.fr is down, maybe for good? Some packages have moved to gitlab.inria.fr, but I don't know about mpfi.

**Comment by tornaria** [comment]
It should now be fixed.

New repo is on https://gitlab.inria.fr/mpfi/mpfi. There are no release tarballs, so must run autoreconf on tag tarballs, but the code is the same as before.

Note that release 1.5.4 is broken in many different ways, and not even HEAD is fixed. A few issues in their gitlab describe the problems and how to fix them, but I don't think it's worth doing anything until they do a new release, since 1.5.3 works out of the box.

**Pull request merged**
