### PR TITLE
unbound: add logging service

### PR DESCRIPTION
**Pull request by AluminumTank**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
@leahneukirchen LGTM

**Comment by leahneukirchen** [comment]
no `-t unbound`?

**Comment by leahneukirchen** [comment]
ah it autodetects that, fine.

**Comment by leahneukirchen** [comment]
But `log/supervise` is missing, no?

**Comment by AluminumTank** [comment]
That's automatically created by `sv` at runtime. I don't think it's supposed to be included in the package.

**Comment by AluminumTank** [comment]
If  you're trying to install and run this on your machine with unbound already installed and service enabled, you'll have to manually enable the log service, or just unlink and relink to `/var/service/unbound`

**Comment by Duncaen** [comment]
> That's automatically created by sv at runtime. I don't think it's supposed to be included in the package.

No `runsv` creates the directory, not the symlink. It would just create a directory in the service directory if the symlink is missing.
`vsv` in xbps-src should create both supervise symlinks,  but for some reason it does not do in the CI run.
https://github.com/void-linux/void-packages/runs/3082099002#step:9:66

**Comment by ericonr** [comment]
So, is this actually necessary? I get unbound information just fine in `svlogtail` output without a `log` service...

**Comment by AluminumTank** [comment]
Huh, you're right. I think I got confused when I was trying to enable logging within unbound because I copied a config from somewhere which didn't have the `use-syslog: true` directive. I'll close then, thanks for the tip.

As an aside, the issue about `log/supervise` missing may be related to `log/run` being a symlink to `/usr/bin/vlogger` since I checked several other services in void-packages using this symlink (`bluez`, dhcp`, `caddy`) and none of them have `log/supervise` either. Not sure if this is intended behavior or not...

**Comment by ericonr** [comment]
> Not sure if this is intended behavior or not...

I don't think so. Can you open an issue so we can remember to try and fix it?

**Pull request closed without merging**
