### PR TITLE
cherrytree: update to 0.38.8; fix noarch; add new dependency+build_op…

### PR DESCRIPTION
**Pull request by chinarulezzz**
…tion

### CODE REVIEW

**Comment by maxice8** [comment]
rebase

**Comment by chinarulezzz** [comment]
done. thanks.

**Comment by maxice8** [comment]
can be just update to <version>

**Comment by Chocimier** [comment]
Build option for extending `depends`is not very useful, why to rebuild cherrytree if just installing p7zip do the same.

**Pull request closed without merging**
