### PR TITLE
add patch to remove CLOCK_SGI_CYCLE usage from fftw

### PR DESCRIPTION
**Pull request by paigeadelethompson**
Refer to issue:
https://github.com/void-linux/void-packages/issues/53417

#### Testing the changes
- I tested the changes in this PR: yes

#### Local build testing
- I built this PR locally for my native architecture, (aarch64-musl) ✓
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-musl ✓
  - armv7l ✗
  - armv6l-musl ✗

### CODE REVIEW

**Comment by classabbyamp** [comment]
let's grab this patch instead: https://github.com/FFTW/fftw3/pull/123.patch

**Comment by paigeadelethompson** [comment]
> let's grab this patch instead: https://github.com/FFTW/fftw3/pull/123.patch

ugh good grief, `Mon Sep 17 00:00:00 2001` oh never mind that's ... `Date: Fri, 5 Jan 2018 21:27:23 +0100` okay fine but still good grief.. why don't they just fix it upstream? More importantly do you happen to know why `&& defined(CLOCK_SGI_CYCLE)` is even getting defined in the first place? I assume it must have something to do with autotools but I'm dreading having to figure it out (I haven't had the best of luck with autotools)

**Comment by classabbyamp** [comment]
> Mon Sep 17 00:00:00 2001 oh never mind

heh that's the magic email patch header

> why don't they just fix it upstream?

who knows

> More importantly do you happen to know why && defined(CLOCK_SGI_CYCLE) is even getting defined in the first place?

it's defined in [time.h](https://git.musl-libc.org/cgit/musl/tree/include/time.h#n97) because [linux defines it](https://git.musl-libc.org/cgit/musl/commit/include/time.h?id=d74e462a76d37ce10a048d3794ca89ca7d480ddb)

**Comment by classabbyamp** [comment]
also, don't forget to increment `revision` in fftw's template

**Comment by paigeadelethompson** [comment]
Huh, thats interesting I just noticed where that patch links to (https://patch-diff.githubusercontent.com/raw/FFTW/fftw3/pull/123.patch) OK thats authentic enough for me, I will: 

- test the patch in build 
- install the package on my test system (I'd like to run gqrx and make sure it works as expected) 
- update this PR 

I'll ping you back

**Review by paigeadelethompson — COMMENTED** [review]
This commit leaves behind the patch I provided and introduces two patches from upstream. These patches can be found here: https://patch-diff.githubusercontent.com/raw/FFTW/fftw3/pull/123.patch

EDIT: the revision number for the template was bumped from 2 to 3.

**Comment by paigeadelethompson** [comment]
hey, also I just saw all this from earlier https://github.com/void-linux/void-packages/actions/runs/12247947213/job/34167229779 

I'm fine amending that but... 

Also I'd be happy to rebase the two commits in this PR if I could figure out how; something tells me if I rebase/squash I know I'll have to force push that to my fork, but IIRC doing that will completely screw up this PR and I'll just have to reopen a new one. I wanted to leave the option open since for posterity it might be nice to have on the record that I provided a patch which was ultimately not used at your request. Please advise if possible on how to proceed, because my methods for dealing with this are a bit crude and I wouldn't mind some improvement.

**Comment by paigeadelethompson** [comment]
Heads up, I just ran into the same problem again somehow I missed this problem with gqrx but I went to start sdrangel and its not starting (CLOCK_SGI_CYCLE) so I need to figure out whats going on before we should merge this

**Comment by paigeadelethompson** [comment]
HEY what are you doing ??????

**Comment by Qui3tOrg** [comment]
> let's grab this patch instead: https://github.com/FFTW/fftw3/pull/123.patch

The upstream code discussed here has not been updated in ~7 years (Date: Fri, 5 Jan 2018 21:27:23 +0100). Why should this be considered a reasonable patch if it is no longer being supported by the developer? To properly solve this issue, maintained code is required.

**Comment by classabbyamp** [comment]
force-pushing the branch won't close the PR unless it causes there to be 0 commits different between master and your branch

in https://github.com/void-linux/void-packages/commit/f15b006deb93b5630765a5575aa32a40fe490e05, I took the patch from upstream and downloaded it as-is, this preserves the context of who wrote the patch and what it does because it has the commit messages attached.

based on its cmake files, sdrangel may be using its own copy of fftw, or linking it statically, which would cause the fix not to work without further patching or recompilation respectively.

sorry for pre-emptively merging, the fix worked for me

**Comment by paigeadelethompson** [comment]
No problem, thank you

**Pull request closed without merging**
