### PR TITLE
New package: etterna-0.68.1

### PR DESCRIPTION
**Pull request by AN3223**
Advanced cross-platform rhythm game focused on keyboard play
https://github.com/etternagame/etterna/

### CODE REVIEW

**Comment by Johnnynator** [comment]
Nice, it even ships with it's own a decade old zlib version, and other multiple years deps. Just no, there is no good reason not to just use the system version of these.

**Comment by AN3223** [comment]
> Nice, it even ships with it's own a decade old zlib version, and other
> multiple years deps. Just no, there is no good reason not to just use
> the system version of these.

Etterna is a fork of Stepmania, Stepmania is also packaged here and also
ships with the same version of zlib.

**Comment by Johnnynator** [comment]
> Nice, it even ships with it's own a decade old zlib version, and other multiple years deps. Just no, there is no good reason not to just use the system version of these.
> Etterna is a fork of Stepmania, Stepmania is also packaged here and also ships with the same version of zlib.

No, Stepmania actually allows to dynamically link against system libs in most cases.

**Comment by AN3223** [comment]
> > Nice, it even ships with it's own a decade old zlib version, and
> > other multiple years deps. Just no, there is no good reason not to
> > just use the system version of these.
> > Etterna is a fork of Stepmania, Stepmania is also packaged here and also ships with the same version of zlib.
>
> No, Stepmania actually allows to dynamically link against system libs
> in most cases.

Ah okay, my mistake

**Comment by AN3223** [comment]
Well, I got stepmania working by applying #16630 so my knack for a rhythm game has been satisfied. Closing now.

**Pull request closed without merging**
