### PR TITLE
dpkg: Add zstd compression

### PR DESCRIPTION
**Pull request by CRKatri**

### CODE REVIEW

**Comment by ericonr** [comment]
I'm okay with this when it gets a release... Pushing a patch this big for a new feature doesn't sit right with me. What would the use case even be?

**Comment by CRKatri** [comment]
This isn't really a big new feature. Canonical has had this for a very long time, it's been thoroughly tested.

**Comment by Duncaen** [comment]
Is the patch upstreamed? No? can't get in.

**Comment by Diatrus** [comment]
@ericonr @Duncaen This patch would greatly improve my own workflow when packaging for Canonical's Ubuntu, who have included Zstandard support in their build of dpkg since version 1.19. 

This patch implements a feature that has been tested thoroughly over a long period of time by one of, if not *the* most commonly used Linux distribution. Not only that, but it does not change any default behavior and wouldn't break any workflows. It's silly to write such a thing off immediately.

**Comment by the-maldridge** [comment]
Closing as per duncaen's comment, this is not aligned with Void's patch policy.

**Comment by Duncaen** [comment]
You are free to run your own patched build, patching in features into random packages is not something that Void does.
If the patch is thoroughly tested and used a lot why is it not upstreamed? This would be a better approach than requesting random patches being added to random linux distributions.

**Pull request closed without merging**
