### PR TITLE
New package: python3-contourpy-1.0.5

### PR DESCRIPTION
**Pull request by misuchiru03**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-GLIBC)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-musl
  - armv7l

### CODE REVIEW

**Comment by sgn** [comment]
You may need to add `depends` to `python3-matplotlib`?

**Comment by misuchiru03** [comment]
> You may need to add `depends` to `python3-matplotlib`?

I have that already, just wanted to see if the intended actions are good now. I will push my matplotlib template.

**Comment by misuchiru03** [comment]
I added the commit to this PR as it's directly related. If it's better to separate into its own PR I can do that.

**Comment by misuchiru03** [comment]
I do not know if we can add the depends for python3-matplotlib as python3-contourpy has a checkdepends of python3-matplotlib... but python3-matplotlib actually has a runtime dependency of python3-contourpy.
Thus the (partial) failed builds (cyclic dependency, failed for some builds, succeeded for cross-builds) when updating the revision number on python3-matplotlib. I've regressed that for the mean time. 

Any suggestions?

**Comment by classabbyamp** [comment]
find the tests that require matplotlib by removing it from checkdepends and disable them. (from what i saw in the repo, there might not be any?)

**Comment by ahesford** [comment]
Thanks, I overlooked this new dependency with the last update. The build cycle is broken by disabling matplotlib tests unless "full" checks are turned on, allowing the user to run the full test suite provided that matplotlib is already packaged.

**Pull request closed without merging**
