### PR TITLE
python3-pandas: update to 2.2.2.

### PR DESCRIPTION
**Pull request by Vinfall**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc

#### Information regarding numpy

numpy is also updated as latest pandas (2.2.2) requires numpy>=2.0.0rc1.
(I can raise a separate PR for numpy if you prefer that.)

Dropped old patches after checking v2.0.0 [pyproject.toml](https://github.com/numpy/numpy/blob/v2.0.0/pyproject.toml) and [pytest.ini](https://github.com/numpy/numpy/blob/v2.0.0/pytest.ini).

`xbps-query -X python3-numpy`:
- python3-imageio (no update, rebuild for python3-numpy)
- python3-matplotlib (rebuild)
- python3-pandas

I'm not sure if python3-numpy-stl is related since it's not a reverse dep.

### CODE REVIEW

**Comment by Vinfall** [comment]
CI is failing to build numpy 2.0.0 while building it locally runs perfectly fine. I'm not sure what's the cause, do I need to raise a PR for numpy, wait for its merge, then update pandas?

**Comment by classabbyamp** [comment]
```
=> python3-numpy-2.0.0_1: running do_check ...
python3: can't open file '/builddir/python3-numpy-2.0.0/runtests.py': [Errno 2] No such file or directory
```
you're probably not running check locally

**Comment by ahesford** [comment]
Please drop the numpy update from this PR; it is a major update and has a lot of dependants, so I'm going to take care of it myself.

**Comment by Vinfall** [comment]
> you're probably not running check locally

Indeed, I always use `xbps-src pkg` and just discovered that it would not run checks :(

> Please drop the numpy update from this PR

Agreed, I'm gonna make this pandas only. NumPy 2.0 update seems to be much larger than I thought although most of my scripts run fine. I'll let you handle it.

**Comment by ahesford** [comment]
Because the current version of Pandas requires NumPy < 2, I'm going to include an update in the larger NumPy PR #51077.

**Pull request closed without merging**
