### PR TITLE
New package: ghidra-9.1

### PR DESCRIPTION
**Pull request by abenson**
Since the other PR was closed.

### CODE REVIEW

**Comment by Johnnynator** [comment]
Can you go through my comments in #15958 and apply them here if applicable.

**Comment by abenson** [comment]
I already did

**Comment by Johnnynator** [comment]
> I already did

At least not

>Add skiprdeps and nostrip the the example files
```diff
@@ -23,6 +23,24 @@ checksum="e24593fb4cf3e1d1b7a8dfeae85edfba9fd9d446b360c7a5d12e9640438735e3
  00ed038eb6abaf6ddec8d202a3ed7a81b521458f4cd459948115cfd02ff59d6d"
 skip_extraction="AXMLPrinter2.jar"
 nopie=true
+skiprdeps="/usr/lib/ghidra/docs/GhidraClass/ExerciseFiles/Advanced/animals
+ /usr/lib/ghidra/docs/GhidraClass/ExerciseFiles/Advanced/compilerVsDecompiler
+ /usr/lib/ghidra/docs/GhidraClass/ExerciseFiles/Advanced/createStructure
+ /usr/lib/ghidra/docs/GhidraClass/ExerciseFiles/Advanced/custom
+ /usr/lib/ghidra/docs/GhidraClass/ExerciseFiles/Advanced/dataMutability
+ /usr/lib/ghidra/docs/GhidraClass/ExerciseFiles/Advanced/globalRegVars.so
+ /usr/lib/ghidra/docs/GhidraClass/ExerciseFiles/Advanced/inline
+ /usr/lib/ghidra/docs/GhidraClass/ExerciseFiles/Advanced/jumpWithinInstruction
+ /usr/lib/ghidra/docs/GhidraClass/ExerciseFiles/Advanced/ldiv
+ /usr/lib/ghidra/docs/GhidraClass/ExerciseFiles/Advanced/noReturn
+ /usr/lib/ghidra/docs/GhidraClass/ExerciseFiles/Advanced/opaque
+ /usr/lib/ghidra/docs/GhidraClass/ExerciseFiles/Advanced/override.so
+ /usr/lib/ghidra/docs/GhidraClass/ExerciseFiles/Advanced/setRegister
+ /usr/lib/ghidra/docs/GhidraClass/ExerciseFiles/Advanced/sharedReturn
+ /usr/lib/ghidra/docs/GhidraClass/ExerciseFiles/Advanced/switch
+"
+nostrip_files="animals createStructure dataMutability inline ldiv opaque setRegister switch
+ compilerVsDecompiler custom globalRegVars.so jumpWithinInstruction noReturn override.so sharedReturn"
 
 do_configure() {
  mkdir -p ~/.gradle/init.d
```

This is needed for musl, otherwise xbps wants to pull in glibc for the Exercise files. Furthermore the Exercise files are the ones ones that you want to have as nostrip, so use `nostrip_files` instead of `nostrip=yes`. And `skiprdeps=yes` is a noop, it requires a whitespace separated list of files

**Comment by Johnnynator** [comment]
Also I would prefer that all source files are listed in distfiles instead of having gradle fetching some.

**Comment by abenson** [comment]
Ah, okay. I misunderstood that. I'll get that fixed.

**Pull request closed without merging**
