### PR TITLE
[WIP] scribus: update to 1.5.5.

### PR DESCRIPTION
**Pull request by Johnnynator**
updae to a devel version to not depend on qt-4 anymore

### CODE REVIEW

**Comment by Piraty** [comment]
"1.5.3 has a new text engine and scribus will not be able to ensure that the text flow will not change when opening files created with older version."
I can confirm that most of my projects break in that regard with this PR's update, but I was told by a dev we just have to live with it, because the changes bring much more benefits than this drawbackk.

+1 on this

**Comment by Piraty** [comment]
On the other hand, it should be possible to install multiple version in parallel...

**Comment by ericonr** [comment]
ping?

**Comment by Piraty** [comment]
i won't block this

**Pull request merged**
