### PR TITLE
neovim: update to 0.5.1

### PR DESCRIPTION
**Pull request by FollieHiyuki**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ram02z** [comment]
`CMAKE_BUILD_TYPE` should be `Release` for releases, `RelWithDebInfo` is reserved for nightlies.

https://github.com/justinmk/neovim/commit/6f965f41dfd6b1927a23b2afa188fbcb88e8b2f3

**Comment by ericonr** [comment]
Ugh, that kinda sucks. I'm pretty sure CMake strips our CFLAGS in `Release` mode, which includes the debug info stuff.

**Comment by FollieHiyuki** [comment]
> Ugh, that kinda sucks. I'm pretty sure CMake strips our CFLAGS in Release mode, which includes the debug info stuff.

That was why I go with RelWithDebInfo when I made the PR for 0.5.0. But personally I can build neovim myself if I need debug symbols so I'm fine with Release.

**Comment by ericonr** [comment]
Please check my final commit for an idea of a better commit message. *what* is being done can usually be had by looking at the diff. The most important thing is documenting the *why*.

**Comment by FollieHiyuki** [comment]
> Please check my final commit for an idea of a better commit message. what is being done can usually be had by looking at the diff. The most important thing is documenting the why.

Thanks @ericonr I'll remember that :)

**Pull request closed without merging**
