### PR TITLE
go: update to 1.18.

### PR DESCRIPTION
**Pull request by josegpt**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by howdoicomputer** [comment]
Now we're at `1.18`

**Comment by josegpt** [comment]
Thank you for pointing it out. I updated the pr.

**Comment by endigma** [comment]
merge when?

**Comment by sina-devel** [comment]
Why not merge? I don't think there is a problem.

**Comment by sug0** [comment]
I've been using this update for a few days, no issue for me.

**Comment by howdoicomputer** [comment]
> Why not merge? I don't think there is a problem.

Probably because the maintainers have limited time. Void isn't a distro with unlimited distros. If you want this package then you can clone this repo and build it.

**Comment by Jlll1** [comment]
Works great!

**Comment by the-maldridge** [comment]
As howdoicomputer suggested above, Void has a limited team with limited time.  Your patience is appreciated.

**Pull request closed without merging**
