### PR TITLE
New package: Grammalecte-1.6.0

### PR DESCRIPTION
**Pull request by Eluminae**

### CODE REVIEW

**Comment by jnbr** [comment]
You can remove `unzip` and the `do_extract` hook, support to extract zip files was added to xbps-src.
You might have to rebase your branch for this to work.

**Comment by Eluminae** [comment]
> You can remove `unzip` and the `do_extract` hook, support to extract zip files was added to xbps-src.

I had an issue and by-passed it this way. Maybe there is a better
solution:

```
-%<-
=> Grammalecte-1.6.0_1: extracting distfile(s), please wait...
/void-packages/common/xbps-src/shutils/common.sh: line 31: cd: /builddir/Grammalecte-1.6.0: No such file or directory
=> ERROR: Grammalecte-1.6.0_1: cannot access wrksrc directory [/builddir/Grammalecte-1.6.0]
```

```
void-packages$ ls masterdir/builddir/
grammalecte  grammalecte-cli.py  grammalecte-server.py  LICENSE.fr.txt
LICENSE.txt  README.txt  setup.py
```

The vanila do_extract seems to not extract in a "${pkgname}-${version}"
directory but in the builddir root. Or maybe Grammalecte do not respect
the tree structure in their released zip.

How should we do?

**Comment by jnbr** [comment]
Setting `create_wrksrc=yes` should work around it.

**Comment by Eluminae** [comment]
> Setting `create_wrksrc=yes` should work around it.

This is just amazing. Fixed! Thanks a lot!

**Comment by Eluminae** [comment]
```
=> ERROR: Grammalecte-1.6.0_1: cannot find unzip or bsdtar bin for extraction.
The command "if [ -z "$XLINT" ]; then docker exec -t void hostrepo/common/travis/build.sh $BOOTSTRAP $ARCH; fi" exited with 1.
```
Some archs miss unzip on travis. What to do ?

**Comment by jnbr** [comment]
Not sure what is going on. It worked on my machine. Our builders didn't like it either, so I added bsdtar to hostmakedepends for now.
Thanks for your contribution.

**Pull request merged**
