### PR TITLE
New package: libpurple-discord-0.9.2023.02.15.git.4a09188

### PR DESCRIPTION
**Pull request by Spacur**
#### Description
Discord plugin for libpurple

#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture: **x86_64**
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - i686 (crossbuild)
  - armv6l (crossbuild)
  - armv7l (crossbuild)

#### Notes
- Has been tested on x86_64 and appears to be working fine at runtime (with pidgin) over the course of several days, however no testing has been made for alternative architectures/musl despite successful builds.
- Authors have never provided versions/releases, latest git commit at the time of writing is being used instead.

### CODE REVIEW

**Comment by abenson** [comment]
> **Package Requirements**
> Software need to be used in version announced by authors as ready to use by the general public - usually called releases. Betas, arbitrary VCS revisions, templates using tip of development branch taken at build time and releases created by the package maintainer won't be accepted.

**Comment by Spacur** [comment]
Hi there @abenson, 

I understand this and left a note regarding this in the notes to inquire further. Given the author has never provided a version ever for this project (And it appears that the author expects users to use the build at the latest commit as the software ready to use by the general public shown by the author pointing to the nightly build for the download) is there any exceptions to this rule? I have additionally used this software at the latest build for several months without issue on 3 different operating systems. https://github.com/EionRobb/purple-discord

If there can be no exceptions whatsoever, I will raise this with the package author instead to see if they can create an official release and hopefully re-raise this pull request per procedure at a later date.

**Comment by classabbyamp** [comment]
There won't be an exception for this

**Comment by Spacur** [comment]
Thanks for confirming

**Pull request closed without merging**
