### PR TITLE
nvidia: update to 470.57.02.

### PR DESCRIPTION
**Pull request by abenson**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [X] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by abenson** [comment]
plz test

**Comment by ericonr** [comment]
Uh https://github.com/void-linux/void-packages/pull/32100

**Comment by ardadem** [comment]
There is new firmware and nvvm compiler library in the package, installed them in #32100. Can you review it?

**Comment by abenson** [comment]
Derp.

**Pull request closed without merging**
