### PR TITLE
mariadb: update to 10.1.45.

### PR DESCRIPTION
**Pull request by rmccask**

### CODE REVIEW

**Comment by sgn** [comment]
Please don't merge this until #22218 merged/settled
unless there's urgent issue addressed by this change.

**Comment by sgn** [comment]
Also, please `[ci skip]` this PR, Travis can't download the tarball.

**Comment by rmccask** [comment]
This can wait until [#22218](https://github.com/void-linux/void-packages/pull/22218) is merged/settled.  I have added [ci skip] but the problem with Travis isn't downloading the tar ball.  The problem is that the build time is around the maximum limit for Travis and some builds timeout.

**Comment by rmccask** [comment]
Is it worth keeping more than one version of mariadb available like an lts?  It looks like 5.5, 10.1, 10.2, 10.3, 10.4 and 10.5 are getting updates currently.  10.5 is still in development.  Debian has mariadb-10.0, 10.1, 10.3 and 10.4.  Arch only has 10.4.  Gentoo has all of them.

**Comment by sgn** [comment]
> Is it worth keeping more than one version of mariadb available like an lts? It looks like 5.5, 10.1, 10.2, 10.3, 10.4 and 10.5 are getting updates currently. 10.5 is still in 
development.

If you could make them not conflicts with each other, I see no reason to decline.

> Debian has mariadb-10.0 (jessie), 10.1 (stretch), 10.3 (bullseye, sid, buster) and 10.4 (experimental).

So Debian supports only 1 version.

> Arch only has 10.4. Gentoo has all of them.

**Pull request closed without merging**
