### PR TITLE
vscode: update to 1.70.0.

### PR DESCRIPTION
**Pull request by shizonic**
#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by paper42** [comment]
cc @atk

**Comment by paper42** [comment]
@atk I don't get a notification when you only upvote a comment, could you approve this PR next time instead?

**Comment by atk** [comment]
Sorry, will do next time.

**Comment by paper42** [comment]
> Sorry, will do next time.

It's not a problem at all, just that I could easily miss it.

**Pull request merged**
