### PR TITLE
quakespasm: update to 0.94.3.

### PR DESCRIPTION
**Pull request by benalb**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by benalb** [comment]
also ping [SolitudeFS](https://github.com/SolitudeSF)
I can take care of this package, recently found my old Quake CD. :)

**Comment by ericonr** [comment]
I don't think that ping works

@SolitudeSF

**Comment by SolitudeSF** [comment]
@benalb go for it, i even forgot it was me who added it.

**Comment by ericonr** [comment]
@benalb ping on adopting package?

**Comment by benalb** [comment]
thought about changing the maintainer in the next update, but, anyways, done.

**Pull request merged**
