### PR TITLE
New package: yambar-1.5.0

### PR DESCRIPTION
**Pull request by travankor**
Waiting for a new release

### CODE REVIEW

**Comment by travankor** [comment]
```
yambar: /usr/lib/libjson-c.so.5: no version information available (required by yambar)
```

**Comment by sgn** [comment]
> ```
> yambar: /usr/lib/libjson-c.so.5: no version information available (required by yambar)
> ```

Where did you see that?

**Comment by travankor** [comment]
Output of yambar when I run in the terminal. I think it's just a warning.

**Comment by travankor** [comment]
ready for review

**Pull request closed without merging**
