### PR TITLE
gnucobol: update to 3.2

### LINKED ISSUE #45612: GnuCOBOL package with missing dependencies (and outdated)
### Is this a new report?

Yes

### System Info

current

### Package(s) Affected

gnucobol

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

_No response_

### Expected behaviour

full support of all features (this is what this issue is about, the update would likely be handled by the update-script), and up-to-date, you can see both when executing `cobc --info`

Note that the [current template](https://github.com/void-linux/void-packages/blob/master/srcpkgs/gnucobol/template) also doesn't use an official GNU mirror for download but a mirror that is not directly related to the GNU project.

The official homepage would be `url="https://www.gnu.org/software/gnucobol/` , the source would be `distfiles="https://ftp.gnu.org/gnu/${pkgname}/${pkgname}-${version}.tar.xz"` (you may also want to download and verify the signature).

For dependencies you may want to see https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=open-cobol (additional dev dependencies for libxml2 and either cjson or json-c, and for all libraries a runtime dependency in gnucobol-libs)

Also note that if you want a make_check_target, then this would be `make_check_target="checkall"` (doing more or less a `make check` and `make test`).

### Actual behaviour

XML and JSON are likely missing (at least they miss the dependencies in https://github.com/void-linux/void-packages/blob/master/srcpkgs/gnucobol/template), version is at 3.1.2 (3.2 is a month old and as no bug reports so far).

### Steps to reproduce

check with `cobc --info`

### PR DESCRIPTION
**Pull request by cinerea0**
#### Testing the changes
- I tested the changes in this PR: **briefly**

I am reaching out to a more experienced user of this package for testing. Closes #45612.

### CODE REVIEW

**Comment by GitMensch** [comment]
Why is that auto-reconfigured? Apart from needing more tools (`automake gettext-devel-tools libtool` would not be necessary otherwise) this won't use the versions of the tools that were tested when doing the boostrap upstream, so there normally should be a good reason for that [some distros _always_ do that _for , but most don't].

There is a lot of output because of configure ending in "mixed" harding options.
I'd suggest to explicit configure with either `--enable-hardening` (obviously making the binary a bit slower) or `--disable-hardening` to fix that, or configure with explicit specifying `CFLAGS=-O -g`.

To ensure that the dependencies that are noted are indeed used it is useful to drop the "guessing" part in configure by making that explicit `--with-db --with-curses=ncursesw --with-json=json-c --with-xml2`.

So you may want to add something like `configure_args="--disable-hardening --with-db --with-curses=ncursesw --with-json=json-c --with-xml2"`

Note for `checkdepends`: only one of wget or curl is needed, the second one is preferred.
Currently only `make test` is run for the test (which uses an external testsuite, therefore those curl).

I'd suggest to do this with `make checkall` instead as this will first run the internal testsuite, then the external one.

The cross-builds fail during "install", it looks like this is happening during "vmove" but as I don't know what they do for whatever reason and if they should work, I cannot comment on those.

**Comment by cinerea0** [comment]
> Why is that auto-reconfigured?

That can sometimes solve crossbuilding install issues. Obviously in this case it did not.

> There is a lot of output because of configure ending in "mixed" hardening options.

Void's packaging philosophy is to leave things as "vanilla" from upstream as possible. Unless there is a specific configuration recommended by upstream, we generally leave it be.

> I'd suggest to do this with make checkall instead as this will first run the internal testsuite, then the external one.

As I mentioned before, the vast majority of the tests from the `check` target fail in Void's build environment.

**Comment by GitMensch** [comment]
> > I'd suggest to do this with make checkall instead as this will first run the internal testsuite, then the external one.
> 
> As I mentioned before, the vast majority of the tests from the `check` target fail in Void's build environment.

That should be solved when adding one of the configure options `--enable-hardening` or `disable-hardening`, especially as the external testsuite passes completely.

**Comment by cinerea0** [comment]
The test cases have been fixed by disabling hardening and defining a custom check step; this will appear in the next push.

I did some investigating and found out what's causing the install failure on cross-compile. Only when cross-compiling, the file `/usr/lib/gnucobol/CBL_OC_DUMP.so` is not generated, this is what gets moved over in that second `vmove` line. Is this file necessary for gnucobol to function?

**Comment by GitMensch** [comment]
Ah, the extras directory and cross compile!

No, it is not necessary and it can be created on the target system after install. It may be possible to create a post install step to do so.

Background: extras contains COBOL sources which are compiled by the generated cobc.

The following options exist to handle that:
* ignore those files (currently there is only one)
* create and install them on the target system manually, if needed
* create and install them via the package manager as post install step on the target system
* have a host version of the same GnuCOBOL version installed and use that to do the compile and link with cross-compile options

**Comment by GitMensch** [comment]
The currently failing test 488 on musl is a bug "not clean handling" in GnuCOBOL. You may want to use the official (not yet upstream) patch found in https://git.adelielinux.org/adelie/packages/-/commit/21fe3ef399c25f030d6657e83cc635335f3a9f40 (0002-errno) [and may also take a fix for a regression (0001-move) live].

The failing in test 818 on musl is "known" from the Adélie CI; if you can provide any insights that would be useful, otherwise you may consider to drop that test for now by running `sed -i tests/testsuite -e "/^818;/d";`.

**Comment by GitMensch** [comment]
As noted, I suggest to consider adding the one patch from Adélie and (at least on musl or general) disable one test that is known to not work on musl via the sed command provided.
That should get all builds passing, so this PR may be merged.

**Pull request merged**
