### PR TITLE
[wip] guile: update to 2.2.4

### PR DESCRIPTION
**Pull request by bobertlo**
Trying to fix underlying issues related to gc which break the current version also (#6522) but this is how far I had gotten. I used `nostrip_files` to clear the guile modules instead of deleting them. I don't know if this is preferrable or just deleting them (#6521)

I don't mean to spam another PR, but this is where I got last night. I'm assuming these files are worth installing since it spends so much time compiling them.

### CODE REVIEW

**Comment by bobertlo** [comment]
This is for #6418 btw. It compiles if `gc` is reverted to 8.0.0, which breaks the current guile template aswell.

**Comment by bobertlo** [comment]
Ok, looks like some dependency updates have fixed cross compiling on this! I just need to work on dependencies now, since this will break them:

- [ ] aisleriot-3.22.7_2
- [ ] autogen-5.18.4_7
- [ ] geda-1.8.2_7
- [ ] gnucash-3.4_1
- [ ] xbindkeys-1.8.6_3

I'm not looking forward to autogen, but since this whole thing has been such a cluster, it might just work with guile upgraded :)

**Comment by bobertlo** [comment]
@pullmoll could you take a look at these? I didn't think it would be such a big change. These are all ready and I made the guile2.0 package just for geda, which seems to compile now, but won't cross compile.

The autogen package has errors identical with master. I'd appreciate input since you maintain pretty much all the packages which aren't orphaned. I just can't figure out geda or autogen, and I've run out of free time on this for a few days.

**Comment by pullmoll** [comment]
No, sorry, I'm busy with my day job and don't have too much time at my hands.
I tried to update guile myself and gave up when I realized the impact the ABI/API changes have on the packages depending on it.

**Comment by bobertlo** [comment]
No problem. I'm just busy too. I could never figure out autogen so it's mostly waiting on that and geda cross compiling, which I did not try very hard on. Just wondered if you had any thoughts on a guile2.0 package or saw something wrong. Hopefully I will have more time for these soon.

**Comment by Gottox** [comment]
stalled since >6 months. please reopen once there's progress.

**Pull request closed without merging**
