### PR TITLE
thunderbird: update to 68.0

### PR DESCRIPTION
**Pull request by q66**
This does a bunch of changes while doing this:

1) synchronize patchset with Firefox (it's the same base)
2) synchronize template with Firefox (add the cross-compiling bits and so on, unrestrict archs)
3) preliminary ppc32 support bits for later (at least the stuff that's guaranteed to be needed)
4) attempt to enable some degree of debug info on 32-bit hosts
5) unconditionally disable gold because there's no point in keeping it enabled

I need someone to test this on `x86_64`, `x86_64-musl`, `i686` at least. And maybe some ARM cross-compiling too, though I can test that myself later, probably.

Built/Tested:

- [x] ppc64le
- [x] aarch64 [build]
- [x] armv7l [build]
- [x] i686
- [x] x86_64
- [x] x86_64-musl

### CODE REVIEW

**Comment by Hoshpak** [comment]
x86_64 works fine

**Comment by q66** [comment]
```
=> Creating thunderbird-68.0_1.aarch64.xbps for repository /host/binpkgs/test ...
=> Creating thunderbird-dbg-68.0_1.aarch64.xbps for repository /host/binpkgs/test/debug ...
```

**Comment by q66** [comment]
Can't build-test `armv7l` since I don't have a crosscompiler ready for it here. I assume it should be fine

**Comment by Hoshpak** [comment]
i686 errors out on oom:

```
 7:16.60 LLVM ERROR: out of memory
 7:16.86 error: Could not compile `gkrust`.
 7:16.86 Caused by:
 7:16.86   process didn't exit successfully: `/usr/bin/rustc --crate-name gkrust toolkit/library/rust/lib.rs --color never --crate-type staticlib --emit=dep-info,link -C opt-level=2 -C panic=abort -C codegen-units=1 -C lto --cfg 'feature="bindgen"' --c
fg 'feature="cubeb-remoting"' --cfg 'feature="cubeb_pulse_rust"' --cfg 'feature="gecko_profiler"' --cfg 'feature="gkrust-shared"' --cfg 'feature="moz_memory"' --cfg 'feature="moz_places"' --cfg 'feature="quantum_render"' --cfg 'feature="servo"' -C meta
data=43bb7b1e146e4088 -C extra-filename=-43bb7b1e146e4088 --out-dir /builddir/thunderbird-68.0/obj-i686-pc-linux-gnu/i686-unknown-linux-gnu/release/deps --target i686-unknown-linux-gnu -C linker=/builddir/thunderbird-68.0/build/cargo-linker -L dependen
cy=/builddir/thunderbird-68.0/obj-i686-pc-linux-gnu/i686-unknown-linux-gnu/release/deps -L dependency=/builddir/thunderbird-68.0/obj-i686-pc-linux-gnu/release/deps --extern gkrust_shared=/builddir/thunderbird-68.0/obj-i686-pc-linux-gnu/i686-unknown-lin
ux-gnu/release/deps/libgkrust_shared-e03409551b436c61.rlib --extern mozilla_central_workspace_hack=/builddir/thunderbird-68.0/obj-i686-pc-linux-gnu/i686-unknown-linux-gnu/release/deps/libmozilla_central_workspace_hack-4b41fd95e63cbed3.rlib -C opt-level
=2 -C debuginfo=2 --cap-lints warn -L native=/builddir/thunderbird-68.0/obj-i686-pc-linux-gnu/i686-unknown-linux-gnu/release/build/lmdb-rkv-sys-1bd04f6620f36165/out` (signal: 6, SIGABRT: process abort signal)
 7:16.86 make[4]: *** [/builddir/thunderbird-68.0/config/makefiles/rust.mk:240: force-cargo-library-build] Error 101
 7:16.86 make[3]: *** [/builddir/thunderbird-68.0/config/recurse.mk:74: toolkit/library/rust/target] Error 2
 7:16.87 make[3]: *** Waiting for unfinished jobs....
```

**Comment by q66** [comment]
Okay. so it's not C++ that runs out of memory, but Rust. I wonder if we can coerce Rust to generate less debuginfo

**Comment by q66** [comment]
As a matter of fact, we can: `-C debuginfo=1`

**Comment by q66** [comment]
Well, maybe this will fix it...

**Comment by jnbr** [comment]
`x86_64-musl` works for me, `armv7l` build completed

**Comment by Hoshpak** [comment]
unfortunately the RUSTFLAGS change did not do the trick. The gkrust build still runs into oom on i686.

**Comment by q66** [comment]
Can you post the failing line like before? I wanna see where and if the `RUSTFLAGS` get put in.

**Comment by Hoshpak** [comment]
Sure, I didn't think of checking for that, seems it is not put in:

```
 6:42.84 LLVM ERROR: out of memory
 6:42.97 error: Could not compile `gkrust`.
 6:42.97 Caused by:
 6:42.97   process didn't exit successfully: `/usr/bin/rustc --crate-name gkrust toolkit/library/rust/lib.rs --color never --crate-type staticlib --emit=dep-info,link -C opt-level=2 -C panic=abort -C codegen-units=1 -C lto --cfg 'feature="bindgen"' --cfg 'feature="cubeb-remoting"' --cfg 'feature="cubeb_pulse_rust"' --cfg 'feature="gecko_profiler"' --cfg 'feature="gkrust-shared"' --cfg 'feature="moz_memory"' --cfg 'feature="moz_places"' --cfg 'feature="quantum_render"' --cfg 'feature="servo"' -C metadata=43bb7b1e146e4088 -C extra-filename=-43bb7b1e146e4088 --out-dir /builddir/thunderbird-68.0/obj-i686-pc-linux-gnu/i686-unknown-linux-gnu/release/deps --target i686-unknown-linux-gnu -C linker=/builddir/thunderbird-68.0/build/cargo-linker -L dependency=/builddir/thunderbird-68.0/obj-i686-pc-linux-gnu/i686-unknown-linux-gnu/release/deps -L dependency=/builddir/thunderbird-68.0/obj-i686-pc-linux-gnu/release/deps --extern gkrust_shared=/builddir/thunderbird-68.0/obj-i686-pc-linux-gnu/i686-unknown-linux-gnu/release/deps/libgkrust_shared-e03409551b436c61.rlib --extern mozilla_central_workspace_hack=/builddir/thunderbird-68.0/obj-i686-pc-linux-gnu/i686-unknown-linux-gnu/release/deps/libmozilla_central_workspace_hack-4b41fd95e63cbed3.rlib -C opt-level=2 -C debuginfo=2 --cap-lints warn -L native=/builddir/thunderbird-68.0/obj-i686-pc-linux-gnu/i686-unknown-linux-gnu/release/build/lmdb-rkv-sys-1bd04f6620f36165/out` (signal: 6, SIGABRT: process abort signal)
 6:42.97 make[4]: *** [/builddir/thunderbird-68.0/config/makefiles/rust.mk:240: force-cargo-library-build] Error 101
 6:42.97 make[3]: *** [/builddir/thunderbird-68.0/config/recurse.mk:74: toolkit/library/rust/target] Error 2
 6:42.97 make[2]: *** [/builddir/thunderbird-68.0/config/recurse.mk:34: compile] Error 2
 6:42.97 make[1]: *** [/builddir/thunderbird-68.0/config/rules.mk:413: default] Error 2
 6:42.97 make: *** [client.mk:125: build] Error 2
 6:43.01 572 compiler warnings present.
```

**Comment by q66** [comment]
Yep, it's not. I guess the build system does not pick up external `RUSTFLAGS` then. I saw a commit a while ago (was 3 years ago or so) which enabled that, I suppose they had to disable it again since. I'll try my alternative method :)

**Comment by q66** [comment]
Alright. I patched the default value in the build system directly now. Please try again, it should probably work now...

**Comment by Hoshpak** [comment]
i686 build succeeds now.

**Comment by q66** [comment]
I think we're good then. This should be ready

**Comment by q66** [comment]
Hm, looks like i missed the `--disable-gold`. Lemme re-test with that

**Comment by q66** [comment]
Well, from looking at the source code, it seems it already picks `bfd` as first choice by default, so that option probably doesn't make any difference... (and on cross systems, where `gold` is not available, it will not try to use it at all) - might as well still explicitly disable it though.

**Comment by q66** [comment]
yep, still builds/works fine

**Pull request merged**
