### PR TITLE
linux: update to 4.17.

### PR DESCRIPTION
**Pull request by nutcase84**

### CODE REVIEW

**Comment by cr6git** [comment]
Good idea, 4.16 is EOL.

**Comment by cr6git** [comment]
Tested: nvidia340-340.107_1 works fine with 4.17.4 !

**Comment by Duncaen** [comment]
Wait, can we do this next time with more oks from other people?

**Comment by cr6git** [comment]
@Duncaen Before merging this I asked on IRC, @Vaelatern and @Gottox agreed. I'm really sorry if I did something wrong.

**Comment by Gottox** [comment]
Are there any known issues with 4.17?

**Comment by Duncaen** [comment]
Not that I know of, but I didn't know that there was an OK from IRC, if the major dkms modules work then I'm fine with changing the default.

**Comment by Vaelatern** [comment]
Hold off for zfs right now.

**Comment by Duncaen** [comment]
4 days too late.

**Comment by Vaelatern** [comment]
lol :)

**Pull request closed without merging**
