### PR TITLE
orage: remove package

### PR DESCRIPTION
**Pull request by paper42**
* abandoned by upstream
* depends on GTK2

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
I prefer to avoid revbumping removed-packages too much, thanks!

**Comment by Anachron** [comment]
But why close this then? Keep it open so you know next time when bumping it to include this one.

**Comment by paper42** [comment]
@Anachron  It was merged without bumping revision of removed-packages, so next time removed-packages is revbumped, it will be included.

**Comment by Anachron** [comment]
Sorry didnt see on my phone.

**Pull request closed without merging**
