### PR TITLE
etc/defaults.conf: point to xbps-create for supported compression formats

### PR DESCRIPTION
**Pull request by AluisioASG**
Seems this didn't get updated in tandem with xbps 0.54.

### CODE REVIEW

**Comment by xtraeme** [comment]
lz4 is also suported

**Comment by AluisioASG** [comment]
Yup, just went back to see if I missed any. Could be better to just point to the xbps-create manpage, no?

**Comment by xtraeme** [comment]
Yeah

**Comment by AluisioASG** [comment]
Alright, how about this?

**Pull request merged**
