### PR TITLE
podman-compose: update to 1.0.6

### PR DESCRIPTION
**Pull request by aadi58002**
#### Testing the changes
- I tested the changes in this PR: YES

### CODE REVIEW

**Comment by realcharmer** [comment]
You should follow the commit and PR naming convention, so it should be "podman-compose: update to 1.0.6" in both cases.

**Comment by aadi58002** [comment]
> You should follow the commit and PR naming convention, so it should be "podman-compose: update to 1.0.6" in both cases.

I will keep that in mind from now on.

**Comment by realcharmer** [comment]
Change the commit message as well, please.
Otherwise the update looks good. Quick testing shows no issues.

**Comment by realcharmer** [comment]
Great stuff, LGTM.

**Pull request merged**
