### PR TITLE
ddcci-dkms: fix update-check, update to 0.4.2, adopt, fix build on `linux5.15`

### PR DESCRIPTION
**Pull request by subnut**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

Contains the changes of #37124

### CODE REVIEW

**Comment by subnut** [comment]
Hey @zenfailure, is it okay if I take over maintainership of this package?

**Comment by zenfailure** [comment]
Hey @subnut, absolutely, you'd be doing me a favor actually.

**Comment by subnut** [comment]
> Is there anything to do on my part?

Nope. Your confirmation is all that's needed. :slightly_smiling_face:

> you'd be doing me a favor

Glad to do so. :grin:

**Comment by ericonr** [comment]
Can you squash the two commits? It's better to have this as a single change.

**Comment by subnut** [comment]
@ericonr Done.

**Pull request merged**
