### PR TITLE
vivaldi: update to 6.0.2979.15.

### PR DESCRIPTION
**Pull request by tororutsu**
#### Testing the changes
- I tested the changes in this PR: **YES**|**briefly**|**NO**

### CODE REVIEW

**Comment by classabbyamp** [comment]
@rafeyu thoughts on bumping to 6.0?

**Comment by rafeyu** [comment]
@classabbyamp yes please! :+1:  Should I update my PR or should you just merge this?

**Comment by classabbyamp** [comment]
I'll merge this

**Comment by tororutsu** [comment]
thanks guys

**Comment by tororutsu** [comment]
@rafeyu can I get some advice on how you update the checksums for this, i had to run all three builds wait for them to fail with the checksum mismatch and then get the new ones. Im sure this is not the proper method?

**Comment by rafeyu** [comment]
@tororutsu What I ofently did is download directly from their site, and check with `sha256sum`. Sometime, I check if it work normally by extract it, and run the binary (amd64 only).

**Comment by tororutsu** [comment]
> @tororutsu What I ofently did is download directly from their site, and check with `sha256sum`. Sometime, I check if it work normally by extract it, and run the binary (amd64 only).

Ok thanks for that! I'll keep that in mind

**Pull request merged**
