### PR TITLE
Update OBS to 30.0.0

### PR DESCRIPTION
**Pull request by the-maldridge**
WIP PR to stage this update so we can submit it when the final release happens.  Since this release deprecates FTL in favor of WHIP, the dependencies for that get added.

### CODE REVIEW

**Comment by Lolzen** [comment]
As the browser plugin is enabled by default, can we get that? 

https://obsproject.com/wiki/Building-OBS-Studio
@Duncaen

**Comment by 10leej** [comment]
Can this PR use the git master branch rather than the release tarballs as I mentioned in #46835 that way websocket support can be enabled?

**Comment by lemmi** [comment]
We can certainly look into adding websocket support once `30.0` has been released. 
Using `master` is [almost certainly out of the question](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements). Same goes for the browser plug-in, since that one has a [rather annoying dependency](https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Linux#prerequisites-1) which requires packaging another browser.

**Comment by m3tav3rse** [comment]
[Upstream  said](https://github.com/obsproject/obs-studio/pull/7475#issuecomment-1663961298) github tarballs will contain all submodules (including websocket) "sometime after the next release".
Upstream issue https://github.com/obsproject/obs-studio/issues/7407

**Comment by Lolzen** [comment]
> We can certainly look into adding websocket support once `30.0` has been released. Using `master` is [almost certainly out of the question](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements). Same goes for the browser plug-in, since that one has a [rather annoying dependency](https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Linux#prerequisites-1) which requires packaging another browser.

For now i'm simply enhancing the default template, it's not that hard to download a second tarbal imho. But i might just miss your point.
https://pastebin.com/Ug9mw7Ln -> modified template

**Comment by the-maldridge** [comment]
@Lolzen the browser plugin is unlikely to ever be accepted to the main template for the stated reasons above.  You can, however, install obs-plugin-browser-bin which may or may not work at any given time.

Websockets are enabled in the build now.

**Comment by Johnnynator** [comment]
> Websockets are enabled in the build now.

Nope, websockets are not in the template/build.

**Pull request merged**
