### PR TITLE
rsyslog: enable omelasticsearch.so

### PR DESCRIPTION
**Pull request by zdykstra**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by zdykstra** [comment]
Checks seem to be taking longer than the timeout threshold. Doh.

**Comment by ericonr** [comment]
If the test works locally you can add `make_check=ci-skip` and mention that it timeouts.

**Comment by zdykstra** [comment]
============================================================================
Testsuite summary for rsyslog 8.2010.0
============================================================================
# TOTAL: 473
# PASS:  420
# SKIP:  11
# XFAIL: 0
# FAIL:  42
# XPASS: 0
# ERROR: 0

I'll see if any of these can reasonably be fixed - the tests that are failing don't seem to have anything to do with `omelasticsearch.so` being enabled.

**Comment by zdykstra** [comment]
Tests run with the current template from `master`:
```
============================================================================
Testsuite summary for rsyslog 8.2010.0
============================================================================
# TOTAL: 473
# PASS:  418
# SKIP:  11
# XFAIL: 0
# FAIL:  44
# XPASS: 0
# ERROR: 0
```

**Pull request merged**
