### PR TITLE
xvfb-run: update to 21.1.11pl2

### PR DESCRIPTION
**Pull request by cinerea0**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by sgn** [comment]
Please stay on stable, unstable will be kept removing when new unstable come out. The stable release will be there for at least 6 years.

**Comment by sgn** [comment]
IOW, please use `21.1.7pl3`

**Comment by sgn** [comment]
1b07242e091d5197519b525bddde32781e1070de

**Comment by cinerea0** [comment]
You didn't give me any time to respond...

**Pull request closed without merging**
