### PR TITLE
xtools: added spdx-licenses-list for linting license field

### PR DESCRIPTION
**Pull request by anjandev**
See: https://github.com/leahneukirchen/xtools/issues/180#issuecomment-624752073

@Chocimier

### CODE REVIEW

**Comment by sgn** [comment]
I'm not really sold on this idea.
`xbps-src` has a `licenses.lst` in `common/travis/license.lst`

I would modify `xlint` to fallback to that file instead.

**Comment by Anachron** [comment]
Sgn if someone installs xtools and uses xlint without a license list it can return false positives this way.

**Comment by sgn** [comment]
> Sgn if someone installs xtools and uses xlint without a license list,
> it can return false positives this way.

I'm fine either ways, that packages doesn't cost me much, anyway.
I'll it to Leah to decide.

**Comment by Chocimier** [comment]
> I would modify xlint to fallback to that file instead.

Could be done too, but now xlint is so simple it don't even know about `common/`, and this is beauty.

@leahneukirchen, comments?

**Comment by sgn** [comment]
OK by leah2 on IRC.

**Pull request closed without merging**
