### PR TITLE
New package: dsda-doom-0.22.5

### PR DESCRIPTION
**Pull request by TwelveEyes**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by TwelveEyes** [comment]
@ericonr Looks like this needs maintainer approval for the CI build tests.

**Comment by TwelveEyes** [comment]
Should be much closer to style standards now.

**Comment by ericonr** [comment]
Ok, it looks way better. Now the only issue is that it's yet another Doom :/

**Comment by TwelveEyes** [comment]
Even though it is another Doom sourceport, I think it's worth including as it is a prboom-plus based port that is still maintained. The prboom-plus package included in the repository right now is 2.5.1.4, which has discontinued development and has been superseded by prboom-plus-um, which dsda-doom is a fork of.

Dsda-doom also is the port leading MBF21 development, and it has Heretic and Hexen support going for it as well.

**Comment by q66** [comment]
maybe let's replace prboom-plus with this one then?

**Comment by ericonr** [comment]
Why not move prboom to use this upstream?

**Comment by TwelveEyes** [comment]
Do you mean have the prboom-plus package point to dsda-doom? Or something else?

**Comment by ericonr** [comment]
Yes, that would be the idea.

**Comment by TwelveEyes** [comment]
Would this be the correct way to setup the prboom-plus template to pull in dsda-doom?

```
# Template file for 'prboom-plus'
pkgname=prboom-plus
version=0.22.5
revision=1
build_style=meta
depends="dsda-doom"
short_desc="PrBoom+ meta package"
maintainer="Gene <elkaufman5@gmail.com>"
license="GPL-2.0-or-later"
homepage="https://github.com/kraflab/dsda-doom"
```

**Comment by q66** [comment]
since nobody seems to feel like merging this, i'll just go ahead

let's not replace prboom-plus yet since this is nocross

**Pull request merged**
