### PR TITLE
python3-redis: update to 4.3.4

### PR DESCRIPTION
**Pull request by ahesford**
@abenson I see no reference to `redis` anywhere in the `ytmdl` repository. Please confirm that removing this dependency is OK.

### CODE REVIEW

**Comment by abenson** [comment]
Correct, it should be added to `python3-spotipy`

**Comment by abenson** [comment]
[Hm, that might cause an issue](https://github.com/plamere/spotipy/blob/master/setup.py#L33)

**Comment by ahesford** [comment]
> [Hm, that might cause an issue](https://github.com/plamere/spotipy/blob/master/setup.py#L33)

No, that limits the maximum version only for Python less than v3.4. I'll move the dependency to spotipy (and also try to convince upstream to make redis an optional dependency, because it's only really required if you opt to use redis for cache handling).

**Comment by abenson** [comment]
Oh, I was just looking at this part. `redis<4.0.0`

**Pull request merged**
