### PR TITLE
flake8: various template changes

### PR DESCRIPTION
**Pull request by icp1994**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by icp1994** [comment]
I should have built it before making PR :facepalm:

**Comment by paper42** [comment]
`make_check=no # FIXME`  would be acceptable in this case since it's just a homepage change

**Comment by icp1994** [comment]
It requires running the `flake8` command itself, i.e., needs installing before running tests.

**Comment by paper42** [comment]
> It requires running the `flake8` command itself, i.e., needs installing before running tests.

awesome, thank you for looking into this

**Pull request merged**
