### PR TITLE
patchelf: update to 0.14.5.

### PR DESCRIPTION
**Pull request by unspecd**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-musl
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - ppc64le-musl

### CODE REVIEW

**Comment by sgn** [comment]
Why don't we use the pre-generated tarball?

**Comment by unspecd** [comment]
@sgn
Are you talking about this file?
https://github.com/NixOS/patchelf/releases/download/0.12/patchelf-0.12.tar.bz2

```console
$ ls -1 masterdir/builddir
patchelf-0.12.20200827.8d3a16e
```

**Comment by ahesford** [comment]
The usual path would be `distfiles="${homepage}/archive/${version}.tar.gz"`, which will untar into the directory `${patchelf}-${version}` and not need `wrksrc` defined.

**Comment by unspecd** [comment]
> ${homepage}/archive/${version}.tar.gz

But that tar does not contain `configure` script.

**Comment by ahesford** [comment]
> > ${homepage}/archive/${version}.tar.gz
> 
> But that tar does not contain `configure` script.

Can it be created with autotools? A `pre_configure` that builds the configure script is preferable to a `wrksrc` variable that contains a commit hash which becomes obsolete with every version update.

**Comment by unspecd** [comment]
> Can it be created with autotools? 

Sure, but as I understand, @sgn is [against](https://github.com/void-linux/void-packages/pull/31104#issuecomment-849279446) this.

**Comment by sgn** [comment]
On 2021-06-02 06:28:46-0700, Evgeny Ermakov ***@***.***> wrote:
> > Can it be created with autotools? 
> 
> Sure, but as I understand, @sgn is [against](https://github.com/void-linux/void-packages/pull/31104#issuecomment-849279446) this.

Well, I didn't know it includes a hash there.
Anyway, I advocated for another approach. I may make a proposal this
weekend.

-- 
Danh

**Comment by ericonr** [comment]
@sgn ok to merge this in the meantime?

**Comment by ahesford** [comment]
I think the now-closed #31522 approach was better.

**Comment by unspecd** [comment]
Updated to 0.14.5.

**Pull request merged**
