### PR TITLE
wxWidgets, wxPython

### PR DESCRIPTION
**Pull request by ahesford**
Our wxWidgets/wxPython stack is pretty old, and it may be more trouble to patch for Python 3.12 than just updating these packages. Thus I would like to:

* Drop `pcsx2`, `perl-Alien-wxWidgets` and `dispcalGUI` (cc: @lemmi). The first two don't seem well-maintained, and all three rely on wxWidgets with GTK2 support that should be retired. `dispcalGUI` also requires the long-past-EOL Python 2.
* With these three dependants gone, we can remove `wxWidgets` and `wxPython`.
* This simplifies the update to `wxWidgets-gtk3` and (hopefully---I'm still working) `wxPython4`.
* While we're at it, we can transition `wxPython4` back to its proper name, just `wxPython`.

[ci skip]

closes #44849

### CODE REVIEW

**Comment by classabbyamp** [comment]
this should enable #44849

**Comment by lemmi** [comment]
Yes, if #44849 works with that, we can finally drop `dispcalGUI`.

**Comment by ahesford** [comment]
There are five failures on an `x86_64` build:
- [ ] OpenCPN
- [ ] audacity
- [ ] codeblocks
- [ ] codelite
- [ ] kicad

**Comment by ahesford** [comment]
All packages build natively after adopting some patches from @sgn in #39491 (plus a few extra for `codeblocks`) and updating `OpenCPN` to 5.8.4 (cc @Johnnynator). I'll start running through all other architectures and also do some run tests.

**Comment by ahesford** [comment]
I pulled in the DisplayCAL changes and fixed the double revbump; now I'm shaking out some bugs when building with other arches. When everything builds cleanly, I'll do some run testing.

**Pull request closed without merging**
