### PR TITLE
mesa: update to version 23.1.4.

### PR DESCRIPTION
**Pull request by SpidFightFR**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x64-GlibC)

Hey guys, it's a little PR to update mesa to the latest release that was published today, a few hours ago.
Best regards - Spid.

### CODE REVIEW

**Comment by Fade-ing** [comment]
Would be nice if this was merged quickly

Since this update fixes a major regression that causes many wine programs to crash on graphic card with OpenGL < 4.6 support
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/23762

**Comment by mhmdanas** [comment]
Can confirm that this works fine for me.

**Comment by HadetTheUndying** [comment]
23.1.5 has now been released.

**Comment by SpidFightFR** [comment]
> 23.1.5 has now been released.

I’ll see what i can do abt that. But it’ll take time. :(

**Comment by Fade-ing** [comment]
Just compiled 23.1.5 yesterday and can confirm it works fine

Both of the 64 bit version and the 32 bit version

`version=23.1.5`
`checksum=3cf88576fdebf24fc4047067936131c90cb6541c27365996b79b661dec1fb153`

**Comment by biopsin** [comment]
Not shure how critical these warnings are but seeing 
```
Run-time dependency libunwind found: NO (tried pkgconfig and cmake)
WARNING: OpenMP found but omp.h missing.
Run-time dependency OpenMP found: NO (tried system)
```
adding libunwind-devel and libgomp-devel to makedepends resolves the configure warnings

**Comment by HadetTheUndying** [comment]
> Not shure how critical these warnings are but seeing 
> ```
> Run-time dependency libunwind found: NO (tried pkgconfig and cmake)
> WARNING: OpenMP found but omp.h missing.
> Run-time dependency OpenMP found: NO (tried system)
> ```
> adding libunwind-devel and libgomp-devel to makedepends resolves the configure warnings
> 
> Edit: 23.1.5 tests ok (x86_64-libc/radeonsi rx570)

Can confirm the warnings at compile time are not there once you update the makedepends. If this PR is indeed stale and no one has opened a new one by tomorrow, I will once I'm home.

**Comment by Fade-ing** [comment]
> Not shure how critical these warnings are but seeing
> 
> ```
> Run-time dependency libunwind found: NO (tried pkgconfig and cmake)
> WARNING: OpenMP found but omp.h missing.
> Run-time dependency OpenMP found: NO (tried system)
> ```
> 
> adding libunwind-devel and libgomp-devel to makedepends resolves the configure warnings
> 
> Edit: 23.1.5 tests ok (x86_64-libc/radeonsi rx570)

Nice catch! This might explains the issue that wine complains about missing libunwind.so.1, which i resolved by installing libunwind package separately

Gonna go rebuild it then

**Comment by SpidFightFR** [comment]
Overlapped by https://github.com/void-linux/void-packages/pull/45974.

**Pull request closed without merging**
