### PR TITLE
telegram-desktop: update to 4.4.1.

### PR DESCRIPTION
**Pull request by timas130**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc

### CODE REVIEW

**Comment by classabbyamp** [comment]
this should be one commit

**Comment by timas130** [comment]
@classabbyamp squashed and rebased

**Comment by timas130** [comment]
@classabbyamp I didn't reset the revision to 1, please approve again. `xlint` passes now. I'm so sorry.

**Comment by timas130** [comment]
Doesn't build on musl because of a linking error relating to `cld3`. I give up for now.

```
/usr/bin/ld: cmake/external/cld3/libexternal_cld3_bundled.a(getonescriptspan_test.cc.o): in function `main':
getonescriptspan_test.cc:(.text.startup+0x0): multiple definition of `main'; Telegram/CMakeFiles/Telegram.dir/SourceFiles/main.cpp.o:main.cpp:(.text.startup+0x0): first defined here
collect2: error: ld returned 1 exit status
```

**Comment by Johnnynator** [comment]
closed with 0cf0904f7719df93542b53e9ba16015a9285521c

**Pull request closed without merging**
