### PR TITLE
swayimg: update to 3.3.

### PR DESCRIPTION
**Pull request by voidbert**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-musl)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - armv6l-musl

#### Notes
Extra dependencies had to be added to fix `librsvg-2.0` not being found by `pkgconfig`.

### CODE REVIEW

**Comment by classabbyamp** [comment]
> Extra dependencies had to be added to fix `librsvg-2.0` not being found by `pkgconfig`.

these should be added to librsvg-devel probably then

**Comment by voidbert** [comment]
> > Extra dependencies had to be added to fix `librsvg-2.0` not being found by `pkgconfig`.
> 
> these should be added to librsvg-devel probably then

Done! I kept things in two separate commits, as two different packages were involved in this PR, but I can make it a single commit if that's preferred.

**Comment by classabbyamp** [comment]
different commits is correct. are the dependencies still needed for swayimg directly?

**Comment by voidbert** [comment]
> different commits is correct. are the dependencies still needed for swayimg directly?

Sorry, my bad. All fixed now.

**Pull request merged**
