### PR TITLE
grim: update to 1.4.1, orphan

### PR DESCRIPTION
**Pull request by Bnyro**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by Duncaen** [comment]
Could you please change the maintainer to `Orphaned <orphan@voidlinux.org>` since they haven't contributed since 2019.

**Comment by Bnyro** [comment]
I would like to adopt the package then if that's fine?

**Comment by Duncaen** [comment]
I would prefer to orphan it for now and adopt it if you updated and/or reviewed/tested the package at least twice. We get a lot of contributors that adopt packages and then never update them again resulting in extra work when reviewing PRs.

**Comment by Bnyro** [comment]
Makes sense, thank you!

**Pull request merged**
