### PR TITLE
adwaita-qt: enable Qt 6 support

### PR DESCRIPTION
**Pull request by dsemy**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, x86-64-glibc

### CODE REVIEW

**Comment by dsemy** [comment]
Cross compile is failing because QT_HOST_PATH isn't set (required when cross compiling with Qt 6 as it turns out).
Not sure how to make this work, the best information I found about this variable are two messages sent to a Debian mailing list by someone who also didn't seem to figure this out.

**Comment by classabbyamp** [comment]
hostmakedepends+=qt6-tools

**Comment by classabbyamp** [comment]
also this seems to *remove* the qt5 version. it's probably going to have to be built twice, once with each version of qt

**Comment by dsemy** [comment]
Yeah you're right I didn't realize that (I was using a local Qt 6 build alongside the current package so I had both versions installed).
Maybe this should be split into two packages?

**Comment by classabbyamp** [comment]
i'm not sure this needs separate packages, maybe something like what qwt does could be done

**Comment by sgn** [comment]
d2ade215f130d0c134cd4810fde8ce25fd45341d

**Pull request closed without merging**
