### PR TITLE
New package: metamath-0.180

### PR DESCRIPTION
**Pull request by xelxebar**

### CODE REVIEW

**Comment by xelxebar** [comment]
In light of the discussion at #17223, I propose this alternative.

**Comment by xelxebar** [comment]
Whoops. I just realized that upstream upgraded while I kept an old version number. Fixed PR.

**Comment by xelxebar** [comment]
No way... they ninja edited the source archive again. I thought this was worked out. Have contacted upstream.

**Comment by xelxebar** [comment]
Okay, so it turns out that the source archive was getting automatically regenerated every day, and zip files are not deterministic on input, hence our hash mismatches. After talking to them, they fixed the archive-building scripts, so we should be good now.

**Comment by xelxebar** [comment]
Okay, so I updated the metamath executable wrapper `mm`.
On a side note, is it even reasonable to include such a thing here?

**Comment by sgn** [comment]
Do they provide constant url?
Something with the same hash regardless of download time?

**Comment by xelxebar** [comment]
@sgn As noted above, the urls should be fixed now. In a later thread, I also asked upstream to push version tags to their GitHub repositories, so we could perhaps use those instead. I'll go ahead and do that now.

**Comment by xelxebar** [comment]
Looks like upstream updated to 0.183 about a week ago. Happily, this also merges in a PR I submitted that fixes the broken `Makefile.am`, so now we can remove the local patch.

**Comment by ericonr** [comment]
What about a versioned source for the PDF? They still don't have one?

**Comment by xelxebar** [comment]
Ugh. Typo in the licenses. Really wish xlint would catch these things.

@ericonr If we want a versioned URL for the PDF, our only option is to typset the LaTeX sources. I did this for Guix and can do the same here if that's reasonable. My thinking was that pulling in texlive as a native dependency might be too much.

**Comment by ahesford** [comment]
I don't think we should be pulling an unversioned PDF. The program has a manpage and you can vdoc README.txt if there's useful information there. Unless the release tarball includes PDF documentation, let people turn to the web site for richer explanation.

**Comment by xelxebar** [comment]
@ahesford Thanks for looking at this. That's reasonable stance. I am happy to remove the pdf if that will get this merged.

That said; the pdf really is the only reasonable local documentation. The man page just provides a terse overview of the internal metamath syntax, and the README only discusses details about building. Upstream's official documentation is the pdf, which is why I figured it makes sense to include it in the package.

Cheers!

**Comment by ahesford** [comment]
The issue is that the package breaks the minute upstream replaces that file with a different version. Maybe you can convince them to bundle the PDF into the release tarball for a future version, then it will be trivial to include. If you want to build the PDF from (versioned) TeX sources, we can consider doing so.

**Comment by ericonr** [comment]
@xelxebar void now includes packaged texlive for all archs, so building the documentation is reasonable, since they don't provide versioned PDFs. The other option is adding a `README.voidlinux` file that links to where one can download the PDF. We don't want to depend on unversioned distfiles, since they unfortunately end up making things a lot more complicated

**Comment by ericonr** [comment]
I will be closing this PR due to inactivity, feel free to re-open it :)

**Pull request closed without merging**
