### PR TITLE
python3-shodan: update to 1.25.0

### PR DESCRIPTION
**Pull request by misuchiru03**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by misuchiru03** [comment]
As noted in #25552, tests will succeed locally if given SHODAN-API-KEY, which is account-based.

**Comment by ericonr** [comment]
Please add `make_check=extended` to the template and leave a comment that one should export that variable in their environment before running tests.

**Comment by misuchiru03** [comment]
Sounds good. Side note, when doing this, `xlint` shows that `make_check=` must come after `checksum` but also that it is a custom variable which should begin with `_`. Checked this against package `efl` and it returns the same.

**Comment by ericonr** [comment]
Yes, see https://github.com/leahneukirchen/xtools/pull/205

**Comment by misuchiru03** [comment]
Looks good. Thanks.

**Pull request merged**
