### PR TITLE
New packages: SuiteSparse-5.10.1, igraph-0.9.4, rankwidth-0.9

### PR DESCRIPTION
**Pull request by tornaria**
Dependency for sage. I compiled sage-9.4 using this (maybe I should add: it is the sage I use every day).

I placed these three packages in one PR because of their dependency.

### CODE REVIEW

**Comment by leahneukirchen** [comment]
`/usr/bin/rw` clashes with the `rw` packages, is it possible to rename this? else add `conflicts=`.

**Comment by leahneukirchen** [comment]
Else drop the binary and the `/usr/share/doc/rw`, we probably won't need it.

**Comment by tornaria** [comment]
> Else drop the binary and the `/usr/share/doc/rw`, we probably won't need it.

It turns out sagemath doesn't need the binary, so I just removed the binary and docs.

In case anyone ever needs the binary, we can rename the binary or make a separate package with `conflicts=` or whatever...

**Comment by tornaria** [comment]
Second force-push because I had forgotten to `git add`.

**Pull request merged**
