### PR TITLE
linux3.16: update to 3.16.82

### PR DESCRIPTION
**Pull request by pullmoll**
This update builds for i686{,-musl} yet it fails to build for
x86_64{,-musl} and I have no clue why.

[ci skip]

### CODE REVIEW

**Comment by pullmoll** [comment]
Here's the last few lines of log when trying to build for `x86_64`:
```
  CC      drivers/tty/serial/8250/8250_core.o
  CC      drivers/tty/serial/8250/8250_pnp.o
  CC      drivers/tty/serial/8250/8250_dma.o
  CC      drivers/tty/serial/8250/8250_early.o
  CC      drivers/tty/serial/8250/8250_pci.o
  LD      drivers/video/fbdev/core/fb.o
  LD      drivers/video/fbdev/core/built-in.o
  LD      drivers/tty/serial/jsm/built-in.o
  LD      drivers/staging/lustre/lustre/obdclass/built-in.o
  LD      drivers/scsi/qla4xxx/built-in.o
  LD      drivers/usb/serial/built-in.o
  LD      drivers/staging/vt6656/built-in.o
  LD      drivers/usb/built-in.o
  LD      drivers/gpu/drm/nouveau/built-in.o
  LD      drivers/gpu/drm/built-in.o
  LD      drivers/staging/vt6655/built-in.o
  LD      drivers/gpu/built-in.o
  LD      drivers/video/fbdev/via/built-in.o
  LD      drivers/staging/lustre/lustre/ptlrpc/built-in.o
  LD      drivers/scsi/qla2xxx/built-in.o
  LD      drivers/video/fbdev/built-in.o
  LD      drivers/scsi/built-in.o
  LD      drivers/staging/built-in.o
  LD      drivers/tty/serial/8250/8250.o
  LD      drivers/video/built-in.o
  LD      drivers/tty/serial/8250/built-in.o
  LD      drivers/tty/serial/built-in.o
  LD      drivers/tty/built-in.o
  LD      drivers/built-in.o
=> ERROR: linux3.16-3.16.82_1: do_build: 'make EXTRAVERSION=${_patchver} ${makejobs} bzImage' exited with 2
=> ERROR:   in do_build() at srcpkgs/linux3.16/template:74
```

Could it be some (host) dependency is missing for 64 bit builds? I already tried to `strace` the build to no avail.

**Comment by xtraeme** [comment]
the real error should be somewhere, try grep -i error log

**Comment by pullmoll** [comment]
Uh, gotcha!
```
arch/x86/ia32/ia32entry.S:98: Error: unsupported instruction `sysexit'
make[2]: *** [scripts/Makefile.build:293: arch/x86/ia32/ia32entry.o] Error 1
make[1]: *** [scripts/Makefile.build:404: arch/x86/ia32] Error 2
```

**Comment by pullmoll** [comment]
BTW: Same issue as with [linux4.4-4.4.213](https://build.voidlinux.org/builders/x86_64_builder/builds/22922/steps/shell_3/logs/stdio)

**Comment by pullmoll** [comment]
Problem seems to be this one: https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commit;h=4b5aaf5f6992319c2c72e080a1a55842640b8732

**Pull request merged**
