### PR TITLE
gnome-sound-recorder: update to 3.38.0

### PR DESCRIPTION
**Pull request by PaperMountainStudio**

### CODE REVIEW

**Comment by ericonr** [comment]
I can't launch it on sway:

```
Gjs-Message: 17:15:34.580: JS LOG: Sound Recorder (org.gnome.SoundRecorder)
Gjs-Message: 17:15:34.580: JS LOG: Version: 3.38.0
Gjs-Message: 17:15:34.692: JS LOG: Not all elements could be addded.
Error: Argument element may not be null

(gnome-sound-recorder:13843): Gjs-CRITICAL **: 17:15:34.692: JS ERROR: TypeError: srcElement is null
_init@resource:///org/gnome/SoundRecorder/js/recorder.js:103:9
_init@resource:///org/gnome/SoundRecorder/js/window.js:48:25
vfunc_activate@resource:///org/gnome/SoundRecorder/js/application.js:113:23
main@resource:///org/gnome/SoundRecorder/js/main.js:47:30
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
@/bin/gnome-sound-recorder:8:17
```

Am I missing a dependency or does it require gnome?

**Comment by PaperMountainStudio** [comment]
I am not sure, I also have sway and it works fine, but I have gnome installed. When I tried uninstalling it, it still worked, but there may be some dependencies left which I installed manually. Could you maybe try installing libhandy1?

**Comment by ericonr** [comment]
I already have that installed/

**Comment by PaperMountainStudio** [comment]
closing, already updated: c8ce95b6a8eafc421807ef1ece04795f272972b7

**Comment by sgn** [comment]
Sorry, I didn't see this PR.

@ericonr glibc works fine, musl has problems.
I can't run full gnome on musl. I guess pulseaudio is required, pulseaudio somehow always run under "pulse" not current users.

**Pull request closed without merging**
