### PR TITLE
New package: abuild-3.7.0

### PR DESCRIPTION
**Pull request by paper42**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by q66** [comment]
substituting ash for sh is no good, it will cause issues (e.g. `/bin/abuild: 2109: Bad substitution`)

**Comment by paper42** [comment]
thank you for noticing, I substituted ash for bash now

**Comment by q66** [comment]
i'm not sure if packaging this is otherwise worthwhile either - i'm using abuild on other distros (with bash it works) but it requires an `apk` installation with a database initialized (which you have to do entirely by hand) and only is safe to use for `rootbld` builds (so it has a high potential of messing up people's systems if used "incorrectly")

**Comment by paper42** [comment]
I used abuild for fetching and getting checksums of distfiles and used dabuild (abuild in a docker container) for building. I am starting to think dabuild isn't that much slower than abuild even for simple actions like getting the checksum. I am starting to doubt it is worth packaging.

**Pull request closed without merging**
