### PR TITLE
gjs: update to 1.78.3.

### PR DESCRIPTION
**Pull request by oreo639**
#### Testing the changes
- I tested the changes in this PR: **briefly**

Supersedes: https://github.com/void-linux/void-packages/pull/48295

### CODE REVIEW

**Comment by oreo639** [comment]
Looked in to the gjs build failure on armv7l-glibc a bit. It also happens with mozjs102, but it doesn't happen when 'native' compiling armv7l with binfmt. I tried using qemu-user-static-7.1.0, which I know worked with cross compiling gjs and the same error occurred.

I assume this is related to the armv7l cross compiler, I'll look in to it more later.

**Comment by chrysos349** [comment]
> Looked in to the gjs build failure on armv7l-glibc a bit.

add `lld` to `hostmakedepends`

**Comment by oreo639** [comment]
> add `lld` to `hostmakedepends`

`lld` works because it pulls in `libxml2`, which pulls in `icu-libs`.
Not sure why that is an issue, I'll look in to it more later.
Thanks for the help.
(`cjs` builds fine because gtk+3 is in `hostmakedepends` which also pulls in `libxml2`)

**Comment by chrysos349** [comment]
> `lld` works because it pulls in `libxml2`, which pulls in `icu-libs`.

I see. And i was wondering why `gcc`  needed `lld` at all to crossbuild for `armv7l`.
No matter, It is a peculiar case.

**Comment by oreo639** [comment]
Alright I found the commit that caused the build failure https://github.com/void-linux/void-packages/commit/736df7da50e147e7280043c69b7f1190a4d2c226

Strange issue.

**Comment by chrysos349** [comment]
sorry to bother you, but what is the ETA on this pr?

**Comment by chrysos349** [comment]
`mozjs115-115.7.0 -> mozjs115-115.8.0`

**Comment by sgn** [comment]
Well, libpsl can work with either icu or libidn2 backend. icu rebuild is painful, thus I switch libpsl to libidn2

**Pull request merged**
