### PR TITLE
New package: pcaudiolib

### PR DESCRIPTION
**Pull request by skmpz**

### CODE REVIEW

**Comment by joey-commits** [comment]
Interesting coincidence. I opened a pull request for this a day after you because I didn't notice your open pull request. Sorry about that. You can maintain it and I will close mine. I would like to point out that you are missing alsa-lib-devel and pulseaudio-devel in makedepends. Are you also trying to get espeak-ng into the repos? That is why I packaged sonic. I am a heavy Orca user and espeak-ng has less audio latency with Orca.

**Comment by skmpz** [comment]
No worries, you can keep yours. Since you're a heavy Orca user, you seem more suitable than me anw, I'll close mine. It would be great if you could add espeak-ng as well! :)

**Comment by joey-commits** [comment]
Ideally,  espeak users could be moved to espeak-ng since the former is unmaintained, but this will take some careful planning to prevent breakage. I know for a fact that speech dispatcher has weird issues when it is built against espeak-ng and espeak at the same time. Also, espeak-ng and espeak cannot coexist on the same system because espeak-ng ships compat links so that older packages supporting espeak can be built against espeak-ng. Another minor issue is an espeakup build issue, but that can be built against espeak-ng with minor changes to its makefile. Sonic is used by espeak-ng for faster speech rates. Just curious, did my packaging sonic cause you to create this pr or was it purely coincidental? As far as I know, espeak-ng is the only thing using libsonic and pcaudiolib etc.

**Comment by skmpz** [comment]
I started working on this because calibre needs espeak-ng now.

**Comment by joey-commits** [comment]
In testing this on my end, I found that there are a few alsa issues fixed in pcaudiolib git that can still be found in pcaudilib stable when using espeakup. I opened an issue upstream for them to release a new maintenance release incorporating the fixes since they are already in git and am hoping they will do that soon.

**Comment by joey-commits** [comment]
IN doing some research, Debian has brought the patches in from git and is duplicating them locally but I would like to avoid doing that.

**Comment by joey-commits** [comment]
I applied the patches to my pcaudiolib package. Can you take a look and see if I did it correctly? I am new to packaging with patches in Void.

**Comment by joey-commits** [comment]
Let me know when you finish with espeak-ng. I will take care of updating and testing espeakup and speech dispatcher.

**Pull request closed without merging**
