### PR TITLE
crun: update to 1.4.2.

### PR DESCRIPTION
**Pull request by natrys**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Review by paper42 — COMMENTED** [review]
can we replace `do_check()` with `make_check=extended`?

**Comment by natrys** [comment]
@paper42 don't think that's semantically equivalent. If I remember, it was done like this mostly to stop tests from running in CI (they don't even work locally because of chroot), and probably because `ci-skip` wasn't a thing yet. So I would think equivalent would be `make_check=ci-skip` altogether, should I do that instead?

**Comment by paper42** [comment]
> they don't even work locally because of chroot

Then we need to fix them, skip some of them or disable them.

**Comment by leahneukirchen** [comment]
4242fb76e47678e45f0141611cd8ed92c3d802c1

**Pull request closed without merging**
