### PR TITLE
New package: rpi-libcamera:20230303

### PR DESCRIPTION
**Pull request by strec007**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64
  - aarch64-musl

### CODE REVIEW

**Comment by strec007** [comment]
armv6l does not link. Filed an issue with the author.

**Comment by classabbyamp** [comment]
that's fixable, `grep NO_ATOMIC srcpkgs/` to see how to fix it

**Comment by strec007** [comment]
> that's fixable, `grep NO_ATOMIC srcpkgs/` to see how to fix it

Thank you for your helpful comment.

**Comment by strec007** [comment]
Closing. Changes are represented in PR #42579.

**Pull request closed without merging**
