### PR TITLE
taglib: rebuild for gcc stdc++ dropping gcc4 compat

### PR DESCRIPTION
**Pull request by jnbr**
fixes https://github.com/void-linux/void-packages/issues/1126

### CODE REVIEW

**Comment by bra1nwave** [comment]
Hm, strange. `taglib` was already rebuild https://github.com/void-linux/void-packages/commit/1bf037c0c8dc0805a4c4623b8a8dd62e683f5244...

**Comment by jnbr** [comment]
Strange indeed. Should have checked the git log …
It might fix the problem with mixxx but gcc compat doesn't seem to be the reason here, so I'm closing this.

**Comment by bra1nwave** [comment]
I believe that `mixxx` needs a rebuild.

**Comment by jnbr** [comment]
I believe so, too. My masterdir was outdated, so my local taglib was built with old abi.

**Comment by bra1nwave** [comment]
Yeah, `protobuf` and `mixxx` need a rebuild. Just tried it out and everything works as expected.
Also rebuilding `protobuf` will break some stuff like `cura` for example...

**Comment by cr6git** [comment]
Linux seems so fragile in the end... pretty ridiculous.

**Comment by cr6git** [comment]
@jnbr just to say, it doesn't fix the issue https://github.com/void-linux/void-packages/issues/1126

**Pull request closed without merging**
