### PR TITLE
libwacom: update to 2.5.0

### PR DESCRIPTION
**Pull request by hervyqa**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-musl)

Screenshot_20220625_143106

### CODE REVIEW

**Comment by hervyqa** [comment]
```
[0/1] Running all tests.
1/8 libwacom:all / files-in-git                  SKIP            0.01s   exit status 77
2/8 libwacom:all+valgrind / test-load            OK              0.14s
3/8 libwacom:all+valgrind / test-tablet-validity OK              0.16s
4/8 libwacom:all+valgrind / test-stylus-validity OK              0.05s
5/8 libwacom:all+valgrind / test-svg-validity    OK              0.10s
6/8 libwacom:all+valgrind / test-dbverify        OK              0.45s
7/8 libwacom:all / test-ltversion                OK              0.01s
8/8 libwacom:all / pytest                        FAIL           28.94s   exit status 1
```
Any suggestion?
@paper42

**Comment by classabbyamp** [comment]
the reverse shlibdeps of libwacom should be bumped for this, there's a change to the so version.

re: pytest: it seems that the test that's failing is trying to use [these files](https://github.com/linuxwacom/libwacom/tree/libwacom-2.3.0/data) but isn't finding them

**Comment by 0-st** [comment]
@hervyqa Did you get version 2.4.0 to build?

**Comment by hervyqa** [comment]
> @hervyqa Did you get version 2.4.0 to build?

I haven't tried it yet.

**Comment by classabbyamp** [comment]
disable those tests or add the files

**Comment by hervyqa** [comment]
isn't it already disabled?
```
configure_args+=" -Dtests=disabled"
```

how to add the files?

**Comment by classabbyamp** [comment]
look at the line before that:

```sh
if [ -z "${XBPS_CHECK_PKGS}" ]; then
        configure_args+=" -Dtests=disabled"
```

if you want to add the files, add them as a distfile

**Comment by hervyqa** [comment]
maybe it has something to do with this issue https://github.com/linuxwacom/libwacom/issues/515

**Comment by mhmdanas** [comment]
See my PR https://github.com/void-linux/void-packages/pull/41569, which should fix the test failure.

**Comment by hervyqa** [comment]
fix: https://github.com/void-linux/void-packages/pull/41569

**Pull request closed without merging**
