### PR TITLE
kodi-addon-inputstream-adaptive: update to 19.0.7

### PR DESCRIPTION
**Pull request by hk0O7**
Bump version to 19.0.7 (latest one supported by Matrix).

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64

### CODE REVIEW

**Comment by abenson** [comment]
Please update the commit message to following [convention](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#committing-your-changes).

It should say: `kodi-addon-inputstream-adaptive: update to 19.0.7.`

You can edit your commit message by amending the commit:

    $ git commit --amend

This will open an editor allowing you to edit the commit message, then save and quit. Next, force push to your branch.

    $ git push -f

**Comment by hk0O7** [comment]
Fixed `revision` field as it should have been set to `1`.

**Comment by hk0O7** [comment]
It looks as if the lint template in the newly failed PR __Check build / Lint templates__ [job](https://github.com/void-linux/void-packages/actions/runs/6410524637/job/17439706536)'s regex does not take the Kodi release name suffix (`_${_kodi_release}`) into account:
```
/archive/refs/tags/(v?|\Qkodi-addon-inputstream-adaptive\E[-_])?\K[\d.]+(?=\.tar\.gz")
```
How can we go about this?

**Comment by hk0O7** [comment]
> ```
> /archive/refs/tags/(v?|\Qkodi-addon-inputstream-adaptive\E[-_])?\K[\d.]+(?=\.tar\.gz")
> ```
Added `/refs/tags/` to `${distfiles}` as (also) required by the regex.

**Comment by hk0O7** [comment]
@abenson could you or one of the maintainers please check on the current [workflow job](https://github.com/void-linux/void-packages/actions/runs/6643018998) (stuck pending approval)?

**Comment by hk0O7** [comment]
Bump.

**Pull request closed without merging**
