### PR TITLE
Add ${VIDEOLAN_SITE}

### PR DESCRIPTION
**Pull request by tibequadorian**
[ci skip]

#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by tibequadorian** [comment]
@paper42

**Comment by tibequadorian** [comment]
@Hoshpak could you take a look at this?

**Comment by Duncaen** [comment]
What is the point of this, is there anything to gain from using variables?

**Comment by tibequadorian** [comment]
> What is the point of this, is there anything to gain from using variables?

It makes it easier to switch to a mirror

>This is useless, there is no repetition, we just set the distfiles once, adding the variable into the copied download link is more work.
It also makes it harder to just copy the download link out of the template.

Sorry, I don't understand how this is different to other `*_SITE` variables, can you explain?

**Comment by Duncaen** [comment]
> Sorry, I don't understand how this is different to other `*_SITE` variables, can you explain?

Its not, I'm also questioning its value of the other examples.

We just haven't added any new `_SITE` variables in 4 years so its just coming up now again.

**Comment by tibequadorian** [comment]
> Its not, I'm also questioning its value of the other examples.

Didn't know that the use of these variables is controversial. In this and some other cases I see its value for switching to a mirror.

**Pull request merged**
