### PR TITLE
New package: universal-ctags-5.9.20210131.0

### PR DESCRIPTION
**Pull request by Gottox**

### CODE REVIEW

**Comment by leleliu008** [comment]
you shoud install [GNU libiconv](https://www.gnu.org/software/libiconv/) rather than using the `musl iconv`, the reason is [here](https://wiki.musl-libc.org/functional-differences-from-glibc.html)

It seems that we can not install `GNU libiconv` via `xbps`, we can install from source, reference instructions as following:
```
curl -LO https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.16.tar.gz
tar vxf libiconv-1.16.tar.gz
cd libiconv-1.16
./configure --enable-extra-encodings
make
make install
```

**Comment by ericonr** [comment]
@Gottox why prefer a new package instead of an update, as in #28885 ?

@leleliu008 do they use the GNU extensions with `//` and such ? :/

**Comment by leleliu008** [comment]
> @leleliu008 do they use the GNU extensions with `//` and such ? :/

I don't understand what you mean, I hope you can tell me in details, thank you!

**Comment by leleliu008** [comment]
@Gottox 
```
pre_configure() {
	autoreconf -fi
}
```
change to
```
pre_configure() {
	./autogen.sh
}
```
`./autogen.sh` do more things, not only run `autoreconf -fi`

**Comment by ericonr** [comment]
```
	if type perl > /dev/null; then
		for i in ${ctags_files}; do
			o=${i%.ctags}.c
			echo "optlib2c: translating $i to $o"
			if ! ./misc/optlib2c $i > $o; then
				echo "failed in running optlib2c" 1>&2
				exit 1
			fi
		done
	else
		for i in ${ctags_files}; do
			o=${i%.ctags}.c
			echo "use pre-translated file: $o"
		done
	fi
```

I'm okay with using the pre-translated stuff...

> I don't understand what you mean, I hope you can tell me in details, thank you!

The main difference between musl and glibc iconv is that glibc allows `<enconding>//<suffix>` as parameters to `iconv_open`, which change how the function behaves. I will check out the test suite locally to see what's wrong.

**Comment by ericonr** [comment]
IMO just disable those tests specifically. They try to use an encoding not supported by musl (`cp932`), and unless that's extremely common (and I hope not), it's no reason to introduce `libiconv` into Void.

**Comment by Gottox** [comment]
Actually I think we should go with the update. What do you think?

**Pull request closed without merging**
