### PR TITLE
Update lf to r5

### PR DESCRIPTION
**Pull request by TeddyDD**
moved form old repo
https://github.com/voidlinux/void-packages/pull/14583

### CODE REVIEW

**Comment by maxice8** [comment]
can squash both to the same commit.

**Comment by TeddyDD** [comment]
sure, why not.

**Comment by maxice8** [comment]
i mean, do squash all changes to the same package into the same commit.

**Comment by TeddyDD** [comment]
Done. Why though? I thought it's good to have all versions as separate commits just in case someone would want to build older versions of package?

**Comment by maxice8** [comment]
On Sat, Jun 16, 2018 at 09:05:34AM -0700, Daniel Lewan wrote:
> Done. Why though? I thought it's good to have all versions as separate commits just in case someone would want to build older versions of package?
> 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/24#issuecomment-397822211

it is really superfluous people can just change the version= field and rebuild the package.

**Pull request closed without merging**
