### PR TITLE
vkd3d: fix build.

### LINKED ISSUE #24010: FTBFS: vkd3d
### System

Fails on all systems.

* package:  
  vkd3d-1.1

### Expected behavior

Builds.

### Actual behavior

Fails with

```
libs/vkd3d/vkd3d_private.h:680:54: error: 'VK_PIPELINE_BIND_POINT_RANGE_SIZE' undeclared here (not in a function); did you mean 'VK_PIPELINE_BIND_POINT_MAX_ENUM'?
  680 |     struct vkd3d_pipeline_bindings pipeline_bindings[VK_PIPELINE_BIND_POINT_RANGE_SIZE];
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                      VK_PIPELINE_BIND_POINT_MAX_ENUM
make[1]: *** [Makefile:1084: libs/vkd3d/vkd3d_main.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from libs/vkd3d/resource.c:19:
libs/vkd3d/vkd3d_private.h:680:54: error: 'VK_PIPELINE_BIND_POINT_RANGE_SIZE' undeclared here (not in a function); did you mean 'VK_PIPELINE_BIND_POINT_MAX_ENUM'?
  680 |     struct vkd3d_pipeline_bindings pipeline_bindings[VK_PIPELINE_BIND_POINT_RANGE_SIZE];
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                      VK_PIPELINE_BIND_POINT_MAX_ENUM
ar: `u' modifier ignored since `D' is the default (see `U')
In file included from libs/vkd3d/state.c:20:
libs/vkd3d/vkd3d_private.h:680:54: error: 'VK_PIPELINE_BIND_POINT_RANGE_SIZE' undeclared here (not in a function); did you mean 'VK_PIPELINE_BIND_POINT_MAX_ENUM'?
  680 |     struct vkd3d_pipeline_bindings pipeline_bindings[VK_PIPELINE_BIND_POINT_RANGE_SIZE];
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                      VK_PIPELINE_BIND_POINT_MAX_ENUM
make[1]: *** [Makefile:1084: libs/vkd3d/resource.lo] Error 1
make[1]: *** [Makefile:1084: libs/vkd3d/state.lo] Error 1
In file included from libs/vkd3d/device.c:19:
libs/vkd3d/vkd3d_private.h:680:54: error: 'VK_PIPELINE_BIND_POINT_RANGE_SIZE' undeclared here (not in a function); did you mean 'VK_PIPELINE_BIND_POINT_MAX_ENUM'?
  680 |     struct vkd3d_pipeline_bindings pipeline_bindings[VK_PIPELINE_BIND_POINT_RANGE_SIZE];
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                      VK_PIPELINE_BIND_POINT_MAX_ENUM
make[1]: *** [Makefile:1084: libs/vkd3d/device.lo] Error 1
In file included from libs/vkd3d/utils.c:19:
libs/vkd3d/vkd3d_private.h:680:54: error: 'VK_PIPELINE_BIND_POINT_RANGE_SIZE' undeclared here (not in a function); did you mean 'VK_PIPELINE_BIND_POINT_MAX_ENUM'?
  680 |     struct vkd3d_pipeline_bindings pipeline_bindings[VK_PIPELINE_BIND_POINT_RANGE_SIZE];
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                      VK_PIPELINE_BIND_POINT_MAX_ENUM
make[1]: *** [Makefile:1084: libs/vkd3d/utils.lo] Error 1
In file included from libs/vkd3d/command.c:20:
libs/vkd3d/vkd3d_private.h:680:54: error: 'VK_PIPELINE_BIND_POINT_RANGE_SIZE' undeclared here (not in a function); did you mean 'VK_PIPELINE_BIND_POINT_MAX_ENUM'?
  680 |     struct vkd3d_pipeline_bindings pipeline_bindings[VK_PIPELINE_BIND_POINT_RANGE_SIZE];
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                      VK_PIPELINE_BIND_POINT_MAX_ENUM
```

### Steps to reproduce the behavior

Build vkd3d.

---

I can't see any further developments on their repo, will have to try to search for / create some patches for new Vulkan headers, assuming that's the issue.

### PR DESCRIPTION
**Pull request by ericonr**
Fixes #24010

### CODE REVIEW

**Comment by ericonr** [comment]
@Hoshpak @st3r4g does this look ok?

**Comment by st3r4g** [comment]
It is fixed on master it seems: https://source.winehq.org/git/vkd3d.git/commitdiff/9b03ebde858fa3e6da5cbd404a2ee3775e6be919

**Comment by ericonr** [comment]
I had checked the GH repo instead of their website. Thanks!

**Comment by ericonr** [comment]
Damn, it doesn't apply cleanly :/

**Comment by ericonr** [comment]
Backporting the fix is easy enough, but it seems to depend on other fixes around the code base. Lots of compile errors.

**Comment by st3r4g** [comment]
I don't get errors with [this](https://gist.github.com/st3r4g/a8d138c3e16f12f3bb81a242d5bb5ff8). Hope that's correct.

**Comment by ericonr** [comment]
Thanks! Will try to test with some game.

**Comment by Hoshpak** [comment]
lgtm

**Pull request merged**
