### PR TITLE
coreutils: update to 9.5.

### PR DESCRIPTION
**Pull request by iFoundSilentHouse**
- I tested the changes in this PR: **briefly**
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures:
  - aarch64-musl

Split buffer bug was fixed in https://github.com/coreutils/coreutils/commit/c4c5ed8f4e9cd55a12966d4f520e3a13101637d9 commit. So patch no longer needed

### CODE REVIEW

**Comment by classabbyamp** [comment]
> I tested the changes in this PR: briefly

something as core as coreutils should be tested more than briefly

**Comment by iFoundSilentHouse** [comment]
How can I prevent make_check from skipping when cross-compiling? Or it's better to create separate x86_64-musl prefix?

**Comment by classabbyamp** [comment]
you can't run tests when cross-compiling

see the readme for the musl masterdir

**Comment by iFoundSilentHouse** [comment]
Tests that fail locally on x86_64-musl : join, expr, cut, uniq, dd/no-allocate

**Comment by iFoundSilentHouse** [comment]
test-canonicalize.c patch source: https://www.mail-archive.com/bug-coreutils%40gnu.org/msg33507.html

**Comment by iFoundSilentHouse** [comment]
I'm already using it for 5 days, though imo it needs more testing. @classabbyamp would you mind adding ```needs-testing``` label to this PR?

**Comment by iFoundSilentHouse** [comment]
Which changes were tested: 
 - cp, mv, cat, split, sort. This utils were changed fundamentally.
 - mv --exchange
 - env -a
 - chgrp --from=OWNER:GROUP

**Pull request closed without merging**
