### PR TITLE
New package: fastfetch-1.12.2

### PR DESCRIPTION
**Pull request by AntonIXO**
#### Testing the changes
- I tested the changes in this PR: YES

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): YES

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-musl
  - armv6l

### CODE REVIEW

**Comment by classabbyamp** [comment]
see https://github.com/void-linux/void-packages/pull/38310

**Comment by AntonIXO** [comment]
I am not the only one who wants this package. And this is not just another theme, because it's provides additional and better functionality compared to neofetch. 

Anyway, cool setups from unixporn nicely promotes void linux;)

> see #38310

**Comment by sgn** [comment]
> Anyway, cool setups from unixporn nicely promotes void linux;)

That is a negative point!

**Comment by AntonIXO** [comment]
> That is a negative point!

Why?)

**Pull request closed without merging**
