### PR TITLE
mesa: update to version 24.0.7.

### PR DESCRIPTION
**Pull request by SpidFightFR**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x64-musl

### CODE REVIEW

**Comment by SpidFightFR** [comment]
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x64-musl

A little hotfix up to date.

**Comment by SpidFightFR** [comment]
apparently errors are related to this https://github.com/mesonbuild/meson/issues/12973, should we revert the upate to meson 1.4.0 i did, while this gets fixed in upstream ?

**Comment by SpidFightFR** [comment]
> this seems to fix the issue: #50262

Noted, i'll try to pull your changes to re-try building mesa for arm.

I'll keep you in touch

**Comment by zlice** [comment]
includes kotor fix for dg2/arc/a770 :+1:

**Comment by SpidFightFR** [comment]
> includes kotor fix for dg2/arc/a770 👍

intel fixes for arc GPUs ?

**Comment by zlice** [comment]
> intel fixes for arc GPUs ?

ya, it's in the changelog. there should be another coming for fallout 3 / timbr(?) tiling they added in 24

**Comment by SpidFightFR** [comment]
> > intel fixes for arc GPUs ?
> 
> ya, it's in the changelog. there should be another coming for fallout 3 / timbr(?) tiling they added in 24

that's cool ! i've seen [some videos](https://youtu.be/BHmEYw42Otk?si=XRnlUZ8GKZy9VZrk) of some benchmarks lately, it's amazing how intel is progressing on Linux.

Is the support better here than on Windows ? or is it something similar ?

**Pull request merged**
