### PR TITLE
offlineimap: update to 8.0.0; remove dispensable py2 deps

### PR DESCRIPTION
**Pull request by icp1994**
#### Testing the changes
- I tested the changes in this PR: **NO**

#### Local build testing
- I built this PR locally for my native architecture, x86_64

This update migrates the package to python 3. Two of the python 2 dependencies under the old full-deptree don't have any more dependent packages. I removed one of them outright. For the other, which provided a python 3 counterpart as subpackage, removed the python 2 package and converted the python 3 symlinked package to be its own module.

I **DID NOT** do any significant runtime testing on the updated `offlineimap` package expect for installing and running `--version`, `--help` etc.

### CODE REVIEW

**Comment by leahneukirchen** [comment]
Do not merge without my approval please.

**Comment by leahneukirchen** [comment]
GitHub Actions doesn't do IPv6, please disable these tests too.

**Comment by icp1994** [comment]
Maybe I got the commit order wrong? Seemed okay to me but some builds are confused about not finding the `imaplib2` lib while others work fine :/

**Comment by leahneukirchen** [comment]
python3-imaplib2 needs to be in hostmakedepends too if it's needed during build

**Comment by icp1994** [comment]
Ah, everything under `$depends` of `offlineimap` were needed for building too. But I never noticed anything locally since they were always getting pulled in for `checkdepends`. That's my guess since every CI with test passed the build.

**Comment by leahneukirchen** [comment]
Used it for three days, seems to work fine and even is a bit faster.

**Comment by classabbyamp** [comment]
@leahneukirchen still working well? can this be merged?

**Pull request merged**
