### PR TITLE
mpv: update to 0.34.0.

### PR DESCRIPTION
**Pull request by dm1tz**
Support for libplacebo older than v3.104.0 was dropped in https://github.com/mpv-player/mpv/commit/7c4465cefb27d4e0d07535d368febdf77b579566.

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by travankor** [comment]
Seems like there's a build failure for libplacebo and armv6.

**Comment by dm1tz** [comment]
> Seems like there's a build failure for libplacebo and armv6.

Yeah, smth to do with atomic lib. I think it'd be better to use previous [3.120.3 ](https://github.com/haasn/libplacebo/releases/tag/v3.120.3) release since armv6 succeeds with that one.

**Comment by paper42** [comment]
> Yeah, smth to do with atomic lib. I think it'd be better to use previous [3.120.3 ](https://github.com/haasn/libplacebo/releases/tag/v3.120.3) release since armv6 succeeds with that one.

let's fix it instead:
```sh
if [ "$XBPS_TARGET_NO_ATOMIC8" ]; then
	makedepends+=" libatomic-devel"
	LDFLAGS+=" -latomic"
fi
```

Please do not open new PRs like #33880, instead force push to this PR.

**Comment by dm1tz** [comment]
> > Yeah, smth to do with atomic lib. I think it'd be better to use previous [3.120.3 ](https://github.com/haasn/libplacebo/releases/tag/v3.120.3) release since armv6 succeeds with that one.
> 
> let's fix it instead:
> 
> ```shell
> if [ "$XBPS_TARGET_NO_ATOMIC8" ]; then
> 	makedepends+=" libatomic-devel"
> 	LDFLAGS+=" -latomic"
> fi
> ```
> 
> Please do not open new PRs like #33880, instead force push to this PR.

Got it. Thanks for the tip, I've tried that already but still get the same undefined reference error.

**Comment by paper42** [comment]
> Got it. Thanks for the tip, I've tried that already but still get the same undefined reference error.

Are you sure?
```
=> Registering new packages to /host/binpkgs/mpv
index: added `libplacebo-4.157.0_1' (armv6l-musl).
index: added `libplacebo-devel-4.157.0_1' (armv6l-musl).
index: 2 packages registered.
```

**Comment by dm1tz** [comment]
> > Got it. Thanks for the tip, I've tried that already but still get the same undefined reference error.
> 
> Are you sure?
> 
> ```
> => Registering new packages to /host/binpkgs/mpv
> index: added `libplacebo-4.157.0_1' (armv6l-musl).
> index: added `libplacebo-devel-4.157.0_1' (armv6l-musl).
> index: 2 packages registered.
> ```

Well, let's give it a try then.

**Comment by paper42** [comment]
libplacebo build was failing, no? So why are you trying to fix atomics in mpv?

**Review by paper42 — CHANGES_REQUESTED** [review]
Each package update should have exactly one commit in this PR. The mpv commit shouldn't contain the libplacebo update.

**Comment by dm1tz** [comment]
> libplacebo build was failing, no? So why are you trying to fix atomics in mpv?

That was dumb, sorry.


> Each package update should have exactly one commit in this PR. The mpv commit shouldn't contain the libplacebo update.

Should be good to go now.

**Review by paper42 — APPROVED** [review]

**Pull request merged**
