### PR TITLE
cups: replace `xdg-open` by `gio open` from glib

### PR DESCRIPTION
**Pull request by concatime**

### CODE REVIEW

**Comment by Hoshpak** [comment]
Is there any compelling reason to change this, something wrong with xdg-utils?

**Comment by concatime** [comment]
glib has a LOT more chance of being already on the system. In my case, I have no other package beside cups that depends on xdg-utils, but 73 for glib.

**Comment by Chocimier** [comment]
xdg-utils is 320KB package with no dependencies. Is it too much?

If it is, I would rather made wrapper from gio to xdg-utils, and depend on virtual package provided by them both than patch every package using latter.

**Comment by concatime** [comment]
> Is it too much?

_I_ consider it as too much because it can be avoided (Occam's razor), but I may be wrong and don’t want to impose this PR. This patch is a suggestion.

No need to change every other packages, I’ve submitted this patch just to get rid of a useless dependency on *my* system, and see if it may also be relevant for other people.

If you have multiple packages from the same set (say MATE or XFCE) that require xdg-utils, then we should keep `xdg-open` and not change to `gio open`. But in this case, cups is “linked” to cups-filters, which depends on glib (`glib-2.60.6_1 (remove) breaks installed pkg cups-filters-1.25.2_1`). So it makes sens for cups to also use glib, instead of a new package.

**Comment by xtraeme** [comment]
We use what upstream uses, thanks for the patch anyway.

**Pull request closed without merging**
