### PR TITLE
wstunnel: update to 8.5.4

### PR DESCRIPTION
**Pull request by cinerea0**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by cinerea0** [comment]
Version 8.5.2 (the latest as of this comment) requires Rust 1.75.

**Comment by leahneukirchen** [comment]
Sure it requires?

**Comment by cinerea0** [comment]
This is the error I get when compiling the new latest version (8.5.4):
```
error[E0658]: use of unstable library feature 'file_set_times'
  --> src/tunnel/tls_reloader.rs:89:26
   |
89 |             let _ = file.set_modified(SystemTime::now()).map_err(|err| {
   |                          ^^^^^^^^^^^^
   |
   = note: see issue #98245 <https://github.com/rust-lang/rust/issues/98245> for more information
```

That feature was stabilized in Rust 1.75. However, it can be made to compile by commenting out one small block that supports an edge case (see https://github.com/erebe/wstunnel/issues/209#issuecomment-1873437744). What do you think?

**Comment by leahneukirchen** [comment]
sgtm, even if 1.75 will land soon i assume.

**Pull request merged**
