### PR TITLE
Update Vulkan to v1.2.135

### PR DESCRIPTION
**Pull request by wundrweapon**
It hasn't been updated on Void since December, and newer games may expect later Vulkan versions.  
I'm still very new both to pull requesting in general and to xbps packaging, so please let me know if there's something I totally missed.

### CODE REVIEW

**Comment by wundrweapon** [comment]
Tested MW3 multiplayer, DOOM (2016), and Wolfenstein II all through DXVK; no trouble to report. Interestingly, performance metrics from Wolfenstein and DOOM suggest that the loader is on v1.2.133 though it definitely isn't. Not a Void issue, for sure.

**Comment by rwt3k** [comment]
Please add `Vulkan-Tools` and `Vulkan-ValidationLayers` to the PR.

**Comment by wundrweapon** [comment]
@rwt3k good idea; done. VVL doesn't have a 135 version, and I'm not sure how to test either package (having never used them).

Also, I'm starting to wonder whether my previous testing was moot. It seems SteamPlay has its own Vulkan build it runs so people needn't install it themselves. Maybe I'm wrong here; I sure want to be(!)

**Comment by rwt3k** [comment]
> and I'm not sure how to test either package (having never used them).
>
I'm not sure, but I think they are development libs.

> Also, I'm starting to wonder whether my previous testing was moot. It seems SteamPlay has its own Vulkan build it runs so people needn't install it themselves. Maybe I'm wrong here; I sure want to be(!)
>
It is still necessary to have Vulkan installed to run native games or through Steamplay (d9vk, dxvk) and if you want to use MangoHud as an overlay.

**Comment by st3r4g** [comment]
To amend an erratic commit (and edit the commit history in general), use `git rebase -i <...>` and then force push the branch

**Comment by wundrweapon** [comment]
Think I should do that now?

**Comment by xtraeme** [comment]
yes, there's a dup commit message

**Comment by wundrweapon** [comment]
I'm surprised with how smoothly that went. Just four commits now, each just a single update.

**Pull request merged**
