### PR TITLE
jamulus: update to 3.9.1

### PR DESCRIPTION
**Pull request by 38github**
Updated version and checksum. Built correctly and runs.

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64 (Glibc)

### CODE REVIEW

**Comment by classabbyamp** [comment]
commit message should be `jamulus: update to 3.9.1.`

**Comment by 38github** [comment]
What is "Linting template" that fail?

**Comment by paper42** [comment]
This PR should contain one commit with the correct commit message as documented in CONTRIBUTING.md.

**Comment by 38github** [comment]
Anyone capable wanting to update Jamulus? I need to learn the package update procedure before I try updating a package again.

**Comment by astralchan** [comment]
If you want to update it, just rebase the last two commits and squash them to one: "jamulus: update to 3.9.1"

**Pull request closed without merging**
