### PR TITLE
qt6-webengine: enable proprietary codecs

### PR DESCRIPTION
**Pull request by xegrox**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-LIBC)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-musl

[ci skip]

### CODE REVIEW

**Comment by sgn** [comment]
No, enable proprietary codecs will prevent us from redistribution.

**Comment by xegrox** [comment]
> No, enable proprietary codecs will prevent us from redistribution.

Sorry don't quite understand why, this flag only tells qt6-webengine to recognize proprietary codecs and does not ship any additional codecs? The user is free to choose open source codec implementations (e.g. x264) or a proprietary one (e.g. h264), so wouldn't any licensing issues lie with the user?

also this flag is already enabled for qt5-webengine

https://github.com/void-linux/void-packages/blob/master/srcpkgs/qt5-webengine/template#L12

**Comment by sgn** [comment]
Then we should disable it on Qt5 instead.

See https://bugs.chromium.org/p/chromium/issues/detail?id=795935

**Comment by sgn** [comment]
Hm, I guess I was wrong. Chromium team build Chromium with bundled FFMEG, thus disabling proprietary codecs. We build Qt6 with system FFMEG, thus enabling is fine, since Qt6-WebEngine will use whatever enabled by FFMEG.

**Comment by sgn** [comment]
Tagging myself, so it's in my backlog.

**Comment by ahesford** [comment]
This fixes video playback in qutebrowser. Can you bump the revision so that this change will trigger a rebuild of the package?

**Pull request closed without merging**
