### PR TITLE
Replace mysql with mariadb

### PR DESCRIPTION
**Pull request by Johnnynator**
#26051

### CODE REVIEW

**Comment by ericonr** [comment]
maybe mytop split should be mentioned in the commit as being done to avoid cyclic dependencies?

**Comment by Johnnynator** [comment]
> maybe mytop split should be mentioned in the commit as being done to avoid cyclic dependencies?

done

**Comment by Johnnynator** [comment]
So far `libatomic` on `armv6l` does provide some problems, need to investigate those.

**Comment by Johnnynator** [comment]
Everything  builds now again.

**Comment by ericonr** [comment]
#14485 is likely relevant here.

**Pull request merged**
