### PR TITLE
lxd: update to 4.4.

### PR DESCRIPTION
**Pull request by CameronNemo**

### CODE REVIEW

**Comment by ahesford** [comment]
Per [my comment](https://github.com/void-linux/void-docs/pull/151#issuecomment-671138650) in #151 and the reply from @flexibeast, I'm inquiring here about dropping the `systemd` cgroup mount logic in the runit service.

1. Is there a compelling reason the mount responsibility should not be moved to a user's `/etc/fstab` or `/etc/rc.local`, wiht the service failing (either explicity in the `run` script or by letting `lxd` itself fail) if the `systemd` cgroup fs has not been mounted?

2. If the previous answer is "yes", is there a compelling reason to move the `systemd` mount to `/etc/runit/core-services/00-pseudofs.sh` for a global solution?

If there is a good reason to leave the mount in the runit service, I think there ought to be a `finish` script to unmount the `systemd` cgroup fs since the service takes resposibility for maintaining it.

**Comment by flexibeast** [comment]
```
$ lxc launch images:voidlinux/musl                                                                                                                         
Creating the instance                                                                                                                                                    
Instance name is: unbiased-polliwog                                                                                                                                      
Starting unbiased-polliwog                                                                                                                                               
Error: Failed to run: /usr/bin/lxd forkstart unbiased-polliwog /var/lib/lxd/containers /var/log/lxd/unbiased-polliwog/lxc.conf:                                          
Try `lxc info --show-log local:unbiased-polliwog` for more info                                                                                                          
$ lxc info --show-log local:unbiased-polliwog
Name: unbiased-polliwog
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/08/16 14:01 UTC
Status: Stopped
Type: container
Profiles: default

Log:

lxc unbiased-polliwog 20200816140108.752 INFO     lxccontainer - lxccontainer.c:do_lxcapi_start:972 - Set process title to [lxc monitor] /var/lib/lxd/containers unbiased-polliwog
lxc unbiased-polliwog 20200816140108.753 INFO     start - start.c:lxc_check_inherited:277 - Closed inherited fd 4
lxc unbiased-polliwog 20200816140108.753 INFO     start - start.c:lxc_check_inherited:277 - Closed inherited fd 5
lxc unbiased-polliwog 20200816140108.753 INFO     start - start.c:lxc_check_inherited:277 - Closed inherited fd 6
lxc unbiased-polliwog 20200816140108.753 INFO     lsm - lsm/lsm.c:lsm_init:29 - LSM security driver nop
lxc unbiased-polliwog 20200816140108.753 INFO     conf - conf.c:run_script_argv:342 - Executing script "/proc/18044/exe callhook /var/lib/lxd 2 start" for container "unbiased-polliwog"
lxc unbiased-polliwog 20200816140108.787 ERROR    conf - conf.c:run_buffer:323 - Script exited with status 1
lxc unbiased-polliwog 20200816140108.787 ERROR    start - start.c:lxc_init:804 - Failed to run lxc.hook.pre-start for container "unbiased-polliwog"
lxc unbiased-polliwog 20200816140108.787 ERROR    start - start.c:__lxc_start:1898 - Failed to initialize container "unbiased-polliwog"
lxc unbiased-polliwog 20200816140108.787 INFO     conf - conf.c:run_script_argv:342 - Executing script "/usr/bin/lxd callhook /var/lib/lxd 2 stopns" for container "unbiased-polliwog"
lxc unbiased-polliwog 20200816140108.888 INFO     conf - conf.c:run_script_argv:342 - Executing script "/usr/bin/lxd callhook /var/lib/lxd 2 stop" for container "unbiased-polliwog"
lxc unbiased-polliwog 20200816140108.921 ERROR    conf - conf.c:run_buffer:323 - Script exited with status 1
lxc unbiased-polliwog 20200816140108.921 ERROR    start - start.c:lxc_end:971 - Failed to run lxc.hook.post-stop for container "unbiased-polliwog"
lxc unbiased-polliwog 20200816140108.921 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:843 - No such file or directory - Failed to receive the container state
```

**Comment by CameronNemo** [comment]
@flexibeast did you get to the bottom of this issue and/or try LXD 4.5?

**Comment by flexibeast** [comment]
Sorry, no, i haven't looked into it, nor tried 4.5.

**Pull request closed without merging**
