### PR TITLE
New package: minecraft-launcher-2.1.13829

### PR DESCRIPTION
**Pull request by MattTreadwell**
Continuation of https://github.com/void-linux/void-packages/pull/14221 with the input from https://github.com/void-linux/void-packages/issues/13139. I'll close my old PR and start working on a minecraft-legacy package to replace the original, unmaintained minecraft package.

### CODE REVIEW

**Comment by Vaelatern** [comment]
INSTALL.msg is way too long, why do we need this package? Why is it restricted instead of the existing minecraft package's merely nonfree?

**Comment by MattTreadwell** [comment]
@Vaelatern Currently, the existing minecraft package violates Mojang's license which doesn't allow redistribution. This is the currently maintained launcher by Mojang. In https://github.com/void-linux/void-packages/issues/13139, there were reports of issues running newer minecraft versions on the existing launcher. 

Ideally, we'd have minecraft-launcher and minecraft-legacy packages which abide by Mojang's licensing (replacing the existing minecraft package). This way users can choose between the electron launcher (minecraft-launcher) or the java launcher (minecraft-legacy).

I'll definitely change INSTALL.msg and add the `build_style=fetch` to https://github.com/void-linux/void-packages/pull/21944

**Comment by Vaelatern** [comment]
Why continue to distribute the legacy version at all, then?

And doesn't MultiMC remove all these issues for us?

**Comment by MattTreadwell** [comment]
I don't think there's a good reason to continue to distributing the legacy launcher. When I tried updating the existing minecraft launcher (to the electron one), there wash some push back in https://github.com/void-linux/void-packages/issues/13139. 

MultiMC seems like it does solve the issue. On the other hand, some users may want to use Mojang's official launcher even though it's closed source. I mean, there's an `oraclejdk` package even though most people are using `openjdk` without issue.

For the legacy package, it should either be purged or at the very least use some of the updates I proposed (whether it's as `minecraft` or `minecraft-legacy`).

**Comment by the-maldridge** [comment]
MultiMC already serves the purpose of a launcher for distro packaged software.  One of the good things of Java is that you can put JARs anywhere you want.  That is the most appropriate way to install the launcher.

**Comment by MattTreadwell** [comment]
@the-maldridge I'm not really sure why it's necessary to debate the purpose of this package when it was basically given the ok a few months ago https://github.com/void-linux/void-packages/pull/14268#pullrequestreview-290136949. I don't see the harm in giving users a choice between MultiMC and the official launcher. Why not have the freedom of choice?

If JARs should be user-manged, the existing `minecraft` package should be removed. Although, it kind of defeats the purpose of having a package manager. 

What do think is the ideal way to solve https://github.com/void-linux/void-packages/issues/13139?

**Pull request closed without merging**
