### PR TITLE
openjdk: update to 8u232b09, rename to openjdk8, native bootstrap

### PR DESCRIPTION
**Pull request by q66**
This updates OpenJDK 8 to a newer version and brings a bunch of changes.

Newly, it is bootstrapped with openjdk7-bootstrap, so it does not need to download binaries. It can also cross-compile and is patched for musl and other platforms.

We're newly using the aarch64 port repo in order to get aarch64 JIT. For non-aarch64 platforms, the codebase is the same.

The symlink for /usr/lib/jvm/openjdk is also now gone and we're using a unified java-VERSION-VENDOR naming.

Also general template cleanup.

Blocking:

- [x] https://github.com/void-linux/void-packages/pull/16429
- [x] https://github.com/void-linux/void-packages/pull/16589

Testing to be done:

- [x] ppc64le
- [x] ppc64
- [x] ppc
- [x] ppc64le-musl
- [x] ppc64-musl
- [x] ppc-musl
- [x] x86_64
- [x] x86_64-musl
- [x] aarch64
- [x] aarch64-musl
- [x] i686
- [x] armv6l/armv7l

More to investigate:

~~I noticed that upgrading from the previous package layout does not properly wipe alternatives for the previous packages, so you're left with an empty `openjdk` for the `java` and `jdk` alternatives groups. This is likely a bug in xbps. There is also a chance it will not happen anymore as that upgrade was when the template was still unfinished.~~

### CODE REVIEW

**Comment by q66** [comment]
Transitional package stuff addressed here: https://github.com/void-linux/xbps/pull/179

**Comment by q66** [comment]
Tested for all targets now.

**Comment by q66** [comment]
`void-packages` PR for the `xbps` bug: https://github.com/void-linux/void-packages/pull/16589

**Comment by q66** [comment]
Ok, all ready I think. Need review from @Vaelatern

**Comment by Vaelatern** [comment]
building on my hardware now

**Pull request closed without merging**
