### PR TITLE
mesa: fix dependency cycle due to reorganization of library dependencies

### PR DESCRIPTION
**Pull request by oreo639**
#### Testing the changes
- I tested the changes in this PR: **briefly**

CC: @classabbyamp

### CODE REVIEW

**Review by classabbyamp — APPROVED** [review]
fyi @SpidFightFR

**Comment by SpidFightFR** [comment]
> fyi @SpidFightFR

Thank you, i'll study this as soon as possible, for the future if something similar is required.

Best regards - Spid

**Comment by oreo639** [comment]
> Thank you, i'll study this as soon as possible, for the future if something similar is required.

Basically, libgbm was changed to depend on libgallium instead of loading it dynamically: https://github.com/sailfishos-mirror/mesa/commit/93511c1c5c5fb60166c806d417e4b4378bf1fb31

This resulted in a dependency loop of mesa -> libgbm -> mesa -> libgbm -> ...

**Comment by SpidFightFR** [comment]
> > Thank you, i'll study this as soon as possible, for the future if something similar is required.
> 
> Basically, libgbm was changed to link to libgallium instead of loading it dynamically: https://gitlab.freedesktop.org/mesa/mesa/-/commit/93511c1c5c5fb60166c806d417e4b4378bf1fb31
> 
> This resulted in a dependency loop of mesa -> libgbm -> mesa -> libgbm -> ...

Ahhh i see... How did you get the info ? Did you encounter the error yourself ? If you got tips for me to anticipate such things in the future i would gladly take them ! :smile:

**Comment by oreo639** [comment]
> How did you get the info ? Did you encounter the error yourself ?

I noticed it when building gnome-desktop and discussed it with clasabbyamp.

>  If you got tips for me to anticipate such things in the future i would gladly take them !

Checking building some dependents with the package and looking at the "Compare to Previous" output can help catch these kinds of issues. (although the package I was building was not a direct dependent of mesa or libgbm)

**Pull request merged**
