### PR TITLE
New package: linux5.15-5.15.0

### PR DESCRIPTION
**Pull request by leahneukirchen**
All archs updated, compile tested on x86_64.

We enable the new NTFS driver with compression but no linux-only ACL.

We don't enable SMB_SERVER as we don't have userland yet anyway, and it's experimental.

We enable SYSFB_SIMPLEFB, UEFI-users please test!

<details>
<summary>x86_64 diffconfig</summary>

```
-BLK_CMDLINE_PARSER y
-BLK_SCSI_REQUEST y
-CACHEFILES_HISTOGRAM n
-CIFS_WEAK_PW_HASH n
-DEBUG_BLOCK_EXT_DEVT n
-FSCACHE_HISTOGRAM n
-FSCACHE_OBJECT_LIST n
-MANDATORY_FILE_LOCKING y
-NVM y
-NVM_PBLK n
-PRINTK_NMI y
-PRISM54 m
-SND_SOC_SOF_HDA_ALWAYS_ENABLE_DMI_L1 n
-TEST_SORT n
-X86_SYSFB n
 USB_COMMON y -> m
+AD5110 m
+AF_UNIX_OOB y
+AMD_PTDMA m
+ARCH_HAS_PARANOID_L1D_FLUSH y
+ARCH_NR_GPIO 1024
+BLK_DEV_BSG_COMMON y
+BLOCK_HOLDER_DEPRECATED y
+CHARGER_CROS_PCHG m
+CHARGER_MT6360 m
+CRYPTO_SM4_AESNI_AVX2_X86_64 n
+CRYPTO_SM4_AESNI_AVX_X86_64 n
+DAMON y
+DAMON_DBGFS y
+DAMON_VADDR y
+DMABUF_SYSFS_STATS n
+DRM_PANEL_WIDECHIPS_WS2401 m
+DRM_VMWGFX_MKSSTATS n
+F2FS_IOSTAT y
+GPIO_VIRTIO m
+I2C_VIRTIO m
+INTEL_ATOMISP2_PDX86 y
+INTEL_IDXD_BUS m
+INTEL_IDXD_COMPAT n
+INTEL_SAR_INT1092 m
+INTEL_WMI y
+IOMMU_DEFAULT_DMA_LAZY y
+IOMMU_DEFAULT_DMA_STRICT n
+IPV6_IOAM6_LWTUNNEL y
+MAXLINEAR_GPHY m
+MCTP m
+MERAKI_MX100 m
+MHI_WWAN_MBIM m
+NET_VENDOR_LITEX y
+NTFS3_64BIT_CLUSTER n
+NTFS3_FS m
+NTFS3_FS_POSIX_ACL n
+NTFS3_LZX_XPRESS y
+PAGE_IDLE_FLAG y
+PERF_EVENTS_AMD_UNCORE m
+PRINTK_INDEX n
+PTP_1588_CLOCK_OPTIONAL y
+REGULATOR_RTQ2134 m
+REGULATOR_RTQ6752 m
+SCSI_COMMON y
+SCSI_UFS_HPB y
+SENSIRION_SGP40 m
+SENSORS_AQUACOMPUTER_D5NEXT m
+SENSORS_SBRMI m
+SMBFS_COMMON m
+SMB_SERVER n
+SND_HDA_CODEC_CS8409 m
+SND_SOC_AMD_ACP5x m
+SND_SOC_ICS43432 m
+SND_SOC_SDW_MOCKUP m
+SND_SOC_WCD_MBHC m
+SYSFB y
+SYSFB_SIMPLEFB y
+VFIO_PCI_CORE m
+WERROR n
+XEN_PV_DOM0 y
```

</details>

Will wait for 5.15.1 before merge.

### CODE REVIEW

**Comment by Animeshz** [comment]
> Will wait for 5.15.1 before merge.

What is the blocker? 🤔 (sorry for a dumb question). Can I build and install locally?

**Comment by ologantr** [comment]
Hi,
I have tested on a UEFI system with a Ryzen 5 1400 and an AMD RX 480 and everything looks fine, it boots properly.
There is only one drawback: I think that snd_usb_audio is in some way broken on 5.15. There is a constant 
crackling sound while playing audio. Notice that I'm using ALSA and not pulse. 
I've tried the new lowlatency module parameter set to 0 but it's still the same. Any thoughts?
Cheers.

**Comment by leahneukirchen** [comment]
I don't know anything about it, but there were some changes to USB Audio. What's the device USB ID?

**Comment by ologantr** [comment]
```ID 08bb:2902 Texas Instruments PCM2902 Audio Codec```

**Comment by leahneukirchen** [comment]
5.15.1 is out and has no alsa fix for that, so please report a kernel bug @ologantr.

**Comment by ologantr** [comment]
@leahneukirchen 
After updating to 5.15.1 and setting lowlatency=0 in modprobe.d, it now seems to work properly.
(lowlatency=1, which is the default, does have problems though)
Everything else seems to be working as expected with this release in UEFI mode.
Thank you for your time!

**Comment by dkwo** [comment]
With 5.15, my boot process _seems_ stuck at "loading initramfs ...", although if I input the encryption password, then it proceeds as usual.
By reading https://bbs.archlinux.org/viewtopic.php?pid=2001959 , I wonder whether this is caused by `SYSFB_SIMPLEFB`.

**Comment by ericonr** [comment]
@dkwo would you mind opening an issue to track this? Since it's already merged, the PR shouldn't be used for tracking bugs.

**Pull request merged**
