### PR TITLE
Update kde frameworks to 5.47.0

### PR DESCRIPTION
**Pull request by Chocimier**

### CODE REVIEW

**Comment by Johnnynator** [comment]
This seems to have broken the `-DDESKTOPTOJSON_EXCUTABLE=/usr/bin/desktoptojson` hack that gets used for getting a few packages cross compiled.

**Comment by Chocimier** [comment]
> This seems to have broken the |-DDESKTOPTOJSON_EXCUTABLE=/usr/bin/desktoptojson| hack that gets used for getting a few packages cross compiled.
All was fine for me, can you show logs?

**Comment by Johnnynator** [comment]
Compiling kexi did not work anymore. ( I actually looked into fixing cross for `print-manager`).
I can upload logs tomorrow.

**Comment by Johnnynator** [comment]
Can put some logs here later. I tried to fix `print-manager` but the usual trick did not work.
I also got that error when trying to compile marble5.
Idk maybe it is a fault on my side, but I idk what may cause this issue.

At least `kcoreaddons` did not have any significant changes that could break it, so I'm not totally sure if it was actually this PR or something else.

**Comment by Johnnynator** [comment]
It can also be related to `kpackage`. Since all old packages that did use that fix still work (and afaik don't depend on kpackage).
```
/usr/aarch64-linux-musl/usr/lib64/cmake/KF5Package/KF5PackageMacros.cmake(63):  execute_process(COMMAND /usr/aarch64-linux-musl/usr/bin/kpackagetool5 --appstream-metainfo /builddir/print-manager-18.04.3/plasmoid/package --appstream-metainfo-output /builddir/print-manager-18.04.3/build/plasmoid/org.kde.plasma.printmanager.appdata.xml ERROR_VARIABLE appstreamerror RESULT_VARIABLE result )
```
Log of print-manager https://gist.github.com/Johnnynator/a8b8cca67644a2d247aa7529bb3af41a

**Comment by Chocimier** [comment]
Yes, KPackage generally [is not ready](https://phabricator.kde.org/T7743) for cross compilation. With below template compilation passes, but metainfo is still missing. I guess it is not a reason to mark is nocross.
```
# Template file for 'print-manager'
pkgname=print-manager
version=18.04.3
revision=1
build_style=cmake
configure_args="-DBUILD_TESTING=OFF"
hostmakedepends="extra-cmake-modules qt5-qmake qt5-host-tools kcoreaddons-devel kconfig-devel kauth-devel"
makedepends="plasma-framework-devel kcmutils-devel cups-devel"
short_desc="Printing management for KDE 5"
maintainer="Giuseppe Fierro <gspe@ae-design.ws>"
license="GPL-2.0-or-later"
homepage="https://github.com/KDE/print-manager"
distfiles="${KDE_SITE}/applications/${version}/src/${pkgname}-${version}.tar.xz"
checksum=7358b2394f1944a5e68c7f6ffa26aec528338efeab8076597eb001f36f9383d6

if [ "$CROSS_BUILD" ]; then
	configure_args+=" -DKF5_HOST_TOOLING=/usr/lib/cmake"
fi
```

**Comment by Johnnynator** [comment]
Ok. Thanks for giving me a solution to work around that problem.

**Comment by Chocimier** [comment]
Also you need to change kauth patch to https://gist.github.com/Chocimier/47b1daf37bfd16804a5af09888e47d15

**Comment by Johnnynator** [comment]
mkay. I will look into including it into my plasma PR and try to fix the remaining nocross issues there. Thanks for your work.

**Pull request merged**
