### PR TITLE
switch anthy 0.4's upstream to debian

### PR DESCRIPTION
**Pull request by sgn**
- switch to Debian's fork,
- upstream is dead
- utf-8 most of the things, now
- new character (令和)
- dict updated.

### CODE REVIEW

**Comment by sgn** [comment]
Make as a draft for now, I want to add the kitchen sink into uim.

**Comment by sgn** [comment]
RPATH is sneaking in, with or without `--disable-rpath`

**Comment by sgn** [comment]
RPATH fixed (libtool's problem)

**Comment by sgn** [comment]
@7185  @mvf @hyonhyoro I'll merge in next 24 hours if I hear nothing back from you.

**Comment by 7185** [comment]
Looks good, thank you!

**Comment by mvf** [comment]
LGTM too.

**Pull request merged**
