### PR TITLE
soju: update to 0.6.0.

### PR DESCRIPTION
**Pull request by classabbyamp**
#### Testing the changes
- I tested the changes in this PR: **NO**
    - (plan on deploying this soon, will test then)

cc maintainer: @flupe

### CODE REVIEW

**Comment by icp1994** [comment]
According to the upstream [packaging guide](https://git.sr.ht/~emersion/soju/tree/v0.6.0/item/doc/packaging.md), isn't it better to use `go_build_tags="libsqlite3` with `sqlite-devel` in makedepends?

**Comment by classabbyamp** [comment]
good catch

**Comment by TeddyDD** [comment]
Installed in on my deployment, works fine (though I still use FS storage for messages, so I didn't test new sqlite msg store).

**Comment by classabbyamp** [comment]
I wouldn't suggest migrating the message store yet, I've seen mentions of some bugs amd extreme slowness in the current migration scripts

**Comment by TeddyDD** [comment]
Oh, I'm not going to migrate anytime soon, but thanks for the heads-up.

**Pull request merged**
