### PR TITLE
kodi: update to version 19.0-Matrix

### PR DESCRIPTION
**Pull request by marmeladema**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (x86_64)
- [x] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [x] aarch64
  - [x] x86_64-musl

### CODE REVIEW

**Comment by marmeladema** [comment]
Build is fine on all supported arch, some tests are failing probably because they are run in CI:
```
353/586 Test #353: TestCPUInfo.GetCPUFrequency ............................................***Failed    0.15 sec
Note: Google Test filter = TestCPUInfo.GetCPUFrequency
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from TestCPUInfo
[ RUN      ] TestCPUInfo.GetCPUFrequency
../xbmc/utils/test/TestCPUInfo.cpp:41: Failure
Expected: (CServiceBroker::GetCPUInfo()->GetCPUFrequency()) >= (0.f), actual: -1 vs 0
[  FAILED  ] TestCPUInfo.GetCPUFrequency (0 ms)
[----------] 1 test from TestCPUInfo (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (66 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] TestCPUInfo.GetCPUFrequency

 1 FAILED TEST
Clean shutdown of TestGlobalPattern1

...

The following tests FAILED:
	353 - TestCPUInfo.GetCPUFrequency (Failed)
```

**Comment by ericonr** [comment]
If you can disable only that specific test, please do so! Otherwise, we can use `make_check=extended` in the template (with an appropriate comment) so it only runs with `./xbps-src -K pkg kodi` (which is not what CI uses).

**Comment by marmeladema** [comment]
@ericonr will try! Tests are managed by gtest. I have never used it I might be able to skip some tests for specific architectures.

**Comment by marmeladema** [comment]
@ericonr Ok I think I got it now!

**Comment by ericonr** [comment]
Please squash the two kodi commits together, and have one `kodi-addon` commit for each package.

**Pull request merged**
