### PR TITLE
tree-sitter: build and install tree-sitter CLI.

### PR DESCRIPTION
**Pull request by gbrlsnchs**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
I was really happy with building tree-sitter not requiring any Rust just yet... Do you think this is strictly necessary?

Also, due to cross compilation and some other concerns, building the Rust parts would require a whole lot of code, to the point I would consider making this a `build_style=cargo` template and using `make` manually in `post_build` and post_install` for the `libtree-sitter` part; or just creating a paired template that should be updated in tandem that builds only the Rust part.

**Comment by gbrlsnchs** [comment]
> I was really happy with building tree-sitter not requiring any Rust just yet... Do you think this is strictly necessary?

I think the CLI is part and parcel of tree-sitter as a whole, so currently we have an incomplete package in the repos. I say that based on [this explanation](https://tree-sitter.github.io/tree-sitter/implementation) from its homepage.

> Also, due to cross compilation and some other concerns, building the Rust parts would require a whole lot of code, to the point I would consider making this a `build_style=cargo` template and using `make` manually in `post_build` and post_install`for the`libtree-sitter` part; or just creating a paired template that should be updated in tandem that builds only the Rust part.
> 
> Doing the first suggestion will probably work well enough, I think.

Yeah, we could have something like `tree-sitter-cli_package()` but, as you said, Rust demands fine-tuning manual installation, so it would be a bad choice maintainability-wise. I can in fact use the `cargo` build style for the CLI and then run the appropriate `make` command in `post_build`/`post_install` as needed, what do you think?

**Comment by ericonr** [comment]
> I can in fact use the cargo build style for the CLI and then run the appropriate make command in post_build/post_install as needed, what do you think?

Yes, that'd be the best option, I think.

Does the CLI need `tree-sitter` headers to work? Or is it completely separate from that?

**Comment by gbrlsnchs** [comment]
> Does the CLI need `tree-sitter` headers to work? Or is it completely separate from that?

Sincere question from a C noob: would that affect anything considering both CLI and library are always shipped together?

**Comment by ericonr** [comment]
> Sincere question from a C noob: would that affect anything considering both CLI and library are always shipped together?

Yes, the cli would be shipped in either `tree-sitter-devel` or `tree-sitter`.

**Comment by gbrlsnchs** [comment]
> > Sincere question from a C noob: would that affect anything considering both CLI and library are always shipped together?
> 
> Yes, the cli would be shipped in either `tree-sitter-devel` or `tree-sitter`.

Oh, I see, thanks. In my experience, no, you don't need the headers. But there is always a possibility that some niche operation needs it, since the CLI compiles things, still I think it can be worked around by simply installing `tree-sitter-devel` when this necessity arises, if it ever happens.

What do you think, can we ship the CLI in `tree-sitter` and make the latter a `cargo` template?

**Comment by ericonr** [comment]
I'm still somewhat pending towards shipping the CLI in devel, since packages like neovim will come to depend on it and it's more stuff to pull in (probably much bigger than the library) that most people won't be using. If you want to generate grammars, you can grab the -devel package.

And yes, switch to the cargo build style.

**Comment by gbrlsnchs** [comment]
> I'm still somewhat pending towards shipping the CLI in devel, since packages like neovim will come to depend on it and it's more stuff to pull in (probably much bigger than the library) that most people won't be using. If you want to generate grammars, you can grab the -devel package.

Neovim 0.5 only uses `tree-sitter-devel` as a `makedepends` dependency (example [here](https://github.com/gbrlsnchs/void-packages/blob/8030a6713946c4dedd2c89fbaf25988099e1a029/srcpkgs/neovim/template) from my custom packaging), so its end-users won't necessarily install `tree-sitter-devel` on their machines in order to run Neovim, since only `tree-sitter` (which includes `libtree-sitter`, needed by Neovim) is needed.

That's why I think shipping `libtree-sitter` and the CLI together in the same package is a better idea, and I think it's a lot more expected than having the CLI in a `-devel` package.

**Comment by ericonr** [comment]
> so its end-users won't necessarily install tree-sitter-devel on their machines in order to run Neovim, since only tree-sitter (which includes libtree-sitter, needed by Neovim) is needed.

Which is exactly my point. Most neovim users (or some other application) *won't* be defining their own grammars, but we want to be sure people *can* do that by shipping a neovim linked against tree-sitter, which is a tiny simple library. The cost increases a lot when people need to have a big CLI. IMO looking for a CLI used for compiling grammars in a -devel package sounds reasonable, and one can also find it using `xlocate`.

**Comment by gbrlsnchs** [comment]
OK, I don't think there's a correct answer here so I agree to do it as you suggest, which I think is also a very good option. I only have a few questions now before patching this PR:
- How do I set up the CLI to be installed along with `tree-sitter-devel`? Is it enough to have an empty `do_install` in the main template (in order to override `cargo` build style own `do_install`) and then add `vinstall ...` inside `pkg_install`?
- Just for learning purposes on my part, could you give me an example on how would I look for the tree-sitter CLI using `xlocate` in order to find it, for example, in the `tree-sitter-devel` package? I might need this later, so better to learn now.

**Comment by FollieHiyuki** [comment]
Something like this `xlocate /usr/bin/tree-sitter-cli` will give you the package that provides the cli

**Comment by ericonr** [comment]
Or really just `xlocate tree-sitter-cli`. What you should do here is not touch `do_install` and in `pkg_install` do `vmove usr/bin`

**Comment by gbrlsnchs** [comment]
Thanks for all the tips and teachings, I have followed as you instructed, so now the tree-sitter CLI should be packaged in `tree-sitter-devel`.

**Comment by ericonr** [comment]
```
 ---- tests::tags_test::test_tags_with_parse_error stdout ----
thread 'tests::tags_test::test_tags_with_parse_error' panicked at 'called `Result::unwrap()` on an `Err` value: Error(["No such file or directory (os error 2)", "Failed to read grammar.json"])', cli/src/tests/helpers/fixtures.rs:25:10
```

maybe the tests are running in the wrong directory?

**Comment by gbrlsnchs** [comment]
> maybe the tests are running in the wrong directory?

Just checked here, tests demand generating fixtures via scripts. Those scripts fetch files from another repository and then run some `cargo` commands. Should I skip `do_check` at all?

**Comment by ericonr** [comment]
Yeah probably disable :(

Or try at least running tests for the C library.

**Comment by gbrlsnchs** [comment]
There doesn't seem to have neither a `check` nor `test` target for `make`, so, yeah... I'm disabling check for this package.

**Comment by FollieHiyuki** [comment]
You can have `make_check=extended` after checksum, instead of using an empty do_check()

**Comment by gbrlsnchs** [comment]
> You can have `make_check=extended` after checksum, instead of using an empty do_check()

Shouldn't I use `make_check=no` in this case?

**Comment by FollieHiyuki** [comment]
In this case they do the same. You can use whatever you prefer

**Comment by ericonr** [comment]
shlibs change wasn't necessary (there was no ABI change), I squashed the commits and update to .3. Thanks :D

**Comment by gbrlsnchs** [comment]
> shlibs change wasn't necessary (there was no ABI change), I squashed the commits and update to .3. Thanks :D

Thanks @ericonr for tidying things up.

Out of curiosity, how do I detected ABI changes in this case? I'm still learning about C and want to make better PRs in the future.

**Comment by ericonr** [comment]
> Out of curiosity, how do I detected ABI changes in this case? I'm still learning about C and want to make better PRs in the future.

Basically if functions change or are removed from the header, as well as changes to the structs described in it (especially the interface one). They seem to be good about making a 0.x.0 release for ABI breaks as well.

**Comment by ericonr** [comment]
The header is under src/include/tree_sitter IIRC

**Comment by gbrlsnchs** [comment]
I see. Thanks for the explanation!

**Pull request closed without merging**
