### PR TITLE
zfs: update to 2.1.11.

### PR DESCRIPTION
**Pull request by milyth**
#### Testing the changes
- I tested the changes in this PR: **YES**

Booted into locally, ZFS-On-Root, x86-64 using linux `6.2.12_1`.

### CODE REVIEW

**Comment by classabbyamp** [comment]
let's keep this on hold for the moment: https://github.com/openzfs/zfs/issues/14753

**Comment by ahesford** [comment]
Should probably wait on this, seems there are some issues: https://github.com/openzfs/zfs/issues/14753

**Comment by zdykstra** [comment]
2.1.11 has been released; it should sit and bake for a few days before being merged.

**Comment by zdykstra** [comment]
I don't see any emergency open issues related to 2.1.11, so it's probably safe to bump this PR and get it in the hands of a few people for testing.

**Comment by zdykstra** [comment]
This builds and runs fine on `x86_64`. CI/CD should be re-run.

**Pull request merged**
