### PR TITLE
android-studio: update to 3.3.1

### PR DESCRIPTION
**Pull request by mustaqimM**

### CODE REVIEW

**Comment by ndowens** [comment]
Curious, why keep closing and opening?

**Comment by mustaqimM** [comment]
@ndowens Sorry about that, I didn't actually close it. The `_studio_rev` changed and when I forced pushed to my repo/branch, GitHub automatically closed it.

**Comment by mustaqimM** [comment]
Please don't merge yet, I'm now getting package conflicts when trying to install:
```bash
CONFLICT: cross-vpkg-dummy-0.29_1 with installed pkg kernel-libc-headers-4.19.0_2 (matched by kernel-libc-headers>=0)
CONFLICT: cross-vpkg-dummy-0.29_1 with installed pkg binutils-2.31.1_2 (matched by binutils>=0)
CONFLICT: cross-vpkg-dummy-0.29_1 with installed pkg libgcc-8.2.0_9 (matched by libgcc>=0)
CONFLICT: cross-vpkg-dummy-0.29_1 with installed pkg libstdc++-8.2.0_9 (matched by libstdc++>=0)
CONFLICT: cross-vpkg-dummy-0.29_1 with installed pkg libstdc++-devel-8.2.0_9 (matched by libstdc++-devel>=0)
CONFLICT: cross-vpkg-dummy-0.29_1 with installed pkg libgomp-8.2.0_9 (matched by libgomp>=0)
CONFLICT: cross-vpkg-dummy-0.29_1 with installed pkg gcc-8.2.0_9 (matched by gcc>=0)
CONFLICT: cross-vpkg-dummy-0.29_1 with installed pkg glibc-2.28_5 (matched by glibc>=0)
CONFLICT: cross-vpkg-dummy-0.29_1 with installed pkg glibc-devel-2.28_5 (matched by glibc-devel>=0)
Transaction aborted due to conflicting packages.
```
same as in #9830
@Pretch, @pullmoll could you please see why?

**Comment by sineemore** [comment]
@mustaqimM,
Reveal of original problem: https://github.com/voidlinux/void-packages/pull/12766
Fix of `04-generate-runtime-deps.sh`: https://github.com/voidlinux/void-packages/commit/f274d7728c95612cdd69775816f3dd2efc764b34
Template file fix: https://github.com/voidlinux/void-packages/commit/8fb44e50ca3b3214b984395b2806944e78de4813

In short: the package contains libraries for ARM. They are linked with `libc.so` and not `libc.so.6` as required by GNU libc. The goal is to find those libraries and add them to `skiprdeps` in template file.

**Comment by mustaqimM** [comment]
Running `xbps-query --repository=hostdir/binpkgs/android-studio-update-branch/nonfree/ android-studio` for `3.1.4` shows:
```bash
shlib-requires:
        libc.so.6
        libjli.so
        libawt_xawt.so
        libdl.so.2
        libpthread.so.0
        libm.so.6
        libjava.so
        libjvm.so
        libawt.so
        libfreetype.so.6
        ld-linux-x86-64.so.2
        libgcc_s.so.1
        libthread_db.so.1
        libXext.so.6
        libX11.so.6
        libXrender.so.1
        libXtst.so.6
        libXi.so.6
        libasound.so.2
```
For `3.3.0`:
```bash
shlib-provides:
        liblldb.so.7
        libtinfo.so.5
        libpython2.7.so.1.0
        libedit.so.0
shlib-requires:
        libc.so.6
        libedit.so.0
        libpython2.7.so.1.0
        libz.so.1
        librt.so.1
        libdl.so.2
        libpthread.so.0
        libm.so.6
        libstdc++.so.6
        libgcc_s.so.1
        ld-linux-x86-64.so.2
        libutil.so.1
        liblldb.so.7
        libawt.so
        libawt_xawt.so
        libjava.so
        libjvm.so
        libjli.so
        libX11.so.6
        libthread_db.so.1
        libasound.so.2
        libXext.so.6
        libXrender.so.1
        libXtst.so.6
        libXi.so.6
        libfreetype.so.6
        libc.so
```

Running:
```bash
$>  fd -e so -x file {}                                        
lib/libpty/linux/x86_64/libpty.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=20337c5794ef7fe6fc6f0b78a2950b65e7c335e7, stripped
bin/lldb/lib/readline.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=26080c31ae092274b2c933cbf585d584ba472937, stripped
jre/lib/amd64/libjawt.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=c9871623af689a109c8fa043032ed4cefdb0a2bf, not stripped
plugins/android/lib/libwebp_jni64.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=117d9df9abcdd77cbc5bdb135d86446271d5c963, not stripped
lib/libpty/linux/x86/libpty.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=a66b551cfcdc6ca25c2c60949c6cfc006188749a, stripped
jre/jre/lib/amd64/libsaproc.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=32aa0601db31926e58625fdb577b7053931bef23, not stripped
plugins/android/lib/libwebp_jni.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=0703db87ea43be6c87abe6bcce8a7d20afc23de1, not stripped
jre/jre/lib/amd64/libzip.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=17783a6957145a065a3422cd6a0edc8a5887c84e, not stripped
jre/lib/amd64/jli/libjli.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=7c01b6cfa818b4fd23a15926d4d75ac8ae83e97c, not stripped
jre/jre/lib/amd64/libjaas_unix.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=fc42e0261878d162922e19aeac9b250bfdab088e, not stripped
jre/jre/lib/amd64/libunpack.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=37fc3c049d5c28bcadef94c49428b173277da0f2, not stripped
jre/jre/lib/amd64/libjsoundalsa.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=378a1546ede2f36341a9ebe05190eb494034d74b, not stripped
jre/jre/lib/amd64/libinstrument.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0a4f9874a3b1eb8e869d2a00c84bcd90de905c70, not stripped
jre/jre/lib/amd64/libawt.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=b95dbf28ced908665b38cb3312fafa0098d0ef60, not stripped
jre/jre/lib/amd64/libjawt.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=c9871623af689a109c8fa043032ed4cefdb0a2bf, not stripped
jre/jre/lib/amd64/libhprof.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=436d0f0c9652f5700e5cb40bae160941b1aaeb92, not stripped
jre/jre/lib/amd64/libjava.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=79ad7f7942676e8af25c123faed4f4ff2d2e2172, not stripped
jre/jre/lib/amd64/libverify.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=776f70344a24b7b6420aace3303f958ec9103da8, not stripped
jre/jre/lib/amd64/libjsig.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=e39fc6c89d89bfc88e9b110d9184e360b200002c, not stripped
jre/jre/lib/amd64/libsunec.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=91921a0485559c299bcdb4af1b54de7e5965d162, not stripped
jre/jre/lib/amd64/libj2pkcs11.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=da7cfdaa57efd7346233df979f7ac79fba98f8f3, not stripped
jre/jre/lib/amd64/libsplashscreen.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=06672d17497ed9ea2fc2d62b1d8c1e9b4781c001, not stripped
jre/jre/lib/amd64/libjsound.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0ef441f897454ee14214e53d8b377fbd70b2925d, not stripped
jre/jre/lib/amd64/libattach.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=35340ee16f0bb36ba4f789c99eccad30aeea1581, not stripped
jre/jre/lib/amd64/libmlib_image.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=18f1f4a5ff8de25f06acf00e0a16e0fa1dcbcfec, not stripped
jre/jre/lib/amd64/libjava_crw_demo.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=2a859b79c29eb4a17efe10ad061ebff71ac1f360, not stripped
jre/jre/lib/amd64/libj2pcsc.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=c81f60849e4ae9917dd0cb7ac833c5a54a208394, not stripped
jre/jre/lib/amd64/libnpt.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=523dec107512672305fbae2eff46422ce34920c4, not stripped
jre/jre/lib/amd64/libdt_socket.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=346848d57c7e01275a30e464436625c639ed097b, not stripped
jre/jre/lib/amd64/libsctp.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=b7b62587201353ea60c4fb550784b4adb20d63e0, not stripped
jre/jre/lib/amd64/libj2gss.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0a9ef17f3d66de46c0d6ee1ae78b3e695d2673dd, not stripped
jre/jre/lib/amd64/libawt_headless.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=144d4de12b9fbfab5628d7d9aa2f733d55dbb05a, not stripped
jre/jre/lib/amd64/liblcms.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=cb2cb97d68c763e9df255cfa88b6759682aa3964, not stripped
jre/jre/lib/amd64/libawt_xawt.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=bfcdb8b36736ecc341cda16f9b3366941e612e3d, not stripped
jre/jre/lib/amd64/libnio.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=4a8540d22d2953bbf56643e92a5b5e6c6c46ff0a, not stripped
jre/jre/lib/amd64/libnet.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=1095488abda2b9446d35e9aa6fc73442e67ccf47, not stripped
jre/jre/lib/amd64/libjpeg.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=bddc42c83b8885fa4069b1491800bbeacbc23a42, not stripped
jre/jre/lib/amd64/libmanagement.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=8f5c8b5e8c33134e5b226d27a204f4de87dfb59e, not stripped
jre/jre/lib/amd64/libjdwp.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=78ed32984488eb1256984540eaa3710ee99e79b2, not stripped
jre/jre/lib/amd64/libfontmanager.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=2b679ba5370cf1ae75857687b11c17213bd5b1ba, not stripped
jre/jre/lib/amd64/libjsdt.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=86aecbfefb39600446a5076e26b4fb105be0b0a2, not stripped
bin/lldb/lib/python2.7/lib-dynload/resource.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=a6aa0dece4713c1617bc09808a7c1c278cb2ad3d, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_hotshot.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=6bebb9a5b48f5b262644582c4eb068ef7fc1b008, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/crypt_failed.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=dc687b9f18ae41493384f0418130606dc9b33f9f, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_sha.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=bc8cf22fd37e5d49b949c9d568d1da25986c5f4a, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/datetime.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0391efbf27ad35cb1a309705d22bdd9f184e3646, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/time.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=ae73e98a4cec2c0fa1344c4b826d96f122ad383d, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/syslog.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=c074c36a326c31d39d72ae35ac2abe02e5a0b2d5, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/itertools.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=d4276ac320f6afa9087e5c5ef59eadbf0b0dc0af, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/mmap.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=134c5df5c83d162f77941760be8e8bad1b3b57dc, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_lsprof.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=9b5b61a006e86f02d1882dabdbf50e3a71c47c19, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/linuxaudiodev.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=763099ffdabf7988912eb1264bd926c38c4a16db, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_md5.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=316e8554af44ac7a0a1e541201184dbefbd4c5f4, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_json.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=7a48db598ac106da46feaa8e25e7c54dab00c480, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/array.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=8e47c580f513c0c748699f497a7810ea9c457f19, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_codecs_jp.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=6685915875860b055f083cd3beaed5032268ffc1, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/select.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=467a7c76e378b05a25ef39c7ca5c63f5715d685e, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_heapq.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=654564c5709eec28a720241d5b6b38292aeec0b6, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_locale.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=af529f2a8b4611e93c010564770f3916bbf75173, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_io.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=3d0c73efa1174978aaa8cf87fa1992422e811b7e, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/spwd.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=15899bf628b39102bc25cccdde8682b1b31c802e, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_functools.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=2e6ae934a497899760af0cd0f20fc43b60bc315a, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_ctypes_test.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=46d5cc014bf9a4214758a6742e6b12dc23141500, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/cmath.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=1fe54e053496e9a030e279ec305bda6209162f4d, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_ctypes.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=e4bc706ec28d6e7ab28bc1c3b1d605723777cb26, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_collections.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=4a98c79261f837896103319ddc635661d2d2d8b6, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/strop.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=9350af9dea9f8d2376061b58f6f07447cf2ea659, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/operator.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=7c15b093c25fc09a8ad6ff5b9c9f1d1733dde4f8, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/binascii.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=2fc0d6bf7209a9f07c3275e7cb8a540cd743b1b7, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/grp.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=c2cc7fbbb110afadcbc4b04c24db10caa327c3e7, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/termios.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=99f0e7f90a24d97b14f545919d81ff47513d9411, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/nis_failed.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=13b674ab38aa69f507f15eab9897f837785444a7, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/cStringIO.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=28e0e9976709d3ba196ed2e421139f24e336dffd, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_codecs_tw.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=4bccc308baad241272730bf6119dc29cd2551aba, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_socket.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=40755d8cfd165c04ffe3adb1bc64c56dd620d4dd, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_codecs_cn.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=c7f703dadcc13b3cd02e78a09ba6adfcf6592379, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_codecs_iso2022.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=1a5bd7ad6ff8e6c8f851c5417b9719edafb1c9ef, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_random.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=bf8f9c74d6f4d2388a9ddb41573b4f8c2447494f, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_bisect.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=8bab502a943bfb5d292b1573eb9ee5f53f971276, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/unicodedata.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=016ebc7a66dcb5558744b6b34c517266f52e370d, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/parser.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=ff2d184fdea46e2fa04084444e3d4d6ea840b674, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_struct.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=9b86bcefcd56044060190c1391c642957b5d5be1, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_elementtree.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=7544b5a15e0179e172a974065ec56f10e18bba59, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/fcntl.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=ee574df23d4b5c42d2822e5e16f5cf50a5c079c7, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_multibytecodec.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=86cfbda9358ee5f3da8e060e110f4b361017023c, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_testcapi.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=f11b3365df0087ea99ea504a7cf511d05de9e804, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/cPickle.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=c5686ee8d11cfcfa3e4d04eea230bbf67f6c5029, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_codecs_kr.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=f1c3cbe392e4b1dfc10c0446fcc95269cfefe913, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/audioop.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=64e9d9a4128a1464faa5a1f289defb6c987f945d, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_multiprocessing.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=bbf1001e78fca683c02fbdb3d900c7b5d85085f0, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/ossaudiodev.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=9d877848ccf8e2c1629d7b1dc1b77684bded5719, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/future_builtins.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=cf5845db1b82e99eeef31a77993c5b707ea48efe, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_csv.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=9ac199d80bb62598da2d42abd68b6b2a565d8204, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/math.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=b10f0076a85d7eb424b9bdbc580cd32fab3c30fb, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/pyexpat.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=b019a0051b46717f8239f0ded46af76a8e5ce0cc, with debug_info, not stripped
bin/lldb/lib/python2.7/lib-dynload/_codecs_hk.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=f8148499d41586b8a3f61b0a98786edfaa82d646, with debug_info, not stripped
jre/jre/lib/amd64/server/libjsig.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=e39fc6c89d89bfc88e9b110d9184e360b200002c, not stripped
jre/jre/lib/amd64/jli/libjli.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=7c01b6cfa818b4fd23a15926d4d75ac8ae83e97c, not stripped
jre/jre/lib/amd64/server/libjvm.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=4eefe6b226225c4fbd1a73e1d72b63839773af72, not stripped
plugins/android/resources/perfa/x86_64/libperfa.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, stripped
plugins/android/resources/perfa/armeabi-v7a/libperfa.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
plugins/android/resources/perfa/x86/libperfa.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, stripped
plugins/android/resources/perfa/arm64-v8a/libperfa.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
```

**Comment by sineemore** [comment]
The following must be added to `skiprdeps`:
```
/opt/android-studio/plugins/android/resources/perfa/x86_64/libperfa.so
/opt/android-studio/plugins/android/resources/installer/armeabi-v7a/installer
/opt/android-studio/plugins/android/resources/installer/x86/installer
/opt/android-studio/plugins/android/resources/installer/arm64-v8a/installer
```
___

Android Studio bundles Python 2.6. It should replaced by system python or we should stop doing `common/hooks/pre-pkg/03-rewrite-python-shebang.sh` on package files.
___

Maybe we should fix [runtime dependecies](https://github.com/void-linux/void-packages/blob/master/Manual.md#runtime-dependencies) as well. Python 2.6 and several libraries are already among the package files.

**Comment by mustaqimM** [comment]
It was erroring out because I didn't increment the `revision` number. It's now building and installing with the following libs being skipped:
```diff
 # These files are not run or loaded on the host thus skip scanning their runtime deps
-skiprdeps="/opt/android-studio/plugins/android/resources/perfa/armeabi-v7a/libperfa.so
- /opt/android-studio/plugins/android/resources/perfa/x86/libperfa.so
+skiprdeps="
+ /opt/android-studio/plugins/android/resources/installer/arm64-v8a/installer
+ /opt/android-studio/plugins/android/resources/installer/armeabi-v7a/installer
+ /opt/android-studio/plugins/android/resources/installer/x86/installer
  /opt/android-studio/plugins/android/resources/perfa/arm64-v8a/libperfa.so
+ /opt/android-studio/plugins/android/resources/perfa/armeabi-v7a/libperfa.so
+ /opt/android-studio/plugins/android/resources/perfa/x86/libperfa.so
+ /opt/android-studio/plugins/android/resources/perfa/x86_64/libperfa.so
+ /opt/android-studio/plugins/android/resources/perfd/arm64-v8a/perfd
  /opt/android-studio/plugins/android/resources/perfd/armeabi-v7a/perfd
  /opt/android-studio/plugins/android/resources/perfd/x86/perfd
- /opt/android-studio/plugins/android/resources/perfd/arm64-v8a/perfd"
 
 do_install() {
        unzip android-studio-ide-${_studio_build}-linux.zip
```

Should `x86_64` libs also be skipped(It wasn't in the previous commit)? It doesn't seem like all need to be skipped. The package also provided it's own python libs

**Comment by sineemore** [comment]
If libraries are not used on the host system, they must be omitted.

**Comment by mustaqimM** [comment]
@maxice8 I think this is ready for merging

**Comment by sineemore** [comment]
@mustaqimM, @maxice8 I don't think we've properly resolved the python issue.

**Comment by sineemore** [comment]
@mustaqimM, I think some current package dependencies are unnecessary (like `python` and `lldb`), but I don't know the way to omit certain dependencies in xbps.

> I'm quite new to xbps-src building

So am I. I've only used to help pullmoll with the past android-studio issue.

**Comment by mustaqimM** [comment]
@sineemore according to the guys on irc, as long as the SONAME `libpython2.7.so.1.0` is linked in `common/shlibs`, `xbps-src` will look for the corresponding package the lib specified links to. So what we have now is correct, I think nothing further needs to be done

**Comment by sineemore** [comment]
@mustaqimM, oh, good, thanks for explanation. @maxice8, as all issues we were aware of are resolved this can be merged.

**Comment by maxice8** [comment]
Please fix the problems pointed out by xlint

**Comment by mustaqimM** [comment]
@maxice8 I've corrected the xlint problems and it installed correctly on my end

**Pull request merged**
