### PR TITLE
nushell: update to 0.82.0.

### PR DESCRIPTION
**Pull request by sirkhancision**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc

### CODE REVIEW

**Comment by icp1994** [comment]
The point of the patch was to link against system sqlite instead of the bundled one.

**Comment by icp1994** [comment]
See discussion in https://github.com/nushell/reedline/pull/474 and the linked void PR there.

**Comment by sirkhancision** [comment]
I'll try to fix that as soon as I can, thanks for the heads up

**Comment by sirkhancision** [comment]
Should be good to go now

**Comment by icp1994** [comment]
Tested locally, works :+1:

**Pull request merged**
