### PR TITLE
restic: update to 0.17.3.

### PR DESCRIPTION
**Pull request by kaistian**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86-64-LIBC

### CODE REVIEW

**Comment by kaistian** [comment]
I don't understand why this is failing, `xbps-src check restic` do complete without error on my machine with the added `make_check_args` and `checkdepends`

**Comment by classabbyamp** [comment]
some tests are assuming they aren't running as root and so they expect an error like unreadable file but don't get one

**Comment by kaistian** [comment]
Aha! The ones I added to skip was for those that need root since I run check is as a ordinary user not root..
Would disable the check with `check_make=no` be accepted?

**Comment by classabbyamp** [comment]
i would put the skips in an if block so it only applies on ci:
```bash
if [ "${XBPS_BUILD_ENVIRONMENT}" = "void-packages-ci" ]; then
	make_check_args="..."
fi
```

**Pull request merged**
