### PR TITLE
blender: update to 2.81

### PR DESCRIPTION
**Pull request by rwtek30**

### CODE REVIEW

**Comment by Johnnynator** [comment]
Blender 2.80+ requires a) a new python version and b) would require you to rebase the patches.

I do already have a update commit in the Python 3.8 PR https://github.com/void-linux/void-packages/pull/15623

**Comment by leahneukirchen** [comment]
We still want the update to 3.81 no?

**Comment by Johnnynator** [comment]
Sure, Someone just has to update it. I won't have time for it anytime soon.

**Comment by GithubPrankster** [comment]
I would like to have 2.81a on Void :D Have the problems with Python 3.8 been solved?

**Pull request closed without merging**
