### PR TITLE
audacity: update to 3.4.2, disable update checks and crashreports.

### PR DESCRIPTION
**Pull request by m3tav3rse**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by Zapeth** [comment]
Does it still compile without `libcurl-devel`? Might be possible to remove it from the dependencies if the networking flags are disabled

**Comment by m3tav3rse** [comment]
It compiles without libcurl-devel so I'll remove it but on current master it needs another [patch](https://github.com/audacity/audacity/pull/5597) to compile.
I think I'll wait for next audacity release instead of pulling patches that will be in next release.

**Comment by Johnnynator** [comment]
They released 3.4.2 which should work without patches and be compatible with current wxWidgets.

**Comment by m3tav3rse** [comment]
Ok, ready for merge.

**Pull request merged**
