### PR TITLE
cava: update to 0.10.2

### PR DESCRIPTION
**Pull request by tranzystorekk**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by tranzystorekk** [comment]
@skmpz I've been maintaining cava on autopilot for a while, do you still want to be the maintainer (and me to stop posting updates) or maybe I could adopt?

**Comment by demproc** [comment]
@tranzystorekk yeah you can adopt if you want

**Comment by skmpz** [comment]
@tranzystorekk yeah you can adopt if you want

**Comment by tranzystorekk** [comment]
I decided instead to close this for now to break the habit on my end.

**Pull request closed without merging**
