### PR TITLE
stepmania: fix runtime crash when built with new versions of gcc.

### PR DESCRIPTION
**Pull request by aliasless**
patch comes from https://github.com/stepmania/stepmania/commit/3f64564dd7c62a2f3d9557c1bdb8475fd953abea

### CODE REVIEW

**Comment by Francesco149** [comment]
hey, it would be nice to have this merged as the current build of stepmania crashes out of the box

**Comment by sgn** [comment]
Current template built with external ffmpeg. Please switch to system ffmpeg.

**Comment by sgn** [comment]
This is for building with system ffmpeg. Build failure, though.
```diff
diff --git a/srcpkgs/stepmania/template b/srcpkgs/stepmania/template
index b416cfa4a5..7e0355708c 100644
--- a/srcpkgs/stepmania/template
+++ b/srcpkgs/stepmania/template
@@ -3,10 +3,11 @@ pkgname=stepmania
 version=5.0.12
 revision=3
 build_style=cmake
+configure_args="-DWITH_SYSTEM_FFMPEG=ON"
 cmake_builddir="Build"
-hostmakedepends="nasm yasm pkg-config git"
+hostmakedepends="nasm yasm pkg-config"
 makedepends="libmad-devel libvorbis-devel pcre-devel libjpeg-turbo-devel
-alsa-lib-devel libXrandr-devel libva-devel glew-devel"
+alsa-lib-devel libXrandr-devel libva-devel glew-devel ffmpeg-devel"
 short_desc="Advanced rhythm game"
 maintainer="Michael Aldridge <maldridge@voidlinux.org>"
 license="MIT"
```

**Comment by travankor** [comment]
@sgn Original author abandoned this PR? Do you want to manually fix this up or should I do it?

**Comment by sgn** [comment]
Hi @travankor

If you can make this works with system ffmpeg, I'll merge it.
I'm busy with libreoffice in aarch64 now.

**Comment by travankor** [comment]
@sgn Seems like [this commit](https://github.com/stepmania/stepmania/commit/b8a79cd0f61c0109b68a23a324c45891851bcc4c) is necessary, but it is on git master (no releases). This looks difficult to backport to old versions.

**Comment by jason1987d** [comment]
I know this is old, but stepmania development has taken a new direction with the OutFox branch (stepmania 5.3). Technically nonfree for now. I know one of the developers personally and they plan to eventually make open source. Should this still be fixed and any PR I create have a different package name i.e. 'stepmania-outfox' or should I just make a PR for the new stepmania with the same package name?

**Comment by ericonr** [comment]
@jason1987d When the new open source version is up, I think we should just update this one.

**Pull request closed without merging**
