### PR TITLE
LLVM 13

### PR DESCRIPTION
**Pull request by DBLouis**
This adds LLVM 13 and updates from LLVM 12.

*Work-in-progress*

The following packages need to be updated or patched:

- `beignet`
- `ispc`
- `qtcreator`

Rebuilt packages:

- `juCi++`
- `kdevelop`
- `codelite`
- `mesa`
- `include-what-you-use`
- `ccls`
- `clazy`
- `bpftrace`
- `qt5`
- `rtags`
- `shiboken2`
- `gnome-builder`
- `bcc`

### CODE REVIEW

**Comment by TeddyDD** [comment]
Related: #34649

**Comment by q66** [comment]
looks pretty good, but if possible it would be best to move as much as possible (ideally all) to 13 and simply drop 12

also these new shlibs should not be added

**Comment by DBLouis** [comment]
Should I bump revision for all packages listed by `./xbps-src show-hostmakedepends` and `./xbps-src show-makedepends` for clang and llvm/llvm13?

**Comment by q66** [comment]
you should revbump packages that have a direct dependency on either newer libclang or libLLVM, so that the older llvm should be safely removed; things that have llvm or clang simply as a host dependency and don't depend on it at runtime should be build-tested (to ensure they still build) but not revbumped

**Comment by wael444** [comment]
Anything new about this?

**Comment by DBLouis** [comment]
It's mostly done. I need help with patches. Is there an easy way of updating patches when the base file changes? This is always very tedious for me. I would like suggestions

**Comment by DBLouis** [comment]
beignet, ispc and qtcreator patches need update

Ok that's how I do it, it's a pain but I guess there is no other way

**Comment by q66** [comment]
maybe we should just finally drop beignet if it's non-trivial to patch, it's been dead for years and it's not really the distro's responsibility to keep it working

**Comment by motorto** [comment]
Trying to help so I updated qtcreator to use llvm13.  Honestly I don't use the app but it compiles on my x86_64 glibc 
 (will create a vm so that I can force install and see if it at least runs, but compiling takes a lot of time on my dual core pc )

MesaRevbump.diff: https://paste.rs/4aN
qt5: update to 5.15.3+20210429: https://paste.rs/lj3
qtcreator: update to 6.0.2: https://paste.rs/hy9

And I will post it here as well:

<details>
    <summary><u>All diffs</u> (<i>click to expand</i>)</summary>
    

```diff
diff --git a/srcpkgs/mesa/template b/srcpkgs/mesa/template
index eb81cbb345..d0499ba9fb 100644
--- a/srcpkgs/mesa/template
+++ b/srcpkgs/mesa/template
@@ -1,7 +1,7 @@
 # Template file for 'mesa'
 pkgname=mesa
 version=21.3.5
-revision=1
+revision=2
 build_style=meson
 configure_args="-Dglvnd=true -Dshared-glapi=enabled -Dgbm=enabled -Degl=enabled
  -Dosmesa=true -Dgles1=enabled -Dgles2=enabled -Dglx=dri -Ddri3=enabled
```

```diff
diff --git a/srcpkgs/qt5/template b/srcpkgs/qt5/template
index c3cb8018f7..9391058428 100644
--- a/srcpkgs/qt5/template
+++ b/srcpkgs/qt5/template
@@ -1,9 +1,9 @@
 # Template file for 'qt5'
 pkgname=qt5
-version=5.15.3+20211001
-# commit fcca82ca40a5d8a02a4ddd90846d070f2c58cfad
+version=5.15.3+20210429
+# commit fcca82ca40a5d8a02a4ddd90846d070f2c58cfad NEED TO CHANGE THIS !!!
 # base repo: https://invent.kde.org/qt/qt/qt5
-revision=2
+revision=1
 build_style=meta
 hostmakedepends="cmake clang flex perl glib-devel pkg-config
  python re2c ruby which"
@@ -28,7 +28,7 @@ homepage="https://qt.io/"
 # to keep the size smaller qtwebengine, qtwebview, qtdocgallery, qtactiveqt and qtpim
 # can be marked with the export-ignore attribute
 distfiles="https://void.johnnynator.dev/distfiles/qt5-${version}.tar.gz"
-checksum=6bff56434b4c2413ec0c9e57ffdcfed1f0966754d1ccf34dafe31840f4006c5a
+checksum=6936ecf7c35162832bde5b5685f24c0924868745983f030e377924c1d80f68d1
 python_version=2 #unverified
 replaces="qt5-doc<5.6.0 qt5-quick1<5.6.0 qt5-quick1-devel<5.6.0 qt5-webkit<5.6.0 qt5-webkit-devel<5.6.0
  qt5-enginio<5.7.1 qt5-enginio-devel<5.7.1 qt5-plugin-gtk<5.7.1 qt5-canvas3d<5.13.0"
```

```diff
diff --git a/srcpkgs/qtcreator/template b/srcpkgs/qtcreator/template
index 28e871b406..ac1152bcca 100644
--- a/srcpkgs/qtcreator/template
+++ b/srcpkgs/qtcreator/template
@@ -1,13 +1,13 @@
 # Template file for 'qtcreator'
 pkgname=qtcreator
-version=5.0.3
+version=6.0.2
 revision=1
 wrksrc="qt-creator-opensource-src-${version}"
 build_style=qmake
 make_install_args="INSTALL_ROOT=\${DESTDIR}/usr"
-hostmakedepends="clang llvm perl pkg-config python3 which qt5-qmake
+hostmakedepends="llvm13 perl pkg-config python3 which qt5-qmake
  qt5-host-tools"
-makedepends="qt5-declarative-devel qt5-script-devel qt5-tools-devel
+makedepends="qt5-declarative-devel qt5-script-devel qt5-tools-devel qt5-svg-devel
  qt5-quickcontrols clang llvm"
 depends="qt5-declarative-devel qt5-quickcontrols qt5-plugin-sqlite"
 short_desc="Cross-platform IDE for Qt developers"
@@ -16,7 +16,7 @@ license="LGPL-3.0-or-later, custom:QtCompany-GPL-Exception-1.0"
 homepage="https://wiki.qt.io/Category:Tools::QtCreator"
 changelog="https://code.qt.io/cgit/qt-creator/qt-creator.git/plain/dist/changes-${version}.md"
 distfiles="https://download.qt.io/official_releases/qtcreator/${version%.*}/${version}/${wrksrc}.tar.xz"
-checksum=7fd3b14310bcecee6b134f8cb7f4c0ed2385d7f4cecd48d756c5c1fd650ce2eb
+checksum=3d173c1a02ce55137a23f294e1a840d7648656e97826067eb29d9df653351bfa
 replaces="qtcreator-data>=0"
 python_version=3
```

</details>

Feedback is welcome

**Comment by Chocimier** [comment]
Patched qtcreator in #35853, can wait few days for to llvm13 with merging.

**Comment by ifreund** [comment]
`zig` will also need to be updated to `0.9.1` in sync with this LLVM update, which in turn means updating `river` to `0.1.3`, which is blocked on <https://github.com/void-linux/void-packages/pull/35017>.

I'd be happy to do the zig and river updates, hopefully I can get the wlroots update merged soonish as well. Feel free to reach on on IRC, my nick is `ifreund` there too.

**Comment by motorto** [comment]
Here we go the ispc update, 

Once again I don't use the package so I can't guarantee that is working 100%, it compiles on my machine x86_64-glib.

here is the diff: http://ix.io/3QNh

(Can't copy and paste this time, because it's really big) @DBLouis, now it's just missing the beignet right ? 

@ifreund  I can update zig if you want I will send a diff today.

**Comment by JamiKettunen** [comment]
Could this be bumped to LLVM 14.0.0 which released back in March 25th?

**Comment by wael444** [comment]
https://github.com/void-linux/void-packages/pull/36229#issuecomment-1079941567

**Pull request closed without merging**
