### PR TITLE
lighttpd: update to 1.4.68

### PR DESCRIPTION
**Pull request by gstrauss**
lighttpd: update to 1.4.68

#### Testing the changes
- I tested the changes in this PR: **NO**

### CODE REVIEW

**Comment by gstrauss** [comment]
> src/meson.build:718:0: ERROR: File t/test_mod_evasive.c does not exist.

It is true that mod_evasive.c and t/test_mod_evasive.c no longer exist, and the meson.build files were updated.

It appears that a clean build needs to be done by the CI.

**Comment by gstrauss** [comment]
Maintainers: how can a clean build for lighttpd be triggered in the CI?

**Comment by gstrauss** [comment]
@Gottox: how can a clean build for lighttpd be triggered in the CI?

**Comment by gstrauss** [comment]
ick.  There is a stray reference to t/test_mod_evasive.c that must be removed.  I'll have to patch it.

**Comment by kruceter** [comment]
Please squash your commits into one.

Do not forget to retain the explanation about meson options.

**Comment by gstrauss** [comment]
squashed as requested.

**Review by kruceter — APPROVED** [review]
Looks good to me. Tested on x86_64-musl.

The changes provided by 1.4.68 do not affect the *default* installation at all.

**Pull request merged**
