### PR TITLE
perl-YAML-PP: update to 0.026.

### PR DESCRIPTION
**Pull request by zdykstra**

### CODE REVIEW

**Comment by ericonr** [comment]
Can it be made to pass a build with `-Q`?

**Comment by zdykstra** [comment]
> Can it be made to pass a build with `-Q`?

Can you clarify what you're asking for here?

**Comment by ericonr** [comment]
I got errors when running tests for it. Is it easy to make it pass them?

**Comment by zdykstra** [comment]
> I got errors when running tests for it. Is it easy to make it pass them?

Likely, I'll give it a try locally to see what's happening here!

**Comment by zdykstra** [comment]
`checkdepends` set, tests pass now.

**Comment by ericonr** [comment]
Thanks!

**Pull request merged**
