### PR TITLE
[RFC] Fix alternatives for openjdk{11,17}

### PR DESCRIPTION
**Pull request by tornaria**
#### Testing the changes
- I tested the changes in this PR: **briefly**

Make sure alternatives for openjdk match the files that are shipped, to fix an issue with disappearing `/usr/bin/java`.

Steps to reproduce:
 - install `openjdk11-jre` so there is a symlink `/usr/bin/java -> ../lib/jvm/openjdk11/bin/java`
 - install `openjdk11` so the alternative switches from `java` to `jdk`, which also makes a symlink `/usr/bin/java -> ../lib/jvm/openjdk11/bin/java`
 - uninstall `openjdk11` so the alternative switches back from `jdk` to `java`. The symlink will be removed for `jdk` but not added back for `java`.

Arguably this is a bug in `xbps-alternatives`, but it doesn't seem ok for a package to provide an alternative for a file it doesn't contain (or for two packages to provide the exact same alternative.

However, I'm not sure this is ok. What happens if one tries to use `jdk` alternative from one version and `java` alternative from a different version? Maybe that's the reason why this was set up this way. Thus the [RFC]. I also didn't bump the revision, let me know if I should do that or just fix it and wait for a next update.

I found this while installing and uninstalling `jmol` which depends on `java-environment`, thus `openjdk11` would be installed/uninstalled breaking `/bin/java` for me. I also think `jmol` should not depend on java-environment but that java-runtime should be good enough (it seems to run ok; I don't use it directly but only through sage which uses it sometimes to create png files). So I added a commit here to that effect, but of course I could move that to a separate PR.

Ping: @mhmdanas @classabbyamp since you often update these.

### CODE REVIEW

**Comment by ahesford** [comment]
If the jdk/java selections must be consistent (it seems like they ought to be), I wonder if the better approach is to move everything to a common `Java` alternative. The JRE packages could provide a subset of the full alternative group provided by the JDK packages. Whether the alternatives system behaves properly here requires testing.

**Comment by tornaria** [comment]
> yeah it's fairly complex. it's trying to make it so the jdk and jre groups match by making the former a superset of the latter. this has existed longer than I've been around so I don't know what's up really. there's probably a better way.

I see, but the problem is that `xbps-alternatives` doesn't handle duplicate alternatives gracefully...

In the comment above I showed steps to reproduce a bad behavior in this respect. What is the bad behavior that would be caused by "fixing" the alternatives as I suggest in this PR?

> If the jdk/java selections must be consistent (it seems like they ought to be), I wonder if the better approach is to move everything to a common `Java` alternative. The JRE packages could provide a subset of the full alternative group provided by the JDK packages. Whether the alternatives system behaves properly here requires testing.

So we would have (say) four providers for the `java` alternative group:
 - openjdk11-jre
 - openjdk11
 - openjdk17-jre
 - openjdk17

But then, say I choose `openjdk11-jre` alternative, and later I install `openjdk11` then I won't have the symlinks for the binaries in `openjdk11`.

**Comment by classabbyamp** [comment]
basically what needs to happen is:
- if only 1 JRE is installed, it should be `java` and the same for the other JRE programs
- if only 1 JDK is installed, same thing for the JDK tools
- if multiple JREs or JDKs are installed, then the `java` and JDK tools must be the same version.

but because each version is split in 2 packages, it's hard to do.

I think it may be possible to do this with a script (multicall, so it can act as any of the tools) that gets installed in /usr/bin.

Perhaps the alternative group could manage a symlink like `/usr/lib/jvm/openjdk-jre -> /usr/lib/jvm/openjdk##` and `/usr/lib/jvm/openjdk-jdk -> /usr/lib/jvm/openjdk##`, and the script wrapper ensures they're the same version.

```sh
#!/bin/sh

prog="$0"

if [ -e "/usr/lib/jvm/openjdk-jdk" ]; then
    if [ "$(realpath /usr/lib/jvm/openjdk-jdk)" != "$(realpath /usr/lib/jvm/openjdk-jre)" ]; then
        echo "WARNING! JDK/JRE mismatch! use xbps-alternatives to choose one"
    fi
    exec "/usr/lib/jvm/openjdk-jdk/bin/$prog" "$@"
fi

exec "/usr/lib/jvm/openjdk-jre/bin/$prog" "$@"
```
(just spitballing here)

**Comment by classabbyamp** [comment]
also don't forget about openjdk8

**Comment by ahesford** [comment]
I think wrapping the Java commands in a script that monitors a pair of alternative links is the best approach we'll get with XBPS.

**Comment by tornaria** [comment]
Closing in favor of #47866

**Pull request closed without merging**
