### PR TITLE
lvm2: update to 2.03 series

### PR DESCRIPTION
**Pull request by dkwo**
- I tested the changes in this PR: yes
- I built this PR locally for my native architecture, (x86_64-musl)

### CODE REVIEW

**Comment by dkwo** [comment]
#39821

**Comment by mhmdanas** [comment]
Can this be updated to 2.03.19?

**Comment by dkwo** [comment]
it's already in the 2nd commit

**Comment by mhmdanas** [comment]
Ah, the outdated PR title misled me.

**Comment by dkwo** [comment]
updated to v21, which incidentally should also work with 16k page sizes.

**Comment by dkwo** [comment]
@Duncaen Can you take a look?

**Comment by Duncaen** [comment]
I don't have any lvm setup.

**Comment by mhmdanas** [comment]
I use the FDE setup as detailed in https://docs.voidlinux.org/installation/guides/fde.html, so I'll be testing this and reporting back. Fingers crossed this won't break my boot. :)

**Comment by dkwo** [comment]
Thanks. I also tested this on my setup in the past, and it worked fine.

**Comment by mhmdanas** [comment]
I booted my FDE installation with lvm2 built from this PR. I get this error at runit stage 1 though:
```
[    18.554315] udevd[992]: failed to execute '/usr/lib64/udev/no' 'no --no-block --property DefaultDependencies=no --unit lvm-activate-voidvm /usr/bin/lvm vgchange -aay --autoactivation event voidvm': No such file or directory
```
(I had to copy this manually from a picture of the TTY, so apologies for any typos)

Otherwise the system booted up just fine.

**Comment by dkwo** [comment]
@mhmdanas I don't see that warning, using FDE too. Maybe it's related to the initramfs being used?
Mine (tinyramfs) mounts by UUID, and this Gentoo guide describes four options: https://wiki.gentoo.org/wiki/Custom_Initramfs#LVM

**Comment by dkwo** [comment]
Debian has this https://github.com/chimera-linux/cports/blob/master/main/lvm2/patches/udev-no-systemd.patch

**Comment by mhmdanas** [comment]
@dkwo I use dracut for my initramfs.

> Debian has this https://github.com/chimera-linux/cports/blob/master/main/lvm2/patches/udev-no-systemd.patch

Alright, I'll try out the patch and see if it gets rid of the error message.

**Comment by mhmdanas** [comment]
With that patch, the error seems to go away.

**Comment by dkwo** [comment]
I can include the patch, if this is preferred.

**Comment by dkwo** [comment]
Know any maintainer who can test this?

**Comment by mhmdanas** [comment]
I'd squash the second commit into the first.

> Know any maintainer who can test this?

Not as far as I know.

**Comment by dkwo** [comment]
@leahneukirchen can you perhaps take a look?

**Comment by leahneukirchen** [comment]
Yes, i just need to reboot 🙈

**Comment by dkwo** [comment]
Rebased. @leahneukirchen Maybe this one too? ;)

**Comment by leahneukirchen** [comment]
Please rebase.

**Comment by dkwo** [comment]
Rebased.

**Comment by mhmdanas** [comment]
Been using this for 10 days on x86_64-glibc, with no issues as far as I can tell.

**Comment by leahneukirchen** [comment]
Please rebase again, then let's merge this.

**Comment by dkwo** [comment]
rebased

**Pull request merged**
