### PR TITLE
[NOMERGE] sway: update to 1.0-beta.2

### PR DESCRIPTION
**Pull request by CameronNemo**
[ci skip]

Hello, I am here purely for visibility and criticism. How is your day?

### CODE REVIEW

**Comment by jcgruenhage** [comment]
Does this work for you? I've just tried to build it on x86_64-musl and it failed with this error:

```
FAILED: swaylock/swaylock@@swaylock@exe/main.c.o 
cc -Iswaylock/swaylock@@swaylock@exe -Iswaylock -I../swaylock -Iinclude -I../include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/elogind -flto -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Werror -std=c11 -DWL_HIDE_DEPRECATED -DWLR_USE_UNSTABLE -Wno-unused-parameter -Wno-unused-result -Wundef '-DSYSCONFDIR="//etc"' '-DSWAY_VERSION="1.0-beta.2"' -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pthread  -MD -MQ 'swaylock/swaylock@@swaylock@exe/main.c.o' -MF 'swaylock/swaylock@@swaylock@exe/main.c.o.d' -o 'swaylock/swaylock@@swaylock@exe/main.c.o' -c ../swaylock/main.c
../swaylock/main.c: In function 'main':
../swaylock/main.c:964:65: error: 'POLL_IN' undeclared (first use in this function)
  loop_add_fd(state.eventloop, wl_display_get_fd(state.display), POLL_IN,
                                                                 ^~~~~~~
../swaylock/main.c:964:65: note: each undeclared identifier is reported only once for each function it appears in
ninja: build stopped: subcommand failed.
=> ERROR: sway-1.0_1: do_build: '${make_cmd} -C ${meson_builddir} ${makejobs} ${make_build_args} ${make_build_target}' exited with 1
=> ERROR:   in do_build() at common/build-style/meson.sh:110
```

**Comment by CameronNemo** [comment]
Seems like an easy fix, working on a patch now but may get interrupted.

**Comment by CameronNemo** [comment]
swaylock defines _POSIX_C_SOURCE but not _XOPEN_SOURCE

https://github.com/runtimejs/musl-libc/blob/master/include/signal.h#L199

**Comment by jcgruenhage** [comment]
Thanks, I'll try it later

**Comment by jcgruenhage** [comment]
It builds fine now, runs fine too, but there is a bug with replicating bars.. I guess that is an upstream problem though. I'll check in more detail once I'm back at a proper computer

**Comment by shumvgolove** [comment]
I set up the `XDG_RUNTIME_DIR` environment in `.profile`, but sway still refuses to launch:

`[backend/session/logind.c:489] Failed to get session id: No data available.`

**Comment by maxice8** [comment]
superseeded by #8171 ?

**Pull request closed without merging**
