### PR TITLE
libsixel: update to 1.10.3, switch upstream

### PR DESCRIPTION
**Pull request by cinerea0**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by cinerea0** [comment]
This won't build properly until the new upstream adds SONAME versioning; waiting on this issue to be resolved: https://github.com/libsixel/libsixel/issues/37.

**Comment by dankamongmen** [comment]
> This won't build properly until the new upstream adds SONAME versioning; waiting on this issue to be resolved: [libsixel/libsixel#37](https://github.com/libsixel/libsixel/issues/37).

i've got your corner; done

**Comment by cinerea0** [comment]
@dankamongmen Thank you! I'll watch the libsixel repo for releases so I can update this when the next release comes out.

**Comment by dankamongmen** [comment]
> @dankamongmen Thank you! I'll watch the libsixel repo for releases so I can update this when the next release comes out.

you can just ask =] i'll put one out for you now.

**Comment by dankamongmen** [comment]
> > @dankamongmen Thank you! I'll watch the libsixel repo for releases so I can update this when the next release comes out.
> 
> you can just ask =] i'll put one out for you now.

1.10.3 hot off the presses for my good friends in void linux

**Comment by cinerea0** [comment]
@dankamongmen Thanks again! I've switched to the new release for this PR. @abenson, I'm pinging you here because this is your package.

**Pull request merged**
