### PR TITLE
qt6: Update to 6.8

### PR DESCRIPTION
**Pull request by Johnnynator**
- **qt6-3d: update to 6.8.0.**
- **qt6-base: update to 6.8.0.**
- **qt6-charts: update to 6.8.0.**
- **qt6-connectivity: update to 6.8.0.**
- **qt6-declarative: update to 6.8.0.**
- **qt6-imageformats: update to 6.8.0.**
- **qt6-languageserver: update to 6.8.0.**
- **qt6-location: update to 6.8.0.**
- **qt6-lottie: update to 6.8.0.**
- **qt6-multimedia: update to 6.8.0.**
- **qt6-networkauth: update to 6.8.0.**
- **qt6-pdf: update to 6.8.0.**
- **qt6-position: update to 6.8.0.**
- **qt6-qt5compat: update to 6.8.0.**
- **qt6-quick3d: update to 6.8.0.**
- **qt6-quicktimeline: update to 6.8.0.**
- **qt6-remoteobjects: update to 6.8.0.**
- **qt6-scxml: update to 6.8.0.**
- **qt6-sensors: update to 6.8.0.**
- **qt6-serialport: update to 6.8.0.**
- **qt6-shadertools: update to 6.8.0.**
- **qt6-speech: update to 6.8.0.**
- **qt6-svg: update to 6.8.0.**
- **qt6-tools: update to 6.8.0.**
- **qt6-translations: update to 6.8.0.**
- **qt6-virtualkeyboard: update to 6.8.0.**
- **qt6-wayland: update to 6.8.0.**
- **qt6-webchannel: update to 6.8.0.**
- **qt6-websockets: update to 6.8.0.**
- **qt6-webview: update to 6.8.0.**

[ci skip] or [skip ci] 🤷

Failing:
- `fcitx5-qt`
- `qtcreator`
- `telegram-desktop`

### CODE REVIEW

**Comment by classabbyamp** [comment]
everything that builds against `qt6-*-private-devel` needs a revbump too

**Comment by Johnnynator** [comment]
> everything that builds against `qt6-*-private-devel` needs a revbump too

I'm aware, but no PyQt6 6.8 release yet, which is needed.
I didn't want to add revbumps yet, since updating them can be annoying.

**Comment by Astate** [comment]
> > everything that builds against `qt6-*-private-devel` needs a revbump too
> 
> I'm aware, but no PyQt6 6.8 release yet, which is needed. I didn't want to add revbumps yet, since updating them can be annoying.

it's out now :)
https://riverbankcomputing.com/news/PyQt_v6.8.0_Released

**Comment by Johnnynator** [comment]
Testing repo: https://void.johnnynator.dev/dev/qt6.8/

Everything compiles, stuff seems to work.

**Comment by sleepppwalker** [comment]
Thanks...
```dbus-run-session startplasma-wayland``` - doesn't work anymore

as file [log-dbus.txt](https://github.com/user-attachments/files/18253399/log-dbus.txt)

as text
```
org.kde.startup: not a reply org.freedesktop.locale1 QDBusMessage(type=Error, service="", error name="org.freedesktop.DBus.Error.ServiceUnknown", error message="The name org.freedesktop.locale1 was not provided by any .service files", signature="s", contents=("The name org.freedesktop.locale1 was not provided by any .service files") )
dbus-daemon[1191]: [session uid=1000 pid=1191] Activating service name='org.kde.KSplash' requested by ':1.0' (uid=1000 pid=1192 comm="startplasma-wayland")
dbus-daemon[1191]: [session uid=1000 pid=1191] Activating service name='org.freedesktop.portal.Desktop' requested by ':1.4' (uid=1000 pid=1207 comm="/usr/bin/kcminit_startup")
dbus-daemon[1191]: [session uid=1000 pid=1191] Activating service name='org.freedesktop.portal.Documents' requested by ':1.5' (uid=1000 pid=1210 comm="/usr/libexec/xdg-desktop-portal")
dbus-daemon[1191]: [session uid=1000 pid=1191] Activating service name='org.freedesktop.impl.portal.PermissionStore' requested by ':1.6' (uid=1000 pid=1216 comm="/usr/libexec/xdg-document-portal")
dbus-daemon[1191]: [session uid=1000 pid=1191] Successfully activated service 'org.freedesktop.impl.portal.PermissionStore'
dbus-daemon[1191]: [session uid=1000 pid=1191] Successfully activated service 'org.freedesktop.portal.Documents'
fusermount3: failed to access mountpoint /run/user/1000/doc: Permission denied
error: fuse init failed: Can't mount path /run/user/1000/doc

(/usr/libexec/xdg-desktop-portal:1210): xdg-desktop-portal-WARNING **: 23:19:29.381: Failed to load RealtimeKit property: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files

(/usr/libexec/xdg-desktop-portal:1210): xdg-desktop-portal-WARNING **: 23:19:29.381: Failed to load RealtimeKit property: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files

(/usr/libexec/xdg-desktop-portal:1210): xdg-desktop-portal-WARNING **: 23:19:29.381: Failed to load RealtimeKit property: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files
dbus-daemon[1191]: [session uid=1000 pid=1191] Activating service name='org.freedesktop.impl.portal.desktop.kde' requested by ':1.5' (uid=1000 pid=1210 comm="/usr/libexec/xdg-desktop-portal")
/usr/bin/ksplashqml: symbol lookup error: /usr/lib/libLayerShellQtInterface.so.6: undefined symbol: _ZN15QtWaylandClient14QWaylandWindow9wlSurfaceEv, version Qt_6_PRIVATE_API
No backend specified, automatically choosing drm
kwin_wayland_drm: drmSetClientCap for Atomic Mode Setting failed. Using legacy mode on GPU "/dev/dri/card0"
[E] pw.loop [loop.c:69 pw_loop_new()] 0x564886851ef0: can't make support.system handle: No such file or directory
kwin_screencast: Failed to create PipeWire loop: No such file or directory
Initializing  "/usr/lib/qt6/plugins/plasma/kcms/systemsettings/kcm_style.so"
dbus-daemon[1191]: [session uid=1000 pid=1191] Activating service name='org.a11y.Bus' requested by ':1.10' (uid=1000 pid=1379 comm="busctl call --user org.a11y.Bus /org/a11y/bus org.")
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
> Warning:          Could not resolve keysym XF86KbdInputAssistPrevgrou
> Warning:          Could not resolve keysym XF86KbdInputAssistNextgrou
Errors from xkbcomp are not fatal to the X server
dbus-daemon[1191]: [session uid=1000 pid=1191] Successfully activated service 'org.a11y.Bus'
Initializing  "/usr/lib/qt6/plugins/plasma/kcms/systemsettings/kcm_fonts.so"
Initializing  "/usr/lib/qt6/plugins/plasma/kcms/systemsettings/kcm_fonts.so"
Initializing  "/usr/lib/qt6/plugins/plasma/kcms/systemsettings/kcm_mouse.so"
Initializing  "/usr/lib/qt6/plugins/plasma/kcms/systemsettings/kcm_style.so"
org.kde.plasma.session: process job  "kcminit_startup" finished with exit code  0
dbus-daemon[1191]: [session uid=1000 pid=1191] Successfully activated service 'org.freedesktop.impl.portal.desktop.kde'
[E] pw.loop [loop.c:69 pw_loop_new()] 0x56036725e660: can't make support.system handle: No such file or directory

(/usr/libexec/xdg-desktop-portal:1210): xdg-desktop-portal-WARNING **: 23:19:30.457: Failed connect to PipeWire: Couldn't create PipeWire main loop
dbus-daemon[1191]: [session uid=1000 pid=1191] Successfully activated service 'org.freedesktop.portal.Desktop'
dbus-daemon[1191]: [session uid=1000 pid=1191] Activating service name='ca.desrt.dconf' requested by ':1.16' (uid=1000 pid=1410 comm="/usr/bin/kded6")
dbus-daemon[1191]: [session uid=1000 pid=1191] Successfully activated service 'ca.desrt.dconf'
org.kde.kameleon: found no RGB LED devices
QDBusObjectPath: invalid path "/modules/plasma-session-shortcuts"
kf.dbusaddons: The kded module name "plasma-session-shortcuts" is invalid!
org.kde.colorcorrectlocationupdater: Geolocator stopped
org.kde.pulseaudio: Failed to connect context
org.kde.libkbolt: Failed to connect to Bolt manager DBus interface: The name org.freedesktop.NetworkManager was not provided by any .service files
org.kde.bolt.kded: Couldn't connect to Bolt DBus daemon
kf.config.kconf_update: /usr/share/kconf_update/dolphin_detailsmodesettings.upd defined Version=5 but Version=6 was expected
kf.config.kconf_update: /usr/share/kconf_update/dolphin_directorysizemode.upd defined Version=5 but Version=6 was expected
kf.config.kconf_update: /usr/share/kconf_update/konsole.upd defined Version=5 but Version=6 was expected
kf.modemmanagerqt: Failed enumerating MM objects: "org.freedesktop.DBus.Error.ServiceUnknown" 
 "The name org.freedesktop.ModemManager1 was not provided by any .service files"
kf.bluezqt: PendingCall Error: "The name org.bluez.obex was not provided by any .service files"
kf.kio.gui: Failed to determine systemd version, falling back to extremely legacy forking mode.
Initializing  "/usr/lib/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kcm_kgamma.so"
Initializing  "/usr/lib/qt6/plugins/plasma/kcms/systemsettings/kcm_touchpad.so"
Xlib XKB extension major= 1  minor= 0
New PolkitAgentListener  0x55731b481610
Adding new listener  PolkitQt1::Agent::Listener(0x55731b480e80) for  0x55731b481610
Listener online
Authentication agent result: true
dbus-daemon[1191]: [session uid=1000 pid=1191] Activating service name='org.kde.ActivityManager' requested by ':1.23' (uid=1000 pid=1456 comm="/usr/libexec/org_kde_powerdevil")
/usr/bin/plasmashell: symbol lookup error: /usr/lib/libLayerShellQtInterface.so.6: undefined symbol: _ZN15QtWaylandClient14QWaylandWindow9wlSurfaceEv, version Qt_6_PRIVATE_API
kf.kio.gui: "org.kde.plasmashell" "<html>The command <tt></tt> could not be found.</html>"
X server XKB extension major= 1  minor= 0
kf.windowsystem: virtual void KX11Extras::connectNotify(const QMetaMethod&) may only be used on X11
kf.windowsystem: virtual void KX11Extras::connectNotify(const QMetaMethod&) may only be used on X11
dbus-daemon[1191]: [session uid=1000 pid=1191] Successfully activated service 'org.kde.ActivityManager'
org.kde.powerdevil: [DDCutilDetector]: Failed to initialize callback
org.kde.powerdevil: org.kde.powerdevil.chargethresholdhelper.getthreshold failed "Charge thresholds are not supported by the kernel for this hardware"
org.kde.powerdevil: org.kde.powerdevil.backlighthelper.brightness failed
org.kde.powerdevil: Handle button events action could not check for screen configuration
org.kde.powerdevil: org.kde.powerdevil.chargethresholdhelper.getthreshold failed "Charge thresholds are not supported by the kernel for this hardware"
```

**Comment by Johnnynator** [comment]
The rebuild is still in progress, I should have taken care to ensure that the repo is staged so updates would not be available until everything is finished.

Until then you need to either downgrade the packages or wait until the rebuild is finished. (Compiling the missing packages yourself, or fetching from my dev repo also works)

**Pull request merged**
