### PR TITLE
cryptsetup: use subpacakges= instead of case esac to guard a function.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by Johnnynator** [comment]
You have a typo in your commit message s/subacakges/subpackages

**Comment by maxice8** [comment]
On Fri, Sep 14, 2018 at 08:59:14AM -0700, John Zimmermann wrote:
> You have a typo in your commit message s/subacakges/subpackages
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/2753#issuecomment-421404295

fixed, thanks

**Comment by Gottox** [comment]
Please add a short description why this change was made to the commit message.

**Comment by maxice8** [comment]
On Sun, Sep 16, 2018 at 06:13:52AM -0700, Enno Boland wrote:
> Please add a short description why this change was made to the commit message.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/2753#issuecomment-421763623

added

**Pull request merged**
