### PR TITLE
slurm-wlm: update to 20.02.5.1.

### PR DESCRIPTION
**Pull request by Vaelatern**

### CODE REVIEW

**Comment by Vaelatern** [comment]
These build failures are in a weird pattern.

**Comment by st3r4g** [comment]
I also tried to update this locally. `x86_64` runs fine while `x86_64-musl` couldn't be built:
```
/usr/bin/ld: /builddir/slurm-slurm-20-02-5-1/src/api/.libs/libslurmfull.so: undefined reference to `res_ninit'

/usr/bin/ld: /builddir/slurm-slurm-20-02-5-1/src/api/.libs/libslurmfull.so: undefined reference to `res_nsearch'

/usr/bin/ld: /builddir/slurm-slurm-20-02-5-1/src/api/.libs/libslurmfull.so: undefined reference to `qsort_r'
```
it seems it's using functions that doesn't exist on musl, so it needs to be patched (similar patches were made already by pullmoll) or just deemed broken on musl.

**Comment by ericonr** [comment]
Ping

**Comment by Piraty** [comment]
obsoleted by https://github.com/void-linux/void-packages/pull/33284

**Pull request closed without merging**
