### PR TITLE
gimp: update to 2.10.10.

### PR DESCRIPTION
**Pull request by jnbr**
alternative to #9380

### CODE REVIEW

**Comment by jnbr** [comment]
The `INSTALL` file is harmful when `xbps-install -r` is used.

**Comment by biopsin** [comment]
libgimp_package() ... vmove "usr/lib/*.so.*"

**Comment by jnbr** [comment]
> libgimp_package() ... vmove "usr/lib/.so."

--verbose

**Comment by luzpaz** [comment]
any updates ?

**Comment by maxice8** [comment]
ping

**Comment by jnbr** [comment]
I'm still no fan of doing things this way but realistically, it will take some more time to fix this in xbps.
Feel free to merge if aarch64-musl passes on travis.

**Comment by biopsin** [comment]
Get while try to execute
`gimp-2.10: symbol lookup error: /usr/lib/libgimpcolor-2.0.so.0: undefined symbol: gegl_scratch_alloc`

**Pull request merged**
