### PR TITLE
New package: Platinum9-theme-0.0.0.20170720

### PR DESCRIPTION
**Pull request by cr6git**
thanks to **@GrandOrbiter** :green_apple: 
https://forum.voidlinux.org/t/offical-desktop-screenshot-thread/30/535

### CODE REVIEW

**Comment by jnbr** [comment]
I doubt it's ok to distribute these fonts.

**Comment by Johnnynator** [comment]
@cr6git Can you give any clear licensing of any part of this package? I can't find anything in the repo.

**Comment by jnbr** [comment]
To clarify: by "ok" I meant legal.
Both, Monaco and Carocal were published by Apple without the permission to distribute them.

Besides:  I don't see why we need packages for more themes. Even less so, if they don't have proper releases.

**Comment by cr6git** [comment]
@Johnnynator well, I only found some vague reference to "GPL" in:
https://github.com/grassmunk/Platinum9/blob/master/ClassicPlatinumStreamlined/gtk-2.0/gtkrc#L3

@jnbr noted, thanks.

**Comment by cr6git** [comment]
https://github.com/void-linux/void-packages/commit/01a1edb4cd754824d41c58d1e12c390281db8e2d

**Pull request merged**
