### PR TITLE
xchm: update to 1.26.

### PR DESCRIPTION
**Pull request by Chocimier**
Old homepage redirects to new.

### CODE REVIEW

**Comment by maxice8** [comment]
Travis

**Comment by newbluemoon** [comment]
The `configure` script contains

```
if test -n $XMLRPCDIR ; then
    CFLAGS="-I$XMLRPCDIR/include -I$XMLRPCDIR/include/xmlrpcpp $CFLAGS"
    CXXFLAGS="-I$XMLRPCDIR/include -I$XMLRPCDIR/include/xmlrpcpp $CXXFLAGS"
    CPPFLAGS="-I$XMLRPCDIR/include -I$XMLRPCDIR/include/xmlrpcpp $CPPFLAGS"
    LDFLAGS="-L$XMLRPCDIR/lib -Wl,-rpath,$XMLRPCDIR/lib $LDFLAGS"
fi
```

I think `$XMLRPCDIR` needs to be quoted here else the test is always true and this leads to setting
`-L$XMLRPCDIR/lib` = `-L/lib`
which fails in cross-builds with the apparent error. Don’t know, however, why aarch64 seems to work.

This simple patch works for me:
```
--- configure.orig	2019-03-21 21:31:51.965584205 +0100
+++ configure	2019-03-21 21:38:24.770907107 +0100
@@ -5669,7 +5669,7 @@
 fi
 
 
-if test -n $XMLRPCDIR ; then
+if test -n "$XMLRPCDIR" ; then
     CFLAGS="-I$XMLRPCDIR/include -I$XMLRPCDIR/include/xmlrpcpp $CFLAGS"
     CXXFLAGS="-I$XMLRPCDIR/include -I$XMLRPCDIR/include/xmlrpcpp $CXXFLAGS"
     CPPFLAGS="-I$XMLRPCDIR/include -I$XMLRPCDIR/include/xmlrpcpp $CPPFLAGS"
```

I’ll report it upstream.

**Comment by newbluemoon** [comment]
Btw: 1.27 is out. ;)

**Comment by newbluemoon** [comment]
It has been fixed upstream. :)

**Comment by Chocimier** [comment]
Updated. Thanks for investigating, @newbluemoon.

**Pull request merged**
