### PR TITLE
zfs/spl: update to 0.7.11.

### PR DESCRIPTION
**Pull request by cr6git**
@Vaelatern please review this

### CODE REVIEW

**Comment by Cogitri** [comment]
Boots for me, does `do_check` work for you though?

**Comment by maxice8** [comment]
@Vaelatern

**Comment by cr6git** [comment]
@Cogitri `do_check` fails for `spl`
````
Making check in scripts
make[1]: Entering directory '/builddir/spl-0.7.11/scripts'
scripts/check.sh
make[1]: scripts/check.sh: Command not found
make[1]: *** [Makefile:435: check] Error 127
make[1]: Leaving directory '/builddir/spl-0.7.11/scripts'
make: *** [Makefile:502: check-recursive] Error 1
````

**Comment by Vaelatern** [comment]
Wait for my review, it'll come in the next day, and either way I'll push an update.

**Comment by Cogitri** [comment]
@cr6git make it'd make sense to not run tests in do_check then.

**Comment by Vaelatern** [comment]
@cr6git this is no fun! You broke the commit naming scheme! 
/me fixes

**Comment by Vaelatern** [comment]
Please tell me where you got the removal of `--with-blkid`.

**Comment by Cogitri** [comment]
> Please tell me where you got the removal of --with-blkid.

Seems to me as if ZFS' configure script doesn't offer that option anymore.

**Comment by Vaelatern** [comment]
e3a2d85f56 980e45a9ec

**Comment by cr6git** [comment]
> Please tell me where you got the removal of --with-blkid.

You should open your eyes in the `do_configure` phase...

**Pull request closed without merging**
