### PR TITLE
New package: grim-1.0

### PR DESCRIPTION
**Pull request by Derriick**
Grab images from a Wayland compositor [](https://wayland.emersion.fr/grim)

### CODE REVIEW

**Comment by maxice8** [comment]
Cross-compilation is failing because it can't find wayland-scanner.

Add `wayland-devel` to `hostmakedepends=`, files that need to be executed on the host system need to be there.

**Comment by maxice8** [comment]
Same recommendation of adding `scdoc` to `hostmakedepends=` apply here. See: https://github.com/void-linux/void-packages/pull/7224#discussion_r248224793

**Comment by maxice8** [comment]
On Wed, Jan 16, 2019 at 10:27:33AM +0000, Derriick wrote:
> Thank you for your recommendations. Do I just have to do a new commit in my branch and push it ?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/7222#issuecomment-454729233

Please do not push new commits to the branch, instead amend your commit

1. make the recommended changes
2. git add path/to/package
3. git commit --amend --no-edit
4. git push -f


In the end of the day what is important for Void's Git history is that a set of changes (in this case adding a package) is confined to a single commit that can be reverted.

**Comment by Derriick** [comment]
It's done, thank you for your help !

**Comment by maxice8** [comment]
Merged, thanks for your contribution!

**Pull request merged**
