### PR TITLE
Rust 1.40

### PR DESCRIPTION
**Pull request by q66**
Testing:

- [x] x86_64
- [x] x86_64-musl
- [x] ppc*
- [x] aarch64(-musl)
- [x] armv7l(-musl)
- [x] Firefox builds

Depends on https://github.com/void-linux/void-packages/pull/17671

### CODE REVIEW

**Comment by q66** [comment]
Gonna need these files mirrored from https://repo.voidlinux-ppc.org/distfiles/ to our distfiles location:

```
e930b7da1f3ae1e0d3568c06cd4cc5f68a61813a8c53adf0e97d9592f3e3425e  cargo-0.40.0-powerpc64le-unknown-linux-musl.tar.xz
d516be75b7cde33aa69db1e4fd99b222b868df3f642dada3bfed34d1db585380  cargo-0.40.0-powerpc64-unknown-linux-gnu.tar.xz
af226341d50cebc5af608375b6b200a1c10e14139812dc77a928140fe5120be9  cargo-0.40.0-powerpc64-unknown-linux-musl.tar.xz
a2a64bba73102caadf819dd268f5710c978ece0efa05aaa89cbae45a5443e880  cargo-0.40.0-powerpc-unknown-linux-gnu.tar.xz
bbbf7037590fd38c5d4b2e2ac7ddddcc13213d05885d7c1fc2eacbffa4d920f5  cargo-0.40.0-powerpc-unknown-linux-musl.tar.xz
aeb989553eb6b1e8a7473369d491c1ac4ff27a553743f19a042d759b1cbfbad9  rustc-1.39.0-powerpc64le-unknown-linux-musl.tar.xz
fa5fe636f502cd5a6af97281656dba59295d76e91158c19b59d6a970987fce8f  rustc-1.39.0-powerpc64-unknown-linux-gnu.tar.xz
f1fd45b8570bff03e22c70dcfc8cfa6e7657ab41ce082687f4bd294e08dad152  rustc-1.39.0-powerpc64-unknown-linux-musl.tar.xz
ed91f1e60b56e6bd09b003fda0aef5b99e014663033f3b2ede44a51e5b574b13  rustc-1.39.0-powerpc-unknown-linux-gnu.tar.xz
3a83a55b11774af98f199ca47bf7429338a2f1e1df5fdbffbdee6bc5ffcae5c9  rustc-1.39.0-powerpc-unknown-linux-musl.tar.xz
d7bf5bab6cd80d387fa1b9d41dd5a5825fc5de520048cc89a8d621760c44e6df  rust-std-1.39.0-powerpc64le-unknown-linux-musl.tar.xz
74f5deadb1052abf5475b3d7b204101a52337a89867daf3efde2adcd8dee78b2  rust-std-1.39.0-powerpc64-unknown-linux-gnu.tar.xz
c3455841abfb9e59ae0709fe5f0fa171212e8628bf464214734eafb46f97c4c2  rust-std-1.39.0-powerpc64-unknown-linux-musl.tar.xz
2cb595dd95d5f557b3d36006ce6fe283f324e721ad8f92e1f7772cc261787cae  rust-std-1.39.0-powerpc-unknown-linux-gnu.tar.xz
4b16d538a5a3ff8d85bd0a2bb28896ab170a340f40e40e06a8f59028285d57f6  rust-std-1.39.0-powerpc-unknown-linux-musl.tar.xz
```

@Gottox @Duncaen @the-maldridge

**Comment by Duncaen** [comment]
Done

**Comment by jnbr** [comment]
Please don't merge yet. There are issues when cross building for armv7-musl.

**Comment by q66** [comment]
Really? I cross-compiled for `armv7l-musl` just fine

**Comment by pullmoll** [comment]
FWIW I could just now cross build rust for `armv7l-musl` using rust for `x86_64` without issues. Trying with rust for `x86_64-musl` now.

**Comment by q66** [comment]
We figured it out yesterday, there is a regression in cargo that results in libraries from cross sysroot leaking into host, particularly libgcc_s; that results in certain configs breaking, e.g. aarch64-musl on x86_64-musl, with errors from host dynamic linker such as "unsupported relocation <N>" where N is some aarch64 reloc number... We will probably revert the rev in cargo locally

**Comment by q66** [comment]
added @jnbr's cargo patch to fix crossbuilds

@jnbr can you re-test this?

**Comment by jnbr** [comment]
Yes, musl builds are fine now, already tested this. Currently running glibc builds to make sure it doesn't break anything else.

**Pull request merged**
