### PR TITLE
timeshift: update to 19.01

### PR DESCRIPTION
**Pull request by ndowens**
@abenson 

Added cronie, due to launching gtk part, gives error of missing crontab. Tested to see if it will launch, but I don't have BTRFS to test with.

### CODE REVIEW

**Comment by jnbr** [comment]
There are multiple cron implementations available. Forcing a specific one (cronie) is bad.
Also, if this tool is usefull without a cron srevice running, there is no need to depend on one.

**Comment by ndowens** [comment]
> There are multiple cron implementations available. Forcing a specific one (cronie) is bad.
> Also, if this tool is usefull without a cron srevice running, there is no need to depend on one.

It doesn't run without, but what I could do, is maybe have option to install cronie(it specifically says crontab), or if not wanting a crontab, use sed to remove the dependency

**Comment by jnbr** [comment]
You can depend on `virtual?cron-daemon`. 
Imo, leaving it off to the user to install a crond-daemon is fine as well.

**Comment by ndowens** [comment]
> You can depend on `virtual?cron-daemon`.
> Imo, leaving it off to the user to install a crond-daemon is fine as well.

K. I think I will sed it out, as they can set up cron to do it via the cmdline version and still use basic stuff in GUI

**Pull request merged**
