### PR TITLE
GitHub action improve

### PR DESCRIPTION
**Pull request by sgn**

### CODE REVIEW

**Comment by ericonr** [comment]
Have you taken a look at my changes in #26773 ? They include similar fixes...

**Comment by sgn** [comment]
> Have you taken a look at my changes in #26773 ? They include similar fixes...

No, I haven't look into PR for a while xD

**Comment by sgn** [comment]
@ericonr Anyway, I think the change to `fetch-xtools.sh` and `xbps-remove git` could be merged now. As of it's now, the `show-files` step couldn't work.

**Comment by ericonr** [comment]
I think my PR is ready to merge now, if you agree with my reasoning re. the wildcards.

**Pull request closed without merging**
