### PR TITLE
mkinitcpio: add zstd dependency

### PR DESCRIPTION
**Pull request by tranzystorekk**
#### Testing the changes
- I tested the changes in this PR: **briefly**

cc @ahesford

### CODE REVIEW

**Comment by classabbyamp** [comment]
new version is coming pretty soon, is this super urgent?

**Comment by tranzystorekk** [comment]
@classabbyamp not really, i can close, just gotta remember to include these changes

**Comment by ahesford** [comment]
`zstd` is optional because not all kernels we ship use zstd-compressed modules and, even for those that do, the errors printed when `mkinitcpio` tries to decompress the modules by default (which can be disabled) don't prevent the original, compressed modules from being included.

Nevertheless, if the errors are alarming to users and the solution (installing `zstd`) isn't obvious, we can add the dependency.

**Comment by ahesford** [comment]
I pushed the update to v37 and included the `homepage` change. Using the Gitlab archive in `distfiles` breaks the version number recorded in `/usr/bin/mkinitcpio`, so I reverted to `sources.archlinux.org` for a tarball that contains proper version information.

I'm still on the fence about `zstd` and didn't include that in the `depends` with the latest update.

**Comment by ahesford** [comment]
It turns out that Arch considers `zstd` a hard requirement even as they use the `optdepends` mechanism for other compressors: https://gitlab.archlinux.org/archlinux/packaging/packages/mkinitcpio/-/blob/main/PKGBUILD

That makes a convincing enough argument that we should just pull it in, so we can merge this if you rebase.

**Pull request merged**
