### PR TITLE
haproxy: fix armv6 build

### PR DESCRIPTION
**Pull request by Johnnynator**

### CODE REVIEW

**Comment by cr6git** [comment]
`=> ERROR: Failed to install bootstrap packages!`

I got the same error on my previous PR :(

**Comment by Johnnynator** [comment]
```ERROR: [reposync] failed to fetch file `http://vm1.a-mci-us.m.voidlinux.org/current/aarch64/x86_64-repodata': Operation timed out```
Sounds like a connection issue to the used mirror. Will hopefully resolved soon.

**Comment by cr6git** [comment]
good night.

**Comment by cr6git** [comment]
https://github.com/void-linux/void-packages/commit/c5e06652bdc353bdd1d025949169b379163909e0

**Pull request closed without merging**
