### PR TITLE
[WIP] Build libva with glx (remove libva-glx)

### PR DESCRIPTION
**Pull request by st3r4g**
Since we have `libglvnd` now, it should be possible to build libva with glx support without introducing build cycles.
Untested for now
Hmm maybe the transition can be done by replace= and removing libva-glx completely

### CODE REVIEW

**Comment by ericonr** [comment]
Nice!

**Comment by st3r4g** [comment]
I have tested that the replacement of `libva-glx` with `libva` happens correctly. Couldn't test `bomi` because it seems to have a problem on its own (some missing stuff for the ui, results in a black window), I'll open an issue for that.

Now I'm thinking that `QMPlay2`, `mpv` and `qtav` don't need to be rebuilt since nothing changes for the binpkg, right?

**Comment by travankor** [comment]
>Now I'm thinking that QMPlay2, mpv and qtav don't need to be rebuilt since nothing changes for the binpkg, right? (because they weren't actually linking to libva-glx before)

Yes, I think that's correct.

**Comment by st3r4g** [comment]
ready for review

**Review by ericonr — APPROVED** [review]

**Review by ahesford — CHANGES_REQUESTED** [review]
I can confirm that this introduces no dependency cycles. However, you need `libva-glx` and `libva-glx-devel` transitional packages to pull in the new `libva` and `libva-devel`, respectively. While XBPS will recognize the `replaces` directive if a dependant is updated and requires the new merged package, it will not recognize the replacement path on its own. Transitional packages will force this.

**Comment by st3r4g** [comment]
> However, you need `libva-glx` and `libva-glx-devel` transitional packages to pull in the new `libva` and `libva-devel`, respectively. While XBPS will recognize the `replaces` directive if a dependant is updated and requires the new merged package, it will not recognize the replacement path on its own. Transitional packages will force this.

But here `libva-glx` depends on `libva` already (and same for `-devel`) so the replacement will always happen.

**Comment by ericonr** [comment]
@st3r4g could perhaps add this explanation to the commit message?

**Comment by ahesford** [comment]
OK, that makes sense.

**Review by ahesford — APPROVED** [review]

**Comment by st3r4g** [comment]
> @st3r4g could perhaps add this explanation to the commit message?

done

**Comment by ericonr** [comment]
Pending on confirmation from #18712

**Pull request closed without merging**
