### PR TITLE
htop: enable sensors support

### PR DESCRIPTION
**Pull request by the-eater**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

libsensors won't be a runtime dependency, and will only be loaded if detected

### CODE REVIEW

**Comment by ericonr** [comment]
Oh neat, good find.

**Comment by ericonr** [comment]
Ok, `--enable-sensors` is only in git master, this version should be using `--with-sensors`. Or we can wait for an update :)

**Comment by BenBE** [comment]
Next release will take a few more $UnitsOfTime … ;-)

**Comment by ericonr** [comment]
So use `--with-sensors` and leave a comment that next version will be using `--enable-sensors` instead :)

**Comment by the-eater** [comment]
haha, so default value is `check` so it worked™ anyhow.

also

`configure: WARNING: unrecognized options: --enable-cgroup, --enable-taskstats` should I just remove those in that case?

**Comment by BenBE** [comment]
The options for `configure` have been renamed recently (cf. https://github.com/htop-dev/htop/pull/482) accompanied by changing the defaults to check for the dependencies to be present. If you want to get a stable build (ensuring features are actually compiled in) it's best to specify those options explicitly.

**Comment by the-eater** [comment]
removed `--enable-cgroup --enable-taskstats` since they don't exist

**Comment by dkwo** [comment]
I do not see any temperature in `Available meters`.
Is any further configuration required?

```
$ htop --version
htop 3.0.5
$ xuname
Void 5.11.21_1 x86_64-musl GenuineIntel uptodate hold rrnFFFF
$ xpkg -v | grep sensors
libsensors-3.6.0_1
```

Thanks.

**Comment by the-eater** [comment]
Display Options -> Also show CPU Tempature

**Comment by dkwo** [comment]
Thanks.

**Pull request merged**
