### PR TITLE
musl: update to 1.1.22

### PR DESCRIPTION
**Pull request by Gottox**
tested on x86_64 with gnome.

### CODE REVIEW

**Comment by pullmoll** [comment]
This should update `cross-powerpc64-linux-musl` and the `mips*-musl`as well, no?

**Comment by xtraeme** [comment]
Yeah, please do. Hi pullmoll! I'm back 🙏

**Comment by Gottox** [comment]
updated

**Comment by pullmoll** [comment]
Welcome back @xtraeme.
Thank you @Gottox. I'm merging this locally and test some (cross-) builds.

**Comment by pullmoll** [comment]
@Gottox you need to bump the cross-*-musl version or at least the revision.

**Comment by pullmoll** [comment]
First errors when trying to cross build `x86_64-musl` and `i686-musl` packages `base-chroot-musl` are in `libgpg-error`:
```
strerror-sym.c: In function 'gpg_strerror_sym':
strerror-sym.c:45:13: warning: implicit declaration of function 'errnos_msgidxof'; did you mean 'msgidxof'? [-Wimplicit-function-declaration]
       idx = errnos_msgidxof (code);
             ^~~~~~~~~~~~~~~
             msgidxof
strerror-sym.c:47:9: error: 'errnos_msgstr' undeclared (first use in this function)
  return errnos_msgstr + errnos_msgidx[idx];
         ^~~~~~~~~~~~~
strerror-sym.c:47:9: note: each undeclared identifier is reported only once for each function it appears in
strerror-sym.c:47:25: error: 'errnos_msgidx' undeclared (first use in this function)
  return errnos_msgstr + errnos_msgidx[idx];
                         ^~~~~~~~~~~~~
make[3]: *** [Makefile:1118: gpg_error-strerror-sym.o] Error 1
make[3]: *** Waiting for unfinished jobs....
mv -f .deps/gpg_error-strsource-sym.Tpo .deps/gpg_error-strsource-sym.Po
mv -f .deps/libgpg_error_la-strsource.Tpo .deps/libgpg_error_la-strsource.Plo
mv -f .deps/libgpg_error_la-code-to-errno.Tpo .deps/libgpg_error_la-code-to-errno.Plo
mv -f .deps/libgpg_error_la-code-from-errno.Tpo .deps/libgpg_error_la-code-from-errno.Plo
mv -f .deps/libgpg_error_la-syscall-clamp.Tpo .deps/libgpg_error_la-syscall-clamp.Plo
mv -f .deps/libgpg_error_la-version.Tpo .deps/libgpg_error_la-version.Plo
mv -f .deps/libgpg_error_la-posix-thread.Tpo .deps/libgpg_error_la-posix-thread.Plo
mv -f .deps/libgpg_error_la-strerror.Tpo .deps/libgpg_error_la-strerror.Plo
mv -f .deps/libgpg_error_la-posix-lock.Tpo .deps/libgpg_error_la-posix-lock.Plo
mv -f .deps/libgpg_error_la-b64enc.Tpo .deps/libgpg_error_la-b64enc.Plo
mv -f .deps/libgpg_error_la-init.Tpo .deps/libgpg_error_la-init.Plo
mv -f .deps/libgpg_error_la-sysutils.Tpo .deps/libgpg_error_la-sysutils.Plo
mv -f .deps/gpg_error-gpg-error.Tpo .deps/gpg_error-gpg-error.Po
mv -f .deps/libgpg_error_la-b64dec.Tpo .deps/libgpg_error_la-b64dec.Plo
mv -f .deps/libgpg_error_la-spawn-posix.Tpo .deps/libgpg_error_la-spawn-posix.Plo
mv -f .deps/libgpg_error_la-visibility.Tpo .deps/libgpg_error_la-visibility.Plo
mv -f .deps/libgpg_error_la-logging.Tpo .deps/libgpg_error_la-logging.Plo
mv -f .deps/libgpg_error_la-argparse.Tpo .deps/libgpg_error_la-argparse.Plo
mv -f .deps/libgpg_error_la-estream-printf.Tpo .deps/libgpg_error_la-estream-printf.Plo
mv -f .deps/libgpg_error_la-estream.Tpo .deps/libgpg_error_la-estream.Plo
good
cp gpg-error-config-old gpg-error-config
make[3]: Leaving directory '/builddir/libgpg-error-1.36/src'
make[2]: *** [Makefile:650: all] Error 2
make[2]: Leaving directory '/builddir/libgpg-error-1.36/src'
make[1]: *** [Makefile:509: all-recursive] Error 1
make[1]: Leaving directory '/builddir/libgpg-error-1.36'
make: *** [Makefile:441: all] Error 2
=> ERROR: libgpg-error-1.36_1: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 2
=> ERROR:   in do_build() at common/build-style/gnu-configure.sh:13
```

**Comment by pullmoll** [comment]
arch | base-chroot-musl | base-system
-----|----------------|------------
x86_64-musl | [x] | [ ]
i686-musl | [x] | [ ]
aarch64-musl | [ ] | [ ]
armv5tel-musl | [ ] | [ ]
armv6l-musl | [ ] | [ ]
armv7l-musl | [ ] | [ ]
mips-musl | [ ] | [ ]
mipshf-musl | [ ] | [ ]
mipsel-musl | [ ] | [ ]
mipselhf-musl | [ ] | [ ]
ppc-musl | [ ] | [ ]
ppc64-musl | [ ] | [ ]
ppc64le-musl | [ ] | [ ]

**Comment by xtraeme** [comment]
@pullmoll sounds good, I don't remember why there was a need to have both.

**Comment by pullmoll** [comment]
No problems so far building thousands (> 8000) of `*-musl` arch packages. IMO this is ok to merge.

**Pull request merged**
