### PR TITLE
WIP: teams-bin: update to 1.4.00.26453.

### PR DESCRIPTION
**Pull request by TeddyDD**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by TeddyDD** [comment]
Welp, camera does not work, and I can't see screen shared by other people. Could someone test this version?

**Comment by arkeane** [comment]
Camera and screen sharing from others doesn't work for me too

**Comment by TeddyDD** [comment]
Protip: if you need teams for work - install them from flatpak :/

**Comment by TeddyDD** [comment]
I'm closing this, don't know how to fix it. Use flatpak I guess.

**Pull request closed without merging**
