### PR TITLE
portage: update to 2.3.101

### PR DESCRIPTION
**Pull request by teldra**

### CODE REVIEW

**Comment by Chocimier** [comment]
Please add tar and zstd to depends and checkdepends.

**Comment by teldra** [comment]
> Please add tar and zstd to depends and checkdepends.

Since there is no checkdepends I only added them to depends.

**Comment by Chocimier** [comment]
So add checkdepends variable too.

**Comment by teldra** [comment]
I was not aware, that check stage seems to be buildin. Added.

**Pull request merged**
