### PR TITLE
New Package: Scikit-video 1.1.11

### PR DESCRIPTION
**Pull request by ashbhat1**
Package for using Scikit-video.

### CODE REVIEW

**Comment by ashbhat1** [comment]
How can I rerun xlint on my computer to recreate the error from travis?

**Comment by jnbr** [comment]
> How can I run xlint on my computer to recreate the error from travis?

xlint is part of the xtools package. After installing run `xlint  srcpkgs/python3-scikit-video/template`.

**Comment by ashbhat1** [comment]
@jnbr Thanks! That helped.

**Comment by ashbhat1** [comment]
ok, It seems the commit didn't implement my change. I need to go back and fix it, I tried using git commit --amend and git push -f. I am trying to see how I won't pollute the merge request.

**Comment by ashbhat1** [comment]
ok, I changed my commit history to only include the last commit. For some reason on the pull request all the commits are showing up. Any input? Or can this be merged as is?

**Comment by jnbr** [comment]
Having the force pushes in the PR history is intentional and simplifies reviews.

> Any input? Or can this be merged as is?

According to `/usr/lib/python3.8/site-packages/scikit_video-1.1.11-py3.8.egg-info/requires.txt`, the package depends on numpy, scipy and pillow.
Please add the corresponding packages do `depends`.
You could also use a more informative and less redundant `short_desc`.
Otherwise, looks good to me.

**Comment by jnbr** [comment]
That's better.
Sorry for nitpicking but please keep short_desc down to one sentence.
Also, please squash your commits again.

**Comment by ashbhat1** [comment]
Ok, I believe I made all the fixes.

**Comment by q66** [comment]
bad commit message, should've been fixed first

**Comment by jnbr** [comment]
Damn, missed that. Sorry.

**Pull request merged**
