### PR TITLE
bloaty: Unmark nocross

### PR DESCRIPTION
**Pull request by ndowens**

### CODE REVIEW

**Comment by q66** [comment]
i kinda don't understand how any of this is supposed to actually solve the problem...

**Comment by ndowens** [comment]
I don't understand how "qemu" helps, but I retried w/o qemu and it fails.

**Comment by q66** [comment]
not a big fan of doing random changes that "make things work" without understanding why they do that

**Comment by leahneukirchen** [comment]
Wild guess: this makes a protobuf compiler for the target run on the host?

**Comment by Johnnynator** [comment]
> Wild guess: this makes a protobuf compiler for the target run on the host?

Yes, this is what currently is happening.

**Pull request merged**
