### PR TITLE
Rebuilt musl cross packages for the patched kernel-libc-headers

### PR DESCRIPTION
**Pull request by Johnnynator**
Needed for getting iwd cross compile on musl #6

### CODE REVIEW

**Comment by maxice8** [comment]
cc @pullmoll 

seems safe but i like the opinion of an expert

**Comment by pullmoll** [comment]
:shipit:

**Comment by maxice8** [comment]
wtf is that dog

and nice, will merge together with a few other stuff.

**Comment by maxice8** [comment]
it's merged, i'll take a look after shower.

**Pull request merged**
