### PR TITLE
python-requests-mock: Update to 1.7.0

### PR DESCRIPTION
**Pull request by ndowens**
Updated to 1.7.0 ; set python2 version to meta for
removal

Signed-off-by: Nathan Owens <ndowens04@gmail.com>

### CODE REVIEW

**Comment by Chocimier** [comment]
Don't make empty packages, either just remove template or make it subpkg of python3 version that depend on main package.

**Comment by ndowens** [comment]
> Don't make empty packages, either just remove template or make it subpkg of python3 version that depend on main package.

I asked @the-maldridge last night if it was better to remove or make meta and reply was along the lines of meta avoids xbps-src bug

**Comment by Chocimier** [comment]
What bug?

**Comment by ndowens** [comment]
> What bug?

No idea? Didn't say

**Pull request closed without merging**
