### PR TITLE
dnscrypt-proxy: ensure log dir is present

### PR DESCRIPTION
**Pull request by Piraty**

### CODE REVIEW

**Comment by maxice8** [comment]
should problably add logic to the runit service to make sure the logdir is available.

mkdir -p /var/log/dnscrypt-proxy
chown _dnscrypt-proxy:_dnscrypt-proxy /var/log/dnscrypt-proxy
chmod 0750 /var/log/dnscrypt-proxy

**Comment by maxice8** [comment]
also change the system account to match the other as _dnscrypt-proxy if possible.

**Comment by Piraty** [comment]
1. placing it in `run` file seems a good choice, but to my defence: i just followed example by some templates that only use `make_dirs` and not care in `run` (example: [dq](https://github.com/void-linux/void-packages/blob/master/srcpkgs/dq/template#L10))
2. chaning the system account will definetly require the `run` script to ensure correct owning

**Comment by maxice8** [comment]
On Sat, Jun 16, 2018 at 05:12:19AM -0700, Piraty wrote:
> 1. placing it in `run` file seems a good choice, but to my defence: i just followed example by some templates that only use `make_dirs` and not care in `run` (example: [dq](https://github.com/void-linux/void-packages/blob/master/srcpkgs/dq/template#L10))
> 2. chaning the system account will definetly require the `run` script to ensure correct owning
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/5#issuecomment-397808232

1. make_dirs doesn't guarantee that the directories will stay that way so if you can use run files to guarantee that they stay with the correct permissions and owners it is a big plus.

2. i have been seeing a big switch to adding _ prefix to system accounts

**Pull request merged**
