### PR TITLE
nodejs-lts: update to 12.13.1. [ci skip]

### PR DESCRIPTION
**Pull request by k4leg**
Compiled successfully on x86_64.

### CODE REVIEW

**Comment by Piraty** [comment]
@q66 (ppc patches)

**Comment by k4leg** [comment]
Also added a new package: `nodejs-lts-devel`.

**Comment by q66** [comment]
this means there will no longer be a version of node that works on ppc32 (as 12.x broke it), which will be a problem once i have fixed (or someone else has) firefox (as that needs node to build)

10.x is supported until mid 2021...

i wonder what would be the best thing to do

**Comment by k4leg** [comment]
@q66 hi! May need to add two more packages. For example, as in [Arch Linux](https://i.imgur.com/OhSpiEo.png).

**Comment by k4leg** [comment]
- Deleted files from `usr/include/node/openssl`;
- Conflicts added.

**Comment by q66** [comment]
yeah, I guess adding a new package for that should be ok - can you add it in this PR? should be mostly copying the nodejs-lts pre-update and renaming it to something else.

**Comment by k4leg** [comment]
I'm sorry, I did not understand you. Can it be simpler?  (I do not speak English. I use Google Translate.)

**Comment by Johnnynator** [comment]
@q66 He has a `nodejs-lts-10` package in #16150

**Comment by q66** [comment]
i see, then it's all fine

**Pull request merged**
