### PR TITLE
borg: update to 1.2.1.

### PR DESCRIPTION
**Pull request by TinfoilSubmarine**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by leahneukirchen** [comment]
Can this still talk to 1.1 servers?

Let's wait a bit more before merging.

**Comment by TinfoilSubmarine** [comment]
I just tested it with a server which still has 1.1.16.

**Comment by paper42** [comment]
@leahneukirchen do you think we could merge this now?

**Comment by TinfoilSubmarine** [comment]
I use rsync.net and they have 1.2.1 on their servers:
```
ssh rsync.net borg --version
```

**Pull request merged**
