### PR TITLE
pari: update to 2.13.0.

### PR DESCRIPTION
**Pull request by sgn**
@motorto @dkwo Please test.

### CODE REVIEW

**Comment by motorto** [comment]
Can't seem to compile it

'''
=> ERROR: libreadline8-8.0.004_1: failed to install 'ncurses-devel-6.2_3' dependency! (error 19)
ncurses-libs-6.2_3 in transaction breaks installed pkg `ncurses-6.2_4'
Transaction aborted due to unresolved dependencies.
=> ERROR: Please see above for the real error, exiting...
'''

**Comment by sgn** [comment]
On 2020-11-12 01:27:11-0800, André Cerqueira <notifications@github.com> wrote:
> Can't seem to compile it
> 
> '''
> => ERROR: libreadline8-8.0.004_1: failed to install 'ncurses-devel-6.2_3' dependency! (error 19)
> ncurses-libs-6.2_3 in transaction breaks installed pkg `ncurses-6.2_4'
> Transaction aborted due to unresolved dependencies.
> => ERROR: Please see above for the real error, exiting...
> '''

Please update your void-packages.

**Comment by motorto** [comment]
You are totally right ! Forgot that sorry.

The program does compile and seems to be working fine (tested with some 
small functions)

**Comment by dkwo** [comment]
It builds and works fine on x86_64-musl as well, thank you.
I will try to build sagemath using this version soon, but first I'd like to update isl or isl15.

**Pull request merged**
