### PR TITLE
 gajim: update to 1.9.1. 

### PR DESCRIPTION
**Pull request by AnInternetTroll**
- **python3-nbxmpp: update to 5.0.1.**
- **gajim: update to 1.9.1.**

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by Emru1** [comment]
tested, looks ok

**Comment by lissine0** [comment]
Works for me too on x86_64-glibc

**Comment by lissine0** [comment]
If I do `xbps-install -Su gajim` it only updates gajim (it doesn't update python3-nbxmpp, the library it uses)
Shouldn't that command update all its dependencies as well?

**Comment by Emru1** [comment]
```
=> ERROR: gajim-1.9.1_2: specifying version in build dependency 'python3-nbxmpp>=5.0.1' is invalid, template version is used always
```
I added `python3-nbxmpp>=5.0.1` to `depends`

**Comment by ahesford** [comment]
We don't encode minimum version restrictions in general. The shlib dependencies from `common/shlibs` are a special case, because that is required to not break package management, and the version restrictions are automatically applied from a central database whose consistency is enforced by `xbps-src`. Manual specification is likely to be incorrect and drift from reality over time.

Users attempting partial ugprades are expected to understand that software might have higher minimum dependencies and either a) update their entire systems; or b) iteratively update dependencies until their systems are in a suitably consistent state.

**Comment by Emru1** [comment]
I think `Manual.md` should be updated to specify that.
[Manual](https://github.com/void-linux/void-packages/blob/master/Manual.md#optional-variables) states, that one can specify versioned dependency in `depends` variable.

**Pull request merged**
