### PR TITLE
 gimp: depend on mypaint-brushes1

### PR DESCRIPTION
**Pull request by Chocimier**

### CODE REVIEW

**Comment by Gottox** [comment]
What's the effect of this change?

**Comment by biopsin** [comment]
For only Gimp users a extra mypaint-brushes v1.3 is installed side by side, v2.0 remains and won't be problematic unless user activates it in settings. 
For Mypaint and Gimp users duplicate brush sets maybe? needs testing

mypaint-brushes1 pkg needs to be removed when either Gimp is patched or libmypaint handles it [issue 128](https://github.com/mypaint/libmypaint/issues/128)

**Comment by Chocimier** [comment]
@Gottox: mypaint-brushes got updated from major version 1 to 2, but gimp can't use or be build with 2.

**Comment by Gottox** [comment]
Ok to merge. Thanks for the explaination!

**Comment by briend** [comment]
@biopsin I just committed a patch to fix https://github.com/mypaint/libmypaint/issues/128

**Pull request merged**
