### PR TITLE
apache: move rotatelogs into separate package.

### PR DESCRIPTION
**Pull request by freshprince**
I don't know if this is desired.  I'd like to use `rotatelogs` on systems with little storage space so I don't want to install the whole of Apache.

### CODE REVIEW

**Comment by maxice8** [comment]
revbump

**Comment by freshprince** [comment]
> revbump
fixed.

**Comment by Duncaen** [comment]
[svlogd(8)](https://man.voidlinux.org/svlogd.8) which comes with runit does log rotation too. It seems like it is very similar to rotatelogs, but also supports processors after a log file is rotated.

**Comment by freshprince** [comment]
Thanks for the hint!  I can indeed do what I need to with svlogd (except for file permissions but that's not a show-stopper for me).

**Comment by freshprince** [comment]
This is no longer really necessary for me.  Maybe a apache-utils package would make more sense if at all.

**Pull request closed without merging**
