### PR TITLE
qemu(-user-static): update to 9.0.2, libvirt(-python3): update to 10.5.0

### PR DESCRIPTION
**Pull request by dataCobra**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86_64-musl
  - i686

### CODE REVIEW

**Review by classabbyamp — CHANGES_REQUESTED** [review]
this is the first time you are touching all of these packages. please don't adopt them.

**Comment by dataCobra** [comment]
> this is the first time you are touching all of these packages. please don't adopt them.

Removed the maintainer change.

**Comment by dataCobra** [comment]
Forgot to restore the maintainer in libvirt-python3.

Is fixed now.

**Comment by dataCobra** [comment]
Found a panic that I need to check.

Might not be version related. I will give an update when tested.

**Comment by dataCobra** [comment]
The issue is not related with the update so everything is fine here.

**Comment by classabbyamp** [comment]
remove ci skip and force push please, i don't see why skipping ci would be warranted here

**Comment by dataCobra** [comment]
Force pushed after removing ci skip.

**Comment by classabbyamp** [comment]
let's report those i686 test fails https://gitlab.com/qemu-project/qemu/-/issues

**Pull request merged**
