### PR TITLE
elogind: fix building of sway with musl

### PR DESCRIPTION
**Pull request by Derriick**
I'm not sure it is the best idea, but it is the only solution I found to be able to build sway (rc2 and rc3) with musl

### CODE REVIEW

**Comment by maxice8** [comment]
don't move conf_files

**Comment by maxice8** [comment]
This is not an update so don't have the commit be named as such

**Comment by maxice8** [comment]
Please provide an error message so we can work out the issue, this honestly looks like forcing elogind to work around stuff

**Comment by Derriick** [comment]
I change that.
For conf_files emplacement I just followed xlint recommendations and the commit was named with xbump

**Comment by maxice8** [comment]
On Tue, Feb 19, 2019 at 09:59:30PM +0000, Derriick wrote:
> I change that.
> For conf_files emplacement I just followed xlint recommendations and the commit was named with xbump
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/8928#issuecomment-465328106

I really need to revert that change.

xbump as the name implies if meant for bumping (updating the version of a package).

**Comment by maxice8** [comment]
commit has 2  problems:

- POSIC_C_SOURCE looks wrong
- It doesn't tell me what it is doing, be more descriptive (something like `elogind: fix building of sway with musl`, then fill the body of the commit with a detailed explanation)

**Comment by CameronNemo** [comment]
Have you talked with upstream (elogind) at all about the issue?

**Comment by Derriick** [comment]
> 
> 
> commit has 2 problems:
> 
>     * POSIC_C_SOURCE looks wrong
> 
>     * It doesn't tell me what it is doing, be more descriptive (something like `elogind: fix building of sway with musl`, then fill the body of the commit with a detailed explanation)

Done. Thank you for your support. I will open an issue too with more details.

**Comment by Derriick** [comment]
So the problem comes directly from systemd, which now has a patch (https://github.com/systemd/systemd/pull/11790).
elogind also has it now ([src/systemd/sd-event.h#L74](https://github.com/elogind/elogind/blob/104a897631bf3456c7e119e8015fa2442f9f0ae6/src/systemd/sd-event.h#L74)) and it should be available in a future release.
In the meantime, I think that this patch can be used until the next version of elogind is released.

Please let me know if I have another change to make so that this pull request can be merged.

**Pull request merged**
