### PR TITLE
sabnzbd: update to 3.2.1

### PR DESCRIPTION
**Pull request by vaft22**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Please add `python3-Cheroot` explicitly to `depends` :)

**Comment by vaft22** [comment]
> Please add `python3-Cheroot` explicitly to `depends` :)

May I ask why this should be? I checked Debian, Arch, and Gentoo packages, and they all use the same dependency format: sabnzbd depends on python3-CherryPy, and python3-CherryPy depends on python3-Cheroot.

**Comment by ericonr** [comment]
Sorry, I should have linked it! It might be nice to include the link in the commit message, even:

https://github.com/sabnzbd/sabnzbd/blob/3.2.1/requirements.txt

The reasoning being that if `cherrypy` changes its dependencies, `cheroot` will still be available for `sabnzbd` :)

**Comment by ericonr** [comment]
I squashed the commits locally and pushed, thanks!

**Pull request closed without merging**
