### PR TITLE
ansible: update to 2.5.5

### PR DESCRIPTION
**Pull request by iaroki**

### CODE REVIEW

**Comment by the-maldridge** [comment]
LGTM from void-ops; once SPDX identifier is added then merge away!

**Comment by iaroki** [comment]
Updated

**Comment by maxice8** [comment]
license is GPL-3.0-or-later

**Comment by iaroki** [comment]
@maxice8 How do you see this?
I can't find any "or later" occurences here: https://github.com/ansible/ansible/blob/devel/COPYING

**Comment by maxice8** [comment]
On Mon, Jun 18, 2018 at 12:53:09AM -0700, iaroki wrote:
> @maxice8 How do you see this?
> I can't find any "or later" occurences here: https://github.com/ansible/ansible/blob/devel/COPYING
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/111#issuecomment-397970863


the source files have headers, you can check a few and make an educated guess

a few have

# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

the + indicates -or-later

and https://github.com/ansible/ansible/blob/devel/lib/ansible/release.py has the full text that says

# Ansible is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

**Comment by iaroki** [comment]
Thanks for explanation. 
It is not so obvious to check sources if license file is present.

**Comment by maxice8** [comment]
>  It is not so obvious to check sources if license file is present.

sadly GNU licenses follow the complexity of it's software so you have to take a look at the sourcefiles to know if they are only that license or allow you to upgrade to a future version.

**Pull request merged**
