### PR TITLE
mesa: update to 22.3.5.

### PR DESCRIPTION
**Pull request by ardadem**
#### Testing the changes
- I tested the changes in this PR: **YES**

~~**Draft until 22.3.1.**
Feel free to review and test it meantime.~~

### CODE REVIEW

**Comment by zlice** [comment]
Was just about to make a PR. 22.3.1 has a bunch of Intel fixes. Switching to that instead of git-latest but so far it's been great.

**Comment by biopsin** [comment]
fixes gallium issue for AMD Aruba introduced in 22.2.x

`../src/gallium/drivers/r600/r600_state_common.c:961 r600_shader_select - Failed to build shader variant (type=1) -1 EE ../src/gallium/drivers/r600/r600_shader.c:193 r600_pipe_shader_create - translation from TGSI failed !`

**Comment by bubba-champion** [comment]
I think we should move `/usr/share/vulkan/icd.d/radeon_icd.i686.json` from `mesa-vulkan-radeon` to `mesa-vulkan-radeon-32bit`, and do the same with `mesa-vulkan-intel`. Also, I suppose we can move `/usr/share/drirc.d/00-radv-defaults.conf` from `mesa` to `mesa-vulkan-radeon`.

**Comment by vincele** [comment]
I tested this on x86_64, Radeon RX 550.
Desktop, browsing, glmark2, extreme tux racer.
Works OK

**Comment by ardadem** [comment]
> I think we should move `/usr/share/vulkan/icd.d/radeon_icd.i686.json` from `mesa-vulkan-radeon` to `mesa-vulkan-radeon-32bit`, and do the same with `mesa-vulkan-intel`.

It is on purpose, there is a comment about that on the template;

```
# ensure that each eligible architecture ships its multilib icd files
# in some cases, multiple counterpart architectures may exist (aarch64)
# this allows us to not have to ship these files in the current *-32bit packages
```

> Also, I suppose we can move /usr/share/drirc.d/00-radv-defaults.conf from mesa to mesa-vulkan-radeon.

This is how it should be, thanks for the feedback.

**Comment by bubba-champion** [comment]
Works well on RX 6400 (x86_64-glibc) in steam games (DXVK, Native), and with multimedia (mpv).

**Comment by bubba-champion** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/tags/mesa-22.3.2

**Comment by ardadem** [comment]
Regular rebase.

**Comment by Seltyk** [comment]
[22.3.3](https://gitlab.freedesktop.org/mesa/mesa/-/tags/mesa-22.3.3) was released today; consider bumping

**Comment by motorto** [comment]
From my testing the lto is only broken currently on x86_64 so probably we could disable lto only for x86_64 and enable for all the others archs. (Yeah I was working on updating this package, wihtout looking for active PR's) also bump it to x86_64

```
# lto fails on x86 only, no need to disable on all archs
case "$XBPS_TARGET_MACHINE" in
	x86_64*) configure_args+=" -Db_lto=false" ;;
	*) configure_args+=" -Db_lto=true" ;;
esac
```

**Comment by motorto** [comment]
@ardadem was there an issue with x86_64 ?

**Comment by ardadem** [comment]
@motorto Not really, LTO works well with x86_64 but it fails on i686. I think you got confused on that.

**Comment by motorto** [comment]
> @motorto Not really, LTO works well with x86_64 but it fails on i686. I think you got confused on that.

Hum weird, unless x86 on alpine only refers to i686 ... 

https://git.alpinelinux.org/aports/tree/main/mesa/APKBUILD#n107

**Comment by JamiKettunen** [comment]
> Hum weird, unless x86 on alpine only refers to i686 ...

@motorto It does, see https://wiki.alpinelinux.org/wiki/Architecture & https://dl-cdn.alpinelinux.org/alpine/edge/main/

**Comment by lemmi** [comment]
Have been running it for about 2 days. Too bad upstream didn't merge `radeonsi` support for `rusticl` yet https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/19232

**Comment by motorto** [comment]
Using it the last week and it works fine on my side !

**Comment by bubba-champion** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/tags/mesa-22.3.4

**Comment by HadetTheUndying** [comment]
This update caused `gnome` to break in a number of ways. I'm going to take some disk snapshots tomorrow and then I'll post screenshots. I verified it was this update by rolling back mesa. If someone else that has more time than i do would like to test I would appreciate it.

**Comment by ardadem** [comment]
@HadetTheUndying by "this update" you mean 22.3.4? Can you also try build with `-Db_lto=false`.

**Comment by bubba-champion** [comment]
I can confirm with `-Db_lto=false` all works fine, but without it gnome interface completely broken.

**Comment by motorto** [comment]
Don't use gnome myself, but that's weird, going to spin a vm to check why, meanwhile it looks okay to disable lto

**Comment by HadetTheUndying** [comment]
> @HadetTheUndying by "this update" you mean 22.3.4? ~Can you also try build with `-Db_lto=false`.<~ Can you try now?

I won't have a chance to test until Monday. I hadn't done any system maintenance in awhile so unfortunately i didn't do a very good test case when I rolled back since i also reinstalled gnome, xorg and all that jazz. I'll take a snapshot of my disk Sunday night and then do the upgrade again.

**Comment by Piraty** [comment]
@JamiKettunen @jcgruenhage might be interested to know that there is a bug in 22.3.4 affecting the pinephone (bug first appeared in mesa-22.3.3 with 2adab724e59c662a046cb1da8bfb3177330e01da )

**Comment by HadetTheUndying** [comment]
> I can confirm with `-Db_lto=false` all works fine, but without it gnome interface completely broken.

Just for reference you experienced the font rendering problems and just general black display blocks? I haven't had time to do any testing since my initial report.

**Comment by bubba-champion** [comment]
> > I can confirm with `-Db_lto=false` all works fine, but without it gnome interface completely broken.
> 
> Just for reference you experienced the font rendering problems and just general black display blocks? I haven't had time to do any testing since my initial report.

I experienced problems with font rendering, and also artifacts in the steam overlay while playing.

**Comment by HadetTheUndying** [comment]
> > > I can confirm with `-Db_lto=false` all works fine, but without it gnome interface completely broken.
> > 
> > 
> > Just for reference you experienced the font rendering problems and just general black display blocks? I haven't had time to do any testing since my initial report.
> 
> I experienced problems with font rendering, and also artifacts in the steam overlay while playing.

Just to clarify, disabling LTO fixed that? I'll have some time to test over the weekend. Mesa 23 is likely just around the corner at this point though.

**Comment by bubba-champion** [comment]
> > > > I can confirm with `-Db_lto=false` all works fine, but without it gnome interface completely broken.
> > > 
> > > 
> > > Just for reference you experienced the font rendering problems and just general black display blocks? I haven't had time to do any testing since my initial report.
> > 
> > 
> > I experienced problems with font rendering, and also artifacts in the steam overlay while playing.
> 
> Just to clarify, disabling LTO fixed that? I'll have some time to test over the weekend. Mesa 23 is likely just around the corner at this point though.

Yes, as I wrote earlier, `-Db_lto=false` fixes all the above problems.

**Comment by motorto** [comment]
Fedora has this patch: https://src.fedoraproject.org/rpms/mesa/blob/rawhide/f/gnome-shell-glthread-disable.patch 

Can you enable lto again with this patch ?

**Comment by ardadem** [comment]
> Fedora has this patch: https://src.fedoraproject.org/rpms/mesa/blob/rawhide/f/gnome-shell-glthread-disable.patch
> 
> Can you enable lto again with this patch ?

It is not gnome related, i've also experienced it on WM.

Also Fedora keeps LTO disabled. See https://src.fedoraproject.org/rpms/mesa/blob/rawhide/f/mesa.spec#_341.

**Comment by ardadem** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/7743

It is actually broken but sometimes it is not.

> Given that the commits which (un)break things with LTO tend to be not directly related to any code actually used on the affected setup, there seem to be other bigger factors than the specific commit. I'd say any commit which exists today has to be assumed to be potentially affected.

Anyways, we should keep disabled.

> Mesa is known to hit various issues with LTO, I'd recommend disabling it for now.

**Comment by ardadem** [comment]
> @JamiKettunen @jcgruenhage might be interested to know that mesa-22.3.3 and mesa-22.3.4 have a [bug affecting the pinephone](https://gitlab.freedesktop.org/mesa/mesa/-/issues/8198)

Should be fixed now.

**Pull request closed without merging**
