### PR TITLE
iwd: update to 1.13.

### PR DESCRIPTION
**Pull request by ericonr**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by st3r4g** [comment]
Could you adjust the man page for the changes in `resolvconf-default.patch`?
It was suggested [here](https://github.com/void-linux/void-packages/pull/25923#issuecomment-719068530) but not actually applied...

**Comment by ericonr** [comment]
Will look into it, I think we should patch the rst.

**Comment by ericonr** [comment]
Fixed.

**Comment by st3r4g** [comment]
Nice. I'm testing the update, looks ok.

**Pull request merged**
