### PR TITLE
grub-btrfs: update to 4.9.

### PR DESCRIPTION
**Pull request by teldra**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (x86_64-GLIBC)
- [x] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [x] aarch64-musl
  - [x] armv7l
  - [x] armv6l-musl

### CODE REVIEW

**Review by ericonr — COMMENTED** [review]
Not sure how I feel about the patch... I would also consider making the patch smaller by moving the files around in `post_install`.

@FollieHiyuki and @anjandev , thoughts?

**Comment by FollieHiyuki** [comment]
I agree with moving the file using `post_install()`. I would rather patch the source to reflect the new config path:

```
diff --git a/41_snapshots-btrfs b/41_snapshots-btrfs
index 2a1f215..ca71206 100755
--- a/41_snapshots-btrfs
+++ b/41_snapshots-btrfs
@@ -41,7 +41,7 @@ prefix="/usr"
 exec_prefix="/usr"
 datarootdir="/usr/share"
 sysconfdir="/etc"
-grub_btrfs_config="${sysconfdir}/default/grub-btrfs/config"
+grub_btrfs_config="${sysconfdir}/conf.d/grub-btrfs"
 
 [[ -f "$grub_btrfs_config" ]] && . "$grub_btrfs_config"
 . "$datarootdir/grub/grub-mkconfig_lib"
diff --git a/Makefile b/Makefile
index 6ffe8c1..12c760d 100644
--- a/Makefile
+++ b/Makefile
@@ -14,7 +14,6 @@ install:
                exit 1; \
        fi
        @install -Dm755 -t "$(DESTDIR)/etc/grub.d/" 41_snapshots-btrfs
-       @install -Dm644 -t "$(DESTDIR)/etc/default/grub-btrfs/" config
        @install -Dm644 -t "$(LIB_DIR)/systemd/system/" grub-btrfs.service
        @install -Dm644 -t "$(LIB_DIR)/systemd/system/" grub-btrfs.path
        @install -Dm644 -t "$(SHARE_DIR)/licenses/$(PKGNAME)/" LICENSE
@@ -33,7 +32,6 @@ uninstall:
        fi
        @grub_dirname="$$(grep -oP '^[[:space:]]*GRUB_BTRFS_GRUB_DIRNAME=\K.*' "$(DESTDIR)/etc/default/grub-btrfs/config" | sed "s|\s*#.*||;s|(\s*\(.\+\)\s*)|\1|;s|['\"]||g")"; \
         rm -f "$${grub_dirname:-/boot/grub}/grub-btrfs.cfg"
-       @rm -f "$(DESTDIR)/etc/default/grub-btrfs/config"
        @rm -f "$(DESTDIR)/etc/grub.d/41_snapshots-btrfs"
        @rm -f "$(LIB_DIR)/systemd/system/grub-btrfs.service"
        @rm -f "$(LIB_DIR)/systemd/system/grub-btrfs.path"
```

and use `/etc/conf.d/grub-btrfs` (instead of `grub-btrfs.cfg`) so that it aligns with our naming scheme (as for `snapper`)
And maybe rename `grub-btrfs-runit` to `runit-grub-btrfs` for naming consistency (we have `runit-iptables` and `runit-kdump` for example)

**Comment by ericonr** [comment]
All that said, I'd suggest talking this out with upstream; maybe they are open to officially supporting this setup. I don't like the thought of carrying patches forever :p

**Comment by teldra** [comment]
I have proposed changes upstream: https://github.com/Antynea/grub-btrfs/pull/150 so I just update this for now.

**Comment by sgn** [comment]
Is this package built and tested? f01490cac7

**Pull request merged**
