### PR TITLE
New packages: fl{aa,amp,cluster,log,msg,net,wkey,wrap}

### PR DESCRIPTION
**Pull request by Goorzhel**
/label new-package wip
@classabbyamp (https://github.com/void-linux/void-packages/pull/38771#issuecomment-1221202322)

I need help with:
1. ~~picking a good name for the meta-package (`fldigi-full` was a wild guess),~~
2. ~~`fl{amp,cluster,msg}` failing to set `USE_X` (I left a writeup in the `flamp` template), and~~
3. the applications that _do_ build presenting an all-black theme: black font on black background. Just my machine (running sway), or something wrong with the way I built the programs?

#### Testing the changes
- I tested the changes in this PR: **briefly**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

### CODE REVIEW

**Comment by classabbyamp** [comment]
I'm not sure we need a metapackage for all of them

**Comment by Goorzhel** [comment]
Item 2 in parent message: I was missing `hostmakedepends="pkg-config"`.

**Comment by classabbyamp** [comment]
image

can confirm the weirdness. Also, I don't appear to be able to open any of the menus at the top, fllog just freezes

**Comment by classabbyamp** [comment]
ok the same colour thing is happening in fldigi, but not flrig

**Comment by Goorzhel** [comment]
I could reproduce the weirdness on two OSes set up somewhat identically (i.e., running `sway` upon `seatd`):
- FreeBSD 13.1-R, `pkg install -y flamp`
- NixOS 22.05.2512.a82127cea64, built from upstream tarball in `nix-shell -p pkgconfig -p fltk`

@classabbyamp doesn't use Wayland, so it's probably not something specific to Wayland either. (Even so, I should try to reproduce this in an X environment.) Nor does it seem specific to `fltk` alone, because `dillo` is built on `fltk` and I saw no problems there.

**Comment by classabbyamp** [comment]
I think this is something to bring up upstream

**Comment by Goorzhel** [comment]
> ok the same colour thing is happening in fldigi, but not flrig

On FreeBSD, both work.  On NixOS, flrig works, and fldigi behaves like `flamp`.

> I think this is something to bring up upstream

Agreed.

**Comment by Goorzhel** [comment]
I left `fltk-devel` as a `depends` in one of the packages. :clown_face:

**Comment by Goorzhel** [comment]
The problem went away for @classabbyamp (`bspwm`), but not for me (`sway`). I definitely need to try an X environment.

**Comment by Goorzhel** [comment]
I tried [six different environments](https://groups.io/g/linuxham/topic/93843043) — {{Void,FreeBSD} laptop,NixOS VM} plus {sway,i3} —  and the fltk test programs displayed correctly only on the NixOS VM, in both X and Wayland.

I wanted to figure out what NixOS was doing differently, but I went about it in a very caveman-like way: I went back to the Void system and tried compiling with each dependency I figured I was missing, one-by-one:
```
$ xi -y libXft-devel
$ ./configure && make -j8 && test/preferences && make clean
$ # and so on, for libX{inerama,cursor,fixes,...}
```
But I couldn't get the all-black UI to go away. I also tried `./configure --enable-local{jpeg,zlib,png}` — same behavior.

There is almost certainly something very stupid I'm missing. But I'll devote some more time to finding it before asking [up-upstream](https://www.fltk.org/).

**Comment by Goorzhel** [comment]
I was close to giving up on this but there's less work left than I thought. I just need to redo the fltk tests, take some screenshots, and file an issue at github.com/fltk/fltk.

**Comment by Goorzhel** [comment]
Well, damn. I downloaded the [latest FLTK snapshot](https://www.fltk.org/pub/fltk/snapshots/fltk-1.4.x-20221223-e7eac09c.tar.bz2) (fltk/fltk@e7eac09c), compiled the tests, and saw them display perfectly. Then [I downloaded the 1.3.8 release](https://www.fltk.org/pub/fltk/1.3.8/fltk-1.3.8-source.tar.gz) separately, compiled the tests there\*, and got that all-black UI again.

It seems this is stuck until FLTK 1.4.

\* `./configure && make -j8 && ./test/preferences`

**Comment by Goorzhel** [comment]
@classabbyamp, if you have a spare moment can you download the two tarballs I linked above and try `./configure && make -j8 && ./test/preferences` inside each of them?

**Pull request closed without merging**
