### PR TITLE
mutt: update to 1.11.1

### PR DESCRIPTION
**Pull request by hanspolo**

### CODE REVIEW

**Comment by maxice8** [comment]
@Vaelatern

**Comment by Vaelatern** [comment]
Slightly surprised libinotify isn't in the depends on this.
```
 + inotify is used for local mailbox monitoring on Linux.  Configuration flag
    --disable-filemonitor turns this off.
```

Need to account (in alternatives) for:
```
  ! pgpring has been renamed to mutt_pgpring.
```

**Comment by ndowens** [comment]
1.11.2 is now released

**Comment by Gottox** [comment]
@hanspolo please update your PR.

**Pull request closed without merging**
