### PR TITLE
sharenix: update to 0.11.0a

### PR DESCRIPTION
**Pull request by HadetTheUndying**
Sharenix is a version behind in the repos right now, I've mostly done this to familiarize myself with github for future package submissions. But this sat out of date for awhile so i figured this would be my first one.

### CODE REVIEW

**Comment by not-chicken** [comment]
Thanks for the contribution. Please use this syntax for updates  `<pkgname>: update to <version>`

**Comment by HadetTheUndying** [comment]
Gotcha can do in the future

**Comment by jnbr** [comment]
> Gotcha can do in the future

please use the commit message syntax in this PR already. You can change it with it `git commit --amend` and then `git push --force`

**Comment by HadetTheUndying** [comment]
> > Gotcha can do in the future
> 
> please use the commit message syntax in this PR already. You can change it with it `git commit --amend` and then `git push --force`

Done, apologies i misunderstood. Should just be waiting on the builds to validate now.

**Pull request merged**
