### PR TITLE
gnuradio: Add Qt support

### PR DESCRIPTION
**Pull request by repk**
The patches are fetched from debian package and are backport of current
gnuradio-qt5 branch.

[ci skip]

### CODE REVIEW

**Comment by bra1nwave** [comment]
I think, it would be better if this is split up into a subpackage (`gnuradio-qt`).

**Comment by repk** [comment]
Do you mean that main gnuradio is still compiled with those patches but the libgnuradio-qtgui is moved to a subpackage (i.e. gnuradio-qt) ?

**Comment by bra1nwave** [comment]
Yes, exactly.

**Comment by bra1nwave** [comment]
Forget what I said. I thought it's a separate Qt GUI, sorry.

**Comment by repk** [comment]
Yes gnuradio binary will be looking for a libgnuradio-qtgui*.so at runtime, so making it a subpkg won't work. Too bad, this was an idea I liked.

**Comment by maxice8** [comment]
Isn't this upstream ? i don't want to add 10k lines, i added 2k on various occasions but 10k is more than too big

**Comment by repk** [comment]
Yes this is upstream since 2016, ready for 3.8 but I don't know when would that be released. It could be tomorrow or in another two years. Those patches were only plain backports to 3.7.

On a side note they are in feature freeze since my PR, so the release can be coming up soon.

At the end if you don't want to add 10k line patches, then fine I won't fight against that.

**Pull request closed without merging**
