### PR TITLE
rust: fix musl build

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by Cogitri** [comment]
Currently testing this...

**Comment by Gottox** [comment]
I'm test compiling aarch64 atm.

**Comment by Gottox** [comment]
Native testbuilding afterwards and merging if it succeeds.

**Comment by Gottox** [comment]
```
error: cannot produce dylib for `rustc_driver v0.0.0 (file:///builddir/rustc-1.28.0-src/src/librustc_driver)` as the target `aarch64-unknown-linux-musl` does not support these crate types
```

**Comment by Cogitri** [comment]
Mind giving uploading the whole log?

**Comment by Gottox** [comment]
https://gist.github.com/ab75b3796a9383423deecc0828494ac5

**Comment by atweiden** [comment]
Could this have anything to do with it? https://github.com/void-linux/void-packages/blob/892afb70b2355862ab49316c10dabc88eb42bce1/srcpkgs/rust/template#L151

I believe it's erroneously double double-quoted.

**Comment by Gottox** [comment]
https://github.com/rust-lang/rust/issues/44991

**Comment by Gottox** [comment]
@atweiden I don't think that makes any difference.

**Comment by Cogitri** [comment]
> I believe it's erroneously double double-quoted.

It doesn't make a difference - although those double quotes are unnecessary.

**Comment by Cogitri** [comment]
> rust-lang/rust#44991

Thanks for liking to that, found it already - currently testing some stuff.

**Comment by Gottox** [comment]
The error is triggered in cargo afaics:
https://github.com/rust-lang/cargo/blob/master/src/cargo/core/compiler/context/compilation_files.rs#L323

**Comment by Gottox** [comment]
This function may return the wrong result.

https://github.com/rust-lang/cargo/blob/master/src/cargo/core/compiler/context/compilation_files.rs#L358-L454

**Comment by Cogitri** [comment]
Hm, curious why no other musl distro (e.g. alpine) carries a patch for that though...

Also, maybe I should just combine this with a rust bump to 1.29.1?

**Comment by jnbr** [comment]
I think it is just a matter of disabling crt-static for musl - currently testing. We do this for x86_64-musl already. Alpine does this for all architectures.

**Comment by Cogitri** [comment]
Currently testing with https://git.alpinelinux.org/cgit/aports/plain/community/rust/musl-fix-linux_musl_base.patch

**Comment by jnbr** [comment]
aarch64-musl build completed with `crt_static_default = false`. I've set it in `src/librustc_target/spec/linux_musl_base.rs`, can as well be done in the architecture specific profiles.

**Comment by Cogitri** [comment]
Alright, mind leaving a patch here then?

**Comment by jnbr** [comment]
```
--- rustc-1.28.0-src/src/librustc_target/spec/linux_musl_base.rs.orig   2018-10-08 21:02:21.588611506 +0200
+++ rustc-1.28.0-src/src/librustc_target/spec/linux_musl_base.rs        2018-10-08 21:02:40.846454873 +0200
@@ -61,7 +61,7 @@
     base.post_link_objects_crt.push("crtn.o".to_string());

     // These targets statically link libc by default
-    base.crt_static_default = true;
+    base.crt_static_default = false;
     // These targets allow the user to choose between static and dynamic linking.
     base.crt_static_respected = true;
```
This is redundant to `srcpkgs/rust/files/musl.patch`.

**Comment by Cogitri** [comment]
Testing...

**Comment by maxice8** [comment]
good to merge ?

**Pull request merged**
