### PR TITLE
zfs: upgrade to 2.1.0

### PR DESCRIPTION
**Pull request by ahesford**
Works on `x86_64` and within ZFSBootMenu. Adds a few new features so could use a bit of testing.

cc: @Vaelatern @ericonr @zdykstra

### CODE REVIEW

**Comment by zdykstra** [comment]
Tested on x86_64 and ppc64le, no issues so far.

**Comment by ericonr** [comment]
I took a quick look, and /usr/src/zfs-2.1.0/tests takes up 35MB uncompressed. We should obviously test building for a few kernels without it, but if possible it would certainly make the package a tad smaller for little work on our side.

@Vaelatern, thoughts?

**Comment by Vaelatern** [comment]
I'm OK with turning tests into a subpackage for those who want it

**Comment by ahesford** [comment]
The `/usr/src/zfs-2.x.y` directory is just a pristine version of the upstream source (except for any patches we've applied, especially the one that skips building user-space utilities that would just be thrown out by DKMS anyway).

1. If we start pruning tests, why not also prune contrib and all of the other utilities? We start down a slippery slope regarding where to stop removing pieces unnecessary for the kmods.
2. If the answer is that tests are obviously different because they are, well, tests; and the test suite is several times *larger* than the kmod source, which itself is about as large as the rest of the tree combined; then I wonder what value a tests subpackage has. Using the build-time test suite we ship in this package is not much easier than fetching an upstream source tarball and running them in a different place.
 
My take is that, if tests are special enough to want to eliminate, we just drop them. If somebody finds value in the tests, we should just keep the tree pristine.

**Comment by ericonr** [comment]
I generally agree with 2 and think we should drop them entirely.

**Comment by Vaelatern** [comment]
I somewhat favor a subpackage, so a machine admin doesn't need to make sure trees are synced with xbps

**Comment by ahesford** [comment]
When building the module, DKMS runs the package's configure script; this references the `tests` tree and fails, preventing the module from building. I attempted to remove `tests` in `post_extract`, but this directory is listed as a requirement in both `Makefile.am` and `configure.ac`. While this is probably an easy fix (remove all `tests/*` file references in `configure.ac` and remove references to the `tests` directories in, *e.g.*, the `SUBDIRS` specification of `Makefile.am`), I'm not thrilled about carrying patches to the build system to support test removals, especially since there is some disagreement about whether the tests should just be removed or offered in a subpackage.

I'm merging as-is for now; anybody who wants to pick up the effort can do so.

**Pull request merged**
