### PR TITLE
Packages which need -fcommon for gcc10

### PR DESCRIPTION
**Pull request by pullmoll**
Packages I found doing `xbps-fbulk` for `x86_64`.
See #24258

### CODE REVIEW

**Comment by sgn** [comment]
`mesa` also needs to be rebuilt, but update to 20.1.5 fixed `-fcommon` #24312

**Comment by pullmoll** [comment]
Merged and builds fine with `gcc-10.2.0` as is.

**Comment by pullmoll** [comment]
Ping @void-linux/pkg-committers does anyone care to review? Otherwise I'd merge it as is.

**Comment by q66** [comment]
vtk update needs a freecad rebuild

other than that, i think let's just merge it

**Comment by pullmoll** [comment]
Ok, revbump for freecad is there. The github interface doesn't want to rebase and merge even though the branch is on top of master. Merge manually?

**Pull request closed without merging**
