### PR TITLE
syft: update to 0.62.2.

### PR DESCRIPTION
**Pull request by jcgruenhage**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by classabbyamp** [comment]
0.62.3 is available

**Comment by classabbyamp** [comment]
can you rebase for ci?

**Comment by jcgruenhage** [comment]
I thought I had, apparently not. Thanks for the heads-up

**Comment by jcgruenhage** [comment]
So, this was up to date for not even an hour. 47 minutes after this was merged, we got 0.63.0 upstream ;D

**Comment by classabbyamp** [comment]
🤦‍♀️

**Pull request merged**
