### PR TITLE
fwupd-efi & gnu-efi-libs update

### PR DESCRIPTION
**Pull request by dataCobra**
#### Testing the changes
- I tested the changes in this PR: **NO**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86_64-musl
  - i686
  - aarch64 (cross)
  - armv7l (cross)

@dkwo are you able to test this?

Edit: Are revbumps necessary for the packages that include gnu-efi-libs in their dependencies?

### CODE REVIEW

**Comment by dkwo** [comment]
does this require a firmware update to be tested?
if so, no firmware updates for my laptop for a while.
can it be tested with fwupd itself?

**Comment by dataCobra** [comment]
You can use `fwupdmgr reinstall` to try to trigger a reinstall event for your current firmware.

That is at least what one of the maintainers suggested to me.

**Comment by dkwo** [comment]
Sorry, I'm not interested in testing.
Also, can you please remove my name from maintainer field,
as I have not been using this for some time?

**Comment by dataCobra** [comment]
The package is now orphaned.

**Comment by dataCobra** [comment]
I close this PR in favor of a complete PR https://github.com/void-linux/void-packages/pull/52372.

**Pull request closed without merging**
