### PR TITLE
thunderbird: update to 68.11.0

### PR DESCRIPTION
**Pull request by mmnmnnmnmm**
Tested on x86_64-glibc, builds on aarch64-musl and armv7l-musl.

This includes pull #23789 by @ericonr.

### CODE REVIEW

**Comment by ericonr** [comment]
Nice, thanks!

**Comment by mmnmnnmnmm** [comment]
Superseded by 3d06a02b131422ebcf777d410dc4a37eb2e3295c and 2570038d76a063984b0a6b9018eeb77ad94d5fe7.

They don't include the wayland wrapper so @ericonr do you want to reopen #23789?

**Comment by mmnmnnmnmm** [comment]
Superseded by 3d06a02 and 2570038.

They don't include the wayland wrapper so @ericonr do you want to reopen #23789?

**Comment by mmnmnnmnmm** [comment]
Stupid Github won't let me close this pull request.

**Comment by mmnmnnmnmm** [comment]
For some completely unknown reason Github won't let me close this pull request.  If someone has permission to close this, please go ahead...

**Comment by ericonr** [comment]
Thanks for the warning, will go ahead and re-open.

**Pull request closed without merging**
