### PR TITLE
New package: cargo-outdated-0.7.1

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by jnbr** [comment]
why?

**Comment by jnbr** [comment]
ignore (deleted) previous comment

**Comment by jnbr** [comment]
it uses crate `libgit2-sys`, so `libgit2-devel` must be added to `makedepends` and `LIBGIT2_SYS_USE_PKG_CONFIG` must be exported

**Comment by Cogitri** [comment]
Hm, works for me without it

**Comment by jnbr** [comment]
Sure it works, it builds it's own libgit2 and links it statically.
In my opinion, we should avoid this because:
- rust projects waste a lot of time on the builders already
- static linking means we have to rebuild cargo-outdated if libgit2 has e.g. a security flaw, this doens't scale

**Pull request merged**
