### PR TITLE
Firefox 70.0.0

### PR DESCRIPTION
**Pull request by zdtcd**
Included 2 commits from #15686, since Firefox 70.0 requires nss 3.46.1

---
Built for:
- [x] x86_64-musl
- [x] x86-64
- [x] i686
- [x] armv7
- [x] aarch64-musl

Tested with:
- [x] x86_64
- [x] x86_64-musl

### CODE REVIEW

**Comment by jnbr** [comment]
Thank you.
Please add a header to the patch which describes why it is necessary.

I'll test on i686 and check if it builds on armv7.

**Comment by jnbr** [comment]
x86_64 and i686 work for me. armv7 built successful as well.

**Comment by zdtcd** [comment]
My computer memory couldn't stand parallel build. I'm restarting aarch64 build.

**Comment by jnbr** [comment]
forgot to check armv7l-musl. Working on a fix.

**Comment by zdtcd** [comment]
> forgot to check armv7l-musl. Working on a fix.

I'll look into it.

**Comment by jnbr** [comment]
The problem is with `build/moz.configure/rust.configure`. It sets the target to `armv7-unknown-gnueabi`.

**Pull request merged**
