### PR TITLE
New package: pinebookpro-base-0.1

### PR DESCRIPTION
**Pull request by renatoaguiar**

### CODE REVIEW

**Comment by xtraeme** [comment]
The musl build needs to be fixed in - uboot to merge this one. I'll merge this when it's ready.

**Comment by renatoaguiar** [comment]
> The musl build needs to be fixed in - uboot to merge this one. I'll merge this when it's ready.

It also needs to wait for pinebookpro-kernel. I'll see if I can fix musl build in the meantime.

**Comment by renatoaguiar** [comment]
Check should pass after pinebookpro-kernel (https://github.com/void-linux/void-packages/pull/19293) is merged.

**Comment by renatoaguiar** [comment]
All dependencies are merged, so this is now ready to go.

**Comment by xtraeme** [comment]
I really think we should have generic ARM kernels with all dts builtin, like NetBSD... but it's not too easy to test all supported platforms... mainly because I lost all !x86 machines a while ago.

So this is a great work by @renatoaguiar and others. Hope this device works as expected and make our users happy.

Cheers

**Pull request merged**
