### PR TITLE
move update-check out of xbps-src

### PR DESCRIPTION
**Pull request by sgn**
Continue discussion from #31546 

It's better to rewrite in a real programming language, however this is enough for now.

TODO: check only distfiles.

The `eval` step should be removed when we can remove all variable except `pkgname` and `version` from `distfiles`, and merge the first `distfiles` to the same line of `distfiles=`

@void-linux/pkg-committers 
@the-maldridge moving out of `xbps-src`, we can drop the weird `XBPS_ALLOW_CHROOT_BREAKOUT=yes` from `update-check` container.

### CODE REVIEW

**Comment by the-maldridge** [comment]
I had started a rewrite in Go, but our regexes require backtracking (`\K`) , which prevented this from being reasonable.  If we had a mechanical way to remove our need for backtracking, it would be fairly easy to pick that back up and make it work.

**Comment by Gottox** [comment]
Can you elaborate on the reason? 'It's better' is a bit vague for my taste.

**Comment by the-maldridge** [comment]
@Gottox a primary reason is that shell lacks high parallelism and its difficult to extend.  There's a lot more we could be doing with this data but because its in an awkward format its difficult to actually use.

**Comment by sgn** [comment]
The reason to move out of `xbps-src` is:

- update-check doesn't need xbps
- running inside xbps-src requires xbps
- running inside xbps-src requires either chrooting (which requires xbps) or XBPS_ALLOW_CHROOT_BREAKOUT
- rewrite in a real programming language could speed things up a bit

**Comment by Chocimier** [comment]
> check only distfiles

homepage and site are important too

> remove all variable except pkgname and version from distfiles

There are templates that use wrksrc, _distver being custom transformation of version and more.

> update-check doesn't need xbps 

It uses dewey version sort with `xbps-uhelper cmpver` and needs to use it more. Current [sort -Vu](https://github.com/void-linux/void-packages/blob/471c2d1dd4af758dcd5a450f498439dc25045e34/common/xbps-src/shutils/update_check.sh#L179) sorts beta releases as greater than final releases - so that xupdate updates templates that for some reasons are in `2beta1` version to `2beta2` rather than `2`.

> requires [...] XBPS_ALLOW_CHROOT_BREAKOUT

Is this problem?

> could speed things up a bit

Test was done on templates with `0.` prepended to version to force matches.
There are around 60 packages for which new versions are not detected after that change as for now, not counting R and ruby packages defining distfiles in build style.
Run time of void-updates -p 5 went down by 5min, from 2h 25min to 2h 20min. On same machine, `xbps-src show` for all packages takes around 10 min - limit of what can be expected to improve.
Roughly half of execution time was spent in void-updates' `get_date` - but this is not representative, as there are more found versions that usually.

My conclusion is that this is micro-optimization that doesn't touch real problem pointed by maldridge  - templates being bash programs depending on lot of xbps-src code that are complex to really understand, hard or slow to process for all usecases, like cycle detection.

**Pull request closed without merging**
