### PR TITLE
gscan2pdf: corrected a patch to make tesseract available

### PR DESCRIPTION
**Pull request by numerys**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-musl)

### CODE REVIEW

**Comment by classabbyamp** [comment]
gscan2pdf will also need a revision increment

**Comment by classabbyamp** [comment]
squash this into 1 commit and it should be good

**Review by Hoshpak — CHANGES_REQUESTED** [review]
Please squash the changes into one commit. Please also amend the commit message to state more clearly what patch is changed and why.

Optionally you could also mention the issue number in the commit comment (e.g. "closes #42932") to ensure that the corresponding issue is automatically closend when the PR is merged.

**Review by Hoshpak — CHANGES_REQUESTED** [review]
Please reformat the commit title according to the format lined out in [CONTRIBUTING.md](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md) :

for template modifications without a version change, use `<pkgname>: <reason>`

**Review by Hoshpak — APPROVED** [review]

**Pull request merged**
