### PR TITLE
New packages: ipsvd, socklog-ucspi

### LINKED ISSUE #41300: void-socklog: ucspi is configured to use tcpsvd which doesn't exist.
### Is this a new report?

Yes

### System Info

Void 6.0.13_1 x86_64 AuthenticAMD uptodate FF

### Package(s) Affected

void-socklog

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

_No response_

### Expected behaviour

`socklog-conf ucspi-tcp nobody log` creates a ucspi-tcp configuration for socklog, but the `/etc/sv/socklog-ucspi/run` script refers to `tcpsvd`:

```
exec tcpsvd -vllogserver -unobody 0 "$PORT" socklog ucspi TCPREMOTEIP
```
which doesn't exist (as far as I can tell) for Void. Using `tcpserver` from s6-networking or from ucspi-tcp might work.

I expected the default installation of socklog-ucspi to reference a utility that exists on my system (or that can be installed).

### Actual behaviour

```
bash-5.1# head /var/log/socklog-ucspi-tcp/main/current
@4000000063a9c4ee2b51dddc ./run: 4: exec: tcpsvd: not found
@4000000063a9c4ef2b67cb24 ./run: 4: exec: tcpsvd: not found
@4000000063a9c4f02b843494 ./run: 4: exec: tcpsvd: not found
```

### Steps to reproduce

1. `xbps-install socklog-void xtools` (if not present)
2. `socklog-conf ucspi-tcp nobody log`
3. `head /var/log/socklog-ucspi-tcp/main/current`
4. `xlocate tcpsvd`

### PR DESCRIPTION
**Pull request by kruceter**
cc: @leahneukirchen (socklog's maintainer)

Closes #41300.

#### Testing the changes
- I tested the changes in this PR: **briefly**

### ipsvd

The build method is not much different from socklog (the same author).

#### Testing the changes
- I tested the changes in this PR: **briefly**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

### CODE REVIEW

**Comment by leahneukirchen** [comment]
Packaging ipsvd is fine, I'd not change the depends for socklog as this is a mode that's rarely used.

**Comment by leahneukirchen** [comment]
You could make a socklog-remote or so package that depends on socklog and ipsvd and provides a service.

**Comment by sbromberger** [comment]
> Packaging ipsvd is fine, I'd not change the depends for socklog as this is a mode that's rarely used.

The problem is that the current installation of socklog is broken precisely because it assumes `tcpsvd` is available, and it's not. As I see it, the options are either
1. package `ipsvd` and make it a dependency,
2. change socklog dependency to include djb's `ucspi-tcp` package (might also need tcp6) and change the syntax in the `socklog-remote` run file, or
3. disable / remove `socklog-remote`

**Comment by kruceter** [comment]
> change socklog dependency to include djb's ucspi-tcp package (might also need tcp6) and change the syntax in the socklog-ucspi run file

`socklog-conf.c` and the manual page should be patched for this purpose.

I doubt this will be accepted here.

> disable / remove socklog-ucspi

I believe you assume removal of the feature. See above.

> modify the manpage to clarify that it won't work [...]

It would be nice to inform a user of tcpsvd coming with a separate package, but Void Linux is not the open based operating system with documentation stored in manual pages, meaning that void-specific documentation is handled in a different way (see void-docs).

Maybe it will be accepted at least there.

**Comment by leahneukirchen** [comment]
Void depends are only for essential dependencies, if *you* configure socklog to use tcpsvd, it's your problem to have the appropriate tools installed.

(My suggestion was to actually add a preconfigured setup to the socklog-ucspi package, however.)

**Comment by sbromberger** [comment]
> Void depends are only for essential dependencies, if you configure socklog to use tcpsvd, it's your problem to have the appropriate tools installed.

Interesting. I hadn't thought of it this way before. In this case perhaps it's better to not create a runfile that is broken by default? If the user has to go through the steps of installing tcpsvd, then s/he is probably adept enough to create an appropriate service.

**Comment by kruceter** [comment]
> add a preconfigured setup to the socklog-ucspi package

I had my doubts for this new metapackage, but it seems I completely misunderstood your suggestion.

**Pull request merged**
