### PR TITLE
bluebird-themes: fix template

### PR DESCRIPTION
**Pull request by motorto**
#### Testing the changes
- I tested the changes in this PR: nope

Doesn't build from source, since god knows when. Upstream seems dead. It's a theme

### CODE REVIEW

**Comment by classabbyamp** [comment]
> Doesn't build from source, since god knows when. Upstream seems dead. It's a theme

can you add this to the body of the commit?

**Comment by motorto** [comment]
like that ?

**Comment by classabbyamp** [comment]
was thinking
```
bluebird-themes: remove package.

Doesn't build from source, since god knows when. Upstream seems dead. It's a theme
```
this makes it so git(hub) displays the first line (title) but you can expand to see the rest (body)

**Comment by motorto** [comment]
done !

**Comment by motorto** [comment]
@Chocimier just to be sure can you confirm that this package doesn;t build from source ?

**Comment by Chocimier** [comment]
It builds with `librsvg` in place of `librsvg-utils` and works then. Apparently loader was moved between packages.

**Comment by motorto** [comment]
> It builds with `librsvg` in place of `librsvg-utils` and works then. Apparently loader was moved between packages.

Thanks fixed the template in this pr then

**Pull request merged**
