### PR TITLE
New package: fsverity-utils-1.3

### PR DESCRIPTION
**Pull request by ailiop-git**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Is this useful as a distro package, currently? I believe android makes use of verify, but iirc it's mostly for the read-only parts...

**Comment by ailiop-git** [comment]
> Is this useful as a distro package, currently? I believe android makes use of verify, but iirc it's mostly for the read-only parts...

The advantage of fsverity is that it can be used on a per-file basis, instead of requiring the entire block device to be read-only (as dm-verity does). So one can selectively enable and automatically enforce integrity on specific files (e.g. rotated/sealed log-files, binaries etc).

It is only currently supported on ext4 and f2fs, though. We also do not enable CONFIG_FS_VERITY=y and CONFIG_FS_VERITY_BUILTIN_SIGNATURES=y in the void kernels, but that shouldn't be a problem to enable, since this doesn't affect anything else (and verity needs to be explicitly enabled as an mkfs/tune2fs option in ext4).

**Comment by ericonr** [comment]
I think we should try to enable those options for void kernels, then. Can you open a PR?

**Comment by ailiop-git** [comment]
#28925

**Pull request closed without merging**
