### PR TITLE
yazi: update to 0.3.3.

### PR DESCRIPTION
**Pull request by Rooyca**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by tranzystorekk** [comment]
don't forget to ping the package maintainer

**Review by Bnyro — APPROVED** [review]
Thanks for pinging @tranzystorekk.

@Rooyca You created this PR just less than 8 hours after it got released - I would prefer if you give the maintainer of the package (me in this case) some time before "stealing" the update.

It's fine to update another one's package after a week or so if the maintainer didn't create a PR yet, but 8 hours is just not enough time for me. I usually update packages for me, test them 2 or 3 days long in my daily workflow, and create a PR afterwards, if everything seems to be okay. There's no chance I can do that when somebody creates a pull request 8 hours after the release...

**Comment by Bnyro** [comment]
Void Linux currently lacks a real policy for that unfortunately, nevertheless I can still remember some discussions about it from around a year ago.

**Comment by ahesford** [comment]
Superseded by maintainer submission

**Pull request closed without merging**
