### PR TITLE
Komikku: update to 0.21.1.

### PR DESCRIPTION
**Pull request by not-chicken**

### CODE REVIEW

**Comment by Chocimier** [comment]
```
komikku 
Traceback (most recent call last):
  File "/usr/bin/komikku", line 69, in <module>
    from komikku.application import Application
  File "/usr/lib/python3.8/site-packages/komikku/application.py", line 24, in <module>
    from komikku.add_dialog import AddDialog
  File "/usr/lib/python3.8/site-packages/komikku/add_dialog.py", line 17, in <module>
    from komikku.models import create_db_connection
  File "/usr/lib/python3.8/site-packages/komikku/models/__init__.py", line 5, in <module>
    from .database import backup_db
  File "/usr/lib/python3.8/site-packages/komikku/models/database.py", line 16, in <module>
    from komikku.servers import convert_image
  File "/usr/lib/python3.8/site-packages/komikku/servers/__init__.py", line 23, in <module>
    from komikku.utils import get_cache_dir
  File "/usr/lib/python3.8/site-packages/komikku/utils.py", line 297, in <module>
    class PlaintextKeyring(keyring.backend.KeyringBackend):
  File "/usr/lib/python3.8/site-packages/komikku/utils.py", line 303, in PlaintextKeyring
    folder = os.path.join(get_data_dir(), 'keyrings')
  File "/usr/lib/python3.8/site-packages/komikku/utils.py", line 69, in get_data_dir
    from komikku.servers import get_servers_list
ImportError: cannot import name 'get_servers_list' from partially initialized module 'komikku.servers' (most likely due to a circular import) (/usr/lib/python3.8/site-packages/komikku/servers/__init__.py)
```

**Comment by not-chicken** [comment]
Sorry, I couldn't reproduce it. I'll try reporting this traceback to upstream.

**Comment by fushinari** [comment]
> Sorry, I couldn't reproduce it. I'll try reporting this traceback to upstream.

There is no circular import like that in Komikku's code afaik. I'm not on Void, so I can't test either. I might just turn out to be unhelpful.

@Chocimier can you try building again after clearing cache? I tried to reproduce this, but I couldn't.

**Comment by not-chicken** [comment]
Ah, it was a one time error on the very first launch. Upstream tagged a new release with fix.

**Comment by fushinari** [comment]
I have no idea why but it didn't affect the AUR package either.

**Comment by not-chicken** [comment]
oof. Now I'm having some other issues with new release. Marking nomerge till I get some time to look into it.

**Comment by not-chicken** [comment]
Good to go.

**Comment by ericonr** [comment]
Downloaded and read stuff with it.

**Pull request merged**
