### PR TITLE
freeplane: update to 1.8.6.

### PR DESCRIPTION
**Pull request by fosslinux**
Fixes gradle build

### CODE REVIEW

**Comment by abenson** [comment]
i686 didn't for me either, but it was a different error...

**Comment by fosslinux** [comment]
I only built for x86_64 and x86_64-musl since it is noarch. Hm...

**Comment by fosslinux** [comment]
@abenson did you get

```
> Task :freeplane_mac:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':freeplane_mac:compileJava'.
> Could not target platform: 'Java SE 11' using tool chain: 'JDK 8 (1.8)'.
```

**Comment by fosslinux** [comment]
Huh, it should be... https://github.com/freeplane/freeplane/blob/f57dd25341d3955de3ab9762efe57f07a297211a/freeplane_debughelper/build.gradle#L10 I'll just patch it out and submit a bug report

**Comment by fosslinux** [comment]
Ok, builds on i686 now!

**Pull request closed without merging**
