### PR TITLE
Update granite

### PR DESCRIPTION
**Pull request by TeddyDD**
let's see if ci will timeout, hopefully not

#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-glibc (cross)

### CODE REVIEW

**Comment by TeddyDD** [comment]
Build passed for 4603bb7 (also tested locally),  3acb11d  just fixes lint errors.

**Comment by Jlll1** [comment]
Hey, are you still working on this? I could fix up the build issues if that's alright with you.

**Comment by TeddyDD** [comment]
Go ahead, my PC is currently broken, and I can't work on my PRs until it returns from service.

**Comment by paper42** [comment]
done in #36085

**Pull request closed without merging**
