### PR TITLE
[do not merge][help needed]Samba4

### PR DESCRIPTION
**Pull request by SirFerdek**
I got stuck and I need help to finish this.

- [ ] sssd needs a version bump, or at least a revbump, due to changed deps SONAME versions
- [ ] sssd's libwbclient conflicts with samba's libwbclient - they both provide the same library
- [ ] I don't know how to properly package private libraries of samba which reside in sub-directory of /usr/lib (namely /usr/lib/samba). They are not being picked-up by pre-pkg hook that detects provided shlibs (`06-shlib-provides.sh`). Also I don't quite like the idea of putting the private libraries with `-samba4.so` suffixes into `common/shlibs`. Let me know how to approach this.
- [ ] When this is sorted out, shlibs needs to be revieved and everything samba and sssd related fixed
- [ ] The samba package needs to be properly split into smaller subpackages
- [ ] I don't know how to properly package python extensions with names like `libpytalloc-util.cpython-36m-x86-64-linux-gnu.so.2` which reside in libdir. Also, I've noticed that architecture part does not change if cross-compiling. This might be some kind of a bug.
- [ ] Fixing python dependencies is required to build Active Directory Domain Controller functionality

I am sure I missed some more issues, but hey, at least, with some additional care, it compiles and cross-compiles! ;)

### CODE REVIEW

**Comment by Piraty** [comment]
you may want to look into using qemu to execute the tests, instead of providing an answer file

**Comment by SirFerdek** [comment]
Agreed, however that requires slightly different patchset to WAF from what I recall. I didn't wanted to waste time when the package has other fundamental flaws that I don't know how to work around.

**Comment by Mek101** [comment]
Any news?

**Comment by SirFerdek** [comment]
I was not offered any help.

**Comment by ahesford** [comment]
Superseded by #27166

**Pull request closed without merging**
