### PR TITLE
python-Markdown: add python_version

### PR DESCRIPTION
**Pull request by fosslinux**

### CODE REVIEW

**Comment by Chocimier** [comment]
should be build_style=python2-module and revbumped instead

04-create-xbps-metadata-scripts.sh is buggy here, thanks for catching

**Comment by fosslinux** [comment]
@Chocimier  thanks :)

**Comment by fosslinux** [comment]
@Chocimier Is xlint correct in saying `pycompile_module` should be removed?

**Comment by Chocimier** [comment]
Yes, here there is regular python module, so `pycompile_module` don't need to be set.

Executable need to be moved with `mv ${DESTDIR}/usr/bin/markdown_py ${DESTDIR}/usr/bin/markdown_py2` to fix alternative, in python3-Markdown too. python3-setuptools is not needed here. Will you update?

**Comment by fosslinux** [comment]
Sure. Also, does `python-setuptools` really need to be in depends?

**Comment by Chocimier** [comment]
Yes, executable uses module from python-setuptools.

Please revbump python3-Markdown too.

**Comment by fosslinux** [comment]
> Please revbump python3-Markdown too.

Done

**Comment by Chocimier** [comment]
Thank you.

**Pull request merged**
