### PR TITLE
fix playonlinux

### LINKED ISSUE #53628: python3-pyasyncore
### Is this a new report?

Yes

### System Info

Void Linux glibc

### Package(s) Affected

 python3-pyasyncore 

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

_No response_

### Expected behaviour

Playonlinux.

### Actual behaviour

Hello Void. After last python3 update playonlinux not work. Always is problem with python3-pyasyncore. Playonlinux don't start and run.

### Steps to reproduce

Crash.

### PR DESCRIPTION
**Pull request by toadwastoast**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc
- I built this PR locally for these architectures:
  - i686 (cross)

Probably resolves #53628

### CODE REVIEW

**Review by classabbyamp — COMMENTED** [review]
the patch is getting installed by the `cp -r` on line 22: https://github.com/void-linux/void-packages/actions/runs/12462653837/job/34783873791?pr=53646#step:9:13

**Comment by toadwastoast** [comment]
seems like it's an issue with `pycompile_dirs`? package seems to work fine if I remove that line.

**Comment by classabbyamp** [comment]
no, that's just how xbps-src patches things. it copies the patch into wrksrc and applies it. `cp -r *` grabs the patch because it's just sitting there

**Comment by toadwastoast** [comment]
Yeah sorry, I misunderstood you earlier. completely missed the `cp -r *` line somehow.

**Pull request merged**
