### PR TITLE
gawk: fix tests

### PR DESCRIPTION
**Pull request by paper42**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Is this necessary on glibc and musl?

**Comment by paper42** [comment]
tests that this PR fixes are skipped on musl:
```
======== Done with machine-specific tests ========
/bin/sh: line 5: locale: command not found
%%%%%%%%%% Inadequate locale support: skipping charset tests.
%%%%%%%%%% At least en_US.UTF-8, fr_FR.UTF-8, ru_RU.UTF-8 and ja_JP.UTF-8 are needed.
```

**Comment by ericonr** [comment]
If we merge #26142 or similar we can look into improving this. Can you leave a comment in the commit message or template about this?

**Comment by sgn** [comment]
Hm, on musl, with:
```
cat >some-bin/locale <<\EOF
#!/bin/sh
printf '%s.UTF-8\n' C en_US fr_FR ru_RU
EOF
```

a test failed because musl doesn't consider `U+1680` as space character.

**Pull request merged**
