### PR TITLE
New package: podman-tui-0.9.1

### PR DESCRIPTION
**Pull request by xeji**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc

### CODE REVIEW

**Comment by xeji** [comment]
I don't understand the arm build errors - seems to compile but "failed to strip". How can I fix this?

**Comment by classabbyamp** [comment]
it's building it for the host arch instead of the target arch. I would suggest not using the makefile and instead using go build style, as that will cross-compile correctly

**Comment by xeji** [comment]
I see, thanks. Upstream build instructions use makefile but I'll try go build.

**Comment by xeji** [comment]
Switched to build_style=go, hope it will cross-compile better now.

**Pull request merged**
