### PR TITLE
[draft] New package: swtpm-0.5.2

### LINKED ISSUE #28955: Package request: swtpm (sw tpm emulator for qemu/libvirt vms)
[qemu](https://qemu.readthedocs.io/en/latest/specs/tpm.html)/[libvirt](https://libvirt.org/formatdomain.html#tpm-device) can emulate TPM device via [`swtmp`](https://github.com/stefanberger/swtpm), this package would extend possibility to test TPM in virtualization environments.

See OpenSUSE article [Software TPM Emulator For QEMU](https://en.opensuse.org/Software_TPM_Emulator_For_QEMU) about such emulation for more info.

### PR DESCRIPTION
**Pull request by jirib**
Fixes #28955.

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by jirib** [comment]
Tests do not fail locally, is it possible how get `tests/*.log` files?

**Comment by sgn** [comment]
Please:
- one commit per package; and
- `build_style=gnu-configure`

**Comment by jirib** [comment]
> Please:
> 
> * one commit per package; and
> * `build_style=gnu-configure`

Done. Thx.

**Comment by jirib** [comment]
> Tests do not fail locally, is it possible how get `tests/*.log` files?

IIUC there's no 'tss' user in build env. But even if we would do `sed -i 's/tss/root/' ${wrksrc}/tests/test_config`, some tests would fail because they spawn `tcsd` and `tcsd` internally [checks](https://github.com/srajiv/trousers/blob/1722374cb9dbab6053a71d9422efc3c50e912197/src/tcsd/tcsd_conf.c#L767) the owner of `tcsd` config file is `tss` user. Thus, `make_check=extended`.

**Comment by jirib** [comment]
I'm not going to continue with this. If anybody is interested in it, feel free to reuse this PR.

**Pull request closed without merging**
