### PR TITLE
[WIP] Qgis package

### PR DESCRIPTION
**Pull request by sgn**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

Close #27041

### CODE REVIEW

**Comment by nezos** [comment]
Hi, has this been stalled out?

**Comment by sgn** [comment]
@Nyx70 sorry, I couldn't find time to continue. Would you mind to continue?

**Comment by sgn** [comment]
`git fetch https://github.com/sgn/void-packages.git qgis-package`

**Comment by Nyx70** [comment]
Ok, i’ll continue later.

QGIS needs SIP 5, which is no more included in void-linux.
SIP 4 also make problems (python 2.x code mix ?): "sip: Py_ssize_t is undefined"
I‘ll wait until SIP 6 is supported in QGIS and reopen a new „pull request“.
Until then, QGIS for void-linux is available on  https://void-linux.nýx.ch/ (https://nýx.ch/prj/qgis/)

👁 https://github.com/qgis/QGIS/issues/38911

**Comment by nezos** [comment]
@Nyx70 could you please upgrade grass as its GUI is not currently working? grass does not rely on SIP. Things will be easier then for QGIS to be added.

[Package 'grass' : GRASS GUI not working #29209](https://github.com/void-linux/void-packages/issues/29209)

**Comment by Nyx70** [comment]
@nezos https://github.com/void-linux/void-packages/pull/30452

**Comment by Nyx70** [comment]
https://github.com/void-linux/void-packages/pull/30452

I get out

**Pull request closed without merging**
