### PR TITLE
gpart: fix crash on non-disk device

### PR DESCRIPTION
**Pull request by ndowens**
Last release was 4-or-more years ago
Patches cherry-picked from https://github.com/baruch/gpart/compare/0.3...master

### CODE REVIEW

**Comment by Duncaen** [comment]
I don't think we should merge ~3000 line patches into this repository.
I think fetching patches through distfiles or using debian sources would be a better alternative.

**Comment by ndowens** [comment]
> I don't think we should merge ~3000 line patches into this repository.
> I think fetching patches through distfiles or using debian sources would be a better alternative.

Debian doesn’t have the patches. I could find somewhere free to host the patches

**Comment by Chocimier** [comment]
It is already here: [https://github.com/baruch/gpart/compare/0.3...master.patch](https://github.com/baruch/gpart/compare/0.3...master.patch)

However, I do not support to include that. Void has policy of packaging releases, not release+patches set from patches collector who not decided to make new release. We could ask for one, but that repo seems to be unmaintained for years too.

**Comment by ndowens** [comment]
> I don't think we should merge ~3000 line patches into this repository.
> I think fetching patches through distfiles or using debian sources would be a better alternative.

I created a repo on github for patches, esp big ones. So I've included a "release" of them in distfiles

**Comment by Cogitri** [comment]
While I do think it's correct to include patches for CVEs and for crashes I strongly oppose including "speed fixes", especially if upstream is dead. Those "speed fixes" could very much contain new bugs/issues which IMO Void shouldn't have to deal with unless it were to take that project over.

**Comment by ndowens** [comment]
> While I do think it's correct to include patches for CVEs and for crashes I strongly oppose including "speed fixes", especially if upstream is dead. Those "speed fixes" could very much contain new bugs/issues which IMO Void shouldn't have to deal with unless it were to take that project over.

Ok, I can remove the speed patch

**Pull request merged**
