### PR TITLE
spectrwm: update to 3.4.0.

### PR DESCRIPTION
**Pull request by ailiop-git**

### CODE REVIEW

**Comment by Piraty** [comment]
x86_64-musl fails on travis

**Comment by ericonr** [comment]
Adding `musl-legacy-compat` to the template should be enough. But you should probably also complain to upstream, they shouldn't have started depending on those headers :p

**Comment by Piraty** [comment]
@ailiop-git  ping

**Comment by ailiop-git** [comment]
updated to 3.4.1, fixed musl issues.

**Pull request merged**
