### PR TITLE
New package: pipr-0.0.14

### PR DESCRIPTION
**Pull request by willeccles**
Pipr is a utility for interactively writing and previewing shell pipelines. I will be maintaining the package.

### CODE REVIEW

**Comment by sgn** [comment]
On 2020-09-08 13:40:46-0700, Will Eccles <notifications@github.com> wrote:
> Pipr is a utility for interactively writing and previewing shell pipelines. I will be maintaining the package.

Please learn the tool (Git and GitHub) instead of closing and
re-opening.

**Comment by willeccles** [comment]
> 
> On 2020-09-08 13:40:46-0700, Will Eccles ***@***.***> wrote: Pipr is a utility for interactively writing and previewing shell pipelines. I will be maintaining the package.
> Please learn the tool (Git and GitHub) instead of closing and re-opening.

Git was very broken. The extra commit that it added to my branch (despite not being in the branch before) was unavailable for rebasing. The rebase command refused to show the commit for me to delete it and I was unable to change anything about the commit. It was far easier to re-fork the repository than spend hours reading up on ancient git questions on SO.

**Comment by sgn** [comment]
On 2020-09-08 16:27:24-0700, Will Eccles <notifications@github.com> wrote:
> > 
> > On 2020-09-08 13:40:46-0700, Will Eccles ***@***.***> wrote: Pipr
> > is a utility for interactively writing and previewing shell
> > pipelines. I will be maintaining the package.
> > Please learn the tool (Git and GitHub) instead of closing and re-opening.
> 
> Git was very broken. The extra commit that it added to my branch
> (despite not being in the branch before) was unavailable for
> rebasing.

May I guess? It's a merge commit ;) or the commit available upstream.
Then Git is definitely not broken.
Why don't you try to finish the rebasing and check the result first ;)

> The rebase command refused to show the commit for me to
> delete it and I was unable to change anything about the commit. It
> was far easier to re-fork the repository than spend hours reading up
> on ancient git questions on SO.

**Comment by willeccles** [comment]
> 
> On 2020-09-08 16:27:24-0700, Will Eccles ***@***.***> wrote: > > On 2020-09-08 13:40:46-0700, Will Eccles ***@***.***> wrote: Pipr > is a utility for interactively writing and previewing shell > pipelines. I will be maintaining the package. > Please learn the tool (Git and GitHub) instead of closing and re-opening. Git was very broken. The extra commit that it added to my branch (despite not being in the branch before) was unavailable for rebasing.
> May I guess? It's a merge commit ;) or the commit available upstream. Then Git is definitely not broken. Why don't you try to finish the rebasing and check the result first ;)
> […](#)
> The rebase command refused to show the commit for me to delete it and I was unable to change anything about the commit. It was far easier to re-fork the repository than spend hours reading up on ancient git questions on SO.

Can't try now, that is gone forever.

**Pull request closed without merging**
