### PR TITLE
New package: jellyfin-media-player-1.9.1

### PR DESCRIPTION
**Pull request by inalone**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**|**NO**

#### Local build testing
- I built this PR locally for my native architecture, x86_64 glibc

This PR is largely a revival of https://github.com/void-linux/void-packages/pull/33199 .

### CODE REVIEW

**Comment by inalone** [comment]
> @inalone
> 
> > This PR is largely a revival of #33199 .
> 
> why did you leave out the web interface? it's present in the old template you mentioned. the package is incomplete without it.
> 
> the latest version is here --> https://repo.jellyfin.org/releases/server/portable/stable/web/

I will add it back to the template when I get some free time to do so - I removed it at Jellyfin Media Player no longer relies on it like it used to, and due to the moving of repository.

**Comment by chrysos349** [comment]
> Jellyfin Media Player no longer relies on it

nope.

the official instructions include the step of running the script which downloads the web interface.
see here --> https://github.com/jellyfin/jellyfin-media-player#building-at-a-glance-linux

official deb packages also include the web interface.

**Comment by inalone** [comment]
I agree now that it should be included - the application has been specifically made recently to not rely on it for usage, but I agree that for the sake of packaging for a distribution we should include it. I am now working on this.

**Comment by inalone** [comment]
Web interface now added.

**Comment by chrysos349** [comment]
> Web interface now added.

you added the link, but didn't add it properly to the package. it's absent in the compiled package.

Other suggestions:
`-DQTROOT='${XBPS_CROSS_BASE}/usr'` - not needed
`qt5-devel` is not needed because it will be pulled by other qt5-* deps.

```
https://repo.jellyfin.org/releases/server/portable/stable/web/jellyfin-web_${_web_version}_portable.tar.gz
```
this is the dynamic link for the web interface. next time it updates. the file won't be found.
here is the proper link

```
https://repo.jellyfin.org/releases/server/portable/versions/stable/web/${_ver}/jellyfin-web_${_ver}_portable.tar.gz
```

Below is a refactored template and a patch, which disables update checking, because it doesn't make any sens for our use. It works, and crossbuilds.

TEMPLATE
```
# Template file for 'jellyfin-media-player'
pkgname=jellyfin-media-player
version=1.9.1
_ver=10.8.11
revision=1
build_style=cmake
configure_args="-DCMAKE_BUILD_TYPE=Release -DLINUX_X11POWER=ON
 -DOpenGL_GL_PREFERENCE=GLVND"
hostmakedepends="pkg-config python3 qt5-host-tools qt5-qmake"
makedepends="SDL2-devel libcec-devel mpv-devel qt5-declarative-devel
 qt5-location-devel qt5-webchannel-devel qt5-webengine-devel qt5-x11extras-devel
 zlib-devel"
depends="qt5-quickcontrols"
short_desc="Desktop media client for Jellyfin"
maintainer="inalone <me@inal.one>"
license="GPL-2.0-only"
homepage="https://github.com/jellyfin/jellyfin-media-player"
distfiles="https://github.com/jellyfin/jellyfin-media-player/archive/v${version}.tar.gz
 https://repo.jellyfin.org/releases/server/portable/versions/stable/web/${_ver}/jellyfin-web_${_ver}_portable.tar.gz"
checksum="8d119bb78e897ace3041cf332114a79c51be4d8e0cc8c68f5745fd588c2b9bde
 e78dd5c14e7929193478a350a79d5e9d52a27b0405b6080a7e556f608b89d764"

post_extract() {
	mv ${pkgname}-${version}/* .
	mkdir -p build/dist
	mv jellyfin-web_*/* build/dist
}
```

PATCH

```
diff --git a/resources/settings/settings_description.json b/resources/settings/settings_description.json
index 20fff81..9979de5 100644
--- a/resources/settings/settings_description.json
+++ b/resources/settings/settings_description.json
@@ -118,7 +118,7 @@
       },
       {
         "value": "checkForUpdates",
-        "default": true
+        "default": false
       },
       {
         "value": "enableInputRepeat",
```

**Comment by inalone** [comment]
Have now used the refactored template and added the patch. Thank you for putting so much effort and time into making those :)

**Comment by chrysos349** [comment]
bump

**Pull request closed without merging**
