### PR TITLE
New package: vpm-1.2a

### PR DESCRIPTION
**Pull request by netzverweigerer**
New srcpkgs template for VPM, an XBPS package management helper
Requested via: https://github.com/netzverweigerer/vpm/issues/4
Project URL: https://github.com/netzverweigerer/vpm

### CODE REVIEW

**Comment by Anachron** [comment]
there is xlint from the xtool package that you can use to get your pkg template checked for common errors

```
srcpkgs/vpm/template:6: short_desc should not start with an article
srcpkgs/vpm/template:7: maintainer needs email address
srcpkgs/vpm/template:14: indent with tabs
srcpkgs/vpm/template:17: Last line is empty
```

**Comment by shabahengam** [comment]
I think this issue #17273 should be closed.

**Comment by netzverweigerer** [comment]
> I think this issue #17273 should be closed.

Thanks, closing.

**Comment by netzverweigerer** [comment]
Okay I'm confused, should I leave this open until this successfully got merged/rejected or is this safe to close already?

**Comment by netzverweigerer** [comment]
Re-opened for now as I'm guessing closing this right now makes no sense.

**Comment by shabahengam** [comment]
@netzverweigerer  This PR should stay open until get merged but that issue (#17273) can get closed because it's just a request to make a PR(and you did that).my english is not very good but I hope you understand what i mean.sorry to make you confused.

**Comment by xtraeme** [comment]
could you please rebase?

**Comment by xtraeme** [comment]
no manpage? ok

**Pull request merged**
