### PR TITLE
Komikku: update dependencies

### PR DESCRIPTION
**Pull request by not-chicken**

### CODE REVIEW

**Comment by sgn** [comment]
Sorry, why does `Komikku` needs `python3-keyring`? I run it just fine.

**Comment by not-chicken** [comment]
> Sorry, why does `Komikku` needs `python3-keyring`? I run it just fine.

Doesn't work without it for me :(
```[~]$ komikku
Traceback (most recent call last):
  File "/usr/bin/komikku", line 69, in <module>
    from komikku.application import Application
  File "/usr/lib/python3.8/site-packages/komikku/application.py", line 24, in <module>
    from komikku.add_dialog import AddDialog
  File "/usr/lib/python3.8/site-packages/komikku/add_dialog.py", line 17, in <module>
    from komikku.models import create_db_connection
  File "/usr/lib/python3.8/site-packages/komikku/models/__init__.py", line 5, in <module>
    from .database import backup_db
  File "/usr/lib/python3.8/site-packages/komikku/models/database.py", line 15, in <module>
    from komikku.servers import convert_webp_buffer
  File "/usr/lib/python3.8/site-packages/komikku/servers/__init__.py", line 23, in <module>
    from komikku.utils import get_cache_dir
  File "/usr/lib/python3.8/site-packages/komikku/utils.py", line 12, in <module>
    import keyring
ModuleNotFoundError: No module named 'keyring'
```
Thanks for the update btw, I didn't notice new libhandy coming in.

**Comment by sgn** [comment]
I guess you're reading from some servers that requires logging in.
I tried with mangadex. So, `python3-keyring` is an optional dependencies.

**Comment by not-chicken** [comment]
Ah, crunchyroll :3.
 I'd still vote for adding it tho, as [upstream](https://gitlab.com/valos/Komikku/-/blob/master/README.md) lists it as a dependency.

**Comment by sgn** [comment]
On 2020-08-25 07:14:59-0700, Lorem <notifications@github.com> wrote:
> Ah, crunchyroll :3.
>  I'd still vote for adding it tho, as
>  [upstream](https://gitlab.com/valos/Komikku/-/blob/master/README.md)
>  lists it as a dependency.

Fair enough, but I'll it to other people to make the call.

-- 
Danh

**Comment by ahesford** [comment]
I don't use Komikku, but I'll note that the `komikku.servers` module does an unguarded `import keyring` and there are a lot of `komikku.servers` imports, so it looks like this is would be a minefield without `python3-keyring`. Also, the upstream flatpak pulls in `python3-keyring`. This seems to be the right call.

**Pull request merged**
