### PR TITLE
Drop unnecessary python2 requirement

### PR DESCRIPTION
**Pull request by sgn**
- python-docutils is mostly used as executable, ~it could be safely removed~, sphinx, aws-cli and botocore depends on it
- mpv can be bootstrap with python3, now
- pelican is an executable, can be used with python3 -> moved to #16653 
- anything that uses `python-*`as hostdepends will be change to `python3-\1`

### CODE REVIEW

**Comment by xtraeme** [comment]
ready? looks ok to me

**Comment by sgn** [comment]
On 2019-11-17 03:50:56-0800, Juan RP <notifications@github.com> wrote:
> ready? looks ok to me

This PR can be merged as-is,
However, I would like to include more changes.

-- 
Danh

**Comment by sgn** [comment]
Looks good now.
I intended to dig into `pygtk`, but it would be a large update.

I'm tempted to drop `python-pex` entirely, replace both `python-pex` and `python3-pex` with a single package `pex` (for python3) only.

**Comment by sgn** [comment]
Apparently, CI is failed because of ghc

**Comment by sgn** [comment]
DO NOT MERGE
python3-docutils is broken badly.

**Pull request merged**
