### PR TITLE
Compile terminfo description when building

### LINKED ISSUE #34392: alacritty-terminfo fails script, because ncurses is not installed
In an empty docker container, I install `bash` and `alacritty-terminfo`, but the latter seems to fail part of the install stage, suggesting dependencies are not correctly declared for this subpackage.

```
# xbps-install alacritty-terminfo

Name               Action    Version           New version            Download size
alacritty-terminfo install   -                 0.9.0_1                3281B

Size to download:              3793B
Size required on disk:         4930B
Space available on disk:       194GB

Do you want to continue? [Y/n]

[*] Downloading packages
alacritty-terminfo-0.9.0_1.x86_64.xbps.sig: 512B [avg rate: 18MB/s]
alacritty-terminfo-0.9.0_1.x86_64.xbps: 3281B [avg rate: 112MB/s]
alacritty-terminfo-0.9.0_1: verifying RSA signature...

[*] Collecting package files
alacritty-terminfo-0.9.0_1: collecting files...

[*] Unpacking packages
alacritty-terminfo-0.9.0_1: unpacking ...

[*] Configuring unpacked packages
alacritty-terminfo-0.9.0_1: configuring ...
/tmp/.xbps-script-DuhzIC: 34: tic: not found
alacritty-terminfo-0.9.0_1: installed successfully.

1 downloaded, 1 installed, 0 updated, 1 configured, 0 removed.
```

### System

voidlinux/voidlinux docker image c26f06f5f5c5

### Expected behavior

Installation and scripts succeed, pulling in `ncurses` as a dependency.

### Actual behavior

Installation succeeds, script fails, ncurses needs to be installed afterwards and then alacritty-terminfo force-reinstalled.

### Steps to reproduce the behavior

1. `docker run -ti --rm voidlinux/voidlinux sh`
2. `xbps-install bash alacritty-terminfo`

### PR DESCRIPTION
**Pull request by meator**
Some `*-terminfo` packages do not actually provide compiled terminal descriptions, but only the source file. They then have to compile it with `tic` in `INSTALL` and then remove in in `REMOVE`. This approach is more complicated, adds `ncurses` (the provider of `tic`) as a runtime dependency of these packages and it has to explicitly specify completions to remove from `/usr/share/terminfo` (I've already had to add missing ones to `st-terminfo` in #33116 because some were missing).

As far as I know this approach doesn't have any advantages over just compiling the terminfo files and then shipping them in the package. If compiling these files "locally" has some purpose than please comment here and explain.

The presence of terminfo files that haven't been compiled in `/usr/share/terminfo` can also confuse some programs. For example when I install all packages which this PR modifies and then run `toe > /dev/null`, it shows:
```
toe: couldn't open terminfo file xst.terminfo.
toe: couldn't open terminfo file st.terminfo.
toe: couldn't open terminfo file rxvt-unicode.terminfo.
toe: couldn't open terminfo file mtm.ti.
toe: couldn't open terminfo file dvtm.info.
toe: couldn't open terminfo file alacritty.info.
```

I've also tried to simplify the templates I've been working with and I've adopted `st` because I'm an active user of it. And does `st` really depend on `ncurses`? I didn't want to mess with this but it could be possible that this dependency was added because of terminfo generation before `st` and `st-terminfo` were separate packages.

Ping @thypon (maintainer of `alacritty`)
Ping @travankor (maintainer of `mtm`)
Ping @leahneukirchen (maintainer of `rxvt-unicode`)
Ping @ndowens (maintainer of `xst`)
Ping @erwin

#### Testing the changes
- I tested the changes in this PR: **briefly**

closes #34392

### CODE REVIEW

**Comment by meator** [comment]
One way to solve the conflicts would be to `rm` conflicting files from `ncurses-term` and add the relevant `-terminfo` packages as dependencies of `ncurses-term`. What do you think?

**Comment by classabbyamp** [comment]
I think that has been done previously for foot https://github.com/void-linux/void-packages/pull/36884#issuecomment-1131836929

**Comment by meator** [comment]
> I think that has been done previously for foot [#36884 (comment)](https://github.com/void-linux/void-packages/pull/36884#issuecomment-1131836929)

This is interesting. But now `ncurses-terminfo` doesn't contain terminfo descriptions for `foot`. I think adding `foot-terminfo` as a dependency of `ncurses-term` would be better. When I install `ncurses-term`, I expect to get all terminfo files, not only ones that do not have its own package.

**Comment by paper42** [comment]
> > I think that has been done previously for foot [#36884 (comment)](https://github.com/void-linux/void-packages/pull/36884#issuecomment-1131836929)
> 
> This is interesting. But now `ncurses-terminfo` doesn't contain terminfo descriptions for `foot`. I think adding `foot-terminfo` as a dependency of `ncurses-term` would be better. When I install `ncurses-term`, I expect to get all terminfo files, not only ones that do not have its own package.

We can't do that. ncurses is a very core package and shouldn't have any dependencies. Currently it doesn't, so building it is quick even with `-N`. What you are proposing would make the build take hours and most likely introduce a lot of build cycles, for example `ncurses (ncurses-term) -> foot (foot-terminfo) -> ncurses (ncurses-devel)`

**Comment by meator** [comment]
You are right. It would only create problems. Currently using the same approach as `foot-terminfo`.

**Comment by sgn** [comment]
I think it's better to remove those conflicts in `post_install` instead of patching.
Anyway, I support compile terminfo.

**Comment by classabbyamp** [comment]
what's the status of this?

**Comment by meator** [comment]
This should be still ready to merge. I won't fix the lint error because I know nothing about rust and the lint error is unrelated to the changes I'm proposing.

And while I'm here, I might as well fix the indentation of one comment I made. I don't know if this is a feature but `xlint` doesn't check that comments are indented with tabs instead of spaces.

**Comment by classabbyamp** [comment]
the lint can be fixed by making it `--package autocfg:1.0.1`

```
=> alacritty-0.10.1_2: running post_patch ...
    Updating crates.io index
    Updating autocfg v1.0.1 -> v1.1.0
```

**Comment by classabbyamp** [comment]
and there's a typo in the last commit, `ncurses` not `nurses`

**Comment by classabbyamp** [comment]
hm i see ncurses still has a foot+base terminfo, is that fine?

**Comment by meator** [comment]
It isn't. The `rm` should be equivalent to the patch. Thanks for pointing that out!

**Pull request merged**
