### PR TITLE
catch2: update to 2.13.3.

### PR DESCRIPTION
**Pull request by ndowens**

### CODE REVIEW

**Comment by ndowens** [comment]
Unsure why test fails on x86_64-musl

**Comment by Johnnynator** [comment]
They fail because `errno` on Musl and Glibc expand differently by one space.
```
xml.sw:
--- xml.sw.approved.txt

+++ xml.sw.unapproved.txt

-          errno == 1
+          (*__errno_location()) == 1
  
****************************
  Results differed
```

Can you add this patch and remove your `|| msg_warn`
```patch
--- scripts/approvalTests.py	2019-12-28 21:24:04.000000000 +0100
+++ -	2020-12-31 16:19:56.118506507 +0100
@@ -44,7 +44,7 @@
 
 # errno macro expands into various names depending on platform, so we need to fix them up as well
 errnoParser = re.compile(r'''
-    \(\*__errno_location\ \(\)\)
+    \(\*__errno_location\s*\(\)\)
     |
     \(\*__error\(\)\)
     |

```

**Comment by ndowens** [comment]
> They fail because `errno` on Musl and Glibc expand differently by one space.
> 
> ```
> xml.sw:
> --- xml.sw.approved.txt
> 
> +++ xml.sw.unapproved.txt
> 
> -          errno == 1
> +          (*__errno_location()) == 1
>   
> ****************************
>   Results differed
> ```
> 
> Can you add this patch and remove your `|| msg_warn`
> 
> ```diff
> --- scripts/approvalTests.py	2019-12-28 21:24:04.000000000 +0100
> +++ -	2020-12-31 16:19:56.118506507 +0100
> @@ -44,7 +44,7 @@
>  
>  # errno macro expands into various names depending on platform, so we need to fix them up as well
>  errnoParser = re.compile(r'''
> -    \(\*__errno_location\ \(\)\)
> +    \(\*__errno_location\s*\(\)\)
>      |
>      \(\*__error\(\)\)
>      |
> ```
> 
> [catchorg/Catch2#2143](https://github.com/catchorg/Catch2/pull/2143)

Done

**Comment by ericonr** [comment]
Goddamnit .4 was out https://github.com/catchorg/Catch2/releases

**Comment by ndowens** [comment]
> Goddamnit .4 was out https://github.com/catchorg/Catch2/releases

I'll try to remember to update later on if someone dont beat me. Been working on some nocross ones

**Pull request merged**
