### PR TITLE
Add Adam Gausmann to mailmap and update maintainer emails

### PR DESCRIPTION
**Pull request by agausmann**

### CODE REVIEW

**Comment by mhmdanas** [comment]
I don't belive revision bumps are needed for a change like this.

**Comment by agausmann** [comment]
Oh, you're right. Should have checked more commits.
There was a revbump in 7d97b3819c218e1c7bbef3bb4eb1422d200719da but a changelog was also added

**Comment by mhmdanas** [comment]
I think that revision bump is actually unnecessary too.

**Comment by Duncaen** [comment]
Those fields end up in the binary package, but generally we don't want to revbump packages just to change some metadata unless there is a good reason.

**Comment by mhmdanas** [comment]
@Duncaen good to know.

**Pull request merged**
