### PR TITLE
Manual.md: document preserve variable

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by newbluemoon** [comment]
It might not be clear at first which files are preserved: is `preserved` a list of files that are preserved or are all files of the package preserved if `preserved` is just set (to any value)? Perhaps s/files/all files of the package/ is a bit more precise? Or maybe just adding an example like “e.g. `preserve=yes`” should suffice, too. :)

**Comment by maxice8** [comment]
@Vaelatern updated to be like yours with a tiny bit different wording, still not satisfied with just telling the users "no, dont use it" IMO a reason/example should be given

**Comment by Vaelatern** [comment]
@maxice8 I'd rather the emphasis be on the user's system, so people can think of what they are doing when they set this variable. Also, it's not clear if `=yes` makes sense for that variable, from the description.

**Comment by newbluemoon** [comment]
Maybe point out that it’s a special use case? I can only find it in kernel templates where it makes sense, to keep previous kernels and there the files/directories are versioned so that there aren’t any conflicts.

**Comment by maxice8** [comment]
> I'd rather the emphasis be on the user's system, so people can think of what they are doing when they set this variable.

I fail to see where else would the variable apply

> Also, it's not clear if =yes makes sense for that variable, from the description.

all consumers of it use =yes, it is pretty much unspoken/undocumented style to use =yes on variables that are simply knobs, the only exception i can think of is make_use_env=compliant

**Pull request closed without merging**
