### PR TITLE
New package: xwm-0.1.3

### PR DESCRIPTION
**Pull request by mcpcpc**

### CODE REVIEW

**Comment by mcpcpc** [comment]
Appears to fail checks due an internal Github Actions error.  Failed checks need to be forcefully re-run (which is something i do not have access to do).

**Comment by abenson** [comment]
Since options are determined at compile time, could you add something similar to https://github.com/void-linux/void-packages/blob/master/srcpkgs/dwm/template#L14 to copy a custom config.h over?

**Comment by mcpcpc** [comment]
> Since options are determined at compile time, could you add something similar to https://github.com/void-linux/void-packages/blob/master/srcpkgs/dwm/template#L14 to copy a custom config.h over?

Updated the template for a custom config.h file.

**Comment by biopsin** [comment]
@mcpcpc Ping bump to 0.1.8
(hm I might migrate to this wm)

**Pull request closed without merging**
