### PR TITLE
[WIP] owncloudclient: update to 2.5.3.

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by Cogitri** [comment]
See: https://github.com/owncloud/client/issues/6791

v2.5.0 of owncloudclient doesn't support Nextcloud instances properly. Nextcloud's new client (https://github.com/nextcloud/desktop) didn't have a non-rc release yet and doesn't build with libressl 2.8.x yet.

**Comment by maxice8** [comment]
owncloud upstream doesn't cross test with nextcloud so we shouldn't care about it really

**Comment by Cogitri** [comment]
Uh? Not care about breaking sync for all Nextcloud users?

**Comment by Cogitri** [comment]
Either we keep an older version of this (maybe the themed version) as Nextcloudclient 2.4.3 or we use the broken Nextcloudclient 2.5.0

**Comment by maxice8** [comment]
On Thu, Feb 14, 2019 at 04:20:09AM -0800, Rasmus Thomsen wrote:
> Uh? Not care about breaking sync for all Nextcloud users?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/4453#issuecomment-463607167

Upstream doesn't

**Comment by Cogitri** [comment]
Should I add an INSTALL.msg to make users aware of nextcloudclient?

**Comment by maxice8** [comment]
On Thu, Feb 14, 2019 at 10:35:07PM -0800, Rasmus Thomsen wrote:
> Should I add an INSTALL.msg to make users aware of nextcloudclient?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/4453#issuecomment-463925375

Can be

**Comment by maxice8** [comment]
Can't be merged due to breaking Nextcloud sync users.

**Pull request closed without merging**
