### PR TITLE
PrusaSlicer: update to 2.5.0

### PR DESCRIPTION
**Pull request by hvraven**
Updates PrusaSlicer to the latest release. It requires occt-7.6 for STEP import, I couldn't find any option to disable it temporarily. Version bump for occt is posted in PR #36356. Using it I successfully built and used the software on my system.

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by Gottox** [comment]
The issue with this PR is, that `occt` is pinned to 7.6.2. This will break any update to `occt`. I suggest the following patch to relax this requirements to PrusaSlicer:

```cat cmake-relax-dependency.patch```:
```patch
--- PrusaSlicer-version_2.5.0/src/occt_wrapper/CMakeLists.txt.orig	2022-09-17 11:47:02.398209546 +0200
+++ PrusaSlicer-version_2.5.0/src/occt_wrapper/CMakeLists.txt	2022-09-17 11:47:30.092595307 +0200
@@ -19,7 +19,7 @@ include(GenerateExportHeader)
 
 generate_export_header(OCCTWrapper)
 
-find_package(OpenCASCADE 7.6.2 REQUIRED)
+find_package(OpenCASCADE 7.6.2...7.999.999 REQUIRED)
 
 set(OCCT_LIBS
     TKXDESTEP
```

**Comment by hvraven** [comment]
Thanks @Gottox for the review and spotting the pinned version. I added the patch you suggested. I also tried building with the occt-7.4 currently in the tree, but the build fails with it.

**Comment by sgn** [comment]
I though `find_package(OpenCASCADE 7.6.2 REQUIRED)` is min version is `7.6.2`? (no `EXACT` specified)?

**Comment by vincele** [comment]
Same goal as #39756

**Pull request closed without merging**
