### PR TITLE
senpai: update to 0.2.0.

### PR DESCRIPTION
**Pull request by eoli3n**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, glibc

### CODE REVIEW

**Comment by eoli3n** [comment]
Fix https://github.com/void-linux/void-packages/issues/43860

**Comment by kedodrill** [comment]
@eoli3n if you would like to maintain this package I don't mind. I don't use IRC / senpai enough to be super interested in updates

**Comment by mdkcore0** [comment]
@kedodrill, @eoli3n: I'm using senpai on a daily use, and would like to adopt it if you are not planning to maintain it anymore :)

**Comment by eoli3n** [comment]
@mdkcore0 ok to me

**Pull request merged**
