### PR TITLE
New package: mutt-wizard-3.2.1

### LINKED ISSUE #35330: [Package request] Muttwizard
**About:** Muttwizard is a tool that automatically sets up a neomutt-based minimal email system.

**Website:** https://muttwizard.com/
**Repository:** https://github.com/lukesmithxyz/mutt-wizard

**License:** GNU General Public License v3.0

**Why?** Easy way to setup Mutt/ NeoMutt

### PR DESCRIPTION
**Pull request by motorto**
#### Testing the changes
I tested the changes in this PR: briefly

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): Yes

#### Local build testing
- I built this PR locally for my native architecture, x86_64-musl

As requested/fixes #35330

### CODE REVIEW

**Comment by Chocimier** [comment]
Please do not open new PRs, use `git push -f <fork> <attempt2>:<branch-of-pr>`.

**Comment by motorto** [comment]
Actually it was complaining about my fork being to old ... And to be
honest didn't know how to do it ... 

I apologized in the IRC also

**Comment by Chocimier** [comment]
I wanted just friendly show you how to continue work in same PR.

The error was about branch muttWizard being too old, not whole fork. So it is enough to rebase (or whatever you did locally to put changes onto fresh origin), then force push to your existing branch in existing fork.

**Comment by dataCobra** [comment]
Hey @motorto, what is the reason about closing this PR?

**Comment by motorto** [comment]
As stated on the PR you created its just a shell script.  And I didn't want to maintain the package

**Pull request closed without merging**
