### PR TITLE
libunwind: add patches for ppc*-musl

### PR DESCRIPTION
**Pull request by q66**
Requires https://github.com/void-linux/void-packages/pull/12359 first

This patches some internal bits to compile on ppc(64) with musl, where some structures have a different layout.

### CODE REVIEW

**Comment by q66** [comment]
Hm, don't merge this yet, still got something else to do maybe.

**Comment by q66** [comment]
Okay, now it does the right thing. We needed to add linkage for `-lucontext` when using libunwind on ppc-musl, as one of the macros in public headers actually uses ucontext.

**Comment by pullmoll** [comment]
Trying to build `strace` for `ppc-musl` or `ppc64-musl` with this PR's `libunwind` and `libucontext` gives me an error:
```
…
checking libunwind-ptrace.h usability... yes
checking libunwind-ptrace.h presence... yes
checking for libunwind-ptrace.h... yes
checking for backtrace in -lunwind... no
configure: error: in `/builddir/strace-5.1':
configure: error: failed to find libunwind
See `config.log' for more details
=> ERROR: strace-5.1_1: do_configure: '${configure_script} ${configure_args}' exited with 1
=> ERROR:   in do_configure() at common/build-style/gnu-configure.sh:7
```
I don't know if perhaps `libunwind` for `*-musl` should `makedepends+=" libexecinfo-devel"`...

**Comment by q66** [comment]
Dunno about that one. If you find the solution, let me know, I will also investigate.

**Comment by q66** [comment]
Figured it out. Will update PR in a few

**Comment by q66** [comment]
Fixed. Strace however needs another unrelated patch to build

**Pull request closed without merging**
