### PR TITLE
firefox-esr: update to 102.2.0.

### PR DESCRIPTION
**Pull request by oreo639**
#### Testing the changes
- I tested the changes in this PR: **briefly**

[ci skip]

This fixes build with current cbindgen in repos. This also fixes build with gcc 12.

### CODE REVIEW

**Comment by biopsin** [comment]
Tests ok for me on x86_64-glibc

**Comment by classabbyamp** [comment]
91.13.0 and 102.2.0 are available

**Comment by oreo639** [comment]
It doesn't have the patches:
https://github.com/chimera-linux/cports/blob/master/contrib/firefox-esr/template.py#L26

**Comment by classabbyamp** [comment]
btw, can we try removing `python` from hostmakedepends? It was removable for thunderbird so probably fine here too

**Comment by oreo639** [comment]
> btw, can we try removing `python` from hostmakedepends? It was removable for thunderbird so probably fine here too

Builds fine. Afaict from the fedora template, python2 is only needed for the tests unless I am misunderstanding.

cc: @Duncaen (the main ff package also still has python2 in its hostmakedeps)

**Comment by oreo639** [comment]
https://github.com/void-linux/void-packages/commit/4f1daf96bee4a39ba0db2325ef30119c48fa1f18

**Pull request closed without merging**
