### PR TITLE
New package: opensnitch-1.3.6

### LINKED ISSUE #28819: Package request: OpenSnitch
Reopen of #11093 since they have 1.3.6 now

Homepage: https://github.com/evilsocket/opensnitch
License: GPL-3.0

### PR DESCRIPTION
**Pull request by anubhavkini**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

closes #28819

### CODE REVIEW

**Comment by FollieHiyuki** [comment]
Should closes #28819

**Comment by ericonr** [comment]
Should be one `New package: pkgname-version` commit per package.

**Comment by ericonr** [comment]
Should be one `New package: pkgname-version` commit per package.

**Comment by Duncaen** [comment]
Is there a reason to split this into a meta package and a `d` package?
IMHO should should just be `opensnitch` containing the daemon and maybe a subpackage for the ui.

**Comment by itsanubhavkini** [comment]
It was easier since opensnitchd uses the go build-style and opensnitch-ui uses python3-module build-style.

**Comment by itsanubhavkini** [comment]
> IMHO should should just be `opensnitch` containing the daemon and maybe a subpackage for the ui.

Can subpackages have a different build-style from the source package?

**Comment by Duncaen** [comment]
No subpackages just move files from the main package, you would have to build it in the main package so you would have to do your own do_configure/do_build/do_install to build both and then move files into sub packages.

**Comment by itsanubhavkini** [comment]
Alright, I'll try that.

**Comment by ericonr** [comment]
@Duncaen maybe make one package for daemon and one for UI, to avoid having to duplicate most of the build logic? And make the daemon depend on the UI, if that makes sense.

I agree on the meta not being necessary. It's unfortunate that they use the same distfiles for both... If we go the route of separate packages, I'd add a comment to each template about keeping in sync with the other.

**Comment by Duncaen** [comment]
The separation between ui and daemon doesn't make a lot of sense and becomes cyclic if we add the dependencies on each other, which would be the only correct way to ensure that both are installed and at the same way.

**Comment by anubhavkini** [comment]
Finally got it to work

**Comment by anubhavkini** [comment]
@ericonr does this look okay?

**Comment by ericonr** [comment]
Sorry, I won't be able to review this soon.

**Pull request closed without merging**
