### PR TITLE
grafana: update to 8.0.4.

### PR DESCRIPTION
**Pull request by paper42**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Seems to have some non deterministic build failure, but besides that seems fine.

**Comment by ericonr** [comment]
Also, @the-maldridge for review.

**Comment by ericonr** [comment]
Any idea what could be causing the build failures? Just GH CI screwing with connectivity?

**Comment by paper42** [comment]
I don't think it's a problem outside of CI, builds on my computer work fine for both native (x86_64) and cross (aarch64-musl)

**Comment by paper42** [comment]
yarn is built for i686, so I removed the restriction. CI fails for that architecture probably because of github CI. I built it on my computer without a problem.

**Comment by ericonr** [comment]
@the-maldridge probably can't review this yet, and I think this version is used in void servers, so I'd rather wait a bit for his ok.

**Pull request closed without merging**
