### PR TITLE
dracut: update to 059.20231027

### PR DESCRIPTION
**Pull request by LaszloGombos**
#### Testing the changes
- I tested the changes in this PR: **NO**

Add a new version of dracut based on the latest git commit.
With this version upgrade I was able to remove 4 patches maintained in the tree.
Help is needed to test this upgrade.

It has been over 10 months since the last upstream dracut release. Upstream release generation is stalled, see - https://github.com/dracutdevs/dracut/issues/2431#issuecomment-1754305440

CC @zdykstra

### CODE REVIEW

**Comment by classabbyamp** [comment]
we shouldn't need to update as we still use gummiboot, which is not affected by the broken UKI math

**Comment by ahesford** [comment]
We don't permit updating to unreleased repository snapshots like this.

If there are a few **critical** patches you would like to backport to an official Dracut release, that would be acceptable; that would involve keeping the same version and just incrementing the revision.

**Comment by ahesford** [comment]
No, the policy applies to all packages and is described at the end of the [requirements section of our contributor guidelines](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements). There are rare exceptions, of course. In particular, the Intel video driver is legacy software that is not generally recommended for X11 (the mode setting driver is the recommended approach for Intel hardware). We tolerate a deviation from policy in this case because the legacy may be required for functionality with certain older hardware and backporting critical patches only would become an excessive maintenance burden.

In the case of Dracut, it seems we're looking at only a few key patches to maintain functionality. This case is complicated by the fact that some people, including you, maintain write privileges with Dracut but lack the authority to tag releases that we would accept as package updates. If this problem continues indefinitely, we can investigate other alternatives for keeping Dracut up to date. In the meantime, I hope that you and your collaborators can find a way to restore full, active maintenance of the project repository.

We appreciate the work you do to advance the state of Dracut and the fact that you remain mindful of the needs of distributions that do not use systemd (and, more generally, do not use it in initramfs images).

**Comment by zdykstra** [comment]
The stub that Void ships, Gummiboot, still works with the old UKI process. When/if we get systemd-boot in the repositories, we can look to backport the UKI offset fixes.

I'm not seeing anything in the linked issue that indicates why releases are stalled. Is there an issue I can follow that tracks that problem?

**Comment by zdykstra** [comment]
> > I'm not seeing anything in the linked issue that indicates why releases are stalled. Is there an issue I can follow that tracks that problem?
> 
> This is indeed the key issue here. I think @ahesford 's comment is already a great summary of the situation, but just to add...
> 
> > Currently only Github project admins can tag git commits in this project. The current project admins are documented in the wiki - https://github.com/dracutdevs/dracut/wiki/Dracut-development
> 
> At closer look you would notice that none of the project admins are active, and the remaining active maintainers are not able to make a tagged release. Here is one more pointer of a failed release attempt from July: [dracutdevs/dracut#2444](https://github.com/dracutdevs/dracut/issues/2444)
> 
> > If this problem continues indefinitely, we can investigate other alternatives for keeping Dracut up to date.
> 
> I just wanted to get a sense of how much this community is willing to wait for a release for something as critical to the boot process of the system. I think it is reasonable to revisit this issue in e.g. in 2024.

Right now, I think Void is pretty comfortable with the version of Dracut that we ship. Our tooling is more-or-less stable, so we aren't having to chase any systemd behavioral changes. We use an older EFI stub for UKI's, so the recent systemd-boot stub change didn't impact us.

For my needs (Dracut user, ZFSBootMenu developer), Dracut as it stands is a stable tool that has quirks that are known and can be targeted.

**Pull request closed without merging**
