### PR TITLE
liburing: update to 0.7.0.

### PR DESCRIPTION
**Pull request by ericonr**
Add test target (currently broken), remove arch restrictions.

Closes #17702.

### CODE REVIEW

**Comment by ericonr** [comment]
The previous version also had lots of broken tests.

**Comment by ahesford** [comment]
Why is `liburing` not in `common/shlibs` if its sole product is a shared object?

**Comment by ericonr** [comment]
Because nothing currently depends on it, which is also why I'm curious why it's even packaged.

**Comment by ahesford** [comment]
@ailiop-git can you comment on why this was packaged and why the shared object isn't listed in `common/shlibs`?

**Comment by ericonr** [comment]
ping @ailiop-git

**Comment by ailiop-git** [comment]
this was packaged to enable development and testing on top of the uring interface. the .so isn't in listed in shlibs as indeed there's currently no package that depends on it yet.

**Pull request merged**
