### PR TITLE
New package: otus-2.0

### PR DESCRIPTION
**Pull request by rc-05**

### CODE REVIEW

**Comment by Chocimier** [comment]
This [patch](https://gist.githubusercontent.com/Chocimier/0b609a167f320913c35c559bc9b0b491/raw/0de6db9afdebe33671cf4e969b9eebd5ac55fba6/otus-2.0.patch) fixes cross compilation.
I would name that package ol, like in urls and executable.

**Comment by rc-05** [comment]
Do i need to create a new package with xnew ol or i can just modify this package right here?

**Comment by rc-05** [comment]
> This [patch](https://gist.githubusercontent.com/Chocimier/0b609a167f320913c35c559bc9b0b491/raw/0de6db9afdebe33671cf4e969b9eebd5ac55fba6/otus-2.0.patch) fixes cross compilation.
> I would name that package ol, like in urls and executable.

Do I also need to rename the directory from "otus" to "ol" or is it best that i create a completely new package?

**Comment by rc-05** [comment]
Thinking about it it's better than I close this pull request and create a brand new package with the patch you suggested to apply @Chocimier.

**Pull request closed without merging**
