### PR TITLE
kdenlive: update to 21.08.0

### PR DESCRIPTION
**Pull request by hervyqa**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by Chocimier** [comment]
How did you test package, when it does not build?

**Comment by hervyqa** [comment]
> How did you test package, when it does not build?

oh, I didn't think it would fail.
yeah right, I haven't tested it locally.

**Comment by Chocimier** [comment]
Kde applications update is usually unproblematic, but one should test every updated program, and certainly not say that it was tested, when it wasn't.
This is one reason why some templates are lagging.

**Comment by Chocimier** [comment]
By testing, I mean install, build, launch manually and do _something_ with it. For packages with more impact (base libraries, drivers etc.) running for a day or more is encouraged.

**Comment by hervyqa** [comment]
> Kde applications update is usually unproblematic, but one should test every updated program, and certainly not say that it was tested, when it wasn't. This is one reason why some templates are lagging.
> By testing, I mean build, install, launch manually and do _something_ with it. For packages with more impact (base libraries, drivers etc.) running for a day or more is encouraged.

:) I'm too optimistic. this can be used as a record for me. thank you @Chocimier

**Comment by Johnnynator** [comment]
Closed in favour of #32576

**Pull request closed without merging**
