### PR TITLE
Drop maintainership of orphaned packages

### PR DESCRIPTION
**Pull request by lugubris**
some packages were dropped but their maintainer= was not updated in template.
this will help new maintainers adopt these packages.

-> https://github.com/void-linux/void-packages/pull/13930#issuecomment-524610652

### CODE REVIEW

**Comment by lugubris** [comment]
command used:
```
grep -nr "maintainer=\"maxice8\ <thinkabit.ukim@gmail.com>\"" | cut -d ':' -f 1 | parallel sed -i 's/maintainer=\"maxice8\ \<thinkabit.ukim@gmail.com\>\"/maintainer=\"Orphaned\ \<orphan@voidlinux.org\>\"/g'
```

**Comment by Anachron** [comment]
FYI: It didn't even need a grep. Just sed it next time using `sed -i "s|maxice|orphan|g' srcpkgs/*/template`. :-)

**Comment by lugubris** [comment]
Anachron @ 2019-08-25 18:06 UTC:

> FYI: It didn't even need a grep. Just sed it next time using sed 
> -i "s|maxice|
> orphan|g' srcpkgs/*/template. :-)

@Anachron That would catch false positives because `maxice` can 
come in a url or
a program's name or anywhere else. afaik sed uses a single cpu to 
perform the
job whereas parallel uses all 4 cpus so faster but yes this could 
be done with
just sed.

--
Lugubris
2AD2 612A AF91 A34B F09E
FB04 0EB1 022B D624 0D7A

**Comment by lugubris** [comment]
Lugubris @ 2019-08-26 07:21 UTC:

> Anachron @ 2019-08-25 18:06 UTC:
>
>> FYI: It didn't even need a grep. Just sed it next time using 
>> sed
>> -i "s|maxice|
>> orphan|g' srcpkgs/*/template. :-)
>
> @Anachron That would catch false positives because `maxice` can
> come in a url or
> a program's name or anywhere else. afaik sed uses a single cpu 
> to
> perform the
> job whereas parallel uses all 4 cpus so faster but yes this 
> could
> be done with
> just sed.

For some reason the formatting is broken, this is a test email to 
check
if mu4e has fixed the formatting.
--
Lugubris
2AD2 612A AF91 A34B F09E
FB04 0EB1 022B D624 0D7A

**Comment by Anachron** [comment]
My example was not a completely working one ... you'd have to replace it with the sed regex you provided, of course. Just removes the need for the grep. But then again you're right, it wouldn't parallelize, didn't think of that.

**Comment by lugubris** [comment]
Lugubris @ 2019-08-26 07:21 UTC:

> Anachron @ 2019-08-25 18:06 UTC:
>
>> FYI: It didn't even need a grep. Just sed it next time using 
>> sed
>> -i "s|maxice|
>> orphan|g' srcpkgs/*/template. :-)
>
> @Anachron That would catch false positives because `maxice` can
> come in a url or
> a program's name or anywhere else. afaik sed uses a single cpu 
> to
> perform the
> job whereas parallel uses all 4 cpus so faster but yes this 
> could
> be done with
> just sed.

mu4e was hard breaking those lines which is not good, checking if 
it
still does that.
--
Lugubris
2AD2 612A AF91 A34B F09E
FB04 0EB1 022B D624 0D7A

**Comment by lugubris** [comment]
Lugubris @ 2019-08-26 07:32 UTC:

> Lugubris @ 2019-08-26 07:21 UTC:
>
>> Anachron @ 2019-08-25 18:06 UTC:
>>
>>> FYI: It didn't even need a grep. Just sed it next time using
>>> sed
>>> -i "s|maxice|
>>> orphan|g' srcpkgs/*/template. :-)
>>
>> @Anachron That would catch false positives because `maxice` can
>> come in a url or
>> a program's name or anywhere else. afaik sed uses a single cpu
>> to
>> perform the
>> job whereas parallel uses all 4 cpus so faster but yes this
>> could
>> be done with
>> just sed.
>
> For some reason the formatting is broken, this is a test email 
> to
> check
> if mu4e has fixed the formatting.

hmm still not fixed, testing this thing again with different 
config used
in mu4e.

--
Lugubris
2AD2 612A AF91 A34B F09E
FB04 0EB1 022B D624 0D7A

**Pull request merged**
