### PR TITLE
protobuf and dependants: rebuild for gcc stdc++ dropping gcc4 compat

### PR DESCRIPTION
**Pull request by jnbr**
fixes https://github.com/void-linux/void-packages/issues/1126

### CODE REVIEW

**Comment by Hoshpak** [comment]
did you try compiling mumble? I also had to rebuild `Ice` to successfully link it after compiling it.

**Comment by jnbr** [comment]
everything built for x86_64-glibc, testing everything else now …

**Comment by jnbr** [comment]
x86_64-glibc and -musl builds work now. Should be good to merge. I have no idea how this version of `cura-engine` did ever build. Apparently it did.

**Comment by jnbr** [comment]
local builds for i686 and cross builds (aarch64, armv7l, armv6l) for glibc and musl completed.

**Pull request closed without merging**
