### PR TITLE
crun: update to 1.6.

### PR DESCRIPTION
**Pull request by natrys**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by daniel-eys** [comment]
1.6 is available, works without issues so far

**Comment by natrys** [comment]
@daniel-eys Perhaps you should make a new PR? I doubt maintainers look at months old ones, so doesn't matter if I update here.

**Comment by leahneukirchen** [comment]
Please update this PR.

**Review by paper42 — COMMENTED** [review]
remove libtool from hostmakedepends, it shouldn't be necessary

**Pull request merged**
