### PR TITLE
libreoffice: update to 6.2.3.2 and enable KDE/Qt integration

### PR DESCRIPTION
**Pull request by purpurrot**
[ci skip]

### CODE REVIEW

**Comment by Cogitri** [comment]
Does this work properly now? Last time I've tested with libreoffice 6.1 it was preeeeetty broken

**Comment by purpurrot** [comment]
I haven't tested it yet, but LibreOffice 6.2 added VCL plugins for qt5 and kde5.

Although, maybe it's better to wait for 6.2.1.
https://wiki.documentfoundation.org/ReleasePlan/6.2#6.2.1_release
https://download.documentfoundation.org/libreoffice/src/6.2.1/

**Comment by Cogitri** [comment]
> I haven't tested it yet

You should certainly test your contributions before posting them here.

**Comment by purpurrot** [comment]
I tested it on my machine (x86_64) and it seemed to work (starting libreoffice, opening lowriter and loimpress).
I moved the vcl plugins for qt5 and kde5 into a new package 'libreoffice-kde'.
I also updated the version to the newest release.

**Comment by maxice8** [comment]
@pullmoll

**Comment by pullmoll** [comment]
I would be testing this PR in the next few days for x86_64, yet some dependencies don't currently build, e.g. oracle-jdk-8u202. The download at Oracle is gone and thus we cannot bootstrap openjdk any longer :(

**Comment by pullmoll** [comment]
Works for me. I haven't tried anything KDE related, yet the basic programs seem to be ok.

**Pull request closed without merging**
