### PR TITLE
pijul: update to 0.11.0.

### PR DESCRIPTION
**Pull request by maxice8**
Please wait for travis to complete, testing if arm works.

### CODE REVIEW

**Comment by Vaelatern** [comment]
Looks like musl also has the wrong type, as does aarch64.

**Comment by jnbr** [comment]
musl patch:
```
--- line/src/unix.rs.orig       2018-11-19 17:58:53.508689362 +0100
+++ line/src/unix.rs    2018-11-19 18:01:09.899536021 +0100
@@ -4,9 +4,15 @@
 use utf8parse;

 fn size() -> (usize, usize) {
+
+#[cfg(target_env = "musl")]
+    type IoctlReq = libc::c_int;
+#[cfg(not(target_env = "musl"))]
+    type IoctlReq = libc::c_ulong;
+
     unsafe {
         let mut size: libc::winsize = std::mem::zeroed();
-        if libc::ioctl(1, libc::TIOCGWINSZ as libc::c_ulong, &mut size) == 0 {
+        if libc::ioctl(1, libc::TIOCGWINSZ as IoctlReq, &mut size) == 0 {
             (size.ws_col as usize, size.ws_row as usize)
         } else {
             (0, 0)
```

**Comment by Vaelatern** [comment]
@jnbr any way for that to work for arm as well?

**Comment by maxice8** [comment]
@jnbr updated, thanks

**Comment by jnbr** [comment]
yes, builds on all architectures here

**Comment by jnbr** [comment]
better patch which does exactly the same:
```
--- line/src/unix.rs.orig       2018-11-19 19:17:02.606568203 +0100
+++ line/src/unix.rs    2018-11-19 19:17:13.762473164 +0100
@@ -6,7 +6,7 @@
 fn size() -> (usize, usize) {
     unsafe {
         let mut size: libc::winsize = std::mem::zeroed();
-        if libc::ioctl(1, libc::TIOCGWINSZ as libc::c_ulong, &mut size) == 0 {
+        if libc::ioctl(1, libc::TIOCGWINSZ, &mut size) == 0 {
             (size.ws_col as usize, size.ws_row as usize)
         } else {
             (0, 0)
```

**Pull request merged**
