### PR TITLE
element-desktop: update to 1.10.14.

### PR DESCRIPTION
**Pull request by jcgruenhage**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by notramo** [comment]
Element Desktop 1.10.8 has been released with a security fix.

**Review by paper42 — COMMENTED** [review]
Can we use create_wrksrc to make sure everything gets cleaned up?

**Comment by jcgruenhage** [comment]
> Can we use create_wrksrc to make sure everything gets cleaned up?

I've looked into this for a bit, but it's not quite as trivial as I had hoped. It makes fiddeling with the patches a bit more difficult. I can't find a way to dynamically generate the patch args for the two different extracted tarballs, as `${PATCHESDIR}` is read only and writing it next to the `.patch` file in the `${XBPS_BUILDDIR}` doesn't seem to have any effect. Any idea how to handle this?

**Comment by classabbyamp** [comment]
the issue with patching and create_wrksrc should be fixable now with `patch_args="-Np1 -d ${build_wrksrc}"`

**Pull request merged**
