### PR TITLE
ne: update to 3.2

### PR DESCRIPTION
**Pull request by tpar2911**
#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by Duncaen** [comment]
The commit title should be `ne: update to 3.3.2.`, the checksum is also wrong, not sure how this would be able to build.

**Comment by tpar2911** [comment]
I see where I've made the mistakes. I'll fix them and create a new pull request. Thank you

**Comment by Duncaen** [comment]
Please don't open new PRs, you can fix the problems and force push to the same branch you opened the PR for.

**Comment by tpar2911** [comment]
I understand, I'll do that.

**Comment by tpar2911** [comment]
I think I've fixed the issue. The file change should be correct now.

**Comment by Duncaen** [comment]
There are still unrelated commits in the PR and there should be just one commit.
Probably easier to reset your branch to master and the redo the commit.

**Comment by tpar2911** [comment]
Alright, I'll do that.

**Comment by tpar2911** [comment]
I'm sorry I seem to be stuck. What would i need to do in order to do this?

**Comment by Duncaen** [comment]
You could do something like:
```
git switch master
git branch -D ne
git switch -c ne
... do the changes and commit..
git push -f origin ne
```

**Comment by Duncaen** [comment]
Not sure, this should have fixed it as its the same branch in clean. Maybe its because it was closed.

**Comment by tpar2911** [comment]
I see. Thanks anyway for your help.

**Pull request closed without merging**
