### PR TITLE
build-style/meson: enable Link-Time-Optimization by default.

### PR DESCRIPTION
**Pull request by maxice8**
This PR enables [Link Time Optimization](https://gcc.gnu.org/wiki/LinkTimeOptimization) or LTO by default on all meson builds

changes:

switch to using the gcc-ar wrapper that passes the correct plugin paths for static libraries (this is working around a binutils bug). See: https://github.com/mesonbuild/meson/issues/1646

- [x] AppStream
- [x] Marker
- [x] Minder
- [x] bolt
- [x] gnome-tweaks
- [x] FeedReader
- [x] accountsservice
- [x] appstream-glib
- [x] at-spi2-atk
- [x] atk
- [x] atomix
- [x] at-spi2-core
- [x] bijiben
- [x] brisk-menu
- [x] baobab
- [x] cinnamon-desktop
- [x] cinnamon-session
- [x] colord
- [x] corebird
- [x] cozy
- [x] dconf-editor
- [x] dconf
- [x] devhelp
- [x] elogind
- [x] enlightenment
- [x] eog
- [x] epiphany
- [ ] file-roller
- [x] five-or-more
- [x] fuse3
- [x] fwupd
- [x] gcab
- [x] gdk-pixbuf
- [x] geocode-glib
- [x] girara
- [x] glib-networking
- [x] gnome-backgrounds
- [x] gnome-bluetooth
- [x] gnome-chess
- [x] gnome-builder
- [x] gnome-calculator
- [x] gnome-calendar
- [x] gnome-characters
- [x] gnome-boxes
- [x] gnome-clocks
- [x] gnome-color-manager
- [x] gnome-contacts
- [x] gnome-control-center
- [x] gnome-dictionary
- [x] gnome-disk-utility
- [x] gnome-documents
- [x] gnome-font-viewer
- [x] gnome-initial-setup
- [x] gnome-maps
- [x] gnome-mines
- [x] gnome-multi-writer
- [x] gnome-music
- [x] gnome-power-manager
- [x] gnome-recipes
- [x] gnome-screenshot
- [x] gnome-settings-daemon
- [x] gnome-session
- [x] gnome-shell-extensions
- [x] gnome-shell
- [x] gnome-sudoku
- [x] gnome-system-monitor
- [x] gnome-todo
- [x] gobject-introspection
- [x] gradio
- [x] grilo-plugins
- [x] fuse-sshfs
- [x] gvfs
- [x] hexchat
- [x] intel-gpu-tools
- [x] json-glib
- [x] jsonrpc-glib
- [x] kiwix-lib
- [x] kiwix-tools
- [x] ksh
- [x] libcloudproviders
- [x] libdazzle
- [x] libdrm
- [x] libepoxy
- [x] libgepub
- [x] libgit2-glib
- [x] libgusb
- [x] libgweather
- [x] libinput
- [x] libmpdclient
- [x] libxkbcommon
- [x] libzim
- [x] lightsoff
- [x] lighttpd
- [x] linux-driver-management
- [x] lollypop
- [x] mpc
- [x] nautilus
- [x] ncmpc
- [x] nemo
- [x] nautilus-sendto
- [x] gnome-mpv
- [x] pantheon-screenshot
- [x] paper-icon-theme
- [x] paprefs
- [x] pipewire
- [x] playerctl
- [x] pithos
- [x] polari
- [x] pulseeffects
- [x] libGL
- [x] gnome-twitch
- [x] rage-player
- [x] razergenie
- [x] seahorse
- [x] shotwell
- [x] simple-scan
- [x] spice-protocol
- [x] swell-foop
- [x] sysprof
- [x] totem-pl-parser
- [x] terminology
- [x] totem
- [x] vapoursynth-mvtools
- [x] template-glib
- [x] viewnior
- [x] xapps
- [x] eolie
- [x] xorg-server
- [x] zathura-cb
- [x] zathura-pdf-poppler
- [x] zathura-pdf-mupdf
- [x] zathura
- [x] zathura-ps
- [x] zathura-djvu
- [x] taisei
- [x] goodvibes
- [x] gnome-usage
- [x] io.elementary.calculator
- [x] libratbag
- [x] libplacebo
- [x] io.elementary.videos
- [x] zim-tools
- [x] sequeler
- [x] io.elementary.terminal
- [x] pdftag
- [x] piper
- [x] pscircle
- [x] zchunk
- [ ] quickDocs
- [ ] scrcpy
- [x] pantheon-agent-polkit

### CODE REVIEW

**Comment by Cogitri** [comment]
IMO LTO should be optionalised (but enabled by default), some stuff fails to build with LTO or errors out during runtime with it enabled.

**Comment by maxice8** [comment]
templates can pass -Db_lto=false in configure_args

**Comment by Cogitri** [comment]
> templates can pass -Db_lto=false in configure_args

Oh, yeah

**Comment by Gottox** [comment]
In general I'd like to get LTO enabled, but I fear increasing buildtimes.

**Comment by maxice8** [comment]
I didn't take numbers but building didn't appear to take much longer

**Comment by Gottox** [comment]
@maxice8 Okay. If it won't impact the build time for most projects we can still disable it individually.

**Comment by Cogitri** [comment]
Some crude build time testing (`time ./xbps-src pkg <package>`, run `./xbps-src clean` beforehand):

- xorg-server:
  * without LTO: real	1m46.581s
  * with LTO: real	2m8.415s
- totem
  * without LTO: real	1m51.862s
  * with LTO: real	2m4.466s

**Comment by maxice8** [comment]
@Gottox i'd like this to not be merged until i complete my rebuild of all build_style=meson packages

**Comment by Gottox** [comment]
@maxice8 schedule the merge as you'd like :+1:

**Pull request closed without merging**
