### PR TITLE
WIP Qt6 webengine

### PR DESCRIPTION
**Pull request by sgn**
Never tried to cross build
Functionality works (at least can view youtube video on x86_64-musl)

#### Testing the changes
- I tested the changes in this PR: **YES**|**briefly**|**NO**
[ci skip]

### CODE REVIEW

**Comment by skmpz** [comment]
All packages **except qt6-webengine** built successfully for:
- x86_64
- i686
- aarch64 (cross on x86_64)
- armv7l (cross on x86_64)
- x86_64-musl
- aarch64-musl (cross on x86_64-musl)

Package **qt6-webengine** fails for x86_64-libc (did not try other archs)
<details>
<summary>build error</summary>

```sh
...
In file included from ../../../../../src/3rdparty/chromium/third_party/crashpad/crashpad/util/linux/ptracer.cc:29:
../../../../../src/3rdparty/chromium/third_party/crashpad/crashpad/util/linux/ptracer.cc: In function 'bool crashpad::{anonymous}::GetThreadArea32(pid_t, const crashpad::ThreadContext&, crashpad::LinuxVMAddress*, bool)':
../../../../../src/3rdparty/chromium/third_party/crashpad/crashpad/util/linux/ptracer.cc:74:11: error: invalid conversion from 'int' to '__ptrace_request' [-fpermissive]
   74 |           PTRACE_GET_THREAD_AREA, tid, reinterpret_cast<void*>(index), &desc) !=
      |           ^~~~~~~~~~~~~~~~~~~~~~
      |           |
      |           int
In file included from /usr/include/sys/ptrace.h:198,
                 from ../../../../../src/3rdparty/chromium/third_party/crashpad/crashpad/compat/linux/sys/ptrace.h:18,
                 from ../../../../../src/3rdparty/chromium/third_party/crashpad/crashpad/util/linux/ptracer.cc:20:
/usr/include/bits/ptrace-shared.h:132:47: note:   initializing argument 1 of 'long int ptrace(__ptrace_request, ...)'
  132 | extern long int ptrace (enum __ptrace_request __request, ...) __THROW;
      |                         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
[16388/29148] CXX obj/third_party/crashpad/crashpad/util/util/scoped_pr_set_ptracer.o
[16389/29148] CXX obj/third_party/crashpad/crashpad/util/util/scoped_ptrace_attach.o
[16390/29148] CXX obj/third_party/crashpad/crashpad/util/util/time_linux.o
[16391/29148] CXX obj/third_party/crashpad/crashpad/util/util/ptrace_broker.o
[16392/29148] CXX obj/third_party/crashpad/crashpad/util/util/paths_linux.o
[16393/29148] CXX obj/third_party/crashpad/crashpad/util/util/memory_map.o
[16394/29148] CXX obj/third_party/crashpad/crashpad/util/util/socket.o
[16395/29148] CXX obj/third_party/crashpad/crashpad/util/util/process_memory_linux.o
[16396/29148] CXX obj/third_party/hunspell/hunspell/bdict.o
[16397/29148] CXX obj/third_party/crashpad/crashpad/util/util/ptrace_client.o
[16398/29148] CXX obj/third_party/crashpad/crashpad/util/util/process_memory_sanitized.o
[16399/29148] CXX obj/third_party/crashpad/crashpad/util/util/process_info_linux.o
[16400/29148] CXX obj/third_party/fdlibm/fdlibm/ieee754.o
[16401/29148] CXX obj/third_party/hunspell/hunspell/bdict_reader.o
[16402/29148] CXX obj/third_party/hunspell/hunspell/bdict_writer.o
ninja: build stopped: subcommand failed.
FAILED: src/core/None/x86_64/QtWebEngineCore.stamp src/core/None/x86_64/QtWebEngineCore /builddir/qtwebengine-everywhere-src-6.3.1/build/src/core/None/x86_64/QtWebEngineCore.stamp /builddir/qtwebengine-everywhere-src-6.3.1/build/src/core/None/x86_64/QtWebEngineCore
cd /builddir/qtwebengine-everywhere-src-6.3.1/build/src/core && /builddir/.xbps-qt6-webengine/wrappers/ninja -C /builddir/qtwebengine-everywhere-src-6.3.1/build/src/core/None/x86_64 QtWebEngineCore
ninja: build stopped: subcommand failed.
=> ERROR: qt6-webengine-6.3.1_1: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 1
=> ERROR:   in do_build() at common/build-style/cmake.sh:85
```

</details>

On armv6l-musl (cross on x86_64-musl) **qt6-base** fails
<details>
<summary>build error</summary>

```sh
/usr/arm-linux-musleabihf/usr/include/c++/10.2/bits/stl_algo.h:1945:5: note: parameter passing for argument of type 'QList<std::pair<double, QVariant> >::iterator' changed in GCC 7.1
/usr/arm-linux-musleabihf/usr/include/c++/10.2/bits/stl_algo.h:1924:34: note: parameter passing for argument of type 'QList<std::pair<double, QVariant> >::iterator' changed in GCC 7.1
 1924 |       std::__move_median_to_first(__first, __first + 1, __mid, __last - 1,
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1925 |       __comp);
      |       ~~~~~~~                     
/usr/arm-linux-musleabihf/usr/include/c++/10.2/bits/stl_algo.h:1924:34: note: parameter passing for argument of type 'QList<std::pair<double, QVariant> >::iterator' changed in GCC 7.1
/usr/arm-linux-musleabihf/usr/include/c++/10.2/bits/stl_algo.h:1959:25: note: parameter passing for argument of type 'QList<std::pair<double, QVariant> >::iterator' changed in GCC 7.1
 1959 |    std::__introsort_loop(__cut, __last, __depth_limit, __comp);
      |    ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/arm-linux-musleabihf/usr/include/c++/10.2/bits/stl_algo.h:1666:23: note: parameter passing for argument of type 'QList<std::pair<double, QVariant> >::iterator' changed in GCC 7.1
 1666 |       std::__make_heap(__first, __middle, __comp);
      |       ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/arm-linux-musleabihf/usr/include/c++/10.2/bits/stl_algo.h: In member function 'void QVariantAnimation::setKeyValues(const KeyValues&)':
/usr/arm-linux-musleabihf/usr/include/c++/10.2/bits/stl_algo.h:1974:25: note: parameter passing for argument of type 'QList<std::pair<double, QVariant> >::iterator' changed in GCC 7.1
 1974 |    std::__introsort_loop(__first, __last,
      |    ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
 1975 |     std::__lg(__last - __first) * 2,
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1976 |     __comp);
      |     ~~~~~~~              
/usr/arm-linux-musleabihf/usr/include/c++/10.2/bits/stl_algo.h:1886:25: note: parameter passing for argument of type 'QList<std::pair<double, QVariant> >::iterator' changed in GCC 7.1
 1886 |    std::__insertion_sort(__first, __first + int(_S_threshold), __comp);
      |    ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/arm-linux-musleabihf/usr/include/c++/10.2/bits/stl_algo.h:1891:23: note: parameter passing for argument of type 'QList<std::pair<double, QVariant> >::iterator' changed in GCC 7.1
 1891 |  std::__insertion_sort(__first, __last, __comp);
      |  ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
[294/1559] Building CXX object src/corelib/CMakeFiles/Core.dir/global/qversiontagging.cpp.o
[295/1559] Building CXX object src/corelib/CMakeFiles/Core.dir/io/qfilesystemengine_unix.cpp.o
[296/1559] Building CXX object src/corelib/CMakeFiles/Core.dir/io/qfilesystemiterator_unix.cpp.o
[297/1559] Building CXX object src/corelib/CMakeFiles/Core.dir/io/qfsfileengine_unix.cpp.o
[298/1559] Building CXX object src/corelib/CMakeFiles/Core.dir/io/qlockfile_unix.cpp.o
[299/1559] Building CXX object src/corelib/CMakeFiles/Core.dir/kernel/qcore_unix.cpp.o
[300/1559] Building CXX object src/corelib/CMakeFiles/Core.dir/kernel/qeventdispatcher_unix.cpp.o
[301/1559] Building CXX object src/corelib/CMakeFiles/Core.dir/kernel/qtimerinfo_unix.cpp.o
[302/1559] Building CXX object src/corelib/CMakeFiles/Core.dir/thread/qthread_unix.cpp.o
[303/1559] Building CXX object src/corelib/CMakeFiles/Core.dir/thread/qatomic.cpp.o
[304/1559] Building CXX object src/corelib/CMakeFiles/Core.dir/thread/qmutex.cpp.o
[305/1559] Building CXX object src/corelib/CMakeFiles/Core.dir/thread/qreadwritelock.cpp.o
[306/1559] Building CXX object src/corelib/CMakeFiles/Core.dir/thread/qsemaphore.cpp.o
/builddir/qtbase-everywhere-src-6.3.1/src/corelib/thread/qsemaphore.cpp: In function 'bool futexSemaphoreTryAcquire_loop(QBasicAtomicInteger<unsigned int>&, quintptr, quintptr, int)':
/builddir/qtbase-everywhere-src-6.3.1/src/corelib/thread/qsemaphore.cpp:197:26: warning: right shift count >= width of type [-Wshift-count-overflow]
  197 |                 curValue >>= 32;
      |                 ~~~~~~~~~^~~~~~
/builddir/qtbase-everywhere-src-6.3.1/src/corelib/thread/qsemaphore.cpp: In function 'bool futexSemaphoreTryAcquire(QBasicAtomicInteger<unsigned int>&, int, int)':
/builddir/qtbase-everywhere-src-6.3.1/src/corelib/thread/qsemaphore.cpp:249:24: warning: right shift count >= width of type [-Wshift-count-overflow]
  249 |         if (((curValue >> 32) & 0x7fffffffU) == 0x7fffffffU) {
      |               ~~~~~~~~~^~~~~
[307/1559] Building CXX object src/corelib/CMakeFiles/Core.dir/thread/qthreadpool.cpp.o
[308/1559] Building CXX object src/corelib/CMakeFiles/Core.dir/thread/qthreadstorage.cpp.o
[309/1559] Building CXX object src/corelib/CMakeFiles/Core.dir/thread/qwaitcondition_unix.cpp.o
[310/1559] Building CXX object src/corelib/CMakeFiles/Core.dir/thread/qexception.cpp.o
[311/1559] Building CXX object src/corelib/CMakeFiles/Core.dir/thread/qfutureinterface.cpp.o
FAILED: src/corelib/CMakeFiles/Core.dir/thread/qfutureinterface.cpp.o 
/builddir/.xbps-qt6-base/wrappers/arm-linux-musleabihf-c++ -DCore_EXPORTS -DQT_ASCII_CAST_WARNINGS -DQT_BUILDING_QT -DQT_BUILD_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_DEPRECATED_WARNINGS_SINCE=0x060000 -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_MOC_COMPAT -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_USING_NAMESPACE -DQT_TYPESAFE_FLAGS -DQT_USE_QSTRINGBUILDER -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I/builddir/qtbase-everywhere-src-6.3.1/build/src/corelib/Core_autogen/include -I/builddir/qtbase-everywhere-src-6.3.1/build/include -I/builddir/qtbase-everywhere-src-6.3.1/build/include/QtCore -I/builddir/qtbase-everywhere-src-6.3.1/src/corelib -I/builddir/qtbase-everywhere-src-6.3.1/build/src/corelib -I/builddir/qtbase-everywhere-src-6.3.1/build/src/corelib/global -I/builddir/qtbase-everywhere-src-6.3.1/build/src/corelib/kernel -I/builddir/qtbase-everywhere-src-6.3.1/src/corelib/../3rdparty/tinycbor/src -I/builddir/qtbase-everywhere-src-6.3.1/build/include/QtCore/6.3.1 -I/builddir/qtbase-everywhere-src-6.3.1/build/include/QtCore/6.3.1/QtCore -I/builddir/qtbase-everywhere-src-6.3.1/src/corelib/../3rdparty/forkfd -I/builddir/qtbase-everywhere-src-6.3.1/build/src/corelib/.rcc -I/builddir/qtbase-everywhere-src-6.3.1/mkspecs/linux-g++ -I /usr/arm-linux-musleabihf/usr/include/glib-2.0 -I /usr/arm-linux-musleabihf/usr/lib/glib-2.0/include -DNDEBUG -fstack-clash-protection -D_FORTIFY_SOURCE=2 -O2 -march=armv6 -mfpu=vfp -mfloat-abi=hard   -I/usr/arm-linux-musleabihf/usr/include -fdebug-prefix-map=/builddir/qtbase-everywhere-src-6.3.1=. -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -Wsuggest-override -std=c++17 -MD -MT src/corelib/CMakeFiles/Core.dir/thread/qfutureinterface.cpp.o -MF src/corelib/CMakeFiles/Core.dir/thread/qfutureinterface.cpp.o.d -o src/corelib/CMakeFiles/Core.dir/thread/qfutureinterface.cpp.o -c /builddir/qtbase-everywhere-src-6.3.1/src/corelib/thread/qfutureinterface.cpp
/tmp/ccdMiAHP.s: Assembler messages:
/tmp/ccdMiAHP.s:825: Error: selected processor does not support `yield' in ARM mode
/tmp/ccdMiAHP.s:850: Error: selected processor does not support `yield' in ARM mode
/tmp/ccdMiAHP.s:1612: Error: selected processor does not support `yield' in ARM mode
/tmp/ccdMiAHP.s:2493: Error: selected processor does not support `yield' in ARM mode
/tmp/ccdMiAHP.s:3539: Error: selected processor does not support `yield' in ARM mode
ninja: build stopped: subcommand failed.
=> ERROR: qt6-base-6.3.1_1: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 1
=> ERROR:   in do_build() at common/build-style/cmake.sh:85
```

</details>

**Comment by sgn** [comment]
Did you mean qt6-webengine failed on x86-64 with glibc?

**Comment by skmpz** [comment]
> Did you mean qt6-webengine failed on x86-64 with glibc?

yes

**Comment by sgn** [comment]
@skmpz Can you test with new patchset?

**Comment by skmpz** [comment]
attaching log from qt6-base tests failure
[qt6-base.log](https://github.com/void-linux/void-packages/files/9332891/qt6-base.log)

**Comment by sgn** [comment]
@skmpz  added more patches :p

**Comment by skmpz** [comment]
seems better :D now only the tst_qstorage is failing..
```
********* Start testing of tst_QStorageInfo *********
Config: Using QtTest library 6.3.1, Qt 6.3.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 10.2.1 20201203), unknown unknown
PASS   : tst_QStorageInfo::initTestCase()
FAIL!  : tst_QStorageInfo::defaultValues() '!storage.isRoot()' returned FALSE. ()
   Loc: [/builddir/qtbase-everywhere-src-6.3.1/tests/auto/corelib/io/qstorageinfo/tst_qstorageinfo.cpp(59)]
QINFO  : tst_QStorageInfo::dump() Filesystem (Type)            Size  Available BSize  Label            Mounted on
QINFO  : tst_QStorageInfo::dump() /dev/mapper/void_enc-home (ext4) RW 
                        213960016  184044368  4096  subvol=/sk/void-packages  /void-packages
QINFO  : tst_QStorageInfo::dump() cgroup (tmpfs)      RW   16390408   16390408  4096                            /void-packages/masterdir/sys/fs/cgroup
QINFO  : tst_QStorageInfo::dump() devtmpfs            RW   16351232   16351232  4096                            /void-packages/masterdir/dev
QINFO  : tst_QStorageInfo::dump() tmpfs               RW   16390408   16046516  4096                            /void-packages/masterdir/dev/shm
QINFO  : tst_QStorageInfo::dump() /dev/mapper/void_enc-home (ext4) RW 
                        213960016  184044368  4096  subvol=/sk/void-packages/hostdir /host
PASS   : tst_QStorageInfo::dump()
PASS   : tst_QStorageInfo::operatorEqual()
FAIL!  : tst_QStorageInfo::operatorNotEqual() 'storage1 != storage2' returned FALSE. ()
   Loc: [/builddir/qtbase-everywhere-src-6.3.1/tests/auto/corelib/io/qstorageinfo/tst_qstorageinfo.cpp(126)]
FAIL!  : tst_QStorageInfo::root() 'storage.isValid()' returned FALSE. ()
   Loc: [/builddir/qtbase-everywhere-src-6.3.1/tests/auto/corelib/io/qstorageinfo/tst_qstorageinfo.cpp(133)]
FAIL!  : tst_QStorageInfo::currentStorage() 'storage.isValid()' returned FALSE. ()
   Loc: [/builddir/qtbase-everywhere-src-6.3.1/tests/auto/corelib/io/qstorageinfo/tst_qstorageinfo.cpp(150)]
FAIL!  : tst_QStorageInfo::storageList() 'volumes.contains(root)' returned FALSE. ()
   Loc: [/builddir/qtbase-everywhere-src-6.3.1/tests/auto/corelib/io/qstorageinfo/tst_qstorageinfo.cpp(167)]
FAIL!  : tst_QStorageInfo::tempFile() 'free != -1' returned FALSE. ()
   Loc: [/builddir/qtbase-everywhere-src-6.3.1/tests/auto/corelib/io/qstorageinfo/tst_qstorageinfo.cpp(198)]
FAIL!  : tst_QStorageInfo::caching() 'free != -1' returned FALSE. ()
   Loc: [/builddir/qtbase-everywhere-src-6.3.1/tests/auto/corelib/io/qstorageinfo/tst_qstorageinfo.cpp(228)]
PASS   : tst_QStorageInfo::cleanupTestCase()
Totals: 4 passed, 7 failed, 0 skipped, 0 blacklisted, 10ms
********* Finished testing of tst_QStorageInfo *********
CMake Error at tst_qstorageinfoWrapperNone.cmake:17 (message):
  
  /builddir/qtbase-everywhere-src-6.3.1/build/tests/auto/corelib/io/qstorageinfo/tst_qstorageinfo
  execution failed with exit code 7.
```

**Comment by sgn** [comment]
`tst_qstorageinfo` is too problematic, I guess we should disable that.
Are you running your system on ext4 on top of btrfs? Qt6 StorageInfo is broken with btrfs and zfs.

**Comment by skmpz** [comment]
i'm running on ext4 (no btrfs)

**Comment by sgn** [comment]
ext4 supports `subvol=` now?

**Comment by skmpz** [comment]
I'm using LVM+ext4 full disk encryption as described in the docs (https://docs.voidlinux.org/installation/guides/fde.html).

Build with x86-64 is ok now.. I will retry building all the packages again and will update.

**Comment by skmpz** [comment]
@sgn there are a couple of test failures on i686 for qt6-base package..
[qt6-base-i686.log](https://github.com/void-linux/void-packages/files/9333624/qt6-base-i686.log)

**Comment by sgn** [comment]
> @sgn there are a couple of test failures on i686 for qt6-base package.. [qt6-base-i686.log](https://github.com/void-linux/void-packages/files/9333624/qt6-base-i686.log)

qglobal is unexpected passed. qvector seems like a real problem.

**Comment by skmpz** [comment]
built all the packages with latest changes for
- x86_64 + tests
- i686 + tests
- aarch64 (cross on x86_64)
- armv7l (cross on x86_64)
- x86_64-musl + tests
- aarch64-musl (cross on x86_64-musl)
- armv6l-musl (cross on x86_64-musl)

qt6-websockets and qt6-webengine fail on x86_64 so I didn't move on to build for the other archs. All other packages built fine.

Failed build logs attached
[qt6-base.log](https://github.com/void-linux/void-packages/files/9335091/qt6-base.log)
[qt6-base-i686.log](https://github.com/void-linux/void-packages/files/9335092/qt6-base-i686.log)

**Comment by sgn** [comment]
`tst_qvectornd` passed with `-O0`, that seems like an incorrect optimization to me.

**Pull request closed without merging**
