### PR TITLE
wireguard: add runit service for wg-quick

### PR DESCRIPTION
**Pull request by atweiden**

### CODE REVIEW

**Comment by jnbr** [comment]
> That is kinda useless if you don't include more service files for all possible interface names,

using a conf file likee.g. `dhcpcd` is, makes more sense

> also you need to patch wg-quick so that will run forever instead of exiting after creating the interface, otherwise runit will re-create the interface over and over and will fail consequently after it has been created.

this is prevented by `exec cause`

**Comment by atweiden** [comment]
@jnbr good thinking. Updated with `./conf` file which can be sourced for a configureable `WIREGUARD_INTERFACE`.

@Piraty: `exec pause` takes care of it. I've been using this in [my own setup](https://github.com/atweiden/voidvault/blob/master/doc/guides/wireguard.md) for several days now. Having the runit service is very handy for automatic cleanup of changes to `/etc/dnscrypt-proxy.conf` on system shutdown. It's easy to forget to run `wg-quick down wg0`.

**Comment by CameronNemo** [comment]
You could make it instanced in the same style as agetty.

**Comment by atweiden** [comment]
@Duncaenn Anecdotally, I have `echo 0 > /sys/class/graphics/fbcon/cursor_blink` and `zramen make` (for making a zram swap dev) in my `/etc/rc.local`. Both work independently of any other service. More important, I'm 0% likely to want to "turn off" either setting at any time while my machine is running.

Conversely, I commonly turn wg on or off at a whim. Can't really get that same flexibility from `/etc/rc.local`. In addition, my wg-quick [settings](https://github.com/atweiden/voidvault/blob/master/doc/guides/wireguard.md) reconfigure/restart nftables and dnscrypt-proxy on every wg up/down, and I don't think that'll be too uncommon. It seems like a much better fit for a system service.

**Comment by Piraty** [comment]
Maybe i should apologize for failing to be recognized as being sarcasting.

I don't see what
> automatic cleanup of changes to /etc/dnscrypt-proxy.conf on system shutdown"

has to do with bringing wireguard interfaces up and down. I still favor custom scripts here, until endusers of "vpn-services" that are afraid of leakage can rely on nm-plugins or whatever (when that will have been done someday).

I am *against* providing such dumb "run 1 time and sleep forever" service files, as it makes little difference to making your own logic that does `wg-quick down ... && wg-quick up ...` on your demand. really.
Similar "useless" as the [iptables-service](https://github.com/void-linux/void-packages/blob/67b1585ce1d4731eb52debdd4a704cbedff2f466/srcpkgs/iptables/files/ip6tables/run) that does just the same.

If you implement a runit-service for that, fine with me. But please do not provide such things per default, otherwise we could do that for every other package too.

**Comment by atweiden** [comment]
@Piraty if you want your WireGuard VPN server to forward your DNS, then you need to reconfigure your firewall, as well as dnscrypt-proxy, dnsmasq, or all of the above in order to bring up WireGuard on the server. Changes to kernel parameter settings are also required, see: https://github.com/atweiden/voidvault/blob/master/doc/guides/wireguard.md

With so many other services affected by wg-quick up/down, it is best practice to ensure clean wg teardown is accomplished each time wg is turned off, especially on system shutdown.

If nothing else, it is an illuminating fact that WireGuard ships with a `.service` file (see: `WITH_SYSTEMDUNITS=yes` on Arch Linux):

```systemd
[Unit]
Description=WireGuard via wg-quick(8) for %I
After=network-online.target
Wants=network-online.target
Documentation=man:wg-quick(8)
Documentation=man:wg(8)
Documentation=https://www.wireguard.com/
Documentation=https://www.wireguard.com/quickstart/
Documentation=https://git.zx2c4.com/WireGuard/about/src/tools/man/wg-quick.8
Documentation=https://git.zx2c4.com/WireGuard/about/src/tools/man/wg.8

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/wg-quick up %i
ExecStop=/usr/bin/wg-quick down %i

[Install]
WantedBy=multi-user.target
```

The service here is comparable.

**Comment by Piraty** [comment]
Well, i never doubted you have a legitimate reason to use it that way, but I still don't see what a wg-interface bing-down-bring-up action has to do with all the other software you mentioned...

There just is no benefit over `sv down wg-service && sv up wg-service` over `wg-quick down ... && wg-quick up ...`

Comparing the .service file you mentioned is not wise either, because you might see that the systemd-unit is a template and you can therefore distinctively start/stop specific interfaces each via their discrete "service". that wouldn't be the case for your proposed run file, else you have to replicate them with hardcoded interfaces, which brings us to your custom use-case again (instead of providing a generically useful service file for all void users)

Since i don't call shots here, let's wait for those who do

**Comment by atweiden** [comment]
Forgetting to run `wg-quick down` before turning off your computer is a good reason to have runit manage the service. Maybe `/etc/rc.shutdown` is a good backstop there, but you kill two birds in one stone with a runit service given how frequently wireguard gets turned on and off during normal operation.

```sh
sv up wireguard
# ... normal operation
# shut down your computer, and you know everything's taken care of
sv down wireguard
```

It's maybe why upstream ships a service file for wg-quick...

> Comparing the .service file you mentioned is not wise either, because you might see that the systemd-unit is a template and you can therefore distinctively start/stop specific interfaces each via their discrete "service". that wouldn't be the case for your proposed run file, else you have to replicate them with hardcoded interfaces, which brings us to your custom use-case again (instead of providing a generically useful service file for all void users)

... And? I don't know what kind of service file you're suggesting here, but at this point, you should really write more code and talk a lot less, because you're not making any sense. If you want to supervise wg0 and wg1, `cp -a /etc/sv/wireguard /etc/sv/wireguard-wg1`. It's how dhcpcd's runit service is setup in void-packages.

**Comment by Piraty** [comment]
In my eyes, you failed to provide legitimate reason for your proposed changes. In fact, you didn't even clearly make the point what your use-case of wireguard and dnsproxy has to do with "easily" upping/downing the wg-interface.
Also, as you didn't explain more context, it doesn't make sense why you would want to down the wg-interface on shutdown (machine is off anyway??), nor see the benefit of that dummy service to "supervise" wg-interfaces.

**Pull request closed without merging**
