### PR TITLE
redshift: patch for wayland, AppArmor

### PR DESCRIPTION
**Pull request by CameronNemo**
I like to think there is a little something for everybody in here.

### CODE REVIEW

**Comment by maxice8** [comment]
With that it will work on all wayland wlroots compositors ones that support the same protocol ?

**Comment by CameronNemo** [comment]
Yes indeed! See https://github.com/jonls/redshift/pull/704

**Comment by Cogitri** [comment]
Why not wait for upstream to merge this?

**Comment by CameronNemo** [comment]
@Cogitri yeah, not sure when upstream is going to merge and release, figured people may be interested considering that sway 1.0 is out.

**Comment by Cogitri** [comment]
Ah, alright

**Comment by ericonr** [comment]
Heh, thanks for the patch! Do you think we could talk to this guy https://github.com/minus7/redshift/tree/wayland about releasing a version in their repo? It'd be great to have that actually packaged.

**Comment by CameronNemo** [comment]
I have actually been thinking about forking. I have merged quite a few fixes into this branch https://github.com/CameronNemo/redshift/commits/master

**Comment by ericonr** [comment]
Are all of those fixes integrated into the current package?

**Comment by CameronNemo** [comment]
Not at all. Current template is unpatched.

**Comment by jnbr** [comment]
I'm against adding patches adding functionality.

> I have actually been thinking about forking.

If upstream isn't accepting your patches or is not moving at all, please do so.
Adding large amount of patches into void-packages is not sustainable in the long term.

**Comment by ericonr** [comment]
@CameronNemo if you do fork it and have a definitive template for it, add `/etc/apparmor.d/local/usr.bin.redshift` as a `conf_files`.

**Comment by CameronNemo** [comment]
#23

**Pull request closed without merging**
