### PR TITLE
WIP: podman: update to 1.9.0

### PR DESCRIPTION
**Pull request by Eluminae**

### CODE REVIEW

**Comment by Eluminae** [comment]
Used WIP cause it seems there is a bug

**Comment by Gottox** [comment]
See containers/libpod#5874 for the upstream bug

**Comment by ocroz** [comment]
Meanwhile the issue [https://github.com/containers/libpod/issues/5874](https://github.com/containers/libpod/issues/5874) is still opened, how can we downgrade podman to 1.8.2 ?
Following the [install](https://podman.io/getting-started/installation.html) instructions, the [Kubic project](https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable) seems only to provide the latest version 1.9.0.

**Comment by Eluminae** [comment]
> how can we downgrade podman to 1.8.2 ?

Just install back the repository version. It is probably not prod proof but it worked for me.

**Comment by ocroz** [comment]
> Just install back the repository version

How do we do that?

I am using this repository link:
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/devel:kubic:libcontainers:stable.repo
How can I select another repository version?

**Comment by Eluminae** [comment]
This issue is about updating the VoidLinux package repository. If you updated podman using this MR just

$ xbps-remove podman
$ xbps-install podman

to reinstall the remote repository version, which is 1.8.2

I think this is not your case and your question is out of context here

**Comment by Eluminae** [comment]
1.9.2 does not have the bug anymore.

Closed in favor of https://github.com/void-linux/void-packages/pull/21947

**Comment by Piraty** [comment]
please don't close+open PRs for the same package, just update the template and force-push to your branch

**Pull request closed without merging**
