### PR TITLE
New package: msgraph-0.2.1, uhttpmock: update to 0.10.0

### PR DESCRIPTION
**Pull request by fanyx**
#### Testing the changes
- I tested the changes in this PR: **NO**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

Needed by `gvfs-1.54.0` (https://github.com/void-linux/void-packages/pull/49428)

### CODE REVIEW

**Comment by fanyx** [comment]
reading the error messages, i assume this cannot be built for archs other than `x86*`

https://gitlab.archlinux.org/archlinux/packaging/packages/msgraph/-/blob/main/PKGBUILD?ref_type=heads#L12
Arch also only build it for x86_64

**Comment by classabbyamp** [comment]
> Arch also only build it for x86_64

arch only exists (officially) for x86_64

**Comment by cinerea0** [comment]
I've been working on this offline over the past week, just opened a PR here: https://github.com/void-linux/void-packages/pull/49482. It builds properly for all architectures, but you have to disable docs on cross. I'll just close this one.

**Comment by fanyx** [comment]
Ohhh, absolutely missed your one.
only got active with gnome a few days ago, so thanks for letting me know

I'll try rebuilding goa using your pr

**Pull request closed without merging**
