### PR TITLE
[NOMERGE] glibc: update to 2.31.

### PR DESCRIPTION
**Pull request by ailiop-git**

### CODE REVIEW

**Comment by jnbr** [comment]
```
* System call wrappers for time system calls now use the new time64
  system calls when available. On 32-bit targets, these wrappers
  attempt to call the new system calls first and fall back to the
  older 32-bit time system calls if they are not present.  This may
  cause issues in environments that cannot handle unsupported system
  calls gracefully by returning -ENOSYS. Seccomp sandboxes are
  affected by this issue.
```

We should check if this affects chromium or firefox on i686 before merging.

**Comment by ailiop-git** [comment]
I just noticed sshd breaking due to this upgrade, so please hold off merging.

**Comment by ailiop-git** [comment]
> I just noticed sshd breaking due to this upgrade, so please hold off merging.

The sshd is breaking due to its seccomp filter not explicitly allowing the clock_nanosleep and clock_nanosleep_time64 syscalls which are being called due to glibc commit 2e44b10b42 ("sysdeps/clock_nanosleep: Use clock_nanosleep_time64 if avaliable"), so logins fail as the child process is being killed.

This is fixed in openssh upstream with commit b1c82f4b ("seccomp: Allow clock_nanosleep() in sandbox."), which will be part of the next release (see also [1]). 

I've backported this for now, but I'm afraid that this means there will be many other packages breaking due to using seccomp sandboxes (note that this is especially valid on 64-bit archs, as glibc is now invoking clock_nanosleep_time64 which has a different syscall nr).

There's also at least one other issue, glibc 2.31 has removed the __glibc_has_include macro (commit bfa864e164 ("Don't use a custom wrapper macro around __has_include (bug 25189)."), and this breaks compilation of sources that include stat.h/statx.h, as gcc does fixincludes on those headers (it will use the gcc fixed-up /usr/lib/gcc/x86_64-unknown-linux-gnu/9.2/include-fixed/bits/statx.h while glibc-2.31 has removed the macro, and fail). See also [2], this seems to be in progress with gcc upstream.

[1] https://bugzilla.mindrot.org/show_bug.cgi?id=3093
[2] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91085

**Comment by jnbr** [comment]
Besides that, the entries in `common/shlibs` should be updated.

**Comment by schnitzeltony** [comment]
Background: Am not using void-linux but it is always a source of inspiration when it comes to trouble with musl. This is an kind of thank you.

For 32bit-targets / glibc >=2.31 / chromium I created a fix [1] - maybe it helps here either

[1] https://github.com/OSSystems/meta-browser/blob/master/recipes-browser/chromium/files/0003-Fix-sandbox-Aw-snap-for-syscalls-403-and-407.patch

**Comment by pullmoll** [comment]
Hi @schnitzeltony *wink* Thank you for this payback.

P.S.: Long live Space Attack *lol*

**Comment by ailiop-git** [comment]
thanks, I haven't had the time to look more into this, but one of the issues is that we don't know which other packages this change may break. 

One idea could be to scan all binaries on the repo side by dumping their debug symbols and checking for usage of nanosleep/seccomp/prctl, and narrow it down to those pkgs so that we can check them before upgrading.

There's also the second issue mentioned above with the gcc fixincludes and statx headers, that I haven't check yet if it was resolved upstream.

**Comment by ericonr** [comment]
@ailiop-git if you need to scan a whole repo, https://github.com/void-linux/xmandump does it already for man pages, and should be faster than a shell for at least part of the tasks.

**Comment by kernle32dll** [comment]
Anyone up to working on this?

**Comment by ericonr** [comment]
glibc 2.32 removed SunRPC. We have a couple of packages that from what I can see depend on it, since `libtirpc` was added only on musl. @q66 this is probably of interest to you.

At least:

- xorg-server
- conntrack-tools
- open-vm-tools (doesn't depend on libtirpc on glibc)

**Comment by leahneukirchen** [comment]
Will be done as part of #24258.

**Pull request closed without merging**
