### PR TITLE
chafa: update to 1.12.3

### PR DESCRIPTION
**Pull request by UltimateNyn**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-musl)

### CODE REVIEW

**Comment by tranzystorek-io** [comment]
Consider my changes as well from here https://github.com/tranzystorek-io/void-packages/blob/fastfetch/srcpkgs/chafa/template to enable man pages and some additional capabilities

**Comment by UltimateNyn** [comment]
@tranzystorek-io added it. Why did you add ``xmlcatmgr`` as host dependency? I got the manpage and SVG/WebP support without adding it

**Comment by tranzystorek-io** [comment]
The configure script seems to check for the `/etc/xml/catalog/` file that this provides, but if it works without it then SGTM

**Comment by tranzystorek-io** [comment]
Ah, I see, `docbook` depends on `xmlcatmgr` so it gets pulled in implicitly. I wish chafa's README explained manpage generation instead of us having to blindly check around 😤

**Comment by tranzystorek-io** [comment]
Also @UltimateNyn these changes don't warrant sepparate commits, you should squash them into the original commit and keep `revision=1` instead

**Comment by UltimateNyn** [comment]
I would wait for a maintainer to decide, if the commits should be squashed since every commit is descriptive in what it does

**Comment by classabbyamp** [comment]
they should be squashed, as the contributing guidelines say

**Pull request merged**
