### PR TITLE
python3-neovim: update to version 0.4.1

### PR DESCRIPTION
**Pull request by fivestang**

### CODE REVIEW

**Comment by Piraty** [comment]
please squash it into one commit

**Comment by fivestang** [comment]
Please advise on how this is to be done.

**Comment by Piraty** [comment]
@fivestang : https://lmddgtfy.net/?q=git%20squash%20commit

**Comment by Piraty** [comment]
please make the commit message conform [CONTRIBUTING.md](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md)

**Comment by Piraty** [comment]
53993c52ec6764933b6a0ae674ce43b24d48ec6a

**Pull request closed without merging**
