### PR TITLE
scheme48: Enabling cross compilation.

### PR DESCRIPTION
**Pull request by rc-05**

### CODE REVIEW

**Comment by Anachron** [comment]
Please merge your commits.

**Comment by Chocimier** [comment]
Still fails. Did it pass for you locally? https://travis-ci.org/void-linux/void-packages/jobs/559492465

**Comment by Anachron** [comment]
Please read about how to squash your commits.

https://gist.github.com/patik/b8a9dc5cd356f9f6f980

**Comment by Chocimier** [comment]
Well, he was asked to merge and he merged. ;)

There is also `git rebase HEAD~9 -i` then `fixup` way.

**Comment by rc-05** [comment]
I'm working on correcting some mistakes with the merge conflicts

**Pull request closed without merging**
