### PR TITLE
obs: depend on v4l2loopback for virtual camera support

### PR DESCRIPTION
**Pull request by larsgrah**
#### Testing the changes
- I tested the changes in this PR: **YES**

This dependency enables virtual camera support

### CODE REVIEW

**Comment by lemmi** [comment]
I'm not a fan of including `v4l2loopback` as a dependency. Since it is a `dkms` module, it pulls in a whole bunch of other stuff like `gcc` and `linux-headers` that not everybody necessarily needs. Also installing `v4l2loopback` alone won't magically make virtual cam work. You still need to load the module and configure it. At that point you already need to know enough that I would assume installing a package manually shouldn't be too hard a task. 
At the moment this doesn't have my support, but I'm open hearing other opinions.

**Comment by larsgrah** [comment]
Not entirely sure what you mean, when installing v4l2loopback the modues got configured automatically for me. In what setup would that not work? After starting obs after installing it, virtual camera worked ootb

**Comment by larsgrah** [comment]
Hm, unfortunately i cannot reproduce your experience. Currently unsure why it would not be loaded after being installed.

FWIW https://bugs.archlinux.org/task/69918 on arch it is included

**Comment by lemmi** [comment]
Sadly we don't have optional dependencies, it would definitely be the right use case here. Maybe upstream could be convinced to display an error or hint that the module needs to be installed and loaded for virtual cam to work. Most we can do is display an install message, but I doubt it has the necessary visibility to justify the added spam.
For the moment I considered this closed. Still, thank your for your effort.

**Pull request closed without merging**
