### PR TITLE
New package: telegram-cli-20200106

### PR DESCRIPTION
**Pull request by timmykill**

### CODE REVIEW

**Comment by Noah-Huppert** [comment]
Built recently and I needed to add `tar` to the `hostmakedepends`: [`telegram-cli-fix-build.patch`](https://gist.github.com/Noah-Huppert/b40b93edb66ab1417ffa99f23c837319/raw/c663083aec6a25919f54cc869cb6d9c1adf9754f/telegram-cli-fix-build.patch)

**Comment by ericonr** [comment]
Having a specific `libcrypto` in `hostmakedepends` is very wrong. `libressl-devel` will pull the version it depends on by itself.

I'm closing this for inactivity, feel free to reopen :) 

@jcgruenhage if you want to take over the PR, feel free as well.

**Comment by jcgruenhage** [comment]
@ericonr you sure you meant me? Not sure what I got to do with this :D

**Comment by ericonr** [comment]
oops, sorry! I meant @Noah-Huppert !

**Pull request closed without merging**
