### PR TITLE
virtualbox-ose: update to 7.0.8

### LINKED ISSUE #44040: virtualbox-ose-dkms 7.0.6 fails to build
### Is this a new report?

Yes

### System Info

Void 6.3.3_1 x86_64 AuthenticAMD uptodate hold rrrrmdFFFFFFFFF

### Package(s) Affected

virtualbox-ose-dkms-7.0.6_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

_No response_

### Expected behaviour

$ xbps-install virtualbox-ose-dkms
is expected to build the dkms module succesfully

### Actual behaviour

$ xbps-install virtualbox-ose-dkms
...
Building DKMS module 'virtualbox-ose-7.0.6' for kernel-6.3.3_1... FAILED!
DKMS module 'virtualbox-ose-7.0.6' failed to build, please check /var/lib/dkms
for errors in the log file.
virtualbox-ose-dkms-7.0.6_1: installed successfully.

$ cat make.log
```
DKMS make.log for virtualbox-ose-7.0.6 for kernel 6.3.3_1 (x86_64)
Tue May 23 01:02:27 PM EEST 2023
make: Entering directory '/usr/src/kernel-headers-6.3.3_1'
  CC [M]  /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxnetadp/linux/VBoxNetAdp-linux.o
  CC [M]  /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv/linux/SUPDrv-linux.o
  CC [M]  /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxnetflt/linux/VBoxNetFlt-linux.o
  CC [M]  /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxnetadp/VBoxNetAdp.o
  CC [M]  /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv/SUPDrv.o
  CC [M]  /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxnetflt/VBoxNetFlt.o
  CC [M]  /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv/SUPDrvGip.o
  CC [M]  /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxnetflt/SUPR0IdcClient.o
  CC [M]  /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxnetflt/SUPR0IdcClientComponent.o
  CC [M]  /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxnetflt/linux/SUPR0IdcClient-linux.o
  CC [M]  /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv/SUPDrvSem.o
  LD [M]  /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxnetadp/vboxnetadp.o
  CC [M]  /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv/SUPDrvTracer.o
  CC [M]  /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv/SUPLibAll.o
  CC [M]  /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv/common/string/strformatrt.o
  CC [M]  /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv/combined-agnostic1.o
  LD [M]  /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxnetflt/vboxnetflt.o
  CC [M]  /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv/combined-agnostic2.o
  CC [M]  /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv/combined-os-specific.o
/var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv/SUPDrvTracer.o: warning: objtool: SUPR0TracerFireProbe+0x7: indirect jump found in RETPOLINE build
/var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv/SUPDrvTracer.o: warning: objtool: supdrvTracerProbeFireStub+0x0: 'naked' return found in RETHUNK build
/var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv/SUPDrvTracer.o: warning: objtool: SUPR0TracerFireProbe+0x7: missing int3 after indirect jump
/var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv/SUPDrvTracer.o: warning: objtool: supdrvTracerProbeFireStub+0x0: missing int3 after ret
In file included from /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv/combined-os-specific.c:43:
/var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv/r0drv/linux/memobj-r0drv-linux.c: In function 'rtR0MemObjNativeLockUser':
/var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv/r0drv/linux/memobj-r0drv-linux.c:1404:39: error: assignment of read-only member 'vm_flags'
 1404 |                 papVMAs[rc]->vm_flags |= VM_DONTCOPY | VM_LOCKED;
      |                                       ^~
/var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv/r0drv/linux/memobj-r0drv-linux.c: In function 'rtR0MemObjNativeMapUser':
/var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv/r0drv/linux/memobj-r0drv-linux.c:1876:35: error: assignment of read-only member 'vm_flags'
 1876 |                     vma->vm_flags |= VM_DONTEXPAND | VM_DONTDUMP;
      |                                   ^~
make[2]: *** [scripts/Makefile.build:252: /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv/combined-os-specific.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [scripts/Makefile.build:494: /var/lib/dkms/virtualbox-ose/7.0.6/build/vboxdrv] Error 2
make: *** [Makefile:2025: /var/lib/dkms/virtualbox-ose/7.0.6/build] Error 2
make: Leaving directory '/usr/src/kernel-headers-6.3.3_1'

```

### Steps to reproduce

$ xbps-install virtualbox-ose-dkms

### PR DESCRIPTION
**Pull request by nezos**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-LIBC)

Fixes #44040 (the build of DKMS for linux kernel 6.3.3)

### CODE REVIEW

**Comment by classabbyamp** [comment]
this should be a single commit for the changes to the package and a commit for the changes to shlibs. i would recommend not using the web interface

**Comment by nezos** [comment]
> this should be a single commit for the changes to the package and a commit for the changes to shlibs. i would recommend not using the web interface

Do you want me to close and open a new pull request or is it ok for this time?

**Comment by classabbyamp** [comment]
Don't make a new PR, just fix the commits locally and force push to the branch

**Comment by sgn** [comment]
Pushed

**Pull request closed without merging**
