### PR TITLE
anydesk eula changed

### PR DESCRIPTION
**Pull request by MrFastDie**
The hash for the anydesk eula changed to 6e638faec127a59a7f43027d656d124fcb214a02044667b88ec9de7449dd82a5

### CODE REVIEW

**Comment by ericonr** [comment]
`=> ERROR: EULA changed, new digest: 32e6f0aad35f9df2aca67415460b7faf9adb4a7c9c4e60010bed109034edc61f`

This doesn't seem to be stable anymore? Given that the package is restricted, I would consider removing the EULA entirely.

**Comment by ericonr** [comment]
The build will now fail in the `vlicense` line.

**Comment by MrFastDie** [comment]
I tested the run the `./xbps pkg anydesk` finished flawless - also I understand the `vlicense` line as copying the license to the desired folder (and the eula still got downloaded in the `post_install()` ) - But now I removed the postinstall and the vlicense and the project still works. I don't know if we dont want to have the eula or not - but as suggested I got the vlicense out.

**Comment by sgn** [comment]
I oppose the decision to remove `vlicense eula`. I don't think playing politic game is safe.

**Comment by MrFastDie** [comment]
> I oppose the decision to remove `vlicense eula`. I don't think playing politic game is safe.

So which of the three resolutions do we want to have?

**Comment by ericonr** [comment]
My reasoning is that removing the EULA is ok, because it's a restricted package. Since it isn't versioned, it breaks the build regularly, and fetching it without a checksum feels kinda dirty.

Removing the EULA is the simplest solution to keep it in repo.

But if you prefer to keep it in, feel free. Removing the EULA isn't ideal, just a compromise I was ok with.

**Comment by sgn** [comment]
https://github.com/void-linux/void-packages/commit/550b51c2d7205cef97cc7113e6914f1ab85985d9

**Pull request closed without merging**
