### PR TITLE
librime: update to 1.11.2.

### PR DESCRIPTION
**Pull request by Vinfall**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc

Did not test fcitx-rime since last time I tried it's already broken.

### CODE REVIEW

**Comment by sgn** [comment]
Why do we need to rebuild?

> Did not test fcitx-rime since last time I tried it's already broken.

how?

**Comment by Vinfall** [comment]
> Why do we need to rebuild?

For brise, it's recommended in the template (although I think we should definitely migrate to [plum](https://github.com/rime/plum/blob/master/README.md#install-as-shared-data) since brise is deprecated for a long time). ibus-rime is rebuilt just in case as I'm not sure how lua support is updated in rime.

> how?

It was last month so I can't remember clearly, but the setup won't run due to lua support or whatever. (I only recognized later that archived [fcitx-rime](https://github.com/fcitx/fcitx-rime) and [fcitx5-rime](https://github.com/fcitx/fcitx5-rime) are different, and I'm not sure which one I tried then).

Either way, current librime is rather old and since updating it does not affect the functionality of (deprecated) ibus-rime, it should get updated. brise -> plum migration & fcitx-rime/fcitx5-rime update are just a bonus I did not take.

**Comment by sgn** [comment]
> > Why do we need to rebuild?
> 
> For brise, it's recommended in the template (although I think we should definitely migrate to [plum](https://github.com/rime/plum/blob/master/README.md#install-as-shared-data) since brise is deprecated for a long time). ibus-rime is rebuilt just in case as I'm not sure how lua support is updated in rime.

You mean this?

    # And the binary files will be recompiled if librime is updated.

No, that's for:
```
# NOTE: don't run either:
#	make preset-bin
#	make all-bin
#	rime_deployer --build output
```

> It was last month so I can't remember clearly, but the setup won't run due to lua support or whatever. (I only recognized later that archived [fcitx-rime](https://github.com/fcitx/fcitx-rime) and [fcitx5-rime](https://github.com/fcitx/fcitx5-rime) are different, and I'm not sure which one I tried then).

OK, I will remove all fcitx v4 then. Please try with `fcitx5-rime`

> Either way, current librime is rather old and since updating it does not affect the functionality of (deprecated) ibus-rime, it should get updated. brise -> plum migration & fcitx-rime/fcitx5-rime update are just a bonus I did not take.

OK!

**Comment by Vinfall** [comment]
> You mean this?

Yes, so it's just a misread I guess. I'll try fcitx5-rime this week.

**Comment by Vinfall** [comment]
> how?

It turns out to be Wayland or SwayWM's fault (text-input-v2 or text-input-v3 support, specifically). I've been back to X11 so everything works fine.

> I'll try fcitx5-rime this week.

Fcitx5-rime 5.1.8 works fine with librime-1.11.2 so I'm updating it as well in this PR.

However, I'm not sure about the proper way to update fcitx5 IME. Looking back at [your commit history](https://github.com/void-linux/void-packages/commits/master/srcpkgs?author=sgn&since=2024-05-21&until=2024-05-23), the versions seem to match the ones mentioned in [fictx5 release note](https://github.com/fcitx/fcitx5/releases/tag/5.1.9). Maybe fcitx5 itself should be updated before this? It should be fine to bump only fcitx5-rime though.

**Pull request closed without merging**
