### PR TITLE
hackrf: fix udev rules directory

### PR DESCRIPTION
**Pull request by motorto**
#### Testing the changes
- I tested the changes in this PR: **NO**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - armv6l

[39083](https://github.com/void-linux/void-packages/issues/39083)

### CODE REVIEW

**Comment by Piraty** [comment]
ping @bra1nwave .

**Comment by Piraty** [comment]
before
```
xbps-query -Rf libhackrf | grep udev
/usr/lib/udev/rules.d/53-hackrf.rules

xbps-query -Rf hackrf | grep udev

```

after
```
fd -t f rules masterdir/destdir
masterdir/destdir/hackrf-2021.03.1/usr/lib/udev/rules.d/53-hackrf.rules
```

**Comment by motorto** [comment]
I moved the udev rule from the libpackage because it would conflict (it seemed that both packages installed the same file).

In my opinion if the main package installs it then, there isn't a point on the lib package to have the same udev rule (pretty sure previously the rule was duplicate just in different directories)

**Comment by classabbyamp** [comment]
I think it makes more sense to keep this in the lib package, because someone who links against libhackrf for hackrf support in their app should have those rules so that users of the app can access the device properly. the `vinstall` can be replaced with `vmove` i think

**Comment by Piraty** [comment]
it should be in the lib package. no need to change the template as it installs to the right path already.

**Comment by motorto** [comment]
@Piraty how to solve the file conflict between the `hackrf` and `libhackrf_package` on the udev_rule ?

@classabbyamp could you specify the vinstall, the one in `libhackrf_package` ?

**Comment by Piraty** [comment]
```
diff --git a/srcpkgs/hackrf/template b/srcpkgs/hackrf/template
index 9e756967f4..397efa95a0 100644
--- a/srcpkgs/hackrf/template
+++ b/srcpkgs/hackrf/template
@@ -4,6 +4,7 @@ version=2021.03.1
 revision=1
 build_wrksrc=host
 build_style=cmake
+configure_args="-DUDEV_RULES_PATH=/usr/lib/udev/rules.d/"
 hostmakedepends="pkg-config"
 makedepends="libusb-devel fftw-devel"
 _desc="Low cost software defined radio (SDR) platform"
@@ -28,7 +29,7 @@ libhackrf_package() {
 	short_desc="${_desc} - library"
 	pkg_install() {
 		vmove usr/lib/*.so.*
-		vinstall libhackrf/53-hackrf.rules 644 usr/lib/udev/rules.d/
+		vmove usr/lib/udev/rules.d
 	}
 }
```

**Comment by classabbyamp** [comment]
the previously-installed rules with the `vsed` made it so only elogind users could use the udev rules. The now-installed rules only work with the `plugdev` group (and the `vsed` did nothing useful), this patch fixes that.

This should also be upstreamed, I think.

template change:
```diff
diff --git a/srcpkgs/hackrf/template b/srcpkgs/hackrf/template
index 397efa95a0..f47857bada 100644
--- a/srcpkgs/hackrf/template
+++ b/srcpkgs/hackrf/template
@@ -12,13 +12,9 @@ short_desc="${_desc} - tools"
 maintainer="Orphaned <orphan@voidlinux.org>"
 license="GPL-2.0-or-later"
 homepage="https://greatscottgadgets.com/hackrf/"
-distfiles="https://github.com/mossmann/hackrf/releases/download/v${version}/${pkgname}-${version}.tar.xz"
+distfiles="https://github.com/greatscottgadgets/hackrf/releases/download/v${version}/${pkgname}-${version}.tar.xz"
 checksum=a43e5080c11efdfe69ddebcc35a02b018e30e820de0e0ebdc7948cf7b0cd93a3
 
-pre_configure() {
-	vsed -i 's|MODE="660", GROUP="plugdev"|TAG+="uaccess"|g' libhackrf/53-hackrf.rules
-}
-
 post_install() {
 	for f in ../firmware-bin/*.{bin,dfu}; do
 		vinstall "$f" 644 usr/share/hackrf/
```
patch:
```diff
enable device access via elogind

--- a/host/libhackrf/53-hackrf.rules.in
+++ b/host/libhackrf/53-hackrf.rules.in
@@ -1,13 +1,13 @@
 # HackRF Jawbreaker
-ATTR{idVendor}=="1d50", ATTR{idProduct}=="604b", SYMLINK+="hackrf-jawbreaker-%k", MODE="660", GROUP="@HACKRF_GROUP@"
+ATTR{idVendor}=="1d50", ATTR{idProduct}=="604b", SYMLINK+="hackrf-jawbreaker-%k", MODE="660", GROUP="@HACKRF_GROUP@", TAG+="uaccess"
 # HackRF One
-ATTR{idVendor}=="1d50", ATTR{idProduct}=="6089", SYMLINK+="hackrf-one-%k", MODE="660", GROUP="@HACKRF_GROUP@"
+ATTR{idVendor}=="1d50", ATTR{idProduct}=="6089", SYMLINK+="hackrf-one-%k", MODE="660", GROUP="@HACKRF_GROUP@", TAG+="uaccess"
 # rad1o
-ATTR{idVendor}=="1d50", ATTR{idProduct}=="cc15", SYMLINK+="rad1o-%k", MODE="660", GROUP="@HACKRF_GROUP@"
+ATTR{idVendor}=="1d50", ATTR{idProduct}=="cc15", SYMLINK+="rad1o-%k", MODE="660", GROUP="@HACKRF_GROUP@", TAG+="uaccess"
 # NXP Semiconductors DFU mode (HackRF and rad1o)
-ATTR{idVendor}=="1fc9", ATTR{idProduct}=="000c", SYMLINK+="nxp-dfu-%k", MODE="660", GROUP="@HACKRF_GROUP@"
+ATTR{idVendor}=="1fc9", ATTR{idProduct}=="000c", SYMLINK+="nxp-dfu-%k", MODE="660", GROUP="@HACKRF_GROUP@", TAG+="uaccess"
 # rad1o "full flash" mode
-KERNEL=="sd?", SUBSYSTEM=="block", ENV{ID_VENDOR_ID}=="1fc9", ENV{ID_MODEL_ID}=="0042", SYMLINK+="rad1o-flash-%k", MODE="660", GROUP="@HACKRF_GROUP@"
+KERNEL=="sd?", SUBSYSTEM=="block", ENV{ID_VENDOR_ID}=="1fc9", ENV{ID_MODEL_ID}=="0042", SYMLINK+="rad1o-flash-%k", MODE="660", GROUP="@HACKRF_GROUP@", TAG+="uaccess"
 # rad1o flash disk
-KERNEL=="sd?", SUBSYSTEM=="block", ENV{ID_VENDOR_ID}=="1fc9", ENV{ID_MODEL_ID}=="0082", SYMLINK+="rad1o-msc-%k", MODE="660", GROUP="@HACKRF_GROUP@"
+KERNEL=="sd?", SUBSYSTEM=="block", ENV{ID_VENDOR_ID}=="1fc9", ENV{ID_MODEL_ID}=="0082", SYMLINK+="rad1o-msc-%k", MODE="660", GROUP="@HACKRF_GROUP@", TAG+="uaccess"
 #
```

**Comment by motorto** [comment]
@classabbyamp  still having the same conflict, but thanks for taking the time and fixing the vsed rule !

**Comment by classabbyamp** [comment]
bump the revision and this should be good

**Pull request merged**
