### PR TITLE
New package: SuperSlicer-2.4.58.5

### LINKED ISSUE #39486: Package request: SuperSlicer
### Package name

SuperSlicer

### Package homepage

https://github.com/supermerill/SuperSlicer

### Description

SuperSlicer is an extended fork of PrusaSlicer which adds, among other features, a Klipper GCode flavour. It should be able to re-use the packaging infrastructure, and is a massive pain to compile by hand.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

### PR DESCRIPTION
**Pull request by enderger**
#### Testing the changes
- I tested the changes in this PR: briefly

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture,  x86_64-musl|

Closes #39486

### CODE REVIEW

**Comment by enderger** [comment]
Might need to run the CI

**Comment by enderger** [comment]
Alright, think I fixed the lint. The build failure appears to be a flakey test, as it is failing to download xlocate rather than anything in the PR.

**Comment by enderger** [comment]
Alright, no idea why CI is failing. Xlocate appears to be a part of the packaging system itself, so unless I'm doing something wrong the test might just not be working here.

**Comment by hvraven** [comment]
built and used it successfully on my machine for x86_64. Thanks for the package.

**Pull request closed without merging**
