### PR TITLE
New package: linux5.5-5.5.2 (tested on x86_64).

### PR DESCRIPTION
**Pull request by xtraeme**
This enables X86_UMIP among other things, also restores
TRANSPARENT_HUGEPAGE_MADVISE=y (which was set to
_ALWAYS again, see [1]).

How to know what is the policy to enable or disable
any option? simple: we follow what upstream defaults to, e.g:
if an option is disabled by default (N), we don't enable
it unless it's explicitely required. For any other options
that can be built as modules, we build them as modules.

So the linux kernel configuration that void uses depends
on what upstream sets by default.

For now this only contains working configurations for
x86 and x86_64. People with working hardware should adapt
this configuration to the target arch appropiately.

Built and tested on x86 and x86_64.

[1] https://blog.nelhage.com/post/transparent-hugepages/

[ci skip]

### CODE REVIEW

**Comment by xtraeme** [comment]
@q66 @pullmoll please update the !x86 configs

**Comment by xtraeme** [comment]
It's restricted to be built only for i686 and x86_64. This way we can push this without introducing build failures due to outdated configuration.

**Comment by q66** [comment]
This introduces a bunch of rather questionable changes to the kernel config, like disabling page posioning, restricting CPUs to 64, disabling KASLR, and disabling a class of broadcom wifi drivers, possibly others. How about not merging things like this without undergoing review?

**Comment by xtraeme** [comment]
Feel free to update it, it took me a long while already.

**Comment by xtraeme** [comment]
CPUs is restricted to 64 because this is the default.

I simply used defaults.

**Comment by xtraeme** [comment]
You are talking about "without undergoing review", linux5.4 reverted my change to not enable THP by default, as stated in my commit message. Who reviewed this? obviously nobody.

So I don't think this is worse than that was there before.

**Comment by xtraeme** [comment]
Note that I've used oldconfig and looking at each option one by one.

It took me literally a few hours.

**Comment by q66** [comment]
The existing config was fine as it was already - just take the config from previous version, run oldconfig on it in the new tree, update options that are new/have changed, and possibly change the things you explicitly wanted to change later. There is no need to go through creation of a new config and is likely to do more harm than good.

**Comment by xtraeme** [comment]
@q66 this is what I did.

**Comment by xtraeme** [comment]
If you don't trust me, try yourself with the existing linux5.4 config.

**Comment by q66** [comment]
"You are talking about "without undergoing review", linux5.4 reverted my change to not enable THP by default, as stated in my commit message. Who reviewed this? obviously nobody."

previous mistakes should not justify making them again. Besides, I only call out things I notice problems with, in this case I went to diff the new config against the old one to be able to see what changed so I could use that for the ppc configs.

I don't have an x86_64 machine at hand to test that out, but I had another user on IRC confirm that oldconfig *does not* ask for those things that were changed.

**Comment by q66** [comment]
Anyway, my main point here is that these kinds of things just should not happen, as there should be no rush with introducing any new packages into the repository, so we can take our time; 5.4 is a longterm tree and 5.5 does not introduce anything extremely important.

**Pull request merged**
