### PR TITLE
Intel packages

### PR DESCRIPTION
**Pull request by zlice**
#### Testing the changes
- I tested the changes in this PR: **yes**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, **x86_64**

#### Comments

Packages for Intel DG2/Alchemist/Arc support. Still pending ffmpeg5 largely https://github.com/void-linux/void-packages/pull/36315.

Able to use ffmpeg ~~5.1.2~~ ~~git~~ 4.4 with a A770 encode and these libraries. (ffmpeg5 doesn't install, LD_LIBRARY_PATH and untaring the xbps's to do this)

OneVPL is the successor to IntelMediaSDK (libmfx), but only one of these can be enabled in ffmpeg. Furthermore only latest ffmpeg has OneVPL support.

- ~~igt-gpu-tools~~ (updated to 1.27.1 outside of this PR)
- intel-media-drivers (needed for vaapi on dg2. 22.6.4 works, 22.6.6 does not seem to)
- intel-gmmlib (needed for new intel-media-drivers to compile)
- onevpl (replaces intel-media-sdk - but only available in ffmpeg git)
- onevpl-intel-gpu
- intel-media-sdk
- libmfx (part of intel-media-sdk)
- ffmpeg with mfx for Intel vaapi support

#### Concerns/Questions

- ~~mlt/7 - just prep work for ffmpeg5~~ mlt6 & 7 updated
- onevpl naming ? `intel-onevpl` ? `lib` ?
- libmfx naming ? `intel-libmfx` ?
- mesa 22.3.1 pretty much required for new Intel GPUs https://github.com/void-linux/void-packages/pull/41084

### CODE REVIEW

**Comment by zlice** [comment]
think this is ready, though not really useful yet. lmk what i messed up

**Comment by zlice** [comment]
Re-added libmfx for ffmpeg4 because 5 is clearly going to be a few before it's ready.

**Comment by classabbyamp** [comment]
new packages should be committed as `New package: $pkgname-$version`, and you only need to mention the primary package, not the subpkgs.

updates should be just `$pkgname: update to $version` (not with the word version)

**Comment by zlice** [comment]
So that patch doesn't really fix anything, exported some bad videos. Not sure if the nonfree part of the package should be in the nonfree distro.

Also any tips with the libva-glx conflict?

**Comment by zlice** [comment]
Updating to keep alive. `mlt` was updated in the repo. `gmmlib` and `libva-intel-driver` updated.

**Comment by icp1994** [comment]
imo it makes sense to remove the glx stuff from libva-intel-driver

**Comment by zlice** [comment]
libva-intel-driver seems to build and work fine w/o glx. Still have the problem of needing the non-free intel-media-driver https://github.com/void-linux/void-packages/pull/41132#issuecomment-1359539524 / https://github.com/intel/media-driver/issues/1580

**Comment by icp1994** [comment]
Ah, okay. I mostly meant for the file conflicts.

**Comment by zlice** [comment]
Yep, thanks for the input.

**Comment by Anachron** [comment]
Did someone already test this?

I have a 

```
CPU:    12th Gen Intel(R) Core(TM) i5-1240P (16x)
GPU:    Alder Lake-P Integrated Graphics Controller (i915)
```

setup so I could potentially be testing this, but if I saw it correctly we still have the corruption issue of https://github.com/intel/media-driver/issues/1580 left before we can use this?

**Comment by icp1994** [comment]
Since my comment here, I have updated the relevant intel packages in my laptop (intel-gmmlib, intel-media-driver, and libva-intel-driver) from this pr. I haven't noticed any issues in the last ~4 days with my workflow.

```
CPU: quad core 11th Gen Intel Core i5-1135G7 (-MT MCP-)
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] (i915)
```

**Comment by Anachron** [comment]
FYI:
I'm currently running this PR, so far all well.

**Comment by Anachron** [comment]
Running this for 2+ weeks and its rock solid.

Can we fix the conflict and get this merged?

**Comment by zlice** [comment]
> Running this for 2+ weeks and its rock solid.
> 
> Can we fix the conflict and get this merged?

intel-media-driver still seg-faults for me without non-free drivers. You were using an iGPU, not sure if that would help intel on that issue. Haven't seen an update on it.

**Comment by zlice** [comment]
Hm, see the conflict on libva/libva-intel, didn't notice that before only the glx bit.

**Comment by zlice** [comment]
Actually, if one of you with the iGPU can verify maybe - should `libva-intel-driver` be removed then?

**Comment by icp1994** [comment]
Can confirm, I don't need libva drivers. I din't have it before testing this PR and VA worked fine.

**Comment by zlice** [comment]
There was a fix for the intel-media-driver issue. Seemed to run fine for me so I used that patch (no release yet).

**Comment by zlice** [comment]
I was working on ffmpeg6 to get AV1. 6 seems good and better overall but could just be placebo.

(ffmpeg6 changes the packages in here for oneVPL only and no libmfx)

**Comment by zlice** [comment]
I'm guessing you have these packages installed, do you have `libva` installed?

**Comment by zlice** [comment]
Reading again you said you're running 6.1. I think 6.2 is really needed for A770/DG2 right now. Been running great for me for a few months. Intel's mesa staging and firmware help out a bunch too (though mesa 23 added some RADV option to ignore waits on texture/buffer loads and I get some white flashing. Mainly Discord of all things)

https://github.com/intel-gpu/Mesa/tags

https://github.com/intel-gpu/intel-gpu-firmware

Not needed for these changes, but A770 specifically benefits.

**Comment by zlice** [comment]
https://github.com/void-linux/void-packages/commit/111918317d06598fe1459dbe139923404f3f4b9d

**Comment by zlice** [comment]
There was a ffmpeg update, but I'm running ffmpeg6 atm so I can't really 'test' to verify. No reason things shouldn't work though.

**Comment by Anachron** [comment]
Ohhh, new stuff.

Will compile and test later.

Anything new on the "when is this ready" from? Specifically about any open issues.

**Comment by zlice** [comment]
> Anything new on the "when is this ready" from? Specifically about any open issues.

¯\_(ツ)_/¯ been using it for 6 months. 1 bug concern fixed 3mo ago. switched to ffmpeg6 a month+ ago

**Comment by zlice** [comment]
@anachron how's it working for you?

**Comment by Anachron** [comment]
Wow it's been 2 weeks since you asked me?

I will compile this later and install. Sorry for the delay.

**Comment by zlice** [comment]
Would this be able to be re-opened or should I make a new PR ?

Has been floating for almost a year now. Not sure if anyone has updated or used libmfx. I have been using ffmpeg6 and onevpl

**Comment by mdkcore0** [comment]
> Would this be able to be re-opened or should I make a new PR ?
> 
> Has been floating for almost a year now. Not sure if anyone has updated or used libmfx. I have been using ffmpeg6 and onevpl

I'm quite interested, as `sunshine` uses newer versions of ffmpeg, and void still having ffmpeg4 (and I'm trying to build sunshine folling this PR https://github.com/void-linux/void-packages/pull/47417, using their ffmpeg instead of the system one)

**Pull request closed without merging**
