### PR TITLE
nnn: update to 3.6.

### PR DESCRIPTION
**Pull request by UsernameRandomlyGenerated**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by FollieHiyuki** [comment]
Would it be possible to split `nnn` into 3 packages to support icons?
Like so: `nnn`, `nnn-nerd` and `nnn-icons`. Just different flags when compiling

**Comment by UsernameRandomlyGenerated** [comment]
> Would it be possible to split `nnn` into 3 packages to support icons?
> Like so: `nnn`, `nnn-nerd` and `nnn-icons`. Just different flags when compiling

I think it should be up to maintainer, but in my opinion I think enabling icons by default is better than splitting package, as it's just a flag that doesn't require any new dependencies by itself.

**Comment by FollieHiyuki** [comment]
> I think it should be up to maintainer, but in my opinion I think enabling icons by default is better than splitting package, as it's just a flag that doesn't require any new dependencies by itself.

I suggest we do like those `emacs` packages.

Any way the flags are `O_ICONS=1` (use `icons-in-terminal` dependency) and `O_NERD=1` (need a nerd font). I think they are conflicting, hence icons is not enable in default build.

**Comment by tibequadorian** [comment]
>I think it should be up to maintainer

The maintainer isn't maintaining the package :D you can adopt or orphan it

**Comment by tibequadorian** [comment]
> Would it be possible to split `nnn` into 3 packages to support icons?
> Like so: `nnn`, `nnn-nerd` and `nnn-icons`. Just different flags when compiling

I would prefer `build_options`

**Comment by sgn** [comment]
What happens if ICONS is enabled but not available? If nothing broken, just enable it unconditionally.
Anyway, please disable `-O3` (`CFLAGS_OPTIMIZATION=-O2`)

**Comment by FollieHiyuki** [comment]
Oh we don't have `icons-in-terminal` in the repo, so just go with the "using Nerd font" option. I will try to see whether enabling the feature without having a patched font works

**Comment by UsernameRandomlyGenerated** [comment]
Please check it if you can, you can also take over updating if you want, I'm on limited data so downloading huge nerd font for tests is impossible for me right now.

**Comment by FollieHiyuki** [comment]
@UsernameRandomlyGenerated you don't need to download the whole package. Downloading 1 font from their github is enough.
Anyways, if icons is enabled without setting your terminal font to a Nerd font, `nnn` will try to find the glyphs with other fonts, and the icons will look weird.
So if we go with the `build_options`, disable icons by default. I still want a separated package though.

**Comment by tibequadorian** [comment]
Why hasn't this been merged? The fonts are in no relation to the update...

**Pull request closed without merging**
