### PR TITLE
New package: dnscontrol-2.9

### PR DESCRIPTION
**Pull request by ScOut3R**

### CODE REVIEW

**Comment by Hoshpak** [comment]
Seems to have issues with 32 bit architectures.

**Comment by ScOut3R** [comment]
@Hoshpak is it acceptable to limit the package to 64 bit only?

**Comment by Hoshpak** [comment]
It would be better if upstream fixed the issue but marking it as broken for now would be acceptable. Ypu can use `XBPS_WORDSIZE` to select for 32 bit architectures.

**Comment by ScOut3R** [comment]
@Hoshpak I've added the `archs` option to the template. Is this an acceptable solution for now?

**Comment by pullmoll** [comment]
I think @Hoshpak thought along the lines
```
if [ "$XBPS_WORDSIZE" -ne 64 ]; then
        broken="Compiles only for 64 bit architectures."
fi
```
This would allow to build the package for e.g. `aarch64`, `ppc64`, and `ppc64le`, if that makes sense.

**Comment by ScOut3R** [comment]
I'm closing this PR ans will open a new one eventually with the most recent version.

**Pull request closed without merging**
