### PR TITLE
rpi-imager: update to 1.6.

### PR DESCRIPTION
**Pull request by agausmann**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by Piraty** [comment]
is there a way you can address the telemetry issue?

**Comment by FollieHiyuki** [comment]
```
/* Phone home the name of images downloaded for image popularity ranking */
#define TELEMETRY_URL                     "https://rpi-imager-stats.raspberrypi.org/downloads"
#define TELEMETRY_ENABLED_DEFAULT         true
```
I think we can patch their `config.h` to redirect to localhost and turn it off by default.

**Comment by sgn** [comment]
On 2021-03-16 09:24:51-0700, FollieHiyuki ***@***.***> wrote:
> ```
> /* Phone home the name of images downloaded for image popularity ranking */
> #define TELEMETRY_URL                     "https://rpi-imager-stats.raspberrypi.org/downloads"
> #define TELEMETRY_ENABLED_DEFAULT         true
> ```
> I think we can patch their `config.h` to redirect to localhost and turn it off by default.

How about 0.0.0.0? Send them to a black holes instead.

-- 
Danh

**Comment by agausmann** [comment]
I'm fine with disabling telemetry by default, but I'd rather not functionally break it. AFAIK that isn't done to other packages with telemetry, for example Firefox.

It's open source, so it's entirely transparent about what data it collects. Plus there is an [official disclosure](https://github.com/raspberrypi/rpi-imager#telemetry) that we can copy to a prominent location if that would help.

**Comment by Piraty** [comment]
let's switch it to opt-in but not break it

**Pull request merged**
