### PR TITLE
wget: update to 1.21.

### PR DESCRIPTION
**Pull request by ulfw2020**
adopt

### CODE REVIEW

**Comment by ulfw2020** [comment]
Apologies, I accidentally closed the pull request.

**Comment by NeelChotai** [comment]
Conflicts with #27603.

**Comment by ulfw2020** [comment]
> Conflicts with #27603.

Didn't see yours, have you adopted the package?

**Comment by ericonr** [comment]
There wasn't any maintainer change here, so the PR has been superseded by #27603 

Feel free to open a separate PR if you wish to adopt the pacakge (which involves changing the `maintainer` field)

**Pull request closed without merging**
