### PR TITLE
New package: lean-3.4.2

### PR DESCRIPTION
**Pull request by Eloitor**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (ARCH-LIBC)
- [ ] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [ ] aarch64-musl
  - [ ] armv7l
  - [ ] armv6l-musl

### CODE REVIEW

**Comment by ericonr** [comment]
IRC suggestion to name this lean3, since 4 is supposedly coming out soon.

**Comment by Chocimier** [comment]
Is there a reason to use this over maintained lean-community?

**Comment by Eloitor** [comment]
> Is there a reason to use this over maintained lean-community?

Not really. This is my first template that I try to write, and I got recommended that the official lean has more chances to be included in the repo than lean-community.

**Comment by Eloitor** [comment]
Should I also make a package for https://github.com/leanprover-community/mathlib-tools ?

**Pull request closed without merging**
