### PR TITLE
ffmpeg: update to 4.1.

### PR DESCRIPTION
**Pull request by prspkt**

### CODE REVIEW

**Comment by maxice8** [comment]
https://github.com/void-linux/void-packages/pull/4389

**Comment by jnbr** [comment]
LGTM. Why did you close?

**Comment by prspkt** [comment]
@jnbr sorry, quick fingers.

**Comment by jnbr** [comment]
Can someone confirm test video playback in firefox-esr with this update?

**Comment by prspkt** [comment]
@jnbr video playback for `firefox-esr` works for me on x86_64-musl

**Pull request merged**
