### PR TITLE
[DO NOT MERGE] mono: update to 5.12.0.226

### PR DESCRIPTION
**Pull request by codingHahn**
I don't know if I have to revbump packages that depend on mono.

### CODE REVIEW

**Comment by codingHahn** [comment]
It builds fine. It just times out

**Comment by Hoshpak** [comment]
It doesn't time out because it takes to long for travis to build but because the new version contains a severe regression on musl. Caused by some threading changes, the compiler is now stalled for 50-60 seconds on shutdwon on musl which essentially makes the package unusable on musl right now. For reference, the upstream issue is https://github.com/mono/mono/issues/7167 . Please don't update the package until either a working patch or a new version containing a fix is released.

**Comment by codingHahn** [comment]
Ok. Then lets wait for upstream to fix this.

**Comment by Hoshpak** [comment]
superseded by #3585

**Pull request closed without merging**
