### PR TITLE
New package: sublime-text4-4113

### PR DESCRIPTION
**Pull request by shizonic**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by shizonic** [comment]
Unfortunately I can't find any license file.

**Comment by Chocimier** [comment]
Review comments at #31036

**Comment by shizonic** [comment]
@Chocimier I made the changes mentioned in https://github.com/void-linux/void-packages/pull/31036.

`aarch64` is untested and the build fails. What is the correct way to test this locally?

**Comment by Chocimier** [comment]
> made the changes mentioned in #

But why only part of them?

> |aarch64| is untested and the build fails. What is the correct way to test this locally?

Do a cross build as described in readme. Testing native build architecture is enough if one has no hardware.

**Comment by shizonic** [comment]
> But why only part of them?

Excuse me but which ones did I miss?

> Do a cross build as described in readme. Testing native build architecture is enough if one has no hardware.

Okay got it and will do it ASAP.

**Comment by shizonic** [comment]
@Chocimier Guess I fixed everything and made every suggestions mentioned in https://github.com/void-linux/void-packages/pull/31036

**Comment by Chocimier** [comment]
Closed by #31036.

**Pull request closed without merging**
