### PR TITLE
[DO NOT MERGE] android-studio: update to 3.4.2

### PR DESCRIPTION
**Pull request by mustaqimM**
Please don't merge yet, I'm getting the following error when trying to install:
```zsh
$> sudo xbps-install --repository=hostdir/binpkgs/android-studio-update-branch/nonfree android-studio
Password:
android-studio-3.4.0_1: broken, unresolvable shlib `ld-linux.so.2'
android-studio-3.4.0_1: broken, unresolvable shlib `libncurses.so.5'
Transaction aborted due to unresolved shlibs.
```

### CODE REVIEW

**Comment by daniel-eys** [comment]
I think the `skiprdeps` need some revision to resolv the `unresolvable shlib` error.

**Comment by gemath** [comment]
We may have the libraries we need on Void:
`ld-linux.so.2` is called `ld-2.xx.so` and is linked as `ld-linux-x86-64.so.2`
`libncurses.so.5` could probably be replaced with `libncursesw.so.5` which basically just adds unicode support.

**Comment by mustaqimM** [comment]
@gemath Both of them are already linked:
https://github.com/void-linux/void-packages/blob/f19f9f9cf7ef89b294ab4a37340f33d41a55c6a8/common/shlibs#L26
https://github.com/void-linux/void-packages/blob/f19f9f9cf7ef89b294ab4a37340f33d41a55c6a8/common/shlibs#L72

Currently it's only aborting on:
```zsh
android-studio-3.4.0_1: broken, unresolvable shlib `libncurses.so.5'
```

**Comment by Gottox** [comment]
stalled. please reopen when there's progress.

**Pull request closed without merging**
