### PR TITLE
Firefox 74

### PR DESCRIPTION
**Pull request by jnbr**

### CODE REVIEW

**Comment by jnbr** [comment]
Tested briefly on x86_64, glibc and musl.
Builds pass for arm7, aarch64 and i686 as well.

**Comment by zdykstra** [comment]
Broken on ppc64le:
```
=> firefox-74.0_1: patching: fix-toolkit.patch.
1 out of 1 hunk FAILED -- saving rejects to file toolkit/mozapps/update/common/updatedefines.h.rej
```

It's beyond me to fix the specific problem, I'll have to defer to @q66.

**Comment by jnbr** [comment]
On Tue, 10 Mar 2020 13:23:36 -0700
Zach Dykstra <notifications@github.com> wrote:

> Broken on ppc64le:
> ```
> => firefox-74.0_1: patching: fix-toolkit.patch.  
> 1 out of 1 hunk FAILED -- saving rejects to file
> toolkit/mozapps/update/common/updatedefines.h.rej ```
> 
> It's beyond me to fix the specific problem, I'll have to defer to
> @q66. 
> 

This is weird because this hunk was removed from the patchset.
Make sure your branch is up to date.

**Comment by zdykstra** [comment]
> This is weird because this hunk was removed from the patchset. Make sure your branch is up to date.

Yup, quick-and-dirty work on my end was incomplete. I caught it right after I commented, so I deleted it. Now my shame is public ;)

**Comment by michaelforney** [comment]
Some more of the patch hunks can be dropped; firefox 74 includes a few other upstreamed musl fixes.

- fix-seccomp-bpf.patch is no longer necessary, it was fixed in https://hg.mozilla.org/mozilla-central/rev/3ec8c96f4d53
- The `__NR_pread` hunk in fix-toolkit.patch is no longer necessary, it was fixed in https://hg.mozilla.org/mozilla-central/rev/660da1ec99c0

Additionally, you might consider dropping the basename hunk in fix-tools.patch in favor of the upstream fix scheduled for firefox 75: https://hg.mozilla.org/mozilla-central/rev/a3096ca24124

**Comment by jnbr** [comment]
That's nice. Thank you. I've updated the PR.

**Comment by michaelforney** [comment]
Looking through the remaining patches, I think the libgen.h hunk in fix-toolkit.patch is not necessary since firefox 63: https://hg.mozilla.org/mozilla-central/diff/5284d9a25ffb3ec2130f2526f1b8785a9e48e0ba/toolkit/crashreporter/google-breakpad/src/common/linux/dump_symbols.cc.

The two other remaining hunks fix-toolkit.patch also don't seem necessary. stabs_reader.cc is only built on Darwin since firefox 47: https://hg.mozilla.org/mozilla-central/diff/62a0d8c93da2ca24f3f87642a2989c4741f214d4/toolkit/crashreporter/google-breakpad/src/common/moz.build

**Comment by jnbr** [comment]
Thank you for reviewing these patches.

**Pull request merged**
