### PR TITLE
New package: noise-suppression-for-voice-0.91

### PR DESCRIPTION
**Pull request by mustaqimM**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, `(x86_64-glibc)`

### CODE REVIEW

**Comment by prez** [comment]
>`DBUILD_LV2_PLUGIN=OFF`

very questionable decision. I'd argue LV2 is what you want to have, the others are optional.

**Comment by prez** [comment]
> Well, that's up for discussion. I only kept LADSPA enabled since it can be used system-wide through a pipewire/pulse sink

The same goes for LV2. I suggest building LV2 only for now.

**Comment by cinerea0** [comment]
I think this one is worth keeping open.

**Comment by JamiKettunen** [comment]
@mustaqimM Could this be bumped to [v1.03](https://github.com/werman/noise-suppression-for-voice/releases/tag/v1.03)?

> The same goes for LV2. I suggest building LV2 only for now.

@prez Why not both? I'm using this as a PipeWire LADSPA plugin as [documented on the README](https://github.com/werman/noise-suppression-for-voice#pipewire) and just tried to make it use the LV2 plugin but was unsuccessful.

I checked `lv2ls` (from `lilv`) and this could be problematic:
```
$ lv2ls
lilv_world_add_plugin(): warning: Duplicate plugin <https://github.com/werman/noise-suppression-for-voice>
lilv_world_add_plugin(): warning: ... found in file:///usr/lib64/lv2/rnnoise_stereo.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/lib64/lv2/rnnoise_mono.lv2/ (ignored)
...
https://github.com/werman/noise-suppression-for-voice
```
Considering the README itself mentions `It also would consume 2x resources` with regards to using the `stereo` plugin as compared to the `mono` one (which I know my microphone only is mono channel).

https://docs.pipewire.org/page_module_filter_chain.html mentions `For LV2, this is the plugin URI obtained with lv2ls` but I couldn't get it working. I'm very much a newbie when it comes to PipeWire configuration so if someone has a working LV2 `mono` plugin config I wouldn't mind LADSPA wasn't present in this package; I just want a working configuration with the `mono` plugin that's all.

**Comment by mustaqimM** [comment]
@JamiKettunen I had to add `libsanitizer-devel` for it to build the new version, but now it's failing for other arches. I don't have time to see what's up, so if someone wants to take over, please do so. 
Also I set the flag `-DBUILD_VST_PLUGIN=OFF` but in the new version, it still builds it and adds it to `/usr/lib/vst3/rnnoise.vst3/Contents/x86_64-linux/rnnoise.so`

**Pull request closed without merging**
