### PR TITLE
crypto++: update to 800

### PR DESCRIPTION
**Pull request by ndowens**

### CODE REVIEW

**Comment by maxice8** [comment]
Please check MEGAsdk last time crypto++ would break it

**Comment by ndowens** [comment]
> Please check MEGAsdk last time crypto++ would break it

Will do, was waiting for travis build to see how it reacts. Will reply with my outcome.

**Comment by ndowens** [comment]
on x86_64(glibc) it built fine against newer crypto++

**Comment by maxice8** [comment]
On Mon, Jan 14, 2019 at 03:58:59PM -0800, Nathan wrote:
> on x86_64(glibc) it built fine against newer crypto++
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/7127#issuecomment-454209901

I mean runtime

**Comment by ndowens** [comment]
Closing as it seems update would break other packages, and I have no idea how to work around it

**Pull request closed without merging**
