### PR TITLE
[RFC] Support git worktree

### PR DESCRIPTION
**Pull request by sgn**
My effort to address #20393 

~This PR haven't set `XBPS_REPOSITORY` to correct branch yet.~

### CODE REVIEW

**Comment by xtraeme** [comment]
I like the idea, this will allow us to get rid of chroot-git as well.

**Comment by sgn** [comment]
On 2020-04-21 09:34:46-0700, Juan RP <notifications@github.com> wrote:
> I like the idea, this will allow us to get rid of chroot-git as well.

I thought about get rid of `chroot-git` as well.
But even if split single `/usr/bin/git` out of git (to provide e.g.
git-core), it still have dependencies on libpcre2.

Not sure if the added dependencies to base-chroot annoys anyone.


-- 
Danh

**Comment by sgn** [comment]
The change is _NOT_ ready yet.
`xbump` tool report an error.

**Comment by sgn** [comment]
@Piraty You may be interested in this PR.

**Comment by Piraty** [comment]
i am :)  saw it already, yet have to test

**Comment by sgn** [comment]
@void-linux/pkg-committers Any comment?

**Comment by Piraty** [comment]
please wait some more. i want to test it yet

**Comment by sgn** [comment]
@Piraty I drop 2 patches, 1 that replaces git-log and the other one for testing.

If no-one complains, I'll push this version in the weekend and see the world burnt xD

**Comment by Piraty** [comment]
let it burn

**Pull request merged**
