### PR TITLE
New package: yacy-1.924

### PR DESCRIPTION
**Pull request by jason1987d**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by FollieHiyuki** [comment]
The custom system account should be `_yacy`

**Comment by FollieHiyuki** [comment]
Can you squash all the commits into 1?

**Comment by jason1987d** [comment]
> Can you squash all the commits into 1?

What's the best way to do this?

**Comment by FollieHiyuki** [comment]
I will go with `git rebase --interactive HEAD~10` then drop all the relevant commits (except the 1st one).

Then `git pull upstream master --rebase`.

And finally adding your changes to the template (again), then `git commit --amend`, `git push -f`

**Comment by hiljusti** [comment]
Just curious, but how are you doing rebases?

**Pull request closed without merging**
