### PR TITLE
qt5-webengine: enable WebRTC screen sharing via PipeWire

### PR DESCRIPTION
**Pull request by Eluminae**

### CODE REVIEW

**Comment by Eluminae** [comment]
Someone could tell me why it build on some archs but not on others ?

**Comment by Eluminae** [comment]
Works on local but builds seems to lack the pipewire/pipewire.h. pipewire-devel contain this header. 

What am I missing ?

**Comment by Eluminae** [comment]
Okay I think I got it:

libpipewire0.2-devel contains /usr/include/pipewire/pipewire.h but pipewire-devel got /usr/include/pipewire-0.3/pipewire/pipewire.h

Why an older version of pipewire is the default and unversionned one ?

**Comment by Johnnynator** [comment]
Thx, I will take a look at this and pull it into the 5.15.3 update.

**Pull request closed without merging**
