### PR TITLE
mesa: update to version 23.1.7.

### PR DESCRIPTION
**Pull request by SpidFightFR**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x64-GlibC)

Addendum: 

Hey guys, a new pr that will close the previous (https://github.com/void-linux/void-packages/pull/45635) this pull request was **tested** and it worked on my side. Even tho i had a weird error the first try but pretty sure it was my bad.

Anyways, feel free to send feedback ! :smile: 

Best regards - Spid

### CODE REVIEW

**Comment by zlice** [comment]
Ok, failing to build, good I'm not crazy xp

**Comment by SpidFightFR** [comment]
> Ok, failing to build, good I'm not crazy xp

Why is it happening? It happens with 23.1.6 even tho it worked before i close it…

**Comment by zlice** [comment]
> Why is it happening? It happens with 23.1.6 even tho it worked before i close it…

idk, asked in irc the other day but no reply. didn't see any open issues anywhere either

**Comment by Luciogi** [comment]
Try building locally for 32bit

**Comment by SpidFightFR** [comment]
> > Why is it happening? It happens with 23.1.6 even tho it worked before i close it…
> 
> idk, asked in irc the other day but no reply. didn't see any open issues anywhere either

I opened a discussion field here (https://github.com/void-linux/void-packages/discussions/45987), hoping that someone can help.

**Comment by SpidFightFR** [comment]
In case it now works again, i just tried to re-commit...

**Comment by SpidFightFR** [comment]
My bad, there was a mistake. now it should work.

**Pull request closed without merging**
