### PR TITLE
virt-viewer: update to 7.0.

### PR DESCRIPTION
**Pull request by Hoshpak**
compatible with spice-gtk-0.35, resolves staging on the builders. CC @Duncaen

### CODE REVIEW

**Comment by Cogitri** [comment]
Sorry, forgot to open a PR for that myself after the spice-gtk bump. It seems like building virt-viewer like this results in it being unable to connect to spice hosts:

`Failed to connect: Unsupported graphic type 'spice'`

**Comment by Hoshpak** [comment]
did you recompile the old virt-viewer 6.0 which is not compatible with spice-gtk-0.35 or the current version from this PR? I am able to connect to a locally running VM (managed by libvirt, created and configured via virt-manager) with virt-viewer-7.0 using the spice protocol without issues.

**Comment by Cogitri** [comment]
I'm using virt-viwer 7.0:

```
virt-viewer -V
virt-viewer version 7.0
```

I connect to a machine in my LAN via `virt-viewer -v -c qemu+ssh://root@192.168.1.72/system`, but now I only get:

```
Opening connection to libvirt with URI qemu+ssh://root@192.168.1.72/system
Guest exqa is running, determining display
Guest exqa has unsupported spice display type
```

when connecting to it.

**Comment by Hoshpak** [comment]
I configured an ssh server and used another computer on the same network to execute virt-viewer, the result:

```
]$ virt-viewer -v -c qemu+ssh://helmut@192.168.178.10/system
Opening connection to libvirt with URI qemu+ssh://helmut@192.168.178.10/system
Guest Android_x86 is running, determining display
Guest Android_x86 has a spice display
Opening indirect TCP connection to display at 127.0.0.1:5900
Setting up SSH tunnel via helmut@192.168.178.10

(virt-viewer:1921): GSpice-WARNING **: 23:20:25.783: PulseAudio context failed Connection refused

(virt-viewer:1921): GSpice-WARNING **: 23:20:25.784: pa_context_connect() failed: Connection refused

(virt-viewer:1921): GSpice-WARNING **: 23:20:26.154: Warning no automount-inhibiting implementation available
```
So spice connections generally work. I'm don't know what exactly causes your connection to fail.

**Comment by Cogitri** [comment]
Hm, okay, go on and merge this then, this might be due to some local breakage on my side. I'll open a PR to fix that later on if it isn't.

**Pull request merged**
