### PR TITLE
New package: NetworkManager-pptp-1.2.8

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by Cogitri** [comment]
Please test @xerxeslins

**Comment by xerxeslins** [comment]
Thank you very much. I'll test and then i'll tell you the result.

**Comment by Cogitri** [comment]
Thanks

**Comment by xerxeslins** [comment]
Yes! It looks like everything is OK! I was able to use it. But I had to start the nm-applet with sudo. It should just be a matter of giving my user permission. But the plugin is working! 

I do not know if I did right. I copied the template and compiled it by xbps-src.

Thank You.

**Comment by Cogitri** [comment]
Glad it works, thanks for testing :)

**Pull request merged**
