### PR TITLE
New package: openjdk17-17.0.1+12

### LINKED ISSUE #32942: Package Request: openjdk-17
Would be nice to include a newer java runtime thing, for compatibility with newer compiled java .jar's

### PR DESCRIPTION
**Pull request by classabbyamp**
Built upon the work of @sgn and @raedwulf.

Closes #32942
Supercedes #34390, #35078

#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

#### Local build testing
- I built this PR locally for these architectures:

| arch | cross | built | `check` passes |
|:-----:|:-----:|:-----:|:-----:|
| x86_64 || 12 ✔ <br> 13 ✔ <br> 14 ✔ <br> 15 ✔ <br> 16 ✔ <br> 17 ✔ | 12 ✔ <br> 13 ✔ <br> 14 ✔ <br> 15 ✔ <br> 16 ✔ <br> 17 ✔ |
| x86_64-musl || 12 ✔ <br> 13 ✔ <br> 14 ✔ <br> 15 ✔ <br> 16 ✔ <br> 17 ✔ | 12 ✔ <br> 13 ✔ <br> 14 ✔ <br> 15 ✔ <br> 16 ✔ <br> 17 ✔ |
| i686 || 12 ✔ <br> 13 ✔ <br> 14 ✔ <br> 15 ✔ <br> 16 ✔ <br> 17 ✔ | 12 ✔ <br> 13 ✔ <br> 14 ✔ <br> 15 ✔ <br> 16 ✔ <br> 17 ✔ |
| aarch64 | ✔ | 17 ✔ ||
| aarch64-musl | ✔ | 17 ✔ ||
| armv7l | ✔ | 17 ✔ ||
| armv6l-musl | ✔ | 17 ✔ ||

[ci skip]

### CODE REVIEW

**Comment by Duncaen** [comment]
You don't have to cross build i686, you can use a i686 masterdir on x86_64* systems like you do with a different libc masterdir.

**Comment by classabbyamp** [comment]
ok thanks, i was about to ask that on irc

**Comment by EliteTK** [comment]
The XBPS_MAKEJOBS -> XBPS_ORIG_MAKEJOBS trick doesn't appear to work. I haven't quite figured out why yet but:

* If I build openjdk17 (indirectly building openjdk12-bootstrap) the configure gets passed --with-jobs=1.
* If I explicitly set XBPS_ORIG_MAKEJOBS when building openjdk17 this is still the case.
* If I explicitly build openjdk12-bootstrap the issue persists.
* If I explicitly build openjdk12-bootstrap with XBPS_ORIG_MAKEJOBS the issue persists.

I will just hardcode a sensible value, build, and chip in by testing this on x86_64 a bit.

**Comment by classabbyamp** [comment]
@EliteTK you only need to set the standard `XBPS_MAKEJOBS` for it to work. `XBPS_ORIG_MAKEJOBS` shouldn't be changed manually, because if `XBPS_MAKEJOBS` is unset, `XBPS_ORIG_MAKEJOBS` will be set to 1 within xbps-src

**Comment by classabbyamp** [comment]
sidenote for other reviewers: should something be added to Manual.md about `XBPS_ORIG_MAKEJOBS`?

**Comment by EliteTK** [comment]
Yes, what I meant is that it didn’t work regardless of if I just set XBPS_MAKEJOBS or if I set both.

**Comment by classabbyamp** [comment]
I cloned a fresh copy of void-packages and tried it:
```
$ echo $XBPS_MAKEJOBS
12
$ ./xbps-src configure openjdk12-bootstrap
...
checking for number of cores... 12
checking for memory size... 32019 MB
...
Build performance summary:
* Cores to use:   1
* Memory limit:   32019 MB
```

That's very strange; when I was running my builds locally, I got 12 cores in both places of the configure output. Do you get the correct number in the first spot?

**Comment by classabbyamp** [comment]
seems setting `XBPS_MAKEJOBS` in your environment doesn't work, you have to either `echo 'XBPS_MAKEJOBS=n' >> etc/conf` or use the `-j n` flag of xbps-src. Should not be an issue on the builders

**Comment by motorto** [comment]
@classabbyamp  Anything I can do to help ? It seems that the work is mostly done, but just making sure

**Comment by classabbyamp** [comment]
If you'd like, you can try to build it on your machine, but other than that there's not much to do I think

**Comment by endigma** [comment]
What's blocking merge?

**Comment by classabbyamp** [comment]
nothing, just waiting for maintainers

**Comment by dadudeme** [comment]
I am quite new to git hub but want to build this package could someone let me know how to do this or refer me to an explanation?
Thanks in advance

**Comment by motorto** [comment]
1) Clone the repo and cd into it
2) wget this url and at the end add .diff 
3) git apply the downloaded diff file and ./xbps-src pkg <namePackage>

**Comment by classabbyamp** [comment]
no need to do that weird diff process.

do step 1 above, then `git fetch origin pull/34989/head:openjdk17`, then don't forget to bootstrap with `./xbps-src binary-bootstrap` before running `./xbps-src pkg openjdk17`.

Once that's done, use `xi` from the package xtools to install the package to your system (`xi openjdk17`)

**Comment by JamiKettunen** [comment]
Failed to build under `x86_64-musl` & `x86_64` with the following for me:
```
./xbps-src pkg openjdk17
...
Extracting Java cacerts (JKS) to /builddir/jdk17u-jdk-17.0.1-12/ca/etc/pki/tls/java/cacerts...Done!
=> ERROR: openjdk17-17.0.1+12_1: post_install: 'chmod -R ugo+rw ./ca' exited with 1
=> ERROR:   in post_install() at srcpkgs/openjdk17/template:170
```

**Pull request merged**
