### PR TITLE
occt: update to 7.3.0.

### PR DESCRIPTION
**Pull request by karl-nilsson**
Built and tested on x86_64 glibc
not ABI compatible with 7.2, so rebuild freecad

### CODE REVIEW

**Comment by yopito** [comment]
@karl-nilsson : my PR #137 is about the same software stack and is waiting for a while. It's about cleanup and small fixes. Should we consider merging PR #137 into this one ?

**Comment by karl-nilsson** [comment]
@yopito works for me, just let me know what (if anything) you need me to do

**Comment by yopito** [comment]
@karl-nilsson : OK. I will provide you additional commits you will have to merge into your PR if you're ok with. Maybe in the next couple of hours.

**Comment by maxice8** [comment]
ping

**Comment by maxice8** [comment]
On Tue, Nov 27, 2018 at 03:29:21PM -0800, Karl Nilsson wrote:
> @maxice8 pong
> What do you need from me?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/1215#issuecomment-442258423

If it's ok to merge

**Comment by luzpaz** [comment]
FreeCAD needs updating as well. The next release which is coming out soon is py3 and Qt5 compliant. Can the FreeCAD 0.17 be pinned to the current OpenCasCade formula that it works with ?

**Comment by luzpaz** [comment]
Any progress on this ? FreeCAD shouldn't block this issue. Since the 0.18 release is just around the corner it would be strategic to just port the freecad port to qt5/py3 /occ7.3

**Comment by luzpaz** [comment]
Yea, no idea why they released a patched 7.3 version instead of a 7.4 release :man_shrugging:

**Comment by maxice8** [comment]
Outdated, please rebase

**Comment by karl-nilsson** [comment]
@maxice8 rebased
also, it might be worthwhile to label this [CI Skip]

**Comment by karl-nilsson** [comment]
Thanks!

**Pull request merged**
