### PR TITLE
Libdispatch package

### PR DESCRIPTION
**Pull request by Ilia1**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86-64

This library is required to upgrade package deadbeef.

### CODE REVIEW

**Comment by Bnyro** [comment]
This should likely be in the same  PR with the deadbeef update. And please do one commit per added / updated package as explained in https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#updating-a-template.

**Comment by Ilia1** [comment]
This library is not specific to the deadbeef package and can be used by other programs in the future. So I put it in a separate package.

**Comment by Bnyro** [comment]
Yes, but your other PR depends on it. So it should be added in the same PR as a dependency, because it's required there in order to update the package.
Nevertheless the package has to be independent from the deadbeef package.

**Comment by Ilia1** [comment]
OK, I was thinking that 1 PR = 1 package.
Now I close this PR.

**Pull request closed without merging**
