### PR TITLE
hunspell-pt_PT-preao: update to 20220621.

### PR DESCRIPTION
**Pull request by voidbert**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-musl)

#### NOTE
Related to #41623, don't know if I can do two packages in one PR. Let's hope my University's server doesn't decide to time out for GitHub Actions for this one.

### CODE REVIEW

**Comment by motorto** [comment]
For the record you can do several packages per PR as long as they are related : ) 

Nice to see some Portuguese people around here

**Comment by voidbert** [comment]
@motorto With a relatively large Portuguese Linux community, I still wonder why these hunspell packages aren't in the repos. By the way, do you know if I need to fix the length of the package description (the linting error) for it to be approved? I didn't because the package isn't mine, I just upped the version.

**Comment by classabbyamp** [comment]
yes, please fix the lint

**Comment by sgn** [comment]
> By the way, do you know if I need to fix the length of the package description

No, but if I were the author, I would just write:
```
short_desc="Pre-1990 Portuguese dictionary for hunspell"
```

**Pull request merged**
