### PR TITLE
[WIP] Python-3.7

### PR DESCRIPTION
**Pull request by Gottox**
This PR adds a python3.7 package. Currently this pkg conflicts with python3 as /usr/lib/libpython3.so is not a versioned object.

I'd like to discuss how we can handle the python3.7 branch in general:

* We could update python3-3.6. That means we need to rebuild all python3 packages to handle the new path.

* Or we keep the 3.6 branch and introduce a new python3.7 package like I did with this PR

### CODE REVIEW

**Comment by CameronNemo** [comment]
how much appetite is there for concurrent versions of python?

**Comment by Gottox** [comment]
From a users perspective I see no reason to support multiple minor versions of python. But if there's a reason to support both 3.6 and 3.7 concurrently and be it only an easier update, it would be okay.

**Comment by CameronNemo** [comment]
Seems like the python3.7 necessarily conflicts with python3.6 ?

```
$ xbps-query -o /usr/lib/libpython3.so
python3-3.6.9_1: /usr/lib/libpython3.so (regular file)
python3.7-3.7.4_1: /usr/lib/libpython3.so (regular file)
```

**Comment by CameronNemo** [comment]
The `/usr/bin/python3` symlink is also clashing -- not sure why xbps cannot detect either case.

**Comment by xtraeme** [comment]
This should be all handled by alternatives. Including shared libraries or
whatever.

**Comment by CameronNemo** [comment]
@xtraeme the shared library seems unnecessary. the python3 symlink should indeed be handled by alts. See #13608 for more info.

**Comment by Gottox** [comment]
I don't see a reason for using alternatives either. In the worst case we can introduce a versioned soname for python3.7.

We already did this with python3.5 -> python3.6 and I can't remember having hassle with this update.

**Comment by Gottox** [comment]
See 286f5ae67635c4e5d1cc43d1f9a1b047fabafbbb and following

**Comment by leahneukirchen** [comment]
We'll have Python 3.8 soon, let's not bother with this.

**Pull request closed without merging**
