### PR TITLE
amdvlk: update to 2024.Q1.3.

### PR DESCRIPTION
**Pull request by SpidFightFR**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x64-GlibC)

### CODE REVIEW

**Comment by SpidFightFR** [comment]
The issue with x64-musl happens after the update, the original version still builds fine.

**Comment by Johnnynator** [comment]
The `errors` in the build logs seem to be mainly missuse of NULL and should be patched to be `OL`.

Most of the warnings can probably be ignored.

**Comment by SpidFightFR** [comment]
> The `errors` in the build logs seem to be mainly missuse of NULL and should be patched to be `OL`.
> 
> Most of the warnings can probably be ignored.

Copy that. I'll see what i can do.

It's because of a misuse from Upstream and not a difference between glibc and musl?

**Comment by Johnnynator** [comment]
Musl and Glibc differ at how they define NULL. (`std::nullptr` vs `(void*)0`).
Both of these choices are valid, but std::nullptr can't be implicitely used as a number.

Upstream amdvlk uses NULL as an integer and not a Pointer in a few places

**Comment by SpidFightFR** [comment]
> Musl and Glibc differ at how they define NULL. (`std::nullptr` vs `(void*)0`). Both of these choices are valid, but std::nullptr can't be implicitely used as a number.
> 
> Upstream amdvlk uses NULL as an integer and not a Pointer in a few places

I see... Thanks for the explanation! If i got some time in the future i'll try to learn more about musl and glibc.

**Comment by SpidFightFR** [comment]
I made a little test on the rush, replacing `NULL,` by `OL` returns `undefined` and `0L` (apparently it's a zero, long number type) returns another error.

I might have made a few mistakes here and there tho. I tried to changed the `NULL,` that was reported in the error to not create any new error. 

But which ones should i change in particular?

**Comment by SpidFightFR** [comment]
[Nevermind, talked about it on the IRC: TL;DR available [here](https://github.com/GPUOpen-Drivers/AMDVLK/issues/357).]

**Pull request merged**
