### PR TITLE
SDL2: update to 2.24.0.

### PR DESCRIPTION
**Pull request by motorto**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc

### CODE REVIEW

**Comment by biopsin** [comment]
X11 : configure: WARNING: unrecognized options: --enable-video-x11-xinerama, --enable-video-x11-vm
Seems theses can be dropped then

**Comment by motorto** [comment]
Thanks for the heads up, have removed those two options.

**Comment by biopsin** [comment]
Not shure if we need  libXinerama-devel  in makedepends, their changelog didnt spesifie a drop and I didnt dig deeper..

**Comment by motorto** [comment]
It seems to build without it.

**Pull request merged**
