### PR TITLE
util-linux: update to 2.38

### PR DESCRIPTION
**Pull request by marmeladema**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64 (crossbuild) + tested on aarch64 bare metal board

Release notes: https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.38/v2.38-ReleaseNotes

### CODE REVIEW

**Comment by paper42** [comment]
please use one commit per package

**Comment by marmeladema** [comment]
> please use one commit per package

Even if each commit taken separately is invalid?

**Comment by paper42** [comment]
> > please use one commit per package
> 
> Even if each commit taken separately is invalid?

yes, that's how we currently do it

**Comment by marmeladema** [comment]
@paper42 done

**Comment by ericonr** [comment]
I switched the commit order, since `util-linux` is the one that depends on `util-linux-common`. Thanks!

**Pull request closed without merging**
