### PR TITLE
New package: go-task-3.27.1

### PR DESCRIPTION
**Pull request by mchlumsky**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-musl
  - aarch64
  - armv7l
  - armv7l-musl
  - armv6l-musl
  - armv6l
  - i686-musl
  - i686
  - x86_64-musl

### CODE REVIEW

**Comment by mchlumsky** [comment]
How should I resolve the situation where 2 packages have a conflicting command filename? In this case it's task from both  task warrior and go-task.

In Fedora they renamed task from go-task as go-task. Does that make sense in Void? (Sorry I'm new here :) )

**Comment by icp1994** [comment]
`mv ${DESTDIR}/usr/bin/{,go-}task` in `post_install()`

**Comment by mchlumsky** [comment]
Ready for review.

**Comment by komidore64** [comment]
I would love to see `go-task` make it into void!

**Pull request closed without merging**
