### PR TITLE
mesa: update to 21.0.1

### PR DESCRIPTION
**Pull request by marmeladema**
Friendly take over / continuation of https://github.com/void-linux/void-packages/pull/27956

### CODE REVIEW

**Comment by abenson** [comment]
> Mesa 21.0.0 is a new development release.

We wait for the production releases, which will be 21.0.1.

**Comment by marmeladema** [comment]
Sure sure but I still want to test it before 21.0.1 on one of my aarch64 board to let lima crew know if some problems I have been facing have been fixed.
Moreover the cross compilation problems happening now will most likely happen with the stable too so my hope is that if we can fix it now the better.

**Comment by ardadem** [comment]
is this waiting for to be reviewed or WIP?

**Comment by marmeladema** [comment]
@ardadem it's fully ready to be reviewed

**Comment by codingHahn** [comment]
Is anything blocking this?

**Comment by marmeladema** [comment]
I don't think so, we're just waiting for an admin to review and merge this
Maybe @abenson or @ericonr can take a look?

**Pull request closed without merging**
