### PR TITLE
Thunderbird 78.6.0

### PR DESCRIPTION
**Pull request by ericonr**
Still seeing if cross compilation reaches the end successfully.

Would appreciate testers.

Have launched on x86_64-musl, but I'm not on the device that uses thunderbird, so I haven't logged in yet.

Based on and closes #24509 

[ci skip]

### CODE REVIEW

**Comment by dkwo** [comment]
I missed this pr, will test tomorrow on my x86_64-musl machine.
Thanks.

**Comment by dkwo** [comment]
It builds successfully.
@ericonr Could you remind me how to install on my local machine a package that was buillt on a different one (same arch) and copied via scp, if possible? I have a `thunderbird-78.5.1_1.x86_64-musl.xbps` file but not sure how to use it.
Thanks.

**Comment by ericonr** [comment]
@dkwo just use `xdowngrade` from `xtools`!

**Comment by dkwo** [comment]
Thanks.
It seems to work fine, you can merge the PR as far as I'm concerned.

**Comment by fusion-zone** [comment]
Hi,
is there an schedule when Thunderbird 78.x gets released as a package?

Thanks

**Comment by ericonr** [comment]
I'm working on finishing it up (and updating to 78.6.0), then will as for review from others and merge ASAP.

**Comment by ericonr** [comment]
Welcoming testers, especially on glibc.

**Comment by ibhagwan** [comment]
> Welcoming testers, especially on glibc.

@ericonr 

I tried compiling both v78.5.1 and  v78.6.0 in a clean `void-packages` folder (cloned from your fork) and both fail in the same location:

```
274:03.82   import imp
274:03.89 toolkit/library/build/libxul.so
276:24.63 collect2: fatal error: ld terminated with signal 9 [Killed]
276:24.63 compilation terminated.
276:24.63 make[4]: *** [/builddir/thunderbird-78.6.0/config/rules.mk:606: libxul.so] Error 1
276:24.63 make[4]: *** Deleting file 'libxul.so'
276:24.70 make[3]: *** [/builddir/thunderbird-78.6.0/config/recurse.mk:74: toolkit/library/build/target] Error 2
276:24.70 make[2]: *** [/builddir/thunderbird-78.6.0/config/recurse.mk:34: compile] Error 2
276:24.70 make[1]: *** [/builddir/thunderbird-78.6.0/config/rules.mk:390: default] Error 2
276:24.71 make: *** [client.mk:125: build] Error 2
276:24.71 434 compiler warnings present.
276:25.47 Failed to parse ccache stats output: secondary config (readonly)         /etc/ccache.conf
 Config object not found by mach.
Configure complete!
Be sure to run |mach build| to pick up any changes
=> ERROR: thunderbird-78.6.0_1: do_build: './mach build' exited with 2
=> ERROR:   in do_build() at srcpkgs/thunderbird/template:179
```

Let me know if you need any info about my system/setup and I will provide it, running up-to-date glibc void with latest kernel 5.9.16.

**Comment by ericonr** [comment]
> 276:24.63 collect2: fatal error: ld terminated with signal 9 [Killed]

The kernel's OOM killer is killing the process during the linking phase. You have to give it more memory (less parallelism, for example). Here the linker took around 10G of RAM.

**Comment by ibhagwan** [comment]
> > 276:24.63 collect2: fatal error: ld terminated with signal 9 [Killed]
> 
> The kernel's OOM killer is killing the process during the linking phase. You have to give it more memory (less parallelism, for example). Here the linker took around 10G of RAM.

Correct, I was able to compile it on my desktop with 64GB RAM, as I finished compiling I saw it was actually just published as a pre-packaged binary in the repos and works great :-)

Ty!

**Pull request merged**
