### PR TITLE
thunderbird: add thunderbird-wayland wrapper.

### PR DESCRIPTION
**Pull request by ericonr**
It's similar to the one shipped by Firefox.

### CODE REVIEW

**Comment by ericonr** [comment]
Closing for #23973 c:

**Comment by ericonr** [comment]
@Hoshpak

**Comment by Hoshpak** [comment]
> @Hoshpak <https://github.com/Hoshpak>

I'm not the maintainer of the package but if it works, by all means, go
ahead.

**Comment by ericonr** [comment]
Oh, I tagged you because you commited the last update. In that case, @Gottox

**Comment by ericonr** [comment]
That's reasonable. Ideally mozilla would switch to wayland by default at some point, too.

**Pull request closed without merging**
