### PR TITLE
glibc: update to 2.28.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by jnbr** [comment]
to avoid breaking systems on update, `common/shlibs` should be updated and xbps should be bumped: https://github.com/voidlinux/void-packages/pull/6015

**Comment by travankor** [comment]
some new build options to consider:

- `--enable-static-pie` was added in glibc 2.27 and takes effect with gcc8.1+
- `--enable-cet` Intel Control-flow Enforcement Technology added in glibc 2.28. Adds indirect branch tracking (IBT) and shadow stack (SHSTK) (only for x86_64 and i386) needs gcc8.1+
- `--enable-kernel` can be 3.16 since this is the oldest maintained kernel
- `--disable-crypt` and use separate libgcrypt (glibc will supposedly deprecate this in the future, regardless: "We have tentative plans to hand off maintenance of the passphrase-hashing
  library, libcrypt, to a separate development project that will, we hope,
  keep up better with new passphrase-hashing algorithms.")
- `--disable-timezone-tools` ?  (not sure about this)
- remove `--enable-obsolete-nsl` and `--enable-obsolete-rpc` and `--enable-add-ons` (?; the last two are no longer mentioned in the documentation... also there are some other options no longer documented too and should be removed)

I'm not sure if this breaks stuff (removing crypt and nsl could break things without planning), but I can help test. The first two options are things that should definitely be added IMO; the rest might be of marginal to no benefit.

**Comment by chneukirchen** [comment]
Arch has `--enable-cet=auto`, which is the sensible option.

**Comment by chneukirchen** [comment]
And a few ARM platforms still have kernel 3.4 and 3.14.

**Comment by Duncaen** [comment]
You don't really need to bump xbps, this was only necessary because xbps was bumped without the shlib bump and already used symbols from the new glibc which results in the break.
The rebuild was necessary to get the right version requirements from shlibs.

**Comment by travankor** [comment]
`--enable-cet=auto` is the gcc option. I'm not sure what the difference between the gcc and glibc flags do (do you need both enabled or is gcc enough?).

And on outdated arm platforms, musl would be a better fit for them, no? Then again, best not to tempt Murphy's Law.

**Comment by chneukirchen** [comment]
Ah yes, but we can't `--enable-cet` for glibc as only the newest intel chips even support it.

**Comment by travankor** [comment]
yes, I think only the newest Xeon supports this. (it should be backwards compatible though: "NOTE: --enable-cet has been tested for i686, x86_64 and x32 on non-CET processors.")

**Comment by Cogitri** [comment]
Soo...what's the status on this? glibc 2.27+ has some rather big performance improvements which would be nice to have.

**Comment by maxice8** [comment]
On Sat, Sep 15, 2018 at 12:05:39AM -0700, Rasmus Thomsen wrote:
> Soo...what's the status on this? glibc 2.27+ has some rather big performance improvements which would be nice to have.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/1605#issuecomment-421536945

For all intents and purposes abandoned

**Pull request closed without merging**
