### PR TITLE
[RFC] mesa: reorganize dri drivers subpkgs (fixes debug info)

### LINKED ISSUE #12760: mesa-nouveau-dri: -dbg package: debug information mismatch, missing details in backtrace
### System

* xuname:  
  Void 5.1.15_1 x86_64 GenuineIntel uptodate rrrrmdFFFFFFFFF
* package:  
  mesa-nouveau-dri-dbg-19.1.1_1

### Expected behavior

`gdb` should load debug symbols for the right file, i.e. `/usr/lib/debug/vdpau/libvdpau_nouveau.so.1` should match `/usr/lib/vdpau/libvdpau_nouveau.so.1`, etc., backtrace should contain symbols for all loaded libraries, etc.

### Actual behavior

`gdb` gives debug information mismatch warning, backtrace is missing details

### Steps to reproduce the behavior

(trying to debug void-linux/void-packages#12717)

* On a system using `nouveau` X graphics driver and `gdb` installed, run the following in a terminal:
```sh
# xbps-install vdpauinfo{,-dbg} glibc-dbg mesa-nouveau-dri-dbg
```
* Run `vdpauinfo` under GDB

Results on my system:
```sh
$ gdb -q vdpauinfo 
Reading symbols from vdpauinfo...
Reading symbols from /usr/lib/debug//usr/bin/vdpauinfo...
(gdb) set pagination off 
(gdb) run
Starting program: /usr/bin/vdpauinfo 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
display: :0   screen: 0
warning: the debug information found in "/usr/lib/vdpau/libvdpau_r300.so.1.0.0" does not match "/usr/lib/vdpau/libvdpau_nouveau.so.1" (CRC mismatch).

warning: the debug information found in "/usr/lib/vdpau/libvdpau_r300.so.1.0.0" does not match "/usr/lib/vdpau/libvdpau_nouveau.so.1" (CRC mismatch).

[New Thread 0x7fffefbda700 (LWP 11586)]

Thread 1 "vdpauinfo" received signal SIGSEGV, Segmentation fault.
0x00007ffff72b2937 in ?? () from /usr/lib/vdpau/libvdpau_nouveau.so.1
(gdb) bt full
#0  0x00007ffff72b2937 in ?? () from /usr/lib/vdpau/libvdpau_nouveau.so.1
No symbol table info available.
#1  0x00007ffff72c1696 in ?? () from /usr/lib/vdpau/libvdpau_nouveau.so.1
No symbol table info available.
#2  0x00007ffff7288210 in ?? () from /usr/lib/vdpau/libvdpau_nouveau.so.1
No symbol table info available.
#3  0x00007ffff72882bf in ?? () from /usr/lib/vdpau/libvdpau_nouveau.so.1
No symbol table info available.
#4  0x00007ffff72b0deb in ?? () from /usr/lib/vdpau/libvdpau_nouveau.so.1
No symbol table info available.
#5  0x00007ffff72859b7 in ?? () from /usr/lib/vdpau/libvdpau_nouveau.so.1
No symbol table info available.
#6  0x00007ffff72ddceb in ?? () from /usr/lib/vdpau/libvdpau_nouveau.so.1
No symbol table info available.
#7  0x00007ffff72e5dac in ?? () from /usr/lib/vdpau/libvdpau_nouveau.so.1
No symbol table info available.
#8  0x00007ffff70034f3 in ?? () from /usr/lib/vdpau/libvdpau_nouveau.so.1
No symbol table info available.
#9  0x00007ffff6ffcf2a in ?? () from /usr/lib/vdpau/libvdpau_nouveau.so.1
No symbol table info available.
#10 0x00007ffff6fecdcb in vdp_imp_device_create_x11 () from /usr/lib/vdpau/libvdpau_nouveau.so.1
No symbol table info available.
#11 0x00007ffff7e6daf5 in vdp_device_create_x11 () from /usr/lib/libvdpau.so.1
No symbol table info available.
#12 0x00005555555554ad in main (argc=<optimized out>, argv=0x7fffffffe198) at vdpauinfo.cpp:488
        o = {
          display_name = 0x7fffffffeb53 ":0", 
          screen = <optimized out>
        }
        display = 0x55555576ce70
        screen = 0
        device = 1
        get_proc_address = 0x1
        rv = <optimized out>
        impl = <optimized out>
(gdb) 
```

Running `objdump -g` on the debug information file confirms the incorrect link:
```sh
$ objdump -g /usr/lib/debug/usr/lib/vdpau/libvdpau_nouveau.so.1.0.0

/usr/lib/debug/usr/lib/vdpau/libvdpau_nouveau.so.1.0.0:     file format elf64-x86-64

objdump: Warning: could not find separate debug file 'libvdpau_r300.so.1.0.0'
objdump: Warning: tried: /lib/debug/libvdpau_r300.so.1.0.0
objdump: Warning: tried: /usr/lib/debug/usr/libvdpau_r300.so.1.0.0
objdump: Warning: tried: /usr/lib/debug/libvdpau_r300.so.1.0.0
objdump: Warning: tried: /usr/lib/debug/usr/lib/vdpau/.debug/libvdpau_r300.so.1.0.0
objdump: Warning: tried: /usr/lib/debug/usr/lib/vdpau/libvdpau_r300.so.1.0.0
objdump: Warning: tried: .debug/libvdpau_r300.so.1.0.0
objdump: Warning: tried: libvdpau_r300.so.1.0.0

Section '.eh_frame' has an invalid size: 0x8bfb0.
Contents of the .gnu_debuglink section (loaded from /usr/lib/debug/usr/lib/vdpau/libvdpau_nouveau.so.1.0.0):

  Separate debug info file: libvdpau_r300.so.1.0.0
  CRC value: 0x69940ea

```

My guess is that something went wrong during build or packaging. I haven't looked into it, so I don't know if the problem is with the recipe or with `xbps-src` itself.

### PR DESCRIPTION
**Pull request by st3r4g**
Aims to fix #12760 and #15104
I believe that two things must be addressed in order to fix the issue:

~~1. xbps-src must be aware of hard links when stripping debug symbols.~~ (EDIT: see third comment)
2. `libGL` must be reorganized by creating a subpackage for each "megadriver" that creates hard links (hard links to the same megadriver must be together in the same subpackage).

This is currently just a first step, I moved all the hard links to `libmesa_dri_drivers.so` to a new subpackage `mesa-dri` as a first example. Next would be to create a new subpackage for the aliases to `libgallium_dri.so` and so on, while also removing the current separation by vendors. The final result is going to be a pretty big change in the template structure, so let me know whether it's a good idea or not before I go on.

### CODE REVIEW

**Comment by st3r4g** [comment]
Finished to reorganize subpackages.

**Comment by st3r4g** [comment]
I didn't see that there is a variable `nostrip_files` that can be put in the template, then the best thing would be to explicitly list all the hard links there rather than patching `xbps-src` for such a corner case. I still think that the `-dri` subpackages reorganization needs to be done though.

**Comment by st3r4g** [comment]
Now xbps-src doesn't need to change, and also possible user confusion is reduced because the debug info is contained in a file named as the megadriver (like `libmesa_dri_drivers.so`) instead of one of the hard links at random. For this I needed to introduce a single-line patch that retains the original megadriver name hard link.

**Comment by xtraeme** [comment]
Looks good to me conceptually! thanks (I didn't test)

**Comment by xtraeme** [comment]
@Duncaen @q66 @leahneukirchen any opinion? lgtm on my side

**Comment by xtraeme** [comment]
This is the one that fixes everything and avoids the hardlinks... ok.

**Comment by xtraeme** [comment]
life is strange... part 3

**Comment by q66** [comment]
I still see a musl FIXME in there, otherwise vaguely lgtm but I haven't tested

**Comment by st3r4g** [comment]
The FIXME is about something I found that was already present before (a broken symlink, at least on my system on musl), but it's out of the scope of this PR I think. It's more like a TODO.

**Comment by xtraeme** [comment]
Sounds ok

**Comment by xtraeme** [comment]
@st3r4g maybe lstat?

**Comment by xtraeme** [comment]
lstat aka lestat.... the vampire

**Comment by st3r4g** [comment]
Ah, that symlink is broken because the file it points to is installed by `xorg-server`, which I didn't have installed some days ago.

**Comment by xtraeme** [comment]
@Duncaen @leahneukirchen @Gottox @Chocimier @jnbr @Johnnynator ?

**Comment by Gottox** [comment]
lgtm, but haven't tested either.

**Comment by st3r4g** [comment]
The only possible thing that could "surprise" users that I'm seeing is that the `mesa-vdpau` and `mesa-XvMC` won't be provided by default anymore (they were part of the `dri` packages), but have to be manually installed if needed. These are `radeon` and `nouveau` libraries for hardware video acceleration, used by programs like `vlc` and `mpv`. I can't directly test, but I don't think their absence breaks anything, seeing that e.g. on archlinux `mesa-vdpau` is optional and `mesa-XvMC` is disabled altogether.

**Comment by st3r4g** [comment]
Improvements:

- `VA-API` stuff (`*_drv_video.so`) was split from `mesa-dri-gallium`
- Disabled automatic detection of provided shlibs for `mesa-vdpau` and `mesa-XvMC` (another thing that was broken due to the hard links)
- Removed mesa XvMC libs that were specified in `common/shlibs` but not actually used

**Comment by xtraeme** [comment]
Nice one buddy

**Comment by st3r4g** [comment]
Changed all the other places where the deleted `mesa-*-dri` appeared (did it with `grep -r` on `srcpkgs`).

**Comment by st3r4g** [comment]
Applied the corrections/improvements proposed by @q66 on IRC

**Comment by m3tav3rse** [comment]
x86_64 glibc with AMD works without any issues

**Comment by st3r4g** [comment]
@m3tav3rse I see you tested this, but mesa was updated in the meantime. If you have not reverted yet these changes, you should do so before updating.

**Comment by xtraeme** [comment]
is this PR still relevant?

**Comment by st3r4g** [comment]
of course, I'll rebase soon.

**Comment by q66** [comment]
please rebase for 19.3.1, i think we can merge this then

**Comment by xtraeme** [comment]
yeah, this one is also good to have

**Comment by st3r4g** [comment]
no pc until the 27th

**Comment by st3r4g** [comment]
Why was this closed?

**Comment by xtraeme** [comment]
no idea :-)

**Comment by Johnnynator** [comment]
Also no idea, I probably missclicked somewhere :man_shrugging: , but I can't reopen because of the forced push. You need to open a new PR.

**Comment by st3r4g** [comment]
> but I can't reopen because of the forced push.
Ah, didn't know this. Well, no problem

**Pull request closed without merging**
