### PR TITLE
rust-analyzer: update to 2021.01.18.

### PR DESCRIPTION
**Pull request by gbrlsnchs**

### CODE REVIEW

**Comment by gbrlsnchs** [comment]
I'm not sure why CI is failing for a few architectures, I might need help with this one. :cry:

**Comment by ericonr** [comment]
It's running rust-analyzer's test suite. You can run this locally with `./xbps-src -Q pkg rust-analyzer`

**Comment by gbrlsnchs** [comment]
> It's running rust-analyzer's test suite. You can run this locally with `./xbps-src -Q pkg rust-analyzer`

Dang, it was working for previous versions of rust-analyzer. Some change introduced in recent versions (of rust-analyzer) might have broken compatibility with some architectures. It works fine on my side but this PR is now blocked, I think probably by upstream, right?

**Comment by ericonr** [comment]
Just disable the tests, they require the presence of the Rust source repo in the file system. You can ask upstream for a way to run tests without source files, but idk how.

```
do_check {
: # tests require rust code base
}
```

**Pull request merged**
