### PR TITLE
Vulkan: update to 1.3.204.1

### PR DESCRIPTION
**Pull request by tibequadorian**
closes #35185 

#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by tibequadorian** [comment]
This is required for the ffmpeg 5.0 update

**Comment by tibequadorian** [comment]
also closes #35185

**Comment by tibequadorian** [comment]
@ericonr do you want to test this on musl?

**Comment by subsonik** [comment]
Confirm that this is working on musl. I need this update to get the Vulkan wlroots backend working. Thanks @tibequadorian!

**Comment by RicArch97** [comment]
Tested on x86-64 glibc, everything builds and works fine.

**Pull request merged**
