### PR TITLE
WIP: New package: finvizfinance-0.14.3

### PR DESCRIPTION
**Pull request by jason1987d**

### CODE REVIEW

**Comment by paper42** [comment]
* try to build the package on your own computer before pushing
* do NOT push every 10 seconds
* do not delete the PR template and fill it

**Comment by jason1987d** [comment]
My apologies. Discovered the xbps-src pkg -Q switch now. Even though I've included python3-BeautifulSoup4 as a hostmakedepends, makedepends, and depends, it's still not finding 'bs4' in its check mode.

**Comment by classabbyamp** [comment]
add it to checkdepends (or, even better: `checkdepends="$depends"`)

**Comment by jason1987d** [comment]
> add it to checkdepends (or, even better: `checkdepends="$depends"`)

Sorry, meant that it failed even with that.

**Comment by tranzystorek-io** [comment]
This patch should fix the bs4 problem:

```patch
diff --git a/setup.py b/setup.py
index 3671638..3e2030b 100644
--- a/setup.py
+++ b/setup.py
@@ -18,7 +18,7 @@ INSTALL_REQUIRES = [
       'pandas',
       'datetime',
       'requests',
-      'bs4',
+      'beautifulsoup4',
       'lxml'
 ]
 CLASSIFIERS = [
```

but it seems we're missing the `datetime` dependency anyway

**Comment by tranzystorek-io** [comment]
Also, since this is purely API, the package should be named "python3-finvizfinance"

**Pull request closed without merging**
