### PR TITLE
sbcl: update to 2.4.5

### PR DESCRIPTION
**Pull request by MIvanchev**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (X86_64-GLIBC)

### CODE REVIEW

**Comment by MIvanchev** [comment]
Added a proper `do_check`.

**Comment by icp1994** [comment]
cc @leahneukirchen

**Comment by fanyx** [comment]
can be closed
https://github.com/void-linux/void-packages/commit/b26d4fada9db96c1b33b4351d488fa744b444e0c

**Comment by MIvanchev** [comment]
Closing this. @leahneukirchen IMO it's a good idea to enable the SBCL tests, they are very extensive.

**Pull request closed without merging**
