### PR TITLE
drone-cli: update to 1.3.0.

### PR DESCRIPTION
**Pull request by teldra**
#### Have the results of the proposed changes been tested?
- [x] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (x86_64-glibc)
- [x] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [x] aarch64-musl
  - [x] armv7l
  - [x] armv6l-musl

### CODE REVIEW

**Comment by ericonr** [comment]
Thanks!

**Comment by teldra** [comment]
> Thanks!

I wonder what for.. :)

**Comment by ericonr** [comment]
Well, for all the quality PRs :)

Makes merging much easier.

**Comment by teldra** [comment]
I try my best to be a productive part (in my limits).

**Pull request merged**
