### PR TITLE
Waybar: add update file.

### PR DESCRIPTION
**Pull request by ericonr**
It was finding weird matches.

```
Waybar  0.9.2 -> 1.0.0  2020-05-23  https://github.com/Alexays/Waybar
Waybar  0.9.2 -> 2.0.0  2020-05-23  https://github.com/Alexays/Waybar
Waybar  0.9.2 -> 2.1.0  2020-05-23  https://github.com/Alexays/Waybar
Waybar  0.9.2 -> 2.2    2020-05-23  https://github.com/Alexays/Waybar
Waybar  0.9.2 -> 2.3    2020-05-23  https://github.com/Alexays/Waybar
Waybar  0.9.2 -> 2.4    2020-05-23  https://github.com/Alexays/Waybar
Waybar  0.9.2 -> 2.4.1  2020-05-23  https://github.com/Alexays/Waybar
Waybar  0.9.2 -> 3.0.0  2020-06-16  https://github.com/Alexays/Waybar
```

### CODE REVIEW

**Comment by sgn** [comment]
It found weird pattern because that is the pattern of date library it also pulls in.
I think we're better to do update check for first url only?
Instead of doing case by case check

**Comment by sgn** [comment]
Either that or ship HowardHinnant's date as an `devel` package.

**Comment by sgn** [comment]
Anyway, `./xbps-src pkg Waybar` doesn't clean `date-*`

**Comment by ericonr** [comment]
> It found weird pattern because that is the pattern of date library it also pulls in.

ooh that does make a lot of sense. Will try to make the logic simpler.

The date library needs patching to generate a pkg-config file that meson can use, so I'm waiting for a release from them.

Any tips on how I could make it clean? Or just add a `post_clean` function?

**Comment by sgn** [comment]
```diff
diff --git a/srcpkgs/Waybar/template b/srcpkgs/Waybar/template
index 42b922ca0d..63965cb9e1 100644
--- a/srcpkgs/Waybar/template
+++ b/srcpkgs/Waybar/template
@@ -3,6 +3,8 @@ pkgname=Waybar
 version=0.9.2
 revision=1
 build_style=meson
+create_wrksrc=yes
+build_wrksrc=Waybar-$version
 configure_args="-Dgtk-layer-shell=enabled -Dlibudev=enabled -Dman-pages=enabled
  -Dsystemd=disabled
  -Dlibnl=$(vopt_if libnl enabled disabled)
```

**Comment by ericonr** [comment]
Fixed

**Comment by sgn** [comment]
Look obviously correct, but all my builders are busy with gnome right now.
If noone check this, I'll look into it tomorrow.

**Comment by ericonr** [comment]
Cool, thanks c:

**Pull request merged**
