### PR TITLE
file: update to 5.43.

### PR DESCRIPTION
**Pull request by tjkirch**
#### Testing the changes
- I tested the changes in this PR: **briefly** - installed the new version and ran `file` on several types of files with the expected results.

#### Local build testing
- I built this PR locally for my native architecture, x86-64 glibc
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - armv6l

I confirmed both of the changes in the deleted patch file are in the 5.43 sources.

### CODE REVIEW

**Comment by tjkirch** [comment]
x86-64 musl unit tests failed with:
```
2022-10-08T23:42:25.2927150Z Running test: ../tests/dsd64-dsf.testfile
2022-10-08T23:42:25.3031608Z ../tests/dsd64-dsf.testfile: DSD Stream File, mono, simple-rate, 1 bit, 141184 samples
2022-10-08T23:42:25.3032087Z lt-test: ERROR: result was (len 57)
2022-10-08T23:42:25.3032524Z DSD Stream File, mono, simple-rate, 1 bit, 141184 samples
2022-10-08T23:42:25.3032828Z expected (len 94)
2022-10-08T23:42:25.3033193Z DSF audio bitstream data, 1 bit, mono, "DSD 64" 2822400 Hz, no compression, ID3 version 2.3.0
```

I haven't figured out yet how to run unit tests during a cross build with xbps-src, so I'm not sure if this is reproducible.  I don't seem to have the ability to rerun CI checks.

**Comment by paper42** [comment]
Checks only run in native builds, you can use a musl masterdir and run the build with checks there. See the -m option and the arch argument to binary-bootstrap.

**Comment by tjkirch** [comment]
Thanks for the tip!  I was able to do that and confirm that it fails locally as well.  I found [an upstream bug](https://bugs.astron.com/view.php?id=382) matching this failure on musl, and it says it's been fixed in the source, just not released yet.  I'll work on adding it as a patch.

**Comment by tjkirch** [comment]
I found that the test failure (or similar ones) continued through all later commits with musl, so I filed another bug upstream: https://bugs.astron.com/view.php?id=393

**Comment by tjkirch** [comment]
The new bug was resolved and many new commits applied to file's master branch, but the only change to the failing test was reverting the first patch I mentioned, which puts it back at the same point as 5.43 that's failing.  I believe there may be a combination of other commits that fix more general issues and may fix musl as well, but in my opinion, it's probably not worth carrying as many patches as we'd - I think it'd be better to wait for a 5.44 release.

**Pull request closed without merging**
