### PR TITLE
update singular to 4.3.0

### PR DESCRIPTION
**Pull request by dkwo**
This now builds fine without patches also on newer musl.

@tornaria Does it solve the issue with doctests in sage?

### CODE REVIEW

**Comment by dkwo** [comment]
I temporarily switched to the ftp distfiles, as Arch does, so that we can test 4.3.0

**Comment by dkwo** [comment]
The hash works fine here.
All tests also pass.
I'll update the distfiles again when they release on github.

**Comment by tornaria** [comment]
Maybe they changed the tarball, I get 74f38288203720e3f280256f2f8deb94030dd032b4237d844652aff0faab36e7.

Can you change it and push again?

I didn't test with sagemath yet; right now the failing test is disabled so there's no problem with doctests on singular 4.2.1. Once we get 4.3.0 working I'll try reenabling the test to see what happens.

**Comment by dkwo** [comment]
Done.

**Comment by leahneukirchen** [comment]
The website says 4.3.0 is released so IMO this can be merged.

**Comment by dkwo** [comment]
Yes, please do, I've already edited distfiles accordingly.

**Pull request merged**
