### PR TITLE
openttd: update to 12.2, gfx to 7.1, sfx to 1.0.3, msx to 0.4.2.

### PR DESCRIPTION
**Pull request by Idesmi**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64*

Closes https://github.com/void-linux/void-packages/pull/36728

### CODE REVIEW

**Comment by Idesmi** [comment]
The fix for cross-compiling is described here: https://github.com/OpenTTD/OpenTTD/pull/8350#issue-756401333

I tried to replicate it in the commented text in the template, but get `strgen: cannot execute binary file: Exec format error`. Suggestions are welcome.

**Comment by Chocimier** [comment]
Resigning from cross build when it was working previously is not acceptable.
Linked solution is somewhat similar to what is done in `plplot` template, can you try again?

**Comment by Chocimier** [comment]
Fixed cross build. Build in `native` was target build because of env vars, cleared with `env -i PATH=$PATH`.

**Comment by Idesmi** [comment]
ping

**Pull request closed without merging**
