### PR TITLE
New package: gltron-0.70

### PR DESCRIPTION
**Pull request by timmykill**

### CODE REVIEW

**Comment by timmykill** [comment]
The release is from 2003, so no.
Someone seems to have patched it for SDL2 support tho https://github.com/laanwj/gltron
I could ask him to make a release or fork his project and release it myself

**Comment by xtraeme** [comment]
Would be nice to use it with SDL2

Cheers

**Comment by xtraeme** [comment]
Please fix the xlint warnings

**Comment by timmykill** [comment]
> Please fix the xlint warnings
Warnings fixed,
for SDL2 support, the repo linked would not work, so i would have to port it manually.
I could do it on my spare time, but I never used SDL (or SDL2 for that matter) so I cant know for sure how long it's gonna take.

**Comment by xtraeme** [comment]
@timmykill this is ok. Just a suggestion if you are bored :-)

SDL2 has support for wayland (among other things).

**Comment by xtraeme** [comment]
anyway xwayland works too, so SDL apps are still supported :-)

**Comment by timmykill** [comment]
> @timmykill this is ok. Just a suggestion if you are bored :-)

I am slowly starting to work on that, if I manage to do anything of value ill keep you updated

**Pull request merged**
