### PR TITLE
New package: img2pdf-0.4.0

### LINKED ISSUE #29281: Package request: img2pdf
[img2pdf](https://gitlab.mister-muffin.de/josch/img2pdf): Lossless conversion of raster images to PDF.

Python program, I think we have most of the dependencies already.

### PR DESCRIPTION
**Pull request by oynqr**
A tool to convert images to PDFs in a lossless way, more info at https://gitlab.mister-muffin.de/josch/img2pdf
Would close #29281

#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by oynqr** [comment]
Current depends include everything but the kitchen sink, maybe python3-tkinter could be dropped since the GUI is not very useful

**Comment by leahneukirchen** [comment]
Hmm, why is setuptools_scm_git_archive needed?

**Comment by oynqr** [comment]
I tried building pikepdf with both python3-pep517 and python3-module styles, the former did not want to cross compile and the latter requires setuptools_scm_git_archive. I'll have another look at it tomorrow, maybe the version check can be patched out easily.

**Comment by oynqr** [comment]
Bumped pikepdf to the latest version and removed its setuptools_scm* dependency

**Comment by leahneukirchen** [comment]
Thank you!

**Pull request merged**
