### PR TITLE
chromium: update to 90.0.4430.212.

### PR DESCRIPTION
**Pull request by pbui**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

[ci skip]

- Built for x86_64, x86_64-musl.
- Tested on x86_64.

### CODE REVIEW

**Comment by ericonr** [comment]
Can you upload it somewhere?

**Comment by pbui** [comment]
Yep, they are at https://h4x0r.space.

**Comment by ericonr** [comment]
Thanks! Working well on musl. Have you built for i686?

**Comment by pbui** [comment]
I have not, but I can do that now and report back.

**Comment by pbui** [comment]
Looks like i686 builds just fine. I have also uploaded the built package to the same web server.

**Pull request merged**
