### PR TITLE
binutils: update to 2.32

### PR DESCRIPTION
**Pull request by xtraeme**

### CODE REVIEW

**Comment by maxice8** [comment]
There is also avr-binutils

**Comment by pullmoll** [comment]
I'm trying a x86_64 bootstrap and will build some of the cross compilers.

**Comment by Cogitri** [comment]
Could you test #6926 with this?

**Comment by pullmoll** [comment]
@Cogitri ok, will try to build eflutils-0.175 as well

**Comment by Cogitri** [comment]
Ah, the build itself should be OK, but please also try to build the DKMS module Hoshpak has mentioned since that's the only thing borked about that PR.

**Comment by pullmoll** [comment]
Ok, I'll see what it takes to build the dkms. Probably need `base-system` and/or `base-devel` for x86_64 then.

**Pull request closed without merging**
