### PR TITLE
ocl-icd: fix broken distfile url

### PR DESCRIPTION
**Pull request by q66**
I'm not sure if pointing it to our own sources like this is a good idea, but the original URL is down and there doesn't seem to be any other mirror with the tarball.

### CODE REVIEW

**Comment by Hoshpak** [comment]
How abaout using github release tarballs? https://github.com/OCL-dev/ocl-icd

**Comment by q66** [comment]
These require bootstrap (autoreconf), which introduces autoconf/libtool dep which is currently not there

**Comment by Hoshpak** [comment]
That's fine if it doesn't cause issues with bootstrapping.

**Comment by q66** [comment]
Okay. I will fix it later today

**Comment by q66** [comment]
btw, should switching to the different tarball cause a revbump, even if it's the same release?

**Comment by Hoshpak** [comment]
That would better as the resulting binary could be different.

**Comment by q66** [comment]
Okay, did the appropriate changes and fixed lint issues.

**Pull request merged**
