### PR TITLE
New package: dub-1.10.0

### PR DESCRIPTION
**Pull request by Follpvosten**
Dub is the source package manager and build system for Dlang projects. (This is my first completely new package, if anything is wrong with it, please tell me)

### CODE REVIEW

**Comment by Follpvosten** [comment]
I think everything should be fine now, sorry about that.

**Comment by SolitudeSF** [comment]
i can point out all the mistakes if you want, but here's more correct version.
```sh
# Template file for 'dub' 
pkgname=dub 
version=1.10.0 
revision=1 
hostmakedepends="dmd" 
makedepends="libcurl-devel" 
short_desc="Package/build management system for D projects" 
maintainer="Follpvosten <wolfi@karpador.xyz>" 
license="MIT" 
homepage="https://github.com/dlang/dub" 
distfiles="${homepage}/archive/v${version}.tar.gz" 
checksum=db6c3a9e45408d2431bc3d1138a31b561fb71665c1d89db4b0cb3725b2b12faa 
nocross=yes 
 
do_build() { 
        ./build.sh 
} 
 
do_install() { 
        vbin bin/dub 
        vlicense LICENSE 
} 
```
also, you need to squash commits.

**Comment by Follpvosten** [comment]
Thanks for the help! I applied the suggestions and also added `dmd` to the runtime depends - afaik, dub can work with any D compiler, but I don't think any others are packaged at the moment, so it makes sense.

I hope everything's right now.

**Comment by Follpvosten** [comment]
Sorry to bother again, but the checks have not actually failed. Something was wrong with the build pipeline at the time of commit as far as I can tell (as you can see in the build log, it failed at the stage "Installing xbps...").

How would I trigger another check to finally get this merged?

**Comment by SolitudeSF** [comment]
force push again

**Comment by Follpvosten** [comment]
Done, thanks!

**Comment by Follpvosten** [comment]
There should be a build log from when I first created this PR, I cannot really find it right now because the commits were squashed, so I don't know exactly what it was.

It might be because of [this line](https://github.com/void-linux/void-packages/blob/master/srcpkgs/dmd/template#L26) in the template for dmd.

So the nocross line should look like this:

    nocross=yes # because of dmd, see template line 26

Is that right?

**Comment by Hoshpak** [comment]
Yes, that's it. You can put the explanation right into the nocross field like `nocross="because of dmd, see template line 26"`. xbps-src just checks if nocross is not empty. The field was just set to `yes` in many templates earlier but giving an explanation will help people who might want to fix cross-compilation in the future.

**Comment by Follpvosten** [comment]
Thanks for the info! Didn't have time yesterday. Should be right now.

**Pull request merged**
