### PR TITLE
acme.sh: update to 3.0.5, adopt

### PR DESCRIPTION
**Pull request by filiprojek**
Tagging the maintainer @Wesley-Chan 

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)
- I built this PR locally for these architectures:
  - x86_64-musl

### CODE REVIEW

**Comment by filiprojek** [comment]
Since the original maintainer is inactive, I am willing to adopt this package.

**Comment by Wesley-Chan** [comment]
Please, by all means.

Thanks for you effort, filiprojek.

**Comment by abenson** [comment]
I see this is your first contribution; we prefer to see a few more before package adoption.

**Comment by filiprojek** [comment]
> I see this is your first contribution; we prefer to see a few more before package adoption.

would you merge this pull request if I remove the adoption?

**Comment by abenson** [comment]
I believe it would make it more likely for any of us.

**Comment by realcharmer** [comment]
I would adopt this if needed, so it, at least, has a regular maintainer. Same goes for `acme-client` #42741.

**Comment by filiprojek** [comment]
Alright, thanks

**Pull request merged**
