### PR TITLE
firefox: update to 66.0.

### PR DESCRIPTION
**Pull request by jnbr**
[ci skip]

### CODE REVIEW

**Comment by Duncaen** [comment]
One patch was moved to `srcpkgs/firefox/mallinfo.patch`.

**Comment by jnbr** [comment]
thanks, fixed

**Comment by jnbr** [comment]
armv7l and armv7l-musl fail with:

```
 2:17.81 In file included from /builddir/firefox-66.0/obj-armv7l-linux-gnueabihf/js/src/wasm/Unified_cpp_js_src_wasm2.cpp:29:
 2:17.81 /builddir/firefox-66.0/js/src/wasm/WasmSignalHandlers.cpp:520:19: error: field 'ufp' has incomplete type 'user_vfp'
 2:17.81    struct user_vfp ufp;
 2:17.81                    ^~~
 2:17.81 /builddir/firefox-66.0/js/src/wasm/WasmSignalHandlers.cpp:520:10: note: forward declaration of 'struct user_vfp'
 2:17.81    struct user_vfp ufp;
 2:17.81           ^~~~~~~~
 2:17.81 /builddir/firefox-66.0/js/src/wasm/WasmSignalHandlers.cpp:521:23: error: field 'ufp_exc' has incomplete type 'user_vfp_exc'
 2:17.81    struct user_vfp_exc ufp_exc;
 2:17.81                        ^~~~~~~
 2:17.81 /builddir/firefox-66.0/js/src/wasm/WasmSignalHandlers.cpp:521:10: note: forward declaration of 'struct user_vfp_exc'
 2:17.81    struct user_vfp_exc ufp_exc;
 2:17.81           ^~~~~~~~~~~~
```

**Comment by Duncaen** [comment]
https://dxr.mozilla.org/mozilla-central/source/js/src/wasm/WasmSignalHandlers.cpp#232-252

**Comment by jnbr** [comment]
all builds succeed now, x86_64, x86_64-musl and aarch64-musl are tested and work

**Pull request merged**
