### PR TITLE
void-updates: update to 20210324.

### PR DESCRIPTION
**Pull request by 42LoCo42**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by Johnnynator** [comment]
Why do you want to change this to something totally unrelated? Besides scripts like that do not meet the quality requirement for new packages.

**Comment by 42LoCo42** [comment]
I found the old void-updates script to be quite slow and computationally intensive.
Thus I rewrote it with the goal of maximum speed and stability.
My version is significantly faster, taking only a few seconds to generate a list of packages to upgrade.
If that is not the goal of the original script, I'm sorry that I have wasted your time with this PR.
Apart from that, I don't really see why my script would not meet the quality requirements.
Shellcheck reports no warnings and all functions have descriptive names, which eases debugging.

**Comment by ericonr** [comment]
@42LoCo42 please make a PR to the proper repository and it can be discussed there. Changing upstream of the script is not really an option.

**Comment by Johnnynator** [comment]
I think you didn't quite catch what the old script did. It checked upstream if the version in a template was old. You script checks if a package in your local binary repo is older than the template.

For what you do, take a look at xbps-checkvers (it is probably even faster than your script)

**Comment by ericonr** [comment]
That is, PR your code changes to void-updates repository.

**Comment by 42LoCo42** [comment]
Thank you all for enlightening me on this matter!

**Pull request closed without merging**
