### PR TITLE
igraph: update to 0.10.2.

### PR DESCRIPTION
**Pull request by tornaria**
#### Testing the changes
- I tested the changes in this PR: **briefly**

I run sagemath testsuite with this update.

### CODE REVIEW

**Comment by classabbyamp** [comment]
does `rankwidth` need to be revbumped for this?

**Comment by tornaria** [comment]
> does `rankwidth` need to be revbumped for this?

No, because it's statically linked. But maybe it should (so we make sure it still builds ok).

Maybe I should put together update SuiteSparse (#39846) + update igraph + revbump rankwidth. I'm not in a hurry with this, the priority is to get sagemath updated (#39876) and hopefully working with python 3.11.

BTW, the issue with SuiteSparse is that there are file conflicts between `SuiteSparse-devel` and `mongoose-devel`, but those already conflict in current versions (try `xlocate libmongoose`). I don't know if there's anything we can do about this. Hopefully the sonames remain different.

**Comment by szhorvat** [comment]
Note that SuiteSparse is no longer a dependency of igraph since version 0.10.

flex and bison are only needed if you are trying to build the development version from the git repo. If you build from the release archive, as you are doing now, they are not needed.

python3 is only needed if building the docs. The docs are already included in the release archive, so if you want to install them, you can just copy the `doc` folder directly, no need to build anything.

Regarding rankwidth: igraph 0.10 is not API-compatible with 0.9. Some very significant changes have been made, so basically every dependency will need source changes. rankwidth seems to be lucky in that a single very minor change allows it to build, see https://sourceforge.net/p/rankwidth/tickets/2/

**Comment by tornaria** [comment]
> Note that SuiteSparse is no longer a dependency of igraph since version 0.10.
> 
> flex and bison are only needed if you are trying to build the development version from the git repo. If you build from the release archive, as you are doing now, they are not needed.
> 
> python3 is only needed if building the docs. The docs are already included in the release archive, so if you want to install them, you can just copy the `doc` folder directly, no need to build anything.
> 
> Regarding rankwidth: igraph 0.10 is not API-compatible with 0.9. Some very significant changes have been made, so basically every dependency will need source changes. rankwidth seems to be lucky in that a single very minor change allows it to build, see https://sourceforge.net/p/rankwidth/tickets/2/
> 
> A short upgrade guide for package maintainers is here: [igraph/igraph#2134 (comment)](https://github.com/igraph/igraph/issues/2134#issuecomment-1220427403)

Thanks for the info, it will be very useful. I'm fighting with sage-on-python 3.11 with a deadline right now, but I will come back to this PR later and make sure igraph + rankwidth work ok.

**Comment by tornaria** [comment]
Force push:
- removed makedepends on SuiteSparse (no longer needed)
- removed hostmakedepends on flex, bison, python (not needed for the release tarball).
- patched rankwidth and revbump so it compiles with igraph 0.10.2
- tested by running sagemath testsuite after installing the new rankwidth.

**Pull request merged**
