### PR TITLE
New package: rust-sccache-0.2.8

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by jnbr** [comment]
why `rust-sccache` instead of `sccache`?

**Comment by Cogitri** [comment]
We don't really have a guideline for that yet, but there are some other rust-* packages already, e.g. `rust-cargo-audit` and `rust-cargo-bloat`. I feel like we should prefix them with rust- just like we also prefix ruby and python packages.

**Comment by jnbr** [comment]
We prefix libraries for python and ruby. For standalone tools, I see no good reason to diverge from upstream naming.

**Comment by maxice8** [comment]
> We prefix libraries for python and ruby.

ruby-travis, ruby-asciidoctor

**Comment by jnbr** [comment]
>>    We prefix libraries for python and ruby.

> ruby-travis, ruby-asciidoctor

Also ripgrep, not rust-ripgrep and ranger, not python-ranger.

I don't really care, I just see no point in diverging from upstream and our own Manual here.

**Comment by Cogitri** [comment]
I think we should just settle on one of the two for all packages then instead of having this naming inconsistency. IMHO prefixing them to avoid conflicts would be the best.

**Comment by Chocimier** [comment]
Manual and (mostly) practice now is that package naming is consistent with other packages that offer same type of interface.
Python libraries got prefixed with `python-`, no matter if they are written in Python or C. Rust libraries got `rust-` prefix. Packages with Command Line Interface have no prefix, whether they are written with Perl, C++ or Haskell.  And if they offer also shared object interface subpackage with `lib` prefix is created.

Do you know of any other sccache that can conflict? I do not think prefixing "just in case" is necessary.

**Pull request merged**
