### PR TITLE
vala: update to 0.56.9

### PR DESCRIPTION
**Pull request by Bnyro**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by Bnyro** [comment]
@paper42 why are the checks disabled for the vala package? They work fine on my native arch, so probably due to cross builds? I just need to know for fixing xlint here.

**Comment by Bnyro** [comment]
@paper42 what's the reason for setting `make_check=no` here? I'd like to fix xlint at that point here.

**Comment by paper42** [comment]
> @paper42 what's the reason for setting `make_check=no` here? I'd like to fix xlint at that point here.

there is no make_check=no, the tests are set as extended, I don't know why, maybe they take a lot of time or have some special requirements for the host system, you will have to figure that out and add that to the comment

**Comment by Bnyro** [comment]
I've been running one locally now and yes, they do take a lot of time.

**Comment by Bnyro** [comment]
And sorry for pinging you about that, I haven't found anyone else who recently updated vala

**Pull request merged**
