### PR TITLE
virtualbox-ose: update to 6.1.26.

### LINKED ISSUE #32327: VirtualBox breaks with Kernel 5.13
Support for Kernel 5.13 was added in VirtualBox 6.1.26 but current available version in Void is 6.1.20 so it breaks.

VirtualBox needs no be updated to latest 6.1.26 to work in Kernel 5.13

### PR DESCRIPTION
**Pull request by ericonr**
Remove vsed added in 13b1a5d83b4f3d03689a150c2ddf080ee91587c0 with no
justification; another configure step needed GCC version to have been
obtained.

It's broken: uses `-I/usr/include/qt5/QtGui/QtOpenGL` in flags instead of `-I/usr/include/qt5/QtOpenGL`, I can't find where that mistake happens. That can be fixed by fixing the `#include` in one of the files, because I can't find where these CXXFLAGS are set.

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

Closes #32327

### CODE REVIEW

**Comment by ericonr** [comment]
```
g++ -c -O2 -fPIC -g -pipe -Wall -Wextra -Wno-missing-field-initializers -Wno-trigraphs -fdiagnostics-show-option -Wlogical-op -Wno-variadic-macros -frtti -fno-exceptions -Wno-long-long -fshort-wchar -fno-strict-aliasing -fvisibility=hidden -DVBOX_HAVE_VISIBILITY_HIDDEN -DRT_USE_VISIBILITY_DEFAULT -fvisibility-inlines-hidden -Wno-multistatement-macros -Wno-ignored-qualifiers  -std=c++11   -Wno-deprecated-declarations -fPIC -Wno-deprecated-copy -g -pipe -Wall -Wextra -Wno-missing-field-initializers -Wno-trigraphs -fdiagnostics-show-option -Wlogical-op -Wno-variadic-macros -frtti -fno-exceptions -Wno-long-long -fshort-wchar -fno-strict-aliasing -fvisibility=hidden -DVBOX_HAVE_VISIBILITY_HIDDEN -DRT_USE_VISIBILITY_DEFAULT -fvisibility-inlines-hidden -Wno-multistatement-macros -Wno-ignored-qualifiers  -std=c++11   -Wno-deprecated-declarations -fPIC -m64 -I/builddir/VirtualBox-6.1.26/src/VBox/Frontends/VirtualBox/include -I/builddir/VirtualBox-6.1.26/out/linux.amd64/release/bin/sdk/bindings/xpcom/include -I/builddir/VirtualBox-6.1.26/out/linux.amd64/release/bin/sdk/bindings/xpcom/include/xpcom -I/builddir/VirtualBox-6.1.26/out/linux.amd64/release/bin/sdk/bindings/xpcom/include/string -I/builddir/VirtualBox-6.1.26/out/linux.amd64/release/bin/sdk/bindings/xpcom/include/xpcom -I/builddir/VirtualBox-6.1.26/out/linux.amd64/release/bin/sdk/bindings/xpcom/include/nsprpub -I/builddir/VirtualBox-6.1.26/out/linux.amd64/release/bin/sdk/bindings/xpcom/include/ipcd -I/usr/include/qt5/QtGui/QtOpenGL -I/usr/include/qt5/QtGui -I/builddir/VirtualBox-6.1.26/out/linux.amd64/release/obj/VBoxOGL2D/qtmoc -I/builddir/VirtualBox-6.1.26/out/linux.amd64/release/obj/VBoxOGL2D/qtuic -I/builddir/VirtualBox-6.1.26/include -I/builddir/VirtualBox-6.1.26/out/linux.amd64/release -DVBOX -DVBOX_OSE -DVBOX_WITH_64_BITS_GUESTS -DRT_OS_LINUX -D_FILE_OFFSET_BITS=64 -DRT_ARCH_AMD64 -D__AMD64__ -DVBOX_WITH_DEBUGGER -DVBOX_WITH_HARDENING -DRTPATH_APP_PRIVATE=\"/usr/share/virtualbox\" -DRTPATH_APP_PRIVATE_ARCH=\"/usr/lib/virtualbox\" -DRTPATH_SHARED_LIBS=\"/usr/lib/virtualbox\" -DRTPATH_APP_DOCS=\"\" -DPIC -DIN_RING3 -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DHAVE_CONFIG_H -DHC_ARCH_BITS=64 -DGC_ARCH_BITS=64 -DVBOX_WITH_XPCOM -DVBOX_WITH_XPCOM_NAMESPACE_CLEANUP -DPIC -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DHAVE_CONFIG_H -DVBOX_WITH_VIDEOHWACCEL -DVBOX_GUI_USE_QGL -DQT_OPENGL_LIB -D_REENTRANT -Wp,-MD,/builddir/VirtualBox-6.1.26/out/linux.amd64/release/obj/VBoxOGL2D/src/VBoxGLSupportInfo.o.dep -Wp,-MT,/builddir/VirtualBox-6.1.26/out/linux.amd64/release/obj/VBoxOGL2D/src/VBoxGLSupportInfo.o -Wp,-MP -o /builddir/VirtualBox-6.1.26/out/linux.amd64/release/obj/VBoxOGL2D/src/VBoxGLSupportInfo.o  /builddir/VirtualBox-6.1.26/src/VBox/Frontends/VirtualBox/src/VBoxGLSupportInfo.cpp
/builddir/VirtualBox-6.1.26/src/VBox/Frontends/VirtualBox/src/VBoxGLSupportInfo.cpp:22:10: fatal error: QGLWidget: No such file or directory
   22 | #include <QGLWidget>
      |          ^~~~~~~~~~~
compilation terminated.
kmk: *** [/builddir/VirtualBox-6.1.26/kBuild/footer-pass2-compiling-targets.kmk:277: /builddir/VirtualBox-6.1.26/out/linux.amd64/release/obj/VBoxOGL2D/src/VBoxGLSupportInfo.o] Error 1
kmk: *** Waiting for unfinished jobs....
```

I figure the include can be changed to `<qt5/QtOpenGL/QGLWidget>`.

**Comment by ericonr** [comment]
I might have a fix, let's see.

**Comment by amak79** [comment]
> I can't find where that mistake happens.

Relevant? https://www.virtualbox.org/changeset/90377/vbox

**Comment by ericonr** [comment]
Don't think so, what I did was

```diff
diff --git a/srcpkgs/virtualbox-ose/files/LocalConfig.kmk b/srcpkgs/virtualbox-ose/files/LocalConfig.kmk
index 71ffd9876c..d283c39363 100644
--- a/srcpkgs/virtualbox-ose/files/LocalConfig.kmk
+++ b/srcpkgs/virtualbox-ose/files/LocalConfig.kmk
@@ -15,6 +15,7 @@ VBOX_WITH_REGISTRATION_REQUEST =
 VBOX_WITH_UPDATE_REQUEST =
 VBOX_USE_SYSTEM_XORG_HEADERS = 1
 VBOX_NO_LEGACY_XORG_X11 = 1
+PATH_SDK_QT5_INC := /usr/include/qt5
 # Enable it when vnc pkg is available.
 #VBOX_WITH_VNC := 1
 VBOX_GCC_WERR =
```

**Comment by ericonr** [comment]
Built successfully here, let's see.

**Pull request merged**
