### PR TITLE
PHP updates

### PR DESCRIPTION
**Pull request by TinfoilSubmarine**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by Johnnynator** [comment]
Can we also enable fpm acls? `--with-fpm-acl`

It is kinda weird that we use the `http` user as default for `fpm` without creating this user anywhere, but on the other hand we don't have a single "web" user like `www-data` or `http` for web servers and apache, nginx, caddy all have their own user.  Not sure if there could exist a good default for the fpm user considering all the other packages.

**Comment by TinfoilSubmarine** [comment]
> It is kinda weird that we use the `http` user as default for `fpm` without creating this user anywhere, but on the other hand we don't have a single "web" user like `www-data` or `http` for web servers and apache, nginx, caddy all have their own user. Not sure if there could exist a good default for the fpm user considering all the other packages.

Maybe there should be a default though, even if it isn't good. That way when a user installs an `.*fpm` package the runit service isn't broken out-of-the-box.

**Comment by TinfoilSubmarine** [comment]
> Can we also enable fpm acls? `--with-fpm-acl`

Done

**Comment by TinfoilSubmarine** [comment]
So as I'm thinking about this, the acl was the missing piece for my setup to not really care about what user `php-fpm` is running with. Now I just do `listen.acl_users = caddy` and be done with it.

Are there any other use cases that would actually care what user the process is running as?

**Comment by Johnnynator** [comment]
> So as I'm thinking about this, the acl was the missing piece for my setup to not really care about what user `php-fpm` is running with. Now I just do `listen.acl_users = caddy` and be done with it.

You could have gotten this with `listen.owner = caddy`

> Are there any other use cases that would actually care what user the process is running as?

All these depend on what the user wants. The general read-only, just execute some php, use-case with a `755`/`644` permission on the web directory doesn't really care. It starts to matter once you have like writable directories, strict permissions for certain files.
But these cases have to be handled by the user either way.

**Comment by TinfoilSubmarine** [comment]
I have just updated all of the packages in this PR to the latest available versions. 

Is there anything else that needs to be addressed from your end @Johnnynator? I have added `_phpfpm` user creation.

Otherwise, if there is nothing else could we get this merged? I would like to start working on adding PHP 8.4.

**Pull request merged**
