### PR TITLE
Added INSTALL.msg for libreoffice

### PR DESCRIPTION
**Pull request by MrLazerbean**
Add an install message for libreoffice so people will know that they may need one after install

### CODE REVIEW

**Comment by Duncaen** [comment]
We generally preserve INSTALL.msg for important changes, adding more will just increase the fact that users are already rarely noticing or reading them.

**Comment by MrLazerbean** [comment]
I agree, but at the same time for many users libre office wont work without a language package. When I installed libre office I had to go looking on reddit in order to find out about these packages at all. If there is a better way to get this info to users than a INSTALL.msg that I am unaware of please let me know.

**Comment by mmnmnnmnmm** [comment]
A few packages use localisation in this way:

    $ xbq -i18n | awk -v FS="( |-i18n-)" '{print $2}' | sort -u
    firefox
    firefox-esr
    icecat
    kicad
    libreoffice
    python3-precis
    thunderbird

This looks like a good candidate to put in the docs
https://github.com/void-linux/void-docs

**Comment by ericonr** [comment]
@MrLazerbean do you think the PR can be closed now? void-docs has information about localization packages now.

**Comment by MrLazerbean** [comment]
Yes, closing it now. Forgot about it lol

**Pull request closed without merging**
