### PR TITLE
libbluray: enable building bdjava

### LINKED ISSUE #21641: libbluray needs to build .jar for bluray menus to work
### System

* xuname:  
  Void 5.4.38_1 x86_64 GenuineIntel uptodate rrrmFFFF
* package:  
  libbluray-1.2.0_1

### Expected behavior
Blurays play fine in VLC, including their menus.

### Actual behavior
VLC tells me that it can only play blurays in no-menus mode because I don't have Java installed, even though I do have Java installed.

### But what does this have to do with the libbluray package?
To make a long story short, I did some digging and figured out that the problem is that I don't have libbluray.jar anywhere on my system (and that multiple developers deserve to suffer a public drubbing for their lazy error messages.)
The xbps template for the libbluray package has a flag set to explicitly not build the .jar. I don't know why that option is set, but the .jar seems to be important for anyone who wants to watch blurays with menus. (For TV shows, this includes having any ability to play the episodes in their correct order.)

### PR DESCRIPTION
**Pull request by ericonr**
Fixes #21641 

I'm assuming optimizations were disabled for some reason, we could consider re-enabling them. @DeepwaterCreations, if you could test this out? I'd like to know if it can work without Java installed, because it currently doesn't have Java as a hard dependency.

### CODE REVIEW

**Comment by DeepwaterCreations** [comment]
Hmm... now I can't get anything but
```
[00007f9ac8001120] libbluray demux error: BD-J menus not supported. Playing without menus. BD-J support: 1, JVM found: 0, JVM usable: 0
```
even with openjdk installed... but that doesn't go away if I revert back to the unmodified libbluray template, so it might be some unrelated problem. (Previously it was `JVM found: 1, JVM usable: 0`)

**Comment by DeepwaterCreations** [comment]
Okay, never mind, I sorted my issue out. It was just a problem with JDK_HOME not being set.
So with your changes, the package installs with or without Java installed, and it does indeed fix my original problem. :+1:

**Comment by abenson** [comment]
Hm, menus work for me but sound doesn't... I haven't done much with bluray so I don't know if this disc or not.

**Comment by abenson** [comment]
Sound works... turns out the speakers turn off if you have headphones plugged in.

**Pull request merged**
