### PR TITLE
New package: greenclip-4.2

### PR DESCRIPTION
**Pull request by kawaiiamber**
Closes [this](https://github.com/void-linux/void-packages/issues/26187)

### CODE REVIEW

**Comment by kawaiiamber** [comment]
On some archs, it fails with:
```
--  While building package X11-1.9.2 (scroll up to its section to see the error) using:
      /tmp/stack-4206a322125a5924/X11-1.9.2/.stack-work/dist/x86_64-linux/Cabal-3.0.1.0/setup/setup --builddir=.stack-work/dist/x86_64-linux/Cabal-3.0.1.0 configure --user --package-db=clear --package-db=global --package-db=/builddir/greenclip-3.4/.stack/snapshots/x86_64-linux/3840f607810bca29e8c4f3fb38a11fff24b1a0f241b8b4aa1607d8ca5a10ac7a/8.8.4/pkgdb --libdir=/builddir/greenclip-3.4/.stack/snapshots/x86_64-linux/3840f607810bca29e8c4f3fb38a11fff24b1a0f241b8b4aa1607d8ca5a10ac7a/8.8.4/lib --bindir=/builddir/greenclip-3.4/.stack/snapshots/x86_64-linux/3840f607810bca29e8c4f3fb38a11fff24b1a0f241b8b4aa1607d8ca5a10ac7a/8.8.4/bin --datadir=/builddir/greenclip-3.4/.stack/snapshots/x86_64-linux/3840f607810bca29e8c4f3fb38a11fff24b1a0f241b8b4aa1607d8ca5a10ac7a/8.8.4/share --libexecdir=/builddir/greenclip-3.4/.stack/snapshots/x86_64-linux/3840f607810bca29e8c4f3fb38a11fff24b1a0f241b8b4aa1607d8ca5a10ac7a/8.8.4/libexec --sysconfdir=/builddir/greenclip-3.4/.stack/snapshots/x86_64-linux/3840f607810bca29e8c4f3fb38a11fff24b1a0f241b8b4aa1607d8ca5a10ac7a/8.8.4/etc --docdir=/builddir/greenclip-3.4/.stack/snapshots/x86_64-linux/3840f607810bca29e8c4f3fb38a11fff24b1a0f241b8b4aa1607d8ca5a10ac7a/8.8.4/doc/X11-1.9.2 --htmldir=/builddir/greenclip-3.4/.stack/snapshots/x86_64-linux/3840f607810bca29e8c4f3fb38a11fff24b1a0f241b8b4aa1607d8ca5a10ac7a/8.8.4/doc/X11-1.9.2 --haddockdir=/builddir/greenclip-3.4/.stack/snapshots/x86_64-linux/3840f607810bca29e8c4f3fb38a11fff24b1a0f241b8b4aa1607d8ca5a10ac7a/8.8.4/doc/X11-1.9.2 --dependency=base=base-4.13.0.0 --dependency=data-default=data-default-0.7.1.1-5cjrhz8y8DG881Qqkxq9GB --exact-configuration --ghc-option=-fhide-source-paths
    Process exited with code: ExitFailure 77
```
I wonder if I need to do something like:
```
case "${XBPS_TARGET_MACHINE}" in
    aarch64*)
    <compile options>
    ;;
    armv6l* | armv7l*)
    <compile options>
    ;;
esac
```
in `do_install` as, for those archs, the build flags / options have issues with the `X11` headers? I'm not too familiar with the archs that it's failing on. I wonder if it's also worth just saying `archs="x86_64* i686"`.

**Comment by kawaiiamber** [comment]
On the archs that it's failing on:
```
X11                              > Configuring X11-1.9.2...
X11                              > configure: WARNING: unrecognized options: --with-compiler
X11                              > checking for gcc... /usr/bin/cc
X11                              > checking whether the C compiler works... no
X11                              > configure: error: in `/tmp/stack-ad9194d8222f383b/X11-1.9.2/.stack-work/dist/x86_64-linux/Cabal-3.0.1.0/build':
X11                              > configure: error: C compiler cannot create executables
X11                              > See `config.log' for more details
```
I wonder why the C compiler doesn't work on these archs. I have interest in trying to fix this rather than setting `nocross` if possible. I only have a musl machine. Is there a way for me to see this `config.log` for more details?

**Comment by kawaiiamber** [comment]
Okay, I'll try `./xbps-src -a aarch64-musl pkg greenclip` and look inside the `$wrksrc` directory for config.log and see if I can't fix it.

**Comment by kawaiiamber** [comment]
Recently discovered through the IRC that cross build currently don't work with Haskell. Plus, there seems to be a march switch check upstream anyways.

**Comment by FollieHiyuki** [comment]
4.0 came out

**Comment by kawaiiamber** [comment]
> 4.0 came out

Updated template to 4.0 and built locally with `xbps-src`.

**Comment by FollieHiyuki** [comment]
Ping for 4.2

**Comment by kawaiiamber** [comment]
> Ping for 4.2

Updated template to 4.2

**Comment by kawaiiamber** [comment]
bump

**Pull request closed without merging**
