### PR TITLE
New package: intel-media-driver-19.3.1

### PR DESCRIPTION
**Pull request by st3r4g**
https://github.com/intel/media-driver
> The Intel(R) Media Driver for VAAPI is a new VA-API (Video Acceleration API) user mode driver supporting hardware accelerated decoding, encoding, and video post processing for GEN based graphics hardware.

This is a new `libva` backend for Broadwell+ GPUs. Also introduces a dependent library package. Is package naming fine? Other backends are currently called `libva-*`. I think this only makes sense on `i686* x86_64*` archs.
Tested on `x86_64-musl`

### CODE REVIEW

**Comment by st3r4g** [comment]
> Media driver supports two build types as below:
Full Feature Build is default driver build, which supports all feature by hardware accelerator and close source shaders(media kernel binaries). Ubuntu intel-media-va-driver-non-free package is generated from this build type.
Free Kernel Build, enables fully open source shaders(media kernels) and hardware features but the features would be limited. Ubuntu intel-media-va-driver package is generated from this build type.

It seems there are closed source bits with default configuration. Should I create two different templates or make the close source shaders an option?

**Comment by xtraeme** [comment]
Yes, pleasd

**Comment by xtraeme** [comment]
I prefer two pkgs, this way the user only needs to install them.

**Comment by st3r4g** [comment]
> I prefer two pkgs, this way the user only needs to install them.

But in this way I'll have to create a duplicate template, if I understand correctly. I don't think most users will care for the additional features of the closed source kernels. I'll leave it as a build option for now, I'll reconsider that if there are specific requests.

**Comment by xtraeme** [comment]
OK. But please enable it by def

**Comment by xtraeme** [comment]
And then let's see

**Comment by st3r4g** [comment]
> OK. But please enable it by def

So I must put it in the nonfree repo right?

**Comment by xtraeme** [comment]
Hmm. So enabling the option builds extra lis?

**Comment by st3r4g** [comment]
> Hmm. So enabling the option builds extra libs?

?? no... but if BUILD_NONFREE_KERNELS is ON by default we have a package with nonfree bits in the `current/` repo

**Comment by xtraeme** [comment]
So the affected libs are modified with new symbols?

**Comment by xtraeme** [comment]
looking at this one now

**Comment by xtraeme** [comment]
merged

**Pull request closed without merging**
