### PR TITLE
fontmatrix: remove

### PR DESCRIPTION
**Pull request by maxice8**
Dead upstream, depends on qt4

@newbluemoon

### CODE REVIEW

**Comment by newbluemoon** [comment]
Well, according to this https://github.com/fontmatrix/fontmatrix/issues/13#issuecomment-435597820 the code is “unstable as hell and unmaintained”. Probably (but sadly) a good idea to remove it. It was helpful to me a few times in the past.

Don’t know if other Void users used it and if they might have objections, but I guess I’m ok with the removal. As long as Qt4 is in the repository I can always build it locally if needed. ;)

**Comment by dicktyr** [comment]
I found it useful and was disappointed to see it removed

it's not dead; it's even [somewhat stirring](https://github.com/fontmatrix/fontmatrix/commits/master) rather than resting!

**Comment by dicktyr** [comment]
indeed, it is not dead and has been ported to QT5

https://github.com/fontmatrix/fontmatrix/releases/tag/v0.9.100

**Comment by newbluemoon** [comment]
Alright, I’ll try to package it again, the reasons why it was removed seem to be no longer valid. :)

**Comment by dicktyr** [comment]
that's the spirit! :}

**Pull request merged**
