### PR TITLE
protobuf: update to 3.11.2

### PR DESCRIPTION
**Pull request by ahesford**
This PR updates the protobuf package and subpackages to version 3.11.2. Google updates the major version of its shared libraries with every release, and this moves libproto*.so.18 to libproto*.so.22. Accordingly, this PR also:

* Revbumps all packages dependent on these shlibs
* Renames the libproto{c,buf,buf-lite}18 subpackages to drop the major version from the name
* Adds "replaces" directives to these subpackages to record the name change.

cc: @the-maldridge

### CODE REVIEW

**Comment by ahesford** [comment]
> The revbumps should each be in separate commits. The versioned sub-packages were introduced to be able to install two versions of the library at the same time and avoid staging on the build servers so they should probably be kept. The replaces is incorrect in any case I think.

Please hold. I'm locally testing rework based on your suggestions and what I've seen with boost packaging:

* Keep libprotobuf18 and libprotoc18
* Version all existing protobuf subpackages:
  - protobuf -> protobuf18
  - protobuf-lite -> protobuf18-lite
  - libprotoc-devel -> libprotoc18-devel
* Rename libprotobuf-lite18 -> libprotobuf18-lite; add a replaces declaration in the subpackage for this name change (this is easier to parse in directory listings, it fits with the protobuf->protobuf18 change, and makes logical sense because the library is the light version of protobuf 18)
* Create new, non-versioned (sub)packages protobuf{,-devel,lite} and libprotoc-devel for protobuf 3.11.2
* Create new, versioned subpackages libprotobuf22{,-lite} and libprotoc22
* Add conflicts with the unversioned new packages in protobuf18{,-devel} and libprotoc18-devel

In future updates, the procedure would look the same: migrate the unversioned packages to protobuf22 or libprotoc22, create a new unversioned master package with {-devel,-lite} and libprotoc-devel subpackages, and create new versioned subpackages for the shared libraries.

Does this seem reasonable? When my local tests pass, I'll push them here.

**Comment by xtraeme** [comment]
Yeah, versioned pkgs seems to be a good solution to me

**Comment by ahesford** [comment]
As requested: versioning on the old packages and new shared library subpackages, one commit for each revbump (complete with a few cleanups to fix some build errors).

**Comment by jnbr** [comment]
This pull request is too large for Travis CI.
Please add  a line containing `[ci skip]` to your latest commit message (HEAD) to avoid blocking the travis queue.

**Comment by ahesford** [comment]
Just pinging here, I modified the PR to build protobuf 3.11.3 instead of 3.11.2 because the former was recently released.

**Comment by ahesford** [comment]
Bumped to protobuf 3.11.4

**Pull request merged**
