### PR TITLE
element-desktop: update to 1.7.3.

### PR DESCRIPTION
**Pull request by ProjectMoon**

### CODE REVIEW

**Comment by ProjectMoon** [comment]
Now updated to 1.7.3.

**Comment by Chocimier** [comment]
You should build and test updated version before submitting PR.

**Comment by ProjectMoon** [comment]
It seems they changed the directory name in between 1.7.2 and 1.7.3.

**Comment by ProjectMoon** [comment]
Should build now.

**Comment by ProjectMoon** [comment]
I have been testing Element 1.7.3 for a week or two now, and it looks like it works fine.

**Pull request merged**
