### PR TITLE
New Package: mcos-mjv-xfce-edition-0

### PR DESCRIPTION
**Pull request by LinArcX**
a GTK3-theme/ XWM4-theme:

https://github.com/paullinuxthemer/McOS-MJV-XFCE-Edition

### CODE REVIEW

**Comment by Chocimier** [comment]
Lot of failures. Did you build it locally before pushing?

**Comment by Piraty** [comment]
As discussed a few times before (in the old, now gone, gh-repo and on IRC), Void prefers to not package more themes, icons, mouse cursors etc., especially if they are derivatives of other themes, possibly contain work of dubious licensing situation or are expected to not be of interest for most users.
The policy mostly was/is to provide themes that are used by the main desktop environments, and it is expected that such things can easily installed by users on their own.

**Comment by LinArcX** [comment]
@Piraty 
Hi again. I'v noticed that there are lots of theme packages in void repo that don't belong to any specific desktop environments. like:
1.  numix-themes
2. paper-gtk-theme
3. tango-icon-theme
4. yaru
5. faience-icon-theme
...
And some other themes and icon-themes. 
My question is why these packages can exists in void repo but my packages can't?
Edit: the license of mcos-mjv-xfce-edition is gpl-2. So it's free and open source project!

**Comment by Chocimier** [comment]
\> Void prefers to not package **more** themes

That's that simple.

You can still put your favourite themes into home dir, or build and install form private template.

**Pull request closed without merging**
