### PR TITLE
New package: font-jetbrainsmono-ttf-1.0.6

### PR DESCRIPTION
**Pull request by alferguet**
New free TrueType font with ligatures by the JetBrains team for their IDEs but also available standalone.

I needed to open the new pull request from #18671 because no longer have access to the old fork and some modifications were required asides from the update, made by @gcat432 .

### CODE REVIEW

**Comment by gcat432** [comment]
Can this somehow please be reviewed and merged? @Hoshpak maybe?
An update of the version is needed now, but that could be done later, at worse.

**Comment by alferguet** [comment]
> 
> 
> Can this somehow please be reviewed and merged? @Hoshpak maybe?
> 
> An update of the version is needed now, but that could be done later, at worse, unless @alferguet is willing to do it before.

Yup, I can get around to it this evening, but anyway surprises me this hasn't been reviewed yet, thought as the second PR would get more attention.

**Comment by alferguet** [comment]
Updated to the newest version!

**Comment by Chocimier** [comment]
We usually do not accept eyecandy that can be dropped into homedir. There are some fonts in repo already, and including everyone's favourite is not our goal.

**Comment by alferguet** [comment]
I understand, but wouldn't have done the pull request without thinking it was popular enough to have it in the repository.

Hope in the future if many people are requesting this you could merge it. Thanks!

**Pull request closed without merging**
