### PR TITLE
mandrel: update to 23.0.1.2; update revdeps

### PR DESCRIPTION
**Pull request by icp1994**
#### Testing the changes
- I tested the changes in this PR: **briefly** (built `jet`, included in PR)

#### Local build testing
- I built this PR locally for my native architecture: **x86_64**

cc @leahneukirchen

### CODE REVIEW

**Comment by icp1994** [comment]
I'm not sure the patch is necessary. The source file it patched was completely removed with it's parent dir. Found some similar code at `substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/libc/HostedMuslLibC.java`

**Comment by leahneukirchen** [comment]
The patch is needed if it links musl statically else (easy to verify).

Please also rebuild Babashka.

**Comment by icp1994** [comment]
> The patch is needed if it links musl statically else (easy to verify).

Does that require a musl system to verify?

**Comment by leahneukirchen** [comment]
```
2023-07-16T11:06:37.4448375Z => babashka-1.3.181_1: running post-install hook: 06-strip-and-debug-pkgs ...
2023-07-16T11:06:37.8129728Z    Stripped static executable: /usr/bin/bb
```

We want this dynamically linked.

**Comment by leahneukirchen** [comment]
Something is wrong, bb and jet are still static binaries on x86_64-musl.

**Comment by leahneukirchen** [comment]
Hmm, looks like the linker doesn't get passed `fPIE` or so.

**Comment by leahneukirchen** [comment]
You need to patch /mandrel-mandrel-23.0.0.0-Final/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/libc/HostedMuslLibC.java `getAdditionalLinkerOptions` which hard-codes `-no-pie`.

**Comment by leahneukirchen** [comment]
Then this is good to go, I think!

**Comment by icp1994** [comment]
Do you want me to remove the `musl.patch` file again then? I don't think it's doing anything we need.

**Comment by leahneukirchen** [comment]
Okay, but please keep the line that non-static is broken on musl.

**Pull request merged**
