### PR TITLE
znc: update to 1.7.2.

### PR DESCRIPTION
**Pull request by prspkt**

### CODE REVIEW

**Comment by Duncaen** [comment]
Same here, why is it necessary to produce bigger diffs just to alphabetically order fields the update doesn't even touch.

I'm curious why you update those packages they were both released within the last 24 hours, did you test them?

**Comment by prspkt** [comment]
@Duncaen  Sometimes running `xmindep` results in less dependencies being explicitly declared in the template. But you're right, it does create more _noise_ and is not related to the update.
I think the http to https change is safe to keep.

**Comment by Duncaen** [comment]
Yes http → https is good, reading the ZNC change log seem like a "safe" update.
Did you test it, or should I build it and test it with my setup too?

**Comment by prspkt** [comment]
@Duncaen Yes `znc-1.7.2` builds and tests OK on both x86_64 and x86_64-musl.

**Comment by maxice8** [comment]
I'd rather not xmindep stuff or rather xmindep only stuff that isn't linked in the final binary.

making and encouraging xtrimdeps was a mistake

**Pull request merged**
