### PR TITLE
[RFC] switch patch_args to -Np1

### PR DESCRIPTION
**Pull request by sgn**
[ci skip]

Being suggested on IRC @void-linux/pkg-committers

### CODE REVIEW

**Comment by q66** [comment]
we should not do it this way, we should instead patch all the patches as needed

**Comment by sgn** [comment]
> we should not do it this way, we should instead patch all the patches as needed

Yes, but I would like to do it step by step in order to limit the # of changes in each step. I.e. the next change will be patching the patch for packages start with "a".

**Comment by Vaelatern** [comment]
I think q66 is right, we should alter patches on a per-template basis when the template comes up again.

**Comment by sgn** [comment]
> I think q66 is right, we should alter patches on a per-template basis when the template comes up again.

I think q66 meant to alter all patches in one pass?

**Comment by q66** [comment]
i just wonder if there's a point in doing it like this and not just modifying all the patches in one pass (considering it appears scriptable)

**Comment by sgn** [comment]
> i just wonder if there's a point in doing it like this and not just modifying all the patches in one pass (considering it appears scriptable)

I think it's easier to scripted-check obviously-incorrect-change when doing like this. i.e. a single change for adding -Np0, single change for fixing patches. In fact, I think it's better to keep `-Np0` for `antiword` and `daemontools` when reviewing.

**Comment by Gottox** [comment]
There's a way to make patches compatible with both `-p0` and `-p1`. This would allow to progressively move from -p0 to -p1:

```diff
--- ./aaa	2021-06-18 15:32:17.698429013 +0200
+++ ./bbb	2021-06-18 15:32:21.679428845 +0200
@@ -1 +1 @@
-aaa
+bbb
```

**Comment by q66** [comment]
that seems pretty sketchy to me, i think we can just convert them properly

**Comment by sgn** [comment]
> There's a way to make patches compatible with both `-p0` and `-p1`. This would allow to progressively move from -p0 to -p1:
> 
> ```diff
> --- ./aaa	2021-06-18 15:32:17.698429013 +0200
> +++ ./bbb	2021-06-18 15:32:21.679428845 +0200
> @@ -1 +1 @@
> -aaa
> +bbb
> ```

Looks nice but we're patching it, let's just patch it properly.

Everything is done, now. We should make decision soon.

**Comment by ericonr** [comment]
I don't see why not go forward with it. `-Np1` is the default for almost all tooling.

**Comment by q66** [comment]
i haven't seen any opposition, so maybe let's just do it?

**Comment by ahesford** [comment]
+1 to go

**Comment by the-maldridge** [comment]
LGTM, thanks for taking the initiative on this!

**Pull request merged**
