### PR TITLE
New package: KITScenarist-0.7.2.rc9h

### PR DESCRIPTION
**Pull request by abenson**
Can someone help with the cross issue?

### CODE REVIEW

**Comment by abenson** [comment]
For now, I've marked it `nocross`, but the error is:

    /usr/lib/gcc/aarch64-linux-gnu/9.2.0/../../../../aarch64-linux-gnu/bin/ld: 
                     ../../build/Release/bin/scenarist-desktop/.obj/SpellChecker.o: in function 
                     `SpellChecker::addWordToChecker(QString const&) const':
    SpellChecker.cpp:(.text+0x1130): undefined reference to `Hunspell::add(char const*)'

Adding `hunspell-devel` to `makedepends` nor `hostmakedepends` helped

**Comment by ndowens** [comment]
> Can someone help with the cross issue?

I’ll try to remember to look at cross later today when I can

**Comment by ndowens** [comment]
Currently looks like it isn’t adding -lhunspell, I got to find where it is defining ldflags, may be a little while after I start on it as I am not use to qmake stuff

**Comment by abenson** [comment]
Patching it to use to system hunspell seems to have fixed it.

**Comment by ndowens** [comment]
Ah good, that was my other thought that might be the issue, as it was using
it's own

**Comment by ndowens** [comment]
arm*) broken="qt5-webengine-devel not available for arm"

**Pull request closed without merging**
