### PR TITLE
New package: GPXSee-8.3

### PR DESCRIPTION
**Pull request by 0-st**
Only tested on x86_64 and x86_64-musl

### CODE REVIEW

**Comment by kawaiiamber** [comment]
```
=> ERROR: GPXSee-7.36_1: Could not find qmake - missing in hostdepends?
Error: Process completed with exit code 1.
```
This is the error for the failed checks. You might try adding `qt-qmake` or `qt5-qmake` (idk which one it wants) to `hostdepends` (on the archs that it's failing) by the sound of it.

**Review by kawaiiamber — CHANGES_REQUESTED** [review]
Add `qt5-qmake` and `qt5-host-tools` to `hostmakedepends` to pass cross build. I tested on aarch64-musl.

**Comment by Sarkasper** [comment]
> Add `qt5-qmake` and `qt5-host-tools` to `hostmakedepends` to pass cross build. I tested on aarch64-musl.

Thanks

**Comment by kawaiiamber** [comment]
```
ERROR: [trans] failed to download `libpciaccess-0.16_1' signature from `http://alpha.us.repo.voidlinux.org/current/musl': Transient resolver failure
Transaction failed! see above for errors.
eudev-libudev-devel-3.2.9_1: verifying RSA signature...
Error: Process completed with exit code 1.
```
That's just CI messing up. Just rebase against upstream master and repush and it should pass.

**Pull request closed without merging**
