### PR TITLE
base-files: initialise empty etc/modules-load.d folder

### PR DESCRIPTION
**Pull request by NeelChotai**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Please rebase, and hold this change for a bit. I want to see if we can ship directories in XBPS.

**Comment by fosslinux** [comment]
Is there a compelling reason for this? (I do not see one). It's very trivial to mkdir `/etc/modules-load.d` if you want that. This adds confusion to users, IMO, but that's just me. (Either way I don't really mind, though).

**Comment by NeelChotai** [comment]
> Is there a compelling reason for this? (I do not see one). It's very trivial to mkdir `/etc/modules-load.d` if you want that. This adds confusion to users, IMO, but that's just me. (Either way I don't really mind, though).

If an empty `etc/modprobe.d` folder is initialised, it stands to reason that an empty `etc/modules-load.d` should also be initialised.

**Comment by ericonr** [comment]
To avoid holding this up indefinitely, I'm pushing as is. Doing a bigger fix can come later.

**Pull request merged**
