### PR TITLE
New package: codec2-1.0.1

### PR DESCRIPTION
**Pull request by unspecd**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-musl
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-musl

### CODE REVIEW

**Comment by unspecd** [comment]
Some tests failed with the message saying something about regular expressions:
```
 94/120 Test  #94: test_fsk_modem_octave_port .....................***Failed  Required regular expression not found. Regex=[PASS
]  0.37 sec
```

**Comment by Chocimier** [comment]
They use regexes after test action to validate result. "Required regular expression not found" means "test fail". Important lines are "???: command not found". Add them to checkdepends.
You can run tests locally with `./xbps-src pkg -Q codec2`.

**Comment by unspecd** [comment]
They use octave, but the signal processing package is missing.
```
$ octave-cli
octave:1> pkg load signal
error: package signal is not installed
error: called from
    load_packages at line 47 column 7
    pkg at line 588 column 7
```

https://github.com/drowe67/codec2:
> 1. Install GNU Octave and libraries on Ubuntu with:
>
> sudo apt install octave octave-common octave-signal liboctave-dev gnuplot python3-numpy sox valgrind

**Comment by Chocimier** [comment]
Then disable tests depending on octave like networkmanager-qt5 do.

**Pull request merged**
