### PR TITLE
Add GitHub site

### PR DESCRIPTION
**Pull request by maybe-one-day-ubermensch**

### CODE REVIEW

**Comment by leahneukirchen** [comment]
Why? There are no GitHub mirrors.

**Comment by maybe-one-day-ubermensch** [comment]
I apologize for not elaborating further in my original post. I was rereading the Manual and came across the part where it talks about the sites. The global variables are provided to avoid repetition and since I frequently see github's site being used in distfiles/homepage I figured submitting this pull request would be a good idea.

**Comment by maybe-one-day-ubermensch** [comment]
sorry about the extra stuff there, was trying to keep the branch updated with master

**Comment by Chocimier** [comment]
This will change repetition of `https://github.com` to repetition of `${GITHUB_SITE}`, what is one character less.

Other common hosting sites contain path that is likely to change, and some of them actually was changed. I wouldn't expect `github.com` domain to change.

If we encourage to use GITHUB_SITE, we should do that in both distfiles and homepage, and then homepage can not be copied out and pasted into browser anymore.
Even our own tools do not handle that complexity, see [void-updates.txt](https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt).

I do not think this is gain.

However, there are certainly other ways you can contribute to Void Linux, ask on reddit or irc.

**Comment by maybe-one-day-ubermensch** [comment]
Ahhh ok that makes more sense now, thank you!

**Pull request closed without merging**
