### PR TITLE
cargo-crev: update to 0.21.1

### PR DESCRIPTION
**Pull request by cinerea0**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Any idea about the failing test?

**Comment by cinerea0** [comment]
@ericonr No, sorry. Is it alright if I just close this and the other PR with failing Rust tests and leave it for the actual maintainer to update?

**Comment by ericonr** [comment]
We can tag him :P @jcgruenhage 

And fwiw their tests don't work either https://github.com/crev-dev/cargo-crev/runs/3209853516

Can you run them locally to see if the results match, at least?

**Comment by cinerea0** [comment]
Running the tests locally results in the same error found in CI here:

```
running 1 test
test creates_new_id_implicitly ... FAILED

failures:

---- creates_new_id_implicitly stdout ----
thread 'creates_new_id_implicitly' panicked at 'assertion failed: c.run(&[\"id\", \"trust\", \"--level=medium\",\n        \"FYlr8YoYGVvDwHQxqEIs89reKKDy-oWisoO0qXXEfHE\"], \"\").status.success()', cargo-crev/tests/clitest.rs:11:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    creates_new_id_implicitly

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.05s
```

What's interesting is the tests you linked show version 0.21.1 of cargo-crev being compiled, but that version doesn't seem to exist yet.

**Comment by ericonr** [comment]
I can't be forced to care about their tests more than they do. Can you update to 0.21.1 and we can merge?

**Comment by cinerea0** [comment]
@ericonr Our tests now fail the same way upstream's do. Does that mean this is okay to merge?

**Pull request merged**
