### PR TITLE
New package: grapejuice-4.9.2

### PR DESCRIPTION
**Pull request by wael444**
New package: grapejuice-4.8.2

#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-LIBC)
- grapejuice's dependencies `freetype-32bit`, `gnutls-32bit`, `libgcc-32bit` will not work on musl.

### CODE REVIEW

**Comment by Chocimier** [comment]
> * grapejuice's dependencies `freetype-32bit`, `gnutls-32bit`, `libgcc-32bit` will not work on musl.

They do not work on i686, and arguably on glibc x86_64 either, see https://github.com/void-linux/void-packages/pull/540#issuecomment-417855681.
I guess they need to be left to install manually.

**Comment by cinerea0** [comment]
Why is this pointing at some arbitrary commit instead of the project's latest release?

**Comment by wael444** [comment]
> Why is this pointing at some arbitrary commit instead of the project's latest release?

The latest release is 4.0.0. this is 4.8.2,

**Comment by cinerea0** [comment]
> The latest release is 4.0.0. this is 4.8.2,

Exactly, the version of the package should match the upstream release version.

**Comment by wael444** [comment]
> > The latest release is 4.0.0. this is 4.8.2,
> 
> Exactly, the version of the package should match the upstream release version.

I will try to contact the project creator.

**Comment by z-ffqq** [comment]
> > The latest release is 4.0.0. this is 4.8.2,
> 
> Exactly, the version of the package should match the upstream release version.

The project maintainer of [grapejuice](https://gitlab.com/brinkervii/grapejuice) has forgot to make a new tag for the latest stable release (v4.8.2), so @wael444 is forced to use commits to avoid more confusion. v4.0.0 is NOT the newest stable version, v4.8.2 is

I just made this comment to clear up any confusion

**Comment by wael444** [comment]
before i update the template, i would like to ask if having `freetype-32bit, gnutls-32bit, libgcc-32bit` is appropriate to be included in the package, as it only solves problems with wine such as 
libgcc-32bit:
```
libgcc_s.so.1 must be installed for pthread_cancel to work
wine client error:154: write: Bad file descriptor
``` 
freetype-32bit:
```
Wine cannot find the FreeType font library. 
```
gnutls-32bit:
```
HttpSendRequest Failed
```
i will not be including wine as an dependency as roblox requires a different build of wine with required patches to make roblox work.
these dependencies have nothing to do with grapejuice, but only provide fixes to wine problems.

**Comment by Chocimier** [comment]
To sum up:

- this is launcher of single proprietary game
- moving fast
- that can't be installed with dependencies of game due to way void multilib works
- requiring wine built from source separately (up to 1 hour build time)
- being pure python module buildable within minutes

Sorry, but it is not worthwhile to package this.
However, after restoring -32bit dependencies jut for glibc x86_64, you have nice template you can share somewhere else.

**Comment by karimrir1** [comment]
> To sum up:
> 
>     * this is launcher of single proprietary game
> 
>     * moving fast
> 
>     * that can't be installed with dependencies of game due to way void multilib works
> 
>     * requiring wine built from source separately (up to 1 hour build time)
> 
>     * being pure python module buildable within minutes
> 
> 
> Sorry, but it is not worthwhile to package this. However, after restoring -32bit dependencies jut for glibc x86_64, you have nice template you can share somewhere else.

It's not a launcher, It's a wrapper for wine. Just like lutris. Nothing else nothing more.

**Pull request closed without merging**
