### PR TITLE
go: update to 1.12.9.

### PR DESCRIPTION
**Pull request by nilium**

### CODE REVIEW

**Comment by Gottox** [comment]
What's up with i686?

**Comment by nilium** [comment]
Not sure yet. Haven’t had time to submit an issue for Go, since this seems like it may be a bug in Go.

**Comment by the-maldridge** [comment]
Any update on the weirdness with i686?

**Comment by nilium** [comment]
No. Haven't had time to look into it further or put together an issue describing what's happening. At minimum, it's a bug in Go -- the compiler shouldn't panic at any point.

**Comment by nilium** [comment]
Looks like @0palescent opened an issue for it, golang/go#33977, relating to their PR. Can close this one if needed.

**Comment by nilium** [comment]
Closing to update my branch to 1.13.

**Pull request closed without merging**
