### PR TITLE
font-iosevka: add Aile and Etoile version

### PR DESCRIPTION
**Pull request by kozachynskyi**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by FollieHiyuki** [comment]
Hmm, then we also need to add `iosevka-curly` and `iosevka-curly-slab` for the completeness. At that point the package seems kinda bloated :)

**Comment by kozachynskyi** [comment]
@FollieHiyuki That's a good point. I'm not familiar with how void-linux handles such questions about "bloat". Just wanted to open discussion. 

I think one should have all font Family Types provided in one package.

**Comment by FollieHiyuki** [comment]
iosevka

I like to have all the variants packaged too since I use them all. The only problem here is that the font is rather heavy with only just the main variants (see picture above), and the updating frequency is quite often (around 2-3 times a month).

It all comes to "is it worth adding all the main variants with the sacrifice of bandwidth".

**Comment by FollieHiyuki** [comment]
Please leave the PR open. We could hear some opinions from Void maintainers before deciding how we should go with it.

**Pull request closed without merging**
