### PR TITLE
Vulkan 1.3.211.0

### PR DESCRIPTION
**Pull request by tibequadorian**
#### Testing the changes
- I tested the changes in this PR: **YES** (x86_64-glibc)

### CODE REVIEW

**Comment by tibequadorian** [comment]
@wundrweapon You can help test this PR, if you want

**Comment by ericonr** [comment]
```
-- The ASM compiler identification is GNU
-- Found assembler: /builddir/.xbps-vulkan-loader/wrappers/aarch64-linux-gnu-gcc
[...]
[2/21] Linking C executable loader/asm_offset
[3/21] Generating gen_defines.asm
FAILED: loader/gen_defines.asm /builddir/Vulkan-Loader-sdk-1.3.211.0/build/loader/gen_defines.asm 
cd /builddir/Vulkan-Loader-sdk-1.3.211.0/build/loader && asm_offset GAS
/bin/sh: line 1: asm_offset: command not found
ninja: build stopped: subcommand failed.
```

This looks like it's building `asm_offset` for the target, because CMake can't really do anything else, afaik. So we'd have to try and fix that.

Possibly relevant https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=259718

**Comment by tibequadorian** [comment]
Yes, i thought about installing asm_offset to vulkan-loader and depend on it. Will look into it later, thanks.

**Comment by tibequadorian** [comment]
Related: https://github.com/KhronosGroup/Vulkan-Loader/issues/881

I explicitly disabled GAS for cross builds now like done in https://github.com/gador/nixpkgs/commit/8e1009a9b869375b4b4c4429fb76024f0241ce46

It looks like in older versions, cross compiling didn't fail because the build logic was wrong.
This got fixed in https://github.com/KhronosGroup/Vulkan-Loader/commit/db5e3d0f454f063db7b4505e4d08b759f1874bbb which makes it fail now.

**Comment by tibequadorian** [comment]
ping @ericonr

**Comment by Seltyk** [comment]
This is still relevant. There are no other Vulkan PRs, and Vulkan has not been updated on Void in a long time.  
As an extra note, The Vulkan SDK [has been updated](https://github.com/KhronosGroup/Vulkan-Headers/releases/tag/sdk-1.3.224.1) and this PR should be updated to match it

**Comment by tibequadorian** [comment]
Sorry I'm not interested in updating PRs that get no attention. Feel free to take over

**Pull request closed without merging**
