### PR TITLE
sequeler: update to 0.6.8.

### PR DESCRIPTION
**Pull request by TeddyDD**

### CODE REVIEW

**Comment by maxice8** [comment]
That will fail on aarch64 as far as i remember

**Comment by TeddyDD** [comment]
I'll deal with this tomorrow

**Comment by maxice8** [comment]
ping

**Comment by TeddyDD** [comment]
working on it
https://github.com/Alecaddd/sequeler/issues/242

**Comment by TeddyDD** [comment]
huh, it builds on my machine with this patch. Investigating further

**Comment by TeddyDD** [comment]
all right, I don't know how to fix it, marking as broken on aarch64 and armv7l for now.

If someone uses either of those platforms: you can try following patch. It works for me with cross compilation, I can't test it on native machine.


```diff
--- src/meson.build
+++ src/meson.build
@@ -59,10 +59,12 @@ executable(
         dependency('libgda-5.0'),
         dependency('libssh2'),
         dependency('libsecret-1'),
+        dependency('libfixposix'),
         dependency('gtksourceview-3.0'),
         m_dep,
         linux_dep
     ],
-        vala_args: vala_args + ['--pkg', 'libfixposix'],
+        vala_args: vala_args,
     install: true
 )
+
```

**Pull request merged**
