### PR TITLE
gcc: remove wrong no-stack_chk_fail_local.patch

### PR DESCRIPTION
**Pull request by pullmoll**
This patch was introduced with gcc 7.2.0 to circumvent problems
with strong stack protector enabled for gcc.

With the current version it is not just obsolete but outright
wrong and causes "strange" issues with builds failing for
no obvious reason.

One example is the mruby package which failed to build and
now, after the bad patch is removed, works out of the box.

Set `_have_gccgo=no` also for `i686-musl` because `gcc` cannot be cross
compiled for this target.

With the same revbump add two patches for mips32 header file
location and soft-float for mips-musl and mipsel-musl.

### CODE REVIEW

**Comment by q66** [comment]
the cross-powerpc-linux-musl template is not patched properly

**Comment by q66** [comment]
otherwise LGTM

**Comment by pullmoll** [comment]
It does not work yet. I need to sort out when to `--disable-ssp` and whether or when to explicitly enable it or let gcc's configure scripts decide.

**Comment by pullmoll** [comment]
Got it sorted out for `cross-i686-linux-musl`. Now doing the same for `cross-powerpc-linux-musl`.

**Comment by pullmoll** [comment]
Hmm.. not quite yet. Cross building gcc for `i686-musl` now gives me an error for gccgo:
```
go1: error: ‘-fsplit-stack’ currently only supported on GNU/Linux
```
So I have to find out how to disable split stack for i686-musl and, perhaps, ppc-musl.

**Comment by pullmoll** [comment]
Now it worked. I think I did not have the latest update in my master, but only in the branch.
If this also works for ppc64le as builder I think it should be ok.

**Comment by q66** [comment]
i'll test it out on my builders, may take a while; if this is good to go, i'll merge it afterwards

**Comment by pullmoll** [comment]
Darn. I reported the wrong result: `cross-i686-linux-musl` can be built, yes, but `gcc` for `i686-musl` cannot be built from `x86_64` chroot. Currently trying if it can be built from a `i686` chroot where the change is already applied.

Anyway, as I said, this is not relevant for the official builders.

**Comment by pullmoll** [comment]
I think this is beause there is no `ld.gold` in `cross-i686-linux-musl`. Trying to enable it via `--enable-gold` and also adding `--enable-split-stack` to the template.

**Comment by pullmoll** [comment]
The problem persists no matter what I try:
```
make[4]: Leaving directory '/builddir/gcc-9.3.0/build/i686-linux-musl/libgo'
make[3]: Leaving directory '/builddir/gcc-9.3.0/build/i686-linux-musl/libgo'
make[2]: Leaving directory '/builddir/gcc-9.3.0/build/i686-linux-musl/libgo'
make[2]: Entering directory '/builddir/gcc-9.3.0/build/gotools'
i686-linux-musl-gccgo  --sysroot=/usr/i686-linux-musl  -O2 -pipe -march=i686  -g -I/usr/i686-linux-musl/usr/include -I ../i686-linux-musl/libgo -static-libstdc++ -static-libgcc -Wl,--as-needed    -L/usr/i686-linux-musl/usr/lib -L ../i686-linux-musl/libgo -L ../i686-linux-musl/libgo/.libs -o go /builddir/gcc-9.3.0/gotools/../libgo/go/cmd/go/alldocs.go /builddir/gcc-9.3.0/gotools/../libgo/go/cmd/go/go11.go /builddir/gcc-9.3.0/gotools/../libgo/go/cmd/go/main.go ../i686-linux-musl/libgo/libgotool.a  
i686-linux-musl-gccgo  --sysroot=/usr/i686-linux-musl  -O2 -pipe -march=i686  -g -I/usr/i686-linux-musl/usr/include -I ../i686-linux-musl/libgo -static-libstdc++ -static-libgcc -Wl,--as-needed    -L/usr/i686-linux-musl/usr/lib -L ../i686-linux-musl/libgo -L ../i686-linux-musl/libgo/.libs -o gofmt /builddir/gcc-9.3.0/gotools/../libgo/go/cmd/gofmt/doc.go /builddir/gcc-9.3.0/gotools/../libgo/go/cmd/gofmt/gofmt.go /builddir/gcc-9.3.0/gotools/../libgo/go/cmd/gofmt/internal.go /builddir/gcc-9.3.0/gotools/../libgo/go/cmd/gofmt/rewrite.go /builddir/gcc-9.3.0/gotools/../libgo/go/cmd/gofmt/simplify.go  
echo 'package main' > zdefaultcc.go.tmp
i686-linux-musl-gccgo  --sysroot=/usr/i686-linux-musl  -O2 -pipe -march=i686  -g -I/usr/i686-linux-musl/usr/include -I ../i686-linux-musl/libgo -static-libstdc++ -static-libgcc -Wl,--as-needed    -L/usr/i686-linux-musl/usr/lib -L ../i686-linux-musl/libgo -L ../i686-linux-musl/libgo/.libs -o vet /builddir/gcc-9.3.0/gotools/../libgo/go/cmd/vet/doc.go /builddir/gcc-9.3.0/gotools/../libgo/go/cmd/vet/main.go ../i686-linux-musl/libgo/libgotool.a  
i686-linux-musl-gccgo  --sysroot=/usr/i686-linux-musl  -O2 -pipe -march=i686  -g -I/usr/i686-linux-musl/usr/include -I ../i686-linux-musl/libgo -static-libstdc++ -static-libgcc -Wl,--as-needed    -L/usr/i686-linux-musl/usr/lib -L ../i686-linux-musl/libgo -L ../i686-linux-musl/libgo/.libs -o buildid /builddir/gcc-9.3.0/gotools/../libgo/go/cmd/buildid/buildid.go /builddir/gcc-9.3.0/gotools/../libgo/go/cmd/buildid/doc.go ../i686-linux-musl/libgo/libgotool.a  
echo 'func defaultGCCGO(goos, goarch string) string { return "/usr/bin/gccgo" }' >> zdefaultcc.go.tmp
echo 'func defaultCC(goos, goarch string) string { return "gcc" }' >> zdefaultcc.go.tmp
go1: error: ‘-fsplit-stack’ currently only supported on GNU/Linux
go1: error: ‘-fsplit-stack’ is not supported by this compiler configuration
go1: error: ‘-fsplit-stack’ currently only supported on GNU/Linux
go1: error: ‘-fsplit-stack’ is not supported by this compiler configuration
go1: error: ‘-fsplit-stack’ currently only supported on GNU/Linux
go1: error: ‘-fsplit-stack’ is not supported by this compiler configuration
make[2]: *** [Makefile:821: go] Error 1
make[2]: *** Waiting for unfinished jobs....
echo 'func defaultCXX(goos, goarch string) string { return "g++" }' >> zdefaultcc.go.tmp
make[2]: *** [Makefile:823: gofmt] Error 1
make[2]: *** [Makefile:827: vet] Error 1
go1: error: ‘-fsplit-stack’ currently only supported on GNU/Linux
go1: error: ‘-fsplit-stack’ is not supported by this compiler configuration
make[2]: *** [Makefile:829: buildid] Error 1
echo 'const defaultPkgConfig = "pkg-config"' >> zdefaultcc.go.tmp
/bin/bash /builddir/gcc-9.3.0/gotools/../move-if-change zdefaultcc.go.tmp zdefaultcc.go
echo timestamp > s-zdefaultcc 
make[2]: Leaving directory '/builddir/gcc-9.3.0/build/gotools'
make[1]: *** [Makefile:12090: all-gotools] Error 2
make[1]: Leaving directory '/builddir/gcc-9.3.0/build'
make: *** [Makefile:964: all] Error 2
=> ERROR: gcc-9.3.0_5: do_build: 'make ${makejobs}' exited with 2
=> ERROR:   in do_build() at srcpkgs/gcc/template:340
```

**Comment by pullmoll** [comment]
I wonder if we should just ditch `i686-musl`. The user base is probably around 1 or 2 people :-P

**Comment by q66** [comment]
Still need this:

```
commit 6027e0496db60f406b5f4b6d2a53d38fe6472c42
Author: q66 <daniel@octaforge.org>
Date:   Sun Jun 7 13:26:21 2020 +0200

    fix gcc bootstrap

diff --git a/srcpkgs/gcc/files/libssp-musl.patch b/srcpkgs/gcc/files/libssp-musl.patch
new file mode 100644
index 0000000000..c4b9db4516
--- /dev/null
+++ b/srcpkgs/gcc/files/libssp-musl.patch
@@ -0,0 +1,24 @@
+Taken from Alpine. We use libssp from gcc but need this to bootstrap anyway.
+
+Original comment:
+
+Author: Timo Teräs <timo.teras@iki.fi>
+
+Alpine musl package provides libssp_nonshared.a. We link to it unconditionally,
+as otherwise we get link failures if some objects are -fstack-protector built
+and final link happens with -fno-stack-protector. This seems to be the common
+case when bootstrapping gcc, the piepatches do not seem to fully fix the
+crosstoolchain and  bootstrap sequence wrt. stack-protector flag usage.
+
+--- gcc-6.1.0/gcc/gcc.c.orig
++++ gcc-6.1.0/gcc/gcc.c
+@@ -870,8 +870,7 @@
+ 
+ #ifndef LINK_SSP_SPEC
+ #ifdef TARGET_LIBC_PROVIDES_SSP
+-#define LINK_SSP_SPEC "%{fstack-protector|fstack-protector-all" \
+-		       "|fstack-protector-strong|fstack-protector-explicit:}"
++#define LINK_SSP_SPEC "-lssp_nonshared"
+ #else
+ #define LINK_SSP_SPEC "%{fstack-protector|fstack-protector-all" \
+ 		       "|fstack-protector-strong|fstack-protector-explicit" \
diff --git a/srcpkgs/gcc/template b/srcpkgs/gcc/template
index 626f131e32..e3dd6683a6 100644
--- a/srcpkgs/gcc/template
+++ b/srcpkgs/gcc/template
@@ -171,6 +171,7 @@ pre_configure() {
 	case "$XBPS_TARGET_MACHINE" in
 		*-musl)
 			patch -p1 -i ${FILESDIR}/libgnarl-musl.patch
+			patch -p1 -i ${FILESDIR}/libssp-musl.patch
 			patch -p0 -i ${FILESDIR}/gccgo-musl.patch
 			;;
 	esac
```

otherwise gcc fails to bootstrap itself on musl. Can you test if things still work?

**Comment by pullmoll** [comment]
Thank you! I will test this patch now.

**Comment by q66** [comment]
read the diff again :P

**Comment by pullmoll** [comment]
Darn. I'm tired and the gcc-6.1.0 led me to the wrong idea this was for the gcc6 package.

**Comment by q66** [comment]
all built on my side now, seems fine

**Comment by pullmoll** [comment]
I'm still trying here. Cross compiling xbps for i686-musl failed before because of the missing libssp.

**Comment by pullmoll** [comment]
Isn't the libssp_nonshared.patch required for cross-powerpc-linux-musl also? I haven't tried that one yet.

**Comment by q66** [comment]
don't think so, i think it's just a workaround for when gcc builds some of its stage stuff without ssp, and the crosstoolchains build fine for me

**Comment by pullmoll** [comment]
Ok. I still have the problem that xbps cannot be cross built for i686-musl from i686. Need to retry the entire cross build once again.

**Comment by pullmoll** [comment]
If I add `LDFLAGS="-lssp_nonshared"` it works. Perhaps we can simply add that to the default `common/cross-profiles/i686-musl.sh` as `XBPS_CROSS_LDFLAGS="-lssp_nonshared"`. I have to check if such a variable is evaluated and used.

**Comment by q66** [comment]
no, that's terrible

it just means we should change musl crosstoolchains to use the same patch as gcc

**Comment by pullmoll** [comment]
If you look at the latest version of `cross-i686-linux-musl` I already did apply that patch.
This is why I said *I'm baffled* because the problem still is there.
And all this reminds me of 2017 and why we finally did use the patch which now shall be removed...

**Comment by pullmoll** [comment]
Looking at the `libssp-musl.patch` isn't the `#ifdef TARGET_LIBC_PROVIDES_SSP` wrong and should instead be `#ifndef TARGET_LIBC_PROVIDES_SSP`? We want gcc to link against `libssp_nonshared` regardless of stack protector flags in the case where libc (read: glibc) doesn **not** provide the hooks...

**Comment by pullmoll** [comment]
Nope, that doesn't work either. I'm giving up for today.

**Comment by q66** [comment]
i'll test it myself, maybe it'll lead somewhere

**Comment by q66** [comment]
Indeed, got the same thing. Your assumption about `TARGET_LIBC_PROVIDES_SSP` is incorrect though, that's defined if the libc provides ssp support, which musl does.

**Comment by q66** [comment]
This is a bug in `xbps`. It doesn't pass `CFLAGS` for linkage of `libxbps.so`, only `LDFLAGS`, which means the right SSP related flags are passed for build but not link.

**Comment by q66** [comment]
Anyway, please add the libssp musl patch into every musl cross-toolchain and bump them appropriately. We can fix xbps separately later.

**Comment by q66** [comment]
```
=> Registering new packages to /host/binpkgs/test
index: added `libxbps-0.59.1_1' (i686-musl).
index: added `libxbps-devel-0.59.1_1' (i686-musl).
index: added `xbps-0.59.1_1' (i686-musl).
index: 52 packages registered.
```

**Comment by pullmoll** [comment]
*It doesn't pass CFLAGS for linkage ...*

I think we will see that for some more packages and then need to fix them accordingly.

**Comment by q66** [comment]
We generally won't, I'd be surprised if there were many or any at all. The standard way is to pass both.

**Comment by q66** [comment]
lgtm now

**Comment by q66** [comment]
Btw, please test again if gccgo is buildable for `i686-musl` now. Add `--enable-split-stack` in gcc template if necessary. It builds in the crosstoolchain, so chances are it should be able to in gcc itself too.

**Comment by pullmoll** [comment]
As I said above I cannot test changes now because I'm building my repository from scratch.

Since perhaps noone except me builds i686-musl, once I get to build that base-chroot again, I can apply necessary changes to the gcc template w/o revbump.

**Comment by q66** [comment]
OK, I'll merge it once the crosstoolchain builds have finished on my side.

**Comment by q66** [comment]
Looks like the crosstoolchains are now failing, more changes will be needed into the templates. I think I figured out what it is though, so I can just fix it myself.

**Comment by pullmoll** [comment]
Thank you. I'm busy on my own now.

**Comment by pullmoll** [comment]
Still doing trial + error for i686-musl cross build of gcc. I believe for musl it should be `--disable-split-stack` and addition of `_args+=" gcc_cv_libc_provides_ssp=no"`. It must be possible to cross build `gcc` somehow or the build of `cross-i686-linux-musl` would not work... anyway, that's a tough job and trial + error takes a lot of time.

**Comment by q66** [comment]
no, the previous changes were fine regarding ssp - musl does provide ssp support, as does glibc, there is an explicit triplet check for it in gcc and overriding it is wrong

just don't mess with the PR any more, I have a ready-to-merge bunch of commits staged here and you're just making it hard for me to compare what you changed and where

if you figure out gccgo on i686-musl later, feel free to change things later

**Comment by q66** [comment]
anyway i'll close this now, merge the changes (without `--enable-split-stack` in i686-musl) and any i686-musl specific fixes can be done later

**Comment by q66** [comment]
The changes are in, as far as I can see all the crosstoolchains build/work. The gccgo stuff in gcc will remain disabled for i686-musl for now, if it get figured out we can change things separately.

**Comment by q66** [comment]
also, looks like gccgo does not actually require split-stack support; e.g. it works on ppc32 yet ppc32 has no split stack support in gcc at all - the issue is somewhere else, we just need to find where.

**Comment by q66** [comment]
https://github.com/gcc-mirror/gcc/blob/41d6b10e96a1de98e90a7c0378437c3255814b16/libgo/configure.ac#L382

**Comment by q66** [comment]
you can try this workaround in `gcc` template: `libgo_cv_c_split_stack_supported=no` for `i686-musl`

**Comment by pullmoll** [comment]
FWIW I still see the same error when trying to cross build `base-chroot` and in there `gcc` for `x86_64-musl` from `x86_64`:
```
go1: error: ‘-fsplit-stack’ currently only supported on GNU/Linux
go1: error: ‘-fsplit-stack’ is not supported by this compiler configuration
```
I don't know why yet it seems as if cross compiling from `powerpc64le` was/is different from `x86_64`.
I'll give `aarch64-musl` a try to see how it is there.

With the workaround `libgo_cv_c_split_stack_supported=no` I also still see that error for `i686-musl`.

**Comment by pullmoll** [comment]
Uh, strange errors appear here; perhaps my system is somehow broken. See the build log (tail) for building `gcc` from `x86_64` for `aarch64-musl`: https://misc.voidlinux.de/aarch64-log.txt

**Comment by pullmoll** [comment]
Same strange error now trying to build `base-chroot` for `i686-musl` from `x86_64` environment:
https://misc.voidlinux.de/i686-log.txt
I don't get it what is going on here.

I'll zap my entire repo again and will build the first `gcc` with the options `~ada gnatboot`.

**Pull request closed without merging**
