### PR TITLE
xbps-src: remove proot chroot-style

### PR DESCRIPTION
**Pull request by Duncaen**
proot is broken and result in random hard to debug issues,
this is the best way to not have new users use it.

### CODE REVIEW

**Comment by ericonr** [comment]
Needs to remove from README as well.

**Comment by Duncaen** [comment]
removed every mention from the readme.

**Comment by pullmoll** [comment]
There is an alpha release at https://github.com/proot-me/proot dated 2020-04-14 which builds here. I haven't tested it yet, though.

**Comment by Chocimier** [comment]
proot is also mentioned in defaults.conf

**Comment by fosslinux** [comment]
I agree with this change. I don't believe proot is a good fit for xbps in any way and lots of stuff randomly breaks under it.

**Comment by ericonr** [comment]
Another data point: https://github.com/void-linux/void-packages/issues/24240#issuecomment-723896196

**Comment by zenny** [comment]
> removed every mention from the readme.

Is it only me that I still see https://github.com/void-linux/void-packages/blob/master/README.md#proot1

**Comment by zenny** [comment]
> There is an alpha release at https://github.com/proot-me/proot dated 2020-04-14 which builds here. I haven't tested it yet, though.

I tried with the release you mentioned, but still problematic to build gccemacs without any way to debug, fyi.

**Comment by Duncaen** [comment]
> > removed every mention from the readme.
> 
> Is it only me that I still see the mention in `readme` till these lines are written?
> 
> ```
> https://github.com/void-linux/void-packages/blob/master/README.md#proot1
> ```

I was talking about the changes in this PR, that are not yet merged...

**Comment by ericonr** [comment]
Ping

**Pull request merged**
