### PR TITLE
autofirma: fix passing arguments to app

### PR DESCRIPTION
**Pull request by Xx-Seth-xX**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by classabbyamp** [comment]
the revision needs to be incremented

**Comment by Xx-Seth-xX** [comment]
> the revision needs to be incremented

I don't know if this is the right place to ask, but linting is failing because there is a new version of autofirma (1.8.3), should I bump and test that in this PR or how can I make this pass CI? 

(It's my first PR in a public project)

**Comment by classabbyamp** [comment]
the error is `Error: 658a8a479: authored by noreply email`

you'll need to set a different email in your git config and `git commit --amend --reset-author`

**Comment by Xx-Seth-xX** [comment]
> the error is `Error: 658a8a479: authored by noreply email`
> 
> you'll need to set a different email in your git config and `git commit --amend --reset-author`

Thank you, I missread, it should be fixed now

**Pull request merged**
