### PR TITLE
sagemath-9.5: package updates and fixes

### PR DESCRIPTION
**Pull request by tornaria**
#### Testing the changes
- I tested the changes in this PR: **YES**

This includes
 - upgrade to lrcalc-2.1 (from #36209)
 -  _already merged_ ~upgrade to sympy-1.10.1 (from #36397)~
 - _postponed_ ~upgrade to SuiteSparse-5.11.0, igraph-0.9.7, planarity-3.0.2.0, python3-cvxopt-1.3.0 (from #36423)~
 - _already merged_ ~upgrade to giac-1.7.0.53 (from #36421)~
 - _already merged_ ~upgrade to gp2c-0.0.12pl1 (from #36422)~
 - new package threejs-sage for 3d plots (#36504)
 - backported fixes for sagemath-9.5 to accomodate these upgrades, and also ipython and scipy upgrades which are already merged

~I want to see if the CI can cope with this. Otherwise I'll just split this in a few separate PR. Except for the upgrade to lrcalc-2.1, which must be coordinated with sage, everything else can be handled separately.~

cc: @dkwo

EDIT: I ended up making 3 new PR to handle the packages that can be upgraded separately from sagemath (#36397, #36421, #36422, #36423 should be ok to merge if CI passes).

EDIT 2: this PR is now just to upgrade lrcalc to 2.1 (will be needed for sagemath-9.6) and fix sagemath-9.5 so it works with lrcalc 2.1 (and several minor doctest fixes for upgrades to ipython, scipy, sympy).

EDIT 3: rebased on top of #36504 (new package threejs-sage) and fix sagemath config to use it, now 3d plots work

### CODE REVIEW

**Comment by dkwo** [comment]
Great, let me take a look.

**Comment by tornaria** [comment]
> Is it possible to make sagemath available for aarch64? It is [available in Fedora](https://fedora.pkgs.org/35/fedora-aarch64/sagemath-9.4-1.fc35.aarch64.rpm.html), but I don't know if they cross compile it...

We have a few packages that are nocross at this moment (from top of my head: ntl, givaro/fflas/linbox, cysignals, and packages that depend on those). I wouldn't expect sagelib itself to be an issue, but I never tried

If you have an aarch64 box capable of running sagemath, you could try compiling sagemath native using xbps-src which should recursively compile all the packages that are not available in the official repo because of nocross.

**Comment by Eloitor** [comment]
Thanks for the answer, I'll try compiling from source.

**Comment by dkwo** [comment]
iirc, the main blocker to cross in ntl, the rest follows from that.

see also https://github.com/libntl/ntl/issues/8

**Comment by tornaria** [comment]
@leahneukirchen this is now ready to merge, it is an improvement over 9.5_1 on a few counts:
 - better compatibility with some python packages that were upgraded in void (ipython, scipy, sympy, sphinx)
 - upgrade lrcalc to 2.1 which is required by current betas of 9.6 and will be needed when we get around to release 9.6
 - enable 3d plots via new pkg threejs-sage (this feature was missing before).

Other upgrades (e.g. #36423) can be done later independently, in principle it shouldn't be necessary to change the sagemath pkg again until the release of 9.6.

**Comment by Duncaen** [comment]
I don't think adding ignore patterns to the git repository for random versions you deem unsuitable is a good idea, just don't update them, no need to litter the history with versions that are never applied.

**Pull request merged**
