### PR TITLE
foot: update to 1.12.1.

### PR DESCRIPTION
**Pull request by ifreund**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by camoz** [comment]
The config now lives under `/etc`, but should probably not yet added to `conf_files` due to https://github.com/void-linux/xbps/issues/342

**Comment by ftrvxmtrx** [comment]
Tested on aarch64-musl. Works well. Very much like the new `-E` option.

**Comment by camoz** [comment]
Thinking about it, the new release now installs a config file to `/etc/xdg/foot/foot.ini`, see https://codeberg.org/dnkl/foot/pulls/1015

AFAUI a possible user config file at that location would be overwritten anyway, so why not just add it to `conf_files` now?

**Comment by ericonr** [comment]
@ifreund ping on the `conf_files` idea?

**Comment by ifreund** [comment]
@ericonr Implemented, thanks for the ping :)

**Comment by camoz** [comment]
I just want to highlight that this upgrade (with or without the `conf_files` option) has the potential to delete the user's configuration, because `/etc/xdg/foot/foot.ini` has already been the standard location for a system-wide foot config for some time. What is new in 1.12 is just that a default config is being installed there. So if void really wants to avoid overwriting the user's config, this should not be merged in the current state.

**Comment by ifreund** [comment]
Looks like an ncurses update was merged to master in the meantime and we now need to resolve the terminfo conflict one way or another. From foot's `INSTALL.md`:

> As of ncurses 2021-07-31, ncurses includes a version of foot’s terminfo. The recommendation is to use those, and only install the terminfo definitions from this git repo if the system’s ncurses predates 2021-07-31.
>
> But, note that the foot terminfo definitions in ncurses’ lack the non-standard capabilities. This mostly affects tmux; without them, terminal-overrides must be configured to enable truecolor support. For this reason, it is possible to install “our” terminfo definitions as well, either in a non-default location, or under a different name.
>
> Both have their set of issues. When installing to a non-default location, foot will set the environment variable TERMINFO in the child process. However, there are many situations where this simply does not work. See [#695](https://codeberg.org/dnkl/foot/issues/695) for details.
>
> Installing them under a different name generally works well, but will break applications that check if $TERM == foot.
>
> Hence the recommendation to simply use ncurses’ terminfo definitions if available.
>
> If packaging “our” terminfo definitions, I recommend doing that as a separate package, to allow them to be installed on remote systems without having to install foot itself.

It seems like the simplest option is to drop `foot-terminfo`, thoughts?

**Comment by ifreund** [comment]
I dropped `foot-terminfo` in the latest commit, following upstream's recommendation. This should be ready for merge now as far as I'm concerned.

**Comment by ifreund** [comment]
Good catch @r-ricci, done.

**Review by ericonr — COMMENTED** [review]
You need to fix `depends` for foot too

**Comment by ifreund** [comment]
After some discussion on IRC, I decided to instead resolve the conflict by patching foot's terminfo out of ncurses as this will be the least disruptive for foot users.

**Pull request merged**
