### PR TITLE
glade3 3.38

### PR DESCRIPTION
**Pull request by sgn**
- Hold on bumping gnome-builder because sysprof https://gitlab.gnome.org/GNOME/sysprof/-/merge_requests/37

### CODE REVIEW

**Comment by q66** [comment]
i'll just fold it into gnome 3.38

i've had patched sysprof there since way before

**Comment by sgn** [comment]
> i'll just fold it into gnome 3.38

That'll work, too. But, I would like to merge this if possible to split the building time.
 
> i've had patched sysprof there since way before

Yeah, I've just looked at it, now.

**Comment by q66** [comment]
I'll merge the gnome stuff in two halves so it doesn't matter anyway

**Comment by q66** [comment]
folded into the gnome PR

**Pull request closed without merging**
