### PR TITLE
musikcube: update to 0.92.1

### PR DESCRIPTION
**Pull request by the-eater**

### CODE REVIEW

**Comment by the-eater** [comment]
bootstrap env. in docker seems out of date

**Comment by the-eater** [comment]
should configure a cron to update it, and/or run `./xbps-src bootstrap-update` before starting a build

**Comment by pullmoll** [comment]
Automatic generation of the docker images was voted against AFAIR because w/o scrutiny they may become (very) broken. Not sure if `bootstrap-update` will help.

**Comment by the-eater** [comment]
oh ye i am not thinking, it's a desync of the git repo and remote repo I forgot

**Comment by Chocimier** [comment]
Please rebase.

**Pull request closed without merging**
