### PR TITLE
purge_distfiles.sh: forcefully remove files

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by Anachron** [comment]
What‘s the reason here? Any issue open in reference to this?

**Comment by maxice8** [comment]
On Tue, Apr 09, 2019 at 07:19:17AM +0000, Anachron wrote:
> What‘s the reason here? Any issue open in reference to this?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/10730#issuecomment-481133037

It will prompt you if it hits any file with wrong permissions

**Comment by Anachron** [comment]
Ok I see. Did it happen already or is this just a precaution?

**Comment by maxice8** [comment]
On Tue, Apr 09, 2019 at 07:25:19AM +0000, Anachron wrote:
> Ok I see. Did it happen already or is this just a precaution? 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/10730#issuecomment-481134708

Already happened with me

**Comment by Anachron** [comment]
May I ask how it happened? Shouldn‘t the permissions be correct at the time of package extraction? In which process did you get wrong permissions on the file?

**Comment by maxice8** [comment]
> May I ask how it happened?

Yes but i can't give an answer

> Shouldn‘t the permissions be correct at the time of package extraction?

Yes, but better safe than sorry

> In which process did you get wrong permissions on the file?

The one being affected by this PR

**Pull request merged**
