### PR TITLE
New package: F-Sy-H-1.66

### PR DESCRIPTION
**Pull request by cinerea0**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by itsdeadguy** [comment]
Just a heads up, the author of fast-syntax-highlighting has wiped everything from everywhere and gone AWOL.
more info can be found in [this reddit thread about the whole situation](https://www.reddit.com/r/zsh/comments/qinb6j/httpsgithubcomzdharma_has_suddenly_disappeared_i/)

**Comment by cinerea0** [comment]
Thanks for the heads up, I'll be switching the upstream in the template to refer to one of the re-uploads.

**Comment by cinerea0** [comment]
I'm still working on this.

**Comment by cinerea0** [comment]
After some more investigation, it appears that installing this plugin system-wide results in subtle bugs that I don't know how to fix. As such, I am closing this PR.

**Pull request closed without merging**
