### PR TITLE
WIP: clamav: update to 1.2.0.

### PR DESCRIPTION
**Pull request by nsudsgaard**
- [x] Builds locally on x86_64-musl
- [x] Builds locally on x86_64
- [ ] Builds locally on i686
- [x] Builds locally on aarch64-musl _crossbuild_
- [x] Builds locally on aarch64 _crossbuild_
- [ ] Builds locally on armv7l-musl _crossbuild_
- [ ] Builds locally on armv7l  _crossbuild_
- [ ] Builds locally on armv6l-musl _crossbuild_
- [ ] Builds locally on armv6l _crossbuild_
- [ ] Test on x86_64-musl
- [ ] Test on x86_64
- [ ] Cleanup/patch the configuration files
- [ ] Add service files

### CODE REVIEW

**Comment by nsudsgaard** [comment]
> There's #41188.

I had a look at the PR, and the patches seem quite unnecessary, especially `rust-optimize.patch`, which can be done by simply setting `CMAKE_BUILD_TYPE=Release`.

I was also thinking about adding service files, but I chose to just focus on updating on this PR.

Also, the PR you mentioned is updating to the latest version (1.2.0). I chose to go with the most recent LTS version (1.0.3). I suppose it's better to update to the latest-and-greatest rather than an LTS version on Void Linux?

**Comment by classabbyamp** [comment]
we'd prefer if you had a [few more contributions before adopting](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#adopting-a-template) a template

**Comment by nsudsgaard** [comment]
> we'd prefer if you had a [few more contributions before adopting](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#adopting-a-template) a template

Fair enough.

**Comment by nsudsgaard** [comment]
> Latest stable is generally preferred.

I will start testing 1.2.0 then.

> Having two PRs creates confusion, I think one should be closed.

I will leave this decision to the contributors/members. I will contribute my work to the one that remains open.

**Comment by nsudsgaard** [comment]
WIP: 1.2.0 patch

```patch
--- a/common/shlibs	2023-09-14 14:00:08.268535424 +0900
+++ b/common/shlibs	2023-09-14 21:32:26.745618939 +0900
@@ -2256,11 +2256,11 @@
 libsfml-window.so.2.5 SFML-2.5.0_1
 libsfml-audio.so.2.5 SFML-2.5.0_1
 libsfml-graphics.so.2.5 SFML-2.5.0_1
-libclamav.so.11 clamav-1.0.3_1
-libclamunrar.so.11 clamav-1.0.3_1
-libclamunrar_iface.so.11 clamav-1.0.3_1
-libclammspack.so.0 clamav-1.0.3_1
-libfreshclam.so.2 clamav-0.103.1_2
+libclamav.so.12 clamav-1.2.0_1
+libclamunrar.so.12 clamav-1.2.0_1
+libclamunrar_iface.so.12 clamav-1.2.0_1
+libclammspack.so.0 clamav-1.2.0_1
+libfreshclam.so.3 clamav-1.2.0_1
 libqca-qt5.so.2 qca-qt5-2.1.3_1
 libqt5keychain.so.1 qtkeychain-qt5-0.7.0_1
 libphonon4qt5.so.4 phonon-qt5-4.8.3_1
--- a/srcpkgs/clamav/template	2023-09-14 23:44:26.619590292 +0900
+++ b/srcpkgs/clamav/template	2023-09-14 22:15:10.006635765 +0900
@@ -1,6 +1,6 @@
 # Template file for 'clamav'
 pkgname=clamav
-version=1.0.3
+version=1.2.0
 revision=1
 build_style=cmake
 cmake_builddir=build
@@ -10,9 +10,9 @@
  -D CMAKE_BUILD_TYPE=Release
  -D CMAKE_INSTALL_PREFIX=/usr
  -D APP_CONFIG_DIRECTORY=/etc
- -D DATABASE_DIRECTORY=/var/lib/_${pkgname}
- -D CLAMAV_USER=_${pkgname}
- -D CLAMAV_GROUP=_${pkgname}
+ -D DATABASE_DIRECTORY=/var/lib/_clamav
+ -D CLAMAV_USER=_clamav
+ -D CLAMAV_GROUP=_clamav
  -D ENABLE_JSON_SHARED=OFF"
 hostmakedepends="rust cargo python3"
 makedepends="bzip2-devel check-devel libcurl-devel json-c-devel libmilter-devel
@@ -21,17 +21,19 @@
 maintainer="Orphaned <orphan@voidlinux.org>"
 license="GPL-2.0-only"
 homepage="https://www.clamav.net/"
+changelog="https://raw.githubusercontent.com/Cisco-Talos/clamav/main/NEWS.md"
 distfiles="https://www.clamav.net/downloads/production/clamav-${version}.tar.gz"
-checksum=8779458dc31fdee1232eb8986f092d25568b39f5d337c0cbcd9c1abb5dc2886b
-system_accounts="_${pkgname}"
-_clamav_descr="ClamAV user"
-_clamav_homedir="/var/lib/_${pkgname}"
+checksum=97a192dffe141480b56cabf1063d79a9fc55cd59203241fa41bfc7a98a548020
+system_accounts="_clamav"
+_clamav_homedir="/var/lib/_clamav"
 conf_files="/etc/clamd.conf /etc/freshclam.conf /etc/clamav-milter.conf"
 
 if [ "$CROSS_BUILD" ]; then
 	build_helper="qemu"
 	makedepends+=" rust-std"
-	configure_args+=" -D RUST_COMPILER_TARGET:STRING=${XBPS_CROSS_RUST_TARGET}"
+	configure_args+="
+	-D RUST_COMPILER_TARGET:STRING=${XBPS_CROSS_RUST_TARGET}
+	-D RUSTFLAGS=${XBPS_CROSS_RUSTFLAGS}"
 fi
 
 if [ "$XBPS_TARGET_LIBC" = "musl" ]; then
@@ -39,15 +41,6 @@
 	configure_args+=" -D CMAKE_EXE_LINKER_FLAGS=-lfts"
 fi
 
-pre_configure() {
-	if [ "$CROSS_BUILD" ]; then
-		path=${XBPS_CROSS_BASE}/lib/rustlib/${XBPS_CROSS_RUST_TARGET}/lib
-
-		sed -i cmake/FindRust.cmake \
-		   -e "s:^set(RUSTFLAGS \"\")$:set(RUSTFLAGS \"-L${path}\"):g"
-	fi
-}
-
 post_install() {
 	vmkdir /etc 755
 	for path in ${conf_files}; do
@@ -57,7 +50,7 @@
 		vsconf ${PKGDESTDIR}/${path} ${name}.sample
 		sed -i ${PKGDESTDIR}/${path}        \
 			-e "s;^Example$;# Example;" \
-			-e "s;#DatabaseDirectory.*;DatabaseDirectory /var/lib/_${pkgname};"
+			-e "s;#DatabaseDirectory.*;DatabaseDirectory /var/lib/_clamav;"
 	done
 	vdoc ${FILESDIR}/README.voidlinux
 
```

**Comment by jcgruenhage** [comment]
It looks like something went wrong here. With regard to which of the two PRs should remain open: I don't really care. I need clamav for work, and since the packaged clamav doesn't have a service at the moment, my primary goal was adding that an updating clamav while I'm at it. As long as that is done at some point, I don't have a strong preference otherwise.

I agree that combining the efforts into a single PR probably makes sense though.

**Comment by nsudsgaard** [comment]
> It looks like something went wrong here.

Yeah... I suck at using Git/GitHub. :/

> With regard to which of the two PRs should remain open: I don't really care. I need clamav for work, and since the packaged clamav doesn't have a service at the moment, my primary goal was adding that an updating clamav while I'm at it. As long as that is done at some point, I don't have a strong preference otherwise.

Implementing service files is something I want to get done in this update as well. However, I am currently struggling to put the configuration files into /etc/clamav instead of dumping them all into /etc (putting them in the directory is easy, getting xbps to recognize them is not).

> I agree that combining the efforts into a single PR probably makes sense though.

I already nuked my PR. I am considering just contributing to yours once I get the issue above resolved.

**Pull request merged**
