### PR TITLE
srcpkgs/*: remove all cryptocurrency/blockchain packages

### LINKED ISSUE #14402: Package request: Solar
[Solar](https://github.com/satoshipay/solar) is a wallet for [XLM](https://www.stellar.org/lumens/), licensed under the GPLv3. Would be nice to have a standalone wallet too instead of only the one integrated into keybase.

### LINKED ISSUE #24491: Package request: zeronet
Decentralized websites using Bitcoin crypto and BitTorrent network:
https://github.com/HelloZeroNet/ZeroNet

### LINKED ISSUE #35228: Request: Wasabi
- Upstream: https://wasabiwallet.io/
- Latest release: https://github.com/zkSNACKs/WalletWasabi/releases/tag/v1.1.13.0

Wasabi is a privacy-focused Bitcoin wallet.

### LINKED ISSUE #38410: Package request: Ledger live
### Package name

ledger-live-desktop

### Package homepage

https://github.com/LedgerHQ/ledger-live-desktop/releases

### Description

Application for Ledger nano X/S cryptocurrency hardware wallet. This app has an Appimage version, but it doesn't work correctly with void.

This app has an Appimage version, but it doesn't work correctly with Void.

### Does the requested package meet the quality requirements?

System

### Is the requested package released?

Yes

### LINKED ISSUE #39723: Package request: Electrum Personal Server (EPS)
### Package name

electrum-personal-server

### Package homepage

https://github.com/chris-belcher/electrum-personal-server

### Description

The [Bitcoin Wiki](https://en.bitcoin.it/wiki/Electrum#Electrum_Personal_Server) explains the role of EPS in detail:

> Electrum Personal Server has a different approach to a normal server. It is intended to be used by a single person only. Instead of creating a database of every transaction and address ever used on the bitcoin blockchain, Electrum Personal Server only tracks the user's own wallets. This allows it to be much more efficient with resources, it does not need any extra data files and is compatible with [Bitcoin Core](https://en.bitcoin.it/wiki/Bitcoin_Core)'s pruning feature.
>
> Electrum Personal Server is probably the best way to combine Electrum's feature-richness (hardware wallet integration, multi-signature, [seed phrase](https://en.bitcoin.it/wiki/Seed_phrase), etc) with a [full node](https://en.bitcoin.it/wiki/Full_node)'s strong security and privacy.

I'd like this package to be managed by xbps, since it has features other servers lack support.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

### PR DESCRIPTION
**Pull request by 0x5c**
This has been discussed multiple times on IRC, and it seems the general consensus was towards removal.

Also closes these cryptocurrency-related package requests and pending PRs:
Closes #24491
Closes #35228
Closes #39723
Closes #43702
Closes #44133
Closes #38410
Closes #14402

[ci skip]

### CODE REVIEW

**Comment by paper42** [comment]
It would be nice to add a notice to CONTRIBUTING.md next to browser forks and themes, so people don't spend their time packaging and opening PRs for new cryptocurrency stuff

**Comment by ar-jan** [comment]
How about not accepting new package requests and removing unmaintained packages, but keeping actively maintained ones?

I'd like to get #43702 in, but am OK with removing `Electron-Cash` from it (that's better run from AppImage anyway).

(It's been ready for a month but needs rebasing since a few hours ago. I'll hold off on updating it depending on what is decided here).

**Review by paper42 — APPROVED** [review]

**Review by classabbyamp — APPROVED** [review]

**Comment by SpecialBomb** [comment]
I would like to preface this by saying that I am not telling any of you what to do, and I'm certainly not asking to revert this PR. I appreciate the Void Linux project and its maintainers, and I hate crypto grifts as much as the next person. I don't even dabble in cryptocurrency at all.

However, I and others have discussed this PR and what it entails, and I personally think it's a little shortsighted to remove cryptocurrency packages for the sake of it being associated with scams. While it's most definitely true that the current main use of cryptocurrency is for scams and dubious investments, that doesn't remove from the tangible utility that cryptocurrencies have for many people trying to make anonymous transactions for goods and services.

While I think it's the maintainers' rights to choose what gets added to the repo or not, seeing a decision made like this in such a manner as this doesn't evoke confidence in me or others even if we do think crypto is kinda stupid. I could care less about these packages, but I can't deny that the way they were removed wasn't very thought out or sensible. I do understand why you would want to remove them, and I probably would to, but I think seeing it from another perspective is helpful.

And of course, at the end of the day, it doesn't really matter since nothing is preventing anyone from obtaining and using any of this software from other sources. I just feel like the decision was too subjective.

**Comment by kevcrumb** [comment]
This looks like a decision based on personal preference (and a lack of understanding) more than anything and is underlined by the fact that no reasoning is being provided. Of course it would be hard to argue for this.

**Comment by drizzt** [comment]
@SpecialBomb yes, you are correct... any bitcoin-related packages should be re-added since they are not scam...
I know upstream suggest to uses their pre-built binaries, but you can't do that if you use void with musl (like many people do, like me) and so we need to rebuilt the package by ourself.
I did some commits on Bitcoin Core and I work for Red Hat, so I think I'm trusted enough to say that :)

**Comment by uberscientist** [comment]
I don't know what to say.  I was confused when my full node didn't start up after updating and finally found this issue.

This is very disappointing.  I know I am just one user, and I feel as though I haven't done anything wrong, but I feel like apologizing for whatever caused this sweeping action to be taken.

Void still is probably still the best choice for my infrastructure and daily driver, but I am put on alert by this "rug pull".  I don't want to be seen as an enemy/scammer or whatever the reasoning was behind the breaking changes.  If there's any room for discussion or suggestions I hope to be able to suggest less violent solutions than going nuclear on all crypto related packages.

**Comment by 0x5c** [comment]
For what its worth, it's standard procedure for removed packages to be added to `removed-packages`, which removes them from user's computers. This is done so that these packages don't create broken shlibs issues down the line with future updates. It's really important to always check the xbps transaction summary for that reason.

I'm not sure how I feel about the `removed-packages` mechanism, It feels a bit heavy-handed, but it's the current way things are done when a package is dropped from the repos.

**Comment by lemmi** [comment]
@maciozo I assume you want to keep some of the packages. You can do that with `xbps-pkgdb -m hold $PACKAGE`

@0x5c Sure. This is less about that things were added to removed-packages, but rather the eager timing of it. A couple weeks of adding an install message would have been nice, so people still using the package could have had a chance to make preparations instead of just ending up with packages forcibly uninstalled from their system they were still using.

**Comment by 0x5c** [comment]
> Sure. This is less about that things were added to removed-packages, but rather the eager timing of it. A couple weeks of adding an install message would have been nice, so people still using the package could have had a chance to make preparations instead of just ending up with packages forcibly uninstalled from their system they were still using.

I have never heard of any packages getting that treatment (may have happened but never heard of that), nor did anyone suggest doing that.

**Comment by maciozo** [comment]
It would have been nice to have some community input on the matter. While some discussion may have happened on IRC, it's apparent that not all of us have the time to spend on there. I was thinking that perhaps some sort of e-mailed newsletter whenever breaking changes like this occur, but @lemmi's suggestion of including it as an install message would probably be easier to manage. That plus some time for an RFC, especially for such a contraversial change.


> I have never heard of any packages getting that treatment (may have happened but never heard of that), nor did anyone suggest doing that.

I seem to recall something like this happening with a PipeWire package recently (`pipewire-media-session`, or something like that?), that was replaced with something else, but still managed to break my audio stack.

**Comment by ar-jan** [comment]
> I have never heard of any packages getting that treatment (may have happened but never heard of that), nor did anyone suggest doing that.

But usually packages are removed for being obsolete, not because they are suddenly deemed undesirable while having active users.

**Comment by 0x5c** [comment]
> > I have never heard of any packages getting that treatment (may have happened but never heard of that), nor did anyone suggest doing that.
> 
> But usually packages are removed for being obsolete, not because they are suddenly deemed undesirable while having active users.

At least from changes I've seen, I can name https://github.com/void-linux/void-packages/pull/40044 (PolyMC) as a package deemed undesirable (in that case, rogue upstream) with a then active userbase that also didn't get a message when removed despite the replacement being a not fully compatible fork.

**Comment by maciozo** [comment]
>At least from changes I've seen, I can name https://github.com/void-linux/void-packages/pull/40044 (PolyMC) as a package deemed undesirable (in that case, rogue upstream) with a then active userbase that also didn't get a message when removed despite the replacement being a not fully compatible fork.

That doesn't seem like a particularly desirable precedent to me. At least in that case the package was somewhat transparently replaced with a fork, and the reasoning for it had some merit. Here, packages are just being unilaterally removed from people's PCs with no warning and no alternative offered, for what seem to be somewhat opinionated reasons.

I get that Void isn't exactly meant to be a begginer-friendly distro, but I'm sure there are users out there who just blindly run `xi -Syu`, reasonably assuming that the OS won't suddenly remove potentially important software from their PCs.

**Comment by lemmi** [comment]
@0x5c usually it's not necessary because we remove packages that are unused, broken and/or have been unmaintained for quite a while. Even then, they usually are orphaned first. While there were a lot of packages very ripe for removal in your PR and I too wouldn't have thought about giving them any sort of extra treatment, there were also some with PRs open or those that were at least occasionally maintained.
I get that you were given immediate positive feedback from other core members, so I understand that you didn't get the impression you were maybe overreaching a bit with some removals. I'm not blaming anyone in particular, I still don't like how the whole thing went down.

**Comment by Yorizuka** [comment]
Every encounter I have had with the maintainers has been a negative one for the last few years. Look I understand opensource work pays nothing and is often a thankless job. But I have interacted with maintainers for other project and it never was this bad.
Consistently moves are made with zero attempt to communicate them before they are done. This is not a one-off, this is a pattern, I will list the last 3 times that upsetting actions have been done before communicating them from my memory.

1. I have attempted to a good user and to give back, on my first contribution I had my Pull request closed with no explanation as to why. (An explanation did come, but it was a day later, after I gave up.) https://web.archive.org/web/20230903041209/https://github.com/void-linux/void-packages/pull/37370 While I still feel it was a bit rude, I forgive this one. (please do not harass any of the people involved)
2. Another upsetting action the maintainers have done is hijacking an existing packages and shipping a different program under the same name with zero communication about it before they did so. https://web.archive.org/web/20230903034123/https://github.com/void-linux/void-packages/pull/40044 This one alone under other a sightly different context would of had mobs of angry people & is still in principle an unacceptable behavior. The new launcher was not 1 to 1 compatible & gave me quite the scare, I a small amount of time thought my 7 year old world was lost, that was stressful.
3. This: Most users do not interact with the maintainers of the software they use. There is a silent majority that is not hanging out in the IRC. Given the current popular stance on Crypto, I'm guessing this has more then just technical motivations, I understand not adding new coins, but looking at the Monero wallet, this clearly is a quick and dirty hit job, The Monero wallet was removed, but the debug and development files are still showing up in the search. https://web.archive.org/web/20230903044828/https://voidlinux.org/packages/?arch=x86_64&q=monero

I do not appreciate the maintainers making life style choices for me, Whats next? Are you going to remove TOR, that allows you to access and do bad things. Maybe void should remove everything with encryption, it's what bad people use to hide things.
I use to run xbps-install -Suy weekly, keeping my system up to date, Now hesitate to update, every time I do so there is a chance something annoying will be done by the maintainers and that I should go double check.

**Comment by Yorizuka** [comment]
I feel there is a wider problem at play here, I have started a issue for discussing it: https://github.com/void-linux/void-packages/issues/45892 Hopefully we can reach a solution that makes everyone happy.

**Pull request merged**
