### PR TITLE
python3-pycares: update to 3.0.0

### PR DESCRIPTION
**Pull request by TheExpert1337**

### CODE REVIEW

**Comment by Hoshpak** [comment]
Fails on musl:

```
c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
   15 | #include <ffi.h>
      |          ^~~~~~~
```

Adding `libffi-devel` to makedepends could help since it provides the header file but I don't have time to test that right now.

**Comment by Hoshpak** [comment]
It requires python3-ffi bot in makedepends and depends as it is defined in setup.py. Then the cross builds will work.

**Comment by Chocimier** [comment]
Please resolve travis lint notes.

**Comment by Hoshpak** [comment]
I'm closing this PR as stale because there's been no response or progress for an extended amount of time. Please reopen or create a new PR when there's progress on this.

**Pull request closed without merging**
