### PR TITLE
fix cross python because of change in uname wrapper

### PR DESCRIPTION
**Pull request by sgn**
From commit cf6e6f1, (wrappers/uname: report correct machine type
on ethereal, 2020-02-10), uname wrapper has been updated to report
correct machine type in ethereal mode by replace its original machine
type by value reported by $XBPS_ARCH.

This effectively breaks python{,3}{,-tkinter}'s cross compile because
we reset all environment variable to configure for the host build.

Keep those environment variable.

### CODE REVIEW

**Comment by xtraeme** [comment]
While you are at it, could you please update python3 to 3.8.2? Thanks.

**Comment by sgn** [comment]
Working on it, I will submit after checking

**Comment by sgn** [comment]
@xtraeme I've built and tested on local machine, (included all cross target).

The build take too long on Travis, you can check it yourself.

**Comment by pullmoll** [comment]
I didn't realize this interferes with me updating libffi to version 3.3, which is why I revbumped python3-3.8.1 - sorry.

**Comment by pullmoll** [comment]
Merged via git-merge-pr

**Pull request closed without merging**
