### PR TITLE
Plasma6

### PR DESCRIPTION
**Pull request by Luciogi**
#### Testing the changes
- I tested the changes in this PR: **yes"

- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-GLIBC)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-musl

[skip ci]
[ci skip]

### CODE REVIEW

**Comment by Luciogi** [comment]
checks are not tested yet :|

**Comment by sgn** [comment]
Update file that only strips `kf6-` from `pkgname` can be dropped.
Those `libkexiv2` and the likes should be named: `libkexiv2-qt6`, just in case it's `libkexiv2-qt7` later.

**Comment by Luciogi** [comment]
> Update file that only strips `kf6-` from `pkgname` can be dropped. Those `libkexiv2` and the likes should be named: `libkexiv2-qt6`, just in case it's `libkexiv2-qt7` later.

I'll fix
---
https://github.com/void-linux/void-packages/commit/d218f45bf773fe8167e04559dca7acd85e1f7ae8

**Comment by Luciogi** [comment]
> Those `libkexiv2` and the likes should be named: `libkexiv2-qt6`, just in case it's `libkexiv2-qt7` later.

It can be simply libkexiv2 for latest qt version, if qt 7 releases , new pkg `libkexiv2-qt6` can be introduced for any pkg that requires qt6 version this library, otherwise can be skipped

**Comment by Luciogi** [comment]
Some kf6 tests fixed

**Comment by TinfoilSubmarine** [comment]
After doing a `./xbps-src pkg kde5` and trying to upgrade, I get this:
```
MISSING: plasma-nm>=6.0.4
Transaction aborted due to unresolved dependencies.
```

**Pull request merged**
