### PR TITLE
remove noarch for build_style=gem

### PR DESCRIPTION
**Pull request by fosslinux**

### CODE REVIEW

**Comment by q66** [comment]
@fosslinux @sgn ??? why was this merged? one template per commit

**Comment by sgn** [comment]
I think bulk change is fine in this case, no?

**Comment by q66** [comment]
why would a bulk change be fine? it revbumps packages, how is that any different from any other package rebuild

**Comment by sgn** [comment]
> why would a bulk change be fine?

I thought it was only a cosmetic change, :shrug: 

> it revbumps packages, how is that any different from any other package rebuild

Point taken.

**Comment by fosslinux** [comment]
Hm, I origniall chose a bulk commit because it seemed more reasonable but I see your point, it makes more sense and aligns with standards to do it one template per commit.

**Pull request merged**
