### PR TITLE
[WIP] protonmail-bridge: update to 3.12.0.

### PR DESCRIPTION
**Pull request by M4RZ3R0**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

#### Tasks
- [ ] Build from source

### CODE REVIEW

**Comment by classabbyamp** [comment]
would be nice to [build from source](https://github.com/ProtonMail/proton-bridge/blob/master/BUILDS.md)

**Comment by classabbyamp** [comment]
I just pushed what should be necessary for building from source, please try this out (I don't have a protonmail account to test that it does anything other than launch)

**Comment by classabbyamp** [comment]
(ignore that lint failure, it's a false positive)

**Comment by classabbyamp** [comment]
not sure why it's failing in CI, it finds Qt fine locally

**Comment by M4RZ3R0** [comment]
I've updated build_helper to use qmake6 for better qmake detection. This fixes the previous issues, and it works fine on my setup now.

> I just pushed what should be necessary for building from source, please try this out (I don't have a protonmail account to test that it does anything other than launch)
> 
> also, does the package layout make sense for how the package should be used?
> 
> ```
> .
> └── usr
>     ├── bin
>     │   ├── protonmail-bridge -> /usr/libexec/protonmail/bridge
>     │   └── protonmail-bridge-gui -> /usr/libexec/protonmail/bridge-gui
>     ├── libexec
>     │   └── protonmail
>     │       ├── bridge
>     │       └── bridge-gui
>     └── share
>         ├── applications
>         │   └── proton-bridge.desktop
>         └── icons
>             └── hicolor
>                 └── scalable
>                     └── apps
>                         └── protonmail-bridge.svg
> ```

I think this layout makes sense

**Comment by classabbyamp** [comment]
i know what's causing that build failure and I'll fix it soon

**Pull request merged**
