### PR TITLE
picom: update to 12.1.

### PR DESCRIPTION
**Pull request by chee-z1**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-musl)

#### Replaced dependency
Replaced asciidoc to asciidoctor(ruby-asciidoctor package) for building document.

### CODE REVIEW

**Comment by tranzystorekk** [comment]
It's polite to ping the maintainer: @0x5c

**Comment by 0x5c** [comment]
Currently testing it, not ready yet
I will be making the PR when it's ready

As I've discovered with last version, picom can have dramatic effects when it hits a bug

**Comment by chee-z1** [comment]
Oh, I'm sorry

**Comment by 0x5c** [comment]
haha, not even half an hour ago the devs released a .3 version
I think I'm going to let it cook a bit more

**Pull request closed without merging**
