### PR TITLE
icu: update to 62.1.

### PR DESCRIPTION
**Pull request by maxice8**
Building on x86_64 status:

- [x] 0ad
- [x] R
- [x] R-cran-stringi
- [x] an
- [x] bind
- [x] boost
- [x] brltty
- [x] calibre
- [x] couchdb
- [x] deepin-music
- [x] dwdiff
- [x] epiphany
- [x] evolution-data-server
- [x] firebird
- [x] firefox
- [x] firefox-esr
- [x] freshplayerplugin
- [x] gnote
- [x] gnustep-base
- [x] goffice
- [x] harfbuzz
- [x] icecat
- [x] icu4lua
- [x] kdb
- [x] kiwix-lib
- [x] libcdr
- [x] libe-book
- [x] libgdal
- [x] libmspub
- [x] libqxp
- [x] libreoffice
- [x] libvisio
- [x] libxml2
- [x] libzim
- [x] maim
- [x] mimic
- [x] modsecurity
- [x] mozjs52
- [x] mpd
- [x] ncmpcpp
- [x] nodejs
- [x] nodejs-lts
- [x] open-vm-tools
- [x] openttd
- [x] perl-XML-LibXML
- [x] phantomjs
- [x] php
- [x] poedit
- [x] postfix
- [x] python-PyICU
- [x] qalculate
- [x] qt5
- [x] qt5-webkit
- [x] rspamd
- [x] sile
- [x] slop
- [x] swift
- [x] sword
- [x] tectonic
- [x] tesseract-ocr
- [x] thunderbird
- [x] tracker
- [x] tracker-miners
- [x] webkit2gtk
- [x] webkitgtk
- [x] widelands
- [x] xerces-c
- [x] xmlsec1
- [x] yaz
- [x] znc

### CODE REVIEW

**Comment by maxice8** [comment]
i removed swift since it is broken for so long

@pullmoll can you test libreoffice ?

**Comment by pullmoll** [comment]
@maxice8 I'm currently busy with too many things, sorry. If everything fails, it would be possible to use the shipped icu instead (--without-system-icu), so IMO libreoffice should be no show stopper.

**Comment by maxice8** [comment]
On Thu, Aug 30, 2018 at 08:56:30PM +0000, Jürgen Buchmüller wrote:
> @maxice8 I'm currently busy with too many things, sorry. If everything fails, it would be possible to use the shipped icu instead (--without-system-icu), so IMO libreoffice should be no show stopper.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/2198#issuecomment-417464407

I just don't want to subject my machine to more torture than

webkit2gtk
webkitgtk2
qt5
qt5-webkit
firefox
firefox-esr

**Comment by pullmoll** [comment]
Ok, I'll try to build libreoffice for x86_64 on a branch with just icu updated and with the official repo's packages for the other dependencies.

**Comment by pullmoll** [comment]
I have auccessfully built libreoffice for x86_64. Unsigned packages (i.e. download and install from local path) can be found here: https://repo.voidlinux.de/current/icu/
Now going to take a nap :)

**Comment by Hoshpak** [comment]
0ad also builds fine with the new icu on `x86_64`.

**Comment by Hoshpak** [comment]
tesseract-ocr also builds.

**Comment by newbluemoon** [comment]
Building for armv7l-musl right now. So far no problems. Done are:

an, bind, boost, icu, libxml2 ...

**Comment by maxice8** [comment]
@newbluemoon 

1. Thanks, removed libswift
2. Thanks for building on other arches
3. Please open a FTBFS issue with relevant info if possible

**Comment by newbluemoon** [comment]
@maxice8 Already deleted the evolution-data-server builddir, but once I’m through with all packages I’ll try again, maybe it was just a hiccup. If not I’ll open an issue.

**Pull request closed without merging**
