### PR TITLE
Swapspace: install systemd unit

### PR DESCRIPTION
**Pull request by tranzystorek-io**
#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by classabbyamp** [comment]
don't think this is needed, a runit service is already installed and it isn't done by the default install phase of the package

**Comment by tranzystorek-io** [comment]
Not even for reference?

**Comment by classabbyamp** [comment]
we already include a service, so I'm not sure why a user would need to reference it

**Comment by tranzystorek-io** [comment]
Ah, I see. I'll close this then.

**Pull request closed without merging**
