### PR TITLE
pipewire: update to 0.3.33

### PR DESCRIPTION
**Pull request by st3r4g**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by paper42** [comment]
from the changelog:

> Use libfreeaptx instead of libopenaptx.

So we need to package libfreeaptx or aptx will not work with this version of pipewire :( The template should be very similar to libopenaptx, because it's a fork.

**Comment by st3r4g** [comment]
Ah thanks, missed that. Maybe it would be better to explicitly enable all features to catch such mistakes, instead of relying on autodetection.

Are you going to package libfreeaptx?

**Comment by st3r4g** [comment]
I think I will also have a look at the `echo-cancel-webrtc` which was added some release ago and enable it.

**Comment by paper42** [comment]
> Are you going to package libfreeaptx?

It would be nice to get it in this PR, what do you think?
[0001-New-package-libfreeaptx-0.1.1.patch](https://ttm.sh/tLa.patch)
[0002-libopenaptx-remove.patch](https://ttm.sh/tLO.patch)
[0003-removed-packages-add-libopenaptx-and-bump.patch](https://ttm.sh/tLm.patch)

**Comment by st3r4g** [comment]
this is how it looks when reworked for `--auto-features=enabled`.
Configure summary diff:
```
--- pipewire-configure-auto	2021-08-07 16:10:02.608323202 +0200
+++ pipewire-configure-enabled	2021-08-07 16:35:58.239295344 +0200
@@ -7,15 +7,15 @@
 
   Misc dependencies
                          SDL 2: NO
-         WebRTC Echo Canceling: NO
+         WebRTC Echo Canceling: YES
 
   pw-cat/pw-play/pw-dump tool
                        sndfile: YES
              Build pw-cat tool: YES
 
   Streaming between daemons
-                      libpulse: NO
-       Avahi DNS-SD (Zeroconf): NO
+                      libpulse: YES
+       Avahi DNS-SD (Zeroconf): YES
                            ROC: NO
 
   Backend
```

**Comment by ericonr** [comment]
Let's go with enable, then :)

What does enabling `libpulse` mean?

And IIRC we can't remove `libopenaptx` yet, correct?

**Comment by paper42** [comment]
> What does enabling `libpulse` mean?

It should be for streaming between devices - for example a desktop computer could use speakers from a laptop.

> And IIRC we can't remove `libopenaptx` yet, correct?

Yes, we need to either leave libopenaptx in repositories until bluez-alsa starts supporting libfreeaptx or patch it.

**Comment by paper42** [comment]
> > And IIRC we can't remove `libopenaptx` yet, correct?
> 
> Yes, we need to either leave libopenaptx in repositories until bluez-alsa starts supporting libfreeaptx or patch it.

@st3r4g let's leave libopenaptx in the repositories. The next pipewire version might use libopenaptx as a fallback and bluez-alsa doesn't use libfreeaptx.

**Comment by dkwo** [comment]
This update seems to break audio for me: nothing in alsamixer and the warning
`[W][02053.586348][   policy-node.c:  910 rescan_node()] no node found for 38`
from pipewire. Am I the only one?

Thanks.

**Comment by st3r4g** [comment]
> nothing in alsamixer

You mean that `alsamixer` doesn't run because there are no cards? If that's the case, I think its caused by one of the alsa updates, not pipewire

**Comment by dkwo** [comment]
@st3r4g for `Card: PipeWire`, it says `This sound device does not have any controls.`

**Comment by dkwo** [comment]
@st3r4g You're right, `xdowngrade /var/cache/xbps/alsa-lib-1.2.4_2.x86_64-musl.xbps` solves my issue.

**Comment by ericonr** [comment]
I wonder if https://github.com/void-linux/void-packages/pull/32577 is enough to fix this?

**Comment by dkwo** [comment]
@ericonr Yes, that does the job, thank you.

**Pull request merged**
