### PR TITLE
calibre: Update to 5.2.0

### PR DESCRIPTION
**Pull request by ajshell1**

### CODE REVIEW

**Comment by ericonr** [comment]
This requires a bit of fixing and should possibly wait on #25420

**Comment by ericonr** [comment]
I'm working on a branch to improve it, will post it in a bit.

**Comment by ericonr** [comment]
Could you take a look here? https://github.com/void-linux/void-packages/compare/master...ericonr:calibre

**Comment by sgn** [comment]
@ericonr Is `pychm` new dependency in 5.2.0?

**Comment by ericonr** [comment]
@sgn according to elibrokeit, it stopped being vendored in recently. So now needs to be a separate package.

**Pull request closed without merging**
