### PR TITLE
polybar: update to 3.5.3.

### PR DESCRIPTION
**Pull request by pbui**

### CODE REVIEW

**Comment by ericonr** [comment]
Apparently you can now build docs for polybar without having git available. Want to do that?

**Comment by pbui** [comment]
@ericonr Done.  It looks like there should be a man page for polybar now.

**Comment by ericonr** [comment]
Is

```
/usr/share/doc/polybar/.buildinfo
/usr/share/doc/polybar/_sources/dev/packaging.rst.txt
/usr/share/doc/polybar/_sources/dev/release-workflow.rst.txt
/usr/share/doc/polybar/_sources/index.rst.txt
/usr/share/doc/polybar/_sources/man/polybar.1.rst.txt
/usr/share/doc/polybar/_sources/man/polybar.5.rst.txt
/usr/share/doc/polybar/_sources/user/actions.rst.txt
/usr/share/doc/polybar/_static/alabaster.css
/usr/share/doc/polybar/_static/basic.css
/usr/share/doc/polybar/_static/custom.css
/usr/share/doc/polybar/_static/doctools.js
/usr/share/doc/polybar/_static/documentation_options.js
/usr/share/doc/polybar/_static/file.png
/usr/share/doc/polybar/_static/jquery-3.5.1.js
/usr/share/doc/polybar/_static/jquery.js
/usr/share/doc/polybar/_static/language_data.js
/usr/share/doc/polybar/_static/minus.png
/usr/share/doc/polybar/_static/plus.png
/usr/share/doc/polybar/_static/pygments.css
/usr/share/doc/polybar/_static/searchtools.js
/usr/share/doc/polybar/_static/underscore-1.3.1.js
/usr/share/doc/polybar/_static/underscore.js
/usr/share/doc/polybar/config
/usr/share/doc/polybar/dev/packaging.html
/usr/share/doc/polybar/dev/release-workflow.html
/usr/share/doc/polybar/genindex.html
/usr/share/doc/polybar/index.html
/usr/share/doc/polybar/man/polybar.1.html
/usr/share/doc/polybar/man/polybar.5.html
/usr/share/doc/polybar/objects.inv
/usr/share/doc/polybar/search.html
/usr/share/doc/polybar/searchindex.js
/usr/share/doc/polybar/user/actions.html
```

too much? I'm not sure we need to ship that part. The man pages are a good addition, though.

**Comment by pbui** [comment]
@ericonr OK, I've modified the template to remove the files under `/usr/share/doc/polybar`.

**Pull request merged**
