### PR TITLE
kdegear update to 23.08.5

### PR DESCRIPTION
**Pull request by Luciogi**
[ci skip]
#### Testing the changes
- I tested the changes in this PR: **Yes**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-GLIBC)

### CODE REVIEW

**Comment by Luciogi** [comment]
@Johnnynator review

**Comment by Johnnynator** [comment]
Looks mostly okay.

KDevelop fails to compile for `aarch64` and `aarch64-musl`

**Comment by Johnnynator** [comment]
```diff
diff --git a/srcpkgs/kdevelop/template b/srcpkgs/kdevelop/template
index e55de503f79..03797add041 100644
--- a/srcpkgs/kdevelop/template
+++ b/srcpkgs/kdevelop/template
@@ -21,6 +21,9 @@ changelog="https://kde.org/announcements/changelogs/gear/${version}/#kdevelop"
 distfiles="${KDE_SITE}/release-service/${version}/src/kdevelop-${version}.tar.xz"
 checksum=d634f287f72c6e1097f2de1ea2f8bab41899952adcf879b0fe6daa14fecee1f8
 
+# Should be a dpendency of llvm17-devel, remove once the llvm template is updated
+makedepends+=" libomp-devel"
+
 build_options="webengine"
 desc_option_webengine="Use Qt5 WebEngine for documentation"
 
```

**Comment by Luciogi** [comment]
> ```diff
> diff --git a/srcpkgs/kdevelop/template b/srcpkgs/kdevelop/template
> index e55de503f79..03797add041 100644
> --- a/srcpkgs/kdevelop/template
> +++ b/srcpkgs/kdevelop/template
> @@ -21,6 +21,9 @@ changelog="https://kde.org/announcements/changelogs/gear/${version}/#kdevelop"
>  distfiles="${KDE_SITE}/release-service/${version}/src/kdevelop-${version}.tar.xz"
>  checksum=d634f287f72c6e1097f2de1ea2f8bab41899952adcf879b0fe6daa14fecee1f8
>  
> +# Should be a dpendency of llvm17-devel, remove once the llvm template is updated
> +makedepends+=" libomp-devel"
> +
>  build_options="webengine"
>  desc_option_webengine="Use Qt5 WebEngine for documentation"
>  
> ```

patching done

**Pull request merged**
