### PR TITLE
nvidia: update to 520.56.06

### PR DESCRIPTION
**Pull request by dataCobra**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)

### CODE REVIEW

**Comment by abenson** [comment]
I've held off of this update because of [issues](https://forums.developer.nvidia.com/t/bug-report-black-x11-screen-and-partial-lockup-when-upgraded-to-515-76-and-dual-rtx3060/228912).

Unfortunately, it seems to only affect certain recent versions I can't test for multiple reasons.

I'm willing to merge if someone can verify the issue is fixed now.

**Comment by dataCobra** [comment]
It seems like the [issues](https://forums.developer.nvidia.com/t/bug-report-black-x11-screen-and-partial-lockup-when-upgraded-to-515-76-and-dual-rtx3060/228912) are not fixed with the current release of 515.76.

I can update the package to [520.56.06](https://www.nvidia.com/Download/driverResults.aspx/193764/en-us), with this version the problem was fixed.

Currently, there do not seem to be any known critical bugs.

**Comment by dataCobra** [comment]
I've tested 520.56.06 successfully. :+1:

**Comment by dataCobra** [comment]
@abenson what is your opinion?

I'm running 520.56.06 for a week now without any issues. :+1:

**Comment by abenson** [comment]
We typically avoid the New-Feature Branch and try to stick with the Production Branch, keeping in-line with Void policies.

[515.86.01](https://www.nvidia.com/Download/driverResults.aspx/194662/en-us/) was just released, which fixes the regression 515.76 introduced.

**Comment by abenson** [comment]
I recommend hold on to this PR, keep testing, and we'll be ready for the next big bump.

**Comment by dataCobra** [comment]
> I recommend hold on to this PR, keep testing, and we'll be ready for the next big bump.

Sounds good to me. :+1:

**Comment by abenson** [comment]
[Next big bump!](https://www.nvidia.com/Download/driverResults.aspx/196723/en-us/).  525.60.11 is out!

**Pull request closed without merging**
