### PR TITLE
openocd: add support for TI XDS110 and SimpleLink devices

### PR DESCRIPTION
**Pull request by Gigahawk**
These changes have been merged into upstream for almost a year now, and are released as a source distribution on [TI's site](http://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/simplelink-openocd/latest/index_FDS.html), but openocd hasn't tagged a new release for the past two years.

### CODE REVIEW

**Comment by Gigahawk** [comment]
Would it make sense to host what is essentially a fork of openocd that conflicts with the default package?

I could rename the binary so that there's no conflict but I'm just not sure if that's the best way to do this.

**Comment by knusbaum** [comment]
Sorry, I misunderstood the situation. 
Upon closer inspection, I see that TI contributed some code to openocd, which was merged, but openocd has not published a release since then.

I can't speak for this repo's maintainers, but I don't think it's a good idea to merge what amounts to a fork of openocd into this repository. The patch set is really huge and adds features. The best option is to get openocd to release a new version. It's possible to compile a version from a newer git revision in the openocd repository, but I doubt that would be accepted either, especially when proper releases exist.

Another option might be to have a `openocd-ti` package that contains TI's openocd distribution.

**Comment by jnbr** [comment]
Adding a 21kloc patch is not an option.
Please find another solution. Viable options would be to ask upstream to create a new release or create a fork.

**Comment by ericonr** [comment]
OpenOCD is not very good about tagging releases. We can only patiently wait. I really recommend installing by yourself from master for now.

**Pull request closed without merging**
