### PR TITLE
cargo: added patch for #28372

### PR DESCRIPTION
**Pull request by RossComputerGuy**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Please add where the patch came from at the top of the file.

**Comment by RossComputerGuy** [comment]
I have done that now

**Comment by ericonr** [comment]
This should still be a single commit. Please squash them.

**Comment by RossComputerGuy** [comment]
Ok, I tried to do that

**Comment by ericonr** [comment]
That's not what you did... https://github.com/void-linux/void-packages/pull/28373/commits

**Comment by RossComputerGuy** [comment]
https://www.git-tower.com/learn/git/faq/git-squash/ I followed what this website did, `git rebase -i HEAD~2` then I edited the last one to say "squash" instead of "push". But when I did that, it said that `git pull` and a merge is needed.

**Comment by RossComputerGuy** [comment]
I tried to squash it again

**Comment by ericonr** [comment]
You're trying to merge it with itself, this just shouldn't happen... Are you pushing with `git push -f` ?

**Comment by RossComputerGuy** [comment]
I'm just pushing like normal

**Comment by ericonr** [comment]
Yeah don't do that. You need to force push so it overwrites the changes here (which we want).

**Comment by RossComputerGuy** [comment]
I think I got it now

**Comment by ericonr** [comment]
Since this didn't trigger a CI run (feel free to improve the hook to detect changes in files other than templates), I will test manually in a bit.

**Pull request merged**
