### PR TITLE
New package: drawio-desktop-14.6.13

### PR DESCRIPTION
**Pull request by noarchwastaken**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by noarchwastaken** [comment]
I'm not sure whether the desktop entry should be called `draw.io` or `diagrams.net`.

The former is still used everywhere internally, including the executable script and the desktop file in the "official" appimage, and the latter is the current "supposed" branding but is only used in places like the about page and the window title.

**Comment by Johnnynator** [comment]
All these `find` and `for` loops make that template quite ugly to read imo. Maybe electron builder can be abused to provide a more usable directory structure.

Regarding naming an so, you could just take a look at the official '.deb' or '.rpm' and copy the naming from there.

**Comment by noarchwastaken** [comment]
> All these `find` and `for` loops make that template quite ugly to read imo.

Most of these are just to keep the destdir clean; [The AUR package](https://aur.archlinux.org/packages/drawio-desktop/) that I'm referencing from is pretty cursed in some places, I tweaked it significantly but kept the cleanup process.
I'm pretty sure everything will work fine without the cleanup; but the size of the produced package might be a tiny bit bigger.
Your opinion on removing that bit for extra readability?

> Maybe electron builder can be abused to provide a more usable directory structure.

I had a peek at your `Rocket.Chat-Desktop` package, it seems like Rocket.Chat supports `electron-builder` OOTB so you can simply `yarn run electron-builder ...` to build it.
However `draw.io` doesn't seem to support it, so I might have to write an `electron-builder.json` and so on...

> Regarding naming an so, you could just take a look at the official '.deb' or '.rpm' and copy the naming from there.

The official `.deb` and `.rpm` are pretty much just uncompressed appimage, installed in `/opt`. They still use `drawio`, so I think I'm fine here.

**Comment by noarchwastaken** [comment]
@Johnnynator nvm, I just realized that drawio-desktop actually have electron-builder configs.

I have updated the template to use electron-builder, please have a look ;)

**Pull request closed without merging**
