### PR TITLE
meson: copy vim files to neovim's runtime dir

### PR DESCRIPTION
**Pull request by maybe-one-day-ubermensch**

### CODE REVIEW

**Comment by sgn** [comment]
Sorry, I tempted to tell you to bug neovim people to read those files explicitly instead

**Comment by sgn** [comment]
Related to #21733

**Comment by maybe-one-day-ubermensch** [comment]
Sounds good!

**Comment by maybe-one-day-ubermensch** [comment]
I can understand the reluctance in merging this, but it'd be nice to have meson's runtime files work out of the box with neovim.

**Comment by Johnnynator** [comment]
If you want them installed twice, just symlink to the vim files instead of duplicating the files.

**Comment by maybe-one-day-ubermensch** [comment]
Done!

**Comment by ericonr** [comment]
Fixed commit message and merged!

**Comment by maybe-one-day-ubermensch** [comment]
Awesome, thanks!

**Pull request closed without merging**
