### PR TITLE
perl: update to 5.34

### PR DESCRIPTION
**Pull request by dkwo**
This is my attempt: perl builds and tests ok on x86_64.
Had to remove a part of a patch, and add a variable to skip certain tests.

### CODE REVIEW

**Comment by dkwo** [comment]
In the meantime, I have a question: `xbps-query -RX perl` lists all packages that depend on `perl`.
Those include e.g. `texlive2020-bin`, which was not revbumped last time (5.32): what is the criterion for ignoring some?

Moreover, how do I list the packages that `(host)makedepend` on perl, to be revbumped?

**Comment by dkwo** [comment]
Ok, so right now I would revbump all packages in:
```
xbps-query -RX perl | xargs -n1 xbps-uhelper getpkgname
grep -rnwl 'srcpkgs/' -e 'build_style=perl-module'
grep -rnwl 'srcpkgs/' -e 'build_style=perl-ModuleBuild'
grep -rnwl 'srcpkgs/' -e 'makedepends.*perl'
grep -rnwl 'srcpkgs/' -e 'hostmakedepends.*perl'
```
Open to suggestions.

**Comment by dkwo** [comment]
do not rebuild for the moment: texlive*, thunderbird, chromium, firefox, gcc, cross-*, qt5/6 stuff.

**Comment by ericonr** [comment]
@dkwo things that depend only on perl as `hostmakedepends` should usually not be rebuilt.

**Comment by dkwo** [comment]
Had to update `perl-Business-ISBN-Data` and remove its patch.

**Comment by dkwo** [comment]
@ericonr Thanks, I'm now testing that everything builds.

**Comment by Chocimier** [comment]
Perl modules in general and packages depending on perl don't need to be rebuild either. 5.32 rebuild was big because of noarch, but 5.30 only had packages requiring perl versioned soname, you can get list with `xbps-query -p shlib-requires -Rs libperl.so.5.32`

**Comment by dkwo** [comment]
@Chocimier thanks, now it looks better.

I built everything on `x86_64` and checked `perl`.
Only package I'm unsure about is `perl-Crypt-Rijndael`: to update it, had to remove a patch.
I may revbump a few more to pass `biber` tests as well, other than that it should be ready.

**Comment by dkwo** [comment]
I fixed all lint errors, except for
```
$ xlint perl-Barcode-ZBar
/tmp/build/void-packages/srcpkgs/perl-Barcode-ZBar/template:5: wrksrc should be a top-level directory
```
How should I deal with it?

**Comment by sgn** [comment]
> I fixed all lint errors, except for
> 
> ```
> $ xlint perl-Barcode-ZBar
> /tmp/build/void-packages/srcpkgs/perl-Barcode-ZBar/template:5: wrksrc should be a top-level directory
> ```
> 
> How should I deal with it?

#31844

**Comment by leahneukirchen** [comment]
```
% gg shlib_requires.*perl
HEAD:liboping/template: shlib_requires="libperl.so.5.32"
HEAD:perl-Lchown/template:shlib_requires=libperl.so.5.32
HEAD:rrdtool/template:  shlib_requires="libperl.so.5.32"
```

you need to bump these references too.

**Comment by dkwo** [comment]
@leahneukirchen Thanks.

Any idea how to fix this perl test failure?

```
Test Summary Report
-------------------
../lib/ExtUtils/t/Embed.t                                          (Wstat: 0 Tests: 6 Failed: 1)
  Failed test:  10
  Parse errors: Tests out of sequence.  Found (10) but expected (6)
                Bad plan.  You planned 10 tests but ran 6.
Files=2676, Tests=1191415, 574 wallclock secs (98.26 usr 19.10 sys + 635.60 cusr 69.57 csys = 822.53 CPU)
Result: FAIL
```
I can imagine how to fix musl locale, as e.g. in alpine..

**Comment by leahneukirchen** [comment]
I don't know really. The math bug also appeared in prior release.

IMO we can ignore it...

**Comment by dkwo** [comment]
Currently, besides `perl` itself, on my `x86_64` these fails some tests:
```
srcpkgs/biber/template
srcpkgs/gnumeric/template
srcpkgs/perl-Devel-Caller/template
srcpkgs/perl-Fuse/template
srcpkgs/perl-Gtk2/template
srcpkgs/perl-HTML-Parser/template
srcpkgs/perl-Image-Sane/template
srcpkgs/perl-Linux-Inotify2/template
srcpkgs/perl-OpenGL/template
srcpkgs/perl-Search-Xapian/template
srcpkgs/perl-Unix-Mknod/template
srcpkgs/perl-pcsc/template
srcpkgs/postgresql12/template
srcpkgs/postgresql13/template
srcpkgs/rrdtool/template
srcpkgs/subversion/template
```

**Comment by dkwo** [comment]
If I rebuild and check perl, _after_ I built everything else, then
`All tests successful.`
in particular
`../lib/ExtUtils/t/Embed.t ............................................ ok`

**Comment by leahneukirchen** [comment]
You mean the checkdepends? Because the perl package shouldn't depend on other stuff that makes a difference there?

**Comment by dkwo** [comment]
@leahneukirchen That's what confuses me: none of the `checkdepends` of `perl` are rebuilt in this pr, but if I first do `./xbps-pkg update-bulk` and then `./xbps-pkg -f perl` (I set `XBPS_CHECK_PKGS=full`), then `perl` passes the tests (see above), so I do not know why it fails on ci.

Btw, I fixed a couple of `checkdepends` for the failures above, and I'm left with test failures in
```
srcpkgs/biber/template
srcpkgs/gnumeric/template
srcpkgs/perl-Fuse/template
srcpkgs/perl-Gtk2/template
srcpkgs/perl-Image-Sane/template
srcpkgs/perl-Linux-Inotify2/template
srcpkgs/perl-OpenGL/template
srcpkgs/perl-Search-Xapian/template
srcpkgs/perl-Unix-Mknod/template
srcpkgs/perl-pcsc/template
srcpkgs/postgresql12/template
srcpkgs/postgresql13/template
srcpkgs/rrdtool/template
srcpkgs/subversion/template
```
as for biber, it can be removed from this pr, where it does not belong, but what about remaining others?
should I be happy with `make_check=no`?

**Comment by leahneukirchen** [comment]
I'm ok with the packages building on some platform in CI and we can just merge this then if you think it's ready.

**Comment by dkwo** [comment]
@leahneukirchen I think it is ready, so you can go ahead.

To summarise, for future reference: these fail some tests (some of them probably failed before the update):
```
srcpkgs/gnumeric/template
srcpkgs/perl-Fuse/template
srcpkgs/perl-Gtk2/template
srcpkgs/perl-Image-Sane/template
srcpkgs/perl-Linux-Inotify2/template
srcpkgs/perl-OpenGL/template
srcpkgs/perl-Search-Xapian/template
srcpkgs/perl-Unix-Mknod/template
srcpkgs/perl-pcsc/template
srcpkgs/postgresql12/template
srcpkgs/postgresql13/template
srcpkgs/rrdtool/template
srcpkgs/subversion/template
```

The `perl` itself passes all tests on `x86_64`, so at worst it could fail locale on `x86_64-musl` and math on `i686`.

As for `srcpkgs/biber/template`, I left it with this PR, even though it was not required.
Will come back to its test failures maybe later.

As a final note, it would be nice to have a mechanism to force CI to first build all commits, and only do checks later, not sure if it's possible though.

**Comment by leahneukirchen** [comment]
I agree, but that's how the CI currently is.

**Comment by leahneukirchen** [comment]
merged with git-merge-pr, as the UI doesn't like rebasing big PR.

**Comment by dkwo** [comment]
Just for future reference: it seems also
```
perl-Specio
perl-File-ShareDir
perl-DateTime-Locale
perl-Params-Validate
```
need a rebuild (all passing checks).

**Pull request closed without merging**
