### PR TITLE
haskell-language-server: update to 1.5.1.

### PR DESCRIPTION
**Pull request by motorto**
#### Testing the changes
- I tested the changes in this PR: yes

#### Local build testing
- I built this PR locally for my native architecture, x86-64-glibc

### CODE REVIEW

**Comment by ericonr** [comment]
> As we noted in the previous release we have dropped support for ghc versions 8.6.4, 8.10.2, 8.10.3, 8.10.4 in this release

Interesting that it still works for us, since that happened in 1.5.0.

**Comment by motorto** [comment]
Hum ... Actually weird but it builds and I am currently using it actively for my project ... Wanna maybe wait for #33850, @ericonr ?

**Comment by ericonr** [comment]
Yeah it might be okay to merge, I just don't know enough about Haskell to know what removing support for older GHC entails.

If it's just not guaranteeing support but not outright breaking stuff, it should be ok to merge. Do you know if you can find that out?

**Comment by motorto** [comment]
As I said I am currently using it on my school project, and everything
seems to work fine. 

To be honest with you I am no Haskell expert to tell it certainty that it means no outright breaking stuff,I could ask on
hls GitHub and see their answer...

@slotThe  whats your opinion ?

**Comment by slotThe** [comment]
> @slotThe whats your opinion ?

"Dropping support" here basically means that i) stuff won't be tested against 8.10.4 anymore (which includes the updating to a stackage resolver for 8.10.7 in which things _might_ break with 8.10.4) and ii) depending on [some `8.10.7` compatible version](https://github.com/haskell/haskell-language-server/pull/2197/files#diff-7fec8325c6bd8bb86738dbe9638c6eb14d8f4eb7df78d8052a0244961648fb4a) of `ghc-lib` (basically, GHCs API since we want to parse and transform Haskell code).

Since the bumps from 8.10.4 -> 8.10.7 were mostly with regards to other platforms having some problems, this should be a case of "if it builds then it works", so we can merge this without too much trouble.

Though that reminds me that #33850 has essentially been "done" for quite a while—should get onto that again :)

**Pull request closed without merging**
