### PR TITLE
New package: got-0.70

### PR DESCRIPTION
**Pull request by omar-polo**
#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture (aarch64-glibc)

### CODE REVIEW

**Comment by leahneukirchen** [comment]
Leading whitespace error in line 17.

This should fix cross: https://l2.re/Ntreyu

**Comment by omar-polo** [comment]
thanks @leahneukirchen!  I've merged your patch and started to cross compile for x86_64, but I figured it would be faster to just push the changes and see if the workers manage to build (building on a rpi tends to take time...)

**Comment by omar-polo** [comment]
updated to got 0.70

**Comment by omar-polo** [comment]
Thanks!

**Comment by omar-polo** [comment]
P.S. @leahneukirchen I've upstreamed the `configure.ac` patch, will be included in the next release.  thanks :)

**Pull request merged**
