### PR TITLE
python3-dotenv: update to 0.18.0.

### PR DESCRIPTION
**Pull request by kartikynwa**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (x86_64)
- [ ] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [ ] aarch64-musl
  - [ ] armv7l
  - [ ] armv6l-musl

#### Notes

The only package that depends on this is `docker-compose`. I don't think it needs to be rebuilt since it's a python3 module. Am I correct?

### CODE REVIEW

**Comment by ericonr** [comment]
> The only package that depends on this is docker-compose. I don't think it needs to be rebuilt since it's a python3 module. Am I correct?

yes :)

Do you have `ci-skip` somewhere?

**Comment by ericonr** [comment]
I assume you've tested docker-compose with this?

**Comment by kartikynwa** [comment]
@ericonr

I didn't use ci-skip anywhere. Will force push a commit and see if it triggers the builds.


I have tested it. I use it on my machine for development. Here is a short example:

```
~/docker-compose-test
❯ xbps-query python3-dotenv | grep ver
pkgver: python3-dotenv-0.17.1_1

~/docker-compose-test
❯ cat docker-compose.yml
version: "3.9"

services:
  hello:
    container_name: ${NAME}
    image: hello-world:latest

~/docker-compose-test
❯ cat .env
NAME=hello-world-container

~/docker-compose-test
❯ sudo docker-compose up
Starting hello-world-container ... done
Attaching to hello-world-container
hello-world-container |
hello-world-container | Hello from Docker!
hello-world-container | This message shows that your installation appears to be working correctly.
hello-world-container |
hello-world-container | To generate this message, Docker took the following steps:
hello-world-container |  1. The Docker client contacted the Docker daemon.
hello-world-container |  2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
hello-world-container |     (amd64)
hello-world-container |  3. The Docker daemon created a new container from that image which runs the
hello-world-container |     executable that produces the output you are currently reading.
hello-world-container |  4. The Docker daemon streamed that output to the Docker client, which sent it
hello-world-container |     to your terminal.
hello-world-container |
hello-world-container | To try something more ambitious, you can run an Ubuntu container with:
hello-world-container |  $ docker run -it ubuntu bash
hello-world-container |
hello-world-container | Share images, automate workflows, and more with a free Docker ID:
hello-world-container |  https://hub.docker.com/
hello-world-container |
hello-world-container | For more examples and ideas, visit:
hello-world-container |  https://docs.docker.com/get-started/
hello-world-container |
hello-world-container exited with code 0
```

**Comment by kartikynwa** [comment]
@ericonr So some of the tests are failing because the test suite is using `python3-sh` to call `dotenv` which is an executable installed by this package which is not found. I am guessing it's not installed or it's not in the $PATH. Any idea what I can do about this?

**Comment by ericonr** [comment]
If you can figure out a way to skip those tests, I think we can push the package with tests enabled (might be missing `python3-ipython` in `checkdepends` though.

Otherwise, `make_check=no` with a comment is a good hammer to disable tests.

**Comment by kartikynwa** [comment]
@ericonr 

I have updated the template to skip tests that didn't work with xbps-src. For this, I have added a `do_check` function. First I tried adding the a line like:

```bash
make_check_args="-k 'not test_cli'"
```

But it would throw this error: `ERROR: file or directory not found: test_cli'`

So I ended up redefining the `do_check` function. Let me know if you want any changes.

**Comment by kartikynwa** [comment]
Nevermind I ended up not using quotes inside `make_check_args` and it works now.

**Comment by ericonr** [comment]
Assuming it works, it seems 0.18.0 is out D:

**Comment by kartikynwa** [comment]
@ericonr I will update it to 0.18 in a bit.

**Comment by kartikynwa** [comment]
@ericonr Have tested the update and it works fine. Both as python module and cli. I have tested it with docker-compose as well and it works there too.

The issues with some test cases failing in xbps-src still persist so I have left the `make_check_args` variable intact. I tried without it first but the build fails.

**Pull request merged**
