### PR TITLE
wesnoth: update to 1.14.9

### PR DESCRIPTION
**Pull request by obunden**

### CODE REVIEW

**Comment by obunden** [comment]
Seems like the compilation is spamming travis a bit too much. What would be the right way to go about fixing this? I tried passing different options to the configure_args but it doesn't affect the output. I thought the '-Wno-deprecated' option in cmake would get rid of the problem but there is a lot of warnings about old style casts still. Not sure how to see if the option is used or not, might it be the xbps cmake build script that overrides it?

I would be glad to get some input on how to solve this the right way.

**Comment by Hoshpak** [comment]
I wouldn't bother with it at all. There are many packages that don't pass travis because they take too long to compile or produce too much output. Passing travis is an indicator that the build works, not a strict requirement for a PR to be merged.

The build should be tested manually for the relevant architectures in this case. If you don't have the time or hardware resources to do it, I could run some builds later.

**Comment by obunden** [comment]
The hardware is probably the biggest problem. I don't have musl installed anywhere right now but that could probably be arranged. But even then I only have access to x86/x86_64. So if you/someone else could test it on the other platforms that would surely help things. I'll post an update here when I tested everything that I can, but not sure when I will get the time.

**Comment by Hoshpak** [comment]
x86_64 is fine, it's the architecture the build servers are running. I don't have Void running on any other architecture either. xbps-src gives you everything you need to cross-compile to another architecture or have a separate masterdir for a compatible architecture.

To cross-compile, you just pass the target architecture with `-a`, like
```
./xbps-src -a armv6l pkg wesnoth
```

For a compatible architecture, just create a separate masterdir once and use that to compile, e.g.
```
./xbps-src -m musl binary-bootstrap x86_64-musl
./xbps-src -m musl pkg wesnoth
```

But I don't want to burden you too much, I'm currently running some builds for musl and several cross-compiled architectures and will merge if they pass.

**Comment by obunden** [comment]
That's neat, good to know. Thanks once again for all the help. Hopefully I can be a bit more self-reliant if I manage to learn some more about all of this stuff.

**Pull request merged**
