### PR TITLE
chromium: create debug package on 64bit archs

### PR DESCRIPTION
**Pull request by Johnnynator**
[ci skip]

### CODE REVIEW

**Comment by anddam** [comment]
I tried something similar (passing `-g` in `C*FLAGS`) and got a binary without debugging symbols.

Can you confirm the resulting binary has debugging symbols?

**Comment by Johnnynator** [comment]
The binary will be stripped, the debug symbols will be in a package called chromium-dbg.

**Comment by Johnnynator** [comment]
Not for myself:
setting `symbol_level = 1` / `symbol_level = 0` instead `-g` might be better?

**Comment by ericonr** [comment]
Ping?

**Comment by Johnnynator** [comment]
pong :)

**Pull request closed without merging**
