### PR TITLE
xnots: Add aarch64 support

### PR DESCRIPTION
**Pull request by ndowens**

### CODE REVIEW

**Comment by Chocimier** [comment]
I'm not so sure. Filename is arch/arm64/include/asm/unistd32.h, talks about "AArch32 (compat) system call definitions". [Values](https://github.com/seccomp/libseccomp/blob/master/src/arch-aarch64-syscalls.c) here are different. Will have to dig deeper.

**Comment by ndowens** [comment]
Yea I am not sur either. When searching I found values that was even lower
than arm, which I believed wouldn’t be correct. I would expect it to be
atleast equal or more than arm[67]

**Comment by Chocimier** [comment]
We should just use upstream patch https://github.com/thePalindrome/xnots/commit/2a86dd618f864faaaa6f5b7e3c2f5528d33220d7.patch

**Comment by ndowens** [comment]
> We should just use upstream patch https://github.com/thePalindrome/xnots/commit/2a86dd618f864faaaa6f5b7e3c2f5528d33220d7.patch

Ah figures, one I overlooked. Did a search for a fix and didn’t see this, so I ended up searching for values arm64 would use. Will apply this ASAP , thanks

**Comment by ndowens** [comment]
Ok, have added upstream's patch to remove their definitions and use libc*, which also works on -musl

**Pull request merged**
