### PR TITLE
wxWidgets: rebuild to fix ABI mismatch 

### LINKED ISSUE #1785: Erlang built with -o x11 link error
### System

* xuname:  
  Void 4.17.14_1 x86_64 GenuineIntel uptodate rFFF
* package:  
  erlang-21.0

### Expected behavior
Compiled with `-o x11` should link with `wx` libraries and it should run graphical applications, like `observer:start()`.

### Actual behavior
`observer:start()` doesn't work and throws an error like:
```=CRASH REPORT==== 15-Aug-2018::07:49:14.974426 ===
  crasher:
    initial call: observer_wx:init/1
    pid: <0.83.0>
    registered_name: observer
    exception exit: {{load_driver,"undefined symbol: _ZThn704_N17wxGenericListCtrl31GetSizeAvailableForScrollTargetERK6wxSize"},
                     [{wxe_server,start,1,[{file,"wxe_server.erl"},{line,65}]},
                      {wx,new,1,[{file,"wx.erl"},{line,115}]},
                      {observer_wx,init,1,
                                   [{file,"observer_wx.erl"},{line,98}]},
                      {wx_object,init_it,6,
                                 [{file,"wx_object.erl"},{line,372}]},
                      {proc_lib,init_p_do_apply,3,
                                [{file,"proc_lib.erl"},{line,249}]}]}
      in function  wx_object:init_it/6 (wx_object.erl, line 385)
    ancestors: [<0.81.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: [{'_wx_object_',{observer_wx,'_wx_init_'}}]
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 292
  neighbours:
```

### Steps to reproduce the behavior

Compile with:
```
./xbps-src clean erlang
./xbps-src pkg -o x11 erlang
sudo xbps-install --repository=hostdir/binpkgs erlang
```
Then run with:
```
erl
observer:start().
```

### PR DESCRIPTION
**Pull request by Johnnynator**
[ci skip]
resolves #1785 

Mostly untested so far, feel free to test it.

### CODE REVIEW

**Comment by Johnnynator** [comment]
Dolpin-emu broken:
```
[ 26%] Building CXX object Source/Core/Common/CMakeFiles/common.dir/GL/GLExtensions/GLExtensions.cpp.o
/builddir/dolphin-5.0/Source/Core/Common/x64CPUDetect.cpp:45:12: error: ambiguating new declaration of 'u64 _xgetbv(u32)'
 static u64 _xgetbv(u32 index)
            ^~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-musl/8.2/include/x86intrin.h:74,
                 from /builddir/dolphin-5.0/Source/Core/Common/Intrinsics.h:12,
                 from /builddir/dolphin-5.0/Source/Core/Common/x64CPUDetect.cpp:10:
```

**Comment by cr6git** [comment]
Debian patches:
https://sources.debian.org/patches/dolphin-emu/5.0+dfsg-3/01_shared-gtest.patch/
https://sources.debian.org/patches/dolphin-emu/5.0+dfsg-3/02_glibc-2.26.patch/
https://sources.debian.org/patches/dolphin-emu/5.0+dfsg-3/03_gcc8.patch/

Looks like WX is not enabled in Arch?
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/dolphin-emu

**Comment by Johnnynator** [comment]
@cr6git Thanks for providing these links. I just backported the gcc8 patch already myself. Arch is using the git version of dolpin-emu which uses qt5 already.

**Comment by Johnnynator** [comment]
DarkRadiant is broken (musl (?))
```
In file included from ../../libs/os/file.h:4,
                 from FileChooser.cpp:9:
../../libs/os/fs.h:20:21: error: 'filesystem' is not a namespace-name
 namespace fs = std::filesystem;
```

**Comment by newbluemoon** [comment]
Regarding DarkRadiant:

libstdc++-devel-7.3.0 only had `/usr/include/c++/7.3/experimental/filesystem`.

With libstdc++-devel-8.2.0 there’s now `/usr/include/c++/8.2/experimental/filesystem` and `/usr/include/c++/8.2/filesystem`. `configure` seems to prefer the latter which doesn’t work for some reason. But when patching `configure.ac` to only check for `experimental/filesystem` it works again.

```
--- configure.ac.orig	2018-05-10 19:35:33.000000000 +0200
+++ configure.ac	2018-08-20 09:00:29.197395807 +0200
@@ -159,23 +159,13 @@
 # By default, we rely on boost.filesystem, unless we have the C++17 libs 
 use_boost_filesystem=yes
 
-# Check for the regular C++17 <filesystem> header
-AC_CHECK_HEADER([filesystem], [found_std_filesystem=yes], [found_std_filesystem=no])
+AC_CHECK_HEADER([experimental/filesystem], [found_experimental_filesystem=yes], [found_experimental_filesystem=no])
 
-# if no <filesystem> is present, check for the pre-C++17 header <experimental/filesystem>
-if test "$found_std_filesystem" = "yes"
+if test "$found_experimental_filesystem" = "yes"
 then
-    AC_DEFINE([HAVE_STD_FILESYSTEM], [1], [Define this to indicate that the <filesystem> header is available for inclusion.])
-    use_boost_filesystem=no
-else
-    AC_CHECK_HEADER([experimental/filesystem], [found_experimental_filesystem=yes], [found_experimental_filesystem=no])
-    
-    if test "$found_experimental_filesystem" = "yes"
-    then
-        AC_DEFINE([HAVE_EXPERIMENTAL_FILESYSTEM], [1], [Define this to indicate that the <experimental/filesystem> 
-                                                        header is available for inclusion.])
-        use_boost_filesystem=no
-    fi
+AC_DEFINE([HAVE_EXPERIMENTAL_FILESYSTEM], [1], [Define this to indicate that the <experimental/filesystem> 
+						header is available for inclusion.])
+use_boost_filesystem=no
 fi
 
 FILESYSTEM_LIBS=''
```

Trying to find out what the problem with `<filesystem>` is...

**Comment by Johnnynator** [comment]
@newbluemoon I added the Debian patch to Dark Radiant already yesterday. Only pcsx2 is missing. Everything else should be fine

**Comment by newbluemoon** [comment]
@Johnnynator Sorry, didn’t notice. :)

**Comment by newbluemoon** [comment]
@Johnnynator Ah, I see. :) I can confirm that it builds and starts up ok. I can’t do much more with it as I don’t have any required PS2 data.

**Pull request merged**
