### PR TITLE
New package: io.elementary.calendar-4.2.3

### PR DESCRIPTION
**Pull request by CameronNemo**

### CODE REVIEW

**Comment by maxice8** [comment]
No symlinks for the subpkgs were made

**Comment by CameronNemo** [comment]
My bad. Thank you for catching that.

**Comment by maxice8** [comment]
Travis did

**Comment by Hoshpak** [comment]
please rebase and resolve the conflict

**Comment by maxice8** [comment]
Merged after fixing shlibs and -devel dependencies

**Comment by CameronNemo** [comment]
Thanks!

**Pull request closed without merging**
