### PR TITLE
New package: diffuse-0.4.8

### PR DESCRIPTION
**Pull request by Gigahawk**

### CODE REVIEW

**Comment by jnbr** [comment]
Does it work with python3 as well?

**Comment by Gigahawk** [comment]
No, it uses python2 only syntax.

I've never tried updating it to work with both but if it's non trivial I don't mind creating a patch for it.

**Comment by Gottox** [comment]
I don't think adding any more python2 packages make sense as python2 has only a few months of support left.

**Comment by Gigahawk** [comment]
Fair enough, are python2 packages being removed when support ends?

**Pull request closed without merging**
