### PR TITLE
android-file-transfer-linux: update to 4.2.

### PR DESCRIPTION
**Pull request by uw2021**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by uw2021** [comment]
Works flawlessly except for one thing. On 4.0, when I didn't have a device plugged in and tried to launch it would throw up an error saying 'no MTP device connected'. Now, it doesn't open anything at all when lanched and a device isn't plugged in, which might confuse some. Might be specific to my system, I'm not sure yet.

**Comment by uw2021** [comment]
> Works flawlessly except for one thing. On 4.0, when I didn't have a device plugged in and tried to launch it would throw up an error saying 'no MTP device connected'. Now, it doesn't open anything at all when lanched and a device isn't plugged in, which might confuse some. When a device is plugged in, it runs and works fine. Might be specific to my system, I'm not sure yet.

Confirmed by another user with the same issue on x86_64 and aarch64-musl.

**Comment by ericonr** [comment]
I will be merging for now, since it fixes some important suff for samsung. please reach out to upstream to ask if this behavior is intended, since I didn't see anything in release notes.

**Comment by uw2021** [comment]
> I will be merging for now, since it fixes some important suff for samsung. please reach out to upstream to ask if this behavior is intended, since I didn't see anything in release notes.

Will do, cheers.

**Pull request merged**
