### PR TITLE
scrcpy: update to 2.3

### PR DESCRIPTION
**Pull request by devlocalhost**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by devlocalhost** [comment]
scrcpy 2.2 adds a new feature which allows you to use your phones camera as a webcam: http://0x0.st/Hy08.png

**Comment by mhmdanas** [comment]
It looks good, but you have to use an actual e-mail address for your commit (this is why the lint GitHub action failed). To do so, run these commands (replacing john.doe@example.com with your actual e-mail address, not a GitHub-provided one):
```
$ git config --global user.email john.doe@example.com
$ git commit --amend --reset-author
$ git push -f
```

**Comment by lemmi** [comment]
I'll quickly mention @daniel-eys, since they did the last couple of updates.

**Comment by devlocalhost** [comment]
linting failed again, why? i followed the steps mhmdanas told me

**Comment by daniel-eys** [comment]
Works for me, but the new camera feature seems to have some issues https://github.com/Genymobile/scrcpy/issues/4392

**Comment by daniel-eys** [comment]
2.3 has been released which fixes the camera issues :tada:

**Comment by devlocalhost** [comment]
Bumped version, but I didn't build because it's 4 am lol. Will check in the morning

**Comment by daniel-eys** [comment]
> Bumped version, but I didn't test (build on my machine) because it's 4 am lol. Will check in the morning
> 
> A question: should I update the PR's name? (2.2 to 2.3)

yes and please squash the commits into one

**Comment by biopsin** [comment]
surpassed @ #47926

**Comment by devlocalhost** [comment]
I wonder why it commit wasn't already pushed...

**Pull request closed without merging**
