### PR TITLE
cgminer: remove package

### PR DESCRIPTION
**Pull request by classabbyamp**
cgminer:
- Upstream is archived and hasn't had a commit or release since 2018
- Template last touched in 2020 (to update cflags), last updated in 2018
- Popcorn lists no usage (out of 75)

~~libbitcoin-*:~~
- ~~unused libraries~~
- ~~excludes libbitcoin-secp256k1, which is used by electrum~~

#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by atweiden** [comment]
libbitcoin-explorer isn’t strictly a library, it also provides a `bx` executable, which has been written about [here](http://aaronjaramillo.org/category/libbitcoindocs).

libbitcoin-server too isn’t strictly a library: it provides a `bs` executable (and libbitcoin-node a `bn` executable).

What’s the rationale for removing these templates?

**Comment by classabbyamp** [comment]
> What’s the rationale for removing these templates?

They seemed to be unused libraries. if they aren't (as you say), I'll remove them from this

**Comment by paper42** [comment]
>     * Upstream is archived and hasn't had a commit or release since 2018

Could you include this in the commit message body?

**Comment by classabbyamp** [comment]
> Could you include this in the commit message body?
done

**Pull request merged**
