### PR TITLE
asio: update to 1.18.0

### PR DESCRIPTION
**Pull request by ndowens**

### CODE REVIEW

**Comment by ericonr** [comment]
Can we simply remove this package instead?

**Comment by sgn** [comment]
On 2020-11-08 19:26:46-0800, Érico Nogueira Rolim <notifications@github.com> wrote:
> Can we simply remove this package instead?

I'm pretty sure asio is provided by boost::asio.

**Comment by ndowens** [comment]
I've removed instead of updated as asked to

**Comment by ahesford** [comment]
The `asio` library is an alternative to `boost::asio`: https://think-async.com/Asio/

I wouldn't hastily remove this package, and I don't know why it depends on `boost-devel`.

**Comment by ndowens** [comment]
> The `asio` library is an alternative to `boost::asio`: https://think-async.com/Asio/
> 
> I wouldn't hastily remove this package, and I don't know why it depends on `boost-devel`.

Looks like it will build fine without it. I will repush update after done testing build to make sure

**Pull request closed without merging**
