### PR TITLE
devilutionX: update to 1.5.1

### PR DESCRIPTION
**Pull request by bugcrazy**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by Duncaen** [comment]
This may be "nonfree".

**Comment by bugcrazy** [comment]
> This may be "nonfree".

It's a nonfree license!

https://blog.n8n.io/announcing-new-sustainable-use-license/

https://n8n.io/blog/fair-code-for-sustainable-open-source-alternatives/

**Comment by SolitudeSF** [comment]
https://github.com/void-linux/void-packages/pull/44521#issuecomment-1597602204

**Comment by bugcrazy** [comment]
I compiled on 2 different machines for x86_64, x86_64-musl and i686, there were no test errors.

**Comment by SolitudeSF** [comment]
Unless you somehow included game data in chroot, there should be test errors.

**Comment by bugcrazy** [comment]
> Unless you somehow included game data in chroot, there should be test errors. As indicated by CI.

I added your patch!

**Comment by kedodrill** [comment]
Fwiw, played through the shareware version of diablo with this and it was fine. Although the license changed and now must be stuck in the nonfree repo, 1.5.0 does bring a lot of fixes.

**Comment by bugcrazy** [comment]
PR is waiting for approval or not!?

**Comment by MIvanchev** [comment]
Hey, I updated to 1.5.2 in #48628 so IMO this can be closed. I did some additional patching to deal with the covert downloads of dependencies. I also fixed the failing test by downloading the shareware version during the build.

**Pull request closed without merging**
