### PR TITLE
[RFC] base-{minimal,voidstrap,system}: unify base packages

### PR DESCRIPTION
**Pull request by ahesford**
Unifying the three alternative base packages makes it easier to manage dependencies consistently, and having successively more featureful packages depend on the next more spartan package makes the additional inclusions more obvious.

If there is any real reason not to have a `base-system -> base-voidstrap -> base-minimal` dependency chain, we can still preserve dependency maintainability by defining, *e.g.*,

```sh
_minimal_depends="[...]"
_voidstrap_depends="${_minimal_depends} [...]"
```

in the header.

#### Testing the changes
- I tested the changes in this PR: **NO**

### CODE REVIEW

**Comment by ahesford** [comment]
Seeking comments from @void-linux/pkg-committers

**Comment by classabbyamp** [comment]
I like the idea.

I think having multiple `base-` packages installed might be confusing to people, so maybe the alternative approach would be better.

**Review by sgn — APPROVED** [review]

**Comment by Duncaen** [comment]
This means building `base-minima` requires a lot more dependencies, not sure how useful this really is.

**Comment by Duncaen** [comment]
Also not a fan of having the base packages depend on other base packages, this just obfuscates the dependencies for no good reason.

**Comment by classabbyamp** [comment]
> This means building `base-minimal` requires a lot more dependencies, not sure how useful this really is.

what about a build option that disables the subpackages for bootstrapping?

**Comment by sgn** [comment]
I think it's better to have 3 separated packages. I like the chain dependency, though.

**Comment by ahesford** [comment]
I don't understand why adding more dependencies to the build of `base-minimal` is a concern. We don't use it for bootstrapping; that's what `base-chroot` is for, and that's still a separate template. Maybe it adds a little more time to the build, but:
1. As far as CI and official builds are concerned, we ought to keep these dependencies in sync anyway, so any update to `base-minimal` ought to include corresponding updates to `-voidstrap` and `-system`; in that case, the build time is actually *reduced* by avoiding triple package installations.
2. Are people really building custom `base-minimal` on their own enough that we should be concerned that sombody winds up fetching the Linux kernel when building the package from the merged template? Meh.

Regarding the dependency chain: I recognize the potential for confusion or annoyance when trying to understand the full list of dependencies of the more featureful bases, but I'm not sure whether that's offset by the fact that chained dependencies makes it more obvious how the packages are related. We've seen a few questions asking for clarity about the differences, and `run_depends: base-minimal [...]` is pretty obvious in that regard. Either way, I can switch to the alternative approach (common variables in a common template to satisfy DRY while avoiding nested dependencies) if there is strong support there.

**Comment by Duncaen** [comment]
I don't really see a strong reason to unify those templates and more reason to not change anything.

- Additional build dependencies for smaller `base-*` packages.
- Changing one of the `base-*` packages requiring an "update" for all.
- More confusing to keep the order of dependencies right (important for example `gawk` being before any other dependency that pulls in the `awk` virtual package.

**Comment by ahesford** [comment]
I can't strongly defend against the criticisms here, so we might as well just persist with the status quo.

**Pull request closed without merging**
