### PR TITLE
python3-dnsrecon: update to 1.1.4

### PR DESCRIPTION
**Pull request by jason1987d**
#### Testing the changes
- I tested the changes in this PR: YES

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)
- I built this PR locally for these architectures (if supported. mark crossbuilds):

### CODE REVIEW

**Comment by tornaria** [comment]
Are you aware you don't need to close a PR and open a new one to change it?

**Comment by abenson** [comment]
Please don't open/close PRs. If you need to make changes, [amend the commits](https://www.atlassian.com/git/tutorials/rewriting-history) and force push to the branch(`git push -f`).

**Comment by jason1987d** [comment]
I only cancelled the PR because I had accidentally stapled the larger package KataGo into this (see my other PR) which would have tied up your CI workflows and CPU a second time unnecessarily. I did not see any such button or have the privs that I know of to stop the CI runs and cancelling the PR was the only way. I tried to reopen the PR but was unable to do so. That's the only reason for the bizarre situation.

**Comment by classabbyamp** [comment]
if you push it will cancel the currently-running CI, so you could have just removed the katago changes from this branch and force-pushed

**Pull request merged**
