### PR TITLE
php8.0: patch for openssl3

### PR DESCRIPTION
**Pull request by dkwo**
- I tested the changes in this PR: no
- I built this PR locally for my native architecture, (x86_64-musl)

#37681 @TinfoilSubmarine

### CODE REVIEW

**Comment by TinfoilSubmarine** [comment]
My preference is that we get https://github.com/void-linux/void-packages/pull/38536 merged. Then we can get php8.2 in repo and drop 8.0 (since 8.1+ support openssl3)

**Comment by dkwo** [comment]
That PR is dropping 7.*, right? Assuming it gets merged soon, would you mind adding this patch for 8.0 there temporarily, before that gets dropped sometimes later?

**Comment by paper42** [comment]
@TinfoilSubmarine I don't think we should drop php 8.0, it is still getting security fixes until the end of the year and some projects still prefer it. Are there some big issues with php 8.0 and openssl 3?

**Comment by TinfoilSubmarine** [comment]
It is not supported, see https://www.php.net/manual/en/openssl.requirements.php and https://bugs.php.net/bug.php?id=81540&edit=1. I don't know where this patch came from, but it's not official.

**Comment by paper42** [comment]
I would be in favor of building it with openssl1.1-compat then

**Comment by dkwo** [comment]
@paper42 Ok, but last time I tried it conflicts with openssl, which seems to be pulled in by default in the chroot. What is the right way to do it? I can then apply that also to the other removed package.

**Comment by paper42** [comment]
> @paper42 Ok, but last time I tried it conflicts with openssl, which seems to be pulled in by default in the chroot. What is the right way to do it? I can then apply that also to the other removed package.

openssl1.1-devel conflicting with openssl-devel doesn't matter because only one will be installed at one time, openssl1.1-compat can probably be an empty meta-package because I think we don't need anything it provides. Also, openssl1.1-devel probably doesn't have to depend on openssl1.1-compat, but you would have to try that.

**Comment by dkwo** [comment]
Hmm that worked for `gcsf`, but it seems something (for sure `apache-devel`, maybe others) in `php8.0` brings in `openssl-devel` independently ??

**Comment by paper42** [comment]
I guess we will have to remove this package with openssl 3.0 then

**Pull request closed without merging**
