### PR TITLE
New package: tspreed-2.0.1

### PR DESCRIPTION
**Pull request by kawaiiamber**
# Additions
Adds the shell script "tspreed." I just read the manual that seemed a little over me, I am probably doing this wrong. This is my first time ever trying contributing to VOID.

### CODE REVIEW

**Comment by kawaiiamber** [comment]
I'm not sure why the Lint templates check is failing. It is released under GPL license as seen [here](https://github.com/n-ivkovic/tspreed/blob/master/LICENSE), and "GPL-3.0-or-later" should be the right license as seen [here](https://spdx.org/licenses/GPL-3.0-or-later.html).

**Comment by ericonr** [comment]
It is complaining that the license is being installed with `vlicense`, not about the value.

Also, please squash your commits and use the appropriate commit message `New package: tspreed-${version}`

**Comment by kawaiiamber** [comment]
Umm, I tried squashing the commits and now there's more files changed for some reason. I just want to change the tspreed file (I'm not a master of git...)

**Comment by ndowens** [comment]
> Umm, I tried squashing the commits and now there's more files changed for some reason. I just want to change the tspreed file (I'm not a master of git...)

Switch to master and do git pull upstream(assuming you have https://github.com/void-linux/void-packages as upstream) master --rebase ; git push origin master

In this branch git pull upstream master --rebase ; though I don't know if it will fix if you squashed any others that doesn't belong with this commit.

**Comment by kawaiiamber** [comment]
Okay, looks like its back to just adding the tspreed template. I still am not sure how to fix Lint check failure.

**Comment by ndowens** [comment]
Remove vlicense line. Common licenses don't need it, licenses such as MIT, BSD* for example does need it

**Comment by kawaiiamber** [comment]
Removed vlicense line

**Comment by ndowens** [comment]
To squash your commits, do: git rebase -i HEAD~4 and the commits related to this package, first commit change p to r (reword), other 3 change p to f (fixup). When editor comes up change commit message to: New package: tspreed-1.2.1 , save and then git rebase --continue

**Comment by ndowens** [comment]
Error is that you need to change the very first line to: # Template file for 'tspreed' instead of # Template file for 'teespreed'

**Comment by kawaiiamber** [comment]
I'm a little new to git myself, the squash instructions fail for me. I'll keep trying stuff if squashing commits is requirement.

**Comment by ndowens** [comment]
> I'm a little new to git myself, the squash instructions fail for me. I'll keep trying stuff if squashing commits is requirement.

It kinda is because no need to many commit msgs when it only relates to one pkg.

**Comment by kawaiiamber** [comment]
I did git rebase -i HEAD~5 and it pulls up what looks like vim with this
```
  1 pick f42d507647 qemu: fix patch
  2 pick dba1c48a43 Add tspreed
  3 pick b127dd90eb New package: tspreed-1.2.1
  4 pick d7e25a2f92 polybar: update to 3.5.1.
  5 pick e945ff7070 amfora: install .desktop, sample config
  6 pick ee18ba1f2f vapoursynth: update to R52
  7 pick f802014c3e Removed vlicense line
  8
  9 # Rebase 079bba41c1..f802014c3e onto 079bba41c1 (7 commands)
 10 #
 11 # Commands:
 12 # p, pick <commit> = use commit
 13 # r, reword <commit> = use commit, but edit the commit message
 14 # e, edit <commit> = use commit, but stop for amending
 15 # s, squash <commit> = use commit, but meld into previous commit
 16 # f, fixup <commit> = like "squash", but discard this commit's log message
 17 # x, exec <command> = run command (the rest of the line) using shell
 18 # b, break = stop here (continue rebase later with 'git rebase --continue')
 19 # d, drop <commit> = remove commit
 20 # l, label <label> = label current HEAD with a name
 21 # t, reset <label> = reset HEAD to a label
 22 # m, merge [-C <commit> | -c <commit>] <label> [# <oneline>]
 23 # .       create a merge commit using the original merge commit's
 24 # .       message (or the oneline, if no original merge commit was
 25 # .       specified). Use -c <commit> to reword the commit message.
 26 #
 27 # These lines can be re-ordered; they are executed from top to bottom.
 28 #
 29 # If you remove a line here THAT COMMIT WILL BE LOST.
 30 #
 31 # However, if you remove everything, the rebase will be aborted.
 32 #
```

**Comment by ericonr** [comment]
You want to make it look like:

```
  1 pick f42d507647 qemu: fix patch
   4 pick d7e25a2f92 polybar: update to 3.5.1.
  5 pick e945ff7070 amfora: install .desktop, sample config
  6 pick ee18ba1f2f vapoursynth: update to R52
2 pick dba1c48a43 Add tspreed
  3 squash b127dd90eb New package: tspreed-1.2.1
  7 fixup f802014c3e Removed vlicense line
```

Then edit the final commit message

**Comment by ericonr** [comment]
Wow! Really sorry, I must have misclicked

**Comment by kawaiiamber** [comment]
```
[amber@otaku ~/projx/repos/void-packages]$ git push origin tspreed
Username for 'https://github.com': kawaiiamber
Password for 'https://kawaiiamber@github.com':
To https://github.com/kawaiiamber/void-packages.git
 ! [rejected]              tspreed -> tspreed (non-fast-forward)
error: failed to push some refs to 'https://github.com/kawaiiamber/void-packages.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by ndowens** [comment]
You have to force push,: git push origin tspreed -f

**Comment by kawaiiamber** [comment]
Force pushed squashed commits.

**Comment by ndowens** [comment]
You didnt edit the first one to change commit message and now something happened to break lint again

**Comment by kawaiiamber** [comment]
I think everything is fixed now. Thanks for the help.

**Comment by ndowens** [comment]
Almost but no. You added to commit message, not changed change p to r in git rebase -i HEAD~1

**Comment by kawaiiamber** [comment]
Oh. How would I fix it? I take it I first to git rebase -i HEAD~1, then what exactly does the file need to look like, then the next prompt?

**Comment by ndowens** [comment]
Since you added, Remove the first two lines and write: New package: tspreed-1.2.1

**Comment by kawaiiamber** [comment]
Upon running git rebase -i HEAD~1, is this what it should look like?
```
  1 pick 1cfc9e3113 New package: tspreed-1.2.1
  2
  3 # Rebase ee18ba1f2f..1cfc9e3113 onto ee18ba1f2f (1 command)
  4 #
  5 # Commands:
  6 # p, pick <commit> = use commit
  7 # r, reword <commit> = use commit, but edit the commit message
  8 # e, edit <commit> = use commit, but stop for amending
  9 # s, squash <commit> = use commit, but meld into previous commit
 10 # f, fixup <commit> = like "squash", but discard this commit's log message
 11 # x, exec <command> = run command (the rest of the line) using shell
 12 # b, break = stop here (continue rebase later with 'git rebase --continue')
 13 # d, drop <commit> = remove commit
 14 # l, label <label> = label current HEAD with a name
 15 # t, reset <label> = reset HEAD to a label
 16 # m, merge [-C <commit> | -c <commit>] <label> [# <oneline>]
 17 # .       create a merge commit using the original merge commit's
 18 # .       message (or the oneline, if no original merge commit was
 19 # .       specified). Use -c <commit> to reword the commit message.
 20 #
 21 # These lines can be re-ordered; they are executed from top to bottom.
 22 #
 23 # If you remove a line here THAT COMMIT WILL BE LOST.
 24 #
 25 # However, if you remove everything, the rebase will be aborted.
 26 #
```

**Comment by ndowens** [comment]
Yup

**Comment by kawaiiamber** [comment]
After :wq, I get
`Successfully rebased and updated refs/heads/tspreed.`

**Comment by ndowens** [comment]
Looks like it is fine now, maybe it was something on my end

**Comment by kawaiiamber** [comment]
I push all final changes just to be safe.
```
[amber@otaku ~/projx/repos/void-packages]$ git push origin tspreed
Username for 'https://github.com': kawaiiamber
Password for 'https://kawaiiamber@github.com':
Everything up-to-date
[amber@otaku ~/projx/repos/void-packages]$
```
On my end, there seems to be one commit with "New package: tspreed-1.2.1"

**Comment by kawaiiamber** [comment]
Added vman tspreed.1 for the man page.

**Comment by paper42** [comment]
Hi, the project has a Makefile, could you delete the do_install function and add build_style=gnu-makefile? Always prefer build_style if possible.

**Comment by kawaiiamber** [comment]
Removed `do_install()` and added `build_style=gnu-make`, sorry for the delay.

**Comment by kawaiiamber** [comment]
The checks are now failing with the following:
```
chown: changing ownership of '/usr/local/share/man/man1/tspreed.1': Invalid argument
make: *** [Makefile:32: install] Error 1
=> ERROR: tspreed-1.2.1_1: do_install: '${make_cmd} STRIP=true PREFIX=/usr DESTDIR=${DESTDIR}
${make_install_args} ${make_install_target}' exited with 2
=> ERROR:   in do_install() at common/build-style/gnu-makefile.sh:40
```
It looks like it's failing to do something with ownership of the man page?

**Comment by paper42** [comment]
looking at the makefile, this seems to be the first issue I see...
```
chown 644 $(MANDIR)$(EXEC).$(MANSEC)
```
chown's first parameter is the username of the owner of the file, so it seems like the command should be `chmod`. The Makefile is exceptionally bad in this package, so I take my recommendation back. You can try to fix the makefile upstream or use the do_install function without build_style like you were using previously. I am sorry I recommended something wrong to you, but it seems to be the project's fault. Makefiles should never touch ~/.config nor should they try to change the owner of files.

**Comment by kawaiiamber** [comment]
No problem, understood. I updated to use `vbin` and `vman` as upstream's Makefile seems to have problems.

**Comment by kawaiiamber** [comment]
I made PR for change of `chown` to `chmod` [here](https://github.com/n-ivkovic/tspreed/pull/6). Until upstream fixes Makefile, I hope using `vbin` and `vman` is acceptable.

**Comment by n-ivkovic** [comment]
Hi, I'm the developer of tspreed. I would first like to say I am very grateful for you creating a Void Linux package for tspreed.

Soon tspreed 1.2.2 will be released, assuming no additional fixes will need to be made. As of this release the new file ./default.rc will be copied to /etc/tspreed/tspreed.rc when tspreed is installed. This functionality is included in the makefile in the develop branch of tspreed, ready to be merged into master for the release.

I wish to request a change be made to the package template once 1.2.2 is released in order to perform the copying of the config file. I believe adding the following to `do_install()` will work as intended:
```
vconf default.rc tspreed/tspreed.rc
```
Please feel free to implement the intended functionality however you wish, you will be the maintainer after all.

If you wish to implement these changes and have this PR be merged only once 1.2.2 is released, please be prepared to wait possibly over a week before the release happens. I will be busy with commitments over the next few days so I may not be able to release the update in that time, however I can guarantee the update will be released within the next 1.5 weeks.

If you do not wish to wait for the release feel free to continue with the merge as you would have before and implement the change at a later date.

If you agree to implement this change, whether it be part of this PR or later on, I'm happy to list this package as the preferred installation method for Void Linux users under the installation section of the README.

Please feel free to ask for any clarification or provide any critique/feedback.

**Comment by kawaiiamber** [comment]
Wow, it's pretty awesome to hear from the creator of the software itself! I will be sure to keep an eye on the next release and the best way to implement the change. Thank you very much ~

**Comment by n-ivkovic** [comment]
I should notify that tspreed 1.2.2 has now been released

**Comment by kawaiiamber** [comment]
When trying `build_style=gnu-makefile` on v1.2.2, it reports that
```
=> ERROR: tspreed-1.2.2_1: PKGDESTDIR is empty and build_style != meta
=> ERROR: tspreed-1.2.2_1: cannot continue with installation!
```
It looks like `build_style` isn't successfully configuring the Makfile. I'll use the `do_install` function for now and play around and see if I can't get `build_style` to work.

**Comment by FollieHiyuki** [comment]
You just need to delete the redundant directories inside `masterdir/destdir` and the build will proceed fine

**Comment by kawaiiamber** [comment]
Okay, removed `do_install()` and added `build_style=gnu-makefile`

**Comment by kawaiiamber** [comment]
Checks still seem to fail with same error on both my end on the github checks even after `./xbps-src clean` and removing everything from `masterdir/destdir`, reverting to `do_install()`.

**Comment by n-ivkovic** [comment]
Hi @kawaiiamber, please note that default.rc will need to be installed as **/etc/tspreed/tspreed.rc**. The current use of `vconf` will not install default.rc to that destination.

According to the [docos](https://github.com/void-linux/void-packages/blob/master/Manual.md#global-functions), `vconf` will always copy the 1st argument into /etc/ (like how `vbin` copies the 1st argument into /usr/bin/), thus it appears currently default.rc will be installed as /etc/etc/tspreed.rc. I believe changing the use of `vconf` to the following will install default.rc in the correct destination:
```
vconf ${wrksrc}/default.rc tspreed/tspreed.rc
```
Please note that I am not a Void Linux user and do not have any xbps-based machine to test, so take my code changes with a grain of salt!

**Comment by kawaiiamber** [comment]
Ah, I see. Thanks for pointing it out. Updated to use `vconf ${wrksrc}/default.rc tspreed/tspreed.rc`

**Comment by paper42** [comment]
> When trying `build_style=gnu-makefile` on v1.2.2, it reports that
> 
> ```
> => ERROR: tspreed-1.2.2_1: PKGDESTDIR is empty and build_style != meta
> => ERROR: tspreed-1.2.2_1: cannot continue with installation!
> ```
> 
> It looks like `build_style` isn't successfully configuring the Makfile. I'll use the `do_install` function for now and play around and see if I can't get `build_style` to work.

The Makefile didn't respect `$DESTDIR`, so the package got installed to `/` instead of `/destdir`. I submitted a PR which should fix it: https://github.com/n-ivkovic/tspreed/pull/8

**Comment by kawaiiamber** [comment]
@paper42, wow! Thanks for the PR on upstream! I didn't know myself about those best practices about stuff like `$DESTDIR` for packages on distributions.

**Comment by kawaiiamber** [comment]
Removed redundant `${wrkwrc}` expansion. Keeping an eye out if the updated `Makefile` gets merged to upstream master branch.

**Comment by n-ivkovic** [comment]
The changes merged in https://github.com/n-ivkovic/tspreed/pull/8 have now been merged into master and the v1.2.2 tag + release have been moved to include these Makefile changes.

**Comment by paper42** [comment]
> ... and the v1.2.2 tag + release have been moved to include these Makefile changes.

Thanks, however moving a tag is generally not a good thing to do. Why? For example this PR is broken now. If you wanted to build it, it would fail, because the checksum changed. Also, you broke the AUR package where it's a bigger a problem, because users build the software manually there, so a checksum mismatch will (I think) jump at them them every time they try to install tspreed. If you want to add something new, just make a new release.

**Comment by kawaiiamber** [comment]
Removed `do_install()` and added `build_style=gnu-makefile`, as well as updated the checksum.

**Comment by n-ivkovic** [comment]
> ...moving a tag is generally not a good thing to do. Why? For example this PR was broken until kawaiiamber fixed it. If you wanted to build it, it would fail, because the checksum changed. Also, you broke the AUR package where it's a bigger a problem, because users build the software manually there, so a checksum mismatch will (I think) jump at them them every time they try to install tspreed

Apologies for this not-so-great approach. I was too focused on finding a quick and easy solution to including the updated Makefile without incrementing the version number (since there was no change to the actual script) and/or without breaking semantic versioning and did not think too far ahead about the consequences. I'll be sure to avoid moving tags unless absolutely necessary in future.

**Comment by kawaiiamber** [comment]
I was just reading through the void-packages manual and thought adding `conf_files` to the template would be appropriate given how `tspreed` now handles configuration.

**Comment by kawaiiamber** [comment]
I've extensively tested the tspreed template with `xbps-src` and `xbps-install` to install locally. It works great with no bugs.

**Comment by n-ivkovic** [comment]
Hi @kawaiiamber, tspreed has now been updated to v2.0.0. If you wish to update this PR it should be a simple version+revision and checksum update.

**Comment by kawaiiamber** [comment]
> Hi @kawaiiamber, tspreed has now been updated to v2.0.0. If you wish to update this PR it should be a simple version+revision and checksum update. Thank you!

Updated the template to 2.0.0

**Comment by kawaiiamber** [comment]
I guess strictly speaking, this new script isn't POSIX, but most shells should have one of the two functionalities needed (if not both) to make the script work.

**Comment by kawaiiamber** [comment]
Since tspreed is a shell script, it does not build. So I just had the `do_build` phase return true to skip it. Otherwise, the "default" rule for the upstream makefile warns to specify install or uninstall.

**Comment by ericonr** [comment]
While interesting, this application is just a shell script, which means it doesn't fit within our quality requirements for becoming a package.

Closing for now, sorry.

**Comment by kawaiiamber** [comment]
> While interesting, this application is just a shell script, which means it doesn't fit within our quality requirements for becoming a package.
> 
> Closing for now, sorry.

## Quality Requirements

> To be included in the Void repository, software must meet at least one of the following requirements. Exceptions to the list are possible, and might be accepted, but are extremely unlikely. If you believe you have an exception, start a PR and make an argument for why that particular piece of software, while not meeting any of the following requirements, is a good candidate for the Void packages system.

> System: The software should be installed system-wide, not per-user.

> Compiled: The software needs to be compiled before being used, even if it is software that is not needed by the whole system.

> Required: Another package either within the repository or pending inclusion requires the package.

> In particular, new themes are highly unlikely to be accepted. Simple shell scripts are unlikely to be accepted unless they provide considerable value to a broad user base. New fonts may be accepted if they provide value beyond aesthetics (e.g. they contain glyphs for a script missing in already packaged fonts).

tspreed is installed system wide, not just for the user. So one of the quality requirements *is* met. Furthermore:
> If you believe you have an exception, start a PR and make an argument for why that particular piece of software, while not meeting any of the following requirements, is a good candidate for the Void packages system.
> Simple shell scripts are unlikely to be accepted unless they provide considerable value to a broad user base.
I'd make an argument that this shell script "provide[s] considerable value to a broad user base." There are other packages that are just shell scripts.

I would argue this PR should be re-opened on the grounds that:
1. It meets at least one quality requirement as it is installed system-wide
2. The shell script "provide[s] considerable value to a broad user base."

@ericonr

**Comment by sgn** [comment]
> > System: The software should be installed system-wide, not per-user.
> tspreed is installed system wide, not just for the user. So one of the quality requirements _is_ met. Furthermore:

Well anything *could* be installed system-wide, but I don't think this package *should* be installed system wide.

> 2. The shell script "provide[s] considerable value to a broad user base."

I don't think this package has *broad user base*. It seems like only you interested in it. AUR has only 2 votes.

**Pull request closed without merging**
