### PR TITLE
tinyssh: update to 20210601.

### PR DESCRIPTION
**Pull request by ailiop-git**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
It had some commits here and there trying to enable cross compilation, can you try removing `nocross`?

@CMB ok?

**Comment by ailiop-git** [comment]
Tried removing `nocross`, but it doesn't compile on aarch64. I don't currently have time to look more into it/fixing this.

**Comment by CMB** [comment]
I got cross-compilation to work.  Just a bit and I'll push a branch
with my changes.  Should I file a PR for that, or what?

**Comment by CMB** [comment]
The tinyssh branch of CMB/void-packages has the patch to make
crossbuilding work.
https://github.com/CMB/void-packages/tree/tinyssh

**Comment by ericonr** [comment]
@CMB feel free to open a PR, I'd appreciate the CI run ;)

**Pull request closed without merging**
