### PR TITLE
ytop: remove package

### PR DESCRIPTION
**Pull request by hervyqa**
fix: https://github.com/void-linux/void-packages/issues/37240

#### Testing the changes
- I tested the changes in this PR: **NO**

### CODE REVIEW

**Comment by classabbyamp** [comment]
does it still build and run? If it still works, I don't see a reason to remove it at the moment, it's only two years past when the dev abandoned it.

**Comment by hervyqa** [comment]
@classabbyamp that's right, ytop is still working properly. but in the void there is already `btm` with a similar program. and both are built with cargo.

**Comment by paper42** [comment]
I also don't see a reason to remove it. It builds, works and a lot of people are probably still using it without knowing it's abandoned and that btm exists.

**Comment by paper42** [comment]
@hervyqa I just noticed ytop is not compiling anymore, upstream is dead and we are the only distribution that still packages it, let's reopen this PR.

**Review by paper42 — APPROVED** [review]

**Pull request merged**
