### PR TITLE
julia: update to 1.1.0

### PR DESCRIPTION
**Pull request by silvernode**

### CODE REVIEW

**Comment by maxice8** [comment]
Please add [ci skip] the end of all commits in this Pull Request.

This Pull request takes over 50 minutes to package per-job on
Travis CI and is automatically terminated with a failure.

**Comment by silvernode** [comment]
alright, I thought maybe I could change that on github but it looks like I gotta do it locally

**Comment by maxice8** [comment]
On Sun, Feb 10, 2019 at 05:21:27PM -0800, silvernode wrote:
> alright, I thought maybe I could change that on github but it looks like I gotta do it locally
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/8499#issuecomment-462200181

It needs to be in the commit

**Comment by silvernode** [comment]
I did an amend and force pushed just now

**Comment by silvernode** [comment]
For future reference, should I always add [ci skip] to the end of commits that are going to take a long time for Travis to process?

**Comment by maxice8** [comment]
On Sun, Feb 10, 2019 at 06:16:52PM -0800, silvernode wrote:
> For future reference, should I always add [ci skip] to the end of commits that are going to take a long time for Travis to process?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/8499#issuecomment-462204612

Over 50 minutes since that is the time limit, after it passes 50 minutes the job is killed.

**Comment by silvernode** [comment]
> On Sun, Feb 10, 2019 at 06:16:52PM -0800, silvernode wrote: For future reference, should I always add [ci skip] to the end of commits that are going to take a long time for Travis to process? -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#8499 (comment)](https://github.com/void-linux/void-packages/pull/8499#issuecomment-462204612)
> Over 50 minutes since that is the time limit, after it passes 50 minutes the job is killed.

I'll keep that in mind, hopefully my last commit has been written properly. This whole [ci-skip] thing is new to me since I haven't contributed in a long time.

**Comment by maxice8** [comment]
On Sun, Feb 10, 2019 at 06:21:19PM -0800, silvernode wrote:
> > On Sun, Feb 10, 2019 at 06:16:52PM -0800, silvernode wrote: For future reference, should I always add [ci skip] to the end of commits that are going to take a long time for Travis to process? -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#8499 (comment)](https://github.com/void-linux/void-packages/pull/8499#issuecomment-462204612)
> > Over 50 minutes since that is the time limit, after it passes 50 minutes the job is killed.
> 
> I'll keep that in mind, hopefully my last commit has been written properly. This whole [ci-skip] thing is new to me since I haven't contributed in a long time.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/8499#issuecomment-462205014

If you're using the github Browser UI you can see there is no yellow/green/red ball besides the name when scrolling through pull requests and there is no checks running at the end of the PR

**Comment by silvernode** [comment]
> On Sun, Feb 10, 2019 at 06:21:19PM -0800, silvernode wrote: > On Sun, Feb 10, 2019 at 06:16:52PM -0800, silvernode wrote: For future reference, should I always add [ci skip] to the end of commits that are going to take a long time for Travis to process? -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#8499 (comment)]([#8499 (comment)](https://github.com/void-linux/void-packages/pull/8499#issuecomment-462204612)) > Over 50 minutes since that is the time limit, after it passes 50 minutes the job is killed. I'll keep that in mind, hopefully my last commit has been written properly. This whole [ci-skip] thing is new to me since I haven't contributed in a long time. -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#8499 (comment)](https://github.com/void-linux/void-packages/pull/8499#issuecomment-462205014)
> If you're using the github Browser UI you can see there is no yellow/green/red ball besides the name when scrolling through pull requests and there is no checks running at the end of the PR

looks good then

**Comment by silvernode** [comment]
I have been using this package for 5 days locally without issues so it should be good to merge.

**Comment by maxice8** [comment]
I pushed it with a few changes, notably the usage of the new archs= instead of only_for_archs=, the commit is still credited to you

**Comment by silvernode** [comment]
> I pushed it with a few changes, notably the usage of the new archs= instead of only_for_archs=, the commit is still credited to you

Hey! Thanks! Cheers! :)

**Comment by non-Jedi** [comment]
Thanks for bumping the version on this. Been on my todo list for a bit.

**Comment by silvernode** [comment]
> Thanks for bumping the version on this. Been on my todo list for a bit.

No problem, thanks for maintaining it.

**Pull request closed without merging**
