### PR TITLE
New package: qimgv-0.7.

### PR DESCRIPTION
**Pull request by travankor**

### CODE REVIEW

**Comment by maxice8** [comment]
CMake Warning:
  Manually-specified variables were not used by the project:
    CMAKE_INSTALL_LIBDIR
    CMAKE_INSTALL_SBINDIR
    WITH_KDE_BLUR

**Comment by maxice8** [comment]
Patch needed for musl

```
diff --git a/core.cpp b/core.cpp
index 26821e3..231ec1a 100644
--- a/core.cpp
+++ b/core.cpp
@@ -16,7 +16,7 @@ Core::Core()
       scaler(nullptr),
       thumbnailer(nullptr)
 {
-#ifdef __linux__
+#ifdef __GLIBC__
     // default value of 128k causes memory fragmentation issues
     // finding this took 3 days of my life
     mallopt(M_MMAP_THRESHOLD, 64000);
```

**Comment by maxice8** [comment]
The template needs patch_args="-Np1" or the template needs to be adapted to not have the a/ b/ prefix.

**Comment by easymodo** [comment]
You should change version to 0.7.1 so that musl fix will be included

**Comment by travankor** [comment]
0.7.1 musl patch is already included in Void's build

**Pull request merged**
