### PR TITLE
linux6.2: update to 6.2.15

### PR DESCRIPTION
**Pull request by atk**
#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by dkwo** [comment]
is it possible to include this https://github.com/torvalds/linux/commit/c1592a89942e9678f7d9c8030efa777c0d57edab as patch?
or alternatively, as soon as 6.2.15 is out?

**Comment by dkwo** [comment]
cc mantainer @Johnnynator

**Comment by dkwo** [comment]
actually, 6.2.15 is out :)

**Comment by atk** [comment]
The netfilter patch is no longer neccessary, too, as 6.2.15 already received the changes.

**Comment by atk** [comment]
Same goes for the previous mt7921 wireless patch.

**Comment by atk** [comment]
lint job failed due to network issue; worked flawlessly locally.

**Comment by dkwo** [comment]
@leahneukirchen can this be merged? it fixes cve

**Pull request merged**
