### PR TITLE
[WIP] firefox: update to 79.0

### PR DESCRIPTION
**Pull request by jnbr**

### CODE REVIEW

**Comment by jnbr** [comment]
Builds for all targets but not tested yet.

**Comment by q66** [comment]
the endian patches need fixing in a way that affects litle endian as well, so please hold on until I have figured it out

**Comment by q66** [comment]
meanwhile, tested and working on ppc64le, the big endian VM is still busy building other packages first

**Comment by q66** [comment]
squash this into your update https://gist.github.com/q66/596078427ba7f11aef34b6302d42b918

it doesn't fix things completely, and a bunch of the stuff are ugly hacks, but at least it no longer affects LE, and looks less broken than before... (it's largely usable now, if one can deal with some random things becoming blue...)

**Comment by q66** [comment]
here's a `firefox-i18n` patch

```
From f461d3f50ead70918db5a37050e9b4bd1e790207 Mon Sep 17 00:00:00 2001
From: q66 <daniel@octaforge.org>
Date: Sat, 1 Aug 2020 18:36:54 +0200
Subject: [PATCH] firefox-i18n: update to 79.0

---
 srcpkgs/firefox-i18n/template | 194 +++++++++++++++++-----------------
 1 file changed, 97 insertions(+), 97 deletions(-)

diff --git a/srcpkgs/firefox-i18n/template b/srcpkgs/firefox-i18n/template
index f549123e50..a148c2a7e1 100644
--- a/srcpkgs/firefox-i18n/template
+++ b/srcpkgs/firefox-i18n/template
@@ -1,6 +1,6 @@
 # Template file for 'firefox-i18n'
 pkgname=firefox-i18n
-version=78.0.1
+version=79.0
 revision=1
 build_style=meta
 short_desc="Firefox language packs"
@@ -140,99 +140,99 @@ _pkgtmpl() {
 	}
 }
 
-checksum="90521f2667cde54440a61d155677169b7bdc09f440383b0258096952131b4f62
- 0af04db105a7cdadf8f6fc39d454c3a15de5d7a2ee5117cd29a059c60c604d15
- 47b417f44ce952a1fd451e16bc31cf6c7045a6dff93f37780c935c7537c26119
- 97734b492dc7b7a3a4bc9780e5bc353afbfe0499b01c7682dba09e454156ac0c
- 38428fcc196f2ff890fae6e54dc18272f6402dc66c85002e73c24ccc28875beb
- 234b3981dfe399ffd2726c2584300ca8f83458f63897c61e8ac244043d1fb1cf
- 76f8272f129a6daf7c90ac25a346186974b5fa9afbcb694842d073951fa54552
- bd8b2d2a607954de2d3bab4b94417f81f9e5852ecd1a2312f53e4d4be8159fbd
- ebbf458a3ce8d356f344bd4e3a535679b3c0b89b125d63304bb44983fc27e9b6
- 08ce3b3ca2fd263ed719afc32be5a563c84a3e7bbc445870b46048781a7da919
- 41fb7385a65b51a6d73fdc3225f781f36d403620323ffdc6430808a1c4ff4eaa
- 07d438f10f3e39ecb414aab86009469a30415034a5116c9e5e809618d5a281c6
- 781ab7889dcab32c3df9b4eaa9fa2b6cb39c5361341a212cae304cf26a494296
- 4c534a68fb342eb666298e158cc20711fd92e9c9e4430693c46977a596086bd7
- 1bb2872cf1a7e879608ce8f50432b978835054d189317d5a6ff82ef5bb4c8181
- 28c2f16e0c377aaf1d298eb63ce81777107be1673295e3f59539ebec235fe5c8
- fc97cd0744e04af274b32d4d97afe01b96f4c35735461b740eba2abffe597d72
- 5e507acfd977dfe2d325db0ec7bdc961c00a08b66e89e8a88168d9a2d5024874
- a0122cc935a022be804688a1d551a98d05d8ce1f6ce5e10d8e3dd0c7adab45ef
- cd966b155cfb0b6f8f1b0ead85ca3469fee13dfa668c22f331fc8f92b12d02c6
- 366dff0773dde7ec8766994f6e7590b62fcfd93e6d1617db9edb1e9a781434d8
- c31fe1e438be42d0ea827164469256bb59e75e129840712acbe4ebb49c39a8fb
- 7bb78e8eb556454b605e949066527b5fadc1ad38c546f59f67a055f7bbcbcd3c
- 65c90e8ecc5237c0c9e288b759364fe6db5286550c4e1870e2e71f1b6a0cab32
- 87bbabd0500a97c0f57c6bb55b331fe1fcb0e6a445bfc89ff4a721146762b913
- 9245bec16f2c3c5d0e2cd4dcfde62b421098d06d3bc5044a290493f4dbeabc5f
- c86ea0f3890e59271adb420f9ca56d4072f5925f611714ecad104c62f637f041
- e7b113762b3fa60d219a8f22f2bbbc1743165261f36654f609222489c07e2ae3
- bdba4774c873744e53646087e72abcf35d1d8c84a51060c4477a23648fadbd3e
- 37b93f0fd21e1006a0b21ab725d9d050683945843ffc2348529bc1b492caffa2
- 6a8bda1b568333fe145b7a3ba290613c6ceb687aa589f697a6bd947c423642a3
- 7543e8d4ed7f944992382f3341a19e6bdad88ba55179445b587c36aa90462891
- a5e3ab6da8a414deb65766dda9362fb61657ec257c141728fe23d778ef58f92d
- 70d63163bb1331726e057d17cfdd97c661944f8ba81cb6a745adbe46dbe52bde
- c291cc8e20e3b66449ac68aa0f92c6d800a4cf2f837f9ac6b820cf77cb3f1397
- e5f25cd79c0ec35cffa3d6f092c2d1c92c6ef3807e90451959ffe2f4ccca7e22
- e39706a18fd58e400169aee275bb7e08e48067141191caf6cf7c08c34e161124
- 44cf48809085d963a9af740fcf0dfe291ea38a742869bd85c89637937414bb04
- 41fbc3a295e654590e0f1348ba103437eb2ba22ef18d8d9d24c5e4ccc43c9a74
- 8c596ca3df70350f89555012d0a73408616cee9f1eead7f5f413e0cd0152a98e
- 64546d9c4e649a6c7f8da845ae4e5bc5b8e415ceab3cf7b40f3588d6d8f8f933
- 16b414f06b50277fe7690d7a086a010ed665f55fad2727d22a91a9797d181943
- e8f8e3ea5fd7040e34e9320b4164fb543b8d7706ab87e0d9d43dd032526c4e81
- 0cf2a8d1f41a33b10b54ab87f35429e7a5ceb3a15110fa573b4707962e4f479f
- 762dd9d36e30b7449438d7daa342e026bef9fe5a01ae605204efc4946ba9e820
- f5f42b5764a8770e4da00f81a168bf86f8f30f3e29d71405c4bc9380cfee4ff4
- 2f25e294bed19d34a765431a386370056f5c8144c15ad4b817438c588cc5163d
- b720ebb5c53b299bea2872b50a4eed47327eaf8bd85fd900bdd2456781812c90
- fa39cf5f751cdd932610e3c81198647fc97e171b79c6f877b37d5fb639ea4e90
- f1916f059faefe1ca5d476e9ebb069fa8e69f30e1943fb88dff85c5d35b64aef
- a383d9fee42902815231e40b99bcad096dc0d45b5779449e3dc2de4f4bd26b93
- d552de68cf1f7b7ff3c066a37430d3422b672f51a4e52214592252f2c1359c8d
- 459689f3c5b53e337a15817617aa42722b5db7f09f7453a8dd02f13c01e492a2
- 1c70fb25038be21a055be1dcb690f7a23dc7436ef30f321b4520d43af9038921
- af653f080237b0a91a74c1f465acebe1851de7e890d46c6c3d8e6286fed7c11f
- c7beb3e3f98c18c0962cef4739edf370d99af2ee2fa89c2fd9bb1dc00b1ffd9c
- fa0ce6eb7b914d643b162aec4282049fe76d5f0eb6824b869be475cafbbbbcff
- 62a2fae53deeb417d33c94d144aab6f7d311510560b79a09b3a8940e3346bb1f
- 98a34320bad6e29fba9525362475eda9fdb13c33f79bb02b2a647cac0990112a
- b31a76aead78a10d251abbc23159ce65897b8af39d81a2d6237d9fce06244fc6
- 3877d7b633fb9aee4ad516a59abdca72ec3765ace81e0c014c9c6ba79ea7dcd6
- 68a6c43de1a4e63af63d9e4229e692d8e64b629ff018f9334911e9b0b37b586f
- 3a203b996140959d602e45a5347cab753d952df96fa4455330e9d21ced2aba46
- 3b1bdff5225dafb00826f1c45940fd84d354c9c8beb089d6653a9fd7a9d0e281
- f11e08ba479c81f3b09187a03d3f516527ede4201f931d59a95585b2c96a931d
- 02d53acbe28195551bd5a3690dc2ae151067f8ab6e8460e1bbfba7e7509c6f0d
- 393ae386d8e180623a1830e78a0bd4484f9054e8c6acbe8dd88a029eb8c48e2f
- c268f48d94cc249bfebe04e465656414dfffbaa5142447468d4f50a72df7e79a
- dd5899d331f51a7664d34730e4b5c7170fdc41a0959003d1b1bca3958156a01a
- a5819538f273b8d607dd3b15b22cdd776e0ce060bf1c903f93bf13197677f14f
- 3fb5aa0ae6a64beeb7c904a22a2261b1f024dce633f83f8c96f1667711ecb2fa
- 7ed9c83bf704980cd7b6f512d3147c1cf6ab55634701ac1cc844b61dabb9106e
- 638f250f425d968abcdb05fc06a2aed4a7f31fa4b8b9a863c43e46def03a88b7
- a953a778d8143a7524fec7f74798ed76537057e1e26f213a45c8e50f0cb991e7
- accbd49f05c83c670d78d8c31aa443af49763fea18dc56060e5ac560804bdeb1
- 8d9eb5f46a7273ba2434a6c841aaf62cda141c605be458f06e4bbee172c01082
- 71fcb289a444c393ead1449c92bbb70c282547fa32fe5bf3ceea3293d79aed1d
- 9974b184071d47df1cd3ca023b34b95a8f43974e166fef5bec3af9e9345032b0
- e4a41f7ebdedd2ea800ead2cb267c3e41f9f4a4c51f85ecafd53773c1dcdb0d0
- 29e45e23e11f07bcb09458c5da6f622ac076a8f6fa43eb56cc48e7cf722cbbf7
- 8c5991ec848ffa6f0b15a413ff74d913453464750888fd6ce559664eeb8203e2
- e7b074ed21f0f51bedb0759d96e2a301bda8f5c1e90d97bd78c208c0f1a51400
- c82d9a06fc6cd9def0b8bd28a8ba364275fc2f2593b3780a27499ba534e530db
- e6e492ab26ac9aae61faa57a98d1cdaca1af0d4782f77badd83a0bc327892b45
- 9c13e510d1404ca73b8445cac9290ee59e24ebb8c766974dfe11bf1f9cdd181e
- 24db16fcaec936cc312a9edb3c94ef5b9f55b2f06ef570d49296a0100045e52c
- 47034124aa0ac099a8aaf9f604da30ffdeaf133cf756150b7f5a71b1ccdbd6bd
- a0bcd7a835e0f1d13af3e0105f85ecd4b84e5c23159cb20b5178580235372dca
- 9c51bc7b4fdba58a5d329c455c96f2085d29f3873bf1fa5cd9de00b6ce589829
- 3f3148ba8a0aa6655cd68378f3727ea10b0d79bff84e89cd7156aad01723cc90
- 7678da76a31b55c4de34a1bb20444c4688f4555d356862e5078faa882e53cae9
- 2cb5fdb8812cddda1126928cad5b0b24b41fba347dc5d5f604c6579625386ccf
- 4cf0b2b8b61c4db730782686b082b3429745c5b1a60c4b4dd91f73ed839556b5
- e60de056209652559dc2c8508d2d68ae088ddebdd9eff9d9af8ebe4021cdab0c
- 90e758744e322ed8ae84fd84f313f34b321405caf641491ea3f37b7ca33907e0
- a3bf8b37fd9c4e3737aaeae0a148ae10bb1d5169eec7516f3b98e832af482f47"
+checksum="911ef827eaeab995e7270eeb28033fbc3ce402598ddf955014594d817d1c978f
+ 983b2eb7a8517afce57640680ee67560280fa45b49770b0c8d467206fbd8086d
+ 14614238df913b5ece0f97b61b4ee6752bce82522b34b39d6509821317665551
+ fd54d2d70afdb46c1c3d2ee98031f838c7b47794180ce382fc5e370689d8ef90
+ 3b6eb29eb88a36d5c9fb9b3c967a3d8861373d0b0d3f420b2286512941e0d019
+ 12e392c234918b9a55c54992dead682ce3f2a2222b8b000a06c8defbb1a8bb53
+ 1e4f7f853844c8574c04d181bf8e17c488c853f59359c09d5c6bc8055ef77069
+ 38628429290e0ed59a8f9f22cca9d104b301ba58d1e6ea03436fccab55b3b760
+ 30172930a46c697a8ab27dad7e69bcdcfe32f12f59d5078985dcef804ee587d4
+ b544eef867394c9bad066c8fc3181431c84c41d8dbb215145038f072197087f6
+ 5fd5902bf3ee95329fe92464a5245f309c37bf312d68f4b4b5e6c816cacdb946
+ c4ef2584152de8f07dcaba18d5299e8efbe7111ea630ef398afc348815ba68c5
+ 313e4e6a253930272c2e89dc5d55b19521d688640acc5eb40bf1e52f8976545a
+ 6f7b3e3f46218074eccba60f0155e4aa147f60b5e8dd15a9dfa779d4cef998f5
+ 02c3ce4c3d2aa978b48efdf4ab8f85e0c5016498c6399cc9bf47d1912b8709fc
+ c7f2fb867ce1963b9036862c4667bd079af2eab12b41beb2484f74834e84f08a
+ 72a931ff0a04675341041f1be2151c916720eb0488707cbe9fc1d7b0bbab8833
+ 3d47ee3cb1eee421d9dffada7a0f82dd487aa8576344010a096945390a270599
+ b983eb8987595c20228fd2a528f06dbd7c3600774387de7f9ee74994ecb265dd
+ a158c2ca320dd9bc63603cf26fede3596833a389983796f8ba6c8b65cbb0f003
+ d3036a9428be3c10756c9ac0c74b4e74d425913fd531ca053d58b33ef0e716cf
+ c5f38ad6a9a40b5946721f957e3252686c6bb9201755ac8b8d8c5d4ad44edfdb
+ e984841a7f5c9e26f5792dd7a621ee59bae8c42b9d616da77bf4430367dfb3d8
+ 9fd81a161083c4cf84d63f955a82ab64bdf7972f88b62a23b3ab52d2c8ef000d
+ af5e43b5e8a4072c073a1ca24f2a2f99656a26de1bd95eb68ac33c30edcb385e
+ 8d8ed077e50860356bbe30058ca2d87b6a398fc930025a34215b002ddc085046
+ a51da8b740522c4291581a1fdb94d976be8ec7be795069364fb329344df72aa0
+ eff776467a86a766b18d27f31ab0aac768e5a6f28420d73409c00b769ad1d460
+ 922ae040938bb0aac1c534e7bc8bd8165079204d98fd8e7b956f5a98502300e6
+ 24fc12e12b3e5c1cbfd55c5fb350c676607edbdfbafb41375b4be9929f6bdb9d
+ da53c7afd9b6f128f9b4b8a23af0a03459518ccbe668cf39711ff83482dafdae
+ 607c5570406365e44e38eb6d07047742f978717ebc381f32c813f6f0c123792e
+ 9d34a7d049fcd24038d25c993852a42fbd63a8023bca93e812b6fb88afa5e303
+ 8de7623c5f56764f3f2ee0b3271d2d3d877b5a5698b7a2199bf0721c35260219
+ 1c406fdddb13520e76888c74b95252e70d5827ce0f763c45104434bed654a34c
+ cdc6885ad11f2b4eebcdb050d7a6d30c933e7117a1783d277ab194496300e33f
+ edf5baa7426f19e266278553f513f8ffc521a7ce9ed5f50786203ca535cc59db
+ c78e49f49ba95d0ba7e97422d26c65474a6e21f66c8487b3ca415f6ff331b7b9
+ 16cba73411c97f0a218ff3408122d8137e44370695e499b2e39677bdeaf14844
+ 49bcd136fa6683ea110f5a1a06970bf3fdc76c27be4cc5b2e9ec5c296c167c14
+ f646ef3b54675dbe2d30c49983b3ecb7f2954485840b0d1bc7c4a0602d0aa3a9
+ 12ac52e8ea3a98812e0b0905b9273addd8d2377c86fa8245e5fb71c1c4fc2430
+ 0b759120041362b66a17b28b93ad50d983d849f1db997932877c35ac6cb5b68d
+ 0c07d678683d8f46dbe9cac11d90d3b4325bdc9b1c4ef7ed097f30086173b340
+ 3b7e4911bd52e3828a12acb026bc9d8c7246deb25a800e1ac9e137751f1c0e9d
+ 7d85bc754f6f7162f99074b27b2d362b4219dee77d4b284d7e2a08b6f3f6bba6
+ 1b0380fb6ed06998c35b711f80f88df004fd3b59f70f479421d0d404fc64aac9
+ ef2c8e2c12de18c00b319e980a6a7ddc2b85d9a752022eacbd7884771531fe03
+ 39bb628ccd04432e53b3a208cebc5afb758d07235f4ef09fc2edb94fafb9f7c2
+ ef05a3f38dbf89279d68cf9980e006e72bad9eb5bdc72ba84fce43dca01ed00e
+ c403c5c77657003605a600203c7d2f8600f28552f718fe054992f2a8683cf949
+ f0303d8437242ac039046cd8881d1112006c2a00221ae18a0eda41574a067003
+ 09f3ba18cf4f8a0192dcedd8f88ab25c8ea6b6d03f6421708051566d16044c0d
+ 8856408fcb3ba244bd8ba233864f4acd647e7027f3520fbc6ea6b75a4d8401ed
+ f8580345607aa9ea607d0b1b31347a056551229d272d273e04ecb39e4d151f27
+ dc6d54eac9ab6b210ae9538c8ac775e25e6bb7126b33379fc640f981a1f3991b
+ 665b0501b441a7f6bdba3da65af1be7d702d02c20347d53fb792a405a7030afe
+ 5ce07f2a5d4bd50d40d76521237428332c4c0245c4f323278ee0b7b01bf38dbc
+ 8de0de7cd2906f5763dada07994925ec9ecae8aefde7bd3510f3660e901666e6
+ 8cf69191d042e9ec3526d10fd880a99b37047900ec65b95efa5b11c5bf1d947d
+ 626a3ad4f9299243a359aeca86ccd9cc4544204f954f285df0adf358e522e046
+ b7756b7879d9a470bf0b35dba534331276e789e65a22ea1811196e63667f3896
+ 050d26f61ca79df60f94bedd1cc4498bf10f5a5a8164b3fb4a63e322ed6f6362
+ 5c0a09d7e79b96b858b60929f3dbed6a162a7c044fdce3ff57a098874af69eac
+ 761b1658dc876ee8c3c7da1c3f0d04625beeeac830dde44eaa0a5c21eab24164
+ 14ce371b6719ce2964192b1c5e3b2caf91600f55c3dfb7a254cbc8c0fbc260d5
+ 334aa328efc3c06906f69932aca2d3e5c32c099176dc1dee8a553830d2943326
+ d5df1afbca5db07ad0409d45a53185c7aa834ddac1f6710179811738984e6d7c
+ ae3cb5660aab88e51d37b57afdb7091ca48c7668cbd1a3fec54ca9060644ab3c
+ 9665152c43e712541687d45d8d5eb4a92dc4270c54dd8a3777f7edcfe4065a31
+ 480990e66dd7fc88cad381e66a39ea6c2ed474a460c869e322a51e45ea7ed4bd
+ 80b59e34c837f0685c65cb7bbc804f8e66c942be4f1bf7f2529af2adf347fd3e
+ ac0d61da046ca60e82e19537a88fc80a8e6cb9f41d8a9a13836f5be584d6eb20
+ 0e41681ae400eb512b51b42273370f8b757be79a0f97f81e04e0ae5623e9adfa
+ d5777d4382b482edb0059a62daef6b042cdb53abdd0e879b31fb46ac45f7671d
+ 63714549e9b8e74c55035d383f4e1e0303d9e49d8f422f7bc92cae30ce227322
+ 5ab137a12dc017e9bfab7666e928c6883caa0ce4b081d617dec9163d2a52700e
+ 3ab8e897ef31fbd4a94215b4bf8319b5b9322dd28209428424889b829269eb93
+ 3ca90a08b917edfb9cc7439e397641e8ef256e3693e0a86061e3ce2b42cd6f87
+ 96d049d031228e18a4bb3a515723b58f353dfe1ab0a61fd015cb1f285d289856
+ 09283c9bb05a84583488febbd7fbe3e8afeb0e9e56294099b0dad70424b16a78
+ 62eed45412ede9a0e4c1ed9a229489acb5c515dc0258137dd7340515e9e708ce
+ 339006144703992314f22081add5fcc30865059a36544ba40d3abfbb3a327a76
+ 8fbb77dad5b47f4e3e4f0811b6cac47a7c58c06d7dcfcab0a6589d1527a79f06
+ 0f2bd8d15e6ef273798c0107f3d24103f979b2e029fd0ca112ec92a98f6d6932
+ f082f6971a5e63e648315050197500f5201214f26d16b9a18d320407f2d6119c
+ 64d2b552712b7a42813cebfbb9f547f38850eca9ce35eda1cd8e3297534380cd
+ caf71fc4f1384f67c1e6eac9e086ae33f2b74124754de2742151e0d27ace7346
+ d0bb54c9e9a53c8f03b8e24ea1a1a8ba5e2a2195afb65ff6807fd2ab505b820d
+ a6a74a18c9b36bfcd8666f5b15694ce2411ddd6f9d1e6201abdfaf218214d4e8
+ e5224e49e367be23dd015fe0b827320e31bb93d32451741eb586c9826b143024
+ 4e5df2a926385f4dcd4575859fa3e84f480a539d71f060108f24651f479be775
+ dd36b49c232610bb722eea4491e418d4d1c4f3bad4060a34dd4c438b21f94f9c
+ f62d9bcb95b42f6666ebe5aa06bfa0124b99c91501675c27da96ddd899f39211
+ c9661940a2214310fad28e2400290d7226691546b613e55d4d01d5af4018e15a
+ 417c81b953dbea9bcb3fd8d600dd055d210df4f1298a961c98f3ab95df3cb830"
-- 
2.27.0
```

**Comment by jnbr** [comment]
merged

**Pull request closed without merging**
