### PR TITLE
mobile-broadband-provider-info: update to 20201225.

### PR DESCRIPTION
**Pull request by ulfw2020**
adopt

### CODE REVIEW

**Comment by ericonr** [comment]
You left the rooster commit here.

**Comment by ericonr** [comment]
That's the wrong thing to do. You should rebase the branch interactively and drop the commits that aren't related to the package being updated.

**Comment by ulfw2020** [comment]
> That's the wrong thing to do. You should rebase the branch interactively and drop the commits that aren't related to the package being updated.

How can I do that? I'm reading up on it but I'm confused. Any help is much appreciated.

**Comment by Piraty** [comment]
https://github.com/void-linux/void-packages/blob/master/Manual.md#contributing-via-git

**Comment by ulfw2020** [comment]
> https://github.com/void-linux/void-packages/blob/master/Manual.md#contributing-via-git

I've force pushed a new commit with the right file, but the old commit with the rooster template is still there. So going to 'Files changed' and clicking delete file under rooster is the wrong way? What is the correct way to do it? Thanks.

**Pull request closed without merging**
