### PR TITLE
skarnet stuff: update and drop noarch.

### PR DESCRIPTION
**Pull request by ericonr**

### CODE REVIEW

**Comment by ericonr** [comment]
Tarball for at least `s6-portable-utils` has changed, I'm reaching out to upstream about it.

**Comment by ericonr** [comment]
We will probably get a few new releases soon, so imma wait for that instead.

**Comment by ericonr** [comment]
interested parties: @mobinmob @Duncaen @bougyman @lemmi (?)

**Comment by ericonr** [comment]
Fixes #25346

**Comment by mobinmob** [comment]
LGTM. I use the skarnet stack mainly through 66, boot-66serv and 66 frontend files. 66 is not affected with the upgrade (links relevant libs statically)  and AFAICT none of the others do. Thank you  for doing the work for the update.

**Pull request merged**
