### PR TITLE
mumble: update to 1.3.0rc2.

### PR DESCRIPTION
**Pull request by singul0**
I transferred maintainership to myself as it is orphaned

### CODE REVIEW

**Comment by Johnnynator** [comment]
We don't package releases candidates, pls wait for the actual 1.3.0 release.

**Comment by singul0** [comment]
> We don't package releases candidates
OK. It should be stated in CONTRIBUTING.md or somewhere over documentation, isn't it?

**Comment by Johnnynator** [comment]
> Please note that we do not accept any packages containing non-release versions such as specific git- or svn-revisions anymore.

In Contributing.md, and a "release candidate" is a "non-release" version. Furthermore it is normally expected by upstream the the latest stable version is in the repo of a distro.

We have exceptions here and there for various reasons, but mumble currently works as is and judging by their issue tracker the final release should be soon :tm:

**Comment by singul0** [comment]
On hold until 1.3.0 release

**Pull request closed without merging**
