### PR TITLE
subuser: added the required package "python3-setuptools" as a runtime…

### PR DESCRIPTION
**Pull request by VoidNoire**
… dependency

### CODE REVIEW

**Comment by cr6git** [comment]
Hey you already opened [#343](https://github.com/void-linux/void-packages/pull/343)

**Comment by VoidNoire** [comment]
Shall i close #343 then?

**Comment by cr6git** [comment]
No, just use `git commit --amend` for your previous PR, and close this one.

**Comment by VoidNoire** [comment]
Ok i'll do it when i get back on my pc

**Comment by VoidNoire** [comment]
I followed https://help.github.com/articles/checking-out-pull-requests-locally/ to fetch the #343 pull request, made the corrections to the `template` file, then did `git commit --amend`, and then tried to do `git push --set-upstream origin branch_1` (branch_1 is the branch name i used when checking out earlier). This fails with:

``` 
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
Username for 'https://github.com': VoidNoire
remote: Permission to void-linux/void-packages.git denied to VoidNoire.
```

Sorry about all this. I don't know how to use git all that well. What should I really be doing?

**Pull request merged**
