### PR TITLE
astroid: build with guri and webkit2gtk-4.1

### PR DESCRIPTION
**Pull request by oreo639**
#### Testing the changes
- I tested the changes in this PR: **briefly**

@bitmeise Can you test this and verify if it works for you?

### CODE REVIEW

**Comment by bitmeise** [comment]
I can confirm that this patch works me (smoke tested). Are there any visible changes I should look out for?
Where is this patch coming from?

Also, you should bump the revision.

**Comment by oreo639** [comment]
> Are there any visible changes I should look out for?

The only real change is that the URI parsing for `astroid --mailto`, to use Glib instead of libsoup-2.0.

> Where is this patch coming from?

I wrote it, I'm planning to submit it upstream.

**Comment by bitmeise** [comment]
I'm just curious: Is this about getting rid of old dependencies in the ecosystem from a Void perspective?
As a small contributor I'm definitely fine with the changes. I generally think though that changes should be integrated upstream as often as possible. We could wait for them to do so.

Well, in that case, you are the Void member :)

**Comment by oreo639** [comment]
> Is this about getting rid of old dependencies in the ecosystem from a Void perspective?

webkit2gtk is a massive dependency and having to compile it 3 times is not ideal. Many distros have already stopped shipping it and the changes in this case are relatively simple.

> I generally think though that changes should be integrated upstream as often as possible.

Of course, that is why I submitted a PR upstream.

**Comment by oreo639** [comment]
bump

**Pull request merged**
