### PR TITLE
Linux 5.3: Enable CONFIG_SND_HDA_PATCH_LOADER=y

### PR DESCRIPTION
**Pull request by kchuangk**
This allows hdajackretask from alsa-tools to set firmware code on boot.

### CODE REVIEW

**Comment by xtraeme** [comment]
Looks OK, but please update the other archs as well

Merci

**Comment by kchuangk** [comment]
Updated rest of the architectures.

**Comment by xtraeme** [comment]
Did you run `xbps-src configure` for all archs? No interactivity, remember

**Comment by kchuangk** [comment]
Sorry, happy to squash them all and do a xbps-src configure for all archs. But not sure what the proper way to enable these options are as I've just hand edited the and compile before. Happy to do it if you let me know how you want them done.

**Comment by q66** [comment]
When you update configs, don't alter them by hand, but rather take the kernel source, put the dotconfig in it as `.config`, then run `make oldconfig`, then enable the option via `make menuconfig`. This will make sure to correctly take care of dependencies, if there are any.

You should only have to do this for one architecture in this case, for the others you can just take the diff between the old and new config, and apply the same diff to the other files.

**Comment by q66** [comment]
Also, I'm not sure if there's point in applying this on `linux5.3` considering the current version is the EOL release and will be removed in near future. It'd probably be best to update it on `linux5.4`, and perhaps the older LTS releases.

**Comment by kchuangk** [comment]
So, I applied this to the 5.4 branch. When I tried patching the diff files for all architectures other than x86_64 it all failed so I didn't do anything to the other dotconfigs. Let me know if you still want me to commit and request a pull for this.

**Comment by q66** [comment]
what's the resulting diff?

**Comment by kchuangk** [comment]
Here's the unified patch file.

```
--- x86_64-dotconfig	2019-12-21 14:43:52.617503360 -0500
+++ config.new	2019-12-21 15:02:07.079458479 -0500
@@ -1,6 +1,6 @@
 #
 # Automatically generated file; DO NOT EDIT.
-# Linux/x86_64 5.4.3 Kernel Configuration
+# Linux/x86 5.4.5 Kernel Configuration
 #
 
 #
@@ -818,17 +818,8 @@
 CONFIG_ARCH_HAS_GCOV_PROFILE_ALL=y
 # end of GCOV-based kernel profiling
 
-CONFIG_PLUGIN_HOSTCC="g++"
+CONFIG_PLUGIN_HOSTCC=""
 CONFIG_HAVE_GCC_PLUGINS=y
-CONFIG_GCC_PLUGINS=y
-
-#
-# GCC plugins
-#
-# CONFIG_GCC_PLUGIN_CYC_COMPLEXITY is not set
-# CONFIG_GCC_PLUGIN_LATENT_ENTROPY is not set
-# CONFIG_GCC_PLUGIN_RANDSTRUCT is not set
-# end of GCC plugins
 # end of General architecture-dependent options
 
 CONFIG_RT_MUTEXES=y
@@ -6106,7 +6097,7 @@
 CONFIG_SND_HDA_RECONFIG=y
 CONFIG_SND_HDA_INPUT_BEEP=y
 CONFIG_SND_HDA_INPUT_BEEP_MODE=1
-# CONFIG_SND_HDA_PATCH_LOADER is not set
+CONFIG_SND_HDA_PATCH_LOADER=y
 CONFIG_SND_HDA_CODEC_REALTEK=m
 CONFIG_SND_HDA_CODEC_ANALOG=m
 CONFIG_SND_HDA_CODEC_SIGMATEL=m
@@ -8989,10 +8980,6 @@
 # Memory initialization
 #
 CONFIG_INIT_STACK_NONE=y
-# CONFIG_GCC_PLUGIN_STRUCTLEAK_USER is not set
-# CONFIG_GCC_PLUGIN_STRUCTLEAK_BYREF is not set
-# CONFIG_GCC_PLUGIN_STRUCTLEAK_BYREF_ALL is not set
-# CONFIG_GCC_PLUGIN_STACKLEAK is not set
 # CONFIG_INIT_ON_ALLOC_DEFAULT_ON is not set
 # CONFIG_INIT_ON_FREE_DEFAULT_ON is not set
 # end of Memory initialization
```

**Comment by q66** [comment]
Okay. You can ditch the whole part about gcc plugins, so it seems only that one line changed. You should apply this to 5.4 configs (all architectures), probably not worth doing for 5.3, as it's EOL and won't get rebuilt anymore.

**Comment by xtraeme** [comment]
what @q66 said. EOL

**Pull request closed without merging**
