### PR TITLE
firejail: add patch to fix firefox under firejail

### PR DESCRIPTION
**Pull request by PaperMountainStudio**
Close: #20226

### CODE REVIEW

**Comment by PaperMountainStudio** [comment]
ping maintainer @Duncaen

**Comment by ericonr** [comment]
Is this fixed by #23916 ? If not, could it be rolled up into it?

@jnbr ?

**Comment by PaperMountainStudio** [comment]
New Firefox version will not solve this. Firefox started using a file which was blacklisted by firejail, so when Firefox was started under firejail, it didn't find this file and crashed. Unless Firefox stopped using the file (probably not), we still need this patch until firejail releases a new version.

**Comment by ericonr** [comment]
Oh, the patch is only in firejail! Sorry. Then yeah, this PR should stay by itself.

**Pull request merged**
