### PR TITLE
thunderbird: update to 102.6.1.

### PR DESCRIPTION
**Pull request by crtxcr**
#### Testing the changes
- I tested the changes in this PR: **yes**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc
- I built this PR locally for these architectures (if supported. mark crossbuilds):
     * armv7l

[ci skip]

### CODE REVIEW

**Comment by crtxcr** [comment]
Ping @ericonr

**Comment by crtxcr** [comment]
Also built for armv7l

**Comment by ahesford** [comment]
Don't ping arbitrary maintainers to try to get attention. It's rude and generally ineffective. Ping the person listed as the package maintainer unless you have a question specifically for another individual.

**Comment by ahesford** [comment]
My apologies; I saw the `-i18n` maintainer and overlooked that ericonr is the listed maintainer for the primary Thunderbird package. Please disregard my other comment.

**Comment by lane-brain** [comment]
as a thunderbird user, thank you very much! I'll be testing this PR until it's merged

**Comment by crtxcr** [comment]
102.6.1 was released yesterday. I'll force-push later today or tomorrow once the armv7l for this version finishes

**Comment by crtxcr** [comment]
102.6.1 pushed. I've build and tested it for x86_64-glibc, built for armv7l

**Pull request merged**
