### PR TITLE
roswell: update to 21.10.14.111.

### PR DESCRIPTION
**Pull request by LiamHowley**
#### Testing the changes
- I tested the changes in this PR: **YES**|**briefly**|**NO**

### CODE REVIEW

**Comment by LiamHowley** [comment]
Apologies. Should have tested with -Q as stated in the manual. I've opened an issue at the Roswell repository.

**Comment by ericonr** [comment]
The commit message doesn't have to list that libcurl was added to hostmakedepends.

What you could do in the commit body is explain what it needs specifically `libcurl` for.

**Comment by ericonr** [comment]
```
 cc "-D ROSWELL_TSV_TEST" -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -fdebug-prefix-map=/builddir/roswell-21.10.14.111=.  -Wl,-z,relro -Wl,-z,now -Wl,--as-needed     -o tsv_sbcl tsv_sbcl-tsv-sbcl-bin.o tsv_sbcl-main.o tsv_sbcl-opt.o tsv_sbcl-util.o tsv_sbcl-util_windows.o tsv_sbcl-util-list.o tsv_sbcl-util-string.o tsv_sbcl-util-dir.o tsv_sbcl-util-dir_windows.o tsv_sbcl-util-file.o tsv_sbcl-util-file_windows.o tsv_sbcl-util-system.o tsv_sbcl-util-system_windows.o tsv_sbcl-util-cmdline.o tsv_sbcl-proc-opt.o tsv_sbcl-manual.o tsv_sbcl-manual_windows.o  -lcurl 
/usr/bin/ld: tsv_sbcl-main.o:(.bss+0x40): multiple definition of `argv_orig'; tsv_sbcl-tsv-sbcl-bin.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
```

Looks like they haven't run tests with GCC 10 or above. That should be fixable by adding `-fcommon` to CFLAGS or asking upstream for a proper fix :)

**Comment by LiamHowley** [comment]
_That should be fixable by adding -fcommon to CFLAGS or asking upstream for a proper fix :)_

Thanks ericonr. I get the same error unfortunately.

**Comment by ericonr** [comment]
What did you try to do to fix it?

**Comment by LiamHowley** [comment]
As you suggested, I added CFLAGS="-fcommon". I followed the example of a bunch of other templates to do so. Ran ./xbps-src clean roswell, and then rebuilt with -Q flag set.

**Comment by ericonr** [comment]
Can add `make_check=no # tests require -fcommon` to the template, temporarily.

**Comment by LiamHowley** [comment]
Hi Ericonr,

Thanks for the help. I'm obviously doing something wrong. I'll sit down and go through this and do it right next time.
Liam

**Comment by paper42** [comment]
The CI failure can be fixed with this command:

```
git pull --rebase --autostash upstream master
```

**Comment by LiamHowley** [comment]
Thanks very much paper42. I've got a bit of reading to do I think. Appreciate the help, and of course Ericonr

**Pull request merged**
