### PR TITLE
busybox: enable cttyhack applet

### PR DESCRIPTION
**Pull request by zdykstra**

### CODE REVIEW

**Comment by Piraty** [comment]
why?

**Comment by ericonr** [comment]
It can be used to enable job-control in dracut's emergency shell.

**Comment by zdykstra** [comment]
> why? possible side-effects?

I'd like to use that busybox applet/module in other software I create. I don't believe there are any side-effects to enabling another built-in module - I tested it locally without any problems.

**Comment by Piraty** [comment]
I was under the impression that the "no job control" issue in initramfs was due to insufficient bind mounts

**Pull request merged**
