### PR TITLE
mozc: update to 2.26.4353.100. (new package for fcitx5-mozc)

### PR DESCRIPTION
**Pull request by sgn**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by sgn** [comment]
@q66  please check if the ported patch is correct.

**Comment by sgn** [comment]
I only have limited usage of Japanese.

**Comment by sgn** [comment]
@noarchwastaken it seems like you will be interested in this package.
Cc: @mvf

**Comment by noarchwastaken** [comment]
> @noarchwastaken it seems like you will be interested in this package.
> Cc: @mvf

yup.

For the patch, I noticed that the Reiwa era is already in `src/data/dictionary_manual/era.txt`, should we use that instead?

**Comment by sgn** [comment]
> For the patch, I noticed that the Reiwa era is already in `src/data/dictionary_manual/era.txt`, should we use that instead?

Yay, that should work. I started from an old version and the latest version has the era already.

**Comment by mvf** [comment]
Sorry, there just wasn't enough time for me to look into this. This change has issues, most notably it breaks `ibus-mozc` on Qt WebEngine apps like `anki` and `qutebrowser` (that's why I stopped updating). So it's either a revert or an `ibus-mozc` removal (or we figure out why it stopped working after 2.23.2815.102).

**Comment by ericonr** [comment]
@mvf can you open an issue to track this, please?

**Comment by mvf** [comment]
@ericonr Will do. Turns out the version update was unavoidable since `fcitx-mozc` was rebased and the old sources are simply no longer available. I will submit a followup change.

**Pull request merged**
