### PR TITLE
apparmor: update to 3.1.7.

### PR DESCRIPTION
**Pull request by piekay**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)

### CODE REVIEW

**Comment by piekay** [comment]
Version 3.1.7 also fixes some Python syntax warnings happening during installation and when running aa-notify.

**Comment by piekay** [comment]
After the Ci-fail I retested building the package locally and it worked, without errors.

Command used: 

> ./xbps-src -a x86_64-musl -Q pkg apparmor

**Comment by classabbyamp** [comment]
`-a` will prevent tests from running, you want `-A x86_64-musl`

**Comment by piekay** [comment]
Thanks, while I can now recreate the error, I currently have little idea of why this is happening. I will sleep over it and hopefully find the reason tomorrow

**Comment by piekay** [comment]
Interesting: I can reproduce these errors with the 3.1.6_2 template

**Comment by piekay** [comment]
[apparmor_old.log](https://github.com/user-attachments/files/15775399/apparmor_old.log)
[apparmor_new.log](https://github.com/user-attachments/files/15775402/apparmor_new.log)

**Pull request merged**
