### PR TITLE
New package: railway-2.2.0

### PR DESCRIPTION
**Pull request by Eloitor**
#### Testing the changes
- I tested the changes in this PR: **NO**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

I get this error, which I do not know how to solve:

```
error[E0583]: file not found for module `config`
```

### CODE REVIEW

**Comment by icp1994** [comment]
`meson` is supposed to create that file from [config.rs.in](https://gitlab.com/schmiddi-on-mobile/railway/-/blob/master/src/config.rs.in) using the [meson.build](https://gitlab.com/schmiddi-on-mobile/railway/-/blob/master/src/meson.build) file.

**Comment by Eloitor** [comment]
Thanks I was able to build it. 

- Should I change the binary name to railway? It is currently diebahn, but the program is called railway.
- When I run it I get 

```
$ diebahn
zsh: IOT instruction  diebahn
```

**Comment by chrysos349** [comment]
```
# Template file for 'railway'
pkgname=railway
version=2.2.0
revision=1
build_style=meson
build_helper=rust
hostmakedepends="cargo desktop-file-utils gettext glib-devel
 gtk-update-icon-cache pkg-config"
makedepends="libadwaita-devel rust-std"
short_desc="Travel with all your train information in one place"
maintainer="chrysos349 <chrysostom349@gmail.com>"
license="GPL-3.0-or-later"
homepage="https://gitlab.com/schmiddi-on-mobile/railway"
distfiles="https://gitlab.com/schmiddi-on-mobile/railway/-/archive/${version}/railway-${version}.tar.gz"
checksum=ed28cbfc8c2fa73187f85b2ba941e63226bb2adce8255448e50ff6fcf25333f4

post_patch() {
	if [ "$CROSS_BUILD" ]; then
		vsed -i src/meson.build \
			-e "s%rust_target /%'${RUST_TARGET}' / rust_target /%"
	fi
}
```

**Comment by Eloitor** [comment]
Thank you!

**Comment by chrysos349** [comment]
Bump

**Pull request closed without merging**
