### PR TITLE
xrootd: update

### PR DESCRIPTION
**Pull request by dkwo**
- I tested the changes in this PR: no
- I built this PR locally for my native architecture, (x86_64-musl)

Builds fine with openssl3 #37681 but note https://github.com/xrootd/xrootd/issues/1877
It performs no tests, so it is hard to tell @BenJarg

### CODE REVIEW

**Comment by amadio** [comment]
Please wait for 5.5.2 which will be released shortly with a fix for issue 1877 and many others. Cheers.

**Comment by dkwo** [comment]
@amadio If I try to build 5.5.2 with the present template on `x86_64-musl` (and openssl1.1 series), I encounter the error
```
[492/583] Building CXX object src/CMakeFiles/XrdOssCsi-5.dir/XrdOssCsi/XrdOssCsiFile.cc.o
FAILED: src/CMakeFiles/XrdOssCsi-5.dir/XrdOssCsi/XrdOssCsiFile.cc.o 
/usr/bin/g++ -DHAVE_ATOMICS -DHAVE_CRYPT -DHAVE_DH_PADDED -DHAVE_FSTATAT -DHAVE_GETHBYXR -DHAVE_GETIFADDRS -DHAVE_LIBZ -DHAVE_NAMEINFO -DHAVE_READLINE -DHAVE_SENDFILE -DHAVE_SETRESUID -DHAVE_SHADOWPW -DHAVE_SIGWTI -DHAVE_SSL -DHAVE_STRLCPY -DHAVE_XRDCRYPTO -DXRDPLUGIN_SOVERSION=\"5\" -DXrdOssCsi_5_EXPORTS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I/builddir/xrootd-5.5.2/src/.. -I/builddir/xrootd-5.5.2/src/. -I/builddir/xrootd-5.5.2/src -I/builddir/xrootd-5.5.2/build/src -DNDEBUG -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2    -ffile-prefix-map=/builddir/xrootd-5.5.2/build=. -Wall -Wextra -Wno-unused-parameter -fPIC -std=gnu++14 -MD -MT src/CMakeFiles/XrdOssCsi-5.dir/XrdOssCsi/XrdOssCsiFile.cc.o -MF src/CMakeFiles/XrdOssCsi-5.dir/XrdOssCsi/XrdOssCsiFile.cc.o.d -o src/CMakeFiles/XrdOssCsi-5.dir/XrdOssCsi/XrdOssCsiFile.cc.o -c /builddir/xrootd-5.5.2/src/XrdOssCsi/XrdOssCsiFile.cc
In file included from /builddir/xrootd-5.5.2/src/XrdOssCsi/XrdOssCsiFile.cc:34:
/builddir/xrootd-5.5.2/src/XrdOssCsi/XrdOssCsiTagstoreFile.hh: In member function 'int XrdOssCsiTagstoreFile::MarshallAndWriteHeader()':
/builddir/xrootd-5.5.2/src/XrdOssCsi/XrdOssCsiTagstoreFile.hh:176:46: error: 'bswap_32' was not declared in this scope
  176 |       if (fileIsBige_ != machineIsBige_) y = bswap_32(y);
      |                                              ^~~~~~~~
/builddir/xrootd-5.5.2/src/XrdOssCsi/XrdOssCsiTagstoreFile.hh:180:46: error: 'bswap_64' was not declared in this scope
  180 |       if (fileIsBige_ != machineIsBige_) x = bswap_64(x);
      |                                              ^~~~~~~~
/builddir/xrootd-5.5.2/src/XrdOssCsi/XrdOssCsiTagstoreFile.hh:184:46: error: 'bswap_32' was not declared in this scope
  184 |       if (fileIsBige_ != machineIsBige_) y = bswap_32(y);
      |                                              ^~~~~~~~
/builddir/xrootd-5.5.2/src/XrdOssCsi/XrdOssCsiTagstoreFile.hh:188:47: error: 'bswap_32' was not declared in this scope
  188 |       if (machineIsBige_ != fileIsBige_) cv = bswap_32(cv);
      |                                               ^~~~~~~~
```
Do you know how to fix this?

**Comment by BenJarg** [comment]
@dkwo That should compile with the more up to date musl patch from xrootd/xrootd#1632, or the reworked PR xrootd/xrootd#1908 (the latter should be preferred, but I haven't tested applying it to 5.5.2 yet)

**Comment by dkwo** [comment]
@BenJarg Thanks a lot. Can you give it a try when you have time? I also tried to enable tests, but it just says
```
=> xrootd-5.5.2_1: running do_check ...
[0/1] Running tests...
Test project /builddir/xrootd-5.5.2/build
No tests were found!!!
```

**Comment by amadio** [comment]
Running the tests requires setting up multiple containers then launching the test executables to run against them. I hope this year I will convert as many tests as possible to run with a simple call to `ctest`, but for now, we run most tests outside the CI environment (some tests are run in CI, see the GitHub actions on how to run them).

**Comment by dkwo** [comment]
I tried building 5.5.3, assuming it includes the musl patch, but it fails at
```
[6/617] Building CXX object src/CMakeFiles/XrdUtils.dir/XrdSys/XrdSysE2T.cc.o
FAILED: src/CMakeFiles/XrdUtils.dir/XrdSys/XrdSysE2T.cc.o 
/usr/bin/g++ -DHAVE_ATOMICS -DHAVE_CRYPT -DHAVE_CURL_MULTI_WAIT -DHAVE_DH_PADDED -DHAVE_ET_COM_ERR_H -DHAVE_FSTATAT -DHAVE_FUSE -DHAVE_GETHBYXR -DHAVE_GETIFADDRS -DHAVE_LIBZ -DHAVE_NAMEINFO -DHAVE_READLINE -DHAVE_SENDFILE -DHAVE_SETRESUID -DHAVE_SHADOWPW -DHAVE_SIGWTI -DHAVE_SSL -DHAVE_STRLCPY -DHAVE_XML2 -DHAVE_XRDCRYPTO -DXRDPLUGIN_SOVERSION=\"5\" -DXrdUtils_EXPORTS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I/builddir/xrootd-5.5.3/src/.. -I/builddir/xrootd-5.5.3/src/. -I/usr/include/uuid -I/builddir/xrootd-5.5.3/src -I/builddir/xrootd-5.5.3/build/src -DNDEBUG -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2    -ffile-prefix-map=/builddir/xrootd-5.5.3/build=. -Wall -Wextra -Wno-unused-parameter -O3 -DNDEBUG -fPIC -std=gnu++14 -MD -MT src/CMakeFiles/XrdUtils.dir/XrdSys/XrdSysE2T.cc.o -MF src/CMakeFiles/XrdUtils.dir/XrdSys/XrdSysE2T.cc.o.d -o src/CMakeFiles/XrdUtils.dir/XrdSys/XrdSysE2T.cc.o -c /builddir/xrootd-5.5.3/src/XrdSys/XrdSysE2T.cc
In file included from /builddir/xrootd-5.5.3/src/XrdSys/XrdSysE2T.cc:35:
/builddir/xrootd-5.5.3/src/./XrdSys/XrdSysPthread.hh: In constructor 'XrdSysRWLock::XrdSysRWLock(PrefType)':
/builddir/xrootd-5.5.3/src/./XrdSys/XrdSysPthread.hh:357:30: error: 'PTHREAD_RWLOCK_PREFER_WRITER_NONRECURSIVE_NP' was not declared in this scope
  357 |                              PTHREAD_RWLOCK_PREFER_WRITER_NONRECURSIVE_NP);
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/builddir/xrootd-5.5.3/src/./XrdSys/XrdSysPthread.hh:356:22: error: 'pthread_rwlockattr_setkind_np' was not declared in this scope; did you mean 'pthread_rwlockattr_setpshared'?
  356 |                      pthread_rwlockattr_setkind_np(&attr,
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      pthread_rwlockattr_setpshared
/builddir/xrootd-5.5.3/src/./XrdSys/XrdSysPthread.hh: In member function 'void XrdSysRWLock::ReInitialize(PrefType)':
/builddir/xrootd-5.5.3/src/./XrdSys/XrdSysPthread.hh:373:22: error: 'PTHREAD_RWLOCK_PREFER_WRITER_NONRECURSIVE_NP' was not declared in this scope
  373 |                      PTHREAD_RWLOCK_PREFER_WRITER_NONRECURSIVE_NP);
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/builddir/xrootd-5.5.3/src/./XrdSys/XrdSysPthread.hh:372:3: error: 'pthread_rwlockattr_setkind_np' was not declared in this scope; did you mean 'pthread_rwlockattr_setpshared'?
  372 |   pthread_rwlockattr_setkind_np(&attr,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   pthread_rwlockattr_setpshared
```

**Comment by amadio** [comment]
Sorry, the musl patches will be part of the 5.6 release, which should come out sometime this month.

**Comment by dkwo** [comment]
@amadio Could you please ping me here, after the musl-compatible release is out?

**Comment by amadio** [comment]
Sure, no problem. The next feature release will be in June. The patches should apply cleanly to 5.5.5 if you'd like to add that, I can create a sinlge patch file for you to apply to it. Just let me know.

**Comment by dkwo** [comment]
@amadio Thank you. I'm now getting this failure using 5.5.5 and the patch:
```
[92/622] Building CXX object src/CMakeFiles/XrdUtils.dir/XrdNet/XrdNetSecurity.cc.o
FAILED: src/CMakeFiles/XrdUtils.dir/XrdNet/XrdNetSecurity.cc.o 
/usr/bin/g++ -DHAVE_ATOMICS -DHAVE_CRYPT -DHAVE_CURL_MULTI_WAIT -DHAVE_DH_PADDED -DHAVE_ET_COM_ERR_H -DHAVE_FSTATAT -DHAVE_FUSE -DHAVE_GETHBYXR -DHAVE_GETIFADDRS -DHAVE_LIBZ -DHAVE_NAMEINFO -DHAVE_READLINE -DHAVE_SENDFILE -DHAVE_SETRESUID -DHAVE_SHADOWPW -DHAVE_SIGWTI -DHAVE_SSL -DHAVE_STRLCPY -DHAVE_XML2 -DHAVE_XRDCRYPTO -DXRDPLUGIN_SOVERSION=\"5\" -DXrdUtils_EXPORTS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I/builddir/xrootd-5.5.5/src/.. -I/builddir/xrootd-5.5.5/src/. -I/usr/include/uuid -I/builddir/xrootd-5.5.5/src -I/builddir/xrootd-5.5.5/build/src -DNDEBUG -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2    -ffile-prefix-map=/builddir/xrootd-5.5.5/build=. -Wall -Wextra -Wno-unused-parameter -O3 -DNDEBUG -std=gnu++14 -fPIC -MD -MT src/CMakeFiles/XrdUtils.dir/XrdNet/XrdNetSecurity.cc.o -MF src/CMakeFiles/XrdUtils.dir/XrdNet/XrdNetSecurity.cc.o.d -o src/CMakeFiles/XrdUtils.dir/XrdNet/XrdNetSecurity.cc.o -c /builddir/xrootd-5.5.5/src/XrdNet/XrdNetSecurity.cc
/builddir/xrootd-5.5.5/src/XrdNet/XrdNetSecurity.cc: In member function 'bool XrdNetSecurity::Authorize(XrdNetAddr&)':
/builddir/xrootd-5.5.5/src/XrdNet/XrdNetSecurity.cc:172:15: error: 'innetgr' was not declared in this scope
  172 |       do {if (innetgr(tlp->text, hName, 0, 0))
      |               ^~~~~~~
```

**Comment by amadio** [comment]
Do you get this error with the master branch? Maybe I missed a commit in the patch attached above.

**Comment by amadio** [comment]
Indeed, I cherry-picked with a range, and that didn't pick up the first commit in the range. Here's an updated patch: [musl.patch.gz](https://github.com/void-linux/void-packages/files/11543740/musl.patch.gz)

**Comment by dkwo** [comment]
Now it works, thanks.

**Pull request merged**
