### PR TITLE
libinput-gestures: update to 2.57.

### PR DESCRIPTION
**Pull request by uw2021**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Could you please update to 2.57?

**Comment by uw2021** [comment]
> Could you please update to 2.57?

Accidentally added a load of other commits, let me just sort this out with git reset.

**Comment by uw2021** [comment]
> > Could you please update to 2.57?
> 
> Accidentally added a load of other commits, let me just sort this out with git reset.

Sorted, sorry about that.

**Comment by FollieHiyuki** [comment]
You should update the commit message and/or the pr title to 2.57 as well

**Comment by ericonr** [comment]
The commit is really the only one that matters. Please fix.

**Pull request merged**
