### PR TITLE
binutils: update to 2.39. 

### PR DESCRIPTION
**Pull request by oreo639**
#### Testing the changes
- I tested the changes in this PR: **briefly**

[ci skip]

Most of the testing for this was done as a part of the [gcc12 PR](https://github.com/void-linux/void-packages/pull/34902), this was split on request.

There were some api changes in libfd, the following packages were tested to build against binutils-devel:
- [x] oprofile
- [x] prelink-cross
- [x] kcov
- [x] linux-tools
- [x] distcc
- [x] chroot-distcc
- [x] sbsigntool
- [ ] llvm12 (I can't remember if I tested it with binutils 2.39 or just 2.38, building it takes forever, but it should be fine since afaict it doesn't use libbfd or `dis-asm.h`)
- [x] rpm (doesn't actually use binutils-devel but it is listed in the makedepends, builds fine without it)

Please test this PR before merging.

Closes: https://github.com/void-linux/void-packages/pull/39291

### CODE REVIEW

**Comment by dkwo** [comment]
Does it make sense to include here also the `cross-*` commits from the gcc PR, with just the updated binutils part?

**Comment by oreo639** [comment]
> Does it make sense to include here also the cross-* commits from the gcc PR, with just the updated binutils part?

Good point. Thanks.

**Comment by dkwo** [comment]
Thanks. Do you mind fixing the trivial lint errors for the cross* pkgs?
It's a bit tedious, but this way we may catch other stuff when CI goes through.

**Comment by dkwo** [comment]
Sorry, ignore my previous comment.
It's enough to remove ci skip to let it go through ci.

**Comment by paper42** [comment]
> Sorry, ignore my previous comment.
> It's enough to remove ci skip to let it go through ci.

ci skip is here for a reason, building cross-* would time out anyway

**Comment by oreo639** [comment]
Already completed as a part of the gcc 12 PR.

**Pull request closed without merging**
