### PR TITLE
New package: Junction-1.5.0

### PR DESCRIPTION
**Pull request by cultab**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- Also successfully cross-compiled for i686 and armv7l (both glibc)

~# This is a work in progress.~

~As of now it builds correctly but when run it seems to be missing a dependency.~

```
$ re.sonny.Junction

(gjs:14669): Gjs-CRITICAL **: 21:42:42.931: JS ERROR: Error: Requiring Xdp, version none: Typelib file for namespace 'Xdp' (any version) not found
require@resource:///org/gnome/gjs/modules/esm/gi.js:14:24
@gi://Xdp:3:25


(gjs:14669): Gjs-CRITICAL **: 21:42:42.931: Module file:///bin/re.sonny.Junction threw an exception
```

~From what I understand it requires something related to xdg-desktop-portal but I have tested with xdg-desktop-portal-gtk and libportal and it still seems to not work.~

#### Made in response to issue #37352.

### CODE REVIEW

**Comment by cultab** [comment]
@q66 any chance you have some insight as to what might be happening? (I tagged you as you're listed as the maintainer for libportal, sorry if it's inappropriate)

I think `/usr/lib/girepository-1.0/Xdp-1.0.typelib` might be missing from our libportal package?

**Comment by paper42** [comment]
> I think `/usr/lib/girepository-1.0/Xdp-1.0.typelib` might be missing from our libportal package?

It is missing in our version, wait for an update to 0.6 in #36311.

**Comment by cultab** [comment]
Ok great thanks! I will watch that issue and check back here when there's progress.

**Comment by cultab** [comment]
After the big gnome 42 merge, it now works as expected :fireworks:.

Aside from x86_64 I also tested cross-compiling for i686 and armv7l.

**Comment by cultab** [comment]
I'm gonna remake this on a later date cause I fucked up with pulling/pushing/rebasing haha

**Pull request closed without merging**
