### PR TITLE
tree-sitter: update to 0.20.1.

### PR DESCRIPTION
**Pull request by jgarte**
#### Testing the changes
- I tested the changes in this PR: NO

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)

### CODE REVIEW

**Comment by jgarte** [comment]
@ericonr 

linter complains:

> revision should be set to 1 on update

But I set the revision to 2.

How come?

**Comment by ericonr** [comment]
It's the same thing as explained in https://github.com/void-linux/void-packages/pull/34180#issuecomment-974797682

We only need revisions when the version remains the same. Once the version changes, we reset the revision.

**Comment by cinerea0** [comment]
I'm currently testing this version of tree-sitter with neovim, seems to work perfectly.

**Comment by jgarte** [comment]
> It's the same thing as explained in [#34180 (comment)](https://github.com/void-linux/void-packages/pull/34180#issuecomment-974797682)
> 
> We only need revisions when the version remains the same. Once the version changes, we reset the revision.

@ericonr 
Got it! I pushed that change.

**Comment by jgarte** [comment]
> I'm currently testing this version of tree-sitter with neovim, seems to work perfectly.

How are you testing tree-sitter?

Could you share a few tips? :)

**Comment by cinerea0** [comment]
> How are you testing tree-sitter?

I use tree-sitter indirectly because I use neovim with a few plugins that rely on its functionality. If tree-sitter broke, tons of things about my editor would be broken. Unfortunately I don't have a great way to test it directly. Sorry :(

**Pull request merged**
