### PR TITLE
replace voidlinux.eu mail addresses with their .org pendant

### PR DESCRIPTION
**Pull request by Gottox**

### CODE REVIEW

**Comment by Gottox** [comment]
@Vaelatern @the-maldridge @bougyman @Duncaen please check if the new mail addresses work for you!

**Comment by maxice8** [comment]
maintainer= changes need revbumps

**Comment by the-maldridge** [comment]
The maintainer isn't actually changing here, so no rebuild.  We're just updating contact information for already well known entities.  An accompanying NEWS post can be made if you'd like some kind of status update that the addresses have changed.

**Comment by maxice8** [comment]
On Thu, Jan 03, 2019 at 11:44:34PM +0000, Michael Aldridge wrote:
> The maintainer isn't actually changing here, so no rebuild.  We're just updating contact information for already well known entities. 

If that is the case then i have no objections

**Comment by Cogitri** [comment]
#6306

**Comment by Gottox** [comment]
We need to revbump at some point, but I don't think that the rebuild is feasible atm.

**Pull request merged**
