### PR TITLE
python3-pybind11: add symlinks to include, cmake, pkg-config dirs

### PR DESCRIPTION
**Pull request by chrysos349**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-LIBC)

#### Note
Before this change, cmake and pkg-config couldn't find the library.
P.S. I could've moved the dirs, but decided to play it safe, and create symlinks instead.

### CODE REVIEW

**Comment by classabbyamp** [comment]
> Before this change, cmake and pkg-config couldn't find the library.

generally you can do something like `-Dpybind11_DIR=${XBPS_CROSS_BASE}/${py3_sitelib}/pybind11/share/cmake/pybind11`

**Comment by chrysos349** [comment]
@classabbyamp thanks for the piece of advice! I'm still learning the ins and outs of creating packages.

**Comment by ahesford** [comment]
When you touch packages that are actively maintained, please tag the maintainer, especially if you are proposing structural changes to the package.

I'm on the fence about this change. On the one hand, it emulates the behavior of the `pybind11-global` package that upstream distributes. On the other, it should generally be unnecessary if you properly configure the build environment to look for the CMake and pkg-config files where they are actually installed.

Moving the directories would have been the wrong choice, because that would break the Python package.

**Comment by chrysos349** [comment]
> When you touch packages that are actively maintained, please tag the maintainer, especially if you are proposing structural changes to the package.

@ahesford Will do next time.

> it should generally be unnecessary if you properly configure the build environment to look for the CMake and pkg-config files where they are actually installed.

I'd rather not do any extra steps like adding `-Dpybind11_DIR=${XBPS_CROSS_BASE}/${py3_sitelib}/pybind11/share/cmake/pybind11`. This seems like a workaround.

**Comment by ahesford** [comment]
Why are you using `xbps-src` variables like `${XBPS_CROSS_BASE}` and `${py3_sitelib}`? Is there some Void template that is not building properly?

"I'd rather not do any extra steps" isn't a sufficient reason for moving the complexity into the Void package; if upstream decides to move things around in the future, the symlinks we create could easily be broken without going noticed. The `pybind11-global` package is a bit different because they provide a proper setup script to copy files from a location they know exists into the system paths.

**Comment by chrysos349** [comment]
> Why are you using `xbps-src` variables like `${XBPS_CROSS_BASE}` and `${py3_sitelib}`?

That's what @classabbyamp suggested above (https://github.com/void-linux/void-packages/pull/43981#issuecomment-1556058510).

`-Dpybind11_DIR=${XBPS_CROSS_BASE}/${py3_sitelib}/pybind11/share/cmake/pybind11` is used in `gnuradio` templates.

>  Is there some Void template that is not building properly?

No, there's not. I created a template for `audiotube`. cmake couldn't find `pybind11Config.cmake`. So I modified `python3-pybind11`'s template, and recompiled it. I didn't know I could've defined `-Dpybind11_DIR`.

BTW, it turns out there's already a pr for `audiotube` - #37569. At least I learnt something while building it.

> "I'd rather not do any extra steps" isn't a sufficient reason for moving the complexity into the Void package; if upstream decides to move things around in the future, the symlinks we create could easily be broken without going noticed. The `pybind11-global` package is a bit different because they provide a proper setup script to copy files from a location they know exists into the system paths.

Well then, I'm not gonna complicate things any longer. PR closed. Thanks for your valuable feedback.

**Pull request closed without merging**
