### PR TITLE
dropbear: update to 2022.82.

### PR DESCRIPTION
**Pull request by mtboehlke**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by abenson** [comment]
Try to fix the checks.  Start with `checkdepends=python3`

**Comment by mtboehlke** [comment]
I am skipping some tests that run a local dropbear instance, such as the channel tests, which don't work from within xbps-src and probably shouldn't be run there anyways.  In fact, the only tests that run are for dropbearconvert.

Also, we let xbps install the python checkdepends and not pip.

**Comment by leahneukirchen** [comment]
Please remove tests with `rm` instead of patching them out.

**Comment by mtboehlke** [comment]
@leahneukirchen
Thanks!  I made the changes.

**Pull request merged**
