### PR TITLE
gnome-connections: update to 45.0

### PR DESCRIPTION
**Pull request by chrysos349**
split into a separate pr (https://github.com/void-linux/void-packages/pull/48762#issuecomment-1976502687).
a part of #48752

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-musl x
  - armv7l x
  - armv6l-musl x

### CODE REVIEW

**Comment by oreo639** [comment]
> I tested the changes in this PR: YES

Does this work for you? It segfaults for me when connecting to localhost after printing the following multiple times:
```
** (gnome-connections:21832): WARNING **: 20:44:30.882: No data received from local clipboard for sending to remote side!

(gnome-connections:21832): Gdk-WARNING **: 20:44:30.886: ../gdk/wayland/gdkselection-wayland.c:283: error reading selection buffer: Operation was cancelled
```

**Comment by chrysos349** [comment]
I enabled remote desktop on localhost via `gnome-remote-desktop`, and successfully connected to localhost with `gnome-connections`. No segfaulting.

**Comment by chrysos349** [comment]
Actually, i reproduced the same intermittent segfaults when trying to connect to localhost. It happens when I copy an image to the clipboard.

```
../gdk/wayland/gdkselection-wayland.c:283: error reading selection buffer: Operation was cancelled
No data received from local clipboard for sending to remote side!
```

When I connect to the remote windows box, no segfaulting happens (even if I have an image in the clipboard).

Does it mean the bug is specific to localhost connections and has something to do with the clipboard contents? (Who needs connecting to the localhost  anyway??)

**Comment by chrysos349** [comment]
here is what I found in release notes for `gnome-connections-46.beta`
see here - https://download.gnome.org/sources/gnome-connections/46/gnome-connections-46.beta.news
```mardkown
- Update gtk-frdp
     - Fix several crashes related to clipboard channel
```
that may be the reason for the crashes.

**Comment by chrysos349** [comment]
The backported patch didn't fix crashes.

`45.0` introduced clipboard channel support (via the update gtk-frdp widget), which causes crashes.
`46.beta` and `46.rc` also crash.

`44.0` doesn't exhibit this behavior, because it doesn't have clipboard channel.

AGAIN, the crash only happens with localhost connections. Remote connections don't crash, and I can successfully paste an image into the document on the windows box.

**Comment by chrysos349** [comment]
flatpak version of `gnome-connections-45.0 ` crashes as well.

**Comment by chrysos349** [comment]
`gnome-connections-45.0` on `Ubuntu 23.10` also crashes when having something in the clipboard and connecting to localhost. So not a void-specific bug.

**Pull request closed without merging**
