### PR TITLE
[WIP] New package: vvave-1.2.1

### LINKED ISSUE #2579: Package request: Babe Music Player
"Babe will handle your whole music collection
by retreaving semantic information from the web.

Just relax, enjoy and discover your new [music](https://vvave.kde.org)"

Tar.xz included: [here](https://download.kde.org/stable/babe/1.2/src/babe-1.2.tar.xz.mirrorlist)

Thank You.

### PR DESCRIPTION
**Pull request by Johnnynator**
resolves #2579

### CODE REVIEW

**Comment by Johnnynator** [comment]
Just for the records. It doesn't work properly right now. Segfaults while indexing my music lib.

**Comment by MirceaMx** [comment]
I think it's in Alpha or Beta right now. They have an .appimage, I downloaded that and indexing was a problem with that too. I was hoping the release wouldn't behave the same but from what you're telling me it appears it does. Oh well...thank you and hope I will find a way to get it working or...just wait for another release.

**Comment by MirceaMx** [comment]
@Johnnynator Fine by me. Can you please close the issue. Thank you.

**Comment by MirceaMx** [comment]
@Johnnynator Please close this too.

**Comment by cr6git** [comment]
@MirceaMx done.

**Pull request closed without merging**
