### PR TITLE
par: added unicode support

### PR DESCRIPTION
**Pull request by ValTimchenko**
Subj. Just added unicode patch made by Jérôme Pouiller as of: http://sysmic.org/dotclear/index.php?post/2006/06/22/55-add-multibyte-characters-support-in-par

### CODE REVIEW

**Comment by Hoshpak** [comment]
We usually don't patch software to introduce new features, I will refer to the maintainer of the package regarding this though.

Please not that should this be merged, the commit title should be formatted with the package name first and then what it does, like `par: add unicode patch`. Also you should increase the revision in the package template, otherwise the builders won't rebuild the package with the change.

**Comment by ValTimchenko** [comment]
> We usually don't patch software to introduce new features, I will refer to the maintainer of the package regarding this though.
Should've done that myself, but just overreacted yesterday, when par -w80rj had almost left me without me lectures on history.
> Please not that should this be merged, the commit title should be formatted with the package name first and then what it does, like `par: add unicode patch`.
Done.
> Also you should increase the revision in the package template, otherwise the builders won't rebuild the package with the change.
Done in the first place rev. 3->4.

**Comment by ValTimchenko** [comment]
Ok, can anyone tell me what to do with Travis' "srcpkgs/par/template:9: use SPDX id for 'custom' license or see Manual.md"?

**Comment by zdtcd** [comment]
> > Please note that should this be merged, the commit title should be formatted with the package name first and then what it does, like `par: add unicode patch`.
> 
> Done.

He meant you needed to change the commit message itself, not this PR's title.

**Comment by ValTimchenko** [comment]
> > > Please note that should this be merged, the commit title should be formatted with the package name first and then what it does, like `par: add unicode patch`.
> > 
> > 
> > Done.
> 
> He meant you needed to change the commit message itself, not this PR's title.

Done.

**Comment by zdtcd** [comment]
> Done. Still don't know what to do with license.

`s/custom/&:par/` or `s/custom/&:nicemice/`

**Comment by leahneukirchen** [comment]
Debian has this patch too, I don't object to adding it.

**Pull request merged**
