### PR TITLE
foot: update to 1.6.0

### PR DESCRIPTION
**Pull request by st3r4g**
@ifreund do you want to try the new partial PGO build? Imo it's fine as it is.

### CODE REVIEW

**Comment by ifreund** [comment]
> @ifreund do you want to try the new partial PGO build? Imo it's fine as it is.

@st3r4g Since void uses `-O2` by default and foot [strongly recommends](https://codeberg.org/dnkl/foot/src/branch/master/INSTALL.md#performance-optimized-pgo) `-O3` for PGO builds I don't think it makes sense to enable them for the void package by default. Perhaps a default-disabled build option enabling `-O3` and PGO would be good to have though.

**Comment by ericonr** [comment]
@st3r4g are you going to add it for this update or is it ok to merge?

**Comment by st3r4g** [comment]
Not interested atm, ok to merge.

**Comment by ericonr** [comment]
@ifreund @st3r4g 

I had to add bb297cad7e3eec455bff93abc3f9791ec2314b0d because the build failed on some builders. If either of you could take the issue upstream, that'd be great! Thanks :)

**Comment by ericonr** [comment]
Actually fixed with https://github.com/void-linux/void-packages/commit/b1041435727bc2379b98c5320afb40de7f6576f4 , so there isn't much to do anymore.

**Comment by st3r4g** [comment]
Ah sorry, didn't notice the issue.

**Comment by ericonr** [comment]
No worries, I couldn't even reproduce locally reliably. For some reason the builders hit it constantly.

**Pull request merged**
