### PR TITLE
lvm2: update to 2.03.08.

### PR DESCRIPTION
**Pull request by Anachron**

### CODE REVIEW

**Comment by Anachron** [comment]
I'm going to give this package a short test. Please wait.

**Comment by xtraeme** [comment]
I always assume that all pkg updates submitted via github are tested locally.

If this is not the case I'd like to know.

**Comment by Anachron** [comment]
Yes but for some packages (like LVM2) I need to reboot so I can't do it instantly after packaging. Sorry, this time I made the PR too fast.

**Comment by xtraeme** [comment]
np. I almost know who are the ones that I can trust of.

**Comment by Anachron** [comment]
Normally I say when the package is not tested/WIP ;)
If I submit a PR without a comment and it builds it's normally tested on x86_64.

**Comment by xtraeme** [comment]
ok, thanks for the info.

**Comment by Anachron** [comment]
After checking the source it looks like lvm2app is not part of lvm2 anymore. I'm going to dig in deeper.

**Pull request closed without merging**
