### PR TITLE
minidlna: add runit logging

### PR DESCRIPTION
**Pull request by jbenden**
This patch introduces runit-based logging to the package.

Also fixed a few `xlint` complaints.

Signed-off-by: Joseph Benden <joe@benden.us>

### CODE REVIEW

**Comment by Duncaen** [comment]
use vlogger instead, logger has a race condition and doesn't log if it starts before sockog.

```
ln -s /usr/bin/vlogger srcpkgs/minidlna/files/minidlnad/log/run
```

**Comment by jbenden** [comment]
Thank you!

**Comment by Duncaen** [comment]
If the run script of log is a link to /usr/bin/vlogger, you don't have to specify the tag, it will use the name of the service.

**Comment by jbenden** [comment]
Even better!

Thank you very much!

**Pull request closed without merging**
