### PR TITLE
Manual.md: recommend keeping systemd units

### LINKED ISSUE #32481: [RFC] systemd service files
Currently there is no policy on systemd files, some packages ship them and some delete them.

There is an open issue about removing them #32154 and a hook for automatically removal was discussed there.

I personally would prefer to keep them as a reference point for services.

### PR DESCRIPTION
**Pull request by CameronNemo**
Closes #32481

[ci skip]

#### Testing the changes
- I tested the changes in this PR: **N/A**

### CODE REVIEW

**Review by paper42 — APPROVED** [review]

**Comment by Chocimier** [comment]
What are possible negative side effects?

**Comment by CameronNemo** [comment]
One scenario I had in mind was if there was some configure flag that installed the units but also changed the runtime of the service in some way. I did not want packagers feeling like they had to install units in that case, or patch the software to get around it. It is just sort of a generic out, letting the packager know they won't get dinged if they exclude the units.

**Comment by Chocimier** [comment]
> installed the units but also changed the runtime or dependencies of the package in some way

Okay, please mention this as example in manual.

**Comment by CameronNemo** [comment]
Alright added the examples.

**Review by classabbyamp — APPROVED** [review]

**Pull request merged**
