### PR TITLE
electron19: update to 19.1.3.

### PR DESCRIPTION
**Pull request by Johnnynator**
#### Testing the changes
- I tested the changes in this PR: **YES**|**briefly**|**NO**

### CODE REVIEW

**Comment by classabbyamp** [comment]
is it possible to move this to py3?

**Comment by Johnnynator** [comment]
Should be some easy fixes hopefully, but `s/python2/python3/` is not enough.

**Comment by Johnnynator** [comment]
The fix was a bit more trivial than expected. Just one `iteritems` -> `items` in a script that probably nobody except us even uses.

**Comment by Johnnynator** [comment]
Wondering if I should probably start maintainging the patches outside of void-packages, or just fetch a pre patched tarball, `electron19` dir is currently 35MB

**Comment by paper42** [comment]
electron19 in the current version doesn't build with gcc 12: https://github.com/void-linux/void-packages/issues/39809, [log](https://vasilek.cz/logs/gcc12-musl/bad/electron19.txt), I will be able to check this version tomorrow, could we wait for that before merging this update?

**Review by paper42 — COMMENTED** [review]
`gtk+-devel` and `libgnome-keyring-devel` can probably be removed from build dependencies, they were removed from the chromium template in f2fa87cd97d0338d631d5e2a7a5c7994fb264123

**Comment by paper42** [comment]
the current version and this update now fail to build with Python 3.11:
```
=> electron19-19.1.3_1: running do_configure ...
Please use python3.10 or python3.9 or python3.8 or python3.7 or python3.6.
Node.js configure: Found Python 3.11.0...
=> ERROR: electron19-19.1.3_1: do_configure: './configure --prefix=/usr --shared-zlib --shared-libuv --shared-openssl --shared-cares --openssl-use-def-ca-store --without-npm --without-dtrace --without-bundled-v8 ${conf_args}' exited with 1
=> ERROR:   in do_configure() at srcpkgs/electron19/template:281
```

**Comment by paper42** [comment]
It's from nodejs and not fixed in any 16 release, this commit fixes it https://github.com/nodejs/node/commit/cf748ad2b7f760e2df1bc8a811f887161b892534

**Pull request closed without merging**
