### PR TITLE
owncloudclient: add service

### PR DESCRIPTION
**Pull request by ndowens**
Added service, as one can sync folder without the need of GUI
Adopt; contacted maintainer and he said I could take

### CODE REVIEW

**Comment by Duncaen** [comment]
I don't think this service should be added.
`exec sleep 2; cmd` is definitively wrong.

**Comment by xtraeme** [comment]
Heh

**Comment by ndowens** [comment]
> I don't think this service should be added.
> `exec sleep 2; cmd` is definitively wrong.

Should it be just sleep 2m, drop the exec?  I think having a service file would be convenient for people that doesn’t want/need a GUI to run to sync files. I know I don’t want it having to be up just to sync and waste more memory than a service would use

**Comment by Duncaen** [comment]
Even without the exec, its not a good service, it will supervise the run script and its running as root.
I feel like if we would allow this, we open the doors for a bunch of other not really services that don't fit into the supervision model.

**Pull request closed without merging**
