### PR TITLE
cvs: fix cross.

### PR DESCRIPTION
**Pull request by fosslinux**
The check evaluates to null anyway.

### CODE REVIEW

**Review by sgn — COMMENTED** [review]
I think it's better to just append `cvs_cv_func_printf_ptr=yes` to `configure_args`

**Comment by sgn** [comment]
Anyway, isn't cvs available in all repo already?

**Comment by fosslinux** [comment]
Yes it is but for some reason recently it seems to be FTBTS on cross.

**Comment by sgn** [comment]
Work on my machine for musl target.

**Pull request closed without merging**
