### PR TITLE
anki: update to 2.1.65 failed

### PR DESCRIPTION
**Pull request by loreb**
=> anki-2.1.64_1: skipping check (XBPS_CHECK_PKGS is disabled) ...
=> anki-2.1.64_1: running pre-install hook: 00-libdir ...
=> anki-2.1.64_1: running pre-install hook: 02-script-wrapper ...
=> anki-2.1.64_1: running pre-install hook: 98-fixup-gir-path ...
=> anki-2.1.64_1: running do_install ...
error: found a virtual manifest at `/builddir/anki-2.1.64/Cargo.toml` instead of a package manifest
=> ERROR: anki-2.1.64_1: do_install: '${make_cmd} install --target ${RUST_TARGET} --root="${DESTDIR}/usr" --offline --locked ${configure_args} ${make_install_args}' exited with 101
=> ERROR:   in do_install() at common/build-style/cargo.sh:22

#### Testing the changes
- I tested the changes in this PR: **YES**|**briefly**|**NO**

### CODE REVIEW

**Comment by loreb** [comment]
I tried to force it to compile by patching out submodules, got this far and I'm not sure how to proceed.
Regarding the submodules the idea was to follow the example of https://github.com/void-linux/void-packages/blob/master/srcpkgs/tracebox/template - any comment/correction/... appreciated

**Comment by acdimalev** [comment]
Thanks for working on this.  I'm trying a different approach as well.

https://forums.ankiweb.net/t/anki-source-tarballs/33686

I've got a few reasons for wanting complete official source tarballs, so going to find out where asking nicely takes things.

**Comment by acdimalev** [comment]
That went nowhere fast.

Just in case anyone else has been bit by the same problem.  Upgrading Anki on my phone automatically enabled the following feature that broke Anki on my desktop:

Settings / Reviewing / New timezone handling

Disabled that and it's working again.

Building Recent versions of Anki in Void looks a bit like a mess.  It's worth noting that the docs call out musl as being explicitly not supported.  But just trying to get the thing to build at all, this is what I've got.

```
# force use of OS binaries
export NODE_BINARY=/usr/bin/node
export PROTOC_BINARY=/usr/bin/protoc
export PYTHON_BINARY=/usr/bin/python3
export YARN_BINARY=/usr/bin/yarn
export PYTHONPATH=/usr/lib/python3.11/site-packages

# disable all pyenv package installation
echo > python/requirements.base.txt
echo > python/requirements.dev.txt
echo > python/requirements.qt6_lin.txt

# add runtime dependencies...
# black
# python3-Flask
# python3-Flask-Cors
# python3-protobuf
# python3-waitress

# disable use of pip-sync
# --- a/build/runner/src/pyenv.rs
# +++ b/build/runner/src/pyenv.rs
# @@ -25,7 +25,6 @@ pub fn setup_pyenv(args: PyenvArgs) {
#
#      let pyenv_bin_folder = pyenv_folder.join(if cfg!(windows) { "scripts" } else { "bin" });
#      let pyenv_python = pyenv_bin_folder.join("python");
# -    let pip_sync = pyenv_bin_folder.join("pip-sync");
#
#      if !pyenv_python.exists() {
#          run_silent(
# @@ -52,6 +51,4 @@ pub fn setup_pyenv(args: PyenvArgs) {
#              &args.initial_reqs,
#          ]));
#      }
# -
# -    run_silent(Command::new(pip_sync).args(&args.reqs));
#  }

# disable protobuf mypy output
# maybe there's a dependency that would satisfy this...
# --- a/build/configure/src/python.rs
# +++ b/build/configure/src/python.rs
# @@ -86,9 +86,7 @@ pub struct GenPythonProto {
#  impl BuildAction for GenPythonProto {
#      fn command(&self) -> &str {
#          "$protoc $
# -        --plugin=protoc-gen-mypy=$protoc-gen-mypy $
#          --python_out=$builddir/pylib $
# -        --mypy_out=$builddir/pylib $
#          -Iproto $in"
#      }
# EOD

# build
tools/build
```

This results in the output of a couple wheel files which _should_ be installable via normal means, but I've run out of steam for testing at the moment.

```
$ ls -1 out/wheels/
anki-2.1.65-cp39-abi3-manylinux_2_28_x86_64.whl
aqt-2.1.65-py3-none-any.whl
```

**Comment by loreb** [comment]
lol, that makes two of us!

In my case I've decided that mnemosyne can import all my cards and it builds without much trouble (and much more quickly); if you ever feel like giving it another try, I can only recommend that you read the bug about anki being too hard to build, then look at the work done by the guys who packaged it for nix and freebsd, pick whichever you find more readable and do exactly what they do.

**Comment by Vaelatern** [comment]
Me three. Wow this is a challenge.

**Pull request closed without merging**
