### PR TITLE
incidenceeditor: update to 23.04.2

### PR DESCRIPTION
**Pull request by chrysos349**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-LIBC)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64

### CODE REVIEW

**Comment by classabbyamp** [comment]
> - I tested the changes in this PR: **briefly**
> 
> #### Local build testing
> - I built this PR locally for my native architecture, (x86_64-LIBC)
> - I built this PR locally for these architectures (if supported. mark crossbuilds):
>   - aarch64

what did you do to test it?

**Comment by chrysos349** [comment]
@classabbyamp I launched the executable file `/usr/bin/kincidenceeditor`.

**Comment by ahesford** [comment]
Clearly you aren't testing these. Stop making submissions like this.

**Comment by chrysos349** [comment]
@ahesford Clearly you're wrong. I tested #44710, #44713, #44714, #44715, #44716 for a bit. I launched[^1] all of them, and used them briefly. I admit i don' know how to properly test #44712, #44711. 

All of those are minor releases without any breaking changes in the functionality, etc. What else do i need to do to test them?

There's hardly any information in the manual about how to test different types of packages - apps, libs, python modules, etc. Could you give me any advice?

[^1]: There is this line in CONTRIBUTING.md: "Also, new packages and updates will not be accepted unless they have been runtime tested by installing and running the package."

**Comment by ahesford** [comment]
The first step in testing the package is successfully building it. CI builds of your submission failed for every architecture against which we test. How did this build successfullly for you to test it?

**Comment by chrysos349** [comment]
@ahesford I know. Thanks for stating the obvious.

I build the packages for my own arch and aarch64. Here are the build logs and a check log.
[incidenceeditor-x86_64.txt](https://github.com/void-linux/void-packages/files/11910514/incidenceeditor-x86_64.txt)
[incidenceeditor-aarch64.txt](https://github.com/void-linux/void-packages/files/11910516/incidenceeditor-aarch64.txt)
[incidenceeditor-check.txt](https://github.com/void-linux/void-packages/files/11910517/incidenceeditor-check.txt)

Do I need to attach the built packages as well?

> How did this build successfully for you to test it?

See the logs above, and you tell me.

>There's hardly any information in the manual about how to test different types of packages - apps, libs, python modules, etc. Could you give me any advice?

Any comments?

P.S. What's your reasoning behind closing my other submissions? They passed the checks. I tested them briefly. What else?

**Comment by ahesford** [comment]
If we were interested in untested or trivially tested updates, we'd employ a bot to do the task.

Your other update PRs were closed because the rapid-fire nature of shoddy or poorly tested submissions has eroded your credibility. Please limit your contributions in the future to updates that you've spent some time using and can comment on with greater depth than "I launched an executable."

**Comment by sgn** [comment]
Those packages needs to be built together. KDE requires all packages has the same version.

**Pull request closed without merging**
