### PR TITLE
Adding x86_64 package to wine

### PR DESCRIPTION
**Pull request by bugcrazy**
Adding support for x86_64 to generate x84_64 and i686 packages to have a wine 64 package required by many

### CODE REVIEW

**Comment by bugcrazy** [comment]
My x86_64 build log, no errors appear! This link [here](https://gist.githubusercontent.com/bugcrazy/73fb15bccf7ba3dc40145c3c0168a2b7/raw/b6089897f9c30475b321a8806d9b6e5d9454e755/Mylog_wine_x86_64)

**Comment by Eluminae** [comment]
How are we supposed to handle travis too long logs issues ? :)

**Comment by travankor** [comment]
@bugcrazy See https://github.com/void-linux/void-packages/pull/540#issuecomment-417840507

**Comment by Eluminae** [comment]
so this will never be merged ?

**Comment by travankor** [comment]
I think a separate template called `wine64` might work.

**Comment by bugcrazy** [comment]
> How are we supposed to handle travis too long logs issues ? :)
This issue gets in the way, the travis should generate a file, thus facilitating the fixes!

**Comment by bugcrazy** [comment]
> @bugcrazy See [#540 (comment)](https://github.com/void-linux/void-packages/pull/540#issuecomment-417840507)
I know, the issue is in travis, it doesn't show what the conflict is, how to fix an issue, if we don't know what it is!

**Comment by bugcrazy** [comment]
It will be merged, when we know issue of travis, we can fix it!


> so this will never be merged ?
It will be merged, when we know issue of travis, we can fix it!

**Comment by bugcrazy** [comment]
> I think a separate template called `wine64` might work.
I think there must be something between the 32-bit libraries with x86_64, which generates the issue, but that's a hypothesis!

**Comment by Oreo639** [comment]
The issue in travis is that the build log is too long. You can use [ci skip] in the commit message to skip travis building. It isn't the reason this pr likely won't get merged though.

As for why wine x86_64 likely won't get merged as was said before. xbps-src is supposed to let you build a package without any precompiled dependencies (it automatically builds them beforehand if they aren't in the repos). However it can't automatically cross compile 32-bit dependencies. If it tries to build a -32bit dependency in 64bit mode it will just make a 64bit package. You have to cross compile all the 32-bit dependencies beforehand. Thus it requires precompiled 32bit dependencies in the repos in order to work which is not optimal.

From Hoshpak:
>However void-packages is built on the premise that it is possible to bootstrap everything from sources without requiring any preexisting binary packages. So I should be able to always just clone this repository, not use any of the mirrors and build a whole system from the sources.

Also your commit log doesn't follow the commit style guide.

If I am mistaken please correct me.

**Comment by bugcrazy** [comment]
> The log too long issue in travis can be worked around by using [ci skip] in the commit message to skip travis building. It isn't the reason this pr likely won't get merged though.
> 
> As for why wine x86_64 likely won't get merged as was said before. xbps-src is supposed to let you build a package without any precompiled dependencies (it automatically builds them beforehand if they aren't in the repos). However it can't automatically cross compile 32-bit dependencies. If it tries to build a `-32bit` package in a 64bit environment it will just make a 64bit package. You have to cross compile all the 32-bit dependencies beforehand. Thus it requires precompiled 32bit dependencies in order to work which is not optimal.
> 
> From Hoshpak:
> 
> > However void-packages is built on the premise that it is possible to bootstrap everything from sources without requiring any preexisting binary packages. So I should be able to always just clone this repository, not use any of the mirrors and build a whole system from the sources.
> 
> Also your commit log doesn't follow the commit style guide.
> 
> If I am mistaken please correct me.

Thanks for the tip! But the Steam package depends on 32-bit libraries, and Steam works on 64-bit with 32-bit libraries.

**Comment by Duncaen** [comment]
> Thanks for the tip! But the Steam package depends on 32-bit libraries, and Steam works on 64-bit with 32-bit libraries.

We don't build steam and it doesn't depend on 32bit (for the same reason).

**Comment by Hoshpak** [comment]
d87090939234e8c4868aca2e4d855789d6011c76

**Pull request closed without merging**
