### PR TITLE
ldc: update to 1.36.0

### PR DESCRIPTION
**Pull request by jtbx**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-musl

### CODE REVIEW

**Comment by oreo639** [comment]
See the output of:
`xbps-query -RX ldc-runtime`

All those packages need to be revbumped as the soname has changed.

**Comment by jtbx** [comment]
Got it, thanks :)

**Comment by oreo639** [comment]
There should be a separate commit per package. You can use `git rebase -i HEAD~n` where n is a number of commits back to manage multiple commits.

**Comment by jtbx** [comment]
Alright sure thing, but those libraries are all symlinks to gtkd.

**Comment by oreo639** [comment]
> but those libraries are all symlinks to gtkd

Ah, yeah, my bad.

**Comment by jtbx** [comment]
Updated to 1.36.0
https://github.com/ldc-developers/ldc/releases/tag/v1.36.0

**Comment by zdykstra** [comment]
The merge commit needs to be removed. Rebase your branch on master instead.

**Comment by jtbx** [comment]
Done

**Pull request closed without merging**
