### PR TITLE
New package: gnome-pomodoro-0.24.0

### PR DESCRIPTION
**Pull request by Eloitor**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by Eloitor** [comment]
What should I do with this tests?

```
(gnome-pomodoro-test-executable:2940): Gtk-WARNING **: 17:22:33.934: cannot open display: 
```

**Comment by classabbyamp** [comment]
checkdepends+=xvfb

make_check_pre=xvfb-run

or something like that

**Comment by Eloitor** [comment]
I don't know what to do with

```
Found CMake: NO
Run-time dependency gom-1.0 found: NO (tried pkgconfig)

meson.build:19:10: ERROR: Dependency "gom-1.0" not found, tried pkgconfig
```

**Comment by classabbyamp** [comment]
probably something in hostmakedepends that shouldn't be

**Pull request closed without merging**
