### PR TITLE
[WIP] Tracking: xorg-server: update to 21.1.0.

### PR DESCRIPTION
**Pull request by leahneukirchen**
In WIP because upstream tarballs are botched: https://gitlab.freedesktop.org/xorg/xserver/-/issues/1240 , waiting for 21.1.1.

Added new dependency libxcvt.

xorg-server-xdmx is gone upstream.

### CODE REVIEW

**Comment by Animeshz** [comment]
XInput also needed to be updated to v2 I guess, XInput2.4 offers new smooth-gesture support coming from [here](https://bill.harding.blog/2021/06/06/linux-touchpad-like-macbook-update-touchpad-gestures-land-to-qt-gimp-and-x-server).

**Comment by leahneukirchen** [comment]
https://gitlab.freedesktop.org/xorg/xserver/-/issues/1241

**Comment by curiousjunior** [comment]
@leahneukirchen that issue is closed already and xorg-server 21.1.2 is a fresh release

**Comment by leahneukirchen** [comment]
I don't have time for this PR and all the required changes currently, someone feel free to pick up.

**Comment by dkwo** [comment]
I tried it in #34593, seems to work fine.

**Comment by Chocimier** [comment]
Updated to 21.1.3 in #34593

**Pull request closed without merging**
