### PR TITLE
json-c: update to 0.14.

### PR DESCRIPTION
**Pull request by rmccask**

### CODE REVIEW

**Comment by ericonr** [comment]
json-c requires a patch for a CVE https://github.com/json-c/json-c/commits/json-c-0.14 and should be releasing a version, because there were some other issues in the 0.14 version.

@leahneukirchen was going to look into this, I believe.

**Comment by rmccask** [comment]
The patch, 2-json-c-0.14-security-fix.patch, that I copied from Gentoo fixes the CVE already.  It is almost exactly like the patch committed upstream.

**Comment by ericonr** [comment]
I missed it, sorry! Could you mention it in the commit as well?

**Comment by rmccask** [comment]
I am in the middle of something.  I will update the commit message as soon as it completes and then I will update this message as well.

**Comment by rmccask** [comment]
An update to frr was just pushed in [22485](https://github.com/void-linux/void-packages/pull/22485/files).  After that is committed to master, I will edit this commit.

**Pull request merged**
