### PR TITLE
[WIP] OCaml 4.08

### PR DESCRIPTION
**Pull request by leahneukirchen**
Missing/broken:
- [x] ELFv2 patches for ppc64 (@q66)
- [ ] verifast
- [x] coq
- [ ] mldonkey
- [x] wyrd
- [x] ocaml-lablgtk2
- [x] unison
- [x] pfff
- [ ] coccinelle
- [x] camlp5
- [x] camlp4
- [x] opam

### CODE REVIEW

**Comment by q66** [comment]
Away from home rn, will look at fixing them after the weekend when I get back

**Comment by leahneukirchen** [comment]
No hurries, we'll have to wait for a bunch of other upstream releases before we can merge this.

**Comment by q66** [comment]
Here's updated patches https://ftp.octaforge.org/q66/random/ocamlpatches/

**Comment by leahneukirchen** [comment]
Bumped to 4.08.1.

The other packages are unlikely to be updated quickly, so we need to decide what to do with this.

**Pull request merged**
