### PR TITLE
mesa: update to 21.1.3.

### PR DESCRIPTION
**Pull request by ardadem**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [X] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

EDIT: tested on x86_64

### CODE REVIEW

**Comment by ardadem** [comment]
aarch64 failed on fetching distfile:
```
=> mesa-21.1.2_1: fetching distfile 'mesa-21.1.2.tar.xz'...
https://mesa.freedesktop.org/archive/mesa-21.1.2.tar.xz: Transient resolver failure
=> ERROR: mesa-21.1.2_1: failed to fetch mesa-21.1.2.tar.xz.
Error: Process completed with exit code 1.
```

**Comment by Cloudef** [comment]
Linking issue https://github.com/void-linux/void-packages/issues/30821 as this will fix it

**Comment by ardadem** [comment]
21.1.3 will be released soon, i'll update it when it's out

**Comment by tsujp** [comment]
I've been using this for the past week or so, `21.1.2` and am building `21.1.3` from this PR. It fixed some horrific artifacting I was getting with an AMD RX 6700 XT when using `21.0.3_4`.

**Comment by ericonr** [comment]
21.1.4 is out, I'm build testing that and will push it if everything seems fine.

**Comment by tsujp** [comment]
How does merging this branch in work? I obviously haven't contributed here and don't want to appear as the canonical "pls merge free work now!!!!" but it appears the checks pass and I and the author have been using this with stability, what else is blocking a merge into main?

**Pull request closed without merging**
