### PR TITLE
mutagen: update to 1.43.1, split package

### PR DESCRIPTION
**Pull request by UsernameRandomlyGenerated**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by Chocimier** [comment]
There are packages depending on both variants, we can't just drop it.

**Comment by UsernameRandomlyGenerated** [comment]
> There are packages depending on both variants, we can't just drop it.

From what I've seen there's only one. We could resolve it by keeping python3-mutagen and using the template from the commit if it's alright to keep old version of package just for idjc. Maybe splitting them into mutagen (python3) and creating python2-mutagen for idjc would be better?

**Comment by Chocimier** [comment]
Please do the former. Renaming package requires to still keep transitional package with old name to provide updates.

**Comment by UsernameRandomlyGenerated** [comment]
I've updated the old mutagen to v1.43.1 and squashed the commits (though I'm not sure if I should do that)

**Comment by Chocimier** [comment]
Executables must be renamed by adding prefixes as they were, and alternatives kept in both variants. For manpages, they may be removed from py2 and left with py3. 
Please split commits to first updating to 1.43.1 and second splitting python3-mutagen.

**Comment by ericonr** [comment]
@Chocimier

**Comment by Chocimier** [comment]
Binaries was renamed to *2 and *3 by python-module build_style,. After change of build-style, they are same and need to be explicitely renamed in post_install in both packages.
For manpages, they may be removed from py2 and left with py3.

**Comment by UsernameRandomlyGenerated** [comment]
Sorry for the delay. There is currently only one package that depends on old mutagen (idjc) which had update to 0.9.1 (we have 0.8.17) and the new version requires mutagen v1.4.4+ (python3 only). So I think it would be safe to delete old mutagen while keeping only python3 version after updating idjc.

**Comment by Chocimier** [comment]
Good. Please remove alternatives, they are not needed for one package.

**Pull request merged**
