### PR TITLE
libgit2: update to 1.2.0.

### PR DESCRIPTION
**Pull request by g4s8**
Updated libgit2 to `v1.2.0`, added patch with PR
https://github.com/libgit2/libgit2/pull/6032 of
`git_remote_name_is_valid` fix for https://github.com/libgit2/git2go/issues/834 issue.

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me: checked with tests of https://github.com/libgit2/git2go (`libgit2` is a dependency there)
- [ ] I generally don't use the affected packages but briefly tested this PR

Ref: #28456
Maintainer: @q66

### CODE REVIEW

**Comment by g4s8** [comment]
I tried to build `geany-plugins` on clean workspace, and it's failing with same error: #33568

**Comment by q66** [comment]
don't worry about julia, this is clearly not caused by libgit2, so just put in a make_check=no plus a comment explaining the reason

**Comment by g4s8** [comment]
@q66 could you please help here? I'm not sure why CI is failing: locally these tests passes fine:
```bash
./xbps-src check gnome-builder
./xbps-src install gnome-builder
./xbps-src check libgit2-glib
./xbps-src install libgit2-glib
```
What is wrong here?

**Comment by q66** [comment]
you forgot to revbump gnome-builder?

**Pull request closed without merging**
