### PR TITLE
thunderbird: update to 78.2.1

### PR DESCRIPTION
**Pull request by mmnmnnmnmm**
Updated to the 78 branch, this contains big OpenPGP changes and supports only webextensions.

### CODE REVIEW

**Comment by sgn** [comment]
On 2020-08-27 08:27:53-0700, mmnmnnmnmm <notifications@github.com> wrote:
> Final release in the 68 branch, next release is 78, which contains
> big OpenPGP changes and supports only webextensions.

I don't use Thunder Bird, but I think we should switch to 78.2 now.

-- 
Danh

**Comment by mmnmnnmnmm** [comment]
Sure, I barely use thunderbird anymore so I can't reliably test the new changes but I'll update this pr once I get it to build.

I could also update firefox-esr to 78 now as I've been running it for over a month now.

**Comment by mmnmnnmnmm** [comment]
Sure, I barely use thunderbird anymore so I can't reliably test the new changes but I'll update this pr once I get it to build.

I could also update firefox-esr to 78 now as I've been running it for over a month now.

**Comment by mmnmnnmnmm** [comment]
The files and template have been taken from firefox78 and modified.

I don't know what I'm doing with regards to browsers so some of the patches
may not be needed.

This works on x86_64-glibc, but if anyone uses OpenPGP please test!

**Comment by archfan** [comment]
I've successfully compiled from your template. Runs fine and the included pgp works also.

Could you please update your template to the latest minor version? 78.2.1 is already out.

**Comment by mmnmnnmnmm** [comment]
Thanks for testing and for reminding me about the release.

**Comment by q66** [comment]
this update will mess up image colors on big endian systems (there have been changes in image loading code which results in things not being properly swizzled on BE, there is no patchset yet), not yet sure how important that is for email client (probably far less than for firefox itself)

**Comment by mmnmnnmnmm** [comment]
> this update will mess up image colors on big endian systems (there have
> been changes in image loading code which results in things not being
> properly swizzled on BE, there is no patchset yet)

Eh, that's annoying, is there a bug tracking this anywhere?

> not yet sure how important that is for email client (probably far less
> than for firefox itself)

I personally would take the security fixes with the caveat of broken
images, though I know a lot of people use html emails full of images.
But it's not my place to say, I don't even use void on BE.

**Comment by dkwo** [comment]
Thanks, I also built it on x86_64-musl and it works fine.
Would it be possible to update to 78.2.2?
My compile time on Intel i5-6300U (4) @ 3.000GHz with `XBPS_MAKEJOBS=4` in `etc/defaults.conf` was aournd 6h: is this normal or did I miss something?

**Comment by sgn** [comment]
> My compile time on Intel i5-6300U (4) @ 3.000GHz with `XBPS_MAKEJOBS=4` in `etc/defaults.conf` was aournd 6h: is this normal or did I miss something?

That's normal.

**Comment by ericonr** [comment]
78.3.1 seems to be available.

**Comment by pullmoll** [comment]
FWIW I already tried moving Icecat, which is basically firefox-esr + patches, but have trouble to get it to cross build.
The patches from 80.x can for the most part be used for 78.3.x as well.

**Comment by dkwo** [comment]
78.4.3 seems to be  available.
What are the conflicts that must be resolved?

**Comment by ericonr** [comment]
I'm working on 78.5.1, which might unfortunately depend on #26609

**Comment by ericonr** [comment]
I managed to build 78.5.1, will try cross now.

I believe the patches I posted in #26609 are necessary only when updating to 1.48, and the build might work just fine with 1.47, which is what we currently have.

**Comment by ericonr** [comment]
@mmnmnnmnmm do you remember why you removed system sqlite and bz2?

**Comment by mmnmnnmnmm** [comment]
On Thu, 03 Dec 2020 13:57:14 -0800
Érico Nogueira Rolim <notifications@github.com> wrote:

> @mmnmnnmnmm do you remember why you removed system sqlite and bz2?
> 

Mozilla removed support for using the system sqlite (https://bugzilla.mozilla.org/show_bug.cgi?id=1611386).

I don't remember why bz2 was disabled but I think it was broken as
well and you have to rely on the builtin one now too.


Also, thank you for picking this up Érico, I have been busy with work
lately and completely forgot about these pull requests!

**Comment by Piraty** [comment]
https://github.com/void-linux/void-packages/pull/26896

**Comment by ahesford** [comment]
Superseded by #26896

**Pull request closed without merging**
