### PR TITLE
libxkbcommon: update to 1.0.1.

### PR DESCRIPTION
**Pull request by dashezup**
btw I saw this and added libxkbregistry.so.0 to shlibs

`=> WARNING: libxkbcommon-1.0.1_1: libxkbregistry.so.0 not found in common/shlibs!`

Questions:

1. ~~Are those shlibs usually added when there are new ones are found like this, or add only when it's actually needed?~~
`libxkbregistry.so.0` is located at `/usr/lib/libxkbregistry.so.0`, I've added it to common/shlibs

2. ~~Should I add `shlib_provides="libxkbcommon.so.0 libxkbregistry.so.0"` and `shlib_provides="libxkbcommon-x11.so.0"` to package template? I also added it for now, ask me to remove them if it's not supposed to be added~~
I will keep it as before, `shlib_provides` is not added in this commit.

### CODE REVIEW

**Comment by ahesford** [comment]
`shlib_provides` is used to tell `xbps-src` about shared objects it doesn't automatically find, for example if a package keeps an unversioned file like `/usr/share/somelib/liblib.so` and you want to link other packages against that library. In this case, you should remove those lines.

As for `common/shlibs`, it doesn't *really* matter that libraries are included unless you want to link against them in another package. However, I'd say that, for consistency, if you have to have one of the libraries listed (which is the case here), you might as well include both. The exception is if the libraries are in some private directory like `/usr/lib/xkbcommon/libxkbregistry.so.0`, which will be picked up by `xbps-src` but are probably not intended for public consumption.

What dependants have you tested against this update? They claim API and ABI compatibility across the big version jump, but given the broad list of dependants, it would be good to do some sanity checks.

**Comment by dashezup** [comment]
@ahesford thanks i got it, see the message I edited. updated and rebased on lasted commit on master branch.
I've checked dependencies, all of dependencies listed are necessarily.

It builds fine here on x86_64-musl, armv7l-musl (cross) and aarch64-musl (cross).

tested sway and mpv (current build of package) both works fine with this version of libxkbcommon on x86_64-musl.

I didn't try to rebuild existing packages which requires libxkbcommon

**Comment by dashezup** [comment]
wait, I got this error while building wlroots `ERROR: wlroots-devel-0.11.0_2: failed to install 'MesaLib-devel-20.1.8_1' dependency! (error 40)`

could it be because of this?

**Comment by ahesford** [comment]
OK, I pushed some changes to your branch. The new `libxkbcommon` builds some command-line tools that, in your PR, added Wayland and X11 dependencies that caused the problem you observed. To get around this, I moved the tools into a new `libxkbcommon-tools` subpackage so these dependencies are not attached to the `libxkbcommon` base package. I have successfully built `wlroots`, `i3lock`, `wev`, `kitty` and `rofi` on `x86_64`. We should be OK now.

Finally, the xkbregistry library is optional and, since we obviously have nothing that depends on it, I've just disabled it during the build. We can enable it in a subsequent build if a package needs it.

If you accept these changes, let me know; I will squash and merge. Otherwise, feel free to make an alternative suggestion.

**Comment by dashezup** [comment]
Thanks that looks  good, I just tried to build `wlroots`, `dmenu-wayland`, `sway`, `wlroots`, `xdotools` `kitty` all of them builds successfully (x86_64-musl, and cross compile for armv7l-musl and aarch64-musl)
go ahead, squash and merge.

**Pull request closed without merging**
