### PR TITLE
unrar: update to 5.8.1

### PR DESCRIPTION
**Pull request by yopito**

### CODE REVIEW

**Comment by yopito** [comment]
no clue regarding non-SPDX license

**Comment by Chocimier** [comment]
> no clue regarding non-SPDX license

set `license="custom:freeware"`

**Comment by Duncaen** [comment]
Is this a stable/published release? On the website 5.80 is beta.

**Comment by yopito** [comment]
@Chocimier: thanks for pointing this. here the fix.

@Duncaen: yes, a little bit strange. Dit not found any announcement. but this PR is about unrar 5.8.1, not 5.8x

**Pull request merged**
