### PR TITLE
[WIP] srcpkgs: remove noarch for perl packages.

### PR DESCRIPTION
**Pull request by fosslinux**
[ci skip]

Very similar to the gem PR but this time for perl packages... next up is python2 packages.

### CODE REVIEW

**Comment by fosslinux** [comment]
Will be split into separate commits.

**Comment by q66** [comment]
sync with @leahneukirchen for perl update

**Comment by fosslinux** [comment]
Here, split into separate commits. Shall wait for @leahneukirchen 's input.

**Comment by sgn** [comment]
I suppose this is obsoleted?

**Comment by fosslinux** [comment]
Yes

**Pull request closed without merging**
