### PR TITLE
pinebookpro-uboot: fix date versioning

### PR DESCRIPTION
**Pull request by renatoaguiar**

### CODE REVIEW

**Comment by Duncaen** [comment]
This needs reverts for the previous versions except if you assume no one actually installed the packages yet.

**Comment by renatoaguiar** [comment]
> This needs reverts for the previous versions except if you assume no one actually installed the packages yet.

I think it is safe to assume no one installed it yet because full support for pinebookpro, e.g. pinebookpro-base, is not merged. If it is too late to change, I'll cancel this and fix it when there is a real update. Same for https://github.com/void-linux/void-packages/pull/19299.

**Comment by Duncaen** [comment]
I think its fine then, I think `xbps-rindex`/`xbps-src` doesn't need a revert to downgrade, only xbps to be able to consider the lower version as an update.

**Comment by renatoaguiar** [comment]
I'll fix the versioning with the next update.

**Pull request closed without merging**
