### PR TITLE
socat: enable openssl-method

### PR DESCRIPTION
**Pull request by paper42**

### CODE REVIEW

**Comment by ericonr** [comment]
@paper42 can you explain what this does in the commit message? I couldn't understand exactly.

**Comment by paper42** [comment]
Added to the commit message:

> allows users to specify the TLS/SSL protocol version

**Comment by Piraty** [comment]
```
$ grep -r -B3 openssl-method CHANGES
Porting:
        OpenSSL functions TLS1_client_method() and similar are 
        deprecated. Socat now uses recommended TLS_client_method(). The old
        functions and dependend option openssl-method can still be
        used when configuring socat with --enable-openssl-method
```
sounds like it's worth a build option (off by default)?

**Comment by Piraty** [comment]
ping @paper42

**Comment by paper42** [comment]
sorry for the delay, I made it an option disabled by default as suggested

**Comment by q66** [comment]
i don't really see a reason to add this

also, your option name does not follow conventions

**Comment by paper42** [comment]
At second thought, I don't think other people would benefit from this.

**Pull request closed without merging**
