### PR TITLE
linux4.19, linux4.20, linux, base-system: ppc64 support

### PR DESCRIPTION
**Pull request by q66**
This adds configs and some other fixes. ~~Base for config is from Ubuntu's kernel, with any options past 4.18 configured according to Void configs for other archs.~~ The kernels are custom configured, with Ubuntu ppc64le config as well as Void x86_64 config used for reference. The general featureset follows Void x86_64 fairly closely, except where platform differences do not allow us to do so; a notable difference is that the kernel uses `CONFIG_PREEMPT_VOLUNTARY` as well as a 250Hz timer instead of Void's `CONFIG_PREEMPT` and 1000Hz timer because 1) a `PREEMPT` kernel will not boot on my Talos 2 and 2) chances are these will be largely running on NUMA systems/server hardware, which makes this configuration make a lot more sense.

### CODE REVIEW

**Comment by q66** [comment]
I noticed that in some areas there are some differences between Void and Ubuntu choices. Any idea how to unify them?

**Comment by q66** [comment]
I will test them properly this weekend and if that works out they should be good enough to merge.

**Comment by q66** [comment]
Looks like I still need to fix a bunch of things in the configs before they can be merged.

**Comment by q66** [comment]
Finally got the configs down. This should be ready unless there is some concern about the template changes.

**Comment by Hoshpak** [comment]
lgtm. I tried to cross-compile for ppc64le but ended up with an error while stripping:

```
  DEPMOD  4.20.2_1
/usr/bin/strip: Unable to recognise the format of the input file `/destdir/powerpc64le-linux-gnu/linux4.20-4.20.2/boot/vmlinux-4.20.2_1'
```

Does stripping only work when running the native strip program compiled for the target architecture or is there a way around this? If ppc64 gets added as an officially architecture one day, it will most likely be cross-compiled from x86_64 so working cross-compilation is important.

**Comment by jnbr** [comment]
should use `/usr/bin/$STRIP` instead of hardcoded `/usr/bin/strip`

**Pull request merged**
