### PR TITLE
Manual: some git info to CONTRIB, explain how to use different branch…

### PR DESCRIPTION
**Pull request by ericonr**
… in PR.

Supersedes #23788, which was closed accidentally and can't be reopened. Still missing some of the corrections.

### CODE REVIEW

**Comment by Chocimier** [comment]
Will merge if you address last comments from #23788.

**Comment by the-maldridge** [comment]
@ericonr @Chocimier status?

**Comment by Chocimier** [comment]
Restored pr mention in manual and reordered ci mentions. @ericonr, are you ok with that?

**Comment by ericonr** [comment]
@Chocimier  Yup, feel free to merge. Thanks!

**Pull request merged**
