### PR TITLE
New package: utfcpp-4.0.5

### PR DESCRIPTION
**Pull request by NafzorOB**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - armv6l

### CODE REVIEW

**Comment by NafzorOB** [comment]
what does "authored by noreply email" and "subject does not follow CONTRIBUTING.md guildelines" exactly?

**Comment by Chocimier** [comment]
- Look at the CONTRIBUTING.md
- We usually do not accept libraries unless required by something else anyway.

**Comment by Chocimier** [comment]
Then close this and add utfcpp to the other PR, so it can pass checks.

**Comment by NafzorOB** [comment]
alright

**Pull request closed without merging**
