### PR TITLE
mupdf: update to 1.23.9

### PR DESCRIPTION
**Pull request by realcharmer**
- I tested the changes in this PR: **briefly**
- I built this PR locally for my native architecture, (x86_64)

### CODE REVIEW

**Comment by leahneukirchen** [comment]
You should bump all packages that statically link mupdf as well.

**Comment by realcharmer** [comment]
@leahneukirchen Thanks for the heads-up. All should be bumped now. Not sure if `cups-filters` needs to be bumped as well, since it has `mupdf-tools` in `hostmakedepends`.

**Comment by leahneukirchen** [comment]
Sorry, bumps should be their own commits.  You can use xrevbump to make them quickly.

**Comment by classabbyamp** [comment]
#48724

**Pull request closed without merging**
