### PR TITLE
android-studio: update to 4.0.1.0

### PR DESCRIPTION
**Pull request by Logarithmus**
Just update the version and nothing else

### CODE REVIEW

**Comment by ericonr** [comment]
commit message format is `android-studio: update to 4.0.1.0.`

**Comment by Logarithmus** [comment]
@ericonr I think now everything is fine

**Comment by ericonr** [comment]
It's showing https://redirector.gvt1.com/edgedl/android/studio/ide-zips/4.1.0.19/android-studio-ide-201.6858069-linux.tar.gz for me

**Comment by Logarithmus** [comment]
> It's showing   
> https://redirector.gvt1.com/edgedl/android/studio/ide-zips/4.1.0.19/android-studio-ide-201.6858069-linux.tar.gz
> for me

The latest version for now is 4.1. I guess I need to change the
template again, I hope I'll have time for that today

**Pull request closed without merging**
