### PR TITLE
Manual: added link to xtools' xbump

### PR DESCRIPTION
**Pull request by anjandev**

### CODE REVIEW

**Comment by Chocimier** [comment]
I would prefer to make this section shoter and point contributing.md.

**Comment by anjandev** [comment]
@Chocimier I agree. I think the contributing guide is much better at explaining everything and we should try not to repeat things in documentation. I have updated the PR with what I understood from what you said. Please provide feedback.

**Comment by Chocimier** [comment]
I don't meant to remove it all, because once one read and applied manual to template, submitting it is the capstone, so it is nice to have this described shortly here. For me removing commands from paragraph on committing, removing commit messages and pointing to contributing.md would be optimum.

**Comment by anjandev** [comment]
@Chocimier I made your requested changes.

**Comment by Chocimier** [comment]
Decreased indentation made github not recognize code blocks, so I made it back. Also reordered sections so they read better.

Thanks for your contribution!

**Pull request closed without merging**
