### PR TITLE
fakeroot: update to 1.25.3

### PR DESCRIPTION
**Pull request by unspecd**

### CODE REVIEW

**Comment by ev-ermakov** [comment]
Cross builds failed, I'm can't figure out what is wrong.

**Comment by ev-ermakov** [comment]
Passing `--with-ipc=tcp` to `./configure` makes the cross build succeed.

**Comment by Chocimier** [comment]
Cross build packages should be same as build natively on target platform. We have sysv ipc support, remove check at end of pre_configure.

**Comment by ericonr** [comment]
I think the homepage should be moved to https://salsa.debian.org/clint/fakeroot , what do you think?

**Comment by ev-ermakov** [comment]
@Chocimier
Hmm, what check do you mean? 

Anyway, I've created a patch that removes the check in the `configure.ac` script.

**Comment by the-maldridge** [comment]
Superseded by #26336 which adopts and therefore has priority.

**Pull request closed without merging**
