### PR TITLE
New package: helix-bin-22.03

### PR DESCRIPTION
**Pull request by shizonic**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by tranzystorek-io** [comment]
I think in this release we could realy easily build from the .tar.gz source, since the build process automatically fetches the grammar files, just as long as there is `hostmakedepens="git"`

**Comment by tranzystorek-io** [comment]
To clarify what I meant:

1. Switch from `helix-bin` to just `helix`
2. Use `build_style=cargo`
3. Switch the distfile to the `22.03.tar.gz` source package (instead of the prebuilt binary)
4. Keep the Rust patch to fix the source code
5. Allow targets other than `x86_64`, I just built it this way for i686 so it should be fine
6. Copy the built binary from `target/${RUST_TARGET}/release/` to `/usr/lib/helix/`
7. Remove the runtime/grammars/.gitkeep file

@paper42 Is automated fetching external files via git acceptable for source packages?

**Comment by leahneukirchen** [comment]
Ideally the git resources are pinned somehow, but it's acceptable.

**Comment by shizonic** [comment]
@tranzystorek-io Thanks for all you effort. Due to the fact, that I do not really use helix anymore I suggest that you become the package maintainer, make all the required changes and make a new PR. Would this be okay for you?

**Comment by tranzystorek-io** [comment]
@shizonic thanks for the heads up, gladly!

**Comment by shizonic** [comment]
@tranzystorek-io I started to make you changes here if you like to use it for you PR: https://github.com/shizonic/void-packages/commit/06ec0a1353673a819ed51af6ca5fe9b2cf8ba5a1

**Pull request closed without merging**
