### PR TITLE
build-style/perl-module: put . into @INC

### PR DESCRIPTION
**Pull request by sgn**

### CODE REVIEW

**Comment by sgn** [comment]
@pullmoll  this change fix those perl  build failure in your repo. I haven't thought about the cross compilation.

**Comment by leahneukirchen** [comment]
I think fixing those builds ala 5c920dac747 is better.

**Comment by leahneukirchen** [comment]
Alternatively we could pass `-I.`, it should not do harm here.

**Comment by sgn** [comment]
I guess you meant:
```diff
diff --git a/common/build-style/perl-module.sh b/common/build-style/perl-module.sh
index 8a4a432864..2611e0b8e0 100644
--- a/common/build-style/perl-module.sh
+++ b/common/build-style/perl-module.sh
@@ -45,7 +45,7 @@ do_configure() {
 			CFLAGS="$CFLAGS -I${XBPS_CROSS_BASE}/usr/include" \
 			LDFLAGS="$LDFLAGS -L${XBPS_CROSS_BASE}/usr/lib -lperl" \
 			LDDLFLAGS="-shared $CFLAGS -L${XBPS_CROSS_BASE}/usr/lib" \
-			perl Makefile.PL ${configure_args} INSTALLDIRS=vendor
+			perl -I. Makefile.PL ${configure_args} INSTALLDIRS=vendor
 	fi
 
 	for i in ${perl_configure_dirs}; do
@@ -57,7 +57,7 @@ do_configure() {
 				CFLAGS="$CFLAGS -I${XBPS_CROSS_BASE}/usr/include" \
 				LDFLAGS="$LDFLAGS -L${XBPS_CROSS_BASE}/usr/lib -lperl" \
 				LDDLFLAGS="-shared $CFLAGS -L${XBPS_CROSS_BASE}/usr/lib -lperl" \
-				perl Makefile.PL ${make_build_args} INSTALLDIRS=vendor
+				perl -I. Makefile.PL ${make_build_args} INSTALLDIRS=vendor
 		else
 			msg_error "*** ERROR: couldn't find $perlmkf, aborting **\n"
 		fi
```

**Pull request merged**
