### PR TITLE
lite-xl: Update to 2.1.1

### PR DESCRIPTION
**Pull request by Jocadbz**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)

### CODE REVIEW

**Comment by Jocadbz** [comment]
I fucked up on my commit name, it was supposed to be `v2.1.1`

**Comment by Jocadbz** [comment]
Closing this. Gonna redo.

**Comment by oreo639** [comment]
in the future, you should just use:
```
git commit --amend
git push -f
```
https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md

**Comment by Jocadbz** [comment]
I… I have no words.
I’m just gonna forgot that this happened and move on with my life.
Lesson learned I guess.

Em sáb., 21 de jan. de 2023 às 16:36, oreo639 ***@***.***>
escreveu:

**Pull request closed without merging**
