### PR TITLE
New package: xdg-desktop-portal-wlr-0.2.0

### PR DESCRIPTION
**Pull request by ifreund**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

Closes #23296

### CODE REVIEW

**Comment by paper42** [comment]
this PR closes #23296

**Comment by ericonr** [comment]
I managed to get it working for me, I had to select the output whose name was empty, instead of the "entire screen" option :/

I still have some slight reservations on it being considered pre-release by upstream. Can you explain their instance on this?

**Comment by ifreund** [comment]
@ericonr
```
10:21 <ifreund> emersion: what's the reasoning for xdg-desktop-portal-wlr being a pre-release? void doesn't usually accept projects marked as such into the repos: https://github.com/void-linux/void-packages/pull/28829#issuecomment-781047601
10:22 <ifreund> which is is a shame, because both chrome and firefox in the void repos are built with pipewire support now :)
10:23 <emersion> ifreund: i don't really understand. meson has version 0.57.0, is it in the repos?
10:23 <ifreund> xdpw 0.2.0 is listed as a pre-release by github here: https://github.com/emersion/xdg-desktop-portal-wlr/releases
10:24 <emersion> oh, the github thing? it's just something automatically done by my release script
10:25 <ifreund> does the script wait for 1.0 before marking it as a release? :D
10:25 <emersion> yea
10:25 <emersion> probably doesn't make a lot of sense
```

**Comment by st3r4g** [comment]
> I managed to get it working for me, I had to select the output whose name was empty, instead of the "entire screen" option :/

which browser is that? I remember this happened in an older firefox version but now it seems fixed

**Comment by ericonr** [comment]
I was on firefox 84, it's better on 85. Thanks for the reminder :)

**Pull request merged**
