### PR TITLE
ardour: add pulseaudio backend

### PR DESCRIPTION
**Pull request by krkk**

### CODE REVIEW

**Comment by krkk** [comment]
uhhh while the patch overall does its job, closing the app with this backend freezes itself, which isn't so great (x86_64-musl). :(

can be closed it if that isn't okay with you.

**Comment by ericonr** [comment]
>  closing the app with this backend freezes itself, which isn't so great (x86_64-musl).

Might be an issue with how it interacts with musl; PA has some design choices that may depend on glibc behaviors. Does it still freeze if you don't use the backend, and it's only been compiled in?

**Comment by krkk** [comment]
> Does it still freeze if you don't use the backend, and it's only been compiled in?

No, it doesn't freeze with alsa

**Comment by ericonr** [comment]
I guess when you have pulseaudio running and use the alsa backend, it runs alsa through pulse anyway? Which wouldn't have locking issues.

**Comment by ericonr** [comment]
If you think you should go on with the PR, please fix the download location to use https://github.com/Ardour/ardour/ ; they delete old tarballs.

**Comment by krkk** [comment]
> I guess when you have pulseaudio running and use the alsa backend, it runs alsa through pulse anyway? Which wouldn't have locking issues.

Well, running ardour with alsa backend does lock pulse at my machine.

> If you think you should go on with the PR, please fix the download location to use https://github.com/Ardour/ardour/ ; they delete old tarballs.

they also [exclude everything] from tarballs – the only thing that's shipped inside is [README-GITHUB.txt].

[exclude everything]: https://github.com/Ardour/ardour/blob/6.3/.gitattributes
[README-GITHUB.txt]: https://github.com/Ardour/ardour/blob/6.3/README-GITHUB.txt

**Comment by ericonr** [comment]
If you have an account in their bug tracker, could you complain about that? It'd be okay if they at least provided tarballs for all releases, but given that they remove old ones...

**Comment by krkk** [comment]
Sorry, I don't have an account there.

**Comment by ericonr** [comment]
No problem. If you still use the software, we can perhaps repurpose this PR to update it to 6.5 :) 

Otherwise, there's a chance the hang was caused by a very specific pattern, and might be solved in Musl 1.2.2. We can revisit enabling pulse then. Or you can make it an off by default build option.

**Comment by ericonr** [comment]
@krkk do you still have interest in pursuing this PR? I can send you a branch with newer musl for testing purposes, if you want.

**Comment by krkk** [comment]
I'm sorry, I don't. I no longer use musl and pulseaudio.

**Comment by ericonr** [comment]
No worries :)

**Pull request closed without merging**
