### PR TITLE
chromium: update to 80.0.3987.87.

### PR DESCRIPTION
**Pull request by mar1n3r0**
Hopefully should be resolving the frequent freezes experienced with 79.0.3945.130

### CODE REVIEW

**Comment by Hoshpak** [comment]
Has this been tested to compile on all the relevant architectures?

**Comment by pbui** [comment]
Simply bumping the version number is not sufficient.   A number of patches need to be removed, and a number of patches need to be added.  I have it building for x86_64, but not for i686 or x86_64-musl yet.

Additionally, upstream has dropped jumbo_build, so all that has to be removed as well.

**Comment by pbui** [comment]
Here is a link to my current work:

https://github.com/pbui/void-packages/commit/af892a730175c3d0fdf7bf67455700bdf9453f02

I hope to fix i686 and x86_64-musl this weekend.

**Comment by mar1n3r0** [comment]
@pbui Thanks didn't realize there is so much patching between versions.

**Comment by pbui** [comment]
@mar1n3r0 To be fair, only major releases require extensive patching.  Minor releases generally do not require much if any patching.  Usually each major release lasts about a month before the next one comes out and in between there are a few minor security releases.

**Comment by pbui** [comment]
@mar1n3r0  Can you checkout https://github.com/void-linux/void-packages/pull/18955 ?

**Pull request closed without merging**
