### PR TITLE
nushell: update to 0.68.0.

### PR DESCRIPTION
**Pull request by jcgruenhage**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by sgn** [comment]
curl and sqlite is bundled again? I think I unbundled them long time ago? unbundle curl is a must!!

**Comment by jcgruenhage** [comment]
@sgn can you show me where curl is being bundled? I can't even find curl in the nushell deps right now.

**Comment by sgn** [comment]
Hey, can you fix the unbundling again.

**Comment by jcgruenhage** [comment]
wdym? I've fixed it for sqlite afaict and am not aware of any other bundled libraries?

**Comment by jcgruenhage** [comment]
Yeah, so upstream has pushed to my branch (which github allowed bc of it being in a PR), so the commit was gone. I've changed it back to where it was before now, so the build should work now.

**Pull request merged**
