### PR TITLE
bat: update to 0.15.1

### PR DESCRIPTION
**Pull request by mustaqimM**

### CODE REVIEW

**Comment by ericonr** [comment]
Did this work fine when compiling locally for you?

**Comment by mustaqimM** [comment]
Ya, I'm using it currently

**Comment by mustaqimM** [comment]
sorry, I removed the repo, re-cloned and attempted to rebuild and it's also failing

**Comment by ericonr** [comment]
If you want to try to solve it, that'd be awesome! Leaving the PR open for that isn't an issue, you can put `[WIP]` in the title or make it a draft.

**Pull request closed without merging**
