### PR TITLE
vale update, style packages

### PR DESCRIPTION
**Pull request by paper42**
ping @SolitudeSF 

it does not build without this line, but I didn't find a better way to do it
```
go_import_path="."
```

### CODE REVIEW

**Comment by SolitudeSF** [comment]
i think `go_import_path="github.com/errata-ai/vale/v2"` shoud work but im not sure if that even matters

**Comment by paper42** [comment]
> go_import_path="github.com/errata-ai/vale/v2"

you were right, thanks

**Comment by ericonr** [comment]
Am I correct in assuming that `vale` by itself isn't very useful without at least one style package?

**Comment by paper42** [comment]
@ericonr I think so, but even if you install `vale` and one `vale-style` package, nothing will happen until you create a configuration file pointing it to /usr/share/vale. I would prefer it to get detected automatically, but vale doesn't load a system wide config file.

example config if you want to try it: `~/.vale.ini`
```
StylesPath = /usr/share/vale/

[*.md]
BasedOnStyles = write-good
```

**Comment by ericonr** [comment]
>  I would prefer it to get detected automatically, but vale doesn't load a system wide config file.

Might be nice to make a request for it :) at least so the user doesn't have to specify `StylesPath` themselves.

**Comment by ericonr** [comment]
Also, vale output shows

```
VERSION:  
   master 
```

maybe there is a build time flag to set this appropriately?

**Comment by ericonr** [comment]
https://github.com/errata-ai/vale/blob/430f6c8b4e6c00e2e50c0c0f4a3475f314db17ee/Makefile#L4 this is probably what you want. There are other templates doing similar things as well.

**Comment by paper42** [comment]
thanks, fixed the version

> > I would prefer it to get detected automatically, but vale doesn't load a system wide config file.
> 
> Might be nice to make a request for it :) at least so the user doesn't have to specify `StylesPath` themselves.

hmm, I do not think this is the correct solution anymore. If the user doesn't specify a config, no style should be used. I don't think all styles available in the system should be used. I will suggest to them a default StylesPath, but the user will still have to specify BasedOnStyles.

**Comment by ericonr** [comment]
> I will suggest to them a default StylesPath

Indeed, at least this.

**Comment by q66** [comment]
why don't the style packages depend on vale? now you can build the styles for targets which don't have vale at all (because they don't have go)

**Comment by ericonr** [comment]
I didn't consider in this case that vale itself wouldn't be available on all platforms. I guess I was thinking of packages like hunspell and aspell dicts, which don't depend on their respective tools. It probably makes more sense for them since they can be used by other packages, which isn't the case for the style packages. I think we can add a dependency, perhaps...

@paper42 what do you think?

**Comment by paper42** [comment]
The styles are "vale compatible" which means there can be other tools using them, but I don't know about any.

**Comment by q66** [comment]
well, if the styles don't necessarily require the original thing, it's probably okay to just leave it

**Pull request merged**
