### PR TITLE
qemu: Fix padding in host_sigevent

### PR DESCRIPTION
**Pull request by ismaell**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ismaell** [comment]
Patch may not be relevant anymore.

**Comment by ismaell** [comment]
The patch breaks with musl 1.2.2.

**Comment by ericonr** [comment]
Please include more context in the commit message. Was the original patch wrong and we failed to detect it with our version of musl, but it appears in musl 1.2.2? What did you use for reference for the patch?

**Comment by ismaell** [comment]
@ericonr yes, the patch is wrong in that it makes the struct much larger than necessary, it should be 64 bytes.

OTOH, it won't build  with musl 1.2.2, because introduces the missing API using different names for the struct fields.

**Comment by ismaell** [comment]
@ericonr I've added some description of the issue to the commit message.

**Comment by ericonr** [comment]
Can we use musl's stuff instead, but renamed appropriately? I think it's clearer and has known provenance.

```
	union {
		char __pad[64 - 2*sizeof(int) - sizeof(union sigval)];
		pid_t sigev_notify_thread_id;
		struct {
			void (*sigev_notify_function)(union sigval);
			pthread_attr_t *sigev_notify_attributes;
		} __sev_thread;
	} __sev_fields;
```

**Comment by ericonr** [comment]
> OTOH, it won't build with musl 1.2.2, because introduces the missing API using different names for the struct fields.

feel free to add a comment to the patch that mentions it should be removed when we update musl.

**Comment by ismaell** [comment]
Done :smile:.

**Comment by ericonr** [comment]
I think you still forgot to revbump the template? Otherwise it won't be rebuilt with this change...

**Comment by ismaell** [comment]
On 18/Sep/2021 20:08, Érico Nogueira Rolim wrote:
> I think you still forgot to revbump the template? Otherwise it won't be rebuilt with this change...

Fixed. Thanks.

**Pull request merged**
