### PR TITLE
New package: python3-SQLAlchemy-Utils-0.36.1

### PR DESCRIPTION
**Pull request by misuchiru03**

### CODE REVIEW

**Comment by Chocimier** [comment]
depends on sqlalchemy, six, and maybe more.

**Comment by misuchiru03** [comment]
`aarch64-musl` and `armv6l-musl` built fine on my box.

**Comment by Chocimier** [comment]
- tests fail, same for total-ordering, please find broken one or define it like 

      do_check() {
             cd build/lib
             python3 -c 'import sqlalchemy_utils as m; print(m)'
      }

- python3-pymysql is a typo
- anyjson-0.3.3 is not python3 compatible
- every module should depend on either another module or interpreter
- add `makedepends="python3-devel"` in pendulum for compiled part
- check phase of pendulum is broken, please fix eg. by importing instead (in build/lib*)
- check phase of PyMySQL fail because of not packaged check dependency, please package or fix another way
- license fetching is better with 

      distfiles="${PYPI_SITE}/t/total_ordering/total-ordering-${version}.tar.gz
       https://raw.githubusercontent.com/kvesteri/total-ordering/1128e3749/LICENSE"
      checksum="a14a2a138a52befaa02b3fd53eb3366f66da69020be299af3cf0b54c9441aacc
       68aa51bd60ab3a6a3e826d91c81d8a8603f816d1bab535a2ff18bf7d69aa9b0a"
      skip_extraction="LICENSE"
 
      post_install() {
            vlicense "${XBPS_SRCDISTDIR}/${pkgname}-${version}/LICENSE"
      }

- `checkdepends="${depends} ..."` helps to pass tests sometimes

**Comment by misuchiru03** [comment]
Good deal. Made some fixes, looking through the rest of the templates.

**Comment by misuchiru03** [comment]
`anyjson` seems to work fine for python3.

**Comment by Chocimier** [comment]
> `anyjson` seems to work fine for python3.

Oh, it is written for py2, then uses `use_2to3` in install phase but not test phase. Ok.

**Comment by ericonr** [comment]
ping @Chocimier

**Comment by Chocimier** [comment]
Anyjson py3 compatibility is not an issue, but rest of them still holds.

ping @misuchiru03

**Comment by ericonr** [comment]
There is another PR in #25067

**Pull request closed without merging**
