### PR TITLE
rsyslog: update to 8.2110.0.

### PR DESCRIPTION
**Pull request by baal-zebub**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by baal-zebub** [comment]
Unfortunately I don't have a slightest clue why the tests failed, reaching out to upstream for help: https://github.com/rsyslog/rsyslog/issues/4619

**Comment by zdykstra** [comment]
The last time I built rsyslog there were a random number of failing tests as well. 

https://github.com/void-linux/void-packages/pull/30883

**Comment by baal-zebub** [comment]
Yep, I dug through previous PRs for rsyslog and it seems to be a persisting issue since 8.2012.

Thanks for providing extensive information and basically handling https://github.com/rsyslog/rsyslog/issues/4619, honestly I thought it would be just an easy version bump and didn't expect such problems :D

**Comment by zdykstra** [comment]
Add `checkdepends="procps-ng"` and the entire test suite should execute correctly.

**Comment by baal-zebub** [comment]
Hmm, I've pushed it and started tests on my computer (x86_64-glibc) and it looks like some are still failing, roughly those that had been previously.

**Comment by zdykstra** [comment]
> Hmm, I've pushed it and started tests on my computer (x86_64-glibc) and it looks like some are still failing, roughly those that had been previously. Same with the CI build it seems.

I misspoke, it looks like both `procps-ng` and `gdb` should be in checkdepends. With out `gdb`, I get the same test failures - with it, 477/488 pass, 11 are skipped. Can you confirm that on your end?

**Comment by baal-zebub** [comment]
Unfortunately 6 of those 488 tests still failed for me in single run after setting `checkdepends="gdb procps-ng"`, will check tomorrow if it's reproducible.

**Comment by zdykstra** [comment]
> Unfortunately 6 of those 488 tests still failed for me in single run after setting `checkdepends="gdb procps-ng"`, will check tomorrow if it's reproducible.

Do you have the list of the 6 tests that failed? Are you building locally on musl or glibc ?

**Comment by baal-zebub** [comment]
> Do you have the list of the 6 tests that failed?

- omfwd-keepalive
- msgdup
- imuxsock_legacy
- imuxsock_logger
- imuxsock_logger_parserchain
- imuxsock_logger_syssock

> Are you building locally on musl or glibc ?

 x86_64 with glibc.

**Comment by zdykstra** [comment]
> > Do you have the list of the 6 tests that failed?
> 
> * omfwd-keepalive
> * msgdup
> * imuxsock_legacy
> * imuxsock_logger
> * imuxsock_logger_parserchain
> * imuxsock_logger_syssock
> 
> > Are you building locally on musl or glibc ?
> 
> x86_64 with glibc.

I just checked this again on my end, and all of the tests that you've listed are marked as PASS for me with `checkdepends="procps-ng gdb"`. Can you try pushing that change to CI so we can see what happens here?

**Comment by ericonr** [comment]
On x86_64-musl, I see:

- FAIL: omfile-outchannel.sh

**Comment by baal-zebub** [comment]
Here it is, could it be that the order of `checkdepends` matters? Haven't got the time yet to check with `checkdepends="procps-ng gdb"` locally.

**Comment by baal-zebub** [comment]
I've got back to it and now I see that all the tests fail on my machine because the following message is prepended to each, otherwise identical to expected, output (`event-horizon` is my hostname):
```
getaddrinfo failed obtaining local hostname - using 'event-horizon' instead; error: No address associated with hostname [v8.2106.0]
```

I don't know how to fix it and can't find anything on the internet about it. Maybe the checks failed for the same reason? Can we access the test log there?

**Comment by ericonr** [comment]
> Maybe the checks here failed for the same reason? Can we access the test log?

Only locally on your own machine. See `masterdir/builddir/...`

Have you tried asking upstream about this? They should know well what their tests require or not...

**Comment by baal-zebub** [comment]
Posted about at https://github.com/rsyslog/rsyslog/issues/4619

**Comment by ericonr** [comment]
```
2021-11-06T12:00:27.1180169Z FAIL: omfile-read-only-errmsg.sh
2021-11-06T12:00:28.2867822Z PASS: omfile-null-filename.sh
2021-11-06T12:00:29.4602776Z PASS: omfile-whitespace-filename.sh
2021-11-06T12:00:30.6629316Z FAIL: omfile-read-only.sh
```

These also look like tests that would fail as root. Please report to upstream.

**Pull request merged**
