### PR TITLE
virt-manager: update to 4.0.0

### PR DESCRIPTION
**Pull request by zen0bit**
#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by zen0bit** [comment]
not yet builded..

ERROR: libxml2-2.9.13_1: failed to install target dependencies! (ERROR 19)
ncurses-libs-6.2_4 in transaction breaks installed pkg `ncurses-6.3_1'
Transaction aborted due to unresolved dependencies.

It will break base-system

**Comment by MouadCharradi** [comment]
Apparently the problem seems to be related to the package `libvirt`, I think we should make the appropriate changes to that package to try to make it pass the tests provided with `virt-manager`.

**Comment by paper42** [comment]
set `make_install_args="--no-compile-schemas --no-update-icon-cache"`

**Comment by zen0bit** [comment]
> Apparently the problem seems to be related to the package `libvirt`, I think we should make the appropriate changes to that package to try to make it pass the tests provided with `virt-manager`.

I will need help with that :heart:

**Pull request closed without merging**
