### PR TITLE
New package: harvid-0.8.3

### LINKED ISSUE #33382: Package Request: harvid
Needed to play video in Ardour

### PR DESCRIPTION
**Pull request by notthewave**
closes #33382 
Ardour http video daemon

#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
I would use this package on a regular basis, but I'm on musl and have trouble patching. 
Compiles on glibc but I can't test.
 
#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (ARCH-LIBC)
- [x] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [x] x86_64-glibc
  - [x] aarch64-musl
  - [ ] armv6l-musl

### CODE REVIEW

**Comment by notthewave** [comment]
Error output is different on my local copy of void-packages.

**Comment by notthewave** [comment]
Not sure why this fails again. Builds just fine on my system with xbps-src.

**Comment by notthewave** [comment]
To make the video thing work in Ardour one also needs xjadeo. Shall I add it to this PR? Or make a seperate one?

**Comment by TinfoilSubmarine** [comment]
I think it should be added to this PR as a separate commit.

**Comment by TinfoilSubmarine** [comment]
Confirmed on a PR staged against my fork: https://github.com/TinfoilSubmarine/void-packages/pull/1 and https://github.com/TinfoilSubmarine/void-packages/pull/4

Only difference between 1 and 4 is that 1 additionally added the 3 packages I mentioned above to hostmakedepends. 4 proves that those are unneeded and the real fix is adding `disable_parallel_build=yes`.

**Comment by notthewave** [comment]
Now onto xjadeo. I had no luck when installing the static binary in `/usr/bin`. When launching it from said directory, it complained about not finding a display, but when I ran it with `./`, it popped up. 

I hope this does not happen when installed with xbps but well see...

**Comment by notthewave** [comment]
Again, different error output.

**Comment by notthewave** [comment]
```
checking whether struct tm is in sys/time.h or time.h... time.h
./configure: line 6429: syntax error near unexpected token `JACK,'
./configure: line 6429: `PKG_CHECK_MODULES(JACK, jack, ,'
```

**Comment by notthewave** [comment]
Do you use a X windowmanager/desktop env.? 
On sway Wayland it reports:
```
Could not open video output.
Could not open display.
```

**Comment by TinfoilSubmarine** [comment]
@notthewave I spun up a x86_64-musl void install and tested, it's working for me. Looks like it might be a system issue/configuration unique to you.

**Comment by notthewave** [comment]
might have to setup my sytem anew because there seem to be multiple configuration issues. Maybe something is corrupted.

**Comment by notthewave** [comment]
Alright, I found the issue. Had it installed in /usr/bin/local before packaging and that caused the problem. Now works without issue.

**Comment by notthewave** [comment]
Ardour crashes when adjusting the bottom timeline view with harvid activated.
To an extent that ardour (without tinkering) does not open the file anymore.

**Pull request closed without merging**
