### PR TITLE
telegraf: update to 1.18.3

### PR DESCRIPTION
**Pull request by damadmai**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by damadmai** [comment]
Building without `dep` worked just fine.

**Comment by ericonr** [comment]
Besides segfaulting the compiler for ARM targets, looks good:

```
 /usr/lib/go/pkg/tool/linux_amd64/link -o $WORK/b001/exe/a.out -importcfg $WORK/b001/importcfg.link -buildmode=exe -buildid=s9-UTy9Bz5UB1geuAmIY/hP_SdF5FK7RIvyEpJIjN/FIOn9d4r6AmbA-W9Gigd/s9-UTy9Bz5UB1geuAmIY -X main.version=1.18.3 -extld=armv7l-linux-gnueabihf-gcc $WORK/b001/_pkg_.a
# github.com/influxdata/telegraf/cmd/telegraf
net(.text): direct call too far: .plt a6878e
net(.text): direct call too far: .plt a68783
net(.text): direct call too far: .plt a6876a
net(.text): direct call too far: .plt a6875b
net(.text): direct call too far: .plt a68759
net(.text): direct call too far: .plt a68752
net(.text): direct call too far: .plt a6874f
net(.text): direct call too far: .plt a6873a
runtime/cgo(.text): direct call too far: .plt a68728
runtime/cgo(.text): direct call too far: .plt a68726
runtime/cgo(.text): direct call too far: .plt a68726
runtime/cgo(.text): direct call too far: .plt a68728
runtime/cgo(.text): direct call too far: .plt a68719
runtime/cgo(.text): direct call too far: .plt a68715
runtime/cgo(.text): direct call too far: .plt a68711
runtime/cgo(.text): direct call too far: .plt a68700
runtime/cgo(.text): direct call too far: .plt a686ed
runtime/cgo(.text): direct call too far: .plt a686f5
runtime/cgo(.text): direct call too far: .plt a686ec
runtime/cgo(.text): direct call too far: .plt a686df
runtime/cgo(.text): direct call too far: .plt a686e1
/usr/lib/go/pkg/tool/linux_amd64/link: too many errors
unexpected fault address 0x7f8905077000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f8905077000 pc=0x46dde1]
```

@the-maldridge looks ok?

**Comment by ericonr** [comment]
Just merged a Go update that carries this commit https://github.com/golang/go/commit/305fa952c23b67e03a21d30318b945fddb2f3916, maybe try again?

**Comment by damadmai** [comment]
I just pushed again, but it still did not compile successfully.

**Pull request closed without merging**
