### PR TITLE
[WIP] Python 3.8

### PR DESCRIPTION
**Pull request by leahneukirchen**
This huge PR tries to bump all packages that either shlib-require
libpython3.6m.so.1.0 or put files into /usr/lib/python3.6/site-packages.

Broken packages (on x86_64):

- [x] ~~attic~~ -> upstream dead, remove?
- [x] blender -> update to 2.80
- [x] eolie -> meson
- [x] fontforge
- [x] freecad
- [x] gst1-python -> meson
- [x] libopenshot -> gcc9 issue, but supposedly fixed? @Spencer-H 
- [x] libpeas
- [x] nagstamon
- [x] paraview
- [x] pockyt
- [x] ~~scudcloud~~
- [x] torbrowser-launcher
- [x] unknown-horizons
- [x] vapoursynth
- [x] variety
- [ ] kdevelop-python -> upstream: https://bugs.kde.org/show_bug.cgi?id=411956 wait for 5.5
- [x] krita: SHA256 mismatch
- [x] ~~shiboken~~
- [x] renderdoc

Untested:

- [ ] libreoffice

### CODE REVIEW

**Comment by CameronNemo** [comment]
Travis is not going to like this.

**Comment by q66** [comment]
Nothing is going to like this :P

**Comment by jnbr** [comment]
patch for paraview: https://github.com/jnbr/void-packages/commit/b17c111d8c3ddd277ed442c9bae5978981e0cb50

**Comment by leahneukirchen** [comment]
Did it with sed already 🙈

**Comment by jnbr** [comment]
libreoffice needs a similar patch: https://cgit.freedesktop.org/libreoffice/core/patch/pyuno?id=2bd585f31d7abb066e3f53d9b29c822af20aea69

**Comment by jcgruenhage** [comment]
>     * attic -> upstream dead, remove?

I'd say so, yes. I'd assume everyone has moved onto borgbackup (fork/successor of attic) by now, and if they haven't, removing attic might remind them to do so.

**Comment by leahneukirchen** [comment]
Still annoying to remove software to access old backups.

But worst case, people could rebuild it for 2.7.

**Comment by faulesocke** [comment]
I just rebased this locally and currently try to build libreoffice. What else is missing to get this going?

**Comment by leahneukirchen** [comment]
Dealing with the meson packages is still not resolved.

Perhaps we should also wait for Python 3.8.1.

**Comment by leahneukirchen** [comment]
Ok, all fixed but kdevelop-python.

**Comment by Johnnynator** [comment]
https://cgit.kde.org/kdev-python.git/patch/?id=e23fa8f15af89a8bd4bd84dd96b5fd7017457516 this should get kdevelo-python working (currently compiling it locally)

**Comment by leahneukirchen** [comment]
That didn't apply on 5.4 here even.

**Comment by Johnnynator** [comment]
> That didn't apply on 5.4 here even.

Well, it applies fine here after changing the prefixes of the patch.

**Comment by obunden** [comment]
I was trying to upgrade blender and noticed the python 3.7 requirement. I'm glad that python will get an update to fix it. I added a couple of comments on the blender diff btw, don't know if they are of any use. Is libreoffice the only showstopper now?

**Pull request closed without merging**
