### PR TITLE
linux-firmware: update to 20221109

### PR DESCRIPTION
**Pull request by absrd**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by ericonr** [comment]
Am going to reboot into this soon.

MIght be worth removing `linux-firmware-dvb` from the repositories.

**Comment by dataCobra** [comment]
@paper42, could you delete the `stale` label please?

**Comment by dataCobra** [comment]
I've finally successful tested this PR on 3 different systems.

I've also created a PR https://github.com/void-linux/void-packages/pull/38683 to get rid of the conflicts between the two packages.
-> (linux-firmware-dvb: remove conflicts with official linux-firmware)

**Comment by dataCobra** [comment]
Hey @absrd,

`linux-firmware` is now on version `20220815`. Could you update the PR?

**Comment by absrd** [comment]
@dataCobra Done!

**Comment by dataCobra** [comment]
Thank you :)

**Comment by dataCobra** [comment]
Hey @classabbyamp,

it seems like @ericonr is currently not available.

I use this firmware version successful on three different physical machines.

I've also create PR https://github.com/void-linux/void-packages/pull/38683 to make sure the conflicts are fixed.

**Comment by dataCobra** [comment]
Hey @ericonr,

do we miss something here or can we go forward with merging PR #38683 to remove the conflicts
and then merge this PR also?

**Comment by absrd** [comment]
Updated to 20220913

**Comment by dataCobra** [comment]
@absrd and myself are still waiting for further information regarding this PR.

If something does still need work, let @absrd or me know. We just want this PR merged.
Since we're still on linux-firmware 20220411.

PR #38683 is created to fix the conflicts with linux-firmware-dvb.

**Comment by dataCobra** [comment]
Yesterday was the release of 20221012. Which has several updates and new firmware.

**Comment by absrd** [comment]
Updated to 20221012

**Comment by vitezfh** [comment]
I was also wondering why we're stuck on old firmware. I'm currently running the new firmware you graciously updated and all is well. 3 systems here too.

**Comment by absrd** [comment]
Rebased on to latest master and updated to 20221109

**Comment by dataCobra** [comment]
> Rebased on to latest master and updated to 20221109

Hey @absrd, could you force push again please?

**Comment by the-maldridge** [comment]
Conflicts in the linked PR have been cleared, please rebase @absrd .

**Comment by classabbyamp** [comment]
also add "fixes #40674" to the commit body

**Comment by JamiKettunen** [comment]
Hm wonder what's up with CI, #38683 should've fixed those `linux-firmware` and `linux-firmware-dvb` conflicts, maybe another rebase/force-push would fix it?

**Comment by classabbyamp** [comment]
> maybe another rebase/force-push would fix it?

no, the new version of `linux-firmware-dvb` just hasn't been indexed by `xlocate` yet.

e.g.:
```sh
$ xlocate -S
$ xlocate as102 | grep firmware   
linux-firmware-20220411_1      /usr/lib/firmware/as102_data1_st.hex
linux-firmware-20220411_1      /usr/lib/firmware/as102_data2_st.hex
linux-firmware-dvb-20170329_4  /usr/lib/firmware/as102_data1_st.hex
linux-firmware-dvb-20170329_4  /usr/lib/firmware/as102_data2_st.hex
linux-firmware-dvb-20170329_4  /usr/share/licenses/linux-firmware-dvb/README.as102
```

**Comment by dataCobra** [comment]
Hey @absrd, could you now force-push again? The indexing seems to be finished.

Also please don't forget to add "fixes #40674" to the body. :+1:

**Comment by classabbyamp** [comment]
image
it's there

**Comment by dataCobra** [comment]
It does seem like the branch should be rebased with master before a new push?

**Comment by classabbyamp** [comment]
no, that shouldn't matter. and xlocate hasn't updated yet from what I see

**Comment by dataCobra** [comment]
> no, that shouldn't matter. and xlocate hasn't updated yet from what I see

Interesting, mine is updated.
```
[datacobra@sourcerer ~]$ xlocate as102 | grep linux-firmware
linux-firmware-20220411_1       /usr/lib/firmware/as102_data1_st.hex
linux-firmware-20220411_1       /usr/lib/firmware/as102_data2_st.hex
linux-firmware-dvb-20170329_5   /usr/share/licenses/linux-firmware-dvb/README.as102
```

**Comment by dataCobra** [comment]
Do get rid of the no longer needed license files I've created a new PR. :+1:

**Comment by dataCobra** [comment]
How long does it take for xlocate to recognise the changes?

**Pull request merged**
