### PR TITLE
delta: update to 0.1.1

### PR DESCRIPTION
**Pull request by imbsky**

### CODE REVIEW

**Comment by ericonr** [comment]
I think you might need to add clang to makedepends.

**Comment by ericonr** [comment]
Or possibly add oniguruma as a dependency (I wonder if this would work for `bat` as well).

**Comment by imbsky** [comment]
Oh thanks for your advice.

**Comment by ericonr** [comment]
Could you take a look at the template for `bat`? It has some useful info. It does link with oniguruma, but uses `libonig.a` instead.

**Comment by imbsky** [comment]
@ericonr Finally, the build passed. Thanks again.

**Comment by ericonr** [comment]
@imbsky cool! It still required `clang` and `llvm` to work?

**Comment by imbsky** [comment]
Probably yes.

```console
error: failed to run custom build command for `onig_sys v69.2.0`
Caused by:
  process didn't exit successfully: `/builddir/delta-0.1.1/target/release/build/onig_sys-10237aa0f829094d/build-script-build` (exit code: 101)
--- stdout
cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
cargo:warning=set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable
--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /host/cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.50.1/src/lib.rs:1711:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ericonr** [comment]
That's weird, but ok. Just wondering why @abenson's version didn't need llvm, only clang. I do think it's best to depend on our own version of oniguruma, which yours does. Thanks for testing c:

**Pull request merged**
