### PR TITLE
profanity: update to 0.12.1. libstrophe: update to 0.12.0.

### PR DESCRIPTION
**Pull request by mhmdanas**
I got this warning when I ran `./xbps-src pkg profanity`, not sure if it's
important:

```
=> WARNING: profanity-0.12.1_1: libprofanity.so.0 not found in common/shlibs!
```

#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by classabbyamp** [comment]
> I got this warning

it's fine to ignore if no other package needs libprofanity

**Comment by mhmdanas** [comment]
It doesn't seem like any other package depends on libprofanity, according to my quick `grep` search.

**Comment by paper42** [comment]
> It doesn't seem like any other package depends on libprofanity, according to my quick `grep` search.

If it did, it would have to be already added to shlibs, so you don't have to care about it.

**Comment by paper42** [comment]
```diff
%: xpkgdiff -x profanity
--- /tmp/xpkgdiff.WS87U/profanity.repo	2022-04-25 16:25:30.834045647 +0200
+++ /tmp/xpkgdiff.WS87U/profanity.local	2022-04-25 16:25:30.839045662 +0200
@@ -1,8 +1,6 @@
-glib>=2.70.0_1
+glib>=2.72.0_1
 glibc>=2.32_1
 gtk+3>=3.0.0_1
-libX11>=1.2_1
-libXScrnSaver>=1.1.3_1
 libcurl>=7.75.0_2
 libgcrypt>=1.6.1_1
 libgpgme>=1.12.0_2
```
It seems like the xscreensaver option doesn't work anymore. And we should replace gtk+-devel with gtk+3-devel.

**Comment by mhmdanas** [comment]
> It seems like the xscreensaver option doesn't work anymore.

That sounds like https://github.com/profanity-im/profanity/issues/1695.

> And we should replace gtk+-devel with gtk+3-devel.

Sure.

**Pull request merged**
