### PR TITLE
New package: CBQN-git-20230503

### PR DESCRIPTION
**Pull request by BryceVandegrift**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86_64-musl (crossbuild)

### CODE REVIEW

**Comment by classabbyamp** [comment]
> Software need to be used in version announced by authors as ready to use by the general public - usually called releases. Betas, arbitrary VCS revisions, templates using tip of development branch taken at build time and releases created by the package maintainer won't be accepted.

[Package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements)

**Comment by BryceVandegrift** [comment]
Software does not provide suitable releases.

**Comment by abenson** [comment]
[It does have tagged releases](https://github.com/dzaima/CBQN/releases/tag/v0.2.0).

**Comment by BryceVandegrift** [comment]
@abenson Those tagged releases will not compile. The author does not support them.
[https://github.com/dzaima/CBQN/issues/79](https://github.com/dzaima/CBQN/issues/79)

**Comment by abenson** [comment]
You'd need to grab the modules as `distfiles` and put them in place.

```
_singeli_hash=853ab1a06ae8d8603f228d8e784fa319cc401459
_replxx_hash=1da4681a8814366ec51e7630b76558e53be0997d
_bytecode_hash=78ed4102f914eb5fa490d76d4dcd4f8be6e53417
distfiles="https://github.com/dzaima/CBQN/archive/v${version}.tar.gz
 https://github.com/mlochbaum/Singeli/archive/${_singeli_hash}.tar.gz
 https://github.com/dzaima/replxx/archive/${_replxx_hash}.tar.gz
 https://github.com/dzaima/cbqnBytecode/archive/${_bytecode_hash}.tar.gz"
checksum="70525117364edefb6c8906e269a5b1b17c8647f516b6599fecdc53ba6e57530e
 a0a8b48aac23bfa458c3af13cfcad1fb6889151e72b7983e85521245e367c1d4
 60ba4d8b566d8af1330f2f4b67d712da8efeb018f53f5055898d8b86a325088f
 f99c10fc674e673bd8253a90e9676d070aadb4decc3f59766bed3b0295f47a1a"

post_extract() {
    rm -r CBQN-${version}/build/{bytecode,replxx,singeli}Submodule
    mv "cbqnBytecode-${_bytecode_hash}" "CBQN-${version}/build/bytecodeSubmodule"     
    mv "replxx-${_replxx_hash}" "CBQN-${version}/build/replxxSubmodule"
    mv "Singeli-${_singeli_hash}" "CBQN-${version}/build/singeliSubmodule"
    cd $build_wrksrc
    vsed -i makefile -e 's/@git/@true/g'
}
```

**Comment by BryceVandegrift** [comment]
Yeah, I guess that could work. I'll see what I can do.

**Pull request closed without merging**
