### PR TITLE
straw-viewer: add missing dependency

### PR DESCRIPTION
**Pull request by PaperMountainStudio**
perl-Term-ReadLine-Gnu is needed for interactive input

### CODE REVIEW

**Comment by ericonr** [comment]
I couldn't reproduce it. Is launching `straw-viewer` enough?

**Comment by PaperMountainStudio** [comment]
Yes, I just typed `straw-viewer`. It should ask for user input, but it crashed, because this package was missing.

**Comment by PaperMountainStudio** [comment]
This works when I delete my config file, but when I put `history => 1,` in it, this error happens:
```
Can't locate object method "history_list" via package "Term::ReadLine::Stub" at /bin/straw-viewer line 583.
```
This PR fixes it.

**Comment by PaperMountainStudio** [comment]
@ericonr can you reproduce it now? I think it's good to go.

**Comment by ericonr** [comment]
Could reproduce. Would you mind adding this depedency for `youtube-viewer` as well?

**Comment by PaperMountainStudio** [comment]
done

**Comment by ericonr** [comment]
Sorry for the delay, merging!

**Pull request merged**
