### PR TITLE
openexr3.0 update

### PR DESCRIPTION
**Pull request by motorto**
[ci-skip] [ci skip]

# TODO:

- **Review**. (If someone could do a rebuild of everything changed here would be highly appreciated, I am currently
leaving my laptop overnight compiling everything with xxbuild for a specific arch, see below what I have already tested, getting some crossbuilding testing would be nice)

## New Templates

- robin-map 1.0.1
- pystring 1.1.3

## Changed Templates:

- alembic 1.7.16 --> 1.8.3 (adopt)
- ilmbase --> imath 3.1.5
- openexr 2.4.1 --> 3.1.5 (adopt)
- gmic 2.9.9 --> 3.1.6
- opencolorio 1.1.1 --> 2.1.2
- openimageio 2.2.15.1 --> 2.3.18.0.

## Revbumped (xrevshlib)

- Field3D
- ImageMagick
- PrusaSlicer
- blender
- calligra
- darktable
- gimp
- hugin
- kimageformats
- kio-extras
- krita
- libgdal
- opencv
- openvdb
- osg
- synfig
- synfigstudio
- vigra
- vips

## Local build testing
- x86_64  (native)
- x86_64-musl (native) 
- i686 (native)
- armv6l (cross)

### CODE REVIEW

**Comment by motorto** [comment]
Need some help with making gmic build with openexr3.0 (and without the ilmbase package).

Inspired myself on the fedora patch: https://src.fedoraproject.org/rpms/gmic/raw/rawhide/f/gmic-openexr3.patch

But it fails and I am not familiarized enough with the package. logs:  https://paste.rs/7MP

Here is my current "patch" (not working). https://paste.rs/HSS

**Comment by motorto** [comment]
@lemmi can you help with the openimageio update ?

**Comment by lemmi** [comment]
Just this week I also tried to update `opencolorio` and `openimageio`.. but oh boy... I gave up. After that I had a quick look at what the arch guys were doing and I was kind of close with my approach, so I was kind of on the right track. I'd start looking there.

**Comment by Johnnynator** [comment]
You should find most needed bits an pieces in my branch here: https://github.com/Johnnynator/void-packages/tree/updates
Only thing I didn't fix was gmic-krita

**Comment by motorto** [comment]
Ok so having some free time this days so going back to work on this, merged master and I am on the process of building again for x86-64-glibc/musl, i686 and armv6l (cross). Just to check that everything works as I left it, aka the only issue is with PrusaSlice cross compilation failling

**Comment by Johnnynator** [comment]
I (force) pushed some changes to your branch:

- Readded some revbumps that got lost while rebasing
- removed cereal.patch from PrusaSlicer (was already added in the boost revbump with a different name)
- Properly removed ilmbase (there was still a reference in common/shlibs before)

**Comment by motorto** [comment]
> I (force) pushed some changes to your branch:
> 
>     * Readded some revbumps that got lost while rebasing
> 
>     * removed cereal.patch from PrusaSlicer (was already added in the boost revbump with a different name)
> 
>     * Properly removed ilmbase (there was still a reference in common/shlibs before)

Glad you noticed that issue with the ilmbase shlibs it completely passed me by. 

Thanks for taking the time to review this huge pr.

**Pull request merged**
