### PR TITLE
pulseaudio: update to 16.1.

### PR DESCRIPTION
**Pull request by motorto**
[ci skip]

#### Testing the changes
- I tested the changes in this PR: **briefly**, please test this more users, I am a pipewire user, don't know if pulseaudio standalone is working :) 

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc

### CODE REVIEW

**Comment by mhmdanas** [comment]
I'd mark this as [ci skip] because it revbumps so many things.

**Comment by motorto** [comment]
Already marked, unfortunately I thought that it was [ci-skip], so that why the builders are running. They should timeout

**Comment by classabbyamp** [comment]
if you force-push it will cancel the current CI run

**Comment by xAlpharax** [comment]
Really wish to see this bumped. What specifically is failing in the CI?

**Comment by motorto** [comment]
> Really wish to see this bumped. What specifically is failing in the CI?

There isn't a problem with this one, I am currently using this on my system, (only the libpulseaudio, and pulseaudio-utils since I am using pipewire).

**Whats missing is testers**, the CI fails because of the bumped packages, not because of the pulseaudio update.

I am going to rebase master into this PR,  and then you could [try this package locally.](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#testing-pull-requests)

**Comment by motorto** [comment]
@xAlpharax when you have a time feel free to try it.

**Comment by xAlpharax** [comment]
> @xAlpharax when you have a time feel free to try it.

@motorto Tested and it seems good, anything else that keeps us from upstreaming this?

**Comment by motorto** [comment]
> > @xAlpharax when you have a time feel free to try it.
> 
> @motorto Tested and it seems good, anything else that keeps us from upstreaming this?

Are you using pulseaudio as your sound server ?

Or are you like me using pipewire ?

**Comment by xAlpharax** [comment]
> > > @xAlpharax when you have a time feel free to try it.
> > 
> > @motorto Tested and it seems good, anything else that keeps us from upstreaming this?
> 
> Are you using pulseaudio as your sound server ?
> 
> Or are you like me using pipewire ? 

I did both to test this in 2 setups

**Comment by classabbyamp** [comment]
rebase pls

**Comment by xAlpharax** [comment]
> rebase pls

i second this (hi abby)

**Comment by motorto** [comment]
@classabbyamp done, sorry for the wait

**Comment by motorto** [comment]
@classabbyamp done, sorry for the delay.

**Pull request merged**
