### PR TITLE
git-cliff: update to 0.6.0.

### PR DESCRIPTION
**Pull request by jcgruenhage**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by cinerea0** [comment]
This is failing due to the ongoing issue with Rust's autocfg (https://github.com/void-linux/void-packages/issues/34889). Also, you have a PR for version 0.4.2 of this package open here: https://github.com/void-linux/void-packages/pull/33955.

**Comment by jcgruenhage** [comment]
I seem to have forgotten about that one.. closed the old one now.

**Comment by cinerea0** [comment]
It seems 0.6.0 just released, maybe that one will have gotten rid of the problem?

**Comment by jcgruenhage** [comment]
yay! Seems to work now.

**Pull request merged**
