### PR TITLE
libksysguard: update to 5.13.3, fix cross-build

### PR DESCRIPTION
**Pull request by yopito**

### CODE REVIEW

**Comment by yopito** [comment]
* need a xlint fix
* have to ensure it does break KDE DE at runtime ... tests in progress

**Comment by Johnnynator** [comment]
#891

**Comment by yopito** [comment]
@Johnnynator : Ah, I miss your (huge) work. If you don't mind, could you inject "material" from this PR into your ? I think you missed a `common/shlibs` entry for `libksysguard` at least.  
Then I will close this PR.

**Comment by Johnnynator** [comment]
OK, I will add the shlib Entry.

**Comment by yopito** [comment]
Useless PR since merged in to PR #891

**Pull request closed without merging**
