### PR TITLE
New package: trident-networkmgr-2020.03.29

### PR DESCRIPTION
**Pull request by beanpole135**
This is a graphical front end for client-side operation of:
* dhcpcd
* wpa_supplicant
* resolvconf
* wireguard

Sponsored by: Project Trident

### CODE REVIEW

**Comment by beanpole135** [comment]
I just released a minor revision of the tool which removes the Qt5 x11extras module dependency and updated the PR. This should help it build on those other architectures, since that appears to be the only build failures (Qt5 x11extras module does not appear to be getting installed properly on some archs).

**Comment by xtraeme** [comment]
Nice, thanks!

It's weird that travis CI check has dissapeared...

**Comment by Johnnynator** [comment]
> (Qt5 x11extras module does not appear to be getting installed properly on some archs).

This issue is with qmake, the module itself is installed properly, qmake just doesn't find it. It can be worked around by installing qt5-x11extras-devel to host, so qmake find the one in the host, but still uses the target one. (or by not using qmake :D)

**Comment by beanpole135** [comment]
Yeah, the first builds ran with qt5-x11extras-devel being included in the "makedepends", but I did not try adding it to the "hostmakedepends". 
I have other tools which do need x11extras (this one was not a hard depends, so I just removed it), so I will try that hostmakedepends trick on the other packages as needed.

**Comment by xtraeme** [comment]
can you please force push to trigger travis ci?

**Comment by beanpole135** [comment]
@xtraeme : Done - does not appear to have triggered travis CI at all. Is there some comment-trigger for Travis to tell it to re-test? I have seen that with other CI systems.

**Comment by beanpole135** [comment]
Or I could always close and re-open the PR if needed.

**Comment by beanpole135** [comment]
All set! Travis CI just finished with all builds successful.

**Pull request merged**
