### PR TITLE
rust: remove libunwind

### PR DESCRIPTION
**Pull request by jnbr**
fixes: https://github.com/void-linux/void-packages/issues/3605

### CODE REVIEW

**Comment by jnbr** [comment]
currently checking all architectures:

- [x] x86_64
- [x] x86_64-musl
- [ ] i686
- [ ] armv6l
- [x] armv6l-musl
- [ ] armv7l
- [x] armv7l-musl
- [ ] aarch64
- [ ] aarch64-musl

**Comment by Cogitri** [comment]
I can test compile aarch64{-musl} with this, if you want to. Is everything about rust fixed on this and #3558 are merged?

**Comment by jnbr** [comment]
> I can test compile aarch64{-musl} with this, if you want to.

Yes, that would help.

**Comment by Cogitri** [comment]
aarch64 works

**Comment by Gottox** [comment]
Ready for merging?

**Comment by jnbr** [comment]
yes

**Pull request merged**
