### PR TITLE
WIP: lxd: update to 3.18

### PR DESCRIPTION
**Pull request by fosslinux**
DO NOT MERGE!

Still broken.

### CODE REVIEW

**Comment by fosslinux** [comment]
fixed the header issue.

still need to make a -devel package for libco

**Comment by CameronNemo** [comment]
See previous #13163 #13848

**Comment by fosslinux** [comment]
Ok, I saw the first two but not the last one.

**Comment by fosslinux** [comment]
@CameronNemo would you like me to close this and defer to your PR? 

FYI: The dqlite update breaks lxd-lts. The newer version of lxd-lts, version 3.0.4 does not fix this issue. IMO lxd-lts should be dropped as it'll just create much more maintenance as another dqlite versioned package will be required, etc.

**Comment by fosslinux** [comment]
Mkay

```
➜ lxc launch images:voidlinux void-111
Creating void-111
Error: Failed instance creation: Create container from image: Unpack failed, Failed to run: unsquashfs -f -d /var/lib/lxd/storage-pools/default/images/628098405/rootfs -n /var/lib/lxd/images/725aec362c603358227c640a2dec89e12ccfa60acb5b72c7a05b74ec3c7b1b0d.rootfs: FATAL ERROR:write_file: failed to create file /var/lib/lxd/storage-pools/default/images/628098405/rootfs/usr/libexec/dhcpcd-hooks/50-ntp.conf, because Too many open files.
```

**Comment by CameronNemo** [comment]
Maybe did not restart lxd? `xcheckrestart` can identify deleted (e.g. updated) binaries that are associated with running processes. Is there a difference between our two branches? perhaps your branch was good but I did something different.

You may have luck by forwarding this upstream.

**Comment by fosslinux** [comment]
Defer to #15045

**Pull request closed without merging**
