### PR TITLE
llhttp: update to 2.0.5

### PR DESCRIPTION
**Pull request by rmccask**
This is needed to update nodejs and nodejs-lts.

### CODE REVIEW

**Comment by mustaqimM** [comment]
@rmccask Are you working on the node packages?

**Comment by rmccask** [comment]
I have nodejs and nodejs-lts built but will build them again before I submit to reverify.  I can send you the changes if you need them sooner.  My build vm is a little slow. 

-Randy


On May 12, 2020 6:20:21 AM EDT, Mustaqim Malim <notifications@github.com> wrote:
>@rmccask Are you working on the node packages?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/void-linux/void-packages/pull/21744#issuecomment-627251549

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mustaqimM** [comment]
I do need it but I'll wait since I see you're also busy with the icu package

**Comment by rmccask** [comment]
My test build of nodejs 14.2.0 without icu 67.1 just errored out with:
    ERROR: icu4c v64.2 is too old, v65.x or later is required.

It built with the update icu already.  Looks like I need to submit those together.

**Comment by oliver-cfc** [comment]
I'm pretty new to node so may be missing something but 'npm install ' fails with llhttp-2.0.5_1

`$ npm i express
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oliver/.npm/_logs/2020-05-12T17_11_37_457Z-debug.log`

Downgrading to llhttp-1.1.4_1 allows it to work again

`$ npm i express
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN nodeapi@1.0.0 No repository field.

+ express@4.17.1
added 50 packages from 37 contributors and audited 126 packages in 14.868s
found 0 vulnerabilities`

Does this mean I need to wait for a node upgrade (current on nodejs-13.2.0_1) before upgrading llhttp again?

**Comment by rmccask** [comment]
I see a lot of errors mentioning "npm ERR! cb() never called".  You could wait for a new node package since it is being worked on but I don't think it should be necessary.  A couple of suggestions I saw:

```
If you have npm version 5 or above, try this first:

$ sudo npm cache verify

Otherwise:

$ sudo npm cache clean
```

Another suggestion said that uninstalling the node package, rebooting and then reinstalling fixed it.  I suspect that just cleared it out of memory but you could try it.  Please let me know if either of these works.

**Comment by oliver-cfc** [comment]
The 'cache verify' came back OK... the 'cache clean' needed to be forced and had no effect.  Uninstalling, rebooting, reinstalling had no effect.
I spun up a fresh void instance in virtualbox and can re-create the problem

**Comment by rmccask** [comment]
I have reproduced it locally.  I am working on it.

**Comment by rmccask** [comment]
I have a new version of nodejs-lts and I put in a revbump for nodejs.  I did builds of them both and they worked after the rebuild.

**Comment by mustaqimM** [comment]
Ya, I read on one of the two git repos llhttp needs to be updated along with nodejs. Perhaps you could add a comment that notes both should get updated in the same PR

**Comment by rmccask** [comment]
@mustaqimM: Is it only because llhttp went from 1.X to 2.X or will it happen every time?  I am thinking a comment in the llhttp template saying that nodejs and nodejs-lts need to be tested and possibly be included in the same PR might be enough.  I think nghttp2 also uses llhttp so it might need  revbump too?

**Comment by mustaqimM** [comment]
They work in-sync and should be updated together. I'm trying to find where I read that. (The same goes for the containerd and docker packages). Most likely every package that has a reverse dependency on it

**Comment by oliver-cfc** [comment]
Confirmed all is good after the revbump for nodejs.  Thanks for the fix.

**Comment by nathanblair** [comment]
> 
> 
> My test build of nodejs 14.2.0 without icu 67.1 just errored out with:
> ERROR: icu4c v64.2 is too old, v65.x or later is required.
> 
> It built with the update icu already. Looks like I need to submit those together.

This is precisely why I had made the static version of node in this PR: https://github.com/void-linux/void-packages/pull/21341

**Pull request merged**
