### PR TITLE
fractal: update

### PR DESCRIPTION
**Pull request by dkwo**
- I tested the changes in this PR: no
- I built this PR locally for my native architecture, (x86_64-musl)

#37681 @CameronNemo

### CODE REVIEW

**Comment by dkwo** [comment]
maybe @paper42 ?

**Comment by dkwo** [comment]
actually, update it

**Comment by dkwo** [comment]
@jcgruenhage , anyone: can you help with cross compile?

**Comment by jcgruenhage** [comment]
I don't see anything obvious going wrong here, rust is claiming to compile successfully...

**Comment by dkwo** [comment]
the cargo.sh script looks at build/target/release
```
cp: cannot stat '/builddir/fractal-4.4.2/build/target/release/fractal-gtk': No such file or directory
FAILED: fractal-gtk/src/fractal 
/builddir/fractal-4.4.2/scripts/cargo.sh .. fractal-gtk/src/fractal /builddir/fractal-4.4.2/build ''
```
while for cross we have e.g. build/target/aarch64-unkonwn-linux-gnu/release
```
$ ls masterdir/builddir/fractal-4.4.2/build/target/aarch64-unknown-linux-gnu/release/
build  deps  examples  fractal-gtk  fractal-gtk.d  incremental
```

**Comment by dkwo** [comment]
i was trying to reinvent the wheel, the fix was already there..

**Pull request merged**
