### PR TITLE
New package: swift-5.2.1

### PR DESCRIPTION
**Pull request by dinama**
Apple's programming language

### CODE REVIEW

**Comment by Chocimier** [comment]
We do not accept new packages depending on python 2.

**Comment by q66** [comment]
there also doesn't seem to be any reason to limit it to x86_64

**Comment by dinama** [comment]
> there also doesn't seem to be any reason to limit it to x86_64

possibly due to the python2 -  build  on other platforms does not go through
I'll try to apply patches to use the python3 and I'll come back.

**Comment by q66** [comment]
It probably just does not cross compile, might need marking nocross. As far as I can see, at least also ppc64le and aarch64 should be supported, maybe others. Musl platforms may need patching. Also, if a build with system llvm is possible, it'd be preferable. Patch the build if necessary

**Comment by q66** [comment]
Also, skip the Travis CI build, it times out and you are just hogging the resources. Also, add a do_check so the testsuite can be run, we don't want untested packages

**Comment by dinama** [comment]
will I have to create a new PR or put patches in here?

**Comment by q66** [comment]
it's fine to put any potential patches together with this

i can test building it in some other environments later once it's shaped up (like ppc64le)

**Comment by dinama** [comment]
building with the system llvm is not possible at this time. resolving other problems will take some time. i do it on next week.

**Comment by dinama** [comment]
> it's fine to put any potential patches together with this
> 
> i can test building it in some other environments later once it's shaped up (like ppc64le)

Compilation using clang is not fully supported in xbps-src (especially cross compilation). And the swift build system is unstable. For this reason, the package preparation is delayed.

**Comment by CRKatri** [comment]
swift 5.3.1 is now available which uses python3 now.

**Comment by dinama** [comment]
> swift 5.3.1 is now available which uses python3 now.

thank you! I gave up trying to build - they were unstable and 1/3 ended  with fail. I will try a new release soon.

**Comment by CRKatri** [comment]
Taking a closer look, it's actually swift 5.4 that switched over, 5.4 is development though.

**Comment by abenson** [comment]
Seemingly abandoned.

**Pull request closed without merging**
