### PR TITLE
ol: update to 2.1.1.

### PR DESCRIPTION
**Pull request by yuriy-chumak**

### CODE REVIEW

**Comment by yuriy-chumak** [comment]
Hmmmmm. I have done the 
```
$ git add <file>
$ git commit --amend
$ git push -f
```
from [CONTRIBUTING](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md). How to restart pull request checks?

**Comment by ericonr** [comment]
It won't redo checks if you don't make any changes. You can rebase your branch on upstream master and push that, then tests will be run again.

**Comment by abenson** [comment]
This needs some work.

At a minimum, you need to add: `disable_parallel_build="yes"` and `make_use_env=yes`

This doesn't solve the cross-build problem.

```
echo '(display "unsigned char repl[] = {") (lfor-each (lambda (x) (for-each display (list x ","))) (file->bytestream "repl")) (display "0};")'| ./vm repl> tmp/repl.c
/bin/sh: ./vm: cannot execute binary file: Exec format error
```

**Comment by yuriy-chumak** [comment]
Thank you. Reasonable.

**Pull request closed without merging**
