### PR TITLE
btop: Update to 1.3.2

### PR DESCRIPTION
**Pull request by zen0bit**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x64 glibc)

### CODE REVIEW

**Comment by Calandracas606** [comment]
Tested and is not working for me on x86-64-musl. CPU bar are missing.

Also, we could add ROCm-SMI-LIB as a dependancy for GPU support. I have a template for it, but it is trivial, and has no dependancies

**Comment by mdkcore0** [comment]
btop [1.3.2](https://github.com/aristocratos/btop/releases/tag/v1.3.2) available

**Comment by Calandracas606** [comment]
I just tested, and 1.3.2 looks like its working for me on musl

Also I created a PR to add ROCm-SMI-LIB for GPU support: #48744

**Comment by zen0bit** [comment]
> I just tested, and 1.3.2 looks like its working for me on musl
> 
> Also I created a PR to add ROCm-SMI-LIB for GPU support: #48744

Definetly will try..

Since btop must be compiled with ROCm support, I think we will need second package for that...

am I right?

**Comment by Calandracas606** [comment]
> 
> Since btop must be compiled with ROCm support, I think we will need second package for that...
> 

ROCm-SMI is a standalone library which doesn't require any additional ROCm components. It pretty much just is an interface to get GPU load, power usage, temps, fan speeds, etc.

**Comment by zen0bit** [comment]
> > Since btop must be compiled with ROCm support, I think we will need second package for that...
> 
> ROCm-SMI is a standalone library which doesn't require any additional ROCm components. It pretty much just is an interface to get GPU load, power usage, temps, fan speeds, etc.

I am speaking about btop and btop-rocm

**Comment by Calandracas606** [comment]
> I am speaking about btop and btop-rocm

I don't think that there is a need for a second package.

How is it different from other packages we build which have optional dependencies for extended functionality?

**Comment by Calandracas606** [comment]
I just checked the code and it should dlopen librocm_64.so

**Comment by zen0bit** [comment]
But as I study btop instructions before. ROCm must be presented at build time. If isn't btop should be builded without ROCm support. So provide library for usuall btop shouldn't be enough. Must be builded again with ROCm, as far as I understand...

**Comment by cinerea0** [comment]
I believe what @Calandracas606 is saying is that there is no need to create a new `btop-ROCm` package, you can simply add `ROCm-SMI-devel` to btop's `makdepends` if/when it gets merged.

That said, `xbps` does not support "optional" dependencies, only build options. Did you mean adding a non-default build option for ROCm-SMI support?

**Comment by Calandracas606** [comment]
made a bug report upstream, but it shouldn't block this PR

https://github.com/aristocratos/btop/issues/774

**Comment by dm17** [comment]
image

I'm not seeing how to get the GPU to display.

**Comment by Calandracas606** [comment]
@dm17 
> I'm not seeing how to get the GPU to display. I've AMDGPUs

btop needs rocm-smi-lib https://github.com/void-linux/void-packages/pull/48744 to display amdgpu details

however, btop also appears bugged, and fails to display without a patch: https://github.com/aristocratos/btop/issues/774

only with patched btop, and rocm-smi-lib will the gpu show: 
image

**Pull request merged**
