### PR TITLE
pgadmin3: Use postgresql libs 12

### PR DESCRIPTION
**Pull request by arete**
Signed-off-by: Gerardo Di iorio <arete74@gmail.com>

#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by Chocimier** [comment]
Why?

**Comment by arete** [comment]
> It's time to remove pgadmin3 then. It hasn't seen a release for 6 years. Postgres 9.6 is being removed from repos (#35546) and newer versions work with pgadmin4.

I have modify pull request to use postgresql 12 libs.

**Comment by paper42** [comment]
> > It's time to remove pgadmin3 then. It hasn't seen a release for 6 years. Postgres 9.6 is being removed from repos (#35546) and newer versions work with pgadmin4.
> 
> I have modify pull request to use postgresql 12 libs.

postgresql 12 has been removed on 30. September 2021

**Comment by Chocimier** [comment]
postgresql 13 will be removed with introduction of 15, eta autumn this year

**Pull request closed without merging**
