### PR TITLE
[WIP] New package: python3-brotlicffi-1.0.9.2

### PR DESCRIPTION
**Pull request by misuchiru03**

### CODE REVIEW

**Comment by misuchiru03** [comment]
References: #4432

**Comment by misuchiru03** [comment]
Oh duh. Totally slipped by me.

**Comment by misuchiru03** [comment]
`aarch64-musl` and `x86_64-musl` build on my local system without errors.

**Comment by NeelChotai** [comment]
I wonder if `python3-wheel` being in `makedepends` rather than `hostmakedepends` has anything to do with it. I can build this template for `aarch64-musl` locally too but it has warnings unless `python3-wheel is in `hostmakedepends`.

**Comment by misuchiru03** [comment]
I added `python3-wheel` to `hostmakedepends`, and that seemed to fix `x86_64-musl` but I saw the error stating `no module named _cffi_backend` on armv6l-musl and aarch64-musl, added `python3-cffi` to `makedepends` but that didn't fix those two. Both package fine with no errors on my machine.

**Comment by misuchiru03** [comment]
Changed to Work-In-Progress

**Comment by classabbyamp** [comment]
it seems that mitmproxy has moved to `Brotli`, which is already packaged as `python3-Brotli`

**Comment by misuchiru03** [comment]
If it's already got a package, I'll leave this one.

**Pull request closed without merging**
