### PR TITLE
lurch: update to 0.7.0.

### PR DESCRIPTION
**Pull request by ThatGeekyWeeb**
This is a quick update for lurch as the current version of it doesn't seem to work, yet after compiling by hand works fine.

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
>  yet after compiling by hand works fine.

Does the resulting package also work? :)

**Comment by ericonr** [comment]
Could be wonky compiler flags or whatever.

**Comment by ThatGeekyWeeb** [comment]
From my testing this package also works.

**Comment by ThatGeekyWeeb** [comment]
@ericonr haha looks like this fell into the back log... I can imagine you have a lot of work,, but whats the status on this?

**Comment by ericonr** [comment]
@ThatGeekyWeeb merging was suspended for most of the weekend due to the builder merge, so it couldn't be merged when I had time to look at it.

Thanks for pinging.

**Pull request merged**
