### PR TITLE
nvidia: update to 455.45.01.

### PR DESCRIPTION
**Pull request by kyurime**

### CODE REVIEW

**Comment by ericonr** [comment]
@abenson

**Comment by abenson** [comment]
Void usually avoids non-stable branches. 

>  Latest New Feature Branch Version: 455.45.01

So for now I've been planning on sticking to 450.xx 

>  Latest Production Branch Version: 450.80.02

I *was* working on the 460.xx beta, but I apparently deleted my branch by accident.  Since it should be the next production release, I'm aiming for that to be the next nvidia package.

**Comment by kyurime** [comment]
Ah, my apologies! I didn't notice that detail about new feature branch vs production branch and just assumed that the latest non beta build was what was typically packaged :p
That being said, I'll close this and wait for 460.xx, thanks for responding

**Comment by abenson** [comment]
If you would like, you can mark this [WIP] and update it to 460.27.04, that way we can have it open for testing and ready to go when they update the production branch.

**Pull request closed without merging**
