### PR TITLE
libGL: add missing `b_ndebug` option

### PR DESCRIPTION
**Pull request by SolitudeSF**
This removes remaining debug info and greatly improves dxvk performance.

### CODE REVIEW

**Comment by maxice8** [comment]
please add at the end with the b_lto=false option

**Comment by maxice8** [comment]
also needs to bump revision

**Comment by maxice8** [comment]
imho we should set b_ndebug=true on the build-style itself @Gottox

**Comment by Gottox** [comment]
We discussed my concerns already in IRC.

NDEBUG disables assertions which are used for input verification on in some applications. Nevertheless at least the current state for meson is quite sane. So I think setting the option globally is reasonable.

**Comment by maxice8** [comment]
This was addressed in a separate PR

**Pull request closed without merging**
