### PR TITLE
New package: Cendric-1.0.4

### PR DESCRIPTION
**Pull request by Johnnynator**

### CODE REVIEW

**Comment by pullmoll** [comment]
The patch does not apply here for whitespace issues.
```
=> Cendric-1.0.4_1: patching: linux.patch.
3 out of 3 hunks FAILED -- saving rejects to file CMakeLists.txt.rej
=> ERROR: Cendric-1.0.4_1: post-extract_00-patches: 'patch -sl ${_args} -i ${_patch} 2> /dev/null' exited with 1
=> ERROR:   in _process_patch() at common/hooks/post-extract/00-patches.sh:34
=> ERROR:   in hook() at common/hooks/post-extract/00-patches.sh:51
=> ERROR:   in run_func() at common/xbps-src/shutils/common.sh:21
=> ERROR:   in run_pkg_hooks() at common/xbps-src/shutils/common.sh:251
=> ERROR:   in main() at common/xbps-src/libexec/xbps-src-doextract.sh:71
```
Using `dos2unix CMakeLists.txt` in `post_extract()` seems to fix this.

**Comment by Johnnynator** [comment]
@pullmoll It only doesn't work for you because you changed the line endings of the patch, the patch on my branch did work fine.

**Comment by pullmoll** [comment]
Ok, I used `git-merge-pr` which obviously touches the patch. Anyway, I think it's easier to maintain patches without MSDOS line endings ;-)

**Comment by Johnnynator** [comment]
Imo Maintaining patches that would apply upstream are easier to maintain, since that would not require to mess with line endings manually. Changing line endings automatically like `git-merge-pr` does feels quite counterproductive for patches (IMO makes maintaining patches harder)

**Pull request closed without merging**
