### PR TITLE
[WIP] rust: update to 1.30.0.

### PR DESCRIPTION
**Pull request by Cogitri**
[ci skip]

### CODE REVIEW

**Comment by Gottox** [comment]
New versions of cargo, rustc, and rust-std have been uploaded to distfiles

**Comment by Cogitri** [comment]
Eh? New cargo?

**Comment by Gottox** [comment]
https://alpha.de.repo.voidlinux.org/distfiles/cargo-0.30.0-2-x86_64-unknown-linux-musl.tar.gz - with the old one I got errors on musl. I suspect that the old 0.30.0 pkg contained another version.

**Comment by Cogitri** [comment]
Eh? The "old" 0.30.0 is different to the "new" 0.30.0?

**Comment by Gottox** [comment]
I suspect that 0.30.0 is actually 0.29.0, that's why there's 0.30.0-2

**Comment by Cogitri** [comment]
Ah, okay.

**Comment by Cogitri** [comment]
Alright, it builds on all glibc platforms already, will look into musl tomorrow

**Comment by Cogitri** [comment]
Bumped cargo to 0.31.0, mind building it for musl @Gottox?

**Comment by Gottox** [comment]
Give me a few minutes :+1:

**Comment by Gottox** [comment]
https://alpha.de.repo.voidlinux.org/distfiles/cargo-0.31.0-x86_64-unknown-linux-musl.tar.gz

**Comment by Cogitri** [comment]
Thanks, updated :)

**Comment by Cogitri** [comment]
Mind testing this @Gottox? As far as I can see everything works.

**Comment by jnbr** [comment]
There is a problem with cross compiling packages with the cargo build style. Do not merge without #4328 being solved.

**Comment by jnbr** [comment]
LGTM, aarch64-musl and armv7-musl work

**Comment by jnbr** [comment]
6b16df3393f8e6d6c118a0e1acf741e4485a681a

**Pull request closed without merging**
