### PR TITLE
epub2txt: update to 2.06.

### PR DESCRIPTION
**Pull request by natrys**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by Chocimier** [comment]
Upstream is fixing bugs, let's wait until it stabilize.

**Comment by natrys** [comment]
Okay, will revisit few weeks later.

**Comment by Duncaen** [comment]
ping

**Comment by natrys** [comment]
There are two newer bug fix commits. Asked upstream for new release: https://github.com/kevinboone/epub2txt2/issues/23

**Pull request merged**
