### PR TITLE
build-style/go: use XBPS_MAKEJOBS to control parallelism

### PR DESCRIPTION
**Pull request by CameronNemo**

### CODE REVIEW

**Comment by CameronNemo** [comment]
@the-maldridge not sure if you want to gosmoke this or what

**Comment by the-maldridge** [comment]
This looks okay, I'd rather merge this though with a change that also fixes everywhere that we've hacked in a parallelism disable.  I don't think we need to gosmoke this, it should be reasonably safe.

**Comment by the-maldridge** [comment]
@xtraeme please do not merge changes that still have open discussions.

**Comment by CameronNemo** [comment]
what packages could take advantage of / test this?

**Comment by xtraeme** [comment]
This has been reverted. I thought the conversation was resolved.

**Comment by CameronNemo** [comment]
Can someone reopen? I cannot find a single template hacking the -p flag in.

**Comment by Duncaen** [comment]
Can't reopen a merged PR.

**Pull request merged**
