### PR TITLE
Nvidia drivers

### PR DESCRIPTION
**Pull request by motorto**
Testing the changes

    I tested the changes in this PR: NO

    I built this PR locally for my native architecture, x86_64

Still haven't got the time to test on hardware, but it builds and installs fine .

Testers are welcome, hope I didn't miss anything ...

I closed the other one without intention... #34664

### CODE REVIEW

**Comment by prateekmedia** [comment]
Nvidia 510 drivers are the latest drivers, So why are you using 495 one?

**Comment by motorto** [comment]
As stated by @abenson : 
> We typically stick to Production branch releases for nvidia.
This is a good start for what will be the next nvidia major update, so keep it open.

Void Linux only uses Production branch releases for nvidia drivers. We are basically just waiting for the new drivers to reach that state .

**Comment by wael444** [comment]
would it be possible to have an unofficial version 510 template?

**Comment by wael444** [comment]
build fails, [here are the logs](https://gist.github.com/wael444/df3aa076d82fd1dbcb83c4fec2ca1ec9)

**Comment by abenson** [comment]
> Nvidia 510 drivers are the latest drivers

510.xx are Beta.

> build fails

The branch needs to be rebased on master.

**Comment by abenson** [comment]
> would it be possible to have an unofficial version 510 template?

I don't plan on making one in the meantime.

**Comment by Lolzen** [comment]
510.47.03 stable is now official

**Comment by abenson** [comment]
I've made a mess of this, but:

@motorto Thank you for your work.  I hope you don't mind, but I updated your PR to the new production version.

Everyone else, please test!

**Comment by Lolzen** [comment]
On a userlevel test everything seems to be fine. 
DKMS module built on 5.15, 5.16 fine. WoW on Lutris no issues, had some issues starting steam due to usererror and not upgrading the 32bit libs, once done no issues there aswell.

**Comment by motorto** [comment]
Don't mind at all
Its your package after all! Thanks for your incredible work !

(My pc was inoperable for some days, sorry for the late reply)

**Comment by wael444** [comment]
> 510.47.03 stable is now official

what? i thought 495 is stable and 510 is production release
also good timing for my comment:

> would it be possible to have an unofficial version 510 template?

i hope wayland works now!

**Comment by abenson** [comment]
>  i thought 495 is stable and 510 is production release

495.xx is still "New Feature" branch, though its currently behind 510.xx "Production Branch".  470.xx is the newest "Legacy".  [Current Releases](https://forums.developer.nvidia.com/t/current-graphics-driver-releases/28500).

**Pull request closed without merging**
