### PR TITLE
tmux: update to 3.0

### PR DESCRIPTION
**Pull request by zdykstra**

### CODE REVIEW

**Comment by ndowens** [comment]
This is not a stable version, reason why I haven't updated yet.

**Comment by ndowens** [comment]
Do you mind if I update this myself, I maintain this one, and can fix the musl build?

**Comment by zdykstra** [comment]
> Do you mind if I update this myself, I maintain this one, and can fix the musl build?

Not a problem - thanks!

**Comment by ndowens** [comment]
> > Do you mind if I update this myself, I maintain this one, and can fix the musl build?
> 
> Not a problem - thanks!

Thank you :)

**Pull request closed without merging**
