### PR TITLE
json-glib: update to 1.6.0

### PR DESCRIPTION
**Pull request by ev-ermakov**
By the way, should I update `common/shlibs` as well? Currently, the corresponding entry looks like this:
```
libjson-glib-1.0.so.0 json-glib-0.12.2_1
```

### CODE REVIEW

**Comment by ev-ermakov** [comment]
Oh, I forgot about revbumps.

It looks like it wasn't a good idea to update this library.

**Comment by ev-ermakov** [comment]
I'll remove [WIP] when #25504 will be merged into the master branch.

**Comment by q66** [comment]
what's the point of these rebuilds?

**Comment by pullmoll** [comment]
There's no point as the ABI didn't change. Upstream did not bump the solib version so all revbumps can be dropped from this PR.

**Comment by ev-ermakov** [comment]
Sorry for this, just misunderstood how `common/shlibs` is meant to be used.

**Comment by ev-ermakov** [comment]
[gtk-doc failed](https://travis-ci.org/github/void-linux/void-packages/jobs/735245086#L774). Maybe it has something to do with Python?

**Comment by ericonr** [comment]
I think it's a cross compilation issue, actually.

**Comment by ev-ermakov** [comment]
@ericonr, compare this package with [orc](https://github.com/void-linux/void-packages/blob/master/srcpkgs/orc/template), it has no such issue.

**Comment by ericonr** [comment]
You can try adding the qemu helper to see what happens.

**Comment by ev-ermakov** [comment]
20044523bd

**Pull request closed without merging**
