### PR TITLE
nsxiv: update to 29

### PR DESCRIPTION
**Pull request by WitherCubes**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by tibequadorian** [comment]
Build error is probably not architecture related, but fails due to cross compiling. Specify `nocross=yes` instead of restricting archs. But preferably you should figure out how to fix cross builds.

**Comment by WitherCubes** [comment]
I will change it to `nocross=yes` for the moment, I will look into fixing cross builds after discussing with the nsxiv dev team.

**Comment by paper42** [comment]
Do not add nocross=yes and remove the architecture restriction, so we can see what's happening.

**Comment by tibequadorian** [comment]
This could be relevant: https://github.com/nsxiv/nsxiv/issues/237

**Comment by N-R-K** [comment]
> This could be relevant: [nsxiv/nsxiv#237](https://github.com/nsxiv/nsxiv/issues/237)

Seems to be the case from the [logs](https://github.com/void-linux/void-packages/runs/5407965374?check_suite_focus=true), it compiled fine but then failed when trying to install.

**Comment by paper42** [comment]
> Seems to be the case from the [logs](https://github.com/void-linux/void-packages/runs/5407965374?check_suite_focus=true), it compiled fine but then failed when trying to install.

For some reason it tries to create options.o and fails before do_install doesn't set cross flags.

**Comment by tibequadorian** [comment]
With your patch from https://github.com/nsxiv/nsxiv/pull/238 it does work @N-R-K

**Comment by N-R-K** [comment]
Just removing `all` from the `install` prerequisite should work as well. This is what I do on the gentoo::guru package: `sed -i -e '/^install: / s|: all|:|' Makefile`.

**Comment by paper42** [comment]
Give the patch an appropriate name and a description, this doesn't tell us anything.

**Comment by WitherCubes** [comment]
> Give the patch an appropriate name and a description, this doesn't tell us anything.

I can't come up with a proper name and description, could you please recommend something?

_BTW the issue that is fixed by the patch is [this](https://github.com/nsxiv/nsxiv/issues/237)_

**Comment by N-R-K** [comment]
Description: "Don't rebuild options.o when installing" (?)
Name: idk, "Fix install" maybe.

**Comment by WitherCubes** [comment]
I have added the proper patch name and description.

**Pull request merged**
