### PR TITLE
firefox: update to 88.0.

### PR DESCRIPTION
**Pull request by jnbr**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

[ci skip]

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (x86_64, x86_64-musl, aarch64)
- [ ] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [x] aarch64-musl
  - [x] aarch64
  - [x] armv7l-musl
  - [x] armv7l
  - [ ] armv6l-musl

Dropping api key as requested on irc.
Tested on x86_64.

### CODE REVIEW

**Comment by Duncaen** [comment]
Using it since yesterday, works fine. on x86_64-glibc.

**Comment by q66** [comment]
enables webrender by default on KDE and xfce, which makes the browser segfault on musl

**Comment by ericonr** [comment]
Might be only on xorg? Works ok on wayland (wayfire).

**Comment by Duncaen** [comment]
Probably what @q66 said, its experimental and only enabled in certain situations (KDE/xfce), see `about:support`.

**Comment by Duncaen** [comment]
https://hg.mozilla.org/mozilla-central/rev/99598a47bacb

**Comment by ericonr** [comment]
We had chatted a bit on IRC, I have most of webrender force enabled here... Can try to launch a Xorg session to check there later...

**Pull request merged**
