### PR TITLE
anki: fix type errors and profile saving.

### PR DESCRIPTION
**Pull request by dm1tz**
Also, disable useless auto update dialog on start.

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by paper42** [comment]
Good job, did you create these patches or got them from somewhere?

**Comment by dm1tz** [comment]
> Good job, did you create these patches or got them from somewhere?

Thanks, I borrowed one that disables update dialog from AUR, the rest are mine.

**Comment by paper42** [comment]
Could you describe why is the fix_profile_save patch necessary? How can I reproduce a crash/bug? This would be also nice to mention in the patch.

**Comment by dm1tz** [comment]
> Could you describe why is the fix_profile_save patch necessary?

It fixes the ```<class 'SystemError'>: PY_SSIZE_T_CLEAN macro must be defined for '#' formats``` error when anki is trying to save your profile data on exit. 

> How can I reproduce a crash/bug?

Create a profile or login into the ankiweb account and then exit anki. 
> This would be also nice to mention in the patch.

Will do.

**Pull request merged**
