### PR TITLE
discord: update to 0.0.23.

### PR DESCRIPTION
**Pull request by zlice**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, **x86_64**

### CODE REVIEW

**Comment by adam-becker** [comment]
I tried making these exact same changes, but now discord fails to start with:

```
$ /usr/lib/discord/Discord --version
[2882:0112/155307.796936:FATAL:fork_and_spawn.cc(196)] posix_spawn: No such file or directory (2)
```

Made the changes, then ran `./xbps-src pkg discord && xi discord`.

**Comment by zlice** [comment]
Do you have extra processes already running? That's usually the issue I have. cuz killing that 'oMg uPgRaDe' window doesn't actually kill "Discord" in the bg.

**Comment by adam-becker** [comment]
> Do you have extra processes already running? That's usually the issue I have. cuz killing that 'oMg uPgRaDe' window doesn't actually kill "Discord" in the bg.

Yep, tried after a clean boot with no discord processes running. Same issue no matter what I've tried.

**Comment by zlice** [comment]
hm, maybe an issue with `~/.config/discord/Cache` ? or the version dir(s) ?

**Comment by adam-becker** [comment]
> hm, maybe an issue with `~/.config/discord/Cache` ? or the version dir(s) ?

Uninstalled discord, removed any traces of it from my system, cleared xbps package cache, removed orphans, rebuilt everything and still the same issue. 🎉

**Comment by Vulldozer** [comment]
I am having the same issue:
`[1365:0113/010834.287844:FATAL:fork_and_spawn.cc(196)] posix_spawn: No such file or directory (2)`

Tried deleting 'Cache', 'Code Cahce', '0.0.22' in discord's config folder, and a reboot, but didn't work

**Comment by zlice** [comment]
I'm afraid to restart discord XP

**Comment by Vulldozer** [comment]
This arch linux bug report seems to have a similar issue: https://bugs.archlinux.org/task/76314

Setting the environment variable `ELECTRON_ENABLE_STACK_DUMPING=true` I can launch discord

**Comment by adam-becker** [comment]
> This arch linux bug report seems to have a similar issue: https://bugs.archlinux.org/task/76314
> 
> Setting the environment variable `ELECTRON_ENABLE_STACK_DUMPING=true` I can launch discord

Oddly enough, this works for me too. Gotta love electron!

**Comment by zlice** [comment]
Huh, weird, not using that var, don't even seem to have electron installed (10,13,19)?

Other box with 5.18.5 is working fine, this 6.2-rc2 is fine. Update the 5.18 box with servercentral mirror and that's fine. Can restart box/discord and everything is normal.

**Comment by classabbyamp** [comment]
you need to include the `chrome_crashpad_handler`, this happened on ptb last update: https://github.com/void-linux/void-packages/commit/db0db39579227e3b8f50b3d7b627e32fcf0e3c87

**Comment by EllisK-L** [comment]
> you need to include the `chrome_crashpad_handler`, this happened on ptb last update: [db0db39](https://github.com/void-linux/void-packages/commit/db0db39579227e3b8f50b3d7b627e32fcf0e3c87)

I was having this problem previously, this also fixed it on my end :)

**Pull request merged**
