### PR TITLE
New package: z-1.11

### PR DESCRIPTION
**Pull request by RustemB**

### CODE REVIEW

**Comment by xtraeme** [comment]
This is not a candidate for inclusion in the void-packages repository.

Why? because it's a simple shell script that anybody can download and run.

Thanks anyway!

**Comment by RustemB** [comment]
sadly :disappointed:

**Comment by xtraeme** [comment]
you can just do `git clone url; cd foo; install -m 755 z.sh ~/bin/z; ~/bin/z` to run it.

Why do you need to use xbps? this is my point.

**Comment by whoizit** [comment]
@xtraeme 
your logic is completely incomprehensible. Then we need to remove youtube-dl, sx, neofetch and many-many others. It's simple scripts that can be installed via git clone or pip.
All scripts are programs, they have versions and require updating.
z is useful program and I need it in the repositories, because it is convenient

**Pull request closed without merging**
