### PR TITLE
Linux5.1: Add some modules for laptops and tablets.

### PR DESCRIPTION
**Pull request by thomas-t-w**

### CODE REVIEW

**Comment by xtraeme** [comment]
you've missed `revision++`

**Comment by thomas-t-w** [comment]
Hi, I did that on purpose because last time I requested a minor change to the kernel, the maintainer didn't bump it. I figured it would be a waste to make everyone download a new kernel for a minor change like this and also occupy the builders. Should I always bump the revision in the future even if it is a minor change like this? Thanks.

**Comment by pullmoll** [comment]
No, actually better not to revbump here. The kernel update rate is close to what our builders can manage anyway. I expect 5.1.7 within a week or so.

**Comment by xtraeme** [comment]
Your point is also valid. Fine with me. I don't have commit rights anyway :-)

**Pull request merged**
