### PR TITLE
alacritty: move INSTALL,REMOVE to subpackage

### PR DESCRIPTION
**Pull request by m3tav3rse**

### CODE REVIEW

**Comment by xtraeme** [comment]
Moved to what subpkg?

**Comment by xtraeme** [comment]
Oh I see. OK. It's ok

**Comment by m3tav3rse** [comment]
alacritty-terminfo, should I write rename?

**Comment by xtraeme** [comment]
Yeah, thr title is a bit confusing

**Comment by xtraeme** [comment]
Commit log is OK. Thanks

**Pull request merged**
