### PR TITLE
gimp: update to 2.10.32

### PR DESCRIPTION
**Pull request by biopsin**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by biopsin** [comment]
@fosslinux

**Comment by dataCobra** [comment]
Hey @biopsin,

could you please resolve the linting error?

After this the PR should be good to go.

I'm successful using the version on my machine.

**Comment by biopsin** [comment]
Heya @dataCobra shure will look into replacing the tics, however this has been accepted earlier.

**Comment by paper42** [comment]
that's a false positive, don't mind it

**Comment by biopsin** [comment]
Anyone else manage to test it on a arch other then x86_64-glibc?

**Pull request merged**
