### PR TITLE
New package: zchunk-0.9.6

### PR DESCRIPTION
**Pull request by cr6git**

### CODE REVIEW

**Comment by maxice8** [comment]
requires 

#include <sys/types.h>

in zck.h

**Comment by cr6git** [comment]
https://travis-ci.org/void-linux/void-packages/jobs/411591707#L785
````
../src/zck.c:38:10: fatal error: argp.h: No such file or directory
 #include <argp.h>
          ^~~~~~~~
compilation terminated.
````

**Comment by Johnnynator** [comment]
``
cc -Isrc/src@@unzck@exe -Isrc -I../src -Iinclude -I../include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=gnu99 -Wunused-result -DZCHUNK_ZSTD -DZCHUNK_OPENSSL -fvisibility=hidden -D_FORTIFY_SOURCE=2 -mtune=generic -O2  -MD -MQ 'src/src@@unzck@exe/unzck.c.o' -MF 'src/src@@unzck@exe/unzck.c.o.d' -o 'src/src@@unzck@exe/unzck.c.o' -c ../src/unzck.c
In file included from ../src/unzck.c:30:0:
../src/unzck.c: In function 'parse_opt':
../src/unzck.c:71:24: error: expected identifier before '(' token
             arguments->stdout = true;
                        ^
../src/unzck.c: In function 'main':
../src/unzck.c:122:19: error: expected identifier before '(' token
     if(!arguments.stdout) {
                   ^
```
requires some more patching for musl, I can take a deeper look at it once I'm finished with the KDE Framework PR.

**Comment by Johnnynator** [comment]
@cr6git add `LDFLAGS=-largp` for musl and
```
--- src/unzck.c	2018-08-02 15:42:19.000000000 +0200
+++ -	2018-08-04 20:20:53.438164577 +0200
@@ -39,7 +39,7 @@
 #include <zck.h>
 
 #include "util_common.h"
-
+#undef stdout
 static char doc[] = "unzck - Decompress a zchunk file";
 
 static char args_doc[] = "<file>";
```

**Comment by cr6git** [comment]
I don't care what Travis says.

**Pull request merged**
