### PR TITLE
FreeCAD stack: python3-pivy fixes, coin3 4.0.0

### PR DESCRIPTION
**Pull request by yopito**
personal runtime is fine.

### CODE REVIEW

**Comment by sgn** [comment]
Picked from #26589
```diff
diff --git a/srcpkgs/python3-pivy/template b/srcpkgs/python3-pivy/template
index fa1044b8ce..4ab2347a5e 100644
--- a/srcpkgs/python3-pivy/template
+++ b/srcpkgs/python3-pivy/template
@@ -6,7 +6,7 @@ revision=2
 wrksrc="pivy-${version}"
 build_style=python3-module
 hostmakedepends="python3-devel swig cmake"
-makedepends="python3-devel coin3-devel"
+makedepends="python3-devel coin3-devel qt5-devel"
 short_desc="Python3 bindings for the high-level 3D graphics library Coin"
 maintainer="yopito <pierre.bourgin@free.fr>"
 license="ISC"
@@ -23,6 +23,49 @@ case "$XBPS_TARGET_MACHINE" in
 	ppc*) broken="{standard input}:3376761: Error: operand out of range";;
 esac
 
+if [ "$CROSS_BUILD" ]; then
+	CFLAGS+=" -I$XBPS_CROSS_BASE/usr/include/Coin3"
+fi
+
+pre_configure() {
+	[ -z "$CROSS_BUILD" ] && return 0
+	case "$XBPS_TARGET_MACHINE" in
+		x86_64*) _CMAKE_SYSTEM_PROCESSOR=x86_64 ;;
+		i686*) _CMAKE_SYSTEM_PROCESSOR=x86 ;;
+		aarch64*) _CMAKE_SYSTEM_PROCESSOR=aarch64 ;;
+		arm*) _CMAKE_SYSTEM_PROCESSOR=arm ;;
+		mips*) _CMAKE_SYSTEM_PROCESSOR=mips ;;
+		ppc64le*) _CMAKE_SYSTEM_PROCESSOR=ppc64le ;;
+		ppc64*) _CMAKE_SYSTEM_PROCESSOR=ppc64 ;;
+		ppcle*) _CMAKE_SYSTEM_PROCESSOR=ppcle ;;
+		ppc*) _CMAKE_SYSTEM_PROCESSOR=ppc ;;
+		*) _CMAKE_SYSTEM_PROCESSOR=generic ;;
+	esac
+	cat >cross_${XBPS_CROSS_TRIPLET}.cmake <<_EOF
+SET(CMAKE_SYSTEM_NAME Linux)
+SET(CMAKE_SYSTEM_VERSION 1)
+
+SET(CMAKE_C_COMPILER   ${CC})
+SET(CMAKE_CXX_COMPILER ${CXX})
+SET(CMAKE_CROSSCOMPILING TRUE)
+
+SET(CMAKE_SYSTEM_PROCESSOR ${_CMAKE_SYSTEM_PROCESSOR})
+
+SET(CMAKE_FIND_ROOT_PATH  "${XBPS_CROSS_BASE}/usr;${XBPS_CROSS_BASE}")
+
+SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
+SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
+SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
+
+SET(wxWidgets_CONFIG_EXECUTABLE ${XBPS_WRAPPERDIR}/${wx_config:=wx-config})
+_EOF
+	cat >$XBPS_WRAPPERDIR/cmake <<_EOF
+#!/bin/sh
+/usr/bin/cmake -DCMAKE_TOOLCHAIN_FILE=$wrksrc/cross_${XBPS_CROSS_TRIPLET}.cmake "$@"
+_EOF
+	chmod +x $XBPS_WRAPPERDIR/cmake
+}
+
 post_install() {
 	vlicense LICENSE
 }
```

**Comment by yopito** [comment]
@sgn: thanks for your help, please review

My tests:
* build fine for x86_64-musl, aarch64 and armv6l
* freecad runtime is fine

**Comment by sgn** [comment]
@Piraty wants to look at this. Hence, I'll let Piraty decide.

**Comment by Piraty** [comment]
lgtm

**Pull request merged**
