### PR TITLE
rtmpdump: fix broken distfile url

### PR DESCRIPTION
**Pull request by q66**
I'm not sure if pointing it to our own sources like this is a good idea, but the original URL is down and there doesn't seem to be any other mirror with the tarball.

### CODE REVIEW

**Comment by Hoshpak** [comment]
I'm not sure that's a good idea either. Do these files ever expire? @void-linux/pkg-committers Even if they don't I think it would be better to upload such files to https://alpha.de.repo.voidlinux.org/distfiles/ which is meant to permanently store files. Since this is yet another mplayerhq project it makes me think we need a strategy for dealing with packages for which upstream outright refuses to publish any releases.

**Comment by q66** [comment]
yeah, probably better to get the file to distfiles; in the meantime, fixed lint.

**Comment by q66** [comment]
Well, I updated it. Lemme know what you think.

**Comment by Johnnynator** [comment]
The checksum of the tar ball changing is not that much of a problem, you can just take the checksum of the files in the tarball prefixed by a `@` e..g as it is done in `android-tools`. (check `xgensim -c`

**Comment by the-maldridge** [comment]
My answer to projects that refuse to publish releases is they aren't in tree, plain and simple.  Its a clearly stated requirement that we need releases that are stable to accept a package, and this organization chooses not to provide them.  Either this is stubbornness, or lack of understanding about how to release software.  Either way the lack of a release shows us that they are not ready for software to be distributed.

**Comment by q66** [comment]
too bad this one is needed for things like ffmpeg and kodi :/

**Comment by the-maldridge** [comment]
Given that kodi is effectively unmaintained I'm in favor of dropping it.  Since this appears to only be needed for the somewhat obscure rtmp stream protocol I think we could safely turn that off.

**Comment by q66** [comment]
Okay, sounds good. How do I do that, do I raise an issue in the tracker?

**Comment by q66** [comment]
fixed using void distfiles url

**Pull request merged**
