### PR TITLE
NoiseTorch: remove package

### PR DESCRIPTION
**Pull request by lz-coder**
This version of NoiseTorch is dead because of secutity breach, see: https://github.com/lawl/NoiseTorch.

### CODE REVIEW

**Comment by classabbyamp** [comment]
is there another upstream we can switch to?

**Comment by JamiKettunen** [comment]
Fwiw there's this community continued fork of the original project: https://github.com/noisetorch/NoiseTorch

I don't use the program personally (anymore) so I don't care what happens with it, just pointing out what I know.

**Comment by lz-coder** [comment]
Yes, the community continued the project, and audits were carried out, because of this security issue. I tried to update the template and build a package for this new version of the community but with no success.

**Comment by paper42** [comment]
What was the issue?

**Comment by lz-coder** [comment]
This new version relies on two git submodules to build.

**Comment by paper42** [comment]
That is not an issue

**Comment by lz-coder** [comment]
These two submodules don't have releases published, just git repos.
"Software need to be used in version announced by authors as ready to use by the general public - usually called releases. Betas, arbitrary VCS revisions, templates using tip of development branch taken at build time and releases created by the package maintainer won't be accepted."

**Comment by JamiKettunen** [comment]
Unfortunately for some programs not much can be done about that, if it's just submodules that don't have tags (but main repo does) it's generally fine to package it, it's just more maintenance burden. https://github.com/void-linux/void-packages/blob/master/srcpkgs/babashka/template is an example of a really unfortunate amount of vendored submodules.

We already have [`rnnoise`](https://github.com/void-linux/void-packages/blob/master/srcpkgs/rnnoise/template) packaged as well so maybe you could make use of `rnnoise-devel` to build against the distro packaging (which is up-to-date) and avoid the submodule for that at least; there is an upstream issue about creating a tag since late 2020: https://github.com/xiph/rnnoise/issues/137

**Pull request closed without merging**
