### PR TITLE
rmapi: update to 0.0.25

### PR DESCRIPTION
**Pull request by z0noxz**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, `x86_64-glibc`

### CODE REVIEW

**Comment by z0noxz** [comment]
The old version (0.0.22.1) doesn't work with the recent updates reMarkable did to their api, this new version (0.0.25) does (for now).

**Comment by paper42** [comment]
commit message should be rmapi: update to 0.0.25 (without v), you can use xbump to create the commit for you

**Comment by z0noxz** [comment]
I see, I used the earlier #40211 as a reference. Do you want me to change the commit name now, or is it for a future reference?

**Comment by z0noxz** [comment]
I think that did it... Had problem pushing to github.com as I normally don't use github as a service.

**Review by Vaelatern — APPROVED** [review]

**Pull request merged**
