### PR TITLE
libavif: enable encoding support

### PR DESCRIPTION
**Pull request by oreo639**
#### Testing the changes
- I tested the changes in this PR: **briefly**

Allows tests to pass for https://github.com/void-linux/void-packages/pull/42426

### CODE REVIEW

**Comment by lemmi** [comment]
Oh, so that was missing for `darktable` be able to export to `avif`. But I was wondering whether multiple encoders need to be enabled. I just glanced at the cmake file and didn't actually try and see what happens if only a single encoder is available:
```
-- Checking for module 'rav1e'
--   Found rav1e, version 0.6.3
-- Found rav1e: /usr/lib/librav1e.so (found version "0.6.3")
-- libavif: Codec enabled: rav1e (encode)
-- Checking for module 'SvtAv1Enc'
--   Found SvtAv1Enc, version 1.4.1
-- Found svt: /usr/lib/libSvtAv1Enc.so (found version "1.4.1")
-- libavif: Codec enabled: svt (encode)
-- Checking for module 'aom'
--   Found aom, version 3.5.0
-- Found aom: /usr/lib/libaom.so (found version "3.5.0")
-- libavif: Codec enabled: aom (encode/decode)
```

**Comment by oreo639** [comment]
You can specify the encoder you want to use (although it can fallback to other plugins).
https://github.com/AOMediaCodec/libavif/blob/647c3c208cf152395d777c1bf7240d2ecf7df5a9/include/avif/avif.h#L707-L715

For example, the kimageformats test fails if you don't provide libaom since ra1ve and libsvt-av1 provide a different binary output.

libaom is the most important since it is necessary for lossless, rav1e and libsvt-av1 are faster allow people to use them through libavif.

**Comment by lemmi** [comment]
`darktable` takes a ridiculous amount of time (several minutes) to export an image. I used `avifenc` to see what's up and the `libaom` codec seemed to perform ok, while the `rav1e` also took considerably longer with default settings. Wasn't able to test `svt`, since it only works on `yuv420`.
So, I'm still not sure what the value of the other codecs is, but I'm happy I can enable the `avif` format once this is merged.

**Comment by oreo639** [comment]
Actually you are right, rav1e is slower than libaom. My bad.

**Pull request merged**
