### PR TITLE
chromium: update to 84.0.4147.105. 

### PR DESCRIPTION
**Pull request by pbui**
- Built for x86_64 and x86_64-musl.
- Tested on x86_64.

- Drop unnecessary secure_getenv musl patch.

- Turn on js_optimize by default.

- Use system libvpx.

- Also update chromium-widevine and modify INSTALL to use `mktemp -d` instead of hardcoded path.

### CODE REVIEW

**Comment by pbui** [comment]
The js_optimize change was suggested by @Johnnynator and the musl change was suggested by @ericonr .

**Comment by q66** [comment]
can you find out of it's maybe possible to use system `libvpx`? we should have an up to date enough version now

**Comment by q66** [comment]
yup: please

1) rebase
2) change `post_extract` to `post_patch` while at this
3) add `libvpx-devel` to `makedepends`, then add `libvpx` to `system`
4) the body of `post_extract` could use some cleaning - first apply the musl patches (change conditional to `if [ "$XBPS_TARGET_LIBC" = "musl" ]`), then apply i686 patches separately (change the case to `i686*` from `i686`)

**Comment by pbui** [comment]
@q66 I have made the changes.  I've only tested building, I haven't run chromium with the linked libvpx yet... I will do so when my second build finishes in an hour or so.

**Comment by q66** [comment]
I have support for `ppc64le` lined up in my tree. I will merge that together with this later tonight

**Comment by Chocimier** [comment]
Closed by 8661b7571cc16a45e86f5154ca2edaed21eaca80.

**Pull request closed without merging**
