### PR TITLE
mpv-0.35.0

### PR DESCRIPTION
**Pull request by abenson**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, x86-64

[ci skip]

### CODE REVIEW

**Comment by 38github** [comment]
Great to see someone taking this on right away. Thank you!

**Comment by travankor** [comment]
The `waf3` build option can be switched to `meson`. I can look at that if you want that done in a separate PR.

**Comment by hazen2215** [comment]
sndio build option can be re-added.

**Comment by q66** [comment]
this should come with a build system switch to meson

**Comment by abenson** [comment]
Added `sndio` option and changed template to `meson`.

A few of the dependencies need some work.

- [X] celluloid
- [ ] minitube
- [X] mpc-qt
- [ ] orion
- [ ] plex-media-player
- [X] qimgv
- [ ] stremio-shell
- [ ] vidcutter

**Comment by abenson** [comment]
Alright, that leaves vidcutter, which I will open an issue with upstream, and orion, which is abandoned upstream.

**Comment by sgn** [comment]
Please remove `mpv.c` from the patches, that will keep the patch shorter.

**Pull request merged**
