### PR TITLE
alsa-lib and alsa-ucm-conf: update to 1.2.7.2

### PR DESCRIPTION
**Pull request by cinerea0**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by cinerea0** [comment]
Tested on a Thinkpad X1C7 running x86_64-GLIBC. As with any ALSA update, this will need testing on other architectures.

**Comment by paper42** [comment]
feel free to adopt alsa-lib

**Comment by CameronNemo** [comment]
Tested on an x86_64 system. Specifically tested with my external USB audio interface, which is working with this release but not without.

**Comment by motorto** [comment]
Tested on x86_64 and glibc and can confirm its working nicely @paper42

**Pull request merged**
