### PR TITLE
jdupes: update to 1.23.0, adopt; New package: libjodycode-2.0.1

### PR DESCRIPTION
**Pull request by cinerea0**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

### CODE REVIEW

**Comment by jbruchon** [comment]
Hey! I'm actually a Void user and noticed the repo was behind and discovered this. In libjodycode I changed the Makefile to fix this: https://github.com/jbruchon/libjodycode/commit/0a99bf3442fd509e77d7ea52e08efc9e202e44b0 - Thanks for finding this problem!

**Comment by leahneukirchen** [comment]
That fix is not sufficient for cross-compiling.

**Comment by leahneukirchen** [comment]
Doesn't work with clang e.g.

What about this?

```
true | $CC -dM -E - |grep __x86_64
```

**Comment by jbruchon** [comment]
@leahneukirchen I don't have Clang here to test with but I applied your suggestion and it's also working.

**Pull request merged**
