### PR TITLE
sof-firmware & sof-tools: update to 2.2

### PR DESCRIPTION
**Pull request by cinerea0**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by abenson** [comment]
Can you update `sof-tools` as well?

**Comment by classabbyamp** [comment]
#37712

does this supercede #38214 ?

**Comment by cinerea0** [comment]
> Can you update sof-tools as well?

That's a weird one. As Abby linked (#37712), their team didn't make the fixes Johnnynator was looking for, and I'm trying to find out what's still broken on their end and how to best communicate that. If you'd like I can put the update (without expanding the archs) in this PR, and work on fixing the issues separately for a revbump.

> does this supercede

Yes, because the commit history there is messy.

**Comment by classabbyamp** [comment]
> If you'd like I can put the update (without expanding the archs) in this PR, and work on fixing the issues separately for a revbump.

fine by me either way. do they need to be version-synced or anything?

**Comment by cinerea0** [comment]
I'm not sure, but I'd prefer not to risk something going wrong by them being out of sync.

**Comment by mayhair** [comment]
> > does this supercede
> 
> Yes, because the commit history there is messy.
hehe, i'm still quite new to git. anyway thank you for doing it in a better way 👍​
i'll be closing my pull request

**Pull request merged**
