### PR TITLE
MultiMC: update to 0.6.11.

### PR DESCRIPTION
**Pull request by SevereOverfl0w**

### CODE REVIEW

**Comment by fosslinux** [comment]
Hm, weird build failure! I did some looking for you, and I found this: https://github.com/MultiMC/MultiMC5/issues/2895.

It seems to be an [internal GCC issue](https://github.com/MultiMC/MultiMC5/issues/2895) and should be fixed if you use clang.

So I would add `clang` to hostmakedepends if XBPS_TARGET_ARCH is armv* and do `CC=clang` and `CXX=clang++` for the build.

**Comment by fosslinux** [comment]
Hm, weird build failure! I did some looking for you, and I found this: https://github.com/MultiMC/MultiMC5/issues/2895.

It seems to be an [internal GCC issue](https://github.com/MultiMC/MultiMC5/issues/2895) and should be fixed if you use clang.

So I would add `clang` to hostmakedepends if XBPS_TARGET_ARCH is armv* and do `CC=clang` and `CXX=clang++` for the build.

**Comment by SevereOverfl0w** [comment]
Paying a bit of attention, it looks like it was supposed to be disabled for armv*.  Line 15 should be MACHINE not ARCH.

**Comment by SevereOverfl0w** [comment]
I failed to get clang in place instead.  Setting it up with cmake & the correct cflags was too difficult for me.

I fixed the broken tag that was there before.

**Comment by fosslinux** [comment]
OH! silly me, so it is....

**Comment by q66** [comment]
don't put `\n` in `broken=`, just the github url is enough

**Comment by SevereOverfl0w** [comment]
@q66 should I use a space to separate build log & github url?

**Comment by q66** [comment]
no, just put in the github link

**Comment by SevereOverfl0w** [comment]
Done

**Pull request merged**
