### PR TITLE
New package: FreeTube-0.17.1

### PR DESCRIPTION
**Pull request by chloris-pale-green**
FreeTube is a privacy-focused desktop application for watching YouTube videos allowing for locally-stored history and subscriptions. Sadly, it is an Electron app, but has no real alternatives when privacy is a requirement.

This PR is also answering requests in #13420. The template is based on the AUR package [`freetube`](https://aur.archlinux.org/packages/freetube).

#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86_64-musl (masterdir, VM)
  - ARM architectures were not tested since Electron can not be cross-compiled

### CODE REVIEW

**Comment by chloris-pale-green** [comment]
Electron 19 is available only on x86_64. Restricted architectures to this subset.

**Comment by paper42** [comment]
> Electron 19 is available only on x86_64*. Restricted architectures to this subset.

You don't have to, if a dependency is not available, it won't be built.

**Comment by chloris-pale-green** [comment]
> You don't have to, if a dependency is not available, it won't be built.

Thank you for the advice. There is, indeed, `ERROR: FreeTube-0.17.1_1: this package cannot be built for aarch64` in the build log. I was puzzled by the succeeding PR checks but empty package file lists for these platforms.

I will remove the unnecessary architecture restriction.

**Comment by autoteelar** [comment]
i genuinely cant find it, whats the command to install it?

**Comment by autoteelar** [comment]
i cant find it in void-packages src or in octoxbps or using xbps-query, am i missing a repo?

**Comment by paper42** [comment]
This is not merged yet, checkout this branch and build it on your own with xbps-src or use a flatpak.

**Comment by autoteelar** [comment]
thanks paper, i figured it out, i was trying to build it, but i didnt realize my xbps-packages folder's srcpkgs was out of date. now i have it thanks!

**Pull request closed without merging**
