### PR TITLE
common/hooks/post-install/04-create-xbps-metadata-scripts.sh: fix return code of failed trigger runs

### PR DESCRIPTION
**Pull request by ahesford**
When a template defines `$triggers`, `xbps-src` writes an `INSTALL` script that will invoke the triggers. If the triggers fail, the test in

    [ $? -ne 0 ] && exit $?

will succeed and `exit` will be invoked. However, at the time `exit` is invoked, `$?` will take the value of *the test* `[ $? -ne 0 ]`, which is always `0` (or else the `&&` will short-circuit and the `exit` will not run).

The right thing to do is capture `$?` in a persistent variable, `$ret`, that can be tested and returned to properly forward the failure code through the trigger.

**NOTE**: This needs a bit of testing, because I don't yet understand the ramifications for `xbps-install` receiving a non-zero trigger return when all of them have returned `0` thus far.

### CODE REVIEW

**Comment by ahesford** [comment]
As pointed out in IRC by @sgn, a much more elegant approach is the just `|| exit` after each trigger invocation. The bare `exit` will forward the (failed) return code of the trigger out of the shell and we don't need to capture an intermediate variable.

While I'm poking around here, I also noticed that none of the trigger arguments are quoted. By convention none by `$CONF_FILE` should contain spaces, so this doesn't matter; also, no existing trigger uses the `$CONF_FILE` argument anyway. Nevertheless, should it ever become important, quoting the `$CONF_FILE` is a good idea since the configuration path provided by a user might contain spaces arbitrarily. I'm quoting everything else just in case.

**Review by ericonr — COMMENTED** [review]
This looks like it implements the correct behavior, but I'm not very familiar with this code, nor the ramifications.

I'd appreciate it if the commit included an example of a failure that the script didn't catch (maybe not really necessary), and the explanation for why things didn't work correctly with the previous version. Explaining the new mechanism neatly would also be helpful. Basically condense the PR description and your comment into the commit message ;)

**Comment by ahesford** [comment]
OK, I had some time to test this some more. I modied the `pycompile` trigger to always `exit 1` in place of the current `exit 0`, then tried installing an existing `python3-setuptools` package. (The existing package has the old `INSTALL` behavior that this PR fixes.)

With the existing behavior, the `INSTALL` script consumes all trigger failures. Failures in the triggers may or may not cause some information to be printed to stdout (this obviously depends on the trigger scripts), but XBPS never sees a nonzero return code. It happily reports a successful installation:
```
[...]
python3-setuptools-57.0.0_1: configuring ...
Byte-compiling python3.9 code for module _distutils_hack...
Byte-compiling python3.9 code for module pkg_resources...
Byte-compiling python3.9 code for module setuptools...
Updating ldconfig(8) cache...
python3-setuptools-57.0.0_1: installed successfully.

7 downloaded, 7 installed, 0 updated, 7 configured, 0 removed.
```
The `xbps-install` process returns `0` and the package `python3-setuptools` shows up as installed and configured (`ii`) in the output of `xbps-query -l`.

After rebuilding the `python3-setuptools` package to get an `INSTALL` script with fixed behavior, `xbps-install` instead reports
```
[...]
python3-setuptools-57.0.0_2: configuring ...
Byte-compiling python3.9 code for module pkg_resources...
Byte-compiling python3.9 code for module setuptools...
Byte-compiling python3.9 code for module _distutils_hack...
Updating ldconfig(8) cache...
ERROR: python3-setuptools-57.0.0_2: [configure] INSTALL script failed to execute the post ACTION: Operation not permitted
Transaction failed! see above for errors.
```
and returns `1`. While the package is installed, it remains in an unconfigured state (`uu` in the output of `xbps-query -l`). In fact, every package installed as part of the transaction remains unconfigured. Attempted to reconfigure the packages causes the same error and leaves the packages unconfigured. Running `xbps-reconfigure -a` will leave all unconfigured packages in the same unconfigured state. However, those packages with triggers that do not fail can be individually configured in separate transactions.

When removing a package, any removal triggers (like `pycompile` in this test) will report failure and abort the installation, leaving the package installed and whatever configuration state it was in before the removal. (Note that some part of the removal trigger may have run, so package state may have changed even though the package remains installed.) Even `xbps-remove -f` seems to fail here, so the package will be uninstallable as long as the removal hook fails.

Thoughts:
1. I think propagating the install errors through to XBPS is the right behavior, and leaving the packages unconfigured is also correct. The configuration failed, so the package shouldn't be marked configured. However, who knows how many triggers leak unexpected nonzero returns harmlessly? We don't know.
2. Propagating the nonzero return on *remove* seems a bit risky here. The package will be effectively uninstallable until (or if) the removal hook can be run without errors. It's probably better to just swallow the error and allow the removal to proceed. I've updated the change to impose this behavior.
3. This behavior won't take effect in packages until they are rebuilt with the new `xbps-src` hook. I don't think there's a need to bulk rebuild everything; the fix can leak in by attrition.

**Comment by ahesford** [comment]
My testing shows that this fix has broader ramifications than I'd originally thought---properly honoring the return code on remove and preventing package uninstallation seems bad---so I'd like more input from @void-linux/pkg-committers before moving forward.

**Comment by Duncaen** [comment]
I think we'll have to fix xbps to not abort transactions on non 0 exits, its a bad idea in general because it leaves the pkgdb in a bad state and we already have a `half-installed` package state for this, but it would be currently only set for the last package which would abort the update/install with `exit 1` or if `XBPS_TARGET_ARCH` is stet.

**Comment by ahesford** [comment]
Given the potential pitfalls of honoring the return code without a corresponding fix in XBPS, I'm binning this for now.

**Pull request closed without merging**
