### PR TITLE
plex-media-player: remove deprecated opengl-cb API, use libmpv Render API

### PR DESCRIPTION
**Pull request by zdykstra**

### CODE REVIEW

**Comment by zdykstra** [comment]
Both of the failures seem to be expected:

`arm*) nocross="Qt5Webengine is not aviable for 32bit cross"`

**Comment by ericonr** [comment]
Hm, need to fix that CI step, it errors out because the package wasn't built, which is fine.

**Comment by ericonr** [comment]
That said, feel free to remove the `broken` for arm, it should be detected automatically.

**Comment by zdykstra** [comment]
> That said, feel free to remove the `broken` for arm, it should be detected automatically.

`nocross` removed. This should be good to go, assuming it builds find on the arm builders.

**Pull request merged**
