### PR TITLE
passwordsafe: update to 1.08.1BETA

### PR DESCRIPTION
**Pull request by yopito**

### CODE REVIEW

**Comment by Johnnynator** [comment]
@yopito The build is failing for i686 and armv7l

**Comment by yopito** [comment]
yep, have to fix it.

**Comment by yopito** [comment]
fixed 32bit build but I'm not yet 100% confident about the corresponding patch.

**Comment by pullmoll** [comment]
@yopito You cannot test for a `typedef <some_type> __time64_t;` with `#if !defined(__time64_t)` because the typedef is not a macro. You could perhaps try to include `<linux/time.h>` and `typedef __kernel_time64_t __time64_t;` but I have no idea how to avoid a conflicting typedef.

**Comment by yopito** [comment]
@pullmoll: I agree; in fact, `__time64_t` is **both** a typedef and a macro, and the macro is defined only on 64bit platform :(

Opened an issue's upstream: https://github.com/pwsafe/pwsafe/issues/563

**Comment by yopito** [comment]
switched to upstream's patch. runtime tests are fine. Let's merge

**Pull request merged**
