### PR TITLE
wxPython4: update to 4.0.6

### PR DESCRIPTION
**Pull request by RunningDroid**
I switched do_build from setup.py to build.py because build.py compiles some libraries that setup.py doesn't (despite what the docs say.)

### CODE REVIEW

**Comment by RunningDroid** [comment]
The most recent force-push fixes $license not conforming to the SPDX spec, but xlint doesn't know that because it doesn't implement that part of the spec.

Also the armv7l, armv6l-musl, and aarch64-musl builds fail when waf tries testing the C compiler because (at least in armv7l's case) CFLAGS picks up a -mtune=generic somewhere and -mtune=generic isn't supported for that target (it needs to be -mtune=generic-armv7-a.)

**Comment by Hoshpak** [comment]
d75660c34351ab04ca09a991efac50d13c86a4c7

**Comment by RunningDroid** [comment]
@Hoshpak Did you mean to link to a different commit?

**Comment by Hoshpak** [comment]
Indeed, copy & waster error. I meant ab41c3bf18aacc23460152dcdb84a81bc910dffc.

**Pull request closed without merging**
