### PR TITLE
nextcloud-client: update to 3.1.0

### PR DESCRIPTION
**Pull request by yopito**

### CODE REVIEW

**Comment by yopito** [comment]
test #32 fails with GH actions, can't reproduce locally, since all tests are OK.  
I will push force to trigger another build

**Comment by yopito** [comment]
fail again. code of test 32:
```
113 static void check_csync_vio_opendir_perm(void **state)
114 {   
115     auto *csync = (CSYNC*)*state;
116     csync_vio_handle_t *dh = nullptr;
117     int rc = 0;
118     mbchar_t *dir = c_utf8_path_to_locale(CSYNC_TEST_DIR);
119     
120     assert_non_null(dir);
121     
122     rc = _tmkdir(dir, (S_IWUSR|S_IXUSR));   /* macro: => mkdir(dir, (S_IWUSR|S_IXUSR)) */
123     assert_int_equal(rc, 0);
124 
125     dh = csync_vio_opendir(csync, CSYNC_TEST_DIR);
126     assert_null(dh);
127     assert_int_equal(errno, EACCES);
128 
129     _tchmod(dir, MKDIR_MASK);
130     c_free_locale_string(dir);
131 }
```
The default umask is probably kind of special in GH actions's container, that would explain this (unrelevant) error ?

**Comment by ericonr** [comment]
If you feel like trying it, you could use `umask` from inside the shell to see if it works? Or just disable/patch the test to do that.

**Comment by ericonr** [comment]
Don't think we should hold the update on this test. Maybe for next release :) 

Also corrected a tiny typo.

**Comment by yopito** [comment]
@ericonr : thanks for the typo fix and the merge.

**Pull request closed without merging**
