### PR TITLE
iperf: update to 2.1.4.

### PR DESCRIPTION
**Pull request by tornaria**
#### Have the results of the proposed changes been tested?
- I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by tornaria** [comment]
On CI there are two test failures (tcp6 and udp6) but everything passes on my box (tested x86_64, x86_64-musl, i686).

**Comment by paper42** [comment]
In that case, either add `make_check=ci-skip` or patch out the failing tests if there is only a few of them.

**Comment by tornaria** [comment]
> In that case, either add `make_check=ci-skip` or patch out the failing tests if there is only a few of them.

All the tests pass when I run in my box. Two of the tests fail when run on ci (the tests or tcp6 and udp6). Should I *conditionally* disable these two only when run in CI? How can I know when I'm running on CI?

**Comment by paper42** [comment]
> > In that case, either add `make_check=ci-skip` or patch out the failing tests if there is only a few of them.
> 
> All the tests pass when I run in my box. Two of the tests fail when run on ci (the tests or tcp6 and udp6). Should I _conditionally_ disable these two only when run in CI? How can I know when I'm running on CI?

It will be easier to disable them in all situations, even outside CI.

**Comment by tornaria** [comment]
I added a patch to skip IP6 tests when IP6 is not available. Now all tests pass on my box (which has ip6 enabled) and on CI the two tests are skipped (since ip6 is disabled).

**Pull request merged**
