### PR TITLE
noise-repellent: update to 0.1.5.

### PR DESCRIPTION
**Pull request by UsernameRandomlyGenerated**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
They need to fix their build:

```
 aarch64-linux-gnu-gcc: error: unrecognized command-line option '-msse'
aarch64-linux-gnu-gcc: error: unrecognized command-line option '-msse2'
aarch64-linux-gnu-gcc: error: unrecognized command-line option '-mfpmath=sse'
```

Specifically, https://github.com/lucianodato/noise-repellent/blob/master/meson.build#L23 is just wrong.

It's not build machine that matters, it's the `host_machine`, and checking if `arch` isn't `aarch64` to enable x86_64 only optimization is also wrong, since they should be checking if arch is `x86_64`. I might make a PR their way later to fix this.

**Comment by ericonr** [comment]
https://github.com/lucianodato/noise-repellent/pull/77

**Comment by UsernameRandomlyGenerated** [comment]
Should I just add your commits as patches in this PR as developer doesn't seem very active?

**Comment by ericonr** [comment]
Yeah probably. https://patch-diff.githubusercontent.com/raw/lucianodato/noise-repellent/pull/77.patch

**Comment by ericonr** [comment]
Hm, you might have to fold that PR into a single diff, or I guess just import two separate patches (and add ordering to them, so `01-foo.patch` and `02-bar.patch`)

**Comment by UsernameRandomlyGenerated** [comment]
It's weird, even if I add only the first commit as patch the result is the same error.

**Comment by ericonr** [comment]
I can try to provide you a proper diff. I guess there must have been a big change in the file between the release and my PR.

**Comment by ericonr** [comment]
Can you make a patch based on mine for the 0.1.5 release? It seems they changed the file a bunch.

**Comment by UsernameRandomlyGenerated** [comment]
Done, it should work now.

**Pull request merged**
