### PR TITLE
gdb: add multiarch build option

### PR DESCRIPTION
**Pull request by Piraty**
#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Is this an RFC for enabling it by default as well?

**Comment by Piraty** [comment]
could be, do you think it's useful enough for everyone else to waste additional 24M on their machines? ;)

**Comment by ericonr** [comment]
I feel like multiarch `binutils` by default can be more useful than this one, since remote debugging isn't exactly that common... I do use `cross-arm-none-eabi-gdb` here (which idk if this even replaces, since that's not a hosted platform), but I don't think I'm in the majority.

At least for now, might be better to keep it disabled by default.

**Comment by Piraty** [comment]
I used it to debug an aarch64 binary on my x86 host (with help of `qemu -g`) so it was helpful to me at least.

**Pull request merged**
