### PR TITLE
gxi: update to 0.8.1

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by jnbr** [comment]
Now it's not rustc failing anymore but:
```
meson.build:25:0: ERROR: Program(s) ['glib-compile-resources'] not found or not executable
```

**Comment by Cogitri** [comment]
Oops, should make that a native dep, thanks for the heads up.

**Comment by Cogitri** [comment]
Seems like it works now, but SIGSEVs on aarch64-musl

**Comment by Cogitri** [comment]
Uh...ping?

**Comment by jnbr** [comment]
> Uh...ping?

Sorry, forgot about it.

Let's see if the builder manage to build it ...

**Comment by Cogitri** [comment]
Thanks :)

**Comment by jnbr** [comment]
Well, it didn't work. Marked is as broken for musl.

**Comment by Cogitri** [comment]
Oh, gtk-rs is still good at blowing up rustc apparently :c

**Pull request merged**
