### PR TITLE
New package: vimtex 2.4

### PR DESCRIPTION
**Pull request by dkwo**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by FollieHiyuki** [comment]
Isn't it more ideal to install this with `vim-plug`, or manually with built-in vim package system?

**Comment by dkwo** [comment]
Well, I'd like to use XBPS to manage it.

What worries me: what happens if there are other vim plugins that write to the folder /usr/share/vim/vimfiles, perhaps with similar or identical names to the ones this plugin writes?

**Comment by FollieHiyuki** [comment]
It would probably be overwritten.

**Comment by dkwo** [comment]
What is the correct way to copy folders, such that if a folder already exists you just add to its content, without overwriting?

**Comment by Chocimier** [comment]
> Well, I'd like to use XBPS to manage it.

Why?

**Comment by dkwo** [comment]
For the same reason I manage other packages with the package manager: it's simpler to update, remove, keep track of files, etc.

**Comment by Chocimier** [comment]
Then sorry, but we are not going to maintain everyone's favourite text editor plugin. Use vundle or similar, they have updates.

> what happens if there are other vim plugins that write to the folder /usr/share/vim/vimfiles, perhaps with similar or identical names to the ones this plugin writes?

The same what happens for `/usr`: directories are merged, files are overwritten.

Note, that xbps expects to be only writer to `/usr` - with exception of `/usr/local`.

**Pull request closed without merging**
