### PR TITLE
[squashfs-tools]: do not create symlinks manually

### PR DESCRIPTION
**Pull request by firasuke**
These symlinks are created automatically upon installation.

#### Testing the changes
- I tested the changes in this PR: **NO**

### CODE REVIEW

**Comment by classabbyamp** [comment]
what do you mean by "created automatically upon installation"?

**Comment by firasuke** [comment]
`make install` should handle both binary installation and symlink creation, yet it seems you are doing manual installation.

**Comment by classabbyamp** [comment]
if that's the case, then your patch is wrong: you're just removing the symlinks from the package altogether

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/commit/d29d187fda697d0c601aabeceb4ce8ebe87967db does it the right way

**Comment by firasuke** [comment]
> if that's the case, then your patch is wrong: you're just removing the symlinks from the package altogether

Ah I see, you were not using `make install` in the first place, and the manual binary installation should also be removed, makes sense.

**Pull request closed without merging**
