### PR TITLE
New Package: windscribe-cli-1.3

### PR DESCRIPTION
**Pull request by rivularis**

### CODE REVIEW

**Comment by Chocimier** [comment]
If it is GPL licensed, I would prefer to build from source.

**Comment by rivularis** [comment]
Build from source as in from github? All I can find that windscribe supplies is the prebuilt binaries in deb and rpm format.

**Comment by Chocimier** [comment]
> Build from source as in from github?

Just like that.

> All I can find that windscribe supplies is the prebuilt binaries in deb and rpm format.

I can't find that too, so it should be checked whether it is GPL'd and one will get source on mail request or other license, and package needs some changes.

**Comment by rivularis** [comment]
ok, I emailed them for access and waiting on a reply for source access.

**Comment by Chocimier** [comment]
> ok, I emailed them for access and waiting on a reply for source access.

Great!

**Comment by rivularis** [comment]
The following is what I received from their support.. 

"We may choose to open source some or all of our apps in the future, but for now, they are closed source. This is due to us using various unblocking techniques that would be exposed and countered if we were to open source the apps. Many countries and networks actively block Windscribe, so for now, the need to stay on top of that outways the benefits of open source."

So it appears the only way to build is via the deb file.

What were the changes I need to make to the package?

**Comment by Chocimier** [comment]
Unfortunately. as there is no license for this program (other than false note on GPL), this is not suitable to be included into repository. You can still update, build and install this for yourself.

**Comment by kiarash96** [comment]
Hi. I'm relatively new to void so forgive me if I'm wrong. But is it possible to include this in the restricted nonfree repository? That way people can access the up-to-date template more easily.

**Pull request closed without merging**
