### PR TITLE
sip: update to 4.19.23

### PR DESCRIPTION
**Pull request by yoctocell**

### CODE REVIEW

**Comment by PaperMountainStudio** [comment]
@yoctocell could you remove lines starting with `pycompile_module` as xlint tells you to? This is the only thing why CI didn't succeed.

**Comment by PaperMountainStudio** [comment]
I have been running this version for 6 days and I can confirm it works (glibc, x86_64).

**Comment by sgn** [comment]
Is sip this project? https://pypi.org/project/sip/#description

It's updated to `5.3.0` in PyPI, my IP range is being banned from river computing.

**Comment by PaperMountainStudio** [comment]
This is the same project, but I don't know if the series 5 is compatible with series 4. New versions are available only through PyPi. They also dropped Python2 support with 5.0.0.

**Pull request closed without merging**
