### PR TITLE
[RFC] xbps-src: default XBPS_MAKEJOBS to `nproc`

### PR DESCRIPTION
**Pull request by classabbyamp**
previously this defaulted to 1. In some rare cases, nproc is not desirable, but that can be easily overriden in the standard ways, etc/conf or -jN.

For compatibility with other distros, it defaults to 1 when nproc is not available.

#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by abenson** [comment]
I kind of support this.  I just wonder what the default should be; all cores, some cores, or specified cores.

**Comment by dataCobra** [comment]
Could we use the amount of cores divided by two?

I support this also, but I feel like defaulting to all cores is a bit too much?

**Comment by jcgruenhage** [comment]
I think `nproc` would be a good default. I usually run with `-j 16` on my laptop, and it's rarely a problem. The only times when I run into trouble is not due to CPU load either, but because I'm exhausting memory (which has been solved by going 16->64gig) or exhausting disk space.

**Comment by ahesford** [comment]
I've seen plenty of historical recommendation for spawning twice as many jobs as CPUs with make, so defaulting to nproc seems reasonable. People with SMT CPUs will have the "right" value, and those without get a reduced "compromise" value.

**Comment by dataCobra** [comment]
Most of the time I'm building stuff while doing other things on my machines. As I mentioned above I still feel like defaulting to all cores is a bit too much.

On some of my machines multi tasking would no longer be possible.

**Comment by vincele** [comment]
Was wondering the other day why this defaults to no parallelism (void newbie here).
LGTM

**Review by leahneukirchen — APPROVED** [review]

**Pull request merged**
