### PR TITLE
mpdevil: rename to plattenalbum, update to 2.2.1

### PR DESCRIPTION
**Pull request by voidisnull**
This package's upstream has been shifted to [plattenalbum](https://github.com/SoongNoonien/plattenalbum)

### CODE REVIEW

**Review by classabbyamp — CHANGES_REQUESTED** [review]
rename the package then, don't remove it

**Comment by voidisnull** [comment]
Sure

But can you help me with it, I have created the template for plattenalbum as

```
# Template file for 'plattenalbum'
pkgname=plattenalbum
version=2.2.1
revision=1
build_style=meson
hostmakedepends="gettext pkg-config glib-devel gtk4-update-icon-cache desktop-file-utils"
makedepends="gtk4-devel libadwaita-devel python3-devel"
depends="python3-mpd2 python3-gobject"
short_desc="Simple music browser for MPD"
maintainer="Orphaned <orphan@voidlinux.org>"
license="GPL-3.0-or-later"
homepage="https://github.com/SoongNoonien/plattenalbum/"
distfiles="https://github.com/SoongNoonien/plattenalbum/archive/refs/tags/v$version.tar.gz"
checksum=38495a0989f3a5b8049e2ec0a17bfb94ea60ab892ec001ac2f12a9e9a6c4f80b
```
<br/>
<br/>

With this template I'm getting an errors 
When I build this for x86_64, I get this error which I have no idea about
```
=> ERROR: plattenalbum-2.2.1_1: failed to install target dependencies! (error 8)
soundtouch-2.3.2_1: broken, unresolvable shlib `libmvec.so.1'
Transaction aborted due to unresolved shlibs.
=> ERROR: Please see above for the real error, exiting...
```
I have tried to add soundtouch-devel but it doesn't makes any difference

**Comment by chrysos349** [comment]
> have created the template for plattenalbum

 - remove `python3-devel` from `makedepends`
 - add `changelog="https://github.com/SoongNoonien/plattenalbum/releases"`
 -  add `mpd` to depends
 - add transitional pkg
 ```sh
mpdevil_package() {
	build_style=meta
	short_desc+=" - transitional dummy package"
	depends="${sourcepkg}>=${version}_${revision}"
}
```

**Comment by chrysos349** [comment]
> I'm pretty new to all this stuff

look at other templates in `srcpkgs` dir. study the [guide](https://xbps-src-tutorials.github.io/). that's how you will learn.

>  but it still gives the same error when building for x86_64

it works on my machine. check your void installation. google the issue.

> could you please explain me where I need to add transitional pkg in mpdevil/template or plattenalbum/template
```sh
cd srcpkgs
rm -r mpdevil
ln -s plattenalbum mpdevil
```
then add that section to the end of `plattenalbum/template`

**Comment by voidisnull** [comment]
@chrysos349 
<br/>
Thank you so much
I really appreciate your inputs

**Pull request merged**
