### PR TITLE
pinephone-kernel: update to 6.1.3.

### PR DESCRIPTION
**Pull request by jcgruenhage**
#### Testing the changes
- I tested the changes in this PR: **YES**

This new kernel version finally makes the keyboard case work. I've compiled it locally and created a fresh image with void-mklive, which I've tested on my Pinephone together with the keyboard case, and it all works as expected.

### CODE REVIEW

**Comment by sgn** [comment]
mainline `6.1.3` has broken ext4, please update to `6.1.4`

**Comment by JamiKettunen** [comment]
@sgn Hm is this a known issue? there isn't a new 6.1.4+ -based tag yet on https://github.com/megous/linux/tags, so I suppose staying with the v6.1.2-based `orange-pi-6.1-20230102-1102` tag should be fine too right?

**Comment by sgn** [comment]
> @sgn Hm is this a known issue? 

Yes, https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.4

> so I suppose staying with [the v6.1.2-based `orange-pi-6.1-20230102-1102` tag](https://github.com/megous/linux/releases/tag/orange-pi-6.1-20230102-1102) should be fine too right?

`6.1.2` has problems with lvm, I'm not sure.

**Comment by jcgruenhage** [comment]
solution is clear: There is now a 6.1.7 tag, which I can base this on ^^

**Comment by jcgruenhage** [comment]
And it works just fine, keyboard and all ^^

**Comment by JamiKettunen** [comment]
@jcgruenhage I know this isn't exactly the best place to write about this but if you don't mind could you check what configs Waydroid needs to work on the PinePhone? these should be mandatory for running the Android OS itself in LXC container, but extra things are most likely needed to setup the networking:
```
CONFIG_PSI=y
# CONFIG_PSI_DEFAULT_DISABLED is not set
CONFIG_ANDROID_BINDER_DEVICES=""
```
(the last one isn't mandatory but those default nodes aren't required since [`ANDROID_BINDERFS`](https://cateee.net/lkddb/web-lkddb/ANDROID_BINDERFS.html) is enabled for runtime binder configuration)

As a reference you can mostly just use `pmbootstrap kconfig check --waydroid --file <path to .config>` (maybe also check against `--container` if there's still issues)

**Comment by Piraty** [comment]
i'd say not running Android on a pinephone is a feature, but meybe i'm weird

**Pull request merged**
