### PR TITLE
New package: portablemc-3.2.0

### PR DESCRIPTION
**Pull request by JamiKettunen**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

### CODE REVIEW

**Comment by classabbyamp** [comment]
this all seems to be in the same repo. could it be split up with subpackages?

**Comment by JamiKettunen** [comment]
@classabbyamp Indeed, I was wondering the same thing too. There is https://github.com/mindstorm38/portablemc/blob/master/src/workspace.py which is mainly "intended for development" but maybe we could re-use it somehow as per https://github.com/mindstorm38/portablemc#setup-environment

**Comment by classabbyamp** [comment]
maybe @icp1994 has a suggestion? they do lots of python packaging

**Comment by icp1994** [comment]
Looking at the add-ons, they seem to be developed and released independently of each other and the core. The upstream monorepo setup is likely just for convenience. So I'd say the add-ons are probably better off as separate packages rather than sub-packages.

**Comment by JamiKettunen** [comment]
I've dropped the `virtual?java-runtime` dependency of `portablemc` as it'll download Mojang provides JVM binaries by default which I've mentioned in the `README.voidlinux`. I've also filed https://github.com/mindstorm38/portablemc/issues/110 regarding the current behaviors under `musl` after testing under `x86_64-musl`.

**Comment by JamiKettunen** [comment]
Drafting until [version 3.2.0](https://github.com/mindstorm38/portablemc/pull/115) is released, it contains some improvements that make it trivial to start the game under `x86_64-musl` & `aarch64-musl` systems which I could test as well which I'll document the relevant pieces about in `README.voidlinux`.

**Comment by JamiKettunen** [comment]
Drafting once more as Python 3.11 upgrade broke the `portablemc-console` add-on: https://github.com/mindstorm38/portablemc/issues/124

On another note I could exclude that package for now if someone wants to review this again and could merge it :)

**Pull request closed without merging**
