### PR TITLE
[RFC] wpa_supplicant: update to 2.8.

### PR DESCRIPTION
**Pull request by pbui**
Drop unnecessary rebased and libressl patches.

Tested with WPA2 and WPA-EAP.

Followup to #5435.  Need to check that #5413 doesn't happen.

### CODE REVIEW

**Comment by xaltsc** [comment]
Works for me with eduroam.

**Comment by shizonic** [comment]
Same here. 👍 Works. Thank you @pbui

**Comment by renatoaguiar** [comment]
:+1:  Works for me with `key_mgmt=WPA-EAP eap=TLS`.

**Comment by steinex** [comment]
👍 Success with WPA 2 Enterprise, Phase 1 EAP-TTLS, Phase 2 MS-CHAPv2.

**Comment by Gottox** [comment]
Yolo! :laughing:

**Pull request merged**
