### PR TITLE
New package: RcloneBrowser-1.7.0

### PR DESCRIPTION
**Pull request by zdykstra**

### CODE REVIEW

**Comment by Chocimier** [comment]
Will merge, but please update.
It's MIT licensed now.

**Comment by zdykstra** [comment]
This is up to 1.7.0 - fixed the license and bumped the version as well.

**Comment by Piraty** [comment]
i still think `rclone-browser` would have been a better name...

**Comment by zdykstra** [comment]
I'm fine renaming it - I just thought we followed the name the software
calls itself. rclone-browser is probably more discoverable...

**Pull request merged**
