### PR TITLE
nim: update to 2.0.0

### PR DESCRIPTION
**Pull request by IcedQuinn**
#### Testing the changes
- I tested the changes in this PR: **briefly**

Confirmed that compiler runs and used it to compile one of my projects.

#### Local build testing
- I built this PR locally for my native architecture, (amd64-glibc)

#### External dependencies
They are still trying to pull git repos from masters during a build--even in the stable release. I've patched around this by adding the latest checkout as of today (20230816) and the Github download links for those. This gets us what appears to be a working copy but I will need to bonk the devs up there to stop doing this.

### CODE REVIEW

**Comment by icp1994** [comment]
https://github.com/void-linux/void-packages/pull/45597

**Comment by IcedQuinn** [comment]
is there some kind of issue i need to resolve to move this along?

**Comment by IcedQuinn** [comment]
:eyes:

**Comment by IcedQuinn** [comment]
updated to appease #46078

**Comment by IcedQuinn** [comment]
time for the fri-daily signs of life update :wave:

**Pull request merged**
