### PR TITLE
thunderbird(-i18n): update to 128.2.3esr.

### PR DESCRIPTION
**Pull request by dataCobra**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86_64-musl
  - i686
  - aarch64 (cross)
  - armv7l (cross)
  - armv7l-musl (cross)

[ci skip]

### CODE REVIEW

**Comment by classabbyamp** [comment]
commit message should match version. have you tested cross-compiling?

**Comment by dataCobra** [comment]
Commit message is using the correct version name.

Cross-Compilation I didn't test yet but can do tomorrow. :)

**Comment by classabbyamp** [comment]
if that's the correct version, then it should be what's in the template

**Comment by dataCobra** [comment]
Sorry maybe I misunterstood.

The version in the template is the same as in the commit message which is also the name of the version internal at thunderbird.

**Comment by dataCobra** [comment]
I see my error now, sorry.

I'll correct it tomorrow as well.

**Comment by dataCobra** [comment]
Here is what I did:

1. Rename both commits with the correct version.
2. Successful cross-compilation for aarch64, armv7l and armv7l-musl

**Pull request closed without merging**
