### PR TITLE
New package: python3-tldextract-2.2.2

### PR DESCRIPTION
**Pull request by Eluminae**

### CODE REVIEW

**Comment by Chocimier** [comment]
We do not accept new py2 stuff, make it py3-only under name tldextract or python3-tldextract.

Looks like it is missing some deps, did you test whether it runs?

**Comment by Eluminae** [comment]
Okay I trimmed the python2 part and only leave the python3 module.
Which dependencies do you mean? I can't find them and the module seems to work in my machine.

**Comment by Chocimier** [comment]
> Which dependencies do you mean? I can't find them and the module seems to work in my machine.

Running inside zap-ed ./xbps-src chroot shows it's at least setuptools and (not-packed?) request-file.

**Comment by Eluminae** [comment]
> Running inside zap-ed ./xbps-src chroot shows it's at least setuptools and (not-packed?) request-file.

Okay, the Arch packaging seems to confirm this and others. I'll add them!

**Comment by Chocimier** [comment]
There is no need to depend on python3 when depending on some python3 module, similarly for other obvious transitive deps.

**Pull request merged**
