### PR TITLE
leftwm: update to 0.5.1.

### PR DESCRIPTION
**Pull request by caughtquick**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by leahneukirchen** [comment]
Needs a patch to support 32-bit platforms.

**Comment by 0323pin** [comment]
Any progress on this?
The needed patch can be found [here](https://github.com/leftwm/leftwm/pull/1202/files).

I'm using it on [NetBSD builds](http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/wm/leftwm/patches/patch-display-servers_xlib-display-server_src_xwrap_setters.rs?rev=1.1&content-type=text/x-cvsweb-markup) and it's working.

**Comment by caughtquick** [comment]
will get to it shortly, thanks

**Comment by 0323pin** [comment]
Thanks!

**Comment by pondichys** [comment]
Greetings, I was busy creating a new PR to update leftwm when I realized this one existed ... I would really like to fix this so I checked out this PR and tried to apply the patch. The problem is that in the mean time, xbps-src has been changed and when I try to build the updated leftwm package from the PR branch, xbps-src displays the following error.

```bash
./xbps-src -a armv7l pkg leftwm
neither chroot-git or git are available in your system!
```
When I switch to my own branch, I can build for armv7l without problem with the help of the patch.

As I'm a noob concerning this kind of issue, could you give me some directions on how to proceed further?

Kind regards.
Seb

**Comment by tranzystorekk** [comment]
Completed in #51615

**Pull request closed without merging**
