### PR TITLE
[WIP] GHC 8.10.7

### LINKED ISSUE #6414: Can't customize XMonad
### System

* xuname: Void 4.19.12_1 x86_64 GenuineIntel uptodate rrrmFFFFFF
* package: xmonad-0.15_1, xmonad-contrib-0.15_1

### Expected behavior

When below is in `~/.xmonad/xmonad.hs`, `xmonad --recompile` should give no output and successfully compile (https://hackage.haskell.org/package/xmonad-contrib-0.15/docs/XMonad-Doc-Configuring.html).

```haskell
   import XMonad

   main = xmonad $ def
       { borderWidth        = 2
       , terminal           = "urxvt"
       , normalBorderColor  = "#cccccc"
       , focusedBorderColor = "#cd8b00" }
```

Additionally, the `xmonad-contrib` package should have more files in it than just the license.

### Actual behavior

With haskell snippet above in `~/.xmonad/xmonad.hs`:

```
$ xmonad --recompile
XMonad will use ghc to recompile, because "/home/adam/.xmonad/build" does not exist.
Error detected while loading xmonad configuration file: /home/adam/.xmonad/xmonad.hs

xmonad.hs:1:1: error:
    Could not find module ‘XMonad’
    Use -v to see a list of the files searched for.
  |
1 | import XMonad
  | ^^^^^^^^^^^^^

Please check the file for errors.
```

And the files in xmonad-contrib are:

```
$ xbps-query -Rf xmonad-contrib
/usr/share/licenses/xmonad-contrib/LICENSE
```

Any ideas @xaltsc?

### Steps to reproduce the behavior

1. Install xmonad.
2. Create `~/.xmonad/xmonad.hs` with config shown above.
3. `xmonad --recompile`

### PR DESCRIPTION
**Pull request by slotThe**
The 8.10.x release flood seems to have stopped; time for the fun part to begin!

- [x] ghc
- [ ] ghc-bin
    - [x] x86_64-musl (**Not uploaded to alpha.de yet** [Link](https://www.mediafire.com/file/i2385lbvjbmzx3l/ghc-8.10.7-x86_64-void-linux-musl.tar.xz/file))
    cc @q66 for the following
    - [ ] ppc64le
    - [ ] ppc64le-musl
- [x] cabal-install
- [x] stack

Rebuild literally every single haskell package we have and see if anything's broken:

- [x] git-mediate
- [x] kmonad
- [x] cgrep
- [x] debug-me
- [x] hlint
- [x] hoogle
- [x] darcs
- [x] shellcheck
- [x] git-annex
- [x] hledger
- [x] pandoc
- [x] xmobar
- [x] haskell-language-server

Other things to do:

- [x] Merge https://github.com/void-linux/void-packages/pull/33749

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

[ci skip]

### CODE REVIEW

**Comment by xaltsc** [comment]
Just fyi If you haven't skimmed through the issue concerning xmonad and xmobar, I've abandonned the maintainership of xmo* because I'm clearly incompetent in these matters.

**Comment by slotThe** [comment]
Oh, right; I should have probably checked out the issue again.  Then this is essentially waiting for https://github.com/void-linux/void-packages/pull/33749 to be merged

**Comment by Chocimier** [comment]
xmonad removal in #33749 is merged.

**Comment by slotThe** [comment]
(rebased for shellcheck)

**Comment by slotThe** [comment]
@q66 I'll be rebuilding the core stack (heh) on musl one more time this coming week, but apart from that I think only the ppc stuff is still outstanding

**Comment by slotThe** [comment]
(rebased on top of `master`)

Also friendly ping @q66

**Comment by q66** [comment]
oh, you should've pinged me sooner about this, i had too much to do and entirely forgot about this one...

**Comment by slotThe** [comment]
Tbh I also completely forgot about this due to holidays and some other things happening, so no worries :)

**Comment by q66** [comment]
can you rebase this? i will build it once that's done, and we can finally get it merged

**Comment by slotThe** [comment]
> can you rebase this? i will build it once that's done, and we can finally get it merged

Sorry for the delay; should be done now!

**Pull request closed without merging**
