### PR TITLE
intltool: avoid process race

### PR DESCRIPTION
**Pull request by ndowens**

### CODE REVIEW

**Comment by Cogitri** [comment]
Is this patch upstream?

**Comment by ndowens** [comment]
https://bazaar.launchpad.net/~intltool/intltool/trunk/revision/748?start_revid=748

**Comment by Cogitri** [comment]
Might be a good idea to add that to the patch as a patch header then

**Comment by ndowens** [comment]
> Might be a good idea to add that to the patch as a patch header then

Added

**Pull request merged**
