### PR TITLE
hg-git: update to 1.0.2.

### PR DESCRIPTION
**Pull request by Luciogi**
#### Testing the changes
- I tested the changes in this PR: **YES**
#### Local build testing
- I built this PR locally for my native architecture, (x86_64-GLIBC)

### CODE REVIEW

**Comment by Luciogi** [comment]
I checked their CI pipeline, it is using python3.11

**Comment by ahesford** [comment]
Upstream testing with Python 3.11 is not sufficient reason to ignore test failures here. You need to understand that nature of the failing tests and skip them with an explanation about why they are not cause for concern.

**Comment by icp1994** [comment]
You could try the upstream [patch](https://foss.heptapod.net/mercurial/hg-git/-/commit/9a52223a95e9821b2f2b544ab5a35e06963da3f1).

**Comment by Luciogi** [comment]
@icp1994  thanks for patch link :)

**Pull request closed without merging**
