### PR TITLE
New package: font-cm-unicode-otf-0.7.0

### PR DESCRIPTION
**Pull request by emacsomancer**

### CODE REVIEW

**Comment by Chocimier** [comment]
We do not want more eyecandy in repo. You can always put it into ~/.fonts.

**Comment by emacsomancer** [comment]
> We do not want more eyecandy in repo. You can always put it into ~/.fonts.

I'm not sure how fonts are 'eyecandy' and there are a number of fonts in the repos which seem to be updated.

**Comment by Chocimier** [comment]
There are enough fonts in repo. We do not aim to provide everyone's favourite. Fonts that got into because were first to or have distinctive features like targetting usually omitted scripts or whatever else reason are updated, sure.

**Comment by emacsomancer** [comment]
> There are enough fonts in repo. We do not aim to provide everyone's favourite. Fonts that got into because were first to or have distinctive features like targetting usually omitted scripts or whatever else reason are updated, sure.

To me it would seem more consistent either to accept reasonable fonts more generally, or to say "we're only going to have a very small set of base fonts to get the system up and running" (like x11 fonts, liberation fonts, and dejavu). But not only are there packages like Iosevka (which is indeed a great font which I use) but also the huge `google-fonts-ttf` package (which, again, I think is useful). So it ends up seeming very arbitrary to me. 

Yes, of course, fonts can be installed locally, and I do. But fonts, like applications, do get updated, and it ends up just being duplicated effort for everyone to have to try to track updates if there's someone willing to maintain a package.

**Pull request closed without merging**
