### PR TITLE
arcan: update to 0.6.1.1

### PR DESCRIPTION
**Pull request by tgvqwsjk4jcs**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x64 glibc)

### CODE REVIEW

**Comment by tgvqwsjk4jcs** [comment]
done

**Comment by Chocimier** [comment]
Not done. Please read through CONTRIBUTING.md.

Can you add comment in `arcan` on connected packages?

**Comment by Chocimier** [comment]
Not done. Please read through CONTRIBUTING.md.

Can you add comment in `arcan` on connected packages?

**Comment by tgvqwsjk4jcs** [comment]
per commit msg updated

>Can you add comment in arcan on connected packages?

added

**Comment by tgvqwsjk4jcs** [comment]
checksum updated

**Comment by tgvqwsjk4jcs** [comment]
checksum updated

**Comment by tgvqwsjk4jcs** [comment]
xarcan added to rebuild with new shlib.
Patch removed from aloadimage, cause it
already in source

**Comment by tgvqwsjk4jcs** [comment]
xarcan added to rebuild with new shlib.
Patch removed from aloadimage, cause it
already in source

**Comment by tgvqwsjk4jcs** [comment]
ping

**Pull request closed without merging**
