### PR TITLE
llvm-17, multiple version of llvm to co-exist.

### PR DESCRIPTION
**Pull request by sgn**
#### Testing the changes
- I tested the changes in this PR: **NO**
[ci skip][skip ci]

### CODE REVIEW

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/pull/46935

**Comment by sgn** [comment]
I see that, but I want multiple version of llvm.

**Comment by Calandracas606** [comment]
I've proposed this in, [#48222
](https://github.com/void-linux/void-packages/issues/48222)

I think there are some issues with cross compiling the PR too.

Please let me know if I should close/stop work on my PR if this one will be used instead

**Comment by sgn** [comment]
> I've proposed this in, [#48222
> ](https://github.com/void-linux/void-packages/issues/48222)
> 
> I think there are some issues with cross compiling the PR too.
> 
> Please let me know if I should close/stop work on my PR if this one will be used instead

Please work on your. I have very limited time.

**Pull request closed without merging**
