### PR TITLE
poppler: update to 0.87.0

### PR DESCRIPTION
**Pull request by svenper**
see #20342

### CODE REVIEW

**Comment by svenper** [comment]
As I understand it, this would only change the name of the pkg. Perhaps the following would need to be rebuilt?

```text
$ xbps-query -RX libpoppler89
calligra-filters-3.1.0_25
extractpdfmark-1.1.0_5
inkscape-0.92.4_8
ipe-7.2.13_2
poppler-0.80.0_1
poppler-cpp-0.80.0_1
poppler-devel-0.80.0_1
poppler-glib-0.80.0_1
poppler-qt5-0.80.0_1
```

**Comment by xtraeme** [comment]
Right, all reverse dependencies of libpoppler89 will need to be rebuilt.

**Comment by xtraeme** [comment]
Another solution is using in libpoppler90:

```
provides="libpoppler89-${version}_${revision}"
replaces="libpoppler89>=0"
```

This solution won't need a rebuild.

**Comment by svenper** [comment]
```text
provides="libpoppler89-${version}_${revision}"
replaces="libpoppler89>=0"
```

force-pushed this!

**Comment by Chocimier** [comment]
Why don't we update poppler to new version and soname?

**Comment by svenper** [comment]
I thought it would be nice to fix this before updating, because it would be messier to fix it later.

**Comment by Chocimier** [comment]
I see not a single package depending on soname < 90. Rebuild is needed, so let's use newer poppler at same time.

**Comment by svenper** [comment]
That won't be a simple rebuild. E.g. I atempted a build of extractpdfmark which broke with poppler 0.87.0, and this likely happens for other revdeps.

Wasn't the purpose of the versioned libpoppler* to not break all revdeps at once?

Also I missed that there are more revdeps from poppler-qt5, bringing us in total: (status WIP)

- [x] YACReader
- [x] biblioteq
- [ ] calligra
- [ ] extractpdfmark **\***
- [ ] inkscape
- [ ] ipe **\***
- [x] katarakt
- [x] kfilemetadata5
- [ ] krita
- [x] okular
- [ ] qpdfview
- [ ] qtikz
- [ ] tellico
- [ ] texstudio
- [ ] texworks

**\*** broken

**Comment by svenper** [comment]
I attempted a poppler 0.87 rebuild and it succeeds locally but travis has this to say:

```text
=> kfilemetadata5-5.68.0_2: installing host dependencies: kcoreaddons-5.68.0_1 extra-cmake-modules-5.68.0_1 pkg-config-0.29.2_2 qt5-host-tools-5.14.2_2 qt5-qmake-5.14.2_2 gettext-0.20.1_2 kcoreaddons-5.68.0_1 python3-3.8.2_1 cmake-3.17.0_1 ...
=> kfilemetadata5-5.68.0_2: installing target dependencies: karchive-devel-5.68.0_1 ki18n-devel-5.68.0_1 poppler-qt5-devel-0.87.0_1 kcoreaddons-devel-5.68.0_1 taglib-devel-1.11.1_4 exiv2-devel-0.27.2_1 ffmpeg-devel-4.2.2_2 attr-devel-2.4.48_1 ebook-tools-devel-0.2.2_3 ...
=> kfilemetadata5-5.68.0_2: removing autodeps, please wait...
=> ERROR: kfilemetadata5-5.68.0_2: failed to install 'karchive-devel-5.68.0_1' dependency!(error 19)
MISSING: poppler-devel>=0.87.0
MISSING: libpoppler98>=0.87.0_1
Transaction aborted due to unresolved dependencies.
=> ERROR: Please see above for the real error, exiting...
The command "if [ -z "$XLINT" ]; then docker exec -t void hostrepo/common/travis/build.sh $BOOTSTRAP $ARCH; fi" exited with 1.
```

**Comment by svenper** [comment]
There! Finally, all that should build, builds! Both native x86_64-musl and cross aarch64-musl succeed locally. Feedback apprecciated!

**Comment by Chocimier** [comment]
`vmove usr/lib/libpoppler.so.${pkgname/libpoppler/}*` could be used in libpoppler subpackage to prevent same mistake in future. Build fails if glob matches nothing.

**Comment by svenper** [comment]
Nice!

**Comment by ahesford** [comment]
This is now outdated; poppler 0.88.0 is available.

**Comment by ericonr** [comment]
Unfortunately, time marches on and poppler 20.09.0 is now available: https://poppler.freedesktop.org/releases.html

**Comment by ahesford** [comment]
I'm working on an update to the new version 20.09.0 that supersedes this. Also, there is no need to revbump every one of these packages, because most use the `poppler-cpp` or `poppler-glib` libraries that have not seen an soname change; unless poppler broke the ABI for these libraries without bumping the soname, the existing packages should function without rebuilding.

The only packages that need revbumping are those identified by `xbps-query -Rp shlib-requires -s libpoppler.so` or `xbps-query -RX libpoppler89` (there are identical sets). Just to be sure, I'll test a few randomly selected other dependants to make sure they can be installed and run without issue.

**Pull request closed without merging**
