### PR TITLE
jupyterlab: update to 4.1.8

### PR DESCRIPTION
**Pull request by tornaria**
#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by tornaria** [comment]
I made this draft for no reason, it's just that I don't know how often to update all the jupyter packages.

There's a jupyterlab 4.2.0rc0, maybe I should update to that one and wait until 4.2.0 is released to bump this?

@dkwo any thoughts?

**Comment by dkwo** [comment]
Thanks for the updates. I didn't test thoroughly yet, but either way is fine with me.
I was waiting for jupyterlab to support server-side handling of cells, such that you can reconnect and do not lose the output, and it seems progress has been made, but not yet ready, so no urgency on my end.

**Comment by tornaria** [comment]
jupyterlab 4.2.0 is out, but it seems to need nodejs 20. A lot of tests fail and they all complain about nodejs version.

Hence, let's push this for now.

**Comment by dkwo** [comment]
Sounds good.
I think it's possbile with 4.2.0 but it requires `jupyter-collaboration >=2.0` and `jupyverse >=0.4.0`.
Let's revisit this later.

**Pull request merged**
