### PR TITLE
gsimplecal-gtk3: update to 2.4.1.

### PR DESCRIPTION
**Pull request by Chocimier**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by paper42** [comment]
can we drop the gtk2 version?

**Comment by Chocimier** [comment]
gtk2 version dropped

cc @jarbowski, I could take over maintainership too.

**Comment by jarbowski** [comment]
Hey,
Feel free to take over maintainership as I don't use Void Linux anymore.
Cheers

**Comment by Chocimier** [comment]
I hope we'll meet again!

Regards

**Pull request merged**
