### PR TITLE
zfs: update to 2.2.7.

### PR DESCRIPTION
**Pull request by zdykstra**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by zdykstra** [comment]
root-on-ZFS, Linux 6.12.4, Dracut - no issues

**Comment by classabbyamp** [comment]
how are we feeling about this?

**Comment by zdykstra** [comment]
I've been running it on my workstation since I opened the PR. I haven't looked at the upstream issue tracker in a few days, but it seemed pretty quiet for 2.2.7 / 2.1.16.

**Comment by classabbyamp** [comment]
looked through the issue tracker & PRs, I don't think there's any showstoppers there

@Vaelatern what do you think?

**Comment by Vaelatern** [comment]
Good to go!

**Pull request merged**
