### PR TITLE
[WIP] rust: update to 1.33.0.

### PR DESCRIPTION
**Pull request by Cogitri**
Gonna wait with this until LLVM 8 has been released (was
scheduled to be released yesterday) since that fixes the
random SIGSEVing we've been experiencing on projects
which use LTO.

### CODE REVIEW

**Comment by Cogitri** [comment]
Alright, seems like LLVM still needs some time to release LLVM8. Could you compile the bootstrap compilers already, @q66, @Gottox?

**Comment by q66** [comment]
So what are we gonna do? Will we still wait? What LLVM should I build my bootstrap compilers with?

**Comment by Cogitri** [comment]
Just build against LLVM7, I don't feel like waiting for LLVM upstream anymore. Will have to fix the musl patches though.

**Comment by q66** [comment]
So what are we gonna do about the LTO stuff? how long will it take for LLVM to release?

**Comment by Cogitri** [comment]
> So what are we gonna do about the LTO stuff?

Well, that doesn't really matter for the bootstrap compiler since rustc builds fine with LLVM7 too. Firefox also builds fine with the patch we have added to 1.32 (is in 1.33), so this only hits a few projects (fractal, Gnome-podcasts, gxi)

> how long will it take for LLVM to release?

No clue, release date for LLVM8 was 27.2.2019, I'll take a more in-depth look what's holding that back in a bit.

**Comment by q66** [comment]
If it's not too far away, I'd still wait, in order to not break build on specific projects. I mean, is there any pressing reason to update to Rust 1.33? Lots of systems are doing just fine with older version than we currently have.

**Comment by Cogitri** [comment]
> If it's not too far away, I'd still wait, in order to not break build on specific projects

It doesn't matter for the bootstrap compilers

> . I mean, is there any pressing reason to update to Rust 1.33?

Some projects (e.g. miniserve) already require it. There's really no disadvantage to upgrading to rust 1.33 now and upgrading LLVM later and rebuilding Rust then, should also make debugging easier in case something goes wrong

**Comment by q66** [comment]
In that case it is probably best to build the bootstrap compilers with internal LLVM. Otherwise it will be necessary to rebuild them by the time LLVM updates (because we link LLVM dynamically now)

**Comment by q66** [comment]
Also, I will take care of building the bootstrap compiler for x86_64-musl while building the ppc64 ones, so no worries about that one @Gottox

**Comment by Cogitri** [comment]
> Otherwise it will be necessary to rebuild them by the time LLVM updates (because we link LLVM dynamically now)

Uhh...no? We will still have liblllvm7 in the tree after upgrading to llvm8 (just like we have libllvm6 in the tree right now).

> Also, I will take care of building the bootstrap compiler for x86_64-musl while building the ppc64 ones

Yeah, musl doesn't work just yet. Also, Gottox needs to upload those.

**Comment by q66** [comment]
Why doesn't it work?

**Comment by q66** [comment]
Also, is there any project that requires keeping llvm7 around? Because otherwise I don't see the point

**Comment by Cogitri** [comment]
> Why doesn't it work?

Because I have to adjust the dynamic linking patch

> Also, is there any project that requires keeping llvm7 around?

Yes, see the LLVM8 PR

**Comment by Cogitri** [comment]
Alright, I suppose it should work on musl now - testing.

**Comment by q66** [comment]
Okay, building bootstraps for `ppc64le-musl`, `ppc64-musl`, `x86_64-musl` now. Also, some bits to fix: `s/internal_llvm/internal-llvm` in the section applying internal llvm patches, and also please bump cargo dist version to 0.33 and update checksums

**Comment by Cogitri** [comment]
> Also, some bits to fix: s/internal_llvm/internal-llvm

Oops, thanks.

> please bump cargo dist version to 0.33 and update checksums

Not really necessary, but sure.

**Comment by q66** [comment]
ppc64 bootstrap compilers in here https://void-ppc64.octaforge.org/distfiles/

The x86_64-musl one fails for me when linking some stuff inside the bundled LLVM. I'm not quite sure how to fix it, so I will need @Gottox to give it a shot after all. @Gottox, please, when building your bootstrap compilers, use the bundled llvm so that it doesn't depend on llvm7 so that we don't have to add it into hostmakedepends after updating to llvm8.

**Comment by Gottox** [comment]
Okay. My schedule is hell atm, so give me a bit of time :)

**Comment by Cogitri** [comment]
Alright, I'll build it then and ping you to host it :)

-------- Original Message --------

**Comment by Cogitri** [comment]
Alright, I've built the rust tarballs for x86_64-musl, you can get them from exp.exqa.de @Gottox

**Comment by q66** [comment]
Cool. While at it, could you also rebuild `x86_64-musl` cargo with `-o static`? Ours are not built that way, and it causes an issue when we bump libgit or whatever. I'm already rebuilding mine for ppc64 and will put them up in a couple minutes... then we'll need to update checksums for the `rust` template as well as `cargo` template.

**Comment by Cogitri** [comment]
Oops, right.

**Comment by q66** [comment]
Updated for `ppc64`, all in https://void-ppc64.octaforge.org/distfiles/

**Comment by Cogitri** [comment]
Thanks, updated checksums.

**Comment by jnbr** [comment]
we most likely need https://github.com/rust-lang/rust/pull/57990 applied for cross builds to work

**Comment by Cogitri** [comment]
Ah, it only happens in crossbuilds, was wondering why I'm not hitting it already

**Comment by q66** [comment]
My musl bootstrap compilers are done with Rust 1.33 and they worked... shrug

**Comment by Cogitri** [comment]
I think I crossed to aarch64-musl already, but wasn't quite sure.

**Comment by Cogitri** [comment]
Yup, works just fine without the patch. AFAICS this is good to go once Gottox mirrors the distfiles.

**Comment by q66** [comment]
The reason this works is that the patch is already present in the 1.33.0 source release. Which makes sense, because it was merged over a month ago.

**Comment by jnbr** [comment]
oops, sorry for cunfusion

**Comment by Gottox** [comment]
files are mirrored.

**Comment by Cogitri** [comment]
Mind mirroring the x86_64-musl files too? They're on https://exp.exqa.de

**Comment by Gottox** [comment]
mirrored, sorry for the delay :(

**Comment by Cogitri** [comment]
Thanks for mirroring, will give it a 2nd test go to make sure nothing broke in the meantime :)

**Comment by Cogitri** [comment]
I don't think you've mirrored the new, static cargo from https://exp.exqa.de @Gottox.

**Comment by Gottox** [comment]
Done

**Comment by Cogitri** [comment]
Thank you :)

**Comment by Cogitri** [comment]
Alright, seems good to merge to me. IMHO we should merge this before LLVM8 and just rebuild this once LLVM8 is merged to not make the LLVM8 bump too chaotic.

**Comment by Cogitri** [comment]
Mind taking a look at this, @jnbr, @Gottox?

**Comment by jnbr** [comment]
I don't have time to test this before the weekend.
It would be good check what is going wrong in #9973 and test if more architectures are affected.
It will also break firefox builds, but this has to be fixed on the firefox side.

**Comment by Cogitri** [comment]
Oh, that still happens with FF66? Had hoped it only hit 65. Maybe we should look into #9973 after the LLVM8 bump in the naïve hope that it might fix itself automagically.

**Comment by q66** [comment]
FF builds/works fine for me, running 66 built with 1.33 right now

**Comment by Cogitri** [comment]
Nice, I suppose they've fixed that in FF66 then. Just tested all the musls and they work fine for me, but if you want to test them on the weekend I might get LLVM8 in mergable state before this

**Comment by q66** [comment]
Scratch that; the reason it works for me is that the breakage is x86 specific and i'm on ppc64le. Non-x86 arches are not broken in FF.

**Comment by jnbr** [comment]
> Scratch that; the reason it works for me is that the breakage is x86 specific and i'm on ppc64le.

and because of #10129 ...

**Comment by jnbr** [comment]
this cannot be built with build option internal_llvm:
```
=> rust-1.33.0_1: running post_extract ...
/builddir/rustc-1.33.0-src/src/llvm /builddir/rustc-1.33.0-src
=> Applying /void-packages/srcpkgs/rust/files/patches/internal_llvm/llvm-*.patch to llvm
patch: **** Can't open patch file '/void-packages/srcpkgs/rust/files/patches/internal_llvm/llvm-*.patch' : No such file or directory
```
the path should be `${FILESDIR}/patches/internal-llvm/llvm-*.patch`

**Comment by Cogitri** [comment]
Yup, thanks.

**Comment by jnbr** [comment]
Merge as is or switch to a working llvm version?

**Comment by Cogitri** [comment]
Hum...I guess LLVM8 should be ready to merge tomorrow, but then we'll have to go through another round of testing (but I don't mind waiting a few more days on this)

**Comment by jnbr** [comment]
Let's get this done.

rust-1.33 doesn't build with llvm8.
@q66: can we switch back to llvm6 to fix aarch64-musl or would this break ppc?

**Comment by q66** [comment]
I find this to be a bad idea, llvm6 is basically two versions behind and there will likely be a performance drop, plus is rust being tested with llvm6? Why not instead conditionally switch aarch64 to use internal-llvm by default for the time being? Yes, llvm6 will break ppc but that could be fixed (I just never bothered to port the template)

**Comment by jnbr** [comment]
> there will likely be a performance drop,

I'd happily trade performance for stability. Void isn't really trimmed for performance.

>  is rust being tested with llvm6?

It is the minimum required version. I tried it and couldn't reproduce any of the known bugs with it.

> Why not instead conditionally switch aarch64 to use internal-llvm by default for the time being?

- arm* is affected as well (segfaults randomly, hard to reproduce)
- someone would need to fix build_option internal_llvm, last time I checked this was broken in many ways

> Yes, llvm6 will break ppc but that could be fixed

Ok, we go with llvm6.0 then and check if we can upgrade with the next rust release without breaking things.

I'm running a rebuild of rust for x86_64* arm* and aarch64* now and will merge later today if nothing unexpected happens.

**Comment by Cogitri** [comment]
> someone would need to fix build_option internal_llvm, last time I checked this was broken in many

Uh? At least on ppc64 and x86_64* it works AFAIK

> Ok, we go with llvm6.0 then and check if we can upgrade with the next rust release without breaking things.

But I'm also OK with that.

**Comment by jnbr** [comment]
> Uh? At least on ppc64 and x86_64* it works AFAIK

Well, it failed to extract, with that solved, it didn't build for aarch*

**Comment by jnbr** [comment]
@q66: if you don't want to patch llvm6.0, we can of course use internal_llvm for ppc, I don't care about build time for this.

**Comment by Cogitri** [comment]
> Well, it failed to extract

Yup, fixed that locally and forgot to push :/

> Well, it failed to extract, with that solved, it didn't build for aarch*

Maybe I'll take a look at that, having internal LLVM work doesn't sound like a bad idea even if we're going with LLVM6, just in case :)

**Comment by q66** [comment]
How about using llvm7 on systems where it works and llvm6 as a fallback? I can patch llvm6 (probably) anyway, I will look into it later today; it's probably mostly about putting the same ppc related patches we have for llvm7 in there.

**Comment by Cogitri** [comment]
> How about using llvm7 on systems where it works and llvm6 as a fallback?

That sounds like a lot of edge cases and variation for little gain.

**Comment by q66** [comment]
```
case "$XBPS_TARGET_ARCHITECTURE" in
    x86_64*|ppc64*) makedepends += " llvm7";;
    *) makedepends += " llvm6.0";;
esac
```

doesn't seem like all that much work to me

**Comment by q66** [comment]
but okay, i will look into patching llvm6 later today

**Comment by Cogitri** [comment]
> doesn't seem like all that much work to me

But it doesn't work on all x86_64* arches, we've regularly seen rustc segfaulting on x86_64-musl too and testing it is work too.

**Comment by q66** [comment]
fair enough then

**Comment by jnbr** [comment]
It would have been to simple, if this would work out. While most things seem to be stable with llvm6, it doesn't build on i686:

```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m32" "-L" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1/lib/rustlib/i686-unknown-linux-gnu/lib" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/std-552b8219b338b715.std.645p7bia-cgu.0.rcgu.o" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/std-552b8219b338b715.std.645p7bia-cgu.1.rcgu.o" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/std-552b8219b338b715.std.645p7bia-cgu.10.rcgu.o" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/std-552b8219b338b715.std.645p7bia-cgu.11.rcgu.o" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/std-552b8219b338b715.std.645p7bia-cgu.12.rcgu.o" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/std-552b8219b338b715.std.645p7bia-cgu.13.rcgu.o" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/std-552b8219b338b715.std.645p7bia-cgu.14.rcgu.o" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/std-552b8219b338b715.std.645p7bia-cgu.15.rcgu.o" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/std-552b8219b338b715.std.645p7bia-cgu.2.rcgu.o" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/std-552b8219b338b715.std.645p7bia-cgu.3.rcgu.o" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/std-552b8219b338b715.std.645p7bia-cgu.4.rcgu.o" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/std-552b8219b338b715.std.645p7bia-cgu.5.rcgu.o" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/std-552b8219b338b715.std.645p7bia-cgu.6.rcgu.o" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/std-552b8219b338b715.std.645p7bia-cgu.7.rcgu.o" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/std-552b8219b338b715.std.645p7bia-cgu.8.rcgu.o" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/std-552b8219b338b715.std.645p7bia-cgu.9.rcgu.o" "-o" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/libstd-552b8219b338b715.so" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/std-552b8219b338b715.15gx6bnt8lvxyxcl.rcgu.o" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/std-552b8219b338b715.4ks4ya8q1jowmw3v.rcgu.o" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps" "-L" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/release/deps" "-L" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/build/compiler_builtins-8d16f6acfd264e4b/out" "-L" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/build/backtrace-sys-d15138a4382e0e82/out" "-L" "/builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1/lib/rustlib/i686-unknown-linux-gnu/lib" "-ldl" "-lrt" "-lpthread" "-Wl,-Bstatic" "-Wl,--whole-archive" "/tmp/rustcbvnwYu/libpanic_unwind-1366e8ae7635b7c1.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustcbvnwYu/libbacktrace_sys-a2a1f5c7d3aff6c2.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustcbvnwYu/libunwind-1bf45e76e0b5b7f9.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustcbvnwYu/librustc_demangle-715f92b119af3aca.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustcbvnwYu/liblibc-630ec565d6e37c89.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustcbvnwYu/liballoc-310d2585fb213200.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustcbvnwYu/librustc_std_workspace_core-b5bad287e94b4d22.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustcbvnwYu/libcore-c8d0afeffe99edeb.rlib" "-Wl,--no-whole-archive" "/tmp/rustcbvnwYu/libcompiler_builtins-9661adfb8c6daed0.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil" "-shared"
  = note: /usr/bin/ld: /builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/std-552b8219b338b715.std.645p7bia-cgu.1.rcgu.o: in function `std::sys::unix::net::Socket::set_timeout':
          /builddir/rustc-1.33.0-src/src/libstd/sys/unix/net.rs:276: undefined reference to `anon.f2320c39b9c93103de69c255afbbca99.19.llvm.17667750923693464799'
          /usr/bin/ld: /builddir/rustc-1.33.0-src/build/i686-unknown-linux-gnu/stage1-std/i686-unknown-linux-gnu/release/deps/std-552b8219b338b715.std.645p7bia-cgu.1.rcgu.o: relocation R_386_GOTOFF against undefined hidden symbol `anon.f2320c39b9c93103de69c255afbbca99.19.llvm.17667750923693464799' can not be used when making a shared object
          /usr/bin/ld: final link failed: bad value
          collect2: error: ld returned 1 exit status


error: aborting due to previous error

error: Could not compile `std`.
```

This only happens, when built from a i686 masterdir, cross-compiling from x86_64 to i686 works.
I'm out of ideas on how to fix this, if no one else has a clue, I guess we have to go with llvm7 or give up and use internal_llvm.

**Comment by Cogitri** [comment]
> I'm out of ideas on how to fix this, if no one else has a clue, I guess we have to go with llvm7 or give up and use internal_llvm.

IMHO we should just go with llvm7 for now. It's _so_ not optimal, but I don't want to pour too much work into LLVM6 when we can upgrade to LLVM8 in 3 weeks anyway.

What platforms does internal_llvm not work on?

**Comment by q66** [comment]
or skip 1.33 and go straight to 1.34

**Comment by Cogitri** [comment]
> or skip 1.33 and go straight to 1.34

Or do that, but I don't see the advantage of that other than that the builders don't have to build this

**Comment by pullmoll** [comment]
@jnbr you may try to use `LD=$CXX` in the configure step. I've seen `cc` failing as linker wrapper where `c++` succeeded before.

**Comment by jnbr** [comment]
Thanks, will try later. But I just merged this.

**Comment by pullmoll** [comment]
I saw it while writing the answer :)

**Comment by Cogitri** [comment]
@jnbr I guess we'll have to mark it nocross until Rust 1.33.0 is built for native arches.

**Comment by Cogitri** [comment]
Nevermind, I should pull before commenting :P

**Comment by jnbr** [comment]
And I should check I have a clean branch before pushing

**Comment by Cogitri** [comment]
Oh well, happens. Thanks everyone for working on this :)

**Comment by jnbr** [comment]
for reference: `LD=$CXX` didn't help for building rust with llvm6.0 on i686

**Comment by cuviper** [comment]
FWIW, I ran into a similar `R_386_GOTOFF` error on Fedora 28 i686 with LLVM 6:
https://bugzilla.redhat.com/show_bug.cgi?id=1699504

**Pull request merged**
