### PR TITLE
drist: update to 2.0, New package: drist1

### PR DESCRIPTION
**Pull request by PaperMountainStudio**
Scripts written for drist v1 are not compatible with drist v2,

### CODE REVIEW

**Comment by Duncaen** [comment]
What about dropping the package instead?

**Comment by PaperMountainStudio** [comment]
Which one do you mean? Dropping entire drist? Updating to v2 without v1 available or creating a new package drist2?

**Comment by Duncaen** [comment]
I'm not a fan of the requirements, but I think this is a good example for why they exist.

https://github.com/void-linux/void-packages/blob/master/Manual.md#quality_requirements

**Comment by PaperMountainStudio** [comment]
That's fair, I think we can drop it. I can manage my own repository. Should we wait for opinion of other maintainers?

**Comment by Anachron** [comment]
Why not keep the original drist pkg on 1.0 and the new one is 2.x? No breakage required. And some day we can deprecate it.

**Comment by Duncaen** [comment]
Why add compatibility, alternatives and _2_ packages for a 150 line shell script 2 people use.

**Comment by Anachron** [comment]
By that logic we would need to delete hundreds of packages.

**Pull request closed without merging**
