### PR TITLE
caddy: several template improvements

### PR DESCRIPTION
**Pull request by steinex**

### CODE REVIEW

**Comment by Duncaen** [comment]
We never ship default `/etc/sv/foo/conf` files, we use something like `${MAX_OPEN_FILES:-8192}` to have a default value.

The `logger` will send logs into the void if its started before the syslog daemon, use `vlogger(1)`.
In this case you can even just do `ln -s /usr/bin/vlogger srcpkgs/caddy/log/run` instead, vlogger will get the tag argument from the service path and `daemon.info` is the default priority.

**Comment by steinex** [comment]
Thank you for the suggestions! Incorporated.

**Comment by Duncaen** [comment]
You still need the `[ -r ./conf ] && . ./conf` in the run script.

**Comment by steinex** [comment]
Ofc. Done.

**Pull request merged**
