### PR TITLE
gnupg: replace with gnupg2

### PR DESCRIPTION
**Pull request by randompass**

### CODE REVIEW

**Comment by Anachron** [comment]
1.) Please use `xlint` from [xtools](https://github.com/chneukirchen/xtools) before opening PRs!
2.) Please don't open PRs that did not build successfully locally. 
3.) Why this change?

**Comment by randompass** [comment]
because gnupg1 is unmaintained and compatible with gnupg2

**Comment by randompass** [comment]
xlint successful for gnupg but not for docker-credential-pass, git-annex, gpa, pass and tpm.
Should i fix it?

**Comment by Chocimier** [comment]
> because gnupg1 is unmaintained and compatible with gnupg2

This is not enough. In general, we do not rename packages. In this case, people who explicitly installed gnupg2 will not receive updates this way.

If there are known vulnerabilities of gnupg, we could consider removing it, but we do not process for that yet.

**Comment by abenson** [comment]
I don't think it's necessary to remove it just yet.

> GnuPG 1.4 is the old, single binary version which still support the unsafe PGP-2 keys. This branch has no dependencies on the above listed libraries or the Pinentry. However, it lacks many modern features and will receive only important updates. 

Additionally, renaming stuff like this could cause breakage when setups are expecting gpg vs gpg2.

**Comment by randompass** [comment]
How i see there no alternative to pacman's `replaces`.
@Anachron @Chocimier @abenson thank you!

**Pull request closed without merging**
