### PR TITLE
mpv: add sndio patch

### PR DESCRIPTION
**Pull request by robbie01**
#### Testing the changes
- I tested the changes in this PR: **YES**

lifted from the following without modification:
- http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/multimedia/mpv/patches/patch-audio_out_ao_c?rev=1.3&content-type=text/x-cvsweb-markup
- http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/multimedia/mpv/patches/patch-audio_out_ao_sndio_c?rev=1.4&content-type=text/x-cvsweb-markup
- http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/multimedia/mpv/patches/patch-wscript?rev=1.5&content-type=text/x-cvsweb-markup
- http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/multimedia/mpv/patches/patch-wscript_build_py?rev=1.3&content-type=text/x-cvsweb-markup

thanks brad

### CODE REVIEW

**Comment by robbie01** [comment]
changed the build dependency from "sndio-devel sndio" to just sndio-devel :+1:

**Comment by ericonr** [comment]
Would enabling sound via SDL2 be an option? The patch is rather simple but I'd prefer to avoid it, if possible.

**Comment by robbie01** [comment]
I can confirm that enabling SDL2 is functional for audio, but with the caveats of needing an xbps-src option of its own (making it no more convenient than ao_sndio for Void users), as well as some sndio users noting AV desync issues with SDL2 in the upstream PR at mpv-player/mpv#9298. I haven't yet tested AV outside of a VM, but I'll report back as soon as I do.

**Comment by robbie01** [comment]
Using mpv's default vo_gpu, I'm seeing ~200 ms delay with ao_sdl and no significant delay with ao_sndio.

**Comment by robbie01** [comment]
mpv-player/mpv#9298 has been merged into upstream, superseding this patch. Closing as there seems to be a lack of interest in backporting ao_sndio at the moment; I hope to see it enabled by default here at the next release 😄

**Pull request closed without merging**
