### PR TITLE
[WIP] newsboat: update to 2.22.

### PR DESCRIPTION
**Pull request by subsonik**
Tested OK on x86_64-musl.

### CODE REVIEW

**Comment by Minoru** [comment]
Hi! I'm the maintainer of Newsboat. You might want to hold this off a bit since I'm going to release 2.22.1 tomorrow. It got three bugfixes for pretty inconvenient regressions in 2.22.

**Comment by Minoru** [comment]
…And also a fix for the warning that failed your CI builds :)

**Comment by subsonik** [comment]
Awesome, I'll keep an eye out for the point release tomorrow, thanks @Minoru.

I'm a regular (and very happy) user of newsboat + podboat btw, keep up the excellent work! :smile:

**Comment by ericonr** [comment]
Why close?

**Comment by subsonik** [comment]
There was a new version released (2.22.1), so I assumed it required a new PR. Was that wrong?

**Comment by ericonr** [comment]
Kinda. Just rename the PR and force push. It's less noisy for us.

**Comment by subsonik** [comment]
Ah OK, apologies, I'll bear this in mind in future. :)

I've already opened another PR for the new version, should I close that one and reopen this?

**Comment by ericonr** [comment]
Np. In this case just leave as is.

**Pull request closed without merging**
