### PR TITLE
meson: update to 1.3.0; python3-meson-python: update to 0.15.0

### PR DESCRIPTION
**Pull request by ahesford**
#### Testing the changes
- I tested the changes in this PR: **in process**

cc: @paper42

### CODE REVIEW

**Comment by dkwo** [comment]
Not totally related, but I wonder whether the meson build helper should have `c_ld` instead of `ld` set to `${LD}`.
See https://mesonbuild.com/howtox.html#set-linker

**Comment by ahesford** [comment]
Using `c_ld` and `cpp_ld` in place of `ld` triggered a build failure in `valabind`, which was the first thing I attempted to compile.

**Comment by ahesford** [comment]
On closer examination, just removing the `ld` definition altogether doesn't seem to cause problems for at least half of the meson packages (which I've build-tested variously across `aarch64*`, `armv6l` and `armv7l-musl`), so we can just drop that altogether.

**Comment by dkwo** [comment]
I think dropping `ld` is fine, as it's probably not used anyway.
According to the link above, "with a compiler that invokes the linker itself (GCC and Clang), c_ld or CC_LD should be the value to pass to the compiler's special argument (such as -fuse-ld with clang and gcc)." Does our `${LD}` do that, or it gives the full path to a linker?

**Comment by ahesford** [comment]
1b3220391e1b6c94e3213171238f88a6cfc667ba -- 28b724db5c4cee6b0dee83b6625d4098a67033f1

**Comment by ahesford** [comment]
The value of `${LD}` is `${XBPS_CROSS_TRIPLET}-ld`, but meson will only accept one of `bfd`, `gold` or `lld` for GCC compilers.

**Pull request closed without merging**
