### PR TITLE
libGL: update to 18.3.0.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by maxice8** [comment]
@lemmi please don't merge after testing, i want to get some more people testing.

Of note, /etc/drirc isn't distributed anymore and /usr/share/drirc.d/00-mesa-defaults.conf took its place. I don't know if we are suppoed to use /etc/drirc or create our own /etc/drirc.d.

**Comment by maxice8** [comment]
libwayland-egl was finally removed and thus the metapackage was removed as well, further commits remove all references to libwayland-egl

**Comment by maxice8** [comment]
pinging some testers: @Cogitri @jnbr @Johnnynator @q66

**Comment by prspkt** [comment]
Usual suspects (Chromium, Firefox and mpv) LGTM on `x86_64-musl` so far.

**Comment by Cogitri** [comment]
Seems to work for me on Intel, will test AMD later today.

**Comment by Johnnynator** [comment]
This broken the Shader cache (of at least SDDM) and I had manually remove `~/.cache/mesa_shader_cache` of every user. Otherwise it seems to work fine.

**Comment by jnbr** [comment]
no issues for me on x86_64 with nouveau

**Comment by Cogitri** [comment]
wfm on AMD (Vega M)

**Pull request merged**
