### PR TITLE
linux5.10: lift build restriction for armv7l

### PR DESCRIPTION
**Pull request by digitalatigid**
arm-dotconfig is based on multi_v7_defconfig and was obtained from the linux source tree by running `env ARCH=arm make defconfig` on the v5.10.4 tag.

no output from xlint; kernel compiles for armv7l and boots on the [helios4](https://wiki.kobol.io/helios4/intro/) board.

linux is very large, so [ci skip]

### CODE REVIEW

**Comment by digitalatigid** [comment]
I just noticed that this configuration is missing device mapper support which causes shutdown errors even when this feature is not used:
```
=> Deactivating Crypt Volumes                                                             
/dev/mapper/control: open failed: No such device                                          
Failure to communicate with kernel device-mapper driver.                                  
Check that device-mapper is available in the kernel.                                      
Incompatible libdevmapper 1.02.170 (2020-03-24) and kernel driver (unknown version).      
Command failed.                              
```
Using lvm or cryptsetup obviously fails.

I will reopen this issue when I have a complete kernel config.

**Comment by q66** [comment]
we're not going to accept a configuration based on defconfig, each dotconfig should be more or less in sync with the other architectures besides the architecture-specific bits

**Comment by digitalatigid** [comment]
makes sense. how can I find out what the dotconfig should cover? is there a better way than just looking at the other dotconfigs and then guessing?

**Comment by q66** [comment]
nope, you're going to have to compare against the other configs (aarch64 would be the closest match, probably)

**Pull request closed without merging**
