### PR TITLE
hugo: remove build options

### PR DESCRIPTION
**Pull request by FollieHiyuki**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by FollieHiyuki** [comment]
Continue from last comments of #30502.
The built binary will be the same so we don't need to revbump.

**Comment by Piraty** [comment]
please revbump as this changes the package's metadata

**Comment by Piraty** [comment]
ping @thypon

**Comment by thypon** [comment]
Good to go for me

**Comment by FollieHiyuki** [comment]
Ok bumped

**Pull request merged**
