### PR TITLE
helix: update to 23.03

### PR DESCRIPTION
**Pull request by Chirikumbrah**
#### Testing the changes
- I tested the changes in this PR: **NO**

### CODE REVIEW

**Comment by Chirikumbrah** [comment]
image
It requires newest rustc version to build)

**Comment by icp1994** [comment]
How did you test briefly if it didn't build? :D
Anyway, yes it's known https://github.com/void-linux/void-packages/issues/40805#issuecomment-1491605768

**Comment by Chirikumbrah** [comment]
I'm sorry))
Corrected this!

**Comment by tranzystorek-io** [comment]
Merged in https://github.com/void-linux/void-packages/pull/43178

**Pull request closed without merging**
