### PR TITLE
tty-clock: fix license in template

### PR DESCRIPTION
**Pull request by lugubris**
change from GPL-3 to BSD-3-Clause
-> https://github.com/xorg62/tty-clock/blob/master/LICENSE

### CODE REVIEW

**Comment by Hoshpak** [comment]
Nice catch. BSD lincenses generally require the inclusion of the license file itself in the package since their content may vary and the license text is not included in the distribution. To do so, you can use the `vlicense` function on the license file.

So please add `vlicense LICENSE` to the install function (would be post_install if the build_style function was used). Since this changes the contents of the package, please also increase the revision of the template.

**Comment by lugubris** [comment]
oh! I messed this commit by mixing two comment of yours.

-> https://github.com/void-linux/void-packages/pull/13930

**Comment by lugubris** [comment]
also github says this branch has conflicts, i am not sure how to resolve them can you help?

**Comment by Hoshpak** [comment]
The conflict is due to one of the other two already merged PRs which also changed the template, most likely due to the maintainer change in #13925 . To resolve it, please rebase this branch on top of the current master and resolve the conflicts git shows you while doing it. Then force-push the updated branch.

**Comment by lugubris** [comment]
sorry for spam, I've never used git for such things. messed up the commit history when trying to fix this.

**Comment by lugubris** [comment]
new pull-request opened
-> https://github.com/void-linux/void-packages/pull/13951

**Pull request closed without merging**
