### PR TITLE
[WIP] libreoffice: remove obsolete patch from files/.

### PR DESCRIPTION
**Pull request by ericonr**
@pullmoll

### CODE REVIEW

**Comment by ericonr** [comment]
I'm trying to add more clean up here.

**Review by pullmoll — APPROVED** [review]

**Comment by pullmoll** [comment]
@ericonr Good work, thank you!

**Comment by q66** [comment]
can we avoid rebuilding libreoffice for no good reason whatsoever

it's a pain in the ass and i'm sure it can wait until next point release

**Comment by pullmoll** [comment]
@q66 sure. What @ericonr did was to solve the problem with one of the dependencies of system packages. No need to hurry and no need to get this into 7.0.0.3.

**Pull request closed without merging**
