### PR TITLE
[WIP] New package: google-earth-pro-7.3.2.5494

### PR DESCRIPTION
**Pull request by cr6git**
based on this [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=google-earth-pro) ...

### CODE REVIEW

**Comment by Johnnynator** [comment]
This has to be at least in nonfree. I'm currently reading through the license stuff to see if it is even allowed to redistribute the binary.

**Comment by Johnnynator** [comment]
``` Prohibited Conduct. When using Google Maps/Google Earth, you may not (or allow those acting on your behalf to):

    redistribute or sell any part of Google Maps/Google Earth or create a new product or service based on Google Maps/Google Earth (unless you use the Google Maps/Google Earth APIs in accordance with their terms of service);
``` I'm not sure how to interpret this part but it sounds like that we can't redistribute the binary.

**Comment by the-maldridge** [comment]
This needs to be in both repository=nonfree and restricted=yes.

**Comment by cr6git** [comment]
@the-maldridge wow you are fast! ^^

**Comment by cr6git** [comment]
@the-maldridge I don't understand what's wrong with this checksum??
https://travis-ci.org/void-linux/void-packages/jobs/430881441#L896
````
requesting https://www.google.com/intl/ALL/policies/privacy/index.html
Google-Privacy-Policy.html: [0B 0%] 52MB/s ETA: unknown
Google-Privacy-Policy.html: 1156B [avg rate: 52MB/s]
=> google-earth-pro-7.3.2.5494_1: verifying checksum for distfile 'Google-Privacy-Policy.html'... 
=> ERROR: SHA256 mismatch for 'Google-Privacy-Policy.html:'
cbcfb5ff1c9671ff7614c8f5b8b0d122fa404ce5ce5f5b5a7bdbf2f0d028746e
````

**Comment by Johnnynator** [comment]
@cr6git You can't checksum google tarballs since they are generated at download time and contain unique meta data, you have to use the content checksum ( use `xgensum -c -i srcpkgs/google-earth-pro/template`

**Comment by cr6git** [comment]
I give up.

**Pull request closed without merging**
