### PR TITLE
re2: update to 2023.03.01.

### PR DESCRIPTION
**Pull request by mhmdanas**
[ci skip]

#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by leahneukirchen** [comment]
Can you verify this doesn't put `-std=c++11` anymore into /usr/lib/pkgconfig/re2.pc ?

**Comment by mhmdanas** [comment]
I can confirm, here are the contents:
```
includedir=/usr/include
libdir=/usr/lib

Name: re2
Description: RE2 is a fast, safe, thread-friendly regular expression engine.
Requires: 
Version: 10.0.0
Cflags: -pthread -I${includedir}
Libs: -pthread -L${libdir} -lre2
```

**Comment by leahneukirchen** [comment]
Sounds good, what's needed to make this a ready PR?

**Comment by mhmdanas** [comment]
Build testing I suppose, namely of chromium, electron19, qt5-webengine, and qt6-webengine, plus also runtime-testing those packages.

**Comment by Johnnynator** [comment]
WiP untested builds: https://void.johnnynator.dev/dev/43684/ (Compile jobs are still running)

**Comment by Johnnynator** [comment]
merged in 75d854da7e405e3c7c2c2281f8a105fb914a8678

**Pull request closed without merging**
