### PR TITLE
topgrade: update to 10.0.1.

### PR DESCRIPTION
**Pull request by jcgruenhage**
#### Testing the changes
- I tested the changes in this PR: **YES**

Note here: This is a fork of the original topgrade. Both the package on
crates.io and the manjaro package now ship the fork, and the original
repository has officially been archived.

### CODE REVIEW

**Comment by tranzystorek-io** [comment]
10.1.0 is out

**Comment by jcgruenhage** [comment]
Yes, but their git tag is still missing: https://github.com/topgrade-rs/topgrade/issues/102

**Comment by tranzystorek-io** [comment]
As well as the whole release page suddenly 🤔

**Comment by DottoDev** [comment]
This was me testing the release pipeline. But for some reason the clap dependencie always let's it fail. 10.1.0 will still need some work.

**Pull request merged**
