### PR TITLE
New package: shaderc-2017.2.

### PR DESCRIPTION
**Pull request by maxice8**
mpv can now use vulkan with `shaderc`

mpv --gpu-api=vulkan --gpu-context=x11vk (or waylandvk if you are a wayland adopter) --spirv-compiler=shaderc (nvidia if you're a nvidia user)

please drop a comment on the following template:

```
[Working fine|failed] on $(xbps-uhelper arch) with [shaderc|nvidia]

===anything else you want to say
```

shaderc is used on intel and amd

### CODE REVIEW

**Comment by abenson** [comment]
Working fine on x86_64 with amdgpu

**Comment by travankor** [comment]
working on nouveau x86 glibc

**Comment by maxice8** [comment]
@travankor please follow the template

**Comment by Vintodrimmer** [comment]
Working fine on x86_64 with shaderc and Intel drivers.
Thanks!

**Pull request closed without merging**
