### PR TITLE
librsvg: update to 2.59.1.

### PR DESCRIPTION
**Pull request by icp1994**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture: **x86_64**

I am not sure if this warrants rebuilding revdeps, hopefully someone can opine on that.

### CODE REVIEW

**Comment by icp1994** [comment]
If I'm reading the logs right, `/usr/bin/cargo` is not available in cross :thinking:

**Comment by chrysos349** [comment]
fix cross
```sh
if [ "$CROSS_BUILD" ]; then
	XBPS_CROSS_RUSTFLAGS+=" -L${XBPS_BUILDDIR}/${pkgname}-${version}/build/rsvg"
	configure_args="-Dtriplet=${XBPS_CROSS_RUST_TARGET}"
	post_patch() {
		vsed -i meson.build -e "s/not meson.is_cross_build() and //"
	}
fi
```

**Comment by icp1994** [comment]
Thanks, that worked.

**Comment by classabbyamp** [comment]
missing dependency: 7e715df772d, caused build fails in ART

**Comment by classabbyamp** [comment]
also, it seems the pkgconfig file is missing cflags on cross. this broke ART and appstream.

**Pull request closed without merging**
