### PR TITLE
gitea: update to 1.14.1

### PR DESCRIPTION
**Pull request by FollieHiyuki**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

Don't know why the patch fails to apply, but the package builds.

### CODE REVIEW

**Comment by ericonr** [comment]
> Don't know why the patch fails to apply, but the package builds.

Locally, you mean?

**Comment by FollieHiyuki** [comment]
Sorry that was misleading. What I meant was I could build and install the package without the patch. The patch fails locally too.
But I can apply it within `gitea` repo with no problem (it is generated from git anyways)

**Comment by FollieHiyuki** [comment]
Don't know why that hunk fails
```
❯ patch -Np0 < config.patch 
patching file custom/conf/app.example.ini
Hunk #2 FAILED at 20.
Hunk #3 succeeded at 87 (offset -2 lines).
Hunk #4 succeeded at 282 (offset -6 lines).
Hunk #5 succeeded at 303 (offset -6 lines).
Hunk #6 succeeded at 368 (offset -6 lines).
Hunk #7 succeeded at 385 (offset -6 lines).
Hunk #8 succeeded at 415 (offset -6 lines).
Hunk #9 succeeded at 432 (offset -6 lines).
Hunk #10 succeeded at 458 (offset -6 lines).
Hunk #11 succeeded at 806 (offset -32 lines).
Hunk #12 succeeded at 871 (offset -32 lines).
Hunk #13 succeeded at 1181 (offset -32 lines).
```

Here is the rej:
```diff
@@ -20,7 +20,7 @@
 
 [repository]
 ; Root path for storing all repository data. It must be an absolute path. By default, it is stored in a sub-directory of `APP_DATA_PATH`.
-ROOT =
+ROOT = /var/lib/gitea/repositories
 ; The script type this server supports. Usually this is `bash`, but some users report that only `sh` is available.
 SCRIPT_TYPE = bash
 ; DETECTED_CHARSETS_ORDER tie-break order for detected charsets.
```

**Comment by FollieHiyuki** [comment]
The patch now magically works even though it is still the same :) so ready for reviewing.

**Pull request merged**
