### PR TITLE
python3-cloudscraper: remove package

### PR DESCRIPTION
**Pull request by FollieHiyuki**
The issue page from github is long gone. The developer does sketchy stuff
(locks down features in paid version, ignores pull requests, ...).
We only packaged this for Komikku, and it already dropped the dependency a
while ago, so I think it's safe to remove this package.

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
> locks down features in paid version

Can you show reference for this? I couldn't find it immediately.

**Comment by FollieHiyuki** [comment]
> locks down features in paid version

https://github.com/VeNoMouS/cloudscraper/blob/229088edf45ad178befeb747ab0b0890e941da55/cloudscraper/__init__.py#L446

**Comment by FollieHiyuki** [comment]
@ericonr doesn't this need to be revbumped? I forgot to add that into the commit :(

**Comment by ericonr** [comment]
Not necessary, removed-packages is revbumped all the time already :)

**Pull request merged**
