### PR TITLE
xdg-desktop-portal: update to 1.15.0.

### PR DESCRIPTION
**Pull request by oreo639**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by Duncaen** [comment]
This is a pre-release

**Comment by oreo639** [comment]
It is required by xdg-desktop-portal-gnome 43 unfortunately.

**Comment by Duncaen** [comment]
Would be more appropriate to do this with the update that would require the pre-release version.

Also why did you switch to the automatically generated release tar ball instead of the one the developers upload with a known sha256 hash?

**Comment by oreo639** [comment]
The autogen dist was missing test files.

**Pull request merged**
