### PR TITLE
helvum: update to 0.4.1.

### PR DESCRIPTION
**Pull request by 0x5c**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by tranzystorek-io** [comment]
Seems like an issue to report upstream, their wrappers don't look properly tested on other platforms

**Comment by 0x5c** [comment]
Ahhh very fun
I feared breakage when seeing the update, tested locally (x86_64 glibc) and had no errors, and had the hubris of expecting to push that before going afk and come back to all green on CI
Welp :(

**Comment by 0x5c** [comment]
Ok, by updating the libspa crate to the latest version we get rid of the bindgen errors on musl, but we still have the type mismatch on 32bit architectures

**Comment by 0x5c** [comment]
https://gitlab.freedesktop.org/pipewire/pipewire-rs/-/issues/84

**Comment by icp1994** [comment]
A bit tangential, this template uses the `cargo` build style instead of the `meson` one and recommends checking all `meson.build` files during each update. I think this is probably not the ideal approach so I had these changes when I updated it locally a few months ago.

```patch
diff --git a/srcpkgs/helvum/template b/srcpkgs/helvum/template
index 1f3c89a66..071033ee1 100644
--- a/srcpkgs/helvum/template
+++ b/srcpkgs/helvum/template
@@ -2,10 +2,12 @@
 pkgname=helvum
 version=0.4.0
 revision=1
-build_style=cargo
-hostmakedepends="pkg-config clang libclang"
-makedepends="gtk4-devel pipewire-devel glib-devel"
+build_style=meson
+build_helper="rust"
+hostmakedepends="pkg-config clang libclang cargo desktop-file-utils gtk4-update-icon-cache"
+makedepends="gtk4-devel pipewire-devel glib-devel rust-std"
 depends="pipewire"
+checkdepends="desktop-file-utils appstream-glib"
 short_desc="GTK patchbay for pipewire"
 maintainer="0x5c <dev@0x5c.io>"
 license="GPL-3.0-only"
@@ -13,17 +15,9 @@ homepage="https://gitlab.freedesktop.org/pipewire/helvum"
 distfiles="https://gitlab.freedesktop.org/pipewire/helvum/-/archive/${version}/helvum-${version}.tar.gz"
 checksum=e93afa788d3e50bae489db888ecf0d79e5735b8f4f8b29fe4174540b0872b622
 
-post_install() {
-	# Normally, meson would do this, but it's simpler to use the cargo build style and do this manually
-	# This also avoids the need for makedeps/build steps that are made unnecessary by xbps' hooks
-	# On update, all meson.build files should be checked for changes
-	_app_id='org.pipewire.Helvum'
-	vinstall data/icons/$_app_id.svg 644 usr/share/icons/hicolor/scalable/apps/
-	vinstall data/icons/$_app_id-symbolic.svg 644 usr/share/icons/hicolor/symbolic/apps/
-
-	vsed -i data/$_app_id.desktop.in -e "s/@icon@/$_app_id/"
-	vinstall data/$_app_id.desktop.in 644 usr/share/applications/ $_app_id.desktop
-
-	vsed -i data/$_app_id.metainfo.xml.in -e "s/@app-id@/$_app_id/"
-	vinstall data/$_app_id.metainfo.xml.in 644 usr/share/metainfo/ $_app_id.metainfo.xml
+post_patch() {
+	if [ "$CROSS_BUILD" ]; then
+		vsed -i src/meson.build \
+		 	-e "s%rust_target /%'${RUST_TARGET}' / rust_target /%"
+	fi
 }
```

**Comment by 0x5c** [comment]
> A bit tangential, this template uses the `cargo` build style instead of the `meson` one and recommends checking all `meson.build` files during each update. I think this is probably not the ideal approach so I had these changes when I updated it locally a few months ago.


The meson story is a pure nuisance for downstream packagers, since all it does is a couple of template filling operations *and things that should only run on the end-user system* in xbps triggers. The reason upstream has it is so that `meson install` does the desktop db update on gnome systems for users that manually build helvum, and for flatpack dist.

**Comment by 0x5c** [comment]
On top of the above, the meson build needlessly bypasses some of our setup for properly building/testing/installing cargo projects

**Comment by icp1994** [comment]
Oh, I wasn't aware of that. I thought this was a common pattern for gtk4+rust apps - fex [amberol](https://github.com/void-linux/void-packages/blob/master/srcpkgs/amberol/template), [gnome-authenticator](https://github.com/void-linux/void-packages/blob/master/srcpkgs/gnome-authenticator/template), [shortwave](https://github.com/void-linux/void-packages/blob/master/srcpkgs/shortwave/template) etc.

**Comment by 0x5c** [comment]
> Oh, I wasn't aware of that. I thought this was a common pattern for gtk4+rust apps - fex [amberol](https://github.com/void-linux/void-packages/blob/master/srcpkgs/amberol/template), [gnome-authenticator](https://github.com/void-linux/void-packages/blob/master/srcpkgs/gnome-authenticator/template), [shortwave](https://github.com/void-linux/void-packages/blob/master/srcpkgs/shortwave/template) etc.

Yeah, it's common for gnome stuff both for the same reasons as above and also because they're often based on a template that does it, along with even worse things like changing `CARGO_HOME` to break caching

**Comment by 0x5c** [comment]
Ok so I found the bug and have a fix that builds. Logically it should be good to go but I can't really test the i686 build currently

**Pull request merged**
