### PR TITLE
firefox-esr: update to 102.7.0

### PR DESCRIPTION
**Pull request by Zapeth**
#### Testing the changes
- I tested the changes in this PR: **briefly**

~I currently dont have the space to build and test this locally, but~ I wanted to at least start it off since apparently a somewhat important issue from 102 version was fixed -> https://bugzilla.mozilla.org/show_bug.cgi?id=1781167

Feel free to close this again, or use it for testing (there were also some language packs missing which I added)

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc

[ci skip]

### CODE REVIEW

**Comment by Zapeth** [comment]
Thanks, added (build process should at least start now)

**Comment by Zapeth** [comment]
> ValueError: invalid mode: 'rU'

Added a new patch that should fix this (can be removed at the next major esr update), still keeping the other python patch though since its also python3.11 related

**Comment by biopsin** [comment]
@Zapeth  the fix-util-python3.11.patch seems incomplete as there are more invalid rU value errors

```
 0:20.25 Creating config.status
 0:20.58 Reticulating splines...
 0:20.97  0:00.43 File already read. Skipping: /builddir/firefox-esr-102.6.0/intl/components/moz.build
 0:21.27  0:00.72 File already read. Skipping: /builddir/firefox-esr-102.6.0/gfx/angle/targets/angle_common/moz.build
 0:24.77 Traceback (most recent call last):
 0:24.77   File "/builddir/firefox-esr-102.6.0/python/mozbuild/mozbuild/preprocessor.py", line 863, in do_include
 0:24.77     args = io.open(args, "rU", encoding="utf-8")
 0:24.77            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 0:24.77 ValueError: invalid mode: 'rU'
 0:24.77 During handling of the above exception, another exception occurred:
 0:24.77 Traceback (most recent call last):
 0:24.77   File "/builddir/firefox-esr-102.6.0/configure.py", line 349, in <module>
 0:24.77     sys.exit(main(sys.argv))
 0:24.77              ^^^^^^^^^^^^^^
 0:24.77   File "/builddir/firefox-esr-102.6.0/configure.py", line 161, in main
 0:24.77     return config_status(config)
 0:24.77            ^^^^^^^^^^^^^^^^^^^^^
 0:24.77   File "/builddir/firefox-esr-102.6.0/configure.py", line 300, in config_status
 0:24.77     return config_status(args=[], **sanitized_config)
 0:24.77            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 0:24.77   File "/builddir/firefox-esr-102.6.0/python/mozbuild/mozbuild/config_status.py", line 165, in config_status
 0:24.77     the_backend.consume(definitions)
 0:24.77   File "/builddir/firefox-esr-102.6.0/python/mozbuild/mozbuild/backend/base.py", line 132, in consume
 0:24.77     if not self.consume_object(obj) and not isinstance(self, PartialBackend):
 0:24.77            ^^^^^^^^^^^^^^^^^^^^^^^^
 0:24.77   File "/builddir/firefox-esr-102.6.0/python/mozbuild/mozbuild/backend/recursivemake.py", line 425, in consume_object
 0:24.77     consumed = CommonBackend.consume_object(self, obj)
 0:24.77                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 0:24.77   File "/builddir/firefox-esr-102.6.0/python/mozbuild/mozbuild/backend/common.py", line 132, in consume_object
 0:24.77     pp.do_include(obj.input_path)
 0:24.77   File "/builddir/firefox-esr-102.6.0/python/mozbuild/mozbuild/preprocessor.py", line 867, in do_include
 0:24.77     raise Preprocessor.Error(self, "FILE_NOT_FOUND", _to_text(args))
 0:24.77 mozbuild.preprocessor.Preprocessor.Error: ('', 0, 'FILE_NOT_FOUND', '/builddir/firefox-esr-102.6.0/config/autoconf.mk.in')
 Config object not found by mach.
*** Fix above errors and then restart with "./mach build"
=> ERROR: firefox-esr-102.6.0_1: do_build: './mach build' exited with 1
=> ERROR:   in do_build() at srcpkgs/firefox-esr/template:235

```

**Comment by paper42** [comment]
I think that trying to update a package without even being able to build it is a terrible idea and will just result in a lot of inefficient communication. @biopsin feel free to open a PR and I can close this one.

**Comment by Zapeth** [comment]
Yeah, as I said at the beginning, feel free to close this and possibly use it for a fully tested PR

I did a last update for the patch where I grep'ed the source archive for `"rU"`, but there could be other issues down the road

**Comment by biopsin** [comment]
@Zapeth Looking over the template I cant find that files/mozconfig is being sourced anymore, can we stop vendoring it since add_options are defined in template?

**Comment by Zapeth** [comment]
I managed to make some space on my machine and was able to build `firefox-esr` and `firefox-esr-i18n` (the only issue I came across was a language entry not being ordered correctly which caused checksum issues, but thats fixed now)

I also had to update my system packages due to the recent gcc update, but after that I was able to use the new version (briefly tested it, updated description)

> @Zapeth Looking over the template I cant find that files/mozconfig is being sourced anymore, can we stop vendoring it since add_options are defined in template?

I think so, yes. I compared the add_options and the only difference I found was that `--enable-system-ffi` is now set with `--with-system-ffi`. I don't know which of the two should be set, but I'd keep the latter since its also used in the normal firefox package.

So I went ahead and removed it, and rebased again

**Comment by biopsin** [comment]
@Zapeth  I will go ahead and test defaults as excluding wayland from build_options in this version fails, so it might no longer be a option any longer too.

**Comment by paper42** [comment]
@Zapeth I merged your python 3.11 fixes separately, could you rebase this PR?

**Comment by Zapeth** [comment]
Rebased and updated to 102.7.0

**Comment by biopsin** [comment]
@Zapeth 
we are also trying to vendor a files/stab.h for *-musl which is missing, see post_extract.
Probably should be copied from firefox files too.

**Comment by Zapeth** [comment]
I'm not sure what you mean, stab.h is already in the files directory of the package and should be copied from there -> https://github.com/void-linux/void-packages/blob/master/srcpkgs/firefox-esr/files/stab.h

**Comment by biopsin** [comment]
never mind, its missing locally for unknown reason.

**Comment by biopsin** [comment]
@Zapeth I've bin testing 102.8. since released

**Comment by Zapeth** [comment]
> @Zapeth I've bin testing 102.8. since released

I've noticed that firefox-esr 102.8 update is now included in https://github.com/void-linux/void-packages/pull/42285

@paper42 @Duncaen Is there a point in keeping this PR open/updated? I think in the long term it would make more sense to include esr updates with regular firefox updates. They get released simultaneously and esr is basically just an older codebase of the regular package, so there should rarely be any esr-specific issues.

**Pull request closed without merging**
