### PR TITLE
rust: update to 1.53.0

### PR DESCRIPTION
**Pull request by ericonr**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

@jnbr @q66

### CODE REVIEW

**Comment by ericonr** [comment]
Still needs the `nocross for now` commit, but besides that it looks good to go. CI managed to run for all the cross builds :)

Pending on ppc from @q66 if he wants to get those ready before merging.

I have built thunderbird with this toolchain and it seems to be working ok.

**Comment by ericonr** [comment]
Going to wait on llvm 12

**Comment by cinerea0** [comment]
@ericonr What is the specific reason for this blocking on llvm 12? Would cargo and rust need to be rebuilt against it when it gets added?

**Comment by ericonr** [comment]
@cinerea0 yes, I believe that was it.

**Comment by ericonr** [comment]
Will definitely update, after my attempt at libreoffice is over.

**Comment by ericonr** [comment]
Updated

**Comment by ericonr** [comment]
Tagging as CI skip to push some cosmetic changes, but fully working CI results can be seen in https://github.com/void-linux/void-packages/actions/runs/835775216

**Comment by rustysec** [comment]
Is there a status update on this? I have another PR I would like to open but it depends on a newer rust version.

**Comment by ericonr** [comment]
It's pending on q66 doing the ppc side of things.

You can clone this locally and use it to test your packages, then just make a PR with `pending on rust update` in the name.

**Comment by paper42** [comment]
Tests fail for me
```
=> rust-1.52.1_1: running do_check ...
    Finished dev [unoptimized + debuginfo] target(s) in 0.24s
warning: x.py has made several changes recently you may want to look at
help: consider looking at the changes in `src/bootstrap/CHANGELOG.md`
note: to silence this warning, add `changelog-seen = 2` at the top of `config.toml`
thread 'main' panicked at 'error: no rules matched src/test/compile-fail', src/bootstrap/builder.rs:225:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:435:5
   2: bootstrap::builder::StepDescription::run
             at ./src/bootstrap/builder.rs:225:17
   3: bootstrap::builder::Builder::run_step_descriptions
             at ./src/bootstrap/builder.rs:571:9
   4: bootstrap::builder::Builder::execute_cli
             at ./src/bootstrap/builder.rs:563:9
   5: bootstrap::Build::build
             at ./src/bootstrap/lib.rs:506:17
   6: bootstrap::main
             at ./src/bootstrap/bin/main.rs:33:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
failed to run: /builddir/rustc-1.52.1-src/build/bootstrap/debug/bootstrap test -j8 --no-doc --no-fail-fast src/test/codegen src/test/codegen-units src/test/compile-fail src/test/incremental src/test/mir-opt src/test/pretty src/test/run-fail src/test/run-fail/pretty src/test/run-make src/test/run-make-fulldeps src/test/ui src/test/ui-fulldeps
Build completed unsuccessfully in 0:00:00
=> ERROR: rust-1.52.1_1: do_check: 'python3 x.py test ${makejobs} --no-doc --no-fail-fast src/test/codegen src/test/codegen-units src/test/compile-fail src/test/incremental src/test/mir-opt src/test/pretty src/test/run-fail src/test/run-fail/pretty src/test/run-make src/test/run-make-fulldeps src/test/ui src/test/ui-fulldeps' exited with 1
=> ERROR:   in do_check() at srcpkgs/rust/template:304
```

**Comment by ericonr** [comment]
@paper42 any idea why it fails? Could be due to our patching.

**Comment by paper42** [comment]
> @paper42 any idea why it fails? Could be due to our patching.

I have no idea, I don't know enough about rust.

**Comment by cinerea0** [comment]
@paper42 How are you getting this error? Rust compiled fine for me when I tried the commits in this PR last night.

**Comment by paper42** [comment]
@cinerea0 it compiles fine, check fails.
```
./xbps-src check rust
```

**Comment by cinerea0** [comment]
Yeah, I'm getting the error now. Here's the output using RUST_BACKTRACE=full:

```
thread 'main' panicked at 'error: no rules matched src/test/compile-fail', src/bootstrap/builder.rs:225:17
stack backtrace:
   0:     0x55f848efe6b0 - std::backtrace_rs::backtrace::libunwind::trace::h74532f8b485906a1
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55f848efe6b0 - std::backtrace_rs::backtrace::trace_unsynchronized::h2c8425dd0be5999b
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55f848efe6b0 - std::sys_common::backtrace::_print_fmt::hd8ce6577f46119ce
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55f848efe6b0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6289eeebc1f97d57
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55f848f22cff - core::fmt::write::h3d3f8a8bb9d4c367
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/fmt/mod.rs:1092:17
   5:     0x55f848ef9e32 - std::io::Write::write_fmt::ha117cbfa72664a7b
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/io/mod.rs:1572:15
   6:     0x55f848f015c5 - std::sys_common::backtrace::_print::h112e8a4ac2720a21
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55f848f015c5 - std::sys_common::backtrace::print::h2a4ab5824600ebce
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55f848f015c5 - std::panicking::default_hook::{{closure}}::h399ab06c3b83a1f2
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:208:50
   9:     0x55f848f01073 - std::panicking::default_hook::h7481e93ca9c2d739
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:225:9
  10:     0x55f848f01bcd - std::panicking::rust_panic_with_hook::h01f9d4e9485ccb8b
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:591:17
  11:     0x55f848f01767 - std::panicking::begin_panic_handler::{{closure}}::h25bff4eb752cc444
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:497:13
  12:     0x55f848efeb6c - std::sys_common::backtrace::__rust_end_short_backtrace::h5dfd3f7920e58cc5
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55f848f016c9 - rust_begin_unwind
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:493:5
  14:     0x55f848484fab - std::panicking::begin_panic_fmt::h5ea05d30b78d4fb2
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:435:5
  15:     0x55f848962d57 - bootstrap::builder::StepDescription::run::h7959fb55c5ccedec
                               at /builddir/rustc-1.52.1-src/src/bootstrap/builder.rs:225:17
  16:     0x55f8489664ba - bootstrap::builder::Builder::run_step_descriptions::h1e65121b32641c91
                               at /builddir/rustc-1.52.1-src/src/bootstrap/builder.rs:571:9
  17:     0x55f848966396 - bootstrap::builder::Builder::execute_cli::he17f02d612b6ec68
                               at /builddir/rustc-1.52.1-src/src/bootstrap/builder.rs:563:9
  18:     0x55f84848ae4b - bootstrap::Build::build::he59c79f668638183
                               at /builddir/rustc-1.52.1-src/src/bootstrap/lib.rs:506:17
  19:     0x55f84848675b - bootstrap::main::h4659e37ed446ebcb
                               at /builddir/rustc-1.52.1-src/src/bootstrap/bin/main.rs:33:5
  20:     0x55f848486eab - core::ops::function::FnOnce::call_once::h1a8cd00380f36571
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/ops/function.rs:227:5
  21:     0x55f8484874fe - std::sys_common::backtrace::__rust_begin_short_backtrace::h13d252e39becdd1c
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:125:18
  22:     0x55f8484861f1 - std::rt::lang_start::{{closure}}::h05db9941e783416a
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/rt.rs:66:18
  23:     0x55f848f020ca - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha7db63b609be77e3
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/ops/function.rs:259:13
  24:     0x55f848f020ca - std::panicking::try::do_call::h715c8c8ca0806d14
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:379:40
  25:     0x55f848f020ca - std::panicking::try::h2530c507ef432acf
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:343:19
  26:     0x55f848f020ca - std::panic::catch_unwind::h0c4984a63ffdd417
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panic.rs:431:14
  27:     0x55f848f020ca - std::rt::lang_start_internal::h12392519f60c6396
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/rt.rs:51:25
  28:     0x55f8484861d0 - std::rt::lang_start::h8cdadcc7fbf2ca81
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/rt.rs:65:5
  29:     0x55f848486dbc - main
  30:     0x7f81ca422e0a - __libc_start_main
                               at /builddir/glibc-2.32/csu/../csu/libc-start.c:314:16
  31:     0x55f8484860da - <unknown>
                               at /builddir/glibc-2.32/csu/../sysdeps/x86_64/start.S:120
  32:                0x0 - <unknown>
failed to run: /builddir/rustc-1.52.1-src/build/bootstrap/debug/bootstrap test -j1 --no-doc --no-fail-fast src/test/codegen src/test/codegen-units src/test/compile-fail src/test/incremental src/test/mir-opt src/test/pretty src/test/run-fail src/test/run-fail/pretty src/test/run-make src/test/run-make-fulldeps src/test/ui src/test/ui-fulldeps
```

**Comment by cinerea0** [comment]
This may be a lot simpler than I thought. I took a look in the `src/test/` directory, and if there was a  "compile-fail" set of tests they don't exist anymore. The "run-fail" and it's sub-test listed in the template don't exist anymore either. Taking out the non-existent tests results in the check process proceeding as it should. I didn't have the forethought to redirect the output to a file and the amount of output exceeded my scrollback buffer, but from what I saw only a few tests failed out of the thousands that were run. I can try to get the full output and link it to here if that would be helpful.

If you want to take a look at the descriptions of all of the available tests, check here: https://rustc-dev-guide.rust-lang.org/tests/intro.html. I don't know if any of them replace the ones that had to be taken out or if any of them even need replacing; that stuff is way over my head.

As a side note, is q66 still working on the ppc stuff for llvm12?

**Comment by cinerea0** [comment]
```diff
diff --git a/srcpkgs/rust/template b/srcpkgs/rust/template (copy)
index 8df40053a1..d3dc5715b8 100644
--- a/srcpkgs/rust/template
+++ b/srcpkgs/rust/template (copy)	
@@ -304,12 +304,9 @@ do_check() {
 	python3 x.py test ${makejobs} --no-doc --no-fail-fast \
 		src/test/codegen \
 		src/test/codegen-units \
-		src/test/compile-fail \
 		src/test/incremental \
 		src/test/mir-opt \
 		src/test/pretty \
-		src/test/run-fail \
-		src/test/run-fail/pretty \
 		src/test/run-make \
 		src/test/run-make-fulldeps \
 		src/test/ui \
```

**Comment by cinerea0** [comment]
The above diff will bring the patches into line with what the newest version of the compiler uses for tests. The "compile-fail" and "run-fail" categories got absorbed into the "ui" category.

**Comment by ericonr** [comment]
I built Firefox successfully with 1.53.0. Good to merge on the `x86_64-musl` side, mainly waiting for @q66 to produce tarballs.

**Comment by cinerea0** [comment]
@q66 Any update on the tarballs?

**Comment by ericonr** [comment]
Merged manually.

**Pull request closed without merging**
