### PR TITLE
bomi: remove package

### PR DESCRIPTION
**Pull request by UsernameRandomlyGenerated**
Unmaintaned and broken.

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

The UI doesn't load for me (saw a similar issue on bomi github page), last release was 6 years ago and it's not maintained anymore.

### CODE REVIEW

**Comment by paper42** [comment]
Closes #11287

**Comment by ericonr** [comment]
@skrzyp ok?

And please mention in the commit how it was broken, since it could still be built.

**Comment by paper42** [comment]
@ericonr bomi is the last dependant of libchardet, but libchardet is still being developed

**Comment by skrzyp** [comment]
> @skrzyp ok?
> 
> And please mention in the commit how it was broken, since it could still be built.

ok for me, I was thinking about purging these unmaintained programs on my own so feel free to proceed

**Comment by ericonr** [comment]
@paper42 no reason to remove libchardet yet, but thanks for the notice.

**Pull request merged**
