### PR TITLE
zlib: fix update-check

### PR DESCRIPTION
**Pull request by Bnyro**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by Chocimier** [comment]
old pattern just works, why the change?

**Comment by Bnyro** [comment]
It doesn't work, it outputs there word be a 1213 release.

**Comment by Bnyro** [comment]
Because it doesn't handle dots properly.

**Comment by Chocimier** [comment]
?

```
./xbps-src update-check zlib      
using zlib/update overrides
fetching https://www.zlib.net and scanning with <B> zlib \K.+?(?=</B>)
fetching https://www.zlib.net/fossils/ and scanning with <B> zlib \K.+?(?=</B>)
found version 1.2.13
```

**Comment by Bnyro** [comment]
Oh, I just noticed the issue is when checking for updates for `zlib-32bit`, `zlib` itself works properly:
```
$ ./xbps-src update-check zlib-32bit
zlib-1.2.13 -> zlib-1213
```
But I don't really have a clue why it works properly for zlib in the meanwhile, don't they use the same template?

**Comment by Chocimier** [comment]
update-check on `-32bit` packages is not an useful operation, as they are made from plain i686 build.
Going to details, this didn't work because xbps-src tries to read non-existent `srcpkgs/zlib-32bit/update` here.

**Comment by Bnyro** [comment]
Makes sense, thanks!

**Pull request closed without merging**
