### PR TITLE
moosefs: update to 4.56.6

### PR DESCRIPTION
**Pull request by toomyem**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)
- I built this PR locally for these architectures (using crossbuilds):
  - aarch64-musl
  - armv7l
  - armv6l-musl

### CODE REVIEW

**Comment by classabbyamp** [comment]
why do we need both 3.x and 4.x?

**Comment by toomyem** [comment]
I assumed that someone may want to stay on 3.x line for whatever reason. Similar to keeping both python2 and 3.

**Comment by classabbyamp** [comment]
I don't think it's similar. python 2 and 3 are kept separate because they are incompatible, and there are other packages that depend on them (same for things like libgit2 and libgit2-1.8)

**Comment by toomyem** [comment]
Ok, then another example may be java 17 and 21. Is it a problem to have two lines 0of moosefs for some time? When 4.x line matures, we can remove the old one.

**Comment by classabbyamp** [comment]
java is another example like python (actually it's worse, you need java N-1 to bootstrap java N).

either update it to the latest 3.x or the latest 4.x, but I don't see a point in making two packages. Major version bumps happen all the time in void, we do not make new packages for every single one.

**Comment by toomyem** [comment]
Ok, so I updated it to 4.x line.

**Comment by toomyem** [comment]
Any chance to get it merged?

**Pull request merged**
