### PR TITLE
Remove noarch from aspell-*

### PR DESCRIPTION
**Pull request by henryprecheur**
aspell dictionaries aren't architecture independent: the dictionary format depends on size_t, therefor it needs to be made architecture specific. This is why the dictionaries are stored in /usr/lib and not in /usr/share.

Without this fix, I get the following error on amd64 when running `aspell check -l fr`:

> Error: The file "/usr/lib/aspell-0.60/fr-40-only.rws" is not in the proper format. Incompatible hash function.

This fixes the aspell-fr package on amd64 and probably most 64bits architectures.

More information about this:

http://aspell.net/0.61/man-html/Using-32_002dBit-Dictionaries-on-a-64_002dBit-System.html

### CODE REVIEW

**Comment by henryprecheur** [comment]
I have only fixed the aspell-fr package. If you would like me to fix all the other aspell dictionaries I can do that too.

**Comment by ericonr** [comment]
I think it would make sense to include all dict here. One commit for each, though.

**Comment by henryprecheur** [comment]
All the dictionaries are now fixed. Let me know if there's anything else that's required to get this merged.

**Comment by ericonr** [comment]
Oh, sorry! You should _probably_ make the commit messages look like `aspell-fr: remove noarch`

**Comment by henryprecheur** [comment]
Done.

**Pull request merged**
