### PR TITLE
tty-clock: fix license

### PR DESCRIPTION
**Pull request by lugubris**
change from GPL-3 to BSD-3-Clause
-> https://github.com/xorg62/tty-clock/blob/master/LICENSE

### CODE REVIEW

**Comment by lugubris** [comment]
git rebase is cool!

**Comment by lugubris** [comment]
I rebased my master from upstream and then rebased this branch from master - all conflicts resolved

**Comment by Hoshpak** [comment]
I didn't anticipate that the license file is not included in the release tarball, that unfortunately makes it more difficult. The license file needs to be fetched via distfiles, added to `skip_extraction` and added via vlicense in a different way. You can find an example of how to to this in the `python-discogs_client` template.

**Comment by lugubris** [comment]
looks good now?

**Pull request merged**
