### PR TITLE
haproxy: update to 1.8.14.

### PR DESCRIPTION
**Pull request by matejgera**

### CODE REVIEW

**Comment by Johnnynator** [comment]
The commit message itself should also formatted as `pkgname: update to version` as you did in the pr title. Also did you actually test this locally? The build log looks like the libressl patch needs to be updated.

**Comment by matejgera** [comment]
I see now, didn't have my local environment set up properly. How would I go about updating the patch?

**Comment by Johnnynator** [comment]
> I see now, didn't have my local environment set up properly. How would I go about updating the patch?

There are generally different ways of doing it. In the end you just either need a second patch file or a rewritten on. I personally use either the upstream git repo and git diff or go into the builddir in `masterdir/builddir/haproxy-*` and use vim and save the diff with `w !diff -u  % - >> ~/void-packages/srcpkgs/haproxy/patches/libressl-2.8.patch`.

**Comment by Johnnynator** [comment]
This patch for the patch file should do it, but you should test it before adding it.
```patch
diff --git a/srcpkgs/haproxy/patches/libressl-2.7.patch b/srcpkgs/haproxy/patches/libressl-2.7.patch
index 6c348dc527..7cc1dd3601 100644
--- a/srcpkgs/haproxy/patches/libressl-2.7.patch
+++ b/srcpkgs/haproxy/patches/libressl-2.7.patch
@@ -102,3 +102,23 @@ index c2b5bf6..ebde76d 100644
  		if (!SSL_is_init_finished(conn->xprt_ctx)) {
  			unsigned int max_early;
  
+--- masterdir/builddir/haproxy-1.8.14/src/ssl_sock.c	2018-10-21 20:57:07.520516300 +0200
++++ -	2018-10-21 21:08:48.989272557 +0200
+@@ -5133,7 +5133,7 @@
+ 					OSSL_HANDSHAKE_STATE state = SSL_get_state((SSL *)conn->xprt_ctx);
+ 					empty_handshake = state == TLS_ST_BEFORE;
+ #else
+-					empty_handshake = !((SSL *)conn->xprt_ctx)->packet_length;
++					empty_handshake = SSL_state((SSL *)conn->xprt_ctx) == SSL_ST_BEFORE;
+ #endif
+ 					if (empty_handshake) {
+ 						if (!errno) {
+@@ -5217,7 +5217,7 @@
+ 				OSSL_HANDSHAKE_STATE state = SSL_get_state((SSL *)conn->xprt_ctx);
+ 				empty_handshake = state == TLS_ST_BEFORE;
+ #else
+-				empty_handshake = !((SSL *)conn->xprt_ctx)->packet_length;
++				empty_handshake = SSL_state((SSL *)conn->xprt_ctx) == SSL_ST_BEFORE;
+ #endif
+ 				if (empty_handshake) {
+ 					if (!errno) {
```

**Comment by matejgera** [comment]
Thank you for that! I updated the patch file, tested building and at runtime locally, everything worked, TravisCI also now seem to complete the checks.

**Comment by matejgera** [comment]
Thank you for that! I updated the patch file, tested building and at runtime locally, everything worked, TravisCI also now seem to complete the checks.

**Comment by matejgera** [comment]
Thank you for that! I updated the patch file, tested building and at runtime locally, everything worked, TravisCI also now seem to complete the checks.

**Pull request merged**
