### PR TITLE
chromium: update to 72.0.3626.96.

### PR DESCRIPTION
**Pull request by Cogitri**
[ci skip]

### CODE REVIEW

**Comment by Cogitri** [comment]
Mind taking a look @duncaen, especially on musl? Binaries are on https://exp.exqa.de if you want those.

**Comment by Duncaen** [comment]
@Cogitri seems to work with gmail which would reliably crash if there is an issue and other non heavy sites.

It logged some errors, some seem to be related to not running dbus etc, not sure for what it uses `/etc/machine-id`.
Not sure what to do about VA-API and the sandbox error.  

```
[7621:7621:0205/115203.987420:ERROR:browser_dm_token_storage_linux.cc(93)] Error: /etc/machine-id contains 0 characters (32 were expected).
[7621:7654:0205/115204.048744:ERROR:bus.cc(396)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[7649:7649:0205/115204.106556:ERROR:vaapi_wrapper.cc(337)] This build of Chromium requires VA-API version 1.3, system version: 1.4
[7649:7649:0205/115204.128530:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
[7621:7621:0205/115208.441022:ERROR:x11_input_method_context_impl_gtk.cc(144)] Not implemented reached in virtual void libgtkui::X11InputMethodContextImplGtk::SetSurroundingText(const string16&, const gfx::Range&)
[7621:7621:0205/115412.622640:ERROR:gaia_auth_fetcher.cc(71)] Missing ID token on refresh token fetch response.
```

**Comment by Cogitri** [comment]
Looks OK to me. I guess we'll have to eventually upgrade VAAPI, but this shouldn't block this PR

**Comment by Duncaen** [comment]
> Looks OK to me. I guess we'll have to eventually upgrade VAAPI, but this shouldn't block this PR

We are ahead of chromium, this makes the patch useless.

**Comment by Cogitri** [comment]
Oh, read it the wrong way. I guess I could disable the patch, but that'll result in a rather big diff for something that doesn't change anything for the user and will most likely be introduced again in the next release.

**Comment by freshprince** [comment]
72.0.3626.96 just got released

**Comment by Cogitri** [comment]
Updating...

**Comment by Cogitri** [comment]
Built for x86_64{,-musl}, mind testing again @Duncaen? Currently building i686.

**Comment by Cogitri** [comment]
Just updated it, building right now

**Pull request closed without merging**
