### PR TITLE
Trim down lua*-devel dependencies

### PR DESCRIPTION
**Pull request by ericonr**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

@q66

### CODE REVIEW

**Comment by q66** [comment]
you should also be able to drop ncurses from 5.3+

**Comment by ericonr** [comment]
It would seem 5.2 dropped any reference to curses from their stuff already, any reason you're starting with 5.3?

**Comment by sgn** [comment]
No need to callout f0105c662bd1be3c1e84271fb6a63da7e6bf3752 in lua53, the depends was there before that.

**Comment by q66** [comment]
hm, yeah i guess 5.2+

**Pull request merged**
