### PR TITLE
godot: update to 3.1.1

### PR DESCRIPTION
**Pull request by obunden**

### CODE REVIEW

**Comment by obunden** [comment]
I wanted to try to update to the latest version because it fixes a security issue. I thought it wouldn't work at all because of an issue that I found posted here in the repo. But everything compiles fine on x86_64 and godot works as intended. Sadly travis was super slow at compiling for x86/x86_64. Don't see why tho, can the jobs be a lot slower at random times? The other platforms failed and I don't have any experience with fixing that kind of thing, and I don't have access to any other hardware.

Gonna look into it at a later time but if someone can test the package I would really appreciate it.

Here's the issue that I mentioned: https://github.com/void-linux/void-packages/issues/10244

**Comment by Hoshpak** [comment]
The llvm9 package wasn't built yet when the travis job was started so it tried to build it first. Since llvm is massive, it will always time out on travis. I restarted the travis job now that llvm9 is finished so it can compile godot regularly.

**Comment by obunden** [comment]
Ok I see, hope it works now. Thanks for all the help and information in general and the speedy handling of the pull requests. Have a nice day :)

**Comment by obunden** [comment]
Seems like it's the same story again. Will you test this manually @Hoshpak ? I had a quick look on the travis website and it that jobs time out after 120 min. But I found out that it's for private repos. Someone raised an issue about this and wanted to have the same limit for public open source projects. It's kinda old but might be worth a read if raising the limit would be useful.

https://github.com/travis-ci/travis-ci/issues/9605#issuecomment-388051236

**Comment by Hoshpak** [comment]
Will do, it might take some time though.

**Pull request merged**
