### PR TITLE
pounce: update to 2.1p1

### PR DESCRIPTION
**Pull request by paper42**

### CODE REVIEW

**Comment by ericonr** [comment]
Would you mind reporting this to the author? From the `armv6l-musl` build:

```
ring.c:143:2: warning: unsigned conversion from 'long long int' to 'unsigned int' changes value from '392952706068336' to '1853190000' [-Woverflow]
  143 |  0x0165636E756F70, // no ring size
      |  ^~~~~~~~~~~~~~~~
ring.c:144:2: warning: unsigned conversion from 'long long int' to 'unsigned int' changes value from '674427682778992' to '1853190000' [-Woverflow]
  144 |  0x0265636E756F70, // time_t only
      |  ^~~~~~~~~~~~~~~~
ring.c:145:2: warning: unsigned conversion from 'long long int' to 'unsigned int' changes value from '955902659489648' to '1853190000' [-Woverflow]
  145 |  0x0365636E756F70,
      |  ^~~~~~~~~~~~~~~~
```

This should probably be fixed, or the software should be marked as broken on 32bit platforms.

**Comment by paper42** [comment]
Thanks for catching this, I should really test armv6 too. I wrote an email to the author.

**Comment by causal-agent** [comment]
@ericonr can you confirm that this patch solves the issue?
[0001-Use-uint64_t-for-save-file-signature.patch.txt](https://github.com/void-linux/void-packages/files/5611466/0001-Use-uint64_t-for-save-file-signature.patch.txt)

**Comment by ericonr** [comment]
@causal-agent No more warnings, at least :)

Can't check at runtime, though.

**Comment by causal-agent** [comment]
Thanks. I've tagged a patch release: https://git.causal.agency/pounce/tag/?h=2.1p1

**Comment by ericonr** [comment]
I will leave updating the PR to @paper42, then :) 

@causal-agent thanks for the quick answer! since it already built, just showed warnings while doing so, do you think there could be users on 32bit systems where the file signature is now wrong?

>  `'392952706068336' to '1853190000'`

**Comment by causal-agent** [comment]
I don't think save files would have ever loaded successfully on 32-bit, since the data version number gets truncated. (load would assume the data is version 0 always)

**Comment by ericonr** [comment]
@causal-agent for the record, you got yourself some new warnings :P 

```ring.c:208:2: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
  208 |  fread(&signature, sizeof(signature), 1, file);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Praise be glibc's headers and their attributes :D

**Comment by causal-agent** [comment]
glibc presumes to know better than me. I'm not a fan.

**Pull request merged**
