### PR TITLE
granite 6

### PR DESCRIPTION
**Pull request by paper42**
#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by paper42** [comment]
@LinArcX we need to rebuild everything that links against granite for this update which includes giti, but the giti build is  currently broken because of a new vala version, so I added a commit to remove it from void-packages for now. If we can fix it, it doesn't need to be removed.

**Comment by CameronNemo** [comment]
Wow thanks for tackling this... was just staring at my long list of out of date packages. Many of them elementary-ware.

What was your logic on updating vs. just revbump-ing? E.g. switchboard-plug-bluetooth has updates available.

**Comment by paper42** [comment]
> What was your logic on updating vs. just revbump-ing? E.g. switchboard-plug-bluetooth has updates available.

I updated packages that fail to build with meson 0.61 to avoid patching every single one of them. Now everything should be updated.

**Comment by 0x5c** [comment]
This would obsolete https://github.com/void-linux/void-packages/pull/34754

**Comment by paper42** [comment]
@CameronNemo I had to rebase your patch for Elementary Calendar - 9032015c23b4565a12c772236d63411237c01458, I see you made a PR upstream, could you update it with these changes if you find them appropriate? https://github.com/elementary/calendar/pull/280. I will credit you as the original author of the patch with the next push, I forgot to do that now, sorry about that.

**Pull request merged**
