### PR TITLE
oksh: remove.

### PR DESCRIPTION
**Pull request by travankor**
Unmaintained, missing upstream security fixes.
loksh is a drop-in replacement.

### CODE REVIEW

**Comment by Duncaen** [comment]
I really don't like this commit. Why does loksh need a INSTALL.msg about oksh?
Why does the commit remove on template and touch/revbump another package?
Why the symlink to loksh, there is no subpackage provides/replaces the old oksh package?

**Comment by Duncaen** [comment]
Ok this was already fixed in tree.

https://github.com/void-linux/void-packages/commit/6f5b634e5cdb2bdd2ff68ae66c891b3193d3134d
https://github.com/void-linux/void-packages/commit/297723095fb0bc3e52dad12266818e7b1f5a02ed
https://github.com/void-linux/void-packages/commit/c0cc0fbf7b130c33c16b6de7d3d1c712ef09ef9f

**Comment by Duncaen** [comment]
@maxice8 even after the fix this is going to break users systems if they used oksh as login shell, I think xbps-alternatives saved it from breaking /bin/sh in general if someone used it as /bin/sh.

**Comment by maxice8** [comment]
On Wed, Jan 02, 2019 at 02:12:46PM -0800, Duncan Overbruck wrote:
> @maxice8 even after the fix this is going to break users systems if they used oksh as login shell, I think xbps-alternatives saved it from breaking /bin/sh in general if someone used it as /bin/sh.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/6416#issuecomment-451001572

Sorry ><

**Pull request merged**
