### PR TITLE
Manual.md: require package names to be lowercase

### PR DESCRIPTION
**Pull request by Piraty**
@void-linux/pkg-committers

### CODE REVIEW

**Comment by the-maldridge** [comment]
I am strongly opposed to this.  This is an arbitrary change with no defined benefit and no justification.  There are no known issues with the current system, and as a general rule I will not support a change for the sake of change.

**Comment by q66** [comment]
I disagree; if anything is arbitrary, it's the current convention, and it just makes package searches confusing and introduces a relatively small minority of packages that have mixed case names while vast majority have lowercase names

not to mention that the current convention isn't even always respected, so it's not "for the sake of change", it's for the sake of consistency

the change is also easily implementable, so i see no reason not to go with it

**Comment by Chocimier** [comment]
Is there any plan to lowercase existing packages, or we will be stuck with old packages mostly upstream-case, new lower-case?

**Comment by q66** [comment]
there is a plan; we will rename the existing packages (in batches: one batch would be all packages that start with an uppercase letter, that's 200something packages and should be relatively small scale, probably less than e.g. a single chromium build :P, the rest is mostly perl packages which would be done with the next perl related rebuild, and then the remainder would be handled individually)

renaming would be done via `provides=` + `replaces=` combo for the old name + removal of the old package from the repos (this would be easy to do, since doing it in a batch means we could just clean the affected packages at once), which means no existing scripts or commands would be broken (there would be a single virtual provider of the old name, which means `xbps` can just pick it up) - the docs would then gradually be updated

**Comment by the-maldridge** [comment]
Lowercasing existing packages would involve a myriad of renames.  Given that XBPS already doesn't handle renames super well, I'm not inclined to do anything large that will risk repo state.  Similarly, I am still against this change on principle as the complaint of searches being harder could be fixed by something far simpler, like making the package search case insensitive.

**Comment by Duncaen** [comment]
Package search is already case insensitive, but xbps-install is not and there is no reason to make it case insensitive.

The main issue is inconsistency and no good reason to have mixed case package names.

**Comment by q66** [comment]
there is less than 300 packages that start with uppercase, and around 1000 total packages that have mixed case, most of them simple (formerly noarch) perl/python packages, this is really rather trivial

it's been discussed in `#xbps` yesterday, and we've come to the conclusion that this is feasible and unlikely to break

@Duncaen was also strongly opposed to making things case insensitive, and so am I, it's just a massive can of worms that's both more complex and uglier than the lowercasing approach

**Comment by Chocimier** [comment]
Replaces simply won't work for this use case.

**Comment by q66** [comment]
it will, when paired with `provides=` (@Duncaen has already confirmed this)

**Comment by leahneukirchen** [comment]
Please don't "rename" packages, but make XBPS normalize the name? Then fix all the templates.

**Comment by Chocimier** [comment]
@66: Package with provides + replaces doesn't install itself in place of manually installed package.

**Comment by Duncaen** [comment]
> @q66: Package with provides + replaces doesn't install itself in place of manually installed package.

Yes looks like it needs a two line patch to work correctly.

> Please don't "rename" packages, but make XBPS normalize the name? Then fix all the templates.

With "provides=" being the old name, its effectively normalized by going through the virtual package if necessary.

**Comment by Chocimier** [comment]
> needs a two line patch to work correctly.

Provides is now used as both "use this instead" and as "this is alternative provider of other non-virtual package", and proposed change will make second usage work incorrectly.

**Comment by Duncaen** [comment]
> Provides is now used as both "use this instead" and as "this is alternative provider of other non-virtual package", and proposed change will make second usage work incorrectly.

I don't really see how anything changed, the proposed change is making updates try virtual packages if a normal package wasn't found, like it already does for dependencies and direct installations.

**Comment by hippi777** [comment]
hi folks :) 

i think it can be a strong reason to bring the package names any nearer to other distros (ok, i saw other interesting stuffs elsewhere, and i dont know enough, but it was strange when i saw the mixed case here...), and i think if this doesnt introduce any collision, then it must be doable (!=done). my 1st (naive/uneducated ?) guess would be to look up both the current name and the name with lowercase if the former cant be found, but this makes a transition period, that i dont know how long it should be...

i can understand the thinking that says if it works then it doesnt need to be fixed, but i have no idea why it was introduced on the 1st place, so, out of curiosity, why? :D 

the greatest difference between all the distros out there is in their package managers and packages, bringing them any nearer to each other is a nice dream of mine, but void is the 1st distro i approached this closely, so i dunno how huge this dragon might be :D otherwise i saw the repology rules, so i have some idea :D also, a script that would install dependencies for various tasks to be done may need a nontrivial translator for package names between various distros, and while the basics will be mostly identical, i can think about nasty cases as well, so this is my other reason to vote on this change...

**Comment by CameronNemo** [comment]
```
diff --git a/Manual.md b/Manual.md
index 4af3a7b78d..9675e5a00f 100644
--- a/Manual.md
+++ b/Manual.md
@@ -255,6 +255,9 @@ Programs can be split into program packages and library packages. The program
 package should be named as described above. The library package should be
 prefixed with "lib" (see section `Libraries`)

+If miscellanious executables are put into a subpackage, name the subpackage
+`${sourcepkg}-tools`. Void does not accept packages with the `-utils` suffix.
+
 <a id="global_funcs"></a>
 ### Global functions

```

**Comment by Gottox** [comment]
I prefer allowing uppercase names. For me it makes templating easier, as I don't have to set up variables for package and upstream filenames for those packages.

Personally, I even would go into another direction and support the full utf8 set. This would allow to find bugs in the string handling of xbps.

Anyway, as I wasn't recently active in void, I won't take a vote in this discussion.

**Comment by Piraty** [comment]
Closing, as most seem opposed.

**Comment by q66** [comment]
not true, i don't see most being opposed

but xbps will need work first

**Comment by Chocimier** [comment]
Reopening. Closing issue won't stop this, but arguments can.

**Comment by ericonr** [comment]
I'm not  entirely sure, but lowercase package names can be more predictable and might help with accessibility as well...

**Comment by the-eater** [comment]
I personally don't really care how the packages are stored repo side, 

I do however get very annoyed by trying to install a package, xbps telling me it doesn't exist and then searching it only to find out it uses random capitals, it's inconsistent and annoying.

I have proposed this in IRC and I think it would align with @Gottox wishes partly as well. (since it would mean overhauling strings a bit)

I would rather have the package matching to be case-insensitive, I assume there's at least consensus that we shouldn't have e.g. `MyPackage`  and `mypackage` at the same time.

allowing package matching to be case-insensitive allows usage pattern to be the same as if all was lowercase, and might ease migration if we plan to go full lowercase anyhow

**Pull request closed without merging**
