### PR TITLE
Vulkan-Headers, Vulkan-Tools, Vulkan-ValidationLayers, vulkan-loader: update to 1.3.224.1.

### PR DESCRIPTION
**Pull request by czkz**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86-64)

### CODE REVIEW

**Comment by JamiKettunen** [comment]
Would you mind bumping these to `v1.3.235`? I'm especially interested in getting [`vkcube` cross-built for all non-x86 arches](https://github.com/KhronosGroup/Vulkan-Tools/commit/e8234991418c5b0536e342bc849d5f8ed9eb6d6f) :)

**Comment by tibequadorian** [comment]
@JamiKettunen Void only packages sdk releases

**Comment by JamiKettunen** [comment]
> @JamiKettunen Void only packages sdk releases

Oh, I don't know what the difference is with any of these, the tagging convention upstream looks convoluted.

**Comment by classabbyamp** [comment]
#40747

**Pull request closed without merging**
