### PR TITLE
flowblade: update to 2.12.0.2, force X11

### PR DESCRIPTION
**Pull request by Luciogi**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-GLIBC)

## Fixes
Crash on wayland

### CODE REVIEW

**Comment by zlice** [comment]
Do you want to reopen this? If not I can.

Was kind of waiting for it for ffmpeg6...

**Comment by Luciogi** [comment]
i can reopen

**Comment by zlice** [comment]
thanks

**Comment by Luciogi** [comment]
> thanks

I cant see reopen button

**Pull request closed without merging**
