### PR TITLE
python-prompt_toolkit2: rename

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by maxice8** [comment]
@CameronNemo please test

**Comment by CameronNemo** [comment]
Works well, thank you!

**Comment by xaltsc** [comment]
You might also want to revert changes I made in #10682 .

**Comment by CameronNemo** [comment]
@xaltsc this is enough to not introduce conflicts from what I can tell. This builds on your changes.

**Comment by xaltsc** [comment]
You might also want to revert changes I made in #10682 .

**Pull request merged**
