### PR TITLE
gnome-passbook: update to 0.8.

### PR DESCRIPTION
**Pull request by uw2021**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
I don't think this has correct dependencies: https://gitlab.gnome.org/gnumdk/passbook

Also, please fix xlint.

I'd maybe consider dropping it... It hasn't seen any action ever since it was introduced.

**Comment by uw2021** [comment]
> I don't think this has correct dependencies: https://gitlab.gnome.org/gnumdk/passbook
> 
> Also, please fix xlint.
> 
> I'd maybe consider dropping it... It hasn't seen any action ever since it was introduced.
> 
> EDIT: do the update, we can consider dropping once it's an actual burden.

Agreed, I was in two minds over whether or not to update it, but it's a tiny package anyway. 

As for xlint, is it as simple as adding a space between the c and the "? I tried that and it solved xlint for me, but I wasn't 100% sure if that was the right method, since other templates didn't have the space. Cheers.

**Comment by ericonr** [comment]
Huh, the only lint I saw was for the description starting with "A "

**Comment by uw2021** [comment]
> Huh, the only lint I saw was for the description starting with "A "

Taking out the 'A' from short_desc made xlint pass:

`short_desc="Password manager for GNOME"`

**Pull request merged**
