### PR TITLE
orc: updated homepage due to link rot

### PR DESCRIPTION
**Pull request by joedavis**
Had some free time, so decided to do the quick fix for #10988 myself. I've set the new homepage to https://cgit.freedesktop.org/gstreamer/orc as I can't find anything better.

### CODE REVIEW

**Comment by maxice8** [comment]
please bump the revision= number by 1 so the package is rebuilt and users can see the new homepage.

also added

```
closes #10992 
```

to the body of the commit message.

**Comment by joedavis** [comment]
Apologies for the multiple force pushes, been a while since I've done any devel. I've added `closes #10988` (the number of the issue) to the commit message (not `#10992`, which is the number of this PR)

**Comment by maxice8** [comment]
Put the closes comment 2 lines below the title

**Comment by maxice8** [comment]
Use the present tense when writing commits

`<pkgname>: update dead homepage`

**Pull request merged**
