### PR TITLE
font-sarasa-gothic: update to 0.34.3

### PR DESCRIPTION
**Pull request by FollieHiyuki**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by Chocimier** [comment]
> this PR works for me

How, when it does not build?

**Comment by FollieHiyuki** [comment]
It builds on my system :) I can screenshot for you to proof it

screenshot

**Comment by FollieHiyuki** [comment]
I don't know what caused the permission hook to fail in this case

**Comment by sgn** [comment]
> => ERROR: font-sarasa-gothic-0.34.3_1: file /usr/share/fonts/TTF/sarasa-bolditalic.ttc has write permission for other users
> => ERROR: font-sarasa-gothic-0.34.3_1: post-install_14-fix-permissions: 'find "$PKGDESTDIR" -type f -perm -0002' exited with 1

**Comment by FollieHiyuki** [comment]
Yes I can read that. The problem is I can't reproduce on my machine. The file gets the right permission 0644 here and the build succeeds.

**Comment by Chocimier** [comment]
Ok, understand. It builds locally as well.

    bsdtar tvf hostdir/sources/font-sarasa-gothic-0.34.3/sarasa-gothic-ttc-0.34.3.7z
    -rw-rw-rw-  0 0      0    79371148 wrz 19 15:35 sarasa-bold.ttc
    -rw-rw-rw-  0 0      0    80673476 wrz 19 15:36 sarasa-bolditalic.ttc

Not sure if this is broken archive, or general problem with bsdtar processing 7z archives, that goes wrong under root.

**Comment by Chocimier** [comment]
It looks like archive created under non-unix, thus not defining permissions. Should be fine to merge.

**Pull request merged**
