### PR TITLE
New package: evopop-icon-theme-0.11

### PR DESCRIPTION
**Pull request by Bleznudd**
Adding solus' [EvoPop icon theme](https://github.com/solus-cold-storage/evopop-icon-theme/tree/master/EvoPop)

### CODE REVIEW

**Comment by sgn** [comment]
https://github.com/void-linux/void-packages/blob/master/Manual.md#quality_requirements

**Comment by Bleznudd** [comment]
I'm sorry, I'm a new void user, but why are you linking me the quality requirements?
As far as I can see, in that document is written:

> To be included in the Void repository, software must meet **at least one** of the following requirements. [...]
> 
> 1.  System: The software should be installed system-wide, not per-user.
> 2.  Compiled: The software needs to be compiled before being used, even if it is software that is not needed by the whole system.
> 3. Required: Another package either within the repository or pending inclusion requires the package.

As an icon pack this package obviously doesn't need to be compiled nor is required by any other package, but surly it's installed system-wide (the EvoPop folder goes under /usr/share/icons)

So what's wrong with this pull request and how is this package different from other that have been merged (such as [papirus](https://github.com/void-linux/void-packages/blob/master/srcpkgs/papirus-icon-theme/template)) ?

**Comment by sgn** [comment]
> As an icon pack this package obviously doesn't need to be compiled nor is required by any other package, but surly it's installed system-wide (the EvoPop folder goes under /usr/share/icons)

Theme can be installed per user basic,
Have you tried extracting them into `~/.local/share/themes`,
More information is provided by: https://wiki.archlinux.org/index.php/GTK#Themes


> So what's wrong with this pull request

It doesn't satisfy any requirements.

> and how is this package different from other that have been merged (such as [papirus](https://github.com/void-linux/void-packages/blob/master/srcpkgs/papirus-icon-theme/template)) ?

It's merged by accident, what's done is done.

**Comment by Bleznudd** [comment]
Theme can be installed per user basic

Yes they can, but they can also be installed system wide as in this case, so why not merging this type of packages?

Anyway, just to be sure that I understand correctly (and maybe be helpful to others), does this mean that void repo won't accept **any** new icon-pack nor gtk theme in the future?

**Comment by sgn** [comment]
On 2020-06-29 07:19:08-0700, Bleznudd <notifications@github.com> wrote:
> > Theme can be installed per user basic
> 
> Yes they can, but they can also be installed system wide as in this
> case, so why not merging this type of packages?

Everything can be installed system-wide ;)
My personal script can be installed system-wide, too :)

Some packages can be installed per user basic.

> Anyway, just to be sure that I understand correctly (and maybe be
> helpful to others), does this mean that void repo won't accept
> **any** new icon-pack nor gtk theme in the future?

Correct!

Exception: System-wide packages requires specific themes to be
functional correctly.


-- 
Danh

**Comment by Bleznudd** [comment]
> >  Anyway, just to be sure that I understand correctly (and maybe be
> >  helpful to others), does this mean that void repo won't accept
> >  **any** new icon-pack nor gtk theme in the future?
> 
> Correct!

I'm sad to hear that, but thanks for the clarification.

May I suggest to modify the [manual](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality_requirements) then?

"_System: The software should be installed system-wide, not per-user_" sounds unclear; something like "_System: The software should be installed system-wide **and must not be** per-user installable_" may be better imho

**Pull request closed without merging**
