### PR TITLE
texlive 2021

### PR DESCRIPTION
**Pull request by ericonr**
- texlive: update to 20210325.
- texlive-basic: update to 2021.0.
- texlive-bibtexextra: update to 2021.58697.
- texlive-core: update to 2021.58710.
- texlive-fontsextra: update to 2021.58704.
- texlive-formatsextra: update to 2021.57972.
- texlive-games: update to 2021.56833.
- texlive-humanities: update to 2021.58589.
- texlive-langchinese: update to 2021.58583.
- texlive-langcyrillic: update to 2021.58426.
- texlive-langextra: update to 2021.58019.
- texlive-langgreek: update to 2021.57684.
- texlive-langjapanese: update to 2021.58632.
- texlive-langkorean: update to 2021.58468.
- texlive-latexextra: update to 2020.57067.
- texlive-music: update to 2021.58331.
- texlive-pictures: update to 2021.58558.
- texlive-pstricks: update to 2021.58293.
- texlive-publishers: update to 2021.58683.
- texlive-science: update to 2021.58667.
- texlive-most: update to 2021.0.
- texlive-minimal: update to 2021.0.
- texlive-lang: update to 2021.0.
- texlive-full: update to 2021.0.

#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by ericonr** [comment]
Interested parties @fosslinux @ahesford @abenson @tornaria

**Comment by dkwo** [comment]
Could you check that `libsynctex` works with the update?
Today I was getting again
```
$ zathura --synctex-forward 1:1:main.tex main.pdf
! SyncTeX Error : No file?
```
on `Void 5.15.5_1 x86_64-musl GenuineIntel uptodate rrnFFFFFF`.

**Comment by dkwo** [comment]
Nevermind, there's no `synctex` file in my folder, so this is unrelated.

**Comment by fosslinux** [comment]
I haven't tested *every* package, but those I regularly use work fine.

**Pull request merged**
