### PR TITLE
php: update to 8.0.0 & xdebug: update to 3.0.0

### PR DESCRIPTION
**Pull request by the-eater**
I am unsure

### CODE REVIEW

**Comment by ericonr** [comment]
Has cross failures:

```
checking for shm_open in -lrt... yes
checking for shm_open in -lroot... no
checking for __shm_open in -lroot... no
checking for mmap() using shm_open() shared memory support... no
configure: error: No supported shared memory caching support was found when configuring opcache. Check config.log for any errors or missing dependencies.
```

Might be something worth adding to autoconfigure cache, or just as an option here.

**Comment by the-eater** [comment]
I don't have any ARM machines at hand, but I can just Assume™ they are available? <the autoconf does a hard fail on cross compiling>

**Comment by ericonr** [comment]
> I don't have any ARM machines at hand, but I can just Assume™ they are available? 

We cross build to arm, so you can attempt the same procedure that will happen in the builders by doing `./xbps-src -a aarch64 php`.

**Comment by ericonr** [comment]
Sorry, you meant the functions, right?

Then yes, you can just assume! :)

**Comment by the-eater** [comment]
yes the functions! thanks!

**Comment by ericonr** [comment]
Oops, sorry for the noise. We are updating to latest 7.x in #27767, so you'll have to rebase in a bit :) 

Did you manage to figure out the cross stuff? Otherwise I can try my hand.

**Comment by the-eater** [comment]
hehe, I honestly haven't had time to look at it so you might take over if you want :)

**Comment by ericonr** [comment]
Are you currently using php 8? I'd at most fix cross, I don't use it nor know how to test adequately

**Comment by the-eater** [comment]
yeah I am currently using it (not in production, but i can confirm it works as intended) the cross was the only issue

**Comment by jonagoldman** [comment]
Some options were renamed or removed in 8.0:

```
configure: WARNING: unrecognized options: --with-freetype-dir, --with-icu-dir, --with-jpeg-dir, --with-libzip, --with-pcre-regex, --with-png-dir
```

**Pull request closed without merging**
