### PR TITLE
New package: fnm-1.35.1

### PR DESCRIPTION
**Pull request by heppu**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture: x86_64
- I built this PR locally for these architectures:
  - x86_64-musl
  - aarch64
  - aarch64-musl
  - armv6hf-musl
  - armv6hf
  - armv6l-musl
  - armv6l
  - armv7hf-musl
  - armv7hf
  - armv7l-musl
  - armv7l

### CODE REVIEW

**Comment by heppu** [comment]
@classabbyamp Fixed the linting errors.

**Comment by classabbyamp** [comment]
please don't ping me on PRs I'm not already involved in

**Comment by heppu** [comment]
Oh, I'm sorry. I thought it was you who allowed the workflow to be executed.

**Comment by Vinfall** [comment]
Are you still working on this? fnm before 1.36.0 does not really work on musl although it does build. And it's no point to build for musl other than x86_64 as unofficial node mirror only has x64-musl tarballs.

**Comment by Vinfall** [comment]
You may find this patch useful:
```diff
--- template	2024-07-03 04:20:29.000000000 +0000
+++ template	2024-07-03 04:19:26.000000000 +0000
@@ -1,18 +1,19 @@
 # Template file for 'fnm'
 pkgname=fnm
-version=1.35.1
+version=1.37.1
 revision=1
+archs="x86_64-musl ~*-musl"
 build_style=cargo
 build_helper=qemu
 hostmakedepends="pkg-config"
 makedepends="libzstd-devel"
 short_desc="Fast and simple Node.js version manager, built in Rust"
 maintainer="Henri Koski <henri.t.koski@gmail.com>"
-license="GPL-3.0-or-later"
+license="GPL-3.0-only"
 homepage="https://github.com/Schniz/fnm"
 changelog="https://raw.githubusercontent.com/Schniz/fnm/master/CHANGELOG.md"
 distfiles="https://github.com/Schniz/fnm/archive/refs/tags/v${version}.tar.gz"
-checksum=df0f010f20e6072a8a52365f195cc94c35ebaf486cc285948e10eabf768d17ba
+checksum=56a170304ab281439a71e541c4db878848c3a891078ae3c2dcc84017cd0306b4
 
 post_install() {
 	for shell in bash fish zsh; do
```

I'm not very sure whether node.js has builds for all those `archs`. You may also need to expose a few environment variables as I said in https://github.com/Schniz/fnm/issues/694#issuecomment-2049004644 or patch them during build time for musl (but I have no idea if xbps can do that, i.e. run patch only on musl builds).

**Pull request closed without merging**
