### PR TITLE
common/xbps-src: source all files under a directory named after the build-style.

### PR DESCRIPTION
**Pull request by maxice8**
This allows a build-style to have various .sh under it, one important
use-case is sharing environment variables that can be set under multiple
build-styles.

As an example both cargo and meson build-style need to set various rust
flags, see #7322.

@Cogitri

### CODE REVIEW

**Comment by Vaelatern** [comment]
Interesting idea, I wonder if all possible entry points were covered, I'll grep for that.

**Comment by Cogitri** [comment]
As explained before it's handy for stuff like #7322 where meson-rust needs the same env as cargo

**Comment by Gottox** [comment]
Nice idea!

I think this could be useful. We should introduce a build-style environment variable that points to `$XBPS_COMMONDIR/build-style` to ease linking and including other files. What do you think?

**Comment by maxice8** [comment]
superseeded by build_helper

**Pull request closed without merging**
