### PR TITLE
Update gap to 4.12.1

### PR DESCRIPTION
**Pull request by fingolfin**
#### Testing the changes
- I tested the changes in this PR: **NO**

CC @tornaria

### CODE REVIEW

**Comment by tornaria** [comment]
@fingolfin Thanks: I have an update to 4.12.1 as part of #39876, with make check passing. Should be merged soon.

**Comment by fingolfin** [comment]
@tornaria that PR seems to use 4.12.0, not 4.12.1?

**Comment by tornaria** [comment]
> @tornaria that PR seems to use 4.12.0, not 4.12.1?

It seems I didn't push that but I have 4.12.1 working. I'll soon push an update to #39876 with this.

**Comment by tornaria** [comment]
@fingolfin: you can see my update from gap 4.11.1 to 4.12.1 here https://github.com/void-linux/void-packages/pull/39876/files#diff-d5e8ac4c14235608656fe702205ba0e985de306ecc14756391643152370bfbd3

Differences from yours:
 - I had to add `autodoc` and `radiroot` pkgs that are needed for some installed packages.
 - I added a check for missing packages (meaning `./xbps-src check` will try to run gap and `LoadPackage(pkg)` for each package and complain on failure).
 - I added a patch to the testsuite so it passes without trying to hit the network (which fails since neither `curl` nor `wget` nor the `io` package are installed), so check passes.

Now I'm having trouble with sagemath  b/c of the same thing with download. There are 8 doctests failed in sage (--long) testsuite. All of them because a warning is printed (No download method is available, etc). However, the actual answers are always correct, so the download is not really needed (???).

I can think two ways forward
a. configure atlasrep to not download anything by default (how would I do that?)
b. have a data package installed in the system that contains all the stuff atlasrep might want to download. I think an issue is that the data packages are not versioned so it would be hard to keep up to date, etc.

Do you know why atlasrep is trying to download something that is not necessary to give the correct answer? What would be missing without this feature? Note that the feature won't work in a system install of gap anyway since the package wants to place the files in a system directory (there's no way we can ship a 1777 directory in `/usr` as the installer wants -- this feature can only work if the downloaded files are placed in the user homedir, preferably in `$XDG_CACHE_HOME` or similar).

**Comment by ahesford** [comment]
@tornaria Please pull any relevant differences into your sage PR.

**Pull request closed without merging**
