### PR TITLE
ffmpeg: update to 4.0.1.

### PR DESCRIPTION
**Pull request by jnbr**
Local builds completed without error for i686, x86_64 and x86_64-musl so far.
I did some basic testing on x86_64.

### CODE REVIEW

**Comment by jnbr** [comment]
The remaining local builds for aarch64, armv7l and armv6l on both, glibc and musl, completed without error.

**Comment by pullmoll** [comment]
This PR looks good to me. I'd like to see some review from @void-linux/pkg-committers though.

**Comment by jnbr** [comment]
If someone want's to test this without building everything, packages are available here: https://jnbr.me/repo/ffmpeg/

**Comment by pullmoll** [comment]
FYI building this PR locally and will, if noone objects, push after a successful build.

**Comment by pullmoll** [comment]
`transcode` is missing from the list and it doesn't build out of the box, i.e. needs a patch.

**Comment by pullmoll** [comment]
Also `xpra` is missing a revbump for `ffmpeg-4.0.1`. It seems to build without problems.

**Comment by copyleftie** [comment]
Shouldn't `mpv` be updated to `0.28.2`?
Anyway I'm building it locally and seeing if it at least works on x86_64 glibc.

**Comment by jnbr** [comment]
I added the bump for xpra and a patch from archlinux for transcode.

**Comment by pullmoll** [comment]
Thanks. It seems some more missing packages are `libfreerdp`, `deepin-movie-reborn` and `dolphin-emu`. They are blocking the `*-stagedata` from being resolved here. Other than that the PR seems to build ok.

**Comment by pullmoll** [comment]
Ok, revbumping them seems sufficient to get my index updated again. *phew* :)

**Comment by jnbr** [comment]
deepin-movie-reborn fails for aarch64, checking the remaining ones currently. Also scrcpy and mgba were missing.

**Comment by Johnnynator** [comment]
Mkay. That is the same issue that arm* has. I didn't have a clue what was going wrong when packageing deepin-movie-reborn and still don't have any.

**Comment by pullmoll** [comment]
`mpd` needs an update, as it was revbumped for `libnfs.so.12`.

**Comment by Johnnynator** [comment]
Mkay. That is the same issue that arm* has. I didn't have a clue what was going wrong when packageing deepin-movie-reborn and still don't have any.

**Comment by jnbr** [comment]
The ffmpegthumbnailer rebuild changed the symbol table, before it was:
```
/usr/aarch64-linux-gnu/usr/bin/objdump -TC /usr/aarch64-linux-gnu/usr/lib/libffmpegthumbnailer.so|grep setSeekTime
000000000000a7b4 g    DF .text	0000000000000008  Base        ffmpegthumbnailer::VideoThumbnailer::setSeekTime(std::string const&)
```
and the new one looks like this:
```
/usr/aarch64-linux-gnu/usr/bin/objdump -TC /usr/aarch64-linux-gnu/usr/lib/libffmpegthumbnailer.so.4|grep setSeekTime
000000000000a298 g    DF .text	0000000000000008  Base        ffmpegthumbnailer::VideoThumbnailer::setSeekTime(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
```
Maybe that's a problem.

**Comment by pullmoll** [comment]
For `deepin-movie-reborn` perhaps the `-D_GLIBCXX_USE_CXX11_ABI=0` is the culprit.

**Comment by jnbr** [comment]
I rebased and bumped mpd

**Comment by Johnnynator** [comment]
@pullmoll to add this flag to fix another issue. I will revisit it once this PR is merged. (Or maybe earlier, at least it is a not critical issue)

**Comment by pullmoll** [comment]
@Johnnynator worked around it by not setting it for `aarch64*`, so at least aarch64 won't keep the `*-stagedata` forever.

**Comment by Johnnynator** [comment]
Ok. I forgot that it would cause a lot of staging on aarch64.

**Comment by pullmoll** [comment]
@chneukirchen `aarch64*` needs a host arch (x86_64) build of at least qt5 please.

**Comment by pullmoll** [comment]
Oops.. That revbump for handbrake was not necessary. I was misled by the missing "ffmpeg-4.0.1" name in the commit message ;-P

**Comment by Gottox** [comment]
@pullmoll just wait till x64_64 finishes, we restart the builder on aarch64 afterwards.

**Comment by Gottox** [comment]
Cleanup is in progress.

**Comment by pullmoll** [comment]
For `kodi-rpi` the patch is rather long. Here's [what I have so far](https://gist.github.com/pullmoll/9f0b77456c8921cceb2f65d40899ac4c)
I have no time to finish it now - need :beers:

**Comment by jnbr** [comment]
@pullmoll I added the missing bits for kodi-rpi: https://gist.github.com/jnbr/5206bde551ed259f29ae76c65154c3b7

**Comment by pullmoll** [comment]
Thank you @jnbr - I think that will fix arm* at least :)

**Pull request closed without merging**
