### PR TITLE
limine: update to 4.20230428.0.

### PR DESCRIPTION
**Pull request by mintsuki**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by biopsin** [comment]
While testing I noticed this ../share/liminie/limine.sys (206K) is smaller then previous version (232K) and would not boot. Does it require to run limine-deploy on every update too?

**Comment by mintsuki** [comment]
@biopsin that's correct. I assume the reason why it's smaller has to do with the fact that Void recently updated the LLVM toolchain to version 15.

**Comment by classabbyamp** [comment]
> Does it require to run limine-deploy on every update too?

> that's correct.

it would probably be good to have a post-install script or something. [grub has a kernel post-install hook](https://github.com/void-linux/void-packages/blob/master/srcpkgs/grub/files/kernel.d/grub.post), when does limine's configuration need updating? on limine update, kernel update, or both?

**Comment by biopsin** [comment]
>  does limine's configuration need updating?

Yes limine.cfg need kernel version bump, but this might be tricky as the configuration is custom and differs, therefore should be left for the user to adjust, same as with the syslinux package.

**Comment by mintsuki** [comment]
@classabbyamp as discussed on Discord, I'd prefer to keep this PR as is as it is a simple version bump, and worry about those things separately.

**Pull request merged**
