### PR TITLE
New package: fvwm3-1.0.0

### PR DESCRIPTION
**Pull request by abenson**

### CODE REVIEW

**Comment by 7185** [comment]
Works great but could you please add `libXft-devel libXpm-devel librsvg-devel readline-devel` in makedepends?

**Comment by abenson** [comment]
`libXft-devel` is already there, but what to do the rest add?

**Comment by 7185** [comment]
> `libXft-devel` is already there, but what about Xcursor or Xft?

Right now there is only `libXt` (intrinsics). Xft is needed for xft font support, Xpm and Svg for additional icons format, readline for a better FvwmConsole. I don't use Xcursor but it can be useful as well.

More info for optional dependencies : https://github.com/fvwmorg/fvwm3/blob/master/dev-docs/INSTALL.md#manually
Basically they should be the same as fvwm except for Xinerama (removed support in fvwm3).

**Comment by 7185** [comment]
Version 1.0.1 has been released

**Comment by leahneukirchen** [comment]
ping, if you got no time I can finish this up

**Comment by abenson** [comment]
Yesterday I was trying to fix cross, was going to backport fixes to fvwm2. No luck

**Comment by leahneukirchen** [comment]
Yeah the configure script is hairy, I don't see a quick workaround for cross.

**Pull request merged**
