### PR TITLE
Updated Godot to 3.4.5

### PR DESCRIPTION
**Pull request by Relected**
Updating the Godot Game engine to the latest version from Aug 2

#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by classabbyamp** [comment]
you're gonna need to update the checksum for the template, which you can do easily with `xgensum` from `xtools`

also, how did you test this if you committed from the github web ui?

**Comment by Relected** [comment]
> also, how did you test this if you committed from the github web ui?

i tested the new version and it worked fine, doesn't that count? or what else should test? sorry for not kknowing that this is the first time i ever made a PR to a repository.

**Comment by classabbyamp** [comment]
you'll want to test the build using xbps-src, i.e.:

1. make the changes to the template
2. build it with `./xbps-src pkg <pkgname>`
3. install it and test the functionality with `xi <pkgname>` (xi is also from `xtools`)

**Comment by Relected** [comment]
@classabbyamp well this might take a while, it takes hours to compile the thing soo...

**Comment by classabbyamp** [comment]
how many cores does your computer have? you can do `echo XBPS_MAKEJOBS=8 >> etc/conf` (replace 8 with some number) to do parallel compilation

**Comment by Relected** [comment]
@classabbyamp ok so it finished compiling and installing and it kind of works, basically it opens and loads the project, but these show up in the logs:

ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ERROR: Condition "status < 0" is true. Returned: ERR_CANT_OPEN
   at: init_device (drivers/alsa/audio_driver_alsa.cpp:89)
WARNING: All audio drivers failed, falling back to the dummy driver.
     at: initialize (servers/audio_server.cpp:222)

**Comment by Relected** [comment]
@classabbyamp nvm i was able to compile it (took long enough), now i dont know how to edit or overwrite this pull request to update the package

also it shows these errors when i run godot from the version i compiled (i mean it still opens and it loads the project fine but these seem concerning):

```
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ERROR: Condition "status < 0" is true. Returned: ERR_CANT_OPEN
   at: init_device (drivers/alsa/audio_driver_alsa.cpp:89)
WARNING: All audio drivers failed, falling back to the dummy driver.
     at: initialize (servers/audio_server.cpp:222)
```
     
these errors do not appear when i run the linux binary from the official site, do you have any info on why that happens?

**Comment by classabbyamp** [comment]
hm i compiled and ran it myself and I don't get that error, but I'm using pipewire. are you using alsa? maybe there's an issue in your sound setup.

to update this PR, you should be able to
```
git commit --amend
git push --force
```
from this branch

**Comment by Relected** [comment]
> hm i compiled and ran it myself and I don't get that error, but I'm using pipewire. are you using alsa? maybe there's an issue in your sound setup.
> 

i also use pipewire and this issue never happened to me either, it only happens when i run the version of the engine that i compiled myself

> to update this PR, you should be able to
> 
> ```
> git commit --amend
> git push --force
> ```
> 
> from this branch

weird, i also ran those commands and it throws this error at me:
```
remote: Permission to void-linux/void-packages.git denied to Relected.
fatal: unable to access 'https://github.com/void-linux/void-packages/': The requested URL returned error: 403
```

**Comment by classabbyamp** [comment]
ah you need to clone from your fork:
```
git clone https://github.com/Relected/void-packages
git checkout patch-1
```
then add your changes, amend the commit, and force push

**Comment by Relected** [comment]
so i was able to successfully make the changes to my own fork and update the template, the problem is that for some reason it also picked up an entire update for chromium somehow which is something i didnt want to happen, but it did for some reason...

idk man imma try again but lets hope i dont do something stupid this time

**Comment by Infinitybeond1** [comment]
> now i dont know how to edit or overwrite this pull request to update the package

As long as you still have a fork of this repo, if you commit to that repo while having an open pull request, then the changes will sync

**Comment by Relected** [comment]
@Infinitybeond1 i figured it out, took long enough

**Comment by Relected** [comment]
shit

**Comment by abenson** [comment]
Next time just [squash](https://www.git-tower.com/learn/git/faq/git-squash) the commits and force push to the branch.

**Pull request closed without merging**
