### PR TITLE
audit: update to 3.0

### PR DESCRIPTION
**Pull request by paper42**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

ping @CameronNemo

### CODE REVIEW

**Comment by ericonr** [comment]
@CameronNemo

**Comment by ericonr** [comment]
3.0.1 is out

**Comment by paper42** [comment]
Is there really 3.0.1? from their website:

> The latest stable release is 3.0, released December 16, 2020.

and the latest tag on github is also 3.0

**Comment by ericonr** [comment]
I saw it in https://raw.githubusercontent.com/linux-audit/audit-userspace/master/ChangeLog , but maybe that's the development version.

**Comment by paper42** [comment]
it seems to be

**Comment by ericonr** [comment]
Any idea what the failing test on musl is?

**Comment by ericonr** [comment]
And 3.0.1 has definitely been released now :)

**Comment by paper42** [comment]
```
$ lib/test/lookup_test                                                        
Testing i386_table...
Testing ppc_table...
Testing s390_table...
Testing s390x_table...
Testing x86_64_table...
Testing actiontab...
Testing errtab...
Testing fieldtab...
Unexpected match `A1'
```
the test failing is on [line 281](https://github.com/linux-audit/audit-userspace/blob/master/lib/test/lookup_test.c#L281) which calls TEST_S2I which contains this part:

```c
/* Blindly assuming this will not generate a    \
   meaningful identifier. */                    \
gen_id(buf);                                    \
if (S2I(buf) != (ERR_VALUE)) {                  \
        fprintf(stderr,                         \
                "Unexpected match `%s'\n",      \
                buf);                           \
        abort();                                \
}                                               \
```
ERR_VALUE = -1 and S2I(buf) = 201, so it seems to me like it actually generated a valid identifier, but I am a bit lost.

**Comment by ericonr** [comment]
Having fixed that, there's still a failure here which I don't understand, but it also happens in previous versions, so not holding back for it:

```
make  auparse_test auparselol_test lookup_test \
  auparse_test.py
make[4]: Entering directory '/builddir/audit-3.0.1/auparse/test'
cc -DHAVE_CONFIG_H -I. -I../..  -I../../auparse -I../../lib   -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -MT auparse_test.o -MD -MP -MF .deps/auparse_test.Tpo -c -o auparse_test.o auparse_test.c
mv -f .deps/auparse_test.Tpo .deps/auparse_test.Po
/bin/sh ../../libtool  --tag=CC   --mode=link cc  -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -static -Wl,-z,relro -Wl,-z,now -Wl,--as-needed     -o auparse_test auparse_test.o ../../auparse/libauparse.la ../../lib/libaudit.la ../../common/libaucommon.la
libtool: link: cc -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,--as-needed -o auparse_test auparse_test.o  ../../auparse/.libs/libauparse.a /builddir/audit-3.0.1/lib/.libs/libaudit.a ../../lib/.libs/libaudit.a -lcap-ng ../../common/.libs/libaucommon.a
cc -DHAVE_CONFIG_H -I. -I../..  -I../../auparse -I../../lib   -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -MT auparselol_test.o -MD -MP -MF .deps/auparselol_test.Tpo -c -o auparselol_test.o auparselol_test.c
mv -f .deps/auparselol_test.Tpo .deps/auparselol_test.Po
/bin/sh ../../libtool  --tag=CC   --mode=link cc  -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -static -Wl,-z,relro -Wl,-z,now -Wl,--as-needed     -o auparselol_test auparselol_test.o ../../auparse/libauparse.la ../../lib/libaudit.la ../../common/libaucommon.la
libtool: link: cc -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,--as-needed -o auparselol_test auparselol_test.o  ../../auparse/.libs/libauparse.a /builddir/audit-3.0.1/lib/.libs/libaudit.a ../../lib/.libs/libaudit.a -lcap-ng ../../common/.libs/libaucommon.a
cc -DHAVE_CONFIG_H -I. -I../..  -I../../auparse -I../../lib   -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -MT lookup_test.o -MD -MP -MF .deps/lookup_test.Tpo -c -o lookup_test.o lookup_test.c
mv -f .deps/lookup_test.Tpo .deps/lookup_test.Po
/bin/sh ../../libtool  --tag=CC   --mode=link cc  -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe     -Wl,-z,relro -Wl,-z,now -Wl,--as-needed     -o lookup_test lookup_test.o ../../auparse/libauparse.la ../../lib/libaudit.la ../../common/libaucommon.la
libtool: link: cc -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,--as-needed -o .libs/lookup_test lookup_test.o  ../../auparse/.libs/libauparse.so /builddir/audit-3.0.1/lib/.libs/libaudit.so ../../lib/.libs/libaudit.so -lcap-ng ../../common/.libs/libaucommon.a
make[4]: Nothing to be done for 'auparse_test.py'.
make[4]: Leaving directory '/builddir/audit-3.0.1/auparse/test'
make  check-local
make[4]: Entering directory '/builddir/audit-3.0.1/auparse/test'
test "../.." = "../.." || \
                cp ../../auparse/test/test*.log .
LC_ALL=C \
./auparse_test > auparse_test.cur
Config file /etc/audit/auditd.conf doesn't exist, skipping
make[4]: *** [Makefile:708: check-local] Error 1
make[4]: Leaving directory '/builddir/audit-3.0.1/auparse/test'
make[3]: *** [Makefile:579: check-am] Error 2
make[3]: Leaving directory '/builddir/audit-3.0.1/auparse/test'
make[2]: *** [Makefile:2038: check-recursive] Error 1
make[2]: Leaving directory '/builddir/audit-3.0.1/auparse'
make[1]: *** [Makefile:2190: check] Error 2
make[1]: Leaving directory '/builddir/audit-3.0.1/auparse'
make: *** [Makefile:465: check-recursive] Error 1
=> ERROR: audit-3.0.1_1: do_check: '${make_cmd} ${make_check_args} ${make_check_target}' exited with 2
=> ERROR:   in do_check() at common/build-style/gnu-configure.sh:33
```

**Pull request closed without merging**
