### PR TITLE
python-jsonschema: update to 3.0.2

### PR DESCRIPTION
**Pull request by fosslinux**

### CODE REVIEW

**Comment by Duncaen** [comment]
This broken in multiple ways, it has missing runtime dependencies and other packages are not compatible with it.

**Comment by Duncaen** [comment]
Also the sed in `pre_build` has no effect, not sure what it exactly did, but seems like setup.cfg is defining some things that were patched out.

**Comment by fosslinux** [comment]
I did not have missing runtime dependencies when I updated it. I should be doing my development on a clean slate, shouldn't I :grimacing:

**Comment by fosslinux** [comment]
I'll redo the pull request when I fix that up. My apologies!!!

**Comment by bobertlo** [comment]
I got this far on this dependency, which fixed anki at least, but docker-compose refuses to run with any 3.x version, so I think this is stuck unless there's a good reason to update it (and create multiple versions)
```
pkgname=python-pyrsistent
version=0.15.4
revision=1
#archs=noarch
wrksrc="pyrsistent-${version}"
build_style=python-module
pycompile_module="pyrsistent"
hostmakedepends="python-setuptools python3-setuptools"
makedepends="python-devel python3-devel"
checkdepends="python-hypothesis python-pytest python3-hypothesis python3-pytest"
depends="python-six"
short_desc="Persistent/Immutable/Functional data structures for Python"
maintainer="Robert Lowry <bobertlo@gmail.com>"
license="MIT"
homepage="https://github.com/tobgu/pyrsistent"
distfiles="https://github.com/tobgu/pyrsistent/archive/v${version}.tar.gz"
checksum=664f3ebc6630c3109d457f29e1e8c090c07ec5c7d5fc80d9f7d115f0ec67fc93

pkg_install() {
        vlicense LICENCE.mit
}

python3-pyrsistent_package() {
        archs=noarch
        pycompile_module="pyrsistent"
        depends="python3-six"
        short_desc="${short_desc/Python2/Python3}"
        pkg_install() {
                vlicense LICENCE.mit
                vmove "usr/lib/python3*"
        }
}
```

**Comment by fosslinux** [comment]
Thank you for the template @bobertlo. 

> I got this far on this dependency, which fixed anki at least, but docker-compose refuses to run with any 3.x version, so I think this is stuck unless there's a good reason to update it (and create multiple versions)

I'm not completely sure what you mean here; https://github.com/void-linux/void-packages/blob/master/srcpkgs/docker-compose/template seems like to me it works with python3. Also, python-jsonschema is python2 and 3. https://github.com/docker/compose/issues/2097 says that docker-compose supports python3. I'll take another stab at this soon.

**Pull request merged**
