### PR TITLE
New package: waypoint-0.1.2

### PR DESCRIPTION
**Pull request by nilium**

### CODE REVIEW

**Comment by nilium** [comment]
Looks like this is having trouble with ARM when hitting cgo. Still looking at it.

**Comment by smorimoto** [comment]
How about now?

**Comment by nilium** [comment]
The ARM build problems were due to the embedded copy of the waypoint entrypoint. I've not had as much time to look into it, but as of 0.1.2 it assumed you would target x86-64 and only provided that, so I may override that and provide the same architecture as the program when embedding the entrypoint instead of doing what Hashicorp is currently doing (since it's kind of a hack as-is). You can refer to this explanation from Mitchell on their forum for more information on the entrypoint: <https://discuss.hashicorp.com/t/waypoint-entrypoint-why-is-the-embedded-entrypoint-always-linux-amd64/16112>

**Comment by nilium** [comment]
Closing this for now. Not convinced yet that it's worth packaging.

**Comment by smorimoto** [comment]
​In this case, the deployment environment is limited to linux/amd64, but the executable binary for the waypoint itself should not. ​Well, I don't think most people will use it at this point, so it doesn't make much sense to package it, but I don't think it's a problem to package it without extra hacks.

**Comment by nilium** [comment]
Well, the deployment environment isn't limited in practice, so the entrypoint limitation is due to a workaround right now. I'd rather wait for it to get further along than package something that I now know I don't have a use for right now.

**Comment by smorimoto** [comment]
​Yeah, I know. ​I agree with you.

**Comment by smorimoto** [comment]
​Oh, we seem to have this:

https://github.com/void-linux/void-packages/blob/0baf47ac2fad9ca82a4bdc918e7976fa9f5824d9/common/environment/build-style/go.sh#L17-L29

So this might be enough for us:

```sh
if [ -z "$GOARM" ]; then
  make bin GOARCH="$GOARCH"
else
  make bin GOARCH="$GOARCH" GOARM="$GOARM"
fi
```

https://github.com/hashicorp/waypoint/blob/ee9443811c1ac724c24b4017dba1b97f6f1018d3/Makefile#L14

**Pull request closed without merging**
