### PR TITLE
grub: update to 2.12.

### PR DESCRIPTION
**Pull request by dataCobra**
#### Testing the changes
- I tested the changes in this PR: **BRIEFLY**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86_64-musl
  - i686

### CODE REVIEW

**Comment by dataCobra** [comment]
When installing the update and only do a update-grub. Grub doesn't boot it seems.

I had the problem on my ThinkPad. After reinstalling grub with the corresponding command, everything worked again as expected.

**Comment by classabbyamp** [comment]
> is it enough to create an update message and inform the users about what to do?

If we can do it in a way that does not require manual intervention, prefer that.

**Comment by dataCobra** [comment]
I've tested a bit more and couldn't reproduce my `grub doesn't boot` after update problem.

I need to check a bit more and encourage others to help me if possible.



> > is it enough to create an update message and inform the users about what to do?
> 
> If we can do it in a way that does not require manual intervention, prefer that.

I checked a few more things and to this point couldn't find a way to not require manual intervention from the user when upgrading.

But if somebody has knowledge about that or has some information, I appreciate the help.

**Comment by classabbyamp** [comment]
> When installing the update and only do a update-grub. Grub doesn't boot.

what do you mean by "doesn't boot"? going to the uefi firmware setup interface?

**Comment by classabbyamp** [comment]
added patch for fwsetup

**Comment by classabbyamp** [comment]
added patch fixing grub-install on xfs, rebased

**Comment by classabbyamp** [comment]
tested on:
- x86_64-efi with ext4
- x86_64-efi with luks1 and xfs
- arm64-efi with ext4

**Pull request merged**
