### PR TITLE
MultiMC: remove package(was MultiMC: update to 0.6.14)

### PR DESCRIPTION
**Pull request by daerich**
#### Testing the changes
- I tested the changes in this PR: **YES**
Unfortunately upstream changed quite some things on how to reliably acquire this package - partly due to new licensing terms.
Also the way has been paved for installscripts geared towards "popular" distributions(Ubuntu/Fedora). They now only deploy a downloader to embed the package in the users home directory.
__Edit__: It can not be reliably built from source anymore as it is missing the `secrets` library.
~So meld the generic Linux binary with the Ubuntu one recreating the prior Void distribution of this package(Icons and .desktop are part of the Ubuntu package and can't be hosted elsewhere).
This all is necessary due to a certain company from Redmond, WA forcing Minecraft onto their infrastructure.~

### CODE REVIEW

**Comment by Duncaen** [comment]
If we can't build it from source then we don't ship it, this is already restricted because of the permissions issue. The value in building it from source is that someone can do it themselves and use it on not supported architectures/libcs.
If you are using the binaries, just use them directly.

**Comment by daerich** [comment]
Well then it would be appropriate to remove that package as it has no value being outdated with limited support for the current login infrastructure(only deprecated method fully supported). The only question remaining would be to add it to removed-packages this time...

**Comment by tibequadorian** [comment]
#34979 was merged

**Comment by tibequadorian** [comment]
Why did you close this PR? It was meant as a reminder to merge this.

**Review by classabbyamp — APPROVED** [review]

**Pull request merged**
