### PR TITLE
[ci skip] firefox: update to 90.0.

### PR DESCRIPTION
**Pull request by Duncaen**
#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (x86_64-glibc)
- [x] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [x] x86_64-musl
  - [x] aarch64-musl
  - [ ] armv7l
  - [ ] armv6l-musl

### CODE REVIEW

**Comment by ericonr** [comment]
Appears to be completely broken on Wayland with `MOZ_ENABLE_WAYLAND=1` in the environment (which most wayland users will have). I have tested on Wayfire, for now.

**Comment by ericonr** [comment]
On wayfire: it's upside down and doesn't render anything besides the bar.

On sway: isn't upside down, but doesn't increase to fill up the container space and only renders the bar.

On cage: appears to works perfectly when launched inside wayfire; when I tested outside I forgot to set the env var, so will have to redo the test.

**Comment by ericonr** [comment]
Fix from https://bbs.archlinux.org/viewtopic.php?id=267954, `gfx.webrender.compositor.force-enabled= false` in about:config, worked.

A lot of folks enabled this because WebRender was the new hotness; I wonder if an INSTALL.msg is in order?

**Comment by ericonr** [comment]
Version without gtk2 seems fine too :)

**Comment by ericonr** [comment]
Merged in https://github.com/void-linux/void-packages/commit/cd63bfa787eea2d4873f9973af8373d35185915f

**Comment by eoli3n** [comment]
@ericonr @Duncaen firefox-i18n does not work, I needed to install language manually.

**Pull request closed without merging**
