### PR TITLE
New package: shellcaster-1.1.0

### PR DESCRIPTION
**Pull request by kawaiiamber**
Addresses [this](https://github.com/void-linux/void-packages/issues/26475)

### CODE REVIEW

**Comment by kawaiiamber** [comment]
Ah... this appears to be a [dup](https://github.com/void-linux/void-packages/pull/24525). The old PR is quite a few versions behind, however.

**Comment by daniel-eys** [comment]
Unfortunately, the issues from #24525 and ncurses-rs are still not solved with this version.

**Comment by kawaiiamber** [comment]
I see. Should I close this PR if you plan on updating your template?

**Comment by daniel-eys** [comment]
I will update my pr as soon as there is a proper solution (like upstream switching away from the ncurses-rs dependency).

**Comment by kawaiiamber** [comment]
Understood, closing this PR.

**Pull request closed without merging**
