### PR TITLE
timeshift: fix compatibility with util-linux 2.37.1

### PR DESCRIPTION
**Pull request by jchook**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

----

Timeshift is virtually unusable due to a change in util-linux, see:

- https://github.com/teejee2008/timeshift/issues/425
- https://github.com/teejee2008/timeshift/issues/753
- https://github.com/teejee2008/timeshift/issues/755

This PR applies an [official patch](https://github.com/teejee2008/timeshift/commit/d437358ac3debf7625aefda4d0bd387a91b69df5) to make the package usable on Void until the next official release, presumably later [this year](https://github.com/teejee2008/timeshift/issues/648).

### CODE REVIEW

**Comment by ericonr** [comment]
The commit should be something like:

```
timeshift: fix compatibility with util-linux 2.37.1.

Timeshift will only start in "Live USB Mode".

Upstream issues:
https://github.com/teejee2008/timeshift/issues/425
https://github.com/teejee2008/timeshift/issues/753
https://github.com/teejee2008/timeshift/issues/755
```

And the commit needs to increase revision of the `timeshift` template, otherwise it won't be rebuilt and changes won't be picked up.

**Comment by jchook** [comment]
Thank you! I bumped the revision and added your suggested commit message (much better, thanks).

**Comment by paper42** [comment]
@jchook GitHub shows Ghost as the commit author, do you know why it is this way? Maybe you don't have the email used in the commit set in your GitHub settings?

**Comment by jchook** [comment]
@paper42 Yep that was the issue. Updated.

**Comment by ericonr** [comment]
Thanks!

**Pull request merged**
