### PR TITLE
LuaJIT: update to git v2.1 branch

### PR DESCRIPTION
**Pull request by CameronNemo**
CC: @q66

The LuaJIT maintainer has not published a new version in 5 years, but he
has steadily added commits to the "2.1" branch, linked below.

https://repo.or.cz/luajit-2.0.git/shortlog/refs/heads/v2.1

Projects like neovim build against this branch or master due to the lack
of a recent release.
Furthermore, distributions such as Arch Linux and Debian Sid are
building from a commit rather than a release.

https://github.com/archlinux/svntogit-community/commit/11473c3c786593b2438a865519d407c7a84ce0a1

https://salsa.debian.org/lua-team/luajit/-/commit/e06cbc6d2a61b253056214f5ed3f03ce661e31f9

The LuaJIT upstream maintainer has declined to cut a release, reasoning
"Releases are an antiquated concept".

https://github.com/LuaJIT/LuaJIT/issues/665#issuecomment-784452583

#### Testing the changes
- I tested the changes in this PR: **YES**, on x86_64 and aarch64

### CODE REVIEW

**Comment by q66** [comment]
i think that packages should be switched from luajit to regular lua where possible

for years luajit has been nothing but a poorly portable liability with a bus factor of 1, and we should do away with it where we can 

neovim can use standard lua, as can a lot of things that are currently built against luajit

**Comment by q66** [comment]
also I'm like 90% sure the ppc64le patch does not apply anymore as I don't see it updated

**Comment by CameronNemo** [comment]
>neovim can use standard lua

Maybe it can, but the devs don't seem to want to support such a setup:

>Neovim should not be built against PUC Lua, and certainly not Lua 5.4 (which is incompatible with Lua 5.1, which Neovim targets).

https://github.com/neovim/neovim/issues/18169

>also I'm like 90% sure the ppc64le patch does not apply anymore as I don't see it updated

Would you be willing to update it? I have no ppc(64)(le) hardware to test with.

**Comment by mhmdanas** [comment]
How about https://github.com/openresty/luajit2, which does have releases and is used by e.g. Homebrew as a replacement for upstream LuaJIT?

**Comment by gbrlsnchs** [comment]
> How about https://github.com/openresty/luajit2, which does have releases and is used by e.g. Homebrew as a replacement for upstream LuaJIT?

That would solve the "bus factor" issue, at least. :sweat_smile:

**Comment by Idesmi** [comment]
Alpine builds on OpenResty's tag release as well.

**Comment by kartikynwa** [comment]
> How about https://github.com/openresty/luajit2, which does have releases and is used by e.g. Homebrew as a replacement for upstream LuaJIT?

this is dope

**Comment by LinArcX** [comment]
I have void-linux for more than 3 years, but recently i'm thinking more to switch to another distro,(that let me do whatever i want without any stupid limitations).

The main reason is that i still don't understand why maintainers of void insist on release versions of applications.

In my opinion, there's no single direction between "no-bug" and "high-quality" software with having "releases".

Stop this annoying policy and let people be more free.

**Comment by Idesmi** [comment]
> I still don't understand why maintainers of void insist on release versions of applications.

I believe it's meant to relieve considerable burden from the project.

**Comment by q66** [comment]
I would be okay with taking the openresty fork by the way, though we would need to test if ppc32 is still broken there

**Comment by kartikynwa** [comment]
Any update on the discussion regarding this?

**Comment by CameronNemo** [comment]
I think the consensus is to switch to the openresty upstream.

**Comment by mitinarseny** [comment]
also related: https://github.com/neovim/neovim/issues/17562

**Pull request closed without merging**
