### PR TITLE
new package: pypy3.7

### PR DESCRIPTION
**Pull request by dkwo**
I've tested it a bit on `x86_64`.
It is mostly taken from #8861, let me know if there's still interest to merge it in Void.

### CODE REVIEW

**Comment by EliteTK** [comment]
The upstream binary would be used to cross compile (and it sounds like that's supported by passing `--platform` to the `rpython` script) for all target platforms. `pypy-bootstrap` (or whatever you want to call it) would only need to support x86_64 and i686 for it to then be possible to use it to cross compile for all architectures, right?

**Comment by ahesford** [comment]
All of these options looks have serious drawbacks. Using native, precompiled binaries to bootstrap another arch is bad because it forces us to cross compile those archs. In Void, cross compilation is an incidental implementation detail of architectures for which we can't afford or don't want to maintain build infrastructure. It should always be possible to natively build any of our archs if one is so inclined, but the precompiled pypy bootstrap breaks this.

Relying on dead cpython is also lousy. We want to get rid of the package, not force it closer to the root of the dependency tree.

If we are going to overlook this catch-22, I would prefer to avoid another cpython2 dependency. I would also like to avoid creating some new package that only exists to build pypy. The best way out, if possible, would be to fetch the prebuilt distribution for native builds as another distfile. Use the locally extracted copy to build the packaged version. For cross builds, this can go away and we just pull the native pypy into hostmakedepends.

**Comment by EliteTK** [comment]
Some distros take the self-referential approach of just making pypy depend on itself for every build. Where at some point in the past they had some bootstrap package which was either an upstream binary or a cpython2 build of pypy which was then used to kickstart the ouroboros in perpetuity. Would this be an option? (Apparently, alpine and maybe archlinux did this.)

Alternatively, it's possible to have the pypy package have cpython2 sources in the distfiles instead of the upstream pypy and build that to then have the pypy package first build cpython2 and then pypy. This would avoid having an official cpython2 package and I think this is certainly a lot more transparent than using the upstream pypy.

@dkwo are you still interested in getting this working? If not, I can try to pick up the effort.

**Comment by ahesford** [comment]
Self-referential cycles are not an option because it will break the dependency resolver and, even if it didn't, our policy requires that all packages in the repo be buildable without requiring specific pre-existing repo state. (This is an ideal, and some package changes can sometimes lead to violations of this policy, but we don't knowingly permit it.)

I can be persuaded that building a temporary cpython 2.7 in pre_build to bootstrap native pypy is reasonable option. That's not much different than how we (were, before py3.10) bootstrapping `python3` on cross builds.

Practically, because the python 2.7 package isn't going anywhere for awhile, maybe it suffices to know that we *can* build a cpython bootstrap in the template if we ever need to; just pulling the python package in hostmakedepends might be OK for now after all.

I'm not sure if using native pypy to bootstrap cross pypy is better than *always* using (and, in the future, potentially building) native cpython. Arguments on either side would be appreciated.

Of course, we can always hope that pypy solves the bootstrap problem before we have to...

**Comment by dkwo** [comment]
@EliteTK please, feel free to pick it up

**Comment by dkwo** [comment]
@EliteTK I'm closing this PR, but by any means feel free to pick it up.

**Pull request closed without merging**
