### PR TITLE
jitterentropy: update to 3.0.1.

### PR DESCRIPTION
**Pull request by UsernameRandomlyGenerated**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

@Piraty

### CODE REVIEW

**Comment by ericonr** [comment]
Superseded by https://github.com/void-linux/void-packages/commit/be36e2cdaff462e617e95b16626efe8aaab7b540

Can be repurposed to add the vlicense line to the template, though.

**Comment by ericonr** [comment]
@Piraty

**Comment by Piraty** [comment]
oh i didn't see this PR, my bad

**Comment by UsernameRandomlyGenerated** [comment]
@Piraty I've made some changes to license as it has gpl2 too

**Comment by Piraty** [comment]
it is bsd OR gpl2, and since Void doesn't comply to SPDX syntax yet (https://github.com/void-linux/void-packages/issues/11240), we keep it to BSD
> Copyright (C) 2017 - 2021, Stephan Mueller <smueller@chronox.de>
> 
> Redistribution and use in source and binary forms, with or without
> modification, are permitted provided that the following conditions
> are met:
> 1. Redistributions of source code must retain the above copyright
>    notice, and the entire permission notice in its entirety,
>    including the disclaimer of warranties.
> 2. Redistributions in binary form must reproduce the above copyright
>    notice, this list of conditions and the following disclaimer in the
>    documentation and/or other materials provided with the distribution.
> 3. The name of the author may not be used to endorse or promote
>    products derived from this software without specific prior
>    written permission.
> 
> ALTERNATIVELY, this product may be distributed under the terms of
> the GNU General Public License, in which case the provisions of the GPL2
> are required INSTEAD OF the above restrictions.  (This clause is
> necessary due to a potential bad interaction between the GPL and
> the restrictions contained in a BSD-style copyright.)
> 
> THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED
> WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
> OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, ALL OF
> WHICH ARE HEREBY DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE
> LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
> CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
> OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
> BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
> LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
> (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
> USE OF THIS SOFTWARE, EVEN IF NOT ADVISED OF THE POSSIBILITY OF SUCH
> DAMAGE.

**Pull request closed without merging**
