### PR TITLE
zimg: update to 3.0.1.

### PR DESCRIPTION
**Pull request by UsernameRandomlyGenerated**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
It seems to be trying to use neon unconditionally for armv7 ?

**Comment by UsernameRandomlyGenerated** [comment]
Yeah, there was an issue about that in upstream but it's closed with conclusion that neon is required.

**Comment by ericonr** [comment]
So they at least have to pass the necessary flags to enable Neon lol

**Comment by UsernameRandomlyGenerated** [comment]
https://github.com/sekrit-twc/zimg/issues/140

**Pull request closed without merging**
