### PR TITLE
Networkmanager 1.20.8

### PR DESCRIPTION
**Pull request by Gottox**
I opened this PR to prevent people from wasting time in updating this package.

NetworkManager removed support for their legacy API, which causes NetworkManager-vpnc and NetworkManager-openvpn to break. We should delay this update until upstream has fixed this issue.

### CODE REVIEW

**Comment by Gottox** [comment]
NetworkManager-vpnc still fails, everything else seems good to go.

**Comment by Gottox** [comment]
I think I will cherry pick the removal of libnm-glib. It may that especially networkmanager-dmenu will be affected by this change.

**Comment by codingHahn** [comment]
FYI: NetworkManager 1.22.x breaks ipv4 dhcp leases. We are currently having some cases of this at 36c3. 1.20.8 is confirmed working.

**Comment by Gottox** [comment]
Can you try to change the dhcp client in NetworkManager.conf?

**Comment by Gottox** [comment]
Moving to 1.22.x

**Pull request closed without merging**
