### PR TITLE
smplayer: Add mpv as runtime dependency

### LINKED ISSUE #40456: Smplayer Does Not Depend on MPV
### Is this a new report?

Yes

### System Info

Void 5.19.17_1 x86_64 GenuineIntel uptodate FFFFFF

### Package(s) Affected

smplayer-22.7.0_1, mpv-0.34.1_2

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

_No response_

### Expected behaviour

The package installs `mpv`, a runtime dependency in order to actually play videos with the application.

### Actual behaviour

`mpv` is not installed and attempting to play a video results in an error.

### Steps to reproduce

1. Install `smplayer`
2. Launch `smplayer`
3. Open a video file with the application

### PR DESCRIPTION
**Pull request by TrueTechie**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

Closes #40456

### CODE REVIEW

**Comment by TrueTechie** [comment]
Closes #40456

**Comment by classabbyamp** [comment]
> Closes #40456

put this in the PR description and/or the commit body so it automatically closes it

**Comment by sgn** [comment]
smplayer can use mplayer as backend, mpv is not a hard dependencies.

**Comment by TrueTechie** [comment]
> smplayer can use mplayer as backend, mpv is not a hard dependencies.

So should `mplayer` be the dependency or what? 

Unlike other packages that are broken  without "optional" dependencies such as `steam`, there is no documentation in the package about this.

**Comment by paper42** [comment]
If you run smplayer and don't have mpv or mplayer installed, do you get a descriptive error message?

**Comment by TrueTechie** [comment]
> If you run smplayer and don't have mpv or mplayer installed, do you get a descriptive error message?
I guess that is up to interpretation: 

```
MPlayer/mpv failed to start. Please check the MPlayer/mpv path in preferences.
```
This is a little cryptic as it tells the user it is improperly configured, possibly implying the need for a standalone version of `mpv` or `mplayer`, rather than missing a package.

**Comment by lxlml** [comment]
I personally prefer smplayer as it is now because I need to complile MPV with vapoursynth support and I am not sure how it would interact if smplayer comes with a hard mpv dependecy.

Besides if one were to search up smplayer, it specifically states it's a frontend of MPV or Mplayer so there should be no confusion. I think letting people choose what they want is the better choice.

**Comment by classabbyamp** [comment]
if it is not a dependency caused by requiring a shared library, it is possible to use [ignorepkg](https://man.voidlinux.org/xbps.d#ignorepkg=pkgname) to not install it

**Comment by sgn** [comment]
I prefer to patch `smplayer` to provide better error message. I dont use smplayer, so I don't care much, anyway.

**Comment by paper42** [comment]
> I prefer to patch `smplayer` to provide better error message. I dont use smplayer, so I don't care much, anyway.

I second that, but the patch should be upstream, we shouldn't carry functional patches like this one in the distribution.

**Comment by sgn** [comment]
Even if we want to put one optional dependency to `smplayer`, it should be `mplayer` not `mpv`.
Quoting from their homepage:

> SMPlayer is a graphical user interface (GUI) for the award-winning [**MPlayer**](http://www.mplayerhq.hu/design7/info.html), which is capable of playing almost all known video and audio formats. But apart from providing access for the most common and useful options of **MPlayer**, SMPlayer adds other interesting features like the possibility to play Youtube videos or download subtitles.

**Comment by ahesford** [comment]
I disagree that the error message, "MPlayer/mpv failed to start", is particularly cryptic. "Please check the path" is a recommendation about how to solve the problem, and a user who tries to inspect the path should be able to determine that neither of these alternatives is available.

Although I would be very happy to see a decent implementation of optional dependencies for XBPS, we currently have no facility for this. Our policy is not to force hard dependencies on software that works with several viable alternatives and, as sgn noted, the natural choice would be `mplayer` anyway because that seems to be the first-class backend for SMplayer. Of course, forcing a user to `ignorepkg` something to swap backends is at least as lousy an experience (and less obviously resolved) than the current situation.

Any team member disagreeing with me can reopen this PR, but it seems like a WONTFIX for now.

**Pull request closed without merging**
