### PR TITLE
Signal-Desktop: update to 5.34

### PR DESCRIPTION
**Pull request by akierig**
#### Testing the changes
I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture: **x86_64**

### CODE REVIEW

**Comment by tibequadorian** [comment]
From the Manual.md:

>When you make changes to your pull request, please *do not close and reopen your pull request*. Instead, just [forcibly git push](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#review), overwriting any old commits. Closing and opening your pull requests repeatedly spams the Void maintainers.

**Comment by akierig** [comment]
> From CONTRIBUTING.md:
> 
> > When you make changes to your pull request, please _do not close and reopen your pull request_. Instead, just [forcibly git push](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#review), overwriting any old commits. Closing and opening your pull requests repeatedly spams the Void maintainers.

that's on me, sorry. I hate using GH and `git` generally, I find them incredibly frustrating. So when I get tripped up by a typo in my formatting, it was my default reaction. sorry again.

**Comment by tibequadorian** [comment]
No problem :) 5.34 is out

**Comment by akierig** [comment]
would the preference be to close this one and open one for 5.34 or just rename everything and push a commit for 5.34 to the same branch?

**Comment by tibequadorian** [comment]
Just rename this one.

**Comment by akierig** [comment]
yikes, didn't mean to close it, sorry.

**Comment by paper42** [comment]
Please rebase on top of (not merge) master and squash the commits into one.

**Pull request merged**
