### PR TITLE
Ilmbase/openexr: update to 2.4.0

### PR DESCRIPTION
**Pull request by pullmoll**
Use build-helper qemu to run the target binaries generating header files.
I'm not sure whether all dependencies of libopenexr need to be revbumped even though there is no ABI change.

Supersedes #16355

### CODE REVIEW

**Comment by Johnnynator** [comment]
> I'm not sure whether all dependencies of libopenexr need to be revbumped even though there is no ABI change.

Yes, a revbump is required since the lib name changed and therefore the packages that need openexr link against not existing libs after that update..

**Comment by pullmoll** [comment]
Not yet ready for merging: openexr needs a patch for musl.

**Comment by pullmoll** [comment]
Not sure if the patch is ok for x86_64-musl. There is no field `magic` in the `_fpstate_64` for musl libc and I assumed that means there is no need to check for it being `0` but rather always `setMxcsr(kfp->mxscr, clearExceptions);`. This assumption may be wrong, though.

**Comment by pullmoll** [comment]
Built update and revbumped packages for x86_64
- [x] ilmbase
- [x] openexr
- [ ] blender
- [ ] calligra
- [ ] darktable
- [ ] devil
- [ ] embree
- [x] enblend-enfuse
- [ ] gimp
- [ ] gmic
- [x] hugin
- [x] kimageformats
- [x] kio-extras
- [ ] krita
- [x] libgdal
- [ ] luxmark
- [ ] luxrays
- [x] opencv
- [x] openimageio
- [ ] osg
- [ ] synfig
- [x] vigra

**Comment by pullmoll** [comment]
It seems that `OpenEXR/OpenEXR.pc.in` is missing the `${prefix}/` in the two lines
```
includedir=@includedir@
OpenEXR_includedir=@includedir@/OpenEXR
```
which is why `gimp` does not find the `/usr/include/OpenEXR/ImfInputFile.h`.

**Comment by pullmoll** [comment]
`synfig` fails to build because of `std::mutex` being undefined when including the `glibmm-2.4/glibmm/objectbase.h` file and trying to define `static std::mutex extra_object_base_data_mutex;`

The error reads like this:
```
In file included from /usr/include/glibmm-2.4/glibmm/wrap.h:22,
                 from /usr/include/glibmm-2.4/glibmm/containerhandle_shared.h:24,
                 from /usr/include/glibmm-2.4/glibmm/arrayhandle.h:21,
                 from /usr/include/glibmm-2.4/glibmm.h:92,
                 from importer.cpp:41:
/usr/include/glibmm-2.4/glibmm/objectbase.h:280:15: error: 'mutex' in namespace 'std' does not name a type
  280 |   static std::mutex extra_object_base_data_mutex;
      |               ^~~~~
/usr/include/glibmm-2.4/glibmm/objectbase.h:28:1: note: 'std::mutex' is defined in header '<mutex>'; did you
 forget to '#include <mutex>'?
   27 | #include <glibmm/debug.h>
  +++ |+#include <mutex>
   28 | #include <sigc++/trackable.h>
```

The `#include <mutex>` is in line 32 so perhaps this line has to be moved up like the compiler suggests.

**Comment by pullmoll** [comment]
Tried it and no, it doesn't make a difference if I move the `#include <mutex>` to after `#include <glibmm/debug.h>`. So as it seems `synfig` is broken and remains broken, independently of the `ilmbase` and `openexr` update.
What can we do? Remove `synfig` from the repository to not be stuck in staging?

**Comment by pullmoll** [comment]
Except for `synfig` this PR should be ready.

**Comment by pullmoll** [comment]
The packages `synfig` and `synfigstudio` need some more tweaking.
The build style changed to cmake and some file are no longer installed / available, such as `/usr/bin/synfig-config`. Out of the box the shared libraries have no SOVERSION and I tried to fix that by patching the `CMakeLists.txt` files.

The `synfig_modules.cfg` is currently installed in `/usr/etc` and currently I post_install a copy in `/etc`. Perhaps a `-DCMAKE_CONFIG_DIR=/etc` or similar would be cleaner?

And `synfigstudio` no longer installs any header files which is why I (for now) removed `synfigstudio-devel`. Do we really need it?

**Comment by Johnnynator** [comment]
1.3.11 is a unstable version.

**Comment by pullmoll** [comment]
Yes, but 1.2.2 won't build at all, with or without ilmbase/openexr update :P

**Comment by Johnnynator** [comment]
Add a revert for the EFL update f8738b43984cfd8d9df0ac90ef25a7c610775515 . That package should kept in sync with synfig.

**Comment by pullmoll** [comment]
@Johnnynator that did the trick. Now synfig builds again.

**Comment by newbluemoon** [comment]
@pullmoll is synfigstudio ok now, too, or is any attention required from my side? :)

**Comment by pullmoll** [comment]
@newbluemoon it all builds fine now. ETL-1.3.11 was the culprit and reverting it solved the issues. AFAICT this PR is ready to be merged.

**Pull request merged**
