### PR TITLE
protonvpn-cli: update to 2.2.6.

### PR DESCRIPTION
**Pull request by uw2021**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by FollieHiyuki** [comment]
Do we really need this update, since the client is blocked and doesn't work in some countries?
I skimmed through their issues a while ago, and they stated that the development had stopped in favor of a new official Linux client (now still in beta).

**Comment by uw2021** [comment]
> Do we really need this update, since the client is blocked and doesn't work in some countries?
> I skimmed through their issues a while ago, and they stated that the development had stopped in favor of a new official Linux client (now still in beta).

Might as well have it, the way I see it. It's a tiny package anyway. What's wrong with having the latest version of something in the repo?

It'd be a bit different if it was an update to GNOME 3.38.2 with 40 right around the corner, for example.

**Comment by ericonr** [comment]
They also still recommend the community version for headless servers: https://protonvpn.com/support/official-linux-client/

>  Please note that the new ProtonVPN app doesn’t currently support Split Tunneling and doesn’t run on headless servers. If you need these features, then the community Linux app remains available.

Anyway, I can't find the source for this new app, so that also sucks hard right out of the gate.

**Comment by ericonr** [comment]
On another note, to fix tests it might be enough to do `checkdepends="$depends"`

**Comment by uw2021** [comment]
> On another note, to fix tests it might be enough to do `checkdepends="$depends"` 

Thank you, I'll give that a try.

**Comment by uw2021** [comment]
> On another note, to fix tests it might be enough to do `checkdepends="$depends"`

Still not compiling successfully with the -Q flag unfortunately. Compiles, installs and works fine without it for me on x86_64-musl. Here's the error I receive:
 `=> ERROR: protonvpn-cli-2.2.6_1: do_check: 'python3 setup.py ${make_check_target} ${make_check_args}' exited with 1
=> ERROR:   in do_check() at common/build-style/python3-module.sh:39`

**Comment by ericonr** [comment]
You ommited the useful part of the output. It's what the command prints above that that matters.

**Pull request merged**
