### PR TITLE
barrier: version update to 2.4.0

### PR DESCRIPTION
**Pull request by jinithin**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by jinithin** [comment]
cc @Johnnynator

**Comment by Johnnynator** [comment]
Thx for updating and testing.

I made a quick change to your commit and also disabled `do_check` since they broke the configuration for running tests somewhere in their cmake (or cmake is the broken one :shrug: )

**Comment by jinithin** [comment]
great! didn't notice it when building locally, but i now see the pipeline failed :)

**Comment by jinithin** [comment]
seems to be related to this.
https://github.com/debauchee/barrier/issues/1086

**Comment by Johnnynator** [comment]
> great! didn't notice it when building locally, but i now see the pipeline failed :)

Checks aren't enabled by default in xbps-src. You can run them with `-Q` or setting `XBPS_CHECK_PKGS=yes` in `etc/conf`.

**Pull request merged**
