### PR TITLE
diffuse: update to 0.8.1

### PR DESCRIPTION
**Pull request by drichline**
#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by drichline** [comment]
Not sure what the `xlint` error means, should I set my git email to a real address?

**Comment by mhmdanas** [comment]
Yes, void-packages does not accept commits using Github noreply e-mail addresses.

**Comment by paper42** [comment]
please squash the commits and this should be good to go

**Comment by drichline** [comment]
> please squash the commits and this should be good to go

I messed up the commit name on the first try, should be good now. Thanks for the review!

**Pull request merged**
