### PR TITLE
New package: Xdialog

### PR DESCRIPTION
**Pull request by ThatGeekyWeeb**

### CODE REVIEW

**Comment by abenson** [comment]
Instead of grabbing arch's binary and extracting it, why not build it from source?

**Comment by q66** [comment]
we don't take repackaging of other people's binaries, especially when those binaries come from another distro that builds them from source

additionally, the archs field is wrong, and the commit structure is wrong

**Comment by ThatGeekyWeeb** [comment]
iI was grabbing arch's binary as it cant build, the mainstream tarball's `./configure` has broken syntax, and the archives for Xdialog no longer exists, so I'm only able to get a work version from a pre-compiled version

**Comment by ThatGeekyWeeb** [comment]
I'll see if I can create a patch

**Comment by q66** [comment]
both the homepage and the source archive (http://xdialog.free.fr/Xdialog-2.3.1.tar.bz2) seem up to me

if configure is broken, just generate it again

**Comment by ThatGeekyWeeb** [comment]
While I may have figured it out, I was meaning the archive for old versions, which the homepage states is
(http://membres.lycos.fr/godefroy/archives/) but this link is dead

**Comment by q66** [comment]
that said, there is nothing wrong with the configure script, as this template works just fine

```
# Template file for 'Xdialog'
pkgname=Xdialog
version=2.3.1
revision=8
build_style=gnu-configure
configure_args="--with-gtk2"
hostmakedepends="pkg-config gettext"
makedepends="gtk+-devel"
short_desc="Xorg Replacement for dialog"
maintainer="ThatGeekyWeeb <thatgeekyweeb@gmail.com>"
license="GPL-2.0-or-later"
homepage="http://Xdialog.free.fr"
distfiles="http://xdialog.free.fr/${pkgname}-${version}.tar.bz2"
checksum=1d446899697145fc36623d8afdd274066177da9383a6b619c18e8eb1b2ba589a
```

but also, since it needs gtk2, this will not be accepted, use `zenity`

**Comment by ThatGeekyWeeb** [comment]
it is possilbe to build with `./configure --prefix=/usr --without-gtk2 --with-gtk=no`
as I was making a template to do...

**Comment by q66** [comment]
There is no such thing, as far as i can tell it requires some version of gtk no matter what (1 or 2)

I'd advise against introducing dead software into the repo either way

**Comment by ThatGeekyWeeb** [comment]
None the less, I believe this template works
```
# Template file for 'Xdialog'
pkgname=Xdialog
version=2.3.1
revision=8
archs="x86_64 i686"
makedepends="gtk+ gtk+-devel libelf gtk+3-devel gtk+3"
depends="xorg gnome-themes-extra"
short_desc="Xorg Replacement for dialog"
maintainer="ThatGeekyWeeb <thatgeekyweeb@gmail.com>"
license="GPL-2.0-or-later"
homepage="http://Xdialog.free.fr"
distfiles="http://xdialog.free.fr/Xdialog-${version}.tar.bz2"
checksum="1d446899697145fc36623d8afdd274066177da9383a6b619c18e8eb1b2ba589a"
nostrip="true"
do_build() {
	./configure --prefix="${DESTDIR}" --without-gtk2 --with-gtk=no
	make
}
do_install() {
	make install_root=${DESTDIR} install
}
```
im currently testing it

**Comment by ThatGeekyWeeb** [comment]
This template works, up until `make`, im fixing that now
```bash
# Template file for 'Xdialog'
pkgname=Xdialog
version=2.3.1
revision=8
archs="x86_64 i686"
makedepends="gtk+ gtk+-devel libelf gtk+3-devel gtk+3 pkg-config"
depends="xorg gnome-themes-extra"
short_desc="Xorg Replacement for dialog"
maintainer="ThatGeekyWeeb <thatgeekyweeb@gmail.com>"
license="GPL-2.0-or-later"
homepage="http://Xdialog.free.fr"
distfiles="http://xdialog.free.fr/Xdialog-${version}.tar.bz2"
checksum="1d446899697145fc36623d8afdd274066177da9383a6b619c18e8eb1b2ba589a"
nostrip="true"
do_build() {
	./configure --prefix="${DESTDIR}" --without-gtk2 --with-gtk=no
	make
}
do_install() {
	make install_root=${DESTDIR} install
}
```

**Comment by q66** [comment]
that'll just build it for gtk2, since there is no such thing as `--without-gtk2` or `--with-gtk=no` and will get silently ignored

it will behave exactly the same as my template, except yours is broken

why do you think you know better? there is no non-gtk support in xdialog, there never was, there never will be, just read the output from configure

either way, this stays closed

**Comment by ThatGeekyWeeb** [comment]
Alright understood

all i know is that without `--without-gtk2` and `--with-gtk=no`
it errors out with
```
checking for gtk-config... no
checking for GTK - version >= 1.2.0... no
*** The gtk-config script installed by GTK could not be found
*** If GTK was installed in PREFIX, make sure PREFIX/bin is in
*** your path, or set the GTK_CONFIG environment variable to the
*** full path to gtk-config.
configure: error: Cannot find GTK: Is gtk-config in path?
```
where as
`./configure --prefix=/usr --without-gtk2 --with-gtk=no` does not error out and build fine

**Comment by q66** [comment]
that's because the configure script likely interprets `--with-gtk2` and `--without-gtk2` as the same thing since it lacks a false branch

```
compile_for="gtk1"
AC_ARG_WITH(gtk2,
  [  --with-gtk2             Compiles for GTK2],[
  compile_for="gtk2"
  CPPFLAGS="$CPPFLAGS -DUSE_GTK2"
  AC_MSG_RESULT(Compiling for GTK2)
  ])
if test "$compile_for" = "gtk2" ; then
  AM_PATH_GTK_2_0(2.2.0, ,
            AC_MSG_ERROR(Cannot find GTK2.))
else
  AM_PATH_GTK(1.2.0, ,
            AC_MSG_ERROR(Cannot find GTK: Is gtk-config in path?))
fi
```

**Pull request closed without merging**
