### PR TITLE
subtle: update homepage and license

### PR DESCRIPTION
**Pull request by UsernameRandomlyGenerated**
Homepage is down for at least one year, no access to source code.

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by Chocimier** [comment]
Current homepage is https://hg.unexist.dev/subtle/

**Comment by UsernameRandomlyGenerated** [comment]
Huh, I looked around the web and couldn't find anything. I guess I'll repurpose the commit to fix homepage and license then.

**Comment by ericonr** [comment]
Please move it to use a tarball https://hg.unexist.dev/subtle/rev/0.11 -> https://hg.unexist.dev/subtle/archive/0.11.tar.gz

And fix the update file.

@thypon for awareness

**Comment by thypon** [comment]
> Please move it to use a tarball https://hg.unexist.dev/subtle/rev/0.11 -> https://hg.unexist.dev/subtle/archive/0.11.tar.gz
> 
> 
> 
> And fix the update file.
> 
> 
> 
> @thypon for awareness

Please don't, subtle tarballs are a terrible idea. Every commit is stable enough, stable releases remain broken for longer time in rolling releases.

**Comment by Chocimier** [comment]
There are tarballs for serial commit number, like https://hg.unexist.dev/subtle/archive/3285.tar.gz

**Comment by UsernameRandomlyGenerated** [comment]
So should I go with the latest commit for the current PR or just fix build with the same commit that we had (3285) for now?

**Comment by thypon** [comment]
If subtle 3285 is compiling with latest ruby and libs just use that one. I will update the package to the latest version￼ hereafter

**Comment by ericonr** [comment]
Ping

**Comment by UsernameRandomlyGenerated** [comment]
Sorry, I won't have access to my home PC for the next week, I won't be able to check if it compiles so if anyone else wants to do it then feel free to create new PR, I will close this one for now.

**Comment by ericonr** [comment]
@UsernameRandomlyGenerated feel free to leave the PR open, if you still want to fix the package when you get back :)

I just pinged to know the status.

**Pull request closed without merging**
