### PR TITLE
volta: update to 0.9.3

### PR DESCRIPTION
**Pull request by atk**

### CODE REVIEW

**Comment by atk** [comment]
It is very strange that this was even tested for other architectures when the archs are explicitly limited to "x86_64 i686".

**Comment by ericonr** [comment]
The error failure isn't about trying to build the package

**Comment by atk** [comment]
I rather think it is:
```
=> ERROR: volta: this package cannot be built for x86_64-musl.
```
Similar lines can be found in all failed builds.

**Comment by ericonr** [comment]
That error isn't fatal, and is expected. What gives you the red X's is that the step that prints package contents couldn't fine the package.

**Comment by atk** [comment]
Yes, it was a network error. A simple force push fixed it.

**Comment by ericonr** [comment]
No, it wasn't a network error. It was fixed in #27157

**Pull request merged**
