### PR TITLE
[to test] New package: postgresql12

### PR DESCRIPTION
**Pull request by Chocimier**
Still some things to do, like fixing pg_config so postgis can be build for 12, adding postgresql-libs9.6 for rebuilding postgis, maybe behind option.

Edit: done.

### CODE REVIEW

**Comment by Chocimier** [comment]
The goal is to allow upgrade database from 9.6 to 12 with pg_upgrade. This requires to simultanoulsy install both versions. Shared library seems to be reusable.

Package is installed into /opt because pg_upgrade needs separate bindir for old and new version.
Modifying configure_args from build-style allows to consistenly set all installation paths.
System account and its parameters are same as in postgresql[9.6].
Manpages are suffixed with -12 and moved do default mandir.

Tested upgrading databases: one with tcl stored procedure and trivial postgis table and repology db using out-of-tree compiled extension.

**Comment by Anachron** [comment]
I'm using postgresql. Will it be moved again from opt after the migration? I'll try this PR on my VPS soon(ish).

**Comment by Chocimier** [comment]
I do not think juggling with paths is convenient. But maybe some net of /usr/libexec, /usr/share/psql/12, and so on can be used instead of /opt (since 13?).

**Comment by oranenj** [comment]
Just drive-by commenting here but FWIW, the upstream "PGDG" packages for eg. CentOS do separate packages for each major version and install files under /usr/pgsql-$MAJOR/ along with providing alternatives configuration that set up symlinks to the various binaries and manual pages under standard paths.

The alternatives probably can't be set up on a machine where postgresql 9.6 is also installed unless you provide an update that moves the files, but it might make sense to keep things in line with upstream for future versions.

**Comment by Chocimier** [comment]
Moved to /usr/lib/psql12, I think I'm done, will merge in few days.

@oranenj thanks for tip. Adding custom dirs to /usr is ugly though and no distro seems to do this.

**Pull request merged**
