### PR TITLE
yt-dlp: update to 2023.03.04.

### PR DESCRIPTION
**Pull request by eljamm**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)
- I built this PR locally for these architectures:
  - armv6l (cross)
  - armv6l-musl (cross)
  - x86_64-musl (cross)

Fixes throttling issues as described in https://github.com/yt-dlp/yt-dlp/issues/6369, https://github.com/yt-dlp/yt-dlp/issues/6400

### CODE REVIEW

**Comment by eljamm** [comment]
Added mpv patch to fix an issue with yt-dlp fragments, which this update causes, and another for related log messages.

**Comment by eljamm** [comment]
I think this is safe to merge, but can anyone else test it to confirm ?

**Comment by daniel-eys** [comment]
https://github.com/yt-dlp/yt-dlp/releases/tag/2023.03.04

**Comment by paper42** [comment]
CI is still failing, please look at the message and fix that

**Comment by eljamm** [comment]
@paper42 It's good now.

**Comment by paper42** [comment]
thanks!

**Pull request merged**
