### PR TITLE
Disallow variables in version back

### PR DESCRIPTION
**Pull request by Chocimier**
[ci-skip]

### CODE REVIEW

**Comment by ericonr** [comment]
Can you explain the motivation in the commit message? Since our tooling already supports such variables, I think it's important to justify why we are not using them anymore.

**Comment by Chocimier** [comment]
- xbps-checkvers substitute whole parameters ignoring #, %, :N
varieties, that's captious
- templates can be updated mechanically with scripts like xupdate

**Comment by sgn** [comment]
+1, with this disallowing, we can move `update-check` out of `xbps-src`, to `common/scripts`.

As of it's now, we need to source the template or do some tricky steps to get current version. If the PR is merged, we can simply `grep ^version=`

**Comment by Chocimier** [comment]
> move `update-check` out of `xbps-src`

Template still need to be sourced with `*_SITE` and R-cran build style available to compute `distfiles`, so not much gain here.

**Comment by Chocimier** [comment]
@void-linux/pkg-committers

**Comment by sgn** [comment]
> Template still need to be sourced with `*_SITE` and R-cran build style available to compute `distfiles`, so not much gain here.

That thing could be grep-ed and substituted. We should check only the first `distfiles`, no?

**Comment by Chocimier** [comment]
> We should check only the first distfiles, no?

Yes, ignoring second and subsequent distfiles would likely increase quality of update-check, after patching few templates that don't put main tarball first.

> That thing could be grep-ed and substituted.

There are also packages that use custom variables in path, e.g. `grass`, so this is a tradeoff between accuracy and speed(?), for which `version` restriction is not crucial, let's discuss separately.

**Pull request merged**
