### PR TITLE
Use linked gumbo-parser library for other packages

### PR DESCRIPTION
**Pull request by krkk**
#### General
Continuation of #29926

- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (x86_64-glibc)
- [ ] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [ ] aarch64-musl
  - [ ] armv7l
  - [ ] armv6l-musl

### CODE REVIEW

**Comment by krkk** [comment]
Build logs still seem to use the static library. Do I have to rebuild the gumbo-parser first?

**Comment by ericonr** [comment]
Oh damn! I got fooled by the CI results in the previous PR. `gumbo-parser` should be revbumped here, and so should `httpdirfs`, because the version in the builders used the old still static gumbo-parser.

**Comment by ericonr** [comment]
And please say "revbump to use dynamic gumbo-parser" in the commit messages :)

**Comment by ericonr** [comment]
There's a conflict somewhere in the branch, it won't allow me to merge from the web UI.

Looks good to me, I'd like to test building something using mupdf first tho.

**Comment by ericonr** [comment]
Seems to be an issue with GH, so don't worry.

**Comment by ericonr** [comment]
Had to merge manually because of the GH bug, thanks :D

**Pull request closed without merging**
