### PR TITLE
booster: update to 0.10

### PR DESCRIPTION
**Pull request by Barbaross93**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, x86-64

### CODE REVIEW

**Comment by dkwo** [comment]
testing now

**Comment by dkwo** [comment]
for me, this breaks lvm: `booster: exec: "lvm": executable file not found in $PATH` with
```
$ cat /etc/booster.yaml 
busybox: true
enable_lvm: true
modules: i915
modules_force_load: usbkbd
```

**Comment by dkwo** [comment]
https://github.com/anatol/booster/commit/7766b079c8fd004fee9d5eba19cb98cac568773b

**Comment by Barbaross93** [comment]
So how should we proceed? Wait for the next release? It seems like there's a bunch of fixes in this [release](https://github.com/anatol/booster/releases/tag/0.10); I'm not sure if these benefits outweigh the current issue.

**Comment by dkwo** [comment]
you may try to apply that commit, as well as https://github.com/anatol/booster/commit/bc988b0c48d337d7b3447ad8a634551ca5080178 as patches. they're already in master.

**Pull request closed without merging**
