### PR TITLE
ulogd: enable pcap output as a build option

### PR DESCRIPTION
**Pull request by ailiop-git**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ahesford** [comment]
What's the point of making this a build option?

**Comment by ailiop-git** [comment]
> What's the point of making this a build option?

There are a whole lot of optional output plugins apart from pcap (pgsql, mysql, sqlite, etc), and it doesn't always makes sense to support everything. It is conceivable that some people may not even want to have pcap as a dependency in their systems.

So irrespective of what the default build options may be, it's always good to give more flexibility to the build files so that people that care about having packages with minimal dependencies can do so.

**Comment by ericonr** [comment]
It doesn't seem to have created any additional dependency in the binary package, I assume because it dlopens things? In this case I agree with ahesford that a build option isn't truly necessary, but it doesn't hurt either. In any case, if you can confirm the new plugin is working, I'd feel comfortable merging as is.

```
=> ulogd-2.0.7_2: running pre-pkg hook: 04-generate-runtime-deps ...
   SONAME: libc.so.6 <-> glibc>=2.32_1
   SONAME: ld-linux-armhf.so.3 <-> glibc>=2.32_1
   SONAME: libnetfilter_log.so.1 <-> libnetfilter_log>=1.0.1_1
   SONAME: libnfnetlink.so.0 <-> libnfnetlink>=1.0.1_1
   SONAME: libmnl.so.0 <-> libmnl>=1.0.3_1
   SONAME: libnetfilter_acct.so.1 <-> libnetfilter_acct>=1.0.2_1
   SONAME: libnetfilter_conntrack.so.3 <-> libnetfilter_conntrack>=1.0.4_1
   SONAME: libdl.so.2 <-> glibc>=2.32_1
   SONAME: libpthread.so.0 <-> glibc>=2.32_1
```

**Comment by ailiop-git** [comment]
> It doesn't seem to have created any additional dependency in the binary package, I assume because it dlopens things?

Good catch. Yes, ulogd dlopens all the plugins, but that's not all. Wouldn't 04-generate-runtime-deps.sh scan all the shared objects anyway and pick up the deps?

I think the issue is that the particular plugin doesn't actually depend on libpcap at runtime:
```
$ ldd ulogd_output_PCAP.so                                                                                                                                                      
        linux-vdso.so.1 (0x00007ffd0b919000)                                                                                                                                                                                     
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f68d00bc000)                                                                                                                                                                     
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f68d028e000) 
```
despite the plugin being compiled with the intention of linking against libpcap:

`libtool: link: cc -shared -Wl,--as-needed  -fPIC -DPIC  .libs/ulogd_output_PCAP.o   -lpcap  -mtune=generic -O2 -g -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,--as-needed   -Wl,-soname -Wl,ulogd_output_PCAP.so -o .libs/ulogd_output_PCAP.so                                                                                                                                                                                                                             `

That's because from what is seems there's really no actual code dependency to libpcap (the ulog plugin output doesn't use any functionality), so it only needs pcap.h during compilation for some structs.

So we really don't need the build option (not for the pcap output plugin at least), so I'll push again making it unconditional.

I suppose also a patch is needed for upstream to remove linking against pcap since this is not really needed.

**Comment by ericonr** [comment]
Great, thanks :)

**Pull request merged**
