### PR TITLE
alacritty: remove cargo lefotver

### LINKED ISSUE #20668: alacritty: Remove /usr/.crates2.json
`alacritty-0.4.2_1` currently distributes a seemingly excess file `/usr/.crates2.json`. Feel free to close this if that's intentional.

### PR DESCRIPTION
**Pull request by m3tav3rse**
Fixes #20668

### CODE REVIEW

**Comment by jnbr** [comment]
You could just drop the full `do_install`. It's a leftover and covered by the cargo build-style now.

**Comment by m3tav3rse** [comment]
Thanks, I didn't know that.

**Comment by m3tav3rse** [comment]
Hm, when I drop this custom do_install cargo fails beacause tarball Cargo.toml is virtual manifest and do_install fails.

**Comment by xtraeme** [comment]
Use post_install

**Comment by m3tav3rse** [comment]
> Use post_install

Why would I use it?
I think possible solution is to change build_wrksrc to alacritty since default do_install uses --path . and we need --path alacritty here.

**Comment by xtraeme** [comment]
Hmm do whatever your think is OK buddy

**Comment by m3tav3rse** [comment]
I mean I don't know what would I put in post_install which isn't what is in do_install right now.

**Comment by jnbr** [comment]
you could use `make_install_args` to set the path, but this works as well

**Comment by m3tav3rse** [comment]
> you could use `make_install_args` to set the path, but this works as well

I tried this approach but cargo doesn't accept multiple `--path` arguments.
`error: The argument '--path <PATH>' was provided more than once, but cannot be used multiple times`

**Comment by travankor** [comment]
@m3tav3rse does this fix the make_install_args issue?

**Comment by m3tav3rse** [comment]
@travankor yes, it does.

**Comment by travankor** [comment]
Sorry, but what is deprecated? You're using --path alacritty? `cargo install --path .` was the broken option.

**Comment by m3tav3rse** [comment]
My bad, output I posted above is from `cargo install` without path argument.

**Pull request merged**
