### PR TITLE
cfm: update to 0.6.5.

### PR DESCRIPTION
**Pull request by willeccles**
I am the maintainer of this package. This update makes drawing smoother and adds some other useful features.

### CODE REVIEW

**Comment by willeccles** [comment]
How did I manage to get the 0.6.4 commit in there? Oh my.

**Comment by willeccles** [comment]
*What have I done*

**Comment by willeccles** [comment]
Oh. This is why you update your local copy before making commits, kids.

**Comment by willeccles** [comment]
CI seems to have been cancelled, not sure how to make it run again.

**Comment by ericonr** [comment]
Triggered it again.

**Pull request merged**
