### PR TITLE
wander: update to 0.14.1

### PR DESCRIPTION
**Pull request by robinovitch61**
#### Testing the changes
- I tested the changes in this PR: NO (see below)

### CODE REVIEW

**Comment by Clos3y** [comment]
Change the PR name to `wander: update to 0.14.1` (see [here](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#committing-your-changes)).

> * I tested the changes in this PR: **YES**|**briefly**|**NO**

Did you test the changes?

**Comment by robinovitch61** [comment]
> Change the PR name to `wander: update to 0.14.1` (see [here](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#committing-your-changes)).
> 
> > * I tested the changes in this PR: **YES**|**briefly**|**NO**
> 
> Did you test the changes?

Thanks. I see now that I'll have to update the checksum, but not sure how without being able to run `xgensum` (I maintain `wander` but don't run Void Linux). Also not sure I'll be able to test things without running Void Linux. I may not be the best person to make this version bump.

**Comment by Clos3y** [comment]
> Thanks. I see now that I'll have to update the checksum, but not sure how without being able to run `xgensum`

No worries. It's just the hash of your distfile,

    $ sha256sum v0.14.1.tar.gz

> Also not sure I'll be able to test things without running Void Linux. I may not be the best person to make this version bump.

There are [containers](https://github.com/orgs/void-linux/packages?repo_name=void-containers) for docker/podman that you can use to test, but don't worry. @Vaelatern is the maintainer for this package on Void.

**Comment by robinovitch61** [comment]
Great, thank you. I added the checksum (`sha256sum ~/Downloads/wander-0.14.1.tar.gz`) and have started the testing process in a container, but have to run. Will update this PR when testing is complete

**Comment by Vaelatern** [comment]
why in a container? just `xi` the package. Use `xbps-src` in your workflow, it does all the work and cleanup for you!

**Comment by robinovitch61** [comment]
Sounds good, thanks for testing and merging @Vaelatern

**Pull request closed without merging**
