### PR TITLE
New package: 7zip-22.01

### LINKED ISSUE #37875: Package request: 7zip
### Package name

7zip

### Package homepage

https://sourceforge.net/projects/sevenzip/files/7-Zip/

### Description

7-Zip is an open source file archiver, supports compression and decompression including 7z, xz bzip2, zip, gzip, tar out of the box.

### Does the requested package meet the quality requirements?

System, Compiled

### Is the requested package released?

Yes

### PR DESCRIPTION
**Pull request by r-ricci**
#### Testing the changes
- I tested the changes in this PR: **YES**

I don't think there's any reason to ship the full and the reduced versions in the same package, so I just compile the full one and create symlinks for compatibility.

#### TODO:

- [x] fix musl
- [ ] ~build with assembly where possible: on i686 and x86_64* it requires `asmc` or `jwasm`/`uasm` assemblers, none of which are packaged~
- [x] build a version with RAR support (nonfree repo)
- [x] use our compile and link flags
- [x] test packages that depend on `p7zip` at build/check time: SLADE, Z80Explorer, ark, cbp2make. (I just tested that they still build)
- test packages that depend on `p7zip` at run time:
    - [ ] lutris
    - [ ] multibootusb
    - [ ] playonlinux

closes #37875

### CODE REVIEW

**Comment by 0x5c** [comment]
Why does this delete p7zip, which is a different, active, project with different source code? If it has files that conflict it should be either
1. Marked as conflicting with p7zip
2. If the conflicting files are equivalent (like commands with the same interface and behaviour), it should be made an alternative
Both options are described in more details in Manual.md

**Comment by abenson** [comment]
For whatever reason, the patch does not apply when I try to build.

**Comment by 0x5c** [comment]
What are the portion written in assembly and what ISA extensions do they use?

**Comment by sgn** [comment]
@r-ricci ^

**Pull request merged**
