### PR TITLE
New package: shfm-0.4.2

### PR DESCRIPTION
**Pull request by motorto**
shfm is a file manager written in posix shell

webpage:https://github.com/dylanaraps/shfm

### CODE REVIEW

**Review by Piraty — CHANGES_REQUESTED** [review]
please squash your commits

**Comment by motorto** [comment]
Done @Piraty

**Comment by Piraty** [comment]
please make the commit message conform the standard (why keep the old titles??)

**Comment by motorto** [comment]
You are right I have done it now @Piraty

**Pull request merged**
