### PR TITLE
isl: update to 0.22.1

### PR DESCRIPTION
**Pull request by dkwo**
I edited the template, the corresponding soname and revbumped all involved.
It builds clean on my machine.
I'm not sure how to include vlicense() for MIT.
This is my first pull request, I hope I didn't mess anything up.

### CODE REVIEW

**Comment by pullmoll** [comment]
Won't merge for now, since isl-0.22.1 is breaking things and we need to first work out whether to keep both packages, `isl` and `isl15`, and/or update which of these two. Breaking our compilers is no good idea, so closing this PR for now.

**Comment by dkwo** [comment]
That makes sense.
Would it be possible to rename the older version from isl to isl12, and isl15 (currently at 0.19) to isl?
Or should I just submit a PR to update isl15?

**Comment by tornaria** [comment]
If compilers depend only on `isl15`, why isn't it possible to just update `isl` and `cloog` and leave `isl15` alone?

I mean: `cloog` has to be revbumped for the updated `isl`, but the (cross) compilers can be left alone, they shouldn't be affected at all by this change.

What am I missing?
@pullmoll @dkwo

**Comment by dkwo** [comment]
Btw, both `cloog` and `isl` seem to have moved on github.

**Comment by dkwo** [comment]
I think this is why I revbumped all that stuff:
```
=> isl-0.23_1: running pre-pkg hook: 99-pkglint ...
=> ERROR: isl-0.23_1: SONAME bump detected: libisl.so.10 -> libisl.so.23
=> ERROR: isl-0.23_1: please update common/shlibs with this line: "libisl.so.23 isl-0.23_1"
=> ERROR: isl-0.23_1: all reverse dependencies should also be revbumped to be rebuilt against libisl.so.23:
=> ERROR:    avr-gcc-9.3.0_1
=> ERROR:    cloog-0.18.4_2
=> ERROR:    cross-aarch64-linux-gnu-0.34_1
=> ERROR:    cross-aarch64-linux-musl-0.34_2
=> ERROR:    cross-arm-linux-gnueabi-0.34_1
=> ERROR:    cross-arm-linux-gnueabihf-0.34_1
=> ERROR:    cross-arm-linux-musleabi-0.34_2
=> ERROR:    cross-arm-linux-musleabihf-0.34_2
=> ERROR:    cross-arm-none-eabi-gcc-9.3.0_1
=> ERROR:    cross-armv7l-linux-gnueabihf-0.34_1
=> ERROR:    cross-armv7l-linux-musleabihf-0.34_2
=> ERROR:    cross-i686-linux-musl-0.34_2
=> ERROR:    cross-i686-pc-linux-gnu-0.34_1
=> ERROR:    cross-mips-linux-musl-0.34_1
=> ERROR:    cross-mips-linux-muslhf-0.34_1
=> ERROR:    cross-mipsel-linux-musl-0.34_1
=> ERROR:    cross-mipsel-linux-muslhf-0.34_1
=> ERROR:    cross-or1k-none-elf-gcc-10.2.0_1
=> ERROR:    cross-powerpc-linux-gnu-0.34_1
=> ERROR:    cross-powerpc-linux-musl-0.34_1
=> ERROR:    cross-powerpc64-linux-gnu-0.34_1
=> ERROR:    cross-powerpc64-linux-musl-0.34_2
=> ERROR:    cross-powerpc64le-linux-gnu-0.34_1
=> ERROR:    cross-powerpc64le-linux-musl-0.34_2
=> ERROR:    cross-powerpcle-linux-gnu-0.34_1
=> ERROR:    cross-powerpcle-linux-musl-0.34_1
=> ERROR:    cross-x86_64-linux-gnu-0.34_1
=> ERROR: isl-0.23_1: cannot continue with installation!
```
Is it fine to revbump just `cloog` instead?

**Comment by tornaria** [comment]
> Is it fine to revbump just `cloog` instead?

I think so. What 99-pkglint is doing is:
 - it realizes that the soname for the library in this package has changed from `libisl.so.10` to `libisl.so.23`, but you haven't updated `common/shlibs` to match.
 - because of that, it runs `xbps-query -Rs libisl.so -p shlib-requires` to find packages that shlib-require `libisl.so.10` and suggests that you revbump them, so they are recompiled against `libisl.so.23`.
 
However note:
```
$ xbps-query -Rs libisl.so -p shlib-requires
avr-gcc-9.3.0_1: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cloog-0.18.4_2: libisl.so.10 (https://alpha.de.repo.voidlinux.org/current)
cross-aarch64-linux-gnu-0.34_1: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-aarch64-linux-musl-0.34_2: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-arm-linux-gnueabi-0.34_1: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-arm-linux-gnueabihf-0.34_1: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-arm-linux-musleabi-0.34_2: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-arm-linux-musleabihf-0.34_2: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-arm-none-eabi-gcc-9.3.0_1: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-armv7l-linux-gnueabihf-0.34_1: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-armv7l-linux-musleabihf-0.34_2: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-i686-linux-musl-0.34_2: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-i686-pc-linux-gnu-0.34_1: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-mips-linux-musl-0.34_1: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-mips-linux-muslhf-0.34_1: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-mipsel-linux-musl-0.34_1: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-mipsel-linux-muslhf-0.34_1: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-or1k-none-elf-gcc-10.2.0_1: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-powerpc-linux-gnu-0.34_1: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-powerpc-linux-musl-0.34_1: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-powerpc64-linux-gnu-0.34_1: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-powerpc64-linux-musl-0.34_2: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-powerpc64le-linux-gnu-0.34_1: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-powerpc64le-linux-musl-0.34_2: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-powerpcle-linux-gnu-0.34_1: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-powerpcle-linux-musl-0.34_1: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
cross-x86_64-linux-musl-0.34_1: libisl.so.19 (https://alpha.de.repo.voidlinux.org/current)
```

You see here that only `cloog` shlib-requires `libisl.so.10`, the compilers require `libisl.so.19`.

If you want to be sure:
```
$ xbps-query -Rs libisl.so.10 -p shlib-requires
cloog-0.18.4_2: libisl.so.10 (https://alpha.de.repo.voidlinux.org/current)
```

I think if you just update the one line in `common/shlibs` for `isl` (keeping the line for `isl15` intact), the error should go away. You should also revbump cloog, but nothing else.

Could you try that?

**Pull request closed without merging**
