### PR TITLE
Update and de-orphan supercollider and sc3-plugins

### PR DESCRIPTION
**Pull request by weldongoree**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86_64-musl

### CODE REVIEW

**Comment by Bnyro** [comment]
de-orphan = adopt.

Please follow the contribution guideline's commit message requirements, e.g. `supercollidier: update to 3.13.0, adopt.`

**Comment by classabbyamp** [comment]
please don't adopt these packages:

> To ensure a template gets the care it needs, template adopters should be familiar with the package and have an established history of contributions to Void. Those who have contributed several updates, especially for the template in question, are good candidates for template maintainership.

https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#adopting-a-template

**Comment by classabbyamp** [comment]
there should be one commit for each template changed, and I think mixxx should be a separate pull request

**Comment by weldongoree** [comment]
Gah, sorry, having some git idiocy moments. sc3-plugins needs the same version sc3 so I was testing them together. One more try in just a minute.

**Pull request closed without merging**
