### PR TITLE
fix deluge

### PR DESCRIPTION
**Pull request by toadwastoast**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc
- I built this PR locally for these architectures:
  - aarch64-musl (cross)
  - armv6l (cross)
  
With the update to python 3.13 `deluge` became incompatible with a few things and it crashes on startup, so I had to update `python3-openssl` and `python3-zope.interface` in order for it to work again. 

It's also necessary to patch this [commit](https://github.com/deluge-torrent/deluge/commit/5d96cfc72f0bfa36d90afd2725aa2216b8073d66) into the package, since python 3.13 dropped support for cgi.

We could also just wait to see if upstream releases a new version of deluge compatible with python 3.13, but it could take a while.

### CODE REVIEW

**Comment by ahesford** [comment]
Please fetch the upstream patch as proper `git-format-patch` output, *e.g.*, by just grabbing

https://github.com/deluge-torrent/deluge/commit/5d96cfc72f0bfa36d90afd2725aa2216b8073d66.patch

This better shows the provenance and justification for changes.

**Comment by toadwastoast** [comment]
Thanks for the tip ahesford.

Also, does anyone know how I should deal with the flaky tests failing on `python3-openssl`?

**Comment by balejk** [comment]
The `zope.interface` update fixes `todoman` too. Without it it breaks like this:
```sh
$ todo new
Traceback (most recent call last):
  File "/usr/bin/todo", line 5, in <module>
    from todoman.cli import cli
  File "/usr/lib/python3.13/site-packages/todoman/cli.py", line 20, in <module>
    from todoman.interactive import TodoEditor
  File "/usr/lib/python3.13/site-packages/todoman/interactive.py", line 3, in <module>
    import urwid
  File "/usr/lib/python3.13/site-packages/urwid/__init__.py", line 76, in <module>
    from urwid.event_loop import AsyncioEventLoop, EventLoop, ExitMainLoop, MainLoop, SelectEventLoop
  File "/usr/lib/python3.13/site-packages/urwid/event_loop/__init__.py", line 13, in <module>
    from .twisted_loop import TwistedEventLoop
  File "/usr/lib/python3.13/site-packages/urwid/event_loop/twisted_loop.py", line 32, in <module>
    from twisted.internet.abstract import FileDescriptor
  File "/usr/lib/python3.13/site-packages/twisted/internet/abstract.py", line 13, in <module>
    from zope.interface import implementer
  File "/usr/lib/python3.13/site-packages/zope/interface/__init__.py", line 57, in <module>
    _wire()
    ~~~~~^^
  File "/usr/lib/python3.13/site-packages/zope/interface/interface.py", line 1104, in _wire
    from zope.interface.interfaces import IElement
  File "/usr/lib/python3.13/site-packages/zope/interface/interfaces.py", line 54, in <module>
    class IElement(Interface):
    ...<91 lines>...
            """
  File "/usr/lib/python3.13/site-packages/zope/interface/interface.py", line 772, in __init__
    self.__attrs = self.__compute_attrs(attrs)
                   ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/usr/lib/python3.13/site-packages/zope/interface/interface.py", line 791, in __compute_attrs
    aname: update_value(aname, aval)
           ~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/zope/interface/interface.py", line 787, in update_value
    raise InvalidInterface("Concrete attribute, " + aname)
zope.interface.exceptions.InvalidInterface: Concrete attribute, __firstlineno__
```

**Comment by classabbyamp** [comment]
it loooks like python3-flaky is not the right checkdep: https://github.com/pyca/pyopenssl/blob/9f82d9715c6221c7e702a07d34c70ebb42240008/setup.py#L100

**Comment by toadwastoast** [comment]
Thank you abby. 

Yeah, I had to package `pytest-rerunfailures` but thankfully there's no more build errors now.

**Pull request merged**
