### PR TITLE
New package: rsv-1.3.3

### PR DESCRIPTION
**Pull request by make-file**

### CODE REVIEW

**Comment by the-maldridge** [comment]
This should not be arch restricted, this sounds like a serious code quality bug, and therefore not fit for inclusion in the packages tree.

**Comment by JojiiOfficial** [comment]
Hi, the dev of this tool here.
It is not arch restricted, I simply haven't tested it for another architectures than x86_64.

**Comment by make-file** [comment]
i've tested it on other archs and it works. so i've removed `archs="i686 x86"`

**Comment by wael444** [comment]
?

**Comment by JojiiOfficial** [comment]
Lol what

**Comment by wael444** [comment]
??

**Pull request merged**
