### PR TITLE
New package: neochat-1.0

### PR DESCRIPTION
**Pull request by ndowens**
libQuotient was renamed from libqmatrixclient. The current version of Quaternion looks for libqmatrixclient. Once new version of Quaternion is released we can remove libqmatrixclient. So add conflict with libqmatrixclient until then

### CODE REVIEW

**Comment by ndowens** [comment]
Getting support from upstream for kquickimageeditor for armv* https://invent.kde.org/libraries/kquickimageeditor/-/issues/1

**Comment by Justinizer** [comment]
Would be nice to update NeoChat to 1.1. 
Attention: libQuotient-devel-0.6.6 is part of following commit too: #29082

**Comment by Justinizer** [comment]
Updatet it with: #29947
@ndowens If you want to maintain it I can add you as maintainer

**Comment by ndowens** [comment]
Going to let @Veganizer do this update

**Pull request closed without merging**
