### PR TITLE
[WIP] GHC 8.8.4

### PR DESCRIPTION
**Pull request by slotThe**
Minor version bump in order to keep in sync with the stackage lts resolver.  *Should* go smoothly.

- [X] ghc
- [x] ghc-bin
    - [X] musl
    - [x] ppc64le
    - [ ] upload
- [X] cabal-install
- [X] stack
 
Rebuild literally every single haskell package we have and see if anything's broken:

- [x]   git-mediate
- [x]   xmonad-contrib
- [x]   kmonad
- [x]   cgrep
- [x]   debug-me
- [x]   hlint
- [x]   hoogle
- [x]   xmonad
- [x]   darcs
- [x]   shellcheck
- [x]   git-annex
- [x]   hledger
- [x]   pandoc
- [x]   xmobar

### CODE REVIEW

**Comment by q66** [comment]
apologies, didn't have time to look into this

i'll build the ppc64le toolchain in the next few days, after that we'll have to test rebuilding stack again, as it tends to break from time to time, and then we can merge it

**Comment by slotThe** [comment]
On Fri, Sep 25 2020 08:44, Daniel Kolesa wrote:
> apologies, didn't have time to look into this
>
> i'll build the ppc64le toolchain in the next few days, after that
> we'll have to test rebuilding stack again, as it tends to break from
> time to time, and then we can merge it

Ah no worries, looking forward to getting this done!

**Comment by q66** [comment]
ghc 8.8.4 for ppc64le now available, at https://repo.voidlinux-ppc.org/distfiles/ghc-8.8.4-powerpc64le-void-linux.tar.xz

checksum `4a13d36a3e3d605db02b89269ed727c3ba23c9d03b84b72c1716a910a28f8074`

it'll need to be mirrored to the right location, but that can be done later...

for now we need to test if stack still builds, and if there are any other updates to be done

**Comment by q66** [comment]
I didn't notice the `x86_64-musl` bindist wasn't uploaded, why isn't there a link anywhere?

**Pull request merged**
