### PR TITLE
telegram-desktop: Update to 4.5.1

### PR DESCRIPTION
**Pull request by baalajimaestro**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64

This PR breaks on musl, and I am unsure how to fix this, please assist me on the same.

### CODE REVIEW

**Review by kruceter — CHANGES_REQUESTED** [review]
I would recommend you to reformat commit headers to the following verbatim:

* `telegram-desktop: update to 4.5.1.`

* `tg_owt: update to 0.0.0.20221208.`

Now that you have decided to use `-DDESKTOP_APP_USE_PACKAGED=ON`, `protobuf` should be added back to `hostmakedepends`, just like you did it elsewhere.

Please remove the line containing `-DTDESKTOP_LAUNCHER_BASENAME=org.telegram.desktop.desktop` since it is obsoleted and removed upstream (https://github.com/telegramdesktop/tdesktop/commit/fc4682d77eeadb5655b5d7083314ae342703ce65).

You may want to remove `getonescriptspan_test.cc` from the build chain entirely to resolve the issue at hand. Please append this patch: [cld3_getonescriptspan_test.txt](https://github.com/void-linux/void-packages/files/10343683/cld3_getonescriptspan_test.txt)

I assume the excluded file is used for testing which does not take place with telegram-desktop, hence there is no need for it.

I could build the package successfully, but since I do not use it, the proper testing should be done by yourself and others.

**Comment by JamiKettunen** [comment]
Previous update attempt (author gave up for now): #41063

**Comment by kruceter** [comment]
> Previous update attempt

Oh, it has the same problem which is not much different from what happens here.

**Comment by JamiKettunen** [comment]
Perhaps look at https://gitlab.alpinelinux.org/alpine/aports/-/tree/master/community/telegram-desktop for hints on the `musl` problem

**Comment by kruceter** [comment]
The submitter claimed on #voidlinux that he found nothing suspicious with APKBUILD that would indicate a problem with musl.

However I myself find it suspicious how it could build with `getonescriptspan_test.cc` intact.

**Comment by baalajimaestro** [comment]
Thanks a lot for looking in, and merging this! Was stuck with other priorities :sweat_smile:

**Pull request merged**
