### PR TITLE
matio : update to 1.5.18

### PR DESCRIPTION
**Pull request by pandom79**
required by hdf5

### CODE REVIEW

**Comment by pandom79** [comment]
There is only a probel related x86_64 musl. How to fix it?

**Comment by ericonr** [comment]
Add `musl-legacy-compat` to `makedepends` for musl.

**Comment by ericonr** [comment]
Might want to pull this into the `hdf5` update PR, btw.

**Comment by ahesford** [comment]
Please incorporate with #25569 because this must be built *after* `hdf5`.

**Pull request closed without merging**
