### PR TITLE
sbsigntool: rewrite post-install kernel hook

### PR DESCRIPTION
**Pull request by sgn**
* run the hook on target filesystem
* Use ls | awk to check ownership and permission, instead of relying on
  GNU-stat.
* libify signing code, in order to support uefi bundle in the future
* Stop append signature to the efi signed by current key/cert.

While we're at it,
* add post-remove script to remove unsigned file if exist

---

@ericonr @ahesford I think you may be interested on this.

### CODE REVIEW

**Comment by Duncaen** [comment]
Is it possible to change the options to set/unset instead of checking for 1 to make all the hooks more uniform, without breaking compatibility?

**Comment by sgn** [comment]
Yes, at the time, I started `sbsigntool`, I mostly copy from `efibootmgr`.
It's too late now.

**Comment by ericonr** [comment]
Could we add support for the UEFI bundles already? Source `dracut-uefi-hook` and check if they are being built, then try to sign them.

**Comment by sgn** [comment]
> Could we add support for the UEFI bundles already? Source `dracut-uefi-hook` and check if they are being built, then try to sign them.

Sure, will do in the weekend. Have we decided stable variable name for that hook, yet?

**Comment by ericonr** [comment]
I don't think so. It's in #22484.

**Comment by ericonr** [comment]
There weren't complaints about the filename, but there were some comments regarding the variables themselves. I think they are solved, though.

**Pull request closed without merging**
