### PR TITLE
New package: clapper-0.6.0

### PR DESCRIPTION
**Pull request by deimonn**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86_64-musl
  - armv6l-glibc (cross)

### CODE REVIEW

**Comment by AnInternetTroll** [comment]
Tested on x86_64-glibc and works as expected! Tried with some mp4 and
mkv videos and they played without issue.

**Comment by AnInternetTroll** [comment]
You should consider adding a clapper-devel subpackage (check out 
`xnew -a clapper clapper-devel`) and the LGPL-2.1-or-later license (or
is it just LGPL-2.1-only? I can never tell :P)

**Comment by deimonn** [comment]
Don't worry, I can't tell either hahaha

From looking at the README, I can say that the two clapper libraries (`libclapper` and `libclapper-gtk`) are `LGPL-2.1-or-later` while the `clapper` binary itself is `GPL-3.0-or-later`.

I mostly mimicked [the AUR package](https://aur.archlinux.org/packages/clapper) while writing this one. I'm wondering on how to split this package if I do - technically there's two libraries (`libclapper` and `libclapper-gtk`), Vala bindings and the actual application itself, all originating from one repo. Do I separate it into just `clapper` and `clapper-devel` or should I do more?

Apologies for the cluessness.

**Comment by ahesford** [comment]
For now, just stick with `clapper` and `clapper-devel`. If some parts of the package are LGPL and others are pure GPL, then the main package should list both licenses, and the devel package will inherit that.

**Comment by deimonn** [comment]
Done, let me know if I need to make any changes.

**Pull request closed without merging**
