### PR TITLE
snapper: update to 0.8.1

### PR DESCRIPTION
**Pull request by sww1235**
hopefully this time things work. This was created on a fork after a more thorough reading of the manual. 

I ran xlint on this with no errors so lets see what travis has to say

### CODE REVIEW

**Comment by sww1235** [comment]
looks like things are borked on the 0.8.1 release. I can do a little more digging but will have to open a PR with opensuse

**Comment by sww1235** [comment]
looks like boost 1.68 broke things. Going to ask the snapper devs if they have any ideas.

**Comment by aschnell** [comment]
snapper builds find with boost 1.68 on openSUSE, e.g. https://build.opensuse.org/public/build/filesystems:snapper/openSUSE_Tumbleweed/x86_64/snapper/_log.

Unfortunately the reason for the error you are seeing is not clear to me.

**Comment by sww1235** [comment]
looks like snapper won't build until https://github.com/openSUSE/snapper/pull/460 gets merged. boost and btrfs both define `#swap` which is causing the issue

**Comment by sww1235** [comment]
added upstream patch incorporating changes made in https://github.com/openSUSE/snapper/pull/460 since they are not in the current release version.

**Comment by aschnell** [comment]
btrfs-progs 4.19.1 renamed the swap macro, see https://www.mail-archive.com/linux-btrfs@vger.kernel.org/msg82954.html.

**Comment by maxice8** [comment]
#5452

**Comment by sww1235** [comment]
@maxice8 thanks for that. When snapper tags a new release my patch can be removed. Otherwise it should't hurt anything.

**Pull request merged**
