### PR TITLE
New package: brave-browser-0.56.15

### PR DESCRIPTION
**Pull request by pr310d3r**
brave-browser for Void Linux users

### CODE REVIEW

**Comment by Vaelatern** [comment]
Reasons I don't want this package.
- It's yet another browser
- It's yet another chromium based browser
- It's not built from source?
- Restricted yet MPL-2.0?
- Somehow not available on more archs?
- Can this software even be MPL-2.0?

**Comment by notramo** [comment]
@Vaelatern If it's "yet anotther browser", could you point a currently packaged browser that has the same features as Brave (BAT, built-in ad, tracking, and fingerprint blocking)?

**Comment by Vaelatern** [comment]
Firefox has built in stuff you just need to turn on. So does Chrome. And there are plugins for any further fixes.

**Comment by notramo** [comment]
https://addons.mozilla.org/hu/firefox/search/?q=basic%20attention%20token&platform=Linux&appver=63.0.3

**Comment by CameronNemo** [comment]
@notramo we don't even have a bch wallet, a BAT enabled browser isn't a deal breaker. Vaelatern is not necessarily saying this is bad software, just that it is not a good fit for Void. What is the advantage of redistributing Brave's DEB? What gains are made here?

**Comment by Duncaen** [comment]
I think adding more packages that use vendor distributed binaries gives users the false sense of software availability on void.
We have no control over it and it is going to break if things like fontconfig get updated.
We already have this problem with a bunch of closed source electron/chromium based applications adding more, even open source programs is just a bad move.

**Comment by philipgg** [comment]
Before adding a new browser, please update Firefox ESR.

https://github.com/void-linux/void-packages/pull/3516

**Comment by Vaelatern** [comment]
I think we agree that this PR is not a good fit for Void. Thank you for your effort, but we are not going to be able to accept this PR at this time.

**Comment by Smooey** [comment]
It's messed up though that the powers to be are rejecting packages submitted by other users... I like Brave, and it was the first thing I looked for after installing Void linux and of course like normal couldn't find a package any where for it. Google sucks for privacy (built-in) and Firefox is no better... Epic browser you can't install extensions nor SRW Iron. Yandex isn't English friendly really and Opera is bloated beyond belief. A lot of linux based browsers don't allow Chrome extensions so we're up shit creek without paddle. George Soros and Firefox are combating "fake news" / alternative news, and Google is spying, and Void devs are "controlling"/playing nazi of what's allowed in or not... we're fucked. 1984 is here.

**Comment by Duncaen** [comment]
The proposed package just redistributed vendor provided binaries, there is nothing stopping you from extracting and using the binaries on your own system.

I explained it already in https://github.com/void-linux/void-packages/pull/5511#issuecomment-445405684.
Another issue is that if a dependency of the binaries would be updated the package would block void from updating the dependency and we would be required to wait for the vendor to release new binaries linked against the updated dependency, which might take years because they are more likely to use versions used in debian release and not like void the most recent stable release.

You can spew your conspiracy theories and remarks somewhere else, if you can't even read this thread and understand why this package was not accepted, how do you think you are able to even understand the other things you are talking about.

> If people want something and contribute to Void then they should be allowed to do it.

No, thats not how it works, void is void because the "devs" make decisions and you have to live with it or start your own distribution.

In general, stop this bullshit, void is in no obligation to provide you anything and posting bullshit like this will just get you banned from participating in this issue tracker in no time.

**Comment by Logarithmus** [comment]
@Duncaen 
> The proposed package just redistributed vendor provided binaries, there is nothing stopping you from extracting and using the binaries on your own system.

Hmm, I thought that one of the main reasons of using the package manager is the ease of uninstalling any program without having to manually search and delete every file which came with this program.

>Another issue is that if a dependency of the binaries would be updated the package would block void from updating the dependency and we would be required to wait for the vendor to release new binaries linked against the updated dependency, which might take years because they are more likely to use versions used in debian release and not like void the most recent stable release.

Brave devs have been managing to keep up with Chromium releases very closely so far. E. g. latest Brave version 1.14.84 is based on Chromium 85. Thus I think the dependencies should be pretty much the same as of Chromium's, and it won't require much effort to maintain. I understand your concerns, but IMHO there's a lot of exaggeration.

I'd like to point out that Brave is not just a yet another Chromium fork as you may think, it has blazing-fast ad-blocker written in Rust, which is compiled to native code, unlike JavaScript extensions such as uBlock Origin. Also there's built-in tracking protection. You may say "just install Firefox if you want tracking protection". But unfortunately, hardware acceleration in Firefox on Linux is still many steps behind Chromium. Hardware video decoding still doesn't work, recently tried on AMD Radeon HD 7670M and NVIDIA GTX 960, both with OpenGL and WebRender compositors, with all those fancy environment variables, about:config flags and stuff. Browsing in Firefox overall feels sloppy, compared to Chromium. Not to mention browser benchmarks, e. g. Fish Bowl, Firefox is a looser, sad but true.
Maybe it works better with Wayland, but currently Wayland is usable only on GNOME. Any other DE (e. g. KDE) is not an option, it's very unstable and basically unusable.
 
Personally I see 4 options here:
1) Add *brave-browser* package with *restricted=yes* flag and build from source
2) Add *brave-browser* with *restricted* flag and just use vendor provided binaries
3) Add *brave-browser* without *restricted* flag and just use vendor provided binaries
4) Add *brave-browser* without *restricted* flag and build from source
5) Do nothing

Obviously, option 5 is the easiest one.
Options 1 and 2 is are good trade-off between server load and user's convenience (again, using package manager is much more convenient than manually extracting and deleting files).
Option 3 - we should investigate, if Brave's devs allow redistribution of their binaries.
Maintainance-wise, options 3 and 4 aren't so bad as you describe, if you take into account the fast pace of Brave's development (as I've already mentioned, latest Brave is based on latest Chromium, so the dependencies are basically the same).
Option 4 require more performant build server or usage of incremental builds.

As I learnt from the discussions in this repo, lack of computational power on Void's build server is often the main reason to reject new packages. If it's so much of an issue, maybe we just need to get a more performant server? I'm willing for making donations for it, and I'm sure there will be other Void users who will support this initiative.

**Pull request closed without merging**
