### PR TITLE
New package: python3-typer-0.9.0

### PR DESCRIPTION
**Pull request by c0m4r**
Typer, build great CLIs. Easy to code. Based on Python type hints.
https://github.com/tiangolo/typer

#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - **x86_64-glibc**
  - **x86_64-musl**

### CODE REVIEW

**Comment by classabbyamp** [comment]
are there applications that you want to package that use the python libraries you're creating new package PRs for? if not (and especially if these are for projects you are developing), you're better off installing these libraries in a python virtual environment or with pipx. adding python libraries that no packages use adds to maintainer burden with little benefit.

**Comment by c0m4r** [comment]
Yes, ultimately I plan to package a vulnerability scanner: [safety](https://github.com/pyupio/safety), which depends on these.

**Comment by classabbyamp** [comment]
then you should make one pr with that package and all its dependencies

**Comment by c0m4r** [comment]
I was about to add _safety_-specific dependencies in a separate PR, however these are not strictly related to _safety_ and can well be used in other projects. There are plenty of Python3 modules in the repository like these, even such that no package depends on, and only a handful of which are apps on itself.

**Comment by classabbyamp** [comment]
> these are not strictly related to safety and can well be used in other projects

doesn't matter, just do it all in one. if you want to package safety, you should just do it. having a bunch of PRs that depend on each other will make it harder to get merged.

**Comment by c0m4r** [comment]
image

**Pull request closed without merging**
