### PR TITLE
rpi-kernel: add nftables support.

### LINKED ISSUE #23662: rpi-kernel: no support for nftables
`nft -f /etc/nftables.conf`

`Error: Could not process rule: Not supported`

### PR DESCRIPTION
**Pull request by fosslinux**
Applied from upstream. https://github.com/raspberrypi/linux/commit/fe915debc1925397f78db8bbfc9f488b0ce4e009. Will be in next update. Is already enabled for arm*.

Closes #23662.

### CODE REVIEW

**Comment by ahesford** [comment]
There's been some talk about bumping to Linux 5.4 now that Raspbian has moved. Any comments about rolling this into a 5.4 update?

**Comment by fosslinux** [comment]
Go right ahead, and I'll close this PR.

**Comment by ahesford** [comment]
I mean that as an invitation for you to update. ;) I don't currently have Void on a Raspberry Pi to test.

**Comment by fosslinux** [comment]
Lol, ok. I'll take a crack at it soon-ish :)

**Pull request merged**
