### PR TITLE
steam: remove patch to LD_PRELOAD required system libs.

### PR DESCRIPTION
**Pull request by Nicop06**
This breaks Aspyr games such as Civilization 5 or Borderlands 2.

### CODE REVIEW

**Comment by teldra** [comment]
Please increment revision in the steam template.

**Comment by Nicop06** [comment]
> Please increment revision in the steam template.

Done.

**Comment by teldra** [comment]
Maybe you forgot to `git add srcpkgs/steam; git commit --amend; git push origin -f`?

**Comment by Nicop06** [comment]
:man_facepalming: this is what happens when using mercurial too much... This is now done for good (I checked, multiple times).

**Pull request merged**
