### PR TITLE
sway: added pcre2 runtime dependency

### PR DESCRIPTION
**Pull request by Clos3y**
#### Testing the changes
- I tested the changes in this PR: YES

#### Local build testing
- I built this PR locally for my native architecture, (x86-64)

### CODE REVIEW

**Comment by classabbyamp** [comment]
is it not already there?

```
$ xbps-query -Rp run_depends sway | grep pcre
libpcre2>=10.22_1
```

**Comment by Clos3y** [comment]
> is it not already there?
> 
> ```
> $ xbps-query -Rp run_depends sway | grep pcre
> libpcre2>=10.22_1
> ```

On a fresh install, sway would not install without me explicitly installing pcre2, rather than the library.

**Comment by subnut** [comment]
wait a minute... sway uses the pcre2 binary itself instead of using the library?

**Comment by classabbyamp** [comment]
what was the error?

**Comment by classabbyamp** [comment]
> wait a minute... sway uses the pcre2 binary itself instead of using the library?

from a quick github search, it uses neither `pcre2grep` nor `pcre2test`, which are the only things in the pcre2 package

**Comment by Clos3y** [comment]
> wait a minute... sway uses the pcre2 binary itself instead of using the library?

I guess? It's not libpcre2 that's listed as a dependency on their github, it's just pcre2

**Comment by subnut** [comment]
I'm currently using sway without having pcre2 installed, and I don't see any problems ....

**Comment by subnut** [comment]
@Clos3y did you face any problem due to not having pcre2 installed?

**Comment by Clos3y** [comment]
> what was the error?

Okay let me spin up the VM one second

**Comment by classabbyamp** [comment]
you can't expect upstreams to list things in exactly the way that void packages them most of the time, they probably mean libpcre2 but just say the name of the whole library

**Comment by Clos3y** [comment]
Sorry, I can't get the vm up yet, my download speed from the repos is too low to do it in a reasonable time. I'll close this pr and once I've confirmed the issue raise it as such

**Comment by classabbyamp** [comment]
next time, just leave it open, there's no urgency. opening/closing creates extra noise for people subscribed to the repo

**Comment by Clos3y** [comment]
My bad, it wasn't pcre2 that fixed the issue: it was just a ttf font missing. Apologies for that, I'll be more careful next time.

**Pull request closed without merging**
