### PR TITLE
nvidia390: adding a patch for linux5.8

### PR DESCRIPTION
**Pull request by MrLimb**
Fixing the nvidia drivers, again. Hello, @ericonr .

### CODE REVIEW

**Comment by ericonr** [comment]
Why can't this be added as a patch in `srcpkgs/nvidia-390/patches` ?

**Comment by MrLimb** [comment]
> Why can't this be added as a patch in `srcpkgs/nvidia-390/patches` ?

I'm sorry, but has something changed? Can I create a separate file? I'll read the documentation again.

**Comment by MrLimb** [comment]
I'll reopen it.

**Comment by ericonr** [comment]
Please don't open and reopen it, that just makes life harder for maintainers, because they receive an email for each action. Leave the PR open and make changes with it open.

**Pull request closed without merging**
