### PR TITLE
New package: gst-rtsp-server-1.18.5

### PR DESCRIPTION
**Pull request by 1is7ac3**
#### Testing the changes
- I tested the changes in this PR: YES

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): YES

#### Local build testing
- I built this PR locally for my native architecture, x86_64
- I built this PR locally for these architectures (if supported. mark crossbuilds):
    - armv7l

### CODE REVIEW

**Comment by marmeladema** [comment]
GStreamer has been updated to 1.20.1 in #36605 so you can probably bump the version here too

**Comment by 1is7ac3** [comment]
> GStreamer has been updated to 1.20.1 in #36605 so you can probably bump the version here too

 ready. updated to 1.20.1

**Comment by paper42** [comment]
This is a new package, please fill this section in the PR template.
```
<!--
#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**|**NO**
-->
```

**Comment by 1is7ac3** [comment]
> This is a new package, please fill this section in the PR template.
> 
> ```
> 
> ```

done

**Pull request closed without merging**
