### PR TITLE
x42-plugins: enable all arches

### PR DESCRIPTION
**Pull request by q66**
Fixing the other-arch builds is actually very easy, it only took a little bit of investigation. @bluntphenomena

### CODE REVIEW

**Comment by q66** [comment]
Okay, looks like more fixes will be needed for cross.

**Comment by bluntphenomena** [comment]
> Okay, looks like more fixes will be needed for cross.

removing -msse -msse2 -mfpmath=ss2 is exactly what i tried but didn't really help.
the build fails without explanation

**Comment by q66** [comment]
See my next update. That seems to make it build, though still waiting for the CI.

**Comment by bluntphenomena** [comment]
> See my next update. That seems to make it build, though still waiting for the CI.

well done, seems to work!

**Comment by q66** [comment]
The reason it didn't build is because the makefile check assumes that it's not cross-compiling and checks for a header in `/usr` instead of the cross sysroot. Since we're ensuring that the lib+header are present, the simplest way to fix it is to just remove the check

**Comment by q66** [comment]
Looks like we're good

**Comment by bluntphenomena** [comment]
> Looks like we're good

Alright, I would've never figured that out, thank you!

**Pull request merged**
