### PR TITLE
xfce4-panel: split lib

### PR DESCRIPTION
**Pull request by Piraty**

### CODE REVIEW

**Comment by q66** [comment]
Any reason for this?

**Comment by Piraty** [comment]
I don't remember the details anymore tbh, but once i was annoyed by something that required the only lib but pulled the hole xfce4-panel package along irrelevant (at least to me) dependencies.

**Comment by q66** [comment]
I'm pretty curious what that thing was... only panel widgets should really depend on the panel lib, and those make sense to pull in the panel too.

**Comment by Piraty** [comment]
You're probably right. Putting this PR to sleep until i can come up with more information

**Comment by Piraty** [comment]
I opened and rebased. Builds for x86_64
@pbui @q66 @Hoshpak

**Comment by Hoshpak** [comment]
lgtm

**Comment by pbui** [comment]
lgtm

**Pull request closed without merging**
