### PR TITLE
imath: update to 3.1.7,  openimageio: update to 2.4.9.0.

### PR DESCRIPTION
**Pull request by mhmdanas**
#### Testing the changes
- I tested the changes in this PR: **briefly**

@motorto

[ci skip]

### CODE REVIEW

**Comment by motorto** [comment]
I can only take a look at this properly after 20th of March (when my laptop comes back from warranty).

Maybe @lemmi can give a proper review sonner than me.

**Comment by lemmi** [comment]
I had a quick glance at it and the changes to my templates were probably overdue anyway, so thank you :)
As I'm not yet setup to do larger builds like this, I'd like someone else to run some tests.
Also it seam CI is running into timeout, I'm adding `[ci skip]` to this.

**Comment by mhmdanas** [comment]
> I had a quick glance at it and the changes to my templates were probably overdue anyway, so thank you :)

You're welcome. :)

>  As I'm not yet setup to do larger builds like this, I'd like someone else to run some tests.

What kind of tests are we talking about here?

>  Also it seam CI is running into timeout, I'm adding `[ci skip]` to this.

That's fair enough.

`openimageio` is failing to build on armv6l-musl in the CI because the vsed regexes need updates, so I'll try to handle that.

**Comment by mhmdanas** [comment]
I'd appreciate somebody testing this PR well. I'll try to do that myself, but I'm afraid time doesn't permit me to do so (and also, my machine takes ages to build everything changed here).

**Comment by mhmdanas** [comment]
For what it's worth, my Void laptop's fan stopped working, and until I get around to fixing that, I'd appreciate it if someone could take over this PR (at the very minimum, removing the duplicate variable definitions in the imath template that I mistakenly pushed, and testing the updated and changed packages).

**Comment by motorto** [comment]
Had a lock at the PR and I don't have any objections ! LGTM

Currently don't have a quick way to do large builds as this one, (have a dual core here) but I will leave overnight [xxbuild](https://github.com/Piraty/xxtools/blob/master/xxbuild) running. 
@mhmdanas  could you please test for some archs as well ?

I can have  the cross-builds ` aarch64-musl aarch64 armv7l-musl armv7l armv6l-musl armv6l` and you do the rest `x86_64 x86_64-musl i686` ? 

```
$ XXBUILD_ARCHS="aarch64 x86_64-musl i686" xxbuild -Q
```

Finally got a working laptop !

**Comment by mhmdanas** [comment]
> I can have the cross-builds  aarch64-musl aarch64 armv7l-musl armv7l armv6l-musl armv6l and you do the rest x86_64 x86_64-musl i686 ?

Sure. For what it's worth, my laptop is also a dual-core (with a mere 4 GBs of RAM to boot), but I'll leave it running the builds for some time. I'll report back as soon as the builds are over.

> Finally got a working laptop !

\o/

**Comment by motorto** [comment]
Probably just do an arch at the time ! Lets keep track of the archs here:

- [ ] aarch64 (cross)
- [ ] aarch64-musl (cross)
- [ ] armv6l (cross)
- [ ] armv6l-musl (cross)
- [ ] armv7l (cross)
- [ ] armv7l-musl (cross)
- [ ] i686
- [ ] x86_64
- [ ] x86_64-musl

**Comment by mhmdanas** [comment]
This was built on all the archs normally tested in the CI (see above comment), so this should be ready for review/merge.

**Pull request merged**
