### PR TITLE
iio-sensor-proxy: update to 3.5.

### PR DESCRIPTION
**Pull request by fanyx**
#### Testing the changes
- I tested the changes in this PR: **NO**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64
  - armv7l

### CODE REVIEW

**Comment by oreo639** [comment]
Remove the fr_FR workaround and add this patch: https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/-/commit/fe56bdba1243cc5f6a652eb75d11ae1d1957ff7e

Also make sure to test it.

**Comment by fanyx** [comment]
Tests succeed after adding the patch.
I'll test it once i'm back on my laptop

**Comment by oreo639** [comment]
Add back the vsed to do `s/cls.has_fr = True/cls.has_fr = False/`.

**Comment by fanyx** [comment]
i might not understand how to test this...
`dev/iio` does not show up on my system, so it's either just impossible or i'm missing some setup for it

**Comment by oreo639** [comment]
> `dev/iio` does not show up on my system, so it's either just impossible or i'm missing some setup for it

That's normal.

> i might not understand how to test this...

Did you enable the runit iio-sensor-proxy service?
(I did test it myself, but just so you know how to test it)

**Comment by fanyx** [comment]
Ohhh, no i did not

**Pull request merged**
