### PR TITLE
New-package: ttf-nerd-fonts-symbols-3.0.2

### PR DESCRIPTION
**Pull request by chrysos349**
@cinerea0

#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64

WHY?
`nerd-fonts` is a bloated package (2GB, REALLY?) which includes a ton of fonts, and scripts which can't be even executed by a non-root user due to permissions. BTW, these scripts have nothing to do with patching fonts, but with cheat sheet functionality. I don't even understand how it it was allowed into the repository in the first place!

`ttf-nerd-fonts-symbols` is the only part that's truly necessary. It provides unique glyphs.  My template includes also `fontconfig` preset.

### CODE REVIEW

**Comment by classabbyamp** [comment]
1. will this break things people who use these fonts by name?
2. it would make more sense for the old nerd fonts packages to be transitional dummy subpackages (grep for transitional in srcpkgs for examples) so that people don't get the old packages uninstalled

**Comment by chrysos349** [comment]
@classabbyamp good idea! working on it.

**Comment by chrysos349** [comment]
@classabbyamp done!

**Comment by cinerea0** [comment]
This is a bad idea:

1. This completely removes the OTF fonts.
2. There are 17 font families that are only packaged as their nerd-font patched variants. This change would remove them from users systems with no alternative except to manually install them.
3. This breaks things for people who use the fonts by their full name.
4. Even in situations where the "base" font is separately available, it doesn't seem to fallback properly.

**Comment by chrysos349** [comment]
I included INSTALL.msg to the affected packages to explain the change.

@cinerea0 

> This is a bad idea:

making this bloated package a part of the official repo WAS a bad idea. replacing it with a leaner version which includes only unique glyphs (as per package requirements concerning fonts) IS NOT!

> 1\. This completely removes the OTF fonts.

so what? the fonts can be downloaded manually.

> 2\. There are 17 font families that are only packaged as their nerd-font patched variants.

do you mean the fonts with included nerd symbols and changed names? it doesn't matter. again, they fonts can be downloaded manually.

> 2\. This change would remove them from users systems with no alternative except to manually install them.

the previous commits would. this one would leave all the fonts in `/usr/share/fonts/NerdFonts`, thanks to @classabbyamp 's suggestion.

> 3\. This breaks things for people who use the fonts by their full name.

again, it won't. the only change is the fonts won't be updated anymore. they'll be left intact in the system dir.

> 4\. Even in situations where the "base" font is separately available, it doesn't seem to fallback properly.

people can download the full versions of fonts themselves.

**Comment by ahesford** [comment]
Whether you consider the addition of `nerd-fonts` to the repo a bad idea is irrelevant, because it is not your decision. We will not accept a PR that removes well-maintained packages from the distribution when the maintainer of those packages objects. Furthermore, you can avoid downloading the large font package and "download the [reduced] versions of fonts [yourself]" if you like.

If your PR offers some additional fonts that are not already present in the `nerd-fonts` packages, please separate the useful additions from the proposed removal and replacement. Otherwise, the PR is not suitable for merging.

**Pull request closed without merging**
