### PR TITLE
WIP: New packages: gotify server and CLI

### PR DESCRIPTION
**Pull request by CameronNemo**

### CODE REVIEW

**Comment by paper42** [comment]
Does the server Web UI work?

**Comment by CameronNemo** [comment]
the server does not even launch -- segfaults :(

**Comment by paper42** [comment]
I tried to package this a few months ago, but abandoned it after the UI didn't work, but I don't remember a segfault. Here is my template (not optimal, some lines are probably not neccessary):
```
# Template file for 'gotify-server'
pkgname=gotify-server
version=2.0.20
revision=1
wrksrc=server-${version}
build_style=go
go_ldflags="-X 'main.Version=${version}' -X 'main.Mode=prod'"
go_import_path="github.com/gotify/server"
hostmakedepends="yarn packr2"
short_desc="Simple server for sending and receiving messages in real-time"
maintainer="Paper <paper@tilde.institute>"
license="MIT"
homepage="https://gotify.net/"
distfiles="https://github.com/gotify/server/archive/v${version}.tar.gz"
checksum=18b656af071368a37493286a2fe6718ec9e50fcaa09ace651c4d72971cc70e89

system_accounts="_gotify"
make_dirs="/var/gotify/ 0755 _gotify _gotify"

do_check() {
	#make test-race test-coverage # test-js
	make test
}

post_extract() {
	vsed -i config.example.yml -e 's,data/,/var/gotify/,'
}

pre_build() {
	cd ui
	yarn install
	yarn build
	cd ${wrksrc}
	# embed assets to the binary
	packr2
}

post_install() {
	mv ${DESTDIR}/usr/bin/server ${DESTDIR}/usr/bin/gotify-server
	vlicense LICENSE
	vsconf config.example.yml
	vsv gotify
}
```
`files/gotify/run`:
```
#!/bin/sh
export GIN_MODE=release
exec chpst -u _gotify:_gotify gotify-server
```

**Comment by CameronNemo** [comment]
@paper42 would you be interested in maintaining the package? It works on x86_64, but I could not get it to work on aarch64-musl which is where I want to use it.

**Comment by paper42** [comment]
That's weird, I am running it on my rpi3B (aarch64-musl). I am not interested in maintaining the package because the code is quite horrible and huge for what it does. I started writing my own small alternative server which implements gotify's API, I may finish it one day.

**Pull request closed without merging**
