### PR TITLE
[DO NOT PACKAGE] New package: ulauncher

### PR DESCRIPTION
**Pull request by paualberto**
This is an updated version of [this template](https://github.com/void-linux/void-packages/issues/5532#issuecomment-447585459) since the issue mentioned there was fixed (in libappindicator 12.10.0_2)

### CODE REVIEW

**Comment by Hoshpak** [comment]
We should wait until upstream releases a version compatible with python 3 since python 2 will reach its EOL in 7 months. No new python 2 only packages are added to the repository.

**Comment by paualberto** [comment]
Sure.
Ulauncher 5 supports Python3 extensions, but I don't think the program itself has been ported. Will reopen when a py3 version is ready.

**Comment by paualberto** [comment]
I got confirmation that Ulauncher 5 will be Python 3 only. 
I updated the template to be compatible with the development version of Ulauncher 5, which builds and runs just fine. I will reopen the PR once the stable version comes out.

paualberto/void-packages@1448933

**Comment by CameronNemo** [comment]
Newer versions of ulauncher are using python3. Can this PR be updated?

**Comment by Anachron** [comment]
@paualberto please update this PR.

**Comment by paualberto** [comment]
Sorry, I had some issues in the last months. I'll try to update it now

**Comment by paualberto** [comment]
Actually this might take longer than expected, the reason I didn't do anything in the last months is I moved to another country, left my desktop PC behind, and now I don't have Void anymore to test stuff 😅  so this may take longer than expected. 

Hold on tight. Suggestions accepted.

**Comment by CameronNemo** [comment]
No worries, take care of yourself.

**Comment by Anachron** [comment]
Yes, we're not in hurry here and good luck on your private life!

**Comment by Piraty** [comment]
this seems ready to merge, given @paualberto fixes python3.8 warnings like
```
/usr/lib/python3.8/site-packages/ulauncher/main.py:8: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
```

**Pull request closed without merging**
