### PR TITLE
rustup: install completions for Cargo.

### PR DESCRIPTION
**Pull request by gbrlsnchs**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
This makes the `rustup` package conflict with `cargo`, which isn't ideal.

**Comment by gbrlsnchs** [comment]
> This makes the `rustup` package conflict with `cargo`, which isn't ideal.

Is there a useful use case where one installs both `cargo` and `rustup`?

**Comment by ericonr** [comment]
There can be, I don't think we should make it impossible to install them together...

To be fair, I don't feel this as much because fish has built in completions already, but still.

**Comment by gbrlsnchs** [comment]
> There can be, I don't think we should make it impossible to install them together...
> 
> To be fair, I don't feel this as much because fish has built in completions already, but still.

I agree. The reason I opened this PR is because I switched from manually installed rustup to the one packaged by Void, and the first thing I noticed was my Cargo completion wasn't working anymore. What do you think is the best solution for this case? Should I keep my rustup template patched locally only? I wouldn't mind, really.

**Comment by ericonr** [comment]
I'm really not sure... The final version of this PR, if merged, should also remove installation of these files from the `cargo` package, but I'm mostly against changing this. There isn't an ideal solution, I *think*.

**Comment by ericonr** [comment]
Ok, I'm closing this for now.

**Pull request closed without merging**
