### PR TITLE
New package: Slic3r-1.3.0

### PR DESCRIPTION
**Pull request by Gigahawk**
Apologies for closing #634, I accidentally pushed before running xbump while the branch was even with master and the PR closed automatically

### CODE REVIEW

**Comment by Gigahawk** [comment]
There seems to be an issue with cross building perl packages, compiling for i686 fails on my x86_64 computer but works fine in the travis i686 bootstrap. I'll figure out which specific packages are causing the problem and push again.

**Comment by newbluemoon** [comment]
Packages for i686 don’t have to be cross-compiled. You can create an i686 masterdir like e.g.

    ./xbps-src -m masterdir-i686 binary-bootstrap i686

**Comment by Gigahawk** [comment]
I've tried everything I can think of, cross compiling works fine on my own machine (had to add a check that would disable tests since the host system cant run the cross compiled binaries). 

The cross compile builds fail on Travis with:

**Comment by Gigahawk** [comment]
I've just turned off compilation for the architectures where it doesn't work. It's very unlikely that anyone will need to use Slic3r on an arm system anyways.

**Comment by Vaelatern** [comment]
Please undo turning off compilation.
You did it wrong in any case.

**Comment by Gigahawk** [comment]
Sorry, can you clarify?
`perl-Wx` refuses to cross compile because it can't find `wxWidgets-devel`, I've tried everything I can think of including manually adding the include folders into the build arguments (which shouldn't be necessary since it looks like they've already been added) and it still wont find the headers. This behavior doesn't occur when not cross compiling. 
If the issue is with placing `-devel` packages in `hostmakedepends`, again many of the other perl packages don't cross compile unless the headers are placed in the host's `/usr/include` (presumably because of the way their build scripts are configured, I'm not really a perl progammer).

**Comment by Vaelatern** [comment]
Remove the spurious `only_for_archs`.

**Comment by Gigahawk** [comment]
They are there to prevent cross compilation, if I remove them `perl-Wx` and `perl-Wx-GLCanvas` fail to build. Is there a proper way to prevent cross compilation?

**Comment by Vaelatern** [comment]
`nocross="Can't find the wx headers on a cross build"`

**Comment by Vaelatern** [comment]
Quoting the very-searchable Manual.md:

- `nocross` If set, cross compilation won't be allowed and will exit immediately.

**Comment by Gigahawk** [comment]
My apologies, I've skimmed it a few times and must have missed it.

**Comment by newbluemoon** [comment]
I think the problem with cross compiling perl-Wx is the line

    INC = -I. -I. -I/usr/lib/wx/include/gtk2-unicode-3.0 -I/usr/include/wx-3.0

in the generated `Makefile`. I haven’t been able to figure out how the includes are determined, yet, but as a quick and dirty work-around you could add the following above `make ...` in `do_build()`:

```
sed -i -e "s;-I\(/usr/lib/wx/include/\);-I${XBPS_CROSS_BASE}\1;" \
 -e "s;-I\(/usr/include/wx\);-I${XBPS_CROSS_BASE}\1;" \
 Makefile
```

With this tweak I was able to cross-build it locally.

**Comment by Gigahawk** [comment]
Actually that's the odd thing, cross compiling on my machine works just fine. I've been making frequent pushes because the issue only shows up on travis. Here's the log I get when I comment out the `noarch` lines and do `./xbps-src -a aarch64 -C pkg Slic3r`

https://gist.github.com/Gigahawk/979cdc9e6336c608719a2fe68d14ef85

**Comment by Gigahawk** [comment]
Yup, adding the sed line doesn't do anything on travis, but on my machine perl-Wx cross builds with or without it.

**Comment by newbluemoon** [comment]
I think cross-compilation works for you locally because you have wxWidgets-devel in `hostmakedepends` which usually isn’t the way to go for finding required includes (there might be target specific differences; an exception is QT5 right now).

Travis fails because e.g. perl-Wx is both in `makedepends` and `hostmakedepends`. So it has to be built twice for the host and the target, but this doesn’t seem to be possible with Travis.

**Comment by Johnnynator** [comment]
I can approve that local cross builds do succeed.

**Comment by Gigahawk** [comment]
@newbluemoon the latest push with the sed line also has all the `-devel` packages removed from `hostmakedepends` (with a comment for now, I'll get everything cleaned up for real once all the issues have been worked out)

**Comment by maxice8** [comment]
I Merged packages individually after doing some fixes. Please open a new PR with only the main package.

**Pull request closed without merging**
