### PR TITLE
wxWidgets: add make-abicheck-non-fatal.patch (resolves #1785)

### LINKED ISSUE #1785: Erlang built with -o x11 link error
### System

* xuname:  
  Void 4.17.14_1 x86_64 GenuineIntel uptodate rFFF
* package:  
  erlang-21.0

### Expected behavior
Compiled with `-o x11` should link with `wx` libraries and it should run graphical applications, like `observer:start()`.

### Actual behavior
`observer:start()` doesn't work and throws an error like:
```=CRASH REPORT==== 15-Aug-2018::07:49:14.974426 ===
  crasher:
    initial call: observer_wx:init/1
    pid: <0.83.0>
    registered_name: observer
    exception exit: {{load_driver,"undefined symbol: _ZThn704_N17wxGenericListCtrl31GetSizeAvailableForScrollTargetERK6wxSize"},
                     [{wxe_server,start,1,[{file,"wxe_server.erl"},{line,65}]},
                      {wx,new,1,[{file,"wx.erl"},{line,115}]},
                      {observer_wx,init,1,
                                   [{file,"observer_wx.erl"},{line,98}]},
                      {wx_object,init_it,6,
                                 [{file,"wx_object.erl"},{line,372}]},
                      {proc_lib,init_p_do_apply,3,
                                [{file,"proc_lib.erl"},{line,249}]}]}
      in function  wx_object:init_it/6 (wx_object.erl, line 385)
    ancestors: [<0.81.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: [{'_wx_object_',{observer_wx,'_wx_init_'}}]
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 292
  neighbours:
```

### Steps to reproduce the behavior

Compile with:
```
./xbps-src clean erlang
./xbps-src pkg -o x11 erlang
sudo xbps-install --repository=hostdir/binpkgs erlang
```
Then run with:
```
erl
observer:start().
```

### PR DESCRIPTION
**Pull request by cr6git**
The patch comes from [here](https://git.archlinux.org/svntogit/packages.git/tree/trunk/make-abicheck-non-fatal.patch?h=packages/wxgtk)...

### CODE REVIEW

**Comment by chneukirchen** [comment]
I think this patch is harmful and we should instead figure out why the ABI changes, and why the libstdc++ rebuild wasn't enough here.

**Comment by chneukirchen** [comment]
When I build wxWidgets locally, I get ABI 1013.

**Comment by cr6git** [comment]
@chneukirchen ok, it is beyond my competence :persevere: I let you take care of this.

**Comment by cr6git** [comment]
@chneukirchen you were right, this patch seems unnecessary...

**Pull request closed without merging**
