### PR TITLE
gnucash: update to 4.4

### PR DESCRIPTION
**Pull request by manfredu**
@Hoshpak: Could you pls have a look at this PR? I'm not sure what to do about the unsuccessful checks...

### CODE REVIEW

**Comment by unspecd** [comment]
https://github.com/void-linux/void-packages/pull/27320#issuecomment-751323377

**Comment by Hoshpak** [comment]
The checks fail because they try to execute `make check` and it seems most of the test binaries are not available. To make them pass, it would be necessary to find out what is missing for the build process to build the tests and make sure they are compiled in the build process.

**Comment by manfredu** [comment]
> The checks fail because they try to execute `make check` and it seems most of the test binaries are not available. To make them pass, it would be necessary to find out what is missing for the build process to build the tests and make sure they are compiled in the build process.

What does the third parameter in "Build packages (x86_64, x86_64, 1)" mean? For the builds where it is set to 0 the build succeeds.

**Comment by fosslinux** [comment]
The 1 means that tests are being run.

**Comment by manfredu** [comment]
> The 1 means that tests are being run.

Thanks. So this explains why only those with 1 fail.

Can this pr still be processed?  

Maybe some tests are failing because `make test` is used? Only `make check` builds and runs the full test suite. Some tests depend on additional libraries and the cmake built-in target test does not build them. Once the check target has been built check and test are synonyms.

Gnucash has got an automatic build and test bot on Travis CI to run the full test suite after every commit and for every Github pull request, so the released code should be fine despite

See https://wiki.gnucash.org/wiki/Testing.

**Comment by manfredu** [comment]
With `make_check_target=check` only 4 tests failed out of 111:

The following tests FAILED:
         31 - test-qof (Subprocess aborted)
         54 - test-gnc-numeric (Failed)
         55 - test-gnc-timezone (Failed)
         56 - test-gnc-datetime (Failed) 

I will try to fix those as well, therefore I have set the PR to WIP.

**Comment by manfredu** [comment]
55 - test-gnc-timezone and
56 - test-gnc-datetime 
no longer fail after adding tzdata as dependency.

The remaining failures appear to be down to not having the fr_FR and de_DE locales installed. The locales are needed only for testing, so imho this is ok now and ready to go.

**Comment by fosslinux** [comment]
You should either disable those two tests or else add `|| : # some comment indicating that the failures are due to lack of locales` to the end of the `make check` block to make the tests pass.

**Comment by manfredu** [comment]
@Hoshpak Could somebody pls review this PR and merge, if possible? Thanks! :-)

**Comment by pullmoll** [comment]
Please squash commits.

**Comment by manfredu** [comment]
> Please squash commits.

Done.

**Pull request merged**
