### PR TITLE
New package: btop-1.1.3

### PR DESCRIPTION
**Pull request by brunorro**
#### Testing the changes
- I tested the changes in this PR: YES

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): YES

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-musl)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-musl: NO (should work)
  - armv7l: NO (should work)
  - armv6l-musl: NO (should work)

### CODE REVIEW

**Comment by paper42** [comment]
duplicate of #33249

**Comment by KeepBotting** [comment]
> duplicate of #33249

Is this still a dupe even though it's a newer version? btop would be nice to have. Any particular reason not to merge this or the older PR?

**Comment by q66** [comment]
this PR does not meet quality criteria (setting `archs` for no reason, `gcc` in `makedepends`, spurious comments, etc) while the other one does

**Comment by brunorro** [comment]
It's OK. The important part is getting btop packaged. BTW, could xlint give warnings about quality criteria?

Thank you

**Comment by paper42** [comment]
> BTW, could xlint give warnings about quality criteria?

xlint warns about things that make sense, are wrong in all cases and are easily detectable. For example gcc in makedepends might make sense in some cases (not this one), comments are sometimes even required, restricting archs is sometimes necessary, etc.

**Pull request closed without merging**
