### PR TITLE
New package: radio-sh-2.0

### PR DESCRIPTION
**Pull request by Singustromo**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-LIBC)

### CODE REVIEW

**Comment by classabbyamp** [comment]
> 1. System: The software should be installed system-wide, not per-user.
> 2. Compiled: The software needs to be compiled before being used, even if it is software that is not needed by the whole system.
> 3. Required: Another package either within the repository or pending inclusion requires the package.
>
> [...] Simple shell scripts are unlikely to be accepted unless they provide considerable value to a broad user base. [...]

from [CONTRIBUTING.md](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements)

how does this meet those requirements?

**Comment by ahesford** [comment]
This belongs in `~/bin`, not a distribution package.

**Comment by Singustromo** [comment]
> > 1. System: The software should be installed system-wide, not per-user.
> > 2. Compiled: The software needs to be compiled before being used, even if it is software that is not needed by the whole system.
> > 3. Required: Another package either within the repository or pending inclusion requires the package.
> > 
> > [...] Simple shell scripts are unlikely to be accepted unless they provide considerable value to a broad user base. [...]
> 
> from [CONTRIBUTING.md](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements)
> 
> how does this meet those requirements?

All right, I thought it might be something worth adding since there are also packages like #14199 with a similar functionality but also with more dependencies. I don't really think this is a **small** unneeded script.

**Comment by ahesford** [comment]
It's not about the length of the shell script, but whether

    curl -L -O ~/bin/output.sh https://some-url-for-download

is equivalent to

    xbps-install some-package

and, for a single shell script that is intended for individual use on a personal computer, is generally true. It is certainly true here. The PyRadio package requires a proper installation and integration into the system's python ecosystem (or else venv management) and is therefore a candidate for packaging.

**Pull request closed without merging**
