### PR TITLE
Bear: update to 3.0.8.

### PR DESCRIPTION
**Pull request by ericonr**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

I'm a bit hesitant on this one, https://github.com/rizsotto/Bear/issues gives the impression that the C++ rewrite generated lots of issues.

@Piraty @Johnnynator @ackalker

### CODE REVIEW

**Comment by ahesford** [comment]
The gRPC dependency changes are fine by me.

**Comment by ericonr** [comment]
The new Bear version seems generally worse, so I am very hesitant to merge the udpate. Not sure there's anything we're missing by not having it.

**Comment by Johnnynator** [comment]
> The new Bear version seems generally worse, so I am very hesitant to merge the udpate. Not sure there's anything we're missing by not having it.

Just update to 2.4.4. instead :P.
I haven't really used Bear in quite some time now, but reading the release notes, I do not see any "new" features, just mostly bug fixes of the c++ rewrite.

**Comment by ericonr** [comment]
Closing for now.

**Pull request closed without merging**
