### PR TITLE
New package: swayr-0.18.0

### PR DESCRIPTION
**Pull request by ram02z**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (x86_64-musl)
- [ ] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [ ] aarch64-musl
  - [ ] armv7l
  - [ ] armv6l-musl

### CODE REVIEW

**Comment by ram02z** [comment]
Not sure why my local version of `xlint` didn't give me the same warnings as the CI, but I have pushed the fixes to the warnings.

**Comment by ericonr** [comment]
CI uses git version of xlint.

**Comment by ram02z** [comment]
Waiting on https://github.com/void-linux/void-packages/pull/32555 to update from v0.62.

**Review by jcgruenhage — APPROVED** [review]
Looks good to me.

**Comment by ram02z** [comment]
Package v.1.18.0 won't build since the version of cargo is too old.

**Comment by jcgruenhage** [comment]
@ram02z Rust has been updated, so a rebase should fix this.

**Comment by ram02z** [comment]
> @ram02z Rust has been updated, so a rebase should fix this.

The swayr project has two tools as part of it now which I have no desire of maintaiting. Feel free to use the template.

**Comment by jcgruenhage** [comment]
yay, another swaybar/i3bar backend :D

I have no intention of using swayrbar, but swayr itself sounds useful enough, so I'll go ahead and whip up a template.

**Comment by jcgruenhage** [comment]
I just opened #37520 which includes both swayr and swayrbar, in case you're still interested in using one of those

**Pull request closed without merging**
