### PR TITLE
New package: v2rayA-2.0.1

### PR DESCRIPTION
**Pull request by xiarenfan**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-musl)

### CODE REVIEW

**Comment by xiarenfan** [comment]
Updates to previous packages [#38528](https://github.com/void-linux/void-packages/pull/38528)

**Comment by classabbyamp** [comment]
why did you add spaces to the paths?

**Comment by xiarenfan** [comment]
Because [this](https://github.com/void-linux/void-packages/pull/42221/checks?check_run_id=11280825123)

**Comment by paper42** [comment]
That is a warning about the commit message, please read CONTRIBUTING.md and follow it. Randomly adding directories with spaces to won't help.

**Pull request closed without merging**
