### PR TITLE
[NOMERGE] New package: pwntools-4.1.2

### PR DESCRIPTION
**Pull request by abenson**

### CODE REVIEW

**Comment by Chocimier** [comment]
python3-pwntools installs lot of executables, so should be named `pwntools`.
python3-ROPgadget advertises as executable, so should be named `ROPgadget`.

pwntools installs `/usr/bin/checksec` conflicting with checksec, `errno` conflicting with moreutils, `phd` conflicting with disputils.

Executables of pwntools depend on setuptools.

pwntools shouldn't install `TESTING.md` and more directly into `/usr/lib/python3.8/site-packages/`.

**Comment by abenson** [comment]
1. Renamed the packages, that makes sense.
2. Since the executable names don't really matter, I went ahead and prefixed them all with the package name.
3. There's an issue with upstream about polluting directories

**Comment by Chocimier** [comment]
How well does it work for you? I can't run it because of unsatisfied unstable unicorn version, also tests of generated code fail.

**Comment by abenson** [comment]
Ah, the executables do fail. the libraries work fine, I'll mark this NOMERGE until unicorn 1.0.2 and pwntools are updated to use it

**Comment by abenson** [comment]
Closed in 0efc6f14821b09cc4c9609e50f1f2f5a4dcefd36

**Pull request closed without merging**
