### PR TITLE
Python 3.11

### PR DESCRIPTION
**Pull request by ahesford**
Tracking the Python 3.11 version bump. 

[ci skip]

### CODE REVIEW

**Comment by ahesford** [comment]
The first-pass build for `x86_64` has completed, with the following failures:
- [ ] DarkRadiant
- [ ] blender
- [ ] blueman
- [ ] collectd
- [ ] freeorion
- [ ] gnome-builder
- [ ] idjc
- [ ] jack_mixer
- [ ] kore
- [ ] libtorrent-rasterbar
- [ ] mimeo
- [ ] mypaint
- [ ] piper
- [ ] profanity
- [ ] python3-altgraph
- [ ] python3-apsw
- [ ] python3-bitarray
- [ ] python3-cypari2
- [ ] python3-empy
- [ ] python3-fpylll
- [ ] python3-frozendict
- [ ] python3-greenlet
- [ ] python3-grpcio
- [ ] python3-keyutils
- [ ] python3-protobuf
- [ ] python3-pyFFTW
- [ ] python3-pygame
- [ ] python3-reportlab
- [ ] python3-ruamel.yaml.clib
- [ ] python3-snakeoil
- [ ] python3-snappy
- [ ] python3-typed-ast
- [ ] python3-watchman
- [ ] python3-yarl
- [ ] rdiff-backup
- [ ] renderdoc
- [ ] root
- [ ] shiboken2
- [ ] sigil
- [ ] sip4
- [ ] uwsgi
- [ ] wxPython4
- [ ] zbar

**Comment by paper42** [comment]
python3-typed-ast should be fixed after a rebase: de8fa883ae741551a58e7d858e6392611394a40d

**Comment by Marco-Sulla** [comment]
>     * [ ]  python3-frozendict upstream says we should wait for 5-6 months [[BUG] Build failure with Python 3.11 Marco-Sulla/python-frozendict#58 (comment)](https://github.com/Marco-Sulla/python-frozendict/issues/58#issuecomment-1180734809)

Upstream said he (me) will wait the official stable release.

**Comment by ahesford** [comment]
@Marco-Sulla thanks; we'll use the py-only version for the time being.

**Comment by ahesford** [comment]
I completed an `x86_64-musl` build and found the list of failing packages agrees with that for the corresponding glibc build.

**Comment by ahesford** [comment]
Ran through `aarch64` and fixed a few cross failures.

**Comment by ahesford** [comment]
This branch currently builds cleanly for all official arches.

**Comment by ahesford** [comment]
Python 3.11 is now out, so people can begin testing this.

**Comment by icp1994** [comment]
Yay! :tada:

**Pull request closed without merging**
