### PR TITLE
spotify-player: add alsa and pulseaudio backend features

### LINKED ISSUE #44557: spotify-player fails to connect to device
### Is this a new report?

Yes

### System Info

Void 6.1.34_1 x86_64-musl GenuineIntel uptodate

### Package(s) Affected

spotify-player-0.14.0_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

There's no upstream bug. The issue is due to the Void build itself.

### Expected behaviour

spotify-player should be able to find the desired backend.

### Actual behaviour

spotify-player is unable to find a backend.

### Steps to reproduce

Install spotify-player having only `alsa` installed and launch the application.

**REASON FOR FAILURE:**
The package is built with the default features, _i.e._ there are no `configure_args=` in the template.

Building the package with `cargo` using `cargo build --release --no-default-features --features alsa-backend` produces a working binary.

### PR DESCRIPTION
**Pull request by classabbyamp**
fixes #44557

@0323pin please test

#### Testing the changes
- I tested the changes in this PR: **NO**

### CODE REVIEW

**Comment by 0323pin** [comment]
@classabbyamp I'm having some issues installing packages built from source. `xbps-install --repository hostdir/binpkgs <package_name>` complains about the repository not being in `xbps.d`.

It's been a while I've used `xbps-src`, was there a change in behavior that hasn't been documented?

I'm sorry but, I can't test your change, I refuse to install `pulseaudio`

**Comment by 0323pin** [comment]
@classabbyamp There was a typo on my install command, everything ok with `xbps-src`, sorry for the noise.

Still, I don't know what's wrong :(

Just built and installed with `xbps-src`
2023-06-22-130147_1920x1080_scrot

Built with `cargo`
2023-06-22-130254_1920x1080_scrot


Btw, 0.14.1 was released [3 weeks ago](https://github.com/aome510/spotify-player/releases/tag/v0.14.1), you might want to bump the version as well.

**Comment by classabbyamp** [comment]
sorry I don't have a spotify account so I can't really bump it myself

**Comment by 0323pin** [comment]
@classabbyamp I had a chat with the dev and multiple backends are currently not well supported. Still, I have no clue why the default `rodio` backend doesn't work here. `rodio` uses `cpal` which in turn uses `alsa`, so it should work.

**Pull request closed without merging**
