### PR TITLE
Orphan dleerams packages

### PR DESCRIPTION
**Pull request by jcgruenhage**
This PR orphans dleeram's packages and takes over maintainership for rustup

### CODE REVIEW

**Comment by jnbr** [comment]
is dleeram aware of this?

**Comment by jcgruenhage** [comment]
Don't know. I wrote them an email a month ago, another one 2 weeks ago, haven't gotten a response. They also haven't contributed to void in a long time.

**Comment by jnbr** [comment]
@dleeram

**Comment by dleeram** [comment]
I'm sorry for not responding earlier. I no longer use void, so I'm OK with this.

**Comment by Hoshpak** [comment]
It seems the rustup distfile checksum changed.

**Comment by jcgruenhage** [comment]
Seems like rustup has seen a few more changes, will fix the package now. Should that be part of this PR?

**Comment by jcgruenhage** [comment]
they all fail on rustfmt, but rustfmt hasn't changed at all. For rustfmt to build, we need to package rust nightly first. Shall we just remove rustfmt? The currently packaged version is highly outdated anyway.

**Comment by jcgruenhage** [comment]
@Hoshpak any update on this? What should I do?

**Comment by jnbr** [comment]
+1 for removing rustfmt. We kept it because there was hope that it would return to be usable with stable rust releases, but this didn't happen and our version of rustfmt is now diverged from the actual rust syntax.

**Comment by Hoshpak** [comment]
The next issue: iomenu seems to have disappeared, the distfiles and project page are not there anymore.

**Comment by jcgruenhage** [comment]
https://github.com/Northcode/iomenu has the code, but there are no tags. Shall iomenu also be removed?

**Comment by jcgruenhage** [comment]
So, CI approved it. Can we merge this now?

**Pull request merged**
