### PR TITLE
mugshot: update to 0.4.3.

### PR DESCRIPTION
**Pull request by machadofguilherme**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by cinerea0** [comment]
Looks like you need to rebase your commits on top of a more "fresh" branch for the CI checks to go through.

**Comment by machadofguilherme** [comment]
> Looks like you need to rebase your commits on top of a more "fresh" branch for the CI checks to go through.

How could I do this, cinerea0?

**Comment by cinerea0** [comment]
Simplest way in this case would probably be these steps:

1. `git reset HEAD~1`
2. `git pull upstream master` (or whatever you named the voidlinux/void-packages remote)
3. Re-commit the changes in this PR.
4. `git push -f origin novo-muhshot`

**Comment by machadofguilherme** [comment]
I ran the command lines you said. Thanks! I hope it works.

**Comment by ericonr** [comment]
Are you no longer interested in this PR?

**Pull request closed without merging**
