### PR TITLE
lxd: update to 4.0.0.

### PR DESCRIPTION
**Pull request by CameronNemo**
LXC 4.0.1 should be released soon, then this PR will be updated.

### CODE REVIEW

**Comment by CameronNemo** [comment]
@fosslinux I tested both LXC and LXD. I expect this PR is ready to merge.

**Comment by fosslinux** [comment]
I will test shortly.

**Comment by xtraeme** [comment]
is this ready and well (build) tested this time?

**Comment by CameronNemo** [comment]
yeah build succeeds and my runtime checks are passing

**Pull request merged**
