### PR TITLE
libvisual: update to 0.4.2.

### PR DESCRIPTION
**Pull request by Piraty**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

------

ping @hartwork

### CODE REVIEW

**Review by hartwork — COMMENTED** [review]
Hi @Piraty cool!

Regarding details:
- The patch applies to configure error output so if you make sure to note take the error path by (1) use of the right flags and (2) the dependencies being around and recent enough, the patch could in theory be dropped again (if you like).
- Some dependencies are still missing on plugins, e.g. Alsa, portaudio, pulseaudio, glu, mesa, jack, bison (rather than flex). https://github.com/Homebrew/homebrew-core/pull/126424/files may be good to compare too, though I notice that plugins should not need SDL there either…

**Comment by hartwork** [comment]
> Hi @Piraty cool!
> 
> Regarding details:
> 
>  * The patch applies to configure error output so if you make sure to note take the error path by (1) use of the right flags and (2) the dependencies being around and recent enough, the patch could in theory be dropped again (if you like).
> 
>  * Some dependencies are still missing on plugins, e.g. Alsa, portaudio, pulseaudio, glu, mesa, jack, bison (rather than flex). https://github.com/Homebrew/homebrew-core/pull/126424/files may be good to compare too, though I notice that plugins should not need SDL there either…

@Piraty any thoughts?

**Comment by Piraty** [comment]
i applied your suggestions.

omitting `autoreconf` yields
```
libtool: Version mismatch error.  This is libtool 2.4.6 Debian-2.4.6-15build2, but the
libtool: definition of this LT_INIT comes from libtool 2.4.7.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6 Debian-2.4.6-15build2
libtool: and run autoconf again.
```

**Comment by hartwork** [comment]
@Piraty what does it take to get this merged?

**Comment by Piraty** [comment]
nothing more than this gentle notification i guess.
i fixed some stuff and rebased. i'll merge if it looks good to you.

**Comment by hartwork** [comment]
@Piraty thanks a lot! :+1: :+1:

**Pull request merged**
