### PR TITLE
yarn: update to 1.22.10

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Comment by ev-ermakov** [comment]
Ok. So, should I close this pull request?

**Comment by smorimoto** [comment]
Hmm... What do you mean? You can if it means that it can be merged.

**Comment by ev-ermakov** [comment]
@smorimoto 
Oh, I'm sorry I wrote in the wrong place, that comment was for another PR (#25727).
:D

**Comment by smorimoto** [comment]
Oh I see. No worries! :)

**Pull request merged**
