### PR TITLE
build-helper/qmake: disable rpath

### PR DESCRIPTION
**Pull request by sgn**
@st3r4g Please test qjackctl.

### CODE REVIEW

**Comment by st3r4g** [comment]
Could you update qjackctl to 0.9.1 here so we save a rebuild?

**Comment by ericonr** [comment]
Ideally we should runtime test all of them... Otherwise some of them could be accidentally relying on rpath to work at all, and we wouldn't detect them.

**Comment by sgn** [comment]
> Could you update qjackctl to 0.9.1 here so we save a rebuild?

Okey.

> Ideally we should runtime test all of them... Otherwise some of them could be accidentally relying on rpath to work at all, and we wouldn't detect them.

Well, I don't use any of them, so my testing ability will be very limited.

**Comment by sgn** [comment]
Anyway, for a long time, the RPATH for cross-compiled stuff is `$XBPS_CROSS_BASE/usr/lib` and nothing breaks.

**Comment by st3r4g** [comment]
I confirm that this removes rpath from qjackctl, thus allowing it to be used with pipewire

**Pull request merged**
