### PR TITLE
New package: julius-1.6.0

### PR DESCRIPTION
**Pull request by marmeladema**

### CODE REVIEW

**Comment by ericonr** [comment]
For the musl build failures, it should be a matter of making a conditional on `$XBPS_TARGET_LIBC = musl` and adding `makedepends+=" libexecinfo-devel"`. You might need to add `-DCMAKE_C_STANDARD_LIBRARIES=-lalleg` to `configure_args` as well, but only if it doesn't work.

**Comment by marmeladema** [comment]
@ericonr thank you that helped!
It fails to link now:
```
2020-11-25T22:55:47.7362775Z /usr/bin/ld: CMakeFiles/julius.dir/src/core/backtrace.c.o: in function `backtrace_print':
2020-11-25T22:55:47.7363899Z backtrace.c:(.text+0x2a): undefined reference to `backtrace'
2020-11-25T22:55:47.7365011Z /usr/bin/ld: backtrace.c:(.text+0x36): undefined reference to `backtrace_symbols'
2020-11-25T22:55:47.7367927Z collect2: error: ld returned 1 exit status
2020-11-25T22:55:47.7377022Z make[2]: *** [CMakeFiles/julius.dir/build.make:5298: julius] Error 1
2020-11-25T22:55:47.7382123Z make[1]: *** [CMakeFiles/Makefile2:119: CMakeFiles/julius.dir/all] Error 2
2020-11-25T22:55:47.7388209Z make: *** [Makefile:160: all] Error 2
2020-11-25T22:55:47.7394853Z => ERROR: julius-1.5.1_1: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 2
2020-11-25T22:55:47.7395869Z => ERROR:   in do_build() at common/build-style/cmake.sh:88
2020-11-25T22:55:47.7803883Z ##[error]Process completed with exit code 1.
```

**Comment by ericonr** [comment]
Add the `configure` args, then.

**Comment by marmeladema** [comment]
@ericonr yeah sorry it took me some time to realize that second part could it.

**Comment by ericonr** [comment]
No problem :)

**Comment by marmeladema** [comment]
@ericonr thank you very much, it seems to have worked :+1:

**Pull request merged**
