### PR TITLE
python-Cython: add setuptools dependency

### PR DESCRIPTION
**Pull request by q66**
This is necessary to make Cython build. Not sure how it did without it before, but not bumping the revision, since it does not make a functional difference.

### CODE REVIEW

**Comment by asergi** [comment]
> This is necessary to make Cython build. Not sure how it did without it before, but not bumping the revision, since it does not make a functional difference.

To date, `setuptools` is not required to build/run `Cython`. Also, entry points and extensions need it now. Also, I see no traceback or errors here.

**Comment by q66** [comment]
It is definitely necessary to run it, since /usr/bin/cython{2,3} imports `pkg_resources`, provided by setuptools

**Comment by q66** [comment]
Check out the contents of `cython2`, for example:

```
#!/usr/bin/python2
# EASY-INSTALL-ENTRY-SCRIPT: 'Cython==0.29','console_scripts','cython'
__requires__ = 'Cython==0.29'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('Cython==0.29', 'console_scripts', 'cython')()
    )
```

**Comment by q66** [comment]
Out of interest, I looked at how Debian handles cython and why the setuptools package is not necessary, and the script looks different there:

```
#! /usr/bin/python2

#
#   Cython -- Main Program, Unix
#

from Cython.Compiler.Main import main
main(command_line = 1)
```

which means it possibly *shouldn't* be necessary to have a setuptools dependency, but the template will need fixing in some other way.

**Comment by q66** [comment]
Sadly, I don't have access to my build machine right now, so i can't test it. But if you feel like the changes are incorrect, please do revert the changes to python-Cython, and I will look into it once again.

**Comment by asergi** [comment]
> It is definitely necessary to run it, since /usr/bin/cython{2,3} imports pkg_resources, provided by setuptools

Ofc it is if you add/use `setuptools` to build the package. Rebuild without it and you'll see.

Please provide a build error or I'll revert it.

**Comment by q66** [comment]
Yes, I see that. Since we definitely want to use `distutils` instead of `setuptools` to install Cython, please revert the dependency either way - I see you have updated Cython to a new version, if it still fails at that point, I will look for a better fix.

**Pull request merged**
