### PR TITLE
linux5.4: update to 5.4.36; enable CIFS_SMB_DIRECT

### PR DESCRIPTION
**Pull request by pullmoll**
Solves #21374 for linux5.4

Builds for all target architectures still running here.

### CODE REVIEW

**Comment by pullmoll** [comment]
Tested on x86_64 and ppc (glibc). All builds succeeded, ready to merge.

**Comment by q66** [comment]
how did these changes in ppc-dotconfig happen?

**Comment by pullmoll** [comment]
I cross compiled for the targets, copied the `.config` file from the build directory and removed the `_1` for the revision because we patch it there.

**Comment by q66** [comment]
ok, just checked locally just in case, lgtm

we can't enable CIFS_SMB_DIRECT on ppc32 since it depends on CONFIG_INFINIBAND which is off

**Pull request merged**
