### PR TITLE
Remove python-asn1crypto, python3-macholib.

### PR DESCRIPTION
**Pull request by travankor**

### CODE REVIEW

**Comment by xtraeme** [comment]
why do these pkgs need to be removed? (other than being unused)

**Comment by travankor** [comment]
They don't need to be removed. They are just orphaned dependencies.
So is Void's policy never to remove?

**Comment by xtraeme** [comment]
I don't know what's the policy... but my point is that what would happen if we remove them and then later we add some sw that require them again?

**Comment by xtraeme** [comment]
My policy is only removing them if they are obsolete and unmaintained for a long time.

**Comment by travankor** [comment]
macholib is for Mac OS stuff and it wasn't need in the first place
asn1crypto is dropped since python-cryptography drops this

**Comment by travankor** [comment]
>I don't know what's the policy..
Me neither....

I actually like your approach, but when you were go no one I think people did the exact opposite...

**Comment by travankor** [comment]
closing this, but you should make this the official policy

**Comment by xtraeme** [comment]
how about onionshare changes?

**Comment by travankor** [comment]
ok, i can send that

**Pull request closed without merging**
