### PR TITLE
vscode: update to 1.69.0

### PR DESCRIPTION
**Pull request by atk**
+ take care of new tracking server

#### Testing the changes
- I tested the changes in this PR: **YES**, but one error was found: at the moment, the internal terminal does not work.

### CODE REVIEW

**Comment by atk** [comment]
@shizonic if you have any idea about the terminal, I'm currently too tired to have a closer look. Maybe tomorrow.

**Comment by cevdetardaharan** [comment]
https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch#_troubleshooting-steps

**Comment by atk** [comment]
We're currently blocked by the missing electron-18 update; using an older electron version breaks the terminal view.

**Comment by shizonic** [comment]
@atk Oh I see. Thanks for informing.

Any idea if and when electron 18 lands in the repo?

**Comment by atk** [comment]
I had opened a package request issue, but unfortunately, there's currently no one to pick it up.

**Comment by paper42** [comment]
Electron 19 is now packaged, can we use it?

**Comment by shizonic** [comment]
> Electron 19 is now packaged, can we use it?

Gonna have a look into it by tomorrow.

**Comment by atk** [comment]
I guess I beat you to it :)

And my assumption that electron13 was breaking the terminal seems to have been right, because with electron19, it works again.

**Comment by shizonic** [comment]
> I guess I beat you to it :)
> 
> And my assumption that electron13 was breaking the terminal seems to have been right, because with electron19, it works again.

Nice work, dude. Thank you!

**Comment by negativeExponent** [comment]
i'm having issue running this version of vscode (including the 1.69.0_1 on main repo). the app closes as soon as you click on File on menu bar.

**Comment by Johnnynator** [comment]
> i'm having issue running this version of vscode (including the 1.69.0_1 on main repo). the app closes as soon as you click on File on menu bar.
> 
> maybe this verbose log will help something: https://pastebin.com/A2W7TQ4S

Are you on musl or glibc?

**Comment by brxken128** [comment]
> i'm having issue running this version of vscode (including the 1.69.0_1 on main repo). the app closes as soon as you click on File on menu bar.
> 
> maybe this verbose log will help something: https://pastebin.com/A2W7TQ4S

This happens for me also, on `1.69.0_1` with glibc. In addition to this, scrolling and just about everything else is slow/sluggish and has large response times.

The context menu/text also seems to be broken with gnome `42.0_1`, although I don't know if it's limited to gnome. The bar with the blue box is supposed to be the menu bar, and clicking the first part (which I assume is the File button) will indeed crash the program. I've tried with all extensions disabled too - no dice.

image

**Pull request merged**
