### PR TITLE
element-desktop: update to 1.11.0.

### PR DESCRIPTION
**Pull request by jcgruenhage**
#### Testing the changes
- I tested the changes in this PR: **YES**

The platform support patch has been removed because it's been merged upstream in https://github.com/vector-im/element-desktop/pull/376.

I've tested this locally on x86\_64, works as expected.

### CODE REVIEW

**Comment by Johnnynator** [comment]
Can you update the PR to use electron 19.

**Comment by jcgruenhage** [comment]
@Johnnynator done

**Comment by Johnnynator** [comment]
Also needs to be changed in /[srcpkgs](https://github.com/void-linux/void-packages/tree/96637b8390e9f6adc8876c78e9f47911237f764a/srcpkgs)/[element-desktop](https://github.com/void-linux/void-packages/tree/96637b8390e9f6adc8876c78e9f47911237f764a/srcpkgs/element-desktop)/[files](https://github.com/void-linux/void-packages/tree/96637b8390e9f6adc8876c78e9f47911237f764a/srcpkgs/element-desktop/files)/element-desktop

**Comment by jcgruenhage** [comment]
... yeah. Building again and trying it out with that changed as well now

**Comment by jcgruenhage** [comment]
So, since I updated electron element is *super* slow. Extremely slow. Very much unusable...

**Comment by jcgruenhage** [comment]
To put some numbers behind that: I'm currently waiting 5 to 15 seconds for switching between chats and even typed characters don't appear right away :/

**Comment by Johnnynator** [comment]
Musl or glibc? Also how is the performance when using upstream electron?

**Comment by jcgruenhage** [comment]
glibc. How do I try it with upstream electron? Don't know much about electron sadly (or maybe not sadly? :D)

**Comment by jcgruenhage** [comment]
I've also noticed some crashes, element-desktop crashed on me for the third time now today...

**Comment by Johnnynator** [comment]
The issue is specific to our electron19, using the upstream one downloaded from https://github.com/electron/electron/releases/tag/v19.0.8 does not exhibit the same issues.

I did probably do most of my tests with a too simple Electron app.

**Comment by Johnnynator** [comment]
Can you retest with rev 2 of electron19. The issues seem to be fixed at least for me.

**Comment by jcgruenhage** [comment]
Tried with rev2, works as expected, performance problem is gone.

**Pull request merged**
