### PR TITLE
[WIP] New package: brave-1.2.41-x64

### PR DESCRIPTION
**Pull request by TheGejr**
This package provides the open source web browser based on chromium.

### CODE REVIEW

**Comment by TheGejr** [comment]
> You use build_style=fetch but does not fetch anything? Weird

I fetch in the INSTALL
`xbps-uhelper fetch "https://github.com/brave/brave-browser/releases/download/v${SVERSION}/brave-v${SVERSION}-linux-${SARCH}.zip"`

**Comment by mobinmob** [comment]
> > You use build_style=fetch but does not fetch anything? Weird
> 
> I fetch in the INSTALL
> `xbps-uhelper fetch "https://github.com/brave/brave-browser/releases/download/v${SVERSION}/brave-v${SVERSION}-linux-${SARCH}.zip"`

You do not need to do that. There are other binary repacks in the repo, they download the upstream package in the do_fetch stage/hook.

**Comment by TheGejr** [comment]
> You do not need to do that. There are other binary repacks in the repo, they download the upstream package in the do_fetch stage/hook.

Well it works ;)
I will change the package so it downloads the upstream in the hooks

**Comment by TheGejr** [comment]
@mobinmob Okay so I've finally got it working with the upstream. This looks and feels a lot better. 

**However** the package doesn't really work. It compiles and installs fine.
But I had to do `vbin "${wrksrc}/brave" && rm "${wrksrc}/brave"` which places the executable in `/usr/bin/`, but the executable `brave` needs to be in `/usr/share/brave` else it won't work. A fix to this is to do the following
```sh
mv /usr/bin/brave /usr/share/brave/
ln -sf /usr/share/brave/brave /usr/bin/brave
```
But I'm not allowed to do this in the template and if I don't `vbin` the ELF the xbps-src fails.

What can be done to fix the last issue?

**Comment by xtraeme** [comment]
Easy, make a shell script that changes directory and execs

**Comment by TheGejr** [comment]
> Easy, make a shell script that changes directory and execs

I did that and called it in `do_clean` since that's the last hook (I think?) but `xbps-src` still failed.

**Comment by xtraeme** [comment]
You are confusing what I'm saying

**Comment by xtraeme** [comment]
Anyway how people can trust such software compiled by who knows and what knows what does it do while it's working... wtf

**Comment by xtraeme** [comment]
Seriously this kind of software is a plague

**Comment by mobinmob** [comment]
@TheGejr 
Have you tried using the rpm or deb file instead of the zip? They should install into the usual paths. Take a peak at the templates for wps-office, adobe-flash-plugin, vivaldi and opera ;)

**Comment by Hoshpak** [comment]
I think we should reject this. There's no reason to allow a software that isn't needed for bootstrap reasons into the repository in binary form and for building from source, that would go against the ongoing browser moratorium.

**Comment by pullmoll** [comment]
I agree with @Hoshpak - We already decided there are more than enough browsers as derivatives of mozilla and chrome we have to maintain. Adding binary packages to the repository is also against our policy, except for the few cases where it is unavoidable to add them.

**Comment by Logarithmus** [comment]
@Hoshpak @pullmoll Why don't you consider adding either binary or source package with *restricted=yes* flag? It works well for *android-studio* for instance.
P. S. Honestly, I think we just need a more powerful build server. I'll donate for it, because it seems that build server's capacity is often the main reason to reject many PRs in this repo. See https://github.com/void-linux/void-packages/pull/5511#issuecomment-699783291 for my opinion about this situation.
P. P. S. Or maybe we should make something like AUR, but xbps-src based?

**Comment by Vaelatern** [comment]
> @Hoshpak @pullmoll Why don't you consider adding either binary or source package with _restricted=yes_ flag? It works well for _android-studio_ for instance.

See 5511.

> P. S. Honestly, I think we just need a more powerful build server. I'll donate for it, because it seems that build server's capacity is often the main reason to reject many PRs in this repo. See [#5511 (comment)](https://github.com/void-linux/void-packages/pull/5511#issuecomment-699783291) for my opinion about this situation.

#5511 is all the reasons we will not accept Brave. Thank you for linking to it.

> P. P. S. Or maybe we should make something like AUR, but xbps-src based?

No. This is an unsupported idea.

**Pull request closed without merging**
