### PR TITLE
minecraft: update to 2.1.9618.

### PR DESCRIPTION
**Pull request by SevereOverfl0w**

### CODE REVIEW

**Comment by abenson** [comment]
Can this be updated to the new latest version?

**Comment by SevereOverfl0w** [comment]
I've done the update

**Comment by Chocimier** [comment]
See #21940. I propose to remove `minecraft` as it is hack to put non-redistributable software into repo. 

cc @Vaelatern @the-maldridge

**Comment by the-maldridge** [comment]
Sounds good.  Please remove at your convenience.

**Pull request closed without merging**
