### PR TITLE
NetworkManager-strongswan: update to 1.5.2.

### PR DESCRIPTION
**Pull request by DBLouis**
I also modified a bit the `strongswan` package because authentication with EAP MS-CHAPv2 was not working.

### CODE REVIEW

**Comment by DBLouis** [comment]
I also modified a bit the `strongswan` package because authentication with EAP MS-CHAPv2 was not working.

**Comment by ericonr** [comment]
Hi! This should be one commit per package (and NetworkManager-strongswan itself has already been updated, so it will still be a single commit for the strongswan changes only).

Please explain the commit what your changes are doing.

**Comment by ericonr** [comment]
@DBLouis ping

**Comment by ericonr** [comment]
Superseded by #30642 and #30869

**Pull request closed without merging**
