### PR TITLE
nsjail: update to 3.0

### PR DESCRIPTION
**Pull request by LamaRaz**

### CODE REVIEW

**Comment by fosslinux** [comment]
1. In future, please do /not/ close an old PR and open a new PR. Just change the one PR.
2. Please squash commits.

**Comment by LamaRaz** [comment]
Don't you have this option?

https://29comwzoq712ml5vj5gf479x-wpengine.netdna-ssl.com/wp-content/uploads/2019/10/github-merge-options.png

**Comment by Chocimier** [comment]
> Don't you have this option?

We disabled all but rebase. Preparing clean git history is here job of person proposing changes, not of person accepting them.

From the fact that proposed update failed to build at first I guess you didn't build and test locally. Did you? If so, what was tested? Any issues?

**Comment by LamaRaz** [comment]
no issues with the changes to the template with xbps-src, even with the older kafel.

**Comment by LamaRaz** [comment]
xbps-src had no issues and I have no idea how to squash it. My attempt despite using HEAD~2 squashed more than was in my branch. My problem was solved, if this pull req is inadequate someone else can update nsjail at a later time and close this.

**Comment by fosslinux** [comment]
To squash:

`git rebase -i HEAD~2`

Then replace the second commit with `f` or `s` (fixup or squash).

Exit the editor and it will squash them.

https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history <-- I recommed this greatly for interactive rebase, this tutorial is made for this exact scenario when a reviewer asks you to do something :D

**Comment by LamaRaz** [comment]
Seems like it worked this time

**Comment by fosslinux** [comment]
Yep, it worked, thanks.

**Pull request merged**
