### PR TITLE
[WIP] GHC 8.10.4

### LINKED ISSUE #6414: Can't customize XMonad
### System

* xuname: Void 4.19.12_1 x86_64 GenuineIntel uptodate rrrmFFFFFF
* package: xmonad-0.15_1, xmonad-contrib-0.15_1

### Expected behavior

When below is in `~/.xmonad/xmonad.hs`, `xmonad --recompile` should give no output and successfully compile (https://hackage.haskell.org/package/xmonad-contrib-0.15/docs/XMonad-Doc-Configuring.html).

```haskell
   import XMonad

   main = xmonad $ def
       { borderWidth        = 2
       , terminal           = "urxvt"
       , normalBorderColor  = "#cccccc"
       , focusedBorderColor = "#cd8b00" }
```

Additionally, the `xmonad-contrib` package should have more files in it than just the license.

### Actual behavior

With haskell snippet above in `~/.xmonad/xmonad.hs`:

```
$ xmonad --recompile
XMonad will use ghc to recompile, because "/home/adam/.xmonad/build" does not exist.
Error detected while loading xmonad configuration file: /home/adam/.xmonad/xmonad.hs

xmonad.hs:1:1: error:
    Could not find module ‘XMonad’
    Use -v to see a list of the files searched for.
  |
1 | import XMonad
  | ^^^^^^^^^^^^^

Please check the file for errors.
```

And the files in xmonad-contrib are:

```
$ xbps-query -Rf xmonad-contrib
/usr/share/licenses/xmonad-contrib/LICENSE
```

Any ideas @xaltsc?

### Steps to reproduce the behavior

1. Install xmonad.
2. Create `~/.xmonad/xmonad.hs` with config shown above.
3. `xmonad --recompile`

### PR DESCRIPTION
**Pull request by slotThe**
It's that time of the year again!

- [X] ghc; I took over as maintainer here, @leahneukirchen said that was okay on IRC (cc'ing here to make sure)
- [ ] ghc-bin; took over as mainainer of orphaned package.
    - [X] x86_64-musl; [Link here](https://void.johnnynator.dev/distfiles/ghc-8.10.4-x86_64-void-linux-musl.tar.xz)
    cc @q66 for these
    - [ ] ppc64le
    - [ ] ppc64le-musl
- [X] cabal-install
- [X] stack
 
Rebuild literally every single haskell package we have and see if anything's broken:

- [x] git-mediate
- [x] kmonad
- [x] cgrep; took over as mainainer of orphaned package.
- [x] debug-me
- [x] hlint
- [x] hoogle
- [x] darcs
- [x] shellcheck
- [x] git-annex
- [x] hledger
- [x] pandoc
- [x] xmobar
- [x] HLS; this is #27961 once that's merged

For the following two I'd like to fix #6414 while we're at it.  Because stack can't install libraries globally, this would involve either removing these packages entirely and advising users to install them in their own [stack or cabal projects](https://github.com/xmonad/xmonad-testing), or finding a way to build them with cabal and updating ghc's data base accordingly.  This would probably use `v1` commands, as we don't want to nuke our users db if we update xmonad. Cc @xaltsc as the current maintainer and @chilledfrogs as someone who might want to tackle this (if I read the IRC discussion correctly). 

- [ ] xmonad
- [ ] xmonad-contrib

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [X] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [X] I built this PR locally for my native architecture, (ARCH-LIBC)
- [ ] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [ ] aarch64-musl
  - [ ] armv7l
  - [ ] armv6l-musl

[ci skip]

### CODE REVIEW

**Comment by leahneukirchen** [comment]
:+1: to take over.

**Comment by leahneukirchen** [comment]
If you want you can adopt pandoc too.

**Comment by mobinmob** [comment]
@slotThe Can you update shellcheck? Thanks :)

**Comment by slotThe** [comment]
Seems to have already been done in c74f45f4407575622cc3b5830edaf82834767392, I'll rebuild and then rebase. 

@q66 friendly ping for the ppc stuff :) 

If no one finds themselves for the xmonad packages I'd say we drop them.  I think installing directly via `stack` is to be preferred anyways.

**Comment by q66** [comment]
sorry, i haven't been able to get to this - i should be able to soon though, within the next two weeks.

**Comment by slotThe** [comment]
Oh, I completely forgot about this pr... 

In the meantime, stack got updated, so we should probably bump that as well.  All that's left to be done is then 

  - Bump stack
  - Check if I built `ghc-bin` correctly on i686-musl (I don't remember why I was so careful when adding this, but I suppose there were reasons)
  - Build everything for ppc (@q66)
  - Upload the binaries that need it 
  - Decide what we want to do with the xmonad packages.  I personally would be in favour of dropping them if no one steps up; installing xmonad via stack is preferable anyways, in my opinion.  The new xmonad tutorial (xmonad/xmonad/pull/278) includes instructions for getting set up with stack and I can confirm that they work on Void.

**Comment by q66** [comment]
i will be handling rust early next week, and i should be able to do ghc afterwards, so next weekend should be okay

**Comment by slotThe** [comment]
@q66 any updates?

**Comment by Johnnynator** [comment]
@slotThe your x86_64-musl distfile link is broken. (You can also reuse the one I have up here: https://void.johnnynator.dev/distfiles (ignore the aarch64 ones, ghc is kinda broken there))

**Comment by slotThe** [comment]
> @slotThe your x86_64-musl distfile link is broken. (You can also reuse the one I have up here: https://void.johnnynator.dev/distfiles (ignore the aarch64 ones, ghc is kinda broken there))

Oh, the hoster must prune links after a few months; thanks for the heads up.  I swapped out the checksum and will link to your file in the OP

**Comment by leahneukirchen** [comment]
The hoster died and his server was terminated. :'(

**Comment by slotThe** [comment]
(just a rebase)

**Comment by slotThe** [comment]
(another rebase)

@q66 do you know when you'll be getting to this?

**Comment by q66** [comment]
rust is done now, I will be getting to this next

**Pull request closed without merging**
