### PR TITLE
qtile: update to 0.24.0, python3-pywlroots-0.16: update to 0.16.6

### PR DESCRIPTION
**Pull request by ftpd**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64

### CODE REVIEW

**Comment by kaistian** [comment]
Running this on X11 x86_64 and it's working.

**Comment by ftpd** [comment]
> LGTM, running this on X11 x86_64 and it's working.

Thanks for checking and sorry for taking it for you - I was online yesterday when the new version was released, so I just made a quick PR ;-)

**Comment by kaistian** [comment]
> Thanks for checking and sorry for taking it from you - I was online yesterday when the new version was released, so I just made a quick PR ;-)

I don't mind, I think it's great that more people contributes :-)

**Comment by ftpd** [comment]
@kaistian what do you think about adding qtile-extras to the repos too?

**Comment by kaistian** [comment]
I see no reason not to, but if it will be accepted I don't know.
I don't use qtile-extra myself so I have not looked into packaging it.

**Pull request merged**
