### PR TITLE
Carla: update to 2.4.1 (with fix to non-explicit cast with Python3.10)

### PR DESCRIPTION
**Pull request by Animeshz**
Older version breaks on Python 3.10, see: falkTX/Carla#1489. PR simply bumps the version.

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (x86_64-glibc)
- [x] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [ ] aarch64-musl
  - [x] armv7l
  - [ ] armv6l-musl

### CODE REVIEW

**Comment by Animeshz** [comment]
Done! Builds in x86_64-musl, haven't tried others (I have data caps).

**Comment by ericonr** [comment]
(please remember to squash commits)

**Comment by Animeshz** [comment]
Rebased over the latest tip :+1:

**Comment by ericonr** [comment]
image

It seems to be stuck continuously loading DSP and pressing the `New` button doesn't do anything.

Also, per  #23390, this is missing the liblo dependency.

**Comment by ericonr** [comment]
> It seems to be stuck continuously loading DSP and pressing the New button doesn't do anything.

Does this happen for you? Any tips on what to investigate? I don't know if it's because I'm on musl...

**Comment by Oreo639** [comment]
> > It seems to be stuck continuously loading DSP and pressing the New button doesn't do anything.
> 
> Does this happen for you? Any tips on what to investigate? I don't know if it's because I'm on musl...

Sorry if I am missing something but `DSP load` is not for "loading DSP", but is just an indicator of how much time the last frame took over the maximum amount of time available based on the sample rate and buffer size:
https://github.com/falkTX/Carla/blob/94139f07b176a5e12c7dab2e19251401c4a1461f/source/backend/engine/CarlaEngineInternal.cpp#L717-L739
As for the "new" button. That just resets the rack. If there are no plugins/VSTs loaded, then nothing will appear:
https://github.com/falkTX/Carla/blob/25c61989de0cfe55e4ff62af002403c9acaa1bd6/source/frontend/carla_host.py#L858-L867

**Comment by ericonr** [comment]
This is why I was asking :)

Good to know it isn't broken, I will try to merge this soon.

**Pull request merged**
