### PR TITLE
geonkick: update to 2.8.0.

### PR DESCRIPTION
**Pull request by teldra**
#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (glibc-x86_64)
- [x] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [x] aarch64-musl
  - [x] armv7l
  - [x] armv6l-musl
-->

### CODE REVIEW

**Comment by teldra** [comment]
Since version 2.7.3, redkite is part of geonkick and does not use external redkite anymore: "Move Redkite GUI toolkit into the Geonkick source and integrate it in the build system (no need to install Redkite now to build Geonkick)"

While building, a tool is generated (`rkpng2c`) to convert pngs. This can not be executed when crosscompiling because it is build for target but run by host. I tried to add qemu as helper without success.
What can I do?

**Comment by ericonr** [comment]
> "Move Redkite GUI toolkit into the Geonkick source and integrate it in the build system (no need to install Redkite now to build Geonkick)"

Ironic that they got the integration wrong :/

**Comment by ericonr** [comment]
You can revert the https://github.com/iurie-sw/geonkick/commit/0ec36f4ef9b37053e0feb60937112c247ca3b310 commit, but keep only the following files:

- standalone/CMakeLists.txt
- CMakeLists.txt 
- plugin/lv2/CMakeLists.txt

**Comment by ericonr** [comment]
An upstreameable solution, given https://github.com/iurie-sw/geonkick/issues/156, might be to find which executable needs to be marked with whatever is necessary to make it use `CMAKE_CROSSCOMPILING_EMULATOR`, which is what we set with the `qemu` build helper.

**Comment by ericonr** [comment]
Given that only this package uses redkite, we can consider removing redkite and moving to only the bundled version, but idk what's preferred in this case.

**Comment by ericonr** [comment]
For a last request, would you mind trying to upstream our musl patch? There's no reason for them not to take it :)

**Comment by teldra** [comment]
Musl patch is merged upstream. Crosscompilation fix is pending.

**Comment by teldra** [comment]
Now its ready to merge!

**Comment by ericonr** [comment]
> remove: redkite-1.3.1_1 

`redkite: remove package` is preferrable, will change commit title as I merge.

**Pull request closed without merging**
