### PR TITLE
yggdrasil: update to 0.3.16.

### PR DESCRIPTION
**Pull request by whoizit**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Can you revert the service changes from c33aec8e707d49731c7b94996450d3ebb0178ce0 as well, please? Our util-linux version now includes the necessary fixes.

@jcgruenhage

**Comment by jcgruenhage** [comment]
@whoizit you've reverted too much, the logging changes should stay

**Comment by whoizit** [comment]
@jcgruenhage can u double check?

**Comment by jcgruenhage** [comment]
@whoizit yes, I double checked. You are changing logging stuff here, see: 
image
Except for that part, this PR looks good to me. Can you reduct the changes in here to just those in the template and the service run script?

**Comment by whoizit** [comment]
@jcgruenhage i'm not understand what do you mean. I've moved log/run to right place now. Correct?

**Comment by whoizit** [comment]
do you mean that I have to restore '/usr/bin/vlogger' to log/run script? But I can't find any similar script with this code in the source tree

**Comment by jcgruenhage** [comment]
ah, that's where part of this misunderstanding comes from: `/usr/bin/vlogger` was not the content, it's a symlink. See the man page of `vlogger`:

```
     If vlogger is executed as a log service for runit(8) or another
     daemontools like supervision suite it uses the service name as default
     tag.  As example if vlogger is linked to /var/service/foo/log/run it uses
     “foo” as tag and “daemon.notice” as pri.
```

Therefore, the script content you currently have there would work, but a simple symlink does achieve the same result. See https://github.com/void-linux/void-packages/blob/master/srcpkgs/caddy/files/caddy/log/run as another in tree example of how this is done in void-linux, and after a quick check, there's a handful of other examples you can find with `find -type l | grep log/run`.

**Comment by whoizit** [comment]
@jcgruenhage thanks for explanation

**Comment by jcgruenhage** [comment]
Changes looking good now, tested it, works fine on my workstation.

**Comment by ericonr** [comment]
@whoizit do you know how to squash commits? This PR should be a single one.

**Comment by jcgruenhage** [comment]
well, you squashed it now, but the commit message is off. You can fix the commit message with `git commit --amend`.

**Comment by jcgruenhage** [comment]
@ericonr can we get this merged?

**Comment by ericonr** [comment]
Updated commit message.

**Pull request merged**
