### PR TITLE
bash: stop vendoring patch

### PR DESCRIPTION
**Pull request by sgn**
- carry them along won't get us anywhere
- verify checksum for libreadline8

conflict with #23815

### CODE REVIEW

**Comment by Chocimier** [comment]
Looks ok. I would commit update separately form dropping patches. Can you also change to `version=5.0.018` and derive rest of variables from it?

**Comment by sgn** [comment]
> Looks ok. I would commit update separately form dropping patches. Can you also change to `version=5.0.018` and derive rest of variables from it?

Initially, I reluctant to derive it since it would involve bashism somewhere, and we may run with `/bin/sh` point to something else on bootstrap.

Now, I've re-read the code, I think we'll be fine since we asked for `/bin/bash` directly.

I'll change in a minute.

**Comment by fosslinux** [comment]
`xbps-src` and templates are full of a bunch of bashisms already.

**Comment by sgn** [comment]
On 2020-07-28 18:56:45-0700, fosslinux <notifications@github.com> wrote:
> `xbps-src` and templates are full of a bunch of bashisms already.

I meant bootstrapping packages, which will be run by foreign distribution/OS.

-- 
Danh

**Comment by fosslinux** [comment]
Ah, I see; although, that doesn't discount the bashisms already in xbps-src. Any foreign distribution/OS will still require bash, due to xbps-src. I don't really see any reason as a result to even bother with removing bashisms if we think xbps-src is ok on bash.

**Comment by sgn** [comment]
> Ah, I see; although, that doesn't discount the bashisms already in xbps-src. Any foreign distribution/OS will still require bash, due to xbps-src. I don't really see any reason as a result to even bother with removing bashisms if we think xbps-src is ok on bash.

Yes, hence I changed my mind

> Looks ok. I would commit update separately form dropping patches. Can you also change to `version=5.0.018` and derive rest of variables from it?

@Chocimier Anything else should be changed?

**Pull request merged**
