### PR TITLE
streamlink: update to 1.3.1

### PR DESCRIPTION
**Pull request by kartikynwa**

### CODE REVIEW

**Comment by anjandev** [comment]
@kartikynwa please delete line 7 of your template. As travis says:
`srcpkgs/streamlink/template:7: do not set pycompile_module, it is autodetected`

Before sending a pull request, it may be helpful to check if the travis check will pass on your template by using xtools' xlint on your local machine as described here: 
https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#travis

This will catch common mistakes you may have in your template.

Happy packaging!

**Comment by kartikynwa** [comment]
Fixed.

Thanks for letting me know. I got complacent. Will be more vigilant from now on.

**Comment by gbrlsnchs** [comment]
Can we merge this? `streamlink` is currently broken because of the new `mpv` version (`0.32.0`).

**Comment by gbrlsnchs** [comment]
Thanks, @xtraeme!

**Pull request merged**
