### PR TITLE
Komikku: update to 0.40.0.

### PR DESCRIPTION
**Pull request by Nathan-MV**
#### Testing the changes
- I tested the changes in this PR: **YES**

xlint, please...

https://github.com/void-linux/void-packages/pull/38235

### CODE REVIEW

**Comment by paper42** [comment]
Once again, please learn how to force push to existing branches to update this PR without closing it and opening a new one. That just spams everyone with useless notifications and the whole review history is lost.
If that happens, at least link all of the closed PRs so reviewers check the reviews there.

**Comment by Nathan-MV** [comment]
> Once again, please learn how to force push to existing branches to update this PR without closing it and opening a new one. That just spams everyone with useless notifications and the whole review history is lost. If that happens, at least link all of the closed PRs so reviewers check the reviews there.

I have that power now, don't worry, example above.

**Comment by Nathan-MV** [comment]
It appears to don't launch unless you have gnome-keyring?

**Comment by abenson** [comment]
Closed in 1cf27c7dc3b892d15be7396ea660281391d0a5de.

**Pull request closed without merging**
