### PR TITLE
sway: update to 1.2.

### PR DESCRIPTION
**Pull request by travankor**
Wayfire needs to be updated.

### CODE REVIEW

**Comment by LennyPenny** [comment]
what is wayfire needed for here?

**Comment by klardotsh** [comment]
@LennyPenny `wayfire` and `sway` both depend on `wlroots`. `sway>=1.2` depends on `wlroots>=0.7` which is incompatible with the Wayfire version Void packages. Thus, everything has to be stuck until that package gets sorted out.

**Comment by CameronNemo** [comment]
wayfire is close https://github.com/WayfireWM/wayfire/issues/285

**Comment by Wychmire** [comment]
No new release quite yet though. Hopefully soon!

**Comment by Wychmire** [comment]
Wayfire has its new release, I can bump it in a separate PR unless someone else wants to/it's bumped in this PR

[new release](https://github.com/WayfireWM/wayfire/releases/tag/0.3.0)

**Comment by Wychmire** [comment]
@travankor I updated all of wayfire's templates [here](https://github.com/Wychmire/void-packages/tree/wayfire), would probably be easier to copy from there instead of doing it again.

**Comment by travankor** [comment]
So when I build wayfire, I get this error.
```
=> ERROR: wayfire-0.3.0_1: failed to install 'wlroots-devel-0.8.1_1' dependency! (error 2)
Unable to locate 'wf-config-devel-0.3_1' in repository pool.
=> ERROR: Please see above for the real error, exiting...
```
It seems like xbps-src can't have three dashes in the keyword? I changed wf-config to wfconfig for now.

Unfortunately, `wf-shell` installs -devel headers into the main package because they use gtk-layer-shell as a git submodule. 

I haven't tested the new wlroots/sway to see if it works, but I will be able to a bit later (everything compiles locally).

Also, thanks @Wychmire!

**Comment by Wychmire** [comment]
I created a [new branch](https://github.com/Wychmire/void-packages/tree/sway) based on your fork with the only changes from yours being the use of `wf-config` over `wfconfig`. Could you try cloning it and building wayfire/wf-shell? Everything works fine on my end.

I considered putting gtk-layer-shell in it's own package but since only one package (wf-shell) uses it seemed unnecessary. If another package ends up using it it might be worth making a package with -devel.

I'm running sway 1.2 and wlroots 0.7 locally, everything is working fine. I'll update wlroots to 0.8.1 later today, and try out wayfire.

**Comment by travankor** [comment]
Hm, I can build your branch. In that case, I probably ran into some corner case that `xbps-src zap` usually cleans up (I didn't run that at the time).

I will remove that commit and push after I do some local testing.

**Comment by Wychmire** [comment]
tested on x86_64 glibc:

Wayfire runs. It's definitely buggy but I think that might just be because it's alpha software. I can't figure out how to exit alt+tab mode w/o killing Wayfire. The wobbly windows are wonderful :D

Sway 1.2 / wlroots 0.8.1  is working smoothly as well.

**Comment by travankor** [comment]
>Wayfire runs. It's definitely buggy but I think that might just be because it's alpha software. I can't figure out how to exit alt+tab mode w/o killing Wayfire. The wobbly windows are wonderful :D

Nice :)

Wayfire and Sway both run well for me too. I think this is ready to merge.

**Comment by Wychmire** [comment]
Sway, Wayfire (and deps: wf-config and wf-shell), Wlroots all build on x86_64-musl as well.

**Pull request merged**
