### PR TITLE
gitea: upgrade to 1.15.8

### PR DESCRIPTION
**Pull request by catdevnull**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture (x86_64)

### CODE REVIEW

**Comment by paper42** [comment]
>     * I tested the changes in this PR: **NO**

Please test changes before making PRs, this PR won't even build.

**Comment by catdevnull** [comment]
Sorry, thought my dumbass could just edit the version on GitHub's web editor to upgrade it but forgot about checksums. Guess it's time to setup another void-packages env..

**Comment by catdevnull** [comment]
This should work now.

**Comment by paper42** [comment]
> This should work now.

Did you runtime test this update? If yes, please update the PR description. If no, please do so and still update the PR description.

**Comment by catdevnull** [comment]
> Did you runtime test this update? If yes, please update the PR description.

Yes, I did. CI passes too. Updated.

**Pull request merged**
