### PR TITLE
Add arcanist package

### PR DESCRIPTION
**Pull request by save-buffer**
Creates arcanist package

### CODE REVIEW

**Comment by save-buffer** [comment]
One issue is that we need to make sure that php curl extension is enabled, but I didn't know how to do this.

**Comment by FollieHiyuki** [comment]
Void does not allow packages built from git. If you really want the package to be in Void repo, please ask upstream to make a release.

**Comment by kawaiiamber** [comment]
This doesn't seem to have a release yet. If they did have a release for version 1.0, it would be [here](https://github.com/phacility/arcanist/archive/v1.0.tar.gz). I would open a request to make a release.

**Comment by save-buffer** [comment]
Would an acceptable alternative be for me to fork it and mark the current tip of master as release v1.0? The arcanist maintainers don't accept PRs on GitHub, only through phabricator. In the official documentation to install it, they straight up say to clone the repository.

**Comment by kawaiiamber** [comment]
To me in sounds okay. In this case the ideal would, I guess, to request through phabricator if that's the only way they take requests.

**Pull request closed without merging**
