### PR TITLE
vscode: update to 1.56.0

### PR DESCRIPTION
**Pull request by atk**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by Johnnynator** [comment]
Pls also update the electron Version in the template to the 12 series.

**Comment by atk** [comment]
updated to electron12.

**Comment by ericonr** [comment]
I can't launch it... 

```
Warning: 'app' is not in the list of known options, but still passed to Electron/Chromium.
```

**Comment by ericonr** [comment]
Well, I think this is due to musl:

```
21864 +++ killed by SIGSEGV (core dumped) +++
21860 +++ killed by SIGSEGV (core dumped) +++
21859 +++ killed by SIGSEGV (core dumped) +++
21867 +++ killed by SIGSEGV (core dumped) +++
21866 +++ killed by SIGSEGV (core dumped) +++
21865 +++ killed by SIGSEGV (core dumped) +++
21863 +++ killed by SIGSEGV (core dumped) +++
21862 +++ killed by SIGSEGV (core dumped) +++
21861 +++ killed by SIGSEGV (core dumped) +++
21858 +++ killed by SIGSEGV (core dumped) +++
21857 +++ killed by SIGSEGV (core dumped) +++
21856 +++ killed by SIGSEGV (core dumped) +++
21855 +++ killed by SIGSEGV (core dumped) +++
21852 +++ killed by SIGSEGV (core dumped) +++
21854 <... ppoll resumed>)              = 1 ([{fd=3, revents=POLLIN|POLLHUP}])
21853 <... ppoll resumed>)              = 1 ([{fd=3, revents=POLLIN|POLLERR|POLLHUP}])
21868 +++ killed by SIGSEGV (core dumped) +++
21851 +++ killed by SIGSEGV (core dumped) +++
21854 recvmsg(3,  <unfinished ...>
21853 recvmsg(3,  <unfinished ...>
```

**Pull request merged**
