### PR TITLE
New package: v2raya-bin-1.5.8.1_1.x86_64

### PR DESCRIPTION
**Pull request by ketlrznt**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-LIBC)

### CODE REVIEW

**Comment by classabbyamp** [comment]
why not build from source, [like here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=v2raya)?

**Comment by ketlrznt** [comment]
> why not build from source, [like here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=v2raya)?

@classabbyamp v2raya-git in aur needs several npm dependencies in user host machine, which may be very slow depending on user's Internet accessibility (e.g. Chinese user). So I choose to fetch pre-buil deb file which is stored in a mirror.

**Comment by classabbyamp** [comment]
On void, users don't need to build packages from templates/sources themselves, that's what the builders do. Users would only be downloading the resulting binary package.

**Comment by ketlrznt** [comment]
> On void, users don't need to build packages from templates/sources themselves, that's what the builders do. Users would only be downloading the resulting binary package.

OK. I get your point. I will try to build it from scratch later.

Another problem is I think shipping such software in Void repository may cause legal affairs in some countries (which has Void Linux mirror). it would be better to make it "restricted" and don't distribute it, that's another reason why I choose to use binary file.

**Comment by classabbyamp** [comment]
hm well v2ray itself is already in the repos so not sure how that interacts with what you're saying

**Comment by ketlrznt** [comment]
> hm well v2ray itself is already in the repos so not sure how that interacts with what you're saying

v2ray does exist in repository, In fact I am not sure about its legality. I haven't seen a distro ships v2raya binary file in its officail repository directly. I will contact v2raya's official team to consult this question. One of its developers maintains v2raya-git / v2raya-bin in AUR. Thanks!

**Comment by ketlrznt** [comment]
I will temporarily close this pr. Thank you for reviewing!

**Pull request closed without merging**
