### PR TITLE
radicale: fixes and cleanup

### PR DESCRIPTION
**Pull request by teldra**
#### Testing the changes
- I tested the changes in this PR: **YES**
should fix https://github.com/void-linux/void-packages/issues/38923

### CODE REVIEW

**Comment by fanyx** [comment]
bump the template revision if this is no version upgrade

**Comment by teldra** [comment]
> bump the template revision if this is no version upgrade

Yes, done.

**Comment by fanyx** [comment]
@teldra can you rebase/resolve the issues here?
Would love to ping one of the maintainers to get it merged.

**Comment by fanyx** [comment]
@paper42 can you take a look?

**Comment by teldra** [comment]
Can you take a look? @classabbyamp

**Comment by classabbyamp** [comment]
why install to both /etc and /usr/share/examples?

**Comment by teldra** [comment]
> why install to both /etc and /usr/share/examples?

yes, thought about it. unnecessary redundancy.
I removed examples, because otherwise there could be user configs removed, right? @classabbyamp

**Comment by classabbyamp** [comment]
i think this solution is not right. it does not make sense to install config files as executable. i think the proper solution would be to `chown` in an `INSTALL` script, see `srcpkgs/fcron/INSTALL` for an example

**Comment by teldra** [comment]
> i think this solution is not right. it does not make sense to install config files as executable. i think the proper solution would be to `chown` in an `INSTALL` script, see `srcpkgs/fcron/INSTALL` for an example

do you think, chmod 644 is suitable?  I don't know, why I came up with 755.
after double checking, updating radicale works flawless here. (https://github.com/void-linux/void-packages/issues/38923)

**Comment by classabbyamp** [comment]
is there a reason why `rights` was installed as `640` before? if so, chowning (or chgrping) is still what I think is right, not giving everyone read access.

**Pull request closed without merging**
