### PR TITLE
pyradio: update to 0.9.2.20, disable self-update, add deps, adopt

### LINKED ISSUE #47653: pyradio needs to use new pipx install method (and not allow self-update from outside Void's repo)
### Is this a new report?

Yes

### System Info

Void 6.5.13_1 x86_64 GenuineIntel uptodate rFFFFF

### Package(s) Affected

pyradio-0.9.2.13_2

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://github.com/coderholic/pyradio/issues/211

### Expected behaviour

pyradio installed via Void's repo shouldn't allow update through non-distro source.

### Actual behaviour

1. pyradio currently automatically prompts and then tries to update and allow someone to update-install from a non-distro source.
2. pyradio now needs pipx for install so won't be able to update without that. See [packagers info](https://github.com/coderholic/pyradio/blob/master/docs/packagers-info.md)

### Steps to reproduce

1. run pyradio
2. It will prompt if there is a new version of the software. Click 'y' to update.
3. It will try to run update, but update fails.

### PR DESCRIPTION
**Pull request by chrysos349**
fixes #47653

@Eloitor 

#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86-64)

### CODE REVIEW

**Comment by Eloitor** [comment]
Great, thanks!

I don't use pyradio anymore, if you wish you can take over maintenance

**Comment by classabbyamp** [comment]
something is wrong here: https://github.com/void-linux/void-packages/actions/runs/7148570873/job/19469716576?pr=47657#step:9:19

**Comment by chrysos349** [comment]
@classabbyamp what exactly is wrong there? all check have passed. `pyradio `works as intended.

**Comment by classabbyamp** [comment]
look at the paths, there should not be a python module called build for this package

**Comment by chrysos349** [comment]
@classabbyamp i see now. Switched to `python3-pep517`. Solved. No more `build` dir.

@Eloitor i will take over the package then.

**Pull request merged**
