### PR TITLE
freecad: update to 0.19.1

### PR DESCRIPTION
**Pull request by yopito**
TODO list:
* [x] wait for official announcement
* [x] ~Embedded help does not launch (via menu help > help or F1 shortcut)~

Superseeds #29466

### CODE REVIEW

**Comment by sww1235** [comment]
Per this forum thread, we have an official release.

https://forum.freecadweb.org/viewtopic.php?f=10&t=56739

**Comment by sww1235** [comment]
And compiled assets are up on github now. It looks like it as released as it ever will be, knowing how freecad handles things like that lol.

**Comment by sww1235** [comment]
And now updated on the main website

**Comment by yopito** [comment]
thanks for tracking official release announcement.

**Launch** of offline help is still broken, although the generated qhc/qch files are fine.
There are even identical to the proposed upstream's download (https://github.com/FreeCAD/FreeCAD/releases/download/0.19.1/FreeCAD.0_19.Offline.Doc.7z).  
Looks like wrong usage of (qt)assistant or file permission on folder that prevent from creating temp file. 
I'm working on it but I don't think this prevent packaging of 0.19.1

**Comment by sww1235** [comment]
I would agree that the non working help files do not matter for upgrading to 0.19.1.

Seems like it is a combo of an upstream bug and something broken on the FC side. 

Forum thread for reference: https://forum.freecadweb.org/viewtopic.php?p=489468#p489470

**Comment by ericonr** [comment]
Tested on musl to be sure, all fine :)

**Comment by yopito** [comment]
Thanks for your time and review.
I was confident on musl since i use it ;)

**Pull request merged**
