### PR TITLE
fceux: upgrade to version 2.6.4

### PR DESCRIPTION
**Pull request by tm512**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by paper42** [comment]
commit message doesn't follow the style from CONTRIBUTING.md

**Comment by tm512** [comment]
Is this really going to be held up over a missing period? I see multiple commits in the log that use exactly the formatting that I've used. Either way, I'm not sure how to revise a commit message after a pull request is already opened. I'm guessing a force push would leave this pull request's ref dangling.

**Comment by classabbyamp** [comment]
it's not the missing period, the [format](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#committing-your-changes) is `<pkgname>: update to <version>` not `<pkgname>: upgrade to version <version>`

**Comment by tm512** [comment]
Alright, how can I change that? Do I need to close this and open a new pull request after force-pushing a revision to my fork?

**Comment by classabbyamp** [comment]
just `git commit --amend; git push --force` is enough

**Pull request merged**
