### PR TITLE
New package: systemd-boot-efistub-255.3

### PR DESCRIPTION
**Pull request by classabbyamp**
see #42566

thoroughly untested atm, but it builds the efistub

#### Testing the changes
- I tested the changes in this PR: **YES**|**briefly**|**NO**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

### CODE REVIEW

**Comment by classabbyamp** [comment]
this is _just_ the stub, which can be used by unified kernel images or other bootloaders like zfsbootmenu to boot directly.

I'm not sure if full systemd-boot would work without other systemd components, but I'm also not interested in it so I don't really care to add it.

**Comment by sonnysighedup** [comment]
Thank you @classabbyamp for doing creating this and for solving the musl-build issue!

I successfully built it locally on void-musl and used it to boot a secure-boot-enabled UEFI image of the current repository version of linux6.2.

[Sounds like this will also work with limine](https://github.com/limine-bootloader/limine/issues/256#issuecomment-1465294605) for those that want to use a separate bootloader.

**Comment by NymanMatthias** [comment]
Yes, this it does work with limine. This was on void-musl.

**Comment by 0x5c** [comment]
> Merging this without these would also make it unlikely to ever have them in the repo since maintaining two systemd templates is infeasible.

This wouldn't require a change on the package name; so if sysd-boot is ever to be added, all that needs to happen is for the template to build the whole sysd-boot and moving the current package to a subpackage.

It's only when a package name (as built) changes that things get complicated

**Comment by classabbyamp** [comment]
> I would like to ask you to reconsider.

I already decided to do it to give continuity to the tens of gummiboot users, and also because the `ukify` script seemed interesting for secure booters

**Comment by 0x5c** [comment]
> The package is named `systemd-boot-efistub`. For me, this implies that the package only includes the EFI stub out of the entire systemd-boot suite.

This isn't much relevant anymore since this PR got updated anyways, but there would not have been any snags post merge had it not been.

The only thing that can't be renamed (easily) is a built package. Where that package comes from (template of the same name, subpackage in a different template, something else outside xbps-src, etc) has no effect.

So going from a template named `systemd-boot-efistub` (that builds and packages the stub and related files) to a `systemd-boot` template (that builds and packages `systemd-boot` and subpackages the stub as `systemd-boot-efistub`) does not incur a special cost and doesn't cause a package to be renamed.
Once the packages are built the only difference is the existence of `systemd-boot`; the stub package remains the same.

**Comment by classabbyamp** [comment]
the hook as it stands is mostly wrong, i copied it from gummiboot. sysd-boot provides some utilities for interacting with the config, so it should use that instead of manually writing a conf

**Comment by junkmanner** [comment]
Only the old version, which only built the efistub builds on x86_64-musl

**Comment by classabbyamp** [comment]
what?

**Comment by classabbyamp** [comment]
this is still heavily WIP, do not expect it to work

**Comment by classabbyamp** [comment]
currently known issue: kernel-install links libsystemd

**Comment by MeganerdNL** [comment]
This would be very welcome for me, because I it enables me to use full disk encryption with LUKS2 argon2i, that is still not possible with grub (and LUKS2 is very slow anyway via github). Besides, I also like to directly boot UKI's, it's fast. I have it working on my laptop with the help mkinitcpio (not tried dracut if that's possible), but only by pulling the compiled `linuxx64.efi.stub` file from Arch (https://aur.archlinux.org/packages/efistub-standalone) and put in the right place on Void. Wonky, but it works for now.

**Comment by classabbyamp** [comment]
the gummiboot efi stub still works, you don't have to grab arch's sysd-boot one

**Comment by MeganerdNL** [comment]
> the gummiboot efi stub still works, you don't have to grab arch's sysd-boot one

Missed that, thanks.

**Pull request merged**
