### PR TITLE
Perl 5.32

### PR DESCRIPTION
**Pull request by leahneukirchen**
Pretty straight forward, I hope I bumped all packages.

All noarch are dropped.

Had to update perl-Barcode-ZBar and strip-nondeterminism due to FTBFS, perl-Pod-Parser is needed for po4a as it was dropped from core.

Tested lightly on x86_64, bootstrap on x86_64-musl and aarch64-musl.

### CODE REVIEW

**Comment by ahesford** [comment]
I've rebuilt everything for `x86_64` and `x86_64-musl` locally without issue. I'm now buiding `i686` and `aarch64*`. Will update as more archs are completed.

**Comment by ericonr** [comment]
Fun fact: I think this solved a bug that reared its head in musl 1.2.1. At least `gscan2pdf` (which is where I had noticed it) no longer hangs here. Couldn't find any relevant commits, tho.

**Comment by ahesford** [comment]
Update: all packages build for `i686` with no problem. Several packages fail to build on `aarch64` and `aarch64-musl` (the set is identical on both architectures) that are not nocross and do not at first glance appear to have arch restrictions. Some of these may have dependencies that are not expected to build on `aarch64*`, but I haven't yet verified them:

- [ ] gvim-huge
- [ ] kvirc
- [ ] libmagick-perl
- [ ] libmagick6-perl
- [ ] perl-Goo-Canvas
- [ ] perl-Gtk2-ImageView
- [ ] perl-Gtk2-Notify
- [ ] postgresql-plperl
- [ ] postgresql-plpython
- [ ] postgresql-pltcl
- [ ] postgresql12-plperl
- [ ] postgresql12-plpython
- [ ] postgresql12-pltcl
- [ ] postgresql13-plperl
- [ ] postgresql13-plpython
- [ ] postgresql13-pltcl
- [ ] vim-huge
- [ ] vim-huge-python3

**Comment by ahesford** [comment]
Rebuilt everything for `armv{6,7}l{,-musl}` and the list of packages is identical to that for `aarch64`. Thus we only have to worry about cross-compiling the unchecked packages in my earlier update.

**Comment by leahneukirchen** [comment]
I'll look into it, thx.

**Comment by leahneukirchen** [comment]
kvirc builds here:

```
index: added `kvirc-5.0.0_5' (aarch64-musl).
```

The Gtk2 things have relocation issues indeed...

**Comment by ahesford** [comment]
Strange. When I try to build kvirc as is, it fails because it tries to run the the target perl. If I add `hostmakedepends=perl`, it gets much further, but eventually fails (at least for armv6l) because it is trying to set `-mtune=generic` and the tool chain apparently doesn't like that. I'll have to look more closely.

**Comment by leahneukirchen** [comment]
Ok, the Gtk2 packages should be nocross as it tries to load the library it just built. Also, they are leaf packages not used anywhere, so no loss (and never built before).

**Comment by ericonr** [comment]
> Also, they are leaf packages not used anywhere, so no loss (and never built before).

Could we just remove them?

**Comment by ahesford** [comment]
I can't crack the kvirc issue and don't really care about it too much. If we want to keep this package, I'd say give it a shot on the builders and, if it fails on cross like I see, make perl a build option that is only enabled by default for cross builds.

**Comment by leahneukirchen** [comment]
Ok, then shall we merge this?

**Comment by ahesford** [comment]
Fine by me, I've only build tested the other archs but can confirm that
zfsbootmenu seems to work, which is the most perl-intensive program I
have installed.

**Comment by ericonr** [comment]
Could pull #25940 into this?

**Comment by leahneukirchen** [comment]
More work than rebasing later.

**Pull request merged**
