### PR TITLE
owncloudclient: update to 2.5.1.10973.

### PR DESCRIPTION
**Pull request by Follpvosten**
It looks like the version number includes a build number now. Don't know if I should that write to a different variable to keep the two-dot version number.

### CODE REVIEW

**Comment by Cogitri** [comment]
Please do not merge this, see #4453. It breaks nextcloud synching.

**Comment by Follpvosten** [comment]
Oh, alright - what exactly doesn't work/breaks? I've installed the updated package on my local machine, it didn't give any error messages on start and seemingly worked fine

**Comment by Cogitri** [comment]
From the PR I've linked:

> See: owncloud/client#6791

v2.5.0 of owncloudclient doesn't support Nextcloud instances properly. Nextcloud's new client (https://github.com/nextcloud/desktop) didn't have a non-rc release yet and doesn't build with libressl 2.8.x yet.

**Comment by Follpvosten** [comment]
Alright, thanks. Maybe it works fine for me because I have Nextcloud 14.0.4. I'll downgrade the package anyways for now.

**Comment by Cogitri** [comment]
Huh? It works fine? Well, I guess I'll have to test it again then, but it seems like Owncloud's stance hasn't changed: They won't support Nextcloud installs.

**Comment by Cogitri** [comment]
screenshot from 2019-01-05 14-04-35

**Comment by Follpvosten** [comment]
Alright, I didn't get the update to 15 yet.

image

**Comment by maxice8** [comment]
Can't be merged due to breaking nextcloudclient users.

**Pull request closed without merging**
