### PR TITLE
[WIP] zfs: update to 0.7.13.

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by Cogitri** [comment]
Testing right now, mind testing too, @Vaelatern?

**Comment by Cogitri** [comment]
Also not quite sure what we said we wanted to go with for the installed tests in /usr/share?

**Comment by Cogitri** [comment]
Oh, #7643, Github search being mediocre again

**Comment by Vaelatern** [comment]
lgtm, I'm a bit busy for testing right now, but the release looks to not be dangerous, so I'll trust your testing.

**Comment by Cogitri** [comment]
Alright, writing this from Linux 4.20, so that appears to be working. Working on the tests right now.

**Comment by Cogitri** [comment]
The test binaries are installed to /usr/libexec now, the non-elf scripts installed into /usr/share. Seems to work for me as of now.

**Comment by Vaelatern** [comment]
Please upstream the patch. I'd rather merge without the fix, since it adds incidental template complexity.

**Comment by Vaelatern** [comment]
(So: upstream the patch, and we'll merge just the update to zfs. ZFS upstream will be responsive.)

**Comment by Cogitri** [comment]
Sure. Should we just remove the tests for the time being then?

**Comment by Vaelatern** [comment]
Agreed, just remove the tests in the meanwhile, with a comment explaining the line should be removed.

**Comment by Cogitri** [comment]
Okie 👍

**Comment by Cogitri** [comment]
Pushed new version.

**Comment by Vaelatern** [comment]
Any link to the patch submitted upstream?

**Comment by Cogitri** [comment]
Will post it here once I get to make the PR, should be done later today

**Pull request merged**
