### PR TITLE
Carla: add patch for gcc 9

### PR DESCRIPTION
**Pull request by sgn**

### CODE REVIEW

**Comment by Chocimier** [comment]
Package lacks python files, is it ok?

**Comment by sgn** [comment]
On 2020-01-30 09:49:29-0800, Piotr <notifications@github.com> wrote:
> Package lacks python files, is it ok?

Python files are located inside `/usr/share/carla`, as same as before.
It's declared in the template, `pycompile_dirs=usr/share/carla`

-- 
Danh

**Comment by Chocimier** [comment]
There isn't even /usr/share, see travis log.

**Comment by sgn** [comment]
> There isn't even /usr/share, see travis log.

Well, it does show up on x86_64-musl build,
see https://api.travis-ci.org/v3/job/643903206/log.txt

Since I only built for x86_64-musl in my local machine,
I haven't detect this earlier, I will look into a fix later.

**Comment by sgn** [comment]
On 2020-01-31 12:00:21-0800, Piotr <notifications@github.com> wrote:
> There isn't even /usr/share, see travis log.

I fixed that problem, turn out it needs which to detect that
compilation script.

And the cross-compiled packages missed /usr/share from very begining,
since python3-PyQt5-devel-tools should be in the hostdepends

I bumped the revision to trigger the rebuild to correct it.

-- 
Danh

**Comment by Chocimier** [comment]
Needs `which` in runtime too, please add it to depends.

Adjust pycompile_version. Pycompile_module controls compilation of files in site-packages, but there are no in package, so no need to set.

Test without -n is preferred here.

**Comment by sgn** [comment]
On 2020-02-03 12:12:58-0800, Piotr <notifications@github.com> wrote:
> Needs `which` in runtime too, please add it to depends.

OK, /usr/bin/carla requires which, damn.
> 
> Adjust pycompile_version. Pycompile_module controls compilation of
> files in site-packages, but there are no in package, so no need to
> set.

IIUC, remove pycompile_module, and set pycompile_version=$py_ver?
> 
> Test without -n is preferred here.

It was added to trigger travis build before,
I'll remove it.

-- 
Danh

**Comment by Chocimier** [comment]
Yes, use **py3_ver**, and remove pycompile_module. Looks good beside those.

**Pull request merged**
