### PR TITLE
New package: giti-1.0.0

### PR DESCRIPTION
**Pull request by LinArcX**
Permanent observer of your git directories:
https://github.com/LinArcX/giti

### CODE REVIEW

**Comment by Piraty** [comment]
aren't there yet enough and more capable git GUIs in the repositories ?

**Comment by LinArcX** [comment]
Which applications?

**Comment by Piraty** [comment]
git-gui, gitg, giggle, qgit, git-cola

**Comment by LinArcX** [comment]
Seems you didn't read[ this README](https://github.com/LinArcX/giti/blob/master/README.md).

Giti is not a gui for doing normal things that you can do with git too. The main purpose behind it is to monitor your git based directories and report you through notifications.

Edit: I forgot to say that giti is the descendant of [captain-ballard ](https://github.com/LinArcX/captain-ballard) that is already in [repo](https://github.com/void-linux/void-packages/blob/a7026a8c8cc4d8ca2ef1e9a6436849f0c779b2f3/srcpkgs/captain-ballard/template).

**Comment by hoomanist** [comment]
i agree i seen the code it could be completely useful

**Comment by Piraty** [comment]
please open a PR to remove captain-ballard in this case

**Pull request merged**
