### PR TITLE
fwupd: update to 1.8.8.

### PR DESCRIPTION
**Pull request by dataCobra**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-musl (crossbuild)
  - x86_64-musl (crossbuild)

### CODE REVIEW

**Comment by dkwo** [comment]
it seems 1.8.7 is out

**Comment by dataCobra** [comment]
> it seems 1.8.7 is out

I've pushed the new version 1.8.7. :+1:

**Review by paper42 — COMMENTED** [review]
from the configure log:
```
DEPRECATION: Option 'supported_build' value 'true' is replaced by 'enabled'
DEPRECATION: Option 'consolekit' value 'false' is replaced by 'disabled'
DEPRECATION: Option 'systemd' value 'false' is replaced by 'disabled'
DEPRECATION: Option 'elogind' value 'true' is replaced by 'enabled'
DEPRECATION: Option 'introspection' value 'true' is replaced by 'enabled'
```

**Comment by dataCobra** [comment]
> from the configure log:
> 
> ```
> DEPRECATION: Option 'supported_build' value 'true' is replaced by 'enabled'
> DEPRECATION: Option 'consolekit' value 'false' is replaced by 'disabled'
> DEPRECATION: Option 'systemd' value 'false' is replaced by 'disabled'
> DEPRECATION: Option 'elogind' value 'true' is replaced by 'enabled'
> DEPRECATION: Option 'introspection' value 'true' is replaced by 'enabled'
> ```

I've changed the replaced the values accordingly, but now meson fails...
```
The Meson build system
Version: 0.64.0
Source dir: /builddir/fwupd-1.8.7
Build dir: /builddir/fwupd-1.8.7/build
Build type: native build

meson.build:1:0: ERROR: Value disabled is not boolean (true or false).

A full log can be found at /builddir/fwupd-1.8.7/build/meson-logs/meson-log.txt
```

**Comment by dataCobra** [comment]
> from the configure log:
> 
> ```
> DEPRECATION: Option 'supported_build' value 'true' is replaced by 'enabled'
> DEPRECATION: Option 'consolekit' value 'false' is replaced by 'disabled'
> DEPRECATION: Option 'systemd' value 'false' is replaced by 'disabled'
> DEPRECATION: Option 'elogind' value 'true' is replaced by 'enabled'
> DEPRECATION: Option 'introspection' value 'true' is replaced by 'enabled'
> ```

I've replaced the values so the deprecation warning are gone.

While looking at the fwupd-efi repository I found out that we are missing an option for fwupd. According to the README, `-Defi_binary=false` should be set for fwupd versions 1.6.x and newer.

And at last I've added the bash completion files which got not installed before.

**Comment by dkwo** [comment]
it seems we now have umockdev, so we could run tests:
```
diff --git a/srcpkgs/fwupd/template b/srcpkgs/fwupd/template
index 115543195a..08b397ae61 100644
--- a/srcpkgs/fwupd/template
+++ b/srcpkgs/fwupd/template
@@ -6,7 +6,7 @@ build_style=meson
 build_helper="gir"
 configure_args="-Dsupported_build=enabled -Dconsolekit=disabled
  -Dsystemd=disabled -Delogind=enabled -Dintrospection=enabled
- -Dtests=false -Defi_binary=false"
+ -Dtests=true -Defi_binary=false"
 # tests require unpackaged umockdev
 hostmakedepends="dejavu-fonts-ttf gnutls-tools pkg-config gcab gi-docgen vala
  glib-devel polkit gettext pango python3-gobject python3-Pillow
@@ -15,6 +15,7 @@ makedepends="libxmlb-devel cairo-devel colord-devel libarchive-devel
  gnutls-devel gpgme-devel json-glib-devel libgusb-devel polkit-devel
  sqlite-devel gcab-devel pango-devel elogind-devel
  tpm2-tss-devel libjcat-devel libcurl-devel protobuf-c-devel"
+checkdepends="umockdev"
 depends="dbus udisks2"
 conf_files="
  /etc/fwupd/*.conf
```

**Comment by dkwo** [comment]
they all pass on my x86_64-musl

**Comment by paper42** [comment]
@dataCobra github can not detect the commit is from you, do you have the commit email added to your github profile?

**Comment by dataCobra** [comment]
> @dataCobra github can not detect the commit is from you, do you have the commit email added to your github profile?

Thank you for the info. I forgot to setup my env on this laptop. Fixed and pushed! :+1:

**Comment by dataCobra** [comment]
The version 1.8.8 is out and I've build it successful.

When the checks pass this PR should be good to go. :+1:

**Pull request merged**
