### PR TITLE
cross-arm-none-eabi : Use exactly the same build recipe as the offici…

### PR DESCRIPTION
**Pull request by teajay-fr**
…al arm toolchain

With this patch, the void build of the arm embedded processor cross
matches the same version as the currently official gcc version 7.3.1.
The arm provided patches are applied and the build recipes match.

This fixes issue 4931 and 1824

### CODE REVIEW

**Comment by jnbr** [comment]
Vendoring a massive patch like this one is not really an option.
Is there a source for the patch?

**Comment by teajay-fr** [comment]
Well I could rework the build to use the tar package provided by arm. That would avoid the patch. The outcome should be the same.
Should I reword this package in this direction ?

**Comment by jnbr** [comment]
Yes, this would be better. Is there a reason why this patch isn't upstream?

**Comment by teajay-fr** [comment]
There are some parts that come upstream but I don't know exactly why arm and the gcc team choose to go this way. As far as I understand arm provides a specific distribution of gcc which follows the gcc developments. I'm not into the details so I can't say much more. I'll look into eliminating the required patch and build the toolchain from the arm provided package.

**Comment by sirikid** [comment]
@pullmoll @jnbr I suppose this PR can be closed now, since cross-arm-none-eabi has already been fixed in #11571

**Pull request closed without merging**
