### PR TITLE
vscode: update to 1.31.0.

### PR DESCRIPTION
**Pull request by shizonic**

### CODE REVIEW

**Comment by maxice8** [comment]
Please add [ci skip] the same error always happens

**Comment by shizonic** [comment]
Sorry, didn't know ci_skip. Will fix that. Thanks!

**Comment by shizonic** [comment]
Just had a look into the manual but couldn't find anything related to ci skip. So how do I add this?

**Comment by maxice8** [comment]
https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build

**Comment by shizonic** [comment]
Thanks!

**Pull request merged**
