### PR TITLE
med: update to 4.0.0.

### PR DESCRIPTION
**Pull request by Chocimier**
Few tests fail on musl.
@Piraty

### CODE REVIEW

**Comment by Chocimier** [comment]
>   * what tests exactly fail on musl?
```
make[6]: Leaving directory '/builddir/med-4.0.0/tests/f/2.3.6'
make  check-TESTS
make[6]: Entering directory '/builddir/med-4.0.0/tests/f/2.3.6'
PASS: test1.sh
PASS: test2.sh
PASS: test4.sh
PASS: test6.sh
PASS: test8.sh
./test10.sh: line 19: 10557 Segmentation fault      ${EXECDIR}/${file} > /dev/null 2>&1
FAIL: test10.sh
PASS: test12.sh
PASS: test14.sh
PASS: test16.sh
PASS: test18.sh
PASS: test19.sh
FAIL: test20.sh
PASS: test21.sh
PASS: test23.sh
PASS: test25.sh
PASS: test27.sh
PASS: test29.sh
PASS: test31.sh
PASS: test3.sh
PASS: test22.sh
PASS: test24.sh
PASS: test26.sh
PASS: test28.sh
PASS: test32.sh
PASS: test33.sh
PASS: test5.sh
PASS: test7.sh
./test9.sh: line 1: 11136 Segmentation fault      ${EXECDIR}/test9 > /dev/null 2>&1
FAIL: test9.sh
FAIL: test11.sh
PASS: test13.sh
PASS: test15.sh
PASS: test17.sh
PASS: test30.sh
====================================
4 of 33 tests failed
Please report to eric.fayolle@edf.fr
====================================
make[6]: *** [Makefile:1089: check-TESTS] Error 1
make[6]: Leaving directory '/builddir/med-4.0.0/tests/f/2.3.6'
```

>   * |nocross|? sure, hdf5 is. but is med per se too?

Can't check. I was told by maxice to mark nocross in such cases.

>   * you can also drop hdf5-18 (because it was made for the old med <https://github.com/voidlinux/void-packages/issues/13621>)

I see current removal procedure faulty. #6443

**Comment by maxice8** [comment]
> maxice

don't forget the 8, the 8 is very important.

the nocross is because the builder will try in vain to build the package. This should be solved by dxpb

**Comment by maxice8** [comment]
ping

**Comment by Chocimier** [comment]
rebased, tests still fail, not a blocker imo

**Comment by yopito** [comment]
@Chocimier : did not see your PR, sorry.  Just opened PR #8909 that includes this work

**Comment by Chocimier** [comment]
@yopito: no problem

**Pull request closed without merging**
