### PR TITLE
seriespl: remove

### PR DESCRIPTION
**Pull request by teldra**

### CODE REVIEW

**Comment by maxice8** [comment]
`seriespl: remove`

**Comment by maxice8** [comment]
`remove` not `removed`

same way we use `update to VERSION` not `updated to VERSION`

**Comment by maxice8** [comment]
Looking at their GitHub it seems most stuff works except that upstream is inactive and one of the websites doesn't work

**Comment by teldra** [comment]
I wrote to dev and he says, he is not interested in further working on it. (Mainly because of captchas.)

**Comment by maxice8** [comment]
On Fri, Dec 07, 2018 at 03:09:37PM +0000, Teldra wrote:
> I wrote to dev and he says, he is not interested in further working on it. (Mainly because of captchas.)
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/5460#issuecomment-445261389

I see

**Pull request merged**
