### PR TITLE
go: update to 1.13.1.

### PR DESCRIPTION
**Pull request by nilium**

### CODE REVIEW

**Comment by nilium** [comment]
Related issue for the i686 failure: golang/go#33977

**Comment by nilium** [comment]
Given that the bug probably isn't going to be fixed until at least a 1.13.1, should we just mark Go as broken if building on i686?

**Comment by the-maldridge** [comment]
This seems reasonable, I'd hoped for 1.13.1 a bit sooner though...

**Comment by ggordan** [comment]
Considering the build is no longer failing, is there still an issue with merging this?

**Comment by calebcase** [comment]
https://groups.google.com/forum/#!topic/golang-dev/VfAcPfryEMY
1.13.1 should be out tomorrow.

**Comment by nilium** [comment]
Doesn’t look like it’ll resolve the i686 issue, unfortunately.

**Comment by nilium** [comment]
This PR now targets Go 1.13.1.

**Comment by nilium** [comment]
The PR has been updated with the patch for the i686 issue. This fails to build in Travis but succeeds both on i686 hardware and in a 32-bit VirtualBox VM (ran stdlib tests on the latter to check behavior), so I'm attributing the failure to Travis resource limits for the time being.

**Pull request closed without merging**
