### PR TITLE
New package: lexbor-0.4.0

### LINKED ISSUE #17001: Package request: lexbor
Web browser engine library with no extra dependencies:

https://github.com/lexbor/lexbor

### PR DESCRIPTION
**Pull request by ndowens**
Closes #17001

Signed-off-by: Nathan Owens <ndowens04@gmail.com>

### CODE REVIEW

**Comment by LinArcX** [comment]
Thank you so much, but there are two points that i want to mention:
1- when you build lexbor from source, it generate multiple .so files:

    liblexbor-core.so
    liblexbor-css.so
    liblexbor-dom.so
    liblexbor-encoding.so
    liblexbor-html.so
    liblexbor-ns.so
    liblexbor-tag.so
    liblexbor-utils.so
    But in your package, just liblexbor.so added to shlibs files.

2- I'm using this lib with cmake for my project. in cmake you can specify libs via pkg-config. but it can't find lexbor:
pkg-config --list-all | grep lexbor

**Comment by ndowens** [comment]
> Thank you so much, but there are two points that i want to mention:
> 1- when you build lexbor from source, it generate multiple **.so** files:
> 
> ```
> liblexbor-core.so
> liblexbor-css.so
> liblexbor-dom.so
> liblexbor-encoding.so
> liblexbor-html.so
> liblexbor-ns.so
> liblexbor-tag.so
> liblexbor-utils.so
> ```
> 
> But in your package, just **liblexbor.so** added to **shlibs** files.
> 
> 2- I'm using this lib with cmake for my project. in cmake you can specify libs via pkg-config. but it can't find lexbor:
> 
> `pkg-config --list-all | grep lexbor`

As far as I know, pkg-config works with .pc(pkgconfig files), but this project doesn't get generated with one. Also I didn't enable separate library build

**Comment by ndowens** [comment]
@LinArcX  I added pkg-config support, though this if my first time of writing one, could you test this and see if it works?

**Comment by LinArcX** [comment]
I installed __lexbor__ and __liblexbor__devel. Second package had __.pc__ file.
And also I'm using cmake, it can find __lexbor__ via __pkg-config__, but seems it can't find the __.so__files related to __liblexbor-dom.so__:

https://gist.github.com/LinArcX/1ebf25acd2edaced36318042534bc9ab

**Comment by ndowens** [comment]
> I installed `lexbor` and `liblexbor-devel`. Second package had a **.pc** file.(That is what i want)
> And also I'm using cmake, it can find `lexbor` via `pkg-config`, but seems it can't find the **.so** files related to **liblexbor-dom.so** and **liblexbor-html.so**.
> 
> I created a test project:
> https://github.com/LinArcX/mgr
> 
> And this is the output of cmake:
> https://gist.github.com/LinArcX/1ebf25acd2edaced36318042534bc9ab
> 
> ~So i think if you add those **.so** files that i mentioned in previous comment, this issue will fix too.~

Ok. Will try separating modules, it will be later today before I can start back on it

**Comment by ndowens** [comment]
I retried it myself, and I figured out what it is, the make file isn't adding LDFLAGS. On the test project, I did a PR on it, so you can see it works.

**Comment by LinArcX** [comment]
I found a solution that doesn't need even path for pkg-config:
https://github.com/LinArcX/mgr/pull/1#issuecomment-561533782
And now everything works like a charm.

**Pull request closed without merging**
