### PR TITLE
wayland: update to 1.20.0.

### PR DESCRIPTION
**Pull request by ifreund**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by ericonr** [comment]
https://bugs.gentoo.org/811840 this is slightly concerning, any idea what's going on there?

**Comment by ericonr** [comment]
That's an old bug, actually. But I saw some chatter in Alpine IRC about wayland update making things not build.

**Comment by ifreund** [comment]
There's currently discussion in #wayland on oftc regarding undefined references to `wl_proxy_marshal_flags()` started by alpine people. Marking this as a draft till we know what's up.

**Comment by ifreund** [comment]
TLDR; it's firefox's fault:
```
20:00 <alextee> ah ok cool, thanks!
20:03 <Ariadne> in alpine, a contributor submitted a package update for the latest wayland version (1.20.0), and now we are having a lot of problems with wl_proxy_marshal_flags missing.
20:03 <Ariadne> we upgraded wayland-protocols already
20:03 <Ariadne> am i missing something?
20:04 --> ikke (~kevin@ikke.user.oftc.net) has joined #wayland
20:07 <emersion> hmm
20:07 <emersion> Ariadne: what kind of issues? do you have an error message at hand?
20:07 <vyivel> undefined references to `wl_proxy_marshal_flags'
20:07 <emersion> when running clients compiled with an older version?
20:08 <ikke> https://build.alpinelinux.org/buildlogs/build-edge-aarch64/community/firefox-esr/firefox-esr-91.4.0-r0.log
20:08 <emersion> or the other way around?
20:08 <emersion> ah when compiling then?
20:08 <ikke> yes
20:09 <Ariadne> gentoo also appears to have this issue
20:09 <ikke> https://bugs.gentoo.org/811840
20:09 <ikke> Their solution was to set LDFLAGS -lwayland
20:09 <Ariadne> hmm, that would indicate that something is no longer pulling -lwayland into the linking flags
20:10 <Ariadne> have you checked the wayland .pc files yet?
20:10 <ikke> -lwayland-client
20:11 <ikke> "Now normally I would just look for a source file to patch where I could add #include <wayland-client> but the file in question seems to be Unified_cpp_gfx_gl0.cpp which is generated-on-the-fly rather than being part of the firefox tarball ..."
20:12 <emersion> libwayland.so doesn't exist…
20:12 <emersion> there's only libwayland-server.so and libwayland-client.so
20:12 <emersion> so i'm a bit surprised -lwayland fixes it
20:12 <ikke> emersion: yeah, I meant -lwayland-client
20:12 <emersion> ah ok
20:15 <emersion> i see the symbol in the so, fwiw
20:15 <emersion> 155: 000000000003e540  1231 FUNC    GLOBAL DEFAULT   12 wl_proxy_marshal_flags
21:02 -- irc: disconnected from server
21:02 --> ifreund (ifreund@94.79.138.86) has joined #wayland
20:18 <emersion> rebuilding wayland-protocols won't help, it's just a bunch of XML files
20:18 <emersion> by any chance, does firefox bundle its own libwayland?
20:20 <emersion> using wayland-scanner 1.20 and linking to libwayland < 1.20 would result in this error
20:23 <emersion> does this only happen with firefox, or also with other packages?
20:35 <emersion> searching for wayland-client in the firefox tree, i don't ever see it looked up…
20:35 <emersion> https://searchfox.org/mozilla-central/search?q=wayland-client&path=
20:36 <emersion> wtf is this https://searchfox.org/mozilla-central/source/widget/gtk/mozwayland/mozwayland.h
20:37 <emersion> let me guess… dlopen shenanigans, and these are placeholders?
20:37 <vyivel> "Wayland compatibility header, it makes Firefox build with wayland-1.2 and Gtk+ 3.10."
20:37  * emersion regrets looking into this, can't unsee now
20:38 <jadahl> emersion: I suggest you to not look at very similar dlopen magic in sdl then
20:38 <vyivel> "Those strucures[sic] are just placeholders and will be replaced by real symbols from libwayland during run-time linking. We need to make them explicitly visible."
20:38 <emersion> ;_;
20:38 <vyivel> why firefox
20:39 <jadahl> because it might need to run on a system without libwayland-client.so
20:39 <emersion> … this isn't how you do software
20:39 <emersion> anyways
20:40 <emersion> maybe adding the missing wl_proxy_marshal_flags prototype in this file might help then
20:40 <emersion> maybe try this Ariadne?
20:40 <emersion> cc ikke as well
20:40 <bl4ckb0ne> why run time link? cant this be done properly?
20:40 <zubzub> does this mean chromium is the only real browser left now? :p
20:40 <vyivel> *a placeholder to https://searchfox.org/mozilla-central/source/widget/gtk/mozwayland/mozwayland.c, i think
20:41 <emersion> yeah that should make the linker happy
20:41 <emersion> hm
20:41 <emersion> but then how will it run on systems with libwayland 1.19
20:41 <emersion> yikes
20:42 <emersion> at this point, not my problem :P
20:46 <emersion> kennylevinsen: ^ a new item to add to your collection of firefox "fun facts"
20:47 <ikke> so const struct wl_interface wl_proxy_marshal_flags;?
20:48 <vyivel> isn't it a function?
20:48 <emersion> yeah, steal it from /usr/include/wayland-client.h
20:48 <emersion> well
20:48 <emersion> and like the rest, add a dummy function body
20:49 <emersion> like this https://paste.sr.ht/~emersion/b191d5216175c9ea5aeb9afe5e813fd79e654ecf
20:50 <ikke> lol@filename
```

**Comment by vyivel** [comment]
So, can this be merged then?

**Comment by ericonr** [comment]
It being Firefox's fault or not, we still need to fix Firefox before we can merge it, unless the fix is guaranteed to come with a new -esr release.

**Comment by novakne** [comment]
Looks like a fix have been merged, only for the next release though if I understand correctly https://bugzilla.mozilla.org/show_bug.cgi?id=1745560

**Comment by ericonr** [comment]
https://github.com/libsdl-org/SDL/commit/e2ade2bfc46d915cd306c63c830b81d800b2575f I tried applying this to an update, but it broke when building with current libwayland. So another package to fix for this update.

**Comment by ifreund** [comment]
@ericonr I think this can be merged, I've update SDL2 to a just release version that is compatible with wayland 1.20.0 and firefox has merged the fix linked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1745560.

If you like I can backport the firefox patch for `firefox` and `firefox-esr`, but I don't really want to trigger rebuilds for them unnecessarily.

**Comment by ifreund** [comment]
Firefox 96 has been released and includes the fix for the build issue. Firefox ESR hasn't been released since the fix was merged to the 91 ESR branch though.

**Comment by notthewave** [comment]
ESR had a new release "91.5.1". Maybe relevant changes have been included.

**Comment by novakne** [comment]
Seems like it will be in 91.6.0 https://hg.mozilla.org/releases/mozilla-esr91/rev/2ed1b3cb869bc6191bf306bab467ea42c3908c03

**Comment by notthewave** [comment]
firefox-esr 91.6.0 is out and the relevant change has been included.

**Comment by KSPAtlas** [comment]
Seems ready to merge then! Once this merges this should help with getting wlroots updated, which would cause all wlroots-based compositors to get updated!

**Comment by paper42** [comment]
> Seems ready to merge then! Once this merges this should help with getting wlroots updated, which would cause all wlroots-based compositors to get updated!

When #35711 is merged, this should be ready, it's not ready now.

**Comment by motorto** [comment]
@paper42 #35711  got merged !!!

**Comment by KSPAtlas** [comment]
Time to merge then

**Comment by tibequadorian** [comment]
@KSPAtlas these comments don't help

**Pull request merged**
