### PR TITLE
zfs: fix linux-4.20 compat

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by Cogitri** [comment]
Usually I'd just wait for upstream to release 0.7.13, but since compat with 0.4.20 is rather trivial I feel like we can just revbump 0.7.12 for now.

**Comment by Vaelatern** [comment]
Not for this.

**Comment by Vaelatern** [comment]
ZFS has enough moving parts I don't dare change things out of lockstep, and the costs for zfs not working are high.

**Comment by Cogitri** [comment]
Alright.

**Pull request closed without merging**
