### PR TITLE
New package: sublime-merge-1075

### PR DESCRIPTION
**Pull request by noblehelm**

### CODE REVIEW

**Comment by Hoshpak** [comment]
Is this redistributable? I couldn't find a license file anywhere.

**Comment by noblehelm** [comment]
It has the same license style of Sublime Text, that is unlimited evaluation for free, but it requires a license purchase. In the sublime-text3 template, its license is stated as 'proprietary' and it goes into the 'nonfree' repository, so I did the same for this.

**Comment by noblehelm** [comment]
Fixed the `sed` command. Also, a new version came out, should I update in this PR or wait until it is (maybe) merged to open a new PR with the update?

**Comment by Johnnynator** [comment]
@noblehelm You can update this PR to use the latest release. Keep it as one commit.

**Comment by noblehelm** [comment]
Updated to version `1075`.

**Pull request merged**
