### PR TITLE
New package: libglvnd-1.1.1

### PR DESCRIPTION
**Pull request by yshui**

### CODE REVIEW

**Comment by Hoshpak** [comment]
glvnd was submitted and rejected before because it didn't work on musl at the time. Has this changed?

**Comment by maxice8** [comment]
It might work this time with the new stack size changes by @Gottox . Regardless if you're gonna introduce libglvnd you will need to make extensive adaptations to LibGL as well

**Comment by yshui** [comment]
@maxice8 @Hoshpak But can the library itself get in at least? Adapting libGL can happen later

**Comment by xtraeme** [comment]
I agree with @yshui 

We could adapt this for musl later.

**Comment by maxice8** [comment]
It needs adaption of libGL, not musl, it might need musl adaptation if the
big stack changes aren't enough to fix the problem.

**Comment by xtraeme** [comment]
@maxice8 right, that's why I edited my comment :-)

**Comment by maxice8** [comment]
I only answer by email

**Comment by KeepBotting** [comment]
Any chance this will be merged? Seems like it could be a silver bullet for laptops cursed with an Optimus configuration (Intel and NVIDIA GPUs). 

I've been trying for a while to puzzle out the best solution to getting the proprietary driver working and stumbled upon [this blog post](https://www.ifnull.org/articles/void_optimus_nvidia_intel/) which mentioned `libglvnd` and led me here.

**Comment by yshui** [comment]
@KeepBotting to clarify, merging this PR is not going to get you want you want directly. but it is a first step.

after this, i should need to adapt the nvidia and mesa packages to make them use this libglvnd (the nvidia driver is actually using libglvnd already)

**Comment by st3r4g** [comment]
`glvnd`is migrating to Freedesktop:
https://gitlab.freedesktop.org/glvnd/libglvnd

**Comment by st3r4g** [comment]
I slightly modified this template and mesa's template and it seems that I can run GL applications on musl under X fine. Still have a problem under Wayland, eglBindWaylandDisplay fails (or the pointer cannot be loaded). The only non trivial thing was to add:
```
# Disable TLS with musl: https://bugs.freedesktop.org/show_bug.cgi?id=35268
case "$XBPS_TARGET_MACHINE" in
        *-musl) configure_args="--disable-tls"
esac
```
just like in mesa's template, otherwise xorg didn't start.

**Pull request closed without merging**
