### PR TITLE
gawk: update to 5.3.0

### PR DESCRIPTION
**Pull request by Calandracas606**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86_64-musl
  - i686
  - aarch64 (cross)
  - aarch64-musl (cross)
  - armv7l (cross)
  - armv7l-musl (cross)
  - armv6l (cross)
  - armv6l-musl (cross)

### CODE REVIEW

**Comment by Calandracas606** [comment]
continuation of https://github.com/void-linux/void-packages/pull/40968 I guess

**Comment by Calandracas606** [comment]
musl test failure appears to be related to locale

**Comment by Calandracas606** [comment]
> musl test failure appears to be related to locale

nvm test failures are not locale related

**Comment by Calandracas606** [comment]
annoyingly, I can't reproduce the musl check failures locally

**Comment by leahneukirchen** [comment]
Symlink the patch perhaps, else :shipit:

**Pull request merged**
