### PR TITLE
New package: abaddon-0.2.1

### PR DESCRIPTION
**Pull request by rookiejet**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

### CODE REVIEW

**Comment by MIvanchev** [comment]
I tested it as well, seems to work fine (glibc x86_64)

**Comment by MIvanchev** [comment]
Thank you for maintaining that package! Just 1 thing, abaddon doesn't currently install an icon so the entry in the .desktop file is wrong. Maybe it's better to remove the line.

**Comment by rookiejet** [comment]
Thanks for the suggestions, I will implement them with the version bump. Do you know if there is a failure case if the icon entry is included without an icon? It seems to validate fine. I'd prefer to leave it because I'd likely forget to add it later.

**Comment by MIvanchev** [comment]
> Thanks for the suggestions. Do you know if there is a failure case if the icon entry is included without an icon? It seems to validate fine. I'd prefer to leave it because I'd likely forget to add it later.

Void doesn't validate the file at all. With my launcher (xlunch) there isn't any icon in this case (icon specified but not found) whereas xlunch puts a generic icon if there is no icon specified at all. So for me nothing is slightly better but different launchers likely handle this in their own manner.

> Can you also clarify why `hicolor-icon-theme` is required? My understanding is it is depended on if the app uses icons from the desktop icon theme for e.g. in its buttons, which abaddon does not do.

IMO the package is required if you use something from `/usr/share/icons/hicolor` even if you put it there but I'm not 100% certain.

**Comment by rookiejet** [comment]
I should clarify, I meant validate using `desktop-file-validate`, but I assume that is only checking syntax. Letting menus display a generic icon if they can is probably better, I will remove the icon line then. Thanks.

**Comment by MIvanchev** [comment]
Desperate bump.

**Pull request closed without merging**
