### PR TITLE
bleachbit: update to 4.4.2.

### PR DESCRIPTION
**Pull request by rivanfebrian123**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86-64 glibc

### CODE REVIEW

**Comment by paper42** [comment]
Could you orphan this package? (change maintainer line to `maintainer="Orphaned <orphan@voidlinux.org>"`)

**Comment by rivanfebrian123** [comment]
No problem

**Comment by rivanfebrian123** [comment]
So, how can I make a single commit without creating a new branch and a new PR?

**Comment by rivanfebrian123** [comment]
Okay, I'll try

**Pull request closed without merging**
