### PR TITLE
cargo: update to 0.33.0.

### PR DESCRIPTION
**Pull request by Cogitri**
Mind testing on ppc, @q66?
@jnbr

### CODE REVIEW

**Comment by jnbr** [comment]
I think the template can be simplified with `build_helper=rust`.
`_cargo_dist_version` and associated distfiles should be updated.

**Comment by Cogitri** [comment]
> I think the template can be simplified with `build_helper=rust`.

Ah, right.

> `_cargo_dist_version` and associated distfiles should be updated.

Yup, but first {ppc64-,}musl stuff has to be rebuilt for 0.33

**Comment by q66** [comment]
Will do, and will put binaries onto my server for mirroring while at it.

**Comment by q66** [comment]
Tested, and new binaries ready in https://void-ppc64.octaforge.org/distfiles/

**Comment by Cogitri** [comment]
Thanks. Mind rebuilding for x86_64-musl too and mirroring what's q66 has built, @Gottox?

**Comment by Gottox** [comment]
https://alpha.de.repo.voidlinux.org/distfiles/cargo-0.33.0-x86_64-unknown-linux-musl.tar.xz

**Comment by Gottox** [comment]
ppc binaries have been uploaded too, thanks @q66!

**Comment by Cogitri** [comment]
Works locally.

**Comment by jnbr** [comment]
> Works locally.

Did you test musl as well? It fails while downloading crates.
Can you test again but run `rm -rf masterdir-musl/tmp/.cargo` before?

**Comment by Cogitri** [comment]
Just tested x86_64-musl with that dir removed again, it works just fine.

**Comment by jnbr** [comment]
very interesting. Can you check which version of libcurl is installed in your masterdir?

**Comment by jnbr** [comment]
applying #8293 fixed it for me

**Comment by Cogitri** [comment]
> very interesting. Can you check which version of libcurl is installed in your masterdir?

Will do.

> applying #8293 fixed it for me

Nice!

**Comment by jnbr** [comment]
please rebase

**Comment by Cogitri** [comment]
Done, let's see what CI says.

**Comment by jnbr** [comment]
#8368 should fix cross builds

**Pull request merged**
