### PR TITLE
New packages: ayugram-desktop-4.9.4, ayugram-desktop-sysfont-4.9.4

### PR DESCRIPTION
**Pull request by incycledream**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (ARCH-LIBC)

### CODE REVIEW

**Comment by ahesford** [comment]
Packages that just clone a git repository in `do_fetch` are not acceptable. A GitHub archive should be fetched properly.

The `ayugram-desktop` and `ayugram-desktop-sysfont` templates seem identical, at least as far as I can tell paging back and forth. What is the difference between them? 

Use of `broken=` to disable unsupported archs is not appropriate. The `archs` variable should be used for proper architecture restrictions.

**Comment by incycledream** [comment]
okay, I'll fix the mistakes. I used official telegram desktop template and I thought everything is okay
also, I forgot to specify that CI will take more than 2 hours due having two commits with different versions

about packages, version with sysfont ending is having system font. you can see by checking patches directory
```
void-packages/srcpkgs/ayugram-desktop/patches:
total 4.0K
   0 drwxr-xr-x 1 westpain westpain  54 Sep 25 17:16 .
   0 drwxr-xr-x 1 westpain westpain  30 Sep 25 17:16 ..
4.0K -rw-r--r-- 1 westpain westpain 419 Sep 25 17:16 0001-use-vendored-gsl.patch

void-packages/srcpkgs/ayugram-desktop-sysfont/patches:
total 8.0K
   0 drwxr-xr-x 1 westpain westpain  80 Sep 25 17:16 .
   0 drwxr-xr-x 1 westpain westpain  30 Sep 25 17:16 ..
4.0K -rw-r--r-- 1 westpain westpain 419 Sep 25 17:16 0001-use-vendored-gsl.patch
4.0K -rw-r--r-- 1 westpain westpain 352 Sep 25 17:16 sysfont.patch
```

**Comment by ahesford** [comment]
Two packages that are the same except for a one-line patch to change the font are not acceptable.

**Comment by Johnnynator** [comment]
https://core.telegram.org/api/terms
> 1.4. It is forbidden to interfere with the basic functionality of Telegram. This includes but is not limited to: making actions on behalf of the user without the user's knowledge and consent, preventing self-destructing content from disappearing, preventing last seen and online statuses from being displayed correctly, tampering with the 'read' statuses of messages (e.g. implementing a 'ghost mode'), preventing typing statuses from being sent/displayed, etc. 

The API Access and therefore the used API Key hast to follow the API Terms of Use. Void has some basic responsibility to not ship software to users with the sole intention of breaking the TOU of a single Service.

**Pull request closed without merging**
