### PR TITLE
protonmail-bridge: update to 1.5.6

### PR DESCRIPTION
**Pull request by vivlim**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Please follow the commit style: `protonmail-bridge: update to 1.5.7`. Also, shouldn't this be 1.5.7?

**Comment by vivlim** [comment]
@ericonr 1.5.6 seems to still be the latest version available, where did you get 1.5.7 from?

image

**Comment by ericonr** [comment]
From https://github.com/ProtonMail/proton-bridge/releases

**Comment by vivlim** [comment]
1.5.7 doesn't haven an official package yet, https://protonmail.com/download/beta/protonmail-bridge_1.5.7-1_amd64.deb is a 404.

**Comment by ericonr** [comment]
Got it! Please just fix the commit message and fix the license (see https://github.com/void-linux/void-packages/pull/26058/files ) and we are good to go.

**Comment by vivlim** [comment]
ah, I missed the news of the license change. From that PR and [this thread](https://www.reddit.com/r/voidlinux/comments/gc6b3w/protonmailbridge/) there was discussion about building the bridge from source instead of pulling it from the .deb. is that a requirement for packages that are in the main repos? or is it fine for this package to continue using the unpacked .deb?

**Comment by ericonr** [comment]
It's unfortunate but it can remain  as is for now. Building it is rather complex :/

**Comment by ericonr** [comment]
Also it wasn't a license change, but rather that the license was just wrong. If you can include that in the commit message, I'd appreciate it.

**Comment by vivlim** [comment]
Sure. How's this?

**Comment by ericonr** [comment]
It's been GPL for longer, we just used a commercial license for some weird reason. You don't have to specify the version, just mention that it was wrong.

**Comment by vivlim** [comment]
Done, the message now says
"Correcting the license which has been GPL 3.0."

**Comment by ericonr** [comment]
Turns out it was "or-later". I fixed it locally and pushed, thanks!

**Pull request closed without merging**
