### PR TITLE
yazi: update to 0.4.2.

### PR DESCRIPTION
**Pull request by xavierfortier1**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64 (crossbuild)
  - armv7l-musl (crossbuild)

@Bnyro

### CODE REVIEW

**Comment by Bnyro** [comment]
Why am I the maintainer of the package when people open update PRs within one day without me having time to test the update and send a PR myself? 💀

**Comment by xavierfortier1** [comment]
Sorry about that, I was simply modifying my config and saw that it got a new release. I can close the PR if you want to test it and update it on your side.

**Comment by bitterhalt** [comment]
> Why am I the maintainer of the package when people open update PRs within one day without me having time to test the update and send a PR myself? 💀

So what's the problem if someone makes a pull request when they see a new version? Many package in Void would be ancient without PR's..

**Comment by Bnyro** [comment]
> Sorry about that, I should've waited a couple days to see if you were going to update it. I was simply modifying my config and saw that it got a new release. I can close the PR if you want to test it and update it on your side.
>
No worries, I just wanted to note that I'd appreciate having a couple of days to handle the update myself first.

**Comment by Bnyro** [comment]
> So what's the problem if someone makes a pull request when they see a new version? Many package in Void would be ancient without PR's..
>
There's no problem with people opening PRs for packages they don't maintain if its maintainer didn't and it doesn't seem that the package maintainer will update the package in the near future, absolutely.

But since this release had only been published about a day before this PR was opened and I personally saw the update when it came out and planned to test it before making a PR but didn't yet have time for it before this one here was opened. Waiting 3 days to a week before updating a package maintained by somebody that's been actively updating it in the past generally would be the more gentleman-like approach.

**Review by Bnyro — APPROVED** [review]

**Pull request merged**
