### PR TITLE
pavucontrol: update to 5.0.

### PR DESCRIPTION
**Pull request by ardadem**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [X] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

```
Changes:

Support for switching Bluetooth codecs (new in PulseAudio 15.0).
Support for locking card profiles (new in PulseAudio 15.0). Locking a profile prevents PulseAudio from automatically switching away from that profile on plug/unplug events.
New translations: Asturian, Basque, Belarusian, Galician, Hebrew, Kazakh, Norwegian Bokmål, Sinhala, Slovenian
Updated translations: Catalan, Chinese (Simplified), Chinese (Traditional), Croatian, Danish, Dutch, Finnish, French, German, Hungarian, Italian, Japanese, Korean, Lithuanian, Norwegian Nynorsk, Polish, Portugese, Portugese (Brazil), Slovak, Spanish, Swedish, Turkish, Ukrainian.
Some bug fixes.
New dependency: json-glib.
Minimum gtkmm version bumped to 3.22.
```

We should merge it after Pulseaudio 15 since it's required for all new features.

### CODE REVIEW

**Comment by ardadem** [comment]
CC @ericonr

**Comment by paper42** [comment]
When this is built with libpulseaudio 15 and runs on a system with libpulseaudio 14, it will fail to start, because of missing symbols? We might want to fix that.

**Comment by ardadem** [comment]
@paper42 Do you mean like this?

**Comment by paper42** [comment]
> Do you mean like this?

This seems fine, could you split it to a separate commit, it touches a different package.

**Comment by ardadem** [comment]
@paper42 I've checked shlibs history. Isn't it's always in the same commit or am i missing something?

**Comment by paper42** [comment]
> I've checked shlibs history. Isn't it's always in the same commit or am i missing something?

They are in the same commit that touches the package which contains the library. We are updating pavucontrol here and noticed that the pulseaudio update forgot to bump the version in shlibs, so I would say that's a separate problem and should be in a separate commit. Of course this is subjective.

**Comment by ericonr** [comment]
I implemented the commit split and merged, thanks.

**Comment by paper42** [comment]
reverted in 8a9bdd07c2796f04e6df1892d97ed21f7357c86b because this update was segfaulting pulseaudio for some reason

**Comment by ardadem** [comment]
Oh, i'm using it with pipewire and thought it will work with pulseaudio if it's works on pipewire. Sorry about that, but i see u already opened a PR.

**Pull request merged**
