### PR TITLE
libwacom: update to 1.9.

### PR DESCRIPTION
**Pull request by skmpz**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Alternatively, you can do `-Dtests=disabled` (https://github.com/linuxwacom/libwacom/blob/master/meson_options.txt#L9) when `$XBPS_CHECK_PKGS` isn't set.

**Comment by skmpz** [comment]
Thanks for the info. What if we have
```
hostmakedepends="pkg-config"
checkdepends="python3-pytest python3-libevdev python3-pyudev"
```
Then if we add the checks in cross compilation
`./xbps-src -Q pkg -a aarch64 -f libwacom`

This will fail right? Isn't that a valid thing? Or we can consider -Q will not be used when cross compiling?

**Comment by ericonr** [comment]
I think `XBPS_CHECK_PKGS` is unset when cross compiling, no matter the options passed... Not sure though. You can probably add those options and try. For the record, neither CI nor the builders use `-Q` for cross builders.

**Comment by skmpz** [comment]
Yeah, it seems that `XBPS_CHECK_PKGS` is set when run with
```
./xbps-src -Q pkg -a aarch64 -f libwacom
```
But since CI/builders don't use -Q for cross builders I guess it's fine to go with the proposed change.

**Pull request merged**
