### PR TITLE
switch to long-lived driver version 410.66

### PR DESCRIPTION
**Pull request by Chili-Bebber**

### CODE REVIEW

**Comment by maxice8** [comment]
Please use proper commit name and update the checksum

**Comment by Hoshpak** [comment]
To update a package you need to at least also update the checksum for the distfiles. An update of the nvidia driver to a new major release probably requires more changes than that, though.

**Comment by Chili-Bebber** [comment]
I'll admit, I'm still not very knowledgeable on how templates are structured, but I don't think the method of driver installation has changed at all and all the instances of the version number are stored in the one variable. I think updating the checksum + changing the variable is all it'll take.

**Comment by Chili-Bebber** [comment]
Also, I should be using md5sum to get the cheksums, right? The most recent driver also drops 32 bit support, so an nvidia-legacy package might be in order.

**Comment by Johnnynator** [comment]
the checksum is sha256. Also you have to update it for all distfiles that are in the template. Also do build and test the update locally. (You would notice that it will no work)

x86_64:
```
> ERROR: SHA256 mismatch for 'NVIDIA-Linux-x86_64-410.66-no-compat32.run:'
c4e297ed93341841c7ccb32569c179baecbb6ea253215cbc3668a51d729227cd
=> ERROR: nvidia-410.66_1: couldn't verify distfiles, exiting...
```
i686:
```
=> nvidia-410.66_1: fetching distfile 'NVIDIA-Linux-x86-410.66.run'...
looking up uk.download.nvidia.com
connecting to uk.download.nvidia.com:80
requesting http://uk.download.nvidia.com/XFree86/Linux-x86/410.66/NVIDIA-Linux-x86-410.66.run
http://uk.download.nvidia.com/XFree86/Linux-x86/410.66/NVIDIA-Linux-x86-410.66.run: Not Found
=> ERROR: nvidia-410.66_1: failed to fetch NVIDIA-Linux-x86-410.66.run.
```

**Comment by Chili-Bebber** [comment]
I think that there is the nvidia-340 package that covers that. Correct me if I'm wrong, but this package is supposed to be the most recent long-lived release of the nvidia driver.

**Comment by HadetTheUndying** [comment]
This driver package should not create any conflicts with Cards it already supports. 340.xx is still the legacy card module as far as I'm aware. I will work on packaging this driver this weekend if someone else has not already gotten to it. I have a working version of the short-lived branch before it, and I believe cspack101 does too.

**Comment by Hoshpak** [comment]
@simonhdickson Please open a PR for it so we can use it for further discussion. Since 390.x is now officially the legacy branch, I think we should create a copy of the package as `nvidia390`, this might also be the best solution for people still using nvidia hardware on i686 that is not supported by `nvidia340`. I don't think there's a possibility to generate multilib packages without generating i686 ones as the multilib packags are a byproduct of the i686 build.

**Comment by Hoshpak** [comment]
superseded by #4221

**Pull request closed without merging**
