### PR TITLE
dma: fix /etc/dma/*.conf permissions

### PR DESCRIPTION
**Pull request by loreb**
Fixes https://github.com/void-linux/void-packages/issues/34431;
solution due to thenktor

#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86-64-musl)

### CODE REVIEW

**Comment by loreb** [comment]
Btw, in case anyone wants to take a look, there were a couple of compilation warnings:

```
net.c: In function 'read_remote.part.0':
net.c:159:6: warning: 'strncpy' specified bound 1024 equals destination size [-Wstringop-truncation]
  159 |      strncpy(neterr, strerror(errno), sizeof(neterr));
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
net.c:154:6: warning: 'strncpy' specified bound 1024 equals destination size [-Wstringop-truncation]
  154 |      strncpy(neterr, ssl_errstr(), sizeof(neterr));
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
net.c:168:4: warning: 'strncat' output may be truncated copying between 0 and 1023 bytes from a string of length 2047 [-Wstringop-truncation]
  168 |    strncat(neterr, buff, copysize);
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
net.c: In function 'send_remote_command':
net.c:104:5: warning: 'strncpy' specified bound 1024 equals destination size [-Wstringop-truncation]
  104 |     strncpy(neterr, ssl_errstr(), sizeof(neterr));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

They were fixed upstream in February 2020 (strncpy=>strlcpy), except that it looks to me that the 2047=>1023 is still there (strncat) and replacing it with strlcat would silence the warning without actually fixing the issue.

**Comment by loreb** [comment]
bump

**Comment by loreb** [comment]
bump

**Comment by classabbyamp** [comment]
can you rebase this?

**Pull request merged**
