### PR TITLE
osg: update to 3.6.5

### PR DESCRIPTION
**Pull request by HadetTheUndying**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

I've briefly tested this as it's very late. I've grabbed the latest patches from the Alpine builds. I know this update has been held before and am seeking review. I personally need this update to build some VR sourceports. I have revbumped the relevant packages as well

### CODE REVIEW

**Comment by HadetTheUndying** [comment]
Might need a little help wrapping my head around what's going on with the build. Everything has built fine locally for me on all architectures. I see and understand the linting error with sumo but am not sure why the actions failed on all x86 builds and not the ARM ones.

**Comment by paper42** [comment]
> Might need a little help wrapping my head around what's going on with the build. Everything has built fine locally for me on all architectures. I see and understand the linting error with sumo but am not sure why the actions failed on all x86 builds and not the ARM ones.

Because the failing phase is `do_check` which is only ran on non-cross targets. You should be able to reproduce the failure with `./xbps-src check <pkg>` or `./xbps-src pkg -K <pkg>`, pkg doesn't run tests by default. If you are still not able to reproduce the issue, it's possible it's specific to the CI environment.

**Comment by HadetTheUndying** [comment]
> > Might need a little help wrapping my head around what's going on with the build. Everything has built fine locally for me on all architectures. I see and understand the linting error with sumo but am not sure why the actions failed on all x86 builds and not the ARM ones.
> 
> Because the failing phase is `do_check` which is only ran on non-cross targets. You should be able to reproduce the failure with `./xbps-src check <pkg>` or `./xbps-src pkg -K <pkg>`, pkg doesn't run tests by default. If you are still not able to reproduce the issue, it's possible it's specific to the CI environment.

Okay so yeah that definitely reproduced the issue, but I have no idea how to go about fixing it. Any advice or help would be nice. I'm still not too great at this kinda learning as I go. I understand that cmake is failing at that specific task but not why.

**Comment by HadetTheUndying** [comment]
Okay so I've set `make_check=no` in `sumo` for the time being. It looks like we are a considerable number of releases behind from the upstream and I will address this once the PR is merged. As Prior to `1.9.0 `sumo` did not support python3 properly and this was not spotted during the python-3.10 revbump which the check also fails on. I know this is a little messy but as this package is so many version out of date, and I don't regularly use it, I would prefer to revbump it and then get it back up to date with the upstream after we get `osg` updated. This is my first PR that effects multiple packages like this so I appreciate everyone that's been helping me learn.

**Comment by HadetTheUndying** [comment]
The issue with Flightgear was definitely introduced by this revbump though. So I'll try to figure that out right now I'm at a loss.

**Comment by paper42** [comment]
Updating sumo to the latest version fixes the test failure.

**Comment by 4ricci** [comment]
Even if `xrevshlib` does not mention it, simgear should be revbumped as well. This may fix the flightgear issue (no time to test right now).

**Comment by HadetTheUndying** [comment]
> Even if `xrevshlib` does not mention it, simgear should be revbumped as well. This may fix the flightgear issue (no time to test right now).

I'll get around to trying to fix this up by Wednesday. Ended up getting a little busy after I started working on this.

**Comment by 4ricci** [comment]
ping

**Comment by HadetTheUndying** [comment]
Hey so, I really don't have time to work on this PR right now, but I've done a lot of the grunt work if someone wants to take over. I expect I'll have time to work on it again in May when things die down for me with other projects. 

If no one gets to it, I will get back to it as soon as I can. There's not a lot left that needs to be done, I just don't have time to test those things right now, and my build server is out of commission right now and can't spare the build times on my main machine at the moment.

**Pull request closed without merging**
