### PR TITLE
ghidra: update to 10.2.1

### PR DESCRIPTION
**Pull request by vitezfh**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

Maybe someone familiar with ghidra can have another look. @abenson ?
It compiles and patches successfully after these changes. Runs seemingly fine too.

### CODE REVIEW

**Comment by classabbyamp** [comment]
please add the email you used to commit to your github account

**Comment by vitezfh** [comment]
Done. Thanks for the heads-up

**Comment by unspecd** [comment]
What's the point of deleting `*.fidb` files?

**Comment by unspecd** [comment]
https://github.com/void-linux/void-packages/actions/runs/3419934671/jobs/5703039380#step:7:2738

> SONAME: ld-linux-x86-64.so.2 <-> glibc>=2.32_1

Looks like there are some extraneous files compiled for glibc.

**Comment by vitezfh** [comment]
> What's the point of deleting `*.fidb` files?

I'm looking it up right now. I think a source was missing for one or more of them.. I might be misremembering

**Comment by unspecd** [comment]
> https://github.com/void-linux/void-packages/actions/runs/3419934671/jobs/5703039380#step:7:2738
> 
> > SONAME: ld-linux-x86-64.so.2 <-> glibc>=2.32_1
> 
> Looks like there are some extraneous binaries compiled for glibc.

/usr/libexec/ghidra/Ghidra/Features/FileFormats/data/sevenzipnativelibs/Linux-amd64/lib7-Zip-JBinding.so

**Comment by vitezfh** [comment]
I can't make much sense of it. But I added the change and tested it very shortly on **glibc**. Seems to work. Commiting it as well.

**Comment by unspecd** [comment]
> But I added the change and tested it very shortly on **glibc**

This applies to musl, not glibc. I think it would be better if you add a condition like this:

```diff
@@ -95,4 +97,7 @@ do_install() {
 	bsdtar --strip-components 1 -C ${DESTDIR}/usr/libexec/ghidra -xf build/dist/ghidra_${version}_DEV_$(date -u +%Y%m%d)_linux_${arch}.zip
 	vmkdir usr/bin
 	ln -srf /usr/libexec/$pkgname/ghidraRun ${DESTDIR}/usr/bin/ghidra
+	if [ "$XBPS_TARGET_LIBC" = "musl" ]; then
+		rm ${DESTDIR}/usr/libexec/ghidra/Ghidra/Features/FileFormats/data/sevenzipnativelibs/Linux-amd64/lib7-Zip-JBinding.so
+	fi
 }
```

**Comment by oreo639** [comment]
10.2.1 is out.
Also this should all be one commit.
> make one commit per package (including all changes to its sub-packages).

https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#committing-your-changes

(You can do that by doing `git reset --soft HEAD~3 && git commit --amend`)

**Pull request closed without merging**
