### PR TITLE
New package: OpenLP-2.4.6

### LINKED ISSUE #1055: Package request: OpenLP
https://openlp.org/
[AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openlp)

### PR DESCRIPTION
**Pull request by Chocimier**
Works, but only basic functions tested. @notramo, is it good enough?

Closes #1055.

### CODE REVIEW

**Comment by notramo** [comment]
@Chocimier translations are not available. I haven't tested other features.

**Comment by Chocimier** [comment]
Translations added.

**Comment by notramo** [comment]
Thanks, now translations are available.
It seems OK.

**Comment by notramo** [comment]
Could you trigger somehow a rebuild?

**Comment by Chocimier** [comment]
Rebased to current master and force-with-lease pushed for rebuild.

**Comment by Chocimier** [comment]
Updated python-alembic.

**Comment by Chocimier** [comment]
Python-alembic updated to 1.0.2.

**Pull request merged**
