### PR TITLE
New package: tree-sitter-0.17.3

### PR DESCRIPTION
**Pull request by mlugg**

### CODE REVIEW

**Comment by ericonr** [comment]
@harrisonthorne has a template for this in #26474 , and theirs does a devel split.

**Comment by harrisonthorne** [comment]
Oh, I have a branch for that. Should I make a new PR for it?

**Comment by ericonr** [comment]
@harrisonthorne your choice; you can cooperate with @mlugg to add your changes as well.

**Comment by mlugg** [comment]
@harrisonthorne I see you've just opened #26484 - if you're happy to clean up the extra commits (and presumably make xlint happy), I'll close this PR. (Alternatively, as ericonr mentioned, I could incorporate your devel split into this PR)

**Comment by harrisonthorne** [comment]
I apologize haha-- I feel like I'm raining on a parade here. #26484 is ready to go

**Comment by mlugg** [comment]
Oh, no problem whatsoever! A devel split probably makes sense, I threw this together quite quickly because I wanted to build neovim nightly :P thanks!

**Pull request closed without merging**
