### PR TITLE
python-PyQt5: fix webengine

### PR DESCRIPTION
**Pull request by Johnnynator**

### CODE REVIEW

**Comment by pbui** [comment]
This fixes PyQt5 with qutebrowser for me.  Thanks @Johnnynator

**Comment by pullmoll** [comment]
Uh, now I see. Thank you and please merge.

**Comment by Johnnynator** [comment]
> Uh, now I see. Thank you and please merge.

I cannot merge anything...

**Comment by maxice8** [comment]
Done

**Pull request merged**
