### PR TITLE
xbps-src: explicitly disallow pattern on build deps

### LINKED ISSUE #37837: xbps-src show-build-deps breaks with version restrictions
For example openocd has jimtcl in makedepends, but it's version restricted: `jimtcl-devel>=0.81_1<=0.81_9999`
```
%: ./xbps-src show-build-deps openocd
=> ERROR: openocd-0.11.0+1_1: dependency 'jimtcl-devel>=0.81_1<=0.81_9999' does not exist!
```
show-build-deps should understand version restrictions and not throw an error.

### PR DESCRIPTION
**Pull request by Chocimier**
It is not possible to use version other than currently in template.

Specifying pattern breaks build if dependency isn't in binary repo
already. That it worked when in repo was a coincidence.

#### Testing the changes
- I tested the changes in this PR: **YES**

Closes #37837

### CODE REVIEW

**Comment by classabbyamp** [comment]
what about the exact version case? (`foo-1.2_3`)

**Comment by Chocimier** [comment]
it isn't as easy to tell what is an exact version, and calling xbps-uhelper is costly

**Comment by paper42** [comment]
Closes #37837

openocd seems to be the only package that currently uses a version restriction in build depends

**Review by Piraty — APPROVED** [review]

**Comment by Duncaen** [comment]
I think this check should go into `setup_pkg` in `common/xbps-src/shutils/common.sh`, this is where we do basic validation on input variables. I would also use pattern matching, either case statement or just `[[` matching.

```bash
for x in "foo>=1" "bar<2" "fizz" "foo-bar-1.0_1" "font-adobe-100dpi-1.8_blah" "cross-x86_64-linux-musl-libc" "perl-PerlIO-utf8-strict-0.008_1" "perl-PerlIO-utf8-strict"; do
    if [[ $x = *[\>\<]* || $x =~ -[^-]+_[0-9]+$ ]]; then 
        echo $x
    fi
done
```

**Comment by Chocimier** [comment]
@Duncaen: ok, modified regex to match xbps-uhelper getpkgname.

**Comment by Duncaen** [comment]
This pattern is more restrictive than the xbps implementation, the only requirement is that revision is numeric not that the version starts with a digit.

**Comment by Chocimier** [comment]
Version has to contain digit, see commit message.

**Comment by Duncaen** [comment]
ah right, this is so stupid this shouldn't have been implemented and i hate it, but it is what it is...

**Review by Duncaen — APPROVED** [review]

**Comment by Duncaen** [comment]
Maybe we can just add `=` as alternative pkgver separator in xbps and slowly migrate over to use that as a more sane choice instead of a character that is used in half the packages names already.

**Comment by classabbyamp** [comment]
+1, i think = makes a lot of sense as a version specifier

**Pull request merged**
