### PR TITLE
zfs: update to 2.1.9.

### PR DESCRIPTION
**Pull request by zdykstra**
#### Testing the changes
- I tested the changes in this PR: **YES**

Built / booted into this locally, root-on-ZFS, x86_64.

### CODE REVIEW

**Comment by zdykstra** [comment]
https://github.com/openzfs/zfs/issues/14413

There might be a 2.1.8.1 release because of this issue.

**Comment by zdykstra** [comment]
ZFS 2.1.9 has been released to address the previous blocking issue. It's otherwise identical to 2.1.8, which I've been running since Monday.

**Comment by zdykstra** [comment]
2.1.9 seems to be pretty stable. There haven't been any show-stopping bug reports opened or problems discussed in libera.chat#zfsonlinux .

@Vaelatern tag, you're it!

**Review by Vaelatern — APPROVED** [review]

**Comment by Vaelatern** [comment]
Thank you!

**Pull request merged**
