### PR TITLE
[WIP] Cinnamon 4.8

### PR DESCRIPTION
**Pull request by ericonr**
Closes #26965 

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

@mobinmob I have yet to search for new releases, but if you know of any I'm missing, please let me know.

### CODE REVIEW

**Comment by mobinmob** [comment]
> Closes #26965
> #### Have the results of the proposed changes been tested?
> 
>     * [ ]  I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
> 
>     * [ ]  I generally don't use the affected packages but briefly tested this PR
> 
> 
> @mobinmob I have yet to search for new releases, but if you know of any I'm missing, please let me know.

Thank you for taking over  the cinnamon update! I am swamped with work (unexpectedly) today.

**Comment by ericonr** [comment]
I'm seeing if I can fix #10650 before merging.

**Comment by ericonr** [comment]
Depends on https://github.com/linuxmint/cinnamon-screensaver/issues/363

**Comment by ericonr** [comment]
@sgn I will add a comment explaining that, thanks. IMO the libdir hook should also be fixed (in a different PR)

**Pull request merged**
