### PR TITLE
New package: NetworkManager-wireguard-20181128

### PR DESCRIPTION
**Pull request by aliasless**

### CODE REVIEW

**Comment by Piraty** [comment]
I heard of this before.
I'd really prefer a tagged release, but the project seems inactive for a year...

**Comment by aliasless** [comment]
I've removed archs= as suggested by xtraeme, but I cannot figure out how to get this to successfully build on the non-x86 architectures. I don't know if its a problem with my template, or if its an issue that needs to be fixed upstream.

**Comment by Hoshpak** [comment]
```
Please note that we do not accept any packages containing non-release versions such as specific git- or svn-revisions anymore.
```

Please ask upstream to tag a release.

**Comment by Piraty** [comment]
I already did (via email), no response so far

**Comment by Piraty** [comment]
I assume this is obsolete
https://blogs.gnome.org/thaller/2019/03/15/wireguard-in-networkmanager/

**Comment by sgn** [comment]
We should package new NetworkManager instead.

**Comment by steinex** [comment]
FWIW. My last info on NM is that @Gottox  was holding back updating NM because they did breaking changes to plugins that are packaged (like `NetworkManager-openvpn` for instance). This was roughly ~1 year ago.

I have no idea about the current situation though.

**Pull request closed without merging**
