### PR TITLE
moc: Add support of sndio

### PR DESCRIPTION
**Pull request by strikersh**

### CODE REVIEW

**Comment by strikersh** [comment]
To test `sndio` support you have to pass `-R sndio` or change `SoundDriver` to include `SNDIO` when moc tries different backend at start

**Comment by Vaelatern** [comment]
Thank you for your contribution!

**Comment by Vaelatern** [comment]
now, I'm going to fix up the work, feel free to notice what else had to be done: 27319b9ce454d79bff8b6bf29c7a8410f2e6d7ca

**Comment by strikersh** [comment]
Sorry for the revision number I did forget about that…

**Comment by Vaelatern** [comment]
That's ok. The `xrevbump` script from the `xtools` package helps avoid forgetting.

**Pull request merged**
