### PR TITLE
nvidia: update to 435.21

### PR DESCRIPTION
**Pull request by Clyybber**

### CODE REVIEW

**Comment by Clyybber** [comment]
Not sure why 32bit is failing..

**Comment by concatime** [comment]
Same with 440.31: https://travis-ci.org/concatime/void-packages/builds/610565576

**Comment by Clyybber** [comment]
I'm gonna close this in favor of updating to 440.31 (if someone manages to fix the failures)

**Comment by st3r4g** [comment]
@Clyybber @concatime 
From https://devtalk.nvidia.com/default/topic/1032650/linux/unix-graphics-feature-deprecation-schedule/
> The Linux-x86 and FreeBSD-x86 release packages, as well as support for 32-bit kernels in the Solaris package, are no longer provided starting with release 396.

So this fails because for `i686` there are no binaries to be packaged in `nvidia` (as it should be). Previously an empty package was still generated... I think the linter behaviour changed

**Comment by st3r4g** [comment]
The easiest/laziest thing is just to add `build_style="meta"` for the `i686` case:
```
else
        _pkg="NVIDIA-Linux-x86_64-${version}"
        distfiles="http://uk.download.nvidia.com/XFree86/Linux-x86_64/${version}/${_pkg}.run"
        checksum=f700899f48ba711b7e1598014e8db9a93537d7baa3d6a64067ed08578387dfd7
        subpackages="nvidia-libs"
        depends="pkgconf libglvnd"
        build_style="meta" <---- Add this here
fi
```
Don't know if the package generation can be avoided altogether (would be better).

**Comment by st3r4g** [comment]
Consider also this:

> The release 430 series will be the last to support installing Linux OpenGL and EGL client libraries that do not use the GL Vendor Neutral Dispatch (GLVND) loader library.

So having the `glvnd` option makes no sense anymore, must be always on.

**Comment by concatime** [comment]
Shouldn’t we limit this package to only x86_64 from now on?

**Comment by st3r4g** [comment]
> Shouldn’t we limit this package to only x86_64 from now on?

No, because we still want `nvidia-libs-32bit` to be generated, and that is done by the `i686` build.
From NVIDIA page:
> Support for 32-bit applications running on x86_64 kernels will continue.

**Pull request closed without merging**
