### PR TITLE
OpenCPN: fix ppc64 and probably arm builds

### PR DESCRIPTION
**Pull request by q66**
This doesn't fix cross compilation, as that would require a bigger rework, but it makes sure that arch is actually set right.

### CODE REVIEW

**Comment by Johnnynator** [comment]
Cross Actually should be easy to fix, removing the two `DwxWidgets*` line should get it working. I'm currently compiling it locally to test.

**Comment by q66** [comment]
Well, there's stuff like `CMAKE_SIZEOF_VOID_P` being for the host system. (though actually, I'm not 100% sure how toolchain files override that) The checks are actually taken from the same file, they were just contained under a specific conditional for `debian-release` for whatever reason.

**Comment by Johnnynator** [comment]
`CMAKE_SIZEOF_VOID_P` works for cross compiling

> This is set to the size of a pointer on the target machine, and is determined by a try compile. If a 64-bit size is found, then the library search path is modified to look for 64-bit libraries first.

**Comment by q66** [comment]
I guess it makes sense, since there is no notion of host or target system in cmake, it's not cross-aware by itself at all (which is kind of ridiculous)

**Comment by Johnnynator** [comment]
#8010

**Pull request closed without merging**
