### PR TITLE
girara: update to 0.3.3 and zathura: update to 0.4.4

### PR DESCRIPTION
**Pull request by ioraff**

### CODE REVIEW

**Comment by ioraff** [comment]
pairing these two updates so as to merge simultaneously--not doing this has been cause for issue in the past according to [#15254](https://github.com/void-linux/void-packages/pull/15254)

**Comment by concatime** [comment]
https://git.pwmt.org/pwmt/girara/merge_requests/3

**Comment by ioraff** [comment]
> https://git.pwmt.org/pwmt/girara/merge_requests/3
are you asking me to add this patch to the PR?

**Comment by ioraff** [comment]
> https://git.pwmt.org/pwmt/girara/merge_requests/3

Are you asking to me add this patch to the PR?

**Comment by concatime** [comment]
As you wish :)
1. Maintain the status quo
2. Apply my patch
3. Add xdg-utils as a dependency to girara

**Comment by lemmi** [comment]
Seems to work fine here. Thanks :)

**Pull request closed without merging**
