### PR TITLE
bloaty: fix build on ppc32 and armv6 (use libatomic)

### PR DESCRIPTION
**Pull request by q66**
Need to give this a CI run.

### CODE REVIEW

**Comment by ndowens** [comment]
I was also trying to fix this, if you add protobuf-devel, atleast for the one arch I was testing on, will giving errors. The needed file is also in the third_party part of wrksrc as well.

**Comment by ndowens** [comment]
http://dpaste.com/12WWYZA is the errors when you add protobuf-devel to makedepends, but even if you know how to fix them, it is generated during build, so can't really patch before it is built at all.

**Comment by q66** [comment]
looks to me it's failing on all cross even before my changes...

**Comment by ndowens** [comment]
Yep, I have yet to figure out how to fix cross-build yet.

**Comment by q66** [comment]
merged with nocross for now

**Pull request merged**
