### PR TITLE
nodejs: update to 20.9.0

### PR DESCRIPTION
**Pull request by rfl890**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by mhmdanas** [comment]
Thanks for your PR! I see you're taking on quite a heavy package for your first contribution to void-packages...

First thing, please don't close your PRs and open new ones just to change some things; instead, amend your commit using `git commit --amend` and then force-push to the PR's branch.

As for the PR itself, first thing, please pull in my changes in https://github.com/paper42/void-packages/pull/7 (except for the `${makejobs}` one, ignore it). Other than that, I'm afraid just testing that node works correctly isn't nearly enough: you also need to make sure that everything that depends on node for building still works correctly, can you please do that?

**Comment by rfl890** [comment]
@mhmdanas
Okay, I've merged your changes. According to `xbps-query -RX nodejs`, there are 10 packages that depend on nodejs excluding nodejs-lts. From what I understand, I need to build all of them from source and test them?

**Comment by mhmdanas** [comment]
> Okay, I've merged your changes. According to xbps-query -RX nodejs, there are 10 packages that depend on nodejs excluding nodejs-lts. From what I understand, I need to build all of them from source and test them?

No, what you found are the packages that depend on nodejs at runtime, but what I meant are packages that have nodejs in `makedepends` or `hostmakedepnends`. Also, you don't strictly need to test all of them, though that's still a good idea if possible.

**Comment by rfl890** [comment]
After a bit of digging, I found these packages:
```
Rocket.Chat-Desktop
Signal-Desktop
ansible-language-server
bismuth
chronograf
electron19
electron24
element-desktop
imgbrd-grabber
keybase-desktop
ntfy
pnpm
pyright
python3-jupyter_nbformat
qt5-webengine
qt5-webengine-devel
qt6-webengine
qt6-webengine-devel
qt6-webengine-examples
rapydscript-ng
riot-desktop
spreed-webrtc
vscode
wire-desktop
yarn
```
I'll test a few of them today.

**Comment by mhmdanas** [comment]
Sorry, another clarification: ideally you would run test builds for ALL of these packages, but it's fine to install and manually test some of them. However, the thing is, there are some packages in there that take a lot of resources and time to build (e.g. qt5-webengine), so it might not be feasible to do it yourself depending on your resources...

**Comment by rfl890** [comment]
Maybe not.

**Pull request closed without merging**
