### PR TITLE
webkit2gtk: update to 2.28.0

### PR DESCRIPTION
**Pull request by streaksu**

### CODE REVIEW

**Comment by streaksu** [comment]
Seems like the build is too long for the CI.
[ci skip]

**Comment by xtraeme** [comment]
dup of #20163

**Comment by Johnnynator** [comment]
> dup of #20163

Can we please not close PR's if they are a duplicate of some clearly untested and broken PR?

**Comment by xtraeme** [comment]
It's ok for me, but we should merge additional changes.

**Comment by xtraeme** [comment]
@Johnnynator be my guest

**Pull request closed without merging**
