### PR TITLE
dua-cli: update to 2.23.0.

### PR DESCRIPTION
**Pull request by jcgruenhage**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by cinerea0** [comment]
This commit upstream will fix the test failure: https://github.com/Byron/dua-cli/commit/9123ee7e648fab654520c33df672c053d5797966.

**Comment by jcgruenhage** [comment]
ah, and you also already had a PR open, I must've overlooked that. Thanks for the hint :)

**Comment by cinerea0** [comment]
No! I am closing mine, as you are the rightful maintainer.

**Comment by jcgruenhage** [comment]
tbqh, I couldn't care less who opens the PR, and you've already got it patched on your PR and contributed the PR upstream, so the package clearly means more to you than to me. If you want to take over maintainership for it, feel free to do so ^^

**Pull request merged**
