### PR TITLE
[WIP] Libressl 2.8.2

### PR DESCRIPTION
**Pull request by Gottox**

### CODE REVIEW

**Comment by biopsin** [comment]
fetchmail ?

**Comment by Gottox** [comment]
@biopsin What's your question?

**Comment by jnbr** [comment]
dependencies of libressl-devel need to be updated

**Comment by jnbr** [comment]
qt5 fails to build. [log](https://gist.github.com/jnbr/5c2eec7cac6a1fe7a9731f5a71165370)

**Comment by jnbr** [comment]
patch for qt5: https://gist.github.com/jnbr/b2a34c70dd9f615293812e87ba8ecfbc

**Comment by jnbr** [comment]
same with qt: https://gist.github.com/jnbr/fb7ad0a41ada9b0806f7527c80eda3ec

**Pull request closed without merging**
