### PR TITLE
gns3-server: update to 2.2.17.

### PR DESCRIPTION
**Pull request by tsndqst**

### CODE REVIEW

**Comment by the-maldridge** [comment]
gns3 spends most of its time not working.  I'm much more inclined to just drop the packages and people that want it can get it from pip.

**Comment by tsndqst** [comment]
I'll leave it up to you.  It must be tough decision whether to maintain an OS package or just use one from sources like pip.

I've maintained a local version of this file for 2.2.14, 2.2.16 with patches, and now 2.2.17 so I figured I'd contribute.  But if it's broken half the time I'd understand if it's removed.

**Comment by the-maldridge** [comment]
The problem that we primarily run into is that the gns3 binary often depends on specific point releases of libraries, so upgrading an unrelated python library can break it.  If you want to take over maintainership of this package you are welcome to do so, but if it stays in my name its likely going to be dropped as I no longer use it and therefore have little interest in keeping it in tree.

**Comment by tsndqst** [comment]
What's involved with maintainership?  Is there more involved than updating the template when there are new releases or things break?

**Comment by ericonr** [comment]
> What's involved with maintainership? Is there more involved than updating the template when there are new releases or things break?

Not really :)

**Comment by tsndqst** [comment]
I'll probably keep maintaining the template on my own so I might as well share my changes.  How does transfer of maintainership go?  Should I make a new PR or change the `maintainer` line in these [two](https://github.com/void-linux/void-packages/pull/26971) PRs?

**Comment by ericonr** [comment]
Just changing the maintainer line should be enough!

**Comment by ericonr** [comment]
Also add `adopt` to the commit message.

**Comment by the-maldridge** [comment]
Please make a new PR updating both packages and changing the maintainership during the upgrade.  This will ensure that the updates are processed sequentially by the builders.

**Pull request closed without merging**
