### PR TITLE
New package: prs-0.3.2

### PR DESCRIPTION
**Pull request by jcgruenhage**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

<del>This is currently sort-of broken. `prs` supports multiple backends, and the default is to use the `gpg` binary, which is broken, because unlike other
distros, Void doesn't ship gnupg2 as `gpg`. Maybe we should add alternatives to gnupg2 and gnupg to allow both as the `gpg` binary?</del>

### CODE REVIEW

**Comment by 0x5c** [comment]
@jcgruenhage Is this still broken? Void now ships gnupg2 (package is now called `gnupg`) as `gpg` and gnupg1 as `gpg1`.

**Comment by jcgruenhage** [comment]
I haven't looked at this in a while, so no idea.

**Comment by 0x5c** [comment]
Looks like there was some check failures too, but only on the cross archs. The logs are gone now, but if the failures were caused by a crate using autocfg or bindgen, we have fixes now.

**Comment by jcgruenhage** [comment]
This PR was from ages before the problems with autocfg started appearing, so it might've been something else, but either way, we'll just see whether the new release works. Updated the package and it works locally just fine.

**Comment by 0x5c** [comment]
Ah yep, it's the autocfg issue on cross. #34889 has a fix

**Comment by jcgruenhage** [comment]
Will apply those fixes later ^^

**Comment by jcgruenhage** [comment]
Updated, and tested again locally.

**Pull request merged**
