### PR TITLE
New package: guile3-3.0.2 

### PR DESCRIPTION
**Pull request by anjandev**

### CODE REVIEW

**Comment by ericonr** [comment]
For reference: 

- #16721
- #6524

I think they faced quite a few issues with the update. Looking forward to building Guix, though :D

**Comment by anjandev** [comment]
@ericonr I got it to compile and run on my machine:

```
anjan@navi ~/b/void-packages (guile)> guile
GNU Guile 3.0.2
Copyright (C) 1995-2020 Free Software Foundation, Inc.

Guile comes with ABSOLUTELY NO WARRANTY; for details type `,show w'.
This program is free software, and you are welcome to redistribute it
under certain conditions; type `,show c' for details.

Enter `,help' for help.
scheme@(guile-user)>
```

Maybe the guile guys fixed the issues the others were having?

**Comment by anjandev** [comment]
It seems like the projects that depend on guile are hard to get to compile. I will leave this open so others can build upon my work. I just wanted to play around with lisp as it is one of my favorite languages.

**Comment by fosslinux** [comment]
Maybe a guile3.0 package would be better, rather than updating guile, which every package seems to break on.

**Comment by travankor** [comment]
>I think they faced quite a few issues with the update. Looking forward to building Guix, though :D


@ericonr 

Are you interested in packaging and maintaining this? If you could that would be great! Should be similar to nix.

**Comment by ericonr** [comment]
@travankor I am, yes. It would depend on Guix building cleanly, though, because I don't think I'd be able to patch it much myself (the C part perhaps, the Guile stuff definitely not).

@fosslinux I think `guile3` would be better, but otherwise I agree. If guile 3.0 and guile 2.x don't have file conflicts, we can try to update applications to Guile 3.0 as well, if they work without issue.

**Comment by anjandev** [comment]
Érico Nogueira Rolim <notifications@github.com> writes:

> @travankor I am, yes. It would depend on Guix building cleanly,
> though, because I don't think I'd be able to patch it much myself (the
> C part perhaps, the Guile stuff definitely not). 

I will be happy to change you to the maintainer Érico. I have no
experience patching Guile stuff and don't have much use for
this package. I just wanted to play around with Guile.

**Comment by ericonr** [comment]
Yeah, I don't have that experience either :p 

We need to check if anything can be updated and if this package has file conflicts with guile2.

**Comment by ericonr** [comment]
`guile3-devel` is depending on `guile` instead of `guile3`.

**Comment by ericonr** [comment]
You also need to rename the `guile`, `guild` and `guile-snarf` binaries. We might have to look into an alternatives group, actually.

**Comment by ericonr** [comment]
I can adopt the PR, if you don't want to work on this stuff.

**Comment by anjandev** [comment]
Please adopt this PR.

**Comment by ericonr** [comment]
I'm doing everything locally, as soon as I have it in a reasonable state I can make a new PR.

**Pull request closed without merging**
