### PR TITLE
scons: update to 4.0.1.

### PR DESCRIPTION
**Pull request by CameronNemo**
Integrated into #25789

Switch to Python3.

Packages to test (`rg -l build_style=scons srcpkgs/ | awk -F '/' '{ print "- [ ] " $2 }'`):

- [x] fceux (patched in sgn's integration branch)
- [x] vdrift (patched in sgn's integration branch)
- [x] xsettingsd (built for x86_64-musl)
- [x] rmlint (built for x86_64)
- [x] mixxx (`makedepends+=" soundtouch-devel"`)
- [x] cbang (built for x86_64)
- [x] xboxdrv (cherry-pick from their stable branch)
- [x] endless-sky (built for x86_64)
- [x] pingus (steal patches from Debian)
- [x] gpick
- [x] serf (patched)
- [x] The-Powder-Toy
- [x] swiften (use vendored scons)
- [x] libffado
- [x] double-conversion
- [x] goxel
- [x] endless-sky-gl21 (built for x86_64-musl)
- [x] gpsd (cnemo build it here)
- [x] godot (@kkga  tested)

### CODE REVIEW

**Comment by sgn** [comment]
- `pingus` is python 2 only for the current release, upstream switch to cmake in development tree, Debian patched it
- `fceux`, `xboxdrv` switched to CMake as official build system, I'll take care
- `double-conversion` supports cmake, too. But, it seems like they prefer scons.

**Comment by CameronNemo** [comment]
Relevant sections of release notes with my annotations:

> NOTE: The 4.0.0 Release of SCons dropped Python 2.7 Support

This is what we want largely. Need to test build of packages using scons because the build scripts are literally python files.

> - Allow user specified location for vswhere.exe specified by VSWHERE.
> NOTE: This must be set at the time the 'msvc' 'msvs' and/or 'mslink' tool(s) are initialized to have any effect.

Does not apply to us.

> - Resolve Issue #3248 - Removing '-Wl,-Bsymbolic' from SHLIBVERSIONFLAGS
> NOTE: If your build depends on the above you must now add to your SHLIBVERSIONFLAGS

Might apply to us? We will see during rebuild I guess.

> - Fixed Github Issue 3628 - Hardcoding pickle protocol to 4 (supports python 3.4+)
> and skipping Python 3.8's new pickle protocol 5 whose main advantage is for out-of-band data buffers.
> NOTE: If you used Python 3.8 with SCons 3.0.0 or above, you may get a a pickle protocol error. Remove your
> .sconsign.dblite. You will end up with a full rebuild.

Does not apply to us (only ever used python2).

**Comment by sgn** [comment]
I think we're better:
- ship 2 packages: `scons2` and `scons`
- and either drop scons build-style or set `make_cmd=scons2` for those stubborn packages, some 20 packages isn't much anyway.
- See if any-upstream is inactive and drop their software.

**Comment by sgn** [comment]
I put my integration branch here https://github.com/sgn/void-packages/tree/scons-python-3

**Pull request closed without merging**
