### PR TITLE
Update kiwix-lib-10.0.1 kiwix-tools-3.2.0 libzim-7.2.0 zim-tools-3.1.0

### PR DESCRIPTION
**Pull request by Animeshz**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by Animeshz** [comment]
Dunno why that last test (reader.cpp) go into deadlock [have made an issue there](https://github.com/openzim/libzim/issues/670).

**Comment by Animeshz** [comment]
Why's build failing :thinking: without error? I only tried to remove a few test that were intended to happen only with the debug builds.

**Comment by paper42** [comment]
remove libzim-musl-logs.txt, I think you added it by accident

**Comment by Animeshz** [comment]
Yeah sorry, I've noticed, but this isn't really merge-able till https://github.com/openzim/libzim/issues/671 (musl-bug) I guess, I'll remove when its fixed along with a version bump or a patch.

**Pull request closed without merging**
