### PR TITLE
qscintilla-qt5 update to 2.14.1, new package python3-pyqt5-qsci

### PR DESCRIPTION
**Pull request by sgn**
@Nyx70 part of effort for QGis

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by gabriel-russo** [comment]
What is missing to this PR to merge?

**Comment by sgn** [comment]
On 2022-06-04 12:58:23-0700, Gabriel Russo ***@***.***> wrote:
> What is missing to this PR to merge?

Someone tests it for me.

-- 
Danh

**Comment by ar-jan** [comment]
I'm now running QGIS 3.28 using this. Would be great to have it committed so I can use it in PR for QGIS. Do you need any more specific testing?

**Comment by ar-jan** [comment]
Compilation on ARM no longer works:

> => python3-pyqt5-qsci-2.12.1_1: running do_configure ...
> Querying qmake about your Qt installation...
> Checking to see if the Qsci bindings can be built...
> sip-build: '/builddir/python3-pyqt5-qsci-2.12.1/Python/build/cfgtest_Qsci/./Qsci' didn't create any output
> => ERROR: python3-pyqt5-qsci-2.12.1_1: do_configure: 'sip-build --no-make ${_qt:+--qmake "$XBPS_WRAPPERDIR/sip-qmake"} --api-dir /usr/share/$_qt/qsci/api/python $configure_args --build-dir "$sip_builddir"' exited with 1
> => ERROR:   in do_configure() at common/build-style/sip-build.sh:124

I am using this in #41812 so I'm hoping this can get in.

**Comment by ar-jan** [comment]
Bump.

**Comment by ar-jan** [comment]
Hi @sgn, are you willing to take another look at this?

**Comment by classabbyamp** [comment]
updated to 2.14.1 and fixed cross (patch had the wrong package name in it)

**Comment by classabbyamp** [comment]
tested the non-python part with openscad and octave, works fine. @ar-jan can you rebase your qgis branch and test this?

**Comment by ar-jan** [comment]
Yup, I can confirm that QGIS (including PyQGIS) works with these versions.

**Pull request merged**
