### PR TITLE
python-cryptography: split python2 package

### PR DESCRIPTION
**Pull request by ahesford**
If we wanted to, we could set CRYPTOGRAPHY_DONT_BUILD_RUST for "this release only" (which probably means this minor version only) and delay the `python3-setuptools_rust` addition. That would also prevent the installation of the no-op `cryptography.hazmat.bindings._rust` module. However, given that Rust is about to become a hard requirement for this package, we might as well just get it done with now.

The `python3-pytest-subtests` package is only required for checks in `python3-cryptography` but, given the importance of `cryptography`, I think it's worth ensuring that those tests pass.

### CODE REVIEW

**Comment by ahesford** [comment]
If `setuptools_rust` upstream rejects the patch to honor RUSTFLAGS in the environment, either we patch anyway or we work around its tendency to overwrite that variable by wrapping `cargo` for cross builds:
```bash
pre_configure() {
	if [ "$CROSS_BUILD" ]; then
		cat > ${XBPS_WRAPPERDIR}/cargo <<-EOF
		#!/bin/bash
		if [[ ! "\$RUSTFLAGS" =~ "--sysroot" ]]; then
		    export RUSTFLAGS="\$RUSTFLAGS --sysroot=${XBPS_CROSS_BASE}/usr"
		fi
		exec /usr/bin/cargo "\$@"
		EOF
		chmod 755 ${XBPS_WRAPPERDIR}/cargo
	fi
}
```

**Comment by ericonr** [comment]
I strongly prefer the patch to `setuptools_rust`.

**Comment by ericonr** [comment]
We might not have to patch the package, https://github.com/PyO3/setuptools-rust/pull/103 can be included in the next release :)

**Comment by ahesford** [comment]
Closed in 76988cd6c9bba

**Pull request closed without merging**
