### PR TITLE
Replace pbp kernel package with linux package

### PR DESCRIPTION
**Pull request by Johnnynator**
- pinebookpro-kernel: remove package
- pinebookpro-base: update to 0.6.

### CODE REVIEW

**Comment by Johnnynator** [comment]
@CameronNemo 
Any objections or suggestions or objection to these changes?

@Calandracas606 abby mentioned that `linux6.5` was missing some modules that you needed?

**Comment by Johnnynator** [comment]
> Any changes needed on the image creation side of things? In principal, no opposition.

Yes, will do this on the weekend. Not sure if we even want to keep the creation of a pbp specific image.
A generic aarch64 efi image should boot just fine (which is still missing on mklive), and we could just suggest users to have a uboot (or towboot) on their SPI.

**Comment by Calandracas606** [comment]
Wifi does not work without:

CONFIG_MFD_RK8XX_I2C
CONFIG_MFD_RK8XX_SPI

All added modules in my .config:

CONFIG_INPUT_RK805_PWRKEY=y
CONFIG_PINCTRL_RK805=y
CONFIG_MFD_RK808=m
CONFIG_MFD_RK8XX_I2C=m
CONFIG_MFD_RK8XX_SPI=m
CONFIG_REGULATOR_RK808=m
CONFIG_RTC_DRV_RK808=m
CONFIG_COMMON_CLK_RK808=m

Some of these modules were included in previous kernels .config, but were removed in 6.5

**Comment by Calandracas606** [comment]
> > Any changes needed on the image creation side of things? In principal, no opposition.
> 
> Yes, will do this on the weekend. Not sure if we even want to keep the creation of a pbp specific image. A generic aarch64 efi image should boot just fine (which is still missing on mklive), and we could just suggest users to have a uboot (or towboot) on their SPI.

Agreed.

TowBoot's sentiment is that [the distribution shouldn't be managing the firmware used to boot the system.](https://tow-boot.org/FAQ.html)

Additionally, I believe that the u-boot image that we distribute isn't ideal, and has some problems with "suspend to ram" (or rockchip's fake suspend to ram). I haven't completely pinned that issue down to our u-boot image, but it was resolved when I switched to [megi's u-boot images and rk2aw bootloader](https://xnux.eu/rk2aw/).

Ultimately, I am of the opinion that it should be up to the user to install and manage their own boot-loader.

Having a generic aarch64 image is likely best, generating an appropriate extlinux

I have a successfully running pbp musl, using rk2aw in SPI, megi's uboot on emmc, generic base-system, linux, u-boot-menu + pinebookpro-firmware. In the past, I've had success booting with Towboot -> grub -> EFI

**Comment by classabbyamp** [comment]
anything needed to merge this?

**Pull request merged**
