### PR TITLE
firefox: update to 81.0.

### PR DESCRIPTION
**Pull request by Duncaen**
x86_64-glibc works, currently building for aarch64 and then building x86_64-musl which I can test.

### CODE REVIEW

**Comment by Duncaen** [comment]
* x86_64 works
* x86_64-musl works
* aarch64-musl builds
* i686 builds

**Comment by zdykstra** [comment]
ppc64le - glibc works

**Comment by Piraty** [comment]
aarch64-musl works

**Comment by ericonr** [comment]
Merged in ad854810caf9afcc98d792db65ffad0ad48ecfca

**Pull request closed without merging**
