### PR TITLE
stern: update to 1.19.0.

### PR DESCRIPTION
**Pull request by TeddyDD**
Switch to maintained fork. Ping @knusbaum

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by TeddyDD** [comment]
```
collect2: fatal error: cannot find 'ld'
```

is this CI related issue or I screwed up something?

**Comment by ericonr** [comment]
grep for `-fuse-ld=bfd` in srcpkgs for a workaround.

**Comment by TeddyDD** [comment]
Thanks!

**Comment by ericonr** [comment]
For the record, you can just set `LDFLAGS`, no need to `export` :)

I have fixed that and will merge in a bit.

**Pull request merged**
