### PR TITLE
WIP: Geoip drop

### PR DESCRIPTION
**Pull request by fosslinux**
1. `mirrorbits` does not compile -- no idea why, have tried quite a few things
2. `qomui`'s tests do not pass

@sgn one of the last noarch things

`geoip-data` been deprecated by upstream for 2 years now. Is noarch. Distfiles
are no longer found (can only be accessed behind a license). No packages
now use it after this PR. If someone really wants an up-to-date legacy database, they
can use geoipupdate (still included in the repo).

### CODE REVIEW

**Comment by mobinmob** [comment]
Please consider creating a package from https://mailfud.org/geoip-legacy/ in order to provide geoip data in the legacy format.
Archlinux does it:
https://github.com/archlinux/svntogit-packages/tree/packages/geoip-database/trunk

**Comment by fosslinux** [comment]
If other maintainers are happy with this, go ahead.

**Comment by the-maldridge** [comment]
I'm relatively confident that those files are non-distributable and I'll be they're in violation of the maxmind license.  As for mirrorbits, feel free to drop it.  It was packaged to support auto.voidlinux.org, a service that no longer exists.

**Comment by q66** [comment]
oops, overlooked this PR

well, this is all done in master now, so...

**Comment by fosslinux** [comment]
thanks

**Pull request closed without merging**
