### PR TITLE
senpai: update homepage and distfiles URL.

### PR DESCRIPTION
**Pull request by mhmdanas**
The repository has been moved, as https://git.sr.ht/~taiite/senpai/tree/5e771831a3196f49d4417e0f913da64a251e8cb5/item/README.md shows.

@realcharmer

#### Testing the changes
- I tested the changes in this PR: **YES**|**briefly**|**NO**

### CODE REVIEW

**Comment by mhmdanas** [comment]
Lint check fails because of long URL in commit message, it can be ignored.

**Comment by realcharmer** [comment]
You also have to increase the package revision number.

**Comment by realcharmer** [comment]
> Lint check fails because of long URL in commit message, it can be ignored.

Is it really necessary to include the hyperlink in the commit message body?

**Comment by mhmdanas** [comment]
> You also have to increase the package revision number.

Not necessarily, I don't think a homepage update warrants a revbump.

> Is it really necessary to include the hyperlink in the commit message body?

I just did it to show the evidence of the move, but it's not strictly necessary I guess.

**Comment by realcharmer** [comment]
> Not necessarily, I don't think a homepage update warrants a revbump.

I reckon any template change without a version bump is a new revision.

**Comment by mhmdanas** [comment]
https://github.com/void-linux/void-packages/pull/44385#issuecomment-1589277787, but I don't care much either way.

**Comment by realcharmer** [comment]
If it's fine with the maintainers and the linter won't complain, it's fine with me as well.

**Comment by realcharmer** [comment]
Also thanks for the PR, good job 👍

**Pull request merged**
