### PR TITLE
tarpaulin: update to 0.17.0.

### PR DESCRIPTION
**Pull request by jcgruenhage**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Tests working on 32bit but failing on 64bit seems rather unexpected.

**Comment by jcgruenhage** [comment]
yeah.. The thing is, I built the package and it works as expected locally. When I check out the release in a git repo and run the tests on my workstation with cargo directly, I get similar failures, so this is not really an issue with the packaging I think? Not sure what to do about this.

**Comment by ericonr** [comment]
Take a look if upstream has issue reports about the failures, or how their CI runs tests :D

**Comment by jcgruenhage** [comment]
Good call on checking their CI.. I had checked their docs and not found anything, but from their CI, it seems like they require the tests to run single-threaded, which we can pass in via make_check_args. I'm running the tests locally rn, if it works I'll push it once they're done.

**Comment by jcgruenhage** [comment]
Okay, now this build timed out? This doesn't make much sense to me, it worked fine locally.

**Pull request closed without merging**
