### PR TITLE
[WIP] Linux 5.16

### PR DESCRIPTION
**Pull request by ericonr**
#### Testing the changes
- I tested the changes in this PR: **NO**

I have built it but not booted into it yet.

The only config that has been updated is the x86-64 one, whose diffconfig is:

```
masterdir/builddir/linux-5.16/scripts/diffconfig srcpkgs/linux{5.15,5.16}/files/x86_64-dotconfig
-88EU_AP_MODE y
-BLK_DEV_CRYPTOLOOP m
-CLK_SP810 y
-DRM_I810 n
-HARDENED_USERCOPY_FALLBACK y
-ICST y
-INLINE_READ_UNLOCK y
-INLINE_READ_UNLOCK_IRQ y
-INLINE_SPIN_UNLOCK_IRQ y
-INLINE_WRITE_UNLOCK y
-INLINE_WRITE_UNLOCK_IRQ y
-IR_SIR n
-KPROBES_SANITY_TEST n
-MEMORY_HOTPLUG_SPARSE y
-MFD_TPS80031 n
-X86_PLATFORM_DRIVERS_INTEL y
 MCTP m -> y
 SCSI_COMMON y -> m
+ADRF6780 m
+ADXL313 m
+ADXL313_I2C m
+ADXL313_SPI m
+ADXL355 m
+ADXL355_I2C m
+ADXL355_SPI m
+AMT m
+ARCH_CORRECT_STACKTRACE_ON_KRETPROBE y
+BARCO_P50_GPIO m
+BRCMSMAC_LEDS y
+CC_IMPLICIT_FALLTHROUGH "-Wimplicit-fallthrough=5"
+CEC_GPIO m
+CEC_PIN y
+CEC_PIN_ERROR_INJ n
+CS_DSP m
+DAMON_PADDR y
+DAMON_RECLAIM y
+DEBUG_PREEMPT y
+DM_AUDIT y
+DRM_DEBUG_MODESET_LOCK n
+DRM_I915_PXP y
+DYNAMIC_SIGFRAME y
+EXCLUSIVE_SYSTEM_RAM y
+HAVE_SAMPLE_FTRACE_DIRECT y
+HAVE_SAMPLE_FTRACE_DIRECT_MULTI y
+HID_NINTENDO m
+HID_XIAOMI m
+HT16K33 m
+ICE_SWITCHDEV y
+INTEL_ISHTP_ECLITE m
+INTEL_MEI_PXP m
+IPMI_IPMB m
+KEYBOARD_CYPRESS_SF m
+KVM_EXTERNAL_WRITE_TRACKING y
+LINEDISP m
+MAX31865 m
+MT7921S m
+MT7921_COMMON m
+NETFILTER_EGRESS y
+NETFILTER_SKIP_EGRESS y
+NET_DSA_TAG_RTL8_4 m
+NET_VENDOR_ASIX y
+NINTENDO_FF y
+NVIDIA_WMI_EC_BACKLIGHT m
+PAGE_SIZE_LESS_THAN_64KB y
+PREEMPTION y
+PREEMPT_BUILD y
+PREEMPT_COUNT y
+PREEMPT_DYNAMIC y
+PREEMPT_RCU y
+PREEMPT_TRACER n
+RPMSG_TTY m
+RTW89 m
+RTW89_8852AE m
+RTW89_CORE m
+RTW89_DEBUGFS n
+RTW89_DEBUGMSG n
+RTW89_PCI m
+SCD4X m
+SCHED_CLUSTER y
+SCSI_UFS_HWMON y
+SENSEAIR_SUNRISE_CO2 m
+SENSORS_MAX6620 m
+SND_AMD_ASOC_RENOIR m
+SND_SOC_AMD_ACP6x m
+SND_SOC_AMD_ACP_COMMON m
+SND_SOC_AMD_ACP_I2S m
+SND_SOC_AMD_ACP_PCM m
+SND_SOC_AMD_LEGACY_MACH m
+SND_SOC_AMD_MACH_COMMON m
+SND_SOC_AMD_SOF_MACH m
+SND_SOC_AMD_VANGOGH_MACH m
+SND_SOC_AMD_YC_MACH m
+SND_SOC_CS35L41_I2C m
+SND_SOC_CS35L41_SPI m
+SND_SOC_INTEL_SOF_ES8336_MACH m
+SND_SOC_MAX98520 m
+SND_SOC_NAU8821 m
+SND_SOC_RT1019 m
+SND_SOC_RT5682S m
+SND_SOC_RT9120 m
+SPI_AX88796C m
+SPI_AX88796C_COMPRESSION n
+STRICT_SIGALTSTACK_SIZE n
+UNINLINE_SPIN_UNLOCK y
+VIDEO_HI846 m
+VIDEO_OV13B10 m
+VIRTIO_PCI_LIB_LEGACY m
+XEN_PCI_STUB y
+XZ_DEC_MICROLZMA n
```

[ci skip]

### CODE REVIEW

**Comment by ahesford** [comment]
Does zfs even support 5.16 yet?

**Comment by ericonr** [comment]
> Does zfs even support 5.16 yet?

Not entirely :P 
Am running a borked build, will backport those locally and try again.

https://github.com/openzfs/zfs/issues/12971

**Comment by Vistaus** [comment]
Did you test yet? I would really like to get 5.16 as it brings quite a few AMD improvements that my AMD Ryzen system can really use.

**Comment by ericonr** [comment]
I've tested it locally with a patch applied to ZFS and things work normally.

Need to update configs for other archs now.

**Comment by leahneukirchen** [comment]
Also bump linux-mainline

**Comment by dm17** [comment]
> Did you test yet? I would really like to get 5.16 as it brings quite a few AMD improvements that my AMD Ryzen system can really use.

I'm also waiting on it for AMDGPU fixes. Thanks everyone!

**Comment by Vistaus** [comment]
Still waiting for this upgrade for the AMDGPU fixes and improvements. For a rolling release, kernel upgrades seem to be very slow on Void. :/

**Comment by Lolzen** [comment]
> Still waiting for this upgrade for the AMDGPU fixes and improvements. For a rolling release, kernel upgrades seem to be very slow on Void. :/

There's nothing holding you back taking the template commit and building the package yourself by following the xbps-src instructions.

**Comment by Vistaus** [comment]
> > Still waiting for this upgrade for the AMDGPU fixes and improvements. For a rolling release, kernel upgrades seem to be very slow on Void. :/
> 
> There's nothing holding you back taking the template commit and building the package yourself by following the xbps-src instructions.

Thanks, I'll look into that.

**Comment by dm17** [comment]
> Still waiting for this upgrade for the AMDGPU fixes and improvements. For a rolling release, kernel upgrades seem to be very slow on Void. :/

Me too, but I think Void is making the right choice generally. As I understand it, they deliberately skip the first ~few versions of new kernels for the sake of stability and testing. AMD's incompetence with Linux bugs & support lately is kind of an edge case.

**Comment by zdykstra** [comment]
There's also https://github.com/openzfs/zfs/issues/13042 - OpenZFS has broken SIMD acceleration for native encryption. It'll take a patch to ZFS to resolve.

**Comment by ericonr** [comment]
aarch64

```
-88EU_AP_MODE y
-BLK_DEV_CRYPTOLOOP m
-CRYPTO_SIMD m
-HANDLE_DOMAIN_IRQ y
-HARDENED_USERCOPY_FALLBACK n
-HAVE_ARCH_PFN_VALID y
-HAVE_S3C_RTC y
-ICST y
-IR_SIR m
-KPROBES_SANITY_TEST n
-MEMORY_HOTPLUG_SPARSE y
-MFD_INTEL_PMT m
-MFD_TPS80031 n
-OF_NET y
-SUN8I_A83T_CCU n
 MCTP m -> y
+ADRF6780 n
+ADXL313 m
+ADXL313_I2C m
+ADXL313_SPI m
+ADXL355 m
+ADXL355_I2C m
+ADXL355_SPI m
+AMT m
+APPLE_MAILBOX m
+ARCH_CORRECT_STACKTRACE_ON_KRETPROBE y
+ARM64_ERRATUM_2054223 y
+ARM64_ERRATUM_2067961 y
+ARM64_ERRATUM_2119858 y
+ARM64_ERRATUM_2139208 y
+ARM64_ERRATUM_2224489 y
+ARM64_ERRATUM_2253138 y
+ARM64_WORKAROUND_TRBE_OVERWRITE_FILL_MODE y
+ARM64_WORKAROUND_TRBE_WRITE_OUT_OF_RANGE y
+ARM64_WORKAROUND_TSB_FLUSH_FAILURE y
+BCM7120_L2_IRQ y
+BRCMSMAC_LEDS y
+CC_IMPLICIT_FALLTHROUGH "-Wimplicit-fallthrough=5"
+CLK_ICST y
+CLK_IMX8ULP m
+COMMON_CLK_MT8195 y
+CORESIGHT_CPU_DEBUG_DEFAULT_ON n
+CRYPTO_DEV_KEEMBAY_OCS_ECC m
+DAMON_PADDR y
+DAMON_RECLAIM y
+DM_AUDIT y
+DRM_DEBUG_MODESET_LOCK n
+DRM_PANEL_EDP m
+DRM_PANEL_SAMSUNG_S6D27A1 m
+DRM_PANEL_SHARP_LS060T1SX01 m
+DRM_V3D m
+EROFS_FS_ZIP_LZMA y
+EXCLUSIVE_SYSTEM_RAM y
+GPIO_ZYNQMP_MODEPIN m
+HAVE_KVM y
+HAVE_POSIX_CPU_TIMERS_TASK_WORK y
+HID_NINTENDO m
+HID_XIAOMI m
+I2C_APPLE m
+ICE_SWITCHDEV y
+IMX8QXP_ADC m
+IMX_DSP_REMOTEPROC m
+IPMI_IPMB m
+KEYBOARD_CYPRESS_SF m
+LINEDISP m
+MAX31865 m
+MLXREG_LC m
+MT7921S m
+MT7921_COMMON m
+NEED_PER_CPU_PAGE_FIRST_CHUNK y
+NETFILTER_EGRESS y
+NETFILTER_SKIP_EGRESS y
+NET_DSA_TAG_RTL8_4 m
+NET_VENDOR_ASIX y
+NINTENDO_FF y
+NITRO_ENCLAVES m
+PAGE_SIZE_LESS_THAN_64KB y
+PCIE_APPLE m
+PCIE_APPLE_MSI_DOORBELL_ADDR 0xfffff000
+PCIE_QCOM_EP m
+PHY_HI3670_PCIE m
+PINCTRL_APPLE_GPIO m
+PINCTRL_MT7986 y
+PINCTRL_QCM2290 m
+PINCTRL_SM6350 m
+POSIX_CPU_TIMERS_TASK_WORK y
+PREEMPT_VOLUNTARY_BUILD y
+QCM_GCC_2290 m
+QCOM_SPM m
+QCOM_STATS m
+RPMSG_TTY m
+RTW89 m
+RTW89_8852AE m
+RTW89_CORE m
+RTW89_DEBUGFS n
+RTW89_DEBUGMSG n
+RTW89_PCI m
+SCD4X m
+SCHED_CLUSTER y
+SCSI_UFS_HWMON y
+SC_CAMCC_7280 m
+SC_LPASSCC_7280 m
+SENSEAIR_SUNRISE_CO2 m
+SENSORS_MAX6620 m
+SND_AUDIO_GRAPH_CARD2 m
+SND_AUDIO_GRAPH_CARD2_CUSTOM_SAMPLE m
+SND_SOC_CS35L41_I2C m
+SND_SOC_CS35L41_SPI m
+SND_SOC_MAX98520 m
+SND_SOC_MT8195_MT6359_RT1011_RT5682 m
+SND_SOC_NAU8821 m
+SND_SOC_QDSP6_APM m
+SND_SOC_QDSP6_APM_DAI m
+SND_SOC_QDSP6_APM_LPASS_DAI m
+SND_SOC_QDSP6_PRM m
+SND_SOC_QDSP6_PRM_LPASS_CLOCKS m
+SND_SOC_ROCKCHIP_I2S_TDM m
+SND_SOC_RT1011 m
+SND_SOC_RT9120 m
+SND_SOC_SOF_COMPRESS y
+SND_TEST_COMPONENT m
+SPI_AX88796C m
+SPI_AX88796C_COMPRESSION n
+SPI_CADENCE_XSPI m
+VIDEO_HI846 m
+VIDEO_OV13B10 m
+VIRTIO_PCI_LIB_LEGACY y
+VMAP_PFN y
+XZ_DEC_MICROLZMA y
```

ppc64le

```
-88EU_AP_MODE y
-BLK_DEV_CRYPTOLOOP m
-CLK_SP810 n
-HARDENED_USERCOPY_FALLBACK y
-ICST y
-IR_SIR n
-KPROBES_SANITY_TEST n
-MEMORY_HOTPLUG_SPARSE y
-MFD_INTEL_PMT n
-MFD_TPS80031 y
-OF_NET y
-REGULATOR_TPS80031 m
-RTC_DRV_TPS80031 m
 CC_VERSION_TEXT "powerpc64le-linux-gnu-gcc (GCC) 10.2.1 20201203" -> "powerpc64le-linux-musl-gcc (GCC) 10.2.1 20201203"
 MCTP m -> y
 SCSI_COMMON y -> m
+ADRF6780 n
+ADXL313 m
+ADXL313_I2C m
+ADXL313_SPI m
+ADXL355 m
+ADXL355_I2C m
+ADXL355_SPI m
+AMT m
+ARCH_HAS_CC_PLATFORM y
+ARCH_OPTIONAL_KERNEL_RWX_DEFAULT y
+BRCMSMAC_LEDS y
+CC_IMPLICIT_FALLTHROUGH "-Wimplicit-fallthrough=5"
+DAMON_PADDR y
+DAMON_RECLAIM y
+DM_AUDIT y
+DRM_DEBUG_MODESET_LOCK n
+DRM_PANEL_EDP m
+DRM_PANEL_SAMSUNG_S6D27A1 m
+DRM_PANEL_SHARP_LS060T1SX01 m
+EXCLUSIVE_SYSTEM_RAM y
+HID_NINTENDO m
+HID_XIAOMI m
+ICE_SWITCHDEV y
+IPMI_IPMB m
+KEYBOARD_CYPRESS_SF m
+LINEDISP m
+MAX31865 m
+MT7921S m
+MT7921_COMMON m
+NETFILTER_EGRESS y
+NETFILTER_SKIP_EGRESS y
+NET_DSA_TAG_RTL8_4 m
+NET_VENDOR_ASIX y
+NINTENDO_FF y
+PAGE_SIZE_LESS_THAN_64KB y
+PREEMPT_VOLUNTARY_BUILD y
+RPMSG_TTY m
+RTW89 m
+RTW89_8852AE m
+RTW89_CORE m
+RTW89_DEBUGFS n
+RTW89_DEBUGMSG n
+RTW89_PCI m
+SCD4X m
+SCSI_UFS_HWMON y
+SENSEAIR_SUNRISE_CO2 m
+SENSORS_MAX6620 m
+SND_AUDIO_GRAPH_CARD2 m
+SND_AUDIO_GRAPH_CARD2_CUSTOM_SAMPLE m
+SND_SOC_CS35L41_I2C m
+SND_SOC_CS35L41_SPI m
+SND_SOC_MAX98520 m
+SND_SOC_NAU8821 m
+SND_SOC_RT9120 m
+SND_TEST_COMPONENT m
+SPI_AX88796C m
+SPI_AX88796C_COMPRESSION n
+SPI_CADENCE_XSPI m
+VIDEO_HI846 m
+VIDEO_OV13B10 m
+VIRTIO_PCI_LIB_LEGACY m
+XZ_DEC_MICROLZMA n
```

i686

```
-88EU_AP_MODE y
-ACPI_THERMAL_REL m
-ARCH_ENABLE_MEMORY_HOTPLUG y
-BLK_DEV_CRYPTOLOOP m
-CLK_SP810 n
-DRM_I810 n
-HARDENED_USERCOPY_FALLBACK y
-ICST y
-INLINE_READ_UNLOCK y
-INLINE_READ_UNLOCK_IRQ y
-INLINE_SPIN_UNLOCK_IRQ y
-INLINE_WRITE_UNLOCK y
-INLINE_WRITE_UNLOCK_IRQ y
-INT3406_THERMAL m
-INT340X_THERMAL m
-INTEL_SOC_DTS_IOSF_CORE m
-IR_SIR n
-KPROBES_SANITY_TEST n
-MFD_TPS80031 n
-X86_PLATFORM_DRIVERS_INTEL y
 MCTP m -> y
 SCSI_COMMON y -> m
 SND_SOC_ES8316 n -> m
+ADRF6780 n
+ADXL313 m
+ADXL313_I2C m
+ADXL313_SPI m
+ADXL355 m
+ADXL355_I2C m
+ADXL355_SPI m
+AMT m
+ARCH_CORRECT_STACKTRACE_ON_KRETPROBE y
+BARCO_P50_GPIO m
+BRCMSMAC_LEDS y
+CC_IMPLICIT_FALLTHROUGH "-Wimplicit-fallthrough=5"
+CEC_GPIO m
+CEC_PIN y
+CEC_PIN_ERROR_INJ n
+CPU_SUP_VORTEX_32 y
+CS_DSP m
+DAMON_PADDR y
+DAMON_RECLAIM y
+DEBUG_PREEMPT y
+DM_AUDIT y
+DRM_DEBUG_MODESET_LOCK n
+DRM_I915_PXP y
+DYNAMIC_SIGFRAME y
+EXCLUSIVE_SYSTEM_RAM y
+HID_NINTENDO m
+HID_XIAOMI m
+HT16K33 m
+INTEL_MEI_PXP m
+IPMI_IPMB m
+KEYBOARD_CYPRESS_SF m
+LINEDISP m
+MAX31865 m
+MT7921S m
+MT7921_COMMON m
+NETFILTER_EGRESS y
+NETFILTER_SKIP_EGRESS y
+NET_DSA_TAG_RTL8_4 m
+NET_VENDOR_ASIX y
+NINTENDO_FF y
+NVIDIA_WMI_EC_BACKLIGHT m
+PAGE_SIZE_LESS_THAN_64KB y
+PREEMPTION y
+PREEMPT_BUILD y
+PREEMPT_COUNT y
+PREEMPT_DYNAMIC y
+PREEMPT_RCU y
+PREEMPT_TRACER n
+RPMSG_TTY m
+RTW89 m
+RTW89_8852AE m
+RTW89_CORE m
+RTW89_DEBUGFS n
+RTW89_DEBUGMSG n
+RTW89_PCI m
+SCD4X m
+SCHED_CLUSTER y
+SCSI_UFS_HWMON y
+SENSEAIR_SUNRISE_CO2 m
+SENSORS_MAX6620 m
+SND_AMD_ASOC_RENOIR m
+SND_SOC_AMD_ACP6x m
+SND_SOC_AMD_ACP_COMMON m
+SND_SOC_AMD_ACP_I2S m
+SND_SOC_AMD_ACP_PCM m
+SND_SOC_AMD_LEGACY_MACH m
+SND_SOC_AMD_MACH_COMMON m
+SND_SOC_AMD_SOF_MACH m
+SND_SOC_AMD_VANGOGH_MACH m
+SND_SOC_AMD_YC_MACH m
+SND_SOC_CS35L41_I2C m
+SND_SOC_CS35L41_SPI m
+SND_SOC_INTEL_SOF_ES8336_MACH m
+SND_SOC_MAX98520 m
+SND_SOC_NAU8821 m
+SND_SOC_RT1019 m
+SND_SOC_RT5682S m
+SND_SOC_RT9120 m
+SPI_AX88796C m
+SPI_AX88796C_COMPRESSION n
+STRICT_SIGALTSTACK_SIZE n
+UNINLINE_SPIN_UNLOCK y
+VIDEO_HI846 m
+VIDEO_OV13B10 n
+VIRTIO_PCI_LIB_LEGACY m
+XZ_DEC_MICROLZMA n
```

ppc64

```
-88EU_AP_MODE y
-BLK_DEV_CRYPTOLOOP m
-CLK_SP810 n
-HARDENED_USERCOPY_FALLBACK y
-ICST y
-IR_SIR n
-KPROBES_SANITY_TEST n
-MEMORY_HOTPLUG_SPARSE y
-MFD_INTEL_PMT m
-MFD_TPS80031 y
-OF_NET y
-REGULATOR_TPS80031 m
-RTC_DRV_TPS80031 m
 CC_VERSION_TEXT "powerpc64-linux-gnu-gcc (GCC) 10.2.1 20201203" -> "powerpc64-linux-musl-gcc (GCC) 10.2.1 20201203"
 MCTP m -> y
 SCSI_COMMON y -> m
+ADRF6780 n
+ADXL313 m
+ADXL313_I2C m
+ADXL313_SPI m
+ADXL355 m
+ADXL355_I2C m
+ADXL355_SPI m
+AMT m
+ARCH_HAS_CC_PLATFORM y
+ARCH_OPTIONAL_KERNEL_RWX_DEFAULT y
+BRCMSMAC_LEDS y
+CC_IMPLICIT_FALLTHROUGH "-Wimplicit-fallthrough=5"
+DAMON_PADDR y
+DAMON_RECLAIM y
+DM_AUDIT y
+DRM_DEBUG_MODESET_LOCK n
+DRM_PANEL_EDP m
+DRM_PANEL_SAMSUNG_S6D27A1 m
+DRM_PANEL_SHARP_LS060T1SX01 m
+EXCLUSIVE_SYSTEM_RAM y
+HID_NINTENDO m
+HID_XIAOMI m
+ICE_SWITCHDEV y
+IPMI_IPMB m
+KEYBOARD_CYPRESS_SF m
+LINEDISP m
+MAX31865 m
+MT7921S m
+MT7921_COMMON m
+NETFILTER_EGRESS y
+NETFILTER_SKIP_EGRESS y
+NET_DSA_TAG_RTL8_4 m
+NET_VENDOR_ASIX y
+NINTENDO_FF y
+PAGE_SIZE_LESS_THAN_64KB y
+PREEMPT_VOLUNTARY_BUILD y
+RPMSG_TTY m
+RTW89 m
+RTW89_8852AE m
+RTW89_CORE m
+RTW89_DEBUGFS n
+RTW89_DEBUGMSG n
+RTW89_PCI m
+SCD4X m
+SCSI_UFS_HWMON y
+SENSEAIR_SUNRISE_CO2 m
+SENSORS_MAX6620 m
+SND_AUDIO_GRAPH_CARD2 m
+SND_AUDIO_GRAPH_CARD2_CUSTOM_SAMPLE m
+SND_SOC_CS35L41_I2C m
+SND_SOC_CS35L41_SPI m
+SND_SOC_MAX98520 m
+SND_SOC_NAU8821 m
+SND_SOC_RT9120 m
+SND_TEST_COMPONENT m
+SPI_AX88796C m
+SPI_AX88796C_COMPRESSION n
+SPI_CADENCE_XSPI m
+VIDEO_HI846 m
+VIDEO_OV13B10 n
+VIRTIO_PCI_LIB_LEGACY m
+XZ_DEC_MICROLZMA n
```

ppc

```
-88EU_AP_MODE y
-BLK_DEV_CRYPTOLOOP n
-CLK_SP810 n
-HARDENED_USERCOPY_FALLBACK y
-HID_PLAYSTATION m
-ICST n
-IR_SIR n
-KPROBES_SANITY_TEST n
-MFD_INTEL_PMT n
-MFD_TPS80031 n
-OF_NET y
-PLAYSTATION_FF y
 CC_VERSION_TEXT "powerpc-linux-gnu-gcc (GCC) 10.2.1 20201203" -> "powerpc-linux-musl-gcc (GCC) 10.2.1 20201203"
 MCTP m -> y
+ADRF6780 n
+ADXL313_I2C n
+ADXL313_SPI n
+ADXL355_I2C n
+ADXL355_SPI n
+AMT m
+ARCH_OPTIONAL_KERNEL_RWX_DEFAULT y
+CC_IMPLICIT_FALLTHROUGH "-Wimplicit-fallthrough=5"
+DAMON_PADDR y
+DAMON_RECLAIM y
+DM_AUDIT y
+DRM_DEBUG_MODESET_LOCK n
+DRM_PANEL_EDP n
+DRM_PANEL_SAMSUNG_S6D27A1 m
+EXCLUSIVE_SYSTEM_RAM y
+HAVE_STATIC_CALL y
+HID_NINTENDO m
+HID_XIAOMI m
+KEYBOARD_CYPRESS_SF m
+MAX31865 m
+MT7921S m
+MT7921_COMMON m
+NETFILTER_EGRESS y
+NETFILTER_SKIP_EGRESS y
+NET_VENDOR_ASIX y
+NINTENDO_FF y
+PAGE_SIZE_LESS_THAN_64KB y
+PREEMPT_VOLUNTARY_BUILD y
+RTW89 m
+RTW89_8852AE m
+RTW89_CORE m
+RTW89_DEBUGFS n
+RTW89_DEBUGMSG n
+RTW89_PCI m
+SCD4X m
+SCSI_UFS_HWMON y
+SENSEAIR_SUNRISE_CO2 m
+SENSORS_MAX6620 m
+SPI_AX88796C m
+SPI_AX88796C_COMPRESSION n
+STATIC_CALL_SELFTEST n
+VIDEO_HI846 m
+VIDEO_OV13B10 n
+VIRTIO_PCI_LIB_LEGACY m
+XZ_DEC_MICROLZMA n
```

**Comment by ahesford** [comment]
The four ZFS patches herein were merged upstream in https://github.com/openzfs/zfs/pull/13058/ for a v2.1.3 staging branch, so pulling them here seems ok to me.

**Comment by Vistaus** [comment]
It took a while, but thank you very much for pushing the update! 🙂

**Pull request merged**
