### PR TITLE
Thunderbird: update to 78.9.1

### PR DESCRIPTION
**Pull request by dkwo**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

[ci skip]

### CODE REVIEW

**Comment by ericonr** [comment]
Remember to skip CI for packages this big ;)

I will wait for GNOME to be done in builders. Thanks!

**Comment by dkwo** [comment]
Sorry about that.
Btw, it builds fine on `x86_64`.

**Comment by ericonr** [comment]
You want to have two commits, one for each package.

**Comment by ericonr** [comment]
Sorry, ended up splitting the commits before I saw you had updated the PR.

Thanks though :)

**Pull request closed without merging**
