### PR TITLE
.github/workflows: update actions/checkout to v2

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Comment by ericonr** [comment]
v2 action depends on nodejs and is all kinds of broken :p

**Comment by sgn** [comment]
> v2 action depends on nodejs and is all kinds of broken :p

Doesn't v1 also depend of nodejs? And isn't nodejs always available is GitHub Action.

**Comment by smorimoto** [comment]
@ericonr Yes. ​So this can't be merged at this time...

@sgn The source for v1 was not public, but it was Bash, not Node.js.

**Comment by RossComputerGuy** [comment]
Do you think you can try to rebuild some packages? I'm noticing some issues with this CI stuff on my fork and I'd like to make sure I'm not the only one having issues. Only linting and x86_64 seems to build right.

Affected packages (with architecture and issue):
* `libtool` on i686: autoconfig mismatch
* `cross-armv7l-linux-gnueabihf` on armv7l: invalid gcc arguments
* `cross-vpkg-dummy` on aarch64: public key import asked

**Comment by the-maldridge** [comment]
Closing due to the previously mentioned nodejs issues.

**Pull request closed without merging**
