### PR TITLE
New package: zsh-history-substring-search-1.0.1

### LINKED ISSUE #12092: Package Request: zsh-history-substring-search
https://github.com/zsh-users/zsh-history-substring-search

### PR DESCRIPTION
**Pull request by yjp20**
closes #12092

### CODE REVIEW

**Comment by youngjinpark20** [comment]
BSD License is included within the shell script. Does it still need a separate license?

**Comment by sirikid** [comment]
Manual.md says yes

**Comment by youngjinpark20** [comment]
It's true that's what it says, but the reason why that rule is there is that these licenses require a copy of the license to be also supplied with the program. 

If it's a binary, like the the manual indicates, then indeed we have to include the license, since it would get destroyed in the compiling process. However, in this case it's an interpreted shell script, which means the license remains intact. It's not legally necessary to include licenses like it is with binaries in this scenario.

**Comment by sirikid** [comment]
There are two other similar packages ([zsh-autosuggestions](https://github.com/void-linux/void-packages/blob/b493c6e2975ef32e4f697ccb3f634670f9eb9e88/srcpkgs/zsh-autosuggestions/template) and [zsh-syntax-highlighting](https://github.com/void-linux/void-packages/blob/b493c6e2975ef32e4f697ccb3f634670f9eb9e88/srcpkgs/zsh-syntax-highlighting/template)) and both install their own license.

**Comment by youngjinpark20** [comment]
Those similar packages provide the license in their way. This package does it differently in a way that's also legally acceptable.

**Comment by PillTime** [comment]
I know this is a bit old, but would it be possible to add
```
sed -E '/#{60,}/,/#{60,}/!d;1,3d' ${pkgname}.zsh | head -n -2 > LICENSE
vlicense LICENSE
```
to the do_install() function?

It's a bit hacky, but it works.

**Pull request closed without merging**
