### PR TITLE
chromium: update to 90.0.4430.72.

### PR DESCRIPTION
**Pull request by pbui**
[ci skip]

- Built for x86_64, i686, x86_64-musl.
- Tested on x86_64.

- Removes API key.  Popups a warning message on startup that certain features are disabled, but most normal browsing continues to work.  The message links the following: https://www.chromium.org/developers/how-tos/api-keys

- Also update chromium-widevine.

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by pbui** [comment]
@q66 Please review the changes to `xxx-ppc64le-support.patch`.

@ericonr The musl build fails due to the use of `pthread_getname_np` in `third_party/perfetto/include/perfetto/ext/base/thread_utils.h`

**Comment by ericonr** [comment]
```diff
diff --git a/include/perfetto/ext/base/thread_utils.h b/include/perfetto/ext/base/thread_utils.h
index fb47d3d..d346e66 100644
--- a/include/perfetto/ext/base/thread_utils.h
+++ b/include/perfetto/ext/base/thread_utils.h
@@ -58,7 +58,7 @@ inline bool MaybeSetThreadName(const std::string& name) {
 
 inline bool GetThreadName(std::string& out_result) {
   char buf[16] = {};
-#if PERFETTO_BUILDFLAG(PERFETTO_OS_ANDROID)
+#if 1
   if (prctl(PR_GET_NAME, buf) != 0)
     return false;
 #else
```

**Comment by pbui** [comment]
@ericonr x86_64-musl builds now.  I have uploaded my build here: https://h4x0r.space/

**Comment by q66** [comment]
made it build on ppc64le-musl, but it does not work (tabs crash) - was it tested on x86_64-musl at all?

**Comment by ericonr** [comment]
Confirmed working on x86_64-musl with youtube and tinkercad

**Pull request closed without merging**
