### PR TITLE
Update ESR Firefox to the new major release (128)

### PR DESCRIPTION
**Pull request by robertek**
[ci skip]

#### Testing the changes
- I tested the changes in this PR: **YES**
- I'm using it on my native system now (x86_64, glibc).

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64 (cross)
  - x86_64
  - x86_64-musl
  - i686

#### Notes
- In this update I have synced firefox-esr-128 package with current firefox-128 package to as much as possible similar state. I don't expect the esr version is much different in this stage.
 - I know that previous firefox-esr was not updated through the minor releases. I'm considering adopting this package (I'm building the minors for myself anyway).

[ci skip]

### CODE REVIEW

**Comment by Vinfall** [comment]
I'd love to see this personally, but old ESR 115 EOL is set to October 1 as per [release calendar](https://whattrainisitnow.com/release/?version=esr). Before October ESR 115 & 128 are all maintained.

**Comment by Zapeth** [comment]
@Vinfall Considering ESR is currently severely outdated on Void and PRs for updates weren't merged I think that is unlikely to happen (maybe that will improve with a dedicated maintainer?)

@robertek Are the transitional `python3.11` changes still necessary? 128.0esr builds fine for me on x86_64 glibc without them (ie with python 3.12).

**Comment by robertek** [comment]
> @robertek Are the transitional `python3.11` changes still necessary? 128.0esr builds fine for me on x86_64 glibc without them (ie with python 3.12).

The original reason was to sync with the current firefox build as much as possible. So the question is more like if it is also necessary in the firefox package. And I feel it would be fine to keep things synced, as it would be possible, all the time even in the dot builds.

**Comment by classabbyamp** [comment]
it can probably use `python3` now

this should just be one commit per package

> I'm considering adopting this package

please don't adopt at this time, but do keep updating it. after you get some more experience with the package you can adopt it

**Comment by robertek** [comment]
Yes I know, I will squash the commits. I have bumped it yesterday and rebuild on the archs mentioned above. It seems to be fine as before.

**Comment by robertek** [comment]
Bumped to 128.1.0

Tested on x86_64-glibc

Built: the same as original message

I have also removed the python 3.11 dependency.

**Pull request merged**
