### PR TITLE
argyllcms: update to 2.1.2.

### PR DESCRIPTION
**Pull request by zdykstra**

### CODE REVIEW

**Comment by xtraeme** [comment]
hmmm I did this a while ago... it fails on 32bit...

**Comment by zdykstra** [comment]
> hmmm I did this a while ago... it fails on 32bit...

Shoot. I'm just going for all the low-hanging fruit that is orphaned right now. Anything that takes actual patching/whatever is being skipped for now.

**Comment by zdykstra** [comment]
https://travis-ci.org/void-linux/void-packages/jobs/659360567#L1227-L1234

**Comment by xtraeme** [comment]
I'm still not sure what to do with 32bit...

**Pull request closed without merging**
