### PR TITLE
xbps-src: add support on show-pkg-var for archs=

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by Vaelatern** [comment]
The view is pretty useless.
Can we match on all targets first, and print acceptable targets? (or noarch)?

**Comment by maxice8** [comment]
On Thu, Mar 14, 2019 at 03:44:09PM -0700, Toyam Cox wrote:
> The view is pretty useless.
> Can we match on all targets first, and print acceptable targets? (or noarch)?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/9840#issuecomment-473094166

Would require cloning the code on common/xbps-src/shutils/pkgtarget.sh

**Comment by Vaelatern** [comment]
Or pulling it out into a function, and looping over targets.

**Comment by Vaelatern** [comment]
This is the kind of code that Must Not Diverge.

**Comment by maxice8** [comment]
@Gottox

**Pull request closed without merging**
