### PR TITLE
New package: nwg-bar-0.1.6

### PR DESCRIPTION
**Pull request by zen0bit**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, x64 glibc

### CODE REVIEW

**Comment by classabbyamp** [comment]
if you,re going to be adding all of nwg-shell, you should do it as one PR

**Comment by zen0bit** [comment]
> if you,re going to be adding all of nwg-shell, you should do it as one PR

**Comment by zen0bit** [comment]
> if you,re going to be adding all of nwg-shell, you should do it as one PR

But most of apps could be used even without nwg-shell. Some already in Void...

So better push them separately?

Packaging all in one PR will make troubleshooting way longer.

It will stop me on first problem.

(Like first check)

PS: I wanna initialy push nwg-shell later, after most of parts will be merged (if)

**Comment by classabbyamp** [comment]
test locally instead of relying on CI, it will make things much faster

**Comment by zen0bit** [comment]
> test locally instead of relying on CI, it will make things much faster

Sure I am doing it, but not for all platforms...

What about pushing parts of nwg-shell separately? Since they can be used standalone anyway...

**Comment by classabbyamp** [comment]
> What about pushing parts of nwg-shell separately? Since they can be used standalone anyway...

opening so many PRs is very spammy, make it all one PR

**Comment by classabbyamp** [comment]
consolidate in #49664

**Pull request closed without merging**
