### PR TITLE
New package: linux5.19-5.19.0

### PR DESCRIPTION
**Pull request by sgn**
[ci skip]

#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by dataCobra** [comment]
Hey @sgn,

I've already changed the template to build 5.19.1 am I allowed to add the changes here for you to use in your PR?

**Comment by sgn** [comment]
@dataCobra Did you change config files? Otherwise, I'm building the new kernel.

**Comment by dataCobra** [comment]
I've only changed the template. So you're good to go. :+1:

**Comment by dkwo** [comment]
Would it make sense to bump `linux-mainline` as well?

**Pull request closed without merging**
