### PR TITLE
sssd: update to 2.2.3.

### PR DESCRIPTION
**Pull request by ahesford**
@inzanez I believe you are interested in `sssd`. Please test this update if possible.

Key changes in the template:
1. Move unversioned symlinks to `sssd-devel`.
2. Use `--with-sudo-lib-path` to move `libsss_sudo.so` to `/usr/lib/sssd`, so that unversioned library is not in the top-level `/usr/lib`.
3. Drop `libwbclient`. I'm pretty sure this was never done right in the first place and it causes shlib dependency confusion with `samba` and `cifs-utils`.

In particular, I would like to know if moving the unversioned symlinks to `sssd-devel` causes any obvious breakage.

### CODE REVIEW

**Comment by inzanez** [comment]
@ahesford Thanks for that! I would have sent a PR tonight (as I already have the package ready), but I guess yours already works too?
I was just waiting for the bind upgrade to be merged.

**Comment by inzanez** [comment]
Let me check that out. I think it will compile as you suggest, but not work as intended. I‘ve seen bugs when not having krb5 included in the config.

**Comment by ahesford** [comment]
I don't follow. The only thing I removed is `libwbclient`, which is used by Samba for ID mapping. But since we don't install the library in an expected place, and our Samba utilities aren't built to expect it, they would never use the alternative library without LD_LIBRARY_PATH shenanigans. Thus I think `libwbclient` was probably never effective on Void.

If I'm mistaken, we should probably find a better way to make this library play alongside Samba.

**Comment by inzanez** [comment]
Well, what I meant is basically that the sssd client did not start up with package 2.0. It logged an error message and exited.
Building package 2.3 without kerberos support did build well, but did not start up sssd either. It exited with errors again.
To build sssd with kerberos support, it requires a version of bind with kerberos support. That‘s one reason I submitted a PR for the bind upgrade to include kerberos support.
I have not built and tested your PR, so I cant say if I will face the same issues as before with version 2.0. I have built 2.3 myself including kerberos support and that changed the binary from ‚not running‘ to ‚working as expected‘. And as your PR doesnt seem to include kerberos, I fear that I might not be able to run the resulting binary, even if it compiles.

**Comment by ahesford** [comment]
Kerberos support was, and still is, included in this template, as `mit-krb5-devel` in `makedepends`. Your bind changes were merged the other day, which prompted my update here. If there is something you're doing differently, let me know and we can reconcile the changes.

**Comment by inzanez** [comment]
Ok, I see. Your package works fine. I upgraded to 2.3.1. already on my end. Maybe we could push this PR here to 2.3.1 too? Might be that this is the release requiring the patch regarding openssl/libressl. If that's the case, I'd be happy to share my patch.

**Comment by ahesford** [comment]
OK, I missed 2.3.1 because I didn't update the homepage and distfiles URLs. I pullsed your libressl patch and everything seems to build where it should. Also, `sssd-python` has been dropped since py2 is EOL and nothing depends on it.

**Pull request merged**
