### PR TITLE
sagemath: update to 10.4

### PR DESCRIPTION
**Pull request by tornaria**
Ideally, this PR should be merged on top of https://github.com/void-linux/void-packages/pull/50565, so that gsl is updated beforehand (both giac + sagemath need to be rebuilt when gsl is updated).

I've tested everything locally with https://github.com/void-linux/void-packages/pull/50565 + this PR so it should be fine to merge both together at the same time. But checking both PRs together takes a bit over 6h so github actions will timeout.

### CODE REVIEW

**Comment by tornaria** [comment]
Rebased on top of #50295, updated to sagemath 10.4.beta6

**Comment by tornaria** [comment]
@dkwo sagemath 10.4 is getting close, this works fine for me on x86_64 and passes all tests on i686 and x86_64-musl. If you want to check on aarch64 this is a good time, if there is any issue we can fix all before we merge it. I expect the final release will be almost the same as rc4 and very soon.

**Comment by tornaria** [comment]
Ideally, this PR should be merged on top of #50565, so that gsl is updated  beforehand (both giac + sagemath need to be rebuilt when gsl is updated).

**Comment by dkwo** [comment]
Thanks. I won't have access to my aarch64 machines for a month or so.
I think this should be merged now, and I'll run tests once I get back.
It's great that it now builds from pypi.

**Comment by tornaria** [comment]
> Thanks. I won't have access to my aarch64 machines for a month or so. I think this should be merged now, and I'll run tests once I get back. It's great that it now builds from pypi.

Great: I think we can merge it once 10.4 is released.

@ahesford: my last push should support numpy 2.0 without any further change (meaning: it builds and checks fine both with numpy 1.26 and with numpy 2.0 -- bear in mind that sagemath built with 1.26 will NOT work with 2.0 so a revbump will be necessary).  I'll be testing it further and let you know in case anything breaks.

**Comment by tornaria** [comment]
I tested locally on x86_64 with numpy 2.0 as follows:
 - On top of this PR I merged #51077 (at a656cfb6837 to be more precise).
 - From the numpy branch, I built numpy, pythran, matplotlib, scipy.
 - From the sagemath branch I rebuilt sagemath itself (nothing else needs numpy)
 - Run full check of sagemath (-K = long test, takes 35m on 8 cores): all tests passed.

**Comment by dkwo** [comment]
This builds and checks fine on aarch64.
At the post-install hook stage, I noticed a bunch of `warning: renamed X.cpython-312-aarch64-linux-gnu.so to X.so`, e.g. `X = algebra_elements`. Not sure if they're relevant.

**Comment by tornaria** [comment]
> This builds and checks fine on aarch64. At the post-install hook stage, I noticed a bunch of `warning: renamed X.cpython-312-aarch64-linux-gnu.so to X.so`, e.g. `X = algebra_elements`. Not sure if they're relevant.

This is a standard pre-pkg hook, the same happens for all python packages, xbps-src renames the libraries since the architecture part is not necessary for our distro python.

**Pull request closed without merging**
