### PR TITLE
common/shlibs: add missing shlibs

### PR DESCRIPTION
**Pull request by chrysos349**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by Chocimier** [comment]
What package fails to build due to lack of these entries?

**Comment by chrysos349** [comment]
Those that depend on those shlibs. From my private repo. Why does it matter?

`fwupd`, `gst-plugins-bad1`, `gst-rtsp-server`, `zopfli` are in the official repo, and provide the shared libs which need to be in the `common/shlibs` file.

**Comment by Chocimier** [comment]
> provide the shared libs which need to be in the `common/shlibs`

Wrong assumption, we usually do not list shared libs in `shlibs` unless used by other package.

> Why does it matter?

Packages would likely need a revbump, and you added none in the PR what raised my question.

> From my private repo.

Enough for me, but I'll like to hear opinion from other maintainers.

**Comment by abenson** [comment]
If these entries aren't needed for anything else that currently exists in `void-packages`, they can live on the same branch as your custom templates.

Additionally, these are unrelated to each other, and each one should be located within the file next to their similar entries (i.e. keep entries for `gst-plugins-bad1` with the existing entries for `gst-plugins-bad1`.

**Pull request closed without merging**
