### PR TITLE
zig: update to 0.6.0.

### PR DESCRIPTION
**Pull request by ifreund**
- Cleaned up the (host)makedepends, not sure why all this stuff was there.
- The `ZIG_STATIC` build options defaults to off, so dont set it.
- The cleanup preformed in post_extract() seems to no longer be needed.

### CODE REVIEW

**Comment by ifreund** [comment]
@Duncaen you're listed as the maintainer of this package. Would you mind giving this a review?

**Comment by Duncaen** [comment]
The "cleanup" seems wrong.

**Comment by Vaelatern** [comment]
@ifreund can you please verify that you know the difference between makedepends and hostmakedepends? I don't understand your move of llvm10 to makedepends.

**Comment by Duncaen** [comment]
its correct, it links the llvm libraries, it doesn't matter if you use gcc or clang as host compiler and "llvm10" is the "-devel" package, there is no split.

**Comment by Vaelatern** [comment]
And I've learned something! Thanks

**Comment by q66** [comment]
the removal of clang from dependencies is wrong though.

right now that doesn't show because for some reason llvm10 depends on clang, i'm investigating that

but re-add clang to makedepends

**Comment by ifreund** [comment]
good catch, PR up #21838

**Pull request merged**
