### PR TITLE
New package: vscodium-bin-1.79.2.23166

### PR DESCRIPTION
**Pull request by loss-and-quick**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (X86_64-GLIBC)
- I built this PR locally for these architectures:
  - aarch64
  - x86_64

### CODE REVIEW

**Comment by classabbyamp** [comment]
our vscode package is already very similar to vscodium (we patch out all telemetry) and it is built to work with system electron.

additionally, using prebuilt binary releases when building from source is possible make this very unlikely to be merged

**Comment by loss-and-quick** [comment]
> our `vscode` package is already very similar to vscodium (we patch out all telemetry) and it is built to work with system electron.
> 
> additionally, using prebuilt binary releases when building from source is possible make this very unlikely to be merged

What about dependency on systemd components(`udev` etc)?

**Comment by classabbyamp** [comment]
see also:

https://github.com/void-linux/void-packages/pull/10640

https://github.com/void-linux/void-packages/pull/18314

> AFAICT this is the only change sans rebranding vscodium does, so this should address issue #10582

**Comment by HanoJing** [comment]
> our `vscode` package is already very similar to vscodium (we patch out all telemetry) and it is built to work with system electron.
> 
> additionally, using prebuilt binary releases when building from source is possible make this very unlikely to be merged

That's great to hear, will vscode be available for ARM64 in the future?
Thanks in advance!

**Pull request closed without merging**
