### PR TITLE
abseil-cpp: update to 20230802.0.

### PR DESCRIPTION
**Pull request by mhmdanas**
[ci skip]

#### Testing the changes
- I tested the changes in this PR: **briefly**

@ahesford

Current failing to build:
- `netdata`
- `telegram-desktop`

### CODE REVIEW

**Comment by ahesford** [comment]
`telegram-desktop` because it tries to link a static library from `tg_owt` that still references the old `abseil-cpp`, so I bumped the `tg_owt` template to fix the build. That has been pushed to your branch.

The next failure is `netdata`, which I have not yet resolved.

**Comment by ahesford** [comment]
Looks like `netdata` is the only failure on `x86_64`; I'll run through the other architectures to confirm everything else works.

**Comment by mhmdanas** [comment]
> The next failure is netdata, which I have not yet resolved.

@Johnnynator mentioned in IRC that that should probably be fixed by an update. I'll handle it sometime in the next few days, or you can do that yourself too.

**Comment by ahesford** [comment]
Alright, I updated and fixed up the `netdata` template, so everything should be building properly now.

**Comment by ahesford** [comment]
Merged in https://github.com/void-linux/void-packages/commit/d840a05610b73f726b1408e7f3aefb6a03656ed8

**Pull request closed without merging**
