### PR TITLE
remove remaining kde4 packages

### PR DESCRIPTION
**Pull request by Johnnynator**
except akonadi.

### CODE REVIEW

**Comment by maxice8** [comment]
ping

**Comment by Johnnynator** [comment]
pong

**Comment by maxice8** [comment]
ok to merge ?

**Comment by maxice8** [comment]
On Sat, Jul 14, 2018 at 08:36:53AM -0700, Jürgen Buchmüller wrote:
> Closed #342 via fc8e22c38c66cc3b7334bf49b21587ea9dc32e90.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/342#event-1733908155

that is a yes

**Comment by Johnnynator** [comment]
plasma-sdk will fail to cross build, but I will fix that in my Plasma PR.

**Pull request closed without merging**
