### PR TITLE
setzer: update to 0.3.9

### PR DESCRIPTION
**Pull request by Bleznudd**

### CODE REVIEW

**Comment by paper42** [comment]
works great, thanks

I noticed some warnings in the build, what do you think about adding AppStream to hostmakedepends?
```
Program appstreamcli found: NO
Program desktop-file-validate found: NO
```

**Comment by paper42** [comment]
nevermind, the releases have it pregenerated

**Comment by ericonr** [comment]
Could you update to 0.4.1, please?

**Comment by Bleznudd** [comment]
I'm sorry, but 0.4.1 added [pdfminer](https://pypi.org/project/pdfminer/) as a dependency, and that module is not yet available in void repositories. I suggest to merge this version and then work on a template for python3-pdfminer

**Comment by ericonr** [comment]
@Bleznudd can you make a 0.4.1 PR later with a commit for pdfminer as a new package as well? It's ok to add new packages for existing packages.

**Comment by Bleznudd** [comment]
Sure, I'll look into that

**Pull request merged**
