### PR TITLE
darktable: update to 4.0.0 

### PR DESCRIPTION
**Pull request by ajtcode71**
- I tested the changes in this PR: **YES**
- I built this PR locally for my native architecture, AMD64-LIBC
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64 (crossbuild)

### CODE REVIEW

**Comment by CameronNemo** [comment]
Squash commits and use the format `darktable: update to 4.0.0` for the commit message.

**Comment by ajtcode71** [comment]
For some reasons all xbps packages i xlint come up with following errors: 
grep: zstd-1.5.2_1.x86_64.xbps: binary file matches
grep: zstd-1.5.2_1.x86_64.xbps: binary file matches
grep: zstd-1.5.2_1.x86_64.xbps: binary file matches
grep: zstd-1.5.2_1.x86_64.xbps: binary file matches
grep: zstd-1.5.2_1.x86_64.xbps: binary file matches
zstd-1.5.2_1.x86_64.xbps: 'homepage' missing!
zstd-1.5.2_1.x86_64.xbps: 'license' missing!
zstd-1.5.2_1.x86_64.xbps: 'maintainer' missing!
zstd-1.5.2_1.x86_64.xbps: 'pkgname' missing!
zstd-1.5.2_1.x86_64.xbps: 'revision' missing!
zstd-1.5.2_1.x86_64.xbps: 'short_desc' missing!
zstd-1.5.2_1.x86_64.xbps: 'version' missing!
zstd-1.5.2_1.x86_64.xbps:1: Header should be: # Template file for ''
zstd-1.5.2_1.x86_64.xbps:1758: File does not end with newline character

These are will packages that I havent built...  My Darktable 4 template is as peer the 3.8 template will the change to version number and checksum..
All the fields that are coming back as missing are in the template...   
Any ideas?

**Comment by CameronNemo** [comment]
@ajtcode71 you run xlint on the template file, not the .xbps file

**Comment by ajtcode71** [comment]
@CameronNemo - Ok stupid me (first time - can u tell?)..   Xlint is not showing any errors at my end.. Yet the xlint test is complaining about 'subject'.
Do i need to do anything else... or just wait for approval to get it merged?

**Comment by abenson** [comment]
'subject' refers to your commit message. Squash the commits and make sure the commit message matches what you put as the title for the PR.

**Comment by lemmi** [comment]
So, I haven't updated the package to `4.0.0` because things tend to break on major versions with darktable. I have `4.0.0` running locally, but there are hand full of small issues I didn't want everyone else to experience. I'd rather wait for a `4.0.1`.

Sorry I didn't see this earlier. Please @ me next time.

**Comment by ajtcode71** [comment]
> So, I haven't updated the package to `4.0.0` because things tend to break on major versions with darktable. I have `4.0.0` running locally, but there are hand full of small issues I didn't want everyone else to experience. I'd rather wait for a `4.0.1`.
> 
> Sorry I didn't see this earlier. Please @ me next time.

Ok no problem.. Should I close this PR?

**Comment by paper42** [comment]
This PR touches unrelated files, please fix that and make sure that it contains only one commit with the correct commit message

**Comment by lemmi** [comment]
@ajtcode71 If you don't mind, I'd rather have this closed. It's also missing the lensfun update to go along side. I usually keep an eye on darktable, as regularly use it myself. 

I pushed what I use to my branches, if you want to build it locally:
https://github.com/lemmi/void-packages/tree/darktable
https://github.com/lemmi/void-packages/tree/lensfun

Couple of issues I had, that held up the update:
- segfaults on website export
- avif image support still not working
- random crashes I wasn't able to reproduce

Sorry I didn't catch this earlier and if this caused unnecessary work for you.

**Pull request closed without merging**
