### PR TITLE
brightnessctl: Add service to store screen brightness

### PR DESCRIPTION
**Pull request by mamins1376**
Thought it would be nice to have this in the original package.

### CODE REVIEW

**Comment by xtraeme** [comment]
Please fix the commit message

**Comment by CameronNemo** [comment]
There are valid arguments against expanding the use of oneshot runit services using pause. Please consider using rc.local and rc.shutdown for these use cases.

**Comment by abenson** [comment]
> There are valid arguments against expanding the use of oneshot runit services using pause. 

I've considered we need a `/etc/oneshot` directory type thing for packages that need a oneshot, and similarly enable them in something like `/var/oneshot`. Or something. I'm not sure what's best.

**Comment by mamins1376** [comment]
@CameronNemo: Originally I was using the solution you mentioned. Then I saw `alsa-util`'s and found that pretty clever, with the added bonus of having the store and restore in one directory.

Is there any doc's indicating the downsides? Why this is not applied to `ALSA`?

**Comment by CameronNemo** [comment]
Lots of services like alsa, iptables, ufw, etc used the mechanism you have here. At first glance it is fairly clever, but it is weak for a couple reasons:

- no way to tell if or when the task has actually completed
- two useless processes hanging around (memory and clutter concerns)

Indeed having the boot/shutdown task in the same place is a nice quality of this mechanism. Hopefully we can maintain that while solving the above problems. It will require additions to void-runit.

**Comment by mamins1376** [comment]
Based on @abenson's suggestion; `/etc/rc.local`:
```
for f in /var/oneshot/*/start; do
    [ -x $f ] && $f;
done
```
And a similar one with `/var/oneshot/*/stop`; So that packages can add their own hooks and even do some sort of dependency satisfaction through number prefixes.
This is kind of borrowed from `/etc/X11/xinit/xinitrc`.

**Comment by Anachron** [comment]
How is the progress here? @abenson

**Pull request closed without merging**
