### PR TITLE
Update to GHC 9.0.2/Stackage LTS-19.0

### PR DESCRIPTION
**Pull request by slotThe**
And so... the ~~hunt~~ fun begins again!

### Core packages to bump

- [x] ghc
- [ ] ghc-bin
    - [x] x86_64-musl [Link](https://download1640.mediafire.com/02oxtdmod6tg/2g0umndrffyechx/ghc-9.0.2-x86_64-void-linux-musl.tar.xz) **Not uploaded yet**
    cc. @q66 for the following
    - [ ] ppc64le
    - [ ] ppc64le-musl
    - [x] aarch64 [Link](https://ftrv.se/_/void/ghc-9.0.2/ghc-9.0.2-aarch64-void-linux.tar.xz) **Not uploaded yet**
    - [x] aarch64-musl [Link](https://ftrv.se/_/void/ghc-9.0.2/ghc-9.0.2-aarch64-void-linux-musl.tar.xz) **Not uploaded yet**
- [x] cabal-install
- [x] stack

#### Rebuild literally every single haskell package we have and see if anything's broken

Most of these are already done, things should probably go smoothly as 9.0.x does not contain any big breaking changes.

- [x] git-mediate
- [x] kmonad
- [x] cgrep
- [x] debug-me
- [x] hlint
- [x] hoogle
- [x] darcs
- [x] shellcheck
- [x] git-annex
- [x] hledger
- [x] pandoc (contains a fix for `pandoc-crossref` on musl \o/)
- [x] xmobar
- [x] haskell-language-server

### Other things to do 

- [x] Either incorporate https://github.com/void-linux/void-packages/pull/36193 into this PR or merge it first and then rebuild GHC for aarch64 and aarch64-musl; cc. @ftrvxmtrx

Closes https://github.com/void-linux/void-packages/pull/36193

[ci skip]

### CODE REVIEW

**Comment by ftrvxmtrx** [comment]
@slotThe I condensed the changes required to get it build on aarch64 and aarch64-musl to one commit: https://github.com/ftrvxmtrx/void-packages/commit/401a299740c47d8f6e1d1d55fb8a09fb38dc08c4

I think it'd be best to get that change into your PR directly. Feel free to cut out parts you might already have in your local tree.

* [distfile for aarch64](https://ftrv.se/_/void/ghc-9.0.2/ghc-9.0.2-aarch64-void-linux.tar.xz)
* [distfile for aarch64-musl](https://ftrv.se/_/void/ghc-9.0.2/ghc-9.0.2-aarch64-void-linux-musl.tar.xz)

I've built `ghc-bin` for both, now building `ghc` which is going to take some time.

**Comment by ftrvxmtrx** [comment]
I've set up rsync://ftrv.se/ghc902 for the builds I'm making, just in case.

**Comment by ftrvxmtrx** [comment]
aarch64-musl, pandoc:

```
Warning: File listed in pandoc-crossref-0.3.12.2/pandoc-crossref.cabal file does not exist:
         ./test/m2m/eqnBlockTemplate/expect.md                              
Warning: File listed in pandoc-crossref-0.3.12.2/pandoc-crossref.cabal file does not exist:
         ./test/m2m/eqnBlockTemplate/expect.tex
                                                                            Warning: File listed in pandoc-crossref-0.3.12.2/pandoc-crossref.cabal file does not exist:
         ./test/m2m/eqnBlockTemplate/input.md
pandoc-crossref> build (lib + exe)                                          pandoc-crossref> Preprocessing library for pandoc-crossref-0.3.13.0..       pandoc-crossref> Building library for pandoc-crossref-0.3.13.0..            pandoc-crossref> Preprocessing executable 'pandoc-crossref' for pandoc-crossref-0.3.13.0..
pandoc-crossref> Building executable 'pandoc-crossref' for pandoc-crossref-0.3.13.0..
                                                                            Warning: File listed in pandoc-crossref-0.3.12.2/pandoc-crossref.cabal file does not exist:                                                                      ./test/m2m/eqnBlockTemplate/expect.md

Warning: File listed in pandoc-crossref-0.3.12.2/pandoc-crossref.cabal file does not exist:                                                                      ./test/m2m/eqnBlockTemplate/expect.tex
                                                                            Warning: File listed in pandoc-crossref-0.3.12.2/pandoc-crossref.cabal file does not exist:
         ./test/m2m/eqnBlockTemplate/input.md
pandoc-crossref> copy/register
pandoc-crossref> Cabal-simple_mPHDZzAJ_3.4.1.0_ghc-9.0.2: filepath wildcard
pandoc-crossref> 'test/m2m/eqnBlockTemplate/expect.md' does not match any files.
pandoc-crossref>
'cabal copy' failed.  Error message:

--  While building package pandoc-crossref-0.3.13.0 (scroll up to its section to see the error) using:
      /builddir/pandoc-2.17.1.1/.stack/setup-exe-cache/aarch64-linux/Cabal-simple_mPHDZzAJ_3.4.1.0_ghc-9.0.2 --builddir=.stack-work/dist/aarch64-linux/Cabal-3.4.1.0 copy
    Process exited with code: ExitFailure 1

Possible causes of this issue:
* No module named "Main". The 'main-is' source file should usually have a header indicating that it's a 'Main' module.
* A cabal file that refers to nonexistent other files (e.g. a license-file that doesn't exist). Running 'cabal check' may point out these issues.

=> ERROR: pandoc-2.17.1.1_1: do_build: 'STACK_ROOT="$wrksrc/.stack" stack ${_stack_args} ${makejobs} build ${make_build_args}' exited with 1
=> ERROR:   in do_build() at common/build-style/haskell-stack.sh:27
```

**Comment by slotThe** [comment]
Ah, very good point; we don't have those data-files so the cabal file shouldn't mention them

**Comment by ftrvxmtrx** [comment]
@slotThe nice, worked this time!

**Comment by ftrvxmtrx** [comment]
k, all packages built successfully for `aarch64-musl`, tested some of them and it works fine, uploaded to `rsync://ftrv.se/ghc902/aarch64-musl/`.

**Comment by ftrvxmtrx** [comment]
@slotThe I updated my patch https://github.com/ftrvxmtrx/void-packages/commit/a5ead59471bfaa690f88bbc1818d29b640f0e949 with new checksums. @q66 pointed out I missed some steps while building a proper bindist so I had to rebuild those.

**Comment by slotThe** [comment]
@ftrvxmtrx thanks, applied!

**Comment by ftrvxmtrx** [comment]
All packages in question built for both `aarch64` and `aarch64-musl` successfully now, jfyi.

**Comment by slotThe** [comment]
@q66 friendly ping

**Comment by q66** [comment]
closing, i will merge this with local changes separately (ghc-bin x86_64-musl path needs to be reverted back, ppc checksums updated, also ppc64 big endian patch got broken in the process and i had to fix that)

**Comment by Piraty** [comment]
https://github.com/void-linux/void-packages/pull/36971

**Pull request closed without merging**
