### PR TITLE
zfs: update to 2.0.5.

### PR DESCRIPTION
**Pull request by ahesford**
Should be uneventful. Compiles on 5.10, I am about to compile and reboot on 5.12 and test with ZBM.

cc: @Vaelatern @ericonr @zdykstra (zdykstra will be testing on ppc64le, i686-musl and MIPS)

### CODE REVIEW

**Comment by ahesford** [comment]
The kmod builds fine for 5.10, builds and runs fine on 5.12 and gives me no troubles in a ZFSBootMenu image (also on 5.12).

**Comment by zdykstra** [comment]
Builds fine on ppc64le for 5.4, 5.10, 5.11, 5.12. Booted root on ZFS with 5.4 and 5.12.

**Comment by paper42** [comment]
What do you think about importing https://github.com/openzfs/zfs/pull/12147?

**Comment by ericonr** [comment]
Tested on 5.12.13.

**Comment by Vaelatern** [comment]
@paper42 not interested in non-merged patches, sorry. I relied on similar patches for my personal ZFS installs before, but it's not appropriate for the distribution level ZFS.

**Review by Vaelatern — APPROVED** [review]

**Comment by ahesford** [comment]
Since we've kickstarted some debate upstream, I've merged this as-is in 7a0ad21a4. Once upstream settles out on the plymouth patch, we can revbump if necessary. There are a few fixes in 2.0.5 that would be good to have in the meantime.

**Pull request closed without merging**
