### PR TITLE
nerd-fonts: update to 3.1.0

### PR DESCRIPTION
**Pull request by Poly2it**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)

### CODE REVIEW

**Comment by icp1994** [comment]
https://github.com/void-linux/void-packages/pull/48765

**Comment by classabbyamp** [comment]
@cinerea0

**Comment by Snxwman** [comment]
> #48765

#47509 also

**Comment by cinerea0** [comment]
Superseded by https://github.com/void-linux/void-packages/commit/1f73728e4653b0947aac06b7dfcb4c48b1d76a06.

**Pull request closed without merging**
