### PR TITLE
mumble: update to 1.4.230.

### PR DESCRIPTION
**Pull request by chili-b**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by stacyharper** [comment]
Does it need some new pipewire devel make depencencies ?

**Comment by chili-b** [comment]
> Does it need some new pipewire devel make depencencies ?

Not that I'm aware. I noticed, though, that you need `pipewire-devel` installed at runtime for mumble to recognize that it's available.

**Comment by paper42** [comment]
Could you try removing depends=mumble from murmur and testing if it still works as expected? https://github.com/void-linux/void-packages/issues/35110#issuecomment-1015537666

**Comment by chili-b** [comment]
@paper42 , It seems to build and work. Is there anything else

**Comment by chili-b** [comment]
> Does it need some new pipewire devel make depencencies ?

@stacyharper , In case you haven't also, I looked into this a little bit more and it seems like mumble manages loading the pipewire library fully at runtime.

**Comment by paper42** [comment]
This update was done in 5f589a9962d7871deedbaa3d3e92751ace5ef1d6, @Hoshpak probably didn't see this PR. Could you look at the changes, rebase this PR and include only the ones which make sense and are not part of 5f589a9962d7871deedbaa3d3e92751ace5ef1d6? At least removing depends=mumble from murmur is important.

**Comment by chili-b** [comment]
> Could you look at the changes, rebase this PR and include only the ones which make sense

Done. I think everything is in order now

**Comment by paper42** [comment]
please increase the revision, then I think this is good to go

**Comment by chili-b** [comment]
Ok, it is done

**Comment by paper42** [comment]
the commit message should be changed, this is not an update anymore

**Comment by chili-b** [comment]
Okay, i've changed the commit message to describe the changes to the template

**Pull request merged**
