### PR TITLE
grub-btrfs: update to 4.8

### PR DESCRIPTION
**Pull request by FollieHiyuki**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by FollieHiyuki** [comment]
Upstream has a `systemd.path` service to monitor /.snapshots directory for changes to update grub.
I can't think of a way to replicate this for runit. Maybe using `inotify-tools`?

**Comment by circhioz** [comment]
Here's my run script :)
```
#!/bin/sh
[ -r conf ] && . ./conf
exec wendy -m 768 -w $SNAPSHOTS_PATH bash -c 'if [ -s "/boot/grub/grub-btrfs.cfg" ]; then /etc/grub.d/41_snapshots-btrfs; else update-grub; fi' 2>&1
```
and conf file
```
SNAPSHOTS_PATH=/.snapshots
```

**Comment by FollieHiyuki** [comment]
Yes but it introduces new dependencies, which I want to avoid

**Comment by circhioz** [comment]
`inotify-tools` would add a dependency, too

**Comment by FollieHiyuki** [comment]
Yes that's why there is a question mark xD

**Comment by circhioz** [comment]
Oh well, there's no "runit way" to replicate systemd's path units. I misinterpreted your question mark xD

**Comment by ericonr** [comment]
We could look into adding a service, perhaps as a subpackage?

**Pull request merged**
