### PR TITLE
mkinitcpio: update to 27.

### PR DESCRIPTION
**Pull request by travankor**
See: https://bugs.archlinux.org/task/59151

### CODE REVIEW

**Comment by mobinmob** [comment]
Currently mkinitcpio in void is broken for LUKS (Ι think there is something with the keymaps, you cannot type the password, at least when root is encrypted) - reported in the IRC.

**Comment by travankor** [comment]
mkinitcpio 25 worked for me with LUKS2, will investigate later

**Comment by travankor** [comment]
does mkinitcpio 27 work for the IRC people?

**Comment by mobinmob** [comment]
I will test your commits myself in a few hours and report back - I do not have a luks2 volume, but a luks1.

**Comment by mobinmob** [comment]
Yep, same problem in versions 25,26 and 27. :(

**Comment by travankor** [comment]
I booted with a v27 initramfs fine with the new kernel 5.3.8, in fact the boot time has significantly gone down (mostly udev was faster).

Do you have keymap defined in `/etc/rc.conf`? What hooks are in your mkinitcpio.conf? You need to add the keyboard hook to mkinitcpio.conf. Also this can be difficult on some hardware, like a regional language keyboard.

**Comment by mobinmob** [comment]
Yes, I have a keymap.
`HOOKS=(base udev autodetect keyboard keymap consolefont modconf block encrypt lvm2 filesystems fsck)`

**Comment by travankor** [comment]
This is really dumb, but  you do have the right packages?
[\*] mkinitcpio-27_1              Next generation of initramfs creation
[\*] mkinitcpio-encrypt-27_1      Next generation of initramfs creation - encrypt support
[\*] mkinitcpio-lvm2-27_1         Next generation of initramfs creation - lvm2 support
[-] mkinitcpio-mdadm-27_1        Next generation of initramfs creation - mdadm support
[\*] mkinitcpio-udev-27_1         Next generation of initramfs creation - udev support
[-] mkinitcpio-xbps-27_1         Next generation of initramfs creation - xbps sup

I'm not sure if mkinitcpio-udev is necessary; it might be redundant.

I have a Void LUKS1 machine that I can try this on later. Any specific steps to reproduce the failure would be helpful.

**Comment by mobinmob** [comment]
I have all of them, plus mkinitcpio-xbps - I recreated the initramfs with xbps-reconfigure -f linux5.3 . Don't sweat it - dracut works fine.

**Pull request merged**
