### PR TITLE
New package: radm-0.6.4

### PR DESCRIPTION
**Pull request by Goorzhel**
- I tested the changes in this PR: **YES**
- This new package (however self-serving) conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

### CODE REVIEW

**Comment by Goorzhel** [comment]
Both CI failures had to do with the `chvt` crate. I'll try to reproduce this locally (
```
❯ for arch in {x86_64,armv{6,7}l,i686,aarch}{,-musl}; do
  ./xbps-src pkg -a $arch $(git b) &> $arch.log
done
```
) and submit any necessary patches to the crate's upstream.

**Comment by Goorzhel** [comment]
Also, a majority of the architectures on [this run](https://github.com/void-linux/void-packages/actions/runs/2906665327) returned success, but actually failed with
```
=> ERROR: pandoc-2.17.1.1_1: cannot be cross compiled...
=> ERROR: pandoc-2.17.1.1_1: yes
```
because I mistakenly added `pandoc` to `makedepends` rather than `hostmakedepends`. I should investigate that later, too.

**Comment by Goorzhel** [comment]
Patches sent upstream to unbreak non-Intel builds:
https://github.com/jonay2000/chvt-rs/pull/2
https://github.com/1wilkens/pam/pull/36

I still need to test these changes at runtime so I'll leave the branch unsquashed for now.

**Comment by Goorzhel** [comment]
> Also, a majority of the architectures on [this run](https://github.com/void-linux/void-packages/actions/runs/2906665327) returned success, but actually failed

Turns out `build.sh` was eating the exit code. https://github.com/void-linux/void-packages/pull/38841

**Comment by q66** [comment]
pandoc is not portable, put the manpage behind a build option that is only enabled if the host architecture is one that has it (`x86_64*|i686|ppc64le*|ppc64`)

**Comment by Goorzhel** [comment]
This is as done as it's ever going to be. Squashing.

**Pull request closed without merging**
