### PR TITLE
igraph: update to 0.10.12.

### PR DESCRIPTION
**Pull request by tornaria**
#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by szhorvat** [comment]
@tornaria Have you considered adding the Python igraph package as well to Void Linux? It is an optional part of SageMath: https://doc.sagemath.org/html/en/reference/spkg/python_igraph.html

**Comment by tornaria** [comment]
> @tornaria Have you considered adding the Python igraph package as well to Void Linux? It is an optional part of SageMath: https://doc.sagemath.org/html/en/reference/spkg/python_igraph.html

I could do it if there is a direct use. Is sagemath (the library / the program) actually using igraph or python-graph?

**Comment by szhorvat** [comment]
I believe SageMath uses igraph as a dependency of [rankwidth](https://sourceforge.net/projects/rankwidth/).

python-igraph is _useful_ in Sage to gain access to igraph's algorithms, but not _required_. See https://doc.sagemath.org/html/en/reference/graphs/sage/graphs/generic_graph.html#sage.graphs.generic_graph.GenericGraph.igraph_graph

**Comment by tornaria** [comment]
> I believe SageMath uses igraph as a dependency of [rankwidth](https://sourceforge.net/projects/rankwidth/).

It's a false dependency. Rankwidth uses igraph only for the binary `rw`. But sagemath only uses the shared library. We don't ship the `rw` binary on void linux, hence our `rankwidth` package does not depend on igraph. 

> python-igraph is _useful_ in Sage to gain access to igraph's algorithms, but not _required_. See https://doc.sagemath.org/html/en/reference/graphs/sage/graphs/generic_graph.html#sage.graphs.generic_graph.GenericGraph.igraph_graph

I see, so if `python-igraph` is available, sagemath has a function to convert its own graphs to igraph and use them via `python-igraph` functions.

I don't do much graph theory myself, but if its useful (together with sage or on on its own), I could try to package it. I'm all in favor of packaging more math software for void linux.

**Comment by szhorvat** [comment]
> It's a false dependency. Rankwidth uses igraph only for the binary `rw`. But sagemath only uses the shared library. We don't ship the `rw` binary on void linux, hence our `rankwidth` package does not depend on igraph.

In that case I actually don't know if there's anything else in SageMath that uses the igraph C library. There might not be.

The usage of igraph in `rw` is very sloppy and unmaintained (and would need patches for igraph 0.10), so if you can skip building the command line program, do so by all means.


> I don't do much graph theory myself, but if its useful (together with sage or on on its own), I could try to package it. I'm all in favor of packaging more math software for void linux.

This would be nice. If you have questions while packaging, feel free to ping me.

**Pull request merged**
