### PR TITLE
Add Ettus UHD support

### PR DESCRIPTION
**Pull request by repk**
This add uhd library package and build gnuradio with uhd support.

### CODE REVIEW

**Comment by maxice8** [comment]
```
[ 59%] Building CXX object lib/CMakeFiles/uhd.dir/experts/expert_factory.cpp.o
In file included from /builddir/uhd-3.13.0.2/host/lib/include/uhdlib/experts/expert_container.hpp:11,
                 from /builddir/uhd-3.13.0.2/host/lib/include/uhdlib/experts/expert_factory.hpp:11,
                 from /builddir/uhd-3.13.0.2/host/lib/experts/expert_factory.cpp:8:
/builddir/uhd-3.13.0.2/host/lib/include/uhdlib/experts/expert_nodes.hpp:36:53: error: expected class-name before '{' token
     class dag_vertex_t : private boost::noncopyable {
                                                     ^
In file included from /builddir/uhd-3.13.0.2/host/lib/include/uhdlib/experts/expert_container.hpp:11,
                 from /builddir/uhd-3.13.0.2/host/lib/experts/expert_container.cpp:8:
/builddir/uhd-3.13.0.2/host/lib/include/uhdlib/experts/expert_nodes.hpp:36:53: error: expected class-name before '{' token
     class dag_vertex_t : private boost::noncopyable {
                                                     ^
make[2]: *** [lib/CMakeFiles/uhd.dir/build.make:3283: lib/CMakeFiles/uhd.dir/experts/expert_factory.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [lib/CMakeFiles/uhd.dir/build.make:3270: lib/CMakeFiles/uhd.dir/experts/expert_container.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:125: lib/CMakeFiles/uhd.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

Got this while trying to compile myself

**Comment by maxice8** [comment]
Please rebase your branch against the newest master since a commit fixing gnuradio was introduced

**Comment by Johnnynator** [comment]
> Got this while trying to compile myself

Probably only a missing include, seems to be fixed already upstream https://github.com/EttusResearch/uhd/commit/5c012cad7858cadcaa85ec295080f3c8b21fdee0

**Comment by repk** [comment]
Yes I forgot to include the patch, sorry.

**Pull request closed without merging**
