### PR TITLE
rpi-*: update and support rpi5

### PR DESCRIPTION
**Pull request by classabbyamp**
- rpi-kernel: update to 6.1.62.
- rpi-firmware: update to 20231102.
- New package: rpi-utils-20231105
- rpi-eeprom: update to 2023.11.09.

#### Testing the changes
- I tested the changes in this PR: **YES**
  - [x] 1B+ (armv6l)
  - [ ] 0 (armv6l)
  - [ ] 1A+ (armv6l)
  - [ ] 2B (armv7l)
  - [x] 3B (aarch64)
  - [x] 02W (aarch64)
  - [x] 4B (aarch64)
  - [x] 5 (aarch64)

### Prebuilt packages and RPi5-compatible install images for testing

**packages:** https://files.placeviolette.net/rpi5

```
`https://files.placeviolette.net/rpi5' repository has been RSA signed by "classabbyamp"
Fingerprint: 6e:a5:91:cc:71:99:18:32:75:dc:be:b4:f8:ac:dc:19
```
**images:** https://files.placeviolette.net/rpi5-live

`rpi5-kernel` is not installed by default on these images, but can be seamlessly switched to by installing it. it will uninstall  `rpi-kernel` (and vice-versa). RPi5 is compatible with both, but `rpi5-kernel` may provide some performance benefits.

The images also include the changes from void-linux/void-mklive#361

[ci skip]

closes #46815 
closes #46522

### CODE REVIEW

**Comment by 0x5c** [comment]
New arm64 generic kernel successfully tested on both a 3B and a 5B (8GB).
Also successful test of the aarch64 image and rpi5-kernel on 5B.

**Comment by moabeat-berlin** [comment]
The kernel is working fine on a 02W (aarch64-musl). Also a dkms module got compiled properly. I was able to successfully use the new live image on an RPi5.

**Comment by moabeat-berlin** [comment]
I have finally found my old RPi 1B Rev 2 board and was able to successfully test the kernel now as well on this old machine.

**Comment by classabbyamp** [comment]
updated things because this has sat for a bit

new versions should be available at https://files.placeviolette.net/rpi5 for testing

**Pull request merged**
