### PR TITLE
New packages: python3-pyside6 shiboken6

### LINKED ISSUE #39975: Package request: python3-pyside6
### Package name

python3-pyside6

### Package homepage

https://pypi.org/project/PySide6/

### Description

Qt6.0+ bindings for python3

Previous PR: #33355 (Stale/Closed)

### Does the requested package meet the package requirements?

Required

### Is the requested package released?

Yes

### PR DESCRIPTION
**Pull request by agausmann**
Closes #39975 , updates #41957 

#### Testing the changes
- I tested the changes in this PR: **briefly**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

### CODE REVIEW

**Comment by agausmann** [comment]
CC @fanyx : do you still want to maintain this?

**Comment by agausmann** [comment]
I think there's something wrong with the CMake scripts in the -devel package, need to look into it some more.

**Comment by agausmann** [comment]
For reference, I'm trying to build KDDockWidgets for Python according to [this README](https://github.com/KDAB/KDDockWidgets/blob/1.7/README-bindings.md), and I get this error from CMake:

```
$ cmake -DKDDockWidgets_PYTHON_BINDINGS=True -DCMAKE_BUILD_TYPE=Release -DKDDockWidgets_QT6=True -GNinja ..
-- The CXX compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE  
-- Found OpenGL: /usr/lib/libOpenGL.so   
-- Found WrapOpenGL: TRUE  
-- Found XKB: /usr/lib64/libxkbcommon.so (found suitable version "1.5.0", minimum required is "0.5.0") 
-- Found WrapVulkanHeaders: /usr/include  
-- Building KDDockWidgets 1.7.1 in Release mode. Installing to /usr/local/KDAB/KDDockWidgets-1.7.1
-- Found Python3: /home/goose/.asdf/shims/python3 (found suitable version "3.11.4", minimum required is "3.7") found components: Interpreter Development Development.Module Development.Embed 
-- ShibokenGenerator base dir: /usr/lib/python3.11/site-packages/shiboken6_generator
-- Shiboken base dir:          /usr/lib/python3.11/site-packages/shiboken6
-- Shiboken custom path:       
-- PySide6 base dir:           /usr/lib/python3.11/site-packages/PySide6
-- PySide6 suffix:             so.6.5
-- PySide include dir:         PYSIDE_INCLUDE_DIR-NOTFOUND
-- PySide library:             /lib/libpyside6.so.6.5
-- PySide typesystems:         PYSIDE_TYPESYSTEMS-NOTFOUND
-- PySide6 version:            6.5.0
CMake Error at /usr/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PySide6 (missing: PYSIDE_INCLUDE_DIR PYSIDE_TYPESYSTEMS)
  (found suitable exact version "6.5.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/KDAB/modules/FindPySide6.cmake:142 (find_package_handle_standard_args)
  python/CMakeLists.txt:32 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by agausmann** [comment]
Oh, this may not be related to the PySide CMake files.

**Comment by fanyx** [comment]
if you want to take this over and have more insight than i do, i'd more than happy to pass this on.

i only wanted to get this to run for some weird package i use privately.

**Comment by fanyx** [comment]
Shiboken6Tools is available in the same source files but needs a separate build for all toolchains apart from x86_64-glibc.
idk who can assist here, tho

**Pull request closed without merging**
