### PR TITLE
instead: update to 3.3.3.

### PR DESCRIPTION
**Pull request by UsernameRandomlyGenerated**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ahesford** [comment]
What happens if the `gtk3` option is disabled? The old template used it as a switch between gtk2 and gtk3, so there was always *some* gtk dependency. Unless there is a compelling reason to allow building a version without any gtk support, I'd just drop the option and always pull in gtk3.

**Comment by UsernameRandomlyGenerated** [comment]
Without gtk3 it builds and works pretty much the same but there is no gtk file pick dialog (F4 button). It's enabled by default in 3.3.3. I can remove the option if you think it's a good call, I don't use the package myself so I can't make any argument for or against it.

**Comment by ericonr** [comment]
I'd go with @ahesford's suggestion; simply remove the build option and force gtk3.

**Comment by UsernameRandomlyGenerated** [comment]
I've removed build option for SDL1 too, SDL2 is also default and I don't think anyone needs building with the old one, though I'll restore it if you think I should.

**Comment by ahesford** [comment]
I don't really have an opinion here and will defer to @ericonr if he does. Dropping the SDL2 option seems ok, because anybody who objects to the list option can always revert that part of the change.

**Comment by ericonr** [comment]
Please mention the changes in the commit message ;)

Besides that, I'm okay with dropping SDL and forcing SDL2.

**Pull request closed without merging**
