### PR TITLE
cryptsetup: update to 2.3.5.

### PR DESCRIPTION
**Pull request by ailiop-git**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
I think you want to update `cryptsetup-static` as well, and add a comment to the `cryptsetup` template to not forget about static ;)

**Comment by abenson** [comment]
> I think you want to update cryptsetup-static

It's a sub-package?

**Comment by abenson** [comment]
It looks like the test failures are specific to CI, they pass fine here.

**Comment by ericonr** [comment]
> It's a sub-package?

No, separate template.

**Comment by ericonr** [comment]
> It looks like the test failures are specific to CI, they pass fine here.

Can make it `make_check=extended`, then.

**Comment by abenson** [comment]
```
cryptsetup-static_package() {
    short_desc+=" - static cryptsetup"
    pkg_install() {
        vmove "usr/bin/*.static"
    }
}
```

**Pull request closed without merging**
