### PR TITLE
i3status: update to 2.13

### PR DESCRIPTION
**Pull request by lugubris**

### CODE REVIEW

**Comment by daniel-eys** [comment]
i3status switched to autotools with 2.13, so the template needs some adjustments.

**Comment by lugubris** [comment]
what changes do I have to make? sorry for negligence but I some issues with reading docs. They didn't update the changelog this time. Also, this builds correctly on my machine when following their install instructions:
```
  autoreconf -fi
  mkdir build
  cd build
  ../configure
  make -j8
  sudo make install
```

**Comment by lugubris** [comment]
from what I understood there should be `autoreconf --force --install`  and `../configure --prefix=/usr ` under `do_build()` before `make CC=$CC ${makejobs}`

**Comment by teldra** [comment]
I tried it like this: https://github.com/void-linux/void-packages/compare/master...teldra:i3status-update

**Comment by Piraty** [comment]
see #13641

**Comment by lugubris** [comment]
@Piraty https://github.com/void-linux/void-packages/blob/adae4d3b7b641eb3ea9180d703745729ebc1f600/srcpkgs/i3status/template#L19

I think someone fixed that issue later, make already depends on libglob (musl)

@teldra looks good

**Comment by lugubris** [comment]
@Piraty build failed for musl variants,  what does:
> To fix this, i3status should link against libglob on musl.

mean?

**Comment by Piraty** [comment]
beb8600e7554308d925345cf56516a7c5a0ca03c

**Pull request closed without merging**
