### PR TITLE
cloudflared: update to 2023.2.1

### PR DESCRIPTION
**Pull request by marmeladema**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64

### CODE REVIEW

**Comment by paper42** [comment]
commit message is wrong and 2023.2.1 is out

**Comment by marmeladema** [comment]
@paper42 whats wrong with the commit message? Other updates were using a similar message

**Comment by paper42** [comment]
I guess noone noticed this yet, according to CONTRIBUTING.md it should be `<pkgname>: update to <version>.`

**Comment by marmeladema** [comment]
You are saying the final dot is missing? 🥲

**Comment by paper42** [comment]
the word version shouldn't be used

**Comment by paper42** [comment]
@marmeladema could you update this package to 2023.2.1 and drop the v from the commit message? It would be nice to merge this update.

**Comment by marmeladema** [comment]
@paper42 done

**Pull request merged**
