### PR TITLE
docker-compose: update to 2.26.1

### PR DESCRIPTION
**Pull request by kartikynwa**

### CODE REVIEW

**Review by ahesford — CHANGES_REQUESTED** [review]
Just include `python3-dotenv` instead of a combined template that also includes `python-dotenv`. Because py2 is EOL, we aren't accepting new py2 packages, and this will just create more work later if (when) 
upstream drops py2 support.

**Comment by kartikynwa** [comment]
> Just include `python3-dotenv` instead of a combined template that also includes `python-dotenv`. Because py2 is EOL, we aren't accepting new py2 packages, and this will just create more work later if (when)
> upstream drops py2 support.

Would this mean discarding the python2 related files that are built?

**Comment by kartikynwa** [comment]
@ahesford It is done!! Also sorry for bad title. Was a mistake.

**Review by ahesford — CHANGES_REQUESTED** [review]
Dropping `python3-pysocks` seems to be appropriate. Aside from `setup.py`, `requirements.txt` and `CHANGELOG.md`, the text `socks` (without regard to case) appears nowhere in `docker-compose`. If people want it, they can install it manually.

**Comment by kartikynwa** [comment]
@ahesford Done.

**Pull request merged**
