### PR TITLE
doxygen: fix broken distfile url

### PR DESCRIPTION
**Pull request by q66**

### CODE REVIEW

**Comment by CameronNemo** [comment]
You are seeing a lint error. I suggest installing xlint from source or using the order of variables as they appear [here](https://github.com/chneukirchen/xtools/blob/master/xlint#L27).

**Comment by q66** [comment]
The lint error was always there, this just fixes the url; the tarball is the same (note the checksum does not change) so it doesn't need a revbump, it's just to make it buildable again.

Linting errors should get fixed, but I wonder if that should get a separate PR?

**Comment by Hoshpak** [comment]
It's fine to do it in the same PR and commit along with other changes. While it is desirable to get all packages in compliance with the linter and it would be appreciated if you took the time to fix these warnings while creating PRs, I don't see it as an absolute requirement to get PRs merged that just fix something and don't introduce new packages.

**Comment by q66** [comment]
fixed lint

**Pull request merged**
