### PR TITLE
apvlv: update to 0.2.0

### PR DESCRIPTION
**Pull request by logenkain**

### CODE REVIEW

**Comment by ericonr** [comment]
Your PR is good, but gtk+3-devel dependencies are wonky right now. I will merge when I have managed to solve them.

**Comment by D-Nice** [comment]
damn, this would install 21 new dependencies... some undesirables with various recent CVEs. I'll either hold or rm apvlv

**Comment by ericonr** [comment]
@D-Nice could you point out the dependencies with issues? Possibly make PRs to update them.

**Comment by D-Nice** [comment]
@ericonr There's none necessarily with active CVEs, I'm just surprised if a major version change, really requires 21 dependencies compared to the last, in which case I mentioned what the best solution for me would be then, probably hold for a bit and remove it.

For posterity, here are all the new dependencies the apparent update from apvlv  0.1.5_8  to 0.2.0_1 requires:
```
bubblewrap                install   -                 0.4.1_2                29KB 
xdg-dbus-proxy            install   -                 0.1.2_1                20KB 
gsettings-desktop-schemas install   -                 3.38.0_1               710KB 
libproxy                  install   -                 0.4.15_1               - 
glib-networking           install   -                 2.66.0_1               127KB 
libpsl                    install   -                 0.21.1_1               60KB 
brotli                    install   -                 1.0.9_2                384KB 
libsoup                   install   -                 2.72.0_1               334KB 
libwoff2common1.0.2       install   -                 1.0.2_1                4072B 
libwoff2dec1.0.2          install   -                 1.0.2_1                19KB 
gstreamer1                install   -                 1.16.2_1               1131KB 
libcdparanoia             install   -                 10.2_14                39KB 
libvisual                 install   -                 0.4.0_9                - 
graphene                  install   -                 1.10.2_1               58KB 
gst-plugins-base1         install   -                 1.16.2_2               2141KB 
libhunspell1.7            install   -                 1.7.0_2                133KB 
enchant                   install   -                 1.6.0_8                30KB 
hyphen                    install   -                 2.8.8_2                49KB 
webkit2gtk                install   -                 2.30.4_1               24MB 
libzip                    install   -                 1.7.3_1                82KB 
ebook-tools               install   -                 0.2.2_3                21KB 
```

And there's a bunch here with a history of CVEs, which isn't worth having on my system for a single app, just as a personal philosophy and security practice:

https://www.cvedetails.com/vulnerability-list/vendor_id-283/product_id-16275/Gnome-Glib.html
https://www.cvedetails.com/vulnerability-list/vendor_id-283/product_id-21096/Gnome-Libsoup.html
https://www.cvedetails.com/vulnerability-list/vendor_id-9481/Gstreamer.html
https://www.cvedetails.com/vulnerability-list/vendor_id-11350/Webkitgtk.html

I am a user for the underlying minimalism potential the distro (void) provides, albeit I understand the current direction isn't necessarily one of minimalism, but I think it would be a preferred practice to not just pull in a whole bunch of dependencies unless strictly necessary, which I am not aware if that is or isn't the case here. If it in fact is, then I just need to find a more minimalist alternative to apvlv, and end of discussion.

**Comment by ahesford** [comment]
You pulled in `webkit2gtk` into your package, these are dependencies for that.

**Comment by ericonr** [comment]
@D-Nice if you'd like to add a build option that removes the webkit2gtk dependency, feel free to do so and make a PR for it. Otherwise the package will probably keep its dependencies.

**Comment by D-Nice** [comment]
@ericonr got it, thanks, I'll consider it depending on the importance of the package, and if it's possible in the first place, was just wondering if this was already considered or explored already.

**Pull request merged**
