### PR TITLE
eigen: upstream switched to gitlab.com

### PR DESCRIPTION
**Pull request by yopito**

### CODE REVIEW

**Comment by sgn** [comment]
If the old archive is still accessible, I see no point to rebuild just for changing mirror.

Let's wait until next release.

Closing now, feel free to reopen if you disagree

**Comment by yopito** [comment]
@sgn: thanks for review.  
I don't agree: more accurate information, that will help to detect the next release. In this other hand, a revbump maybe useless in this case.

**Comment by sgn** [comment]
Make sense, but I'll leave it to other people to decide.
Maybe they have different thought.

At least, I don't support rev bump.

**Comment by Piraty** [comment]
1. please don't revbump an otherwise working package
2. make sure `update-check` still works. most gitlab distfiles require a custom rule i think

**Comment by yopito** [comment]
OK, removed the revdump

yes, I've checked that update-check if fine. With `version=1.0` :
```
$ ./xbps-src update-check eigen
eigen-2.0 -> eigen-3.2.5
eigen-2.0 -> eigen-3.2.6
[...]
eigen-2.0 -> eigen-3.3.6
eigen-2.0 -> eigen-3.3.7
```

**Pull request merged**
