### PR TITLE
dwb: remove.

### PR DESCRIPTION
**Pull request by maxice8**
#2488 

Last commit is from 2016

### CODE REVIEW

**Comment by maxice8** [comment]
@void-linux/pkg-committers opinions please if there are no objections in 2 weeks (that should be plenty of time, if need more just ask) i'll consider this as :shipit:

**Comment by the-maldridge** [comment]
:+1:

**Comment by fosslinux** [comment]
yes please

**Comment by maxice8** [comment]
On Sat, Sep 08, 2018 at 01:23:49AM -0700, Andrea Brancaleoni wrote:
> Why? Is it broken? 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/2510#issuecomment-419623156

Depends on old insecure webkit that is being removed https://github.com/void-linux/void-packages/issues/2488 all others are migrating to webkit2gtk which recieves security patches while this one has pretty much dead upstream as far as i can tell.

**Comment by maxice8** [comment]
also it segfaults currently so 

```
No settingsfile found: Failed to open file “/home/terran/etc/dwb/settings”: No such file or directory
Using default values.
GLib-GIO-Message: 05:44:22.901: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
No keyfile found: No such file or directory
Using default values.
Received SIGSEGV, trying to clean up.

Last 33 stack frames: 

 33: dwb(+0x4538b) [0x55c38bb1938b]
 32: dwb(+0x63d3f) [0x55c38bb37d3f]
 31: /usr/lib/libpthread.so.0(+0x127d0) [0x7f11085067d0]
 30: /usr/lib/libjavascriptcoregtk-3.0.so.0(_ZNK3WTF6String12isolatedCopyEv+0x8) [0x7f110936b598]
 29: /usr/lib/libjavascriptcoregtk-3.0.so.0(_ZNK14OpaqueJSString6stringEv+0x24) [0x7f1108eff1b4]
 28: /usr/lib/libjavascriptcoregtk-3.0.so.0(JSEvaluateScript+0x172) [0x7f1108eda4e2]
 27: dwb(+0x70a52) [0x55c38bb44a52]
 26: dwb(+0x68b7e) [0x55c38bb3cb7e]
 25: /usr/lib/libgobject-2.0.so.0(g_closure_invoke+0x19d) [0x7f1109668a8d]
 24: /usr/lib/libgobject-2.0.so.0(+0x22803) [0x7f110967b803]
 23: /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0xde2) [0x7f1109684792]
 22: /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f1109684ddf]
 21: /usr/lib/libgobject-2.0.so.0(+0x140f4) [0x7f110966d0f4]
 20: /usr/lib/libgobject-2.0.so.0(g_object_notify+0x171) [0x7f110966f521]
 19: /usr/lib/libwebkitgtk-3.0.so.0(+0x449d38) [0x7f110b740d38]
 18: /usr/lib/libwebkitgtk-3.0.so.0(+0xafc5fb) [0x7f110bdf35fb]
 17: /usr/lib/libwebkitgtk-3.0.so.0(+0xb085bb) [0x7f110bdff5bb]
 16: /usr/lib/libwebkitgtk-3.0.so.0(+0xae6d90) [0x7f110bdddd90]
 15: /usr/lib/libwebkitgtk-3.0.so.0(+0x44921e) [0x7f110b74021e]
 14: /usr/lib/libwebkitgtk-3.0.so.0(+0xae6043) [0x7f110bddd043]
 13: /usr/lib/libwebkitgtk-3.0.so.0(+0xaec600) [0x7f110bde3600]
 12: /usr/lib/libwebkitgtk-3.0.so.0(+0xaed724) [0x7f110bde4724]
 11: /usr/lib/libwebkitgtk-3.0.so.0(+0xae58f5) [0x7f110bddc8f5]
 10: /usr/lib/libwebkitgtk-3.0.so.0(+0x5567c6) [0x7f110b84d7c6]
  9: /usr/lib/libwebkitgtk-3.0.so.0(+0x578442) [0x7f110b86f442]
  8: /usr/lib/libglib-2.0.so.0(+0x4cac3) [0x7f1108acaac3]
  7: /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x158) [0x7f1108aca038]
  6: /usr/lib/libglib-2.0.so.0(+0x4c428) [0x7f1108aca428]
  5: /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x2c) [0x7f1108aca4bc]
  4: /usr/lib/libgio-2.0.so.0(g_application_run+0x1fd) [0x7f110994dcbd]
  3: dwb(+0x6f16a) [0x55c38bb4316a]
  2: /usr/lib/libc.so.6(__libc_start_main+0xf1) [0x7f1107e21021]
  1: dwb(+0x4548a) [0x55c38bb1948a]
```

**Comment by thypon** [comment]
👍

**Pull request merged**
