### PR TITLE
New package: opencv4 4.2.0.

### PR DESCRIPTION
**Pull request by ralsei**

### CODE REVIEW

**Comment by ralsei** [comment]
To do that, would these packages just be bumped a revision? Not entirely sure what you mean.

In addition, I'm going to be adding `opencv-contrib` to this package, so hold tight.

**Comment by Hoshpak** [comment]
Exactly. Please also add [ci skip] to the git comment of the last commit since even opencv itself is to massive to be built within the travis timeout. This PR needs to be tested manually before merge.

**Comment by ralsei** [comment]
Should I make a separate commit for including `opencv_contrib` and bumping these package revisions, or should I split them up?

**Comment by Hoshpak** [comment]
One commit for each revision bump please. Adding a new package usually also is a separate commit.

**Comment by ralsei** [comment]
`opencv_contrib` isn't a separate package, though -- it's built and included at compile-time with `opencv`, and I don't believe it's possible to split them.

**Comment by Hoshpak** [comment]
Then it is OK to include it with the update commit. Just add the information that the package is added to the commit title or comment.

**Comment by ralsei** [comment]
Commit dc67ed9 has the configure argument `-DBUILD_opencv_rgbd=OFF`, as it appeared top be missing a library. A similar issue was found here:
https://github.com/opencv/opencv_contrib/issues/2144
albeit no symlink of this nature was found on my system.
The rest of the project compiles without the `rgbd` module.
Not sure what to do about that.

**Comment by ralsei** [comment]
Aaaand when I force-pushed that without changing anything it removed the `[ci skip]` comment. Great. My apologies.

**Comment by ralsei** [comment]
My apologies for the CI running anyway.

**Comment by pullmoll** [comment]
FWIW `actiona` fails to build with:
```
cd actiontools/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /builddir/actiona-3.10.0/actiontools/actiontools.pro PREFIX=/usr LIB=/usr/lib QMAKE_CC=cc QMAKE_CXX=g++ QMAKE_LINK=g++ QMAKE_LINK_C=cc 'QMAKE_CFLAGS=-fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe   -g' 'QMAKE_CXXFLAGS=-fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe   -g' 'QMAKE_LFLAGS=-Wl,-z,relro -Wl,-z,now -Wl,--as-needed    ' ) && make -f Makefile 
Project ERROR: opencv development package not found
make: *** [Makefile:99: sub-actiontools-make_first-ordered] Error 3
=> ERROR: actiona-3.10.0_2: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target} CC="$CC" CXX="$CXX" LINK="$CXX"' exited with 2
=> ERROR:   in do_build() at common/build-style/qmake.sh:58
```

It seems that there is no `/usr/lib/pkgconfig/opencv.pc` or similar and `actiona` does not look for newer `libopencv`.

**Comment by ralsei** [comment]
One thing I noticed when packaging 4.x OpenCV was that /usr/lib/pkgconfig was no longer present.
According to this: https://github.com/opencv/opencv/issues/13154, removal of pkg-config functionality was an intentional change of OpenCV 4.x.

According to this issue on `actiona`'s repo: https://github.com/Jmgr/actiona/issues/90, this issue has been fixed; but only in git, not a "stable" version of the software...

**Comment by xtraeme** [comment]
Next time we need to me careful by checking revdeps

**Comment by pullmoll** [comment]
@xtraeme this PR is not yet merged so I guess we'd better wait for the next actiona release, unless someone wants to backport the change.

**Comment by ralsei** [comment]
it's as simple as changing a build flag for OpenCV itself and changing one name in the `.pro` so I'll give it a go

**Comment by xtraeme** [comment]
@pullmoll OK. Much better. Yes, wait or merge relevant changes.

Thanks pullmoll

**Comment by ralsei** [comment]
`pkg-config` support has been enabled, will work on back-porting changes for `actiona` later.

**Comment by ralsei** [comment]
Patched, and builds on my machine (x86_64 glibc).

**Comment by ralsei** [comment]
Any update on the status of this PR? I'm sorry to bump, and I'm willing to leave this package to myself, if need be.

**Comment by pullmoll** [comment]
I'll retry to build the PR here.

**Comment by pullmoll** [comment]
Humm.. the `opencv4-compat.patch` for `actiona` fails to apply here.
It seems this has to do with MSDOS line endings in `actiona.pro`. I'll try to fix that patch here.

**Comment by pullmoll** [comment]
`digikam` does not detect `opencv4` and also needs a patch.

**Comment by pullmoll** [comment]
Sorry but trying to fix this is taking too much of my time. @ralsei you need to make sure the revbumps actually work before setting this PR to active. As it is this PR cannot be merged.

**Comment by ralsei** [comment]
Is it possible to package this as `opencv4`, `libopencv4`, etc? There's nothing that's explicitly stopping OpenCV 3.x and 4.x from coexisting on the same system, given the separate install directory.

**Comment by pullmoll** [comment]
@ralsei This would make sense. We can then switch packages from `opencv` to `opencv4` whenever they support it. You can modify this PR to create a new package `opencv4` and drop any revbumps.

**Comment by ralsei** [comment]
OpenCV 3.x and 4.x now coexist on my system.

**Pull request merged**
