### PR TITLE
cairo: update to 1.17.2

### PR DESCRIPTION
**Pull request by emacsomancer**

### CODE REVIEW

**Comment by xtraeme** [comment]
unstable version?

**Comment by emacsomancer** [comment]
It's tagged as a snapshot release, but not unstable: https://cairographics.org/news/cairo-1.17.2/

**Comment by q66** [comment]
any odd version in gtk ecosystem is considered unstable

**Comment by xtraeme** [comment]
unstable snapshot is not accepted, thanks anyway

**Comment by emacsomancer** [comment]
@q66 ah, thanks. I didn't know the gtk convention.

**Pull request closed without merging**
