### PR TITLE
qt5: move conflicting files into correct subpkg

### PR DESCRIPTION
**Pull request by Johnnynator**
[ci skip]

### CODE REVIEW

**Comment by pullmoll** [comment]
@Johnnynator I think this is it. I was also working on a solution, trying to remove the qt5-host-tools installed files in the qt5-tools sub-package, but did not yet succeed.

**Comment by Johnnynator** [comment]
> @Johnnynator I think this is it. I was also working on a solution, trying to remove the qt5-host-tools installed files in the qt5-tools sub-package, but did not yet succeed.

These changes worked fine for qt5.13. I wasn't yet able to run the qt5.11 build, but I don't see any reason why it should fail there.

**Comment by pullmoll** [comment]
Yeah, same problem here. Even with ccache testing such a change takes time. I'll verify it here.

**Comment by xtraeme** [comment]
We can now see file conflicts while building packages,
see https://github.com/void-linux/void-packages/commit/e2f098b97271ec9c91ddc320171cedf1a5fad273

**Comment by xtraeme** [comment]
```
=> vlc-3.0.7_1: installing target dependency 'qt5-x11extras-devel-5.11.3_7' ...
ERROR: qt5-host-tools-5.11.3_7: file `/usr/bin/qdbuscpp2xml-qt5' already installed by package qt5-5.11.3_7.
ERROR: qt5-host-tools-5.11.3_7: file `/usr/bin/qdbusxml2cpp-qt5' already installed by package qt5-5.11.3_7.
ERROR: qt5-host-tools-5.11.3_7: file `/usr/bin/qlalr-qt5' already installed by package qt5-5.11.3_7.
ERROR: qt5-host-tools-5.11.3_7: file `/usr/bin/rcc-qt5' already installed by package qt5-5.11.3_7.
ERROR: qt5-host-tools-5.11.3_7: file `/usr/bin/uic-qt5' already installed by package qt5-5.11.3_7.
```

Not sure if this is fixed here, but just in case.

**Comment by Johnnynator** [comment]
> ```
> => vlc-3.0.7_1: installing target dependency 'qt5-x11extras-devel-5.11.3_7' ...
> ERROR: qt5-host-tools-5.11.3_7: file `/usr/bin/qdbuscpp2xml-qt5' already installed by package qt5-5.11.3_7.
> ERROR: qt5-host-tools-5.11.3_7: file `/usr/bin/qdbusxml2cpp-qt5' already installed by package qt5-5.11.3_7.
> ERROR: qt5-host-tools-5.11.3_7: file `/usr/bin/qlalr-qt5' already installed by package qt5-5.11.3_7.
> ERROR: qt5-host-tools-5.11.3_7: file `/usr/bin/rcc-qt5' already installed by package qt5-5.11.3_7.
> ERROR: qt5-host-tools-5.11.3_7: file `/usr/bin/uic-qt5' already installed by package qt5-5.11.3_7.
> ```
> 
> Not sure if this is fixed here, but just in case.

This should be fixed here, at least it is on my qt 5.13 branch https://void.johnnynator.dev/qt5.13/ / #11891

**Comment by pullmoll** [comment]
Yes, this PR solves the issue. No warning during the build (x86_64) and trying to build vlc doesn't print warnings either.

**Pull request merged**
