### PR TITLE
shlibs: add libAppStreamQt.so.2

### PR DESCRIPTION
**Pull request by teldra**

### CODE REVIEW

**Comment by ericonr** [comment]
Can you explain why this is necessary?

**Comment by teldra** [comment]
I try to package a calamares and building stops, because xbps-src don't find libAppStreamQt.so.2 in shlibs

**Comment by ericonr** [comment]
Might make more sense to include this with a calamares PR, then, I think.

**Comment by teldra** [comment]
I am not sure, to PR calamares. Do not think, anyone benefits from it, since its an gui-installer. But I thought, adding libAppStreamQt.so.2 to shlibs for all, might reduce problems for other people in the future. Can close this PR, if its unnecessary.

**Pull request closed without merging**
