### PR TITLE
updates to linbox-1.7.0, givaro-4.2.0, fflas-ffpack-2.5.0, rebuild sagemath

### PR DESCRIPTION
**Pull request by tornaria**
This update is stalled in sagemath (see https://github.com/sagemath/sage/issues/32959) and I don't have a particular reason to do it, but just to be ready. Arch linux uses the updated versions, and the patch needed for sagemath is quite small.

The 3 packages updated (givaro, fflas-ffpack, linbox) need a few small patches just to support i686 and are all taken from and merged upstream.

#### Testing the changes
- I tested the changes in this PR: **very briefly**

@dkwo : maybe you want to try this on aarch64.

### CODE REVIEW

**Comment by tornaria** [comment]
The build on `x86_64` for a stupid transient reason:
```
=> fflas-ffpack-2.5.0_1: fetching distfile 'fflas-ffpack-2.5.0.tar.gz' from 'https://github.com/linbox-team/fflas-ffpack/releases/download/v2.5.0/fflas-ffpack-2.5.0.tar.gz'...
https://github.com/linbox-team/fflas-ffpack/releases/download/v2.5.0/fflas-ffpack-2.5.0.tar.gz: Service Unavailable
=> ERROR: fflas-ffpack-2.5.0_1: failed to fetch 'fflas-ffpack-2.5.0.tar.gz'.
```

**Comment by dkwo** [comment]
Let met try that. Btw, don't you want to revbump sage?

**Comment by dkwo** [comment]
Not too bad :) This is after rebuilding `libtool` and `ntl`, with `xbps_check_pkgs=yes`:
```
sage -t --warn-long 30.0 --random-seed=230775089920805747071539279191783974296 /builddir/sagemath-9.8/pkgs/sagemath-standard/build/lib.linux-aarch64-cpython-311/sage/groups/perm_gps/permgroup.py  # 2 doctests failed
sage -t --warn-long 30.0 --random-seed=230775089920805747071539279191783974296 /builddir/sagemath-9.8/pkgs/sagemath-standard/build/lib.linux-aarch64-cpython-311/sage/parallel/map_reduce.py  # Timed out
sage -t --warn-long 30.0 --random-seed=230775089920805747071539279191783974296 /builddir/sagemath-9.8/pkgs/sagemath-standard/build/lib.linux-aarch64-cpython-311/sage/sets/recursively_enumerated_set.pyx  # Timed out
```
Full log: https://paste.c-net.org/AddictPleasure

**Comment by tornaria** [comment]
This  is ready, and the upstream PR is good now  https://github.com/sagemath/sage/pull/35612.

It may be better to do this when we upgrade to 10.0.

**Comment by tornaria** [comment]
This is supserseded by #43659

**Pull request closed without merging**
