### PR TITLE
New packages: hamster-time-tracker-3.0.2 xfce4-hamster-plugin-1.17

### PR DESCRIPTION
**Pull request by aquaherd**
I am the author of this xfce4 panel plugin and I want it in void, so I packaged it.

### CODE REVIEW

**Comment by aquaherd** [comment]
I was not aware that the gtk2/python2 hamster-applet was dropped from void last September - I still had it running.
So I had to package the gtk3/python3 hamster-time-tracker, too.

**Comment by kawaiiamber** [comment]
On the `aarch64-musl` arch, the check it reporting
```
ERROR: [trans] failed to download `libglvnd-devel-1.3.2_1' signature from `http://alpha.us.repo.voidlinux.org/current/aarch64': Transient resolver failure
Transaction failed! see above for errors.
libglvnd-1.3.2_1: verifying RSA signature...
Error: Process completed with exit code 1.
```
From my experience, just repushing might fix it.

**Comment by aquaherd** [comment]
Now it fails due to locale folder being in /usr/lib. Will fix this upstream and rebase when done.

**Comment by aquaherd** [comment]
Cant say I like autotools.

**Comment by kawaiiamber** [comment]
Whoa, it looks like you pulled all changes from latest upstream. Add upstream as a remote, make sure you're on your branch, then rebase:
```sh
git remote add upstream https://github.com/void-linux/void-packages.git
git pull --rebase upstream master
git push origin master -f
```
It's generally a good practice to have a different branch for your PR, especially if you want to do multiple PRs. I would make a branch for your package that you want specifically.
```
git checkout -b hamster
```
Edit your template in srcpkgs/\<pkg\>/template, then push one commit to that branch.
```
git add -A
git commit -m "New package: xcfe4-hamster-plugin-1.8"
git push origin hamster
```
Then, on this PR, switch the branch from your master branch to your hamster branch to be merged with upstream master. Squash any future commits with `amend`:
```
git add -A
git commit --amend
git push origin hamster -f
```

**Comment by aquaherd** [comment]
Thanks. 
After 20 years on subversion I am having a hard time grokking git. 

Do you have any idea how to skip the make check / do_check stage? It works with ./xbps-src pkg but fails here in github.

**Comment by ericonr** [comment]
You can run checks locally with `./xbps-src pkg -Q package`. Running tests in CI, assuming they can be made to work without adding too many new packages, helps us guarantee that the system behavior is as close to what upstream expects.

**Comment by aquaherd** [comment]
Thank you all for your patience.

**Comment by kawaiiamber** [comment]
Since there's two packages, split the two files to two commits - one per package.

**Comment by aquaherd** [comment]
> Since there's two packages, split the two files to two commits - one per package.

OK done

**Comment by kawaiiamber** [comment]
> > Since there's two packages, split the two files to two commits - one per package.
> 
> OK done

There's three commits.

**Comment by aquaherd** [comment]
Could somebody please merge this? It is slow paced and will not change much.

**Comment by kawaiiamber** [comment]
> Could somebody please merge this? It is slow paced and will not change much.

You might need to rebase and push again so everyone can see the CI status.

**Comment by aquaherd** [comment]
OK, reabesed and force-pushed.

**Pull request closed without merging**
