### PR TITLE
Trigger rebuilds for packages that aren't in musl repos.

### PR DESCRIPTION
**Pull request by ericonr**

### CODE REVIEW

**Comment by sgn** [comment]
On 2020-09-02 12:18:49-0700, Érico Nogueira Rolim <notifications@github.com> wrote:
>   * tarsnap: rebuild to appear in musl repos.

tarsnap is restricted

I'm checking other things.

**Comment by ericonr** [comment]
@sgn most of the cross stuff should now be fixed. I built everything for `armv7l-musl`, and I think it's short enough that CI can finish the build as well.

**Comment by ericonr** [comment]
The builders will time out for glibc native builds, because `renderdoc` is stupidly large.

**Comment by Duncaen** [comment]
The revision doesn't need to be increased, touching the template is enough to trigger a build for a package that doesn't exist.

**Pull request closed without merging**
