### PR TITLE
testdisk: Add missing ncurses-base dependency

### PR DESCRIPTION
**Pull request by jarda-wien**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by jarda-wien** [comment]
I get this error message without the ncurses package installed:
```bash
testdisk
TestDisk 7.1, Data Recovery Utility, July 2019
Christophe GRENIER <grenier@cgsecurity.org>
https://www.cgsecurity.org
Terminfo file is missing.
Extract all files and subdirectories before running the program.
Press Enter key to quit.
```

**Comment by jarda-wien** [comment]
I am not sure what to do about the xlint failure as this is probably my first contribution and the proposed changes are only minor.

**Comment by FollieHiyuki** [comment]
You can change the license to `license="GPL-2-or-later"`

**Comment by jarda-wien** [comment]
> You can change the license to `license="GPL-2.0-or-later"`

done, thanks

**Comment by Duncaen** [comment]
The consensus is that packages shouldn't depend on ncurses-base, packages use some terminfo that can't be expressed as dependency as it depends on your TERM variable. Generally ncurses-base should be installed as part of the base system i.e. the base-system metapackage, it's deliberately not Part of base-minimal as it would increase container sizes. If we would start to add ncurses-base to everything that might need it, we would effectively add it to base-minimal as i.e. util-linux's cfdisk "depends" on terminfo descriptions.

**Comment by jarda-wien** [comment]
> The consensus is that packages shouldn't depend on ncurses-base, packages use some terminfo that can't be expressed as dependency as it depends on your TERM variable. Generally ncurses-base should be installed as part of the base system i.e. the base-system metapackage, it's deliberately not part of base-minimal as it would increase container sizes. If we would start to add ncurses-base to everything that might need it, we would effectively add it to base-minimal as i.e. util-linux's cfdisk "depends" on terminfo descriptions.

My main use case for the testdisk package was having it in a minimal docker container, so I didn't have "base-system" installed. While I understand the reasoning behind *the consensus*, I am not sure if we have any means of at least warning the user that something is missing. Being mostly on archlinux systems, I am not very seasoned in metadata fields provided by void packages. I tried googling something like optional dependecies and came across [this](https://github.com/void-linux/xbps/issues/1).

Please point me to some preferred possibility of informing the user that something is missing in the current environment. If there is no such tool available, I guess you can reject this PR and keep things the way they are.

**Comment by sgn** [comment]
For all normal user, they should use `base-system`. `base-system` is the package which users are told to install in `void-docs`.
IMO, anyone that choose to not install base-system should have enough experience to know what's missing.

**Pull request closed without merging**
