### PR TITLE
icu-70.1, firefox-96.0

### PR DESCRIPTION
**Pull request by Duncaen**
[ci skip]

Maybe I could add harfbuzz>=3.0.0, that would pull in the electron packages though, but there are many overlapping ones.

Updated:
* firefox-96.0
* firefox-esr-91.5.0
* thunderbird-91.5.0
* webkit2gtk-2.34.3
* nodejs-16.13.2 (for python3.10)
* php-7.4.27 (to unbreak icu api usage)

### CODE REVIEW

**Comment by dkwo** [comment]
Would you mind updating `thunderbird` to 91.5.0 since you're already rebuilding it?

**Comment by q66** [comment]
please also bump `webkit2gtk` to 2.34.3

**Comment by Johnnynator** [comment]
Can you add the qt5-webengine update to this? https://github.com/Johnnynator/void-packages/commit/7d3d1a3fbaf8d008de504efc0fcccb147877b54c Currently test building with new icu, only tested with old so far.

**Comment by Duncaen** [comment]
> Can you add the qt5-webengine update to this? [Johnnynator@7d3d1a3](https://github.com/Johnnynator/void-packages/commit/7d3d1a3fbaf8d008de504efc0fcccb147877b54c) Currently test building with new icu, only tested with old so far.

Added the commit and added the `libXdamage-devel` dependency to it.

**Pull request closed without merging**
