### PR TITLE
Remove ebtables and arptables

### PR DESCRIPTION
**Pull request by knusbaum**
This is my solution for #10293

### CODE REVIEW

**Comment by Chocimier** [comment]
For not breaking things, those packages should either still provide compatible service and depend on iptables, or be removed explicitely, in the way resolving https://github.com/void-linux/void-packages/pull/9745.

**Comment by knusbaum** [comment]
@Chocimier I can add iptables to the depends of these packages, but the only package that depends on them has been changed to depend on iptables. Am I missing something?

**Comment by Chocimier** [comment]
@knusbaum Previous comment was turned more to people who can merge this than to you.

> Am I missing something?

The problem is that when package is removed package from repo, during system update it is also silently removed where it was installed either explicitly or as dependency. Not everyone want dissapearing suddenly a service he enabled.

**Comment by knusbaum** [comment]
@Chocimier Yes, this morning I realized that we don't want to break explicit installs or custom packages. I've updated the removed packages to depend on iptables.

**Pull request merged**
