### PR TITLE
qalculate: update to 5.0.0

### PR DESCRIPTION
**Pull request by varuld**
#### Testing the changes
- I tested the changes in this PR:**YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-musl)

### CODE REVIEW

**Comment by varuld** [comment]
ping @yoshiyoshyosh

**Comment by yoshiyoshyosh** [comment]
don't know how I missed both the update and this pr until now... oops

yeah, everything looks good. might want to force-push the commit to be the same name as the current pr name before the void team merges it

**Comment by yoshiyoshyosh** [comment]
[5.1.1 seems to be out now](https://github.com/Qalculate/libqalculate/releases/tag/v5.1.1)

**Comment by cinerea0** [comment]
You're well within your rights to open a separate PR for the newer version, @yoshiyoshyosh.

**Comment by varuld** [comment]
@yoshiyoshyosh I'll assume that you'll be making a new PR with the latest version, so closing this as outdated.

**Pull request closed without merging**
