### PR TITLE
emacs-x11: enable DBus support

### PR DESCRIPTION
**Pull request by egorenar**

### CODE REVIEW

**Comment by xtraeme** [comment]
I would prefer to make this a build option.

**Comment by leahneukirchen** [comment]
Why? DBus adds all kind of lockup issues with Emacs (#15911), and I'd like to keep the x11 version slim. You could just use the GTK versions instead.

**Comment by egorenar** [comment]
i'm also having trouble with gtk version, i didn't modify the x11 version but added an new one with dbus enabled.
i use dbus e.g. for IRC notifications.

**Comment by leahneukirchen** [comment]
What kind of trouble? I'm not really in favor of having to compile emacs 5 times.

**Comment by egorenar** [comment]
e.g. color of selected region is almost equal background color so that i have trouble seeing it.

**Comment by leahneukirchen** [comment]
Isn't that just a matter of changing the region font-face?

**Comment by egorenar** [comment]
you are right, sorry for spam

**Pull request closed without merging**
