### PR TITLE
linux4.19: enable support for Amlogic S905X SoC

### PR DESCRIPTION
**Pull request by marmeladema**

### CODE REVIEW

**Comment by marmeladema** [comment]
Should i increase the revision number in the template for such changes ?

**Comment by CameronNemo** [comment]
Yes, and consider making the changes a single commit.

**Comment by marmeladema** [comment]
@CameronNemo done! Anything else i need to fix / improve ?

**Comment by Hoshpak** [comment]
lgtm Please add `[skip ci]` to the commit the next time you open a PR for a kernel. Kernel builds take a long time and will lead to a timeout on travis. I cancelled the build to avoid wasting CPU cycles on the travis servers.

**Comment by marmeladema** [comment]
> lgtm Please add `[skip ci]` to the commit the next time you open a PR for a kernel. Kernel builds take a long time and will lead to a timeout on travis. I cancelled the build to avoid wasting CPU cycles on the travis servers.

Anywhere in the commit will do ?

**Comment by Johnnynator** [comment]
> > lgtm Please add `[skip ci]` to the commit the next time you open a PR for a kernel. Kernel builds take a long time and will lead to a timeout on travis. I cancelled the build to avoid wasting CPU cycles on the travis servers.
> 
> Anywhere in the commit will do ?

Yep anywhere in the commit message should work.

**Pull request merged**
