### PR TITLE
yazi: update to 0.3.1.

### PR DESCRIPTION
**Pull request by Rooyca**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by manfred3000** [comment]
This is basically a bug fix release addressing bugs introduced with the previous major release...

**Comment by tranzystorekk** [comment]
Completed in a1dc36f

**Comment by Rooyca** [comment]
why

**Comment by tranzystorekk** [comment]
I happened to notice and merge the #52026 PR first, so this one is no longer needed

**Comment by Bnyro** [comment]
> why
>
Besides, I'm the maintainer of the package, so please ping me (or whoever is the maintainer) when updating someone else's package. I didn't notice this PR existed.

**Pull request closed without merging**
