### PR TITLE
New package: wayland-utils-1.0.0

### PR DESCRIPTION
**Pull request by vyivel**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
https://gitlab.freedesktop.org/wayland/wayland-utils claims that this is entirely equivalent to `weston-info`, which people can easily install...

**Comment by ericonr** [comment]
We could also consider splitting `weston-info` into a subpackage of `weston`.

**Comment by vyivel** [comment]
weston-info is [deprecated](https://github.com/wayland-project/weston/blob/1c73ff8d57404ba0e9bd36b2ecaa8448a809473d/clients/weston-info.c#L1864).

**Comment by vyivel** [comment]
Ping?

**Pull request merged**
