### PR TITLE
fbpdf: update to 0.0.20200616.

### PR DESCRIPTION
**Pull request by ailiop-git**

### CODE REVIEW

**Review by Piraty — CHANGES_REQUESTED** [review]
* please use `vsed`
* please introduce a `_githash` variable (take other templates for reference)

**Comment by ailiop-git** [comment]
>     * please use `vsed`
> 
>     * please introduce a `_githash` variable (take other templates for reference)

thanks for the review, requested changes pushed.

**Comment by Duncaen** [comment]
Please squash the commits.

**Comment by ailiop-git** [comment]
> Please squash the commits.

oops, pushed now.

**Pull request merged**
