### PR TITLE
nodejs: update to 14.7.0

### PR DESCRIPTION
**Pull request by Noah-Huppert**
Works on my machine (`x86_64`):

```
% ./xbps-src pkg nodejs
% sudo xbps-install --repository "$PWD/hostdir/binpkgs/node14/" -Syu nodejs
% node -v
v14.5.0
```

I removed the patches b/c I assume in this version they aren't needed? Someone familiar with the package should confirm this.

### CODE REVIEW

**Comment by ericonr** [comment]
@q66 is it still broken for ppc?

**Comment by Noah-Huppert** [comment]
Power PC?

**Comment by Noah-Huppert** [comment]
CI build timed out. It took a long time to build on my laptop as well.

**Comment by fosslinux** [comment]
Add [ci skip] to the commit message if you push again.

**Comment by Noah-Huppert** [comment]
Pushed with CI skip.

**Comment by bn4t** [comment]
Would be great to have this merged. Currently can't use tailwindcss because of a bug in the version that's currently available in the repo.

**Comment by Noah-Huppert** [comment]
Bumping to 14.7.0 rn.

**Comment by Noah-Huppert** [comment]
Now PR is for nodejs 14.7.0. Build took ~1:30 hours so skipping the CI.

**Comment by q5sys** [comment]
This would be a really helpful update as some versions in the Node 13.x range have buggy ES module support or need --experimental-modules at the command line.

**Comment by Noah-Huppert** [comment]
Not really sure why the PR hasn't been merged...

**Comment by q5sys** [comment]
yea idk.  I was thinking of seeing if I could figure out the 14.10 release
but checked to see if there were any outstanding PRs for a newer version,
and sure enough I found your PR.

**Comment by Noah-Huppert** [comment]
bumping this PR to 4.10.0 now.

**Comment by Johnnynator** [comment]
I will look into this PR this weekend.

**Comment by Noah-Huppert** [comment]
> bumping this PR to 4.10.0 now.
Having issues, I wonder if 4.10.0 requires new dependencies.
```
  g++ -o /builddir/node-v14.10.0/out/Release/obj.target/libnode/src/node.o ../src/node.cc '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNODE_ARCH="x64"' '-DNODE_PLATFORM="linux"' '-DNODE_WANT_INTERNALS=1' '-DV8_DEPRECATION_WARNINGS=1' '-DNODE_OPENSSL_SYSTEM_CERT_PATH=""' '-DHAVE_INSPECTOR=1' '-DNODE_ENABLE_LARGE_CODE_PAGES=1' '-D__POSIX__' '-DNODE_USE_V8_PLATFORM=1' '-DNODE_HAVE_I18N_SUPPORT=1' '-DHAVE_OPENSSL=1' -I../src -I/builddir/node-v14.10.0/out/Release/obj/gen -I/builddir/node-v14.10.0/out/Release/obj/gen/include -I/builddir/node-v14.10.0/out/Release/obj/gen/src -I../deps/histogram/src -I../deps/uvwasi/include -I../deps/v8/include -I../deps/brotli/c/include -I../deps/openssl/openssl/include  -Wall -Wextra -Wno-unused-parameter -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -MMD -MF /builddir/node-v14.10.0/out/Release/.deps//builddir/node-v14.10.0/out/Release/obj.target/libnode/src/node.o.d.raw     -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe  -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -c
../src/node.cc: In function 'int node::Start(int, char**)':
../src/node.cc:1092:42: error: 'UV_METRICS_IDLE_TIME' was not declared in this scope
 1092 |     uv_loop_configure(uv_default_loop(), UV_METRICS_IDLE_TIME);
      |                                          ^~~~~~~~~~~~~~~~~~~~
make[1]: *** [libnode.target.mk:313: /builddir/node-v14.10.0/out/Release/obj.target/libnode/src/node.o] Error 1
rm 80455764c1d44a2c5307476ee8e59d862d62cc4f.intermediate
make: *** [Makefile:104: node] Error 2
=> ERROR: nodejs-14.10.0_1: do_build: 'make LD="$CXX" LDFLAGS+=-ldl ${makejobs} V=1' exited with 2
=> ERROR:   in do_build() at srcpkgs/nodejs/template:101
```

**Comment by Johnnynator** [comment]
> > bumping this PR to 4.10.0 now.
> 
> Having issues, I wonder if 4.10.0 requires new dependencies.
> 
> ```
>   g++ -o /builddir/node-v14.10.0/out/Release/obj.target/libnode/src/node.o ../src/node.cc '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNODE_ARCH="x64"' '-DNODE_PLATFORM="linux"' '-DNODE_WANT_INTERNALS=1' '-DV8_DEPRECATION_WARNINGS=1' '-DNODE_OPENSSL_SYSTEM_CERT_PATH=""' '-DHAVE_INSPECTOR=1' '-DNODE_ENABLE_LARGE_CODE_PAGES=1' '-D__POSIX__' '-DNODE_USE_V8_PLATFORM=1' '-DNODE_HAVE_I18N_SUPPORT=1' '-DHAVE_OPENSSL=1' -I../src -I/builddir/node-v14.10.0/out/Release/obj/gen -I/builddir/node-v14.10.0/out/Release/obj/gen/include -I/builddir/node-v14.10.0/out/Release/obj/gen/src -I../deps/histogram/src -I../deps/uvwasi/include -I../deps/v8/include -I../deps/brotli/c/include -I../deps/openssl/openssl/include  -Wall -Wextra -Wno-unused-parameter -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -MMD -MF /builddir/node-v14.10.0/out/Release/.deps//builddir/node-v14.10.0/out/Release/obj.target/libnode/src/node.o.d.raw     -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe  -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -c
> ../src/node.cc: In function 'int node::Start(int, char**)':
> ../src/node.cc:1092:42: error: 'UV_METRICS_IDLE_TIME' was not declared in this scope
>  1092 |     uv_loop_configure(uv_default_loop(), UV_METRICS_IDLE_TIME);
>       |                                          ^~~~~~~~~~~~~~~~~~~~
> make[1]: *** [libnode.target.mk:313: /builddir/node-v14.10.0/out/Release/obj.target/libnode/src/node.o] Error 1
> rm 80455764c1d44a2c5307476ee8e59d862d62cc4f.intermediate
> make: *** [Makefile:104: node] Error 2
> => ERROR: nodejs-14.10.0_1: do_build: 'make LD="$CXX" LDFLAGS+=-ldl ${makejobs} V=1' exited with 2
> => ERROR:   in do_build() at srcpkgs/nodejs/template:101
> ```

https://nodejs.org/en/blog/release/v14.9.0/

^ they upgraded to libuv 1.39. So the libuv package in Void also needs updating.

**Comment by Johnnynator** [comment]
Nodejs 14 (12.18.3 also) do have a broken `--shared-libuv` config flag, they do link against `out/Release/obj.target/deps/uv/libuv.a` first, and to `-luv` only later. Which also should be fixed.

**Comment by leahneukirchen** [comment]
f88309c3d3

**Comment by Noah-Huppert** [comment]
@leahneukirchen THANK YOU! Appreciate you very much 😁

**Pull request closed without merging**
