### PR TITLE
Initial libgnome-keyring removal

### PR DESCRIPTION
**Pull request by CameronNemo**
@Cogitri please test pinentry-gnome, considering you added the libgnome-keyring dependency there

Also see mate-desktop/mate-power-manager#239

### CODE REVIEW

**Comment by CameronNemo** [comment]
https://sources.debian.org/patches/libcryptui/3.12.2-5/daemon-port-to-gcr-3.patch/

**Comment by CameronNemo** [comment]
See also #4884

**Comment by Cogitri** [comment]
Wait, why would we apply downstream patches to remove dependencies?

**Comment by Cogitri** [comment]
I don't quite see why we would do this. Sure, libgnome-keyring is deprecated and it's encouraged to use libsecret or friends instead, but just removing functionality for some reason doesn't sound good to me. Or is there some major CVE or smth in libgnome-keyring?

**Comment by CameronNemo** [comment]
Did you test the pinentry package that uses libsecret? That one should have no loss of functionality.

**Comment by Cogitri** [comment]
I think that's pinentry-gnome and that only saves passwords for up to 15 minutes

**Comment by Cogitri** [comment]
> Did you test the pinentry package that uses libsecret? That one should have no loss of functionality.

Sorry, it appears that we _can_ enable (somewhat) permanent storage via libsecret explicitly during build with `--enable-libsecret`. Without that switch it only does temporary saving of passwords, so that's where my confusion stemmed from. The "problem" is that `--enable-libsecret` enables it for all pinentry programs, so all of them will pull in libsecret. But since libsecret only really pulls in libgcrypt (and glib, but I don't think one gets around that anyway) that shouldn't be too much of a problem,  I guess...

**Pull request closed without merging**
