### PR TITLE
python3-regex: update to 2020.9.27

### PR DESCRIPTION
**Pull request by priner**

### CODE REVIEW

**Comment by ericonr** [comment]
Any idea why the test suite fails?

```
running egg_info
writing regex.egg-info/PKG-INFO
writing dependency_links to regex.egg-info/dependency_links.txt
writing top-level names to regex.egg-info/top_level.txt
reading manifest file 'regex.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'regex.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.9/regex/_regex.cpython-39-x86_64-linux-gnu.so -> regex_3
regex_2 (unittest.loader._FailedTest) ... ERROR
regex_3 (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: regex_2 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: regex_2
Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/builddir/regex-2020.9.27/regex_2/__init__.py", line 1, in <module>
    from .regex import *
  File "/builddir/regex-2020.9.27/regex_2/regex.py", line 501
    except error, e:
                ^
SyntaxError: invalid syntax


======================================================================
ERROR: regex_3 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: regex_3
Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/builddir/regex-2020.9.27/regex_3/__init__.py", line 1, in <module>
    from .regex import *
  File "/builddir/regex-2020.9.27/regex_3/regex.py", line 404, in <module>
    import regex._regex_core as _regex_core
ModuleNotFoundError: No module named 'regex'


----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=2)
Test failed: <unittest.runner.TextTestResult run=2 errors=2 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=2 errors=2 failures=0>
```

**Comment by ahesford** [comment]
The `regex_2` test is failure because it uses obsolete py2 exception labeling syntax that py3 rejects.

Not sure about the import failure; I'm not at a PC and can't look closely now.

**Comment by ahesford** [comment]
The default test setup is broken because the package includes both `regex_2` and `regex_3` alternatives for py2 and py3, respectively. If `regex_2` is removed and the symlink `regex -> regex_3` is created, `python3 setup.py test` succeeds.

**Comment by ahesford** [comment]
Looks like this is outdated; please bump to 2020.10.15. Don't worry if the tests don't pass because it appears that the upstream test configuration is broken.

**Pull request closed without merging**
