### PR TITLE
wireplumber: update to 0.4.12, drop dbus check from service file

### PR DESCRIPTION
**Pull request by dkwo**
- I tested the changes in this PR: **YES**
- I built this PR locally for my native architecture, (x86_64-musl)

According to https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/237 and https://forum.artixlinux.org/index.php/topic,4230.0.html , DBUS is not required, so I dropped it from the service file: everything is working as expected.
(No dbus, no elogind, no membership in audio group: just using seatd and run wireplumber as root using the provided service, my user is member of pipewire group.)

@ericonr @ahesford @Animeshz

### CODE REVIEW

**Comment by Duncaen** [comment]
Does everything that depends on dbus still work if dbus is not available on startup? (bluez)?

**Comment by ahesford** [comment]
I think it's fine to drop dbus from a service we generally advise against, but if you're going to drop the check, you should also drop the `dbus-run-session` wrapper around the `wireplumber` execution.

**Comment by Duncaen** [comment]
But its a regression for anyone currently using it, not enabling dbus cripples wireplumber quite a bit. IMHO it would make more sense to let users who don't want to use dbus write their own service if they want to run a system-wide wireplumber.

**Comment by Duncaen** [comment]
But then again, including system wide services as long as they are not fully supported was probably a mistake, just like with pulse.

**Comment by dkwo** [comment]
@duncaen I see your point. Can you test whether this breaks dbus dependants? I have no such stuff on my machine right now.

**Comment by Duncaen** [comment]
I'm not sure, from just running it manually it seems like modules not being loaded if dbus is not available.

**Comment by dkwo** [comment]
Let me close this, as it's not clear it's actually a good idea.

**Pull request closed without merging**
