### PR TITLE
New package: FAudio | wine: enable FAudio

### PR DESCRIPTION
**Pull request by Francesco149**
FAudio support has recently been merged into wine. it fixes many sound crackling issues in xaudio games. this adds the FAudio library and enables it in the wine build

### CODE REVIEW

**Comment by Hoshpak** [comment]
The symlink for FAudio-devel is missing.

**Comment by Francesco149** [comment]
oops

**Comment by Francesco149** [comment]
hm, this might need SDL2-devel as a host dependency for cross compilation due to ```sdl2-config```

**Comment by Francesco149** [comment]
turns out the cmake file for SDL2 is just broken from cross compilation, manually adding the include dirs fixes cross compilation

**Pull request merged**
