### PR TITLE
herbstluftwm: update to 0.8.0

### PR DESCRIPTION
**Pull request by Nairou**

### CODE REVIEW

**Comment by Nairou** [comment]
Works on x64. Not sure why CI complains about X11 for other platforms. I tried adding a libX11-devel dependency, but it didn't help.

**Comment by natrys** [comment]
Any reason you don't just use `build_style=cmake`? It will take care of cross-building. That way you can also get rid of `do_build` and `do_install` blocks. Move license and completions stuffs to `post_install`. You can test locally for other archs (like e.g. `./xbps-src -a aarch64 pkg herbstluftwm`).

**Comment by Nairou** [comment]
> Any reason you don't just use `build_style=cmake`? It will take care of cross-building. That way you can also get rid of `do_build` and `do_install` blocks. Move license and completions stuffs to `post_install`. You can test locally for other archs (like e.g. `./xbps-src -a aarch64 pkg herbstluftwm`).

Testing other archs locally sounds great. Where can I see how to use build_style? These are new changes, the previous version didn't use cmake.

I'm just an end-user trying to get an orphaned package updated for the first time. :smile:

**Comment by mustaqimM** [comment]
You can read it here:
https://github.com/void-linux/void-packages/blob/master/Manual.md#build-style-scripts

**Comment by travankor** [comment]
Basically, get rid of `do_build` and `do_install` sections and add `build_style=cmake`. Once you get it working run xlint to fix errors up.

**Comment by Nairou** [comment]
@natrys @mustaqimM @travankor Thank you for your help! I think I'm getting the hang of this. :smile:

**Pull request merged**
