### PR TITLE
dropbox: update to 2019.01.31

### PR DESCRIPTION
**Pull request by purpurrot**

### CODE REVIEW

**Comment by maxice8** [comment]
Is there a way to use it without downloading their propietary dropboxd daemon ?

**Comment by purpurrot** [comment]
I don't think so. This package is just the open-source helper program.

**Comment by maxice8** [comment]
On Thu, Feb 07, 2019 at 01:27:41PM -0800, purpurrot wrote:
> I don't think so. This package is just the open-source helper program.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/8183#issuecomment-461602230

Sounds fine in theory but in practice it is (as far as i understand) useless
without the proprietary program.

Oh well, let it slide.

**Comment by purpurrot** [comment]
Yeah, that's kind of what the say on their webpage.

https://www.dropbox.com/install-linux

**Pull request merged**
