### PR TITLE
New package: vivid-0.6.0

### PR DESCRIPTION
**Pull request by FollieHiyuki**
A Rust tool to simply generate LS_COLORS from a defined theme.
[https://github.com/sharkdp/vivid](https://github.com/sharkdp/vivid)

### CODE REVIEW

**Comment by FollieHiyuki** [comment]
There are .yml files in the repo I wanted to add to **/usr/share/vivid** as sample config. I tried to do
```
vmkdir usr/share/vivid 755
vinstall config/filetypes.yml 644 usr/share/vivid filetypes.yml
```
but it doesn't work and I can't find a concrete sample of how to do this.

**Comment by abenson** [comment]
If you use `vsconf`, it'll place them in `/usr/share/examples/vivid`

**Comment by abenson** [comment]
Use 'New package: vivid-0.6.0' for the commit message

**Comment by FollieHiyuki** [comment]
@abenson can you do a review again? Sorry for the ping.
This is a simple Rust program, so I think it is good to merge as it is now.
I recently made a small change, so that the `examples` directory contains all the themes samples as well.

**Pull request merged**
