### PR TITLE
blender: update to 2.83.5

### PR DESCRIPTION
**Pull request by jkoderu-git**

### CODE REVIEW

**Review by ahesford — CHANGES_REQUESTED** [review]
This template circumvents proper `xlint` checks because of the blank lines 21 (after `patch_args`) and 24 (after `pycompile_dirs`). Please remove these blank lines and satisfy the `xlint` checks that will fail as a result.

Also, when moving `configure_args`, please make sure to indent continued lines with one space.

**Comment by martnnw** [comment]
Isn't 2.90 out already? Or are you guys planing on supporting the LTS versions?

**Comment by jkoderu-git** [comment]
> Isn't 2.90 out already? Or are you guys planing on supporting the LTS versions?

Possibly 2 packages for lts and current? Although I am not experienced to package the new 2.90.

**Comment by martnnw** [comment]
Alpine has 2.90 packaged.

**Comment by ahesford** [comment]
You should install `xtools` and run `xlint blender` from your `void-packages` repo locally, because `xlint` sometimes takes several iterations to identify all template quality issues. Each time you iterate through CI you consume 50 minutes of time.

Regarding 2.90, I'm not a blender user, so we'll need to get some input from other users to decide whether bumping to 2.90 makes sense or a blender-lts package is appropriate.

**Comment by martnnw** [comment]
The LTS versions are intended for Larger organizations that work on longer projects such as feature films and therefore need a version that is dependable and does not break when new features are introduced. Constant breakage could lead to unnecessary production costs. 

It's unlikely that we have void-users who work in the CG industry, therefore 2.90 is probably the better option if you favor supporting only one version. However maintaining LTS version probably won't be too difficult as they will only receive occasional bug-fixes.

**Comment by Johnnynator** [comment]
I merged this with an update to 2.83.6 for now. If someone is interested in 2.90 they can feel free to open a PR for it.

**Pull request closed without merging**
