### PR TITLE
Update Manual.md

### PR DESCRIPTION
**Pull request by whoizit**
annoying dot in commit message. different from the general style

### CODE REVIEW

**Comment by xtraeme** [comment]
xbump adds an ending dot by default, I don't agree with this PR.

**Comment by NeelChotai** [comment]
> xbump adds an ending dot by default, I don't agree with this PR.

I've added a pull request to accompany this change: https://github.com/leahneukirchen/xtools/pull/168.

**Comment by leahneukirchen** [comment]
xbump adds a dot because that's how commit messages looked since 2010. I see no good reason to change this now.

**Comment by xtraeme** [comment]
I agree with @leahneukirchen

**Comment by NeelChotai** [comment]
It's inconsistent that the commit message for updating a package has an explicit trailing full stop whereas new, removed and modified package commits don't. Either all of them should have a full stop or none should.

However, this rule isn't stringent so it's more of a nitpick.

**Comment by Chocimier** [comment]
The current way is as good.

**Pull request closed without merging**
