### PR TITLE
cabbage: fix ppc64 build

### PR DESCRIPTION
**Pull request by q66**

### CODE REVIEW

**Comment by Johnnynator** [comment]
`-march=native` should not be used on any system.

**Comment by q66** [comment]
The build system for this does something like

```
ifeq (,$(TARGET_ARCH)
    TARGET_ARCH := -march=native
endif
```

Does it mean we should come up with appropriate flag for each arch and revbump this? If so, what flags should be used? It's impractical to patch it all out as there's many isolated occurences of the same thing all over the codebase.

**Comment by Johnnynator** [comment]
@q66 See my edited part, just make sed call on all Makefiles

**Comment by q66** [comment]
There is a lot of these, with different names that cannot be matched with a pattern. In the meantime, I did this

**Pull request merged**
