### PR TITLE
New package libXnvctrl-devel and a change in MangoHud to depend on it, so that Nvidia cards will be detected on MangoHud

### PR DESCRIPTION
**Pull request by RoundDuckKira**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)
- I built this PR locally for these architectures (if supported. mark crossbuilds): n/a

The default MangoHud package in the repos is a little broken due to the lack of Nvidia detection, only working on open source GPUs. As a result, I looked further and realized it was due to a lack of libraries, and with some help I realized these libs were missing on the original .run installer that is the basis of the Nvidia package. So I looked at how Arch did things and made a package that takes the source for the nvidia-settings tool, compiles it, and then takes its library dev files for GPU detection and makes them into a package. I then updated MangoHud to depend on the package, that way it'll support Nvidia cards finally and people won't need to install a third party version from Flatpak or their repo.

### CODE REVIEW

**Comment by hervyqa** [comment]
_Using the `master` branch of your fork for contributing is also strongly discouraged. It can cause many issues with updating your pull request (also called a PR), and having multiple PRs open at once. To create a new branch:_

```
$ git checkout master -b libxnvctrl
```

https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements

**Comment by abenson** [comment]
Yeah, you might have to switch to a new branch and open a new PR. I remember things get kind of wonky if you try to force push to update this.

You'll need to rebase and get rid of that merge commit. Also, you'll need to move all of the changes to the `libXnvctrl(-devel?)` to one commit and the changes to `MangoHud` to another. Also, `libXnvctrl` package should be a "New package:..." commit and `-devel` split off form it and things be added to `common/shlibs` like other libraries.

**Comment by RoundDuckKira** [comment]
> Yeah, you might have to switch to a new branch and open a new PR. I remember things get kind of wonky if you try to force push to update this.
> 
> You'll need to rebase and get rid of that merge commit. Also, you'll need to move all of the changes to the `libXnvctrl(-devel?)` to one commit and the changes to `MangoHud` to another. Also, `libXnvctrl` package should be a "New package:..." commit and `-devel` split off form it and things be added to `common/shlibs` like other libraries.

Ah alright, the main reason I didn't just name it libXnvctrl is because it is just a development library package, I tried to separate the two with a devel and non devel version and xbps-src warned me that .so and .a files should be in a -devel package, so instead I'll just wholesale rename it to just libXnvctrl unless you say something otherwise and that I should split the .h files and the .so and .a files into their own separate packages.

Also how do I do this, how do I push changes into basically a branch within my repo rather than push to master? When I did git push, git pushed to master instead of to my MangoHud branch. :/

**Comment by RoundDuckKira** [comment]
I'm closing and reopening this pull req so I'm not using the master branch.

**Pull request closed without merging**
