### PR TITLE
New package: snes9x-gtk

### PR DESCRIPTION
**Pull request by Vlad-Romanov**
probably a bit of extra dependency, will try to fix up tomorrow

### CODE REVIEW

**Comment by Duncaen** [comment]
What is the point of this change other than breaking the distfiles url?

**Comment by Vlad-Romanov** [comment]
Sorry, fixed the distfiles URL, made this for the snes9x package because the original snes9x-gtk did not install snes9x, original was missing some dependencies too.

**Comment by Vlad-Romanov** [comment]
hmmm.... still some problems... either with snes9x, or snes9x-gtk. I will play more later with it.

```
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Sound buffer size: 4100 (1025 samples)
PortAudio sound driver initializing...
    --> (ALSA : default, latency 32ms)...OK
```

**Comment by Vlad-Romanov** [comment]
Also snes9x-gtk should depend on snes9x, snes9x-gtk only compile front-end from what I read.
http://maxolasersquad.blogspot.com/2013/09/compiling-snes9x-on-ubuntu.html

**Pull request closed without merging**
