### PR TITLE
Waybar: update to 0.5.0.

### PR DESCRIPTION
**Pull request by DirectorX**

### CODE REVIEW

**Comment by maxice8** [comment]
fails on cross.

**Comment by maxice8** [comment]
fails on cross.

**Comment by maxice8** [comment]
Feel free to tag me when updating packages i maintain.

**Comment by DirectorX** [comment]
I'll try to get help from upstream

**Comment by maxice8** [comment]
On Fri, Mar 22, 2019 at 05:14:21AM -0700, DirectorX wrote:
> I'll try to get help from upstream
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/10122#issuecomment-475598515

Thanks for taking time to work on this :+1:

**Comment by newbluemoon** [comment]
Adding the line `CXXFLAGS+=" -std=c++17"` to the template seems to resolve the problem.

Remains the question why it’s not picked up in the first place, because it’s specified in Waybar’s `meson.build`.

My guess is that when setting up the meson cross environment in `common/build-style/meson.sh` where the flags (`CXXFLAGS`, etc.) are (re-)exported at least the `default_options` set in Waybar’s `meson.build` are lost.

**Comment by Johnnynator** [comment]
I had the same issue with kiwix-lib that -std=c++smth did not get used from the `meson.build`. This only happens with the latest Meson version that we have on repo.

**Comment by DirectorX** [comment]
@maxice8

**Pull request merged**
