### PR TITLE
gcc: update to 9.2.0 and enable gcc-go on musl + go and objc/objc++ on cross targets

### PR DESCRIPTION
**Pull request by q66**
This updates `gcc` to 9.2.0 and while doing that, enables `gcc-go` on `musl`. It also enables `go`, `objc` and `objc++` support in crosstoolchains, allowing us to also enable them for cross targets. That mainly means our cross targets and native targets will all have `gcc` built with the same languages and subpackages, which should be a lot easier to deal with (and possibly enable crosscompiling for some GNUstep stuff etc)

(except on `mips*-musl`, as `libucontext` does not have MIPS support yet, so only enable `objc` and `objc++` on those)

Crosstoolchains updates:

- [x] aarch64
- [x] aarch64-musl
- [x] armv5tel
- [x] armv5tel-musl
- [x] armv6l
- [x] armv6l-musl
- [x] armv7l
- [x] armv7l-musl
- [x] i686
- [x] i686-musl
- [x] mips-musl
- [x] mipshf-musl
- [x] mipsel-musl
- [x] mipselhf-musl
- [x] ppc64le
- [x] ppc64le-musl
- [x] ppc64
- [x] ppc64-musl
- [x] ppc
- [x] ppc-musl
- [x] x86_64-musl

Testing:

- [x] ppc64le
- [x] ppc64le-musl
- [x] ppc64
- [x] ppc64-musl
- [x] ppc
- [x] ppc-musl
- [ ] x86_64
- [ ] x86_64-musl
- [x] aarch64 (build)
- [x] aarch64-musl (build)
- [ ] armv7l (build)

### CODE REVIEW

**Comment by q66** [comment]
I will need someone to test this on `x86_64`, `x86_64-musl` as well as build-test on 32-bit ARM (i can do it for `aarch64`).

**Comment by q66** [comment]
After updating the crosstoolchains for `aarch64` and `aarch64-musl` and then updating the `gcc` template appropriately, I now have `gcc` cross-compiling with the same set of languages as for native builds:

```
-rw-r--r-- 1 q66 q66 32318704 Sep  8 01:44 gcc-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66  2181940 Sep  8 01:44 gcc-ada-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66  7232260 Sep  8 01:42 gcc-fortran-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66  7883712 Sep  8 01:43 gcc-go-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66   703548 Sep  8 01:43 gcc-go-tools-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66  7115192 Sep  8 01:43 gcc-objc++-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66  6610084 Sep  8 01:42 gcc-objc-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66  2768416 Sep  8 01:44 libada-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66  1165140 Sep  8 01:44 libada-devel-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66     6748 Sep  8 01:42 libatomic-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66     7084 Sep  8 01:42 libatomic-devel-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66    34372 Sep  8 01:42 libgcc-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66    49120 Sep  8 01:44 libgcc-devel-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66   327256 Sep  8 01:42 libgfortran-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66   365976 Sep  8 01:42 libgfortran-devel-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66  4373240 Sep  8 01:43 libgo-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66  6361892 Sep  8 01:43 libgo-devel-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66    74104 Sep  8 01:42 libgomp-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66   132220 Sep  8 01:42 libgomp-devel-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66    23952 Sep  8 01:44 libitm-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66   393872 Sep  8 01:44 libitm-devel-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66    34092 Sep  8 01:43 libobjc-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66    37576 Sep  8 01:43 libobjc-devel-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66     5300 Sep  8 01:42 libssp-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66     6308 Sep  8 01:42 libssp-devel-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66   502824 Sep  8 01:44 libstdc++-9.2.0_1.aarch64-musl.xbps
-rw-r--r-- 1 q66 q66  1663724 Sep  8 01:44 libstdc++-devel-9.2.0_1.aarch64-musl.xbps
```

**Comment by q66** [comment]
Alright. As far as I'm concerned I've done everything; what's left is testing on systems I can't test on and merging.

To merge, we'll have to do this in steps:

1) First merge the initial commit updating `gcc` only.
2) Wait until native builders have all rebuilt their `gcc` (first commit marks `gcc` nocross to prevent crossbuilders from attempting anything)
3) Once that's done, merge all of the crosstoolchain rebuilds.
4) Once these are done building, merge the `cross-vpkg-dummy` update as well as the commit that reenables cross for gcc and enables go/objc for cross.
5) that's it

**Comment by jnbr** [comment]
I started builds for x86_64 and armv7hf. Will test and report later today.

**Comment by jnbr** [comment]
Tested on x86_64[-musl], aarch64-musl and armv7hf.
I found no new issues, uncaught exceptions on aarch64-musl still segfault but this is broken for a while and shouldn't block things.

**Comment by q66** [comment]
Cool. I'm building big software with the toolchain already (webkit etc) and everything seems to be fine on my side too.

**Pull request closed without merging**
