### PR TITLE
glib: update to 2.80.0.

### PR DESCRIPTION
**Pull request by oreo639**
#### Testing the changes
- I tested the changes in this PR: **briefly**

glib 2.80.0 introduces libgirepository-2.0 and GIRepository-3.0, which unfortunately creates a build cycle between glib and gobject-introspection, although that is supposedly transitory.

Currently only the C components have been moved over to glib. (Notably, g-ir-scanner is missing, which is needed to compile glib's introspection data. An explanation for why along with the proposed remedies can be found in "The hard part" section of the glib issue below.)
The GLib gir files have also been moved to being generated by glib build instead of gobject-introspection build. (hence why gobject-introspection is necessary)

https://discourse.gnome.org/t/dealing-with-glib-and-gobject-introspection-circular-dependency/18701
https://gitlab.gnome.org/GNOME/glib/-/issues/2616
https://docs.gtk.org/girepository/migrating-gi.html

The bootstrap process, while not intentionally, mirrors the one used by gnome-buld-meta: https://gitlab.gnome.org/GNOME/gnome-build-meta/-/blob/master/elements/sdk/glib.bst
(While gobject-introspection technically doesn't need to be rebuilt I did so here due to issues with dependencies, e.g. glib-bootstrap vs glib)

### CODE REVIEW

**Comment by chrysos349** [comment]
i think python3-packaging is supposed to be in glib-devel depends.
otherwise, there will be the error, like this
```
[87/144] Generating gdbus source libsecret/secret-dbus-generated.c
FAILED: libsecret/secret-dbus-generated.c 
/usr/bin/gdbus-codegen --c-generate-autocleanup all --interface-prefix org.freedesktop.Secret. --c-namespace _SecretGen --body --output libsecret/secret-dbus-generated.c ../libsecret/org.freedesktop.Secrets.xml
Traceback (most recent call last):
  File "/usr/bin/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "/usr/share/glib-2.0/codegen/codegen_main.py", line 30, in <module>
    from . import dbustypes
  File "/usr/share/glib-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "/usr/share/glib-2.0/codegen/utils.py", line 22, in <module>
    import packaging.version
ModuleNotFoundError: No module named 'packaging'
```

**Comment by oreo639** [comment]
> i think python3-packaging is supposed to be in glib-devel depends.

Yeah, thanks (python3-packaging was added as a dependency to replace distutils).

**Comment by oreo639** [comment]
I ported over the gobject-introspection qemuwrapper and patches and tested it with:
```
diff --git a/common/build-helper/meson.sh b/common/build-helper/meson.sh
index 6232f9260c2..e4e7171f031 100644
--- a/common/build-helper/meson.sh
+++ b/common/build-helper/meson.sh
@@ -67,8 +67,8 @@ cat > "${XBPS_WRAPPERDIR}/meson/xbps_meson.cross" <<-EOF
        pkgconfig = '${PKG_CONFIG}'
        rust = ['rustc', '--target', '${RUST_TARGET}' ,'--sysroot', '${XBPS_CROS
S_BASE}/usr']
        g-ir-scanner = '${XBPS_CROSS_BASE}/usr/bin/g-ir-scanner'
-       g-ir-compiler = '${XBPS_CROSS_BASE}/usr/bin/g-ir-compiler'
-       g-ir-generate = '${XBPS_CROSS_BASE}/usr/bin/g-ir-generate'
+       g-ir-compiler = '${XBPS_CROSS_BASE}/usr/bin/gi-compile-repository'
+       g-ir-generate = '${XBPS_CROSS_BASE}/usr/bin/gi-decompile-typelib'
        llvm-config = '/usr/bin/llvm-config'
        cups-config = '${XBPS_CROSS_BASE}/usr/bin/cups-config'
        
```

It seems to work, although looking through it, there are some things that can potentially be improved.

Currently we use fork of prelink-cross to get prelink-rtld to get the recursive dependencies from DT_NEEDED in an lld-like output. I'm not sure this is needed and it can probably be simplified by just using elfutils (which is already a dependency of glib) like what Debian does: https://salsa.debian.org/gnome-team/gobject-introspection/-/blob/debian/latest/debian/elf-get-needed.c (That needs testing though)

That method was also brought up upstream by the Debian maintainer: https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/482

Another thing I noticed is that Debian wraps all of the g-ir-*/gi-* tools with qemu:
https://salsa.debian.org/gnome-team/glib/-/blob/debian/latest/debian/rules?ref_type=heads#L72-91

Not sure how necessary that is, but in meson we pass the raw unwrapped `g-ir-generate` (equivalent of `gi-decompile-typelib` in glib):
https://github.com/void-linux/void-packages/blob/master/common/build-helper/meson.sh#L71
There probably isn't much using it.

I'll worry about this more later.

**Comment by oreo639** [comment]
The glib test failure is due to: https://github.com/void-linux/void-packages/blob/master/srcpkgs/gobject-introspection/patches/0011-giscanner-ld-library-path.patch

Alternatively it can be adjusted to use an environment variable, idk.

**Comment by oreo639** [comment]
The glib test failure is due to: https://github.com/void-linux/void-packages/blob/master/srcpkgs/gobject-introspection/patches/0002-Relocate-the-repository-directory-for-native-builds.patch

Alternatively it can be adjusted to use an environment variable, idk.
(I linked the wrong patch last time)

**Comment by oreo639** [comment]
Cross stuff should be done for glib, the gobject-introspection lldwrapper is a separate PR since it isn't a part of glib: https://github.com/void-linux/void-packages/pull/49468

**Comment by oreo639** [comment]
Should be basically done.
I removed `${makedepends}` from the depends of libglib-devel, not sure why it is there in the first place but glib shouldn't include other headers. This may break some stuff that expects those devel packages to get implicitly pulled in though. I'm going to test building some packages.

**Comment by oreo639** [comment]
Nvm, `${makedepends}` is needed for static linking.

**Pull request merged**
