### PR TITLE
cage: add Xwayland build option.

### PR DESCRIPTION
**Pull request by travankor**

### CODE REVIEW

**Comment by ericonr** [comment]
Is it working with Xwayland? Last I tested it, it didn't work for me.

**Comment by ericonr** [comment]
Also I don't think this should be a build option. If someone knows enough to build it locally with this build option, they can also install xwayland manually.

**Comment by travankor** [comment]
>Is it working with Xwayland? Last I tested it, it didn't work for me.

When was the last time you tested?

**Comment by ericonr** [comment]
Well, just now :p 

Xwayland seems to work with the wayland backend, even if it opens two windows (?), but doesn't work for the DRM backend.

**Comment by travankor** [comment]
>Xwayland seems to work with the wayland backend, even if it opens two windows (?), but doesn't work for the DRM backend.
I hadn't tested the wayland backend, in this case.

That's because your version of cage doesn't have Xwayland built in (ie: what this PR does). I wonder if there's any downside to having Xwayland by default in cage instead of a build option?

**Comment by ericonr** [comment]
Isn't this PR only changing the `depends`? I already have `xorg-server-xwayland` installed, I can't see what else it changes.

**Comment by ericonr** [comment]
@travankor would you like me to include this in #23793 ?

**Comment by travankor** [comment]
Sure, go ahead.

**Comment by ericonr** [comment]
It did work, thanks! I made it default, ok?

**Pull request closed without merging**
