### PR TITLE
eolie: update to 0.9.101.

### PR DESCRIPTION
**Pull request by sgn**
#### Testing the changes
- I tested the changes in this PR: **YES**|**briefly**|**NO**

### CODE REVIEW

**Comment by oreo639** [comment]
Patch should probably be submitted upstream, also there is one more use of libsoup2:
https://gitlab.gnome.org/World/eolie/-/blob/master/eolie/css_stylesheet.py#L128-130

**Comment by sgn** [comment]
> Patch should probably be submitted upstream,

Look like inactive

> also there is one more use of libsoup2: https://gitlab.gnome.org/World/eolie/-/blob/master/eolie/css_stylesheet.py#L128-130

Which one are you talking about?

**Comment by oreo639** [comment]
> Look like inactive

Indeed. Still good though.

> Which one are you talking about?

Yeah, I'm dumb.

**Comment by sgn** [comment]
https://gitlab.gnome.org/World/eolie/-/merge_requests/285

**Pull request merged**
