### PR TITLE
mps-youtube: rename to yewtube, update to 2.10.4.

### PR DESCRIPTION
**Pull request by icp1994**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture: **x86_64**

Seems like mps-youtube has been rebranded in upstream a while ago. There is a couple of hiccups while trying to test it though. The first one is that it complained yt-dlp requires brotli which I fixed in https://github.com/void-linux/void-packages/pull/42661. Now it says httpx requires rfc3986[idna2008]<2,>=1.3 which is also [true](https://github.com/encode/httpx/blob/0.23.3/pyproject.toml#L33) but the version in our repo is already 2.0 so I don't know how to fix that.

### CODE REVIEW

**Comment by sgn** [comment]
It seems like httpx can use rfc3986 2.0, please patch it and run unittest.

**Comment by icp1994** [comment]
https://github.com/void-linux/void-packages/pull/42681 for httpx but unfortunately yewtube still not working with unrelated issue(s).

**Comment by sgn** [comment]
?

**Comment by classabbyamp** [comment]
does it work now?

**Comment by icp1994** [comment]
Yes, have been using it for months now. Also pushed the latest patches.

**Pull request merged**
