### PR TITLE
New package: newm-0.2

### PR DESCRIPTION
**Pull request by iFoundSilentHouse**
Dependency: python3-dasbus:
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

Was done to fulfill https://github.com/void-linux/void-packages/issues/49517 request

### CODE REVIEW

**Comment by ahesford** [comment]
If you're attempting to package `newm-atha`, include this package in that PR. Don't submit packages for dependencies piecemeal.

**Comment by iFoundSilentHouse** [comment]
> If you're attempting to package `newm-atha`, include this package in that PR. Don't submit packages for dependencies piecemeal.

Ok I will. Sorry

**Comment by iFoundSilentHouse** [comment]
> If you're attempting to package `newm-atha`, include this package in that PR. Don't submit packages for dependencies piecemeal.

I wanted to ask you an advice: what if I have multiple distfiles and i need both of them to go through packaging script - both of them to build separately. Could it be managed within one template? 

I'm asking as hewm has separate release for it's engine. I don't want to separate as void packages them because: 1) it'd be too much attention for such thing 2) LICENSE file is able within only one of them

**Comment by blacklightpy** [comment]
> I wanted to ask you an advice: what if I have multiple distfiles and i need both of them to go through packaging script - both of them to build separately. Could it be managed within one template?
> 
> I'm asking as hewm has separate release for it's engine. I don't want to separate as void packages them because: 1) it'd be too much attention for such thing 2) LICENSE file is able within only one of them

I found this: https://github.com/void-linux/void-packages/pull/41185#discussion_r1055638769

**Comment by iFoundSilentHouse** [comment]
> > I wanted to ask you an advice: what if I have multiple distfiles and i need both of them to go through packaging script - both of them to build separately. Could it be managed within one template?
> > I'm asking as hewm has separate release for it's engine. I don't want to separate as void packages them because: 1) it'd be too much attention for such thing 2) LICENSE file is able within only one of them
> 
> I found this: [#41185 (comment)](https://github.com/void-linux/void-packages/pull/41185#discussion_r1055638769)

Thanks. 
We'll use 2 packages then...

**Comment by ahesford** [comment]
I don't think packaging an old tag of a now-abandoned repository is a good idea, and the fork recommended by the original maintainer hasn't seen activity in seven months and hasn't tagged any new releases.

Unless something changes upstream, I'd advise against sinking any time into this PR.

**Pull request closed without merging**
