### PR TITLE
New package: python3-crossplane-0.5.8

### PR DESCRIPTION
**Pull request by c0m4r**
Reliable and fast NGINX configuration file parser and builder

#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-musl
  - x86_64-glibc

### CODE REVIEW

**Comment by c0m4r** [comment]
Ok, I give up. Linter locally says it's happy, here it's failing, the package builds, runs flawlessly. I would appreciate some help in determining what I should correct further.

**Comment by classabbyamp** [comment]
see https://github.com/void-linux/void-packages/actions/runs/7672865186/job/20914297421?pr=48385#step:7:8

the commit message should be changed to match what it says in [CONTRIBUTING.md](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#committing-your-changes)

**Comment by c0m4r** [comment]
Aaaah, ok, I was fixated on the name of the pull request. Still, xlint doesn't let me know about that :/

**Comment by c0m4r** [comment]
image

**Comment by melroy89** [comment]
@c0m4r  Why is it closed?

**Pull request closed without merging**
