### PR TITLE
android-studio: update to 4.1.3.

### PR DESCRIPTION
**Pull request by unspecd**
Also clean up template.

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, x86_64
- [ ] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [ ] i686

### CODE REVIEW

**Comment by unspecd** [comment]
There is a possibility to skip runtime dependency on `openjdk` (due to NEEDED libawt.so, libawt_xawt.so, libjava.so, libjvm.so, libjli.so, which are bundled with the package). Here are the changes I'd like to propose.

File: common/hooks/pre-pkg/04-generate-runtime-deps.sh
```diff
@@ -93,11 +93,14 @@ hook() {
     # above, the mapping is done thru the common/shlibs file.
     #
     for f in ${verify_deps}; do
-        unset _f j rdep _rdep rdepcnt soname _pkgname _rdepver found
+        unset _f j rdep _rdep rdepcnt soname _pkgname _rdepver found skipso
         _f=$(echo "$f"|sed -E 's|\+|\\+|g')
         rdep="$(grep -E "^${_f}[[:blank:]]+.*$" $mapshlibs|cut -d ' ' -f2)"
         rdepcnt="$(grep -E "^${_f}[[:blank:]]+.*$" $mapshlibs|cut -d ' ' -f2|wc -l)"
-        if [ -z "$rdep" ]; then
+        if [[ "${skipsorequires}" == *"$f"* ]]; then
+                skipso=1
+        fi
+        if [ -z "$rdep" -o "$skipso" ]; then
             # Ignore libs by current pkg
             soname=$(find ${PKGDESTDIR} -name "$f")
             if [ -z "$soname" ]; then
```
File: srcpkgs/android-studio/template
```diff
@@ -24,6 +24,8 @@ nopie=yes
 nostrip=yes
 noshlibprovides=yes
 
+# jdk is bundled with the package.
+skipsorequires="libawt.so libawt_xawt.so libjava.so libjvm.so libjli.so"
 # These files are not run or loaded on the host thus skip scanning their runtime deps
 skiprdeps="/opt/android-studio/plugins/android/resources/perfetto/x86_64/traced_probes
```

**Comment by ericonr** [comment]
Please don't skip CI, the package should be buildable.

That sounds like a new feature to add to xbps-src, so tagging @void-linux/pkg-committers. There are places where it's been necessary before, I think, but it's been worked around some way or another. It's weird that `             soname=$(find ${PKGDESTDIR} -name "$f")` doesn't find them in this case...

**Comment by Chocimier** [comment]
Same can be done by adding solibs to `common/shlibs` at end of file, see `elif [ "$rdepcnt" -gt 1 ]` branch.

`soname=$(find ${PKGDESTDIR} -name "$f")` is run only when solib isn't listed in `common/shlibs`.

**Comment by ericonr** [comment]
Merging as is, improvements can come in a later PR.

**Comment by unspecd** [comment]
Ok, thanks.

**Pull request merged**
