### PR TITLE
vscode: update to 1.38.1

### PR DESCRIPTION
**Pull request by ScOut3R**

### CODE REVIEW

**Comment by ScOut3R** [comment]
Is there a way to trigger the Travis job again? Looks like the build failed because a child process was killed in flight.

**Comment by ScOut3R** [comment]
I tend to believe that the Travic instance has issues coping with this build. It runs fine perfectly locally and the SIGKILL signal is very suspicious.

**Comment by Hoshpak** [comment]
#13716

**Comment by ScOut3R** [comment]
Can be squashed during merge. Just saying. :)

**Pull request closed without merging**
