### PR TITLE
qemu(-user-static): update to 8.0.0.

### PR DESCRIPTION
**Pull request by unspecd**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-musl)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - ppc64le-musl

https://wiki.qemu.org/ChangeLog/7.2

### CODE REVIEW

**Comment by unspecd** [comment]
Can anyone help in fixing glibc builds?

**Comment by unspecd** [comment]
I think this is relevant: https://gitlab.gnome.org/GNOME/glib/-/issues/2019

**Comment by unspecd** [comment]
Similar issue to #41216.

**Comment by oreo639** [comment]
The glib thing is a warning not an error, you can ignore it.

For the i686 issue:
https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1908331
You can use `--disable-pie` in qemu-user-static (this is used by Debian and Fedora).
https://salsa.debian.org/qemu-team/qemu/-/blob/master/debian/rules#L342-359

The aarch64 and armv7l issues are probably caused by this:
https://github.com/void-linux/void-packages/commit/b2d670be60b883192d12f79077fa79dff5395554
Which wasn't an issue before since the glibc cross compilers weren't rebuilt.

**Comment by unspecd** [comment]
Adding `--disable-pie` fixes i686 build, thanks!

**Comment by oreo639** [comment]
The cross compilers have been updated so it should build fine once you rebase.

**Comment by unspecd** [comment]
Done.

**Comment by unspecd** [comment]
(Rebased again)

**Comment by AnErrupTion** [comment]
Is there any progress on this? @unspecd

**Pull request closed without merging**
