### PR TITLE
chromium: update to 87.0.4280.66.

### PR DESCRIPTION
**Pull request by pbui**
[ci skip]

- Built for x86_64, x86_64-musl, i686.
- Tested on x86_64.

- Also update chromium-widevine.

@q66 Had to modify two ppc64 patches... mainly updating the location of a few ifdefs macros.  Please let me know if I made a mistake.  Thanks.

### CODE REVIEW

**Comment by q66** [comment]
building

**Comment by Logarithmus** [comment]
Please, consider building it with my PR: https://github.com/void-linux/void-packages/pull/26144
Arch builds Chromium with PipeWire flag, and it works: https://github.com/archlinux/svntogit-packages/blob/packages/chromium/trunk/PKGBUILD
Fedora also uses it: https://src.fedoraproject.org/rpms/chromium/blob/master/f/chromium.spec#_1056
Also I've manually tested screen sharing on  `x86_64-musl`, `x86_64` & `i686` with Chromium 86.
Having ability to share the screen on Wayland is a life-saver for me, especially in the light of remote working/studying.

**Comment by pbui** [comment]
@Logarithmus I would be OK with adding pipewire support.  I don't really have any control over what gets accepted though, so you will need to wait on @q66, @ericonr, and @Johnnynator to determine the best course of action in regards to enabling that support.

**Comment by travankor** [comment]
Can you add a build option for [Ozone](https://chromium.googlesource.com/chromium/src/+/master/docs/ozone_overview.md#wayland), too? This is for supporting the native wayland backend of chromium.

**Comment by Logarithmus** [comment]
> Can you add a build option for [Ozone](https://chromium.googlesource.com/chromium/src/+/master/docs/ozone_overview.md#wayland), too? This is for supporting the native wayland backend of chromium.

AFAIK, it should just werk on Chromium 87: https://aur.archlinux.org/packages/chromium-ozone/#comment-776085

**Comment by q66** [comment]
let's merge this first and wait with the other stuff for the next point release

meanwhile, i've tested this one and all is OK

**Comment by travankor** [comment]
Is the flag automatically enabled because I can't test with Arch? Their PKGBUILD does not contain any references to ozone, unlike in [NixOS](https://github.com/NixOS/nixpkgs/blame/a371a5df8729f79cd6b4ee4313f8ec1953f9ae95/pkgs/applications/networking/browsers/chromium/default.nix#L19).

It could be that it is automatically enabled, but Nix explicility sets [this](https://github.com/NixOS/nixpkgs/blob/a371a5df8729f79cd6b4ee4313f8ec1953f9ae95/pkgs/applications/networking/browsers/chromium/common.nix#L272) up.

**Pull request merged**
