### PR TITLE
WIP: New package: paperde-0.2.1

### PR DESCRIPTION
**Pull request by zen0bit**
PaperDE will require this:

 - libcprime
 - libcsys
 - wayqt
 - dfl-applications
 - dfl-settings
 - dfl-sni
 - dfl-ipc
 - dfl-login1

- patch for libexec

#### Testing the changes
- I tested the changes in this PR: **briefly**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
Not yet builded

Help welcome!

### CODE REVIEW

**Comment by mobinmob** [comment]
shlibs should not be a seperate commit - they should probably be in the same commit with the package they reside in.

**Comment by mobinmob** [comment]
```
=> ERROR: paperde-0.2.1_1: /usr/lib/libexec directory is not allowed!
=> ERROR: paperde-0.2.1_1: cannot continue with installation!
```
The build system does not seem to respect the libexecdir value and installs some executables under `/usr/lib/libexecdir` instead of `/usr/libexecdir`. It is not difficult to[ fix it in the messon.build file(s)](https://termbin.com/rbtw2) but the DE does not start after that.

**Comment by mobinmob** [comment]
Templates that package libraries should have -devel subpackages. These subpackages should be in the **makedepends** array, not in the **hostmakedepends** one. Check other templates for examples ;)
Also, wayfire seems to be a runtime dependency of paperde, so it should probable be in depends.

**Comment by zen0bit** [comment]
bump

**Comment by zen0bit** [comment]
Leave my paperde draft just be for later github!

**Comment by zen0bit** [comment]
bump

**Pull request closed without merging**
