### PR TITLE
[WIP] New package: deno-1.32.3

### PR DESCRIPTION
**Pull request by astralchan**
[ci skip]

Closes [21937](https://github.com/void-linux/void-packages/issues/21937)

Supersedes:
- [22043](https://github.com/void-linux/void-packages/pull/22043)
- [25436](https://github.com/void-linux/void-packages/pull/25436)

#### Testing the changes
- I tested the changes in this PR: **NO**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):

Current error log:

```
   Compiling futures v0.3.27
error: failed to run custom build command for `v8 v0.68.0`

Caused by:
  process didn't exit successfully: `/builddir/deno-1.32.3/target/release/build/v8-b2ba9187d5e6450d/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=.gn
  cargo:rerun-if-changed=BUILD.gn
  cargo:rerun-if-changed=src/binding.cc
  cargo:rerun-if-env-changed=CCACHE
  cargo:rerun-if-env-changed=CLANG_BASE_PATH
  cargo:rerun-if-env-changed=DENO_TRYBUILD
  cargo:rerun-if-env-changed=DOCS_RS
  cargo:rerun-if-env-changed=GN
  cargo:rerun-if-env-changed=GN_ARGS
  cargo:rerun-if-env-changed=HOST
  cargo:rerun-if-env-changed=NINJA
  cargo:rerun-if-env-changed=OUT_DIR
  cargo:rerun-if-env-changed=RUSTY_V8_ARCHIVE
  cargo:rerun-if-env-changed=RUSTY_V8_MIRROR
  cargo:rerun-if-env-changed=SCCACHE
  cargo:rerun-if-env-changed=V8_FORCE_DEBUG
  cargo:rerun-if-env-changed=V8_FROM_SOURCE
  cargo:rerun-if-env-changed=PYTHON
  cargo:rustc-link-lib=static=rusty_v8
  download lockfile: "/builddir/deno-1.32.3/target/release/build/lib_download.fslock"
  static lib URL: https://github.com/denoland/rusty_v8/releases/download/v0.68.0/librusty_v8_release_x86_64-unknown-linux-gnu.a
  cargo:rustc-link-search=/builddir/deno-1.32.3/target/release/gn_out/obj
  Downloading https://github.com/denoland/rusty_v8/releases/download/v0.68.0/librusty_v8_release_x86_64-unknown-linux-gnu.a
  Python downloader failed, trying with curl.

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /host/cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.68.0/build.rs:409:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
=> ERROR: deno-1.32.3_1: do_build: '${make_cmd} build --release --target ${RUST_TARGET} ${configure_args}' exited with 101
=> ERROR:   in do_build() at common/build-style/cargo.sh:8
```

### CODE REVIEW

**Comment by icp1994** [comment]
For a starter, the `distfile` should be `https://github.com/denoland/deno/releases/download/v${version}/deno_src.tar.gz` which should have the submodule sources

**Comment by icp1994** [comment]
Looking at [official docs](https://deno.land/manual@v1.32.3/references/contributing/building_from_source#building-deno) seems like you need `python3` in host, `libglib-devel` in makedepends with `make_cmd="env V8_FROM_SOURCE=1 cargo auditable"`

**Comment by astralchan** [comment]
Updated `hostmakedepends`, `makedepends`, and `make_cmd`.

Current error log:

```
  --- stderr
  thread 'main' panicked at 'Path doesn't exist: "/builddir/deno-1.32.3/target/x86_64-unknown-linux-gnu/release/gn_out/../../../../../../host/cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.68.0/v8/tools/builtins-pgo/x64.profile"', /host/cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.68.0/build.rs:726:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
=> ERROR: deno-1.32.3_1: do_build: '${make_cmd} build --release --target ${RUST_TARGET} ${configure_args}' exited with 101
=> ERROR:   in do_build() at common/build-style/cargo.sh:8
```

**Comment by astralchan** [comment]
The v8 system for deno (https://github.com/denoland/rusty_v8) apparently also needs `curl` and Google's `gn`. It would probably be easiest to make a new package within this PR, as well with a separate commit. However, Google never tags releases, so I would probably do what the `mozc` package does and do it by commit hash.

**Comment by astralchan** [comment]
I added a `gn` package for making the ninja build rules. `deno` should get that package.

Current build error log:
```
  --- stderr
  thread 'main' panicked at 'Path doesn't exist: "/builddir/deno-1.32.3/target/release/gn_out/../../../../../host/cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.68.0/v8/tools/builtins-pgo/x64.profile"', /host/cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.68.0/build.rs:726:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
=> ERROR: deno-1.32.3_1: do_build: '${make_cmd} build --release --target ${RUST_TARGET} ${configure_args}' exited with 101
=> ERROR:   in do_build() at common/build-style/cargo.sh:8
```

**Pull request closed without merging**
