### PR TITLE
coreutils: update to 9.0.

### PR DESCRIPTION
**Pull request by ericonr**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by leahneukirchen** [comment]
While we are at it, can you add a symlink from `test.1` to `[.1`?

**Comment by ericonr** [comment]
Needs to import https://git.savannah.gnu.org/cgit/coreutils.git/commit/?id=e8b56ebd536e82b15542a00c888109471936bfda

**Comment by ericonr** [comment]
https://github.com/openzfs/zfs/issues/11900 ZFS bug triggered by `cp(1)` using `lseek` more aggressively. I'd consider waiting for fixes to be merged.

**Comment by Gottox** [comment]
the zfs bug seems to be merged, reconsider this PR?

**Comment by leahneukirchen** [comment]
Potential upstream bugs that we should backport:
```
  chmod -R no longer exits with error status when encountering symlinks.
  All files would be processed correctly, but the exit status was incorrect.
  [bug introduced in coreutils-9.0]
```

**Comment by mhmdanas** [comment]
coreutils 9.1 is out now.

**Comment by leahneukirchen** [comment]
9.1 has two bugs upsteam that need to be backported first (or wait for 9.2...)

**Pull request closed without merging**
