### PR TITLE
New package: sheldon-0.7.3

### PR DESCRIPTION
**Pull request by tranzystorek-io**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

### CODE REVIEW

**Comment by jcgruenhage** [comment]
I've looked into using it myself, and after looking at the code, I'm really not sure anymore. The config loading and CLI arg evaluation is very complex, more than it needs to be IMO, and it doesn't properly follow the XDG base dir spec. For that latter part, I've submitted a WIP patch upstream (see https://github.com/rossmacarthur/sheldon/pull/149), but properly fixing that is going to take a bit more time which I'm not sure I want to invest.

**Comment by tranzystorek-io** [comment]
@jcgruenhage yeah, I'm aware of the codebase, but for what it's worth, my minimal zsh plugin + completion path config works pretty well on sheldon, the least cumbersome of all the plugin managers I've used, like omz or even zplug.

**Comment by jcgruenhage** [comment]
Yeah, fair enough.. I've nerdsniped myself enough into fixing at least the XDG spec parts that I'd still want to use it if it lands in void, so yeah, would be happy to see this merged. Maybe with the XDG basedir spec patch merged into this PR as well, once it landed upstream, depending on how long they take to release 0.7.0?

**Comment by jcgruenhage** [comment]
Or well, fixing is maybe not the right word, it's not like the code upstream is broken, it's just more complex than it needs to be IMO. Being opinionated and not giving the user the option to configure the location of every single file individually through multiple means, would be a bit better here.

**Comment by tranzystorek-io** [comment]
@jcgruenhage seems your changes just landed in upstream 🎉

**Comment by jcgruenhage** [comment]
yeah well not really, my PR is still open. Something similar has been merged though.

**Comment by jcgruenhage** [comment]
I've been using this for a while now and would like to get it merged at some point. Any opinions on this? The feedback on here has been fairly scarce.

**Pull request merged**
