### PR TITLE
New package: python3-misaka-2.1.1

### PR DESCRIPTION
**Pull request by anjandev**
Needed for sr.ht. #15784

### CODE REVIEW

**Comment by Chocimier** [comment]
Missing runtime dependency on python3-cffi and check dependency on tidy5. Please remove `_pkgname` as it is used once.

**Comment by anjandev** [comment]
fixed

**Comment by Chocimier** [comment]
Yes, but half of cross builds on travis fail, so something is wrong here or there, can look later.

**Comment by Chocimier** [comment]
Needed python3-cffi build-time too.

**Pull request merged**
