### PR TITLE
pipewire: update to 0.3.45

### PR DESCRIPTION
**Pull request by dkwo**
Builds fine on x86_64-musl.
Added a couple of makedepends, in particular dbus.
@st3r4g

### CODE REVIEW

**Comment by st3r4g** [comment]
could you import the fixes for this https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2069

**Comment by dkwo** [comment]
Done.
I believe I included the relevant commits.

**Comment by st3r4g** [comment]
`fix-neon-detection.patch` is still needed

**Comment by dkwo** [comment]
Right.

**Review by st3r4g — APPROVED** [review]

**Comment by st3r4g** [comment]
imo no need to say "add upstream patches" in the commit log, they will be gone next release anyway

**Comment by st3r4g** [comment]
0.3.45 out

**Comment by dkwo** [comment]
Updated and rebased, thanks.

**Pull request merged**
