### PR TITLE
apr-util: update to 1.6.3

### PR DESCRIPTION
**Pull request by klarasm**
Failed to download distfiles when revbumping in #41948

- remove upstreamed patch
- switch to vsed
- cross-compilation fix

#### Testing the changes
- I tested the changes in this PR: I don't use this package directly

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for my native architecture, (x86_64-musl)

### CODE REVIEW

**Comment by klarasm** [comment]
I feel like I'm in over my head on this one.
```
/usr/bin/ld: dbm/.libs/apr_dbm_gdbm.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: dbm/.libs/apr_dbm_gdbm.o: error adding symbols: file in wrong format
```
Is it really correct that the host linker is used rather than the one from the crosscompiler?

**Comment by klarasm** [comment]
configure script complains of:
```
configure: WARNING: unrecognized options: --with-sysroot, --with-libtool-sysroot
```
which may be related

**Comment by paper42** [comment]
> I think I've found the issue. If I revert [dd789b9](https://github.com/void-linux/void-packages/commit/dd789b95eb6490221ae8a53d741d9b873462938c) from #40606 it crosscompiles fine.

cc @oreo639

**Comment by klarasm** [comment]
If I look into the libtool script without the commit i get:
```
# The linker used to build libraries.
LD=${LD:=ld}
```
which allows the linker to be overridden by the environment. With the commit i get:
```
# The linker used to build libraries.
LD="ld"
```
which sets the linker unconditionally.

So the problematic part of the commit is probably:
```
-               # e.g. AR="armv7l-linux-gnueabihf-ar" becomes AR="${AR:=ar}"
-               vsed -i -e "s,\([A-Z]\+\)=\"${XBPS_CROSS_TRIPLET}\-\(.*\)\",\1=\$\{\1:=\2\},g" \
+               # e.g. AR="armv7l-linux-gnueabihf-ar" becomes AR="ar"
+               vsed -i -e "s,\([A-Z]\+\)=\"${XBPS_CROSS_TRIPLET}\-\(.*\)\",\1=\"\2\",g" \
```

I'll revert that part only and see if it still builds ok.

**Comment by oreo639** [comment]
The arm libtool should be consistent with the x86_64 libtool, I'm not sure why this change should be made for one but not the other (or at all).

If you need `LD=${LD:=ld}`, maybe you can sed libtool to XBPS_WRAPPERDIR and use that?

**Comment by klarasm** [comment]
> If you need `LD=${LD:=ld}`, maybe you can sed libtool to XBPS_WRAPPERDIR and use that?
That worked, thanks!

This should be mostly ready now. Though I don't use this package directly so additional testing would be appreciated.

**Comment by klarasm** [comment]
Use archive.apache.org instead of  downloads.apache.org as the former does not delete outdated versions.

**Comment by dkwo** [comment]
I'm seeing the same `configure: WARNING: unrecognized options: --with-sysroot, --with-libtool-sysroot` when cross compiling coreutils in https://github.com/void-linux/void-packages/pull/45305 Can you remind me how to deal with it?

**Comment by oreo639** [comment]
That just means that those options aren't being used.
For example, `--with-sysroot` is used by gmp because the configure script was generated on a distro where libtool uses the `--with-sysroot` variable, whereas if it was generated on Void it would use the `--with-libtool-sysroot` variable since we patched libtool.

This package doesn't use autoconf btw.

**Comment by oreo639** [comment]
(It does use autoconf, sorry, it is just named `*.in` instead of `*.ac`)

**Comment by oreo639** [comment]
(Correction: this package does use autoconf, I just got mixed up, since the file was named `configure.in` instead of `configure.ac`)

**Comment by klarasm** [comment]
You could try `autoreconf -fi` to replace it with Void's version but I don't think it's what causes the failures (the crossbuilds seem to complete, which would be the most likely to fail as a result of the flags not being used correctly. I'm no expert at autoconf/autotools, though).

For the test failure, it's probably more likely the CI restricts the inotify feature if it doesn't happen to you locally.

**Comment by oreo639** [comment]
It is not a failure, it is a warning.

**Comment by klarasm** [comment]
> It is not a failure, it is a warning (one that can be safely ignored in this case).

I also referred to the test failure in my first sentence, sorry if I was unclear.

**Comment by oreo639** [comment]
Ah, sorry.

**Comment by dkwo** [comment]
Thank you, then I'll ignore the warning.
Right, the test failure is only on CI (locally it passes), likely unrelated.

**Comment by oreo639** [comment]
Also, @klarasm here is a solution without the libtool hack:
https://github.com/oreo639/void-packages/commit/d6ed53215f78001a824885598f05b37ba023c1a5

**Comment by klarasm** [comment]
I may have overlooked some vseds when applying...

**Comment by oreo639** [comment]
The vsed should be `if [ "$CROSS_BUILD" ]; then`, sorry.

**Comment by klarasm** [comment]
> The vsed should be `if [ "$CROSS_BUILD" ]; then`, sorry.

No worries. The 32bit arm crossbuilds seems to fail unrelated to this though.

**Comment by oreo639** [comment]
You can use `-e "/^CFLAGS=/s:=.*:=${CFLAGS}:"`, I updated my branch here:
https://github.com/void-linux/void-packages/compare/master...oreo639:void-packages:apr-util

**Comment by klarasm** [comment]
> You can fix that by using `-e "/^CFLAGS=/s:=.*:=${CFLAGS}:"` in the vsed.

That did it, thanks!

**Comment by Emru1** [comment]
Is anything preventing merge in this PR?

**Comment by oreo639** [comment]
That is up to the maintainers. You can try asking for a review on the IRC (politely ofc)

**Pull request merged**
