### PR TITLE
[DO NOT MERGE YET] linux: update to 5.1.

### PR DESCRIPTION
**Pull request by Hoshpak**
@void-linux/pkg-committers any objections?

see also #11660

### CODE REVIEW

**Comment by xtraeme** [comment]
:+1:

**Comment by lemmi** [comment]
Please hold off. 5.1 had massive issues Vega64 cards and I hadn't had a chance to see if the fixes were backported. Give me a day to confirm this.

**Comment by Hoshpak** [comment]
Interesting, is that documented somewhere? The only issue I heard of was caused by an Mesa update but that was fixed in the meantime and not caused by the kernel.

**Comment by lemmi** [comment]
This should be it. Someone asked for a backport a week ago: https://bugs.freedesktop.org/show_bug.cgi?id=110777

**Comment by Hoshpak** [comment]
Thanks, let's wait for it then.

**Comment by xtraeme** [comment]
Let's hope they backport the patch for next version.

**Comment by Gottox** [comment]
Please check if 5.2 solves this issue for you.

**Comment by lemmi** [comment]
I'm gone for the week. Earliest I can review it is Monday.

**Comment by Gottox** [comment]
:+1: thanks!

**Comment by lemmi** [comment]
Still not fixed in 5.2 :\

**Comment by Gottox** [comment]
Dang. @lemmi can you check if the patches mentioned in https://bugs.freedesktop.org/show_bug.cgi?id=110777 solve the issue for you?

**Comment by Hoshpak** [comment]
linux5.1 is EOL.

**Pull request closed without merging**
