### PR TITLE
tmux: update to 3.1. And claim maintainer

### PR DESCRIPTION
**Pull request by sgn**
Change maintainer from Nathan Owens to me.
He/She left for other projects.
And I'm using tmux for every day.

---

Tested with aarch64-musl x86_64{,-musl}

### CODE REVIEW

**Comment by sgn** [comment]
I see a recent CPU spike. Let me check if it's because of new tmux.

**Comment by sgn** [comment]
My tmux with weechat on `aarch64-musl` is crashed this afternoon.
I need to check whether it's related to tmux or not.

**Comment by sgn** [comment]
Not sure what's wrong previously. It's running for 2 days now.

**Comment by q66** [comment]
lgtm

**Pull request merged**
