### PR TITLE
[WIP] New packages: guile3, guix

### PR DESCRIPTION
**Pull request by ericonr**
Supersedes #22304 

- Added 3 as suffix for the guile3 executables.
- Update aisleriot, switch to guile3.
- Added dependencies for guix. I think there may be better ways of packaging them, but I'm not entirely sure. I have to fix the fact that they depend (for runtime) on the `-devel` version of other libraries, too.
- Package guix. Still needs a service file for `guix-daemon`.

### CODE REVIEW

**Comment by ericonr** [comment]
Needs fixes for cross compilation.

**Comment by travankor** [comment]
>Still needs a service file for guix-daemon.

https://issues.guix.gnu.org/issue/40601#5

**Comment by ericonr** [comment]
@travankor thanks! Will look into it.

**Comment by ericonr** [comment]
It doesn't want to work for 32-bit stuff (cross build to aarch64 runs just fine). Probably some issues with headers and config binaries.

**Comment by sgn** [comment]
> It doesn't want to work for 32-bit stuff (cross build to aarch64 runs just fine).
> Probably some issues with headers and config binaries.

Would this trick work?

https://github.com/void-linux/void-packages/blob/master/srcpkgs/LuaJIT/template#L19
https://github.com/void-linux/void-packages/blob/master/srcpkgs/LuaJIT/template#L52

**Comment by ericonr** [comment]
I haven't managed to make it work yet :/

The trick might have helped a bit, though, because it seems to be erroring out in a different place.

**Comment by ericonr** [comment]
@anjandev if you'd like to take my guile3 commits from this PR, feel free to do so. I don't see myself completing this package, since I've now switched full time to musl. @travankor if you'd like to take this over, that's an option too.

**Comment by anjandev** [comment]
Érico Nogueira Rolim <notifications@github.com> writes:

> @anjandev if you'd like to take my guile3 commits from this PR, feel free to do so.

I really dont have a use for this package and will not be
maintaining it.

**Comment by travankor** [comment]
It would be neat if guile3 could work with musl, but I don't have the time unfortunately.

**Comment by ericonr** [comment]
@travankor guile3 itself is working under musl. If you'd like to make a PR with the guile3 commit, it's working for everything. It's Guix that doesn't work on musl.

**Comment by travankor** [comment]
@ericonr Interesting that guile3 works fine on musl, while guix does not. Do you know the reason why guix is broken under musl and if this can be fixed? My understanding was that guix was written entirely in guile, so if guile works, then all application written in guile should work.

**Comment by ericonr** [comment]
Not sure :/ 

I believe `guix` simply doesn't know about musl as a target, so it couldn't get a proper configuration for itself. Since guix seems to want some glibc features such as `nss`, iiuc, I didn't try to go too deep into configuring the whole thing.

**Comment by ev-ermakov** [comment]
@ericonr, @travankor
> It's Guix that doesn't work on musl

Are you sure? :)

screenshot

**Comment by travankor** [comment]
@ev-ermakov 

Nice! Did you install this from a Void template or from the generic shell installer maintained by the Guix community? This is on my todo list to investigate, but I don't have much time right now :/ 

If you have a custom template for this, then it would be nice to upstream it to the void-packages repository :)

**Comment by ev-ermakov** [comment]
@travankor 
I compiled everything from scratch (without using xbps-src), following the [installation instructions](https://guix.gnu.org/manual/en/html_node/Requirements.html).

Here's the patch:
```diff
--- a/gnu/packages/bootstrap.scm
+++ b/gnu/packages/bootstrap.scm
@@ -262,6 +262,7 @@
   "Return the name of Glibc's dynamic linker for SYSTEM."
   ;; See the 'SYSDEP_KNOWN_INTERPRETER_NAMES' cpp macro in libc.
   (cond ((string=? system "x86_64-linux") "/lib/ld-linux-x86-64.so.2")
+        ((string=? system "x86_64-linux-musl") "/lib/ld-musl-x86_64.so.1")
         ((string=? system "i686-linux") "/lib/ld-linux.so.2")
         ((string=? system "armhf-linux") "/lib/ld-linux-armhf.so.3")
         ((string=? system "mips64el-linux") "/lib/ld.so.1")
```
But, of course, this is not enough:
screenshot

**Pull request closed without merging**
