### PR TITLE
xfce4-notes-plugin: update to 1.9.0

### PR DESCRIPTION
**Pull request by gpioneer90**
General

    This is a new package and it conforms to the quality requirements

Have the results of the proposed changes been tested?

I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me

The package showing on the void package website is not working. I created a new template that works for me. Wanted to share it so other users can use xbps-install to download this again.
No idea what I am doing. First time using git and compiling/making, and using xbps-src. Hopefully this works

### CODE REVIEW

**Comment by paper42** [comment]
* this should be in srcpkgs/xfce4-notes-plugin/template
* run xlint on the template to see what you need to fix
* put your name and email in the template

**Comment by ericonr** [comment]
@gpioneer90 ping

**Comment by gpioneer90** [comment]
Closing as I don't have the knowledge to fix some of those points.

**Comment by ericonr** [comment]
It's a good opportunity to learn, if you wish. Which step do you not know?

**Pull request closed without merging**
