### PR TITLE
lazydocker: update to 0.18.1

### PR DESCRIPTION
**Pull request by zen0bit**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, x86_64 libc

### CODE REVIEW

**Comment by paper42** [comment]
@benalb does this sound fine?

**Comment by benalb** [comment]
I will wait because of [this](https://github.com/jesseduffield/lazydocker/issues/327)
Also, I was trying to figure out how to correct the "lazydocker unversioned"

**Comment by paper42** [comment]
> I will wait because of [this](https://github.com/jesseduffield/lazydocker/issues/327)

That's an issue with their docker build, we are not using that, so we are not affected.

> Also, I was trying to figure out how to correct the "lazydocker unversioned"

I usually look at their Makefile or Dockerfile where they set ldflags: https://github.com/jesseduffield/lazydocker/blob/4f096c3c2b60a063d04b9b7ba9236a4d821e4563/Dockerfile#L16

@zen0bit please add `go_ldflags="-X main.version=${version}"` to the template

**Comment by benalb** [comment]
New release https://github.com/jesseduffield/lazydocker/releases/tag/v0.18.1

**Comment by zen0bit** [comment]
> > I will wait because of [this](https://github.com/jesseduffield/lazydocker/issues/327)
> 
> That's an issue with their docker build, we are not using that, so we are not affected.
> 
> > Also, I was trying to figure out how to correct the "lazydocker unversioned"
> 
> I usually look at their Makefile or Dockerfile where they set ldflags: https://github.com/jesseduffield/lazydocker/blob/4f096c3c2b60a063d04b9b7ba9236a4d821e4563/Dockerfile#L16
> 
> @zen0bit please add `go_ldflags="-X main.version=${version}"` to the template

added...I will wait because of https://github.com/jesseduffield/lazydocker/issues/327

That's an issue with their docker build, we are not using that, so we are not affected.

    Also, I was trying to figure out how to correct the "lazydocker unversioned"

I usually look at their Makefile or Dockerfile where they set ldflags: https://github.com/jesseduffield/lazydocker/blob/4f096c3c2b60a063d04b9b7ba9236a4d821e4563/Dockerfile#L16

@zen0bit please add go_ldflags="-X main.version=${version}" to the template

**Pull request merged**
