### PR TITLE
New packages for the Unity desktop environment

### LINKED ISSUE #43579: Package request: Unity desktop environment
### Package name

unityd

### Package homepage

https://gitlab.com/ubuntu-unity/unity/unity

### Description

A desktop platform, based on technologies such as Nux, GTK and Compiz.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

### PR DESCRIPTION
**Pull request by EarldridgeJazzedPineda**
I will the changing some of the packages in the future, but this should do for now.

#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc

#### How to test Unity
To test the Unity desktop environment, build and install the `unity-core` package
 
Enable the `dbus`, `lightdm`, and `openrc-settingsd` services.

At the login screen, click on the circle next to the username and select "Unity (Default)", then login as usual.

#### Services
Here is a list of runit services that I wrote:
* indicator-datetime
* indicator-power
* indicator-session
* indicator-sound
* hud
* unity7
* unity-gtk-module
* unity-panel-service
* unity-panel-service-lockscreen
* unity-settings-daemon
* window-stack-bridge

I later learned that runit is not suitable for these kinds of programs. I will be using gnome-session to make it init-agnostic (inspired by [another attempt to port Unity to a non-systemd distribution](https://forum.porteus.org/viewtopic.php?t=11233)).

#### Known issues
* Indicators do not load at the Unity greeter.

Closes #43579.

### CODE REVIEW

**Comment by abenson** [comment]
Please rebase this to get rid of the merge commit.

**Comment by EarldridgeJazzedPineda** [comment]
Indicators just simply refuse to work. Not sure if it has something to do with using libayatana-indicator vs libindicator, because Unity isn't designed to use the former.

**Comment by EarldridgeJazzedPineda** [comment]
Can I squash all of the commits?

**Comment by EarldridgeJazzedPineda** [comment]
The HUD did not work because it was referring to "com.canonical.dbusmenu" instead of "org.ayatana.dbusmenu". I will patch it later.

**Comment by EarldridgeJazzedPineda** [comment]
Can I squash all of the commits? 40 commits feels like too much and I don't to rebase for every package I make changes to.

**Comment by EarldridgeJazzedPineda** [comment]
I no longer have a Void Linux virtual machine, but feel free to continue my work

**Pull request closed without merging**
