### PR TITLE
kirc: update to 0.2.9

### PR DESCRIPTION
**Pull request by notthewave**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by notthewave** [comment]
forgot the : in commit message

**Comment by notthewave** [comment]
forgot to force push sorry

**Comment by ericonr** [comment]
Remeber to rebase and squash the commits on upstream/master, so the merge commits vanish and we get a single commit.

**Comment by notthewave** [comment]
Learned a new thing

**Pull request merged**
