### PR TITLE
New package: uutils-0.0.24

### LINKED ISSUE #47445: Package request: uutils
### Package name

uutils

### Package homepage

https://github.com/uutils/coreutils

### Description

Rust coreutils

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

### PR DESCRIPTION
**Pull request by caughtquick**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64 glibc)

This PR closes #47445

### CODE REVIEW

**Comment by caughtquick** [comment]
This built fine on my x86_64 glibc PC, not sure why it's not building now

**Comment by oreo639** [comment]
Those are test failures. Run them locally and see if they succeed.
Sometimes test failures are because of bugs in the application other times, test failures are because some functions aren't supported when run in the container. (some tests may rely on having a desktop running, for example)

**Comment by caughtquick** [comment]
In regards to x86_64-glibc, the package built fine, should I be checking x86_64-musl and i686-glibc locally (crossbuilds?).

**Comment by oreo639** [comment]
> In regards to x86_64-glibc, the package built fine

You need to do `./xbps-src pkg -Q uutils` or `./xbps-src check uutils` in order to run the tests.

Testing locally, the following tests do fail:
```
    test_df::test_file_column_width_if_filename_contains_unicode_chars
    test_df::test_nonexistent_file
    test_df::test_output_file_specific_files
    test_df::test_output_mp_repeat
    test_df::test_output_option_without_equals_sign
    test_df::test_total_label_in_correct_column
    test_df::test_type_option_with_file
    test_test::test_file_not_owned_by_egid
    test_test::test_file_not_owned_by_euid
    test_touch::test_touch_system_fails
```

> should I be checking x86_64-musl and i686-glibc locally (crossbuilds?)?

Those are not cross builds, they are native builds. (`-a i686` is cross and `-A i686` is native)
You can't run tests when cross compiling.

**Comment by ahesford** [comment]
This package is misnamed. Normally it should be `coreutils`, which obviously conflicts, so maybe `uutils-coreutils` is a better choice.

I find the documentation very opaque, either because it's missing critical information or because I'm looking for critical information on a phone. The documentation I did find says that "uutils includes a multi-call binary from which the utils can be invoked", but does not say that uutils *is comprised of* a multi-call binary. This makes it sound like the multi-call binary is an optional component of a package that also provides individual commands.

Please confirm that the single executable installed by this package *is* the multi-call executable and can (should) be run similarly to busybox. In particular, I want to ensure that running `/usr/bin/coreutils` won't "helpfully" do something destructive like unpack a bunch of commands or make a bunch of symlinks that would interfere with the system `coreutils` package.

**Comment by caughtquick** [comment]
Running 'coreutils' does not do anything destructive, it just prompts you to run the command you want, for example 'coreutils ls' or 'coreutils bat'. It does not appear to conflict with the GNU coreutils installed by default on the system. In regards to the name change, I'll make that now.

**Pull request closed without merging**
