### PR TITLE
oomox: added missing dependency `python3-Pillow`

### PR DESCRIPTION
**Pull request by VoidNoire**
This fixes themix-project/oomox#159

### CODE REVIEW

**Comment by VoidNoire** [comment]
Right, sorry about that. Fixed the title now.

**Comment by maxice8** [comment]
Please fix the commit title. It is the important one which is going into the git history.

**Comment by Johnnynator** [comment]
@VoidNoire He was talking mainly about the commit message. You can easily change it with `git commit --amend` and then force push.

**Comment by actionless** [comment]
i'd recommend also to sync it with the latest stable version (in a separate PR i guess): https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=oomox

**Pull request merged**
