### PR TITLE
base: comply with FHS a little more

### PR DESCRIPTION
**Pull request by maxice8**
regarding var/mail and var/spool/mail

### CODE REVIEW

**Comment by chneukirchen** [comment]
mailx also has `MAILSPOOL=/var/spool/mail`

**Comment by maxice8** [comment]
On Mon, Dec 17, 2018 at 03:40:57AM -0800, Leah Neukirchen wrote:
> mailx also has `MAILSPOOL=/var/spool/mail`
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/5815#issuecomment-447816143

nail-s too but i'm changing only the base system.

after this change we will be like Debian that has /var/mail with /var/spool/mail being a symlink.

We actually have packages configured to use both places.

**Comment by maxice8** [comment]
Opinions @void-linux/pkg-committers

**Comment by the-maldridge** [comment]
:shipit:

**Comment by Vaelatern** [comment]
:shipit:

**Pull request merged**
