### PR TITLE
font-iosevka: use super TTC packaging format

### PR DESCRIPTION
**Pull request by FollieHiyuki**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

Save roughly 3MB disk space :) and bandwidth

comparison

### CODE REVIEW

**Comment by FollieHiyuki** [comment]
@ericonr good to merge? The next release of the font might come in the next few days, and I want to stick with the new format til then.
The font works on my system for all the apps I use (it is still `.ttc` so nothing changes).

**Comment by ericonr** [comment]
I'd like to be sure all our software works with this format, but idk how to determine that.

Also, it should be fine to repurpose this PR to also do the update.

**Comment by ericonr** [comment]
Since this is also about bandwidth, let's wait for an actual update to do it ;)

**Comment by FollieHiyuki** [comment]
Updated to 6.0.1

**Pull request merged**
