### PR TITLE
KDE Gear update to: 22.12.3

### PR DESCRIPTION
**Pull request by hervyqa**
* kdevelop-python: update to 22.12.3
* kdevelop-php: update to 22.12.3
* kdevelop: update to 22.12.3
* zanshin: update to 22.12.3
* sweeper: update to 22.12.3
* spectacle: update to 22.12.3
* skanpage: update to 22.12.3
* skanlite: update to 22.12.3
* print-manager: update to 22.12.3
* partitionmanager: update to 22.12.3
* palapeli: update to 22.12.3
* okular: update to 22.12.3
* libksane: update to 22.12.3
* libkipi5: update to 22.12.3
* kwave: update to 22.12.3
* ktuberling: update to 22.12.3, adopt
* ktouch: update to 22.12.3
* ktorrent: update to 22.12.3
* ksanecore: update to 22.12.3
* krfb: update to 22.12.3, adopt
* krdc: update to 22.12.3, adopt
* kqtquickcharts: update to 22.12.3
* kpmcore: update to 22.12.3
* korganizer: update to 22.12.3, adopt
* kontact: update to 22.12.3, adopt
* konquest: update to 22.12.3
* konqueror: update to 22.12.3, adopt
* knight: update to 22.12.3
* knotes: update to 22.12.3, adopt
* kmines: update to 22.12.3
* kmail: update to 22.12.3
* pim-data-exporter: update to 22.12.3
* kmail-account-wizard: update to 22.12.3
* kleopatra: update to 22.12.3
* kgpg: update to 22.12.3
* kget: update to 22.12.3, adopt
* libktorrent: update to 22.12.3, adopt
* kdepim-addons: update to 22.12.3
* libksieve: update to 22.12.3
* ktnef: update to 22.12.3
* kitinerary: update to 22.12.3
* kpkpass: update to 22.12.3
* kdenlive: update to 22.12.3, adopt
* kdegraphics-thumbnailers: update to 22.12.3
* libqmobipocket: update to 22.12.3
* kdeconnect: update to 22.12.3
* kde5-baseapps: update to 22.12.3
* konsole: update to 22.12.3
* khelpcenter: update to 22.12.3
* kcolorchooser: update to 22.12.3
* kcharselect: update to 22.12.3
* kcalc: update to 22.12.3
* kblocks: update to 22.12.3
* kate5: update to 22.12.3
* kapman: update to 22.12.3
* kamoso: update to 22.12.3
* kalendar: update to 22.12.3
* kdepim-runtime: update to 22.12.3
* kalarm: update to 22.12.3
* kaddressbook: update to 22.12.3
* k3b: update to 22.12.3
* juk: update to 22.12.3
* incidenceeditor: update to 22.12.3, adopt
* ffmpegthumbs: update to 22.12.3
* eventviews: update to 22.12.3
* elisa: update to 22.12.3
* dragon-player: update to 22.12.3
* dolphin-plugins: update to 22.12.3
* dolphin: update to 22.12.3
* kio-extras: update to 22.12.3
* libkexiv25: update to 22.12.3
* calendarsupport: update to 22.12.3
* baloo-widgets5: update to 22.12.3
* ark: update to 22.12.3
* akregator: update to 22.12.3, adopt
* kontactinterface: update to 22.12.3
* akonadi-notes: update to 22.12.3
* akonadi-import-wizard: update to 22.12.3
* mailcommon: update to 22.12.3
* messagelib: update to 22.12.3
* libgravatar: update to 22.12.3
* kmbox: update to 22.12.3
* mailimporter: update to 22.12.3
* pimcommon: update to 22.12.3
* kimap: update to 22.12.3
* libkdepim: update to 22.12.3
* akonadi-search: update to 22.12.3
* kldap: update to 22.12.3
* akonadi-calendar: update to 22.12.3
* kcalutils: update to 22.12.3
* kidentitymanagement: update to 22.12.3
* kmailtransport: update to 22.12.3
* libkgapi: update to 22.12.3
* ksmtp: update to 22.12.3
* akonadi-contacts: update to 22.12.3
* grantleetheme: update to 22.12.3
* libkleo: update to 22.12.3
* kpimtextedit: update to 22.12.3
* akonadi-mime: update to 22.12.3
* akonadi5: update to 22.12.3
* kmime: update to 22.12.3

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)

Screenshot_20230320_102457

### CODE REVIEW

**Comment by hervyqa** [comment]
hi @Johnnynator, i need advice if there is a package that does not pass the CI test (CTest), what should I do?

**Comment by Chocimier** [comment]
> I tested the changes in this PR: YES

Did you actually manually test each of one hundred packages?

**Comment by hervyqa** [comment]
@Chocimier absolutely YES. see screenshot.

**Comment by Chocimier** [comment]
Please split this into more PRs to let CI finish before timeout.

For failing tests, ideally identifying and reporting/fixing them. For start, split into separate PR to let other packages to build and let's look at issues.

tirpc headers seem to be unsuitable for musl, please disable for now.

> YES. (…) and i installed

Just to make sure we understand each other: testing asked for in form is not building with xbps-src -Q, it is using the programs, that is writing few lines of text in ktouch, watching video in dragon, looking at python code completion in kdevelop, opening this PR with konqueror and so on. Was all of this smooth?

**Comment by hervyqa** [comment]
So far it's been running smoothly, I've been using it for 3 days. you are right, PR should be separated to avoid time out. but what I want to ask, what if a package requires dependencies from another PR, is it possible to compile successfully on CI?

**Comment by hervyqa** [comment]
> you can split off games, kdevelop and packages failing tests and the rest should fit. 

thanks, great idea. I'll try to create a PR from the KDE application category and the relevant dependencies.

**Comment by Chocimier** [comment]
Outdated by b1e9ac1.

**Comment by hervyqa** [comment]
@Chocimier great work. thank you!

**Pull request closed without merging**
