### PR TITLE
New package: bashtop-0.9.25

### PR DESCRIPTION
**Pull request by emacsomancer**

### CODE REVIEW

**Comment by abenson** [comment]
0.9.10 is out

**Comment by gorkawien** [comment]
https://github.com/aristocratos/bashtop

**Comment by abenson** [comment]
Change the value [here](https://github.com/aristocratos/bashtop/blob/master/bashtop#L166) to false so it doesn't check for updates on startup.

**Comment by emacsomancer** [comment]
> Change the value [here](https://github.com/aristocratos/bashtop/blob/master/bashtop#L166) to false so it doesn't check for updates on startup.
> 
> Before your `vbin`, do something like: `vsed -i '/^update_check/s/true/false/' -e bashtop`

updated

**Comment by gorkawien** [comment]
bashtop is no longer maintainded, but it was forked as "bpytop"
https://github.com/aristocratos/bpytop

**Comment by abenson** [comment]
Is the inclusion of [bpytop](#24668) enough to close this?

**Comment by emacsomancer** [comment]
> Is the inclusion of [bpytop](#24668) enough to close this?

I would say "yes", given that `bpytop` is effectively the continuation of `bashtop`.

**Comment by gorkawien** [comment]
> Is the inclusion of [bpytop](#24668) enough to close this?

I would also say "yes". It would be a great addition to the repositories.
Just in case, i post the template for the last verson 1.0.24:

# Template file for 'bpytop'
pkgname=bpytop
version=1.0.24
revision=1
build_style=gnu-makefile
archs=noarch
#conf_files=""
#hostmakedepends=""
#makedepends=""
depends="python3 python3-psutil"
conflicts="python3-psutil<5.7.0"
short_desc="Resource monitor for processor, memory, disks, network, processes"
maintainer="Tuxliban Torvalds <<tenshalito@gmail.com>>"
license="Apache-2.0"
homepage="https://github.com/aristocratos/bpytop"
distfiles="https://github.com/aristocratos/${pkgname}/archive/v${version}.tar.gz"
checksum=f8db1f2710c95f0d5c9c171bff7166678640024ca1e9162cc8c98b898932e7ed

**Comment by Chocimier** [comment]
Closing in favor of bpytop #24668.

**Pull request closed without merging**
