### PR TITLE
Drop mongo

### PR DESCRIPTION
**Pull request by the-maldridge**
As discussed in IRC the company behind mongodb has decided to transition it to the SSPL license.  This license has not been approved by the OSI, and with version 1 being thrown out entirely its fairly unlike that version 2 will be accepted.  Given the unclear relationship the license outlines, and the deliberately toxic nature of its scope clauses, we are following in the steps of Debian, RedHat, and numerous other distributions by removing the mongodb template and purging the existing package file from the repositories.

treefrog-framework is the only in-tree consumer of mongodb and is also dropped.

### CODE REVIEW

**Comment by maxice8** [comment]
This should be closed then #7227 

Don't forget to clean them from the repos

**Comment by maxice8** [comment]
Time to drop ? :D

**Comment by maxice8** [comment]
On Fri, Jan 25, 2019 at 09:43:45AM -0800, Michael Aldridge wrote:
> yeah, lets do it.  I can purge the packages from the mirror later today.
>  Please merge now if its giving you grief with readline.
> 
> --Michael
> 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/7361#issuecomment-457654960

No grief.

**Comment by the-maldridge** [comment]
Well this got away from me.  The packages have since been purged from the repo.

**Pull request merged**
