### PR TITLE
vpnc-scripts: update to 20190117

### PR DESCRIPTION
**Pull request by marmeladema**

### CODE REVIEW

**Comment by maxice8** [comment]
Fix errors pointed out by travis

**Comment by marmeladema** [comment]
Travis does not like ftp:
> ftp://ftp.infradead.org/pub/vpnc-scripts/vpnc-scripts-20190117.tar.gz: Can't open data connection

**Comment by maxice8** [comment]
Please make sure it can be cross compiled then

**Comment by marmeladema** [comment]
It's just a few files that are copied. There is no compilation of any sort.
That is also why it's a noarch package.

**Pull request merged**
