### PR TITLE
mesa: update to version 23.3.0.

### PR DESCRIPTION
**Pull request by SpidFightFR**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x64-GlibC)

Hey lads, a PR to update mesa to version 23.3.0, i hope it will be less of a mess for raytracing than 23.2.1 tho...!
It'll be a draft for now, as i'm testing this out, once that's done, i'll go public.

### CODE REVIEW

**Comment by SpidFightFR** [comment]
Alright, looks like [9590bce3e249a34665b2c42b20bfdbdc7f32147f.patch](https://github.com/void-linux/void-packages/pull/47494/files#diff-1a118364f8f615f00bb39a1feb2235265e4d3fcce75794e398a63be08a28c0af) is creating errors... checking that...

**Comment by SpidFightFR** [comment]
Alright, build worked for me, i'll let the checks run overnight, if they're good tomorrow, then the PR will set as public.

**Comment by SpidFightFR** [comment]
Alright arm is failing, imma check this later on...

**Comment by SpidFightFR** [comment]
I tried to check, but i struggle to understand what's wrong... help would be welcome !

**Comment by classabbyamp** [comment]
that should fix it

**Comment by SpidFightFR** [comment]
> that should fix it. also enabled virtio vulkan

Hey thanks! 
Virtio huh... Reminds me of that display method on Proxmox, that may be the same virtio thingy...!

Thanks for the help ! 🙏

**Comment by devlocalhost** [comment]
this is causing issues for me. gnome is very unstable, crashes randomly, lots of graphical glitches and some other stuff too. someone on irc also had issues with that (flatpak apps), they downgraded to 23.2.1 and everything was fine. heres what i got (when trying to run spotify flatpak):
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: crocus
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: crocus
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
```

these errors are gone if i downgrade mesa, and everything is back to normal

inxi -G --display output:
```
 > inxi -G --display
Graphics:
  Device-1: Intel Mobile 4 Series Integrated Graphics driver: i915 v: kernel
  Device-2: Suyin Acer/Lenovo Webcam [CN0316] driver: uvcvideo type: USB
  Display: wayland server: X.org v: 1.21.1.9 with: Xwayland v: 23.2.1 compositor: gnome-shell
    v: 44.2 driver: X: loaded: intel unloaded: fbdev,modesetting,vesa dri: i965 gpu: i915
    resolution: 1366x768
  API: EGL v: 1.5 drivers: N/A platforms: gbm,wayland
  API: OpenGL Message: No GL data available.
  API: Vulkan Message: No Vulkan data available.
```

**Comment by classabbyamp** [comment]
make an issue, then

**Pull request merged**
