### PR TITLE
neovim: update to 0.5.0

### PR DESCRIPTION
**Pull request by FollieHiyuki**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by FollieHiyuki** [comment]
I haven't tested any new features, since I still use an old config but it seems to run fine on my machine.

**Comment by ericonr** [comment]
I've been periodically tracking master with the LSP stuff, and I'd consider most of it well tested. Will update to the proper release and have some fun, but it should be mergeable.

**Comment by FollieHiyuki** [comment]
`checkhealth` complains about Cmake build style (we have it set to None). I don't know how to put it in Release and Debug for our packages correctly

**Comment by ibhagwan** [comment]
Seems to be working fine for me, I've been on the nightly for a while now, no changes required.

**Comment by siduck76** [comment]
> I haven't tested any new features, since I still use an old config but it seems to run fine on my machine.

works fine for me , my [config](https://github.com/siduck76/NvChad) has 90% of new features configured already.

**Comment by ericonr** [comment]
Thanks for the quick work :)

**Pull request merged**
