### PR TITLE
python3-pykwalify: update to 1.8.0.

### PR DESCRIPTION
**Pull request by Goorzhel**
#### Have the results of the proposed changes been tested?
- [X] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by Goorzhel** [comment]
Specifically, I'm using this for `borgmatic`, and it seems to work fine so far.

Notable parts from [the changelog](https://github.com/Grokzen/pykwalify/releases/tag/1.8.0): 
- Python 3.5 and below (incl. 2.7) obsoleted
- ruamel.yaml supplants PyYAML as the default parser

**Comment by Goorzhel** [comment]
PRs on 86 archs failing with:
```
/usr/bin/python3: No module named pip
error: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpm8_s91ez', '--quiet', 'python-dateutil>=2.8.0']' returned non-zero exit status 1.
```
Consider me stumped. I'll have time later this week to dig into this, though.

**Comment by ericonr** [comment]
It's runnning tests but can't find the dependencies. Just try adding `checkdepends="$depends"`

**Comment by Goorzhel** [comment]
```
ImportError while importing test module '/builddir/pykwalify-1.8.0/tests/test_core.py'.
<...>
tests/test_core.py:16: in <module>
    from testfixtures import compare
ModuleNotFoundError: No module named 'testfixtures'
```

I can dispel that with 
```
diff --git a/srcpkgs/python3-pykwalify/template b/srcpkgs/python3-pykwalify/template
index c53d82aa88..2c2fabe2e8 100644
--- a/srcpkgs/python3-pykwalify/template
+++ b/srcpkgs/python3-pykwalify/template
@@ -9 +9 @@ depends="python3-setuptools python3-ruamel.yaml python3-docopt python3-dateutil"
-checkdepends="$depends python3-pytest"
+checkdepends="$depends python3-pytest python3-pip"
@@ -16,0 +17,4 @@ checksum=796b2ad3ed4cb99b88308b533fb2f559c30fa6efb4fa9fda11347f483d245884
+pre_check() {
+       pip install testfixtures
+}
+
```
but a better bet would be to package `python3-testfixtures` for Void as well.

**Comment by Goorzhel** [comment]
To package _that_ I'd need to package `sybil` and `pytest-django` as well. It's packages all the way down. Are there ways I can get unstuck that are less dirty than the `pip install` fix above, @ericonr?

**Comment by ericonr** [comment]
Add

```
# requires python3-testfixtures, not packaged in void
make_check=no
```

to the template, then it won't run tests. It's unfortunate, but better than to package all that.

**Pull request merged**
