### PR TITLE
raul: remove package

### PR DESCRIPTION
**Pull request by icp1994**
#### Testing the changes
- I tested the changes in this PR: **NO**

#### Local build testing
- I built this PR locally for my native architecture, x86_64

I don't know how to test a C++ header library. Nothing on the repo depends on it. FWIW the upstream tests passes.

In reference to https://github.com/void-linux/void-packages/issues/38229 and https://github.com/void-linux/void-packages/issues/39083.

### CODE REVIEW

**Comment by classabbyamp** [comment]
nothing uses this library, we could probably just remove it outright

**Comment by icp1994** [comment]
That works too I guess - not really attached either way.

**Comment by icp1994** [comment]
Just making sure before I push, we are removing `raul` too, right?

**Comment by classabbyamp** [comment]
yes, i think so

**Pull request merged**
