### PR TITLE
emacs: update to 27.1.

### PR DESCRIPTION
**Pull request by sirikid**

### CODE REVIEW

**Comment by ericonr** [comment]
Smoke tested `emacs-gtk3` with circe, seems to be working fine. WIll be trying other daily usage.

**Comment by sirikid** [comment]
There is a bunch of new options (`--with-json`, `--with-cairo`, `--with-harfbuzz`), Idk if should they be enabled by default or not.

**Comment by flexibeast** [comment]
Haven't tried out this PR, but after downloading the .tar.xz, the .tar.gz, and their associated .sig files (via the links in [the announcement message](https://lists.gnu.org/archive/html/emacs-devel/2020-08/msg00237.html)), then trying to verify with `gpg --verify <file>.sig`, i'm getting "BAD signature"s. Can anyone else confirm?

**Comment by Noah-Huppert** [comment]
Built, in `eshell` (for extra points :smile:), just fine. Loads my `init.el` and seems to be working. x86_64.

**Comment by sirikid** [comment]
@flexibeast nope, just verified them

**Comment by leahneukirchen** [comment]
I would add gmp, enable jansson, disable cairo for now.

**Comment by sirikid** [comment]
I've added options for gmp, json, cairo and harfbuzz. Gmp and json are enabled by default.

**Comment by flexibeast** [comment]
@sirikid: Thanks. :-) i just downloaded again, and it seems to be fine now .... %-}

**Comment by leahneukirchen** [comment]
Runs fine here, will merge tomorrow if nothing shows up. Thanks!

**Pull request merged**
