### PR TITLE
cutter: fix build with qt5.15, switch to cmake, enable python

### PR DESCRIPTION
**Pull request by Piraty**

### CODE REVIEW

**Comment by jnbr** [comment]
Changing the build style is worth bumping revision.
Also, cmake installs a bunch of header files to `usr/include/cutter`, are they useful for anything?

**Comment by Piraty** [comment]
python plugin supports requires shiboken2-5.15 (@yopito)

**Comment by jnbr** [comment]
I bumped cutter to 1.11.0, so the qt5 patch can be dropped.

**Comment by ericonr** [comment]
ping?

**Comment by jnbr** [comment]
Outdated, closing.

**Pull request closed without merging**
