### PR TITLE
bash: update to 5.2.015.

### PR DESCRIPTION
**Pull request by mhmdanas**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by Piraty** [comment]
for reference, arch reverted it . https://lists.archlinux.org/archives/list/arch-dev-public@lists.archlinux.org/message/JTLMTWDKUITZVPAU3BL3OQPE7R7CHDIH/

**Comment by mhmdanas** [comment]
@Piraty oh, shall I close this then?

**Comment by Piraty** [comment]
no why should you?

**Comment by mhmdanas** [comment]
Because it "breaks makepkg" according to that thread you linked?

**Comment by Piraty** [comment]
no. closing PRs based on some random distro's issue with it won't help much.
core packages in specific need careful testing prior to merge.

**Comment by mhmdanas** [comment]
I have been using this since the PR was published, with no issues.

**Comment by Bnyro** [comment]
I've been running this too for the past few days and didn't encounter any issues either.

**Pull request closed without merging**
