### PR TITLE
New package: dumb_runtime_dir-1.0.2

### PR DESCRIPTION
**Pull request by ifreund**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

### CODE REVIEW

**Comment by tornaria** [comment]
I've read the PR and the upstream code and everything LGTM.
 
I built and installed on my desktop, and works ok. Before I had `pam_rundir` which I replaced by this. I like that it comes preconfigured in pam-base. Even if both elogind and this are installed, it doesn't seem a problem at least when run in the order specified in this PR (but I haven't and won't test that).

I wonder if the package name should be `pam-dumb_runtime_dir` for consistency with other pam modules, or have the words "pam" and/or "rundir" somewhere for the benefit of searching.

In any case, other than the package name (on which I have no clear opinion), this is positive review from me.

**Review by tornaria — APPROVED** [review]

**Comment by ifreund** [comment]
> I wonder if the package name should be `pam-dumb_runtime_dir` for consistency with other pam modules, or have the words "pam" and/or "rundir" somewhere for the benefit of searching.

The variable this sets is `XDG_RUNTIME_DIR`, "rundir" seems to be a name invented by `pam_rundir`. I think having `XDG_RUNTIME_DIR` in the package's description should be sufficient.

Anyhow, the policy stated in the [Manual.md](https://github.com/void-linux/void-packages/blob/master/Manual.md#namingconventions) is to follow upstream naming, which I don't plan on changing at this point.

**Comment by tornaria** [comment]
> The variable this sets is `XDG_RUNTIME_DIR`, "rundir" seems to be a name invented by `pam_rundir`. I think having `XDG_RUNTIME_DIR` in the package's description should be sufficient.

`xrs rundir` shows two packages with this purpose (`pam_rundir` and `rundird`)

> Anyhow, the policy stated in the [Manual.md](https://github.com/void-linux/void-packages/blob/master/Manual.md#namingconventions) is to follow upstream naming, which I don't plan on changing at this point.

Cf python packages, and for pam see `pam_zfscrypt`. I'm still don't have a clear opinion on the name.

**Comment by tornaria** [comment]
I've been running this since yesterday on several boxes (local and remote). Uneventful, it just works as expected.

This fixes an issue I had when using `pam_rundir`: if I log in to a remote box, run something in screen, detach and log out, the runtime dir would be removed, in spite of my user still being active.

Therefore I would favor recommending this for runtime dir on the absence of elogind. It is activated just by installing, it is zero maintenance and multi-user.   Since `/run/user` is created at boot by `core-services/00-pseudofs.sh` on a tmpfs, there's no cleanup needed.

Maybe a mention can be added to the manual at https://docs.voidlinux.org/config/session-management.html#xdg_runtime_dir

**Comment by ifreund** [comment]
> I've been running this since yesterday on several boxes (local and remote). Uneventful, it just works as expected.

Excellent! Uneventful was is the goal :)

> Therefore I would favor recommending this for runtime dir on the absence of elogind. It is activated just by installing, it is zero maintenance and multi-user. Since `/run/user` is created at boot by `core-services/00-pseudofs.sh` on a tmpfs, there's no cleanup needed.
> 
> Maybe a mention can be added to the manual at https://docs.voidlinux.org/config/session-management.html#xdg_runtime_dir

There is some discussion on this subject ongoing here: https://github.com/void-linux/void-docs/issues/635

**Review by paper42 — APPROVED** [review]
lgtm

**Comment by ifreund** [comment]
I just released a new version of `dumb_runtime_dir` that uses `pkg-config` at the request of a user. Diffing the 1.0.1 and 1.0.2 binaries produced by xbps-src showed no difference. 

Using pkg-config to link pam has highlight something weird about our pam packaging though, the `.pc` files are in the `pam` package instead of `pam-devel`. If you like I'd be happy to move them as part of this PR.

**Pull request merged**
