### PR TITLE
New package: gamescope-3.11.51

### LINKED ISSUE #36869: Package request: gamescope
https://github.com/Plagman/gamescope
Replaces steamos-compositor

### PR DESCRIPTION
**Pull request by sirkhancision**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc

Closes #36869

### CODE REVIEW

**Comment by HadetTheUndying** [comment]
I've been testing this since yesterday and comparing it to how it works on my Steam Deck and everything seems good. It also fixes some issues for me in Gnome Wayland with some games not performing well.

**Comment by sirkhancision** [comment]
> I've been testing this since yesterday and comparing it to how it works on my Steam Deck and everything seems good. It also fixes some issues for me in Gnome Wayland with some games not performing well.
> 
> That being said gamescope 3.12.0 is out now.

I have created a [branch with gamescope 3.12.0](https://github.com/sirkhancision/void-packages/tree/gamescope-3.12.0), but I'm having problem running it (it builds and installs correctly, it feels like either a gamescope bug or a bug related to my machine), so if you could test it, I'd appreciate it :)

**Comment by Natthias** [comment]
I have a build of gamescope 3.12.0 in my [personal packages repo](https://github.com/Natthias/abyssal-packages), which also builds correctly, yet doesn't function properly.

It seems likely that the issue is this. Is this the same error message on your end?
`wlserver: [xwayland/server.c:270] Xwayland startup failed, not setting up xwm`

As an aside, you probably shouldn't package stb in this PR, as upstream doesn't provide releases. I think including it in the template for gamescope is the correct way to proceed

**Comment by HadetTheUndying** [comment]
I have the same issue with 3.12 . I'll work on investigating over the weekend if no one else figures it out

**Comment by HadetTheUndying** [comment]
Just an update. I'm not gonna be able to do a lot of work on this I'll be away most of the weekend and start a new job on Monday but it might be helpful

```gdb
(gdb) run
Starting program: /usr/bin/gamescope 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
wlserver: [backend/headless/backend.c:68] Creating headless backend
[New Thread 0x7fd85748e6c0 (LWP 4720)]
[New Thread 0x7fd856b4c6c0 (LWP 4722)]
vulkan: selecting physical device 'AMD Radeon RX Vega (RADV VEGA10)': queue family 1
vulkan: physical device supports DRM format modifiers
[New Thread 0x7fd85634b6c0 (LWP 4723)]
[New Thread 0x7fd855b4a6c0 (LWP 4724)]
[New Thread 0x7fd8553496c0 (LWP 4725)]
[New Thread 0x7fd854a486c0 (LWP 4726)]
vulkan: supported DRM formats for sampling usage:
vulkan:   AR24 (0x34325241)
vulkan:   XR24 (0x34325258)
vulkan:   AB24 (0x34324241)
vulkan:   XB24 (0x34324258)
vulkan:   NV12 (0x3231564E)
vulkan:   AB4H (0x48344241)
vulkan:   XB4H (0x48344258)
vulkan:   AB48 (0x38344241)
vulkan:   XB48 (0x38344258)
vulkan:   AB30 (0x30334241)
vulkan:   XB30 (0x30334258)
vulkan:   AR30 (0x30335241)
vulkan:   XR30 (0x30335258)
[New Thread 0x7fd83ffff6c0 (LWP 4727)]
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:16] Starting headless backend
[Detaching after fork from child process 4729]
wlserver: [xwayland/server.c:108] Starting Xwayland on :2
wlserver: wl_event_loop_dispatch failed

Failed to initialize wlserver
[Thread 0x7fd856b4c6c0 (LWP 4722) exited]
[Thread 0x7fd855b4a6c0 (LWP 4724) exited]
[Thread 0x7fd8553496c0 (LWP 4725) exited]
[Thread 0x7fd85634b6c0 (LWP 4723) exited]
(EE) could not connect to wayland server
[Thread 0x7fd83ffff6c0 (LWP 4727) exited]
[Thread 0x7fd854a486c0 (LWP 4726) exited]
[Thread 0x7fd85748e6c0 (LWP 4720) exited]
[Inferior 1 (process 4714) exited with code 01]
```

**Comment by SpidFightFR** [comment]
Do we have any news on this PR ?

**Comment by dexgs** [comment]
I've managed to package gamescope 3.13 such that it works (https://github.com/dexgs/void-packages/commit/7f2d5a92c683c2a12635d277ee93d6dbfb4301da), but it needs a more recent Vulkan-Headers than is currently packaged, so I've opened a PR for that first (#47186)

**Comment by SpidFightFR** [comment]
> I've managed to package gamescope 3.13 such that it works ([dexgs@7f2d5a9](https://github.com/dexgs/void-packages/commit/7f2d5a92c683c2a12635d277ee93d6dbfb4301da)), but it needs a more recent Vulkan-Headers than is currently packaged, so I've opened a PR for that first (#47186)

neat! i certainly hope gamescope will make it to void repos !

**Comment by dexgs** [comment]
No, I've opened #48354. Hopefully it is ready to merge.

**Comment by SpidFightFR** [comment]
This PR should be closed, then ?

**Comment by mdkcore0** [comment]
can we close this PR, since https://github.com/void-linux/void-packages/pull/48354 was merged already?

**Pull request closed without merging**
