### PR TITLE
android-tools: update to 9.0.0r45.

### PR DESCRIPTION
**Pull request by zdtcd**

### CODE REVIEW

**Comment by Johnnynator** [comment]
@zdtcd Boringssl is failing on `i686` https://travis-ci.org/void-linux/void-packages/jobs/554987010

**Comment by zdtcd** [comment]
On 2019-07-06 08:50:10 -0700, John Zimmermann wrote:
> @zdtcd Boringssl is failing on `i686` https://travis-ci.org/void-linux/void-packages/jobs/554987010

Oops, I'll try to find a fix for it.

-- 
Danh

**Comment by zdtcd** [comment]
This looks like a problem with i686 image docker image on amd64 host.
I've packaged this successfully on i686 qemu machine.

**Comment by Hoshpak** [comment]
If it's not caused by docker, this is a serious issue. Our build servers are all x86_64 hosts. Could you maybe try to build the package on your x86_64 machine using an i686 masterdir? I would do it myself but my machine is currently busy compiling kernels.

**Comment by zdtcd** [comment]
On 2019-07-09 00:37:09 -0700, Helmut Pozimski wrote:
> If it's not caused by docker, this is a serious issue. Our build
> servers are all x86_64 hosts. Could you maybe try to build the
> package on your x86_64 machine using an i686 masterdir? I would do
> it myself but my machine is currently busy compiling kernels.

Yes, I've done it.

```
XBPS_ARCH=i686 BOOTSTRAP=i686 ARCH=i686 ./xbps-src binary-bootstrap
XBPS_ARCH=i686 BOOTSTRAP=i686 ARCH=i686 ./xbps-src pkg android-tools
```

`CMAKE_SYSTEM_PROCESSOR` reports x86_64 even with i386 masterdir.
I think cmake is using `uname -m` or something, but I haven't checked.

-- 
Danh

**Comment by Hoshpak** [comment]
Great, I think this is ready to merge then. If no one else gets around to do it, I will get back to it in a few hours once I got time and the builders are free.

**Comment by zdtcd** [comment]
I'll try to figure out later today.
fwiw, LibreSSL met this problems before: https://github.com/libressl-portable/portable/issues/361

**Pull request merged**
