### PR TITLE
neovim: update to 0.3.0.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by maxice8** [comment]
On Tue, Jun 19, 2018 at 12:04:09PM -0700, cr6git wrote:
> Merged #43.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/43#event-1689450149

Was the clipboard issue fixed ?

**Comment by cr6git** [comment]
I don't know what was this clipboard issue?

**Comment by maxice8** [comment]
https://github.com/neovim/neovim/issues/8450

**Comment by cr6git** [comment]
ok, I can reproduce this:
````
:!echo hi > /dev/tty
/bin/bash: /dev/tty: No such device or address

shell returned 1

Press ENTER or type command to continue
````

**Comment by cr6git** [comment]
still not fixed in nightly v0.3.1-dev

**Comment by cr6git** [comment]
They tagged this as **wontfix.**

**Pull request merged**
