### PR TITLE
[WIP] rust: update to 1.46.0

### PR DESCRIPTION
**Pull request by jnbr**
needs some testing
@q66 can you build 1.44 bootstrap binaries for ppc* ?

### CODE REVIEW

**Comment by jnbr** [comment]
Builds are passing for all our official supported architectures.
No issues with building firefox with the updated rust.
Still blocked by powerpc (https://bugzilla.redhat.com/show_bug.cgi?id=1862012).

**Comment by q66** [comment]
1.46 is out tomorrow, we should just update to that; the 1.45.2 bootstrap tarballs are currently being built so we should have them in time

the llvm issue is now solved (patch already included in `void-packages`) so that's not blocking anything anymore

**Comment by jnbr** [comment]
updated to 1.46.0

**Comment by ericonr** [comment]
Regression, but I don't know if it affects projects we use: https://www.reddit.com/r/rust/comments/iingya/compiler_regression_on_1460/

**Comment by Chocimier** [comment]
closed by 6d6416793c0fd6be56ea5f05a94b813c6af39218

**Pull request closed without merging**
