### PR TITLE
[wip] openjdk: alternative binary bootstrap

### PR DESCRIPTION
**Pull request by q66**
This allows me to bootstrap on ppc64le, but I don't expect it to get merged like this; it's more like a starting point to obtain some pointers. @Vaelatern, if you have any ideas how to get things done right, please bring them up here, because I don't.

### CODE REVIEW

**Comment by Vaelatern** [comment]
This is really not a bad way to go about this. I have some cleanups in mind, but this is not bad at all.

**Comment by q66** [comment]
The main thing is that this source is not complete either. It provides builds for x86_64, ppc64le and aarch64, but not 32-bit ARM, nor musl. I'd like to see musl bootstrap solved, but there doesn't seem to be any way to go at it. I think putting the host openjdk based bootstrap under an option is a good thing to do either way, though, since it creates a loop in non-cross environments.

Also, it'd probably be best to switch to a stable snapshot rather than nightly. I only did nightly for this because the latest stable for aarch64 is older than for the other platforms and I didn't feel like adding more conditionals while experimenting. So I'll probably be cleaning this up more anyway.

**Comment by Kistelini** [comment]
I was working on a JDK, too. My approach was to cross compile a bootstrap JDk once for all native builders which can't run x86_64-glibc stuff (so x86_64-musl and i686, should be possible to do that for ppc too). It works but has some shlib-problems and the JDK on musl fails to compile itself, it's still too hacky for a WIP pull request.
https://github.com/Kistelini/void-packages/commit/ac2b76299835f93c6d08d0fd3c34162ef4196d15

**Comment by q66** [comment]
I'll close this for now, since I have another/better approach in mind...

**Comment by Vaelatern** [comment]
Oh? please, tell!

**Comment by Johnnynator** [comment]
https://github.com/void-linux/void-packages/issues/3237#issuecomment-520471986

**Pull request closed without merging**
