### PR TITLE
wayland-utils: update to 1.2.0, update distfiles

### PR DESCRIPTION
**Pull request by caughtquick**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by sgn** [comment]
Remove `, update distfiles`

**Comment by caughtquick** [comment]
@sgn the distfiles location was actually changed, it's not located in at the same URL format it was previously.

**Comment by sgn** [comment]
Me knew that.

**Comment by caughtquick** [comment]
@sgn The change to the commit has been made

**Pull request merged**
