### PR TITLE
[WIP] New package: corosync-3.0.2

### PR DESCRIPTION
**Pull request by jirib**
The Corosync Cluster Engine is a Group Communication System with additional features for implementing high availability within applications.

Needed for future pacemaker package.

### CODE REVIEW

**Comment by jirib** [comment]
Any idea about following issue?

```
$ xbps-query -l | grep corosynclib
ii corosynclib-3.0.2_1                     Corosync libraries
$ sudo xbps-install --repository=hostdir/binpkgs/corosync/ corosynclib-devel
MISSING: corosynclib=>3.0.2_1
Transaction aborted due to unresolved dependencies.
```

**Comment by Hoshpak** [comment]
=> looks odd, I think it should be >=. However you should not need to add that manually since dependencies on shard libraries are automatically detected by xbps-src while building the package. Following the usual pattern for libraries, the sub-package should be called `libcorosync'. Haven't reviewed the rest of the template yet.

**Comment by jirib** [comment]
> => looks odd, I think it should be >=. However you should not need to add that manually since dependencies on shard libraries are automatically detected by xbps-src while building the package. Following the usual pattern for libraries, the sub-package should be called `libcorosync'. Haven't reviewed the rest of the template yet.

Thanks, it was this typo.

BTW, as libknet1 does not build on musl archs, how should this package be treated? Should I define it to be only for non-musl archs? IIUC corosync can't be easily told to be build without 'knet' transport now, see https://github.com/corosync/corosync/issues/501

**Comment by jirib** [comment]
> > => looks odd, I think it should be >=. However you should not need to add that manually since dependencies on shard libraries are automatically detected by xbps-src while building the package. Following the usual pattern for libraries, the sub-package should be called `libcorosync'. Haven't reviewed the rest of the template yet.
> 
> Thanks, it was this typo.
> 
> BTW, as libknet1 does not build on musl archs, how should this package be treated? Should I define it to be only for non-musl archs? IIUC corosync can't be easily told to be build without 'knet' transport now, see [corosync/corosync#501](https://github.com/corosync/corosync/issues/501)

Solved, I'm preparing libknet1/libnozzle1 (new pkg) fix which would support musl, https://github.com/void-linux/void-packages/pull/14215

**Pull request closed without merging**
