### PR TITLE
[Testing needed] New package: wireplumber-0.3.0

### PR DESCRIPTION
**Pull request by paper42**

### CODE REVIEW

**Comment by ericonr** [comment]
Do you think other packages will come to use cpptoml? Otherwise having to carry a patch to devendor it doesn't sound super nice :/ (unless that goes upstream).

**Comment by PaperMountainStudio** [comment]
similar patch is upstream, I updated the PR to use that patch instead of the archlinux one

cmake can not be found on arm architectures, I am not sure why
```
Found CMake: NO
Run-time dependency cpptoml found: NO (tried pkgconfig and cmake)
```

**Comment by ericonr** [comment]
meson can be kinda screwy when doing cross and using cmake for detecting libraries. I have a patch that might fix this in the meson build style, but it's ugly as sin. And I believe meson is looking to improve how they use cmake for cross, so I wasn't sure I should PR it. https://github.com/ericonr/void-packages/commit/a722a66affb8b1110cfd5741bb1f9b1e6d8c8d73

**Comment by ericonr** [comment]
you might be able to get away with only adding `-Dcmake=cmake` to configure_args, though in that case I'd consider adding it to the build style.

**Comment by PaperMountainStudio** [comment]
> you might be able to get away with only adding `-Dcmake=cmake` to configure_args, though in that case I'd consider adding it to the build style.

sadly, no. should I mark it as nocross for now?

**Pull request closed without merging**
