### PR TITLE
various: quote all unquoted reverts

### PR DESCRIPTION
**Pull request by pltrz**
Grepped through the repo to find out all these unquoted instances of `reverts`

### CODE REVIEW

**Comment by maxice8** [comment]
There is no need to quote them in a single wide-ranging commit, it also masks the previous commit so people using `git blame` won't be able to easily find out why the reverts= was added.

**Comment by pltrz** [comment]
> There is no need to quote them in a single wide-ranging commit

That's what I thought, that's why I didn't quote in #10165 on the first push; you said to quote so I was under the impression this is the style all templates should use. So should we rather unquote all the single wide `reverts`?

> ... it also masks the previous commit so people using git blame won't be able to easily find out why the reverts= was added.

This is a valid concern. So we should leave them mixed?

**Comment by maxice8** [comment]
> you said to quote so I was under the impression this is the style all templates should use

All templates should use, we shouldn't make a tree-wide change just for the sake of it. They being unquoted doesn't make them not work they just make them stylistically incompatible, you fix them as you update the package.

> So should we rather unquote all the single wide reverts?

**Comment by maxice8** [comment]
> This is a valid concern. So we should leave them mixed?

yes

**Comment by pltrz** [comment]
Gotcha, thanks for clarifying

**Pull request closed without merging**
