### PR TITLE
New package: python3-Flask-Caching-1.8.0

### PR DESCRIPTION
**Pull request by misuchiru03**

### CODE REVIEW

**Comment by Chocimier** [comment]
I feel stuff like this should be installed into virtualenv rather than system.

**Comment by misuchiru03** [comment]
> I feel stuff like this should be installed into virtualenv rather than system.

Any particular reason as to why it should be installed to virtualenv rather than system?

**Comment by ericonr** [comment]
@Chocimier we already have many other Flask packages...

**Comment by Chocimier** [comment]
> we already have many other Flask packages

Oh, right. Then merge. 1.9.0 is out.

**Comment by misuchiru03** [comment]
Flask-Caching released 1.10.1, updated commit

**Pull request closed without merging**
