### PR TITLE
vscode: update to 1.52.1.

### PR DESCRIPTION
**Pull request by shizonic**

### CODE REVIEW

**Comment by ericonr** [comment]
Please don't include `[ci skip]` in the commit message, it isn't necessary any more.

I assume this failure is in CI only? I can try to build locally to be sure.

**Comment by shizonic** [comment]
Alright.

> I assume this failure is in CI only? I can try to build locally to be sure.

Guess so since it was always only CI but I only tested it on x86_64

**Comment by q66** [comment]
looks like an OOM condition, i guess the CI does not have enough memory in it to build...

**Comment by shizonic** [comment]
> looks like an OOM condition, i guess the CI does not have enough memory in it to build...

Yeah this was always the case. Guess this could get merged safely.

**Comment by shizonic** [comment]
Bump to version 1.52.1.

**Pull request merged**
