### PR TITLE
freecad: fix build for vtk9 and musl.

### PR DESCRIPTION
**Pull request by ericonr**
New patch and add libexecinfo to makedepends.

[ci skip]

### CODE REVIEW

**Comment by ericonr** [comment]
This is still WIP, I'm at 65% of the build.

**Comment by ericonr** [comment]
@yopito @Piraty and @Johnnynator 

could you take a look here? It's not working at all under wayland, but testing under Xorg I could get everything to load. `qt5-webkit` seems to be behaving itself (perhaps even close #21617 ?)

**Comment by ahesford** [comment]
Git is mangling the CRLF line endings in `src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp` so, while your patch will apply cleanly if you have the right endings in your tree, the version you push will have them converted to simple newlines. The patch will not work after the lines are mangled.

nn`

**Comment by ericonr** [comment]
**WARNING**: this PR can't be merged via `git-merge-pr`, because github's `.patch` links mangle line endings, and the patch file is half dos, because FreeCAD is a weird project. Use the web interface directly.

**Comment by pullmoll** [comment]
I manually merged your branch here and am building it. I'll take care to push a working patch.

**Pull request closed without merging**
