### PR TITLE
update: ffmpeg to 5.1.2 [Draft]

### PR DESCRIPTION
**Pull request by absrd**
#### Testing the changes
- I tested the changes in this PR: YES

### CODE REVIEW

**Comment by Danoloan10** [comment]
This package has so many dependencies (`grep "depends=.*ffmpeg" srcpkgs/**/template | wc -l` gives 12000+). And this update is quite breaking apparently. How should we go on about verifying the update? Should a new ffmpeg4 package be introduced while transitioning?

**Comment by icp1994** [comment]
Excluding symlinks, we don't even have 12k total templates!

https://github.com/void-linux/void-packages/pull/36315 has significant work regarding this.

**Comment by Danoloan10** [comment]
That's right, didn't think about the symlinks... That PR has some impressive work. There many broken dependencies yet :(

**Comment by Johnnynator** [comment]
The `xrevshlib` tool in xtools can be used to find all the packages that do link against ffmpeg (or one of its subpackages).

**Comment by motorto** [comment]
Would it be acceptable to create an ffmpeg4.4 package and a ffmpeg (that tracks the upstream version) ? 

This would make it possible to update the ffmpeg, and the packages that don't build with 5.0 uses the 4.4 package.

@Johnnynator @paper42

**Comment by milgra** [comment]
Hi, my programs also need ffmpeg5 so it would be nice if we could make this work. What about creating an ffmpeg5 package so nothing breaks? I don't know what to put into common/shlibs in that case though.

**Comment by paper42** [comment]
This PR is failing all checks, is missing a lot of revbumps and didn't get any attention from the author since it was opened. If anyone is interested in continuing this work, please open a new PR and base it on @tibequadorian's work linked above which was way more complete and wasn't just a simple revbump (which this update definitely isn't).

It would be acceptable to have a ffmpeg4 package and switch all packages that don't work with ffmpeg5 to it if:
* there are important packages that don't work and can not be made to work with ffmpeg5 reliably
* at the same time, ffmpeg is updated to v5 and all packages that work with it get rebuilt with ffmpeg (5)

**Comment by zlice** [comment]
> It would be acceptable to have a ffmpeg4 package and switch all packages that don't work with ffmpeg 5 to it if ...

Have an example package of how this works? I see `mlt`(6) and `mlt7` but I'm not seeing where the binary becomes `melt` vs `melt-7` unless it's in makefiles or something.

**Comment by icp1994** [comment]
wlroots

**Comment by zlice** [comment]
What about something with a binary(ies)?

**Comment by icp1994** [comment]
lua

**Comment by paper42** [comment]
> lua

lua uses versioned packages and the lua package is just an transitional empty package pointing to one version for backwards compatibility

**Comment by zlice** [comment]
> lua uses versioned packages ...

will splitting ffmpeg to 4 and 5 with 'alternatives' like lua and php not work then?

**Pull request closed without merging**
