### PR TITLE
apache-kafka: update to 3.0.0

### PR DESCRIPTION
**Pull request by knusbaum**
#### Testing the changes
- I tested the changes in this PR:  **briefly**

### CODE REVIEW

**Comment by CameronNemo** [comment]
Commit message is in the wrong format. Remove the `srcpkgs/` prefix.

**Comment by knusbaum** [comment]
@CameronNemo Whoops!

Somehow I added `srcpkgs/` to the message. I removed that and the period from the commit message.

About the period at the end, it is added by `xbump`, and I noticed it *is* actually specified in the `CONTRIBUTING.md` document here: https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#committing-your-changes

If the period is not wanted, I'm happy to provide a PR for both `xbump` and the `CONTRIBUTING.md` document. let me know.

**Comment by knusbaum** [comment]
Also not sure why the `i686` build is failing. It passes locally with `check` as well.

**Comment by knusbaum** [comment]
Fixed

**Pull request merged**
