### PR TITLE
New package: smart-wallpaper-1.0

### PR DESCRIPTION
**Pull request by Baitinq**
I added a package called smart-wallpaper, which is a script that is able to change your wallpaper automatically depending on if its day/night in your inputted location. It is very useful to me. Thank you (this is my first void package request)

### CODE REVIEW

**Comment by xtraeme** [comment]
Thanks for this new package.

IMHO this software does not need to be packaged... git clone ...; ./foo

You could even download it and run it via a simple script... there's no point in using xbps.

**Comment by Baitinq** [comment]
Yes I thought so but wouldnt it be better if the package manager was informed of all packages/scripts installed?

**Comment by xtraeme** [comment]
It's such a simple script...

**Comment by xtraeme** [comment]
I think many people are adding their toy programming stuff into void-packages because it *could* be accepted... but imho in this case it's so stupid to have a xbps pkg.

**Comment by Baitinq** [comment]
Okay thanks for the feedback, I will close the pull request.

**Pull request closed without merging**
