### PR TITLE
aerc: update to 0.18.1

### PR DESCRIPTION
**Pull request by mgazeel**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-musl)

### CODE REVIEW

**Comment by balejk** [comment]
Thank you for the update.

Let me mention in this context that #45617 is still relevant. Without it the aerc tests suite will not pass on musl based Void and can potentially cause some issues for the users of the `wrap` filter (see the PR description).

**Comment by balejk** [comment]
0.18.1 is [available](https://git.sr.ht/~rjarry/aerc/refs/0.18.1).

**Comment by mgazeel** [comment]
I've updated to `0.18.1`, tested and it still works.

**Comment by balejk** [comment]
It seems you haven't pushed it though.

**Comment by balejk** [comment]
@mgazeel It seems that you have updated the commit message but not the
template, would you please fix that up?

**Comment by mgazeel** [comment]
Ah indeed, sorry for that fixed it

**Comment by balejk** [comment]
Thanks.

0.18.2 came out in the meantime by the way.

**Pull request closed without merging**
