### PR TITLE
New package: linux5.11-5.11.1.

### PR DESCRIPTION
**Pull request by ericonr**
Switch to using 5.11 tarball + minor version patch. Allows the tarball
to be shared across updates.

TODO:
- poison patch <-- `mm/page_poison.c` has changed a lot, no idea if this is still necessary. @q66
- ppcle patch <-- `ppcle-broken-vdso.patch` and `ppcle-ll-compat-sys.patch` appear to not be upstream, but didn't apply cleanly. I assume they are still necessary?

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (x86_64)
- [x] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [x] aarch64-musl
  - [ ] armv7l
  - [ ] armv6l-musl

[ci skip]

### CODE REVIEW

**Comment by eli-schwartz** [comment]
> Switch to using 5.11 tarball + minor version patch. Allows the tarball
> to be shared across updates.

\o/ happy to see it worked for you.

Are you going to update the older release series to do the same too?

**Comment by toluschr** [comment]
What about enabling intel sgx?

**Comment by ericonr** [comment]
Do you know what the config flag is ? I wasn't prompted for it, so it might be hidden behind something else.

**Comment by toluschr** [comment]
@ericonr

It's `CONFIG_*_SGX`

**Comment by ericonr** [comment]
@toluschr it's easy enough to enable, do you feel it's necessary?

**Comment by toluschr** [comment]
> @toluschr it's easy enough to enable, do you feel it's necessary?

AFAIK, some fingerprint sensors might not work correctly without it. However, that knowledge is based off a BIOS message and a non-working fingerprint sensor.

**Comment by ericonr** [comment]
The whole thing looks rather sketchy, so I'm pending towards leaving it disabled, but at the same time it seems most distros are enabling it.

FWIW, I think you'd need to have drivers using SGX first for it to make a difference, which is not happening yet.

**Pull request merged**
