### PR TITLE
google-earth-pro: update to 7.3.3.7721

### PR DESCRIPTION
**Pull request by jason1987d**

### CODE REVIEW

**Comment by jason1987d** [comment]
Is there a better string for license other than "Google"?

**Comment by ericonr** [comment]
`custom:Google`

**Comment by jason1987d** [comment]
With regards to the other failing check... first of all I wonder how this went unnoticed in previous builds. Although I didn't dig too deep, I didn't find where the list of packages in binary-bootstrap gets installed. tar and xz certainly need to be added to them. Or can this be worked around with makedepends ?

**Comment by ericonr** [comment]
Use `bsdtar` instead of `tar`.

**Comment by ericonr** [comment]
Please read https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#review 

You should use `git commit --amend` to avoid needing to squash your commits.

**Comment by jason1987d** [comment]
> Please read https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#review
> 
> You should use `git commit --amend` to avoid needing to squash your commits.

I'll remember to do that in the future. Something is being weird on my end trying to squash commits. It wants me to pull before push every time after git merge --rebase and is creating more commits. Is there a function here to merge + squash commits?

**Comment by ericonr** [comment]
Why arae you trying to do merge??

Just `git rebase -i HEAD~11`, squash everything in the text editor, and force push.

**Comment by ericonr** [comment]
https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec

**Comment by jason1987d** [comment]
> Why are you trying to do merge??
> 
> Just `git rebase -i HEAD~11`, squash everything in the text editor, and force push.

Do I also put "squash" for the original commit? My mistake might have been squashing everything except the first commit "google-earth-pro: update to 7.3.3.7221" if I misunderstood how that worked.

**Comment by jason1987d** [comment]
I squashed almost everything.

**Comment by ericonr** [comment]
You shouldn't squash the original commits, only the ones leading up to it. You should also fix the commit message.

**Comment by jason1987d** [comment]
I believe I have fixed everything, down to one commit, and a commit --amend for the other fixes. Thank you for your patience here.

**Pull request closed without merging**
