### PR TITLE
kbd: update to 2.4.0

### LINKED ISSUE #29478: consolefont issue?
After the recent kernel update to 5.11, I get in my linux console this message during boot:
```
setfont: ERROR kdfontop.c:285 put_font_piofont: PIO_FONT: unsupported font height: 16
```
Although the font looks fine, I'd like to know what is causing the error, and make sure I'm taking advantage of `CONFIG_FONT_TER16x32=y` in our kernel.

Do you know where I should look?

I'm using `grub` as bootloader, and `dracut` to generate initramfs. I haven't set `FONT` in `/etc/rc.conf`.
```
$ xuname
Void 5.11.6_1 x86_64-musl GenuineIntel uptodate hold rrnFFF
```
Thanks.

### PR DESCRIPTION
**Pull request by dkwo**
I built and used it on my `x86_64-musl`.
Incidentally, the update fixes #29478

### CODE REVIEW

**Comment by Chocimier** [comment]
Apply change asked in #28158.

**Comment by dkwo** [comment]
Thanks, I missed that.
Is it enough to just delete that part? or, could you suggest how to proceed?
@ahesford

**Comment by Chocimier** [comment]
Do it like in commit 000010772d9fd4.

**Comment by dkwo** [comment]
@Chocimier How does it look?

**Review by ahesford — APPROVED** [review]
Looks fine to me.

**Comment by Chocimier** [comment]
please also remove srcpkgs/kbd-data symlink.

**Pull request merged**
