### PR TITLE
xbps-src: redirect various error msg to stderr

### PR DESCRIPTION
**Pull request by zdtcd**
ref: https://github.com/void-linux/void-packages/issues/12907

### CODE REVIEW

**Comment by Gottox** [comment]
:+1: please rebase

I'm thinking about replacing these calls with `msg_error`, but I'm not perfectly sure if everything is initialized properly.

**Comment by zdtcd** [comment]
Lemme trace those code to check if we can replace them with msg_error or not.

On July 18, 2019 6:33:19 AM UTC, Enno Boland <notifications@github.com> wrote:
>:+1: please rebase
>
>I'm thinking about replacing these calls with `msg_error`, but I'm not
>perfectly sure if everything is initialized properly.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/void-linux/void-packages/pull/12962#issuecomment-512684223

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by zdtcd** [comment]
We can't use msg_error. They won't be available until line #680

**Comment by Gottox** [comment]
Ok, leave it as it is.

**Pull request merged**
