### PR TITLE
flatpak: update to 1.10.1

### PR DESCRIPTION
**Pull request by UsernameRandomlyGenerated**
Edit: 1.10.0 is stable so I'm doing that one instead.

### CODE REVIEW

**Comment by ericonr** [comment]
Could you try to look into the test failures?

Has it been working well for you, as well?

**Comment by UsernameRandomlyGenerated** [comment]
Yeah I'll try to do something about failures, though it built without problems for me on x86_64 musl.

I've been running 1.10 since release and it's working fine. Also no problems in any of the flatpak apps that I use.

**Comment by UsernameRandomlyGenerated** [comment]
Looks like it's related to https://github.com/flatpak/flatpak/issues/267 for which Arch uses fix like this
`sed -i '/locale\/C\./d' tests/make-test-runtime.sh`

that makes tests run but then it tries to run tests that require bubblewrap (which it shouldn't) so I'll have to look into it a little more

**Comment by ericonr** [comment]
> that makes tests run but then it tries to run tests that require bubblewrap (which it shouldn't)

Why? Do they not work?

**Comment by UsernameRandomlyGenerated** [comment]
Yeah, if I understand correctly it's related to https://github.com/flatpak/flatpak/commit/752eac6859ba2d38a4d89c88ad90021e8a1d31cd

**Comment by sgn** [comment]
I changed line 91 of `tests/make-test-runtime.sh` to:
```sh
cp -r /usr/lib/locale/* ${DIR}/usr/lib/locale
```
and
```sh
checkdepends+=" gnupg2 attr-progs"
```
reduce the failure from 15 to 1 on glibc host.

**Comment by ericonr** [comment]
1.10.1 is out

**Comment by UsernameRandomlyGenerated** [comment]
> I changed line 91 of `tests/make-test-runtime.sh` to:
> 
> ```shell
> cp -r /usr/lib/locale/* ${DIR}/usr/lib/locale
> ```
> 
> and
> 
> ```shell
> checkdepends+=" gnupg2 attr-progs"
> ```
> 
> reduce the failure from 15 to 1 on glibc host.

Though musl needs different fix. I see that error is related to FUSE, later test that needs it is skipped with 

`No cap_sys_admin in bounding set, can't use FUSE`

So I don't think much can be done about the last error.

**Pull request closed without merging**
