### PR TITLE
pinebookpro-kernel: update to 5.14.0

### PR DESCRIPTION
**Pull request by CameronNemo**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

[skip CI]

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [ ] I built this PR locally for my native architecture, (ARCH-LIBC)
- [x] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [x] aarch64
  - [ ] aarch64-musl
  - [ ] armv7l
  - [ ] armv6l-musl

### CODE REVIEW

**Comment by ericonr** [comment]
Ok to ping possible testers?

**Comment by CameronNemo** [comment]
@ericonr sure or I can go ahead and ping them.

@Skirmisher @Johnnynator @q66 @jcgruenhage @renatoaguiar

**Comment by Skirmisher** [comment]
Already planning to test this tomorrow, along with uboot etc.

Do you know the status of the remaining patches in this tree/know of any others that are pertinent?

**Comment by CameronNemo** [comment]
@Skirmisher the last two kernel patches, the dts changes, have been upstreamed but did not make it into 5.14. The other patches are still relevant AFAIK. Only other patches floating around I have seen are the extcon stuff to get video output working on the USB type-c port. Those are fairly invasive and will never be upstreamed, so I have avoided including them.

**Comment by Skirmisher** [comment]
Makes sense.

I tested this kernel and your uboot/atf bump, with the following patches added:
- uboot
  - [fix panel reset](https://gitlab.manjaro.org/manjaro-arm/packages/core/uboot-pinebookpro/-/blob/master/0001-PBP-Fix-Panel-reset.patch)
  - [change boot order](https://gitlab.manjaro.org/manjaro-arm/packages/core/uboot-pinebookpro/-/blob/master/0002-Correct-boot-order-to-be-USB-SD-eMMC.patch) (in addition to SD/eMMC swap like your existing patch, it puts USB first so it can also be used to override eMMC/NVMe without taking the computer apart)
- atf
  - [attribute fix](https://gitlab.manjaro.org/manjaro-arm/packages/core/uboot-pinebookpro/-/blob/master/0002-fix-rockchip-rk3399-fix-dram-section-placement.patch) (apparently this breaks GCC 11, but the code is wrong in the first place; no functionality change)

U-boot framebuffer console works, but when it hands off to the kernel, it doesn't handle the LCD properly, and it flickers brightly several times before the kernel gets a handle on it. It's...pretty bad.

Other than that, the kernel seems to come up fine, although I did notice that when I got dropped into a rescue shell (for unrelated reasons) the keyboard didn't appear to work at all, though it works once I got into the booted system. I wasn't able to test much further than that, because sddm didn't start and trying to run Xorg would hang the system sometimes, in addition to strange issues like Fn-Alt-PrintScreen not working for magic sysrq combos. I don't have time to test a fresh install tonight.

**Comment by Johnnynator** [comment]
The keyboard not working in dracut is quite critical, I haven't looked into the chnaged config, is it possible that the module changed from built-in to module?

**Comment by CameronNemo** [comment]
>fix panel reset

Not sure what this does / how to reproduce the issue.

>in addition to SD/eMMC swap like your existing patch, it puts USB first so it can also be used to override eMMC/NVMe without taking the computer apart

We should probably just switch to that patch, it is much more common.

>U-boot framebuffer console works, but when it hands off to the kernel, it doesn't handle the LCD properly, and it flickers brightly several times before the kernel gets a handle on it. It's...pretty bad.

Yeah I noticed that on both 5.10 and 5.14 with the new u-boot. It was not as bad with 5.10 from what I could tell, but it still had a noticeable flicker.

Is this specific to us/Void or is it also the case for other distros?

>I did notice that when I got dropped into a rescue shell (for unrelated reasons) the keyboard didn't appear to work at all

>I haven't looked into the changed config, is it possible that the module changed from built-in to module?

I did not change any built ins to modules (at least purposefully...). I wonder if it happens on both 5.10 and 5.14, or just on 5.14.

>strange issues like Fn-Alt-PrintScreen not working for magic sysrq combos

I'll try to test those if I have a minute.

**Comment by Skirmisher** [comment]
> > fix panel reset
> 
> Not sure what this does / how to reproduce the issue.

I haven't seen it either, but the commit message says it's something to do with warm reboots, and seems to work around it by basically power-cycling the panel regulator.

> > U-boot framebuffer console works, but when it hands off to the kernel, it doesn't handle the LCD properly, and it flickers brightly several times before the kernel gets a handle on it. It's...pretty bad.
> 
> Yeah I noticed that on both 5.10 and 5.14 with the new u-boot. It was not as bad with 5.10 from what I could tell, but it still had a noticeable flicker.
> 
> Is this specific to us/Void or is it also the case for other distros?

I can't imagine why it would be specific to Void, unless a config option is somehow the culprit, or someone has come up with a patch I didn't see. But I haven't checked on other distros specifically, or asked other users.

> > I did notice that when I got dropped into a rescue shell (for unrelated reasons) the keyboard didn't appear to work at all
> 
> > I haven't looked into the changed config, is it possible that the module changed from built-in to module?
> 
> I did not change any built ins to modules (at least purposefully...). I wonder if it happens on both 5.10 and 5.14, or just on 5.14.

I did confirm that all the relevant drivers (ehci_hcd/etc., usbhid, hid-generic) are still built in, which is what made it weird. But I also haven't tested it again, since changing the kernel cmdline is kind of a manual process.

> > strange issues like Fn-Alt-PrintScreen not working for magic sysrq combos
> 
> I'll try to test those if I have a minute.

It might well be a keyboard firmware issue too, in which case it has nothing to do with Void. Maybe I'll try reverting to the stock firmware (which has its own issues...) and see if that changes its behavior.

**Comment by CameronNemo** [comment]
@Skirmisher Some follow up:

* the missing module for dracut was `fusb302`. after loading that, the keyboard and other USB inputs registered. so you need to add `add_drivers+=" fusb302 "` to your dracut config. not sure why...
* magic sysrq combos did not work on 5.10 or 5.14
* other users report the same display glitches with graphical u-boot (https://old.reddit.com/r/PINE64official/comments/pjaql4/graphical_uboot_do_you_notice_flickering_when/hbvgumk/)

**Pull request closed without merging**
