### PR TITLE
New package: find-cursor-0.0.0.20180321

### PR DESCRIPTION
**Pull request by biopsin**
..highlight the cursor position in X.

### CODE REVIEW

**Comment by maxice8** [comment]
Needs upstream to tag a release

**Comment by biopsin** [comment]
damnit, I knew it, even simplest PR..
I'll see what I can do, thanks for the comment maxice8 :thumbsup:

**Comment by cr6git** [comment]
> Needs upstream to tag a release

I proposed [#2816](https://github.com/void-linux/void-packages/pull/2816) as well... you're talking nonsense.

**Comment by maxice8** [comment]
On Mon, Sep 17, 2018 at 10:40:30AM -0700, cr6git wrote:
> > Needs upstream to tag a release
> 
> I proposed [#2816](https://github.com/void-linux/void-packages/pull/2816) as well... you're talking nonsense.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/2844#issuecomment-422106040

1. It is not a hard requirement but it is ***MUCH*** better to have an upstream release and have upstream tag releases.
2. It is not nonsense it is just good practice.

**Comment by Carpetsmoker** [comment]
Hello, this is upstream.

I've generally avoided tagging releases for such small/trivial programs, and prefer to consider every commit to master a "release".

I could add a tag I guess; but I don't think it adds much value here, and it's one more thing that could potentially be screwed up or forgotten. My project isn't Firefox or something, it's just a simple 300-line program.

**Comment by Gottox** [comment]
@cr6git Note, that we avoid non-release versions whenever possible. There are very few exceptions, but even then there was a reason to do so *and* there was a discussion beforehand. The default case is described in ["Getting your packages into Void by yourself" in CONTRIBUTING.md](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#getting-your-packages-into-void-by-yourself):
> Please note that we do not accept any packages containing non-release versions such as specific git- or svn-revisions anymore.

**Again**: Please be more careful when merging packages.

**Comment by Vaelatern** [comment]
@cr6git It's Void policy to wait for upstream to tag a release wherever possible. Void policy exists to improve the quality of the packages tree. This package should not have been merged as-is.

**Comment by Carpetsmoker** [comment]
Alright, that makes sense @Duncaen; thanks for explaining.

I added the `v1.0` tag to the latest commit.

**Comment by cr6git** [comment]
> 2. It is not nonsense it is just good practice.

@maxice8 you're right, of course.

> Again: Please be more careful

@Gottox yeah, I will do my best.

**Pull request merged**
