### PR TITLE
rust: update to 1.34.0.

### PR DESCRIPTION
**Pull request by jnbr**

### CODE REVIEW

**Comment by jnbr** [comment]
I tested on some architectures, seems to be fine and fixes #9973.

I intend to merge this PR as is, with the previous release for bootstrapping.
IMO, this makes updates smoother and more sense in general.
@q66 please provide the necessary ppc64* distfiles so we have them ready for the next release, I will do it for x86_64-musl.

**Comment by q66** [comment]
Okay. I'll upload them this weekend

**Comment by jnbr** [comment]
x86_64-musl distfiles are here: https://jnbr.me/distfiles/

**Comment by jnbr** [comment]
@Gottox please mirror these files on void servers:

```
https://void-ppc64.octaforge.org/distfiles/cargo-0.35.0-powerpc64-unknown-linux-musl.tar.xz
https://void-ppc64.octaforge.org/distfiles/cargo-0.35.0-powerpc64le-unknown-linux-gnu.tar.xz
https://void-ppc64.octaforge.org/distfiles/cargo-0.35.0-powerpc64le-unknown-linux-musl.tar.xz
https://void-ppc64.octaforge.org/distfiles/rust-std-1.34.0-powerpc64-unknown-linux-musl.tar.xz
https://void-ppc64.octaforge.org/distfiles/rust-std-1.34.0-powerpc64le-unknown-linux-musl.tar.xz
https://void-ppc64.octaforge.org/distfiles/rustc-1.34.0-powerpc64-unknown-linux-musl.tar.xz
https://void-ppc64.octaforge.org/distfiles/rustc-1.34.0-powerpc64le-unknown-linux-musl.tar.xz
https://jnbr.me/distfiles/cargo-0.35.0-x86_64-unknown-linux-musl.tar.xz
https://jnbr.me/distfiles/rust-std-1.34.0-x86_64-unknown-linux-musl.tar.xz
https://jnbr.me/distfiles/rustc-1.34.0-x86_64-unknown-linux-musl.tar.xz
```

**Pull request closed without merging**
