### PR TITLE
enlightenment: update to 0.24.2

### PR DESCRIPTION
**Pull request by make-file**
since `signal.h` is included  into `e_util_suid.h` so it would be safe to remove patch

### CODE REVIEW

**Comment by ericonr** [comment]
You're missing the actual update from this PR.

**Comment by make-file** [comment]
> You're missing the actual update from this PR.

sorry :sweat_smile: template added

**Comment by q66** [comment]
squash your stuff

**Comment by make-file** [comment]
why, did i do anything wrong?

**Comment by q66** [comment]
one commit per template, that's the rule

**Comment by make-file** [comment]
sorry, i didn't know about that. i must close this PR and create another one?

**Comment by q66** [comment]
no, just rebase and squash your commits, then force-push your branch

**Comment by ericonr** [comment]
Hm, you're still missing the template changes.

**Comment by make-file** [comment]
oh, sorry. i've added template now.

**Comment by make-file** [comment]
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file src/bin/e_util_suid.h.rej

**Comment by make-file** [comment]
```
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file src/bin/e_util_suid.h.rej
```

**Comment by Anachron** [comment]
I'm guessing you dont need the patch anymore since it has been included upstream.

**Comment by make-file** [comment]
thanks a lot. :facepalm:

**Comment by ericonr** [comment]
Ok, this completely locks up on musl when launched as `enlightenment_start` and I right click something. 0.24.1 works fine.

**Comment by ericonr** [comment]
Thanks @q66 for the suggested fix, it was necessary to update efl itself as well.

Make another commit to update `efl`. It should include these changes:

```
diff --git a/srcpkgs/efl/template b/srcpkgs/efl/template
index caba1145ab..a8b26fff25 100644
--- a/srcpkgs/efl/template
+++ b/srcpkgs/efl/template
@@ -1,7 +1,7 @@
 # Template file for 'efl'
 pkgname=efl
-version=1.24.3
-revision=2
+version=1.24.4
+revision=1
 build_style=meson
 configure_args="
  -Dembedded-lz4=false
@@ -52,7 +52,7 @@ license="LGPL-2.1-only"
 homepage="https://enlightenment.org"
 changelog="https://git.enlightenment.org/core/efl.git/plain/NEWS"
 distfiles="https://download.enlightenment.org/rel/libs/efl/efl-${version}.tar.xz"
-checksum=de95c6e673c170c1e21382918b122417c091c643e7dcaced89aa785529625c2a
+checksum=617e6b29d2478259acac72e2867d1908249c01a323ff3284948e999d4787f901
 
 if [ "$XBPS_CHECK_PKGS" ]; then
 	configure_args+=" -Dbuild-tests=true"
```

**Comment by ericonr** [comment]
Pushed the efl update myself. Merging now.

**Comment by make-file** [comment]
thank you.

**Pull request merged**
