### PR TITLE
libsigrok: fix missing udev rules

### LINKED ISSUE #23580: [libsigrok] 61-libsigrok-uaccess.rules udev rule doesn't work correctly
### System

* xuname:  
  *`Void 5.4.50_1 x86_64 GenuineIntel notuptodate rrrmFFFFFFFFFFFFFF`
* package:  
  *`libsigrok-0.5.2_1`

### Expected behavior
Sigrok compatible devices can be accessed without root access.

### Actual behavior
Attempting to access a Sigrok compatible device without root access will result in:
```
λ › sigrok-cli -d saleae-logic16 --scan                                                 ~
sr: ezusb: failed to open device: LIBUSB_ERROR_ACCESS.
sr: saleae-logic16: Firmware upload failed, name saleae-logic16-fx2.fw.
The following devices were found:
saleae-logic16 - Saleae Logic16 with 16 channels: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
```
### Steps to reproduce the behavior
* Install `libsigrok` and `sigrok-cli`
* Run `sigrok-cli --scan`

### PR DESCRIPTION
**Pull request by 0x5c**
Fixes #23580
Closes #23581 (obsoletes the PR)

#### Testing the changes
- I tested the changes in this PR: **YES**

### ~~**This PR is dependent on #36238 being merged.**~~

### CODE REVIEW

**Comment by Duncaen** [comment]
Please no `INSTALL.msg` for this, if this needs documentation, add a `README.void` instead.

**Comment by q66** [comment]
i don't really like this idea, IMO we should add plugdev to default groups in base-files (in debian it's gid 46, here we could simply add it among the base groups (after input, before nogroup) and for existing setups, put a groupadd in an upgrade hook)

**Comment by 0x5c** [comment]
> i don't really like this idea, IMO we should add plugdev to default groups in base-files (in debian it's gid 46, here we could simply add it among the base groups (after input, before nogroup) and for existing setups, put a groupadd in an upgrade hook)
> 
> either that, or change the udev files here to use another, existing group

That would be cleaner it seems and would allow cleanup in *many* templates, but can this be done without breaking current installations? The `plugdev` group already exist with a different GID for many users, will the change take that into account?

**Comment by 0x5c** [comment]
I realised that the original fix in this PR was bogus resulting from improper testing.

With #36238 taking care of adding the plugdev group, we still need to have the package install the missing udev rules. This PR has been updated to do that.

This PR is dependent on #36238 being merged.

**Pull request merged**
