### PR TITLE
Split python3-dbus-devel

### PR DESCRIPTION
**Pull request by sgn**
To avoid unnecessary python 2 when doing development.

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Review by ericonr — APPROVED** [review]
I like the idea, but I think we could consider moving to `python3-dbus` *only* as well.

At least https://github.com/alessio/laditools and http://idjc.sourceforge.net/install_build.html can be updated to python 3.

**Comment by sgn** [comment]
> I like the idea, but I think we could consider moving to `python3-dbus` _only_ as well.

I'm worry that someone who installed `python-dbus-devel` may found this conflicts, so transitional is required, while we're at it, why not make it works by depending on python-dbus :-)

> 
> At least https://github.com/alessio/laditools and http://idjc.sourceforge.net/install_build.html can be updated to python 3.

I didn't check, but moving to python3 sounds like a good move.

**Comment by ericonr** [comment]
https://github.com/muflone/gespeaker and dispcalGUI might be stuck in the past, unfortunately. wicd too, but I think there was a PR...

**Comment by ericonr** [comment]
Sorry, typo, laditools is abandoned, so I think we can remove as a package, but idjc can be updated. I think we should leave the py 2 version as well for now, then. :(

**Comment by sgn** [comment]
I guess it's fine to merge?

**Comment by Chocimier** [comment]
No revbumps of revdeps?

**Comment by sgn** [comment]
No, we only change hostmakedepends, the final dependencies is still the same.

**Pull request merged**
