### PR TITLE
[RFC] common/tags: create file.

### PR DESCRIPTION
**Pull request by ericonr**
Tags taken from relevant "Facets" in
https://packages.debian.org/about/debtags

Fixes (?) #22191 

Needs discussion regarding:

- will there be an xlint?
- how many tags are needed?
- what explanations should we have for each tag?
- how would we limit tags to those in the list?
- does the current build infrastructure also deal with tags correctly?
- is this the correct file to create?
- and, of course, should we commit to tags?

### CODE REVIEW

**Comment by st3r4g** [comment]
my 2 cents: why not just decide on a list of standard "keywords" to use in `short_desc` for some categories, like `game` for games, `web browser` for web browsers, etc... this will improve `short_desc` instead of introducing a separate tag field that needs to be maintained as well.
Each keyword should appear in `short_desc` if and only if the package belongs to the associated category.

**Comment by ericonr** [comment]
@st3r4g I don't really like that, because I tend to take `short_desc` straight from upstream.

**Comment by hippi777** [comment]
hi there! :)

whats the purpose of "culture", "special", and "suite"?

is there a better name (maybe a wider definition) for "iso15924"? actually its exact enough, but not really self-descriptive, while im not sure, but i think that this category could be expanded to all the similar things, but still not to "i18n", that and/or "l10n" could get an own category, or maybe all could be merged...

if there is "x11", then i miss "wayland"

"sound" makes me miss something like "video"/"multimedia" stuffs, but i dont have an exact suggestion here

is "interface" for desktop environments? it could be good to find tools related to a given desktop environment, but would that mean that all the gtk and qt apps should automatically belong to gnome and kde? not really straightforward... themes are basically straightforward, maybe they could get a tag, dunno...

"gui", "tui", "cli"? straightforward and nice to have! :)

programming languages, and their engines and libs (when straightforward)? this could be nice :) otherwise im not really enough deep into the naming convention, but ive seen that it covers this more or less

i think thats all i could think about :D otherwise i would be interested in the tags that u, folks, could come up with, like that u wish for, but have anything against it... just for brainstorming, to polish them up, and to see where this could lead in the long run...

@st3r4g: i think that could become messy to include all the necessary keywords and only those, while this opens up nice possibilities without hackish solutions, and it doesnt require much maintenance, and can be done progressively...

**Comment by Anachron** [comment]
Not sure if `iso15924` is a joke or not, but the others look useful.

I'd probably replace `sound` with media, drop `uitoolkit` and add wayland.

Also whats `special` thought for?

**Pull request closed without merging**
