### PR TITLE
hexchat: update to 2.16.2.

### PR DESCRIPTION
**Pull request by caughtquick**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by classabbyamp** [comment]
@0x5c

**Comment by caughtquick** [comment]
For context, this is the last update Hexchat should receive

**Comment by 0x5c** [comment]
While package update PRs from new contributors are generally appreciated, please don't do that for recently released versions of packages with active maintainers. Especially if the update is less than ~1month and you answer "briefly" to the question about testing.

Instead, target packages that are orphaned, and/or have had an update available for months; other than core packages like glibc/musl/gcc/llvm/rust/etc, those updates tend to be easy and very appreciated. Sometimes those packages don't get the attention they should have.
If you build a history of contribution to void, you could even [adopt](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#adopting-a-template) one of them and [submit new packages](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#creating-a-new-template).

As for this update specifically, there's no rush; it's not like there'd be a new update two days after merging this one. I can take the time to properly test the update and gather patches to fix bugs that we normally would rely on being fixed upstream.

**Comment by caughtquick** [comment]
Sounds good @0x5c, won't do that in the future

**Comment by 0x5c** [comment]
> should I close this PR?

Yes, it'll prevent it being merged accidentally

**Pull request closed without merging**
