### PR TITLE
pcmanfm: update to 1.3.2. and adopt.

### PR DESCRIPTION
**Pull request by uw2021**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Would be nice to update libfm and libfm-extra as well.

**Comment by uw2021** [comment]
> Would be nice to update libfm and libfm-extra as well.

Done - #28619 and #28620.

**Comment by ericonr** [comment]
Please do them in this PR. Especially libfm and libfm-extra should be in exactly the same PR, as mentioned in their templates.

**Comment by uw2021** [comment]
> Please do them in this PR. Especially libfm and libfm-extra should be in exactly the same PR, as mentioned in their templates.

I saw that but had never pushed an update like that before, do I just force push those two template changes to this branch?

**Comment by ericonr** [comment]
Yes, with a commit for each one. The PR will have 3 commits.

**Comment by ericonr** [comment]
> Yes, with a commit for each one. The PR will have 3 commits.

**Pull request closed without merging**
