### PR TITLE
gnome-maps: update to 46.11.

### PR DESCRIPTION
**Pull request by fanyx**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by cinerea0** [comment]
It looks like version 46.11 is now available.

**Comment by fanyx** [comment]
updated to 46.11 ^^

**Comment by fanyx** [comment]
gnome servers hate our GH containers...

**Comment by fanyx** [comment]
`i686` builds fine on my local machine.

**Pull request merged**
