### PR TITLE
amfora: update to 1.7.1

### PR DESCRIPTION
**Pull request by Eluminae**

### CODE REVIEW

**Comment by paper42** [comment]
What do you think about installing contrib/themes/*.toml?

**Comment by Eluminae** [comment]
I think this is not the current topic.

**Comment by ericonr** [comment]
> I think this is not the current topic.

What do you mean?

**Comment by Eluminae** [comment]
I mean that this MR is about upgrading the software version.

Pausing the merge to think about it is could be done in any other merge request.

Anyway, I took time to reply two time on this subject in a row so I'll take this turn to give my thought.

contrib configurations are not required for the targeted release and, for me, are present in the amfora repository for discovery reason. I don't see the point on including them in the voidlinux package.

**Comment by Eluminae** [comment]
> in any other merge request

s/in any other merge request/in any dedicated merge request/

**Comment by ericonr** [comment]
The point against doing it in any other MR, when it could be done here, is that  we avoid

- wasting builder time
- wasting user and server bandwidth with multiple updates
- wasting time by having to review yet another PR

 I'm mostly in favor of packaging the themes, since being installed in your system is much more discoverable than being only in the upstream repo. But I don't use the package, so I don't think my opinion here matters too much.

Also, please decrease the revision in the template, it should be reset to 1 on updates.

**Comment by paper42** [comment]
> contrib configurations are not required for the targeted release and, for me, are present in the amfora repository for discovery reason. I don't see the point on including them in the voidlinux package.

Themes often change with new versions when a new element is added to the UI, so I think they should be included in the package even if just in /usr/share/examples/.

**Comment by Eluminae** [comment]
> Also, please decrease the revision in the template, it should be reset to 1 on updates.

done

> Themes often change with new versions when a new element is added to the UI, so I think they should be included in the package even if just in /usr/share/examples/.

done

**Comment by ericonr** [comment]
Thanks!

**Pull request merged**
