### PR TITLE
Firefox 80

### PR DESCRIPTION
**Pull request by jnbr**
Build passes for all our official supported targets.
Tested on x86_64-musl with pulseaudio.

@pullmoll are you ok with the nasm revert?

### CODE REVIEW

**Comment by q66** [comment]
your reverts line is wrong

**Comment by jnbr** [comment]
> your reverts line is wrong

thanks, fixed

**Comment by pullmoll** [comment]
I have no clue. Guess there is a problem with the most recent nasm update? Do whatever is required to build firefox.

**Comment by jnbr** [comment]
> I have no clue. Guess there is a problem with the most recent nasm update?

Yes, looks like it. There is little information for now, except that it breaks building dav1d: https://bugzilla.nasm.us/show_bug.cgi?id=3392715

**Pull request merged**
