### PR TITLE
couchdb: update to 3.0.0

### PR DESCRIPTION
**Pull request by pullmoll**
This does not yet seem to run so I need help.

I need this to review couchdb for taking part in a paid work environment.

### CODE REVIEW

**Comment by jnbr** [comment]
Building the template in the current state results in a mostly empty package.
I think I got a step further by setting `make_build_target="release"`.

**Comment by pullmoll** [comment]
@jnbr Yeah, this at least gives me a `/usr/lib/couchdb/couchdb/bin/couchdb` which can be symlinked to `/usr/bin/couchdb`. Thanks!

**Comment by pullmoll** [comment]
I cannot get it to start up right. After installing I edited `/etc/couchdb/local.ini` to set an adimistrator account, i.e. `admin = password`, and log level to debug `[log] level = debuug`. Then I ran `sudo -i -u couchdb /usr/lib/couchdb/bin/couchdb` and this is the output:
```ini
Configuration Settings:
  [admins] admin="**********"
  [attachments] compressible_types="text/*, application/javascript, application/json, application/xml"
  [attachments] compression_level="8"
  [chttpd] backlog="512"
  [chttpd] bind_address="127.0.0.1"
  [chttpd] max_db_number_for_dbs_info_req="100"
  [chttpd] port="5984"
  [chttpd] prefer_minimal="Cache-Control, Content-Length, Content-Range, Content-Type, ETag, Server, Transfer-Encoding, Vary"
  [chttpd] require_valid_user="false"
  [chttpd] server_options="[{recbuf, undefined}]"
  [chttpd] socket_options="[{sndbuf, 262144}, {nodelay, true}]"
  [cluster] n="3"
  [cluster] q="2"
  [cors] credentials="false"
  [couch_httpd_auth] allow_persistent_cookies="true"
  [couch_httpd_auth] auth_cache_size="50"
  [couch_httpd_auth] authentication_db="_users"
  [couch_httpd_auth] authentication_redirect="/_utils/session.html"
  [couch_httpd_auth] iterations="10"
  [couch_httpd_auth] require_valid_user="false"
  [couch_httpd_auth] timeout="600"
  [couch_peruser] database_prefix="userdb-"
  [couch_peruser] delete_dbs="false"
  [couch_peruser] enable="false"
  [couchdb] attachment_stream_buffer_size="4096"
  [couchdb] changes_doc_ids_optimization_threshold="100"
  [couchdb] database_dir="./data"
  [couchdb] default_engine="couch"
  [couchdb] default_security="admin_only"
  [couchdb] file_compression="snappy"
  [couchdb] max_dbs_open="500"
  [couchdb] max_document_size="8000000"
  [couchdb] os_process_timeout="5000"
  [couchdb] single_node="true"
  [couchdb] view_index_dir="./data"
  [couchdb_engines] couch="couch_bt_engine"
  [csp] enable="true"
  [feature_flags] partitioned||*="true"
  [httpd] allow_jsonp="false"
  [httpd] authentication_handlers="{couch_httpd_auth, cookie_authentication_handler}, {couch_httpd_auth, default_authentication_handler}"
  [httpd] bind_address="127.0.0.1"
  [httpd] enable_cors="false"
  [httpd] enable_xframe_options="false"
  [httpd] max_http_request_size="4294967296"
  [httpd] port="5986"
  [httpd] secure_rewrites="true"
  [httpd] socket_options="[{sndbuf, 262144}]"
  [indexers] couch_mrview="true"
  [ioq] concurrency="10"
  [ioq] ratio="0.01"
  [ioq.bypass] compaction="false"
  [ioq.bypass] os_process="true"
  [ioq.bypass] read="true"
  [ioq.bypass] shard_sync="false"
  [ioq.bypass] view_update="true"
  [ioq.bypass] write="true"
  [log] file="/var/log/couchdb/couch.log"
  [log] level="debug"
  [log] writer="file"
  [purge] users_db_security_editable="false"
  [query_server_config] os_process_limit="100"
  [query_server_config] reduce_limit="true"
  [replicator] connection_timeout="30000"
  [replicator] http_connections="20"
  [replicator] interval="60000"
  [replicator] max_churn="20"
  [replicator] max_jobs="500"
  [replicator] retries_per_request="5"
  [replicator] socket_options="[{keepalive, true}, {nodelay, false}]"
  [replicator] ssl_certificate_max_depth="3"
  [replicator] startup_jitter="5000"
  [replicator] verify_ssl_certificates="false"
  [replicator] worker_batch_size="500"
  [replicator] worker_processes="4"
  [smoosh.ratio_dbs] min_priority="2.0"
  [smoosh.ratio_views] min_priority="2.0"
  [ssl] port="6984"
  [uuids] algorithm="sequential"
  [uuids] max_count="1000"
  [vendor] name="The Apache Software Foundation"
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,mem3,{{shutdown,{failed_to_start_child,mem3_nodes,{{case_clause,{not_found,no_db_file}},[{mem3_util,ensure_exists,1,[{file,\"src/mem3_util.erl\"},{line,270}]},{mem3_nodes,initialize_nodelist,0,[{file,\"src/mem3_nodes.erl\"},{line,94}]},{mem3_nodes,init,1,[{file,\"src/mem3_nodes.erl\"},{line,45}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,374}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,249}]}]}}},{mem3_app,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,mem3,{{shutdown,{failed_to_start_child,mem3_nodes,{{case_clause,{not_found,no_db_file}},[{mem3_util,ensure_exists,1,[{file,"s

Crash dump is being written to: erl_crash.dump...
```

Perhaps someone can tell what I'm doing wrong or whether there may be a problem with `erlang`? I'm stuck here and ran out of ideas.

**Comment by pullmoll** [comment]
Finally I got it up and running.
Please review and, if you think it's okay, also merge.

**Comment by pullmoll** [comment]
I broke it again. It seems couchdb is very flimsy about access rights to directories it wants to access. Also reading and interpreting `erl_crash.dump` files is an entirely new experience - in case you want to see something new :-)

Now I'm trying to find out which of the recent changes broke it again. It certainly has to do with me trying to make the actual databases be stored below `/var/lib/couchdb/data` instead of `/usr/lib/couchdb/data`.

**Comment by pullmoll** [comment]
:sos: :axe: :bomb: :brain: :building_construction: :exploding_head: ... anyone willing to help? @arete?

**Comment by pullmoll** [comment]
Noone's interested thus closing.

**Pull request closed without merging**
