### PR TITLE
[WIP] Jupyter

### PR DESCRIPTION
**Pull request by ahesford**
This is an attempt to bring all of the jupyter stuff up to date. Currently, `jupyter notebook` works as expected, but `jupyter console` is is broken. This needs to be looked at further.

The `python3-jupyter` meta should be bumped too. I wonder whether it is possible to fold the meta into one of the dependencies as a subpackage without introducing build cycles.

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by dkwo** [comment]
Would it make sense to add `jupyterlab` https://github.com/jupyterlab/jupyterlab at this point?

It's the next-generation user interface for Jupyter offering all the familiar building blocks of the classic Notebook, which it will eventually replace. Moreover it's adding nice features like RTC or cell output update.

I would be willing to help.

**Comment by ahesford** [comment]
Sure, add a JupyterLab package.

**Comment by dkwo** [comment]
I will rely on some updates that you made. Should I still open a new PR, or is there a way to add stuff here?

**Review by dkwo — CHANGES_REQUESTED** [review]
Do you mind adding `python3-argon2` as a dependency?

**Comment by ahesford** [comment]
I think the easiest thing is for you to pull this branch into your own fork, add JupyterLab as appropriate and PR the whole thing. Tag me and I'll close this when that happens.

As for the `argon2` dependency: it seems to be a hard dependency of `notebook`, so adding it is appropriate. You can change that in your fork.

**Comment by ahesford** [comment]
Superseded by #30873.

**Pull request closed without merging**
