### PR TITLE
telegram-desktop: update to 1.3.9.

### PR DESCRIPTION
**Pull request by Johnnynator**
Only tested on x86_64-musl.
I also switched from the debian patchset to the gentoo patchset which should make it possible to enable cross builds. (Currently testing locally if I can get it working)
Edit: Cross build to armv7l and aarch64 succeed. Not tested if they actually work.

~~Edit2: As always i686 is broken for now. Should be an easy fix.~~
Edit3: fixed i686

### CODE REVIEW

**Comment by Johnnynator** [comment]
@maxice8 Can you test and verify that it runs fine on x86_64? (And ofc merge it if it is OK :smile: )

**Comment by maxice8** [comment]
the .application file in /usr/share/applications is executable for some reason.

also it works, but i don't want to merge stuff until the musl builders are up again.

**Comment by Johnnynator** [comment]
OK. Thx for noticing the permission issue. Will fix it later.

**Comment by maxice8** [comment]
is it done ?

**Comment by Johnnynator** [comment]
I think so. The .desktop permission is fixed.

**Pull request merged**
