### PR TITLE
rpi3-base, rpi3-firmware: remove

### PR DESCRIPTION
**Pull request by m3tav3rse**
rpi3-* packages are outdated and not used anywhere.

### CODE REVIEW

**Comment by Piraty** [comment]
Those used to be used by the rpi3 images.
By now they're not used, but people might still have installations based on the old rpi3-base.

So here it's probably best to not push an empty transitional package or at least properly test if making the transitional package depend on the new mechanic work as expected (rpi3-base  depends on mainline kernel package, new installs use rpi-kernel).
I think removing the templates will work, but a transition might be worth the effort.
@m3tav3rse could you test this upgrade path?

**Comment by xtraeme** [comment]
Hmmm

**Comment by m3tav3rse** [comment]
I'm not sure how I could test it.

**Comment by Piraty** [comment]
use an old image which still has the old rpi3-base, make it a transitional package (+ make it depend on the required successor packages), run update, reboot

**Comment by m3tav3rse** [comment]
@Piraty unfortunately I've lost acces to my rpi and I am unable to test the removal.

**Comment by Piraty** [comment]
now that pi4 is a thing we see that merging everything into rpi-kernel etc. wasn't that good.
I may come up with a solution split by rpi{1,2,3,4}-{foo,bar} in the near future to account for that (or at least start a discussion).

putting this on hold until then

**Pull request closed without merging**
