### PR TITLE
Modemmanager: add service

### PR DESCRIPTION
**Pull request by Gottox**

### CODE REVIEW

**Comment by Piraty** [comment]
If i can get my hands on a spare simcard i might try this one.
So far Networkmanager spawns Modemmanager for me

**Comment by Gottox** [comment]
Hmm... It didn't came up for me.

**Comment by Piraty** [comment]
Maybe it's not NM but some other gnome magic which spawns it (i run whole gnome on my tablet)...
but yeah, dbus config seems indeed missing.

**Comment by steinex** [comment]
ModemManager is spawned by NetworkManager for me aswell.

```
dbus-daemon[965]: [system] Activating service name='org.freedesktop.ModemManager1' requested by ':1.3' (uid=0 pid=961 comm="NetworkManager -n ") (using servicehelper)
dbus-daemon[965]: [system] Successfully activated service 'org.freedesktop.ModemManager1'
```

**Comment by Gottox** [comment]
Closing. I it needed a restart of NetworkManager

**Pull request closed without merging**
