### PR TITLE
chatterino2: update to 2.2.2

### PR DESCRIPTION
**Pull request by Eluminae**

### CODE REVIEW

**Comment by ahesford** [comment]
While you're updating this, please change the homepage to `https://chatterino.com` and add `changelog=https://chatterino.com/changelog` to the template.

**Comment by Eluminae** [comment]
links added

**Comment by ahesford** [comment]
Since `homepage` has been changed, you'll have to replace the the `${homepage}` in `distfiles` with a literal `https://github.com/fourtf/chatterino2`

**Comment by Eluminae** [comment]
shit, my bad

**Pull request merged**
