### PR TITLE
okteta: update to 0.26.4

### PR DESCRIPTION
**Pull request by yopito**

### CODE REVIEW

**Comment by yopito** [comment]
@Piraty : special dedicace regarding do_check() ;)

**Comment by Chocimier** [comment]
If you do `export QT_QPA_PLATFORM=offscreen` in pre_check, x server is not required. Two tests will still fail because of misbehaving QFINDTESTDATA. Options are to: disable, fix or merge with failing test for now and solve QFINDTESTDATA later.

**Comment by yopito** [comment]
@Chocimier : thanks for pointing this. Let's digg into.

**Comment by yopito** [comment]
check/testing is functional now, took ages to find a way to make it working ...

**Comment by Chocimier** [comment]
Thanks for solving problem with tests. I'll try to apply your solution to keditbookmarks, that have same problem.

**Pull request merged**
