### PR TITLE
pqiv: add build_options

### PR DESCRIPTION
**Pull request by SolitudeSF**
The names of options and default ones are under the question. I disabled ps/pdf rendering ones, since they arent the primary functional of image viewer.

### CODE REVIEW

**Comment by SolitudeSF** [comment]
https://travis-ci.org/void-linux/void-packages/jobs/476235876#L386
```
srcpkgs/pqiv/template: Place build_options= after checksum=
```
thats a new `xlint` rule?

**Comment by maxice8** [comment]
@chneukirchen

**Comment by Duncaen** [comment]
The naming of the options is a :-1: from me, `video` should be `ffmpeg`, the build options lose value if they all use different names to disable the same dependency.
Other options without default description in `common/options.description` should be set in the template.

**Comment by SolitudeSF** [comment]
what about the default options?

**Pull request merged**
