### PR TITLE
xbps-src: update_check.sh: check distfile existence for kde

### PR DESCRIPTION
**Pull request by yopito**
KDE distfile storage is based on versionned "folder".
An existing folder_version does not mean that the corresponding
distifile exists, so let's check its existence.

This PR provides also the missing `update` files related to this new detection.

Annotated Example:
```
$ ./xbps-src update-check okteta5
okteta5-17.12.1 -> okteta5-17.12.3      ## OK
okteta5-17.12.1 -> okteta5-18.04.0      ## false: no such a release
okteta5-17.12.1 -> okteta5-18.04.1      ## false: no such a release
okteta5-17.12.1 -> okteta5-18.04.2      ## false: no such a release
okteta5-17.12.1 -> okteta5-18.04.3      ## false: no such a release
```

The same with this PR version:
```
$ XBPS_UPDATE_CHECK_VERBOSE=1 ./xbps-src update-check okteta5
=> Using `/build/packages/hostdir/binpkgs/kde.fix.update.check' as local repository.
using okteta5/update overrides
(folder) fetching https://download.kde.org/stable/applications/
fetching https://www.kde.org/applications/utilities/okteta/
fetching https://download.kde.org/stable/applications/17.12.3/src/
fetching https://download.kde.org/stable/applications/18.04.0/src/
fetching https://download.kde.org/stable/applications/18.04.1/src/
fetching https://download.kde.org/stable/applications/18.04.2/src/
fetching https://download.kde.org/stable/applications/18.04.3/src/
found version 17.12.3
okteta5-17.12.1 -> okteta5-17.12.3
```

### CODE REVIEW

**Comment by yopito** [comment]
downside: more call `curl`:
*  once to retrieved "folder_version" list,
* a call for each "folder_version" to check distfile existence

**Comment by Johnnynator** [comment]
I did filter by subdircetory since not all KDE projects follow this subfolder structure, e.g. kdb. But it is probly wiser to just have a more general rule and then handeling these few specially with their own update file.
Otherwise I'm fine with this PR, my main Aim when I added it to the update check was just that it should be good enough, I was aware of it's limitation but never bothered to fix them, so Thanks for doing it :+1:

**Comment by yopito** [comment]
OK, thanks for your kindly answer.  
I will then remove the subpart checks only. (git push force on the go)

**Comment by Chocimier** [comment]
Nice. I want to remind of https://github.com/voidlinux/void-packages/pull/9196, that is not limited to kde.

**Comment by yopito** [comment]
@Chocimier : thanks for the reminder, totally forgot this previous discussion !  
We might extend this check (version folder based) to any package via a new flag in `update` file , something like "`versionned folder=1`", while keeping the default comportment for KDE as proposed here ?  
But let's wait for this PR to get merged first ?

**Comment by maxice8** [comment]
@Johnnynator @yopito any progress ?

**Comment by Johnnynator** [comment]
I merged this manually with some small changes (like a extensive list of kde folders instead of the general glob) for now.
@Chocimier if you want to propose any changes open a PR here.

**Pull request closed without merging**
