### PR TITLE
zathura: update to 0.5.8. + extensions

### PR DESCRIPTION
**Pull request by biopsin**
#### Testing the changes
- I tested the changes in this PR: **NO**

#### Local build testing
- I built this PR locally for my native architecture, (x64_86-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-musl
  - armv7l
  - armv6l-musl

I will test archs builds and extension later tonight.
@lemmi

### CODE REVIEW

**Comment by biopsin** [comment]
`=> ERROR: zathura-0.5.8_1: failed to install target dependencies! (error 40)`
and -musl is broken locally too
<details><summary>output</summary>

```log
=> xbps-src: updating repositories for target (aarch64-musl)...
[*] Updating repository `https://repo-default.voidlinux.org/current/aarch64/bootstrap/aarch64-musl-repodata' ...
aarch64-musl-repodata: 5183B [avg rate: 183MB/s]
[*] Updating repository `https://repo-default.voidlinux.org/current/aarch64/aarch64-musl-repodata' ...
aarch64-musl-repodata: 1777KB [avg rate: 77GB/s]
[*] Updating repository `https://repo-default.voidlinux.org/current/aarch64/nonfree/aarch64-musl-repodata' ...
aarch64-musl-repodata: 6212B [avg rate: 282MB/s]
[*] Updating repository `https://repo-default.voidlinux.org/current/aarch64/debug/aarch64-musl-repodata' ...
aarch64-musl-repodata: 819KB [avg rate: 22GB/s]
=> xbps-src: updating software in / masterdir...
=> xbps-src: cleaning up / masterdir...
=> zathura-0.5.8_1: removing autodeps, please wait...
=> zathura-0.5.8_1: removing autocrossdeps, please wait...
=> Installing aarch64-musl cross pkg: cross-vpkg-dummy ...
=> zathura-0.5.8_1: building with [meson] [meson] for aarch64-musl...
   [host] pkg-config-0.29.2_3: found (https://repo-default.voidlinux.org/current)
   [host] gettext-0.22.5_1: found (https://repo-default.voidlinux.org/current)
   [host] python3-Sphinx-7.2.6_2: found (https://repo-default.voidlinux.org/current)
   [host] desktop-file-utils-0.27_1: found (https://repo-default.voidlinux.org/current)
   [host] appstream-glib-0.8.1_2: found (https://repo-default.voidlinux.org/current)
   [host] glib-devel-2.80.3_1: found (https://repo-default.voidlinux.org/current)
   [host] librsvg-utils-2.58.2_1: found (https://repo-default.voidlinux.org/current)
   [host] meson-1.4.0_2: found (https://repo-default.voidlinux.org/current)
   [target] girara-devel-0.4.4_1: found (https://repo-default.voidlinux.org/current/aarch64)
   [target] sqlite-devel-3.45.3_2: found (https://repo-default.voidlinux.org/current/aarch64)
   [target] file-devel-5.45_1: found (https://repo-default.voidlinux.org/current/aarch64)
   [target] zlib-devel-1.3.1_1: found (https://repo-default.voidlinux.org/current/aarch64)
   [target] libseccomp-devel-2.5.5_1: found (https://repo-default.voidlinux.org/current/aarch64)
   [target] libglib-devel-2.80.3_1: found (https://repo-default.voidlinux.org/current/aarch64)
   [target] texlive-devel-20230313_1: found (https://repo-default.voidlinux.org/current/aarch64)
   [runtime] girara-devel-0.4.4_1: found (https://repo-default.voidlinux.org/current/aarch64)
   [runtime] cairo-devel-1.18.0_1: found (https://repo-default.voidlinux.org/current/aarch64)
=> zathura-0.5.8_1: installing host dependencies: pkg-config-0.29.2_3 gettext-0.22.5_1 python3-Sphinx-7.2.6_2 desktop-file-utils-0.27_1 appstream-glib-0.8.1_2 glib-devel-2.80.3_1 librsvg-utils-2.58.2_1 meson-1.4.0_2 ...
=> zathura-0.5.8_1: installing target dependencies: girara-devel-0.4.4_1 sqlite-devel-3.45.3_2 file-devel-5.45_1 zlib-devel-1.3.1_1 libseccomp-devel-2.5.5_1 libglib-devel-2.80.3_1 texlive-devel-20230313_1 ...
=> zathura-0.5.8_1: removing autodeps, please wait...
=> zathura-0.5.8_1: removing autocrossdeps, please wait...
=> ERROR: zathura-0.5.8_1: failed to install target dependencies! (error 40)
=> ERROR: Please see above for the real error, exiting...

```

</details>

**Comment by classabbyamp** [comment]
does this work?
```bash
if [ "$XBPS_TARGET_LIBC" = musl ]; then
	CPPFLAGS="-D__NR_landlock_create_ruleset=444 -D__NR_landlock_add_rule=445 -D__NR_landlock_restrict_self=446"
fi
```

**Comment by abenson** [comment]
Can you rebase and reorder so that `zathura` is the first commit in the chain?

**Comment by biopsin** [comment]
@abenson sorry did'nt make it it time,

**Comment by abenson** [comment]
No worries! I took care of it at time of merge.

**Pull request closed without merging**
