### PR TITLE
m4: various fixes

### LINKED ISSUE #25604: `./xbps-src bootstrap' fails
### System

* xuname:
  ``Void 5.8.14_1 x86_64-musl GenuineIntel uptodate rrFFFFFFF``
* package:  
  ``base-chroot-0.66`` (?)

### Expected behavior
``./xbps-src zap && ./xbps-src bootstrap`` succeeds.

### Actual behavior
```
...
[*] Collecting package files
kernel-libc-headers-4.19.0_2: collecting files...
musl-1.1.24_3: collecting files...
musl-devel-1.1.24_3: collecting files...
xbps-triggers-0.117_1: collecting files...
base-files-0.141_4: collecting files...
zlib-1.2.11_3: collecting files...
libgcc-9.3.0_6: collecting files...
libstdc++-9.3.0_6: collecting files...
binutils-2.34_1: collecting files...
libgcc-devel-9.3.0_6: collecting files...
libstdc++-devel-9.3.0_6: collecting files...
libssp-9.3.0_6: collecting files...
libssp-devel-9.3.0_6: collecting files...
gcc-9.3.0_6: collecting files...
libada-9.3.0_6: collecting files...
libada-devel-9.3.0_6: collecting files...
ERROR: libada-devel-9.3.0_6: file `/usr/lib/gcc/x86_64-linux-musl/9.3/plugin/include/ada/gcc-interface/ada-tree.def' already installed by package gcc-9.3.0_6.
Transaction failed! see above for errors.
=> ERROR: xbps-src: failed to install base-chroot!
```

### Context
``etc/conf`` contains the following line:
```
XBPS_PKG_OPTIONS_gcc=~ada
```

### PR DESCRIPTION
**Pull request by ev-ermakov**
Require texinfo in hostmakedepends. Partially fixes #25604.

### CODE REVIEW

**Comment by sgn** [comment]
Hm, no. I don't think we want that. I prefer to go with this instead: https://github.com/void-linux/void-packages/pull/24343/commits/f48c94727461c07e0bc4ddfb5afef5cbf5d2076f

**Comment by fosslinux** [comment]
No, we don't want texinfo in the bootstrap, this has been previously discussed.

@sgn I think your patch also needs an `if [ "$CHROOT_READY ]; then hostmakedepends+="texinfo"`

**Comment by sgn** [comment]
@fosslinux I don't know, I think I've run the build inside chroot without `texinfo`, but I haven't build `m4` in a while. I could try that later. I guess you mean something like:

```diff
diff --git a/srcpkgs/m4/template b/srcpkgs/m4/template
index 111dc6a6b07..6db163696da 100644
--- a/srcpkgs/m4/template
+++ b/srcpkgs/m4/template
@@ -14,6 +14,11 @@ maintainer="Enno Boland <gottox@voidlinux.org>"
 distfiles="${GNU_SITE}/${pkgname}/${pkgname}-${version}.tar.xz"
 checksum=f2c1e86ca0a404ff281631bdc8377638992744b175afb806e25871a24a934e07
 
+# Ubuntu 20.04 makeinfo breaks the build with ISO-8859-1 characters
+if [ ! "$CHROOT_READY" ]; then
+	export MAKEINFO=true
+else
+	hostmakedepends="texinfo"
+fi
+
 pre_check() {
 	case "$XBPS_TARGET_MACHINE" in
 		*-musl* )

```

**Comment by sgn** [comment]
https://github.com/void-linux/void-packages/commit/66bf185310ef656f05f8b9c24fb58470e8f27a8f

**Comment by sgn** [comment]
@fosslinux feel free to make a PR to propose adding `texinfo` into `hostmakedepends` for `m4`. I have been pushing a quick fix for bootstrap.

**Pull request closed without merging**
