### PR TITLE
vscode: update to 1.33.1. [ci skip]

### PR DESCRIPTION
**Pull request by shizonic**

### CODE REVIEW

**Comment by maxice8** [comment]
can we do the vscodium changes here ?

**Comment by shizonic** [comment]
Yes. So just the same configuration as vscodium but still named vscode? Have to write some patches for that.

**Comment by maxice8** [comment]
On Fri, Apr 12, 2019 at 10:12:24AM +0000, shizonic wrote:
> Yes. So just the same configuration as vscodium but still named vscode? Have to write some patches for that.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/10848#issuecomment-482519941

yes

**Comment by shizonic** [comment]
Ok. Will work on it.

**Comment by xtraeme** [comment]
This pkg should have be named vscode-bin rather.

**Comment by shizonic** [comment]
@xtraeme Okay. Even it's compiled from source ?

**Pull request merged**
