### PR TITLE
telegram-desktop: update to 3.0.1.

### PR DESCRIPTION
**Pull request by alihardan**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by alihardan** [comment]
Hello. It's my first commit here. I don't know will it build success or not, I'm waiting for workflow approval to see and fix possible errors.

**Comment by paper42** [comment]
> Hello. It's my first commit here. I don't know will it build success or not, I'm waiting for workflow approval to see and fix possible errors.

Please test this (compile, install and use at least for a minute) on your computer first before submitting a PR. Then check appropriate checkboxes in the PR description.

**Comment by alihardan** [comment]
> > Hello. It's my first commit here. I don't know will it build success or not, I'm waiting for workflow approval to see and fix possible errors.
> 
> Please test this (compile, install and use at least for a minute) on your computer first before submitting a PR. Then check appropriate checkboxes in the PR description.

Done. Complied it through Github actions (by forking this repo), then downloaded compiled `telegram-desktop-3.0.1_1.i686.xbps` into my local machine, installed and used it.

Sorry for bad commit messages, they're automated by Github and I forgot to edit them.

**Comment by paper42** [comment]
> > > Hello. It's my first commit here. I don't know will it build success or not, I'm waiting for workflow approval to see and fix possible errors.
> > 
> > Please test this (compile, install and use at least for a minute) on your computer first before submitting a PR. Then check appropriate checkboxes in the PR description.
> 
> Done. Complied it through Github actions (by forking this repo), then downloaded compiled `telegram-desktop-3.0.1_1.i686.xbps` into my local machine, installed and used it.

it's easy to do it on your own: clone this repository, do your changes and run
```
./xbps-src pkg telegram-desktop
```

> Sorry for bad commit messages, they're automated by Github and I forgot to edit them.

We need one commit, so you need to squash the commits. I would recommend not using Github UI, it might not even be possible to do it.

**Comment by alihardan** [comment]
it's easy to compile on person own machine, but since my Void Linux machine is low-end and old, it takes really long time. And this repo was so big for cloning (my bandwhich is limited).

I will squash commits soon.

**Pull request merged**
