### PR TITLE
[NOMERGE] alsa-lib: update to 1.2.5.

### PR DESCRIPTION
**Pull request by ericonr**
Doesn't even build on musl yet, opening PR to prevent others from updating. See https://github.com/alsa-project/alsa-lib/issues/143 and https://github.com/alsa-project/alsa-lib/issues/142

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by biopsin** [comment]
today I noticed, for the first time, running this for a while on x86_64

```
ALSA lib conf.c:5560:(snd_config_expand) Parse arguments error: Invalid argument
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.USB-A
udio.pcm.default_playback_dmix_yes:CARD=1cards.USB-Audio.pcm.default_playback_dm
ix_yes:CARD=1'
ALSA lib conf.c:5088:(_snd_config_evaluate) function snd_func_refer returned err
or: No such file or directory
ALSA lib conf.c:5088:(_snd_config_evaluate) function snd_func_refer returned err
or: No such file or directory
ALSA lib conf.c:5576:(snd_config_expand) Evaluate error: No such file or directo

```
and dmix broke, think restart will resolve it for now..

**Comment by cinerea0** [comment]
@biopsin Do you think that if you installed alsa-ucm-conf 1.2.5 (my PR for that: https://github.com/void-linux/void-packages/pull/31262) it would fix the issue?

**Comment by biopsin** [comment]
@cinerea0 I assume so, but I don't think its related to the dmix dropout.
I downgraded to resolve the problem for now, as reloading alsa did not fix it.

**Comment by biopsin** [comment]
@ericonr try bump to 1.2.5.1 as of https://github.com/alsa-project/alsa-lib/commit/abe805ed6c7f38e48002e575535afd1f673b9bcd
it's ready to go and local x86_64-musl build is successfull :)
Hopefully dmix is resolved too

**Comment by cinerea0** [comment]
@ericonr Have you tested this since updating to 1.2.5.1?

**Comment by ericonr** [comment]
@cinerea0 I'm running it locally, yes. Do you think it's good to merge? I haven't looked for further bug reports.

**Comment by cinerea0** [comment]
@ericonr I was going to test this PR today with my alsa-ucm-conf PR, but I can't seem to get the tarball to download. If you haven't had any more bug reports it should be fine.

**Comment by paper42** [comment]
This update breaks pipewire until it's updated to 0.3.31, so we should wait for #31549

**Comment by cinerea0** [comment]
@ericonr Now that the pipewire PR has been merged, should this and the `alsa-ucm-conf` PRs be merged as well?

**Comment by ericonr** [comment]
Probably should, yes...

**Comment by cinerea0** [comment]
Are there any bug reports remaining for this?

**Comment by ericonr** [comment]
Shouldn't be, thanks for the persistence :)

**Comment by dkwo** [comment]
This update breaks audio for me: pipewire gives the warning
`[W][02053.586348][ policy-node.c: 910 rescan_node()] no node found for 38`
while for `Card: PipeWire`, alsamixer says `This sound device does not have any controls.`
The issue is solved with `xdowngrade /var/cache/xbps/alsa-lib-1.2.4_2.x86_64-musl.xbps`

**Comment by biopsin** [comment]
@dkwo if its relevant, try maybe debug with

> Can you killall pipwire-media-session then run:
> `PIPEWIRE_DEBUG=4 pipewire-media-session 2>log`

**Comment by dkwo** [comment]
@biopsin Your other alsa pr solved my issue, thanks.

**Pull request merged**
