### PR TITLE
[WIP] clamav: update to 1.2.1.

### PR DESCRIPTION
**Pull request by nsudsgaard**
I understand that opening another PR is not the best thing to do. However, my previous PR had a bit of an accident and the other PR for clamav (#41188) is not very active (maybe I am just inpatient).

#### Testing the changes

- [ ] Finished this for 1.2.1

- I tested the changes in this PR: **YES**

#### Local build testing

- [x]  Finished this for 1.2.1

- I built this PR locally for my native architecture, (x86_64, x86_64-musl, i686)
- I built this PR locally for these architectures:
  - aarch64 _crossbuild_
  - aarch64-musl _crossbuild_
  - armv7l _crossbuild_
  - armv7l-musl _crossbuild_
  - armv6l _crossbuild_
  - armv6l-musl _crossbuild_

### CODE REVIEW

**Comment by nsudsgaard** [comment]
Quickly build it locally for x86_64 and everything seems fine.
Reading the error messages it seems like a network issue (Fails to connect to the server to download). However, I am not sure why this happened only for x86_64 and i686.

**Comment by jcgruenhage** [comment]
@nsudsgaard thanks for continuing here! Honestly, if someone else wants to take over clamav, I'm more than happy. I was absent from void for a while, but starting to get back atm and I've used your PR to deploy clamav on my machine. Seems to work fine :)

**Comment by nsudsgaard** [comment]
> @nsudsgaard thanks for continuing here! Honestly, if someone else wants to take over clamav, I'm more than happy. I was absent from void for a while, but starting to get back atm and I've used your PR to deploy clamav on my machine. Seems to work fine :)

I'm glad it worked on your machine.
I'll see if I can update the PR to 1.2.1 and somehow get the checks to not fail when I have some spare time.

**Comment by jcgruenhage** [comment]
I actually built 1.2.1 on my machine, updating that was fairly trivial.

**Pull request closed without merging**
