### PR TITLE
wine: update to 9.7

### PR DESCRIPTION
**Pull request by fvalasiad**
@Hoshpak @iFoundSilentHouse  Opening this but maybe we should wait first for #49943 to be merged first!

### CODE REVIEW

**Comment by fvalasiad** [comment]
@iFoundSilentHouse Realistically, maybe we should merge both PRs into one, to deliver a single big update to Wine 9.7 revision 1.

**Comment by iFoundSilentHouse** [comment]
I'm not sure if I'll be able to solve all packaging difficulties before like wine 9.99 version :)
And there will also be testing time with aarch64 users... but you're always welcome in my fork

**Comment by fvalasiad** [comment]
@iFoundSilentHouse Well I did it anyway so we gonna let the rest decide, it's probably wiser to just ship wine 9.7 for now and keep working on the arm64 PR individually. Worst case scenario we simply rebase.

**Comment by Hoshpak** [comment]
Agreed, will merge this one now.

**Pull request merged**
