### PR TITLE
alsa-{lib, utils, plugins, ucm-conf}: update to 1.2.6.x

### PR DESCRIPTION
**Pull request by cinerea0**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by cinerea0** [comment]
I will say that, while this works, it should probably not be merged until `alsa-lib` and `alsa-utils` are updated as well. I'd do it but I can't access the alsa website or the distfiles no matter what I do.

**Comment by biopsin** [comment]
@ cinerea0 can you test again, as it works for me, and include alsa-lib and alsa-utils in this PR

**Comment by cinerea0** [comment]
@biopsin I figured out a trick to get the distfiles and tested the updates. They all seem to work fine.

**Comment by biopsin** [comment]
@cinerea0 I concur, tested with Sweep, Reaper and mpv

**Review by biopsin — APPROVED** [review]

**Comment by cinerea0** [comment]
@biopsin A couple minor version updates came through. I'm testing everything currently in this PR and it all works properly for me.

**Pull request merged**
