### PR TITLE
gandi-cli: remove package

### PR DESCRIPTION
**Pull request by dotnetfox**
The upstream decided to deprecate gandi-cli (PR Gandi/gandi.cli#313).

According to PR Gandi/gandi.cli#310, their new API (v5) will not be implemented in
this package "*as we have deprecated this CLI in its current form*".

### CODE REVIEW

**Comment by ericonr** [comment]
Please fix links in commit. They currently link to things in void-packages.

**Comment by dotnetfox** [comment]
@ericonr,

> Please fix links in commit. They currently link to things in void-packages.

Did not know that commits on github show links, too. Compliance.

Thank you.

**Comment by ericonr** [comment]
@lonwillett ok?

**Comment by lonwillett** [comment]
@ericonr,
Fine. It does seem to be dead.

**Pull request closed without merging**
