### PR TITLE
New package: i3status-rust-0.10.0

### PR DESCRIPTION
**Pull request by jcgruenhage**

### CODE REVIEW

**Comment by Hoshpak** [comment]
fails on all 32 bit architectures

**Comment by jcgruenhage** [comment]
This is a problem with the upstream package, what do I need to add to the template to ignore those architectures?

**Comment by Hoshpak** [comment]
I think in this case it would be OK to restrict the package to 64 bit architectures. I couldn't find anything about it on the upstream pages but it obviously is incompatible with 32 bit CPU architectures in its current state.

**Comment by Gottox** [comment]
Is there an open upstream issue?

**Comment by jcgruenhage** [comment]
I opened an issue there, yes: https://github.com/greshake/i3status-rust/issues/403

**Comment by jcgruenhage** [comment]
The builds also fail on aarch64 musl due to a different reason, which I also reported and that was already fixed upstream.

**Comment by Gottox** [comment]
Upstream fix: https://github.com/greshake/i3status-rust/pull/406

**Comment by jcgruenhage** [comment]
Since all build failures have been fixed, should we just ask the maintainers to publish a v0.10.1 and package that instead of marking the builds for v0.10.0 as broken or patching those here?

**Comment by Gottox** [comment]
Sry for the delay. I'm okay with both.

**Pull request merged**
