### PR TITLE
xfce4-battery-plugin: add changelog & fix h_page

### PR DESCRIPTION
**Pull request by vadzimnaumuk**
- I tested the changes in this PR: YES

- I built this PR locally for my native architecture, (amd64-glib)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - amd64-glib

### CODE REVIEW

**Comment by vadzimnaumuk** [comment]
@classabbyamp, add this please =)

**Comment by paper42** [comment]
Commit message can be `xfce4-battery-plugin: add changelog, fix homepage`, h_page is very confusing and not necessary.

Is this commit yours? Why is it showing as belonging to someone else? Do you have two accounts on GitHub? Adding the commit email to your main account could fix this.

**Comment by vadzimnaumuk** [comment]
> Commit message can be `xfce4-battery-plugin: add changelog, fix homepage`, h_page is very confusing and not necessary.
> 
> Is this commit yours? Why is it showing as belonging to someone else? Do you have two accounts on GitHub? Adding the commit email to your main account could fix this.

yes this is my commit. i change account for next commits.
in this commit, add link on changelog. previous homepage was deleted. now xfce-web redirect to new page. ssory for my english =)

**Comment by classabbyamp** [comment]
i do not think this change is necessary until it has an update, and can be done then.

**Pull request closed without merging**
