### PR TITLE
New package: removed-packages

### PR DESCRIPTION
**Pull request by Chocimier**
Continuation of #9745.

Adding package to conflicts= in removed-packages will cause removal from systems where it was installed.

In transaction, package is listed as to be removed.

As being explicit and actual remove, I see this way better than hidden and still-in-pkgdb way of updating to empty package.

This do not prevent from installing package again, but will remove again on removed-packages update.

Tested for removal of manually installed package, orphaned dependency, and shlib-provider and shlib-consumer in one transaction.

### CODE REVIEW

**Comment by travankor** [comment]
Any news on this?

**Comment by the-maldridge** [comment]
A year later... I really like this as a clean hack to an otherwise tricky to solve bug.  If there are no complaints from @void-linux/pkg-committers I will merge this on Friday.

**Comment by Chocimier** [comment]
Rebased, and added to other base packages.

**Comment by the-maldridge** [comment]
Friday came and went, and I was apparently more asleep than I thought.  Merging your change in now.

**Pull request merged**
