### PR TITLE
New package: fontmake-2.0.7

### PR DESCRIPTION
**Pull request by svenper**

### CODE REVIEW

**Comment by Chocimier** [comment]
Most python packages are either noarch or requires python3-devel. Only packages without compiled part may be noarch. Please sort out.

We do not want new python2 packages, this includes built with python-module build style.

There is no need to set pycompile_module, since some time ago it is computed.

We have python3 updated to 3.8, so there is no need for backports.

**Comment by ericonr** [comment]
Is this PR still desired? Please remember to ping reviewers once changes have been made, it's easy to miss them.

**Comment by svenper** [comment]
Oh, sorry, it's been a while since I looked at this. I remember getting stuck at one or more of the packages looking for the python2 stuff, hence the backports. There's probably a better way... (read: I have no idea about any of this, I just naively submitted the templates that Worked For Me.)

**Comment by ericonr** [comment]
We don't need the py 2 stuff, only py 3 for now. I think the packages should be named `python3-<something>` as well, instead of `python-<>`.

**Comment by abenson** [comment]
Seemingly abandoned.

**Pull request closed without merging**
