### PR TITLE
New package: cabbage-2.0.03

### PR DESCRIPTION
**Pull request by laserbat**

### CODE REVIEW

**Comment by laserbat** [comment]
Musl builds are failing because csound is broken on them. I'll take a look at it later, maybe I'll figure something out.

**Comment by maxice8** [comment]
ping

**Comment by laserbat** [comment]
It should be fine to merge. I was unable to take a look at csound but otherwise I think this template is okay. It's not pretty, because cabbage uses a horrible build system, but it works.

**Comment by Johnnynator** [comment]
> It should be fine to merge. I was unable to take a look at csound but otherwise I think this template is okay. It's not pretty, because cabbage uses a horrible build system, but it works.

I fixed csound on musl two weeks ago https://github.com/void-linux/void-packages/commit/1cb5c25d336163205866f8005f426b980774fdd9

**Pull request closed without merging**
