### PR TITLE
libGL: update to 18.1.3.

### PR DESCRIPTION
**Pull request by maxice8**
cc @q66 can test 18.1.2 works fine on tegra ?
cc @biospin can test 18.1.2 works fine on nvidia ?

The current blocking problem to this merge is musl stuff getting segfaults, people that can fix that is required.

### CODE REVIEW

**Comment by biopsin** [comment]
typo in nvidia: on line 55 -> usr//
tested glxinfo, played etlegacy, loaded fishGL, watched a movie.. nvidia works.

**Comment by maxice8** [comment]
On Sun, Jun 17, 2018 at 06:28:13AM -0700, biopsin wrote:
> typo in nvidia: on line 55 -> usr//
> tested glxinfo, played etlegacy, loaded fishGL, watched a movie.. nvidia works.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/143#issuecomment-397879109

thanks for catching the typo and testing.

**Comment by biopsin** [comment]
question; why not map it like the old way and directly to
vinstall libglx.so.${version} 755 usr/lib/xorg/modules/extensions/nvidia
ln -sf libglx.so.${version} ${DESTDIR}/usr/lib/xorg/modules/extensions/nvidia/libglx.so
it states it's purpos # GLX ext mod for X (and retains no mesa conflict) ?

**Comment by maxice8** [comment]
On Mon, Jun 18, 2018 at 05:20:30AM -0700, biopsin wrote:
> question; why not map it like the old way and directly to
> vinstall libglx.so.${version} 755 usr/lib/xorg/modules/extensions/nvidia
> ln -sf libglx.so.${version} ${DESTDIR}/usr/lib/xorg/modules/extensions/nvidia/libglx.so
> it states it's purpos # GLX ext mod for X (and retains no mesa conflict) ?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/143#issuecomment-398035482

i just kept it the way the previous person that tried did it.

**Comment by codingHahn** [comment]
Is there anything blocking this?

**Comment by maxice8** [comment]
On Sun, Jun 24, 2018 at 11:57:05AM -0700, codingHahn wrote:
> Is there anything blocking this?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/143#issuecomment-399779038

reports that it doesn't work on musl.

**Comment by Johnnynator** [comment]
@maxice8 I doubt that I will be able to fix libglvnd on musl. So either you have to find someone who may know how to debug and fix it, or just build mesa on musl without libglvnd since it is the only libGL there.

**Comment by q66** [comment]
nothing changed in 18.1.2 regarding tegra so no reason why it wouldn't work. Also, I use it on aarch64-musl and libglvnd works fine.

**Comment by maxice8** [comment]
On Thu, Jun 28, 2018 at 06:39:58AM -0700, Daniel Kolesa wrote:
> nothing changed in 18.1.2 regarding tegra so no reason why it wouldn't work. Also, I use it on aarch64-musl and libglvnd works fine.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/143#issuecomment-401038136

iirc John said that x86_64-musl failed, i do not possess a musl machine, neither time to make one.

**Comment by maxice8** [comment]
> or just build mesa on musl without libglvnd since it is the only libGL there.

won't be possible, libglvnd causes changes to common/shlibs

**Comment by Johnnynator** [comment]
common/shlibs can have AFAIK double entries.

**Comment by maxice8** [comment]
> common/shlibs can have AFAIK double entries.

if that is the case i will work on it after i'm done with #558

**Comment by maxice8** [comment]
@Johnnynator i added libglvnd as a build_option called libglvnd.

i686-musl and x86_64-musl have it disabled, the rest have it enabled, i also marked libglvnd as broken on those arches.

if you could test i would appreciate greatly, i have no musl machines.

**Comment by Johnnynator** [comment]
@maxice8 It seems to work fine. Tested so far with OpenMW, Firefox and some qt5 stuff.

**Comment by Johnnynator** [comment]
Damn. It actually will not work. `xbps-src` will always add the first entry to rundeps so anything that depends on e.g. `libGL.so.1` will try to pull in `libglvnd` on every Architecutre. I wrongly assumed that it may work because some shlibs had already two entries of different packages. It seems like either `common/shlibs`has to be advanced to have a special third arch specific entry or the way `pre-pkg/04-generate-runtime-deps.sh` resolves shlibs has to be done in a more advanced manner.

**Comment by maxice8** [comment]
I have decided to postpone libglvnd support and just push for libGL 18.1.3 to be added.

**Comment by maxice8** [comment]
@q66 i removed libglvnd, see if it has any effect on tegra please.

**Comment by q66** [comment]
@maxice8 i can't test it right now, but it should be fine as long as it builds, because i was doing all my initial 18.1 testing with no libglvnd and it worked like a charm. I checked the commits and they seem fine, too. So no worries about that, I guess

**Comment by Johnnynator** [comment]
x86_64-musl with an Intel iGPU is also working fine.

**Pull request closed without merging**
