### PR TITLE
New package: infisical 0.14.2

### PR DESCRIPTION
**Pull request by 0xdeadbad**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-musl
  - aarch64
  - armv5te-musl
  - armv5te
  - armv5tel-musl
  - armv5tel
  - armv6hf-musl
  - armv6hf
  - armv6l-musl
  - armv6l
  - armv7hf-musl
  - armv7hf
  - armv7l-musl
  - armv7l
  - i686-musl
  - i686
  - ppc64le-musl
  - ppc64le
  - riscv64-musl
  - riscv64
  - x86_64-musl

### CODE REVIEW

**Comment by 0xdeadbad** [comment]
Ok, I just woke up and this looks terrible. Going to refactor-fix

**Comment by classabbyamp** [comment]
- no need to restrict the architectures (especially as what you put limits you to glibc only)
- use the go `build_style`, as it takes care of most things for you
- `build_helper=qemu` allows the `go run` to work in cross
- don't override `do_extract`, use `build_wrksrc` to change the working directory of the build
- `XBPS_CHECK_PKGS` should never be set in templates, that's internal to xbps-src
- there's no need to use `wget`, the default (`xbps-fetch`) should work fine
- indent with tabs
- gzipping the manpage is useless because `vman` will ungz the file

```patch
From aa70f48c14a71f0101b1a1400baa79621a45337d Mon Sep 17 00:00:00 2001
From: classabbyamp <void@placeviolette.net>
Date: Fri, 13 Oct 2023 13:16:27 -0400
Subject: [PATCH] fixup! New package: infisical 0.14.2

---
 srcpkgs/infisical/patches/fix_login..go.patch |  4 +-
 srcpkgs/infisical/template                    | 58 ++++++-------------
 2 files changed, 21 insertions(+), 41 deletions(-)

diff --git a/srcpkgs/infisical/patches/fix_login..go.patch b/srcpkgs/infisical/patches/fix_login..go.patch
index 39d05f4f62b..90bcc9ba20b 100644
--- a/srcpkgs/infisical/patches/fix_login..go.patch
+++ b/srcpkgs/infisical/patches/fix_login..go.patch
@@ -1,5 +1,5 @@
---- a/packages/cmd/login.go	2023-10-13 03:18:59.436901696 -0300
-+++ b/packages/cmd/login.go	2023-10-13 03:23:37.911320438 -0300
+--- a/cli/packages/cmd/login.go	2023-10-13 03:18:59.436901696 -0300
++++ b/cli/packages/cmd/login.go	2023-10-13 03:23:37.911320438 -0300
 @@ -117,7 +117,7 @@
  
  		err = util.StoreUserCredsInKeyRing(&userCredentialsToBeStored)
diff --git a/srcpkgs/infisical/template b/srcpkgs/infisical/template
index 5f7ddd57399..5ee034221e5 100644
--- a/srcpkgs/infisical/template
+++ b/srcpkgs/infisical/template
@@ -2,53 +2,33 @@
 pkgname=infisical
 version=0.14.2
 revision=1
-archs="x86_64 aarch64"
-create_wrksrc=true
-makedepends="go wget tar"
-checkdepends="go git"
-short_desc="CLI tool for infisical, an open-source secret management platform"
+build_style=go
+build_helper="qemu"
+build_wrksrc="cli"
+go_import_path="github.com/Infisical/infisical-merge"
+go_ldflags="-X github.com/Infisical/infisical-merge/packages/util.CLI_VERSION=${version}"
+checkdepends="git"
+short_desc="Open-source secret management platform (CLI)"
 maintainer="Matheus Garcias <matheus.dasilva.garcias@gmail.com>"
 license="MIT"
 homepage="https://infisical.com"
 distfiles="https://github.com/Infisical/infisical/archive/refs/tags/infisical-cli/v${version}.tar.gz"
 checksum=313caf8d4e6ca5fd88d4f2adf72c721958d602404b6f80611a78a2f757d993f1
-fetch_cmd="wget"
-nopie=true
-XBPS_CHECK_PKGS=true
 
-unset build_style
-
-function do_extract() {
-    tar -xvzf ${XBPS_SRCDISTDIR}/${pkgname}-${version}/v${version}.tar.gz \
-        --strip-components=2 \
-        infisical-infisical-cli-v${version}/cli
-}
-
-function do_build() {
-    go build \
-        -o infisical \
-        --ldflags="-X \"github.com/Infisical/infisical-merge/packages/util.CLI_VERSION=${version}\"" \
-        ${XBPS_BUILDDIR}/${pkgname}-${version}
+do_check() {
+	go test ./...
 }
 
-function do_check() {
-    [ "$(./infisical --version)" = "infisical version ${version}" ] || return 1
-    go test github.com/Infisical/infisical-merge/packages/cmd
-    go test github.com/Infisical/infisical-merge/report
-    go test github.com/Infisical/infisical-merge/config
-    go test github.com/Infisical/infisical-merge/detect
-}
+post_install() {
+	mv "${DESTDIR}"/usr/bin/infisical-merge "${DESTDIR}"/usr/bin/infisical
 
-function do_install() {
-    vbin infisical
-}
+	go run . man > infisical.1
+	vman infisical.1
 
-function post_install() {
-    go run . man | gzip -c > "infisical.1.gz"
-    vman "infisical.1.gz"
+	for sh in bash zsh fish; do
+		go run . completion "$sh" > "infisical.$sh"
+		vcompletion "infisical.$sh" "$sh"
+	done
 
-    for sh in bash zsh fish; do
-	    go run . completion "$sh" > "infisical.$sh"
-        vcompletion "infisical.$sh" "$sh"
-    done
-}
\ No newline at end of file
+	vlicense "${wrksrc}"/LICENSE
+}
-- 
2.42.0

```

**Comment by classabbyamp** [comment]
ah that probably worked for me because I have binfmts set up locally. instead of `go run . ...` use `vtargetrun "${DESTDIR}"/usr/bin/infisical ...`

**Comment by 0xdeadbad** [comment]
Wow, thank you very much for the tips, changes and the very clean patch @classabbyamp .I'll do my best to bring cleaner PRs!

**Comment by chrysos349** [comment]
you could also disable telemetry

```
post_patch() {
	# disable telemetry
	vsed -i packages/cmd/root.go \
		-e 's/"telemetry", true/"telemetry", false/'
}
```

**Comment by 0xdeadbad** [comment]
> you could also disable telemetry
> 
> ```
> post_patch() {
> 	# disable telemetry
> 	vsed -i packages/cmd/root.go \
> 		-e 's/"telemetry", true/"telemetry", false/'
> }
> ```

Well spotted! Thank you.

**Comment by 0xdeadbad** [comment]
@classabbyamp I think I'm done with it, I tested personally on my computer (x86_64-glibc) and my raspberry pi 4 (aarch64-glibc) and added to the list every architecture that were cross built successfully. I can squash the commits and add co authors as I did. Anything you think that should be changed?

**Comment by classabbyamp** [comment]
squash but there's no need to add coauthors

**Comment by 0xdeadbad** [comment]
> squash but there's no need to add coauthors

Done. Thanks for the guidance!

**Comment by chrysos349** [comment]
bump

**Comment by chrysos349** [comment]
bump

**Pull request closed without merging**
