### PR TITLE
nvidia304: remove.

### PR DESCRIPTION
**Pull request by travankor**
As per https://nvidia.custhelp.com/app/answers/detail/a_id/3142/,
the nvidia 304 series drivers stopped receiving support at the end of 2017.
The old nvidia binaries are not compatible with Xorg server newer than 1.19,
so it makes sense to remove this binary. Users of this driver are recommended
to use the open-source nouveau driver instead.

-----

Edit: not sure if it makes sense to point the package to the nouveau driver, but if anyone was still using this, it would be broken by the latest xorg updates a few months ago.

### CODE REVIEW

**Comment by maxice8** [comment]
@the-maldridge i don't have nvidia hardware

**Comment by the-maldridge** [comment]
I was mainly adding you to see if the removal looked okay or if anything else needed to be done.

**Comment by maxice8** [comment]
```
srcpkgs/nvidia304-dkms
srcpkgs/nvidia304-libs
srcpkgs/nvidia304-opencl
```

**Comment by maxice8** [comment]
On Wed, Sep 12, 2018 at 02:41:01PM -0700, Michael Aldridge wrote:
> I was mainly adding you to see if the removal looked okay or if anything else needed to be done.
> 
> -- 
> You are receiving this because your review was requested.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/2688#issuecomment-420807420

You did the right thing

**Comment by maxice8** [comment]
While you're at it add another space between title and the message body

```
$ git commit --amend --no-edit
[nvidia304 64f98df85e] nvidia304: remove. As per https://nvidia.custhelp.com/app/answers/detail/a_id/3142/, the nvidia 304 series drivers stopped receiving support at the end of 2017. The old nvidia binaries are not compatible with Xorg server newer than 1.19, so it makes sense to remove this binary. Users of this driver are recommended to use the open-source nouveau driver instead.
```

**Comment by maxice8** [comment]
On Fri, Sep 14, 2018 at 12:55:03AM -0700, cr6git wrote:
> Merged #2688 into master.
> 
> -- 
> You are receiving this because your review was requested.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/2688#event-1845432082

@cr6git

Please contact @Gottox and ask him to remove the packages from the repo

**Pull request merged**
