### PR TITLE
GitHub Action: build on push to non-master branches

### PR DESCRIPTION
**Pull request by sgn**
See https://github.com/sgn/void-packages/actions/runs/493766269

### CODE REVIEW

**Comment by ericonr** [comment]
Doesn't this mean that a staging branch with huge changes will be unnecessarily running CI? I have a couple branches I keep around that I don't want to have CI run on... Opening a PR on your own repo is the simplest way of achieving this without spending a bunch of time running builds.

**Comment by sgn** [comment]
We can set the ignore to pattern matching, let's say, ignore branches with name: 'wip-*'

**Comment by ericonr** [comment]
I'm concerned about people who aren't aware of this new default getting lots of notifications and spending more CI time than they expect. GH is kinda stupid as well, so it will have separate CI runs for the PR and for the branch in the person's repo.

Anyway, if you think this is useful (and I believe others have requested it as well), we can turn it on. As long as this doesn't impact us too much (by, say, counting the number of machines we are using by including forks), I think we can push as something experimental.

**Comment by fosslinux** [comment]
Whats the liquid-dsp change?

**Comment by sgn** [comment]
On 2021-01-18 16:10:09-0800, fosslinux <notifications@github.com> wrote:
> Whats the liquid-dsp change?

That one was pushed out b68a299f86b446d886da9674226e301da4fcdb7b

**Comment by ericonr** [comment]
@sgn maybe we can make CI run on branches named `ci-*` instead? That way it's opt-in.

**Comment by sgn** [comment]
Yay, let's do that instead.

**Pull request merged**
