### PR TITLE
python3-scipy: update to 1.4.1

### PR DESCRIPTION
**Pull request by NeelChotai**

### CODE REVIEW

**Comment by ericonr** [comment]
`int64_t` should be defined in `/usr/include/stdint.h` (it's pulled from `/usr/include/bits/alltypes.h`, but you should use the stdint header). If you can't figure out where the error came from, fixing it with a patch that adds that include would work. It shouldn't be needed, though.

**Comment by st3r4g** [comment]
this builds on musl if you apply ericonr's suggestion

**Comment by NeelChotai** [comment]
@ericonr thank you for your suggestion, worked perfectly! Patch submitted to upstream.

**Comment by ahesford** [comment]
1.5.0 does seem to fix musl. Cross compilation takes a bit more hacking of the build system. See #23295.

**Pull request closed without merging**
