### PR TITLE
libgit2 1.8

### PR DESCRIPTION
**Pull request by tranzystorekk**
#### Testing the changes
- I tested the changes in this PR: **briefly**

~~I'd like to wait until a larger portion of dependent rust packages bump to this version (git2 0.19+) to avoid maintaining a lot of version bump patches.~~

### CODE REVIEW

**Comment by icp1994** [comment]
`git-absorb` bump requires `libgit2 >= 1.8.1 libgit2 < 1.9.0`

**Comment by tranzystorekk** [comment]
I'd stick to manually downgrading git2 back to 0.18 for now

**Comment by SpidFightFR** [comment]
Hey, any news on that front?

**Comment by tranzystorekk** [comment]
@SpidFightFR atm most our rust packages are linking to 1.7 by default, so this has some more time left to wait

**Comment by tranzystorekk** [comment]
Decided to split off the 1.8 package so that we don't have to wait around and the dependents changes can be more gradual

**Pull request merged**
