### PR TITLE
New package: joshuto-0.9.3

### PR DESCRIPTION
**Pull request by siduck**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

works.

image

 I closed the previous PR due to missing license version

### CODE REVIEW

**Comment by paper42** [comment]
please do not close PRs and open new ones just to update their content, that's what force push and git commit --amend is for.

**Comment by paper42** [comment]
and please fill out the New package part in the PR description

**Comment by siduck** [comment]
> please do not close PRs and open new ones just to update their content, that's what force push and git commit --amend is for.

oh didnt know about this, thanks for informing!

**Comment by siduck** [comment]
> and please fill out the New package part in the PR description

done

**Comment by siduck** [comment]
@mobinmob can you approve :c

**Comment by siduck** [comment]
nvm

**Comment by superiums** [comment]
Is this included in void ? 
i can't find it.

**Comment by siduck** [comment]
> Is this included in void ? i can't find it.

no idea, i no longer use void!

**Pull request closed without merging**
