### PR TITLE
New package: gcc4ti-0.96b11

### PR DESCRIPTION
**Pull request by tibequadorian**

### CODE REVIEW

**Comment by q66** [comment]
don't conflate archs and nocross

**Comment by tibequadorian** [comment]
> don't conflate archs and nocross
i didn't set nocross

**Comment by q66** [comment]
yes, exactly. I don't see anything in this tying it to x86, but I'm also like 99% sure this does not cross compile as-is

**Comment by tibequadorian** [comment]
> yes, exactly. I don't see anything in this tying it to x86, but I'm also like 99% sure this does not cross compile as-is

ah sorry misunderstood

**Comment by q66** [comment]
you will need to add these changes, too

```
commit 3faa77c1a86b528175bd659b9c9d7f854cae8985
Author: q66 <daniel@octaforge.org>
Date:   Sat Apr 18 23:54:53 2020 +0200

    gcc4ti: replace platform detection scripts
    
    also stop trying to strip target files

diff --git a/srcpkgs/gcc4ti/template b/srcpkgs/gcc4ti/template
index 0a153a3e19..525f6a6e89 100644
--- a/srcpkgs/gcc4ti/template
+++ b/srcpkgs/gcc4ti/template
@@ -11,6 +11,7 @@ license="GPL-2.0-only"
 homepage="https://github.com/debrouxl/gcc4ti"
 distfiles="https://github.com/debrouxl/gcc4ti/archive/${_commit}.tar.gz"
 checksum=b65eca299c188a1f07887128c4b247363734f1fc44add153c439c07632bfbca1
+nostrip_files="tigcc.a flashos.a fargo.a"
 nocross=yes
 
 do_install() {
@@ -22,6 +23,12 @@ do_install() {
 	export GCC4TIHOST=$XBPS_CROSS_TRIPLET
 	cd ../gcc4ti-0.96b11/scripts
 	./Install_step_1
+
+	# override config.guess/sub from 2004 to detect modern targets
+	local cfgdir="${XBPS_COMMONDIR}/environment/configure/automake"
+	cp ${cfgdir}/config.* ../download/gcc-*
+	cp ${cfgdir}/config.* ../download/binutils-*
+
 	./Install_step_2
 	./Install_step_3
 	./Install_step_4
```

otherwise, it won't compile on musl or non-x86_64 targets (it'll fail to detect the target triplet). The nostrip_files bit is not entirely necssary but it'll prevent it from trying.

also, you should find if you can somehow split the build/install steps.

i'll leave the rest to other reviewers

**Comment by q66** [comment]
tested:

```
q66@rimi: /home/q66$ xbps-query gcc4ti
architecture: ppc64le
filename-sha256: e3b58d541bd4acef97711c6fc86a41ccf63ac047fd1e1b0b194f6ebd454779ca
filename-size: 3839KB
homepage: https://github.com/debrouxl/gcc4ti
install-date: 2020-04-19 00:05 CEST
install-msg: 98B
installed_size: 22MB
license: GPL-2.0-only
maintainer: tibequadorian <tibequadorian@posteo.de>
metafile-sha256: 235115ffa1878025c91a2be01ca016898539fb44adec1fb2676b0a85c9a71470
pkgname: gcc4ti
pkgver: gcc4ti-0.96b11_1
repository: /media/hostdir/binpkgs
run_depends:
	glibc>=2.29_1
shlib-requires:
	libc.so.6
short_desc: Complete and mature GPL SDK for the TI-68k calculators
state: installed
q66@rimi: /home/q66$ /opt/gcc4ti/bin/tigcc     
tigcc: no input files
q66@rimi: /home/q66$ uname -a
Linux rimi 5.5.7_2 #1 SMP Mon Mar 2 14:06:56 UTC 2020 ppc64le GNU/Linux
```

**Pull request closed without merging**
