### PR TITLE
python/python3-setuptools: split template, bump versions

### PR DESCRIPTION
**Pull request by zdykstra**

### CODE REVIEW

**Comment by zdykstra** [comment]
TravisCI error, if a new build can be kicked off this should pass with out an issue.

**Comment by daniel-eys** [comment]
v45.0.0 dropped python2 support. Do we need to split out a v44.0.0 version for our python2 packages?

**Comment by zdykstra** [comment]
> v45.0.0 dropped python2 support. Do we need to split out a v44.0.0 version for our python2 packages?

Good catch - I wish their [release history](https://pypi.org/project/setuptools/45.3.0/#history) gave any indication that they were dropping support for 2.7 after v45. It does appear to run, but throws a dramatic warning:

```
pip2 -V
/usr/lib/python2.7/site-packages/pkg_resources/py2_warn.py:22: UserWarning: Setuptools will stop working on Python 2
************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please comment in
https://github.com/pypa/setuptools/issues/1458
about the steps that led to this unsupported combination.
************************************************************
  sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
pip 19.3.1 from /usr/lib/python2.7/site-packages/pip (python 2.7)
```

I'll split this package apart into python-setuptools (v44.0.0) and python3-setuptools (v46.0.0). Stand by for the changes!

**Comment by zdykstra** [comment]
I still need to resolve both python3-setuptools and python-setuptools trying to control /usr/bin/easy_install . 

https://travis-ci.org/void-linux/void-packages/jobs/660438659#L1363-L1364
https://travis-ci.org/void-linux/void-packages/jobs/660438659#L1462-L1463

**Comment by zdykstra** [comment]
Pending a review / second set of eyes, this should be good to go.

**Comment by Piraty** [comment]
add a comment to the template mentioning this, sth like:
```
# NOTE: upstream dropped python2 support after 44.0
```

**Comment by zdykstra** [comment]
Added comments to the python-setuptools template, as well as an update pattern override to remove false positive update notifications.

**Comment by Chocimier** [comment]
unzip isn't needed to build, now bsdtar unpacks zip

**Comment by zdykstra** [comment]
> unzip isn't needed to build, now bsdtar unpacks zip

unzip removed from both templates - thanks for the tip on that!

**Comment by Chocimier** [comment]
Quick test shows problem with pkg_resources,will need to test more.

**Comment by Chocimier** [comment]
It was false alarm, everything seems to be fine.

**Pull request merged**
