### PR TITLE
clisp: enable readline by default

### PR DESCRIPTION
**Pull request by Nicop06**

### CODE REVIEW

**Comment by Noah-Huppert** [comment]
@Nicop06 Apply this patch to fix the xlint errors:
```patch
diff --git a/srcpkgs/clisp/template b/srcpkgs/clisp/template
index d0576f7c98..24b782b845 100644
--- a/srcpkgs/clisp/template
+++ b/srcpkgs/clisp/template
@@ -7,11 +7,11 @@ archs="x86_64* i686*"
 build_style=configure
 configure_args="--prefix=/usr --disable-mmap --without-dynamic-modules
  $(vopt_with readline)"
+makedepends="ffcall libsigsegv-devel $(vopt_if readline readline-devel)"
 short_desc="ANSI Common Lisp Interpreter, Compiler and Debugger"
 maintainer="Martin Riese <grauehaare@gmx.de>"
 license="GPL-2"
 homepage="http://clisp.cons.org"
-makedepends="ffcall libsigsegv-devel $(vopt_if readline readline-devel)"
 distfiles="${SOURCEFORGE_SITE}/clisp/clisp-${version}.tar.bz2"
 checksum=8132ff353afaa70e6b19367a25ae3d5a43627279c25647c220641fed00f8e890
 

```

**Comment by Nicop06** [comment]
Thanks for the fix!

**Comment by ericonr** [comment]
See i686 build failure:

```
./lisp.run -B . -N locale -E UTF-8 -Epathname 1:1 -Emisc 1:1 -norc -m 2MW -lp  -x '(and (load "init.lisp") (sys::%saveinitmem) (ext::exit)) (ext::exit t)'
C_CODE_ALIGNMENT is wrong. &CRASH = 0x80e8d52.
Add -falign-functions=4 to CFLAGS in the Makefile.
make: *** [Makefile:1404: interpreted.mem] Aborted (core dumped)
```

Also the xlint ones.

**Comment by ericonr** [comment]
Please fix errors reported by CI. You can run `xlint clisp` to see what's wrong with the template.

**Comment by Nicop06** [comment]
I think the clisp package is not building for target `i686` on `x86_64` machine. I used the following commands on my machine at HEAD and got the same error I see in the CI:

```
$ ./xbps-src -m /var/tmp/void-packages/masterdir-x86 binary-bootstrap i686
$ ./xbps-src -m /var/tmp/void-packages/masterdir-x86 pkg clisp
...
./lisp.run -B . -N locale -E UTF-8 -Epathname 1:1 -Emisc 1:1 -norc -m 2MW -lp  -x '(and (load "init.lisp") (sys::%saveinitmem) (ext::exit)) (ext::exit t)'
C_CODE_ALIGNMENT is wrong. &CRASH = 0x80e4512.
Add -falign-functions=4 to CFLAGS in the Makefile.
make: *** [Makefile:1404: interpreted.mem] Aborted
=> ERROR: clisp-2.49_4: do_build: 'make' exited with 2
=> ERROR:   in do_build() at srcpkgs/clisp/template:32
```

The `x86_64` build is working perfectly.

**Comment by ericonr** [comment]
> Add -falign-functions=4 to CFLAGS in the Makefile.

Define those `CFLAGS` in the template for `i686*`.

**Comment by Nicop06** [comment]
It is actually set, but it doesn't not work. This is a weird issue and it seems to be upstream.

**Comment by ericonr** [comment]
@Nicop06 can you shoot me a link to it upstream?

**Comment by ericonr** [comment]
https://sourceforge.net/p/clisp/bugs/686/ See fix there and perhaps extend it to gcc 9? Not sure.

**Comment by ericonr** [comment]
Yeah, it fails to build from source without readline, our clisp build is from 2016.

@pullmoll do you build `clisp` on your repo?

**Comment by pullmoll** [comment]
Yes, I built clips for `x86_64{,-musl}`:
```
-rw-r--r-- 2 1000 1000 6251395 31. Okt 19:40 /work/void/binpkgs/clisp-2.49_4.x86_64-musl.xbps
-rw-r--r-- 2 1000 1000     512 31. Okt 19:49 /work/void/binpkgs/clisp-2.49_4.x86_64-musl.xbps.sig
-rw-r--r-- 2 1000 1000 6558369 21. Okt 08:25 /work/void/binpkgs/clisp-2.49_4.x86_64.xbps
-rw-r--r-- 2 1000 1000     512 21. Okt 08:58 /work/void/binpkgs/clisp-2.49_4.x86_64.xbps.sig
```

**Comment by ericonr** [comment]
> Since there is no i686{,-musl} I think it failed but have no log at hand currently.

Ok, thank you. So it's probably not a one off.

**Comment by ericonr** [comment]
Ping

**Comment by ericonr** [comment]
@Nicop06 it seems pullmoll fixed the build failure, could you try rebasing this PR?

**Pull request merged**
