### PR TITLE
Pass import

### PR DESCRIPTION
**Pull request by adbrown101**
#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by adbrown101** [comment]
Updated version relies on zxcvbn-python, so I created a module for this. This estimator seemed to work when doing a test export of my password store.

**Comment by adbrown101** [comment]
Will do some more testing to before submitting PR

**Comment by icp1994** [comment]
You need to update `python3-pykeepass` first - the otp support was added in [version 4.0.3](https://github.com/libkeepass/pykeepass/blob/master/CHANGELOG.rst#403---2022-06-21).

**Comment by adbrown101** [comment]
Thanks, I noticed it was failing with python3-pykeepass I have been looking at a PR to update this.

**Comment by icp1994** [comment]
https://github.com/void-linux/void-packages/pull/40636 already updated everything necessary so this should work ootb if you rebase on top of master.

**Comment by adbrown101** [comment]
Thanks, I have created a new pr with just pass-import on it [#40801](https://github.com/void-linux/void-packages/pull/40801)

**Pull request closed without merging**
