### PR TITLE
ulozto-downloader: remove package

### PR DESCRIPTION
**Pull request by realcharmer**
This program was developed for a service that has since shut down, rendering this package outdated and inoperable.

### CODE REVIEW

**Comment by classabbyamp** [comment]
is [this](https://ulozto.net) not the service? where do you see that's it's shut down?

**Comment by realcharmer** [comment]
Sorry, I should have been more clear. Due to new regulations the service was forced to change it's bussines model. It is now impossible to share links with others and the service only works as personal cloud storage. No public file sharing, nor sharing between accounts is now possible.

**Comment by paper42** [comment]
I can confirm this is the case.
Could you add a short description of why this package is being removed to the commit body?

**Comment by realcharmer** [comment]
> Could you add a short description of why this package is being removed to the commit body?

Done.

**Pull request merged**
