### PR TITLE
gcc: update to 10.1.0.

### PR DESCRIPTION
**Pull request by raedwulf**
It compiles at least!

### CODE REVIEW

**Comment by jnbr** [comment]
> It compiles at least!

Really? Some of the patches do not apply.

```
patching file libgo/runtime/go-signal.c
Hunk #1 FAILED at 222.
Hunk #2 FAILED at 343.
2 out of 2 hunks FAILED -- saving rejects to file libgo/runtime/go-signal.c.rej
patching file libgo/sysinfo.c
=> ERROR: gcc-10.1.0_1: pre_configure: 'patch -p0 -i ${FILESDIR}/gccgo-musl.patch' exited with 1
=> ERROR:   in pre_configure() at srcpkgs/gcc/template:178
```

Why did you drop the `invalid_tls_model` patch, is it no necessary anymore?

Besides that, most maintainers would be more comfortable waiting for 10.2, I believe.
gcc-10 changed some defaults, most notably `-fno-common`, switching to it now would mean we would probably have to patch a lot of packages, waiting for upstreams to fix their stuff is the less time consuming way.

**Comment by q66** [comment]
yeah, i intentionally haven't done gcc 10.x yet

**Comment by raedwulf** [comment]
Okay, that makes sense - closing :+1:

**Comment by raedwulf** [comment]
Some updates - for when 10.2 comes around: `invalid_tls_model.patch` might not be necessary because upstream disables tls model for musl targets (different behaviour to the current void patch which disables it for more target types).

I didn't notice the previous musl patch failure because I hadn't realised that some patches were selectively pulled in... When I have a moment, I'll investigate - I have an old pine64 board I want to bring up.

**Comment by pullmoll** [comment]
FWIW the `--disable-target-libiberty` configure option is no good because some packages want to link agains `libiberty`. Found `prelink-cross` and `oprofile` so far.

**Pull request closed without merging**
