### PR TITLE
New package: ytfzf-2.5.0

### PR DESCRIPTION
**Pull request by BryceVandegrift**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

I think that this package should be installed system wide, especially since the addition of man pages to this program. There is also an "addons" system, if that warrants any sort of consideration (addons could be added as separate packages).

### CODE REVIEW

**Comment by classabbyamp** [comment]
> Simple shell scripts are unlikely to be accepted unless they provide considerable value to a broad user base
([CONTRIBUTING.md](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md))

does being system-provided/installed provide any benefits vs just downloading the script?

**Comment by BryceVandegrift** [comment]
Installing it system-wide would provide man pages to user(s) instead of just running it as a local script. Addons are also installed by default into a root-owned directory if that's anything to add. This package is similar to [pass](https://www.passwordstore.org/) in how it is structured, as well as popularity.

**Comment by classabbyamp** [comment]
> would provide man pages

[might want to install those then](https://github.com/void-linux/void-packages/actions/runs/3192341632/jobs/5209745099#step:8:9)

**Comment by BryceVandegrift** [comment]
Oh, sorry about that mistake on my end, I'll fix it.

**Comment by BryceVandegrift** [comment]
That's weird, xlint on my system gives no errors at all.

**Comment by classabbyamp** [comment]
it's the commit lint, which is a separate script.

also, this pr shoukd be one commit

**Comment by BryceVandegrift** [comment]
Ok, the pr should be good.

**Comment by BryceVandegrift** [comment]
Ok, everything looking good?

**Pull request closed without merging**
