### PR TITLE
gtk+3: update to 3.24.23.

### PR DESCRIPTION
**Pull request by travankor**
Also update gtk-layer-shell since this needs a bump, anyways.

### CODE REVIEW

**Comment by ericonr** [comment]
Just released: https://github.com/wmww/gtk-layer-shell/releases/tag/v0.5.0

Any reason to skip it?

**Comment by travankor** [comment]
updated to 0.5.0, but I didn't test it yet

>Any reason to skip it?

so far there only seems this issue https://github.com/wmww/gtk-layer-shell/issues/91

0.5.1 might be out soon

**Comment by ericonr** [comment]
I will try running 0.5.0 locally, if 0.5.1 is out by then we can use it.

**Comment by travankor** [comment]
updated to 0.5.1

**Pull request merged**
