### PR TITLE
xpdf: update to 4.01.01.

### PR DESCRIPTION
**Pull request by asiekierka**

### CODE REVIEW

**Comment by asiekierka** [comment]
Regarding CI:

```
ERROR: requires xbps>=0.55
Bootstrap packages must be updated with 'xbps-src bootstrap-update'
```

**Comment by jnbr** [comment]
CI was restarted. Cross builds fail.

**Comment by Hoshpak** [comment]
The package needs `qt5-qmake` and most likely also `qt5-host-tools` in hostmakedepends for cross builds.

**Comment by Gottox** [comment]
Fixing it after merging. Thanks!

**Comment by asiekierka** [comment]
Oh... sorry for not responding, the package escaped my attention. Thank you for the fix!

**Pull request merged**
