### PR TITLE
xbps-src: multiple performance improvements

### PR DESCRIPTION
**Pull request by xtraeme**
xbps-src: multiple performance improvements

- use xbps-checkvers(1) to resolve dependencies.
- all dependencies are installed at once for the host and target.
- the `show-build-deps` target is now much faster.
- the `update-bulk/show-repo-updates` targets are now much faster.
- the `update-sys/show-sys-updates` targets are now much faster.
- the `bootstrap` target now works on musl hosts.
- simplified some loops.
- use cut(1) rather than awk(1) where applicable.
- multiple random changes to improve performance.

 Based on work started by @Duncaen on https://github.com/void-linux/void-packages/pull/12433

Close https://github.com/void-linux/void-packages/pull/12433
Close https://github.com/void-linux/void-packages/pull/11282

### CODE REVIEW

**Comment by xtraeme** [comment]
CC @pullmoll @Duncaen 

I tested this branch this way:

- xbps-src bootstrap
- xbps-src -Nt pkg xbps
- xbps-src -a aarch64-musl -Nt pkg xbps

@pullmoll please test if you have some time! it's way faster now

**Comment by xtraeme** [comment]
Hmm, my latest change broke cross compilation... looking at it.

**Comment by xtraeme** [comment]
Fixed :-)

**Comment by xtraeme** [comment]
Success! the error is due to xlint being too much strict.

**Comment by xtraeme** [comment]
Please review! I'll push it in 12h approx if there are no objections.

**Comment by jnbr** [comment]
There is a python3 update between these commits.

**Comment by jnbr** [comment]
this looks strange, not sure if related to python bump or other changes
```
=> python3-3.6.9_1: running post-install hook: 06-strip-and-debug-pkgs ...
   Stripped position-independent executable: /usr/bin/python3.6m
   Stripped position-independent executable: /usr/bin/python3.6
objcopy: /destdir//python3-3.6.9/usr/bin/stHxfGoT: debuglink section already exists
```

**Comment by xtraeme** [comment]
@jnbr I added the python3 update for testing. About objcopy, this is normal behaviour with hard links.

```
[juan@leysa ~]$ stat --printf='%i\n' /usr/bin/python3.6{,m}
1451894
1451894
[juan@leysa ~]$
```

**Comment by xtraeme** [comment]
I'm running a bulk build via xbps-fbulk(1) for x86_64-musl. Will report results when it's finished.

**Comment by xtraeme** [comment]
```
x86_64-musl bulk build started at 2019-07-04 12:24:08.269790074 +0200
x86_64-musl bulk build 16% completed, 14% success
  Total:   7011
  Success: 1019
  Fail:    36
  Skipped: 56
  Depfail: 70
```

My poor i5-3550 (ivybridge) is getting hot...

**Comment by pullmoll** [comment]
Sorry, I'm currently too busy to test xbps.

**Comment by Piraty** [comment]
@xtraeme don't rush things please

**Comment by xtraeme** [comment]
I'm not rushing anything, @Piraty 

I'm running a bulk build for testing.

**Comment by xtraeme** [comment]
```
(x86_64-musl) started at 2019-07-04 15:19:02.197073026 +0200
(x86_64-musl) 1762 of 7011 processed, 163 failed (36 failed, 50 skipped, 77 deps)
```

Still running, let's hope it does not take the whole weekend :-)

**Comment by xtraeme** [comment]
```
x86_64-musl) started at 2019-07-04 15:19:02.197073026 +0200
(x86_64-musl) 2469 (35%) of 7011 processed, 2224 ok, 245 failed (76 skipped, 109 deps)
```

**Comment by xtraeme** [comment]
```
(x86_64-musl) started at 2019-07-04 15:19:02.197073026 +0200
(x86_64-musl) 2469 (35%) of 7011 processed, 2224 ok, 245 failed (76 skipped, 109 deps)
```

Looks like I ran out of space and some pkgs failed. Will restart after the first pass.

I can see that only packages that use "virtual?" now fail, will get fixed for the next pass.

**Comment by pullmoll** [comment]
Shoot me.

**Comment by pullmoll** [comment]
Reverted except for the python3 and pkg-config updates.

**Comment by xtraeme** [comment]
Ok, no problem @pullmoll

**Comment by xtraeme** [comment]
I fixed the issue with packages that had `depends="virtual?foo"`.

```
(x86_64) started at 2019-07-06 08:23:32.854570446 +0200
(x86_64) 4512 (64%) of 7010 processed, 2232 ok, 2280 failed (47 skipped, 2175 deps)
```

I also moved to another fs with 250GB, so that it's building pkgs that failed previously due to ENOSPC.

I'll report results soon :-)

**Comment by xtraeme** [comment]
This is the final version. No issues compared to current master. All build issues are unrelated to these changes (missing distfiles, gcc-9.x warnings, broken dependencies).

**Comment by xtraeme** [comment]
Also added a check to verify that all dependencies exist:

```
[juan@leysa void-packages]$ ./xbps-src -Nt install autofs
=> autofs-5.1.5_3: building [gnu-configure] ...
=> ERROR: autofs-5.1.5_3: host dependency 'rpcgen' does not exist!
[juan@leysa void-packages]$
```

**Comment by xtraeme** [comment]
Please test and review, will merge next friday if no objections.

**Pull request merged**
