### PR TITLE
cargo-bootstrap: Update to 1.59.0

### PR DESCRIPTION
**Pull request by subnut**
DRAFT because I think we probably also need to update the `cargo` package too?  
**IDK.** Let me know if you think this is appropriate to merge as-is, and I wil un-draft it. :slightly_smiling_face: 

#### Testing the changes
- I tested the changes in this PR: **NO**

### CODE REVIEW

**Comment by subnut** [comment]
@q66 Please review.  
(I made some pretty drastic changes, not gonna lie :sweat_smile:)

**Comment by q66** [comment]
rust, rust-bootstrap, cargo, cargo-bootstrap are always updated together in a single PR

**Comment by q66** [comment]
(those changes are also incorrect, the ppc special case should *not* be removed)

**Comment by subnut** [comment]
@q66 

Okay. So what should be the updated value of `version` ?  
Or should I keep `version` as-it-is and bump `revision` instead?  
Or something else?

**Pull request closed without merging**
