### PR TITLE
build-style/qmake: look for modules in target

### PR DESCRIPTION
**Pull request by sgn**
- With this added, we can remove qt5*-devel from hostmakedepends
- [ci skip]

### CODE REVIEW

**Comment by ericonr** [comment]
Nice! What kind of testing have you managed to do?

**Comment by sgn** [comment]
On 2021-02-09 16:18:30-0800, Érico Nogueira Rolim <notifications@github.com> wrote:
> Nice! What kind of testing have you managed to do?

$ git grep 'build_helper=.*qmake' srcpkgs/ | wc -l
12

Just build them all :-D

**Comment by sgn** [comment]
Ah, no, this is build-style :-p

**Comment by sgn** [comment]
I'll merge this after OpenSSL rebuild.

**Pull request merged**
