### PR TITLE
pulseaudio: remove rtkit dependency and update to 14.2

### PR DESCRIPTION
**Pull request by ericonr**
PulseAudio doesn't need rtkit available to work for basic usage, so
it's better to only pull it in when a user wants realtime (the error
messages should also be clear enough).

Since rtkit now pulls in a complex dependency in polkit, we can avoid
pulseaudio also pulling the whole thing in.

I have yet to test this throroughly. Basic functionality is fine.

@q66

### CODE REVIEW

**Comment by q66** [comment]
no, not really

this will just result in 1) people not knowing what to install when they need it 2) rtkit becoming an orphan and getting autoremoved on existing systems

you just shouldn't have added polkit dependency in rtkit in the first place

**Comment by fosslinux** [comment]
Why not, https://github.com/heftig/rtkit/blob/master/README#L226 says it is needed (is upstream just wrong about requirements for their own software (wouldn't be the first time lol))

**Comment by ericonr** [comment]
@fosslinux it's optional only because they can use it to determine where to dump the polkit config file https://github.com/heftig/rtkit/blob/c295fa849f52b487be6433e69e08b46251950399/meson.build#L53

**Comment by fosslinux** [comment]
Oh, duh, silly me! Yeah, ofc it wont detect for runtime at buildtime lol

**Pull request merged**
