### PR TITLE
libxml2: update to 2.12.1.

### PR DESCRIPTION
**Pull request by mhmdanas**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by classabbyamp** [comment]
reverted: https://github.com/void-linux/void-packages/commit/343da92d12bafa2a7b43f91b92760016946958b0

breaks inkscape build:
```
../src/object/uri.cpp: In constructor 'Inkscape::URI::URI(const gchar*, const char*)':
../src/object/uri.cpp:86:9: error: 'xmlFree' was not declared in this scope; did you mean 'xmlFreeURI'?
   86 |         xmlFree(full);
      |         ^~~~~~~
      |         xmlFreeURI
../src/object/uri.cpp:89:9: error: 'xmlFree' was not declared in this scope; did you mean 'xmlFreeURI'?
   89 |         xmlFree(escaped);
      |         ^~~~~~~
      |         xmlFreeURI
../src/object/uri.cpp: In member function 'std::string Inkscape::URI::str(const char*) const':
../src/object/uri.cpp:292:9: error: 'xmlFree' was not declared in this scope; did you mean 'xmlFreeURI'?
  292 |         xmlFree(saveuri);
      |         ^~~~~~~
      |         xmlFreeURI
```

**Comment by mhmdanas** [comment]
Oops, I'll take a look at it later

**Comment by leahneukirchen** [comment]
Fix for inkscape:

```
--- a/src/object/uri.h
+++ b/src/object/uri.h
@@ -13,6 +13,7 @@
 #define INKSCAPE_URI_H
 
 #include <libxml/uri.h>
+#include <libxml/xmlmemory.h>
 #include <memory>
 #include <string>
 
```

**Comment by mhmdanas** [comment]
I did some mass builds, the bump breaks at least dozens of packages in a similar way. :/

**Pull request merged**
