### PR TITLE
corectrl: update to 1.1.1; fix dependencies

### PR DESCRIPTION
**Pull request by not-chicken**
[ci skip] as only a runtime dependency was added

### CODE REVIEW

**Comment by xtraeme** [comment]
this still does not seem to work on musl, dunno why.

**Comment by not-chicken** [comment]
I had some weird experience on musl as well. I was getting something like 
```
can't load Qt5Quick.so.5 Exec error ( required by /usr/lib/libcorectrl.so)
can't load Qt5Qml.so Exec error ( required by /usr/lib/libcorectrl.so)
libcorectrl.so <some random looking string> Symbol not found 
....
....
```

What eventually fixed it for me was  `xbps-install -ff qt5-declarative` as that's what provided those qt shlibs. So I assumed it was just a issue on my system.

Perhaps you are getting similar errors as well or something else?

**Comment by not-chicken** [comment]
@xtraeme Can you test again and report back the error you are facing on musl? It seems to work fine on musl for me.

I have force pushed to remove `ci skip` to let it build against new qt5 in the repos.

**Comment by ericonr** [comment]
On musl, if it matters:

```
[28-09-20 22:51:36.301][W] glxinfo command failed
[28-09-20 22:51:36.365][W] No translation found for locale en_US
[28-09-20 22:51:36.365][W] Using en_EN translation.
QDBusArgument: read from a write-only object
QDBusArgument: read from a write-only object
QDBusArgument: read from a write-only object
[28-09-20 22:51:36.447][W] Cannot start helper
[28-09-20 22:51:36.447][W] Initialization failed
[28-09-20 22:51:36.447][W] Exiting...
```

**Comment by not-chicken** [comment]
> On musl, if it matters:
> 
> ```
> [28-09-20 22:51:36.301][W] glxinfo command failed
> [28-09-20 22:51:36.365][W] No translation found for locale en_US
> [28-09-20 22:51:36.365][W] Using en_EN translation.
> QDBusArgument: read from a write-only object
> QDBusArgument: read from a write-only object
> QDBusArgument: read from a write-only object
> [28-09-20 22:51:36.447][W] Cannot start helper
> [28-09-20 22:51:36.447][W] Initialization failed
> [28-09-20 22:51:36.447][W] Exiting...
> ```

Could you be using a wm without any polkit agent? There's this issue https://gitlab.com/corectrl/corectrl/-/issues/40

I installed sway and ootb I got the same error as you. Then I installed `polkit-gnome` and added `exec /usr/libexec/polkit-gnome-authentication-agent-1` to sway config, then I got the prompt to enter root password.

**Comment by ericonr** [comment]
hmm, should this depend on `polkit`, then?

**Comment by not-chicken** [comment]
> hmm, should this depend on `polkit`, then?

It already pulls in that via `kauth`. As for an authentication agent, almost all DEs already contain one, so hard dep on a particular one wouldn't be a good idea imo.

**Comment by ericonr** [comment]
Got it, no problem.

**Pull request merged**
