### PR TITLE
gnome-shell: add gnome-menus dependency

### PR DESCRIPTION
**Pull request by oreo639**
This fixes translations for the default folders i.e. X-GNOME-Utilities.

#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by classabbyamp** [comment]
should gnome-menus be revbumped?

**Comment by oreo639** [comment]
No, gettext is a build time dependency.

**Comment by classabbyamp** [comment]
right, does it change the resultant package?

**Comment by oreo639** [comment]
No.

**Comment by classabbyamp** [comment]
oh, i see the edit

**Pull request merged**
