### PR TITLE
beets: update to 1.5.0.

### PR DESCRIPTION
**Pull request by TinfoilSubmarine**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

Added new dependencies. Specifically, the beets devs factored out some functionality into mediafile and confuse. reflink and py7zr are needed for new functionality added.

### CODE REVIEW

**Comment by TinfoilSubmarine** [comment]
This is really bizarre. x86_64, x86_64-musl, and aarch64 are successfully building on my machine (with passing check/test).

**Comment by TinfoilSubmarine** [comment]
This is really bizarre. x86_64, x86_64-musl, and aarch64 are successfully building on my machine (with passing check/test).

**Comment by ericonr** [comment]
This PR will definitely wait until the python 3.10 update. Please ping me if I forget.

**Comment by ericonr** [comment]
One more rebase and we should be good >.<

**Comment by paper42** [comment]
py7zr is listed in extra -> test dependencies, is it really required? Without it, we would avoid 6 new packages - pyzstd, pyppmd, pybcj, multivolumefile, Brotli.

**Comment by TinfoilSubmarine** [comment]
It's not just a test dependency, it's also optionally required for beets at runtime.

**Pull request merged**
