### PR TITLE
New package: hyfetch-1.4.1

### PR DESCRIPTION
**Pull request by Gingeh**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (i386)

### CODE REVIEW

**Comment by classabbyamp** [comment]
as cool as i think this package is, we don't generally package forks of existing packages, and we already have enough sysinfo-showing-commands packaged

**Comment by VitaMoonshadow** [comment]
Heii! is there any chance of this PR being reopened now that neofetch is officially dead? 
I use the pipx package of hyfetch but since it needs the virtual environment, its quite slow.
also, im not sure if the neofetch package should get deleted or turned into a dummy package for smthn like hyfetch or fastfetch, like is done with polymc and prism launcher for example. of course its unmaintained, but you could also consider it finished...

**Comment by VitaMoonshadow** [comment]
oh also, i dont really know how to use github tbh. i updated the template to 1.4.11 (latest version of hyfetch) and it workson my mashine. if i wasnt such an idiot id prolly merge it into this PR, but im too stoopid for that😭

I'll just send the updated template in this comment here for now till i figure this all out lmaoo

```
# Template file for 'hyfetch'
pkgname=hyfetch
version=1.4.11
revision=1
build_style=python3-module
makedepends="python3-setuptools python3-typing_extensions"
depends="python3 python3-setuptools python3-typing_extensions"
short_desc="Neofetch with LGBTQ pride flags"
maintainer="Gingeh <pugdogbeagledog@gmail.com>"
license="MIT"
homepage="https://github.com/hykilpikonna/hyfetch"
changelog="${homepage}/releases/tag/${version}"
distfiles="${homepage}/archive/refs/tags/${version}.tar.gz"
checksum=79cd6706a681fa7c05754b35d9338abf96bebce222c27376a4155e94d6a5350d

post_install() {
	vlicense LICENSE.md
}
```
I'd also consider maybe changing the pkgname to python3-hyfetch to fit with the naming convention.

**Comment by Zeitsperre** [comment]
I would also like to see this package be adopted into Void. Is there a way of letting users know that `neofetch` is no longer maintained?

(Unrelated, but the fact that the original developer of neofetch, @dylanarp, has their profile set to say that they've taken up farming is wonderful; I can totally respect that.)

**Comment by classabbyamp** [comment]
is neofetch *that critical* that users need to move away from it immediately now that upstream development has stopped?

`fastfetch` was packaged as an alternative after neofetch was archived

**Comment by Piecuuu** [comment]
I think that this should just be pulled in anyways. I'm confidently saying that, since so many distros already have it in their repos. Maybe not as much as `fastfetch`, but it's still something. Either way, I don't see any reason not to adopt this package.

**Pull request closed without merging**
