### PR TITLE
base-files+eudev: move kvm.rules from base-files to eudev

### PR DESCRIPTION
**Pull request by sgn**
Prior to 33d781ff19 (base-files: update to 0.120., 2015-03-22).
We don't requires the existence of `kvm` groups.

Since that change, we ship a udev rule with `base-files`, hence the need
of `kvm` groups.

It's more than 5 years from the change, kvm should be available
in all installation.

Simply removing "system_accounts=kvm:24" from base-files may cause
problem with those very old installation.

Let move those statements and the udev rules to eudev instead.
When moving the rules, rename it to allow partial upgrade,
otherwise, we'll run into conflicts.

### CODE REVIEW

**Comment by CameronNemo** [comment]
How does this work if somebody wants to try out an alternative device manager (like mdev, which is part of the busybox-huge package)? I presume both packages will have to declare the group, but what happens when one or the other is uninstalled? Does the group stay?

**Comment by sgn** [comment]
The problem should be fixed by #24812, I think this is not necessary anymore?

**Comment by ericonr** [comment]
> The problem should be fixed by #24812, I think this is not necessary anymore?

I think I would still like to see it done. The way it's been implemented currently is not great.

@CameronNemo 

> How does this work if somebody wants to try out an alternative device manager

Can `mdev` use udev rules files in the udev location?

> Does the group stay?

It does, with a small note that the package requiring it was removed.

**Comment by CameronNemo** [comment]
>Can mdev use udev rules files in the udev location?

No, mdev uses its own more restricted configuration format.

>It does, with a small note that the package requiring it was removed.

That may be manageable, although somewhat misleading.

**Pull request closed without merging**
