### PR TITLE
e3: remove package

### PR DESCRIPTION
**Pull request by meator**
Upstream is dead. The only e3 source archive that I was able to find is http://ftp.uni-kl.de/pub/linux/gentoo/distfiles/9a/e3-2.82.tgz ~~This has a lower version than the version in the template.~~

#### Testing the changes
- I tested the changes in this PR: kinda, one can't really test removed packages

### CODE REVIEW

**Comment by classabbyamp** [comment]
is the distfile you linked not the same version as our template?

**Comment by meator** [comment]
> is the distfile you linked not the same version as our template?

Sorry, you are right. Should I change it? The fact that there is a distfile on the internet doesn't change the fact that upstream is dead. I don't know what should I put into homepage.

**Comment by sgn** [comment]
Available in Debian, too https://packages.debian.org/bookworm/e3
I vote for keep.

**Comment by meator** [comment]
That thing is dead. It has vanished. There are no traces of it on the internet except that one random link. There's no homepage. That thing is never getting an update. Why do you want to keep it?

**Comment by leahneukirchen** [comment]
Arch uses https://drive.google.com/uc?export=download&id=1ZNWI-Fl7Zc69H0hX1WpLpwG9mxUcZf30 as distfile %)

**Comment by leahneukirchen** [comment]
Fixed in c5ade815970

**Pull request closed without merging**
