### PR TITLE
rofi: update to 1.7.0.

### PR DESCRIPTION
**Pull request by ram02z**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ram02z** [comment]
Hmm, I tried to recompile 1.6.1 and it also segfaulted, so I thought it might have been my machine. I'll report this to upstream.

**Comment by ericonr** [comment]
If they run tests in CI, try to see what packages they install.

**Comment by ahesford** [comment]
For some reason, the `textbox_test` executable crashes when making a call into pango from `xbps-src`. The same executable runs fine when run from the host. Maybe it's an X11 thing? (Although blanking `$DISPLAY` doesn't cause a problem.) All other tests pass.

If the `textbox_test` failure is too much of a pain to resolve, maybe skipping that test is sufficient so we can at least run others.

**Comment by ram02z** [comment]
>
> If the `textbox_test` failure is too much of a pain to resolve, maybe skipping that test is sufficient so we can at least run others.

Yeah after comparing other templates, I can't seem to find a resolution. I used the `XFAIL_TESTS` variable to skip the test. I don't have much experience with automake, so let me know if there is another approach.

**Comment by ahesford** [comment]
You need `which` in `hostmakedepends`, the build is trying to run it for something.

Also, make the checks depend on whether xbps-src actually enables checks:
```sh
if [ "$XBPS_CHECK_PKGS" ]; then
	makedepends+=" check-devel"
else
	configure_args+=" --disable-check"
fi
```

**Pull request closed without merging**
