### PR TITLE
New package: Rocket.Chat-Desktop-2.17.11

### PR DESCRIPTION
**Pull request by Johnnynator**

### CODE REVIEW

**Comment by Anachron** [comment]
I'm so happy we have a shared electron pkg now.

**Comment by Anachron** [comment]
Btw. Should we auto set NODE_ENV=production in a xbps hook?

**Comment by Johnnynator** [comment]
> Btw. Should we auto set NODE_ENV=production in a xbps hook? (Check for nodejs in depends)

No, it should be either unconditional or behind a build_style/helper.

**Comment by Anachron** [comment]
Sorry, I meant xbps-src build-helper.

**Comment by Johnnynator** [comment]
> Sorry, I meant xbps-src build-helper.

Yeah, maybe. Point it out in #23947

**Pull request merged**
