### PR TITLE
Revert "chroot-git: simplify and avoid gettext dependency."

### PR DESCRIPTION
**Pull request by sgn**
This reverts commit aa1e576abe9b001879da67da2728e13d71be025d.
Fix cross-compile chroot-git.

@xtraeme

### CODE REVIEW

**Comment by sgn** [comment]
Actually, I want to get rid of configure stuff in git and chroot-git.
Upstream recommends to craft `config.mak` by hand and ignore `configure` entirely.

https://lore.kernel.org/git/xmqq4kxiiuba.fsf@gitster-ct.c.googlers.com/

https://lore.kernel.org/git/xmqqefxe33t5.fsf@gitster.mtv.corp.google.com/

**Comment by pullmoll** [comment]
I thin we can remove the dependency on gettext altogether. In almost every case the person using git is a developer or experienced user and will be able to grok messages in English. If she cannot, she can still report the message in a problem report.

**Comment by xtraeme** [comment]
Wtf? So you want to add back gettext dependency in the host again? No way

**Comment by xtraeme** [comment]
Fix this by other means than reverting

**Comment by pullmoll** [comment]
https://github.com/void-linux/void-packages/commit/08e5cef0145fcf713802a19318b72c681b70a0c7

**Comment by sgn** [comment]
No, it's only partial revert.
The problem is `--with-zlib=$XBPS_MASTER/usr`

`NO_GETTEXT=Yes` in config should be enough to ignore gettext.

**Comment by sgn** [comment]
Well, the build is broken, https://build.voidlinux.org/builders/aarch64-musl_builder/builds/26213/steps/shell_3/logs/stdio

I fast tracked 77ea0f30d99756d5529d976962bd78881fc0d1eb to fix it.

**Pull request closed without merging**
