### PR TITLE
New package: lean3-community-3.42.1

### PR DESCRIPTION
**Pull request by tornaria**
This is an updated version of #32559.

Recently (maybe a cmake update) there is a test failure that seems to be related to cmake. Here's the relevant part of the output of `./xbps-src check lean-community`:
```
[0/1] Running tests...
Test project /builddir/lean-3.40.0/src/build
          Start    1: style_check
   1/1427 Test    #1: style_check .................................................***Failed   26.22 sec
/builddir/lean-3.40.0/src/build/CMakeFiles/3.22.2/CompilerIdCXX/CMakeCXXCompilerId.cpp:0:  No copyright message found.  You should have a line: "Copyright [year] <Copyright Owner>"  [legal/copyright] [5]
/builddir/lean-3.40.0/src/build/CMakeFiles/3.22.2/CompilerIdCXX/CMakeCXXCompilerId.cpp:50:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
/builddir/lean-3.40.0/src/build/CMakeFiles/3.22.2/CompilerIdCXX/CMakeCXXCompilerId.cpp:54:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
/builddir/lean-3.40.0/src/build/CMakeFiles/3.22.2/CompilerIdCXX/CMakeCXXCompilerId.cpp:130:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
/builddir/lean-3.40.0/src/build/CMakeFiles/3.22.2/CompilerIdCXX/CMakeCXXCompilerId.cpp:139:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
/builddir/lean-3.40.0/src/build/CMakeFiles/3.22.2/CompilerIdCXX/CMakeCXXCompilerId.cpp:149:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
/builddir/lean-3.40.0/src/build/CMakeFiles/3.22.2/CompilerIdCXX/CMakeCXXCompilerId.cpp:154:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
/builddir/lean-3.40.0/src/build/CMakeFiles/3.22.2/CompilerIdCXX/CMakeCXXCompilerId.cpp:291:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
/builddir/lean-3.40.0/src/build/CMakeFiles/3.22.2/CompilerIdCXX/CMakeCXXCompilerId.cpp:313:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
/builddir/lean-3.40.0/src/build/CMakeFiles/3.22.2/CompilerIdCXX/CMakeCXXCompilerId.cpp:670:  Missing space after ,  [whitespace/comma] [3]
/builddir/lean-3.40.0/src/build/CMakeFiles/3.22.2/CompilerIdCXX/CMakeCXXCompilerId.cpp:675:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
/builddir/lean-3.40.0/src/build/CMakeFiles/3.22.2/CompilerIdCXX/CMakeCXXCompilerId.cpp:681:  Missing space after ,  [whitespace/comma] [3]
/builddir/lean-3.40.0/src/build/CMakeFiles/3.22.2/CompilerIdCXX/CMakeCXXCompilerId.cpp:688:  Missing space after ,  [whitespace/comma] [3]
/builddir/lean-3.40.0/src/build/CMakeFiles/3.22.2/CompilerIdCXX/CMakeCXXCompilerId.cpp:689:  Missing space after ,  [whitespace/comma] [3]
/builddir/lean-3.40.0/src/build/CMakeFiles/3.22.2/CompilerIdCXX/CMakeCXXCompilerId.cpp:690:  Missing space after ,  [whitespace/comma] [3]
/builddir/lean-3.40.0/src/build/CMakeFiles/3.22.2/CompilerIdCXX/CMakeCXXCompilerId.cpp:699:  Missing space after ,  [whitespace/comma] [3]
/builddir/lean-3.40.0/src/build/CMakeFiles/3.22.2/CompilerIdCXX/CMakeCXXCompilerId.cpp:704:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
/builddir/lean-3.40.0/src/build/CMakeFiles/3.22.2/CompilerIdCXX/CMakeCXXCompilerId.cpp:710:  Missing space after ,  [whitespace/comma] [3]
/builddir/lean-3.40.0/src/build/CMakeFiles/3.22.2/CompilerIdCXX/CMakeCXXCompilerId.cpp:768:  { should almost always be at the end of the previous line  [whitespace/braces] [4]
/builddir/lean-3.40.0/src/build/githash.h:0:  No copyright message found.  You should have a line: "Copyright [year] <Copyright Owner>"  [legal/copyright] [5]
/builddir/lean-3.40.0/src/build/version.h:0:  No copyright message found.  You should have a line: "Copyright [year] <Copyright Owner>"  [legal/copyright] [5]
Total errors found: 21
```

This may be related to the following warning that is output by `./xbps-src configure lean-community`:
```
CMake Warning (dev):
  Policy CMP0058 is not set: Ninja requires custom command byproducts to be
  explicit.  Run "cmake --help-policy CMP0058" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  This project specifies custom command DEPENDS on files in the build tree
  that are not specified as the OUTPUT or BYPRODUCTS of any
  add_custom_command or add_custom_target:

   CMakeFiles/3.22.2/CompilerIdCXX/CMakeCXXCompilerId.cpp

  For compatibility with versions of CMake that did not have the BYPRODUCTS
  option, CMake is generating phony rules for such files to convince 'ninja'
  to build.

  Project authors should add the missing BYPRODUCTS or OUTPUT options to the
  custom commands that produce these files.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

Any help with this is appreciated. I'm sure this was working ok recently.

Another issue is a test failing on i686 only (cf https://github.com/leanprover-community/lean/issues/685) is there an easy way to disable a particular test for i686?

### CODE REVIEW

**Comment by tornaria** [comment]
cc @eloitor

**Comment by leahneukirchen** [comment]
Please name this lean3-community, as lean3 and lean4 will coexist for forseeable future.

**Comment by leahneukirchen** [comment]
Just patch out buggy tests, we don't need to check upstream coding conventions for our builds.

The one you found on i686 looks like a real bug at first, however. Can you reproduce that in a LSP editor?

**Comment by tornaria** [comment]
> Just patch out buggy tests, we don't need to check upstream coding conventions for our builds.

That was not obvious. I had to rewrite `do_check()` to use `ctest -E <regex>`. The build-style uses `ninja test` for this, but I didn't see a way to pass options to `ctest`.

I wish xbps-src had some tools to make skipping tests by name easier for the standard test frameworks (cmake, autotools, pytest, etc).

> The one you found on i686 looks like a real bug at first, however. Can you reproduce that in a LSP editor?

I've just disabled since I don't want to worry about 32 bit right now.

TBH, I don't yet know how to actually USE lean locally -- I want to learn lean so I've been playing with some of the tutorials using the online version. I don't have a clue how to move forward with this. Apparently I need more stuff, like `leanproject` to install mathlib, etc. And I take that this cannot be run from CLI, I need some sort of plugin (unfortunately, it seems there is no vim plugin, only a neovim one).

**Comment by ram02z** [comment]
>  Apparently I need more stuff, like `leanproject` to install mathlib, etc.

I have packaged mathlib-tools (https://github.com/void-linux/void-packages/pull/33587). It contains leanproject, which will update mathlib per project.

**Comment by tornaria** [comment]
On x86_64-musl:
```
The following tests FAILED:
	492 - leanruntest_all (Timeout)
	639 - leanruntest_async_map.lean (Failed)
```

**Comment by Eloitor** [comment]
Maybe we should package https://github.com/leanprover/elan too... Different lean projects require different versions of lean, and `elan` ensures you use the correct version with each project.

**Comment by Eloitor** [comment]
I updated the template to 3.49.0 and now there is only one test that fails due to a timeout in my old computer. Maybe the CI build does not have this timeout. Maybe we can disable the timeout or remove this test... Which option is best?
 
```
495/1438 Test  #493: leantest_wrong_arity.lean ...................................   Passed    0.01 sec
          Start  495: leanruntest_all
 496/1438 Test  #495: leanruntest_all .............................................***Timeout 1500.12 sec
connect
recv
[S, E, C, R, E, T, _, D, A, T, A]

          Start  496: leanruntest_1010.lean
 497/1438 Test  #496: leanruntest_1010.lean .......................................   Passed    3.10 sec
          Start  497: leanruntest_1089.lean

[ more output ]


99% tests passed, 1 tests failed out of 1438

Total Test time (real) = 4973.43 sec

The following tests FAILED:
	495 - leanruntest_all (Timeout)
Errors while running CTest
```

**Pull request closed without merging**
