### PR TITLE
[RFC] build-style: go: allow pie

### PR DESCRIPTION
**Pull request by sgn**

### CODE REVIEW

**Comment by sgn** [comment]
Actually, I tend to drop `darch` entirely. No other distros  ship it, the template file (before clean-up) is a mess

**Comment by shizonic** [comment]
Nope not anymore. Thanks for asking!

**Comment by ericonr** [comment]
Do you want to roll this into a general Go rebuild? Since there were a few Go CVEs lately, the idea would be to rebuild all that's possible to rebuild, and we could take the opportunity to also test PIE. I have a list of the Go packages which I succcessfully built, and I can try them again with these changes to the Go build style.

But a few packages will have to wait for https://github.com/golang/go/issues/42567 to be solved as well, since it breaks `LDFLAGS=-fuse-ld=bfd` for some packages.

**Comment by sgn** [comment]
On 2020-11-13 22:23:52-0800, Érico Nogueira Rolim <notifications@github.com> wrote:
> Do you want to roll this into a general Go rebuild? Since there were
> a few Go CVEs lately, the idea would be to rebuild all that's
> possible to rebuild, and we could take the opportunity to also test
> PIE. I have a list of the Go packages which I succcessfully built,
> and I can try them again with these changes to the Go build style.

I'm flooded with issues irl. I couldn't find time to rebuild all go
packages to check.

If you would like, you could take over.

Thanks,

> 
> But a few packages will have to wait for https://github.com/golang/go/issues/42567 to be solved as well, since it breaks `LDFLAGS=-fuse-ld=bfd` for some packages.

**Comment by ericonr** [comment]
I can take over, sure.

**Comment by ericonr** [comment]
I'm going to list issues I find here:

`go-bindata` built in PIE mode on musl somehow ends up linked to `/lib64/ld-linux-x86-64.so.2`

**Comment by ericonr** [comment]
I think the issue above breaks this proposal completely, unless we can reliably hunt them down.

On the other hand, templates like rclone could be built with PIE and that would solve the issue they had ( https://github.com/ericonr/void-packages/tree/rclone ). So I think we should push forward with a simple way for go binaries to be built with PIE, but not change any defaults yet.

**Comment by sgn** [comment]
On 2020-11-23 10:18:37-0800, Érico Nogueira Rolim <notifications@github.com> wrote:
> I think the issue above breaks this proposal completely, unless we can reliably hunt them down.
> 
> On the other hand, templates like rclone could be built with PIE and
> that would solve the issue they had
> ( https://github.com/ericonr/void-packages/tree/rclone ). So I think
> we should push forward with a simple way for go binaries to be built
> with PIE, but not change any defaults yet.

I think we can add "nopie=yes" en mass to all go-package, then remove
them on a case-by-case basis.

-- 
Danh

**Comment by ericonr** [comment]
> I think we can add "nopie=yes" en mass to all go-package, then remove
them on a case-by-case basis.

Ok, that sounds reasonable.

**Comment by ericonr** [comment]
For the record, alpine is using `-buildmode=pie` for all platforms.

**Pull request closed without merging**
