### PR TITLE
seafile client: update to 7.0.8

### PR DESCRIPTION
**Pull request by yopito**

### CODE REVIEW

**Comment by q66** [comment]
this adds a webengine dependency which will break several targets (all 32-bit cross + native that don't support webengine)

use https://github.com/haiwen/seafile-client/commit/552fb023163db9554eeaa5063bc38a86b01e4e22

**Comment by yopito** [comment]
@q66: thanks for pointing this.  
But it makes funny thing while using cmake files of qt5-webkit.  
Perhaps because qt5-webkit need to be rebuilt with qt5 5.15 ?

here this output on seafile 7.0.8 builds:
```
Build type: Release                                                                                                                                    
qt5 version: 5.15.0                                                                                                                                    
CMake Error at /usr/lib64/cmake/Qt5/Qt5Config.cmake:28 (find_package):                                                                                 
  Found package configuration file:                                                                                                                    
                                                                                                                                                       
    /usr/lib64/cmake/Qt5WebKit/Qt5WebKitConfig.cmake                                                                                                   
                                                                                                                                                       
  but it set Qt5WebKit_FOUND to FALSE so package "Qt5WebKit" is considered to                                                                          
  be NOT FOUND.  Reason given by package:                                                                                                              
                                                                                                                                                       
  Qt5WebKit could not be found because dependency is required to have exact                                                                            
  version 5.14.x.                                                                                                                                      
                                                                                                                                                       
Call Stack (most recent call first):                                                                                                                   
  CMakeLists.txt:192 (FIND_PACKAGE)                                                                                                                    
                                                                                                                                                       
                                                                                                                                                       
-- Configuring incomplete, errors occurred!                                                                                                            
See also "/builddir/seafile-client-7.0.8/build/CMakeFiles/CMakeOutput.log".                                                                            
```

**Comment by q66** [comment]
yes, can you try rebuilding it? we can bump it once confirmed

**Comment by yopito** [comment]
rebuild qt5-webkit with qt 5.15 is fine on x86_64/musl.  
then build and basic run seafile-7.0.8 succeeded too.  
I let you rebuild qt5-webkit ?

**Comment by q66** [comment]
pushed the bump

**Comment by yopito** [comment]
@q66: thanks for your help. Here the right packaging.

**Pull request merged**
