### PR TITLE
postgresql: fix shell version of pg_config.sh

### PR DESCRIPTION
**Pull request by sgn**
@xtraeme @pullmoll Please help to pull this.
Sorry, but I've another thing to do.
The old version (#20783) may work because echo doesn't accept -W -f -L -l by now

### CODE REVIEW

**Comment by xtraeme** [comment]
@pullmoll please take care of it

**Comment by Piraty** [comment]
why now make echo a function
```
echo() { printf '%s\n' "$@" ; }
```

**Comment by sgn** [comment]
> why now make echo a function
> 
> ```
> echo() { printf '%s\n' "$@" ; }
> ```

That would work, too.
I'll change it that way.

**Comment by xtraeme** [comment]
Hmm better use print. An echo func might conflict

**Comment by pullmoll** [comment]
LGTM

**Pull request merged**
