### PR TITLE
wps-office: fix checksum

### PR DESCRIPTION
**Pull request by shizonic**

### CODE REVIEW

**Comment by mobinmob** [comment]
The file changed for the same release? That is new...
I have a PR for the latest version: https://github.com/void-linux/void-packages/pull/14568

**Comment by shizonic** [comment]
Indeed but it didn't build on my machine until i updated the checksum. Anyway it's not necessary to merge it if there is a PR for the latest version.

**Comment by mobinmob** [comment]
Upstream must have changed the rpm :) 

> Indeed but it didn't build on my machine until i updated the checksum. 

Upstream probably changed the rpm the template uses.

**Comment by mobinmob** [comment]
> Anyway it's not necessary to merge it if there is a PR for the latest version.

Well, the current template doesn't work, I think it is necessary since it is a restricted package. I am waiting for review in the PR - licensing change...

**Comment by Hoshpak** [comment]
Since the package has been updated in the meantime, I assume this one is obsolete now.

**Pull request closed without merging**
