### PR TITLE
rpi-kernel: update to 6.1.58 + eeprom + firmware

### PR DESCRIPTION
**Pull request by moabeat-berlin**
- rpi-kernel: update to 6.1.58.
- rpi-firmware: update to 20231020.
- rpi-eeprom: update to 2023.10.20.

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for these architectures:
  - aarch64 (cross)
  - aarch64-musl (cross)

builds for testing available at: https://barrens.de/repo and https://barrens.de/repo/nonfree

Also tested dkms. It's working fine.

[ci skip]

### CODE REVIEW

**Comment by Duncaen** [comment]
This should be one commit per package.

**Comment by classabbyamp** [comment]
I was going to wait for my rpi5 to arrive before updating these

**Comment by moabeat-berlin** [comment]
Sorry, I didn't want to interfere here. But maybe it would be a good opportunity to update to the most recent available kernel version before the necessary RPi5 updates might take longer than expected?

**Comment by classabbyamp** [comment]
please test: #47288

**Pull request closed without merging**
