### PR TITLE
elfutils: update to 0.176.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by maxice8** [comment]
@Cogitri

**Comment by Cogitri** [comment]
Works for ZFS, testing other modules now

**Comment by Cogitri** [comment]
Also works with `vhba-module-dkms`, which failed previously. Dunno about Nvidia

**Comment by maxice8** [comment]
@Hoshpak

**Comment by Hoshpak** [comment]
It works for vhba-module and nvidia340. I'm not currently using any hardware supported by the current version of the nvidia driver.

**Pull request merged**
