### PR TITLE
[NEEDS TESTERS] perl: update to 5.28.0.

### PR DESCRIPTION
**Pull request by maxice8**
Rebuilding on x86_64

- [x] ImageMagick
- [x] collectd
- [x] gnumeric
- [x] hexchat
- [x] irssi
- [x] kvirc
- [x] liboping
- [x] linux-tools
- [x] nix
- [x] perl-Barcode-ZBar
- [x] perl-Bit-Vector
- [x] perl-Cairo
- [x] perl-Cairo-GObject
- [x] perl-Class-XSAccessor
- [x] perl-Clone
- [x] perl-Crypt-Blowfish
- [x] perl-Crypt-CAST5
- [x] perl-Crypt-DES
- [x] perl-Crypt-IDEA
- [x] perl-Crypt-OpenSSL-Bignum
- [x] perl-Crypt-OpenSSL-RSA
- [x] perl-Crypt-OpenSSL-Random
- [x] perl-Crypt-Rijndael
- [x] perl-DBD-Pg
- [x] perl-DBD-SQLite
- [x] perl-DBD-mysql
- [x] perl-DBI
- [x] perl-Data-MessagePack
- [x] perl-Data-UUID
- [x] perl-DateTime
- [x] perl-Devel-Caller
- [x] perl-Devel-LexAlias
- [x] perl-Digest-SHA1
- [x] perl-Email-Address-XS
- [x] perl-Filesys-Df
- [x] perl-Fuse
- [x] perl-Glib
- [x] perl-Glib-Object-Introspection
- [x] perl-Goo-Canvas
- [x] perl-Gtk2
- [x] perl-Gtk2-ImageView
- [x] perl-Gtk2-Notify
- [x] perl-HTML-Parser
- [x] perl-IO-Tty
- [x] perl-Image-Sane
- [x] perl-JSON-XS
- [x] perl-Lchown
- [x] perl-List-MoreUtils-XS
- [x] perl-Locale-gettext
- [x] perl-Math-BigInt-GMP
- [x] perl-Math-Prime-Util
- [x] perl-Math-Prime-Util-GMP
- [x] perl-MusicBrainz-DiscID
- [x] perl-Net-DBus
- [x] perl-Net-SSH2
- [x] perl-Net-SSLeay
- [x] perl-NetAddr-IP
- [x] perl-Package-Stash-XS
- [x] perl-PadWalker
- [x] perl-Pango
- [x] perl-Params-Util
- [x] perl-Proc-ProcessTable
- [x] perl-Search-Xapian
- [x] perl-Socket-MsgHdr
- [x] perl-Socket6
- [x] perl-Sub-Identify
- [x] perl-Sub-Name
- [x] perl-Taint-Runtime
- [x] perl-Template-Toolkit
- [x] perl-Term-ReadKey
- [x] perl-Term-ReadLine-Gnu
- [x] perl-Test-LeakTrace
- [x] perl-Text-Bidi
- [x] perl-Text-CharWidth
- [x] perl-Tk
- [x] perl-Unicode-LineBreak
- [x] perl-Unicode-String
- [x] perl-Unix-Mknod
- [x] perl-Variable-Magic
- [x] perl-WWW-Curl
- [x] perl-XML-LibXML
- [x] perl-XML-Parser
- [x] perl-YAML-LibYAML
- [x] perl-pcsc
- [x] postgresql
- [x] rrdtool
- [x] rxvt-unicode
- [x] ucspi-ssl
- [x] vim
- [x] weechat
- [x] xchat
- [x] znc

### CODE REVIEW

**Comment by maxice8** [comment]
@chneukirchen

**Comment by maxice8** [comment]
@chneukirchen looks good ?

```
/usr/lib/libperl.so -> /usr/lib/libperl.so.5.28.0
/usr/lib/libperl.so.5.28 -> /usr/lib/libperl.so.5.28.0
/usr/lib/perl5/core_perl/CORE/libperl.so -> /usr/lib/libperl.so.5.28.0
```

---

```
/usr/bin/perl5.26.1 -> /usr/bin/perl
/usr/lib/libperl.so -> /usr/lib/perl5/core_perl/CORE/libperl.so.5.26
/usr/lib/libperl.so.5.26 -> /usr/lib/perl5/core_perl/CORE/libperl.so.5.26
```

**Comment by chneukirchen** [comment]
LGTM.

**Comment by maxice8** [comment]
any special precautions to be taken on the builders ?

**Comment by chneukirchen** [comment]
I don't think so.

**Comment by zdykstra** [comment]
I was able to build and install 

```
perl-5.28.0_1
perl-IO-Tty-1.12_5
perl-Net-SSLeay-1.85_3
```
From there, I was able to build and install _perl-Mojolicious_  and _cpanminus_ and then install a fairly extensive list of Perl modules via cpanminus. I was able to successfully run a test suite for a closed-source Perl application against 5.28 and the installed modules.

```
# perl -E 'say $^V'
v5.28.0
```

From an end-user standpoint I'm not seeing any issues with this build.

**Comment by chneukirchen** [comment]
:shipit:

**Pull request closed without merging**
