### PR TITLE
owncloudclient: update to 2.5.4.11654.

### PR DESCRIPTION
**Pull request by damadmai**

### CODE REVIEW

**Comment by Hoshpak** [comment]
The update for owncloudclient is intentionally delayed because it is no longer compatible with nextcloud and would break existing setups while the nextcloud desktop is not yet compatible with libressl.

**Comment by damadmai** [comment]
Good to know that. I have problem with 100% cpu of the owncloud process if internet connection goes down. That is solved with the current version. Maybe it is possible to create an extra package for the current version with another name?

**Comment by butonic** [comment]
*disclaimer: owncloud server developer here*
@Hoshpak I'll go with a local built package, but ... how long will it be delayed? I assumed nobody cared to update the client version. Reading the above I wonder why and who decided to delay the upgrade. I mean ... our desktop team puts a lot of effort into the releases and there are a lot more changes coming. The fork decided to not contribute back, intentionally. There is nothing we can do about that. But why do ownCloud users have to suffer for that?

**Comment by Hoshpak** [comment]
The decision was made by one of the former project members in #6622 . I am pretty sure no one knew about the issues with the version in the repository back then. There's currently work going on to add nextcloudclient into the repository in #14069 . As soon as that is merged, the owncloudclient package can be updated.

**Pull request closed without merging**
