### PR TITLE
nheko: remove.

### PR DESCRIPTION
**Pull request by maxice8**
Unmaintained upstream https://github.com/mujx/nheko

@Johnnynator @Gottox

### CODE REVIEW

**Comment by Vaelatern** [comment]
I'd rather the INSTALL.msg's were a single line, maybe with a link to more information.

**Comment by maxice8** [comment]
@Vaelatern see if the message is good

```
#!/usr/bin/env bash
rm_links_to() {
	find srcpkgs -lname "$1" -exec rm '{}' \;
}

rm_shlib_entries() {
	sed -i "/ $1/d" common/shlibs
}

rm_useless_files() {
	find srcpkgs/"$1" ! -name template -type f -exec rm -f '{}' \;
}

write_install_msg() {
	cat>srcpkgs/"$1"/INSTALL.msg<<EOF
$1 was removed from the repos it will be removed from the index on $(date -d '+1 month' '+%d/%m/%Y')
EOF

${EDITOR:=vi} srcpkgs/"$1"/INSTALL.msg
}

if ! distdir="$(xdistdir)"; then
	exit 1
fi

t="${distdir}/srcpkgs/$1/template"

if [ ! -f "$t" ]; then
	exit 1
fi

source "$t" || {
	echo "Failed to source template for $1" ;
	exit 1;
}

rm_links_to "$pkgname"
rm_shlib_entries "$pkgname"
rm_useless_files "$pkgname"
write_install_msg "$pkgname"

cat>srcpkgs/"$1"/template<<EOF
# Template file for '$pkgname'
pkgname=$pkgname
version=$version
revision=$((revision + 1))
noarch=yes
build_style=meta
short_desc="$short_desc (removed package)"
license="GPL-3.0-or-later"
homepage="$homepage"
EOF
```

**Comment by Vaelatern** [comment]
`$1 was removed from the Void Linux repos, and will be removed from the index on `

**Comment by maxice8** [comment]
On Mon, Nov 05, 2018 at 08:14:21AM -0800, Toyam Cox wrote:
> `$1 was removed from the Void Linux repos, and will be removed from the index on `
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/4372#issuecomment-435933977

updated

**Comment by Vaelatern** [comment]
See my latest update: `$1 is no longer provided by Void Linux, and will be fully removed from the repos on`

**Comment by maxice8** [comment]
On Mon, Nov 05, 2018 at 04:19:03PM +0000, Toyam Cox wrote:
> See my latest update: `$1 is no longer provided by Void Linux, and will be fully removed from the repos on`
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/4372#issuecomment-435935787

ok, updated again

**Comment by maxice8** [comment]
@Vaelatern What is the preferred timeframe from replacing with a removed package and removing from the index ?

my script puts it at 1 month ? should we let maintainers decide and just give a good guesstimate ?

**Comment by Vaelatern** [comment]
We've never done this before. I think 3 months would be ideal, to catch most of our users. I have no stats to back this claim up.

**Comment by whoizit** [comment]
it's forked https://github.com/redsky17/nheko

**Comment by maxice8** [comment]
On Sun, Jan 13, 2019 at 08:51:38PM -0800, whoami wrote:
> it's forked https://github.com/redsky17/nheko
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/4372#issuecomment-453901780

I'm not eager to restore a package because someone forked considered no work is done yet.

Let it be for a while if it proves to be active we can change.

**Pull request merged**
