### PR TITLE
curl: update to 7.88.0.

### PR DESCRIPTION
**Pull request by leahneukirchen**
Fixes three not very serious CVE.

#### Testing the changes
- I tested the changes in this PR: **YES**|**briefly**|**NO**

### CODE REVIEW

**Comment by sgn** [comment]
https://github.com/curl/curl/issues/10525

**Comment by Kangie** [comment]
Recommend that this not be merged due to the HTTP/2 issue linked above.

https://lore.kernel.org/distributions/e3306ab8-3656-3128-40f8-f76e6871a3a3@footclan.ninja/T/#u

Either add a patch to revert the commit that made this more prevalent or (ideally) wait for upstream to merge the fixes (it looks like two patches so far).

I also note that when packaging for Gentoo I had to add new commits from master so that tests would pass.

**Comment by sgn** [comment]
7.88.1 is available.

**Comment by mhmdanas** [comment]
https://github.com/void-linux/void-packages/pull/43279 was merged in, so this is now obsolete.

**Pull request closed without merging**
