### PR TITLE
icewm: update to 2.0.0.

### PR DESCRIPTION
**Pull request by glaulher**

### CODE REVIEW

**Comment by glaulher** [comment]
On my computer compiled without fail, working well.

**Comment by ericonr** [comment]
It's the tests that are failing, because it's not building some executable that it needs.

You can check with `./xbps-src -Q pkg icewm`

**Comment by glaulher** [comment]
the tests in version 1.9.2 that is in the repository also fail the tests, in gentoo there is a report of failure in the tests (https://gitweb.gentoo.org/repo/gentoo.git/commit/x11-wm/icewm/icewm-2.0.1.ebuild?id=2094ac95affc1ea141b6871bd248826a94753318), I believe it is something of the icewm.

------------------------------------------------------------------------------------------------------------------------------------

Unable to find executable: /builddir/icewm-1.9.2/build/strtest
1/1 Test #1: strtest ..........................***Not Run   0.00 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.00 sec

The following tests FAILED:
	  1 - strtest (Not Run)
Errors while running CTest
make: *** [Makefile:116: test] Error 8
=> ERROR: icewm-1.9.2_1: do_check: 'CTEST_OUTPUT_ON_FAILURE=TRUE ${make_cmd} ${make_check_args} ${make_check_target}' exited with 2
=> ERROR:   in do_check() at common/build-style/cmake.sh:98

**Comment by ericonr** [comment]
Would you like to reopen the PR? I had missed the notification... Adding `make_check=no` to template should be enough...

**Pull request closed without merging**
