### PR TITLE
New package: gnome-podcasts-0.4.5

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by maxice8** [comment]
add nocross to the rust package

**Comment by Cogitri** [comment]
I suppose it will fail on Travis anyway due to not putting out anything (also uses cargo as custom_target via meson) - but let's see...

**Comment by jnbr** [comment]
I would prefer to fix the musl build as it was done here: https://github.com/void-linux/void-packages/pull/1781
Your patch will build gettext and link it statically which is unnecessary.

**Comment by Cogitri** [comment]
Yup, did try that, but it didn't seem to work, even after setting those variables it didn't use the system's gettext. No need to set GETTEXT_SYSTEM though, it's already set via `features` https://crates.io/crates/gettext-rs

**Comment by maxice8** [comment]
Took the liberty to do a few fixes and push it myself

**Pull request closed without merging**
