### PR TITLE
New package: rock64-base-0.1

### PR DESCRIPTION
**Pull request by CameronNemo**
still in testing https://github.com/void-linux/void-mklive/pull/177

### CODE REVIEW

**Comment by Johnnynator** [comment]
Anything else that needs to be done?
Can you rebase it.

**Comment by CameronNemo** [comment]
@Johnnynator not sure if I want to drop the linux-firmware dependency. nothing on the board needs it.

**Comment by Johnnynator** [comment]
> @Johnnynator not sure if I want to drop the linux-firmware dependency. nothing on the board itself needs it.

Most of the other `-base` package do not depend on `linux-firmware` or only a specific subpackage, so I don't think there is an expectation for it being installed by a boards `-base` package, so do not add it, if the board doesn't need it.

**Comment by CameronNemo** [comment]
Rebased and added service configuration, but not yet tested.

**Comment by CameronNemo** [comment]
I have since tested this. It works alright.

**Pull request merged**
