### PR TITLE
octave: update to 6.2.0.

### PR DESCRIPTION
**Pull request by ahesford**
I don't use Octave, but I can launch it and display a trivial plot.

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Supersedes #27775 ?

@olafmersmann

**Comment by ahesford** [comment]
Missed that one. @olafmersmann if you want to bump yours to 6.2.0, I'll close this.

**Comment by olafmersmann** [comment]
> Missed that one. @olafmersmann if you want to bump yours to 6.2.0, I'll close this.

I'll bump mine to 6.2.0 in the next day or two.

**Comment by ahesford** [comment]
OK, thanks. Closing with reference to #27775.

**Pull request closed without merging**
