### PR TITLE
 fcitx5

### LINKED ISSUE #29499: Package request: fcitx5
[fcitx5](https://github.com/fcitx/fcitx5): Next generation of fcitx

The currently packaged fcitx4 runs on XWayland on Wayland compositors. Due to that, it has problems following the text cursor in Wayland apps. Fcitx5 solves that problem by supporting Wayland natively.

Note that the [backends](https://fcitx-im.org/wiki/Install_Fcitx_5) also need to be packaged.

More references on Arch Wiki: https://wiki.archlinux.org/index.php/Fcitx5

### PR DESCRIPTION
**Pull request by sgn**
Close #29499 

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by sgn** [comment]
- Works for LibreOffice, qutebrowser
- broken with xterm on x86_64-musl.

**Comment by sgn** [comment]
@noarchwastaken please test.

**Comment by sgn** [comment]
`-DNDEBUG` is added by CMake for `Release` `MinSizeRel` and `RelWithDebInfo`

**Comment by noarchwastaken** [comment]
> @noarchwastaken please test.

Here's my tests on sway, all apps are running in native Wayland except those under "XWayland Apps":

Works:
- Firefox
- Thunderbird
- Thunar
- Epiphany
- Evince
- Telegram Desktop
- KeepassXC
- FileZilla
- XWayland Apps
  - GIMP
  - XTerm
    (probably because I use glibc?)
  - Element
  - VSCode - OSS

Don't (fully) work:
- Flatpak Wayland GTK apps (Fcitx5 runs in XWayland, blurry and has wrong position)
  - Firefox
  - Flatseal
  - [GIMP beta](https://www.gimp.org/downloads/devel/)
- Wofi
  Weird behavior: the first candidate is automatically selected upon every key press, and the whole screen glitches
- Alacritty (known Alacritty issue)

Thank you very much for the work!

**Comment by noarchwastaken** [comment]
Would you please package Mozc for fcitx5 too?

If it doesn't conform the quality standard yet (I couldn't find release tarballs for it), what about packaging fcitx5-kkc or creating another branch for Mozc but not put it in the PR for now? It would be useful for some people, including me, a Japanese learner.

**Comment by sgn** [comment]
On 2021-03-27 15:05:52-0700, noarchwastaken ***@***.***> wrote:
> Would you please package Mozc for fcitx5 too?

Maybe -anthy would work for you?

> If it doesn't conform the quality standard yet (I couldn't find
> release tarballs for it),
> what about packaging fcitx5-kkc or

I will look into -kkc later

> creating another branch for Mozc but not put it in the PR for now?
> It would be useful for some people, including me, a Japanese
> learner.

**Comment by noarchwastaken** [comment]
> On 2021-03-27 15:05:52-0700, noarchwastaken ***@***.***> wrote: Would you please package Mozc for fcitx5 too?
> Maybe -anthy would work for you?
> If it doesn't conform the quality standard yet (I couldn't find release tarballs for it), what about packaging fcitx5-kkc or
> I will look into -kkc later
> […](#)
> creating another branch for Mozc but not put it in the PR for now? It would be useful for some people, including me, a Japanese learner.

-anthy works. BTW fcitx5 is working perfectly for the last two days, so thanks again!

**Comment by noarchwastaken** [comment]
Hi @sgn , just curious, are the new Japanese IMEs ready for testing?

**Comment by sgn** [comment]
It should be. I don't have time to test, though.

**Comment by noarchwastaken** [comment]
I just tested -anthy, and it's working prefectly.

**Comment by sgn** [comment]
I'm mostly worry about -kkc, now. (And musl, of course), I couldn't find anytime to debug the problem with musl, though.

**Pull request merged**
