### PR TITLE
gnuradio: update to 3.10.5.1

### PR DESCRIPTION
**Pull request by unspecd**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-musl)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - ppc64le-musl

### CODE REVIEW

**Comment by unspecd** [comment]
Rebased on master.
Also enabled tests on i686.

**Comment by unspecd** [comment]
I will update to 3.10.5.0 this week.

**Comment by unspecd** [comment]
Updated gnuradio-osmosdr to 0.2.4.

**Comment by unspecd** [comment]
Updated to 3.10.5.1.

**Review by abenson — APPROVED** [review]

**Pull request merged**
