### PR TITLE
higan: fix dead links

### PR DESCRIPTION
**Pull request by meator**
@Johnnynator I'm pinging you since you are the maintainer of `higan`. Do you have any comment on this?
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
```
=> higan-110_1: running post_install ...
Linking out/icarus ...
GNUmakefile:50: *** "make install should not be run as root".  Stop.
=> ERROR: higan-110_1: post_install: 'make STRIP=true compiler=${CXX} platform=linux prefix=${DESTDIR}/usr install' exited with 2
```

the current patch doesn't seem to be enough?

**Comment by meator** [comment]
There is actually a significantly larger problem with this. I have asked people on their official discord and they said that higan can't be installed as root because `System/*` files need to be writable by the program. One of the devs wrote this:

> My recommendation for making a package would be not to run make install at all, but rather to have your package-build script just copy the Template files into /usr/share/higan, install the main binary as /usr/bin/higan.real, and have /usr/bin/higan be a shell-script that copies the template files from /usr/share/higan into the user's home directory if they don't already exist.

**Comment by meator** [comment]
If I understand it correctly, all problems caused by running `make` as root are solved by `higan-paths.patch`, so pathing the root check out should be safe.

**Comment by ericonr** [comment]
Looks about right, thanks.

@Johnnynator ok?

**Comment by Johnnynator** [comment]
Should be okay for now. Will take a deeper look into the other quirks of the packages some time else, not much time for it right now.

**Pull request merged**
