### PR TITLE
kdevelop: update to 5.4.6

### PR DESCRIPTION
**Pull request by yopito**

### CODE REVIEW

**Comment by yopito** [comment]
too big for travis CI (50 min building limit)

**Comment by ndowens** [comment]
Change title back to kdevelop: update to 5.4.6 and amend commit message and add on the next line [ci skip]

**Comment by yopito** [comment]
here it is. thx

**Comment by yopito** [comment]
strange: Travis CI starts anyway building kdevelop that requires  building `kde5-baseapps` ...

**Pull request closed without merging**
