### PR TITLE
rust-bindgen: update to 0.71.1

### PR DESCRIPTION
**Pull request by terminaldweller**
#### Testing the changes
- I tested the changes in this PR: **NO**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86_64-musl

### CODE REVIEW

**Comment by terminaldweller** [comment]
I don't know how to test this. I would appreciate some pointers on that.
As to why I made a PR for this, please look at https://github.com/void-linux/void-packages/pull/53502.

**Comment by classabbyamp** [comment]
you could test by building some packages that use rust-bindgen and seeing if they error

**Comment by terminaldweller** [comment]
The 3 packages that use `rust-bindgen` in our repos is chromium,electron33 and mesa. They all take very long to build. what do i do?

**Comment by classabbyamp** [comment]
i tested a couple builds

**Pull request merged**
