### PR TITLE
go-bindata: update to 3.1.3 and switch to the latest upstream url

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Comment by Johnnynator** [comment]
Can you check if all the packages that depend on go-bindata for building do still compile AND run after this? I think browsh might also get the bindata patch removed with this.

**Comment by smorimoto** [comment]
@Johnnynator Sure. It seems the Travis backlog build growth is preventing the build from being triggered, so I will test them locally and then push the commits.

**Comment by ericonr** [comment]
>Can you check if all the packages that depend on go-bindata for building do still compile AND run after this? I think browsh might also get the bindata patch removed with this.

I hope not, I upstreamed that one D:

**Comment by smorimoto** [comment]
Did you mean that we shouldn't remove the patch in the browsh package?

**Comment by ericonr** [comment]
Yes, unless the package stops working. If it stops working, we might need another patch for the next release.

**Comment by smorimoto** [comment]
Okay. But, is it better not to bump the revision of the browsh package? or is it better to bump the revision if the build is successful and works correctly?

**Comment by ericonr** [comment]
Don't think you need to revbump either way, since browsh is working.

Just remove the patch if having it there breaks the package (ideally, we'd like to keep packages in the repo buildable).

**Comment by smorimoto** [comment]
How do I build browsh using my local edited go-bindata? The build system tells me that it can't find the go-bindata command.

**Comment by ericonr** [comment]
Is `./xbps-src pkg browsh` failing? It should be all set up to build it.

**Comment by smorimoto** [comment]
I tried it, but somehow it says it can't find the go-bindata command.

**Comment by ericonr** [comment]
The package is empty:

```
~/v/void-packages on testprs ➜ xls go-bindata
/usr/share/licenses/go-bindata/LICENSE
~/v/void-packages on testprs ➜ xq go-bindata
pkgver: go-bindata-3.1.3_1
short_desc: Turn data file into go code
architecture: x86_64-musl
filename-sha256: 8f75195cfb2a639d248e3a454395851992d9908511f74108f6c1cea40b27d8dc
filename-size: 794B
homepage: https://github.com/go-bindata/go-bindata
installed_size: 169B
license: Public Domain
maintainer: Andrea Brancaleoni <abc@pompel.me>
pkgname: go-bindata
repository: /home/ericonr/void/void-packages/hostdir/binpkgs/testprs
```

**Comment by the-maldridge** [comment]
Bump?

**Comment by smorimoto** [comment]
I will investigate.

**Comment by ericonr** [comment]
Ping

**Comment by ericonr** [comment]
Closing due to inactivity, feel free to reopen :)

**Pull request closed without merging**
