### PR TITLE
Add base-system-lts

### PR DESCRIPTION
**Pull request by RhinoCodes**

### CODE REVIEW

**Comment by ericonr** [comment]
Why? Users can just `ignorepkg=linux` and install `linux-lts` directly once, and that will be equivalent to this. Any changes to `base-system` will also need to be propagated across two templates, if they happen.

**Comment by ericonr** [comment]
I don't speak for everyone, though. If you want to push for this, make it a sub-package of the `base-system` package instead.

**Comment by RhinoCodes** [comment]
i really dont know much about void packages. so where would i put ignorepkg=linux? Im making a void spin and want to make it more stable and would like lts to be autoinstalled

**Comment by shmalebx9** [comment]
> @ericonr i really dont know much about void packages. so where would i put ignorepkg=linux? Im making a void spin and want to make it more stable and would like lts to be autoinstalled

Add ` ignorepkg=linux ` to /usr/share/xbps.d/xbps.conf. There are a few xbps config files, see [the handbook](https://docs.voidlinux.org/xbps/advanced-usage.html) and the [manpage](https://man.voidlinux.org/xbps.d.5).

**Comment by ahesford** [comment]
If you don't want to mess around with ignoring packages, use `base-voidstrap` or `base-minimal` and build up your desired packages from there.

**Pull request closed without merging**
