### PR TITLE
iwd: fix output sent to tty1

### LINKED ISSUE #20912: iwd: stderr spam to tty1
Same behavior as [#11928](https://github.com/void-linux/void-packages/issues/11928)

### Proposed change
Adding `> /dev/null 2>&1` to the last line of `iwd`'s `run` script seems to sovle the problem

from
`exec /usr/libexec/iwd ${OPTS}`
to
`exec /usr/libexec/iwd ${OPTS} > /dev/null 2>&1`

### PR DESCRIPTION
**Pull request by NeelChotai**
Closes #20912.

### CODE REVIEW

**Comment by sgn** [comment]
Does it retains log?

**Comment by NeelChotai** [comment]
> Does it retains log?

I've tested it a little more and it appears as through simply removing the redirection from stderr to stdout is enough to prevent the spam on tty1. This should retain any log output.

Something of note - the NetworkManager run file uses the approach I originally used, perhaps its output doesn't need to be redirected to /dev/null either? I don't use NetworkManager personally so I'm unable to test it.

**Comment by ericonr** [comment]
Seems to have worked fine for me too!

**Comment by travankor** [comment]
Yeah +1 to merging, I've had this as a private change for ~6months

**Comment by travankor** [comment]
@sgn Anything else?

**Comment by sgn** [comment]
On 2020-05-26 01:23:41-0700, travankor <notifications@github.com> wrote:
> @sgn Anything else?

I forgot about this.

Gimme sometime, maybe this weekend. Please ping me if this PR isn't
merged or commented that time.

I'm also iwd's user but I don't have time to try this for now.

-- 
Danh

**Comment by NeelChotai** [comment]
@sgn

**Comment by Piraty** [comment]
wouldn't have been a log/run symlink be a sensible solution? see #19171 and many others

**Comment by sgn** [comment]
On 2020-06-03 02:15:19-0700, Piraty <notifications@github.com> wrote:
> wouldn't have been a log/run symlink be a sensible solution?
> see #19171 and many others

I don't know :|
Right now, iwd writes log into /var/log/socklog/daemon

-- 
Danh

**Pull request closed without merging**
