### PR TITLE
Luarocks 5.{1,2,3} update to 3.0.4

### PR DESCRIPTION
**Pull request by TeddyDD**

### CODE REVIEW

**Comment by TeddyDD** [comment]
ping @Duncaen

**Comment by Duncaen** [comment]
Since `3.0` luarocks supports multiple lua versions, I wanted to get rid of the `-lua5*` packages.

**Comment by TeddyDD** [comment]
I can't find docs on that (besides `--lua-dir=` flag), could you point me in the right direction?

**Comment by Duncaen** [comment]
https://github.com/luarocks/luarocks/blob/master/CHANGELOG.md#new-flags the `--lua-dir` and `--lua-version` flags.
I would keep one package for the latest lua version and maybe add two shell scripts like:

```
#!/bin/sh
exec luarocks --lua-version 5.1 "$@"
```

**Comment by TeddyDD** [comment]
I'm not big fan of this solution for two reasons:
- user will have to install newest Lua, despite they might want to use older version
- we polluting /usr/bin with scripts for Lua versions that user most likely don't have installed

I'll try to send alternative PR with merged luarocks tho. Is there any metadata that tells xbps to replace luarocks-lua* with luarocks? Like Replaces/Provides in Debian?

**Pull request closed without merging**
