### PR TITLE
[RFC] linux6.8: disable CONFIG_BLK_DEV_WRITE_MOUNTED

### PR DESCRIPTION
**Pull request by classabbyamp**
protects against writing directly to block device nodes while they are mounted

### CODE REVIEW

**Review by thypon — COMMENTED** [review]
is there any application which would need that?
Are we able to disable that, at runtime or in the linux cmdline?

**Comment by classabbyamp** [comment]
cmdline option to reënable this is `bdev_allow_write_mounted`

also, more info on the option is [here](https://www.kernelconfig.io/CONFIG_BLK_DEV_WRITE_MOUNTED)

**Review by thypon — APPROVED** [review]

**Review by Johnnynator — APPROVED** [review]

**Review by cinerea0 — APPROVED** [review]

**Comment by dkwo** [comment]
With this, in linux 6.8.9 the runit boot scripts drop to an emergency shell when checking, as at this point it's still mounted ro I think:
```
=> Checking filesystems:
fsck.ext4: Device or resource busy while trying to open /dev/mapper/cryptroot-root
Filesystem mounted or opened exclusively by another program?

Cannot continue due to errors above, starting emergency shell.
```
Typing exit resumes the boot flow. The link above mentions this case:

> However there are some setups that need this capability
> like running fsck on read-only mounted root device, modifying some
> features on mounted ext4 filesystem, and similar.

What's the best way to address this?

**Comment by ahesford** [comment]
Does `fsck` return a different value when it fails to open the device than when it detects errors? If so, we should make the core-service script aware of that and not panic if we can't run the check.

**Comment by classabbyamp** [comment]
we could use fsck -M

> Do not check mounted filesystems and return an exit status of 0 for mounted filesystems.

**Comment by dkwo** [comment]
I think it's returining value 8.
That's an option. Alternatively, could the check be performed before mounting the filesystem?
For now, I added the option `bdev_allow_write_mounted=true` to my cmdline, as I think it's still valuable to check the root filesystem.

**Comment by classabbyamp** [comment]
8 indicates that *only* operational errors happened

and:
> The exit status returned when multiple filesystems are checked is the bit-wise OR of the exit statuses for each filesystem that is checked.

**Pull request merged**
