### PR TITLE
icu: update to 63.1.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by Cogitri** [comment]
Building on aarch64-musl, let's see...

**Comment by Cogitri** [comment]
LGTM on aarch64-musl, the only package that doesn't build is libzim because `gtest-devel` is missing from makedepends AFAICS

**Comment by maxice8** [comment]
i have fixed builds with libzim and kiwix-lib can you try them again ?

**Comment by Cogitri** [comment]
> i have fixed builds with libzim and kiwix-lib can you try them again ?

wfm, thanks

**Comment by Gottox** [comment]
webkitgtk build error on armv7l-musl https://gist.github.com/e70be884f5e211e9233565acf3a3d9aa

**Comment by Gottox** [comment]
What about short cutting the removal of webkitgtk here? ref: https://github.com/void-linux/void-packages/issues/2488

**Comment by Cogitri** [comment]
Sounds good to me, some distros already removed it (e.g. Fedora) and I feel like we should follow along.

**Pull request closed without merging**
