### PR TITLE
broot: update to 1.23.0

### PR DESCRIPTION
**Pull request by cinerea0**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by cinerea0** [comment]
Temporarily marking as draft while I ask for help on a weird thing that was added to this release.

**Comment by jcgruenhage** [comment]
@cinerea0 what's the state here?

**Comment by cinerea0** [comment]
The new release asks to install and source a script on first run. The script and the change it makes to your bashrc/zshrc/fish_config have to be manually removed if the package is uninstalled. It's not shell completions, but a wrapper script that allows broot to change directory upon exiting. 

I was hoping there was some directory I could install those scripts to where they would be automatically sourced and uninstalled with the rest of the package files. I've asked a couple times on IRC about it but haven't gotten an answer. If that directory doesn't exist I'm fine with marking this as ready to merge and letting users handle it on their own, but I wanted to make sure there wasn't a better way.

**Comment by cinerea0** [comment]
Yeah, there's no way to manage the stuff it generates via xbps. Oh well.

**Comment by classabbyamp** [comment]
yeah that first-run stuff should be left to the user

**Pull request merged**
