### PR TITLE
wxWidgets: rebuild for gcc stdc++ dropping gcc4 compat

### PR DESCRIPTION
**Pull request by Hoshpak**

### CODE REVIEW

**Comment by bra1nwave** [comment]
Oh geez, this will break even more. 
Packages that are broken so far after a quick test:

- `filezilla`
- `audacity`
- `dolphin-emu`

**Comment by Hoshpak** [comment]
Well, the rebuild has to be done nonetheless, otherwise packages building against wxWidgets will fail to link. I guess that means all packages using wxWidgets have to be rebuild and it should be done in the same PR to avoid any breakage on the user side.

**Comment by Hoshpak** [comment]
The PR turned somewhat larger than I had it anticipated. Some more packages than just the ones depending on wxWidgets sneaked in because of libraries like Lucene++ and exiv2. vba-m is missing from this PR because it also needs gtkmm2 so I will wait for this PR and #1132 to be merged to PR it separately.

**Comment by Hoshpak** [comment]
rebased and also added vba-m, should be complete now.

**Pull request closed without merging**
