### PR TITLE
podman: update to 5.3.1.

### PR DESCRIPTION
**Pull request by bryanasdev000**
#### Testing the changes
- I tested the changes in this PR: **Testing...**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

#### Notes

Still testing, specifically for https://blog.podman.io/2024/10/podman-5-3-changes-for-improved-networking-experience-with-pasta/ (in my case, container/app to host/db)

Tests for Quadlet (probably because systemd?) are not passing.

### CODE REVIEW

**Comment by Anachron** [comment]
`podman 5.3.1` was able to build cleanly here on both `x86_64` and `x86_64-musl`.
I've also compiled it for `aarch64` and will test it now on my NAS.

**Comment by bryanasdev000** [comment]
> `podman 5.3.1` was able to build cleanly here on both `x86_64` and `x86_64-musl`. I've also compiled it for `aarch64` and will test it now on my NAS.

Will bump to 5.3.1 and test it here too.

Currently running rootless podman with connections from container to host ok

**Comment by bryanasdev000** [comment]
As expected, tests are failing at the same point on 5.3.1.

Also, not sure if this logs are relevant:

```
grep: Perl matching not supported in a --disable-perl-regexp build
...
make[1]: Leaving directory '/builddir/podman-5.3.1/test/tools'
/usr/bin/bash: line 1: git: command not found
```

**Comment by Anachron** [comment]
That `git: command not found` message claims `git` is missing from `hostmakedepends`. 

I am not sure why you or github would receive this error but my local builds are fine?

**Comment by bryanasdev000** [comment]
> That `git: command not found` message claims `git` is missing from `hostmakedepends`.
> 
> I am not sure why you or github would receive this error but my local builds are fine?

It complete without issues, but is something that print a few times on the build log.

Will add it to see what changes.

**Comment by classabbyamp** [comment]
adding git to hostmakedepends isn't correct. first, it's only used during check, so it would be checkdepends, but in this case putting `PATH=/usr/libexec/chroot-git:${PATH}"` in the template is probably enough

**Comment by bryanasdev000** [comment]
> adding git to hostmakedepends isn't correct. first, it's only used during check, so it would be checkdepends, but in this case putting `PATH=/usr/libexec/chroot-git:${PATH}"` in the template is probably enough

Put this on `do_check()` ?

```
do_check() {
        export PATH=/usr/libexec/chroot-git:${PATH}"
        make .install.ginkgo
        make localunit
}
```

**Comment by bryanasdev000** [comment]
Oh, gotcha an example on ardour.

**Comment by bryanasdev000** [comment]
Well, adding git revels another error:

```
=> podman-5.3.1_1: running do_check ...
removed 'cmd/quadlet/main_test.go'
make -C test/tools build/ginkgo
make[1]: Entering directory '/builddir/podman-5.3.1/test/tools'
make[1]: 'build/ginkgo' is up to date.
make[1]: Leaving directory '/builddir/podman-5.3.1/test/tools'
fatal: not a git repository (or any of the parent directories): .git
```

Trying to ignore the quadlet test as it is the only one failing, messing with `ginkgo` but its ignoring my flags (although it prints that is using it).

So far, if I delete `cmd/quadlet/main_test.go` I can finish the tests ok, but I am not sure if this dirt way is approved.

I am also testing this:

```
diff --git a/srcpkgs/podman/template b/srcpkgs/podman/template
index 0f7c8940ed3..73eff02509c 100644
--- a/srcpkgs/podman/template
+++ b/srcpkgs/podman/template
@@ -20,6 +20,7 @@ distfiles="https://github.com/containers/podman/archive/v${version}.tar.gz"
 checksum=5b4e9ddce69cc2c8c8b8529e90093ae3ea9cb2959e2fceb98469b282dbffbcc7

 export PATH="/usr/libexec/chroot-git:$PATH"
+export TESTFLAGS="--skip-package quadlet --skip-file quadlet"

 if [ "$CROSS_BUILD" ]; then
        go_build_tags+=" containers_image_openpgp"
@@ -35,6 +36,8 @@ post_build() {
 }

 do_check() {
+       rm -v cmd/quadlet/main_test.go
        make .install.ginkgo
        make localunit
 }
```

But like I said, `ginkgo` still parses and execute the quadlet test.

**Comment by bryanasdev000** [comment]
Git or not, does not seem to make any diff on the build:

```
=> podman-5.3.1_1: running do_check ...
removed 'cmd/quadlet/main_test.go'
make -C test/tools build/ginkgo
make[1]: Entering directory '/builddir/podman-5.3.1/test/tools'
go build -o build/ginkgo ./vendor/github.com/onsi/ginkgo/v2/ginkgo
make[1]: Leaving directory '/builddir/podman-5.3.1/test/tools'
fatal: not a git repository (or any of the parent directories): .git
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build  -ldflags ' -X github.com/containers/podman/v5/libpod/define.buildInfo=1732950358 -X github.com/containers/podman/v5/libpod/config._installPrefix=/usr/local -X github.com/containers/podman/v5/libpod/config._etcDir=/etc -X github.com/containers/podman/v5/pkg/systemd/quadlet._binDir=/usr/local/bin -X github.com/containers/common/pkg/config.additionalHelperBinariesDir= ' -o test/goecho/goecho ./test/goecho
GOARCH=amd64 go build -o test/version/version ./test/version/
rm -rf .coverage && mkdir -p .coverage
UNIT=1 ./test/tools/build/ginkgo \
	-r \
	 \
	--skip-package test/e2e,pkg/bindings,hack,pkg/machine/e2e \
	--cover \
	--covermode atomic \
	--coverprofile coverprofile \
	--output-dir .coverage \
	--tags "     exclude_graphdriver_devicemapper seccomp " \
	--succinct
Will skip:
  ./hack/podman-registry-go
  ./pkg/bindings/images
  ./pkg/bindings/test
  ./pkg/machine/e2e
  ./test/e2e
  ```
So I will drop it, I think it comes from https://github.com/containers/podman/blob/main/test/tools/Makefile / https://github.com/vbatts/git-validation.
  
Also, no lucky making ginkgo ignore quadlet tests, so I will proceed with rm to remove it.
  
Will squash and update the PR.

**Comment by Jipok** [comment]
Bump. This PR is very important, because current podman-5.1.2 does not work properly in rootless mode under void.
https://github.com/containers/podman/issues/24777

**Pull request merged**
