### PR TITLE
singular: update to 4.4.0.

### PR DESCRIPTION
**Pull request by tornaria**
#### Testing the changes
- I tested the changes in this PR: **briefly**

This needed bumping sagemath, so its testsuite is fully run here for a good test that singular works fine for us. One test fails due to the update of scipy to 1.13, so I added an easy fix (backported, already merged upstream).

@dkwo may want to test on aarch64.

### CODE REVIEW

**Comment by dkwo** [comment]
Thanks!  Give me a couple of days.

**Comment by tornaria** [comment]
> Thanks! Give me a couple of days.

Sure, there's no hurry at all.

**Comment by dkwo** [comment]
On aarch64, with check=yes, I get one slow doctest
`sage/homology/moment_angle_complex.py Warning, slow doctest: Z.homology()`
and one failure
`sage/algebras/quatalg/quaternion_algebra.py # 1 doctest failed`

I'll try again to see if it was a random failure.

**Comment by tornaria** [comment]
You know that you can write something like
```
sage/homology/moment_angle_complex.py
sage/algebras/quatalg/quaternion_algebra.py 
```
to a file `sagemath-check` in your void-packages directory. Then, when you run the check step, it will only check those two files.

You can also write something like
```
--random-seed=337742633039183257810362073317290869627
sage/algebras/quatalg/quaternion_algebra.py 
```
If you want to run with this particular random seed, which you can copy from the log output. This helps confirm if the doctest failure is random but deterministic with a fixed random seed.

If you don't have this file, *or* if everything is commented out with `#`, then all files are tested as usual.

**Comment by dkwo** [comment]
Thanks for the reminder. Both tests pass from within sage. also from sage, `sage -t -a` passes all tests, so this is good to go.

Btw, I'm getting tons of
`warning: sage/*: noexcept clause is ignored for function returning Python object`
at the beginning of do_build.

**Pull request merged**
