### PR TITLE
Calibre: update to 6.2.1

### PR DESCRIPTION
**Pull request by sgn**
@skmpz [ci skip][skip ci]
Depends on https://github.com/void-linux/void-packages/pull/38509

#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by skmpz** [comment]
@sgn any plans to continue working on this? :)

**Comment by dataCobra** [comment]
Hey @sgn,

are there plans to continue the work on this?
If you need help, I will help you. :+1:

**Comment by sgn** [comment]
> Hey @sgn,
> 
> are there plans to continue the work on this? If you need help, I will help you. +1

I need to finish the `qt6-webengine` first (calibre needs qt6). Right now, all qt6 needs to be updated for cross build.
See #42224

**Comment by sgn** [comment]
Please test.

**Comment by skmpz** [comment]
I'm currently building on x86_64 to test.. will update soon.

**Comment by skmpz** [comment]
built and tested on x86_64 libc.. working fine

**Pull request merged**
