### PR TITLE
haproxy: fix crash on musl

### PR DESCRIPTION
**Pull request by sgn**
Fix: #22684

---
@ailiop-git @Gottox

### CODE REVIEW

**Comment by Gottox** [comment]
nice catch!

**Comment by q66** [comment]
this broke build on armv6, ppc32, mips etc.

fixed in b090364c857e37c54d2fd56f28ba312da5fd6834, don't remove `-latomic` bits next time

**Comment by sgn** [comment]
On 2020-06-09 11:56:05-0700, Daniel Kolesa <notifications@github.com> wrote:
> this broke build on armv6, ppc32, mips etc.
> 
> fixed in b090364c857e37c54d2fd56f28ba312da5fd6834, don't remove `-latomic` bits next time

OK, I'll check it next time.
I read its Makefile, it has some detection logic to add "-latomic".
:shrug:

-- 
Danh

**Comment by sgn** [comment]
On 2020-06-09 11:56:05-0700, Daniel Kolesa <notifications@github.com> wrote:
> this broke build on armv6, ppc32, mips etc.
> 
> fixed in b090364c857e37c54d2fd56f28ba312da5fd6834, don't remove `-latomic` bits next time

It seems like armv6 is not broken with my change, only ppc32 and mips.
Worth to report upstream? They have detection logic for "-latomic" for
armv6 already.

-- 
Danh

**Comment by q66** [comment]
Their "detection logic" is awful, that should not be arch based at all.

**Pull request merged**
