### PR TITLE
qt5-styleplugins: rebuilt against qt5-5.11.2

### PR DESCRIPTION
**Pull request by Johnnynator**

### CODE REVIEW

**Comment by Hoshpak** [comment]
@pullmoll

**Comment by pullmoll** [comment]
LGTM

**Comment by Johnnynator** [comment]
> LGTM .. oh, already merged :)

Nope this isn't merged. You probably only saw the `Merged` Icon from telegram above :D.

**Comment by pullmoll** [comment]
Uh, yes, I did. Then please go ahead.

**Pull request merged**
