### PR TITLE
nodejs: update to 20.13.1

### PR DESCRIPTION
**Pull request by MIvanchev**
#### Testing the changes
- I tested the changes in this PR: **NO**

### CODE REVIEW

**Comment by leahneukirchen** [comment]
Please take a look at https://github.com/void-linux/void-packages/pull/47249/files to see what other changes may be needed.

**Comment by MIvanchev** [comment]
@leahneukirchen It appears electron no longer builds but I thing for an unrelated reason, i.e.

```
In file included from ../../third_party/abseil-cpp/absl/strings/internal/str_format/extension.cc:16:
../../third_party/abseil-cpp/absl/strings/internal/str_format/extension.h:34:35: error: unknown type name 'uint8_t'
```

Do you have an clue to this?

**Comment by leahneukirchen** [comment]
That needs a `#include <stdint.h>` somewhere.

**Comment by MIvanchev** [comment]
I'm removing the WIP status here and arguing that a significant number of projects continue to build successfully with the updated nodejs.

**Comment by brian6932** [comment]
Any chance of this getting merged/anything holding this back from being merged? The current package's extremely out of date :P

**Comment by dkwo** [comment]
Shouldn't the FIXME line is Signal be dropped?

**Comment by MIvanchev** [comment]
@dkwo Indeed it should.

**Pull request closed without merging**
