### PR TITLE
elogind: update to 246.9

### LINKED ISSUE #27132: elogind: keyboard not released under certain conditions
### System

* xuname: Void 5.9.13_1 x86_64 AuthenticAMD notuptodate rFFF
* package: sway-1.5.1_1

### Expected behavior
keyboard grab released, linux console receives keypresses

### Actual behavior
keyboard still grabbed, can only shutdown via power key

### Steps to reproduce the behavior
* use `elogind` as `libseat` backend
* have `exec sway` in `.bash_profile`
* exit sway via `$mod+Shift+e` (`swaymsg exit`)

This started happening after the transition to `libseat` I believe. Would be interesting to know if this happens with other `wlroots` compositor as well.

### PR DESCRIPTION
**Pull request by st3r4g**
@pbui @travankor 

Close #27132

Testing on `x86_64` sway and gnome

### CODE REVIEW

**Comment by pbui** [comment]
This appears to be working OK for me.  When I boot up, I do get a warning message in my console that `elogind` is already running... I have the `elogind` system service enabled and perhaps something else is also trying to start it (`lightdm`?).  Otherwise, logging into my session works fine as does suspend / resume (hooks still work).

I tried disabling the `elogind` system service, but then I got constant messages in my console that `elogind` was already running, so that doesn't work for me.  Likewise, my setup depends on `XDG_RUNTIME_DIR` being setup, so even if I login on the tty... I need elogind to be running for that to work properly.

**Comment by st3r4g** [comment]
> Likewise, my setup depends on `XDG_RUNTIME_DIR` being setup, so even if I login on the tty... I need elogind to be running for that to work properly.

Do you mean that elogind doesn't autostart as soon as you login on the tty?

**Comment by pbui** [comment]
If I don't have the `elogind` system service enabled, then it does not autostart when I login to a `tty`.  I think this is to be expected and is not a change in behavior from previous versions.

Perhaps I could change something in pam, but I find it easier to just have the system service enabled.

**Comment by st3r4g** [comment]
> If I don't have the `elogind` system service enabled, then it does not autostart when I login to a `tty`. I think this is to be expected and is not a change in behavior from previous versions.

Hmm very strange, it does autostart for me by default... I think it works via a dbus call made by pam_elogind after any login, be it tty or graphical. Did you change your pam config maybe?

**Comment by pbui** [comment]
I do have `dbus` enabled and I do not believe I modified my pam config... Let me disable the `elogind` service and try again after a reboot.

**Comment by pbui** [comment]
Ah, OK.  It does autostart... I had an old `chmod 1777 /run/users` in my `/etc/rc.local` that caused `elogind-daemon` to fail when it autostarted.  Removing that allows `elogind` to start automatically from either `tty` or `lightdm`.

**Comment by travankor** [comment]
lightly tested with wayfire(wlroots) seems like it works ok

**Comment by st3r4g** [comment]
https://github.com/elogind/elogind/releases/tag/v246.9-r1

**Comment by pbui** [comment]
Just tested the updated r1 release... still seems fine (does log to syslog now).

**Comment by travankor** [comment]
Any idea about the test failures?

**Comment by travankor** [comment]
All the tests ran locally for me; three were skipped (63,119,125) and the rest passed.

125 looks like something wasn't mounted in the CI.

**Comment by UsernameRandomlyGenerated** [comment]
246.9.2 was released.

**Comment by ericonr** [comment]
So uhhm, what's the status here?

**Comment by pbui** [comment]
I've been using this version for about a month with no issues... So it looks good to me.

**Comment by st3r4g** [comment]
> I've been using this version for about a month with no issues... So it looks good to me.

Same

**Comment by ericonr** [comment]
Can we fix the tests?

**Comment by pbui** [comment]
@ericonr I'm not sure... Locally I get one failed test (103 test-cgroup), and three skipped (63 test-dev-setup, 119 test-bus-match, 125 test-sd-device-monitor).  However, on CI the test suite skips 119 test-bus-match but fails 122 test-login and 125 test-sd-device-monitor.

Since the CI environment and my local machine run different tests with different results I'm not 100% sure how to approach fixing this.

Here is the log from meson from my build machine: http://sprunge.us/WmcWli

**Comment by travankor** [comment]
>(103 test-cgroup)

Might be because we are using `legacy` cgroup hierarchy instead of `v2` or `hybrid`

**Comment by ericonr** [comment]
@travankor https://github.com/void-linux/void-runit/pull/58 points at hybrid...

**Comment by st3r4g** [comment]
No tests fail on my system (x86_64 glibc):
```
Ok:                 128 
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            3   
Timeout:            0   
```

**Comment by travankor** [comment]
>@travankor void-linux/void-runit#58 points at hybrid...

Can logind override this? It's set to `legacy` for the elogind option.

**Pull request closed without merging**
