### PR TITLE
corectrl: update to 1.3.1

### PR DESCRIPTION
**Pull request by ElHereward**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, **x86_64**

### CODE REVIEW

**Comment by classabbyamp** [comment]
don't use the name of the transitional package, use the actual package (`quazip`/`quazip-devel`)

**Comment by ElHereward** [comment]
@classabbyamp you mean at the makedepends section? Why are there the -devel packages in the previous template?

**Comment by ElHereward** [comment]
ah okay - changed and i worked without quazip in the depends

**Comment by ElHereward** [comment]
@classabbyamp the pipeline failed because of wrong email. I changed it to my GitHub mail. is that correct?

**Comment by classabbyamp** [comment]
don't adopt the package, that message was just about the email used to commit. also the last thing you need to do is squash all the commits into 1 called `corectl: update to 1.3.1`

**Pull request closed without merging**
