### PR TITLE
webkit2gtk: update to 2.25.4, refactor template, enable debug

### PR DESCRIPTION
**Pull request by q66**
Additionally, gold is now always off (there was no point in keeping it on and we don't ship it in cross compilers so it was complicating the overall logic).

JIT is also now off for ARMv6. Upstream seems to have dropped it.

It would be nice if somebody could test this on x86_64 and ideally also musl.

### CODE REVIEW

**Comment by q66** [comment]
Libatomic bits were dropped btw as the cmake buildsystem now tests for it. So I also enabled installation of it as makedepend unconditionally, there probably isn't much worth in checking the platforms (the library is tiny).

**Comment by Johnnynator** [comment]
Runs fine on x86_64-musl

**Comment by q66** [comment]
Nice. I'm still looking into an issue here, but once I deal with it it's probably good to go then

**Comment by q66** [comment]
Was something with my masterdir. We're good to go from my side

**Comment by Hoshpak** [comment]
x86_64 is fine however i686 fails for me:

```
OffsetExtractor: No magic values found. Skipping offsets extractor file generation.
make[2]: *** [Source/JavaScriptCore/CMakeFiles/LLIntOffsetsExtractor.dir/build.make:88: DerivedSources/JavaScriptCore/LLIntDesiredOffsets.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:467: Source/JavaScriptCore/CMakeFiles/LLIntOffsetsExtractor.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 51%] Built target WebKit-forwarding-headers
make: *** [Makefile:152: all] Error 2
=> ERROR: webkit2gtk-2.25.4_1: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 2
=> ERROR:   in do_build() at common/build-style/cmake.sh:73
```

**Comment by q66** [comment]
Interesting. Can you try this patch?

```
--- CMakeLists.txt
+++ CMakeLists.txt
@@ -93,6 +93,10 @@ elseif (LOWERCASE_CMAKE_SYSTEM_PROCESSOR
     set(WTF_CPU_MIPS64 1)
 elseif (LOWERCASE_CMAKE_SYSTEM_PROCESSOR MATCHES "^mips")
     set(WTF_CPU_MIPS 1)
+elseif (CMAKE_CXX_LIBRARY_ARCHITECTURE MATCHES "(x64|x86_64|amd64)")
+    set(WTF_CPU_X86_64 1)
+elseif (CMAKE_CXX_LIBRARY_ARCHITECTURE MATCHES "(i[3-6]86|x86)")
+    set(WTF_CPU_X86 1)
 elseif (LOWERCASE_CMAKE_SYSTEM_PROCESSOR MATCHES "(x64|x86_64|amd64)")
     # FORCE_32BIT is set in the build script when --32-bit is passed
     # on a Linux/intel 64bit host. This allows us to produce 32bit
```

If that still doesn't work, can you try disabling `jit`?

**Comment by Hoshpak** [comment]
The patch does not change the error however disabling jit makes the build succeed on i686.

**Comment by q66** [comment]
Yeah, thought so. I guess they don't care about the 32-bit JIT anymore. Do we support pre-SSE2 `i686`? If so, we should disable it anyway (Debian does, for example) - as the i686 JIT relies on SSE2 presence.

**Comment by Hoshpak** [comment]
Currently our base for i686 is the Pentium Pro architecture so we still support pre-SSE2 CPUs. I tried to start a discussion about raising the baseline some time ago since there were some package in the repositories that required SSE2 but no one seemed interested in it. For now I think it would be best to just disable JIT on i686.

**Comment by q66** [comment]
Alright. Btw, turns out it was also disabled on `i686` by default pre-update. So this is actually not changing anything :)

**Comment by q66** [comment]
Also, there may be concerns that this is an "odd" (aka "unstable") release. To clarify that, I decided to go with it anyway because 1) it legitimately fixes some platforms 2) Ubuntu 19.10 is going to ship it and it works fine with all current gtkwebkit browsers 3) It actually introduces proper sandboxing via `bubblewrap`, enabled by default here, a security feature valuable for us - the previous version was not sandboxed, which, on modern web, may be dangerous.

**Pull request merged**
