### PR TITLE
python-PyQt5: update to 5.15.0

### PR DESCRIPTION
**Pull request by PaperMountainStudio**
requires: #23666 
also rebuild qutebrowser against python3-PyQt5 1.15.0
xlint will fail on python-PyQt5, because of indenting, but that's a false alarm

### CODE REVIEW

**Comment by daniel-eys** [comment]
* `python-PyQt5-webengine` should be updated as well.
* The `update` file needs to be adjusted: `pkgname="PyQt5"`
* I'm pretty sure revbumping qutebrowser (as a python package) isn't really necessary here.

**Comment by PaperMountainStudio** [comment]
> * `python-PyQt5-webengine` should be updated as well.
should I add a notice that these packages should be synchronized?
> * I'm pretty sure revbumping qutebrowser (as a python package) isn't really necessary here.
correct, I deleted that commit

**Comment by Johnnynator** [comment]
You should fix your PR and commit messages to list the correct version (you accidentally have 1.15.0)

**Comment by PaperMountainStudio** [comment]
oops, fixed

**Comment by sgn** [comment]
This is not a simple version bump, PyQt5 5.15.0 doesn't support python 2, there're conflicts that needs to be solved.

I'll take over.

**Comment by PaperMountainStudio** [comment]
closing in favour of #24182

**Pull request closed without merging**
