### PR TITLE
audacity: update to 3.6.1

### PR DESCRIPTION
**Pull request by Rooyca**
#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by ahesford** [comment]
Please reconcile with https://github.com/void-linux/void-packages/pull/50047 and, in the future, avoid opening competing PRs wtihout first giving the earlier author a chance to update a pending request.

**Comment by Rooyca** [comment]
yeah, my bad. 
`reconcile` means i need to merge #50047 into my branch?

**Comment by ahesford** [comment]
No, it just means you should consider whether those other dependencies should (or must) be updated along with your audacity update, and ping the author of #50047 to decide which of you should carry forward with the update.

**Comment by Rooyca** [comment]
Ok. Ill contact them.

**Comment by zlice** [comment]
ffmpeg6-devel :)

3.6.1 has scrollbar patch, phew

**Comment by zlice** [comment]
looks like this is the only open audacity pr now. needs ffmpeg6 bump though

**Comment by Rooyca** [comment]
Hey @zlice could you take care of this update? I don't have the time now.

**Pull request closed without merging**
