### PR TITLE
kopia: update to 0.8.4.

### PR DESCRIPTION
**Pull request by daniel-eys**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by daniel-eys** [comment]
waiting for the v0.8.2 release.

**Comment by ericonr** [comment]
Any idea where the build is going wrong on i686? :/

**Comment by daniel-eys** [comment]
Hm not really sure yet what's failing with i686.

**Comment by ericonr** [comment]
Me neither, I can't even see an error message... Shot at the dark, try exporting `GO111MODULE=on` in `pre_build`?

**Comment by daniel-eys** [comment]
Ok so in a fresh i686 masterdir I finally got some more useful error messages:

```
WORK=/tmp/go-build2396301004
mkdir -p $WORK/b267/
cat >$WORK/b267/importcfg << 'EOF' # internal
# import config
packagefile context=/usr/lib/go/pkg/linux_386/context.a
packagefile github.com/kopia/kopia/fs=/host/gocache-glibc/bd/bd8726aebdda0c532c33c2efdd99afc6bb52d02a9c9415e085931e2bb98e9f5d-d
packagefile github.com/pkg/errors=/host/gocache-glibc/42/4275501b50ecad980aaaccdc799d1b1fd818953957fd43be4fe0700845905c16-d
packagefile io=/usr/lib/go/pkg/linux_386/io.a
packagefile os=/usr/lib/go/pkg/linux_386/os.a
packagefile path/filepath=/usr/lib/go/pkg/linux_386/path/filepath.a
packagefile sync=/usr/lib/go/pkg/linux_386/sync.a
packagefile syscall=/usr/lib/go/pkg/linux_386/syscall.a
packagefile time=/usr/lib/go/pkg/linux_386/time.a
EOF
cd /builddir/kopia-0.8.4
/usr/lib/go/pkg/tool/linux_386/compile -o $WORK/b267/_pkg_.a -trimpath "$WORK/b267=>" -p github.com/kopia/kopia/fs/localfs -lang=go1.16 -complete -buildid 7TiDPqNUTbo4FeKVPg8Z/7TiDPqNUTbo4FeKVPg8Z -goversion go1.16.3 -D "" -importcfg $WORK/b267/importcfg -pack -c=4 ./fs/localfs/doc.go ./fs/localfs/local_fs.go ./fs/localfs/local_fs_32bit.go ./fs/localfs/local_fs_nonwindows.go
# github.com/kopia/kopia/fs/localfs
fs/localfs/local_fs_nonwindows.go:26:41: cannot use stat.Dev (type uint64) as type int32 in argument to platformSpecificWidenDev
fs/localfs/local_fs_nonwindows.go:27:42: cannot use stat.Rdev (type uint64) as type int32 in argument to platformSpecificWidenDev
=> ERROR: kopia-0.8.4_1: do_build: 'go install -p "$XBPS_MAKEJOBS" -mod="${go_mod_mode}" -x -tags "${go_build_tags}" -ldflags "${go_ldflags}" ${go_package}' exited with 2
=> ERROR:   in do_build() at common/build-style/go.sh:36
```

I'll inform upstream about this.

**Comment by ericonr** [comment]
Nice! Thanks :)

**Comment by Piraty** [comment]
ping

**Comment by daniel-eys** [comment]
Sorry for the huge delay, I've been quite busy lately.

I added a patch for the i686 build fix and also opened a pr for this on upstream.

**Pull request merged**
