### PR TITLE
meta: rewrite dopatch to use run_step

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by Cogitri** [comment]
Is wlroots supposed to be in this?

**Comment by maxice8** [comment]
Yes

**Comment by pullmoll** [comment]
LGTM. It seems meson cross build problems are solved with this, i.e. `gobject-introspection` and `libdrm` can be cross built again.

**Comment by maxice8** [comment]
@Cogitri wlroots patches and the LDFLAGS are a direct consequence of this, so let's remove it in the same PR

**Comment by maxice8** [comment]
@pullmoll should we rewrite the later stages to also make use of the run_step function ? Mind building more packages to see if the addition of running 'do-$step_name' hooks has any side effects ?

@Gottox are the stages meant to be replaced by run_step ?

**Comment by pullmoll** [comment]
I was not involved with the changes that introduced the stages so I don't know.
I'm continuing to (cross) build packages with gcc-8.3.0 and will report any anomalies.

**Comment by maxice8** [comment]
On Sun, Mar 03, 2019 at 08:04:10AM -0800, Jürgen Buchmüller wrote:
> I was not involved with the changes that introduced the stages so I don't know.
> I'm continuing to (cross) build packages with gcc-8.3.0 and will report any anomalies.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/9328#issuecomment-469036652

Ok i'm merging this please report.

**Pull request merged**
