### PR TITLE
New package: font-jetbrains-mono-2.225

### PR DESCRIPTION
**Pull request by gbrlsnchs**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ahesford** [comment]
From the quality requirements:
> New fonts may be accepted if they provide value beyond aesthetics (e.g. they contain glyphs for a script missing in already packaged fonts).

What's your argument in favor of this font? (Code ligatures fall in the "aesthetics" category.)

**Comment by gbrlsnchs** [comment]
It's a pretty popular programming font. I am basing my argument mostly on [GitHub stars](https://github.com/JetBrains/JetBrainsMono/stargazers). Also, it's made by JetBrains, making it even more popular and well maintained.

**Comment by ahesford** [comment]
Fonts can be installed per-user by copying into `~/.fonts` with the default configuration.

**Comment by gbrlsnchs** [comment]
Sure, no problem. Thanks for reviewing.

**Pull request closed without merging**
