### PR TITLE
tailscale: update to 1.18.1.

### PR DESCRIPTION
**Pull request by dne**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by 0x5c** [comment]
Had to build locally in x86_64 glibc in an attempt to fix a bug. Managed to find what caused the bug (unrelated to any versions), and can confirm this PR works well.

**Comment by ericonr** [comment]
@nilium ok for you?

This release seems to bring some changes re. using `AF_NETLINK` instead of `ip`, would be good to make sure it's working for a wide array of people.

**Comment by linhvng** [comment]
I updated the version in my repo and compiled locally for x86_64 and armv7; it works fine for me.

```
lvn-laptop > uname -a
Linux lvn-laptop 5.15.6_1 #1 SMP Wed Dec 1 14:05:25 UTC 2021 x86_64 GNU/Linux
lvn-laptop > tailscale version
1.18.1
  go version: go1.17.2
```

**Comment by nilium** [comment]
> @nilium ok for you?
> 
> This release seems to bring some changes re. using `AF_NETLINK` instead of `ip`, would be good to make sure it's working for a wide array of people.

I'll build it later and see that it's still working for me. I remember there being some bugs early on with the `ip` removal, but I can't remember how long ago that was now.

**Comment by ericonr** [comment]
Supposedly 1.18.1 fixes some of them, idk if they caught all.

**Comment by dne** [comment]
Also:
> Set TS_DEBUG_USE_IP_COMMAND environment variable to revert to use of /sbin/ip if this breaks your device.

**Comment by nilium** [comment]
1.18.1 appears to still work for me. Some wonkiness with exit node setup, but that's always been fairly fragile for clients on Linux.

**Pull request merged**
