### PR TITLE
openntpd: update to 6.8p1

### PR DESCRIPTION
**Pull request by CameronNemo**
This is the first release in 3 years so definitely needs more testing.

They changed the config since the last release:

```diff
--- /etc/ntpd.conf	2020-12-09 09:51:41.839208968 -0800
+++ /etc/ntpd.conf.new-6.8p1_1	2020-12-09 08:03:15.000000000 -0800
@@ -1,7 +1,11 @@
-# $OpenBSD: ntpd.conf,v 1.14 2015/07/15 20:28:37 ajacoutot Exp $
+# $OpenBSD: ntpd.conf,v 1.16 2019/11/06 19:04:12 deraadt Exp $
 #
 # See ntpd.conf(5) and /etc/examples/ntpd.conf
 
 servers pool.ntp.org
+server time.cloudflare.com
 sensor *
-constraints from "https://www.google.com"
+
+constraint from "9.9.9.9"              # quad9 v4 without DNS
+constraint from "2620:fe::fe"          # quad9 v6 without DNS
+constraints from "www.google.com"      # intentionally not 8.8.8.8
```

### CODE REVIEW

**Comment by Duncaen** [comment]
The announcement said mentioned:

> To build OpenNTPD with time constraint support, libtls from LibreSSL 3.2.2 or later is recommended.

I  think constrains need some extra testing.

**Comment by 4ricci** [comment]
I'm the author of #27046. I enabled constraints in the config and checked that `ntpctl -s status` reported the offset, but nothing more. So I agree this needs more testing.

Just a couple of things to fix here:
-  There's no need for `hostmakedepends` and `pre_configure()`. They were added in 8ea888740dfccdc9e608214c2424219910825cfe because a patch modified `configure.ac`
- The license is ISC, not MIT ([https://github.com/openntpd-portable/openntpd-portable/blob/master/COPYING](url))

**Comment by 4ricci** [comment]
I also think that the runit script should exec `openntpd` directly, otherwise it would not work if it was not set as the default `ntpd` through `xbps-alternatives`.
This probably should be done for all packages providing daemons with alternatives.

**Comment by CameronNemo** [comment]
@4ricci thanks for the tips. I agree on all points and made the changes you suggested.

**Comment by CameronNemo** [comment]
Tested for x86_64 and aarch64-musl. Did not notice any issues when the RTC is working properly.

**Comment by CameronNemo** [comment]
>I do not believe there are any API incompatibilities with LibreSSL 3.1.5 either, if you would like to remain with that version

from the issue I filed with portable repo.

I think this PR is good to go.

**Comment by CameronNemo** [comment]
rebased

**Comment by ericonr** [comment]
@Duncaen ok to merge?

**Comment by ericonr** [comment]
Per #33072, please remove the musl patch.

**Comment by CameronNemo** [comment]
@ericonr done, thanks for the note!

**Pull request merged**
