### PR TITLE
subversion: cross compile

### PR DESCRIPTION
**Pull request by sgn**
Close: #18699

@pullmoll

### CODE REVIEW

**Comment by pullmoll** [comment]
Nice. But it seems there are still host CFLAGS sneaking in, i.e. `-mtune=generic`. This works by accident for `aarch64`, but not for `arm*`.

**Comment by pullmoll** [comment]
Nice. But it seems there are still host CFLAGS sneaking in, i.e. `-mtune=generic`. This works by accident for `aarch64`, but not for `arm*`.

**Comment by sgn** [comment]
Okay, I address perl properly this time.

**Comment by sgn** [comment]
@pullmoll Everythings is well-done now.

**Comment by pullmoll** [comment]
Really good work, thank you very much.

**Pull request merged**
