### PR TITLE
[RFC] common/build-style/go: use -x -> -v so go build logs are readable

### PR DESCRIPTION
**Pull request by classabbyamp**
this is still verbose (prints each module being compiled), but build logs should be more readable (for finding things like errors) now

#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by classabbyamp** [comment]
see CI logs for an example

**Review by Duncaen — APPROVED** [review]
Seems good, the currently logs are very verbose and this seems to still provide enough context without being overly verbose.

```=> syncthing-1.23.6_1: running pre-build hook: 02-script-wrapper ...
=> syncthing-1.23.6_1: running pre_build ...
=> syncthing-1.23.6_1: running do_build ...
go: downloading golang.org/x/time v0.3.0
go: downloading github.com/alecthomas/kong v0.7.1
go: downloading github.com/prometheus/client_golang v1.15.1
go: downloading github.com/syndtr/goleveldb v1.0.1-0.20220721030215-126854af5e6d
go: downloading github.com/thejerf/suture/v4 v4.0.2
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading golang.org/x/text v0.10.0
go: downloading golang.org/x/net v0.11.0
go: downloading github.com/calmh/xdr v1.1.0
go: downloading github.com/jackpal/go-nat-pmp v1.0.2
go: downloading github.com/jackpal/gateway v1.0.10
go: downloading golang.org/x/sys v0.9.0
go: downloading github.com/shirou/gopsutil/v3 v3.23.5
go: downloading golang.org/x/crypto v0.10.0
go: downloading google.golang.org/protobuf v1.30.0
go: downloading github.com/AudriusButkevicius/recli v0.0.7-0.20220911121932-d000ce8fbf0f
go: downloading github.com/flynn-archive/go-shlex v0.0.0-20150515145356-3f9db97f8568
go: downloading github.com/greatroar/blobloom v0.7.2
go: downloading github.com/urfave/cli v1.22.14
go: downloading github.com/sasha-s/go-deadlock v0.3.1
go: downloading github.com/hashicorp/golang-lru/v2 v2.0.3
go: downloading github.com/miscreant/miscreant.go v0.0.0-20200214223636-26d376326b75
go: downloading github.com/syncthing/notify v0.0.0-20210616190510-c6b7342338d2
go: downloading github.com/pierrec/lz4/v4 v4.1.17
go: downloading github.com/minio/sha256-simd v1.0.1
go: downloading github.com/rcrowley/go-metrics v0.0.0-20201227073835-cf1acfcdf475
go: downloading github.com/petermattis/goid v0.0.0-20230518223814-80aa455d8761
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.2
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/calmh/incontainer v0.0.0-20221224152218-b3e71b103d7a
go: downloading github.com/go-ldap/ldap/v3 v3.4.5
go: downloading github.com/julienschmidt/httprouter v1.3.0
go: downloading github.com/vitrun/qart v0.0.0-20160531060029-bf64b92db6b0
go: downloading github.com/quic-go/quic-go v0.34.0
go: downloading github.com/calmh/glob v0.0.0-20220615080505-1d823af5017b
go: downloading github.com/klauspost/cpuid/v2 v2.2.5
go: downloading github.com/russross/blackfriday/v2 v2.1.0
go: downloading github.com/AudriusButkevicius/pfilter v0.0.11
go: downloading github.com/ccding/go-stun v0.1.4
go: downloading github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
go: downloading github.com/chmduquesne/rollinghash v4.0.0+incompatible
go: downloading github.com/golang/snappy v0.0.4
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/cespare/xxhash/v2 v2.2.0
go: downloading github.com/prometheus/client_model v0.4.0
go: downloading github.com/prometheus/common v0.44.0
go: downloading github.com/prometheus/procfs v0.10.1
go: downloading github.com/go-asn1-ber/asn1-ber v1.5.4
go: downloading github.com/Azure/go-ntlmssp v0.0.0-20221128193559-754e69321358
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.4
go: downloading golang.org/x/exp v0.0.0-20230522175609-2e198f4a06a1
go: downloading github.com/quic-go/qtls-go1-20 v0.2.2
go: downloading github.com/golang/protobuf v1.5.3
github.com/syncthing/syncthing/lib/config
github.com/syncthing/syncthing/lib/nat
github.com/syncthing/syncthing/cmd/syncthing/decrypt
github.com/syncthing/syncthing/lib/watchaggregator
github.com/syncthing/syncthing/lib/stun
github.com/syncthing/syncthing/lib/versioner
github.com/syncthing/syncthing/cmd/syncthing/cli
github.com/syncthing/syncthing/lib/discover
github.com/syncthing/syncthing/lib/pmp
github.com/syncthing/syncthing/lib/upnp
github.com/syncthing/syncthing/cmd/strelaysrv
github.com/syncthing/syncthing/lib/connections
github.com/syncthing/syncthing/lib/ur
github.com/syncthing/syncthing/lib/model
github.com/syncthing/syncthing/lib/api
github.com/syncthing/syncthing/lib/syncthing
github.com/syncthing/syncthing/cmd/syncthing/generate
github.com/syncthing/syncthing/cmd/syncthing
=> syncthing-1.23.6_1: skipping check (cross build for aarch64) ...
```

**Comment by the-maldridge** [comment]
Ok for now, but I would like to point out that some of the problems we've encountered in the past (distant past at this point) involved looking at compiler flags.

**Comment by classabbyamp** [comment]
hm, it might be nice to have a general xbps-src functionality to define a debug/higher log level for build processes, e.g. `if  [ "$XBPS_VERBOSE" ]; flag=" -x "; fi`

**Pull request merged**
