### PR TITLE
chromium: enable VAAPI by default & fix on i686

### PR DESCRIPTION
**Pull request by Cogitri**
The '--enable-gpu-rasterization' configure parameter is
required to enable VAAPI (hardware accelerated video
decoding). This commit adds this parameter to the
chromium wrapper script

### CODE REVIEW

**Comment by Cogitri** [comment]
I guess this can wait until the next chromium update too

**Comment by Cogitri** [comment]
Should fix VAAPI on i686 too, currently compiling...

**Comment by Cogitri** [comment]
Builds on both x86_64 and i686, so I guess this should be good to go. Maybe someone can test VAAPI functionality too?

**Comment by dm17** [comment]
I'm using this pkg on x86_64 and I see "not available for your platform" in chrome://flags/#disable-accelerated-video-decode
Am I missing something, or is vaapi not supported?

**Comment by maxice8** [comment]
vaapi is not enabled by default, look at the template https://github.com/void-linux/void-packages/blob/master/srcpkgs/chromium/template

It has the `vaapi` build option in build_options, which build chromium with vaapi support. But it is not in build_options_default.

You should open an issue instead of commenting on year old pull requests.

**Pull request merged**
