### PR TITLE
devilutionX: update to 1.1.0

### PR DESCRIPTION
**Pull request by bugcrazy**

### CODE REVIEW

**Comment by bugcrazy** [comment]
The failure is the connection to the server's internal network, it is not a packet construction error, because the log shows this! This is a problem with travis.

"ERROR: [reposync] failed to fetch file http://alpha.us.repo.voidlinux.org/current/musl/debug/x86_64-musl-repodata: Not Found

https://github.com/diasurgical/devilutionX/archive/1.1.0.tar.gz: Transient resolver failure
ERROR: devilutionX-1.1.0_1: failed to fetch 1.1.0.tar.gz."

**Comment by bugcrazy** [comment]
@ericonr I didn't understand, why to remove INSTALL.msg, because as people will know, what is needed to run the game? I based on the INSTALL.msg game dhewm3, which also needs the data files to run! https://github.com/void-linux/void-packages/blob/master/srcpkgs/dhewm3/INSTALL.msg
I used do_install, because it is in the manual and has templates for other packages you use, the Fedora and Debian packages, use png and font icons, I also did not understand the removal of the code, in my compilations it was necessary, because the ttf font needed by the binary!

**Comment by ericonr** [comment]
@bugcrazy please don't tag me in multiple places, I did see your comment here.

Their cmake install includes all the files, as you can see here:

```
➜ xbps-query -Rf devilutionX
/usr/bin/devilutionx
/usr/share/applications/devilutionx.desktop
/usr/share/diasurgical/devilutionx/README.txt
/usr/share/fonts/truetype/CharisSILB.ttf
/usr/share/icons/hicolor/512x512/apps/devilutionx.png
/usr/share/licenses/devilutionX/LICENSE
```

I removed the INSTALL.msg because they should be used for warnings about package changes or similar, not for general package information. For that, we can use a README.voidlinux. If you want to open a PR to add such a file, I will gladly merge it.

**Comment by bugcrazy** [comment]
> @bugcrazy please don't tag me in multiple places, I did see your comment here.
> 
> Their cmake install includes all the files, as you can see here:
> 
> ```
> ➜ xbps-query -Rf devilutionX
> /usr/bin/devilutionx
> /usr/share/applications/devilutionx.desktop
> /usr/share/diasurgical/devilutionx/README.txt
> /usr/share/fonts/truetype/CharisSILB.ttf
> /usr/share/icons/hicolor/512x512/apps/devilutionx.png
> /usr/share/licenses/devilutionX/LICENSE
> ```
> 
> I removed the INSTALL.msg because they should be used for warnings about package changes or similar, not for general package information. For that, we can use a README.voidlinux. If you want to open a PR to add such a file, I will gladly merge it.

I understand now, the files were automatically added to the package, when I compiled, only the LICENSE file had been packaged, I don't see the need for PR, because INSTALL.msg is a warning, as not everyone is willing to seek information about installation, although the README.txt file, talk about it!
Thanks for answering!

**Pull request closed without merging**
