### PR TITLE
astroid: update to 0.16

### PR DESCRIPTION
**Pull request by bitmeise**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by paper42** [comment]
tests are failing with `tests/run_test.sh: line 18: gpgconf: command not found`, could you add gnupg to checkdepends?

You can run tests on your computer with
```
./xbps-src check <pkg>
```

**Comment by bitmeise** [comment]
Thanks for the hint.
checkdepends is the way to go, but I didn't see it in time. I will fix this soon.

**Comment by bitmeise** [comment]
I'm pretty sure now that checkdepends includes everything necessary for succesfully running the tests. However, the tests only run with X11 (see upstream https://github.com/astroidmail/astroid/issues/516).

By manually bending some stuff to my local X11 I could confirm the tests run 100% fine. However, I don't see how we can run the tests by xbps alone.

The build completes for architectures with disabled tests.

I see three options:
A. Consider upstream to make their tests independent from X (not going to happen soon).
B. Find a way to run tests with some X.
C. Disable tests for now.

Any advice is appreciated.

**Comment by ericonr** [comment]
add `xvfb-run` to `checkdepends`, then add a `do_check` that does `xvfb-run <test command>`

**Comment by bitmeise** [comment]
> add `xvfb-run` to `checkdepends`, then add a `do_check` that does `xvfb-run <test command>`

Thanks, that did the trick.

Sorry for the long delay. I was moving and still only have limited Internet access.

**Comment by ericonr** [comment]
No worries, thanks!

**Pull request merged**
