### PR TITLE
firefox-i18n: update to 69.0.

### PR DESCRIPTION
**Pull request by zdtcd**
[skip ci]

Tested with:
- x86_64

There're build error with:
- x86_64-musl

### CODE REVIEW

**Comment by dylanaraps** [comment]
Not sure if reproducible on your end but `dbus` is now an unconditional dependency in Firefox 69. The `--disable-dbus` `mozconfig` option is broken from Firefox 69 and up, 68.1.0esr is the last version where `--disable-dbus` is known to work.

Source: https://bugzilla.mozilla.org/show_bug.cgi?id=1561207
Caused by this change to Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1429847

**Comment by jnbr** [comment]
Thanks but there is already #14195.
If you split the commit we can merge the firefox-i18n changes.

**Comment by zdtcd** [comment]
@jnbr I'll split the commit

**Comment by jnbr** [comment]
Thanks.

**Pull request merged**
