### PR TITLE
xreader: update to 2.8.1

### PR DESCRIPTION
**Pull request by ndowens**
@the-maldridge xapps is yours. Tested against this newer version of xreader and tested also against nemo

### CODE REVIEW

**Comment by ericonr** [comment]
I think this can be left pending while we finish up with #26965, unless xapps is completely backwards compatible?

**Comment by ndowens** [comment]
> I think this can be left pending while we finish up with #26965, unless xapps is completely backwards compatible?

I will test it against the one listed in that PR and see if it will build against it; it required a minimum version of xapps

**Comment by ndowens** [comment]
Update: does build against xapps in that PR so removing xapps from this one and it can be merged after

**Comment by Chocimier** [comment]
Updated to 2.8.3 by now.

**Pull request closed without merging**
