### PR TITLE
New package: generate-ninja-0.4.1

### PR DESCRIPTION
**Pull request by shizonic**

### CODE REVIEW

**Comment by Johnnynator** [comment]
Why do you use an unmaintained fork of gn instead of the chromium upstream?

**Comment by shizonic** [comment]
> Why do you use an unmaintained fork of gn instead of the chromium upstream?

I have an upstream version too here: https://github.com/shizonic/void-packages/commit/df45ea2e489123f36c9b2e7e6de1a0e3ae412f31

But first there are no release tags and I have to use commit hashes. Second I couldn't build the upstream version successfully yet. Any help is appreciated!

So which one should I use?

**Comment by Johnnynator** [comment]
leah did prepare a template for gn earllier: https://l2.re/X4Opzr . You could update and use that. But make sure to use the `-c` flag of `xgensum`, since google does recreate tarballs on every fetch, so metadata changes.

**Comment by shizonic** [comment]
Ohh nice! Thank you.
I'll gonna update it accordingly.

May you have a look at my other PRs? There are some which can be merged safely: https://github.com/void-linux/void-packages/pulls/shizonic

**Pull request closed without merging**
