### PR TITLE
ports-wide: remove duplicate entries in dependencies field

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by Vaelatern** [comment]
@Duncaen do we care that it's a lot of commits that do nothing?

**Comment by Hoshpak** [comment]
In what way are these duplicates? I couldn't find any actual duplicates in the changes, is this another case of dependencies being pulled in by other dependencies so they can be minified?

**Comment by Cogitri** [comment]
> is this another case of dependencies being pulled in by other dependencies so they can be minified?

If so, I'd "vote" against this, changing the depencies of one package shouldn't break the build of another package. Also IMO it's more work to minify the depencies than just writing down all of them.

**Comment by Hoshpak** [comment]
No, they are actually true duplicates. It just isn't obvious from the way github displays the diffs so I didn't see it earlier. I personally wouldn't care about a lot of commits that do nothing.

**Comment by maxice8** [comment]
> In what way are these duplicates?

They are defined more than once in the templates for the same field.

WindowMaker has libXpm-devel written twice
Chromium has nss-devel and freetype-devel each written twice
cups-filters has libqpdf-devel written twice
ffmpeg has freetype-devel written twice
gloobus-preview has libgxps-devel written twice
gnome-photos has tracker-devel written twice
krdc has knotifyconfig-devel written twice
libvirt has libcap-ng written twice
monero has libldns-devel written twice
namecoin has libevent-devel written twice, so does nfs-utils
partitionmanager has kconfig-devel written twice
pidgin has libXext-devel written twice
python-pytest has python3-atomicwrites written twice

transmission has qt5-tools-devel declared in the main body so adding under conditional is writting it twice but conditionally with no effect whatsoever

uberwriter has python-enchant written twice
volnoti has dbus-glib written twice

xorg-server has MesaLib-devel and libdri2-git-devel in the main body so adding under conditional is writing it twice but condiionally with no effect whatsoever

> I couldn't find any actual duplicates in the changes, is this another case of dependencies being pulled in by other dependencies so they can be minified?

That is trimming and is done by xtrimdeps

to check i just use [this](https://github.com/maxice8/xtools-devel/blob/master/check-dup-deps)
you will also need [xgetdeps](https://github.com/maxice8/xtools-devel/blob/master/xgetdeps)

also the last 2 missing are

```
$ check-dup-deps
libreoffice :: makedepends :: clucene-devel
qt5 :: makedepends :: libvpx-devel libxkbcommon-devel
```

**Comment by maxice8** [comment]
any objections ?

**Comment by Vaelatern** [comment]
Thank you for understanding

**Pull request closed without merging**
