### PR TITLE
Texlive update

### PR DESCRIPTION
**Pull request by fosslinux**
This is the first texlive update (well, texmf packge) update ever.

The metapackages have been updated to pull in the new versions of the packages.

The build_style do_check needs some further fixing. It was flawed on updates because it checked against every single version of the package in repositories. I fixed that in the first commit. However, there is another problem. All of the packages have to first be built and then check run for each package, otherwise it is checking against the outdated information on the other packages.

IMO, the best way to solve this would be to restrict the search to only the repository where the binpkgs are being generated. This means that some checks will be missed in CI but it will pass, and when it is updated on a local machine we can do the two pass:

1. `./xbps-src pkg texlive-blah` for each package
2. `./xbps-src check texlive-blah` for each package

Which is required anyway right now to check and for it to succeed.

@Chocimier thoughts on this above proposal, as you originally wrote the do_check.

### CODE REVIEW

**Comment by Chocimier** [comment]
Locally there is no need for two passes really, because for two packages one of them is build later, when other is already built, so they can be compared.

Instead of limiting repositories, checks could be limited to version in template, with something like below, so single package can be updated and still being checked.

    grep -m 1 version= ${XBPS_SRCPKGDIR}/${p%-*}/template | cut -d= -f2 | tr -d \'\"

**Comment by fosslinux** [comment]
Sure, sounds good.

**Comment by Chocimier** [comment]
Simplified a bit. Is it ready?

**Comment by fosslinux** [comment]
Yes

**Comment by fosslinux** [comment]
Yes

**Pull request merged**
