### PR TITLE
lxd: update to 3.3

### PR DESCRIPTION
**Pull request by iaroki**

### CODE REVIEW

**Comment by CameronNemo** [comment]
Why is the patch needed? Is that something that should go upstream or is it specific to us for some reason?

Ideally we would want to pull in the AppArmor profiles and make sure they work correctly. It doesn't have to happen for this update, but it would be nice.

**Comment by iaroki** [comment]
@CameronNemo That is a bug  with building LXD on musl system which reported upstream https://github.com/lxc/lxd/issues/4848 and quick patch to fix it.

**Comment by CameronNemo** [comment]
Perhaps we should wait for lxc/lxd#4849 and use the same patch as upstream.

**Comment by iaroki** [comment]
Okay, I will wait until it merged upstream and then apply it.

**Comment by maxice8** [comment]
it is merged upstream

**Comment by iaroki** [comment]
With that patch I have:

```
_build-lxd-xbps/src/github.com/lxc/lxd/lxd/cluster/gateway.go:13:2: no Go files in /builddir/lxd-3.3/_build-lxd-xbps/src/github.com/CanonicalLtd/dqlite
=> ERROR: lxd-3.3_1: do_build: 'go get -x -tags "${go_build_tags}" -ldflags "${go_ldflags}" ${go_package}' exited with 1
=> ERROR:   in do_build() at common/build-style/go.sh:17
```

This is on both glibc and musl. Don't know how it is related but I don't have much time to test it right now.

**Comment by CameronNemo** [comment]
See #1830

**Pull request closed without merging**
