### PR TITLE
alacritty: fix missing libXi dependency

### PR DESCRIPTION
**Pull request by HadetTheUndying**
Addresses this Issue, which i have confirmed to be true.
https://github.com/void-linux/void-packages/issues/21158

### CODE REVIEW

**Comment by travankor** [comment]
the commit message is wrong

**Comment by HadetTheUndying** [comment]
@travankor can you explain to me how to properly label a revision? I used xbump for the commit message.

**Comment by travankor** [comment]
seems like you figured it out, but xbump is not for fixup commits

**Comment by HadetTheUndying** [comment]
Yeah pretty sure the message is clear now. My bad

**Pull request merged**
