### PR TITLE
atom: update to 1.29.0

### PR DESCRIPTION
**Pull request by wpbirney**

### CODE REVIEW

**Comment by maxice8** [comment]
Aren't the dependency changes in https://github.com/void-linux/void-packages/pull/759 necessary ?

**Comment by wpbirney** [comment]
@maxice8 yes, i forgot to commit that.
Added it now

**Comment by Hoshpak** [comment]
fails on x86_64:

```
 SONAME: libssl.so.1.0.0 <-> UNKNOWN PKG PLEASE FIX!
   SONAME: libcrypto.so.1.0.0 <-> UNKNOWN PKG PLEASE FIX!
```
looks to me like it wants to link against openssl instead of libressl.

**Comment by Gottox** [comment]
That's because nodejs is built against openssl as libressl is broken.

**Pull request closed without merging**
