### PR TITLE
harfbuzz: update to 1.8.4.

### PR DESCRIPTION
**Pull request by maxice8**
@Johnnynator can you test musl browsers ?

### CODE REVIEW

**Comment by Anachron** [comment]
Has upstream fully tested this version?

**Comment by Johnnynator** [comment]
@maxice8 Did not encounter any issue so far ( Firefox and Chromium )

**Comment by maxice8** [comment]
On Tue, Jul 17, 2018 at 10:59:52AM -0700, John Zimmermann wrote:
> @maxice8 Did not encounter any issue so far ( Firefox and Chromium )
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/979#issuecomment-405671970

Not on x86_64 glibc, i need someone to test musl because i have no musl machines.

**Comment by maxice8** [comment]
On Tue, Jul 17, 2018 at 10:54:40AM -0700, Anachron wrote:
> Has upstream fully tested this version? 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/979#issuecomment-405670350

That is what we are trying to find out before i merge this. Harfbuzz has caused Firefox/Chromium to crash in some past update, we have always checked it ever since.

**Comment by Johnnynator** [comment]
> Not on x86_64 glibc, i need someone to test musl because i have no musl machines.
I know, I should have worded my post differently. **I** did not encounter any issues so far ( ofc on my musl system)

**Pull request closed without merging**
