### PR TITLE
pinebookpro-kernel: update to 5.9.12

### PR DESCRIPTION
**Pull request by CameronNemo**
[ci skip]

@jcgruenhage @Skirmisher

### CODE REVIEW

**Comment by jcgruenhage** [comment]
Build for aarch64-musl just failed for me:

```
/void-packages/srcpkgs/pinebookpro-kernel/template: line 100: cd: /destdir/aarch64-linux-musl/pinebookpro-kernel-5.9/usr/lib/modules/5.9_1: No such file or directory
=> ERROR: pinebookpro-kernel-5.9_1: do_install: 'cd ${DESTDIR}/usr/lib/modules/${_kernver}' exited with 1
=> ERROR:   in do_install() at srcpkgs/pinebookpro-kernel/template:100
```

Looking at the relevant line of `template`, I don't see anything there where musl would make a difference, but I'm building a non-musl variant now to make sure

**Comment by jcgruenhage** [comment]
As for the patches here and why pmOS does not apply them: https://fosstodon.org/@martijnbraam/105024221271723531
I think they got a point, but that obv depends on whether we actually run into the issues they don't run into..

**Comment by sgn** [comment]
I think @jcgruenhage talked about pinebookpro can use mainline 5.9?

**Comment by jcgruenhage** [comment]
@sgn yeah, it can, and it's working well enough that the people over at postmarketOS don't patch their kernel anymore (with the exception of one small patch from linux-next). These patches here are for small issues that remain unfixed in mainline that I didn't know about back in that discussion.

**Comment by CameronNemo** [comment]
Alright re-pushed with your changes. I have built and booted this kernel using the U-Boot built from #21199. Log here: http://ix.io/2AxR (booted from eMMC, though).

If you have an image I can flash to an SD card, I would be happy to test and get the boot log.

**Comment by jcgruenhage** [comment]
So, yeah, I tried it again, still no luck booting from sd card, and I don't want to flash it to my eMMC before I verify it's working from the sd card. Working on getting you links for images and logs (got my uart cable from the hackspace earlier today) to try yourself and look at. Tbh, I doubt my images would be much different from what you could build yourself: It's just a void-mklive based image with the uboot from #21199. I cherry picked the two commits from there and the kernel commit from here onto a master from yesterday.

**Comment by jcgruenhage** [comment]
[void-pinebookpro-20201013.img.xz](https://cloudflare-ipfs.com/ipfs/QmPrmmXsMvQp1eARAFsEKmw7jgpWDe54R5VJNe97ZtLno3)

Boot log with old uboot: https://cloudflare-ipfs.com/ipfs/QmXeah8zHqUQGbxmcCCwdr8SYsJdpHE47Rh6rP8scqTTQN
Boot log with new uboot: https://cloudflare-ipfs.com/ipfs/QmfVW7s5ZhFTESdmMZDFAb4ejUzMqNDx4zFGa3znGdp8PL

**Comment by CameronNemo** [comment]
Added change from #25882

**Comment by CameronNemo** [comment]
@jcgruenhage the image you linked there has a /boot partition with the 5.7 kernel and no boot.scr or extlinux.conf files. U-Boot will not know what to do with that. You may wish to test images with the new kernel and new u-boot separately.

**Comment by jcgruenhage** [comment]
Yeah, I guess these comments would have fitted better on the uboot update PR then. With the old uboot package, these files will probably have been created by something, because it just works there.

**Comment by CameronNemo** [comment]
Right, I have been creating my extlinux.conf using the `u-boot-menu` package, so I did not notice when I accidentally left out the installation of the kernel.d hook in the u-boot PR. I updated that PR to include it so it should work like the existing u-boot package. But I would still suggest testing each PR separately, as they are independent.

**Comment by CameronNemo** [comment]
Updated to 5.9.3. Still running well.

**Comment by ericonr** [comment]
Want to push .11 ? I can merge after linux5.9 is done building.

**Comment by CameronNemo** [comment]
@ericonr pushed 5.9.12

**Comment by Johnnynator** [comment]
This broke iwd on my pinebook
```
DES support not found
No CBC(DES3_EDE) support found, certain TLS connections might fail
No Diffie-Hellman support found, WPS will not be available
The following options are missing in the kernel:
        CONFIG_CRYPTO_USER_API_SKCIPHER
        CONFIG_KEY_DH_OPERATIONS
        CONFIG_CRYPTO_ECB
        CONFIG_CRYPTO_CBC
        CONFIG_CRYPTO_DES
The following optimized implementations might be available:
        CONFIG_CRYPTO_DES3_EDE_X86_64
```

**Pull request merged**
