### PR TITLE
snapper: update to 0.9.0

### PR DESCRIPTION
**Pull request by FollieHiyuki**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

We probably should wait for #29547 to be merged first.

### CODE REVIEW

**Comment by FollieHiyuki** [comment]
Technically not a WIP, I put it there with intention to wait for `btrfs-progs` :)
Some of the locale tests ran on musl while failing on glibc, so I just disable them all.

**Comment by Piraty** [comment]
thanks for adopting it!

**Comment by FollieHiyuki** [comment]
@Piraty does this work with our current btrfs-progs 5.9? I run 5.11.1 already so I couldn't test

**Comment by Piraty** [comment]
I did not test this as I assumed you  (as new maintainer) would have noted otherwise.
(you can downgrade though)

**Comment by FollieHiyuki** [comment]
Yes sorry about that.
I did downgrade for a few hours to test the commands and the cron jobs. But I moved back to 5.11.1 after that. I already noted above that we probably should wait, as I don't trust myself that much with those few hours. Though I can confirm the cron jobs and the commands works as expected.

**Comment by Piraty** [comment]
oh I'm sorry, my bad really! i didn't spot the cross-reference to the btrfs-progs PR in the top post.
let's keep as is now and revert only if necessary

**Pull request merged**
