### PR TITLE
nushell: update to 0.32.0. (waiting on Rust 1.52)

### PR DESCRIPTION
**Pull request by BlueChrystal**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

Won't compile till #30259 is merged.

### CODE REVIEW

**Comment by FollieHiyuki** [comment]
Ping for 0.33.0

**Comment by BlueChrystal** [comment]
Sorry, I don't have my Void machine with me right now, and won't do so for a while to come.

**Comment by ericonr** [comment]
Ping :)

**Comment by ericonr** [comment]
Superseded by #31813

**Comment by BlueChrystal** [comment]
Sorry, the "while" is still not done yet. :)

**Pull request closed without merging**
