### PR TITLE
firefox: Add New Window & New Private Window to firefox.desktop

### PR DESCRIPTION
**Pull request by HaimenToshi**

### CODE REVIEW

**Comment by Vaelatern** [comment]
The person here did not realize they can push changes without closing the PR.
https://github.com/void-linux/void-packages/pull/5884
Do not close PRs for no reason.

**Comment by Vaelatern** [comment]
I don't like this PR at all. Why do we track this .desktop file at all, and why are these changes going to be Void specific?

**Comment by HaimenToshi** [comment]
Well. Debian and Arch has these two options and they are useful, thank you.

**Comment by Vaelatern** [comment]
Does firefox itself not provide a .desktop file? Why are we providing one at all?

**Comment by jnbr** [comment]
We could use `taskcluster/docker/firefox-snap/firefox.desktop` from the firefox sources instead.

**Comment by Vaelatern** [comment]
Also the new-private-window feature seems outright broken.

I lack the language knowledge to verify these languages. I am pretty sure that all the void team put together can't verify these languages. We should not be in the business of customizing .desktop files. That's for upstream firefox, or maybe users who are interested in these things.

**Comment by jnbr** [comment]
I merged #6001 instead, will be effective with the next firefox rebuild.

**Pull request closed without merging**
