### PR TITLE
ueberzug: update to 18.1.8

### PR DESCRIPTION
**Pull request by FollieHiyuki**

### CODE REVIEW

**Comment by ericonr** [comment]
Please fix the linting error:

> srcpkgs/ueberzug/template:12: homepage should not use variables

**Comment by FollieHiyuki** [comment]
Sorry I didn't check

**Comment by ericonr** [comment]
No problem :)

Looking at it, this package really should be available on all archs... Coulld you switch `python3-pillow-simd` to `python3-Pillow` in `depends`? 

Could make it conditional on arch, if you want, so something like:

```
case $XBPS_TARGET_MACHINE in
	x86_64*) depends+=" python3-pillow-simd" ;;
	*) depends+=" python3-Pillow" ;;
esac
```

**Comment by FollieHiyuki** [comment]
I made the changes as you said. Didn't know `python3-pillow-simd` was not available on arm and i386.

1 question though: how can I cross build to arm. It complains about not having glibc (I'm on x86_64-musl)

**Comment by ericonr** [comment]
On musl you can only (currently) cross compile to arm musl. So something like `-a armv7l-musl` works.

**Comment by FollieHiyuki** [comment]
Thanks. I will look into it since 1 of my PRs fails on arm #26283 . Didn't know how to debug it locally when I couldn't cross build.

Can you take a look at it too if you have some time?

**Pull request merged**
