### PR TITLE
kdenlive: update to 18.04.3

### PR DESCRIPTION
**Pull request by jnbr**
[ci skip] because there are too many warnings during build for travis. ~~Local builds work.~~
Edit: my test script was wrong. aarch64[-musl] builds don't succeed.

### CODE REVIEW

**Comment by jnbr** [comment]
aarch64[-musl] breaks because of broken package signatures:
```
libblockdev-2.16_1.aarch64.xbps.sig: [512B 100%] 13MB/s ETA: 00m00s
libblockdev-2.16_1.aarch64.xbps.sig: 512B [avg rate: 13MB/s]
ERROR: libblockdev-2.16_1: the RSA signature is not valid!
ERROR: libblockdev-2.16_1: removed pkg archive and its signature.
```

**Comment by lemmi** [comment]
I'll run local builds this week.

**Comment by lemmi** [comment]
`x86_64` build fine, but `x86_64-musl` isn't quite happy yet. 

```
==> kdenlive__do-fetch_00-distfiles.log


==> kdenlive__do-extract_00-distfiles.log
=> kdenlive-18.04.2_1: extracting distfile(s), please wait...


==> kdenlive__post-extract_00-patches.log


==> kdenlive__pre-configure_00-gnu-configure-asneeded.log


==> kdenlive__pre-configure_01-override-config.log


==> kdenlive__pre-configure_02-script-wrapper.log


==> kdenlive__do_configure.log
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - not found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Could not set up the appstream test. appstreamcli is missing.
-- Looking for include file malloc.h
-- Looking for include file malloc.h - found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Found KF5XmlGui: /usr/lib/cmake/KF5XmlGui/KF5XmlGuiConfig.cmake (found version "5.43.0") 
-- Found KF5 >= 5.23.0 enabling icon coloring
-- Found KF5Archive: /usr/lib/cmake/KF5Archive/KF5ArchiveConfig.cmake (found version "5.43.0") 
-- Found KF5Bookmarks: /usr/lib/cmake/KF5Bookmarks/KF5BookmarksConfig.cmake (found version "5.43.0") 
-- Found KF5CoreAddons: /usr/lib/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.43.0") 
-- Found KF5Config: /usr/lib/cmake/KF5Config/KF5ConfigConfig.cmake (found version "5.43.0") 
-- Found KF5ConfigWidgets: /usr/lib/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake (found version "5.43.0") 
-- Found KF5DBusAddons: /usr/lib/cmake/KF5DBusAddons/KF5DBusAddonsConfig.cmake (found version "5.43.0") 
-- Found KF5KIO: /usr/lib/cmake/KF5KIO/KF5KIOConfig.cmake (found version "5.43.0") 
-- Found KF5WidgetsAddons: /usr/lib/cmake/KF5WidgetsAddons/KF5WidgetsAddonsConfig.cmake (found version "5.43.0") 
-- Found KF5NotifyConfig: /usr/lib/cmake/KF5NotifyConfig/KF5NotifyConfigConfig.cmake (found version "5.43.0") 
-- Found KF5NewStuff: /usr/lib/cmake/KF5NewStuff/KF5NewStuffConfig.cmake (found version "5.43.0") 
-- Found KF5Notifications: /usr/lib/cmake/KF5Notifications/KF5NotificationsConfig.cmake (found version "5.43.0") 
-- Found KF5GuiAddons: /usr/lib/cmake/KF5GuiAddons/KF5GuiAddonsConfig.cmake (found version "5.43.0") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
-- Found PythonInterp: /usr/bin/python (found version "3.6.5") 
-- Found KF5TextWidgets: /usr/lib/cmake/KF5TextWidgets/KF5TextWidgetsConfig.cmake (found version "5.43.0") 
-- Found KF5IconThemes: /usr/lib/cmake/KF5IconThemes/KF5IconThemesConfig.cmake (found version "5.43.0") 
-- Found KF5DocTools: /usr/lib/cmake/KF5DocTools/KF5DocToolsConfig.cmake (found version "5.43.0") 
-- Found KF5FileMetaData: /usr/lib/cmake/KF5FileMetaData/KF5FileMetaDataConfig.cmake (found version "5.43.0") 
-- Found KF5Crash: /usr/lib/cmake/KF5Crash/KF5CrashConfig.cmake (found version "5.43.0") 
-- Found KF5: success (found version "5.43.0") found components:  Archive Bookmarks CoreAddons Config ConfigWidgets DBusAddons KIO WidgetsAddons NotifyConfig NewStuff XmlGui Notifications GuiAddons TextWidgets IconThemes DocTools FileMetaData Crash 
-- Found KF5 FileMetadata to extract file metadata
-- Checking for module 'mlt++'
--   Found mlt++, version 6.8.0
-- Found MLT: /usr/lib/libmlt.so (found suitable version "6.8.0", minimum required is "6.6.0") 
-- Found SharedMimeInfo: /usr/bin/update-mime-database (found version "1.9") 
-- Found OpenGL: /usr/lib/libGL.so   
-- Found LibV4L2: /usr/include  
-- Looking for include file linux/input.h
-- Looking for include file linux/input.h - found
-- Found MLT++: /usr/lib/libmlt++.so
-- Found Qt5 WebKitWidgets. You can use your Freesound.org credentials to download files
-- The following RUNTIME packages have been found:

 * LibV4L2, Collection of video4linux support libraries, <http://freecode.com/projects/libv4l>
   Required for better webcam support

-- The following OPTIONAL packages have been found:

 * Qt5WebKit (required version >= 5.9.0)
 * Qt5WebKitWidgets
 * KF5DocTools
 * KF5FileMetaData
 * KF5Crash
 * PkgConfig

-- The following REQUIRED packages have been found:

 * ECM (required version >= 5.18.0)
 * Qt5Core
 * Qt5DBus
 * Qt5Gui (required version >= 5.10.1)
 * Qt5Widgets
 * Qt5Script
 * Qt5Svg
 * Qt5Network (required version >= 5.10.1)
 * Qt5Qml (required version >= 5.10.1)
 * Qt5Quick
 * Qt5Concurrent
 * Qt5
 * KF5Archive
 * KF5Bookmarks
 * KF5CoreAddons
 * KF5Config
 * KF5ConfigWidgets
 * KF5DBusAddons
 * KF5KIO
 * KF5WidgetsAddons
 * KF5NotifyConfig
 * KF5NewStuff
 * KF5XmlGui
 * KF5Notifications
 * KF5GuiAddons
 * Gettext
 * PythonInterp
 * KF5TextWidgets
 * KF5IconThemes
 * KF5
 * MLT (required version >= 6.6.0), Multimedia framework and video playout server for TV broadcasting, <http://mltframework.org>
   Required to do video processing
 * SharedMimeInfo, A database of common MIME types, <http://freedesktop.org/wiki/Software/shared-mime-info/>
 * OpenGL, the OpenGL library

-- Configuring done
-- Generating done
-- Build files have been written to: /builddir/kdenlive-18.04.2/build


==> kdenlive__pre-build_02-script-wrapper.log


==> kdenlive__do_build.log
Scanning dependencies of target po-es-docs-kdenlive-index-cache-bz2
Scanning dependencies of target tsfiles-2fba49a8e7456ad03509e3c24e73d20e
Scanning dependencies of target po-pt-BR-docs-kdenlive-index-cache-bz2
Scanning dependencies of target pofiles-2fba49a8e7456ad03509e3c24e73d20e
Scanning dependencies of target po-fr-docs-kdenlive-index-cache-bz2
Scanning dependencies of target po-nl-docs-kdenlive-index-cache-bz2
Scanning dependencies of target po-uk-docs-kdenlive-index-cache-bz2
Scanning dependencies of target po-ca-docs-kdenlive-index-cache-bz2
[  1%] Generating ts...
[  2%] Generating po/es/docs/kdenlive/index.cache.bz2
[  2%] Generating mo...
[  2%] Generating po/pt_BR/docs/kdenlive/index.cache.bz2
[  2%] Generating po/fr/docs/kdenlive/index.cache.bz2
[  3%] Generating po/nl/docs/kdenlive/index.cache.bz2
[  3%] Generating po/uk/docs/kdenlive/index.cache.bz2
[  3%] Generating po/ca/docs/kdenlive/index.cache.bz2
-- building... ar/kdenlive.po to kdenlive.mo
[  3%] Built target tsfiles-2fba49a8e7456ad03509e3c24e73d20e
Scanning dependencies of target po-de-docs-kdenlive-index-cache-bz2
[  3%] Generating po/de/docs/kdenlive/index.cache.bz2
-- building... ast/kdenlive.po to kdenlive.mo
-- building... bs/kdenlive.po to kdenlive.mo
-- building... ca/kdenlive.po to kdenlive.mo
-- building... ca@valencia/kdenlive.po to kdenlive.mo
-- building... cs/kdenlive.po to kdenlive.mo
-- building... da/kdenlive.po to kdenlive.mo
-- building... de/kdenlive.po to kdenlive.mo
-- building... el/kdenlive.po to kdenlive.mo
I/O warning : failed to load external entity "/usr/share/kf5/kdoctools/customization/xsl/pt-BR.xml"
No "pt_br" localization of "footer-doc-comment" exists; using "en".
-- building... en_GB/kdenlive.po to kdenlive.mo
No "pt_br" localization of "footer-doc-feedback" exists; using "en".
No "pt_br" localization of "footer-doc-teamname" exists; using "en".
No "pt_br" localization of "footer-doc-comment" exists; using "en".
No "pt_br" localization of "footer-doc-feedback" exists; using "en".
No "pt_br" localization of "footer-doc-teamname" exists; using "en".
-- building... es/kdenlive.po to kdenlive.mo
No "pt_br" localization of "footer-doc-comment" exists; using "en".
No "pt_br" localization of "footer-doc-feedback" exists; using "en".
No "pt_br" localization of "footer-doc-teamname" exists; using "en".
No "pt_br" localization of "footer-doc-comment" exists; using "en".
No "pt_br" localization of "footer-doc-feedback" exists; using "en".
No "pt_br" localization of "footer-doc-teamname" exists; using "en".
No "pt_br" localization of "footer-doc-comment" exists; using "en".
No "pt_br" localization of "footer-doc-feedback" exists; using "en".
No "pt_br" localization of "footer-doc-teamname" exists; using "en".
No "pt_br" localization of "footer-doc-comment" exists; using "en".
No "pt_br" localization of "footer-doc-feedback" exists; using "en".
No "pt_br" localization of "footer-doc-teamname" exists; using "en".
No "pt_br" localization of "footer-doc-comment" exists; using "en".
No "pt_br" localization of "footer-doc-feedback" exists; using "en".
No "pt_br" localization of "footer-doc-teamname" exists; using "en".
[  3%] Built target po-nl-docs-kdenlive-index-cache-bz2
-- building... et/kdenlive.po to kdenlive.mo
Scanning dependencies of target po-it-docs-kdenlive-index-cache-bz2
[  3%] Built target po-ca-docs-kdenlive-index-cache-bz2
[  3%] Built target po-es-docs-kdenlive-index-cache-bz2
[  3%] Built target po-fr-docs-kdenlive-index-cache-bz2
[  3%] Built target po-uk-docs-kdenlive-index-cache-bz2
[  3%] Generating po/it/docs/kdenlive/index.cache.bz2
Scanning dependencies of target po-pt-docs-kdenlive-index-cache-bz2
Scanning dependencies of target po-sv-docs-kdenlive-index-cache-bz2
Scanning dependencies of target doc-index-cache-bz2
Scanning dependencies of target kdenlive_render_autogen
[  3%] Generating po/pt/docs/kdenlive/index.cache.bz2
[  4%] Generating po/sv/docs/kdenlive/index.cache.bz2
[  4%] Generating index.cache.bz2
[  4%] Automatic MOC for target kdenlive_render
[  4%] Built target po-pt-BR-docs-kdenlive-index-cache-bz2
-- building... eu/kdenlive.po to kdenlive.mo
Scanning dependencies of target media_ctrl_autogen
[  5%] Automatic MOC for target media_ctrl
[  5%] Built target po-de-docs-kdenlive-index-cache-bz2
[  5%] Built target media_ctrl_autogen
Scanning dependencies of target kiss_fft_autogen
Scanning dependencies of target mltpreview_autogen
-- building... fi/kdenlive.po to kdenlive.mo
[  5%] Automatic MOC for target kiss_fft
[  5%] Automatic MOC for target mltpreview
[  5%] Built target kiss_fft_autogen
[  5%] Built target kdenlive_render_autogen
Scanning dependencies of target media_ctrl
-- building... fr/kdenlive.po to kdenlive.mo
Scanning dependencies of target kiss_fft
[  5%] Built target mltpreview_autogen
[  6%] Building C object src/lib/external/media_ctrl/CMakeFiles/media_ctrl.dir/mediactrl.c.o
[  6%] Building C object src/lib/external/kiss_fft/CMakeFiles/kiss_fft.dir/kiss_fft.c.o
Scanning dependencies of target kdenlive_render
-- building... ga/kdenlive.po to kdenlive.mo
[  7%] Building CXX object renderer/CMakeFiles/kdenlive_render.dir/kdenlive_render.cpp.o
-- building... gl/kdenlive.po to kdenlive.mo
-- building... he/kdenlive.po to kdenlive.mo
[  7%] Building CXX object src/lib/external/media_ctrl/CMakeFiles/media_ctrl.dir/media_ctrl_autogen/mocs_compilation.cpp.o
-- building... hr/kdenlive.po to kdenlive.mo
[  7%] Linking CXX static library libmedia_ctrl.a
[  7%] Built target media_ctrl
[  7%] Building CXX object renderer/CMakeFiles/kdenlive_render.dir/renderjob.cpp.o
-- building... hu/kdenlive.po to kdenlive.mo
-- building... id/kdenlive.po to kdenlive.mo
-- building... it/kdenlive.po to kdenlive.mo
-- building... ja/kdenlive.po to kdenlive.mo
[  7%] Built target doc-index-cache-bz2
[  7%] Built target po-sv-docs-kdenlive-index-cache-bz2
[  7%] Building CXX object renderer/CMakeFiles/kdenlive_render.dir/kdenlive_render_autogen/mocs_compilation.cpp.o
[  7%] Built target po-it-docs-kdenlive-index-cache-bz2
[  7%] Building C object src/lib/external/kiss_fft/CMakeFiles/kiss_fft.dir/tools/kiss_fftr.c.o
Scanning dependencies of target mltpreview
[  7%] Built target po-pt-docs-kdenlive-index-cache-bz2
-- building... lt/kdenlive.po to kdenlive.mo
[  8%] Building CXX object src/lib/external/kiss_fft/CMakeFiles/kiss_fft.dir/kiss_fft_autogen/mocs_compilation.cpp.o
-- building... mr/kdenlive.po to kdenlive.mo
[  8%] Building CXX object thumbnailer/CMakeFiles/mltpreview.dir/mltpreview.cpp.o
[  8%] Building CXX object thumbnailer/CMakeFiles/mltpreview.dir/mltpreview_autogen/mocs_compilation.cpp.o
-- building... nb/kdenlive.po to kdenlive.mo
-- building... nds/kdenlive.po to kdenlive.mo
-- building... nl/kdenlive.po to kdenlive.mo
In file included from /usr/include/time.h:31:0,
                 from /usr/include/pthread.h:31,
                 from /usr/include/mlt/framework/mlt_consumer.h:28,
                 from /usr/include/mlt/framework/mlt.h:46,
                 from /usr/include/mlt++/MltAnimation.h:26,
                 from /usr/include/mlt++/Mlt.h:24,
                 from /builddir/kdenlive-18.04.2/thumbnailer/mltpreview.h:27,
                 from /builddir/kdenlive-18.04.2/thumbnailer/mltpreview.cpp:21:
/usr/include/bits/alltypes.h:368:34: error: conflicting declaration 'typedef struct __locale_struct* locale_t'
 typedef struct __locale_struct * locale_t;
                                  ^~~~~~~~
In file included from /usr/include/mlt/framework/mlt_animation.h:27:0,
                 from /usr/include/mlt/framework/mlt.h:39,
                 from /usr/include/mlt++/MltAnimation.h:26,
                 from /usr/include/mlt++/Mlt.h:24,
                 from /builddir/kdenlive-18.04.2/thumbnailer/mltpreview.h:27,
                 from /builddir/kdenlive-18.04.2/thumbnailer/mltpreview.cpp:21:
/usr/include/mlt/framework/mlt_property.h:38:15: note: previous declaration as 'typedef char* locale_t'
 typedef char* locale_t;
               ^~~~~~~~
-- building... pl/kdenlive.po to kdenlive.mo
[  8%] Linking CXX static library libkiss_fft.a
-- building... pt/kdenlive.po to kdenlive.mo
[  8%] Built target kiss_fft
Scanning dependencies of target kdenlive_autogen
[  8%] Automatic MOC for target kdenlive
-- building... pt_BR/kdenlive.po to kdenlive.mo
-- building... ro/kdenlive.po to kdenlive.mo
-- building... ru/kdenlive.po to kdenlive.mo
-- building... sk/kdenlive.po to kdenlive.mo
-- building... sl/kdenlive.po to kdenlive.mo
-- building... sv/kdenlive.po to kdenlive.mo
-- building... tr/kdenlive.po to kdenlive.mo
-- building... ug/kdenlive.po to kdenlive.mo
-- building... uk/kdenlive.po to kdenlive.mo
-- building... zh_CN/kdenlive.po to kdenlive.mo
-- building... zh_TW/kdenlive.po to kdenlive.mo
[  8%] Built target pofiles-2fba49a8e7456ad03509e3c24e73d20e
make[2]: *** [thumbnailer/CMakeFiles/mltpreview.dir/build.make:63: thumbnailer/CMakeFiles/mltpreview.dir/mltpreview.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1897: thumbnailer/CMakeFiles/mltpreview.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  9%] Linking CXX executable kdenlive_render
[  9%] Built target kdenlive_render
[  9%] Built target kdenlive_autogen
make: *** [Makefile:141: all] Error 2
=> ERROR: kdenlive-18.04.2_1: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 2
=> ERROR:   in do_build() at common/build-style/cmake.sh:49

```

**Comment by jnbr** [comment]
this was because of the mlt update. fixed.

**Comment by jnbr** [comment]
local builds for all architectures succeeded now

**Comment by jnbr** [comment]
Rebased and bumped to 18.04.3. Local builds work, no real changes between 18.04.2 and 18.04.3.

**Pull request closed without merging**
