### PR TITLE
New package: kubectx-0.7.1

### PR DESCRIPTION
**Pull request by juantascon**

### CODE REVIEW

**Comment by xtraeme** [comment]
missing `archs=noarch`

**Comment by juantascon** [comment]
@xtraeme fixed!

**Comment by juantascon** [comment]
hey @xtraeme could you please review again

**Comment by juantascon** [comment]
@ailiop-git could you please review this pullrq

**Comment by juantascon** [comment]
@travankor could you please review this pullrq

**Comment by travankor** [comment]
you should not use vbin when you can build from source

**Comment by travankor** [comment]
All you're packaging is the wrapper scripts, not the actual binary

**Comment by travankor** [comment]
You should package the golang binary, not the shell scripts.

**Comment by juantascon** [comment]
@travankor I'm packaging the binary too: 

```vbin kubectx```

**Comment by travankor** [comment]
it's the bash version

**Comment by eoli3n** [comment]
any update on this ?

**Comment by eoli3n** [comment]
@juantascon would you update the template to 0.9.3 please ?

**Comment by abenson** [comment]
Seemingly abandoned.

**Pull request closed without merging**
