### PR TITLE
python3-SecretStorage: update to 3.3.1.

### PR DESCRIPTION
**Pull request by RunningDroid**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by RunningDroid** [comment]
I'm gonna have to set XBPS_CHECK_PKGS on my local repo.

**Comment by RunningDroid** [comment]
I think the tests are trying to start gnome-keyring via dbus but failing for some reason. I'll look at this some more tomorrow.

**Comment by RunningDroid** [comment]
The tests work locally, I have why they're failing on the CI.

**Comment by ericonr** [comment]
You can add `make_check=ci-skip` to the template, then.

**Comment by RunningDroid** [comment]
@ericonr done

**Pull request merged**
