### PR TITLE
linux5.15/ntfs-3g: use mount.ntfs as alternative

### PR DESCRIPTION
**Pull request by Animeshz**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by Animeshz** [comment]
Default mount `mount /dev/sdxx /mnt/point` without explicit `-t ntfs3` or `-t ntfs-3g` to be controlled by xbps-alternatives.

**Comment by ericonr** [comment]
This is definitely the wrong place for this; otherwise linux5.16 will have to carry the same alternative, then 5.17, then ...

It does sound like something we should fix, though. I assume that if you uninstall ntfs-3g, it uses the kernel's driver automatically?

**Comment by Animeshz** [comment]
@ericonr  It does not, it mounts with read-only driver ntfs, we've to specify `-t ntfs3` properly for the new 5.15's `ntfs3` driver. For ntfs-3g it automatically selects `ntfs-3g` instead of `ntfs`.

**Comment by Animeshz** [comment]
Problem is ntfs-3g overwrite the symlink to `/usr/bin/mount.ntfs`, so even if linux5.15+ able to overwrite it, later after removal of ntfs-3g it'll be a broken symlink, which i think is properly managed by `xbps-alternatives`.

**Comment by ericonr** [comment]
> it mounts with read-only driver ntfs, we've to specify -t ntfs3 properly for the new 5.15's ntfs3

Wow, that really sucks :/

And yes, alternatives sounds reasonable-ish to solve this, except that if one opts into the new driver, booting into an older kernel and trying to mount something via ntfs won't work properly.

I will open an issue with upstream util-linux.

**Comment by ericonr** [comment]
https://github.com/util-linux/util-linux/issues/1508

**Pull request closed without merging**
