### PR TITLE
GNS3 2.2.35 - new version supports Python 3.11

### PR DESCRIPTION
**Pull request by tsndqst**
Python 3.11 support was added to GNS3 2.2.35.
A new required library was added to 2.2.35 so a new Void package was created.

#### Testing the changes
- I tested the changes in this PR: **briefly**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-GLIBC)

For reference, `gns3` 2.2.34 fails

### CODE REVIEW

**Comment by classabbyamp** [comment]
is this using parts of importlib_resources that are not already part of py3.11? that package is made for backporting/feature preview for the stdlib module

**Comment by classabbyamp** [comment]
yeah it looks like they didn't consider newer python versions for this. could totally patch out the dependency with

requirements.txt:
```diff
- importlib-resources>=1.3
+ importlib-resources>=1.3; python_version < '3.9'
```
all the places they use the library (see https://github.com/GNS3/gns3-server/pull/2133):
```diff
- import importlib_resources
+ try:
+     from importlib import resources as importlib_resources
+ except ImportError:
+     import importlib_resources
```

**Comment by tsndqst** [comment]
Yes.  I'm working on the patch now.  I noticed the backport description in the importlib_resources repo but didn't take the time to see how it would work without it.  Using `importlib.resources` seems to work fine.

**Comment by tsndqst** [comment]
@classabbyamp I started working on a naive patch before I saw your solution.  I like yours better.  I wrote up a patch with your code.

**Pull request merged**
