### PR TITLE
retroarch: update to 1.14.0

### PR DESCRIPTION
**Pull request by Vinfall**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for this architecture:
  - armv6l-musl (crossbuild)

### CODE REVIEW

**Comment by classabbyamp** [comment]
please add the email you used to commit to your github account

**Comment by Vinfall** [comment]
I thought I added via https://github.com/void-linux/void-packages/commit/6b07ccff5b0bc62ca1765e7b5fc39c72f1581f10 that already? I just didn't sign the commit as the PGP key is associated to the no-reply email, not this one.

**Comment by classabbyamp** [comment]
github is showing you committed with an `@riseup.net` email, but the lack of profile image on the commit line above indicates that github doesn't know whose account to associate it with

**Comment by Vinfall** [comment]
I hope it should be fine now.

**Comment by classabbyamp** [comment]
yep, looks good now

**Pull request merged**
