### PR TITLE
Fix svnserve startup to "daemonize" but run in foreground. 

### PR DESCRIPTION
**Pull request by TOertel**
(One of -d -i -t or -X must be provided.)

Also, fix 'run' script to allow config file with custom run options.

### CODE REVIEW

**Comment by maxice8** [comment]
please keep everything in a single commit

**Comment by TOertel** [comment]
Sorry, I don't go through this process very often...

**Comment by TOertel** [comment]
Hopefully I did that correctly... If not, I don't know how to fix it...

**Comment by abenson** [comment]
Commit message should also be something like: `subversion: make svnserve daemonize`

**Pull request merged**
