### PR TITLE
telegram-desktop: fix i686

### PR DESCRIPTION
**Pull request by Johnnynator**
Compilation succeeded fine locally

### CODE REVIEW

**Comment by maxice8** [comment]
mine fails with 

[ 91%] Linking CXX executable Telegram
/usr/lib/gcc/i686-pc-linux-gnu/7.3.0/../../../libQt5Network.so: warning: EVP_CipherFinal is often misused, please use EVP_CipherFinal_ex and EVP_CIPHER_CTX_cleanup
CMakeFiles/Telegram.dir/builddir/tdesktop-1.3.7/Telegram/SourceFiles/ui/effects/radial_animation.o: In function `Ui::InfiniteRadialAnimation::computeState()':
radial_animation.cpp:(.text+0x11b3): undefined reference to `__wrap___divmoddi4'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/Telegram.dir/build.make:8582: Telegram] Error 1
make[1]: *** [CMakeFiles/Makefile2:494: CMakeFiles/Telegram.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by Johnnynator** [comment]
You are sure that you use my branch with the patch here? I did test it in a fully clean environment so I can not think of a reason why it should fail that way.

**Comment by maxice8** [comment]
On Sun, Jun 17, 2018 at 12:08:43PM -0700, John Zimmermann wrote:
> You are sure that you use my branch with the patch here? I did test it in a fully clean environment so I can not think of a reason why it should fail that way.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/187#issuecomment-397899642

yep, i'll try again after merging a few PRs

**Comment by maxice8** [comment]
yep, turns out i was with the old one, finishing rebuilding here and will merge

**Pull request merged**
