### PR TITLE
racer: remove

### PR DESCRIPTION
**Pull request by maxice8**
@Cogitri

### CODE REVIEW

**Comment by jnbr** [comment]
Is there any reason besides that we can not update to the latest version?

**Comment by maxice8** [comment]
On Mon, Jan 14, 2019 at 11:02:18PM -0800, Johannes wrote:
> Is there any reason besides that we can not update to the latest version?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/7158#issuecomment-454287594

No

**Comment by jnbr** [comment]
ok, so you prefer breaking peoples tool chains over having an out of date package?

**Comment by maxice8** [comment]
On Mon, Jan 14, 2019 at 11:11:51PM -0800, Johannes wrote:
> ok, so you prefer breaking peoples tool chains over having an out of date package?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/7158#issuecomment-454289362

1. Why are developers using a super old version ?
2. I don't want to give the illusion we actually care about a package using nightly features
3. Developer can conveniently install the latest version (correct thing) with a single command

#2437

**Comment by jnbr** [comment]
> 1. Why are developers using a super old version ?

as long as the code completer completes code, they might not care how old it is

> 2. I don't want to give the illusion we actually care about a package using nightly features

fair point

> 3. Developer can conveniently install the latest version (correct thing) with a single command

true for glibc systems blessed by upstream

**Comment by jnbr** [comment]
While at it, `rustfmt` should be kept or removed for the same reason.

**Comment by Cogitri** [comment]
> true for glibc systems blessed by upstream

I feel like we should keep racer and rustfmt for that reason, otherwise rust development on musl will be kind of annoying

**Comment by maxice8** [comment]
On Tue, Jan 15, 2019 at 08:18:17AM +0000, Rasmus Thomsen wrote:
> > true for glibc systems blessed by upstream
> 
> I feel like we should keep racer and rustfmt for that reason, otherwise rust development on musl will be kind of annoying
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/7158#issuecomment-454303698

Fair

**Pull request closed without merging**
