### PR TITLE
netcdf : update to 4.7.4

### PR DESCRIPTION
**Pull request by pandom79**
required by hdf5

### CODE REVIEW

**Review by Piraty — CHANGES_REQUESTED** [review]
please switch to `vsed`

**Comment by pandom79** [comment]
> please switch to `vsed`

vsed in place of netcdf?

**Comment by pandom79** [comment]
> please switch to `vsed`

consider it already done...ahahah

**Comment by ahesford** [comment]
Please incorporate with #25569 because this must be built *after* `hdf5`.

**Pull request closed without merging**
