### PR TITLE
streamlink: update to 6.7.3

### PR DESCRIPTION
**Pull request by tstraus13**
It is a requirement for updating the streamlink package which I plan to do once this has been accepted/merged. I have been looking at the streamlink package and it is a little behind and this seems to be the only missing python3 package from the repositories that it needs. Void currently has the python3-trio package, which is used as a starting point for this template. If there is more that is needed for this package, or if I missed anything, in the template let me know. Thanks.

#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86-64-musl

### CODE REVIEW

**Comment by tstraus13** [comment]
It was having issues with the tests and so I added a line similar to the python3-trio package to ignore the test. Though it is still failing on Github CI/CD for some reason. It is building alright on my machine. Let me know what I am missing. Thanks.

**Comment by classabbyamp** [comment]
> which I plan to do once this has been accepted/merged

just do it in this PR

**Comment by tstraus13** [comment]
Ok. I was not sure if I needed to do 1 PR per package. I will try to get the streamlink package in this PR as well. Thanks.

**Comment by tstraus13** [comment]
So it turns out there is one more dependency for streamlink. It is python-exceptiongroup. I am not able to compile as it only has a pyproject.toml file and no setup.py file. I am not very familiar with Python compilation. On my side its just complaining about the build step and trying to run the do_build step by executing 'python3 setup.py build ${make_build_args}' but setup.py does not exist.

**Comment by classabbyamp** [comment]
use the `python3-pep517` build style

**Comment by tstraus13** [comment]
> use the `python3-pep517` build style

I am not getting a build error about flit_scm - "ModuleNotFoundError: No module named 'flit_scm'" and after that message "ERROR Backend 'flit_scm:buildapi' is not available.". Does that mean that flit_scm is now a required additional package?

**Comment by classabbyamp** [comment]
exceptiongroup shouldn't be needed, it's a compatibility backport for <3.11. upstream didn't do any kind of check for python >=3.11 so we should just patch it out:

<details><summary>add this to `srcpkgs/streamlink/patches/`</summary>
<p>

```patch
exceptiongroup is for python<3.11 compat

--- a/src/streamlink.egg-info/requires.txt
+++ b/src/streamlink.egg-info/requires.txt
@@ -1,5 +1,4 @@
 certifi
-exceptiongroup
 isodate
 lxml<6,>=4.6.4
 pycountry
--- a/src/streamlink.egg-info/PKG-INFO
+++ b/src/streamlink.egg-info/PKG-INFO
@@ -32,7 +32,6 @@
 Description-Content-Type: text/markdown
 License-File: LICENSE
 Requires-Dist: certifi
-Requires-Dist: exceptiongroup
 Requires-Dist: isodate
 Requires-Dist: lxml<6,>=4.6.4
 Requires-Dist: pycountry
--- a/PKG-INFO
+++ b/PKG-INFO
@@ -32,7 +32,6 @@
 Description-Content-Type: text/markdown
 License-File: LICENSE
 Requires-Dist: certifi
-Requires-Dist: exceptiongroup
 Requires-Dist: isodate
 Requires-Dist: lxml<6,>=4.6.4
 Requires-Dist: pycountry
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -56,7 +56,6 @@
 requires-python = ">=3.8"
 dependencies = [
   "certifi",
-  "exceptiongroup",
   "isodate",
   "lxml >=4.6.4,<6",
   "pycountry",
--- a/src/streamlink/plugins/twitch.py
+++ b/src/streamlink/plugins/twitch.py
@@ -541,7 +541,6 @@
         headers: Mapping[str, str],
         device_id: str,
     ) -> Optional[Tuple[str, int]]:
-        from exceptiongroup import BaseExceptionGroup  # noqa: PLC0415, I001
         from streamlink.webbrowser.cdp import CDPClient, CDPClientSession, devtools  # noqa: PLC0415
 
         url = f"https://www.twitch.tv/{channel}"
--- a/src/streamlink/webbrowser/webbrowser.py
+++ b/src/streamlink/webbrowser/webbrowser.py
@@ -8,7 +8,6 @@
 from typing import AsyncContextManager, AsyncGenerator, Generator, List, Optional, Union
 
 import trio
-from exceptiongroup import BaseExceptionGroup
 
 from streamlink.utils.path import resolve_executable
 from streamlink.webbrowser.exceptions import WebbrowserError
--- a/src/streamlink/compat.py
+++ b/src/streamlink/compat.py
@@ -5,9 +5,6 @@
 import warnings
 from typing import Any, Callable, Dict, Optional, Tuple
 
-# import exceptiongroup, so it can monkeypatch ExceptionGroup logic on <=py311
-import exceptiongroup  # noqa: F401
-
 from streamlink.exceptions import StreamlinkDeprecationWarning
 
 
--- a/tests/webbrowser/test_webbrowser.py
+++ b/tests/webbrowser/test_webbrowser.py
@@ -7,7 +7,6 @@
 
 import pytest
 import trio
-from exceptiongroup import BaseExceptionGroup
 
 from streamlink.compat import is_win32
 from streamlink.webbrowser.exceptions import WebbrowserError
--- a/tests/webbrowser/cdp/test_connection.py
+++ b/tests/webbrowser/cdp/test_connection.py
@@ -7,7 +7,6 @@
 
 import pytest
 import trio
-from exceptiongroup import ExceptionGroup
 from trio.testing import MockClock, wait_all_tasks_blocked
 from trio_websocket import CloseReason, ConnectionClosed, ConnectionTimeout  # type: ignore[import]
 
--- a/tests/webbrowser/cdp/test_client.py
+++ b/tests/webbrowser/cdp/test_client.py
@@ -4,7 +4,6 @@
 
 import pytest
 import trio
-from exceptiongroup import ExceptionGroup
 from trio.testing import wait_all_tasks_blocked
 
 from streamlink.session import Streamlink
```

</p>
</details>

**Comment by tstraus13** [comment]
Ok will do. Thats good news. Ill scrap everything except trio-websocket and streamlink then. Ill do a build and make sure it all works. I may have to step away for some time but I think I'll be able to finish it up at some point today. Thanks for your help.

**Comment by tstraus13** [comment]
Ok well I just went ahead and made the required changes. streamlink should be ready. It compiled fine but I am not testing the package install and then the executable in a VM.

**Comment by tstraus13** [comment]
Ok I tested the package installed on a VM and it seems good to go. Thanks again. If there is anything else I am missing let me know.

**Comment by tstraus13** [comment]
I am not sure why the check is not passing but I was successfully about to build, install, and run the package locally.

**Comment by tstraus13** [comment]
@classabbyamp Is there anything else that needs done with this? If you can see a way to fix the Check errors let me know. I am not sure why exactly it fails but I am able to build, install, and run the package locally. Thanks.

**Comment by classabbyamp** [comment]
it succeeds locally because you probably aren't running the check phase, add -Q to do that

**Comment by tstraus13** [comment]
Ok I get the error now but I am still unsure how to fix.

**Comment by classabbyamp** [comment]
the tarball from pypi probably doesn't include tests. you might want to try using one from git directly

**Comment by tstraus13** [comment]
I do tell it to ignore the tests file as they fail otherwise. I took that from the python3-trio package.

**Comment by tstraus13** [comment]
I will attempt to pull from git directly though just in case.

**Comment by tstraus13** [comment]
I am getting this error not when attempting to build "neither chroot-git or git are available in your system!" and when I go into chroot via xbps-src chroot and attempt to install git I get this error.

Certificate verification failed for /C=US/O=Let's Encrypt/CN=R3
SSL_connect returned 1
ERROR: [trans] failed to download `gdbm-1.23_1' signature from `https://repo-default.voidlinux.org/current': Operation not permitted
Transaction failed! see above for errors.

I will try again later.

**Comment by classabbyamp** [comment]
also, the streamlink commit should be like i titled the PR

**Comment by tstraus13** [comment]
> also, the streamlink commit should be like i titled the PR

Ok I will change it then. Thanks.

**Comment by tstraus13** [comment]
Even pulling from the git repo for trio-websocket I am getting the same error.

**Comment by classabbyamp** [comment]
ah well, you disabled the only tests: https://github.com/python-trio/trio-websocket/tree/master/tests

use `make_check=no # reason in a comment` instead

**Comment by tstraus13** [comment]
@classabbyamp Ok I think I have things good to go. Let me know if there is anything else needed. Thanks.

**Pull request closed without merging**
