### PR TITLE
libGL: update to 18.2.0.

### PR DESCRIPTION
**Pull request by maxice8**
@q66 need aarch64 test
@newbluemoon musl testing

### CODE REVIEW

**Comment by Cogitri** [comment]
Works for me with radeonsi and i965 on x86_64

**Comment by prspkt** [comment]
Works for me as well with x86_64-musl i965

**Comment by newbluemoon** [comment]
Tested on x86_64-musl (mesa-ati-dri) and armv7l-musl (mesa-vc4-dri), no problems so far. i686 seems to be ok, too.

**Comment by lemmi** [comment]
So far no problems on `x86_64` and `amdgpu` with a `Vega 64`.

**Pull request closed without merging**
