### PR TITLE
New package: blocaled-0.6

### PR DESCRIPTION
**Pull request by pondichys**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86_64-musl
  - armv7l
  - armv6l

### CODE REVIEW

**Comment by pondichys** [comment]
I have no idea why those 4 tests are failing in the pipeline as they all pass fine on both my glibc and musl void installs ... any idea how I can reproduce the environment of the CI agents locally on my workstation? I'm busy trying to reproduce the CI workflow but it's not that easy :)

**Comment by classabbyamp** [comment]
did you run xbps-src with -Q?

**Comment by classabbyamp** [comment]
also ci runs as root so that might be it

**Comment by pondichys** [comment]
Hello @classabbyamp ,
Thanks for your feedback.

Yes I ran the package build with -Q. I'll try as root and check how it's going on.

**Comment by pondichys** [comment]
Ok I found why those tests are failing. As you mentioned @classabbyamp the bild is running as root. The failing tests are all related to permissions. They ensure that the service cannot write to directories the user has no access to. That runs perfectly well with a non root user but as soon as you run those as root, for sure there are no permission issues and the tests fail because the expected error does not happen.

Now, I guess that I could patch the tests to avoid the fault but if you have another idea that fits better in the usual process used for these kind of issues, I'll take it.

Once again thanks for the help.

**Comment by classabbyamp** [comment]
`make_check=ci-skip # some tests check permissions`

**Comment by pondichys** [comment]
I implemented the workaround. Many thanks for your help.

**Pull request closed without merging**
