### PR TITLE
New package: faba-icon-theme-4.3

### PR DESCRIPTION
**Pull request by shizonic**

### CODE REVIEW

**Comment by shizonic** [comment]
I thought it's a convetion of void packages to use versioning in the x.x.x format. If not I will fix it asap.

**Comment by Johnnynator** [comment]
Nope. Void normally just uses whatever upstream is using.

**Comment by shizonic** [comment]
Okay, sorry. I will consider this for future packages and fix this one as soon as I am at home.

**Comment by shizonic** [comment]
@Johnnynator Okay updated as you suggested.

**Pull request merged**
