### PR TITLE
New package: linux5.3

### PR DESCRIPTION
**Pull request by foxlet**
Linux 5.3 kernel.

### CODE REVIEW

**Comment by Hoshpak** [comment]
I know that is still WIP but I still wanted to state early that I don't want to become matainer of this kernel version so please remove me from the maintainer field before it's ready to merge.

Also there's #13569 which probably only needs minor adjustments for the final version so you could build on that.

**Comment by foxlet** [comment]
> I know that is still WIP but I still wanted to state early that I don't want to become matainer of this kernel version so please remove me from the maintainer field before it's ready to merge.
> 
> Also there's #13569 which probably only needs minor adjustments for the final version so you could build on that.

Anyone else who wanted to maintain it?

**Comment by steinex** [comment]
You seem to have taken the configs from Gottox' PR and didn't olddefconfig yourself, there are a few things (I only looked at x86_64) that I noticed:

* `CONFIG_GCC_VERSION` should be raised to 90200.
* Your config has `CONFIG_PSI` unset but linux5.2 has that set in combination with `CONFIG_PSI_DEFAULT_DISABLED=y`. It was probably decided to enable this before Gottox' PR appeared.
* linux5.2 has `CONFIG_IXP4XX_NPE=m`, this config misses that module.

**Comment by steinex** [comment]
That being said, do you mind including the following patchset: https://patchwork.freedesktop.org/series/64505/
The patchset is already merged for 5.4 and fixes a Kernel Oops for AMD Vega users. Here is the corresponding bug report: https://bugzilla.kernel.org/show_bug.cgi?id=204181 

I already tested that the patch applies to 5.3.

We talked in #xbps about it and the consensus was it's fine to include such patches (especially if they fix a serious regression) if they are temporary anyway. It may well be that it will be backported into one of the 5.3 stable kernels.

Thanks!

**Comment by foxlet** [comment]
> You seem to have taken the configs from Gottox' PR and didn't olddefconfig yourself, there are a few things (I only looked at x86_64) that I noticed:

Not sure what commit you were looking at, but the dotconfigs were already updated.

**Comment by steinex** [comment]
> Not sure what commit you were looking at, but the dotconfigs were already updated.

I somehow got it wrong indeed, sorry about that.

**Comment by leahneukirchen** [comment]
Please bump to 5.3.1 then this can be merged.

**Pull request merged**
