### PR TITLE
screenkey: update to 1.2.

### PR DESCRIPTION
**Pull request by not-chicken**

### CODE REVIEW

**Comment by Chocimier** [comment]
There are more mandatory dependencies. Tests fail.

**Comment by not-chicken** [comment]
Updated dependencies and removed `noarch`.

**Comment by Chocimier** [comment]
Tests still fail. Add python3-cairo to depends and checkdepends="${depends} libXtst"

**Comment by not-chicken** [comment]
>Tests still fail

Idk if I'm doing something wrong, but `./xbps-src check` always gives `Ran 0 tests in 0.000s. OK` for me, even after proposed changes. Lacks a test suite?
 Or are you referring to something else?

**Comment by Chocimier** [comment]
If you look at any dependencies list (webpage, setup.py, requires.txt, script itself), pycairo is there.

Yes, `./xbps-src check`. "Ran 0 tests in 0.000s" is good, it means tests were run but not counted, or at least module was imported.

Interesting that it passes for you, here it is

```
=> screenkey-1.2_1: running do_check ...
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
WARNING: The pip package is not available, falling back to EasyInstall for handling setup_requires/test_requires; this is deprecated and will be removed in a future version.
Searching for pycairo
Reading https://pypi.org/simple/pycairo/
Downloading https://files.pythonhosted.org/packages/e8/9d/c8be300fc6b1298559d37a071c3833b0b251e0fff334d2e4c408d5789162/pycairo-1.19.1.tar.gz#sha256=2c143183280feb67f5beb4e543fd49990c28e7df427301ede04fc550d3562e84
Best match: pycairo 1.19.1
Processing pycairo-1.19.1.tar.gz
Writing /tmp/easy_install-1tkis69f/pycairo-1.19.1/setup.cfg
Running pycairo-1.19.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-1tkis69f/pycairo-1.19.1/egg-dist-tmp-qk9enuph
no previously-included directories found matching 'docs/_build'
warning: no files found matching 'README' under directory 'tests'
warning: no files found matching 'README' under directory 'examples'
error: Setup script exited with 'pkg-config' not found.
Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']
=> ERROR: screenkey-1.2_1: do_check: 'python3 setup.py ${make_check_target} ${make_check_args}' exited with 1
=> ERROR:   in do_check() at common/build-style/python3-module.sh:35
```
first, then 
```
=> screenkey-1.2_1: running do_check ...
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing screenkey.egg-info/PKG-INFO
writing dependency_links to screenkey.egg-info/dependency_links.txt
writing requirements to screenkey.egg-info/requires.txt
writing top-level names to screenkey.egg-info/top_level.txt
reading manifest file 'screenkey.egg-info/SOURCES.txt'
writing manifest file 'screenkey.egg-info/SOURCES.txt'
running build_ext
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```
what means tests skipped, but dependencies are present.

Maybe you run it in some equipped masterdir?

**Comment by not-chicken** [comment]
> Maybe you run it in some equipped masterdir?

Indeed, I had a package installed there from some previous testing. My bad.

> If you look at any dependencies list (webpage, setup.py, requires.txt, script itself), pycairo is there.

Yes, but since it was implicitly pulled in via `python3-gobject`, it was left out. 
I haven't added it in recent push, let me know if there's any drawback in this approach.

**Pull request merged**
