### PR TITLE
New package: rumatui-0.1.19

### PR DESCRIPTION
**Pull request by jcgruenhage**

### CODE REVIEW

**Comment by jcgruenhage** [comment]
This is blocked on olm-rs not cross compiling correctly. Not sure whether this is something that needs to be fixed in Void's infra or upstream.

**Comment by Chocimier** [comment]
Upstream, it uses $CC then switches to gcc with no reason, strange.

https://travis-ci.org/github/void-linux/void-packages/jobs/700848455#L774

**Comment by jcgruenhage** [comment]
Okay, have looked into it more closely, there are two problems here:
 - olm-rs/olm-sys (not sure which one of those) statically links libolm, but we package libolm here so it should be dynamically linked. I'll investigate whether that's something we can patch easily, and I'll talk to upstream to make it easily patchable if that's not the case
 - the makefile in libolm sets CC to gcc explicitly. I've talked with upstream, they agree that's bad, so maybe that bit is fixed soon.

**Comment by ericonr** [comment]
You need libolm-devel (if that's the package name) in makedepends for it to even have something to link dynamically. Might need to pass some environment variable too to tell the crate to use the system's libolm.

**Comment by jcgruenhage** [comment]
> You need libolm-devel (if that's the package name) in makedepends for it to even have something to link dynamically.

yes, will do so once linking libolm dynamically is supported in olm-sys

> Might need to pass some environment variable too to tell the crate to use the system's libolm.

https://gitlab.gnome.org/BrainBlasted/olm-sys/-/blob/master/build.rs#L26 doesn't have an option for dynamic linking right now, will contribute that upstream.

**Comment by ericonr** [comment]
I see, good luck.

**Comment by jcgruenhage** [comment]
So, I've patched olm-sys, but I'm not quite sure how integrating that patch into here should be done. I can pull in the branch via a patch section to the Cargo.toml, and then put patches into the srcpkgs/rumatui folder for the Cargo.toml and Cargo.lock files. Would that be good enough? Patches for olm-sys directly in here won't work sadly, because the olm-sys sources are downloaded *after* the the patch phase.

**Comment by jcgruenhage** [comment]
I've got some build logs and ldd outputs here, it seems the env var works correctly:
```
╭─jcgruenhage@happy-raman.jcg.re ~/dev/rumatui  ‹master*› 
╰─➤  cargo build --release 
   Compiling olm-sys v0.1.5 (https://gitlab.gnome.org/jcgruenhage/olm-sys.git?branch=support-dynamic-linking#699d399e)
   Compiling olm-rs v0.5.0
   Compiling matrix-sdk-crypto v0.1.0 (https://github.com/DevinR528/matrix-rust-sdk?branch=rumatui#7a46cc21)
   Compiling matrix-sdk-base v0.1.0 (https://github.com/DevinR528/matrix-rust-sdk?branch=rumatui#7a46cc21)
   Compiling matrix-sdk v0.1.0 (https://github.com/DevinR528/matrix-rust-sdk?branch=rumatui#7a46cc21)
   Compiling rumatui v0.1.16 (/home/jcgruenhage/dev/rumatui)
    Finished release [optimized] target(s) in 1m 07s
╭─jcgruenhage@happy-raman.jcg.re ~/dev/rumatui  ‹master*› 
╰─➤  ldd target/release/rumatui
	linux-vdso.so.1 (0x00007ffd5fbad000)
	libssl.so.47 => /usr/lib/libssl.so.47 (0x00007fc888e6a000)
	libcrypto.so.45 => /usr/lib/libcrypto.so.45 (0x00007fc888c88000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fc888a12000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fc888a0d000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fc8889ec000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fc8889d2000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fc88880d000)
	/lib/ld-linux-x86-64.so.2 (0x00007fc889f01000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fc8886c8000)
╭─jcgruenhage@happy-raman.jcg.re ~/dev/rumatui  ‹master*› 
╰─➤  OLM_LINK_VARIANT=dylib cargo build --release
   Compiling olm-sys v0.1.5 (https://gitlab.gnome.org/jcgruenhage/olm-sys.git?branch=support-dynamic-linking#699d399e)
   Compiling olm-rs v0.5.0
   Compiling matrix-sdk-crypto v0.1.0 (https://github.com/DevinR528/matrix-rust-sdk?branch=rumatui#7a46cc21)
   Compiling matrix-sdk-base v0.1.0 (https://github.com/DevinR528/matrix-rust-sdk?branch=rumatui#7a46cc21)
   Compiling matrix-sdk v0.1.0 (https://github.com/DevinR528/matrix-rust-sdk?branch=rumatui#7a46cc21)
   Compiling rumatui v0.1.16 (/home/jcgruenhage/dev/rumatui)
    Finished release [optimized] target(s) in 1m 02s
╭─jcgruenhage@happy-raman.jcg.re ~/dev/rumatui  ‹master*› 
╰─➤  ldd target/release/rumatui                  
	linux-vdso.so.1 (0x00007ffe07f10000)
	libssl.so.47 => /usr/lib/libssl.so.47 (0x00007fdeb06a9000)
	libcrypto.so.45 => /usr/lib/libcrypto.so.45 (0x00007fdeb04c7000)
	libolm.so.3 => /usr/lib/libolm.so.3 (0x00007fdeb049a000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fdeb0495000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fdeb0474000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fdeb045a000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fdeb0295000)
	/lib/ld-linux-x86-64.so.2 (0x00007fdeb1722000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fdeb0150000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fdeafeda000)
```

**Comment by jcgruenhage** [comment]
So, the remaining question: How do I pass the environment variable to cargo from the template, without overriding do_build and do_install? Setting the variable in the template causes a linter warning, and also doesn't work.

**Comment by jcgruenhage** [comment]
Got an answer in #xbps, *should* work now

**Comment by jcgruenhage** [comment]
ftr: I know this package builds on aarch64 natively, so this is definitely *only* a cross compilation problem. Runs fine on my Pinebook Pro

**Comment by jcgruenhage** [comment]
The only remaining build failure is on i686, where rust hasn't been built yet, so it's timing out trying to build rust

**Pull request closed without merging**
