### PR TITLE
libGL: update to 18.1.5.

### PR DESCRIPTION
**Pull request by maxice8**
i plan on switching to meson as build_system

@q66 needs testing on aarch64

### CODE REVIEW

**Comment by pullmoll** [comment]
Is upstream going to drop autotools support? If not, in my experience meson packages were recently sometimes time consuming to update because of meson introduced pecularities. One package (I do not remember which) I could not fix and switched back to using autotools.

**Comment by Gottox** [comment]
@maxice8 what needs to be done to get the PR ready?

**Comment by maxice8** [comment]
On Tue, Aug 07, 2018 at 06:00:05AM -0700, Enno Boland wrote:
> @maxice8 what needs to be done to get the PR ready?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/1242#issuecomment-411047260

need confirmation from @q66 that the loss of libvdpau on mesa-tegra-dri doesn't cause a loss of functionality

**Comment by q66** [comment]
I confirmed with Mesa/Tegra people that there is no loss of functionality, just leave it out

**Comment by maxice8** [comment]
Ok thanks, I'm currently without Internet due to severe thunderstorms in my
city but soon I'm heading to university.

@Gottox I plan to merge this around 19:30 UTC -3

**Pull request closed without merging**
