### PR TITLE
wlroots: update to 0.14.0.

### PR DESCRIPTION
**Pull request by ifreund**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Wayfire 0.7.2 is out.

**Comment by ericonr** [comment]
Testing locally.

**Comment by ericonr** [comment]
Werking

**Comment by FollieHiyuki** [comment]
hikari 2.3.1 came out

**Comment by ifreund** [comment]
> hikari 2.3.1 came out

Thanks, looks like the diff between 2.3.0 and 2.3.1 matched the patch I had exactly anyways :D

**Pull request merged**
