### PR TITLE
colord: add run script

### PR DESCRIPTION
**Pull request by gch1p**

### CODE REVIEW

**Comment by ericonr** [comment]
For this to take effect, you need to increase the package's revision.

Could you add an explanation to the commit message as to why this is needed?

**Comment by gch1p** [comment]
@ericonr done.

**Comment by Duncaen** [comment]
This should create the directory using `make_dirs` as its not on a temporary filesystem.

**Comment by gch1p** [comment]
It seems it's not needed, the directory is already created using `make_dirs` in the template file, my bad. Removed it.

**Pull request closed without merging**
