### PR TITLE
mesa: update to 22.2.5

### PR DESCRIPTION
**Pull request by bubba-champion**
#### Testing the changes
- I tested the changes in this PR: **NO**

### CODE REVIEW

**Comment by bubba-champion** [comment]
Tested on my x86_64-glibc AMD system in steam games (native and proton), and with multimedia (mpv). Looks like it can be merged.

**Comment by zlice** [comment]
https://github.com/void-linux/void-packages/pull/41084 22.3.1 has been working good for me for the past week.

**Comment by paper42** [comment]
Why did you close this?

**Comment by bubba-champion** [comment]
Because [22.3.1](https://github.com/void-linux/void-packages/pull/41084) more relevant, and have some important bug fixes (for example [this](https://gitlab.freedesktop.org/mesa/mesa/-/commit/5233551e1912519b456515ac8da7a62c9779fca8) issue which caused gpu hanging for me and other users)

**Pull request closed without merging**
