### PR TITLE
New package: adw-gtk3-4.2

### PR DESCRIPTION
**Pull request by LMFuture-Me**
New package: adw-gtk3-4.2

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by classabbyamp** [comment]
> In particular, new themes are highly unlikely to be accepted.

[CONTRIBUTING.md](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements)

**Comment by LMFuture-Me** [comment]
> > In particular, new themes are highly unlikely to be accepted.
> 
> [CONTRIBUTING.md](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements)

But this can be the dependency of some software like Gradience

**Comment by paper42** [comment]
If you want to package Gradience even though it's háčky and unstable afaik, add it to this PR, otherwise I don't really see a reason for this.

**Comment by ahesford** [comment]
This definitely fails to meet the quality standards. Install this theme in your home directory if you really want it.

**Pull request closed without merging**
