### PR TITLE
common/scripts: import xbps-cycles.

### PR DESCRIPTION
**Pull request by ericonr**
From https://github.com/ahesford/xbps-cycles, license is compatible with
void-packages. Will be run in CI, so it should live in the same
repository.

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Probably won't work as is, should run inside a void container.

**Comment by Chocimier** [comment]
Top patch is for sending mail on cycles detected.

**Comment by Chocimier** [comment]
Changed to open informative issue rather than sending vague email.
Same cycle is reported only once, but if there are branches, it can open more than one issue.

https://github.com/Chocimier/void-packages-org/issues

**Comment by ericonr** [comment]
Ok, and it already implements a check to not open repeat issues ! ANything else we need?

**Comment by Chocimier** [comment]
I think it's ready. @ahesford ?

**Comment by ahesford** [comment]
Looks good to me

**Pull request merged**
