### PR TITLE
[wip] gcc: update to 10.2.0

### PR DESCRIPTION
**Pull request by Johnnynator**
[ci skip]

### CODE REVIEW

**Comment by ericonr** [comment]
Well, that was fast. I need to look into how Alpine does it, but q66 suggested adding the headers inside GCC

#24254

**Comment by q66** [comment]
let's not merge for now, since i had changes in mind wrt actually fixing the lib/lib64 stuff on all architectures (right now at very least x86_64 is wrong) so i'll post patches here later

**Comment by ericonr** [comment]
Regarding FORTIFY, patches @ 

- https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/main/gcc/gcc-4.9-musl-fortify.patch
- https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/main/gcc/053_all_libitm-no-fortify-source.patch
- https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/main/gcc/003_all_default-fortify-source.patch - they force it in the compiler instead of using explicit flags like we do, I don't think we need it

Required for time64 update:

- https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/main/gcc/futex-time64.patch

**Comment by ericonr** [comment]
Could we enable the D backend for GCC? Could help with cross compiling D stuff.

**Comment by fosslinux** [comment]
Have we investigated `-fno-comon`

**Comment by q66** [comment]
D frontend is a massive can of worms and I wouldn't bother for now

also, nobody uses D anyway

**Comment by Johnnynator** [comment]
I would prefer to set` -fno-common` on a per template basis. Sure there will be fallout, but I epxect that must packages will build fine.

**Comment by q66** [comment]
yup

**Comment by travankor** [comment]
Does cross for aarch64 support `-fstack-protector` now?

**Comment by fosslinux** [comment]
Yeah, assuming you mean `-fcommon`. Setting `-fcommon` and reporting upstream bugs seems to be the way to go.

**Comment by pullmoll** [comment]
Trying to bootstrap with this PR merged fails when building `gdbm`:
```
…
  CCLD     gdbmtool
/usr/bin/ld: ./libgdbmapp.a(parseopt.o):(.bss+0x8): multiple definition of `parseopt_program_args'; gdbmtool.o:(.data.rel.local+0x260): first defined here
/usr/bin/ld: ./libgdbmapp.a(parseopt.o):(.bss+0x10): multiple definition of `parseopt_program_doc'; gdbmtool.o:(.data.rel.local+0x268): first defined here
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:656: gdbmtool] Error 1
make[3]: Leaving directory '/builddir/gdbm-1.18.1/src'
make[2]: *** [Makefile:499: all] Error 2
make[2]: Leaving directory '/builddir/gdbm-1.18.1/src'
make[1]: *** [Makefile:464: all-recursive] Error 1
make[1]: Leaving directory '/builddir/gdbm-1.18.1'
make: *** [Makefile:396: all] Error 2
=> ERROR: gdbm-1.18.1_1: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 2
=> ERROR:   in do_build() at common/build-style/gnu-configure.sh:13
```

**Comment by pullmoll** [comment]
To be extended list of packages known to require `-fcommon`:
- [x] gdbm
- [x] chroot-distcc
- [x] cpio
- [x] mdocml
- [x] dhcp

**Comment by pullmoll** [comment]
Compiling `cross-i686-pc-linux-gnu` with gcc-10.0.2 fails with:
```
i686-pc-linux-gnu-gcc -nostdlib -nostartfiles -r -o /builddir/cross-i686-pc-linux-gnu-0.34/glibc-build/csu/gcrt1.o /builddir/cross-i686-pc-linux-gnu-0.34/glibc-build/csu/Scrt1.o /builddir/cross-i686-pc-linux-gnu-0.34/glibc-build/csu/gmon-start.os /builddir/cross-i686-pc-linux-gnu-0.34/glibc-build/csu/static-reloc.os
libc-tls.c: In function '__libc_setup_tls':
libc-tls.c:209:30: error: array subscript 1 is outside the bounds of an interior zero-length array 'struct dtv_slotinfo[0]' [-Werror=zero-length-bounds]
  209 |   static_slotinfo.si.slotinfo[1].map = main_map;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
In file included from ../sysdeps/x86/ldsodefs.h:64,
                 from ../sysdeps/gnu/ldsodefs.h:46,
                 from ../sysdeps/unix/sysv/linux/ldsodefs.h:25,
                 from libc-tls.c:21:
../sysdeps/generic/ldsodefs.h:406:7: note: while referencing 'slotinfo'
  406 |     } slotinfo[0];
      |       ^~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [../o-iterator.mk:9: /builddir/cross-i686-pc-linux-gnu-0.34/glibc-build/csu/libc-tls.o] Error 1
make[2]: Leaving directory '/builddir/cross-i686-pc-linux-gnu-0.34/glibc-2.30/csu'
make[1]: *** [Makefile:259: csu/subdir_lib] Error 2
make[1]: Leaving directory '/builddir/cross-i686-pc-linux-gnu-0.34/glibc-2.30'
make: *** [Makefile:9: all] Error 2
=> ERROR: cross-i686-pc-linux-gnu-0.34_1: do_build: 'make ${makejobs}' exited with 2
=> ERROR:   in _glibc_build() at srcpkgs/cross-i686-pc-linux-gnu/template:212
=> ERROR:   in do_build() at srcpkgs/cross-i686-pc-linux-gnu/template:298
```

**Comment by pullmoll** [comment]
[Intermediate repository](https://repo.voidlinux.de/gcc10/binpkgs)

**Comment by pullmoll** [comment]
Bad news: `openjdk8` built with gcc10 segfaults for both `{x86_64,i686}-musl` when trying to build `openjdk9-bootstrap`.

**Comment by Johnnynator** [comment]
Ok, I will look into openjdk. There should be newer releases that might have it fixed.

**Comment by pullmoll** [comment]
openjdk8 actually fails for all architectures it seems. It just did for x86_64. Yeah, an update may fix the underlying problem.

**Comment by Johnnynator** [comment]
@pullmoll The problem with `openjdk9` (and other bootstrap ones maybe), is that it doesn't correctly detect gcc with multi digit versions. https://hg.openjdk.java.net/jdk8u/jdk8u-dev/raw-rev/39a7914e14a0

**Comment by pullmoll** [comment]
Ok, we can probably backport that patch in case there is no update for 9 and 10 bootstrap.

**Comment by pullmoll** [comment]
Better news: `opendjk8-8u272-b02` built w/o problems and I could build `apache-ant` with it and then `gvfs` and its dependencies. I'll add the update to the long list in #24334 now.

**Comment by pullmoll** [comment]
So next one is building openjdk11 with openjdk10-bootstrap. Guess what? It segfaults...

**Comment by q66** [comment]
worst case, if this becomes too much of a pain in the ass to figure out, we could build the bootstrap toolchains with the gcc6 we have in the tree for gcj

**Comment by fosslinux** [comment]
Can't openjdk10-bootstrap have the same patch applied?

**Comment by pullmoll** [comment]
@fosslinux there is no patch - except for the gcc version checking but that is unrelated AFAICT.
It was the update for openjdk8 to 8u272-b02 which fixed the crashes and openjdk9 was good enough to build 10, but now 10 fails to build 11.

**Comment by fosslinux** [comment]
Interesting that 9 could build 10 but 10 cant build 11. https://hg.openjdk.java.net/jdk8u/jdk8u-dev/raw-rev/39a7914e14a0 Can this be forward-ported? Or is it a different issue.

**Comment by pullmoll** [comment]
Actually it's 11 which crashes. That is the generated `/builddir/jdk11u-jdk-11.0.5+10/build/linux-x86_64-normal-server-release/jdk/bin/java` and this may be fixed in a later update. Looking for one...

**Comment by pullmoll** [comment]
Just finished building openjdk11-11.0.9+4_1 so we're set on that end. :clapper: :fireworks:

**Comment by pullmoll** [comment]
Trying to build openjdk9-bootstrap for i686-musl fails. Has anyone ever seen such an error message?
```
Error: failed /builddir/jdk9u-jdk-9.0.4+12/build/linux-x86-normal-server-release/jdk/lib/server/libjvm.so, because Error relocating /builddir/jdk9u-jdk-9.0.4+12/build/linux-x86-normal-server-release/jdk/lib/server/libjvm.so: strtok: initial-exec TLS resolves to dynamic definition in /builddir/jdk9u-jdk-9.0.4+12/build/linux-x86-normal-server-release/jdk/lib/server/libjvm.so
```
I am clueless here...   `strtok: initial-exec TLS resolves to dynamic definition in .../*.so` .. uh?

**Comment by ericonr** [comment]
@pullmoll https://github.com/void-linux/void-packages/blob/master/srcpkgs/mesa/patches/add-use-elf-tls.patch it could have to do with this, right?

**Comment by ericonr** [comment]
@pullmoll I'm thinking more about the define we had to include in Mesa to work properly. Something in the setup isn't supported properly by musl, and might require a similar define for `openjdk`?

**Comment by pullmoll** [comment]
Testing the outcome of systems built with gcc10.2.0 is now possible.
I have a bunch of ISOs with live systems at https://repo.voidlinux.de/live/ for you to download.
If you have time, perhaps test your favourite DE and see if everything works as it should.

Currently firefox-esr fails to build for i686 because of assembler statements in `/builddir/firefox-68.11.0/third_party/dav1d/src/x86/cdef_sse.asm`:
```
4:59.27 /builddir/firefox-68.11.0/third_party/dav1d/src/x86/cdef_sse.asm:1346: error: `%ifndef' expects macro identifiers
 4:59.27 /builddir/firefox-68.11.0/third_party/dav1d/src/x86/cdef_sse.asm:266: ... from macro `CDEF_FILTER' defined here
 4:59.27 /builddir/firefox-68.11.0/third_party/dav1d/src/x86/cdef_sse.asm:263: ... from macro `LEA' defined here
 4:59.27 /builddir/firefox-68.11.0/third_party/dav1d/src/x86/cdef_sse.asm:1172: ... from macro `call' defined here
 4:59.27 /builddir/firefox-68.11.0/third_party/dav1d/src/x86/cdef_sse.asm:1179: ... from macro `call_internal' defined here
 4:59.31 /builddir/firefox-68.11.0/third_party/dav1d/src/x86/cdef_sse.asm:1347: error: `%ifndef' expects macro identifiers
 4:59.31 /builddir/firefox-68.11.0/third_party/dav1d/src/x86/cdef_sse.asm:266: ... from macro `CDEF_FILTER' defined here
 4:59.31 /builddir/firefox-68.11.0/third_party/dav1d/src/x86/cdef_sse.asm:263: ... from macro `LEA' defined here
 4:59.31 /builddir/firefox-68.11.0/third_party/dav1d/src/x86/cdef_sse.asm:1172: ... from macro `call' defined here
 4:59.31 /builddir/firefox-68.11.0/third_party/dav1d/src/x86/cdef_sse.asm:1179: ... from macro `call_internal' defined here
 4:59.35 /builddir/firefox-68.11.0/third_party/dav1d/src/x86/cdef_sse.asm:1348: error: `%ifndef' expects macro identifiers
```
This is why there are no i686 images except base and lxqt: the others need firefox-esr.

**Comment by Johnnynator** [comment]
The firefox-esr problem was most likely just the nasm problem firefox did also run into. It does compile fine for me now.

**Comment by pullmoll** [comment]
Yep, that was nasm causing it. I didn't realize this before... I'm a bit out of order due to real life issue at the moment.

**Comment by pullmoll** [comment]
Another detail we probably need to address:
Some packages, e.g. `bananapi-uboot`, include a gcc header file through a macro call
```
#include gcc_header(__GNUC__)
```
Here `__GNUC__` is `10` and there is no file `linux/compiler-gcc10.h`, so I don't know what to do or how to solve this.
Perhaps some other part of the configuration detects whether or not a specific `gcc` version needs a specific header, or just the default `linux/compiler.h`. The latter seems to be used for `gcc-9.3.0` so it may be there is some compiler version detection which needs to be fixed.

**Comment by ericonr** [comment]
Does that file exist anywhere with version 9? I only see:

```
~ ➜ xlocate compiler-gcc
linux4.14-headers-4.14.192_1    /usr/src/kernel-headers-4.14.192_1/include/linux/compiler-gcc.h
linux4.19-headers-4.19.144_1    /usr/src/kernel-headers-4.19.144_1/include/linux/compiler-gcc.h
linux4.4-headers-4.4.228_1      /usr/src/kernel-headers-4.4.228_1/include/linux/compiler-gcc.h
linux4.9-headers-4.9.232_1      /usr/src/kernel-headers-4.9.232_1/include/linux/compiler-gcc.h
linux5.4-headers-5.4.64_1       /usr/src/kernel-headers-5.4.64_1/include/linux/compiler-gcc.h
linux5.5-headers-5.5.18_1       /usr/src/kernel-headers-5.5.18_1/include/linux/compiler-gcc.h
linux5.6-headers-5.6.19_1       /usr/src/kernel-headers-5.6.19_1/include/linux/compiler-gcc.h
linux5.7-headers-5.7.19_1       /usr/src/kernel-headers-5.7.19_1/include/linux/compiler-gcc.h
linux5.8-headers-5.8.8_1        /usr/src/kernel-headers-5.8.8_1/include/linux/compiler-gcc.h
```

**Comment by pullmoll** [comment]
No, there is no `include/linux/compiler-gcc9.h` either, because (that's what I think) the version 9 does not need specific handling compared to previous compilers (5,6,7,8 I think). For gcc10 this is probably also not required, yet there is some test hidden somewhere which decides whether or not to expect a specific, versioned header, or whether to use the generic `compiler-gcc.h`.

**Comment by ericonr** [comment]
It's a long shot, but did you try upgrading it to version 15.04? It probably won't solve anything, since they are both from 2015.

**Comment by pullmoll** [comment]
I don't think trying to update will change anything. The magic is hidden in the macro `gcc_header` which I had not yet time to locate and to inspect or try to make work for `gcc10`.

**Comment by fosslinux** [comment]
Status update?

**Comment by unihernandez22** [comment]
How much do you think is missing for the update?

**Comment by q66** [comment]
I'll probably get around to fixing the lib64 stuff around this weekend, been super busy with other things

**Comment by ericonr** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95189 probably relevant.

**Comment by q66** [comment]
we're affected by this already

**Comment by q66** [comment]
added my lib64 handling stuff in a7af0e5cf06e9ee705c5782e227c71d14b08edd6, i have nothing more to add, so from my side we're good

**Comment by Johnnynator** [comment]
Welp, I broke this branch while rebasing. Will need to look into it next week.

**Comment by ericonr** [comment]
@Johnnynator you can pull the musl changes from #26067 into this one, if you want to skip some toolchain rebuilds.

**Comment by fosslinux** [comment]
Can we push this yet?

**Comment by q66** [comment]
no, waiting on linux 5.10

**Comment by kachsheev** [comment]
Congratulate with Linux 5.10 out! :)

**Comment by ericonr** [comment]
working on it #27145 

feel free to help out, the rsync requirement is terrible :/

**Comment by Johnnynator** [comment]
Rebased everything ontop of the void-cross build-style.

**Comment by q66** [comment]
the enabling of glibc crosstoolchains on musl won't work just like that, don't mess with it for now

**Comment by Johnnynator** [comment]
> the enabling of glibc crosstoolchains on musl won't work just like that, don't mess with it for now

I didn't look into it besides testing a zsh cross build. (x86_64-musl -> aarch64). What problems didn't I hit yet?

**Comment by pullmoll** [comment]
You could replace
```
sed -i -e "s;http://www.musl-libc.org/;https://musl.libc.org/;" srcpkgs/cross*/template
```

**Comment by Johnnynator** [comment]
Everything seems to compile fine but `cross-powerpc64le-linux-gnu` @q66 

```
In file included from <command-line>:
../sysdeps/ieee754/ldbl-opt/nldbl-sscanf.c:22:23: error: '_IO_sscanf' aliased to undefined symbol 'sscanf'
   22 | strong_alias (sscanf, _IO_sscanf)
      |                       ^~~~~~~~~~
./../include/libc-symbols.h:140:26: note: in definition of macro '_strong_alias'
  140 |   extern __typeof (name) aliasname __attribute__ ((alias (#name))) \
      |                          ^~~~~~~~~
../sysdeps/ieee754/ldbl-opt/nldbl-sscanf.c:22:1: note: in expansion of macro 'strong_alias'
   22 | strong_alias (sscanf, _IO_sscanf)
      | ^~~~~~~~~~~~
```
There is a bug report for this: https://sourceware.org/bugzilla/show_bug.cgi?id=26360

I can workaround this like that, but dunno if this is what we want.
```diff
diff --git a/srcpkgs/cross-powerpc64le-linux-gnu/template b/srcpkgs/cross-powerpc64le-linux-gnu/template
index 90e8c7b365..3f8fc76c6a 100644
--- a/srcpkgs/cross-powerpc64le-linux-gnu/template
+++ b/srcpkgs/cross-powerpc64le-linux-gnu/template
@@ -30,6 +30,7 @@ nocross=yes
 
 cross_triplet=${_triplet}
 cross_linux_arch=powerpc
+cross_gcc_bootstrap_configure_args="--with-long-double-128"
 cross_binutils_configure_args="--enable-secureplt"
 # explicitly enable for final gcc, gfortran does not build without on ppc64le
 cross_gcc_configure_args="--enable-libquadmath"
```

<details>
<summary>Cross chains built:</summary>

```
cross-aarch64-linux-gnu-0.34_1.i686.xbps
cross-aarch64-linux-gnu-0.34_1.x86_64-musl.xbps
cross-aarch64-linux-gnu-0.34_1.x86_64.xbps
cross-aarch64-linux-musl-0.34_1.i686.xbps
cross-aarch64-linux-musl-0.34_1.x86_64-musl.xbps
cross-aarch64-linux-musl-0.34_1.x86_64.xbps
cross-arm-linux-gnueabi-0.34_1.i686.xbps
cross-arm-linux-gnueabi-0.34_1.x86_64-musl.xbps
cross-arm-linux-gnueabi-0.34_1.x86_64.xbps
cross-arm-linux-gnueabihf-0.34_1.i686.xbps
cross-arm-linux-gnueabihf-0.34_1.x86_64-musl.xbps
cross-arm-linux-gnueabihf-0.34_1.x86_64.xbps
cross-arm-linux-musleabi-0.34_1.i686.xbps
cross-arm-linux-musleabi-0.34_1.x86_64-musl.xbps
cross-arm-linux-musleabi-0.34_1.x86_64.xbps
cross-arm-linux-musleabihf-0.34_1.i686.xbps
cross-arm-linux-musleabihf-0.34_1.x86_64-musl.xbps
cross-arm-linux-musleabihf-0.34_1.x86_64.xbps
cross-armv7l-linux-gnueabihf-0.34_1.i686.xbps
cross-armv7l-linux-gnueabihf-0.34_1.x86_64-musl.xbps
cross-armv7l-linux-gnueabihf-0.34_1.x86_64.xbps
cross-armv7l-linux-musleabihf-0.34_1.i686.xbps
cross-armv7l-linux-musleabihf-0.34_1.x86_64-musl.xbps
cross-armv7l-linux-musleabihf-0.34_1.x86_64.xbps
cross-i686-linux-musl-0.34_1.i686.xbps
cross-i686-linux-musl-0.34_1.x86_64-musl.xbps
cross-i686-linux-musl-0.34_1.x86_64.xbps
cross-i686-pc-linux-gnu-0.34_1.x86_64-musl.xbps
cross-i686-pc-linux-gnu-0.34_1.x86_64.xbps
cross-mips-linux-musl-0.34_1.i686.xbps
cross-mips-linux-musl-0.34_1.x86_64-musl.xbps
cross-mips-linux-musl-0.34_1.x86_64.xbps
cross-mips-linux-muslhf-0.34_1.i686.xbps
cross-mips-linux-muslhf-0.34_1.x86_64-musl.xbps
cross-mips-linux-muslhf-0.34_1.x86_64.xbps
cross-mipsel-linux-musl-0.34_1.i686.xbps
cross-mipsel-linux-musl-0.34_1.x86_64-musl.xbps
cross-mipsel-linux-musl-0.34_1.x86_64.xbps
cross-mipsel-linux-muslhf-0.34_1.i686.xbps
cross-mipsel-linux-muslhf-0.34_1.x86_64-musl.xbps
cross-mipsel-linux-muslhf-0.34_1.x86_64.xbps
cross-powerpc-linux-gnu-0.34_1.i686.xbps
cross-powerpc-linux-gnu-0.34_1.x86_64-musl.xbps
cross-powerpc-linux-gnu-0.34_1.x86_64.xbps
cross-powerpc-linux-musl-0.34_1.i686.xbps
cross-powerpc-linux-musl-0.34_1.x86_64-musl.xbps
cross-powerpc-linux-musl-0.34_1.x86_64.xbps
cross-powerpc64-linux-gnu-0.34_1.i686.xbps
cross-powerpc64-linux-gnu-0.34_1.x86_64-musl.xbps
cross-powerpc64-linux-gnu-0.34_1.x86_64.xbps
cross-powerpc64-linux-musl-0.34_1.i686.xbps
cross-powerpc64-linux-musl-0.34_1.x86_64-musl.xbps
cross-powerpc64-linux-musl-0.34_1.x86_64.xbps
cross-powerpc64le-linux-musl-0.34_1.i686.xbps
cross-powerpc64le-linux-musl-0.34_1.x86_64-musl.xbps
cross-powerpc64le-linux-musl-0.34_1.x86_64.xbps
cross-powerpcle-linux-gnu-0.34_1.i686.xbps
cross-powerpcle-linux-gnu-0.34_1.x86_64-musl.xbps
cross-powerpcle-linux-gnu-0.34_1.x86_64.xbps
cross-powerpcle-linux-musl-0.34_1.i686.xbps
cross-powerpcle-linux-musl-0.34_1.x86_64-musl.xbps
cross-powerpcle-linux-musl-0.34_1.x86_64.xbps
cross-x86_64-linux-gnu-0.34_1.i686.xbps
cross-x86_64-linux-gnu-0.34_1.x86_64-musl.xbps
cross-x86_64-linux-musl-0.34_1.i686.xbps
cross-x86_64-linux-musl-0.34_1.x86_64.xbps
```

</details>

<details>
<summary>Native ones:</summary>

```
hostdir/binpkgs/gcc10/gcc-10.2.0_1.aarch64-musl.xbps
hostdir/binpkgs/gcc10/gcc-10.2.0_1.aarch64.xbps
hostdir/binpkgs/gcc10/gcc-10.2.0_1.armv6l-musl.xbps
hostdir/binpkgs/gcc10/gcc-10.2.0_1.armv6l.xbps
hostdir/binpkgs/gcc10/gcc-10.2.0_1.armv7l-musl.xbps
hostdir/binpkgs/gcc10/gcc-10.2.0_1.armv7l.xbps
hostdir/binpkgs/gcc10/gcc-10.2.0_1.i686.xbps
hostdir/binpkgs/gcc10/gcc-10.2.0_1.x86_64-musl.xbps
hostdir/binpkgs/gcc10/gcc-10.2.0_1.x86_64.xbps
```

</details>

**Comment by q66** [comment]
yeah, that is what we want

**Comment by Johnnynator** [comment]
> yeah, that is what we want

Okay, thx for confirming and done.
All toolchains seem to be fine now.

**Comment by q66** [comment]
the powerpc64 and powerpc gnu toolchains did not get updated

**Comment by Johnnynator** [comment]
> the powerpc64 and powerpc gnu toolchains did not get updated

I did.

**Comment by leahneukirchen** [comment]
Patch needed for the new 5.10 kernel libc headers: https://l2.re/GB_Jjg

```diff
diff --git a/common/build-style/void-cross.sh b/common/build-style/void-cross.sh
index 0e5c233635..8b2b992b74 100644
--- a/common/build-style/void-cross.sh
+++ b/common/build-style/void-cross.sh
@@ -159,10 +159,11 @@ _void_cross_build_kernel_headers() {
 
 	cd linux-${ver}
 
-	make ARCH=$cross_linux_arch headers_check
-	make ARCH=$cross_linux_arch \
-		INSTALL_HDR_PATH=${wrksrc}/build_root/usr/${cross_triplet}/usr \
-		headers_install
+	make ARCH=${cross_linux_arch} headers
+	find usr/include -name '.*' -delete
+	rm usr/include/Makefile
+	rm -r usr/include/drm
+	cp -a usr/include ${wrksrc}/build_root/usr/${cross_triplet}/usr
 
 	touch ${wrksrc}/.linux_headers_done
 }
@@ -518,11 +519,7 @@ do_install() {
 
 	# Install Linux headers
 	cd ${wrksrc}/linux-$(cat ${wrksrc}/.linux_version)
-	make ARCH=${cross_linux_arch} \
-		INSTALL_HDR_PATH=${DESTDIR}/${sysroot}/usr headers_install
-	rm -f $(find ${DESTDIR}/${sysroot}/usr/include \
-		-name .install -or -name ..install.cmd)
-	rm -rf ${DESTDIR}/${sysroot}/usr/include/drm
+	cp -a usr/include ${DESTDIR}/${sysroot}/usr
 
 	# Install binutils
 	cd ${wrksrc}/binutils_build
```

**Comment by leahneukirchen** [comment]
Note from #24258: OpenSSH will need a rebuild to allow new 64-bit time syscalls in the sandbox.

**Comment by q66** [comment]
while at this it would be worthwhile to update binutils; i'm working on that right now, will raise it as separate PR and then we can pull it into crosstoolchains as well once merged

**Comment by q66** [comment]
ok, now that is merged, please update the cross templates to use 2.35.1 and also remove the comments on the patching bit for binutils in the cross build-style (i commented it out because the patches do not work in 2.34, but with the update that will change)

**Comment by pullmoll** [comment]
Here building `cross-aarch64-linux-musl` with `binutils-2.35.1` fails with:
```
libtool: compile:  /builddir/cross-aarch64-linux-musl-0.34/gcc_build/./gcc/gccgo -B/builddir/cross-aarch64-linux-musl-0.34/gcc_build/./gcc/ -B/usr/aarch64-linux-musl/bin/ -B/usr/aarch64-linux-musl/lib/ -isystem /usr/aarch64-linux-musl/include -isystem /usr/aarch64-linux-musl/sys-include --sysroot=/builddir/cross-aarch64-linux-musl-0.34/build_root/usr/aarch64-linux-musl -O2 -g -I . -c -fgo-pkgpath=cmd/go/internal/modfetch ../../../gcc-10.2.0/libgo/go/cmd/go/internal/modfetch/cache.go ../../../gcc-10.2.0/libgo/go/cmd/go/internal/modfetch/coderepo.go ../../../gcc-10.2.0/libgo/go/cmd/go/internal/modfetch/fetch.go ../../../gcc-10.2.0/libgo/go/cmd/go/internal/modfetch/insecure.go ../../../gcc-10.2.0/libgo/go/cmd/go/internal/modfetch/key.go ../../../gcc-10.2.0/libgo/go/cmd/go/internal/modfetch/proxy.go ../../../gcc-10.2.0/libgo/go/cmd/go/internal/modfetch/pseudo.go ../../../gcc-10.2.0/libgo/go/cmd/go/internal/modfetch/repo.go ../../../gcc-10.2.0/libgo/go/cmd/go/internal/modfetch/sumdb.go -o cmd/go/internal/modfetch.o
/builddir/cross-aarch64-linux-musl-0.34/build_root/usr/aarch64-linux-musl/lib/../lib64/libucontext.a(startcontext.o): in function `__start_context':
(.text+0x4): relocation truncated to fit: R_AARCH64_CONDBR19 against symbol `__setcontext' defined in .text section in /builddir/cross-aarch64-linux-musl-0.34/build_root/usr/aarch64-linux-musl/lib/../lib64/libucontext.a(setcontext.o)
collect2: error: ld returned 1 exit status
```
The other cross compilers built ok for x86_64.

**Comment by q66** [comment]
looks like a libucontext problem, I'd look there

**Comment by q66** [comment]
try using `libucontext` 0.13.1 in the crosscompiler, it might actually be fixed

**Comment by fosslinux** [comment]
Wild guess, what about adding `-fPIC` to the compile flags? The error `relocation truncated to fit` apparently means that it is trying to access an address too far away, `-fPIC` should allow this..

**Comment by q66** [comment]
no, libucontext is already built with PIC

**Comment by q66** [comment]
the issue appears fixed in latest libucontext `master`, but there is a fix for the build system needed, so i'll deal with that with upstream first

**Comment by q66** [comment]
i have some other fixes lined up for `libucontext`, so i'll try to get upstream to tag a release, then push an update in Void and we can integrate it into this PR, which should also fix the problem

**Comment by leahneukirchen** [comment]
libucontext 1.0 was tagged 3h ago.

**Comment by pullmoll** [comment]
`common/build-styles/void-cross.sh` needs to be fixed for `libucontext-1.0`. It seems the CPPFLAGS are ignored now and the build fails to find `#include <string.h>`.

**Comment by q66** [comment]
not quite, but you can still re-test rebuilding the crosstoolchains with that, if it works then we're good

**Comment by q66** [comment]
i will take over the update from now, it'll be easier than having @Johnnynator apply changes gradually

**Comment by pullmoll** [comment]
Commented in a wrong closed PR. We should keep `libiberty`AFAICT so remove `--disable-target-libiberty` in the gcc template. Packages depend on it: `prelink-cross`, `oprofile` found so far.

**Comment by q66** [comment]
no, it's an internal library, if something depends on it it should be packaged separately (like debian deos)

**Comment by pullmoll** [comment]
A separate `libiberty-devel` makes sense. It should also vmove `/usr/lib/gcc/<arch>/<version-makor.minor>/plugin/include/libiberty.h`.

**Comment by q66** [comment]
it's not a part of the compiler, so it should not be a package in the compiler, it's completely an internal library

if you want it, do it separately, like https://packages.debian.org/bullseye/libiberty-dev

**Comment by pullmoll** [comment]
In that case the `libiberty.h` should be removed from `gcc`. It may be just because of this header that packages are trying to link against `libiberty`.  I haven't verified that yet and am just reporting issues with the gcc 10 upate I find.

**Comment by q66** [comment]
other distributions don't remove it

**Comment by q66** [comment]
FWIW that file is also present in gcc9, and attempting to include it by default does not work - the path it is in is just headers for gcc plugin development, and normally they should not be visible by default

**Comment by q66** [comment]
oprofile build is not a regression though - i just checked this and it behaves the same with gcc9

**Comment by q66** [comment]
we should probably split out a separate `gcc-plugin-devel` package though (which will most likely take care of the problem, but kinda by accident)

**Comment by pullmoll** [comment]
I tried to disable detection of `libiberty.h` in `oprofile` template but that doesn't fix it.
You may want to cherry pick from these:
https://github.com/pullmoll/void-packages/commit/5c8b9616722998085319d491a4fc49d8f5ac2048 
https://github.com/pullmoll/void-packages/commit/2e54f25d7a0b01f1a2e4ffe5a6899ddcc02168b4
https://github.com/pullmoll/void-packages/commit/46efc7ea14081b3a97d87a6aa03f1b9b2cd78ac2

I'll add packages should there be any more.

**Comment by q66** [comment]
i see the problem, it's not gcc at all

```
$ xbps-query -o /usr/include/libiberty.h 
binutils-devel-2.35.1_2: /usr/include/libiberty.h (regular file)
```

**Comment by q66** [comment]
ah, no; we should instead modify `binutils` template to install `libiberty` as that was the pre-2.35 behavior

**Comment by pullmoll** [comment]
That's of course easier than creating a separate package and modifying templates.
I didn't see **that** `libiberty.h` in my cursory look over xlocate's output.

**Comment by q66** [comment]
ok, i have a fix locally available, testing it now

**Comment by q66** [comment]
works, pushed

**Comment by pullmoll** [comment]
yup, `oprofile` and `prelink-cross` are ok now

**Comment by q66** [comment]
I am currently preparing the update in my tree; here is the order in which I will do it https://gist.github.com/q66/051034fac319410172d6b94782610676

I have also switched to Alpine's 10.2.1-git source tarball instead of using the 10.2.0 release; looks like there was a lot of fixes since 10.2.0 and I don't think it's worth it to patch them in individually, we can switch back to upstream tarball after 10.3 is out (or for 11)

**Comment by pullmoll** [comment]
@q66 add `ghdl` to step 3 because it links against `libada`.

**Comment by q66** [comment]
sure, i have that

for now i'm building all the crosstoolchains for everything to make sure they really work

**Comment by ericonr** [comment]
Broken software:

- firefox
- openssh
- possibly firefox-esr and thunderbird (I can't tell why our testing didn't hit issues)

Broken software which we can patch before merging toolchains:

- chromium (already done)
- qt5-webengine
- electron10
- I assume other electrons

**Comment by q66** [comment]
https://github.com/void-linux/void-packages/issues/28034

**Pull request closed without merging**
