### PR TITLE
qalculate: update to 3.17.0

### PR DESCRIPTION
**Pull request by FollieHiyuki**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Argh, they seem to have broken all cross builds. Take a look at their commit log around the build system to see if you can find what it was.

**Comment by FollieHiyuki** [comment]
I think it is around commit https://github.com/Qalculate/libqalculate/commit/8c4526941aed1e39187dba25eb1a74e8f91b56e0 that breaks the cross builds

**Comment by ericonr** [comment]
Indeed, specifically with the addition of the `fixpo` program.

We have a workaround for a similar issue in the `goaccess` package, if you want to look. A possibly upstreamable solution is https://github.com/allinurl/goaccess/pull/2038 ,  but it's not necessary for a simple patch to get it to build..

**Comment by FollieHiyuki** [comment]
I don't know much about compilers, but will take a look at what I can do.

**Comment by FollieHiyuki** [comment]
I've tried to do the same thing in `goaccess` for this package with no luck. Maybe I have done it wrong.
The build chain still fails when reaching those *.po files

**Comment by ericonr** [comment]
See cd6a6013afc3d578436ec9b987634b33712b640f for fix :)

**Comment by FollieHiyuki** [comment]
Thanks. I know what I did wrong now :)

**Pull request closed without merging**
