### PR TITLE
yggdrasil: add service changes from upstream systemd unit

### PR DESCRIPTION
**Pull request by Skirmisher**
yggdrasil will fail to start if the `tun` kernel module is not loaded. Upstream modified their [service file](https://github.com/yggdrasil-network/yggdrasil-go/blob/4b16c325a3d90d97df208457bc35d499249f8146/contrib/systemd/yggdrasil.service) to first attempt to load the module before starting the service. They also opted to drop capabilities to CAP_NET_ADMIN and CAP_NET_RAW, which I saw fit to include.

### CODE REVIEW

**Comment by xtraeme** [comment]
- missing revbump
- missing `libcap-progs` dependency

**Comment by Skirmisher** [comment]
`setpriv` is provided by util-linux, and so should be installed by base-system. Do I need to express that dependency, and if so, how?

**Comment by xtraeme** [comment]
oh right, in this case it's as is. Thanks

**Comment by Vaelatern** [comment]
1f2bdcc821

**Pull request closed without merging**
