### PR TITLE
New package: wxFormBuilder-3.9.0

### PR DESCRIPTION
**Pull request by x12a1f**
wxFormBuilder uses git submodules to pull in ticpp from another repo. ticpp has no official release so I included it as a patch instead.

### CODE REVIEW

**Comment by Noah-Huppert** [comment]
Builds fine on my x86_64

**Comment by ericonr** [comment]
> ticpp has no official release so I included it as a patch instead.

Please don't vendor the repository in. You can have git submodules, just download the specific commit that was listed in the repo for the tagged version. Templates like `wayfire` do it.

**Comment by Noah-Huppert** [comment]
Adding ticpp as another distfile now...

**Comment by Noah-Huppert** [comment]
@x12a1f please apply this patch to download ticpp as a distfile instead of storing it in this repository: [`wxformbuilder-unvendor-ticpp.patch`](https://gist.github.com/Noah-Huppert/fc7e3ad09a6f8f15558a57a77a977722/raw/8ff78acde3a511ba0ac8c680f9a3916f2b6b53b5/wxformbuilder-unvendor-ticpp.patch)

**Comment by x12a1f** [comment]
@Noah-Huppert Sorry, I stopped using void due to the lack of response in general, if you wish you can takeover this PR

**Comment by Noah-Huppert** [comment]
@x12a1f no worries. Since I don't use wxFormBuilder we'll just let this one sit here. If someone wants to add and maintain the package in the future hopefully they find this work useful.

**Pull request closed without merging**
