### PR TITLE
New package: xcolor-0.5.1

### PR DESCRIPTION
**Pull request by Barbaross93**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by biopsin** [comment]
closes #33862

**Comment by Barbarossa93** [comment]
I _think_ it's all set now.  I borked the commit message a little bit, but it shouldn't be a big deal.

**Comment by Barbarossa93** [comment]
This PR is definitely ready now.

**Comment by wael444** [comment]
thank you @Barbarossa93.

**Comment by classabbyamp** [comment]
merged in 64352aa93be5737728a1ed3e25359b64c42e9193

**Pull request closed without merging**
