### PR TITLE
SPIRV-Headers: update to 1.3.236.0.

### PR DESCRIPTION
**Pull request by dataCobra**
#### Testing the changes
- I tested the changes in this PR: **NO**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by ahesford** [comment]
Typo in commit message: `SPRIV` instead of `SPIRV`.

**Comment by dataCobra** [comment]
Fixed. :+1:

**Comment by zlice** [comment]
looks like this is a dupe of https://github.com/void-linux/void-packages/pull/41072/files

**Comment by dataCobra** [comment]
Thanks for letting me know. I delete this PR. :+1:

**Pull request closed without merging**
