### PR TITLE
ell 0.38 bluez 5.56

### PR DESCRIPTION
**Pull request by ericonr**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Welp, they broke ABI

**Comment by ericonr** [comment]
Should wait on IWD 1.12. I'm considering moving it to use built-in ELL to avoid ABI/API mismatches (IWD 1.11 won't even build with this one).

@sgn what do you think about doing the same for bluez?

**Comment by sgn** [comment]
I'm expecting new release of bluez soon. In my experience, ell don't break that often.

**Comment by ericonr** [comment]
From what I understand, most of the time the releases come out near each other, ell, bluez and IWD. But since they are so tied to a specific IWD version, I'm not sure we gain much by using the dynamic library... It's tiny and helps avoid weird compatibility issues.

**Comment by sgn** [comment]
Seems like Debian (which wants to dynamic link the most) also uses bundled version. I think it should be fine.

**Comment by sgn** [comment]
BlueZ: hold for a bit https://marc.info/?l=linux-bluetooth&m=161437459815658&w=2

**Review by ahesford — APPROVED** [review]
`iwd` seems to work fine as a WPA supplicant and link manager. IPv6 still fails to work as expected. In my network, which offers Router Advertisements for IPv6 configuration, `iwd` crashes when it is configured to enable IPv6. Earlier versions supported only DHCPv6 for IPv6, but I don't rememember if that caused `iwd` to crash or just fail to give me a v6 address before. I can't comment on DHCPv6 functionality.

For now, `iwd` still fails to deliver key IPv6 support, which leaves me turning off network configuration and using `dhcpcd`. This is nothing new and, unless previously working DHCPv6 support is broken, probably shouldn't block this update.

I continue to wait for the day when `iwd` handles IPv6 properly and I can drop my `dhcpcd` dependnecy.

**Comment by sgn** [comment]
I would say switch BlueZ to vendor ell for now (if bluez failed to build from source with new ell) and push ell and iwd out first.

**Comment by ericonr** [comment]
> BlueZ 5.55 built fine with new ell?

I didn't check. But now that IWD is using bundled ell, I can hold the ell update without issue.

**Comment by ericonr** [comment]
This PR is now exclusively about ell and bluez.

**Comment by paper42** [comment]
bluez 5.57 and 5.58 are out. They fix an issue in 5.56 where bluetooth headphones could connect with HSP instead of SBC/AptX etc. which meant really bad sound quality.

**Comment by paper42** [comment]
* 5.58 requires ell 0.39
* using `-n` flag in the service means that bluetoothd logs to stdout, could you add logging to the service? What's the policy about logging in services in Void? When should they be included in the package?
* could you add --enable-experimental flag to bluez as a build option? (disabled by default) This option should enable monitoring battery level with a dbus interface.

**Comment by ericonr** [comment]
@paper42 I have pushed an updated version of the PR, could you please test it out?

**Comment by paper42** [comment]
Thanks, I will try using this for a few days and report back soon.

**Comment by paper42** [comment]
I was able to test this only for a few hours before my hardware broke, but it worked fine.

**Pull request closed without merging**
