### PR TITLE
freeorion: update to 0.4.10

### PR DESCRIPTION
**Pull request by SolitudeSF**

### CODE REVIEW

**Comment by SolitudeSF** [comment]
ci times out, what is the procedure for updating things like that?

**Comment by ericonr** [comment]
You can put `[ci skip]` in the commit messag to skip CI, so at least it won't get the red checkmark. Please solve the file conflict as well.

Ping me when you're done, I can try to run it.

**Comment by SolitudeSF** [comment]
@ericonr done

**Comment by ericonr** [comment]
I'm gonna be testing it out now, but as a general tip, leave a not about the platforms where you tested / built the package. And always attempt to run at least some cross builds. It really helps!

**Comment by ericonr** [comment]
I merged it with a small change to the commit message. The `[ci skip]` bit should go in the commit body, not in the title :)

**Pull request closed without merging**
