### PR TITLE
starship: update to 1.7.1.

### PR DESCRIPTION
**Pull request by JuniorSuperTux**
starship: update to 1.7.1

#### Testing the changes
- I tested the changes in this PR: **NO**

### CODE REVIEW

**Review by 0x5c — COMMENTED** [review]
That version of starship does not support the rust version we have (requiring `1.59` while we have `1.57`) and cannot build.

The `checksum=` line must be changed to match the distfile anytime the version changes. Packages simply cannot build if it is not matching.

**Comment by JuniorSuperTux** [comment]
> The `checksum=` line must be changed to match the distfile anytime the version changes. Packages simply cannot build if it is not matching.

I'm sorry, this is my first time doing this, so there are some details that I haven't known. How should I get the checksum of the destination file?

> That version of starship does not support the rust version we have (requiring `1.59 `while we have `1.57`) and cannot build.

So that means I have to make another commit to update rust in this repository?

**Comment by JuniorSuperTux** [comment]
How do I update `rust-bootstrap`? Since `1.59.0` isn't in https://repo-default.voidlinux.org/distfiles

**Comment by classabbyamp** [comment]
there is already an in-progress PR to update rust (#37232)

**Comment by tranzystorek-io** [comment]
Rust 1.61 is there, i think this PR is good to proceed

**Comment by cinerea0** [comment]
As the maintainer of the package, I'll handle updating it when the Rust update PR is merged.

**Comment by cinerea0** [comment]
Currently testing these changes and they work for me, now a member just has to approve the check workflows.

**Comment by 0x5c** [comment]
The commits should be squashed, see [CONTRIBUTING.md](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#starting-a-pull-request)

**Comment by JuniorSuperTux** [comment]
> The commits should be squashed, see [CONTRIBUTING.md](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#starting-a-pull-request)

Done

**Comment by JuniorSuperTux** [comment]
Hello, since I'm new to this, I wonder if there are any essential steps that I have not done correctly? Or is it just a priority of merging pull requests?

**Comment by classabbyamp** [comment]
> Hello, since I'm new to this, I wonder if there are any essential steps that I have not done correctly? Or is it just a priority of merging pull requests?

nope, you're fine. Things just move slowly sometimes.

**Comment by paper42** [comment]
> Hello, since I'm new to this, I wonder if there are any essential steps that I have not done correctly? Or is it just a priority of merging pull requests?

> I tested the changes in this PR: NO

Please test your PR next time

**Pull request merged**
