### PR TITLE
update docker

### PR DESCRIPTION
**Pull request by radiden**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Review by ahesford — CHANGES_REQUESTED** [review]
To fix #30341, please add a `tini` package and include it in the `depends` for the `Docker` meta package.

**Review by ahesford — APPROVED** [review]
This seems fine to me. @pudiva please confirm that the addition of `tini` as packages resolves #30341.

**Comment by pudiva** [comment]
testing...

**Comment by pudiva** [comment]
Ok, the tini package does offer `docker-init`, as a symlink to `tini-static`, which fixes #30341.

Just one note though: I think that the docker package should provide this link, not tini, as tini is not restricted to docker, but a dependency of it. (but I might be wrong :woman_shrugging:)

**Comment by ahesford** [comment]
Moving the `docker-init` link to one of the `docker` packages is a good suggestion. It seems that having the `docker` metapackage depend on `tini`, and therefore offer the `docker-init` symlink, is reasonable because I believe both `moby` and `docker-cli` are usably without `tini` for some workflows.

Because I am not a major user of Docker---I prefer podman for Docker-style containers---I'd like to know what others think.

**Comment by endigma** [comment]
> Ok, the tini package does offer `docker-init`, as a symlink to `tini-static`, which fixes #30341.
> 
> Just one note though: I think that one of the docker packages should provide this link, not tini, as tini is not restricted to docker, but a dependency of it. (but I might be wrong )

It's not like the symlink is adding anything that will cause issues.

**Comment by pudiva** [comment]
> It's not like the symlink is adding anything that will cause issues.

except maybe disorganization and confusion...?

I mean, in this case, it's probably not a big deal, and I can understand if people decide to just merge the way it is because they have better things to do and don't want to waste their time... but I don't think that just _not causing issues_ is a good reason to oversee the quality of the packages.

I mean²: I wasn't having any issues before 9b3c344a79a1930062ec7a0df22882f3a04127ec, when the **docker** package was split into a bunch of mini packages. To me, having them altogether was _not causing issues_, so why care to split anway? :upside_down_face:

Actually... I looking at 9b3c344a79a1930062ec7a0df22882f3a04127ec again, it seems that **docker** was just renamed to **docker-cli**, and that it doesn't actually have any other **docker-** package... why was it split?

**Comment by pudiva** [comment]
> Actually... I looking at 9b3c344 again, it seems that docker was just renamed to docker-cli, and that it doesn't actually have any other docker- package... why was it split?

I mean³: I understand there might be a benefit to splitting **moby** out of **docker**, but why rename **docker** to **docker-cli** instead of just adding **moby** as a dependency to **docker**? Is it even possible to use **docker-cli** without **moby**?

**Comment by ahesford** [comment]
It was split because Docker itself is no longer released as a monolithic package. This was the right call.

The purpose of the new `docker` meta is to pull in the new components and ensure a smooth transition. We bungled this by not including `tini` as `docker-init`. While I noticed the absence of the binary during review, I misinterpreted the `tini` README---which states that the package is included in Docker---as an indication that it would no longer be necessary. That was my mistake.

The only remaining question is whether the `docker-init` symlink belongs in `docker` or `tini`. I agree with @pudiva that it makes more sense in `docker` since that's where it will be used; however, as I said, I'd rather get some comments about this from other Void maintainers who use Docker.

**Comment by pudiva** [comment]
> It was split because Docker itself is no longer released as a monolithic package. This was the right call.

ahhhhh fair enough :+1:

**Comment by endigma** [comment]
It's not really an issue either way, however thinking about it nobody should need the static binary called `docker-tini` except people using docker, so adding it to the meta-package is probably the best call, both for feature parity and cleanliness.

**Comment by endigma** [comment]
> > Actually... I looking at [9b3c344](https://github.com/void-linux/void-packages/commit/9b3c344a79a1930062ec7a0df22882f3a04127ec) again, it seems that docker was just renamed to docker-cli, and that it doesn't actually have any other docker- package... why was it split?
> 
> I mean³: I understand there might be a benefit to splitting **moby** out of **docker**, but why rename **docker** to **docker-cli** instead of just adding **moby** as a dependency to **docker**? Is it even possible to use **docker-cli** without **moby**?

The `docker` package isn't a rename of docker-cli, it's a effectively a metapackage that pulls in `docker-cli`, `moby`, `tini`. This was done because these tools are not codependent, moby can function without docker-cli as docker-cli can function without moby.

**Comment by endigma** [comment]
Is this good to be merged?

**Comment by Skaytacium** [comment]
Any idea when this will actually get merged because all the tests seem to be passing and it's approved.

**Pull request merged**
