### PR TITLE
AusweisApp2: update to 1.24.1.

### PR DESCRIPTION
**Pull request by dataCobra**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)

### CODE REVIEW

**Comment by dataCobra** [comment]
Can somebody help me with the cross compilation issue?

**Comment by Johnnynator** [comment]
Adding `build_helper=qemu` should help with this issue.

**Comment by dataCobra** [comment]
@classabbyamp or @Duncaen what is happening here with the checks? I don't understand the issue.

Building on my machine works without a problem.

I've also finally tested the whole program.

**Comment by dataCobra** [comment]
The checks passed. :+1:

I've successful tested the whole program.

**Pull request merged**
