### PR TITLE
New package: LGOGDownloader-3.3 

### PR DESCRIPTION
**Pull request by RunningDroid**
Continued from voidlinux/void-packages#14973

### CODE REVIEW

**Comment by newbluemoon** [comment]
The problem with the cross-builds is that it uses `help2man` to create the man pages which runs the compiled binary and puts the output into a man page. Apparently, this doesn’t work when cross compiling. ;)

But it seems like the cmake script doesn’t try to do this if it doesn’t find the help2man binary. So adding `help2man` conditionally to `hostmakedepends` will work, like:

```
...
hostmakedepends="pkg-config"
...
if [ -z "$CROSS_BUILD" ]; then
	hostmakedepends+=" help2man"
fi
```

**Comment by RunningDroid** [comment]
@newbluemoon Thanks for the tip!

**Comment by cr6git** [comment]
@RunningDroid your branch has conflicts that must be resolved.

**Comment by RunningDroid** [comment]
@cr6git It's fixed now

**Pull request merged**
