### PR TITLE
New packages: calls + deps (callaudiod + feedbackd)

### PR DESCRIPTION
**Pull request by jcgruenhage**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by Piraty** [comment]
@jcgruenhage what's missing here ? (besides an environment to use this on to acually make phone calls ;) )
I assume @JamiKettunen is interested as well?

**Comment by JamiKettunen** [comment]
@Piraty Yes I'd be interested, I've actually already got these as a part of my phone dev packages ([gnome-calls](https://github.com/SoMainline/void-bootstrap/tree/somainline/packages/misc/gnome-calls),  ̣[callaudiod](https://github.com/SoMainline/void-bootstrap/tree/somainline/packages/misc/callaudiod), [feedbackd](https://github.com/SoMainline/void-bootstrap/tree/somainline/packages/misc/feedbackd)) but haven't unfortunately been able to test them yet on my Qualcomm hardware due to no audio routing :(

**Comment by jcgruenhage** [comment]
The modem shouldn't be the problem on my phone, calling was working just fine on pmOS. How much would I need to get going for this working on Void, any idea @JamiKettunen? Would gnome-calls, callaudiod, feedbackd and ModemManager already be enough?

**Comment by JamiKettunen** [comment]
@jcgruenhage I unfortunately have no idea how the PinePhone cellular stack typically works, I'll explore it more in-depth after getting my PinePhone hopefully soon. However I've seen [eg25-manager](https://gitlab.com/mobian1/devices/eg25-manager) mentioned in Sxmo for example so that may be needed on top of what you mentioned already.

**Comment by Piraty** [comment]
you may get calls working without eg25-manager but it will probably require fiddling with audio settings via at commands

**Comment by jcgruenhage** [comment]
Well, sort-of stale, but I still plan to continue on it.

**Comment by Piraty** [comment]
i'll be happy to merge once you rebased and possibly updated to latest, to bring this forward and enable broader integration of mobile phone stack

**Comment by jcgruenhage** [comment]
I'll try to take a look at this later today when I'm back at home and have access to my pinephone again. Would it make sense to merge those applications already even if the remaining stack for making calls isn't necessarily all there and tested already?

**Comment by jcgruenhage** [comment]
not quite sure what's up here but void doesn't boot on my pinephone right now, but postmarketos does.. I'll have to check again another day when I have a bit more time to investigate..

**Comment by jcgruenhage** [comment]
Getting better and better: Seems that void didn't boot because it was on the sdcard, and the phone was deeply discharged enough that the additional power draw of the sdcard means it couldn't boot. Now that the phone is charged again, void boots just fine. Next hurdle now: Sway doesn't want to launch. I'd assume it's related to the kernel being ancient. I'll look into this again once Linux 6.1.0 is released, because a few new things for the pinephone are in the current release candidates.

**Comment by jcgruenhage** [comment]
So, another two months have gone by, and I have a small-ish update. #41654 brings in kernel 6.1.3, which brings in a bunch of improvements, including finally having the keyboard case working. I still need to grab an adapter to connect a proper keyboard to it for initial setup, which I don't have with me right now, but I'll try to make a little more progress here again.

**Comment by JamiKettunen** [comment]
@jcgruenhage if you don't mind I can submit updated packages which I've confirmed work (minus call audio since I don't have that hooked up in DTS) on my OnePlus 5 phone running a mainline Linux kernel :)

About to start maintaining ModemManager stack too, stay tuned for that ^^

**Comment by jcgruenhage** [comment]
I absolutely don't mind, feel free to take over ^^

**Pull request closed without merging**
