### PR TITLE
ardour: update to 7.0.

### PR DESCRIPTION
**Pull request by rantlivelintkale**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-musl

### CODE REVIEW

**Comment by classabbyamp** [comment]
cc: maintainer @tibequadorian

**Comment by rantlivelintkale** [comment]
```
2022-10-23T02:14:07.9145074Z [1103/1148] Linking build/gtk2_ardour/ardour-7.0.0
2022-10-23T02:14:08.7255634Z /usr/lib/gcc/arm-linux-musleabihf/10.2.1/../../../../arm-linux-musleabihf/bin/ld: gtk2_ardour/audio_clock.cc.1.o: undefined reference to symbol '__atomic_compare_exchange_8'
2022-10-23T02:14:08.7256544Z /usr/lib/gcc/arm-linux-musleabihf/10.2.1/../../../../arm-linux-musleabihf/bin/ld: /usr/arm-linux-musleabihf/lib/libatomic.so.1: error adding symbols: DSO missing from command line
2022-10-23T02:14:08.7257064Z collect2: error: ld returned 1 exit status
```

I assume that's why the armv6l-musl failed, I'll try building it locally as well.

The lint complains about the `PATH` variable not being prefixed, but I assume that it should not be prefixed since it is the `PATH` variable.

**Comment by rantlivelintkale** [comment]
> ```
> 2022-10-23T02:14:07.9145074Z [1103/1148] Linking build/gtk2_ardour/ardour-7.0.0
> 2022-10-23T02:14:08.7255634Z /usr/lib/gcc/arm-linux-musleabihf/10.2.1/../../../../arm-linux-musleabihf/bin/ld: gtk2_ardour/audio_clock.cc.1.o: undefined reference to symbol '__atomic_compare_exchange_8'
> 2022-10-23T02:14:08.7256544Z /usr/lib/gcc/arm-linux-musleabihf/10.2.1/../../../../arm-linux-musleabihf/bin/ld: /usr/arm-linux-musleabihf/lib/libatomic.so.1: error adding symbols: DSO missing from command line
> 2022-10-23T02:14:08.7257064Z collect2: error: ld returned 1 exit status
> ```
> 
> I assume that's why the armv6l-musl failed, I'll try building it locally as well.

Fails with the same error locally as well.

**Comment by classabbyamp** [comment]
grep srcpkgs for ATOMIC8, there's some examples for how to solve that

**Comment by rantlivelintkale** [comment]
> grep srcpkgs for ATOMIC8, there's some examples for how to solve that

Awesome. Should work now. At least it builds locally for armv6l-musl.

**Pull request merged**
