### PR TITLE
[DO NOT MERGE] gnome-terminal: fix umask

### LINKED ISSUE #9707: GNOME-Terminal gets umask wrong
It appears that after #9126 GNOME-Terminal gets the umask wrong, defaulting to 0007. Sourcing /etc/profile fixes that, but I'm not exactly sure why because we already source that via gnome-session.

@glats

### PR DESCRIPTION
**Pull request by Cogitri**
fixes #9707

Please test @glats

### CODE REVIEW

**Comment by Cogitri** [comment]
Ah, you might have to delete and create a new profile in GNOME-terminal for it to use the default

**Comment by Duncaen** [comment]
Its not the traditional behavior tho.

**Comment by Cogitri** [comment]
Yeah, but we can't exactly source the profile with GDM, nor can we execute a script on startup. GDM doesn't run scripts at startup (at least not for Wayland sessions) and setting the umask in /usr/bin/gnome-session seems ineffective as @glats noted.

**Comment by Cogitri** [comment]
Thanks for the heads-up though, hadn't considered that :)

**Comment by Duncaen** [comment]
And in general, the profile shouldn't be responsible to set the umask, this is a big workaround because we set a restrictive umask in `/etc/login.defs` (just for creating restrictive home directories for `useradd`) and revert to a less restrictive umask in the profile.
https://github.com/voidlinux/void-packages/issues/2994

**Comment by Cogitri** [comment]
Sooo...how should we go ahead with this?

**Pull request closed without merging**
