### PR TITLE
New package: helix-bin-0.2.1

### PR DESCRIPTION
**Pull request by shizonic**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by Johnnynator** [comment]
I would recoomend to do a from source build once https://github.com/helix-editor/helix/pull/1536 is merged and a new release tagged.

**Comment by shizonic** [comment]
Closed until https://github.com/helix-editor/helix/pull/1536 is merged.

**Comment by tranzystorek-io** [comment]
22.03 has landed, but now uses the format ident feature from Rust 1.58 so we probably need to wait for https://github.com/void-linux/void-packages/pull/36269

**Comment by leahneukirchen** [comment]
Also needs `conflicts="hex>=0"`.

**Comment by tranzystorek-io** [comment]
> 22.03 has landed, but now uses the format ident feature from Rust 1.58 so we probably need to wait for #36269

Fix landed in https://github.com/helix-editor/helix/commit/f2dd3d446914ec0953cd7e056d430fc3b959e75d, can be used as patch

**Pull request closed without merging**
