### PR TITLE
[TESTING] OpenSSH 8.2

### PR DESCRIPTION
**Pull request by leahneukirchen**
~~Entirely untested so far, I need to get a FIDO2 key first.~~

- [x] x86_64
- [x] x86_64-musl
- [x] armv7
- [ ] i686

Uses Github tarball so far as official one is missing(?).

Please test on the usual platforms.

### CODE REVIEW

**Comment by leahneukirchen** [comment]
Ok, tested with a Yubikey 4 (1050:0407), works fine.

One issue so far: `70-u2f.rules` needs to be installed, but currently already is provided by `u2f-host` (which is deprecated upstream). Ideas?

**Comment by leahneukirchen** [comment]
We could use `u2f-hidraw-policy` instead, but our eudev lacks a rule to permit access to security tokens in general.  I added to `60-u2f-hidraw.rules`:

```
ENV{ID_SECURITY_TOKEN}=="?*", TAG+="uaccess", GROUP="users", MODE="0660"
```

**Comment by leahneukirchen** [comment]
This update must be merged before glibc 2.31, else ssh breaks on 32-bit platforms, I think.

**Comment by eli-schwartz** [comment]
Just want to mention, in case you haven't noticed...

https://lists.archlinux.org/pipermail/arch-dev-public/2020-February/029865.html
https://bugs.archlinux.org/task/65517
https://bugs.gentoo.org/709748

You are going to want to make sure users are warned to restart sshd after the update, or they won't be able to successfully connect to it.

**Comment by leahneukirchen** [comment]
Also, Arch ran into this issue where you need to restart sshd after installation, else you can't login: https://bugs.archlinux.org/task/65517

Should this go into an INSTALL.msg?

**Comment by Vaelatern** [comment]
This would be a valid use for a one-line INSTALL.msg, to be removed after how long?

**Comment by leahneukirchen** [comment]
With 8.3 i guess, which is half a year away?

**Comment by jnbr** [comment]
Basic functionality works for me on armv7 (glibc) and x86_64-musl. Don't have a FIDO2 key to test.

**Comment by leahneukirchen** [comment]
I'll merge this tomorrow unless someone complains.

**Comment by ailiop-git** [comment]
do we really need to make fido2 a default build option? similar to #12486, this isn't really widely used and it's polluting the base-system with libcbor and libfido..

**Comment by leahneukirchen** [comment]
It won't be widely used if it's not on by default, and the additional dependencies are <300k.

You can ignorepkg it without problems (except it wont work, ofc) if you insist.

**Comment by leahneukirchen** [comment]
I misread the announcement, apparently OpenSSH 8.2 is enough on the server. So we could move the fido stuff into a subpkg, and users who want to use it can install it.

**Comment by Vaelatern** [comment]
A subpackage makes some sense, that way you know you are installing fido enabled stuff.

**Comment by the-maldridge** [comment]
While normally I'd be all for isolation and splitting up unnecessary resources, in this case I think the subpackage is probably unnecessary.  How big is the additional data that we'd want to split it off?

**Comment by ailiop-git** [comment]
What's the downside of introducing it as a subpkg? It's really not a matter of size bloat, but rather keeping the base clean from dependencies that aren't strictly required.

**Pull request merged**
