### PR TITLE
gnucash: update to 5.3, enable SQL support + add libdbi packages

### PR DESCRIPTION
**Pull request by cinerea0**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- These new packages conform to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc (crossbuilds disabled for gnucash)

---

**cc: @manfredu**

### CODE REVIEW

**Comment by cinerea0** [comment]
A few things I wanted to point out:
* `gnucash`'s changelog is hosted on GitHub along with a mirror of its source code. That repo also hosts the same release tarballs that are hosted on SourceForge, so the distfiles could be set to that instead if we wanted to move away from SourceForge.
* The reason I split `libdbi` and `libdbi-drivers` as much as I did is because the docs subpackages are larger and have far more files than the base packages, and they contain information only relevant to developers.
* I added `libdbi-drivers` as a dependency to `gnucash` because, while it isn't required for basic functionality, you can't use the SQL backends without it.

**Comment by sgn** [comment]
I think it's better to split those 3 files into 3 packages:
```
/usr/lib/dbd/libdbdmysql.so
/usr/lib/dbd/libdbdpgsql.so
/usr/lib/dbd/libdbdsqlite3.so
```

Those files isn't that big itself, but I guess they will pull libmariaclient and libpgsql in which is big (I guess).

**Comment by cinerea0** [comment]
> I think it's better to split those 3 files into 3 packages

In addition to or instead of the current splits?

**Comment by cinerea0** [comment]
Moving each library out into its own package results in the main package being empty. Taking the trick from `mpg123-extras` and installing the readme as documentation doesn't work because all of the documentation is moved into `libdbi-drivers-doc`. Is there an another workaround?

**Comment by sgn** [comment]
`build_style=meta`, I would say, or let `sqlite3`, which is the lite version stay in main package.

**Pull request merged**
