### PR TITLE
guitarix2: update to 0.42.0 + added 'faust' build option

### PR DESCRIPTION
**Pull request by DavideMaggio**
#27251

### CODE REVIEW

**Comment by ericonr** [comment]
Looks good, thanks! Would you like to enable any of the options by default?

**Comment by DavideMaggio** [comment]
ok, added faust as a default build option but It didn't build on arm* anymore (/usr/bin/faust: not found.).
Solved by changing faust to be host-dependant (instead of target-dependant), that's correct?

**Comment by ericonr** [comment]
@DavideMaggio I was taking a look at how guitarix does its thing, it seems we shouldn't enable faust here.

They use it to generate a bunch of files, which are then post processed with some custom tools. Since they might have to fix those tools when using different faust versions, we risk breaking something by enabling faust. It's better to simply use their pre generated files directly, which is what we already do. From what I understand, guitarix doesn't use faust at runtime at all.

**Comment by DavideMaggio** [comment]
@ericonr I agree.
 I think I could revert all the changes excluding 'version' and 'checksum' fields to at least save the update part.

**Comment by ericonr** [comment]
Sure :)

I would definitely like to merge the update.

**Comment by ericonr** [comment]
Please ping me when done with changes, otherwise I can miss them :P

**Pull request merged**
