### PR TITLE
New package: Komikku-0.14.0

### PR DESCRIPTION
**Pull request by not-chicken**
An online/offline comics,manga reader
- Plus  dependencies
- Tested on x86-64
- `python3-pure-protobuf` is using github source because `PYPI` one lacks `LICENSE` file

### CODE REVIEW

**Comment by Chocimier** [comment]
komikku needs libnotify, otherwise ok.

**Comment by not-chicken** [comment]
> komikku needs libnotify, otherwise ok.

Thanks!. Added `libnotify` dep to `komikku`

**Comment by Chocimier** [comment]
Should be also named uppercase, Komikku.

**Comment by not-chicken** [comment]
> Should be also named uppercase, Komikku.

Done.

**Pull request merged**
