### PR TITLE
Remove apache-maven-bin

### LINKED ISSUE #24617: Weird organization of maven packages
The `apache-maven-bin` package is prebuilt, has files in `/opt`, but symlinks to its files in `/usr/bin`.

On the other hand, the `apache-maven` package has compiled java stuff in `/usr/share`, requires sourcing a profile file to get access to its tools, and if `apache-maven-bin` is installed at the same time, its tools will be first in the PATH anyway, so the profile doesn't really help.

Then, some packages have `apache-maven`, others `apache-maven-bin` in `hostmakedepends`.

IMO neither of these packages really fit the proper packaging guidelines. So my questions are:

- should  the maven binaries become alternatives, or should `apache-maven` become the preferred provider of maven stuff?
- should we move all templates to `apache-maven` (and potentially remove `apache-maven-bin`? Why is it in the repos?)

### PR DESCRIPTION
**Pull request by ericonr**
Related to and fixes #24617

### CODE REVIEW

**Comment by ericonr** [comment]
I guess I need to include https://github.com/fusesource/jansi-native in here, otherwise it downloads pre-built x86 glibc shit.

**Comment by ericonr** [comment]
@Johnnynator are the changes in tuxguitar ok?

**Comment by ericonr** [comment]
@mobinmob might be interested as well

**Comment by mobinmob** [comment]
@ericonr : No time to test I am afraid. Everything seems fine, thank you for doind this!

**Comment by kartikynwa** [comment]
@ericonr dbeaver builds and works fine

**Pull request merged**
