### PR TITLE
obs: add vaapi dependencies.

### PR DESCRIPTION
**Pull request by Valeyard1**
closes void-linux/void-packages#10762

### CODE REVIEW

**Comment by Hoshpak** [comment]
This seems wrong to me. Hardware-specific drivers should not be in the dependencies of a package unless the package cannot be executed without them. In this case they enable additional functionality so it should be up to the user to install the apropriate driver for his hardware.

**Comment by xtraeme** [comment]
I suspect the code uses dlopen().

**Comment by xtraeme** [comment]
I agree with @Hoshpak 

It's weird that you added them via `makedepends` but were not added to `depends`.

xbps-src can't detect dlopen()ed dependencies, remember.

**Comment by Hoshpak** [comment]
I think the maximum that would be apropriate here would be an install message that advises the users that the drivers can optionally be installed if the feature is needed. I just tried on a system that already had the drivers installed and it worked fine so they are not needed at compile time. I'm closing this PR, feel free to create a new one if you want to add an install message.

**Pull request closed without merging**
