### PR TITLE
root: update to 6.28.02

### PR DESCRIPTION
**Pull request by BenJarg**
- I tested the changes in this PR: **YES**

- I built this PR locally for my native architecture, (x86_64_glibc)

### CODE REVIEW

**Comment by dkwo** [comment]
why was the musl patch removed?

**Comment by BenJarg** [comment]
@dkwo I had it merged upstream (root-project/root#10045) and it looks like it made it into this release.

**Comment by dkwo** [comment]
I see, that makes sense.

Current musl failure:
```
[9677/9682] Building CXX object roofit/xroofit/CMakeFiles/RooFitXRooFit.dir/src/xRooFit.cxx.o
FAILED: roofit/xroofit/CMakeFiles/RooFitXRooFit.dir/src/xRooFit.cxx.o 
/usr/bin/g++  -I/builddir/root-6.28.00/roofit/xroofit/inc -I/builddir/root-6.28.00/core/unix/inc -I/builddir/root-6.28.00/core/foundation/v7/inc -I/builddir/root-6.28.00/core/base/v7/inc -I/builddir/root-6.28.00/core/clingutils/inc -I/builddir/root-6.28.00/core/textinput/inc -I/builddir/root-6.28.00/core/thread/inc -I/builddir/root-6.28.00/core/zip/inc -I/builddir/root-6.28.00/core/rint/inc -I/builddir/root-6.28.00/core/clib/inc -I/builddir/root-6.28.00/core/meta/inc -I/builddir/root-6.28.00/core/gui/inc -I/builddir/root-6.28.00/core/cont/inc -I/builddir/root-6.28.00/core/foundation/inc -I/builddir/root-6.28.00/core/base/inc -I/builddir/root-6.28.00/build/ginclude -I/builddir/root-6.28.00/gui/gui/inc -I/builddir/root-6.28.00/graf2d/gpad/inc -I/builddir/root-6.28.00/hist/hist/inc -I/builddir/root-6.28.00/math/mathcore/v7/inc -I/builddir/root-6.28.00/math/mathcore/inc -I/builddir/root-6.28.00/core/imt/inc -I/builddir/root-6.28.00/core/multiproc/inc -I/builddir/root-6.28.00/math/matrix/inc -I/builddir/root-6.28.00/graf2d/graf/inc -I/builddir/root-6.28.00/io/io/v7/inc -I/builddir/root-6.28.00/io/io/inc -I/builddir/root-6.28.00/core/clib/res -I/builddir/root-6.28.00/builtins -I/usr/include/freetype2 -I/builddir/root-6.28.00/gui/ged/inc -I/builddir/root-6.28.00/tree/tree/inc -I/builddir/root-6.28.00/tree/treeplayer/inc -I/builddir/root-6.28.00/roofit/roofitcore/inc -I/builddir/root-6.28.00/math/minuit/inc -I/builddir/root-6.28.00/math/minuit2/inc -I/builddir/root-6.28.00/math/foam/inc -I/builddir/root-6.28.00/math/smatrix/inc -I/builddir/root-6.28.00/roofit/batchcompute/inc -I/builddir/root-6.28.00/roofit/batchcompute/res -I/builddir/root-6.28.00/roofit/common/res -I/builddir/root-6.28.00/roofit/histfactory/inc -I/builddir/root-6.28.00/roofit/roofit/inc -I/builddir/root-6.28.00/roofit/roostats/inc -I/builddir/root-6.28.00/io/xmlparser/inc -I/usr/include/libxml2 -I/builddir/root-6.28.00/roofit/hs3/inc -I/builddir/root-6.28.00/roofit/jsoninterface/inc -I/builddir/root-6.28.00/roofit/xroofit/inc/RooFit -I/builddir/root-6.28.00/net/net/inc -I/builddir/root-6.28.00/graf3d/g3d/inc -DNDEBUG -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2    -ffile-prefix-map=/builddir/root-6.28.00/build=. -fdiagnostics-color=always -std=c++17 -Wno-implicit-fallthrough -Wno-noexcept-type -pipe  -Wshadow -Wall -W -Woverloaded-virtual -fsigned-char -pthread -fPIC -fno-math-errno -std=c++17 -MD -MT roofit/xroofit/CMakeFiles/RooFitXRooFit.dir/src/xRooFit.cxx.o -MF roofit/xroofit/CMakeFiles/RooFitXRooFit.dir/src/xRooFit.cxx.o.d -o roofit/xroofit/CMakeFiles/RooFitXRooFit.dir/src/xRooFit.cxx.o -c /builddir/root-6.28.00/roofit/xroofit/src/xRooFit.cxx
In file included from /builddir/root-6.28.00/roofit/xroofit/src/xRooFit.cxx:43:
/builddir/root-6.28.00/roofit/xroofit/src/coutCapture.h: In constructor 'cout_redirect::cout_redirect(std::string&, size_t)':
/builddir/root-6.28.00/roofit/xroofit/src/coutCapture.h:21:14: error: assignment of read-only location 'stdout'
   21 |       stdout = fp;
      |              ^
/builddir/root-6.28.00/roofit/xroofit/src/coutCapture.h: In destructor 'cout_redirect::~cout_redirect()':
/builddir/root-6.28.00/roofit/xroofit/src/coutCapture.h:28:14: error: assignment of read-only location 'stdout'
   28 |       stdout = old3;
      |              ^
```

**Comment by BenJarg** [comment]
@dkwo Yeah, so looking into this, it seems changing the value of `stdout` isn't portable, as it isn't C standard compliant. I'll write a patch to fix `coutCapture.h` for musl.

**Comment by BenJarg** [comment]
Ok, so it seems the experimental ROOT 7 features are enable by default now, which includes that new code that doesn't work with musl.  So for now, I will just disable these experimental features for musl, until there is a better fix for this.

**Comment by Chocimier** [comment]
6.28/02 is out

**Pull request merged**
