### PR TITLE
New package: xorgxrdp and xrdp

### PR DESCRIPTION
**Pull request by combro2k**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by combro2k** [comment]
ARM and Musl I couldn't test, so if someone can :-)

**Comment by combro2k** [comment]
I see some mistakes I made.
This is a  bit trial and error on my end, I'm not familair with void linux packaging only Debian and such.

**Comment by Chocimier** [comment]
Well.

Cross build fails because default build target generate keys with just-compiled binary.
Keys shouldn't be generated build-time, disable with 

    @@ -55,6 +53,11 @@ pre_configure() {
            ./bootstrap
     }
     
    +post_configure() {
    +       vsed -i keygen/Makefile -e 's@./xrdp-keygen@:@'
    +       vsed -i keygen/Makefile -e 's@$(OPENSSL)@:@'
    +}
    +
     post_install() {
            vsv xrdp
            vsv xrdp-sesman

Musl build fails because of wrong --build target passed. Pass none, build style gets that right.

Build of test need check-devel in checkdepends.

xorgxrdp should be build for all archs.

depends= are filled automatically, see 04-generate-runtime-deps in build log.

**Comment by Anachron** [comment]
@combro2k are you still interested? I may pick this one up if not.

**Comment by combro2k** [comment]
Hi @Anachron please feel free to pick this up :-)
I don't have many time anymore to resolve the outstanding PR.
My work and private time has been changed a bit :-)

**Comment by dezifit** [comment]
@Anachron

> @combro2k are you still interested? I may pick this one up if not.

I also would like to see this package and tested the template with updated `xrdp` (0.9.19) on x86_64/glibc without issues (only replaced dependency `xorg` with the much lighter `xorg-server` package).  I'm not comfortable with the package submission process but am willing to help/test if needed. Any chance to add this package?

**Pull request closed without merging**
