### PR TITLE
xst: update to 0.8.4.1

### LINKED ISSUE #27070: xst no transparency
### System

* xuname:  Void 5.9.13_1 x86_64 GenuineIntel uptodate rrrmFFFFF
* package:  xst-0.8.4_1

### Expected behavior
Transparecy as defined in .Xresources

### Actual behavior
No transparency

### Steps to reproduce the behavior
Download xst (st built with transparency and other patches), have a compositor running, add a value for ``st.opacity:'' (or xst.opacity: or st*opacity:), load .Xresources with xrdb.

I've verified that my compositor is working. Also, I'm taking this as a sign to just use urxvt, but I wanted to make this issue known.

### PR DESCRIPTION
**Pull request by ndowens**
Closes #27070

### CODE REVIEW

**Comment by vikigenius** [comment]
@ndowens , Can you include this fix as a patch https://github.com/gnotclub/xst/commit/a0894b52af4ee6cba42e93a2a756a2092ee46e48.  

I have suggested that they include it in the latest release. But if they don't do it the change is small enough that we can add this as a patch.

**Comment by paper42** [comment]
the homepage and distfiles redirect to https://github.com/gnotclub/xst

**Comment by ndowens** [comment]
> the homepage and distfiles redirect to https://github.com/gnotclub/xst

Thanks, fixed

**Comment by vikigenius** [comment]
@ericonr, can we merge this? This fixes quite a few issues with the previous update to xst

**Pull request merged**
