### PR TITLE
transmission: update to 3.00

### PR DESCRIPTION
**Pull request by kartikynwa**

### CODE REVIEW

**Comment by ericonr** [comment]
Have you checked out their CMake build? Seems to be the recommended version nowadays. And they specify that the std should be `-std=gnu++17`, too. If it compiled I don't think it needs to be changed, though.

**Comment by kartikynwa** [comment]
@ericonr sure I can try making a cmake template. I will try tonight and update on how it goes.

**Comment by ericonr** [comment]
If it doesn't cross build successfully I think we can stick to the current build_style, but if it works it would be great, I think.

**Comment by kartikynwa** [comment]
CMake build fails because the release tarball in transmission/transmission-releases is missing some files. [Link to issue.](https://github.com/transmission/transmission/issues/1248)

And the release on transmission/transmission is missing submodules so cmake doesn't work with that either.

We can wait for them to update the tarball then I can file a new PR if I can get it to work.

**Comment by ericonr** [comment]
Shame. Hope they get a new tarball out soon :)

**Comment by floppym** [comment]
I ended up rolling my own tarball with the fix applied.

https://dev.gentoo.org/~floppym/dist/transmission-3.00.tar.xz

**Pull request merged**
