### PR TITLE
rapydscript-ng: add explicit python_version

### PR DESCRIPTION
**Pull request by fosslinux**

### CODE REVIEW

**Comment by Piraty** [comment]
@bra1nwave

**Comment by bra1nwave** [comment]
LGTM. Only [one](https://github.com/kovidgoyal/rapydscript-ng/blob/master/publish.py) script is converted, which is only useful for the upstream dev(s) anyway.

**Comment by Piraty** [comment]
@fosslinux please revbump so the package is rebuilt

**Comment by fosslinux** [comment]
@Piraty done

**Pull request merged**
