### PR TITLE
inkscape: update to 1.1

### PR DESCRIPTION
**Pull request by hervyqa**
- remove old patch
- add python3-Pillow: support new feature export to webp and jpg. tiff idk (failed).

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 

- [x] I built this PR locally for my native architecture, (x86_64-musl)
- [ ] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [ ] aarch64-musl
  - [ ] armv7l
  - [ ] armv6l-musl

#### Result

Screenshot_20210607_111320

### CODE REVIEW

**Comment by hervyqa** [comment]
failed to build :D
any suggestion @ericonr ?

**Comment by hervyqa** [comment]
Screenshot_20210607_123223

btw, success in my machine.

**Comment by ericonr** [comment]
Update is happening in #31149, though we should pull in your pillow change. Will close this as duplicate.

**Comment by atk** [comment]
Should we both be co-maintainers?

**Comment by ericonr** [comment]
Since @hervyqa wasn't adopting the package in this PR, I would just keep as is.

**Comment by atk** [comment]
I was just asking since he was showing interest and I didn't want to take credits for his work.

**Pull request closed without merging**
