### PR TITLE
New package: imhex-1.25.0

### LINKED ISSUE #36954: Package request: ImHex
https://imhex.werwolv.net/
> ImHex is a Hex Editor, a tool to display, decode and analyze binary data to reverse engineer their format, extract informations or patch values in them. 

https://github.com/WerWolv/ImHex
https://git.alpinelinux.org/aports/tree/testing/imhex/APKBUILD

### PR DESCRIPTION
**Pull request by classabbyamp**
closes #36954

This template will be able to be cleaned up a bit once capstone v5 is released (currently at rc2).

#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

### CODE REVIEW

**Comment by dmarto** [comment]
I know you need only one file, but I saw your question in IRC and wanted to mention that sourcehut actually gives out archives - https://git.sr.ht/~danyspin97/xdgpp/archive/f01f810714443d0f10c333d4d1d9c0383be41375.tar.gz (you can use any valid git ref)

**Comment by classabbyamp** [comment]
ah, would be nice if they exposed that in the UI....

**Comment by iTrooz** [comment]
Hey, we updated Imhex to include a tarball with all sources. Currently, it would look like that : https://github.com/iTrooz/ImHex/releases

Is that okay with you ?

**Comment by classabbyamp** [comment]
works for me :)

I can update the template when the next release happens

**Pull request merged**
