### PR TITLE
New package: matrix-mirage

### PR DESCRIPTION
**Pull request by Francesco149**
this is a client for the matrix protocol and the various dependencies it wants.

### CODE REVIEW

**Comment by Francesco149** [comment]
oops looks like i forgot to include the version name in the commit msg, ill fix later

**Comment by Francesco149** [comment]
okay reworded everything. other than that they were building fine on the CI

**Comment by travankor** [comment]
I built this package and ran into this error when I tried to run it.
<Details>

```
~ 19:59:09 | Got library name:  "/usr/lib/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"                          
~ 19:59:10 | "PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:/src/backend/qml_bridge.py\", line 164, in <module>\n    BRIDGE = QMLBridge()\n\n  File \"qrc:/src/backend/qml_bridge.py\", line 50, in __init__\n    from .backend import Backend\n\n  File \"qrc:/src/backend/backend.py\", line 16, in <module>\n    from .matrix_client import MatrixClient\n\n  File \"qrc:/src/backend/matrix_client.py\", line 27, in <module>\n    from pymediainfo import MediaInfo\n\n  File \"/usr/lib/python3.8/site-packages/pymediainfo/__init__.py\", line 9, in <module>\n    from pkg_resources import get_distribution, DistributionNotFound\n\n  File \"/usr/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 3253, in <module>\n    def _initialize_master_working_set():\n\n  File \"/usr/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 3236, in _call_aside\n    f(*args, **kwargs)\n\n  File \"/usr/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 3265, in _initialize_master_working_set\n    working_set = WorkingSet._build_master()\n\n  File \"/usr/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 575, in _build_master\n    ws = cls()\n\n  File \"/usr/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 568, in __init__\n    self.add_entry(entry)\n\n  File \"/usr/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 624, in add_entry\n    for dist in find_distributions(entry, True):\n\n  File \"/usr/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2067, in find_on_path\n    for dist in factory(fullpath):\n\n  File \"/usr/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2139, in distributions_from_metadata\n    yield Distribution.from_location(\n\n  File \"/usr/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2591, in from_location\n    return cls(\n\n  File \"/usr/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2995, in _reload_version\n    md_version = self._get_version()\n\n  File \"/usr/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2773, in _get_version\n    version = _version_from_file(lines)\n\n  File \"/usr/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2557, in _version_from_file\n    line = next(iter(version_lines), '')\n\n  File \"/usr/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2768, in _get_metadata\n    for line in self.get_metadata_lines(name):\n\n  File \"/usr/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 1434, in get_metadata_lines\n    return yield_lines(self.get_metadata(name))\n\n  File \"/usr/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 1422, in get_metadata\n    value = self._get(path)\n\n  File \"/usr/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 1618, in _get\n    with open(path, 'rb') as stream:\n\nPermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/site-packages/blist-1.3.6-py3.8.egg-info/PKG-INFO'\n"
! 19:59:10 | Unhandled PyOtherSide error: Cannot import module: backend.qml_bridge (Traceback (most recent call last):

  File "qrc:/src/backend/qml_bridge.py", line 164, in <module>
    BRIDGE = QMLBridge()

  File "qrc:/src/backend/qml_bridge.py", line 50, in __init__
    from .backend import Backend

  File "qrc:/src/backend/backend.py", line 16, in <module>
    from .matrix_client import MatrixClient

  File "qrc:/src/backend/matrix_client.py", line 27, in <module>
    from pymediainfo import MediaInfo

  File "/usr/lib/python3.8/site-packages/pymediainfo/__init__.py", line 9, in <module>
    from pkg_resources import get_distribution, DistributionNotFound

  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3253, in <module>
    def _initialize_master_working_set():

  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3236, in _call_aside
    f(*args, **kwargs)

  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3265, in _initialize_master_working_set
    working_set = WorkingSet._build_master()

  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 575, in _build_master
    ws = cls()

  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 568, in __init__
    self.add_entry(entry)

  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 624, in add_entry
    for dist in find_distributions(entry, True):

  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2067, in find_on_path
    for dist in factory(fullpath):

  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2139, in distributions_from_metadata
    yield Distribution.from_location(

  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2591, in from_location
    return cls(

  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2995, in _reload_version
    md_version = self._get_version()

  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2773, in _get_version
    version = _version_from_file(lines)

  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2557, in _version_from_file
    line = next(iter(version_lines), '')

  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2768, in _get_metadata
    for line in self.get_metadata_lines(name):

  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1434, in get_metadata_lines
    return yield_lines(self.get_metadata(name))

  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1422, in get_metadata
    value = self._get(path)

  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1618, in _get
    with open(path, 'rb') as stream:

PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/site-packages/blist-1.3.6-py3.8.egg-info/PKG-INFO'
)
~ 19:59:10 | "PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'BRIDGE' is not defined\n"
! 19:59:10 | Unhandled PyOtherSide error: Function not found: 'BRIDGE.call_backend_coro' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'BRIDGE' is not defined
)
```

secondly, the binary conflicts with the package `mirage` and will overwrite files if you have `mirage` and `matrix-mirage` installed.

**Comment by Francesco149** [comment]
right, i forgot about that. i need to rename the binary.

hmm strange - that error did not happen to me, I'll look into it

**Comment by Francesco149** [comment]
`PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/site-packages/blist-1.3.6-py3.8.egg-info/PKG-INFO'`

ah yes, i remember having to chmod a python package that for some reason wasn't world readable and i have no idea why. I'm gonna try to reinstall all the dependencies and see if it breaks

**Comment by Francesco149** [comment]
yeah blist is definitely being installed with wrong permissions... but why?

```
$ ls -latr /usr/lib/python3.8/site-packages/blist-1.3.6-py3.8.egg-info/
total 48
-rw-r-----   1 root root     6 Jun 12 17:13 top_level.txt
-rw-r-----   1 root root   644 Jun 12 17:13 SOURCES.txt
-rw-r-----   1 root root  8790 Jun 12 17:13 PKG-INFO
-rw-r-----   1 root root     1 Jun 12 17:13 not-zip-safe
-rw-r-----   1 root root     1 Jun 12 17:13 dependency_links.txt
```

**Comment by Francesco149** [comment]
apparently this is just how the tarball is. guess we'll chmod it manually... https://github.com/DanielStutzbach/blist/issues/72

**Comment by Francesco149** [comment]
fixed by just grabbing the tarball off github instead

**Comment by Chocimier** [comment]
Please make new packages python3-only.

**Comment by Francesco149** [comment]
are you sure about that? what's the disadvantage of keeping python2 templates around? we could just not build them when we drop python2

**Comment by Chocimier** [comment]
It's not as easy as stop to build them in future. All py2 packages will need to be checked if they aren't required by other packages. Removing packages from repo require manual work too. Py2 modules are not accepted since few moths.

**Comment by travankor** [comment]
It works now but `qt5-graphicaleffects` should be a dependency somewhere (`matrix-mirage` `pyotherside`?).

>It's not as easy as stop to build them in future. All py2 packages will need to be checked if they aren't required by other packages. Removing packages from repo require manual work too. Py2 modules are not accepted since few months.

@Chocimier Not related to this PR, but `olm-python3` depends on `olm-python`, which seems wrong.

**Comment by Francesco149** [comment]
alright added the dep

**Comment by Chocimier** [comment]
@travankor, thanks for report, fixed.

**Comment by mirukana** [comment]
Note the only submodule still used as of v0.5.1 is hsluv-c, no need to fetch the others.

**Comment by Francesco149** [comment]
ohh thanks for the info

**Comment by Francesco149** [comment]
rebased and removed unnecessary submodules

**Comment by Francesco149** [comment]
rebased (2 deps were added by other people in recent commits) and updated to 0.5.2

**Comment by Francesco149** [comment]
updated to 0.6.0

**Comment by travankor** [comment]
0.6.1 is out

**Comment by Chocimier** [comment]
blist need patch for py3.8: https://patch-diff.githubusercontent.com/raw/DanielStutzbach/blist/pull/78.patch
For tests: tinycss2 needs `pre_check() { vsed -i setup.cfg -e s/--flake8// }`
cssselect2 needs `checkdepends="python3-pytest"` and `pre_check() { vsed -i setup.cfg -e s/--isort// }`
CairoSVG needs `checkdepends="${depends}"`, but tests will still fail without modifications of cairocffi: will push these later.

**Comment by Chocimier** [comment]
Fixed cairocffi.

**Comment by ericonr** [comment]
@Francesco149 ping

**Comment by abenson** [comment]
Seemingly abandoned.

**Pull request closed without merging**
