### PR TITLE
wpa_supplicant: update to 2.11

### PR DESCRIPTION
**Pull request by dkwo**
- I tested the changes in this PR: yes
- I built this PR locally for my native architecture, (x86_64-glibc)

iwlwifi works fine; brcmfmac see discussion at http://lists.infradead.org/pipermail/hostap/2024-August/042893.html

### CODE REVIEW

**Comment by Eloitor** [comment]
It seems that there are some issues with 2.11:
- https://www.lorenzobettini.it/2024/07/downgrading-packages-in-arch-linux-arm/
- https://forum.pine64.org/showthread.php?tid=19368&pid=122855#pid122855

**Comment by dkwo** [comment]
@Eloitor is this specific to pinebook? has it been reported upstream?

I've been running this for more than a week, tested with different networks (including eduroam) and had zero issues.

**Comment by Eloitor** [comment]
I don't know, I don't own one. 
It seems it also afects Broadcom Wireless BCM4331: https://bbs.archlinux.org/viewtopic.php?pid=2186121#p2186121

**Comment by dkwo** [comment]
hmm, so it may be the `brcmfmac` driver. I wonder if this breaks in asahi linux too.

**Comment by dkwo** [comment]
apple silicon is also affected, see https://lore.kernel.org/asahi/20240803-brcmfmac_pmksa_del_ssid-v1-1-4e85f19135e1@jannau.net/T/#u

**Comment by dkwo** [comment]
The problem with brcmfmac was identified by J.Grunau of asahi linux: they fixed it by reverting a commit breaking authentication on brcmfmac in wpa_supplicant (commit 41638606054a09867fe3f9a2b5523aa4678cbfa5). There's also a discussion to improve the upstream kernel driver, but quoting them 'A revert in wpa_supplicant might be still appropriate until exteded kernel drivers are deployed.'

**Comment by dkwo** [comment]
Btw, it seems like the option `-s     Log output to syslog instead of stdout.` is wrong for the runit service: should we drop it?

**Comment by dkwo** [comment]
This works with brcmfmac as well, at least with the asahi-linux kernel.

**Comment by dkwo** [comment]
this should be now safe to merge.
the relevant kernle patch is also in 6.10.7
asahi linux kernel works as well.

**Pull request merged**
