### PR TITLE
[WIP] qt5: update to 5.14.1.

### PR DESCRIPTION
**Pull request by mintsuki**
[ci skip]

### CODE REVIEW

**Comment by q66** [comment]
This doesn't really help. If the update was as simple as this we would've done it already.

**Comment by mintsuki** [comment]
As you can clearly see from the original comment my intent was not that of hogging the CI. I will keep that in mind from now on.

What more is needed exactly? Since this works with x86_64, and since this is not a major qt change, I wonder what else could be so complex about getting it to work, especially considering it works on Alpine Linux.

**Comment by mintsuki** [comment]
Actually, you know what, I am moving to another distro; farewell.

**Comment by q66** [comment]
As was already explained in the other PR, Alpine does not cross-compile their packages, so they don't need to deal with it. Native builds have always worked, it works with the other PR as well.

**Pull request closed without merging**
