### PR TITLE
New package: ruby-mdless-1.0.10

### LINKED ISSUE #19829: Package Request: mdless
> mdless is a utility that provides a formatted and highlighted view of Markdown files in Terminal

Source: https://github.com/ttscoff/mdless
License: [MIT](https://github.com/ttscoff/mdless/blob/develop/LICENSE)
Build-Style: [RakeFile](https://github.com/ttscoff/mdless/blob/develop/Rakefile)

### PR DESCRIPTION
**Pull request by Anachron**
Closes #19829

### CODE REVIEW

**Comment by Anachron** [comment]
Is there something else I can do to get this merged?

**Comment by Chocimier** [comment]
depends="ruby" at least

**Comment by abenson** [comment]
1.0.13 is out

**Comment by Anachron** [comment]
Forgot about this, will be updating it.

**Comment by abenson** [comment]
Since this is a command, shouldn't the package name just be `mdless`

**Comment by abenson** [comment]
Seemingly abandoned.

**Pull request closed without merging**
