### PR TITLE
[WIP] New package: quilter-2.0.3

### PR DESCRIPTION
**Pull request by NeelChotai**
Quilter is a minimalistic markdown editor built for elementary OS.

### CODE REVIEW

**Comment by Johnnynator** [comment]
Cross compiling is broken. You need at least vala in hostmakedepends. Maybe also some others adjustments.

**Comment by NeelChotai** [comment]
Thanks Johnnynator, added vala to hostmakedepends but the build but armv7l and aarch64 keep failing with a `glib-compile-resources` not found error. Couldn't find anything on the package's GitHub so I've tried a few variants of glib and libglib but none seem to be fitting the bill.

**Comment by Johnnynator** [comment]
add `build_helper="gir". It should take

**Comment by NeelChotai** [comment]
I can't seem to figure out why this won't compile for aarch64 and armv*l architectures, I'll revisit this at a later date.

**Pull request closed without merging**
