### PR TITLE
New package: yacy-1.924

### PR DESCRIPTION
**Pull request by jason1987d**
- I tested the changes in this PR: YES

- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): YES

- I built this PR locally for my native architecture, (x86_64-LIBC)

### CODE REVIEW

**Comment by tibequadorian** [comment]
Use rebase instead of merge to keep it one single commit.

**Comment by jason1987d** [comment]
> Use rebase instead of merge to keep it one single commit.

What is the recommended set of commands to do so? I've found documentation on this but it's not removing that merge commit.

**Comment by tibequadorian** [comment]
For updating branches without a merge commit you can use `git pull --rebase upstream master` as described in https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#getting-your-packages-into-void-by-yourself

I recommend reading https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Review by zen0bit — APPROVED** [review]
Looks good to me, tested, builded, using it...

**Pull request closed without merging**
