### PR TITLE
Lightdm gtk greeter settings revbump (Fixes #34692)

### LINKED ISSUE #34692: lightdm-gtk-greeter-settings: Not available for aarch64 (glibc)
### System

* xuname:  
x86_64-glibc system used for the build: *Void 5.15.11_1 x86_64 AuthenticAMD uptodate rrrmFFFFFF*
aarch64-glibc system (RPi 4): *Void 5.10.52_1 aarch64 Unknown uptodate rF*
* package:  
  *lightdm-gtk-greeter-settings-1.2.2_4*

### Expected behavior
Using xbps-install to install the package should work, as the template does not exclude aarch64 and the dependencies can be fulfilled.
### Actual behavior
The package does not exist in the aarch64 (glibc) repo, but everywhere else.
### Steps to reproduce the behavior
* On x86_64 system:
xbps-install -S lightdm-gtk-greeter-settings
Installs fine

* On aarch64 system:
xbps-install -S lightdm-gtk-greeter-settings
*Package 'lightdm-gtk-greeter-settings' not found in repository pool.*

### PR DESCRIPTION
**Pull request by 123randomuser321**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture (x86_64-glibc)
- I built this PR locally for these architectures:
  - aarch64-glibc (cross on x86_64-glibc host)

#### Why?
- As mentioned in issue #34692 , for some reason the pkg is unavailable for aarch64-glibc, and only for that arch.
- As it builds, this PR should fix this (simple revbump)

### CODE REVIEW

**Comment by Chocimier** [comment]
Should be enough to "touch" template, without revbump. Fix xlint points, leaving real reason in commit message.

**Comment by 123randomuser321** [comment]
Fixed the previous complaints, it does however now complain about a long commit message...

Is the current state sufficient yet?

**Comment by Chocimier** [comment]
Squashed commits for you.

**Comment by 123randomuser321** [comment]
Thanks :)

**Pull request merged**
