### PR TITLE
New package: sfeed_curses-0.9.2

### PR DESCRIPTION
**Pull request by devvesa**

### CODE REVIEW

**Comment by devvesa** [comment]
void-linux package rookie here. When running:

    ./xbps-src pkg sfeed_curses

locally, I get the following:

    => ERROR: sfeed_curses-0.9.2_1: cannot access wrksrc directory [/builddir/sfeed_curses-0.9.2]

I honestly don't know what I am doing wrong. Any help appreciated.

**Comment by ericonr** [comment]
You need to look inside `masterdir/builddir` to see the name of the directory that the tarball was unpacked as, and add `wrksrc=<folder_name>` to the template.

**Comment by devvesa** [comment]
I cleaned that directory and after that I could test locally my changes. Thanks @ericonr

**Comment by sgn** [comment]
Fixed `--no-as-needed` for you

**Pull request closed without merging**
