### PR TITLE
linux4.14: add xhci patch

### PR DESCRIPTION
**Pull request by octoghost**
[ci skip]
https://www.spinics.net/lists/linux-usb/msg168827.html

### CODE REVIEW

**Comment by cr6git** [comment]
`udisksctl power-off --block-device <disk>` ?

hmm... never used this command... let's see what other @void-linux/pkg-committers think about this?

**Comment by cr6git** [comment]
@pullmoll I guess we could wait until tomorrow, when 4.14.57 will be released?

**Comment by octoghost** [comment]
According to this:
https://www.spinics.net/lists/stable/msg248517.html
the patch may be included in the upcoming 4.14.57

**Comment by octoghost** [comment]
#1111

**Pull request closed without merging**
