### PR TITLE
nss: update to 3.61.

### PR DESCRIPTION
**Pull request by sgn**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by sgn** [comment]
The test is being run.

**Comment by ericonr** [comment]
> 			aarch64*|ppc*|x86_64*)

I don't know if this is important, but does this work with the ppcle arch?

@q66

**Comment by sgn** [comment]
@ericonr 
```
coreconf/Linux.mk:52:ifeq (,$(filter-out ppc64 ppc64le,$(OS_TEST)))
```

**Comment by sgn** [comment]
Should be harmless, the `OS_TEST` is used to enable architecture specific optimization, for `ppc` it's `gcm-ppc.c`.
Current setup will use C fallback for ppcle

**Comment by sgn** [comment]
Well, after spending a whole day to figure out what wrong with the build system, now I need to figure out what wrong with the test.

**Comment by sgn** [comment]
Waiting confirmation from https://bugzilla.mozilla.org/show_bug.cgi?id=1689508

Note that Mozilla staff usually build with gyp and their comments in `all.sh` indicates that `chain.sh` is usually not run when built by gyp.

**Comment by sgn** [comment]
As analysed, the failed test is really Mozilla ships broken cert.

**Pull request merged**
