### PR TITLE
New package: sequoia-sq 0.24.0

### PR DESCRIPTION
**Pull request by notramo**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Looks like they don't run tests on 32bit platforms... You should report that upstream. If at all possible, you probably want to use the `cargo` build style, or at least the `rust` build helper.

Cross builds need `rust-std` in `makedepends`.

**Comment by notramo** [comment]
I reported the 32 bit platform issue upstream.
Should I disable these architectures for this version? Or wait until every platform is supported? (They said they can fix the overflow soon, but the other issues are harder to fix.)

**Comment by ericonr** [comment]
Depends, how critical are the issues on 32bit platforms? I'm not sold on inclusion either way...

Regarding the package name, I think the discussion in #21910 was that it should be named sequoia, wasn't it?

**Comment by ericonr** [comment]
Also, add `capnproto` to `hostmakedepends`.

**Comment by notramo** [comment]
It was renamed upstream as the `sq` tool has been released separately. `sequoia` is a larger project of which `sequoia-sq` is just the CLI tool.

**Comment by puzzlewolf** [comment]
Hi @notramo, upstream sequoia here :)

Thanks for packaging `sq` :partying_face:, and reporting the 32-bit test failure :crying_cat_face:!

We released [`sq 0.25.0`](https://gitlab.com/sequoia-pgp/sequoia/-/tags/sq%2Fv0.25.0) two days ago, which includes a fix. We're also working on testing on 32-bit in CI, so this doesn't happen again.

**Pull request closed without merging**
