### PR TITLE
eudev: update to 3.2.12.

### PR DESCRIPTION
**Pull request by mhmdanas**
#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by biopsin** [comment]
Throws a warning, but other then that it works fine
```
=> Starting udev and waiting for devices to settle...
[    3.159618] udevd[703]: specified group 'sgx' unknown
```
from
 ~ $ grep -r "sgx" /usr/lib/udev/
```
/usr/lib/udev/rules.d/50-udev-default.rules:SUBSYSTEM=="misc", KERNEL=="sgx_enclave", GROUP="sgx", MODE="0660"
/usr/lib/udev/rules.d/50-udev-default.rules:SUBSYSTEM=="misc", KERNEL=="sgx_vepc", GROUP="sgx", MODE="0660"
```

**Comment by mhmdanas** [comment]
@biopsin hmm, that happens to me too. Should I add sgx to `system_groups`?

**Comment by biopsin** [comment]
Sounds reasonable to me, its available in kernel 5.11 < from what I randomly skimd

**Comment by mhmdanas** [comment]
Since SGX is an Intel thing, do you think we should create the group only on x86_64? Or does the warning occur on non-x86_64 systems too (e.g. aarch64)? What about i686?

**Comment by biopsin** [comment]
I dont have intel, but I think the warning will show when udev initializes on any arch

**Comment by Duncaen** [comment]
This group does not belong into the eudev package. This should probably be part of base-files.

**Comment by dkwo** [comment]
Somehow base-files did not get revbumped, I still have the udevd warnings.

**Comment by Duncaen** [comment]
Bumped in https://github.com/void-linux/void-packages/commit/c0deef6e20efb7e234f24783de91b9a439a5126d.

**Pull request merged**
