### PR TITLE
[RFC] neovim: remove alternatives.

### LINKED ISSUE #36164: Neovim template should not contest Vim namespace in `alternatives`
**Summary**:

The `neovim` template should not install symlinks contesting the `vim` namespace.

**Reasoning**:

1. No other major OS vendor treats Neovim and Vim in this way.

2. In 2022, anyone choosing to open Neovim instead of Vim, or vice versa, is making a very deliberate choice. Because Neovim supports Lua as a first class citizen, while Vim only supports Vimscript as a first class citizen, Neovim’s plugin ecosystem has begun to differ significantly from Vim’s. The Neovim editor is increasingly configured separately from Vim — often in Lua, and with a different selection of plugins.

3. By default, an unconfigured Neovim severely alters the terminal cursor’s appearance in a manner which is difficult to counteract without ending the active terminal session. Accidentally opening an unconfigured Neovim instance upon typing `vim` into a terminal creates an awful user experience — which is precisely what happens when a user installs Neovim after Vim, due to the `neovim` template’s use of `alternatives`.

I’ve been using Vim and Neovim both for a good, long while. To any Neovim fans, I wouldn’t have opened this issue if I didn’t want both programs installed simultaneously. But If I’m typing `vim` in my terminal, I’m most definitely not expecting Neovim to pop open. Type `vim`, and “the” Vim should open, or an error message should appear. At present, due to the `neovim` template’s use of `alternatives`, when you type `vim`, `nvim` pops open instead, and the terminal cursor’s appearance is ruined until you exit the terminal session.

### PR DESCRIPTION
**Pull request by atweiden**
Closes #36164

#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Review by Duncaen — COMMENTED** [review]
I don't think the given reasons warrant the removal of alternatives, its a choice the user can take.

If we have bash as sh and vim as vi, plocate as locate we can have neovim as vim.

**Comment by atweiden** [comment]
> If we have bash as sh and vim as vi

If Neovim can be Vim, Bash can be Dash.

```bash
# Template file for 'dash'
alternatives="
 sh:sh:/usr/bin/dash
 sh:sh.1:/usr/share/man/man1/dash.1"

# Template file for 'bash'
alternatives="
 sh:sh:/usr/bin/bash
 sh:sh.1:/usr/share/man/man1/bash.1"

# Template file for 'neovim'
alternatives="
  vi:vi:/usr/bin/nvim
  vi:vi.1:/usr/share/man/man1/nvim.1
```

The above would be logically consistent.

**Comment by Duncaen** [comment]
Making dash bash breaks all scripts with bash shebang, installing nvim before vim makes it the default provider for the vim alternative group which you can easily fix and doesn't break half the system, all it does is make the cursor werid on your system.

**Comment by atweiden** [comment]
> There would be no point in alternatives, if the requirement would be that they are 100% compatible

That’s fair, but what if we just did away with the symlink to `vim`? Neovim can have the `vi` symlink, and the result would be equal to how `alternatives` is handled in the shells.

It violates user expectation for `vim`, when typed out on any terminal in any circumstance, to *ever* result in Neovim being opened, unless the environment is specifically configured for such a thing.

IIRC, Void isn’t the only distro which symlinks `dash` to `/bin/sh`. Void, however, *is* (literally) the only distro which symlinks `nvim` to `vim`. It makes about as much sense as symlinking `bash` to `dash`.

**Comment by paper42** [comment]
> > There would be no point in alternatives, if the requirement would be that they are 100% compatible
> 
> That’s fair, but what if we just did away with the symlink to `vim`? Neovim can have the `vi` symlink, and the result would be equal to how `alternatives` is handled in the shells.

I already explained in https://github.com/void-linux/void-packages/issues/36164#issuecomment-1068583988 why this is not without a problem. Having vim point to nvim can only happen in specific circumstances:
a) you manually modified alternatives
b) you installed neovim first

`b` can be a bit surprising, but it doesn't matter, people often don't even notice they are using nvim and not vim. 

> It violates user expectation for `vim`, when typed out on any terminal in any circumstance, to _ever_ result in Neovim being opened, unless the environment is specifically configured for such a thing.

And as we already discussed, it doesn't matter to regular users. neovim and vim are basically drop in replacements of each other.

**Comment by atweiden** [comment]
Yesterday, I suggested [doing](https://github.com/void-linux/void-packages/pull/36165#issuecomment-1068754834):

```bash
# Template file for 'dash'
alternatives="
 sh:sh:/usr/bin/dash
 sh:sh.1:/usr/share/man/man1/dash.1"

# Template file for 'bash'
alternatives="
 sh:sh:/usr/bin/bash
 sh:sh.1:/usr/share/man/man1/bash.1"

# Template file for 'neovim'
alternatives="
  vi:vi:/usr/bin/nvim
  vi:vi.1:/usr/share/man/man1/nvim.1
```

I’ve updated the PR accordingly, to minimize any confusion.

I simply don’t recognize any level of logical consistency in the way Neovim is allowed to easily override `vim` on Void systems. There is no logical difference between allowing this and allowing `bash` to override `dash`. It’s simply not what most users want or expect, edge cases from Debian aside.

**Comment by Vaelatern** [comment]
I think this is wrong. :+1: for closing.

**Comment by paper42** [comment]
I agree with @Vaelatern and because there 3 team members agree on this, I am closing this PR.

**Pull request closed without merging**
