### PR TITLE
base-files: add MPL-2.0 to licenses

### PR DESCRIPTION
**Pull request by classabbyamp**
isn't `vlicense`d but per the terms should probably be included

### CODE REVIEW

**Comment by mobinmob** [comment]
I know this is not the issue tracker, but please consider adding hostname and os-release to this package. Maybe also rc.conf and rc.local...
These are all in runit-void.

**Comment by mobinmob** [comment]
bump?

**Review by leahneukirchen — APPROVED** [review]

**Comment by classabbyamp** [comment]
> bump?

I've wanted to do more with this pr but haven't had the time yet

**Comment by mobinmob** [comment]
> > bump?
> 
> I've wanted to do more with this pr but haven't had the time yet

Well, time is in short supply :)

**Pull request merged**
