### PR TITLE
New package: io.elementary.files-4.0

### PR DESCRIPTION
**Pull request by CameronNemo**

### CODE REVIEW

**Comment by maxice8** [comment]
It provides header files and libraries, shouldn't it have a -devel package ?

**Comment by maxice8** [comment]
It provides header files and libraries, shouldn't it have a -devel package ?

**Comment by CameronNemo** [comment]
Theoretically something could depend on the library, but I am not sure that anything does right now.

**Comment by maxice8** [comment]
On Wed, Oct 17, 2018 at 05:14:32PM -0700, Cameron Nemo wrote:
> Theoretically something could depend on the library, but I am not sure that anything does right now.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/3860#issuecomment-430832208

Ok but we still need the -devel package for the headers, pkg-config files and library .solink

**Pull request merged**
