### PR TITLE
pinebookpro-kernel: update to 5.10.9, enable instructions deprecated by ARMv8

### PR DESCRIPTION
**Pull request by Skirmisher**
This allows 32-bit userlands to run some older ARMv6/7 binaries, e.g. distributed for Android or Raspberry Pi, plus some game dependencies like FMOD. It mirrors our main arm64 config and is toggleable via sysctl anyway.

At some point we might want to review the rest of the config to bring it more in line with the generic arm64 kernel package (though I don't know how different it is as it stands).

[ci skip]

### CODE REVIEW

**Comment by Piraty** [comment]
@renatoaguiar

**Comment by ericonr** [comment]
@CameronNemo might also be interested

@thypon might want to test to avoid regressions

**Comment by CameronNemo** [comment]
>At some point we might want to review the rest of the config to bring it more in line with the generic arm64 kernel package (though I don't know how different it is as it stands).

The drivers should be quite different. We do not need to build and ship nouveau or amdgpu drivers for this kernel, for instance. Similarly I disabled support for other SoC platforms (broadcom, nvidia, allwinner, etc. soc support). Doing that considerably reduced both build time and package size.

The net and fs options should probably be pretty similar if not identical, though. Maybe we can try using [merge_config.sh](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/scripts/kconfig/merge_config.sh) for that?

**Comment by thypon** [comment]
I would love using the mainline kernel, even if it weight a little bit more

**Comment by CameronNemo** [comment]
built and tested. this PR looks good to me.

**Comment by Skirmisher** [comment]
> I would love using the mainline kernel, even if it weight a little bit more

That is the end goal, yeah, but since full support for the PBP currently requires this many patches on top of mainline, it makes more sense to keep a stripped-down device-specific package for now. Hopefully the larger stuff will be merged in eventually and we can slap the miscellaneous ones into the main package and `replaces=` this one outta here.

> although bumping to 5.10.9 is nice


Done.

**Comment by ericonr** [comment]
Is this going to include #28007 or is that a separate discussion?

**Comment by Skirmisher** [comment]
@ericonr not sure that there's a consensus on that (just looked at it now), so I think bumping this as-is would be best for now.

**Comment by ericonr** [comment]
Please squash the commits into a single one :)

**Comment by ericonr** [comment]
It asked me about

```
*
* Restart config...
*
*
* ARMv8.5 architectural features
*
Branch Target Identification support (ARM64_BTI) [Y/n/?] y
  Use Branch Target Identification for kernel (ARM64_BTI_KERNEL) [Y/n/?] (NEW)
```

during config.

**Pull request merged**
