### PR TITLE
New package: certbot-apache-1.7.0

### PR DESCRIPTION
**Pull request by fufexan**
Cannot be merged until `python3-augeas` is merged.

### CODE REVIEW

**Comment by fosslinux** [comment]
Put both commits in the 1 pr.

**Comment by fufexan** [comment]
@fosslinux You mean also `python3-augeas`?

**Comment by fosslinux** [comment]
Yeah, `python3-augeas` commit should be in this PR, in Void a PR should be self-contained, by that I mean that for an update or new package any other new packages needed should be included in the one PR.

**Comment by fufexan** [comment]
Right. I will fix it in a few hours.

**Comment by ahesford** [comment]
Is this out of date now? #25310 refers to `certbot-apache-1.8.0`.

**Comment by kartikynwa** [comment]
@ahesford Even mine is outdated now. `1.9.0` was rolled out eleven days ago.

**Comment by fufexan** [comment]
I will close this PR and the certbot-nginx one, as @kartikynwa has already updated the packages.

**Pull request closed without merging**
