### PR TITLE
opentyrian: update to 2.1.20221123, adopt

### PR DESCRIPTION
**Pull request by Aicaya**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86_64-musl
  - armv6l (cross)
  - aarch64 (cross)

### CODE REVIEW

**Review by zen0bit — APPROVED** [review]

**Comment by zen0bit** [comment]
bump

**Comment by zen0bit** [comment]
bump

**Comment by Aicaya** [comment]
bump

**Comment by classabbyamp** [comment]
rebase please

**Comment by Aicaya** [comment]
Done

**Comment by classabbyamp** [comment]
create_wrksrc probably isn't needed

**Comment by Aicaya** [comment]
Removed create_wrksrc and fixed build issues.

**Pull request merged**
