### PR TITLE
hexyl: update to 0.5.1

### PR DESCRIPTION
**Pull request by SolitudeSF**

### CODE REVIEW

**Comment by jnbr** [comment]
You could try to update the `nix` crate to a more recent version to fix the build on arm.
Something like `cargo update --package nix --precise 0.14.1` should work.

**Comment by SolitudeSF** [comment]
ah, i searched the nix crate repo some time ago and didnt find anything related to fixing this.

**Comment by jnbr** [comment]
I haven't tried but this should fix it: https://github.com/nix-rust/nix/commit/196b05b5c7be39b73dcadca5457948d807fdf913#diff-6ac51e14ebdd7fcc9ef06ed5b01af902

**Comment by Gottox** [comment]
fixed and merged. Thanks for the update!

**Pull request closed without merging**
