### PR TITLE
[RFC] Change package removal process

### PR DESCRIPTION
**Pull request by jnbr**
This should improve the process of removing packages.
The major benefit over the current method is, that `xbps-install -Su` lists the package as removed instead of updated.

Please comment @void-linux/pkg-committers

### CODE REVIEW

**Comment by jnbr** [comment]
> Shouldn't we prevent users from installing the removed packages?

Yes, I think we should prevent users from installing removed packages by default.
To achieve this, we could add a list of all removed packages as `conflicts` in `removed-packages`.

> Please document how to use it on Manual.md this is blocking

Will do when the general direction is more clear. Let's discuss what to document first.

**Comment by maxice8** [comment]
Commit name is wrong (depen)

**Comment by maxice8** [comment]
Doesn't replaces= and conflicts= not play well? I had poor results when messing with libvpx

**Comment by maxice8** [comment]
Also other base stuff like base-minimal should depend on it.

**Comment by Vaelatern** [comment]
This is interesting! I don't know if abusing packages like this is the right solution, but it's not a terrible one.

**Comment by Chocimier** [comment]
Yes, conflicts= and replaces= in same package make `xbps-install -Su` not pass.

One working solution is to put replaces= into xbps package, to remove packages first, because xbps is installed into separate transaction, and conflicts= into removed-packages.

That's too ugly i guess. What may be acceptable is splitting into removed-packages-replaces and removed-packages-conflicts, then modify xbps to install removed-packages-replaces in sepatate transaction too.

**Comment by maxice8** [comment]
Imo I'd just provide empty subpackages.

**Comment by jnbr** [comment]
With `conflicts` and `replaces` not working together, the only clean way would be to add the removed package to `replaces` in `removed-packages` and clean up the repos regulary - something that doesn't work very well.

I don't think adding more workarounds improves the situation really.

**Comment by Chocimier** [comment]
> I don't think adding more workarounds improves the situation really.

Agree keeping things simple is good.

> clean up the repos regulary - something that doesn't work very well.

We could teach xbps-rindex to remove entry for package based on variable in template. For now repodata keeps entries even for removed and "cleaned" packages like `python3.4-*`.

**Comment by maxice8** [comment]
> We could teach xbps-rindex to remove entry for package based on variable in template.

That sounds wrong, if we are removing a package from index surely we don't want to keep a template around.

I'm semi-happy with the current system, would be nice if we had removed-packages which holds all subpackages that have been removed.

**Comment by Duncaen** [comment]
We could add another key to packages, maybe `replace` or `obsoletes` which acts similar as `replaces` but instead of being transactional it `xbps-install` would search through the repoindex and replace installed packages with the one that has obsoletes set.
This could be used for this package and other cases where we currently use transactional packages.

**Comment by Chocimier** [comment]
> > We could teach xbps-rindex to remove entry for package based on variable in template.
> 
> That sounds wrong, if we are removing a package from index surely we don't want to keep a template around.

I was thinking of having that modified templates temporarily, and removing when changes are apllied to repodata.

@maxice8 Do you want those empty subpackages to guard against installing removed packages, or there are other reasons?

**Pull request closed without merging**
