### PR TITLE
gajim: update to 1.1.0.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by maxice8** [comment]
Mind trying again ?

**Comment by teldra** [comment]
it seems like, nbxmpp has to be > 6.7

**Comment by maxice8** [comment]
Ok one more time.

**Comment by teldra** [comment]
seems to be working!

**Comment by maxice8** [comment]
On Wed, Nov 07, 2018 at 01:57:30AM -0800, Teldra wrote:
> seems to be working!
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/4476#issuecomment-436569041

i'm suprised it was working before it was missing.

python3-nbxmpp
python3-keyring
python3-cssutil

on the dependencies

**Pull request merged**
