### PR TITLE
opentmpfiles: remove package

### PR DESCRIPTION
**Pull request by cassaundra**
Upstream no longer maintained. Also has a privilege escalation vulnerability that will likely not be fixed.

Not depended upon by any other packages.

See also: https://github.com/OpenRC/opentmpfiles/issues/19

### CODE REVIEW

**Comment by cassaundra** [comment]
Although it's not directly depended on by any packages, there are some that have tmpfiles.d entries:
```
$ xlocate /usr/lib/tmpfiles.d
nix-2.11.0_2          /usr/lib/tmpfiles.d/nix-daemon.conf
x2goserver-4.1.0.3_2  /usr/lib/tmpfiles.d/x2goserver.conf
xpra-4.4.3_1          /usr/lib/tmpfiles.d/xpra.conf
```

**Comment by cassaundra** [comment]
> If this pull request is still relevant bump it or assign it.

Still relevant, but low priority, so I'm fine if this dies.

**Comment by Nidrop** [comment]
just discovered that xbps wants to delete opentmpfiles. I don't see systemd-tmpfiles in the repo. What can I use as an alternative?

**Comment by classabbyamp** [comment]
I don't think there is one at this time

**Pull request closed without merging**
