### PR TITLE
zbar: fix qt option handling

### PR DESCRIPTION
**Pull request by hadrianw**
The option in configure is called qt not qt5.

### CODE REVIEW

**Comment by hadrianw** [comment]
Can I do something about ```ERROR: zbar-0.10_7: failed to install 'gettext-devel-0.20.1_1' dependency! (error 19)```?

**Comment by Hoshpak** [comment]
No, this is the outdated docker image on travis. You can either run local builds for the relevant architecture and confirm that it works fine or wait until a commiter finds the time to run local builds and merge it afterwards.

**Comment by hadrianw** [comment]
I successfully built the package with a following script:
```
#!/bin/sh
set -x
set -e

function __BUILD__() {
	git clean -fdx -e /hostdir
	case "$1" in
		i686) bootstrap=i686;;
		*-musl) bootstrap=x86_64-musl;;
		*) bootstrap=x86_64;;
	esac
	shift
	./xbps-src binary-bootstrap "$bootstrap"
	./xbps-src -j4 "$@" pkg zbar
}

wget  -N "https://alpha.de.repo.voidlinux.org/static/xbps-static-latest.x86_64-musl.tar.xz"
mkdir -p xbps
tar xf xbps-static-latest.x86_64-musl.tar.xz -C xbps
export PATH="$PWD/xbps/usr/bin:$PATH"

(cd void-packages && git pull origin master) ||
git clone --depth 1 git@github.com:hadrianw/void-packages.git

cd void-packages

for arch in x86_64 x86_64-musl i686; do
	__BUILD__ "$arch" || failed="$failed $arch"
done
for arch in aarch64 armv7l armv6l-musl aarch64-musl; do
	source "common/cross-profiles/$arch.sh" &&
	__BUILD__ "$arch" -a "$arch" || failed="$failed $arch"
done

echo Failed:$failed
```

I attach the build log.
```hadrian@karton $ ./check.sh &> build.log```
[build.log](https://github.com/void-linux/void-packages/files/3293131/build.log)

**Comment by hadrianw** [comment]
Also successfully built without qt option:
```hadrian@karton $ XBPS_PKG_OPTIONS=~qt ./check.sh &> build-without-qt.log```
[build-without-qt.log](https://github.com/void-linux/void-packages/files/3293381/build-without-qt.log)

**Comment by hadrianw** [comment]
I bumped the revision number.

**Comment by hadrianw** [comment]
For completeness - logs after revision bump.
[build.log](https://github.com/void-linux/void-packages/files/3293436/build.log)
[build-without-qt.log](https://github.com/void-linux/void-packages/files/3293437/build-without-qt.log)

**Pull request merged**
