### PR TITLE
Update Glew to 2.2.0

### PR DESCRIPTION
**Pull request by ericonr**
Currently `clementine` and `opentoonz` are FTBFS. The first one is some missing constants, which I guess we'll have to track down, and the latter needs simple `QPainter` patching, like everything else.

### CODE REVIEW

**Comment by ericonr** [comment]
Also need to drop some noarchs.

**Comment by ericonr** [comment]
@thypon could we updatae clementine to an rc release? Our current releaseis 4 years old. https://github.com/clementine-player/Clementine/releases

**Comment by ericonr** [comment]
Paraview is broken for musl, I didn't attempt to fix.

Clementine is the only one failing to build.

Took the opportunity to update opentoonz as well @bra1nwave

**Comment by pullmoll** [comment]
FWIW I'm working on cegui to integrate `cegui-data` into the main package and fix cross building so the cross packages have `libCEGUIOpenGLRenderer.so` for e.g. TSC to become cross compilable.
You could perhaps change cegui to remove `depends="… cegui-data"` and instead add `replaces="cegui-data"` here.

**Comment by ericonr** [comment]
I'm not sure I understand why the `replaces` line is necessary. Can you show me a branch with these changes applied?

**Comment by pullmoll** [comment]
I have no branch but am working on a clone of master. I'll just push the update(s) once I'm done and you can then update the revbump for cegui.

A replaces is necessary whenever a package vanishes. Existing installations expect to find a former subpackage update and since there will be no `cegui-data` anymore, the replaces tells xbps that it is now contained in the main package.

**Comment by ahesford** [comment]
`replaces` is necessary when merging subpackages because you want the newer combined package to remove old subpackages when upgrading, otherwise XBPS will detect conflicts. See what I did in `python3-matplotlib`.

**Comment by ahesford** [comment]
No problem building or running `endless-sky` with the new `glew`

**Comment by ericonr** [comment]
Clementine launches on musl and glibc; cross compilation for `armv7l-musl` has been tested for all cross packages.

**Comment by hippi777** [comment]
hi folks! :)

does clementine still leak memory? :D i used it for a while some years ago, but it always ate slowly my ram, while i dunno if thats still the case, nor if it only leaks on erroneous tracks or whatever... i would drop it as a favor to its possible users, but its none of my business... :D

**Comment by ericonr** [comment]
Clementine is seg faulting despite having worked previously :D 

Not sure what the proper fix can be.

**Comment by ericonr** [comment]
"It's alive!"

On Wayland, Clementine simply segfaults on musl, on glibc it complains about not knowing the current backend. @Johnnynator have you ever noticed this issue? It does work if I let it choose its backend, so I'd say this PR is ready. It pulls in stuff from #25135 , so imma close that.

**Comment by ericonr** [comment]
Need to fix cross for projectM.

**Pull request merged**
