### PR TITLE
gitlab-runner: update to 15.1.0

### PR DESCRIPTION
**Pull request by TheGejr**
#### Testing the changes
- I tested the changes in this PR: **YES**
- Please note, I have **not** tested the update pattern.

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [x] aarch64-musl
  - [x] aarch64
  - [x] armv7l-musl
  - [x] armv7l
  - [x] i686-musl
  - [x] i686
  - [x] x86_64-musl

### CODE REVIEW

**Comment by classabbyamp** [comment]
this should be a single commit with the message `gitlab-runner: update to 15.1.0.`

**Comment by paper42** [comment]
> Please note, I have not tested the update pattern.

You can easily test it by adding XBPS_UPDATE_CHECK_VERBOSE=yes to etc/conf

**Comment by TheGejr** [comment]
@classabbyamp The commits have now been squashed.

@paper42 I've tested the update pattern, it seems to work. However since it's my first time changing `update` I'm unsure of what output is expected.
Is the output expected to be just a version number (like `15.1.0`) or is the current output alright `found version <a class="item-title ref-name" href="/gitlab-org/gitlab-runner/-/tags/v15.1.0">v15.1.0`

**Comment by TheGejr** [comment]
The update pattern is now working as expected.

**Pull request merged**
