### PR TITLE
linux: update to 6.10.

### PR DESCRIPTION
**Pull request by classabbyamp**
zfs should support it, @abenson does nvidia support it?

### CODE REVIEW

**Comment by abenson** [comment]
Last I checked it was having crashes with 6.10, let me see if I can figure out if I already have the fix.

**Comment by dkwo** [comment]
Maybe at the same time bump mainline to 6.11, which seems to work fine?

**Comment by gc-user** [comment]
If zfs support is a deciding factor, why not wait for 6.12 and zfs to support it?

If my understanding and calculation is correct, it'll be the next LTS kernel.

Usually. when zfs comes out with a new version that supports a "current" kernel, that one falls out of support shortly after and zfs users can decide if they want to keep using an outdated kernel or downgrade to the newest LTS kernel.

But then "linux" would essentially become "linux-lts". On the other hand, there's also "linux-mainline". So, "the current thing" is already covered by that one... Anyway, the kernel between mainline and LTS is a short-lived kernel which doesn't really deserve it's own package (apart from the one with the version number in it, of course) IMHO - if the credo is. "don't use a kernel that is no longer supported".

But I might also be missing something and be totally wrong.

**Comment by onur-ozkan** [comment]
Is there any plan for another bump?

**Comment by classabbyamp** [comment]
sometime soonish

**Pull request closed without merging**
