### PR TITLE
leftwm: update to 0.3.0

### PR DESCRIPTION
**Pull request by uncomfyhalomacro**
#### Testing the changes
- I tested the changes in this PR: **NO**

### CODE REVIEW

**Comment by classabbyamp** [comment]
I think this is an update, not a new package

**Comment by uncomfyhalomacro** [comment]
> I think this is an update, not a new package



> I think this is an update, not a new package

yeah my bad. all good now

**Comment by uncomfyhalomacro** [comment]
@0323pin updated to 0.3.0 now :)

**Comment by 0323pin** [comment]
@uncomfyhalomacro Thanks! 0.3.0 is a big improvement and addresses a number of minor annoyances. Looking forward for it to build and have already updated my config files accordingly.

**Comment by uncomfyhalomacro** [comment]
> @uncomfyhalomacro Thanks! 0.3.0 is a big improvement and addresses a number of minor annoyances. Looking forward for it to build and have already updated my config files accordingly.

it builds correctly without the patches. i just have to commit amend it since it is not supposed to be titled as a new package

**Comment by 0323pin** [comment]
@uncomfyhalomacro I'll wait for it, no worries. Appreciated!
On NetBSD, I'll keep running a build from git-HEAD.

**Comment by 0323pin** [comment]
Anything stopping the merge? This release solves quite a few bugs and drops `chrono` which is outdated and has a known CVE.

**Comment by uncomfyhalomacro** [comment]
> Anything stopping the merge? This release solves quite a few bugs and drops `chrono` which is outdated and has a known CVE.

idk i guess. u can maybe contact the void maintainers.

**Comment by 0323pin** [comment]
> idk i guess. u can maybe contact the void maintainers.

Oh sorry, my question was intended to void maintainers.

**Comment by paper42** [comment]
> Anything stopping the merge?

This update was not tested according to the PR description, otherwise, lgtm.

**Comment by 0323pin** [comment]
> This update was not tested according to the PR description, otherwise, lgtm.

Does it mean it won't be merged until someone tests to build and run?

**Comment by paper42** [comment]
> > This update was not tested according to the PR description, otherwise, lgtm.
> 
> Does it mean it won't be merged until someone tests to build and run?

It was build tested by CI, now someone only needs to run test it. In 99% of cases, the PR author tests the update.

**Comment by 0323pin** [comment]
> > > This update was not tested according to the PR description, otherwise, lgtm.
> > 
> > 
> > Does it mean it won't be merged until someone tests to build and run?
> 
> It was build tested by CI, now someone only needs to run test it. In 99% of cases, the PR author tests the update.

I'm rather short of time but, if no one else does it within a week or so, I'll kick a build on my laptop.

**Comment by uncomfyhalomacro** [comment]
> > This update was not tested according to the PR description, otherwise, lgtm.
> 
> Does it mean it won't be merged until someone tests to build and run?

i will test it in  a day or so. but i have exams and i have to vote tomorrow. sorry. i will try the build it locally as early as possible.

**Comment by 0323pin** [comment]
> > > This update was not tested according to the PR description, otherwise, lgtm.
> > 
> > 
> > Does it mean it won't be merged until someone tests to build and run?
> 
> i will test it in a day or so. but i have exams and i have to vote tomorrow. sorry. i will try the build it locally as early as possible.

No rush, I understand you.

**Comment by 0323pin** [comment]
@uncomfyhalomacro No need to test the pkg, I've done it. Take care and thanks for the update.

@paper42 Built and running on musl x86_64
2022-05-08-211908_1920x1080_scrot

Can this merged now?

**Comment by paper42** [comment]
> @uncomfyhalomacro No need to test the pkg, I've done it. Take care and thanks for the update.
> Can this merged now?

Sure, thank you for testing

@uncomfyhalomacro good luck!

**Comment by 0323pin** [comment]
@paper42 thanks!

**Comment by uncomfyhalomacro** [comment]
> @paper42 thanks!

oh thanks both of u.!

**Comment by 0323pin** [comment]
Any chance to bump this to 0.4.0?
There are major changes, including a built-in hotkey daemon (`lefthk`) and the use of `ron` instead of `toml` for configuration.
I've been running on it for a month or so on NetBSD.
I can test it if someone bumps the template. Thanks

**Comment by uncomfyhalomacro** [comment]
> Any chance to bump this to 0.4.0?
> There are major changes, including a built-in hotkey daemon (`lefthk`) and the use of `ron` instead of `toml` for configuration.
> I've been running it for a month or so on NetBSD.
> I can test it if someone bumps the template. Thanks

yes i will update this later tonight. im waiting for someone to ping me because im too busy huhu.

**Comment by 0323pin** [comment]
@uncomfyhalomacro Thanks, appreciated.
An heads-up, though.
I've [merged](http://mail-index.netbsd.org/pkgsrc-changes/2022/10/02/msg261412.html) 0.4.0 on NetBSD yesterday, and you need to build with the default features off. Default now includes logging using `journald-log`, which is a systemd-thing.
You will need to build with the equivalent of `cargo build --release --no-default-features --features=lefthk,sys-log`, which in NetBSD world translates into:

```
CARGO_NO_DEFAULT_FEATURES=	YES
CARGO_FEATURES+=		lefthk sys-log
```

So, use whatever is the Voids equivalent to that.
Once again, thanks! I maintain well over a hundred packages for NetBSD and have no time to contribute to Void as well. Even if I use it on another machine.

**Pull request merged**
