### PR TITLE
rpi-kernel: update to 5.15.65 [ci skip]

### PR DESCRIPTION
**Pull request by tsjk**
#### Testing the changes
- I tested the changes in this PR: **YES** (on my Raspberry Pi 1 Rev 2)

#### Local build testing
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - armv6l (cross-built)

#### Notes
- Fixes issue #39129
- I  only have an rpi1, and can thus not test the kernel on newer rpis,
  but I did a quick-and-dirty update of those as well, given input that this is desired.

### CODE REVIEW

**Comment by akce** [comment]
This is wonderful, thanks @tsjk! :)

I've tested armv6l rpi-kernel on an rpi 1 model b+ and confirmed that eth0 is working.

I also built and tested armv7l rpi2-kernel on an rpi 3 model b and it is also functional.

I think the `rpi2-kernel` build is already broken. ie, not due to these changes. `xv` is needed for the **install** phase. That might be why my rpi2 device never had an `rpi2-kernel-5.15.61_1` available for upgrade.

I needed to add `xv` to the **hostmakedepends** list. ie,
```diff
diff --git a/srcpkgs/rpi2-kernel/template b/srcpkgs/rpi2-kernel/template
index d8f55ba073..b103b74dcd 100644
--- a/srcpkgs/rpi2-kernel/template
+++ b/srcpkgs/rpi2-kernel/template
@@ -9,7 +9,7 @@ version=5.15.65
 revision=1
 archs="armv7l*"
 wrksrc="linux-${_githash}"
-hostmakedepends="perl kmod uboot-mkimage openssl-devel bc bison flex"
+hostmakedepends="perl kmod uboot-mkimage openssl-devel bc bison flex xz"
 makedepends="ncurses-devel"
 maintainer="Piraty <piraty1@inbox.ru>"
 homepage="http://www.kernel.org"
```
I've looked at the template files for both `rpi-kernel` and `rpi3-kernel` and they both have `xv` in this list so i think it might've been an oversight that it's missing from `rpi2-kernel`.

It's such a small change, any chance you could add a commit for this to this PR @tsjk?

**Comment by tsjk** [comment]
Sure. I missed xz there. The rpi2 template was still at 5.10...

**Comment by akce** [comment]
That explains it then, great stuff @tsjk :)

**Comment by tsjk** [comment]
Thanks. :)
And, fixed.

**Pull request closed without merging**
