### PR TITLE
fatsort: add update file

### PR DESCRIPTION
**Pull request by tibequadorian**

### CODE REVIEW

**Comment by ndowens** [comment]
Closed mine, musl build is fine, only issue that needs to be solved is tests fail, which currently unsure why

**Comment by tibequadorian** [comment]
> Closed mine, musl build is fine, only issue that needs to be solved is tests fail, which currently unsure why

If you've tested it on musl and it worked fine, I think you may just disable testing for musl builds as it gives wrong results...?

**Comment by ndowens** [comment]
> > Closed mine, musl build is fine, only issue that needs to be solved is tests fail, which currently unsure why
> 
> If you've tested it on musl and it worked fine, I think you may just disable testing for musl builds as it gives wrong results...?

It's not just musl test. All non-cross build's test fail as well.

**Comment by sgn** [comment]
Please do NOT randomly remove the broken line when you can build it.
I don't think shipping an application that works with block device and couldn't pass its own test is a good idea.

**Pull request merged**
