### PR TITLE
linux-firmware: update to 20220708.

### PR DESCRIPTION
**Pull request by MouadCharradi**
#### Testing the changes
- I tested the changes in this PR: **NO**

#### Local build testing
- I built this PR locally for my native architecture, x86_64, glibc
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64

### CODE REVIEW

**Comment by dataCobra** [comment]
Hey @MouadCharradi,

what's needed to get this done and merged?

**Comment by dataCobra** [comment]
Hey @ericonr,

the conflict is with `linux-firmware-dvb` which didn't get any updates since 2017-03-29.

Could we get `linux-firmware-dvb` removed to get this firmware merged?

**Comment by MouadCharradi** [comment]
Do you have any idea what the firmware is used for? Because I don't think we can remove it if it might break someone's system who's actually using it

**Comment by paper42** [comment]
> what's needed to get this done and merged? slightly_smiling_face

testing

**Comment by dataCobra** [comment]
I've finally successful tested this PR on 3 different systems.

I've also created a PR #38683 to get rid of the conflicts between the two packages.
 -> (linux-firmware-dvb: remove conflicts with official linux-firmware)

**Comment by MouadCharradi** [comment]
Thank you so much. I have tested on my system as well, no errors reported.

**Comment by biopsin** [comment]
duplicate #37081

**Comment by dataCobra** [comment]
@MouadCharradi, @biopsin is right. This PR should be closed in favor of #37081. Because it is
a duplicate.

**Comment by MouadCharradi** [comment]
Closing.

**Pull request closed without merging**
