### PR TITLE
Revbump shaderc for glslang update, add warning.

### LINKED ISSUE #23095: mpv: vulkan playback broken
### System

* Void 5.4.47_1 x86_64 AuthenticAMD uptodate rrrmFFFFFFFFFFFFFFFF
* mpv-0.32.0_2

### Expected behavior
Video playback with `--gpu-api=vulkan` works.
### Actual behavior
`mpv --no-config --gpu-api=vulkan` either exits with a segmentation fault, or the output window is blue and console output is like this:

```
[vo/gpu/vulkan/libplacebo] [  1] #version 450
[vo/gpu/vulkan/libplacebo] [  2] #define tex1D texture
[vo/gpu/vulkan/libplacebo] [  3] #define tex3D texture
[vo/gpu/vulkan/libplacebo] [  4] #define LUT_POS(x, lut_size) mix(0.5 / (lut_size), 1.0 - 0.5 / (lut_size), (x))
[vo/gpu/vulkan/libplacebo] [  5] layout(location=0) in vec2 vertex_position;
[vo/gpu/vulkan/libplacebo] [  6] layout(location=1) in vec2 vertex_texcoord0;
[vo/gpu/vulkan/libplacebo] [  7] layout(location=1) out vec2 texcoord0;
[vo/gpu/vulkan/libplacebo] [  8] layout(location=2) in vec2 vertex_texcoord1;
[vo/gpu/vulkan/libplacebo] [  9] layout(location=2) out vec2 texcoord1;
[vo/gpu/vulkan/libplacebo] [ 10] layout(location=3) in vec2 vertex_texcoord2;
[vo/gpu/vulkan/libplacebo] [ 11] layout(location=3) out vec2 texcoord2;
[vo/gpu/vulkan/libplacebo] [ 12] void main() {
[vo/gpu/vulkan/libplacebo] [ 13] gl_Position = vec4(vertex_position, 1.0, 1.0);
[vo/gpu/vulkan/libplacebo] [ 14] texcoord0 = vertex_texcoord0;
[vo/gpu/vulkan/libplacebo] [ 15] texcoord1 = vertex_texcoord1;
[vo/gpu/vulkan/libplacebo] [ 16] texcoord2 = vertex_texcoord2;
[vo/gpu/vulkan/libplacebo] [ 17] }
[vo/gpu/vulkan/libplacebo] vk_compile_glsl(gpu, tmp, GLSL_SHADER_VERTEX, params->vertex_shader, &vert): VK_ERROR_INITIALIZATION_FAILED
AV: 00:00:01 / 02:01:45 (0%) A-V:  0.000 Cache: 94s/114MB
[vo/gpu/vulkan/libplacebo] [  1] #version 450
[vo/gpu/vulkan/libplacebo] [  2] #define tex1D texture
[vo/gpu/vulkan/libplacebo] [  3] #define tex3D texture
[vo/gpu/vulkan/libplacebo] [  4] #define LUT_POS(x, lut_size) mix(0.5 / (lut_size), 1.0 - 0.5 / (lut_size), (x))
[vo/gpu/vulkan/libplacebo] [  5] layout(location=0) in vec2 vertex_position;
[vo/gpu/vulkan/libplacebo] [  6] layout(location=1) in vec2 vertex_texcoord;
[vo/gpu/vulkan/libplacebo] [  7] layout(location=1) out vec2 texcoord;
[vo/gpu/vulkan/libplacebo] [  8] layout(location=2) in vec4 vertex_ass_color;
[vo/gpu/vulkan/libplacebo] [  9] layout(location=2) out vec4 ass_color;
[vo/gpu/vulkan/libplacebo] [ 10] void main() {
[vo/gpu/vulkan/libplacebo] [ 11] gl_Position = vec4(vertex_position, 1.0, 1.0);
[vo/gpu/vulkan/libplacebo] [ 12] texcoord = vertex_texcoord;
[vo/gpu/vulkan/libplacebo] [ 13] ass_color = vertex_ass_color;
[vo/gpu/vulkan/libplacebo] [ 14] }
[vo/gpu/vulkan/libplacebo] vk_compile_glsl(gpu, tmp, GLSL_SHADER_VERTEX, params->vertex_shader, &vert): VK_ERROR_INITIALIZATION_FAILED
```
### Steps to reproduce the behavior
Play any video with `--gpu-api=vulkan`

Edit: I think this is caused by glslang updating without updating or rebuilding shaderc. Downgrading to glslang-7.13.3496_1 makes it work again.

### PR DESCRIPTION
**Pull request by ericonr**
Fixes #23095

### CODE REVIEW

**Comment by ericonr** [comment]
I can try an update for shaderc too, just laying out the fix first.

**Comment by ericonr** [comment]
```
=> shaderc-2020.1_1: running do_build ...
[  4%] Check copyright
[  8%] Building CXX object libshaderc_util/CMakeFiles/shaderc_util.dir/src/resources.cc.o
[  8%] Built target shaderc-pkg-config
[  8%] Built target shaderc_combined-pkg-config
[  8%] Built target shaderc_static-pkg-config
/builddir/shaderc-2020.1/libshaderc_util/src/resources.cc:142:6: error: cannot convert '<brace-enclosed initializer list>' to 'bool' in initialization
  142 |     }};
      |      ^
make[2]: *** [libshaderc_util/CMakeFiles/shaderc_util.dir/build.make:148: libshaderc_util/CMakeFiles/shaderc_util.dir/src/resources.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:382: libshaderc_util/CMakeFiles/shaderc_util.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  8%] Built target check-copyright
make: *** [Makefile:161: all] Error 2
```

I don't really want to take the time to fix this build error right now. Consider this ready to merge from my part.

**Comment by travankor** [comment]
Maybe people more familiar with shaderc can update it like @pbui or @st3r4g 

If they're busy, I can look into it, too

**Comment by st3r4g** [comment]
`v2020.1` was released only 12 days ago, so it might rely on some unreleased (still in master) commit of some dependency. I managed to build `v2020.0` by discarding the patches and adding `SPIRV-Headers` in `makedepends`, so we could update to that

**Comment by BouncyMaster** [comment]
> I managed to build `v2020.0` by discarding the patches and adding `SPIRV-Headers` to `makedepends`, so we could update to that

With your suggestion the new version builds successfully, however, when trying to just open `mpv` (without any media) i get this error
```
mpv: symbol lookup error: /usr/lib/libshaderc_shared.so.1: undefined symbol: _ZTVN8spvtools5utils5TimerE
```
below are the changes to the upstream template

```
diff --git a/srcpkgs/shaderc/template b/srcpkgs/shaderc/template
index fc8f7cf20d..1bad658a68 100644
--- a/srcpkgs/shaderc/template
+++ b/srcpkgs/shaderc/template
@@ -1,18 +1,18 @@
 # Template file for 'shaderc'
 pkgname=shaderc
-version=2019.0
-revision=2
+version=2020.0
+revision=1
 wrksrc="shaderc-${version}"
 build_style=cmake
 configure_args="-DSHADERC_SKIP_TESTS=ON"
 hostmakedepends="python3"
-makedepends="SPIRV-Tools-devel glslang-devel"
+makedepends="SPIRV-Tools-devel SPIRV-Headers glslang-devel"
 short_desc="Collection of tools, libraries and tests for shader compilation"
 maintainer="Orphaned <orphan@voidlinux.org>"
 license="Apache-2.0"
 homepage="https://github.com/google/shaderc"
 distfiles="https://github.com/google/shaderc/archive/v${version}.tar.gz"
-checksum=1018cd02be52295272fdbffa056ee24b881be277c83d039ad554d91230f4e11b
+checksum=e02e2a9d4c3960bc629ca8cdcf83d295bec9c80ed08a8c5062e4e294022605ec
 
 CXXFLAGS="-I${XBPS_CROSS_BASE}/usr/include/glslang"
 
@@ -29,8 +29,8 @@ pre_configure() {
 	# need to keep this in sync with glslang and SPIRV-Tools versions
 	# this is displayed with 'glslc --version'
 	cat <<- EOF > glslc/src/build-version.inc
-		"shaderc 2019.0\n"
-		"SPIRV-Tools-2019.2\n"
-		"glslang-7.13.3496\n"
+		"shaderc 2020.0\n"
+		"SPIRV-Tools-2020.3\n"
+		"glslang-8.13.3743\n"
 	EOF
 }
```

**Comment by st3r4g** [comment]
Yeah I know, this means that stuff that depends on `shaderc` (that is `libplacebo` and `mpv`) needs to be rebuilt. However after updating and rebuilding `libplacebo`, if I try to rebuild `mpv` I get this:
```
Checking for libplacebo support                                           : no ('libplacebo >= 1.18.0' not found)
```
and I have no idea why, the pkgconfig file is there...

**Comment by st3r4g** [comment]
ok no the symbol is external, the problem is in the updated `glslang`

**Comment by st3r4g** [comment]
Disregard my previous comment, `mpv: symbol lookup error` was caused by dropping `fix-link-order.patch`, so that should stay. Now `mpv` works, but there are still more `symbol lookup error` in `glslang` itself to fix

**Comment by st3r4g** [comment]
I have no idea how to fix the errors in `ldd /lib/libglslang.so` and `ldd /lib/libHLSL.so`. It's probably an upstream bug, I've spun up an Alpine VM and they have the same errors. I think we can ignore them for now, they are unrelated to this `shaderc` issue (they were present with old `glslang` too).

So, TLDR for @ericonr : update to `v2020.0`, add `SPIRV-Headers` to `makedepends`, keep `fix-link-order.patch`. I would update `libplacebo` too, but I've run into an issue when rebuilding `mpv` (see a previous comment). Alpine has it though, it should be doable...

**Comment by ericonr** [comment]
Does libplacebo need to be at least revbumped because of this mess? Do you want to open another PR to fix it or should I include it here?

**Comment by st3r4g** [comment]
`libplacebo` cannot just be revbumped, it fails to build against current Vulkan headers...

**Comment by st3r4g** [comment]
ok I figured out the `libplacebo` update issue, `libepoxy-devel` was missing in `libplacebo-devel`. Now `mpv` builds. I can open another PR with everything updated

**Comment by ericonr** [comment]
Please do so! I can close this one then.

**Comment by ericonr** [comment]
Closing this one. Thanks @st3r4g !

**Pull request closed without merging**
