### PR TITLE
 mesa: update to 24.1.3, build with llvm18. 

### PR DESCRIPTION
**Pull request by Calandracas606**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86_64-musl
  - i686
  - aarch64 (cross)
  - aarch64-musl (cross)
  - armv7l (cross)
  - armv7l-musl (cross)
  - armv6l (cross)
  - armv6l-musl (cross)

### CODE REVIEW

**Comment by AnInternetTroll** [comment]
Tested Suicide Squad Kill the Justice League, No Man's Sky, Celeste and
Hollow Knight and encountered no issues.

**Comment by SpidFightFR** [comment]
> Tested Suicide Squad Kill the Justice League, No Man's Sky, Celeste and Hollow Knight and encountered no issues.

Hey ! That's some good news.
I Expected nothing more or less from such a version bump on the mesa side.
However, the LLVM side worried me a tiny bit.
Did you notice any stuttering or nothing at all ?

**Comment by AnInternetTroll** [comment]
No, not at all. If anything it ran better, but take that with a grain of
salt ;)

**Comment by Calandracas606** [comment]
> However, the LLVM side worried me a tiny bit.
Thats the main concern, although the jump from 17 -> 18 seems to be relatively minor, at least compared to previous updates (removal of opaque pointers caused a lot of breakage), so far all the packages that I've tested on llvm17, also work on llvm18 without any patching, although I haven't tried them all

**Pull request merged**
