### PR TITLE
dbus-elogind: remove package, migrate to regular dbus

### PR DESCRIPTION
**Pull request by ahesford**
`dbus-elogind` adds a patch that enabled `dbus` to query elogind to determine whether the current user is seated at a physical console. Without this, there are a few fallbacks that seem not to be enabled or supported in our `dbus` package, so `dbus` just assumes that no user is "at the console".

It seems the only consumer of this is a `connman` policy at `/usr/share/dbus-1/systemd/connman-nmcompat.conf` that, based on the file name, allows connman to respond to messages for `org.freedesktop.NetworkManager` originating from users physically at the console.

This package adds maintenance burden (we have to keep this in sync with `dbus` and have to duplicate services and `INSTALL` scripts) and, in at least one case a few years ago, a user was bitten when a newer `dbus-libs` was somehow installed alongside a `dbus-elogind` package that hadn't been updated, breaking the installation. There is too much confusion for essentially zero benefit, so let's just drop this version and push people to the standard packages.

I still need to test the upgrade path with the elimination of `provides` and `replaces` and the addition of `depends`.

### CODE REVIEW

**Comment by Duncaen** [comment]
I forgot about `/etc/dbus-1/system.d/` there are a few more packages that use `at_console` there.
```
xbps-query -R --cat /etc/dbus-1/system.d/org.neard.conf neard-0.18_2
xbps-query -R --cat /etc/dbus-1/system.d/org.neard.se.conf neard-0.18_2
xbps-query -R --cat /etc/dbus-1/system.d/ofono.conf ofono-1.31_3
xbps-query -R --cat /etc/dbus-1/system.d/wicd.conf wicd-1.7.4_8
```

**Comment by ahesford** [comment]
It looks like `wicd` is on life support and users probably ought to find a better supported network manager anyway. I have no idea how much of an inconvenience this change would pose for users of `neard` or `ofono`; no installations of these packages are currently registered with popcorn.

**Comment by ahesford** [comment]
The compatibility problems are worse than I thought, because `xbps-install dbus-elogind` will pull in the standard `dbus-libs` by default. Not only does that increase the likelihood that a mismatched `dbus` update will break users of `dbus-elogind`, but it also means that there are probably a number of users who installed `dbus-elogind` but don't even get the benefit of the patched `at_console` behavior!

**Comment by ahesford** [comment]
OK, the upgrade path is broken: even though the new `dbus-elogind` no longer provides `dbus`, XBPS sees the currently installed version as providing the needed dependency for the upgraded package's new dependency. I've worked around this by bumping `dbus` and adding a strict minimum version in the new dummy package. This seems to do the right thing for full-system upgrades as well as an explicit `xbps-install -u dbus-elogind` even when `dbus-libs` was pulled in by default.

**Review by Duncaen — APPROVED** [review]

**Pull request closed without merging**
