### PR TITLE
webkit2gtk: fix arm*

### PR DESCRIPTION
**Pull request by pullmoll**
Replace std::max() with a ternary conditional.
Work around this gcc bug:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70124

[ci skip]

Of course it would be good if someone with armv7 hardware could test run `jsc`.

### CODE REVIEW

**Comment by maxice8** [comment]
i believe @newbluemoon has armv7 hardware

**Comment by pullmoll** [comment]
The armv7l and armv7l-musl webkit2gtk-2.22.0_1 pkgs are available at https://repo.voidlinux.de/current

**Comment by newbluemoon** [comment]
Tested `jsc` on armv7l-musl, but I’m afraid it’s not working:
```
a=1
>>> 1
b=2
>>> 2
a+b
>>> Exception: RangeError: Maximum call stack size exceeded.
```

Also tested it with surf. E.g. the forum doesn’t load, it just remains a white page.

**Comment by pullmoll** [comment]
Ok, thanks @newbluemoon so the fix is wrong. I'll look out for how other projects handle arm* for webkit2gtk.

**Comment by pullmoll** [comment]
Ok, rebuilt webkit2gtk-2.22.0_1 for armv[56]{,-musl} and uploaded the pkgs again.
It'd be great if you could test again @newbluemoon .

**Comment by newbluemoon** [comment]
Sorry, but same result. :( Took extra care not to reinstall/use the same (old) version.

**Comment by pullmoll** [comment]
Hmm.. this leaves me baffled. I wonder if/why the Debian unstable for armv7l then works.
Or perhaps this is, again, a problem of musl, not webkit2gtk.

**Comment by newbluemoon** [comment]
I double checked that I’m really using your latest build, not the cached former one. But I have also an armv7l (glibc) installation (I rarely use). Let me bring it up to date and test there. Maybe it is a musl issue...

**Comment by pullmoll** [comment]
I'd really like to know why we face so many troubles with musl libc. Is this all due to the tight stack/heap space or is there another hidden problem with data types or structures. It's annoying to always run against these brick walls :P

**Comment by pullmoll** [comment]
And another try for armv7l-musl with patches devised by peeking at Alpine's patch set for musl for 2.20.3 is uploaded.

**Comment by newbluemoon** [comment]
It works! :)

**Comment by pullmoll** [comment]
Fine, whoever feels the urge to merge this, please do.. I'm taking a break.

**Pull request closed without merging**
