### PR TITLE
readline: update to 8.0.000.

### PR DESCRIPTION
**Pull request by maxice8**
- [x] yoshimi
- [x] yaz
- [x] xorriso
- [x] xfsprogs
- [x] wpa_supplicant
- [x] wcalc
- [x] virtuoso
- [x] vice
- [x] varnish
- [x] util-linux
- [x] unixodbc
- [x] units
- [x] udftools
- [x] tftp-hpa
- [x] swi-prolog
- [x] sqlcipher
- [x] socat
- [x] slurm-wlm
- [x] sdcv
- [x] scanmem
- [x] samba
- [x] ruby
- [x] rlwrap
- [x] renameutils
- [x] rc
- [x] qalculate
- [x] python3
- [x] python
- [x] profanity
- [x] postgresql
- [x] pilot-link
- [x] php
- [x] perl-Term-ReadLine-Gnu
- [x] pcre2
- [x] parted
- [x] opensc
- [x] octave
- [x] nickle
- [x] ngspice
- [x] nftables
- [x] newlisp
- [x] ncmpcpp
- [x] mvwm-git
- [x] mspdebug
- [x] mozjs60
- [x] mozjs52
- [x] monero
- [x] minitalk
- [x] mdbtools
- [x] lvm2
- [x] lua52
- [x] lua51
- [x] lua
- [x] lnav
- [x] libxml2
- [x] libvirt
- [x] libgda
- [x] lftp
- [x] ldapvi
- [x] kid3
- [x] jack
- [x] iwd
- [x] inetutils
- [x] hstr
- [x] hamlib
- [x] guile1.8
- [x] guile
- [x] gsasl
- [x] gphoto2
- [x] gnupg2
- [x] gnupg
- [x] gnuchess
- [x] gnubg
- [x] glusterfs
- [x] gjs
- [x] giac
- [x] genius
- [x] gdb
- [x] gawk
- [x] fvwm
- [x] freetds
- [x] freeciv
- [x] fontforge
- [x] folks
- [x] fluidsynth
- [x] fcron
- [x] eukleides
- [x] es
- [x] edbrowse
- [x] connman
- [x] cjs
- [x] cgdb
- [x] cdecl
- [x] canto-curses
- [x] cadaver
- [x] bluez
- [x] bird
- [x] bind
- [x] bcal
- [x] bc
- [x] augeas
- [x] atari800
- [x] android-file-transfer-linux
- [x] abook
- [x] R
- [x] NetworkManager
- [x] MEGAcmd
- [x] iverilog
- [x] grv

### CODE REVIEW

**Comment by maxice8** [comment]
I'm doing x86_64 builds, feel free to do cross

**Comment by maxice8** [comment]
v8 fails

**Comment by jnbr** [comment]
distfiles for pilot-link are not available

**Comment by jnbr** [comment]
lnav fails in configure for aarch64

**Comment by jnbr** [comment]
samba failed to build on armv6

**Comment by maxice8** [comment]
edbrowse should be fixed

**Comment by maxice8** [comment]
cjs

configure:17032: g++ -std=gnu++11 -c -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -I/usr/     include/glib-2.0 -I/usr/lib/glib-2.0/include conftest.cpp >&5
1553 conftest.cpp:45:10: fatal error: js-config.h: No such file or directory
1554  #include <js-config.h>
1555           ^~~~~~~~~~~~~
1556 compilation terminated.
1557 configure:17032: $? = 1
1558 configure: failed program was:

**Comment by maxice8** [comment]
glusterfs is fixed.

cjs and v8 remain

**Comment by maxice8** [comment]
lnav works on aarch64-musl if the host is also musl.

**Comment by maxice8** [comment]
samba is working here

**Pull request merged**
