### PR TITLE
New package: wxPython4-4.0.3

### PR DESCRIPTION
**Pull request by Gigahawk**

### CODE REVIEW

**Comment by Gigahawk** [comment]
I've set it to `nocross` for now, not sure if I should be using `only_for_archs` instead because cross building for i686 and x86_64-musl are working fine on my machine.

**Comment by Gigahawk** [comment]
The devel subpackage is left out for now, as far as I can tell wxPython4 doesn't seem to come with development files. I can't seem to find development pacakges in other package manager repositories either.

**Comment by Hoshpak** [comment]
This seems strange to me. The comm/shlibs entries look like the package includes wxgtk3. Wouldn't it make more sense to package wxgtk3 separately and then build the python package on that? Arch builds wxWidgets for gtk2 and gtk3 from the same source package. Perhaps it would be in order to rework our wxWidgets package to provide both. The package name makes sense considering that it is incompatible with the previous version but I wonder if it wouldn't be better to prefix it with `python[3]-` like it is done with most python packages.

Considering that wxPython also supports gtk2 and python2 maybe it would be a good idea to include that too or is it reasonable to assume that all applications wanting to use either python2 or gtk2 will stick to the old version?

**Comment by Gigahawk** [comment]
wxPython4 does seem to offer a flag to force gtk2 compilation, should I just enable that?

**Comment by Hoshpak** [comment]
I've prepared a PR for wxgtk3 in the meantime at #2433 . Please wait for this to be merged and build on top of that.

**Comment by Gigahawk** [comment]
I'm guessing I've done something wrong, it appears that wxPython is still compiling with some other wxgtk as opposed to the one you've provided given that it seems to provide a lot of shlibs not found from #2433.

**Comment by Hoshpak** [comment]
There are two modifications that need to be done to compile against the
system wxWidgets instead of building the bundled one:

THe `build.py` script looks for `wx-config`, to avoid a conflict with
the gtk2 wxWidgets package, the script in the gkt3 package is called
`wx-config-gtk3`. This needs to be changes in `build.py` either by
patching the file or replacing with sed.

Furthermore, `build.sh` needs to be passed `--use_syswx`. Since setup.py
seems to offer no options to pass arguments to build.py, I think it is
necessary to call the build.py script directly.

Please also check the `makedepends`. There's a good chance many of them
are not needed any more when the template does not build the complete
wxWidgets itself. Also, please avoid compiling against `SDL` and
`webkitgtk`. `SDL2` and `webkit2gtk` can be used instead.

**Comment by maxice8** [comment]
ping

@Hoshpak is it ok ?

**Comment by Hoshpak** [comment]
It is missing `pycompile_module`, otherwise it looks good to me.

**Pull request closed without merging**
