### PR TITLE
Rust 1.76

### PR DESCRIPTION
**Pull request by tranzystorekk**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by tranzystorekk** [comment]
Results of `build_style=cargo` rebuild for x86_64-gnu:

## New failures since 1.75

### std headers not found by bindgen

- `conduit` https://0x0.st/HdAE.txt cc @TinfoilSubmarine
- `helvum` https://0x0.st/HdAl.txt cc @0x5c
- `openpgp-ca` https://0x0.st/HdA0.txt cc @jcgruenhage
- `openpgp-card-tools` https://0x0.st/HdAk.txt cc @jcgruenhage

### libclang-cpp17 invalid

- `sequoia-sop` https://0x0.st/HdAn.txt
- `sequoia-sq` https://0x0.st/HdA7.txt
- `sequoia-sqv` https://0x0.st/HdAh.txt

cc @jcgruenhage

### failed to compile rustc-serialize

- `fool` https://0x0.st/HdAI.txt cc @wpbirney
- `spotify-tui` https://0x0.st/Hdms.txt cc @abenson
- `spotifyd` https://0x0.st/Hdmi.txt cc @abenson

## Known failures

- `ion`
- `lapce`
- `wasmtime`

**Comment by wpbirney** [comment]
Upstream for `fool` has not seen any commits for 6 years now. Probably not worthwhile to keep in repo

https://github.com/spacekookie/fool

**Comment by TinfoilSubmarine** [comment]
`conduit` failure isn't caused by 1.76, I can reproduce when building it with 1.75 on my machine. Looking into it...

**Comment by tranzystorekk** [comment]
`conduit` is likely caused by the llvm17 update, there are other known packages failing, we probably have to wait for the fix to get merged

**Comment by classabbyamp** [comment]
are the llvm-related fails fixed now?

**Comment by tranzystorekk** [comment]
just checked fresh master, only `sequoia-sqv` fails now, but the cause is not related to llvm: https://0x0.st/HdhH.log

**Pull request merged**
