### PR TITLE
Update to Electrum 4.1.1

### PR DESCRIPTION
**Pull request by ar-jan**
#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
  Electrum works for me, I don't use aiorpcx independently.
- [ ] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, x86_64.
- [ ] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [ ] aarch64-musl
  - [ ] armv7l
  - [ ] armv6l-musl

### CODE REVIEW

**Comment by ar-jan** [comment]
Tests are failing for `aiorpcx` on some arches, presumably because IPv6 is not enabled there (I had the same issue locally and it was solved by enabling IPv6). Presumably IPv6 can/should work on test runners as well?

**Comment by ar-jan** [comment]
Question: `uvloop` is needed to pass tests. Afaict it's not a requirement, so not needed in `depends`?

**Comment by ericonr** [comment]
@ar-jan you can put it in `checkdepends`

**Comment by ar-jan** [comment]
> @ar-jan you can put it in `checkdepends`

I did, I meant I wasn't sure if it's *only* required for the tests but I think so, the asyncio stuff is optional.

The current test failures are only due to IPv6 issue on the test runner, they pass locally.

**Pull request merged**
