### PR TITLE
New package: libdpp-10.0.15

### PR DESCRIPTION
**Pull request by JuniorSuperTux**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by classabbyamp** [comment]
previous PR: https://github.com/void-linux/void-packages/pull/37554

**Comment by JuniorSuperTux** [comment]
How long does it usually take for pull requests of new packages to be merged? Because it just had a new release

**Comment by JuniorSuperTux** [comment]
Are there any procedures I'm lacking? Or are there some issues that needs to be fixed?

**Comment by OoLunar** [comment]
Reopened by my request only to realize that I should open a new PR since I don't have write access to the PR and we're adding a different (newer) version. Apologies for the unnecessary notifications

**Pull request closed without merging**
