### PR TITLE
e2fsprogs: update to 1.47.0, add fuse-devel to makedepends, split fus…

### PR DESCRIPTION
**Pull request by dkwo**
…e2fs subpkg

- I tested the changes in this PR: no
- I built this PR locally for my native architecture, (x86_64-musl)

fixes https://github.com/void-linux/void-packages/issues/42150 @Gottox @danjenson

### CODE REVIEW

**Comment by JamiKettunen** [comment]
Certainly helped me with fixing this ;)
```
e2fsck 1.46.5 (30-Dec-2021)
<DEV> has unsupported feature(s): FEATURE_C12
e2fsck: Get a newer version of e2fsck!

<LABEL>: ********** WARNING: Filesystem still has errors **********
```

**Comment by paper42** [comment]
This will break grub-install because it adds a new default option metadata_csum_seed to mkfs.ext4 which doesn't work with current grub.

**Comment by dkwo** [comment]
Should I patch grub as e.g. Debian does?

**Comment by dkwo** [comment]
perhaps add to grub these two patches from Alpine https://git.alpinelinux.org/aports/tree/main/grub/xx-e2fsprogs-1.patch https://git.alpinelinux.org/aports/tree/main/grub/xx-e2fsprogs-2.patch ?

**Comment by paper42** [comment]
yes, please do

**Comment by dkwo** [comment]
done. i don't use grub, so someone should test.

**Comment by JamiKettunen** [comment]
Any testers to get this going forward? I'm using F2FS so I can't test the GRUB thing (except maybe in a VM but then anyone else could do it too), otherwise I've required this to properly work with [`pmbootstrap`](https://git.sr.ht/~postmarketos/pmbootstrap) ext4 rootfs image generation for a while now and haven't noticed anything out of the ordinary otherwise

**Comment by piso77** [comment]
$ xbps-query -s grub
[*] grub-2.06_2            GRand Unified Bootloader 2
[*] grub-i386-efi-2.06_2   GRand Unified Bootloader 2 - i386 EFI support
[*] grub-x86_64-efi-2.06_2 GRand Unified Bootloader 2 - x86_64 EFI support

Is this the grub version to test?
Other than building 2fsprogs and installing it, what should i test?

**Comment by dkwo** [comment]
@piso77 you should test this pr, both grub and e2fsprogs, not the ones in the repo.

**Comment by dkwo** [comment]
i guess a proper test would be e.g. create a new boot partition with this and check that grub works

**Comment by piso77** [comment]
e2fsprogs built fine, grub on the other hand:

...
=> grub-2.06_3: installing host dependencies: python3-3.11.3_1 pkg-config-0.29.2_3 flex-2.6.4_3 freetype-devel-2.13.0_1 font-unifont-bdf-15.0.01_1 help2man-1.49.2_1 automake-1.16.5_1 gettext-devel-tools-0.21_4 ...
=> grub-2.06_3: installing target dependencies: libusb-compat-devel-0.1.8_1 ncurses-devel-6.3_3 freetype-devel-2.13.0_1 liblzma-devel-5.4.3_1 device-mapper-devel-2.02.187_2 fuse-devel-2.9.9_1 ...
=> grub-2.06_3: removing autodeps, please wait...
=> ERROR: grub-2.06_3: failed to install target dependencies! (error 19)
Package `freetype-devel-2.13.0_1' already installed.
ncurses-libs-6.3_3 in transaction breaks installed pkg `ncurses-6.4_1'
Transaction aborted due to unresolved dependencies.
=> ERROR: Please see above for the real error, exiting...

$ git lg --oneline
a6474c0bf6 (HEAD, e2fs-fix/e2fs) grub: patch for e2fsprogs
2478716a6b e2fsprogs: update to 1.47.0, add fuse-devel to makedepends, split fuse2fs subpkg
...

**Comment by dkwo** [comment]
Simply rebasing should fix that.

**Pull request merged**
