### PR TITLE
purple-plugin-pack: update to 2.8.0 and orphan, pidgin: update to 2.14.12.

### PR DESCRIPTION
**Pull request by mhmdanas**
#### Testing the changes
- I tested the changes in this PR: **NO**

@leahneukirchen

### CODE REVIEW

**Comment by leahneukirchen** [comment]
I don't use this anymore, can't test either.

**Comment by mhmdanas** [comment]
Hmm, too bad, should I orphan the package then?

**Comment by classabbyamp** [comment]
I tested this (along with a pidgin update that python3ises it) with a random selection of plugins and it seems to work

```diff
From a49f01c8a7e34167d80232a7ed06d0faa08c9310 Mon Sep 17 00:00:00 2001
From: classabbyamp <void@placeviolette.net>
Date: Sun, 8 Oct 2023 01:37:31 -0400
Subject: [PATCH] pidgin: update to 2.14.12.

---
 srcpkgs/pidgin/template | 23 +++++++++++------------
 1 file changed, 11 insertions(+), 12 deletions(-)

diff --git a/srcpkgs/pidgin/template b/srcpkgs/pidgin/template
index 51401d93aa1..751089a62f4 100644
--- a/srcpkgs/pidgin/template
+++ b/srcpkgs/pidgin/template
@@ -1,7 +1,7 @@
 # Template file for 'pidgin'
 pkgname=pidgin
-version=2.14.10
-revision=2
+version=2.14.12
+revision=1
 build_style=gnu-configure
 configure_args="--disable-schemas-install --disable-meanwhile
  --enable-cyrus-sasl --disable-doxygen --enable-nm --enable-vv
@@ -10,22 +10,21 @@ configure_args="--disable-schemas-install --disable-meanwhile
  --with-ncurses-headers=${XBPS_CROSS_BASE}/usr/include
  --with-avahi-client-includes=${XBPS_CROSS_BASE}/usr/include
  --with-avahi-client-libs=${XBPS_CROSS_BASE}/usr/lib"
-short_desc="Multi-protocol instant messaging client"
-maintainer="Orphaned <orphan@voidlinux.org>"
-license="GPL-2.0-or-later"
-homepage="https://pidgin.im/"
-distfiles="${SOURCEFORGE_SITE}/pidgin/pidgin-${version}.tar.bz2"
-checksum=454b1b928bc6bcbb183353af30fbfde5595f2245a3423a1a46e6c97a2df22810
-python_version=2
-lib32disabled=yes
-
 hostmakedepends="pkg-config intltool automake libtool gettext gettext-devel glib-devel"
 makedepends="evolution-data-server-devel libglib-devel gtk+-devel libXext-devel
  libXScrnSaver-devel gtkspell-devel startup-notification-devel ncurses-devel
- libxml2-devel gst-plugins-base1-devel libidn-devel python-devel
+ libxml2-devel gst-plugins-base1-devel libidn-devel python3-devel
  avahi-glib-libs-devel dbus-glib-devel NetworkManager-devel nss-devel
  libsasl-devel libSM-devel farstream-devel libgnt-devel"
 depends="cyrus-sasl-modules gst-plugins-good1"
+short_desc="Multi-protocol instant messaging client"
+maintainer="Orphaned <orphan@voidlinux.org>"
+license="GPL-2.0-or-later"
+homepage="https://pidgin.im/"
+distfiles="${SOURCEFORGE_SITE}/pidgin/pidgin-${version}.tar.bz2"
+checksum=2b05246be208605edbb93ae9edc079583d449e2a9710db6d348d17f59020a4b7
+python_version=3
+lib32disabled=yes
 
 CFLAGS="-Wno-deprecated-declarations"
 
-- 
2.42.0

```

**Comment by mhmdanas** [comment]
@classabbyamp thanks, pushed your patch.

**Pull request merged**
