### PR TITLE
New package: dot-0.1.4

### PR DESCRIPTION
**Pull request by liketechnik**
`dot` is a command-line tool for managing dotfiles, written in Rust.
Homepage: https://github.com/ubnt-intrepid/dot

### CODE REVIEW

**Comment by pullmoll** [comment]
Note that `/usr/bin/dot` is a binary contained in the package `graphviz` so you either have to conflict with that package, or rename the `dot` binary to e.g. `dot-rust` or similar.

**Comment by xtraeme** [comment]
ENOWAY

**Comment by liketechnik** [comment]
Thanks for the info, I didn't know this explicitly. Imo it would be more sensible to rename the binary into `dot-rust`/`dot-rs`, because `graphviz` is not that uncommon.

**Comment by abenson** [comment]
Any update on fixing the rename?

**Comment by liketechnik** [comment]
Sorry, I forgot to push my local changes after I ran into the exact issue mentioned above. I hope the way I'm now doing the rename (during `post_install` with a simpe `mv ...`) is acceptable.

I also found the related issue in the mean-time (don't know why I overlooked it back when I opened this issue) at https://github.com/ubnt-intrepid/dot/issues/14 which states that the author intends to change name. Would that have any implications for this package?

**Comment by abenson** [comment]
Renaming like that is fine. I would prefer to wait until the rename if there is going to be one. I'd bump that issue and see if there's a timescale planed for the rename.

**Comment by abenson** [comment]
Seemingly abandoned.  We can re-approach when upstream makes a decision.

**Pull request closed without merging**
