### PR TITLE
gandi-cli: remove package.

### PR DESCRIPTION
**Pull request by Goorzhel**
Upstream archived August 2021.

Follows from https://github.com/void-linux/void-packages/pull/37629#issuecomment-1165840400.

cc: @paper42 @lonwillett

### CODE REVIEW

**Comment by Goorzhel** [comment]
No dependencies:
```
❯ git l | head -2
a77c1d6f9f gandi-cli: remove.
d06dd0d007 wf-recorder: update to 0.3.0.
❯ ag gandi-cli srcpkgs
srcpkgs/removed-packages/template
84: gandi-cli<=1.6_2
```

**Comment by sgn** [comment]
What is `git l`?

**Comment by Goorzhel** [comment]
Whoops, I usually remember to substitute aliases:
```
❯ git config alias.l
log --oneline
```

**Comment by paper42** [comment]
The commit message is usually `$pkgname: remove package`, could you change it?

**Pull request merged**
