### PR TITLE
libgit2: update to 0.27.3.

### PR DESCRIPTION
**Pull request by Gigahawk**

### CODE REVIEW

**Comment by maxice8** [comment]
requires rebuild of various things. use `xrevshlib libgit2` and bump their revision, make sure all of them work, libgit2-glib is notorious for breaking like that

**Comment by maxice8** [comment]
```
$ xrevshlib libgit2
Fritzing
amp
calligra
cargo
geany-plugins
git-series
grv
ktexteditor
libgit2-glib
slcp
stagit
```

**Comment by Gigahawk** [comment]
Haha, was just about to ask how to rebuild all the reverse dependencies, perhaps something should be added to the manual? 
Also does common/shlibs get it's own commit or do I include it with the libgit2 commit

**Comment by maxice8** [comment]
On Fri, Jul 13, 2018 at 07:38:16PM -0700, Gigahawk wrote:
> Haha, was just about to ask how to rebuild all the reverse dependencies, perhaps something should be added to the manual? 

The error message tells it all.

msg_red "${pkgver}: all reverse dependencies should also be revbumped to be rebuilt against ${libname}.so.${rev}:\n"

> Also does common/shlibs get it's own commit or do I include it with the libgit2 commit
> 

include with libgit2 commit

**Comment by Gigahawk** [comment]
So just realized `cargo` depends on a prebuilt binary to build itself, which is currently being hosted at repo.voidlinux.eu/distfiles/. 

The latest version of the binary requires libgit2.so.26, and presumably rebuilding this binary would allow x86_64-musl builds to work.

I'm not really sure how I should go about generating this binary (hopefully with a chroot or something so I don't have to reinstall) as well as how I would get it onto the distfiles repo.

**Comment by Gottox** [comment]
I'll merge this together with rust-1.28.

**Pull request merged**
