### PR TITLE
pixman: update to 0.40.0.

### PR DESCRIPTION
**Pull request by ericonr**
Update links, simplify musl patch.

---

I'm not sure I understand the musl patch. The main thing with musl is that thread stack size is small, so putting the array in thread storage seems worse than leaving it in the main stack.

### CODE REVIEW

**Comment by ericonr** [comment]
Yeah alpine does it by setting stack size manually: https://gitlab.alpinelinux.org/alpine/aports/-/blob/b4bbca3b59db4edb27885498eeded16e8e681ec9/main/pixman/APKBUILD

**Comment by ericonr** [comment]
Fully removed patch, moved to linker flags for fixing on musl.

**Review by ifreund — APPROVED** [review]
Was about to bump this myself but I luckily checked to see if anyone had beat me to it first. Works for me on `x86_64-glibc`.

Looks like pixman has moved to meson and will drop autotools support soon by the way: https://gitlab.freedesktop.org/pixman/pixman/-/merge_requests/39

**Comment by ericonr** [comment]
@ifreund iirc I couldn't find the tarballs for meson (it might have been another package). If I can find it, I can definitely switch for this release.

**Comment by ifreund** [comment]
@ericonr the tarballs downloaded from [here](https://gitlab.freedesktop.org/pixman/pixman/-/tags) have meson build files at least, I haven't tried to build it though:

**Comment by ericonr** [comment]
Those are source tarballs, not release ones :/

But I guess it's a good enough option.

**Comment by ericonr** [comment]
And it wasn't pixman that lacked meson files. I will do the switch, then.

**Pull request merged**
