### PR TITLE
mongoose: improve template and patches

### PR DESCRIPTION
**Pull request by subnut**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by subnut** [comment]
@ahesford paper42 suggested my to ping you, since you're the one who reviewed it last time.

**Comment by ahesford** [comment]
What is the purpose of these changes? You are patching the build system to ship a utility upstream uses for testing. If they mean for this to be a user-visible tool, then it should have an associated installation target.

**Comment by subnut** [comment]
> if they mean for this to be a user-visible tool [...]

They do. See https://mongoose.ws/documentation/#packed-filesystem.

Basically, the `pack` (renamed to `mongoose-pack` due to reasons mentioned in the template) command takes a file hierarchy and _"packs"_ it into source code, which can then be used while building a server so that the server uses the _packed_ files instead of the actual filesystem.

It is useful development only, so I have put it under `mongoose-devel`

> [...] then it should have an associated installation target.

You mean, a target in the Makefile?

**Comment by subnut** [comment]
Also, the package that is currently in the repository was built using the default options of the aforementioned Makefile, and the resulting library doesn't work without this `pack` program (symbol not found errors).

So yeah, the Makefile wasn't meant for package maintainers.

**Comment by ahesford** [comment]
The place for the Makefile patch to do the right thing when packing is disabled is upstream, not here. They should also fix the Makefile to build everything required to make the library work in the default build configuration. It would also help if they move the `pack` source out of a `test` directory so it's more obvious that it's intended as a key component of the library.

That the "packed" version of the library *requires* the client application to expose symbols that are defined by the `pack` executable is a terrible design decision that very tightly couples the library to the design of the application. As you note, this screams for direct integration of the library source code into the client source tree.

Why are we even packaging this?

**Comment by subnut** [comment]
> Why are we even packaging this?

I was also wondering the same.

I just picked it up and adopted it since it was present orphaned and outdated in the repo, and I was thinking of creating a simple web server that used this as a library. I wasn't too accustomed to the build system, etc.

Looks like we should remove this from the repo, then.  

I am closing this PR.  
@ahesford would you please just directly commit to the repo deleting the `srcpkgs/mongoose{,-devel}` directories and add `mongoose{,-devel}` to `removed-packages`?  
I don't want to create a PR.

**Comment by subnut** [comment]
> That the "packed" version of the library requires the client application to expose symbols that are defined by the pack executable is a terrible design decision that very tightly couples the library to the design of the application. As you note, this screams for direct integration of the library source code into the client source tree.

@ahesford That problem doesn't arise by default, with the `packedfs` option disabled.

I've designed the template & patches in such a way, that by default it creates a simple shared library, and it's corresponding `devel` files. The _"packing"_ functionality can be enabled if some user wants to, by building it with the packedfs option enabled.

Also, I think we should include this in the repo, and then use this library for other applications instead of using their outdated versions, like in the case of `smplayer`.

**Comment by ahesford** [comment]
Just kill the build option and patch out the packed stuff. There's no need to complicate the makefile patch and borrow trouble with a build option nobody is going to use. If somebody intends to use the packed option and believes it belongs in the template instead of vendoring two files, let that person make the case when needed.

Also, if the justification is to use this library for other templates, you might as well include those adjustments in this PR to demonstrate the viability.

**Comment by subnut** [comment]
> Also, if the justification is to use this library for other templates, you might as well include those adjustments in this PR to demonstrate the viability.

I'll do that in a future PR. Because currently, the library itself is broken (undefined references) so if somebody wants to use it to build anything, it won't work. So, I think it's better if we fix the library issue as soon as possible, and then later focus on patching other packages.

**Pull request closed without merging**
