### PR TITLE
New package: 1password-8.4.1

### PR DESCRIPTION
**Pull request by b-l-a-i-n-e**
#### Testing the changes
- I tested the changes in this PR: YES

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): YES

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-GLIBC)

### CODE REVIEW

**Comment by b-l-a-i-n-e** [comment]
#34427

**Comment by b-l-a-i-n-e** [comment]
#34425

**Comment by b-l-a-i-n-e** [comment]
thanks for taking a look @Chocimier -- updated addressing your comments

**Comment by Chocimier** [comment]
Changed group name to follow guidelines, reduced build deps, and moved fetching to post_extract so builddir is cleaned correctly.

**Comment by Chocimier** [comment]
@the-maldridge, ok for restricted package?

**Pull request merged**
