### PR TITLE
New package: kdbg-3.0.1

### PR DESCRIPTION
**Pull request by dmarto**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86-64_glibc

### CODE REVIEW

**Comment by dmarto** [comment]
bump

**Comment by MechDR** [comment]
Screenshot_2024-05-19_00-51-50

Happens with any binary you try to load.

**Comment by dmarto** [comment]
I would guess that you probably don't have gdb installed, and kgdb is just gui around gdb. Which is an error in the pkg, as gdb is not listed as (runtime) dependency.

**Comment by MechDR** [comment]
Yes, that does seems to be the problem.

**Comment by MechDR** [comment]
I still can't get it to load anything. It just hangs at loading debug symbols...

**Pull request closed without merging**
