### PR TITLE
New package: checkra1n

### PR DESCRIPTION
**Pull request by foxlet**
Adds architectures and dependencies missing in #18980.

### CODE REVIEW

**Comment by Chocimier** [comment]
Licensing still unclear.

**Comment by foxlet** [comment]
Yep, just waiting on more confirmation.

**Comment by foxlet** [comment]
Clarification from @nullpixel.

**Comment by Duncaen** [comment]
Yea no, I don't think that cuts it. We has some responsibility in what we distribute and without a clear license letting this into the repository and having unknowing third parties mirroring our repositories without a clear license is a big no-go.

**Comment by foxlet** [comment]
Until a new license text is available, I can only leave it as `restricted`.

**Comment by abenson** [comment]
Don't vendor the license, and 0.10.2 is out

**Review by nxqq — APPROVED** [review]

**Comment by ericonr** [comment]
Closing due to inactivity, feel free to reopen! Addressing abenson's comments should be enough.

**Pull request closed without merging**
