### PR TITLE
go: update to 1.20.

### PR DESCRIPTION
**Pull request by paper42**
#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by NyaaaWhatsUpDoc** [comment]
Damn you beat me to this by minutes :sweat_smile: 

(also, thank you!)

**Comment by paper42** [comment]
packages not building with go 1.20 (mostly because they are using an old version of quic-go):
- [x] caddy
- [ ] cloudflared
- [ ] ...

**Comment by unrealjo** [comment]
@paper42  what about this pull request [#42039 ](https://github.com/void-linux/void-packages/pull/42039) ?

**Comment by daniel-eys** [comment]
dnscrypt-proxy go 1.20 release: https://github.com/DNSCrypt/dnscrypt-proxy/releases/tag/2.1.3

**Pull request merged**
