### PR TITLE
xen: update to 4.17.2

### PR DESCRIPTION
**Pull request by numerys**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc, x86_64-musl)

### CODE REVIEW

**Comment by numerys** [comment]
I did a `xlint template` without reporting error. I'll correct the template.

**Comment by numerys** [comment]
Fixed revison typo.

**Comment by numerys** [comment]
Once again...

**Comment by Piraty** [comment]
1. do not close/re-open PRs
2. do not merge upsteam/master into your branch, rebase your branch instead
3. adhere to `CONTRIBUTING.md`

**Pull request closed without merging**
