### PR TITLE
New package: buffyboard-0.2.0

### PR DESCRIPTION
**Pull request by JamiKettunen**
Here's a preview of it:

https://user-images.githubusercontent.com/47358222/155892713-80544008-6e77-4e7e-82ef-a571b6e2dc03.mp4

#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by the-maldridge** [comment]
I'm pulling out a touch enabled device to test this now.  As is this can't be merged due to the excessive pinning to git hashes for dependencies.  Please package the dependencies as distinct packages as required per policy.

**Comment by classabbyamp** [comment]
works decently for me on a touchscreen laptop, x86_64-glibc: https://i.qrm.cat/7f626d4b552.jpg

**Comment by JamiKettunen** [comment]
> As is this can't be merged due to the excessive pinning to git hashes for dependencies. Please package the dependencies as distinct packages as required per policy.

@the-maldridge This doesn't make sense for [LVGL](https://github.com/lvgl/lvgl) which is meant to be customized via header configs on a per-project basis and is built-in to the final executable (it's also included as a submodule in the git repo); so far there haven't been any packages which use LVGL is srcpkgs.

I'll see what I can do about [`squeek2lvgl`](https://gitlab.com/cherrypicker/squeek2lvgl) though, that could maybe get packaged separately.

**Comment by classabbyamp** [comment]
ok I've had the service for this active for a bit, and I believe it's causing ctrl to be stuck on in my x session when it's running. downing the service made this behaviour stop.

**Comment by Johennes** [comment]
@classabbyamp sorry for checking in on this so late. I'm following up from https://gitlab.com/cherrypicker/buffyboard/-/issues/21. Do you remember by any chance what kind of actions you've done in Buffyboard before switching to X? Buffyboard emulates a physical keyboard under the hood so I assume it's possible for keys to get stuck somehow though I haven't so far seen this myself.

**Comment by classabbyamp** [comment]
I'm going to guess it would be caused by using ctrl+alt+f# to switch ttys

**Comment by Johennes** [comment]
Hm, I just tested that locally but CTRL did not end up stuck for me. I could see how it would get stuck when the CTRL key on buffyboard was left active before switching the VT. However, the modifiers in buffyboard auto-release after the first non-modifier key. Will have to poke at this some more.

**Pull request closed without merging**
