### PR TITLE
bCNC: fix breakage

### PR DESCRIPTION
**Pull request by Luciogi**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by Luciogi** [comment]
fixes : #46723

**Comment by Luciogi** [comment]
`checkdepends="python3-wheel python3-imageio libopencv-python3"`
I added libopencv-python3 as checkdepends, but it still compain about it
```
  ir_d = dist.fetch_build_eggs(dist.install_requires)
/usr/bin/python3: No module named pip
error: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpox3gdhhv', '--quiet', 'opencv-python>=2.4']' returned non-zero exit status 1.
=> ERROR: bCNC-0.9.14.307_5: do_check: '${make_check_pre} python3 setup.py ${make_check_target} ${make_check_args}' exited with 1
=> ERROR:   in do_check() at common/build-style/python3-module.sh:28
```

**Comment by ahesford** [comment]
You should start with

    checkdepends="python3-pytest $depends"

and work from there.

**Comment by Luciogi** [comment]
> You should start with
> 
> ```
> checkdepends="python3-pytest $depends"
> ```
> 
> and work from there.
test failed with : with error
```
ModuleNotFoundError: No module named 'pyautogui'
```
`pyautogui` is not  in void repos

**Comment by paper42** [comment]
you will have to add it as a new commit here or disable tests with an appropriate comment

**Pull request closed without merging**
