### PR TITLE
New package: opmsg-1.78s

### PR DESCRIPTION
**Pull request by travankor**

### CODE REVIEW

**Comment by atweiden** [comment]
recommend investigating `src/Makefile` to handle compile error and other opts

```make
# cross-compilation
INC+=-I$XBPS_CROSS_BASE/usr/include
LIBS+=-L$XBPS_CROSS_BASE/usr/lib
# libressl
DEFS+=-DHAVE_BN_GENCB_NEW=0
DEFS+=-DHAVE_LIBRESSL
# chacha20
DEFS+=-DCHACHA20
```

**Comment by travankor** [comment]
thanks for the heads-up
the new libressl added BN_GENCB_NEW (in 2.7+?), so that shouldn't matter

I think the errors are gcc 8.2 related, but I'm not sure what the fix would be

**Comment by travankor** [comment]
also `-DCHACHA20` is broken

```
misc.cc: In function 'const EVP_CIPHER* opmsg::algo2cipher(const string&)':
misc.cc:90:12: error: 'EVP_chacha20_poly1305' was not declared in this scope
   cipher = EVP_chacha20_poly1305();
            ^~~~~~~~~~~~~~~~~~~~~
misc.cc:90:12: note: suggested alternative: 'LN_chacha20_poly1305'
   cipher = EVP_chacha20_poly1305();
            ^~~~~~~~~~~~~~~~~~~~~
            LN_chacha20_poly1305
make: *** [Makefile:98: misc.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by travankor** [comment]
raised upstream issue https://github.com/stealth/opmsg/issues/21

**Pull request closed without merging**
