### PR TITLE
glibc-locales depends gzip

### PR DESCRIPTION
**Pull request by arete**

### CODE REVIEW

**Comment by xtraeme** [comment]
can you please explain why? also the commit msg should be `glibc-locales: depends on gzip`

**Comment by arete** [comment]
Hi, setting locale have need gzip for decompress charset

**Comment by Chocimier** [comment]
Is it really /usr/bin/gzip needed, or some library like zlib.so?

**Comment by sgn** [comment]
This will create circular dependencies? Better to pull gzip/zlib into base-minimal?

**Comment by ericonr** [comment]
@arete ping? This would be nice to solve.

**Pull request closed without merging**
