### PR TITLE
libnma: update to 1.8.32

### PR DESCRIPTION
**Pull request by cinerea0**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Review by paper42 — COMMENTED** [review]
let's add a changelog: https://gitlab.gnome.org/GNOME/libnma/-/raw/master/NEWS

**Comment by cinerea0** [comment]
@paper42 Is the format for the changelog in the most recent push alright?

**Comment by paper42** [comment]
> Is the format for the changelog in the most recent push alright?

@cinerea0 GitHub removed some parts from the URL in my last comment, it should be `https://gitlab.gnome.org/GNOME/libnma/-/raw/master/NEWS`

**Comment by cinerea0** [comment]
@paper42 Fixed!

**Pull request merged**
