### PR TITLE
firefox: update to 88.0.1

### PR DESCRIPTION
**Pull request by dkwo**
- firefox: update to 88.0.1
- firefox-i18n: update to 88.0.1
- firefox: add musl patch

I took the patch from Alpine, hoping that it would allow firefox to run on musl 1.2.2.
Possibly more patches are needed, but at least this one shouldn't do any damage.
I haven't built/tested it on musl yet.

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

Builds on  x86-64

[ci skip]

### CODE REVIEW

**Comment by ericonr** [comment]
Firefox's crash on musl 1.2.2 should be related only to `O_LARGEFILE` changes that happened for `x86_64`. @q66 mentioned he tested firefox with musl 1.2.2 on ppc64le-musl and didn't have any issues.

I'm not sure we should import this patch, unless you have context for what issue it's actually solving?

**Comment by ericonr** [comment]
(sorry, I had missed the bug link in the patch)

but in that case, https://bugzilla.mozilla.org/show_bug.cgi?id=1657849#c2 shows that the patch doesn't solve an actual issue, since the hang was reproduced with seccomp disabled.

**Comment by ericonr** [comment]
Once https://github.com/void-linux/void-packages/pull/30718/commits/a7895ff59e0f5c86a21c7707fff5f9e8e0e3fd6e is removed I'm okay with merging this, seems to be ok on musl.

**Comment by dkwo** [comment]
I see, thanks for pointing this out.

**Comment by ericonr** [comment]
I will merge this by itself, holding it up on #30777 isn't ideal.

**Comment by dkwo** [comment]
Ok.

**Pull request merged**
