### PR TITLE
qtile-wayland: add wayland session entry

### PR DESCRIPTION
**Pull request by Luciogi**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (X86_64-GLIBC)

### CODE REVIEW

**Comment by classabbyamp** [comment]
why not just install the one available from upstream? https://github.com/qtile/qtile/blob/master/resources/qtile-wayland.desktop

**Comment by Luciogi** [comment]
> why not just install the one available from upstream? https://github.com/qtile/qtile/blob/master/resources/qtile-wayland.desktop

I forgot to check upstream

**Comment by Luciogi** [comment]
Now it installs upstream file

**Review by classabbyamp — COMMENTED** [review]
vinstall in post_install then vmove in the subpackage function

**Comment by Luciogi** [comment]
> vinstall in post_install then vmove in the subpackage function

done

**Pull request merged**
