### PR TITLE
freeorion: update to 0.5.

### PR DESCRIPTION
**Pull request by Emru1**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by Emru1** [comment]
bump

**Comment by cinerea0** [comment]
It looks like version 0.5.1 is available upstream, can this PR be updated to that version?

**Comment by Emru1** [comment]
Well, something is wrong.
I have no what, but I'll bet that some dependency was upgraded
https://github.com/freeorion/freeorion/issues/4919

**Comment by Emru1** [comment]
Fix merged upstream

**Pull request merged**
