### PR TITLE
xbps-src: recompute XBPS_MASTERDIR and XBPS_HOSTDIR in chroot stage.

### PR DESCRIPTION
**Pull request by yopito**
fix Issue #8282

### CODE REVIEW

**Comment by pullmoll** [comment]
I still see an error message when using `./xbps -m /tmp/some/path … binary-bootstrap`:
```
chmod: cannot access '/void-packages/masterdir/builddir': No such file or directory
```
from line `xbps-src:716`. Perhaps we should add `--quiet` or `-f` to the `chmod` params.

**Comment by yopito** [comment]
Thanks for inputs. Additional rework is needed.

**Comment by yopito** [comment]
I'ts better now.

About `-m) readonly XBPS_MASTERDIR=….` : I think `export`  is still uneeded here, since It's already working in "normal" mode ?  

the rationale for this tiny modification  is that chrooted xbps-src is in fact a new process, launched without any option (see common/xbps-src/shutils/chroot.sh:221); so this patch should be sufficient at this time.

I don't often use all possible commands of  xbps-src; I will try the one related to chroot this week-end just in case.

**Comment by yopito** [comment]
@pullmoll: I've fixed what you've found. Could you give a try again ? thx

**Pull request merged**
