### PR TITLE
nvidia: restore usr/share/glvnd/egl_vendor.d

### PR DESCRIPTION
**Pull request by cmhainesii**
#### Testing the changes
- I tested the changes in this PR: YES
- I built this PR locally for my native architecture, x86_64 glibc

### CODE REVIEW

**Comment by cmhainesii** [comment]
I inadvertently deleted a vmkdir on line 136 in my previous commit that is still necessary.

**Comment by kruceter** [comment]
cc: @abenson

**Comment by ahesford** [comment]
A commit message like "nvidia:  restore usr/share/glvnd/egl_vendor.d" is more informative than "fix restore deleted line 136".

**Comment by abenson** [comment]
You need to edit the actual commit message, not the PR title.

    $ git commit --amend

Change the message, save, and quit.  Then force push your changes to this branch.

    $ git push -f

**Pull request merged**
