### PR TITLE
ansible: update to 4.0.0

### PR DESCRIPTION
**Pull request by dstolfa**
With the major version update of ansible to 4.0.0, ansible-base has been renamed to ansible-core. This pull request addresses the changes necessary to update ansible to 4.0.0.

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ahesford** [comment]
You should move the transitional package into the new `ansible-core` as a subpackage.

**Comment by ahesford** [comment]
Also, ping @jcgruenhage

**Comment by dstolfa** [comment]
@ahesford After local testing, I believe that it behaves correctly as a subpackage now and that upgrades followed by removal of `ansible-base` shouldn't break `ansible` installations.

**Comment by jcgruenhage** [comment]
I've built this locally and tested the changes, it seems that it all works as expected.

**Comment by ericonr** [comment]
There was a typo in the commit, so closing PR manually.

**Pull request closed without merging**
