### PR TITLE
New packages: innernet-1.5.5 innernet-server-1.5.5

### PR DESCRIPTION
**Pull request by agausmann**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

### CODE REVIEW

**Comment by agausmann** [comment]
I tried making these subpackages, but I'm not sure how to tell Cargo to install multiple local crates without multiple `cargo install` commands. I tried multiple `--path` arguments but it rejects that.

**Comment by agausmann** [comment]
I can't reproduce this test failure, running `./xbps-src check` locally on x86_64 and in a fresh container

**Comment by agausmann** [comment]
This might be able to run as non-root with CAP_NET_ADMIN (tonarino/innernet#41). I haven't tested that yet.

**Comment by icp1994** [comment]
Looks like that test does not work in containers https://github.com/tonarino/innernet/blob/v1.5.5/rpm/Dockerfile#L18

**Comment by agausmann** [comment]
Oh, I was running it in an LXD container, I guess Docker has some different privileges

**Comment by agausmann** [comment]
Still using these, still hoping to merge

**Comment by agausmann** [comment]
bump.

**Pull request closed without merging**
