### PR TITLE
gradle: update to 7.3.3.

### PR DESCRIPTION
**Pull request by unspecd**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-musl
- I built this PR locally for these architectures (if supported. mark crossbuilds):

Supersedes #31971.

#### TODO for packages
 - [x] apache-jmeter
 - [x] chatty
 - [x] freeplane
 - [x] freerouting
 - [x] ghidra
 - [x] jadx

### CODE REVIEW

**Comment by Piraty** [comment]
```
$ xxbuild $(grep -rl gradle srcpkgs/*/template | cut -d/ -f2)

<stuff>
SUMMARY
pkg:gradle host:x86_64 target:x86_64 cross:n result:OK
pkg:jadx host:x86_64 target:x86_64 cross:n result:OK
pkg:ghidra host:x86_64 target:x86_64 cross:n result:OK
pkg:freerouting host:x86_64 target:x86_64 cross:n result:FAILED
```

**Review by Piraty — CHANGES_REQUESTED** [review]
freerouting doesn't build with new gradle.

please check if all packages using it build correctly

**Comment by unspecd** [comment]
apache-jmeter needs too many patches to make it work with gradle 7.3 even if updated to the latest version.

**Comment by Piraty** [comment]
ping @knusbaum

**Comment by knusbaum** [comment]
Genuine question: Is there a particular reason we want to upgrade `gradle`? It seems makes certain packages more difficult to build, requiring patches for `freerouting`.

Void is rolling-release, but ["focuses on stability, rather than on being bleeding-edge"](https://voidlinux.org/). What do we get from this upgrade?

**Comment by unspecd** [comment]
> Is there a particular reason we want to upgrade gradle?

jadx 1.3.2 requires gradle 7.0.

**Pull request closed without merging**
