### PR TITLE
New package: difftastic-0.28.0

### PR DESCRIPTION
**Pull request by juantascon**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (ARCH-LIBC) x86_64-libc

### CODE REVIEW

**Comment by abenson** [comment]
You probably need to add something like:

```
if [ "$XBPS_TARGET_NO_ATOMIC8" ]; then
    makedepends+=" libatomic-devel"
fi
```

**Comment by TeddyDD** [comment]
0.29.1 has been released, maybe it will work 🤞

**Comment by TeddyDD** [comment]
I tried 0.31.0 and it's the same issue. Maybe you clould mark armv6l-musl as broken?

**Comment by Chocimier** [comment]
Try exporting LDFLAGS=-latomic, or whatever way rust toolchain accepts that, if any.

**Pull request closed without merging**
