### PR TITLE
cliphist: update to 0.6.1.

### PR DESCRIPTION
**Pull request by bitterhalt**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc

### CODE REVIEW

**Comment by bitterhalt** [comment]
Ping @LucasTavaresA

**Comment by LucasTavaresA** [comment]
Im not on wayland anymore so i did not see this, i wonder why the tests are not firing on some archs.

**Comment by bitterhalt** [comment]
> Im not on wayland anymore so i did not see this, i wonder why the tests are not firing on some archs.

Yeah seems to fail with some arch. It worked locally just fine, so maybe they have some bigger changes there.

**Comment by LucasTavaresA** [comment]
this test https://github.com/sentriz/cliphist/blob/8c48df70bb3d9d04ae8691513e81293ed296231a/testdata/no-permission.txtar is from a year ago, so it does not seem to be something new.
it is expected to fail to execute a command `exec cliphist store` due to no permission, but here the test fails cause the command works, maybe its the CI environment permissions, might be a bug/mistake in cliphist making the program return sucess.

**Comment by bitterhalt** [comment]
> this test https://github.com/sentriz/cliphist/blob/8c48df70bb3d9d04ae8691513e81293ed296231a/testdata/no-permission.txtar is from a year ago, so it does not seem to be something new. it is expected to fail to execute a command `exec cliphist store` due to no permission, but here the test fails cause the command works, maybe its the CI environment permissions, might be a bug/mistake in cliphist making the program return sucess.
> 
> did you run the tests and they worked?

I did not run any test locally because I could build it without any problems.  There is `xbps-src check` if it helps
[log.txt](https://github.com/user-attachments/files/17534899/log.txt)

**Comment by LucasTavaresA** [comment]
yeah all tests are passing

**Comment by LucasTavaresA** [comment]
this test is just weird, can you append these lines to the template
```
# flimsy test that breaks CI
make_check_args="-skip=TestScripts/no-permission"
```

**Comment by bitterhalt** [comment]
> this test is just weird, can you append these lines to the template
> 
> ```
> # flimsy test that breaks CI
> make_check_args="-skip=TestScripts/no-permission"
> ```

Done.

**Pull request merged**
