### PR TITLE
lxd: add logging

### PR DESCRIPTION
**Pull request by amak79**
This pull request adds service logging to stop lxd from sending messages to tty1.

### CODE REVIEW

**Comment by Duncaen** [comment]
`log/run` can be a symlink to `/usr/bin/vlogger`, vlogger will get the tag from the service path.

**Comment by amak79** [comment]
When using a symlink I noticed that `ps` will display `./run` for the command instead of `vlogger -t lxd`. This is less informative, but if you prefer a symlink I will amend the commit.

**Comment by CameronNemo** [comment]
FWIW lxd has `--syslog` option.

**Comment by amak79** [comment]
I've added conf file support to allow `--syslog` or any other option to be passed to lxd.

**Comment by CameronNemo** [comment]
vlogger logs to syslog. no use in using it when lxd can do that itself. I would suggest defaulting to passing `--syslog`. I am not using runit though, so I do not have much stake in the matter. Either way LGTM.

**Comment by amak79** [comment]
lxd writes to tty1 even with `--syslog`. That's why I kept vlogger. I will amend the commit to use syslog by default.

**Comment by CameronNemo** [comment]
I see... in that case you will have two copies of each message in syslog (one from lxd and one from vlogger). Less than ideal. You could throw away the stdout/stderr streams by redirecting them to `/dev/null`.

**Comment by amak79** [comment]
I noticed the duplicated messages when testing. I will just discard stdout/stderr. Thanks.

**Comment by amak79** [comment]
Is there a reason why `2>&1` was added to the run script? I just realised that it was causing the messages being written to tty1. My current commit discards stdout/stderr, but it's not needed when `--syslog` is passed to lxd.

**Comment by xtraeme** [comment]
If you are enabling syslog logging you can remove the redirects as well.

**Comment by Duncaen** [comment]
vlogger allows to write logs to log files with svlogd and only uses syslog by default. Using vlogger to execute into svlogd is superior because it would never lose any messages (if the daemon starts before the syslog daemon or the syslog daemon is restarted).

**Comment by amak79** [comment]
When the stderr redirect is removed from the run script, vlogger isn't able to log anything. With the redirect only 2 messages are logged. To use vlogger, lxd must be started with `--verbose`. This option appears to output the same messages as `--syslog`.

**Pull request merged**
