### PR TITLE
flameshot: update to 11.0.0

### PR DESCRIPTION
**Pull request by prateekmedia**
#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by oreo639** [comment]
Again, it needs to be `<pkgname>: update to <version>` with pkgname being the same case as the package name (in this case all lowercase)
https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md

As the contributing guide mentions in the `Review` section, just use `git commit --amend` to update the commit message.

**Comment by prateekmedia** [comment]
@oreo639 Done! I was not cloning the repo cause it was more than 400Mb in size, but anyways.

**Comment by paper42** [comment]
> Done! I was not cloning the repo cause it was more than 400Mb in size, but anyways.

If you didn't clone this repository, how did you test this package? We generally require build and runtime testing.

**Comment by prateekmedia** [comment]
> > Done! I was not cloning the repo cause it was more than 400Mb in size, but anyways.
> 
> If you didn't clone this repository, how did you test this package? We generally require build and runtime testing.

I was using --depth 1 before so it was 12 MB in size.

**Comment by paper42** [comment]
great, the commit message still needs to be fixed, <version> is not v11.0.0, but 11.0.0

**Comment by prateekmedia** [comment]
@oreo639 It is passing all test, what next?

**Comment by oreo639** [comment]
That's it. Just be patient.

**Pull request merged**
