### PR TITLE
nvidia: update to 470.57.02.

### PR DESCRIPTION
**Pull request by ardadem**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [X] I generally don't use the affected packages but briefly tested this PR

I am not nvidia user so can't test it locally.

### CODE REVIEW

**Comment by ArmedAviator** [comment]
Builds and installs for me on glibc x86_64.  The driver seems to work, with an exception and I suspect it's user-error or third party software issue.

Using Steam for gaming, I can play native Linux games but games using Proton fail.

`The NVIDIA driver was unable to open 'libnvidia-glvkspirv.so.470.57.02'.  This library is required at run time.`

The library is where it should be in /usr/lib.

**Comment by ardadem** [comment]
Steam uses 32-bit libraries too, maybe you forgot to update 32-bit nvidia libs? Can you check "/usr/lib32/libnvidia-glvkspirv.so.*" ?

**Comment by ArmedAviator** [comment]
That was my thought, too.  I double checked and do have the 32-bit libraries installed.

`rich@area51 ~ $ xbps-query -s nvidia*
[*] nvidia-470.57.02_1            NVIDIA drivers for linux - Libraries and Utilities
[*] nvidia-dkms-470.57.02_1       NVIDIA drivers for linux - DKMS kernel module
[*] nvidia-gtklibs-470.57.02_1    NVIDIA drivers for linux - GTK+ libraries
[*] nvidia-libs-470.57.02_1       NVIDIA drivers for linux - common libraries
[*] nvidia-libs-32bit-470.57.02_1 NVIDIA drivers for linux - common libraries (32bit)

rich@area51 ~ $ ls -lh /usr/lib32/libnvidia-glvkspirv.so.*
-rwxr-xr-x 1 root root 15M Jul 22 04:29 /usr/lib32/libnvidia-glvkspirv.so.470.57.02`

This has happened before during the 460 series of nvidia driver updates and it just "fixed" itself after an update one week.  I do recall that the drivers were not updated when things began working again - maybe something built against nvidia libs in steam/proton?  I don't know.

With that said, it seems this package is good to go and that my problem is coming from Steam/Proton itself.

**Comment by ardadem** [comment]
It should install DLSS for wine libraries too now.

**Comment by abenson** [comment]
I wasn't able to recreate the issue with wine/proton, it seemed to work fine for me.  I'm updating to the most recent commit you pushed, but I am feeling pretty comfortable with this working well.

**Comment by ArmedAviator** [comment]
I tried the latest commit pushed but I am having the same difficulty with Steam/Proton games, but I suspect it is not related to this package anymore.  Everything else including Linux-native gaming via Steam works great.

**Comment by abenson** [comment]
I'll probably merge tomorrow night when I can test on the other laptop(s)

**Comment by kernle32dll** [comment]
> Builds and installs for me on glibc x86_64 with GTX 1660 Super. The driver seems to work, with an exception and I suspect it's user-error or third party software issue.
> 
> Using Steam for gaming, I can play native Linux games but games using Proton fail.
> 
> `The NVIDIA driver was unable to open 'libnvidia-glvkspirv.so.470.57.02'. This library is required at run time.`
> 
> The library is where it should be in /usr/lib.

I can confirm the same issue, but I'm afraid I'm not much help in pinpointing the issue, as I only got myself a nvidia card yesterday (running on AMD before).

**Pull request merged**
