### PR TITLE
New package: handlr-regex-0.10.1

### LINKED ISSUE #51072: Package request: handlr-regex
### Package name

handlr-regex

### Package homepage

https://github.com/Anomalocaridid/handlr-regex

### Description

A mime handler, alternative of xdg-open.
as `handlr` was not mentained so long, hope add this `handlr-regex` fork.

Manage your default applications with ease using handlr! Now with the power of [regular expressions](https://github.com/Anomalocaridid/handlr-regex#setting-regex-handlers)!

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

### PR DESCRIPTION
**Pull request by tranzystorekk**
Closes #51072 

#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

cc @nilium this PR replaces `handlr`, so let me know if you're okay with it, or if you maybe prefer it not being added, or maintaining the new fork yourself?

### CODE REVIEW

**Comment by nilium** [comment]
Feels like you would want this to be an alternative instead of replacing handlr since they operate differently.

**Comment by tranzystorekk** [comment]
Hm, I'm not sure I understand how they operate differently enough to require alternatives? The general CLI API seems mostly compatible between the two, the biggest difference being the nomen-omen regex support.

**Comment by nilium** [comment]
That would be a pretty significant difference between the two that might make them incompatible over time, especially if @chmln makes any new changes. Hence using alternatives, if you want this fork and its maintainer, @Anomalocaridid, insists on using the name `handlr` for their binary instead of choosing a new name, it seems best to do this as an alternative instead of replacing a tool that already does what it intends to do.

**Comment by tranzystorekk** [comment]
Took a more detailed look at the fork's history, there are a few notable bugfixes and improvements ported from the upstream, but seemingly no original contributions from the fork's author, so in the end probably not worth the effort of replacing here.

**Pull request closed without merging**
