### PR TITLE
python3-efl: remove package.

### PR DESCRIPTION
**Pull request by ericonr**
@q66 only dependant was econnman, which you dropped already. If you think it's worth keeping, please update it. I'm slating for removal because I was going to update it and realized I didn't have any application with which to test it.

### CODE REVIEW

**Comment by Boebbele** [comment]
Is Phyton-EFL don't used by EFL?

**Comment by ericonr** [comment]
No, nothing depends on it.

**Comment by Boebbele** [comment]
I don't can remove it on my system. Dependencies: dbus-libs, EFL, glibc, python3-dbus.

**Comment by ericonr** [comment]
That's not what 62fa9161e9561a6b3d122005f1e2f863a44ebed1 says.

**Comment by Boebbele** [comment]
efl, econnman and phyton-efl are in the official Repos.
 
maybe I misunderstand you?? 
I was just afraid that econnman would disappear from official repo....

**Comment by ericonr** [comment]
`econnman` isn't supported by void anymore, and will be removed from repositories at some point... It has been removed from void-packages already. From what I understand there should be network controls built into enlightenment now.

**Comment by Boebbele** [comment]
enlightenment brings an error message (rather a request) if econnman is not installed.  one should install it.  enlightenment livecd is delivered with connman.  then do I have to install cmste which was programmed with Qt and not EFL?  strange decision?

**Comment by ericonr** [comment]
@Boebbele for what it's worth, I think the startup message is about Connman, not `econnman`...

**Comment by Boebbele** [comment]
but, it is econnman! Econnman as GUI for connman. Econnman is Part of the enlightenment-modul for Networkconnection.

**Comment by q66** [comment]
you don't need econnman for general usage of the connman gadget (which is builtin into enlightenment)

and econnman (which can be used for advanced configuration) is indeed long dead, so it has been removed, no, i won't be adding it back

**Comment by Boebbele** [comment]
OK.  I take another look at it carefully.  i think you are right.  I trust you! :-)

**Comment by gorkawien** [comment]
I use econnman in a laptop wher I have installed Enlightenment. 
I made my own template because the original one was deleted. So I will also need python3-efl to build it.
I feel more comfortable having econnman. Other alternatives didn't satisfy me.

**Comment by Boebbele** [comment]
Here is a template for python3-efl...if someone need it:
```
# Template file for 'python3-efl'
pkgname=python3-efl
version=1.25.0
revision=1
wrksrc=python-efl-${version}
build_style=python3-module
pycompile_module="efl"
hostmakedepends="pkg-config python3-devel python3-Cython"
makedepends="efl-devel python-dbus-devel"
depends="python3-dbus"
short_desc="Python3 bindings for Enlightenment Foundation Libraries"
license="LGPL-3.0-only, GPL-3.0-only"
homepage="http://enlightenment.org"
distfiles="http://download.enlightenment.org/rel/bindings/python/python-efl-${version}.tar.xz"
checksum=99e06df773647acfb8e04786d6958bee5b8deae41d996ccaa68d7cca7b30612e

post_extract() {
	# Pre-generated cython output is incompatible with Python 3.9
	rm -f efl/elementary/__init__.c efl/evas/efl.evas.c \
		efl/utils/{conversions,logger,deprecated}.c \
		efl/emotion/efl.emotion.c efl/eo/efl.eo.c \
		efl/ecore/efl.ecore.c efl/edje/efl.edje.c \
		efl/dbus_mainloop/efl.dbus_mainloop.c \
		efl/ethumb/efl.ethumb{,_client}.c \
		efl/ecore_input/efl.ecore_input.c \
		efl/edje_edit/efl.edje_edit.c \
		efl/ecore_con/efl.ecore_con.c \
		efl/ecore_x/efl.ecore_x.c
}

pre_build() {
	# any higher optimization level and gcc OOMs on i686 (even -Os)
	case "$XBPS_TARGET_MACHINE" in
		i686*) export CFLAGS+=" -O1";;
	esac

	# the build likes to add -g without asking
	if [ -z "$XBPS_DEBUG_PKGS" ]; then
		export CFLAGS+=" -g0"
	fi
}

```

**Comment by ericonr** [comment]
The package wasn't removed.

**Pull request closed without merging**
