### PR TITLE
New packages: sing geoip and geosite

### PR DESCRIPTION
**Pull request by hesam-init**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by Clos3y** [comment]
Both packages have scheduled, automated releases, so I think this probably isn't inline with the packaging requirements, https://github.com/void-linux/void-packages/blob/dae26c0b7d8f2fa5a1069d26ecbca8453aa999e3/CONTRIBUTING.md?plain=1#L28-L29 but I could be wrong

**Comment by hesam-init** [comment]
> Both packages have scheduled, automated releases, so I think this probably isn't inline with the packaging requirements,
> 
> https://github.com/void-linux/void-packages/blob/dae26c0b7d8f2fa5a1069d26ecbca8453aa999e3/CONTRIBUTING.md?plain=1#L28-L29
> 
> but I could be wrong
> _EDIT_: You also need to squash your commits.

I will close this request due to a lint issue and will open a new one.

**Comment by hesam-init** [comment]
> Both packages have scheduled, automated releases, so I think this probably isn't inline with the packaging requirements,
> 
> https://github.com/void-linux/void-packages/blob/dae26c0b7d8f2fa5a1069d26ecbca8453aa999e3/CONTRIBUTING.md?plain=1#L28-L29
> 
> but I could be wrong
> _EDIT_: You also need to squash your commits.

I also should mention These packages are requirements for the Nekoray client. After merging these two packages, I will push the Nekoray template.

**Comment by classabbyamp** [comment]
don't close and open new PRs, amend and force push instead. new PRs are lots of noise and they separate the review history

if you're adding dependencies of a package, add them and the package that needs them in one PR.

#51326

**Pull request closed without merging**
