### PR TITLE
pango: update to 1.48.0

### PR DESCRIPTION
**Pull request by ndowens**

### CODE REVIEW

**Comment by travankor** [comment]
aren't the odd-numbered releases development branches for GNOME projects?

**Comment by ndowens** [comment]
> aren't the odd-numbered releases for GNOME projects development releases?

Ah yes, I think so, I will update it using the latest stable update. Forgot gnome does that

**Comment by travankor** [comment]
1.48.0 is out

**Comment by q66** [comment]
uhh, this should've never been merged - it's obvious that it was never properly investigated why this breaks gir on cross architectures, with an extremely poor workaround in place

why was this not properly reviewed? it's already breaking things on builders now

**Comment by ndowens** [comment]
@q66 I will create a revert update and tag you.

**Comment by sgn** [comment]
Reverted: 199eac3f839205565f994c1ddcedfc1038547d8b

**Comment by sgn** [comment]
Updated again 652f97144898c5e02bcb0882e7baa397008b3bc1

**Pull request merged**
