### PR TITLE
coreutils: update to 9.2

### PR DESCRIPTION
**Pull request by dkwo**
- skip test-getcwd.sh test-getlogin: is this ok?
- Add [.1 man page symlink so "man [" works.
- I tested the changes in this PR: YES
- I built this PR locally for my native architectures `x86_64-musl` and `aarch64`

### CODE REVIEW

**Comment by dkwo** [comment]
I cannot reproduce the CI failure locally with `XBPS_CHECK_PKGS=full`.

**Comment by dkwo** [comment]
Added the two patches, one of them taken from Fedora.

**Comment by leahneukirchen** [comment]
Locally I get a fail in tests/cp/sparse-2.sh, but I'm on ZFS...

**Review by leahneukirchen — APPROVED** [review]

**Comment by motorto** [comment]
Is this PR looking for testers (meaning that works is done the only thing missing is people checking if it works) ?

**Comment by leahneukirchen** [comment]
feel free to test :)

**Comment by dkwo** [comment]
I've been using this for about two months. Please test if you like.

**Comment by motorto** [comment]
Just commenting that using this since yesterday and don't have any issues to report !

**Comment by dkwo** [comment]
9.2 is out

**Comment by dkwo** [comment]
been testing 9.2 for some days, no issues.

**Pull request merged**
