### PR TITLE
coredns: update to 1.10.0.

### PR DESCRIPTION
**Pull request by nilium**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)

### CODE REVIEW

**Comment by nilium** [comment]
Fixing xgensum -c flag that snuck into this as well. Removed from shell history at this point to prevent more autopilot mistakes.

**Comment by mhmdanas** [comment]
1.10.1 is out now.

There have been a lot of security fixes since 1.8.6, so it would be good to get this merged.

**Comment by nilium** [comment]
It would be better to open a 1.10.1 PR then. I'm not at my Void workstation right now, so someone else can do that or they can wait until I get around to it later.

**Comment by mhmdanas** [comment]
Sure, I'll do that, can you close this then?

**Pull request closed without merging**
