### PR TITLE
[WIP] NumPy 2.0

### PR DESCRIPTION
**Pull request by ahesford**
This update removes a lot of long-deprecated interfaces and probably breaks several dependants. It will need careful testing.

[ci skip]

The following packages ship shared libraries; most require a rebuild to even be importable, and the rest are included just to be sure (each will be ticked as it is tested for compatibility):
- [ ] gnuradio
- [x] mypaint (leaf; launches and interacts with me)
- [x] opencv
- [x] plplot (leaf; launches and allows me to plot lines in a trivial test)
- [x] python3-Bottleneck (a single test failure for memory leaks appears unrelated to NumPy)
- [x] python3-PyOpenGL-accelerate (its only dependant doesn't require NumPy support, so I'll rebuild without support)
- [x] python3-h5py
- [x] python3-matplotlib (basic use seems to work)
- [x] python3-numexpr
- [ ] python3-numpy-stl (several test failures related to closeness tests that aren't quite as close as expected; also, a few interface changes leak into tests)
- [ ] python3-pandas
- [x] python3-pyFFTW (leaf)
- [x] python3-pyopencl (leaf)
- [x] python3-pywt
- [ ] python3-scikit-image (leaf)
- [ ] python3-scikit-learn (leaf)
- [x] python3-scipy
- [ ] python3-tables (leaf)
- [ ] python3-vispy (leaf)
- [x] urh (leaf; I can launch this, but have no means to really test it)
- [x] wxPython (doesn't actually depend on NumPy, so it will be rebuilt to correct dependencies)

The following package may or may not break with new NumPy, but is already broken because it requires Python < 3.12:
- DisplayCAL

The following packages do not appear to build Python extensions and should not require a rebuild, but some tests should be performed to ensure basic functionality with NumPy 2.0:
- [x] bCNC (leaf)
- [ ] flowblade (leaf)
- [ ] grass
- [ ] hydrus (leaf)
- [x] inkscape (leaf - seems to work in my simple use tests)
- [ ] openrazer-meta
- [ ] pymol (leaf)
- [x] python3-bokeh (leaf)
- [x] python3-imageio
- [x] python3-joblib
- [ ] python3-niapy (leaf)
- [ ] python3-openai (leaf)
- [ ] python3-pgzero (leaf)
- [x] python3-pycollada
- [x] python3-pyqtgraph
- [x] python3-pytools
- [ ] python3-seaborn (leaf)
- [x] python3-tifffile
- [x] python3-trimesh
- [x] pythran (compiles python3-scipy and python3-scikit-image just fine)
- [ ] qgis (leaf)
- [x] xdot (leaf)

### CODE REVIEW

**Comment by Calandracas606** [comment]
> 
> The following package may or may not break with new NumPy, but is already broken because it requires Python < 3.12:
> 
>     * DisplayCAL
> 

There's a new version available. I'll take a look and see if I can get it working with python 3.12

**Comment by Calandracas606** [comment]
updating DisplayCAL to 3.9.12 should unbreak it with python 3.12

**Comment by Calandracas606** [comment]
https://github.com/eoyilmaz/displaycal-py3/issues/335

**Comment by tornaria** [comment]
Note: sagemath 10.4 in our repo is already patched to support numpy 2.0, but it will need to be rebuilt.

**Comment by ahesford** [comment]
9c5fb2efa8046d8e4f6ec76878ac77462a313c41

**Pull request closed without merging**
