### PR TITLE
dolphin-emu: update to 5.0.14790.

### PR DESCRIPTION
**Pull request by Hnaguski**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

Removed the remaining patch as it was merged upstream: https://github.com/dolphin-emu/dolphin/commit/d456e2e391134742c633b0029251f7ca06bb5204

### CODE REVIEW

**Comment by Hnaguski** [comment]
Failed build on i686 seems to have been fixed by https://github.com/dolphin-emu/dolphin/pull/9887
Failed build on musl seems to have been fixed by https://github.com/dolphin-emu/dolphin/pull/9814
I'm not sure how the process of backporting these patches goes, or if it's worth doing now rather than waiting for a new release which includes the fixes.

**Comment by ericonr** [comment]
Both are rather small, I think backporting is the right move.

**Comment by Hnaguski** [comment]
I've updated the PR with the patches applied

**Comment by Hnaguski** [comment]
Well dolphin just released a new beta version. Should I close this PR and open a new one for that version or just rename this one and change the template?

**Comment by paper42** [comment]
> Well dolphin just released a new beta version. Should I close this PR and open a new one for that version or just rename this one and change the template?

You can rename this one and push changes here.

**Comment by Hnaguski** [comment]
Well it seems like this build is failing because dolphin now requires mGBA when building. The [dolphin wiki says](https://github.com/dolphin-emu/dolphin/wiki/Building-for-Linux#checkout-dolphin) to run `git submodule update --init Externals/mGBA` after cloning the git repository. Could someone point me in the right direction as to how to implement this in the package?

**Comment by ericonr** [comment]
What you want to do is add a distfile downloading the submodule at the correct commit, then moving it into place. Check out how wayfire does it, for an example.

**Comment by Hnaguski** [comment]
Everything seems to be in order now, thanks for the help.

**Comment by ericonr** [comment]
Thanks!

**Pull request merged**
