### PR TITLE
nim: update to 2.0.0.

### PR DESCRIPTION
**Pull request by pfpulux**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by Bnyro** [comment]
Duplicate of #45627

**Comment by IcedQuinn** [comment]
seems there are quite a few of us nim developers on void :laughing:

**Comment by pfpulux** [comment]
What about a new package `nim2`?. I'm not happy with the additional hash sources.

**Comment by pfpulux** [comment]
tar.gz should be used in #45627

close for now

**Comment by IcedQuinn** [comment]
> What about a new package `nim2`?. I'm not happy with the additional hash sources.

I have opened a ticket upstream that the release tarballs should be all-containing, so we would not need them. They do not consider it a priority at all.

**Pull request closed without merging**
