### PR TITLE
sudo: update to 1.9.12p1.

### PR DESCRIPTION
**Pull request by mhmdanas**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by johna23-lab** [comment]
After udate the system and the sudo (using xpbs-install -Suv) now i get this errors

sudo
sudo: /etc/sudoers is not a regular file
sudo: no valid sudoers sources found, quitting
sudo: error initializing audit plugin sudoers_audit

Something broke the system?

**Comment by mhmdanas** [comment]
@johna23-lab that sounds worrying, could you please run `su -`, then open /etc/sudoers, and copy and paste its contents in a comment so we can take a look?

**Comment by johna23-lab** [comment]
Here is

https://pastebin.com/raw/3JicgkvF

**Comment by classabbyamp** [comment]
is /etc/suoders a regular file? i.e., what is the output of `ls -l /etc/sudoers` and `file /etc/sudoers`?

**Comment by johna23-lab** [comment]
Well , i tried in a VM i have and the update of sudo worked well, so looks my main system is a bit broke, wich i solved manully downgroading the package and fixing the permissions

Like this one:
pkexec chown root /usr/libexec/sudo/sudoers.so

Summarized: Something was already broke and corrupted the update of sudo, now i fixed and i don't see any problems in the fresh VM i created

**Pull request closed without merging**
