### PR TITLE
phpMyAdmin: update to 5.2.1

### PR DESCRIPTION
**Pull request by MeganerdNL**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by MeganerdNL** [comment]
Corrected commit message (removed "version").

**Review by williamdes — APPROVED** [review]
Thank you !
/phpmyadmin team

**Comment by MeganerdNL** [comment]
cc @TinfoilSubmarine: did you see this? Thanks.

**Comment by williamdes** [comment]
> Why the change from php8.1 to 8.2? Did the minimum php version requirements change?

8.2 works fine for 5.2.1. No need for 8.1

**Comment by TinfoilSubmarine** [comment]
> > Why the change from php8.1 to 8.2? Did the minimum php version requirements change?
> 
> No the minimum is **7.1.3** (https://docs.phpmyadmin.net/en/latest/require.html). But the standard PHP version installed with Void is 8.2 (if you install with **_xbps-install php_** without version - https://voidlinux.org/packages/?arch=x86_64&q=php
> 
> Leaving this to 8.1 installs 8.1 _besides_ 8.2 when people installed the default php. That is imho 1 config file more to maintain. I'd be happy to change it back if you insist...

Just to note: the void-docs [advise against installing the `php` package(s) for non-development purposes](https://docs.voidlinux.org/config/php.html). 

As I'm thinking about it, I don't really understand why we depend on php at all, since the user will have to install the php-fpm, php-apache, or php-cgi for that specific version as well. So all this does is pull in a php that the user may or may not end up using if they installed php8.0 or php8.2 instead. This situation is similar in some ways to postgresql and IIRC is why packages don't generally depend on postgresql and leave it as a task to the user to manually install and configure.

**Comment by williamdes** [comment]
> This situation is similar in some ways to postgresql and IIRC is why packages don't generally depend on postgresql and leave it as a task to the user to manually install and configure.

Just to clear things up phpMyAdmin is not a database, so I assume you are referring to pgAdmin ?

> As I'm thinking about it, I don't really understand why we depend on php at all, since the user will have to install the php-fpm, php-apache, or php-cgi for that specific version as well. 

At Debian we do `Recommends: libapache2-mod-php | lighttpd | nginx | php-fpm | httpd`
And `Depends: ... php-cli ...`
See: https://salsa.debian.org/phpmyadmin-team/phpmyadmin/-/blob/debian/latest/debian/control

**Comment by williamdes** [comment]
> Sorry, this was probably confusing. I was referring to the packaging situation where a package needs to depend on a package like postgresql or php where multiple versions are available in repo. Void/xbps doesn't have a mechanism for depending on a package without caring what version it is.

It's probably right to depend on php8.2 then :)

**Comment by TinfoilSubmarine** [comment]
Idk, this one is tricky. I'm leaning towards the side of *if we don't know what the user wants, we shouldn't force a specific version on them.* There could be a scenario where someone already has a php8.0 install on their machine for other php apps and would like to use that for phpMyAdmin as well. Obviously, nothing is stopping them from still using it, but it does pull in an unnecessary/unused dependency. The main sticking point is that the dependency on any php is not doing anything for the user since they still have to install additional packages (php-cgi, php-fpm, php-apache, etc.) to complete the configuration.

I think it's going to be confusing either way for the user, so perhaps we should
(1) drop the dependency on php and
(2) document this, either in void-docs or an `INSTALL.msg`.

**Comment by MeganerdNL** [comment]
Why not:

`depends=">php7.1.3 mariadb"`

or maybe:

`depends="php mariadb"`

When no version is given version is set to >=0 according to the [manual](https://github.com/void-linux/void-packages/blob/master/Manual.md#optional_vars) and not to the same as when _installing_ it without version.

**Comment by williamdes** [comment]
> Why not:
> 
> `depends=">php7.1.3 mariadb"`
> 
> or maybe:
> 
> `depends="php mariadb"`
> 
> When no version is given version is set to `>=0` according to the [manual](https://github.com/void-linux/void-packages/blob/master/Manual.md#optional_vars) and _not_ the same as when _installing_ it without version.

Let me add one more case, you should suggest MariaDB not force to install it. People can often? have remove databases, and having one run for nothing is way worse.

Having depends on php and not forcing any version looks good to me

**Comment by TinfoilSubmarine** [comment]
> Why not:
> 
> `depends=">php7.1.3 mariadb"`
> 
> or maybe:
> 
> `depends="php mariadb"`
> 
> When no version is given version is set to `>=0` according to the [manual](https://github.com/void-linux/void-packages/blob/master/Manual.md#optional_vars) and _not_ the same as when _installing_ it without version.

This doesn't work how you think in this case. The version numbers in "php8.0", "php8.1", and "php8.2" are actually part of the package name.

> Let me add one more case, you should suggest MariaDB not force to install it. People can often? have remote databases, and having one run for nothing is way worse.

I agree :+1:

**Comment by TinfoilSubmarine** [comment]
OK y'all, I opened a new PR which introduces a `php-runtime` virtual package which solves this dillema. It's got a slew of updates in it so it might take a bit to get merged, but I did include this update to phpMyAdmin with the new dependency solution and would appreciate testing.

**Comment by MeganerdNL** [comment]
Thank you @TinfoilSubmarine, sounds good. 
I updated this PR and removed `mariadb` as depends for now and left `php8.2`. 
If your #45493 gets merged, this PR here is obsolete, otherwise we could still use this.

I will try to test your PR tomorrow, but I cannot guarantee because of time shortage.

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
What a shame

**Pull request closed without merging**
