### PR TITLE
New package: srain-1.0.1

### PR DESCRIPTION
**Pull request by avoidr**

### CODE REVIEW

**Comment by avoidr** [comment]
It seems that `glib-compile-resources` cannot be found on the failing arches.
How should that be handled?

**Comment by travankor** [comment]
you need `build_helper=gir`

**Comment by avoidr** [comment]
Thanks, let's see!
Also, don't merge yet, there was a new release made two hours ago.

**Comment by travankor** [comment]
`build-helper=gir` implies that glib-devel is in host

**Comment by avoidr** [comment]
Do I need to take it out of makedepends, then?

**Comment by travankor** [comment]
you need it in both places

**Comment by travankor** [comment]
I think there's something wrong in the makefile/build flags. I ran into this issue before, but I forgot how I fixed it.

**Comment by avoidr** [comment]
The errors now:
```
gcc: error: unrecognized command line option '-mfpu=vfpv3'
gcc: error: unrecognized command line option '-mfloat-abi=hard'
```
and
```
cc1: error: bad value ('armv8-a') for '-march=' switch
cc1: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 native
```

**Comment by avoidr** [comment]
That looks like an issue upstream, right? I haven't found those flags when I grepped them, though.

**Comment by travankor** [comment]
yes, I would report it upstream

**Comment by travankor** [comment]
`xbps-src` does some automagic to get a cross-compile environment set up and minimal makefiles do not play well with it sometimes

**Comment by avoidr** [comment]
Then isn't it on us to find out what is missing and then open a PR with a fix upstream?

**Comment by travankor** [comment]
Well, you can check on Void's IRC, there's usually one or two people that will help you.

I don't have time to look into this now, sorry.

**Comment by avoidr** [comment]
Oh, yes, no I didn't expect us two to fix it now! Thanks for your help so far, we've progressed!

**Comment by avoidr** [comment]
Ok, I think I get it. The errors look like an host compiler is trying to be used, and not the target compiler. Perhaps the Makefile does not let the compiler to be changed, and it does look like it.

**Comment by avoidr** [comment]
I've added a patch now, to let the CC be overriden by what `xbps-src` wants. But now apparently the environment gets clobbered and headers/dependencies are no longer found.

**Comment by avoidr** [comment]
Alright, using gnu-makefile build style seems to have the same effect as my patch had.
Now I noticed that all the CFLAGS have gone missing, which is why the headers are no longer found. Who let the flags out?

**Comment by xtraeme** [comment]
maybe you need to use `make_use_env=yes`

**Comment by avoidr** [comment]
I was confused about the meaning of `-e` in make. I thought it is necessary for it to use environment variables, but it is only about precedence. The CFLAGS didn't get used because `-e` overrode them. `make` worked correctly without `-e`, using the env var and having flags appended from the Makefile.

The actual problem I had was being unable to set CC by environment, because the Makefile already set CC explicitly. The fix was to set CC conditionally based on whether it has its default value, or it has been redefined — basically falling back to a default if not otherwise specified.

**Comment by avoidr** [comment]
Done.

**Comment by avoidr** [comment]
Ping. According to me, it's good to merge.

**Pull request merged**
