### PR TITLE
straw-viewer: replace with pipe-viewer

### PR DESCRIPTION
**Pull request by 4ricci**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by Chocimier** [comment]
If you want to straw-viewer to be updated to pipe-viewer, leave it as transitional package and remove `replaces`.

**Comment by FollieHiyuki** [comment]
0.0.9 came out

**Comment by ericonr** [comment]
I think this should have a comment explaining that it's a separate package due to versioning? Since otherwise it would have been a subpackage of `pipe-viewer`.

**Comment by 4ricci** [comment]
> I think this should have a comment explaining that it's a separate package due to versioning? Since otherwise it would have been a subpackage of `pipe-viewer`.

Do you mean a comment in the template or in the commit message?

**Comment by ericonr** [comment]
> Do you mean a comment in the template or in the commit message?

I think in the commit is enough.

**Pull request closed without merging**
