### PR TITLE
dpp: Update to 10.0.28

### PR DESCRIPTION
**Pull request by OoLunar**
#### Testing the changes
- I tested the changes in this PR: briefly

#### Local build testing
- I built this PR locally for my native architecture, `x86_64`

#### Notes
~~I disabled `-DDPP_USE_EXTERNAL_JSON=ON` as `json-c++` is packaged by default within dpp. Let me know if I should readd this.~~

### CODE REVIEW

**Comment by classabbyamp** [comment]
we prefer using external to internal

**Comment by OoLunar** [comment]
I'll re-add that as an option then. Additionally the package has recently updated to 10.0.26. Should I open a separate PR or apply it to this one?

**Comment by classabbyamp** [comment]
just update this one

**Comment by OoLunar** [comment]
`-DDPP_USE_EXTERNAL_JSON=ON` has been readded and everything compiles as expected. PR is ready for merge.

**Comment by OoLunar** [comment]
Is there anything holding back this PR from being merged?

**Comment by braindigitalis** [comment]
chiming in; is there anything i can do as the project maintainer to help get this into void sooner?

**Comment by classabbyamp** [comment]
next time, don't create multiple commits for multiple versions of the same package, do it in 1 commit

**Pull request merged**
