### PR TITLE
dtrx: update to 8.0.1.

### PR DESCRIPTION
**Pull request by travankor**
closes #26586

### CODE REVIEW

**Comment by ericonr** [comment]
Build errors on musl about missing Python headers, kinda weird.

**Comment by travankor** [comment]
I successfully cross-build `x86_64-musl` locally and didn't run into that error.

**Comment by ericonr** [comment]
Fails on native build, I just tried locally.

**Comment by sgn** [comment]
On 2020-11-24 20:12:03-0800, Érico Nogueira Rolim <notifications@github.com> wrote:
> Build errors on musl about missing Python headers, kinda weird.

Nothing is weird!

If a template has pip and wheel in hostmakedepends, it's just plain wrong.

**Comment by ericonr** [comment]
> If a template has pip and wheel in hostmakedepends, it's just plain wrong.

Oops, hadn't noticed! I hunted for easy install messages, but didn't see any :D 

So yeah, it probably needs `python3-devel`

**Comment by sgn** [comment]
Let's not over-complicated things.

```diff
diff --git a/srcpkgs/dtrx/template b/srcpkgs/dtrx/template
index 84cf0ed2b3..d8e44456da 100644
--- a/srcpkgs/dtrx/template
+++ b/srcpkgs/dtrx/template
@@ -2,11 +2,15 @@
 pkgname=dtrx
 version=8.0.1
 revision=1
-build_style=python3-module
-hostmakedepends="python3-setuptools python3-pip python3-wheel"
+depends="python3"
 short_desc="Tool that takes all the hassle out of extracting archives"
 maintainer="travankor <travankor@tuta.io>"
 license="GPL-3.0-or-later"
 homepage="https://github.com/dtrx-py/dtrx/"
 distfiles="https://github.com/dtrx-py/dtrx/archive/${version}.tar.gz"
 checksum=4c37b16b741785d1db17c4561da647a52a182472f12758a39a9f03518b9dd17f
+python_version=3
+
+do_install() {
+	vbin scripts/dtrx
+}
```

**Pull request merged**
