### PR TITLE
linux6.10: enabled X86_USER_SHADOW_STACK for x86_64 [ci skip]

### PR DESCRIPTION
**Pull request by gfelber**
enabling X86_USER_SHADOW_STACK inside the kernel dotconfig for x86_64 to improve user land binary security.

Control-flow Enforcement Technology (CET) Shadow Stack https://docs.kernel.org/next/x86/shstk.html

#### Testing the changes
- I tested the changes in this PR: briefly

### CODE REVIEW

**Comment by gfelber** [comment]
Update: 
I build and installed this change locally (x86_64-musl) and didn't run into any problems.

**Comment by vincele** [comment]
Are the listed requirements also met (suitable libraries, etc.) ?

**Comment by gfelber** [comment]
Well it's basically just a new CPU hardware feature, most linkers don't seem to ship with support yet but the kernel already allows using it in combination with prctl.

Enabling this config would just provide another possible hardware security feature that tools can make use of, it doesn't affect existing stuff (or the current void ecosystem) as far as I know.

Also other distros notably arch already ship with this config enabled and it didn't cause any problems.

**Comment by vincele** [comment]
Yes, it should be harmless to enable it in the kernel config now, support for the other pieces of the puzzle can come later.

**Comment by leahneukirchen** [comment]
Please rebase on 6.10.

**Comment by leahneukirchen** [comment]
What ever that was, it wasn't good. :D try again

**Comment by gfelber** [comment]
welp I guess the rebase didn't work correctly, just gonna hard reset and add the fix again

**Comment by gfelber** [comment]
ok this looks better, if you don't like the force push i can create a new pull request with a clean commit

**Comment by leahneukirchen** [comment]
Can you format it like `linux6.10: ...`? Thanks.

**Pull request merged**
