### PR TITLE
wine: update to 8.13.

### PR DESCRIPTION
**Pull request by fvalasiad**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by mhmdanas** [comment]
Works fine for me on x86_64-glibc.

**Comment by classabbyamp** [comment]
cc @Hoshpak

**Comment by Hoshpak** [comment]
It fails to build on x86_64-musl:
https://github.com/void-linux/void-packages/actions/runs/5636252950/job/15268168529?pr=45202

This needs to be solved before the package can  be updated.

**Comment by fvalasiad** [comment]
@Hoshpak Reading the logs I suspect this is a case of a missing include.

An undefined macro next to a variable declaration with a forward-declared struct.

I will look into it.

**Comment by fvalasiad** [comment]
After some digging I found the commit that broke musl support

```
commit 41cc117b3f37ab4b9b4ac8a815cd2a496d38fb4b (HEAD)
Author: Billy Laws <blaws05@gmail.com>
Date:   Sat Jun 3 21:57:42 2023 +0100

commit 41cc117b3f37ab4b9b4ac8a815cd2a496d38fb4b (HEAD)
Author: Billy Laws <blaws05@gmail.com>
Date:   Sat Jun 3 21:57:42 2023 +0100

    server: Avoid using SOL_IPX to detect whether IPX is supported.

diff --git a/server/sock.c b/server/sock.c
index 088e6d63079..34be6ea22ef 100644
--- a/server/sock.c
+++ b/server/sock.c
@@ -62,6 +62,7 @@
 
 #ifdef HAVE_NETIPX_IPX_H
 # include <netipx/ipx.h>
+# define HAS_IPX
 #elif defined(HAVE_LINUX_IPX_H)
 # ifdef HAVE_ASM_TYPES_H
 #  include <asm/types.h>
@@ -70,8 +71,6 @@
 #  include <linux/types.h>
 # endif
 # include <linux/ipx.h>
-#endif
-#if defined(SOL_IPX) || defined(SO_DEFAULT_HEADERS)
 # define HAS_IPX
 #endif
```

the problem with it is at the following code:
```
#ifdef HAS_IPX
        int ipx_type = protocol - WS_NSPROTO_IPX;

#ifdef SOL_IPX
        setsockopt( sockfd, SOL_IPX, IPX_TYPE, &ipx_type, sizeof(ipx_type) );
#else
        struct ipx val;
        /* Should we retrieve val using a getsockopt call and then
         * set the modified one? */
        val.ipx_pt = ipx_type;
        setsockopt( sockfd, 0, SO_DEFAULT_HEADERS, &val, sizeof(val) );
#endif
#endif
```

previously `HAS_IPX` wasn't defined at all, now it is defined while `SOL_IPX` isn't and so we branch to #else without checking for the existence of `SO_DEFAULT_HEADERS` as the macro originally did.

I will consider reverting the commit to upstream wine.

**Comment by fvalasiad** [comment]
Relevant PR: https://gitlab.winehq.org/wine/wine/-/merge_requests/3403

**Comment by fvalasiad** [comment]
Update: The pull request was approved, wine on musl is back! Probably will be included with the next wine version, 8.14

@Hoshpak Until then, do we apply the patch to the package and ship it, or do we wait until wine does?

**Comment by Hoshpak** [comment]
Thanks for the great work! Feel free to include the patch and let's get this update merged.

**Pull request merged**
