### PR TITLE
ansible: update to 2.9.14

### PR DESCRIPTION
**Pull request by PaperMountainStudio**
I tried added some dependencies to checkdepends, thanks to which, the tests don't fail, but... there is 0 of them.

```
...
warning: no previously-included files matching '*.pyc' found under directory 'docs/docsite/_extensions'
warning: no previously-included files matching '*.pyo' found under directory 'docs/docsite/_extensions'
warning: no previously-included files found matching 'test/sanity/code-smell/botmeta.*'
writing manifest file 'lib/ansible.egg-info/SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

### CODE REVIEW

**Review by Piraty — COMMENTED** [review]
```
do_check() {                                                                    
PYTHONPATH=$(pwd)/build/lib python3 -m pytest                               
}
```

**Comment by PaperMountainStudio** [comment]
@Piraty thank you for your help, but it keeps failing. If you want to fix the tests, feel free to open a new issue replacing this one, otherwise I think I will have to disable the tests again.
```
=> ansible-2.9.14_1: running do_check ...
============================= test session starts ==============================
platform linux -- Python 3.9.0, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
rootdir: /builddir/ansible-2.9.14
collected 10924 items / 11 errors / 22 skipped / 10891 selected

==================================== ERRORS ====================================
_ ERROR collecting test/ansible_test/validate-modules-unit/test_validate_modules_regex.py _
ImportError while importing test module '/builddir/ansible-2.9.14/test/ansible_test/validate-modules-unit/test_validate_modules_regex.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/ansible_test/validate-modules-unit/test_validate_modules_regex.py:7: in <module>
    from validate_modules.main import TYPE_REGEX
E   ModuleNotFoundError: No module named 'validate_modules'
____ ERROR collecting test/integration/targets/async/library/async_test.py _____
test/integration/targets/async/library/async_test.py:43: in <module>
    main()
test/integration/targets/async/library/async_test.py:16: in main
    module = AnsibleModule(
build/lib/ansible/module_utils/basic.py:728: in __init__
    self._load_params()
build/lib/ansible/module_utils/basic.py:1962: in _load_params
    self.params = _load_params()
build/lib/ansible/module_utils/basic.py:621: in _load_params
    buffer = sys.stdin.buffer.read()
/usr/lib/python3.9/site-packages/_pytest/capture.py:216: in read
    raise OSError(
E   OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.
__ ERROR collecting test/integration/targets/async_fail/library/async_test.py __
test/integration/targets/async_fail/library/async_test.py:50: in <module>
    main()
test/integration/targets/async_fail/library/async_test.py:17: in main
    module = AnsibleModule(
build/lib/ansible/module_utils/basic.py:728: in __init__
    self._load_params()
build/lib/ansible/module_utils/basic.py:1962: in _load_params
    self.params = _load_params()
build/lib/ansible/module_utils/basic.py:621: in _load_params
    buffer = sys.stdin.buffer.read()
/usr/lib/python3.9/site-packages/_pytest/capture.py:216: in read
    raise OSError(
E   OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.
________ ERROR collecting test/integration/targets/cli/test_k_and_K.py _________
test/integration/targets/cli/test_k_and_K.py:17: in <module>
    '-m command -a whoami -Kkb --become-user cliuser2 localhost'.format(sys.argv[1]),
E   IndexError: list index out of range
____ ERROR collecting test/integration/targets/expect/files/test_command.py ____
test/integration/targets/expect/files/test_command.py:11: in <module>
    user_input = input_function(prompt)
/usr/lib/python3.9/site-packages/_pytest/capture.py:216: in read
    raise OSError(
E   OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.
------------------------------- Captured stdout --------------------------------
foo
_ ERROR collecting test/integration/targets/module_utils/library/test_env_override.py _
ImportError while importing test module '/builddir/ansible-2.9.14/test/integration/targets/module_utils/library/test_env_override.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/integration/targets/module_utils/library/test_env_override.py:6: in <module>
    from ansible.module_utils.json_utils import data
E   ImportError: cannot import name 'data' from 'ansible.module_utils.json_utils' (/builddir/ansible-2.9.14/build/lib/ansible/module_utils/json_utils.py)
_ ERROR collecting test/integration/targets/module_utils/library/test_failure.py _
test/integration/targets/module_utils/library/test_failure.py:14: in <module>
    AnsibleModule(argument_spec=dict()).exit_json(**results)
build/lib/ansible/module_utils/basic.py:728: in __init__
    self._load_params()
build/lib/ansible/module_utils/basic.py:1962: in _load_params
    self.params = _load_params()
build/lib/ansible/module_utils/basic.py:621: in _load_params
    buffer = sys.stdin.buffer.read()
/usr/lib/python3.9/site-packages/_pytest/capture.py:216: in read
    raise OSError(
E   OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.
_ ERROR collecting test/integration/targets/module_utils/library/test_override.py _
ImportError while importing test module '/builddir/ansible-2.9.14/test/integration/targets/module_utils/library/test_override.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/integration/targets/module_utils/library/test_override.py:3: in <module>
    from ansible.module_utils.facts import data
E   ImportError: cannot import name 'data' from 'ansible.module_utils.facts' (/builddir/ansible-2.9.14/build/lib/ansible/module_utils/facts/__init__.py)
_ ERROR collecting test/integration/targets/plugin_namespace/filter_plugins/test_filter.py _
import file mismatch:
imported module 'test_filter' has this __file__ attribute:
  /builddir/ansible-2.9.14/test/integration/targets/collections_plugin_namespace/collection_root/ansible_collections/my_ns/my_col/plugins/filter/test_filter.py
which is not the same as the test file we want to collect:
  /builddir/ansible-2.9.14/test/integration/targets/plugin_namespace/filter_plugins/test_filter.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
_ ERROR collecting test/integration/targets/plugin_namespace/test_plugins/test_test.py _
import file mismatch:
imported module 'test_test' has this __file__ attribute:
  /builddir/ansible-2.9.14/test/integration/targets/collections_plugin_namespace/collection_root/ansible_collections/my_ns/my_col/plugins/test/test_test.py
which is not the same as the test file we want to collect:
  /builddir/ansible-2.9.14/test/integration/targets/plugin_namespace/test_plugins/test_test.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
_____ ERROR collecting test/integration/targets/throttle/test_throttle.py ______
test/integration/targets/throttle/test_throttle.py:11: in <module>
    throttledir, inventory_hostname, max_throttle = sys.argv[1:]
E   ValueError: not enough values to unpack (expected 3, got 0)
=========================== short test summary info ============================
ERROR test/ansible_test/validate-modules-unit/test_validate_modules_regex.py
ERROR test/integration/targets/async/library/async_test.py - OSError: pytest:...
ERROR test/integration/targets/async_fail/library/async_test.py - OSError: py...
ERROR test/integration/targets/cli/test_k_and_K.py - IndexError: list index o...
ERROR test/integration/targets/expect/files/test_command.py - OSError: pytest...
ERROR test/integration/targets/module_utils/library/test_env_override.py
ERROR test/integration/targets/module_utils/library/test_failure.py - OSError...
ERROR test/integration/targets/module_utils/library/test_override.py
ERROR test/integration/targets/plugin_namespace/filter_plugins/test_filter.py
ERROR test/integration/targets/plugin_namespace/test_plugins/test_test.py
ERROR test/integration/targets/throttle/test_throttle.py - ValueError: not en...
!!!!!!!!!!!!!!!!!!! Interrupted: 11 errors during collection !!!!!!!!!!!!!!!!!!!
======================= 22 skipped, 11 errors in 48.26s ========================
=> ERROR: ansible-2.9.14_1: do_check: 'PYTHONPATH=$(pwd)/build/lib python3 -m pytest' exited with 2
=> ERROR:   in do_check() at srcpkgs/ansible/template:26
```

**Comment by Piraty** [comment]
@the-maldridge

**Comment by PaperMountainStudio** [comment]
superseeded by #25774

**Pull request closed without merging**
