### PR TITLE
chezmoi: update to 2.0.2.

### PR DESCRIPTION
**Pull request by titouanco**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
@classabbyamp ok?

**Comment by classabbyamp** [comment]
v2.0.2 is now available and I was going to get around to updating this tonight/this weekend. Wanted to ensure there wasn't anything that needed changes because it's a major version bump.

**Comment by titouanco** [comment]
I'll make a new commit for the 2.0.2 in a few minutes

**Comment by ericonr** [comment]
@classabbyamp I can wait for an approval from you, if you wish to confirm everything is fine.

**Comment by ericonr** [comment]
From my quick skim of the changelog, this PR looks ok.

**Review by classabbyamp — APPROVED** [review]

**Comment by ericonr** [comment]
Well, that works :)

Thanks!

**Pull request merged**
