### PR TITLE
etckeeper: update to 1.18.21, support xbps, run tests

### PR DESCRIPTION
**Pull request by dkwo**
- I tested the changes in this PR: yes
- I built this PR locally for my native architecture, (`x86_64-musl`)

A couple of tests fail, likely due to `fakeroot` or similar.

### CODE REVIEW

**Comment by dkwo** [comment]
```
not ok 8 root_test: create file owned by bin:daemon
# (in test file test-etckeeper, line 88)
#   `install -o $owner -g $group -m $mode /dev/null $testdir/$testfile' failed
# install: invalid user ‘bin’
```

**Comment by dkwo** [comment]
locally:
```
not ok 7 root_test: create file owned by root:root
# (in test file test-etckeeper, line 75)
#   `install -o $owner -g $group -m $mode /dev/null $testdir/$testfile' failed
# install: cannot change ownership of '/tmp/tmp.XUHYBeCFoX/file5': Invalid argument
not ok 8 root_test: create file owned by bin:daemon
# (in test file test-etckeeper, line 88)
#   `install -o $owner -g $group -m $mode /dev/null $testdir/$testfile' failed
# install: invalid user ‘bin’
```

**Comment by zevweiss** [comment]
Bump?

**Comment by zevweiss** [comment]
Bump...though current upstream is now at 1.18.21, FWIW.

**Comment by zevweiss** [comment]
Thanks!

**Pull request merged**
