### PR TITLE
[wip] mesa: update to 21.0.0.

### PR DESCRIPTION
**Pull request by HadetTheUndying**
Reason for changing to the `-Dosmesa` argument:

https://gitlab.freedesktop.org/mesa/mesa/-/commit/ee802372180a2b4460cc7abb53438e45c6b6f1e4

Obviously i'll be fixing the distfiles and wrksrc changes when a stable release is out.

### CODE REVIEW

**Comment by ericonr** [comment]
```
Using 'LDFLAGS' from environment with value: '-Wl,-z,relro -Wl,-z,now -Wl,--as-needed    '
Using 'CPPFLAGS' from environment with value: '   '
C++ compiler for the host machine: g++ (gcc 9.3.0 "g++ (GCC) 9.3.0")
C++ linker for the host machine: g++ ld.bfd 2.35.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
meson.build:92: WARNING: gles1 option "true" deprecated, please use "enabled" instead.
meson.build:100: WARNING: gles2 option "true" deprecated, please use "enabled" instead.
meson.build:119: WARNING: shared-glapi option "true" deprecated, please use "enabled" instead.
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency clang found: NO (tried cmake)
meson.build:393: WARNING: gbm option "true" deprecated, please use "enabled" instead.
meson.build:424: WARNING: egl option "true" deprecated, please use "enabled" instead.
meson.build:504: WARNING: dri3 option "true" deprecated, please use "enabled" instead.
meson.build:527: WARNING: gallium-vdpau option "true" deprecated, please use "enabled" instead.
Using 'PKG_CONFIG' from environment with value: 'pkg-config'
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency vdpau found: YES 1.4
Program glslangValidator found: YES
meson.build:587: WARNING: gallium-xvmc option "true" deprecated, please use "enabled" instead.
```

we should take a look at these deprecation warnings.

**Comment by HadetTheUndying** [comment]
I'll take a look at that in the morning

**Comment by HadetTheUndying** [comment]
Popping up branch conflicts over the version number in the template, someone wanna walk me through how to resolve this because i really don't understand.

**Comment by HadetTheUndying** [comment]
I may not have time to continue working on this. Most of the work is great l already done if someone wants to take over on it. 21.0.1 is the next release though i think we should wait for llvm12 because there are some bugs that have popped up compiling against 11.0.0 that 11.0.1 fixes.

**Pull request closed without merging**
