### PR TITLE
New package: SatDump-1.2.0

### PR DESCRIPTION
**Pull request by agausmann**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

### CODE REVIEW

**Comment by agausmann** [comment]
aaa, the tagged release is pretty old, it checks the host `/proc/cpuinfo` for SIMD features instead of checking the compiler, which breaks cross-compile.
Looks like that has since improved on the master branch.

**Comment by abenson** [comment]
Can you backport that patch?

**Comment by agausmann** [comment]
It doesn't seem like it can be cleanly backported to me.

There are [a lot of changes](https://github.com/SatDump/SatDump/compare/1.0.3...master) between the latest release and master, about 8 months and 767 commits. 

The commits for the SIMD are in the middle of that and also affected a lot of code at the same time, not just CMake. (Roughly https://github.com/SatDump/SatDump/compare/d4f9ff8da127d7507780cb07de349ec4c18990b0...e8135363c2c30328d724ffbc422ed227669e9e96)

May be better to just wait for the next release

**Comment by agausmann** [comment]
They've recently released an update. Works fine on x86_64, currently running some tests on aarch64

**Comment by agausmann** [comment]
aarch64 looks good too

**Comment by agausmann** [comment]
bump

**Comment by classabbyamp** [comment]
please rebase to resolve conflicts

**Pull request merged**
