### PR TITLE
onedrive: update to 2.4.19

### PR DESCRIPTION
**Pull request by abraunegg**
#### Testing the changes
- I tested the changes in this PR: **NO**

**NB:** I am the upstream developer, this change only changes the sha256sum & version number of the 'onedrive' upstream package that void uses.

### CODE REVIEW

**Comment by paper42** [comment]
Please drop the commit body, it's a duplicate of the commit title. I will mark this with help-wanted, so someone can test this.

**Comment by ericonr** [comment]
@selfisekai are you available to test it?

**Comment by ericonr** [comment]
ok, np! thanks for the quick answer :)

**Comment by abraunegg** [comment]
@ericonr
PR updated as v2.4.18 has been released upstream

**Comment by abraunegg** [comment]
@ericonr
PR updated as v2.4.19 has been released upstream

**Comment by abraunegg** [comment]
Closing this - someone in the Void Linux community can look at this.

**Pull request closed without merging**
