### PR TITLE
common/shlibs:  remove entries from packages that don't exist anymore

### PR DESCRIPTION
**Pull request by maxice8**
This removes entries from packages that are available in the repos but not used by any package.

### CODE REVIEW

**Comment by maxice8** [comment]
This was tested by getting shlib-requires from every package in the main repo from these archs:

- x86_64
- i686
- armv6l
- armv7l
- aarch64
- x86_64-musl
- armv6l-musl
- armv7l-musl
- aarch64-musl

1. Set up void-chroots
```
$ cat /home/terran/bin/setup-voidchroots
#!/bin/sh
for arch in armv6l armv7l x86_64
do
	yes | env XBPS_ARCH=$arch xbps-install -S -R https://alpha.de.repo.voidlinux.org/current -r ~/var/lib/machines/void-strap-$arch base-files xbps -y
	yes | env XBPS_ARCH=$arch-musl xbps-install -S -R https://alpha.de.repo.voidlinux.org/current/musl -r ~/var/lib/machines/void-strap-$arch-musl base-files xbps -y
done

yes | env XBPS_ARCH=i686 xbps-install -S -R https://alpha.de.repo.voidlinux.org/current -r ~/var/lib/machines/void-strap-i686 base-files xbps -y

yes | env XBPS_ARCH=aarch64-musl xbps-install -S -R https://alpha.de.repo.voidlinux.org/current/aarch64 -r ~/var/lib/machines/void-strap-aarch64-musl base-files xbps -y

yes | env XBPS_ARCH=aarch64 xbps-install -S -R https://alpha.de.repo.voidlinux.org/current/aarch64 -r ~/var/lib/machines/void-strap-aarch64 base-files xbps -y
```

2. Sync them
```
$ cat /home/terran/bin/sync-voidchroots
#!/bin/sh
for arch in armv6l armv7l x86_64
do
	echo "> syncing $arch"
	env XBPS_ARCH=$arch xbps-install -R https://alpha.de.repo.voidlinux.org/current -r ~/var/lib/machines/void-strap-$arch -S
	echo "> syncing $arch-musl"
	env XBPS_ARCH=$arch-musl xbps-install -R https://alpha.de.repo.voidlinux.org/current/musl -r ~/var/lib/machines/void-strap-$arch-musl -S
done

echo "> syncing i686"
	env XBPS_ARCH=i686 xbps-install -R https://alpha.de.repo.voidlinux.org/current -r ~/var/lib/machines/void-strap-i686 -S

echo "> syncing aarch64"
env XBPS_ARCH=aarch64 xbps-install -R https://alpha.de.repo.voidlinux.org/current/aarch64 -r ~/var/lib/machines/void-strap-aarch64 -S

echo "> syncing aarch64-musl"
env XBPS_ARCH=aarch64-musl xbps-install -R https://alpha.de.repo.voidlinux.org/current/aarch64 -r ~/var/lib/machines/void-strap-aarch64-musl -S
```

3. List all shlibs that don't return anything
```
$ cat /home/terran/bin/find-unused-shlibs
#!/bin/sh
#
shlib_list=$(mktemp)
for v in ~/var/lib/machines/void-strap-*
do
	varch="$(echo "$v" |grep -o -- '-[axi].*[0-9musl]')"
	env XBPS_ARCH="${varch##*-}" xbps-query -Rs '' -p shlib-requires -r "$v" >> "$shlib_list"
done

list_shlibs() {
	grep -v '^#' common/shlibs | while read -r line
	do
		linecount="$(echo "$line" | wc -w)"
		if [ "$linecount" -lt 3 ]
		then
			echo "$line"
		fi
	done
}
list_shlibs | while read -r lib
do
	deps="$(grep "$(echo "$lib" | cut -d ' ' -f1)" $shlib_list)"
	if [ -z "$deps" ]
	then
#		echo "$lib"
		sed -i "/$lib/d" common/shlibs
	fi
done

rm -f "$shlib_list"
```

**Comment by maxice8** [comment]
libunwind-mips is the only obvious casualty i can see.

**Comment by bra1nwave** [comment]
Why? What will we gain out of this?

For example, let's say I decided to make a template for a package. That package requires `libgnuradio-audio-3.7.13.4.so.0.0.0`.
Now I have to create a separate commit (`gnuradio: add libgnuradio-audio entry to shlibs`), 
just to add it back.

And I (or someone else) has to do this everytime, for every package that requires a removed lib from this list.

IMHO this is a case of _Verschlimmbesserung_.

**Comment by Vaelatern** [comment]
I'd rather only packages that we no longer provide (old libressl, old ffmpeg) should have their shlibs purged.

**Comment by maxice8** [comment]
> I'd rather only packages that we no longer provide (old libressl, old ffmpeg) should have their shlibs purged.

i can get that arranged, also was what my previous iteration was about

**Comment by maxice8** [comment]
updated to remove only entries from packages not in the repos.

**Pull request merged**
