### PR TITLE
efibootmgr: correct install message

### PR DESCRIPTION
**Pull request by NeelChotai**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Wow, this install msg is huge. Do you think it could be moved to `README.voidlinux` file instead? Or even partly to void-docs... Having this fly by during installation makes it very easy to miss other important ones. (You're also missing a revbump).

**Comment by NeelChotai** [comment]
> Wow, this install msg is huge. Do you think it could be moved to `README.voidlinux` file instead? Or even partly to void-docs... Having this fly by during installation makes it very easy to miss other important ones. (You're also missing a revbump).

Added a README.voidlinux and revbumped, thanks for the reminder.

Strangely, efivars only needs to be manually mounted on my Dell systems. My PC mounts efivars automatically just fine.

**Comment by ahesford** [comment]
I think it would be reasonable to move the entire contents of this to README.voidlinux and make the install message nothing more than

> See /usr/share/doc/efibootmgr/README.voidlinux for instructions on using efibootmgr to automatically manage EFI boot entries.

I believe `/sys/firmware/efi/efivars` might automatically mounted by elogind for some reason. Systems without elogind probably need to mount it explicitly.

**Comment by NeelChotai** [comment]
> I think it would be reasonable to move the entire contents of this to README.voidlinux and make the install message nothing more than
> 
> > See /usr/share/doc/efibootmgr/README.voidlinux for instructions on using efibootmgr to automatically manage EFI boot entries.
> 
> I believe `/sys/firmware/efi/efivars` might automatically mounted by elogind for some reason. Systems without elogind probably need to mount it explicitly.

That explains it, and your suggestion sounds good - implemented.

**Review by ahesford — APPROVED** [review]

**Pull request merged**
