### PR TITLE
linux5.4: Add first support for RK3399 boards

### PR DESCRIPTION
**Pull request by repk**
This adds built-in configuration for RK808 Power Management System, RK3x
I2C, as well as rockhip's MMC controller driver in order to be able to
boot RK3399 boards on SD card. This also adds module for thermal sensor,
PCIe, USB and EMMC.

This has been tested on Nanopi-m4 board.

### CODE REVIEW

**Comment by Piraty** [comment]
Nice work (didn't test though because I don't have related hardware).
Please apply to 5.5 and all LTS kernels (if applicable) as well

**Comment by repk** [comment]
Sure, same PR or a different one ?

**Comment by Piraty** [comment]
same PR, one commit for every kernel

**Comment by repk** [comment]
Ok for 5.5. 4.19 seems a bit too old to be reliable, but will try, 4.14 and before definitely are too old though.

**Comment by repk** [comment]
I have just added and tested 5.5 that boots also fine. For 4.19 though the only RK3399 board I have has no device tree support yet, it's up to you if you want to merge it anyway.
Older LTS does not have reliable mainstream RK3399 support.

**Comment by Piraty** [comment]
of course it only makes sense for kernels that support the hardware.

**Comment by repk** [comment]
RK3399 boards seem supported on 4.19 just not my board

**Comment by Piraty** [comment]
is it reasonable to enable the same switches for arm32?

**Comment by repk** [comment]
I am not sure to get the point of that as I don't know of any 32bit boards that could benefit of that, but it should not harm though.

**Comment by Piraty** [comment]
changes will be shipped with the next kernel rebuild rebuild (likely update)

**Pull request closed without merging**
