### PR TITLE
zstd: update to 1.4.8

### PR DESCRIPTION
**Pull request by 4ricci**

### CODE REVIEW

**Comment by 4ricci** [comment]
`do_check()` is failing on the (i686, i686, 1). I tested locally on x86_64-glibc with a i686 masterdir, but I cannot reproduce the failure.

**Comment by pullmoll** [comment]
The check prints the problem:
```
zstd: util.c:351: readLinesFromFile: Assertion `pos + lineLength < dstCapacity' failed.
```
Seems like this could be an integer overrun. Hint: `sizeof(long)` is 4 for 32 bit vs. 8  for 32 bit.
No time to further investigate this, though.

**Comment by ericonr** [comment]
I will try to check upstream.

**Comment by 4ricci** [comment]
The problem was fixed [here](https://github.com/facebook/zstd/commit/ae85676d44baee3d12168a5c929347b3836f2cf2).

**Comment by ericonr** [comment]
I think they are going to make a hot fix release, we can probably wait for that. It's good that their code caught alignment issues; on i686 it's indeed not an issue, but it could kill the process with SIGBUS on `armv*`

**Comment by ericonr** [comment]
I fixed the commit message before pushing, thanks!

**Pull request closed without merging**
