### PR TITLE
lxd-lts update to 4.0.4 + Sqlite replication drop

### PR DESCRIPTION
**Pull request by fosslinux**
lxd-lts update is to drop the need for sqlite-replication in the template.

`sqlite-replication` has not been needed for some time after dqlite moved to mainstream sqlite.

### CODE REVIEW

**Review by ericonr — APPROVED** [review]
Looks good to me, but I can't evaluate the resulting package.

@CameronNemo ?

**Comment by CameronNemo** [comment]
removed packages need special care but I do not know the specifics of that. Looks fine to me.

**Comment by fosslinux** [comment]
#23575 is where we do that

**Comment by ericonr** [comment]
Does `sqlite-replication` need special handling in `removed-packages`?

**Comment by fosslinux** [comment]
Yes, it does now that it exists, done.

**Pull request merged**
