### PR TITLE
Add general localized man pages, remove hook that removes them.

### PR DESCRIPTION
**Pull request by ericonr**
Why does this hook exist? `mdocml` doesn't seem to support localized pages, but `man-db` does.

I need some help on the `manpages-l10n` package, since setting `build_style=meta` would force me to manually specify a lot of functions for no gain, and the license shouldn't be `vlicense`d. So `xbps-src` is complaining the package is empty :/ 

The `short_descs` also still need to be updated.

---

`mdocml` supports this, as long as it's configured in `/etc/man.conf`.

### CODE REVIEW

**Comment by fosslinux** [comment]
Generally the commits for stuff in `common` seems to be `common/hooks: XYZ` or something like `common/hooks/post-install/01-remove-localized-manpages.sh: remove`. TBH I thought there was a package `remove-localized-manpages` when I saw this...

**Comment by ericonr** [comment]
@void-linux/pkg-committers is there a reason why localized man pages were explicitly removed from packages?

**Comment by Chocimier** [comment]
> I need some help on the `manpages-l10n` package, since setting `build_style=meta` would force me to manually specify a lot of functions for no gain, and the license shouldn't be `vlicense`d. So `xbps-src` is complaining the package is empty :/

As `manpages-l10n` is empty and depend on nothing, maybe remove it and make one of actual packages main one.

**Comment by ericonr** [comment]
Fixed the commit message and the empty package situation. Should be good now.

**Comment by ericonr** [comment]
This will require an entry in docs about enabling man pages in other languages as well.

**Pull request merged**
