### PR TITLE
gnome 3.38

### PR DESCRIPTION
**Pull request by q66**
This should now be more or less ready. Tested on `aarch64` and on `ppc64le-musl`. Several "unstable" versions were used, since 3.38 shipped with them (e.g. `gnome-online-accounts`, `gnome-contacts` and the `gnome-flashback` components), shouldn't be a practical problem and we can update them later once tagged.

# TODO

- [x] clean it up
- [x] better testing, make sure testsuite passes
- [x] import the useful bits from #21382, or rebase if it gets merged
- [x] make sure crossbuilds work
- [x] test on more platforms
- [x] fix the metapackages (they haven't been touched, possibly in https://github.com/void-linux/void-packages/pull/22936)
- ~~drop the `vala` option in the rest of the packages~~ probably gonna do that once this PR is merged

# Stable updates

- [x] yelp-xsl -> 3.38.0
- [x] yelp-tools -> 3.38.0
- [x] yelp -> 3.38.0
- [x] vala -> 0.50.0
- [x] valadoc -> 0.50.0 
- [x] valabind -> (revbump) 
- [x] devhelp -> 3.38.0
- [x] gdl -> 3.34.0
- [x] libsoup -> 2.72.0
- [x] grilo -> 0.3.13
- [x] grilo-plugins -> 0.3.12
- [x] gtksourceview4 -> 4.8.0
- [x] tepl -> 5.0.0
- [x] glade3 -> 3.38.0
- [x] libhandy -> (revbump)
- [x] libhandy1 -> 1.0.0
- [x] libxfce4ui -> (revbump)
- [x] libdazzle -> 3.38.0
- [x] anjuta -> (revbump)
- [x] sysprof -> 3.38.0
- [x] tracker -> 2.3.6
- [x] tracker-miners -> 2.3.5
- [x] tracker3 -> 3.0.0 **(new)**
- [x] tracker3-miners -> 3.0.0 **(new)**
- [x] bijiben -> 3.36.3
- [x] graphene -> 1.10.2
- [x] amtk -> 5.2.0
- [x] io.elementary.code -> (revbump)
- [x] phodav -> 2.5
- [x] gsettings-desktop-schemas -> 3.38.0
- [x] glib-networking -> 2.66.0
- [x] at-spi2-core -> 2.38.0
- [x] at-spi2-atk -> 2.38.0
- [x] libgweather -> 3.36.1
- [x] gnome-menus -> 3.36.0
- [x] gnome-desktop -> 3.38.0
- [x] gnome-settings-daemon -> 3.38.0
- [x] mutter -> 3.38.0
- [x] cheese -> 3.38.0
- [x] evolution-data-server -> 3.38.0
- [x] folks -> 0.14.0
- [x] gnome-online-accounts -> 3.37.90
- [x] gvfs -> 1.46.0
- [x] gnome-control-center -> 3.38.0
- [x] dconf-editor -> 3.38.0
- [x] gjs -> 1.66.0
- [x] gnome-shell -> 3.38.0
- [x] gnome-shell-extensions -> 3.38.0
- [x] gdm -> 3.38.0
- [x] gnome-session -> 3.38.0
- [x] gnome-initial-setup -> 3.38.0
- [x] xdg-desktop-portal-gtk -> 1.8.0
- [x] nautilus -> 3.38.0
- [x] gnome-maps -> 3.38.0
- [x] evolution -> 3.38.0
- [x] evolution-ews -> 3.38.0
- [x] python3-atspi -> 2.38.0
- [x] python-atspi -> 2.38.0
- [x] orca -> 3.38.0
- [x] gnome-weather -> (revbump)
- [x] vte3 -> 0.62.0
- [x] gnome-terminal -> 3.38.0
- [x] gnome-getting-started-docs -> 3.36.2
- [x] gnome-user-docs -> 3.38.0
- [x] gnome-epub-thumbnailer -> 1.6
- [x] gnome-books -> (revbump)
- [x] gnome-characters -> (revbump)
- [x] gnome-documents -> (revbump)
- [x] gnome-font-viewer -> (revbump)
- [x] totem -> 3.38.0
- [x] gnome-screensaver -> (revbump + build fix)
- [x] gnome-clocks -> 3.38.0
- [x] epiphany -> 3.38.0
- [x] gnome-contacts -> 3.37.2
- [x] gnome-photos -> 3.37.91.1
- [x] eog -> 3.38.0
- [x] evince -> 3.38.0
- [x] file-roller -> 3.38.0
- [x] gnome-calendar -> 3.38.0
- [x] gnome-music -> 3.38.0
- [x] gedit -> 3.38.0
- [x] gedit-plugins -> 3.38.0
- [x] gnome-latex -> 3.38.0
- [x] baobab -> 3.38.0
- [x] gnome-boxes -> 3.38.0
- [x] gnome-calculator -> 3.38.0
- [x] gnome-disk-utility -> 3.38.0
- [x] gnome-screenshot -> 3.38.0
- [x] gnome-system-monitor -> 3.38.0
- [x] adwaita-icon-theme -> 3.38.0
- [x] gnome-backgrounds -> 3.38.0
- [x] simple-scan -> 3.38.0
- [x] rygel -> 0.40.0
- [x] gnome-builder -> 3.38.0
- [x] retro-gtk -> 1.0.0
- [x] gnome-games -> 3.38.0
- [x] gnome-panel -> 3.37.1
- [x] metacity -> 3.37.1
- [x] gnome-flashback -> 3.37.3
- [x] budgie-desktop -> (rebuild)

## Merged

- [x] libsigc++3 -> 3.0.3 (new)
- [x] mm-common -> 1.0.1
- [x] glibmm -> 2.64.2
- [x] pangomm -> 2.42.1
- [x] libnotify -> 0.7.9
- [x] atk -> 2.36.0
- [x] gtk+3 -> 3.24.22
- [x] libportal -> 0.3 (new)
- [x] cogl -> 1.22.28
- [x] geocode-glib -> 3.26.2
- [x] gfbgraph -> 0.2.4
- [x] libgsf -> 1.14.47
- [x] libsecret -> 0.20.3
- [x] libchamplain -> 0.12.20
- [x] gom -> 0.4
- [x] gssdp -> 1.2.3
- [x] gtk-vnc -> 1.0.0 (drops unused gtk2 support)
- [x] gupnp -> 1.2.4
- [x] gnome-video-effects -> 0.5.0
- [x] glib -> 2.66.0
- [x] webkit2gtk -> 2.30.0
- [x] mozjs78 -> 78.2.0 (new)

## No updates

- polari (no newer stable version)
- gtk4 (no stable version yet)

### CODE REVIEW

**Comment by q66** [comment]
cc @mnabid @Gottox 

as for the existing 3.36 PR you can go ahead with it or if you want to wait for this one i don't mind either way

**Comment by mnabid** [comment]
> as for the existing 3.36 PR you can go ahead with it or if you want to wait for this one i don't mind either way

Well, GNOME 3.38 is a month away from releasing, so why not ? :+1: ( Also, I'm afraid I won't get enough time to work on #21382).

But @sgn was working on fixing the cross builds for some packages (especially the `evolution*` ones) , so I'll leave the PR open for now.

**Comment by q66** [comment]
tests are now passing fully on the packages that have been touched, also did assorted minor tweaks

i've also taken the liberty to start dropping the `vala` option in templates and merge it back with `gir`; i've never been able to find a reason to split them in the first place, and splitting them is actively harmful with the current system, since `vala` always depends on `gir`; either way, there is not much of a reason to ever disable it

**Comment by sgn** [comment]
On 2020-08-14 12:03:15-0700, Daniel Kolesa <notifications@github.com> wrote:
> i've also taken the liberty to start dropping the `vala` option in
> templates and merge it back with `gir`; i've never been able to find
> a reason to split them in the first place, and splitting them is
> actively harmful with the current system, since `vala` always
> depends on `gir`; either way, there is not much of a reason to ever
> disable it

I think this is a correct move.
I split out vala because its dependencies also split vala out.
It's better to merge all vala into gir.

-- 
Danh

**Comment by shizonic** [comment]
How can I test this locally?

**Comment by q66** [comment]
just fetch it, apply it in your tree, build it with xbps-src as usual, and test it?

**Comment by shizonic** [comment]
> just fetch it, apply it in your tree, build it with xbps-src as usual, and test it?

I checked out this PR locally into a branch called `gnome` and built it successfully (every gnome related packages were updated to the version of this PR) but if I run `xbps-install --repository hostdir/binpkgs gnome` I get the message `Package 'gnome' already installed.`. What did I miss? Thank you so much for all your work I really appreciate it.

**Comment by q66** [comment]
the metapackage is unchanged, you have to run like `xbps-install -R hostdir/binpkgs -Su`

**Comment by shizonic** [comment]
> the metapackage is unchanged, you have to run like `xbps-install -R hostdir/binpkgs -Su`

Thank you so much it worked! :-) Awesome job man.

**Comment by q66** [comment]
as for `gnome-shell` depending on `gdm`, we can't do that since `gdm` already depends on `gnome-shell`

**Comment by shizonic** [comment]
Do I have to rebuild every pkg if this PR gets updated? If not how do I manage to rebuild only the updated pkgs?

**Comment by fosslinux** [comment]
cross seems to be severely broken, just tried cross building for aarch64 and at least 3 packages failed, didn't try to get any further though

You probably already know this anyway.

**Comment by q66** [comment]
what failed?

**Comment by fosslinux** [comment]
Away from home computer ATM but definatly `gsettings-desktop-schemas` and I believe `libsoup`, I'll try again shortly.

**Comment by shizonic** [comment]
finally released: https://help.gnome.org/misc/release-notes/3.38/ 👍

**Comment by circhioz** [comment]
`libsoup` fails because of a regression in `brotli` (google/brotli#836)

**Comment by q66** [comment]
I restructured the metapackages; the following changes have been applied

1) `gnome-core` is a core distribution without applications that can be replaced
2) `gnome` is `gnome-core` plus core gnome applications that either don't take much space or are always useful (e.g. `file-roller`, `evince`, etc)
3) `gnome-apps` is an extra bundle of things which are either big or niche or will usually be replaced (e.h. `epiphany`, `evolution`, `gnome-boxes` and the like)

i removed the direct dependencies on the libraries, as that just hides messed up dependencies in the actual app/other packages, by installing them directly rather than being installed through the individual components

**Comment by fosslinux** [comment]
Will test shortly, thanks for all your work on this @q66!

**Comment by Gottox** [comment]
```
[121/174] Linking target libsoup/libsoup-2.4.so.1.11.0
FAILED: libsoup/libsoup-2.4.so.1.11.0 
armv7l-linux-gnueabihf-gcc  -o libsoup/libsoup-2.4.so.1.11.0 libsoup/libsoup-2.4.so.1.11.0.p/meson-generated_.._soup-resources.c.o libsoup/libsoup-2.4.so.1.11.0.p/meson-generated_.._soup-enum-types.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-address.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-auth.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-auth-basic.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-auth-digest.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-auth-ntlm.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-auth-negotiate.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-auth-domain.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-auth-domain-basic.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-auth-domain-digest.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-auth-manager.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-body-input-stream.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-body-output-stream.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-cache.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-cache-client-input-stream.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-cache-input-stream.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-client-input-stream.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-connection.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-connection-auth.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-content-decoder.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-content-processor.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-content-sniffer.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-content-sniffer-stream.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-converter-wrapper.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-cookie.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-cookie-jar.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-cookie-jar-db.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-cookie-jar-text.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-date.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-directory-input-stream.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-filter-input-stream.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-form.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-hsts-enforcer.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-hsts-enforcer-db.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-hsts-policy.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-headers.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-init.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-io-stream.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-logger.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-message.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-message-body.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-message-client-io.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-message-headers.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-message-io.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-message-queue.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-message-server-io.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-method.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-misc.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-multipart.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-multipart-input-stream.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-password-manager.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-path-map.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-proxy-resolver.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-proxy-resolver-default.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-proxy-resolver-wrapper.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-proxy-uri-resolver.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-request.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-request-data.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-request-file.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-request-http.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-requester.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-server.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-session.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-session-async.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-session-feature.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-session-sync.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-socket.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-socket-properties.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-status.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-tld.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-uri.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-value-utils.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-version.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-websocket.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-websocket-connection.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-websocket-extension.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-websocket-extension-deflate.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-websocket-extension-manager.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-xmlrpc.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-xmlrpc-old.c.o libsoup/libsoup-2.4.so.1.11.0.p/soup-brotli-decompressor.c.o -L/usr/armv7l-linux-gnueabihf/usr/lib -flto -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libsoup-2.4.so.1 -Wl,-z,relro -Wl,-z,now -Wl,--as-needed /usr/armv7l-linux-gnueabihf/usr/lib/libglib-2.0.so /usr/armv7l-linux-gnueabihf/usr/lib/libgobject-2.0.so /usr/armv7l-linux-gnueabihf/usr/lib/libgio-2.0.so /usr/armv7l-linux-gnueabihf/usr/lib/libxml2.so /usr/armv7l-linux-gnueabihf/usr/lib/libsqlite3.so /usr/armv7l-linux-gnueabihf/usr/lib/libpsl.so -R/usr/lib /usr/armv7l-linux-gnueabihf/usr/lib/libbrotlidec.so /usr/armv7l-linux-gnueabihf/usr/lib/libz.so -Wl,--end-group
armv7l-linux-gnueabihf-gcc: error: unrecognized command line option '-R'
[122/174] Compiling C object tests/tld-test.p/tld-test.c.o
[123/174] Compiling C object tests/ntlm-test-helper.p/ntlm-test-helper.c.o
[124/174] Compiling C object tests/brotli-decompressor-test.p/brotli-decompressor-test.c.o
[125/174] Compiling C object tests/timeout-test.p/timeout-test.c.o
[126/174] Compiling C object tests/streaming-test.p/streaming-test.c.o
[127/174] Compiling C object tests/ssl-test.p/ssl-test.c.o
[128/174] Compiling C object tests/uri-parsing-test.p/uri-parsing-test.c.o
[129/174] Compiling C object tests/websocket-test.p/websocket-test.c.o
ninja: build stopped: subcommand failed.
=> ERROR: libsoup-2.72.0_1: do_build: '${make_cmd} -C ${meson_builddir} ${makejobs} ${make_build_args} ${make_build_target}' exited with 1
=> ERROR:   in do_build() at common/build-style/meson.sh:122
[tox@krusty gnome]$ 
```
On armv7hf

**Comment by sgn** [comment]
> ```
> [121/174] Linking target libsoup/libsoup-2.4.so.1.11.0
> FAILED: libsoup/libsoup-2.4.so.1.11.0 
> armv7l-linux-gnueabihf-gcc: error: unrecognized command line option '-R'
> => ERROR:   in do_build() at common/build-style/meson.sh:122
> [tox@krusty gnome]$ 
> ```
> 
> On armv7hf

Please rebase against newest master, it's fixed by 6335ec8d1644ddbd660e6fa6a9a76ce50a3e9443

**Comment by pullmoll** [comment]
With gcc10 for me fails when trying to build `nautilus` with:
```
Program /usr/lib/tracker-3.0/trackertestutils/tracker-sandbox found: NO

test/automated/displayless/meson.build:3:0: ERROR: Program '/usr/lib/tracker-3.0/trackertestutils/tracker-sandbox' not found
```
Should this binary be installed with tracker3 or perhaps tracker3-devel?

**Comment by q66** [comment]
applied that locally, thanks @pullmoll

gonna push it out together with other potential fixes after i have crossbuilt all stuff

**Comment by q66** [comment]
all cross-compiling issues have been fixed, so i think this is ready for merge

**Comment by Gottox** [comment]
congrats! :heart:

**Comment by Gottox** [comment]
Two small comments:
* `gnome-todo` wasn't bumped but should as it links against evolution-data-server
* I would consider `bijiben` part of `gnome-apps`

**Comment by pullmoll** [comment]
Also `io.elementary.calendar` depends on `evolution-data-server` and needs to be bumped.
Not sure about `planner` while I think that one also. These were the packages I had to force rebuild to solve staging.

**Comment by sgn** [comment]
gtk4 should be updated, too. There's a conflict but will be fix by latest gtk4, see https://github.com/void-linux/void-packages/issues/24964

**Comment by q66** [comment]
bijiben is nocross, so no

gtk4 shouldn't be updated, it's not a part of the release and has no stable version

**Comment by sgn** [comment]
That's fine.

**Comment by Gottox** [comment]
Cross build of bijiben worked for me for armv7hf after removing the nocross flag.

**Comment by pullmoll** [comment]
Bijiben was renamed gnome-notes, see https://gitlab.gnome.org/GNOME/gnome-notes currently at 3.37.92

**Comment by q66** [comment]
no stable release of that yet, so it'll stay as is for now

**Comment by q66** [comment]
added `gnome-todo` and `bijiben` into `gnome-apps`, fixed cross for `bijiben` and `io.elementary.calendar` plus added the missing rebuilds

**Pull request closed without merging**
