### PR TITLE
gnu-efi-libs: update to 3.0.11

### PR DESCRIPTION
**Pull request by ndowens**

### CODE REVIEW

**Comment by sgn** [comment]
I'll check what's wrong with efitools.

**Comment by ndowens** [comment]
> I'll check what's wrong with efitools on i686

Yeah I am not sure myself, I tried setting CFLAGS=-I..... but that didn't help either :\ . From what I can tell, it appears to be checking in the correct include location but not finding it.

**Comment by sgn** [comment]
> > I'll check what's wrong with efitools on i686
> 
> Yeah I am not sure myself, I tried setting CFLAGS=-I..... but that didn't help either :\ . From what I can tell, it appears to be checking in the correct include location but not finding it.

Thanks for the information. I'm the packager of efitools. Lemme check it.

**Comment by sgn** [comment]
Weird, i686 built fine in my local machine!

**Comment by ndowens** [comment]
> Weird, i686 built fine in my local machine!

Hmm weird, will retry and see

**Comment by sgn** [comment]
Please take this commit for efitools
https://github.com/sgn/void-packages/commit/3168a64f67763a4927c5cac148f4fe03e0bc50d7

**Comment by ndowens** [comment]
> Please take this commit for efitools
> [sgn@3168a64](https://github.com/sgn/void-packages/commit/3168a64f67763a4927c5cac148f4fe03e0bc50d7)

Seems it is travis that has issues, but not locally

**Comment by sgn** [comment]
I guess the problem is in ethereal chroot style! This chroot style is used only on Travis.
I'll take a close look into it.

**Comment by sgn** [comment]
Fixed by #17705

**Pull request closed without merging**
