### PR TITLE
gandi-cli: update to 1.4

### PR DESCRIPTION
**Pull request by lonwillett**

### CODE REVIEW

**Comment by maxice8** [comment]
python-click update to 7 will break all packages that depend on version smaller than 7.

**Comment by lonwillett** [comment]
Lovely. So how are dependency version conflicts supposed to be handled? Create a python-click7 package?

**Comment by maxice8** [comment]
On Thu, Feb 07, 2019 at 08:51:44AM -0800, Lon Willett wrote:
> Lovely. So how are dependency version conflicts supposed to be handled? Create a python-click7 package?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/8292#issuecomment-461507529

I usually leave hard python stuff to asergi

**Comment by lonwillett** [comment]
> I usually leave hard python stuff to asergi

OK. I'll let the expert (@asergi) handle it. It's not terribly important, but maybe should be put on a to-do list.

**Pull request closed without merging**
