### PR TITLE
pounce: update to 2.5.

### PR DESCRIPTION
**Pull request by ailiop-git**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by paper42** [comment]
please check one of the checkboxes in the PR template in all your PRs

**Comment by ailiop-git** [comment]
> please check one of the checkboxes in the PR template in all your PRs

why?

**Comment by paper42** [comment]
> > please check one of the checkboxes in the PR template in all your PRs
> 
> why?

The PR template exists for a reason, it helps people with reviewing your PRs.

**Comment by ailiop-git** [comment]
> > > please check one of the checkboxes in the PR template in all your PRs
> > 
> > 
> > why?
> 
> The PR template exists for a reason, it helps people with reviewing your PRs.

You may assume I'm using to some extend any pkg I'm submitting, although I don't see how this helps reviewers at all.

Unless there's an automated way to check that, I'm not going to go through every submission and manually tick checkboxes.

**Comment by paper42** [comment]
> You may assume I'm using to some extend any pkg I'm submitting

that's why we have two possible options:
* I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
* I generally don't use the affected packages but briefly tested this PR

> although I don't see how this helps reviewers at all.

Merging a PR isn't just about clicking a button, the person who merges the PR should make sure it will not break anything (by looking at it, trusting the knowledge of the PR author about the specific package, seeing if the checks succeed, testing it before merging, etc.). The checkboxes might in some cases help with that.

> Unless there's an automated way to check that, I'm not going to go through every submission and manually tick checkboxes.

There is no automated way to check this. Real people **manually** review your PRs, so refusing to do something as simple as clicking on a checkbox isn't nice.

**Comment by Johnnynator** [comment]
If you want to see commits merged/reviewed properly put some effort into it.

From our point of view, all commits look like untested low effort version bumps that might or might not be tested on a whole lot of 1 system.

E.g. #32707 did break on x86_64-musl, you did never tried to fix it or ask someone to help with it.
Such PR's just make it look like you do not care about these updates.

**Comment by ailiop-git** [comment]
> From our point of view, all commits look like untested low effort version bumps that might or might not be tested on a whole lot of 1 system.

That sounds about right. I do not see how submitters ticking on any of those boxes helps in changing this assumption. Whether I use it regularly or I "lightly tested it", should not influence a reviewer's decision, and it is anyway a completely vague statement with no content.

The "this is a new package" checkbox is also rather useless, given that this is obvious from the diff.

> E.g. #32707 did break on x86_64-musl, you did never tried to fix it or ask someone to help with it.
> Such PR's just make it look like you do not care about these updates.

Sorry, but I simply do not have the bandwidth to deal with all test failures and all archs. That also goes on to show how irrelevant those checkboxes are, especially given that travis will anyway build all targets. What difference would it make to any reviewer if I stated that I've built this on x86_64? It's obvious from the travis results what works and what not.

**Comment by ahesford** [comment]
If we didn't care about testing and some level of QA with updates, we could replace most of your contributions with a cronjob. There's a reason we don't do that.

If you don't "have the bandwidth" to address test failures or pay attention to PRs after you dump them in the queue, why are you contributing at all?

**Comment by paper42** [comment]
> > From our point of view, all commits look like untested low effort version bumps that might or might not be tested on a whole lot of 1 system.
> 
> That sounds about right. I do not see how submitters ticking on any of those boxes helps in changing this assumption. Whether I use it regularly or I "lightly tested it", should not influence a reviewer's decision, and it is anyway a completely vague statement with no content.

It is one of many metrics which go into reviewing and merging a PR. Sometimes it is valuable, so let's tick it, it's only one click.
 
> The "this is a new package" checkbox is also rather useless, given that this is obvious from the diff.

The purpose is to make people read the quality requirements if they missed them.

> > E.g. #32707 did break on x86_64-musl, you did never tried to fix it or ask someone to help with it.
> > Such PR's just make it look like you do not care about these updates.
> 
> Sorry, but I simply do not have the bandwidth to deal with all test failures and all archs. That also goes on to show how irrelevant those checkboxes are, especially given that travis will anyway build all targets. What difference would it make to any reviewer if I stated that I've built this on x86_64? It's obvious from the travis results what works and what not.

The "Does it build and run successfully?" section is commented out by default and makes sense to be filled only when CI is skipped.

> When skipping CI, uncomment and fill out the following section.

```
<!--
If GitHub CI cannot be used to validate the build result (for example, if the
build is likely to take several hours), make sure to
[skip CI](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#continuous-integration).
When skipping CI, uncomment and fill out the following section.
Note: for builds that are likely to complete in less than 2 hours, it is not
acceptable to skip CI.
-->
<!-- 
#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [ ] I built this PR locally for my native architecture, (ARCH-LIBC)
- [ ] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [ ] aarch64-musl
  - [ ] armv7l
  - [ ] armv6l-musl
-->

```

I agree that it's easy to miss and some people think they need to fill it in all PRs even when CI runs.

**Comment by ailiop-git** [comment]
> If we didn't care about testing and some level of QA with updates, we could replace most of your contributions with a cronjob. There's a reason we don't do that.

That's great, but you fail to explain how the checkboxes assist with "testing and some level of QA", or how this adds any confidence on top of travis. This is a very poor signal that bears no significance, and quite honestly it seems like a pointless exercise that is being imposed on contributors.

> If you don't "have the bandwidth" to address test failures or pay attention to PRs after you dump them in the queue, why are you contributing at all?

Because the majority of packages contributed aren't failing, and updates are needed. I'm using those packages and I like contributing so that other users can also receive updates in a timely fashion. I do not submit everything I update (e.g. i've been running on glibc-2.33 since March, but I'm aware of the complications and did not push it upstream).

In the end there are updates that would actually benefit from being done (or at least staged) through a crontab. For example #33102 is urgently needed by users due to multiple apache httpd CVEs. Similarly to other packages, unless I contribute, the package may not be updated for months (apparently their maintainers do not care to check the boxes either).

Still you seem to be more preoccupied and worried about checkboxes rather than how this actually affects users.

**Comment by ahesford** [comment]
1. Answering questions and fixing tests bolsters confidence that you are willing to spend more than 3 seconds firing a shell script to do an update. (Many of your PRs receive no response to maintainers' comments about issues with your contributions.)
2. Addressing the questions shows at least a baseline level of commitment to adhere to some contributor standards. It also tells us whether the update is actively used by the contributor, which helps inspire confidence that obvious defects in the update are more likely to have been caught. You can tell us now that "I only update things I use extensively", but none of us keep a checklist where we can note for all time "@ailiop-git is OK, we know he regularly uses the packages he updates". Do us a favor and remind us, since we tend to go through hundreds or thousands of these PRs from hundreds of different people.

Both tests and PR responsiveness become more important if updates cause breakage and need urgent action. We are less concerned about running the latest version than we are about running versions that aren't fundamentally broken. Your historical inattentiveness to issues within your PRs as well as your now combative response and "CBA" attitude do not inspire confidence that you will be available to fix a broken update should the need arise.

**Pull request merged**
