### PR TITLE
New package: v2ray-4.44.0

### PR DESCRIPTION
**Pull request by ipkalm**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (x86_64-glibc)
- [x] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [x] x86_64-musl
  - [x] i686
  - [x] i686-musl
  - [x] aarch64
  - [x] aarch64-musl
  - [x] armv7l
  - [x] armv7l-musl
  - [x] armv6l
  - [x] armv6l-musl
  - [x] ppc64le

### CODE REVIEW

**Comment by ipkalm** [comment]
I apologise for closing previous PR.

**Comment by ipkalm** [comment]
Greetings @ericonr @leahneukirchen !!! guys, may are you check my PR, please?😉

**Comment by ipkalm** [comment]
@leahneukirchen I fixed _template_ file. `x86_64` target - build successful with check stage (`-Q`). And now this stage take much less time than before. Cross Compile (`-a target`) is work for some target machines (x86_64-musl i686 i686-musl aarch64 aarch64-musl armv7l armv7l-musl armv6l armv6l-musl ppc64le).

**Comment by leahneukirchen** [comment]
Please rebase for CI.

**Comment by leahneukirchen** [comment]
Any idea why x86 segfaults?

**Pull request merged**
