### PR TITLE
openttd: update to 1.10.1

### PR DESCRIPTION
**Pull request by stimut**

### CODE REVIEW

**Comment by sgn** [comment]
Please fix `xlint`

**Comment by stimut** [comment]
> Please fix `xlint`

Done.

As an aside, is there a way of getting the same `xlint` that travis uses? The `xlint` from `xtools` didn't give me that same feedback.

**Comment by sgn** [comment]
`xlint srcpkgs/openttd/template`
Does it work for you?

**Comment by not-chicken** [comment]
> As an aside, is there a way of getting the same `xlint` that travis uses? The `xlint` from `xtools` didn't give me that same feedback.

You have to install `spdx-licenses-list` on your system.

**Comment by stimut** [comment]
> You have to install `spdx-licenses-list` on your system.

That did it. Thanks.

**Pull request merged**
