### PR TITLE
bird: update to 2.0.8

### PR DESCRIPTION
**Pull request by klarasm**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (x86_64-musl)
- [x] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [x] aarch64-musl
  - [x] armv7l
  - [x] armv6l-musl

### CODE REVIEW

**Comment by klarasm** [comment]
It seems that the build fails on x86_64-musl with `XBPS_CHECK_PKGS=yes`. I have replicated this on my machine. Attaching logs from builds with and without checks. I have not noticed any problems yet, but my use of the package may not trigger it.

I have located the error in the check to the following tests in lib/printf_test.c:
```
  /* These tests fail.
   * from man 3 printf:
   *        m      (Glibc extension; supported by uClibc and musl.)  Print output of strerror(er‐
   *                      rno).  No argument is required.
   * Maybe libc problem?
  errno = 5;
  BSPRINTF(18, "Input/output error", buf, "%m");
   */
  /* printf("%m\n\0", buf);
   * outputs "I/O error" instead
   */
  /*
  errno = 0;

  BSPRINTF(18, "Input/output error", buf, "%M", 5);
  */
  /*
   * printf("%M\n\0", buf);
   * does not seem to output anything
   */
```

Anyway, the tests that do not pass don't seem very critical to the function of the package. If it's a libc issue it's a bit weird that it only manifests on x86_64 and none of the arm archs.

From musl-1.1.24 src/errno/__strerror.h:39
`E(EIO,          "I/O error")`
From man 3 errno
`       EIO             Input/output error (POSIX.1-2001).`

[bird-v2.0.8_build.log](https://github.com/void-linux/void-packages/files/6218463/bird-v2.0.8_build.log)
[bird-v2.0.8_build-with-checks.log](https://github.com/void-linux/void-packages/files/6218464/bird-v2.0.8_build-with-checks.log)
[printf_test.c.txt](https://github.com/void-linux/void-packages/files/6218550/printf_test.c.txt)

**Comment by ericonr** [comment]
I can look into this later tomorrow, will assign myself so I don't forget. Thanks for the investigation.

**Comment by ericonr** [comment]
Please apply:

```diff
diff --git a/srcpkgs/bird/template b/srcpkgs/bird/template
index 1b6dd7be22..fbdf5c7734 100644
--- a/srcpkgs/bird/template
+++ b/srcpkgs/bird/template
@@ -2,6 +2,7 @@
 pkgname=bird
 version=2.0.7
 revision=2
+wrksrc=bird-v$version
 build_style=gnu-configure
 hostmakedepends="flex autoconf"
 makedepends="ncurses-devel readline-devel libssh-devel"
@@ -17,10 +18,6 @@ system_accounts="_bird"
 
 CFLAGS="-fcommon"
 
-post_extract() {
-	mv -v ${wrksrc/-/-v} $wrksrc
-}
-
 pre_configure() {
 	autoreconf
 }
```

The musl test failure already existed, so we can investigate it after merging, if you prefer (please open an issue, in that case).

**Comment by ericonr** [comment]
The failing test can be left as is, I will reach out to upstream musl.

**Comment by ericonr** [comment]
Actually, please add this patch:

```
diff --git a/lib/printf_test.c b/lib/printf_test.c
index 47ea905..2ec5814 100644
--- a/lib/printf_test.c
+++ b/lib/printf_test.c
@@ -22,6 +22,7 @@ static int
 t_simple(void)
 {
   char buf[256];
+  const char *errormsg;
   memset(buf, 0xa5, 256);
 
   BSPRINTF(0, "", buf, "", NULL);
@@ -32,11 +33,12 @@ t_simple(void)
   BSPRINTF(1, "@", buf, "@", 64);
   BSPRINTF(1, "\xff", buf, "%c", 0xff);
 
-  errno = 5;
-  BSPRINTF(18, "Input/output error", buf, "%m");
+  errormsg = strerror(EIO);
+  errno = EIO;
+  BSPRINTF(strlen(errormsg), errormsg, buf, "%m");
   errno = 0;
 
-  BSPRINTF(18, "Input/output error", buf, "%M", 5);
+  BSPRINTF(strlen(errormsg), errormsg, buf, "%M", EIO);
 
   BSPRINTF(11, "TeSt%StRiNg", buf, "%s", "TeSt%StRiNg");
 
```

And please look into upstreaming it :)

**Comment by klarasm** [comment]
Updated to address issues, confirmed that tests pass with the patch. I may look at upstreaming to bird later. Thanks for the help :)

**Pull request merged**
