### PR TITLE
nyxt: update to 2.2.2

### PR DESCRIPTION
**Pull request by WilliamBehrens**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (x86_64-glibc)
- [ ] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [ ] aarch64-musl
  - [ ] armv7l
  - [ ] armv6l-musl

### CODE REVIEW

**Comment by xaltsc** [comment]
You should update the description to `nyxt: update to 2.2.2`

**Comment by WilliamBehrens** [comment]
@xaltsc Should be fixed now

**Comment by WilliamBehrens** [comment]
it appears something went wrong when trying to contact the git remotes?

**Comment by xaltsc** [comment]
It seems to be a CI issue, github phased out insecure stuff today.

**Comment by xaltsc** [comment]
However, you have make a single commit, use `git commit --amend` for that.

**Comment by WilliamBehrens** [comment]
@xaltsc do I have to sumbit a new pr after that?

**Comment by xaltsc** [comment]
> @xaltsc do I have to sumbit a new pr after that?

No, just force-push the branch

**Comment by WilliamBehrens** [comment]
not sure if I've done it right, first time using `git commit --amend`

**Comment by cinerea0** [comment]
You need to squash your commits.

**Comment by WilliamBehrens** [comment]
@cinerea0 you're gonna have to give me more then that, I just want to update a package

**Pull request closed without merging**
