### PR TITLE
pnpm: update to 8.6.2

### PR DESCRIPTION
**Pull request by 0cool-f**
pnpm reverted pnpm-lock v6.1 to v6.0 https://github.com/pnpm/pnpm/issues/6648 it's suggested to upgrade to v8.6.2

#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by Bnyro** [comment]
Please change the commit message and PR title to `pnpm: update to 8.6.2`

**Comment by Bnyro** [comment]
The lint fails for two reasons:
1. `authored by noreply email` -> Please use a proper email for your commit (it's located in `~/.gitconfig`)
2. `long line: pnpm reverted pnpm-lock v6.1 to v6.0 https://github.com/pnpm/pnpm/issues/6648 it's suggested to upgrade to v8.6.2` => So please remove the description of the commit which should fix that warning, so only keep the commit message I suggested above

**Comment by Bnyro** [comment]
And next time, please name the branch something like `pnpm` or `pnpm-8.6.1`, but not just `patch-1`

**Comment by 0cool-f** [comment]
description removed, my `~/.gitconfig` was ok, author email protection flag unchecked, it should be ok now

sorry for `patch-1`, github made it and I looked at it after pr

**Comment by paper42** [comment]
commit author is still set to the automatic noreply email from github which is not allowed, please change it with `git commit --amend --no-edit --author="Name <EMAIL>"`

**Pull request merged**
