### PR TITLE
New package: PhpStorm-2019.1.3

### PR DESCRIPTION
**Pull request by shizonic**

### CODE REVIEW

**Comment by Chocimier** [comment]
Can you run that? For me that error happens: https://github.com/void-linux/void-packages/pull/11736#issuecomment-506952387

**Comment by shizonic** [comment]
For me it works well... Can't explain why TBH.

**Comment by 2asoft** [comment]
@shizonic what's your $JAVA_HOME set to?
What jdk and jre packages do you have installed?

**Comment by 2asoft** [comment]
I resolved the Java issue in other IntelliJ packages by changing the java dependency to `jetbrains-jdk-bin` and symlinking it in the right places. eg [see the WebStorm package](https://github.com/void-linux/void-packages/blob/96f01f4506afc4c84b3f6b905dfffd93f28b7e12/srcpkgs/WebStorm/template#L52).
If similar changes are made here, I believe it would just work.

@shizonic would you be able to make those changes?
Alternatively, I can do so as well. I believe I'll need to open a new PR for that.

**Comment by Chocimier** [comment]
No need to symlink since #20175, but needs to be updated and tested.

**Comment by Chocimier** [comment]
Included in #20390.

**Pull request closed without merging**
