### PR TITLE
dmidecode: update to 3.5.

### PR DESCRIPTION
**Pull request by mhmdanas**
#### Testing the changes
- I tested the changes in this PR: **briefly**

@steinex

### CODE REVIEW

**Comment by steinex** [comment]
distfile seems to be here now: http://download.savannah.gnu.org/releases/dmidecode/dmidecode-3.5.tar.xz

**Comment by mhmdanas** [comment]
Thanks for the heads up. The current distfile seems to spuriously fail to fetch with 404's on the CI, which is weird. I'll try your URL and see if it works.

**Comment by steinex** [comment]
Then I guess we need to wait until the mirrors all caught up on getting the new distfile.

**Comment by mhmdanas** [comment]
Using a URL that doesn't redirect to mirrors seems to have fixed the issue.

**Pull request merged**
