### PR TITLE
chromium: enable WebRTC screen sharing via PipeWire

### PR DESCRIPTION
**Pull request by Logarithmus**
[ci skip]

- [x] libpipewire0.2
- [x] patch chromium's template
- [ ] test for all supported archs:
    - [x] x86_64 - works for Chromium 87: https://github.com/void-linux/void-packages/pull/26144#issuecomment-731759815 & 86: https://youtu.be/AgyxEC7SfGk
    - [ ] i686 - works for Chromium 86: https://youtu.be/j0MY9C1CwV4
    - [x] x86_64-musl - works for Chromium 87: https://youtu.be/ZJorRl_7Sh4
    There are minor issues though:
    * you have to kill `xdg-desktop-portal*` processes sometimes, probably caused by some sort of race condition;
    * also you may need to start/restart screensharing for it to work.
        ✔️ https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing
        ✔️ https://zoom.us (in-browser version)
        ✔️ https://discord.com (in-browser version)

Currently I'm investigating these stability issues with `pipewire`. It seems that `pipewire` is trying to use `rtkit` to make audio/video processing run in real time. Unfortunately, it fails to do so:
```
2020-11-16T03:49:59.73350 daemon.err: Nov 16 03:49:59 rtkit-daemon[3165]: Failed to make ourselves RT: Function not implemented
2020-11-16T03:49:59.73602 daemon.warn: Nov 16 03:49:59 rtkit-daemon[3165]: Warning: failed to read scheduler policy: Function not implemented
2020-11-16T03:49:59.73620 daemon.debug: Nov 16 03:49:59 rtkit-daemon[3165]: Supervising 0 threads of 0 processes of 1 users.
2020-11-16T03:49:59.73645 daemon.debug: Nov 16 03:49:59 rtkit-daemon[3165]: Supervising 0 threads of 0 processes of 1 users.
2020-11-16T03:49:59.74118 daemon.err: Nov 16 03:49:59 rtkit-daemon[3165]: Failed to make ourselves RT: Function not implemented
```
After a bit of searching, I've found these bugs:
https://bugzilla.redhat.com/show_bug.cgi?id=1229700
https://bugs.gentoo.org/show_bug.cgi?id=569546

I've built `linux5.9` for `x86_64` with `CONFIG_RT_GROUP_SCHED` disabled.
For some strange reason, nothing changed, the error persists. Luckily, screen sharing works without `rtkit`.
I guess that those rare issues with screen sharing, which were described above, may be caused by `rtkit` not working.

### CODE REVIEW

**Comment by Logarithmus** [comment]
@ericonr @q66 @Duncaen @absrd finally, this PR is ready for review.
Related PR (`xdg-desktop-portal-wlr`): https://github.com/void-linux/void-packages/pull/23296

**Comment by Logarithmus** [comment]
I hope this PR will ever be merged... I've spent so much time on it.
Enabling this compile option shouldn't be a problem, because there's a flag in `chromium://flags` to toggle PipeWire support.

**Review by ifreund — CHANGES_REQUESTED** [review]
libpipewire0.2 needs to appear in `common/shlibs`. Also, I'm getting the following error building chromium:
```
[16699/43513] CXX obj/third_party/webrtc/modules/audio_processing/vad/vad/voice_activity_detector.o
[16700/43513] STAMP obj/third_party/webrtc/modules/desktop_capture/desktop_capture_generic.inputdeps.stamp
[16701/43513] CXX obj/third_party/webrtc/modules/congestion_controller/goog_cc/estimators/bitrate_estimator.o
[16702/43513] CXX obj/third_party/webrtc/modules/desktop_capture/primitives/shared_desktop_frame.o
[16703/43513] CXX obj/third_party/webrtc/modules/desktop_capture/pipewire_stubs/pipewire_stubs.o
FAILED: obj/third_party/webrtc/modules/desktop_capture/pipewire_stubs/pipewire_stubs.o 
clang++ -MMD -MF obj/third_party/webrtc/modules/desktop_capture/pipewire_stubs/pipewire_stubs.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DCR_CLANG_REVISION=\"llvmorg-12-init-5035-gd0abc757-3\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DWEBRTC_ENABLE_PROTOBUF=1 -DRTC_ENABLE_VP9 -DHAVE_SCTP -DENABLE_EXTERNAL_AUTH -DWEBRTC_USE_H264 -DHAVE_WEBRTC_VIDEO -DLOGGING_INSIDE_WEBRTC -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -DWEBRTC_ENABLE_AVX2 -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_LINUX -DABSL_ALLOCATOR_NOTHROW=1 -DNO_MAIN_THREAD_WRAPPING -Igen/third_party/webrtc/modules/desktop_capture -I../.. -Igen -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -Igen/shim_headers/libevent_shim -I../../third_party/webrtc_overrides -I../../third_party/webrtc -Igen/third_party/webrtc -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -Igen/protoc_out -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -mllvm -enable-dse-memoryssa=false -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -Wall -Wextra -Wimplicit-fallthrough -Wunreachable-code -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-psabi -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -std=c++14 -fno-trigraphs -Wno-trigraphs -fno-exceptions -fno-rtti -fvisibility-inlines-hidden     -c gen/third_party/webrtc/modules/desktop_capture/linux/pipewire_stubs.cc -o obj/third_party/webrtc/modules/desktop_capture/pipewire_stubs/pipewire_stubs.o
gen/third_party/webrtc/modules/desktop_capture/linux/pipewire_stubs.cc:18:10: fatal error: 'pipewire/pipewire.h' file not found
#include <pipewire/pipewire.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
[16704/43513] CXX obj/third_party/webrtc/modules/congestion_controller/congestion_controller/receive_side_congestion_controller.o
[16705/43513] CXX obj/third_party/webrtc/modules/congestion_controller/goog_cc/alr_detector/alr_detector.o
[16706/43513] CXX obj/third_party/webrtc/modules/congestion_controller/goog_cc/estimators/acknowledged_bitrate_estimator_interface.o
[16707/43513] CXX obj/third_party/webrtc/modules/desktop_capture/desktop_capture_generic/desktop_capture_options.o
[16708/43513] CXX obj/third_party/webrtc/modules/desktop_capture/desktop_capture_generic/desktop_capturer.o
[16709/43513] CXX obj/third_party/webrtc/modules/desktop_capture/desktop_capture_generic/desktop_and_cursor_composer.o
[16710/43513] CXX obj/third_party/webrtc/modules/congestion_controller/goog_cc/goog_cc/goog_cc_network_control.o
[16711/43513] CXX obj/third_party/webrtc/modules/congestion_controller/rtp/control_handler/control_handler.o
[16712/43513] CXX obj/third_party/webrtc/modules/congestion_controller/rtp/transport_feedback/transport_feedback_adapter.o
ninja: build stopped: subcommand failed.
=> ERROR: chromium-87.0.4280.66_1: do_build: 'ninja -C out/Release ${makejobs} chrome chromedriver mksnapshot' exited with 1
=> ERROR:   in do_build() at srcpkgs/chromium/template:269
```
Didn't have time to look into what's causing it yet.

**Comment by Logarithmus** [comment]
@ifreund that's because for some strange reason `chromium` package doesn't depend on `libpipewire0.2-devel`, even though I've added it into the template's `makedepends` section. I had to build and install it manually. Possibly It's mandatory to add `libpipewire0.2` into `common/shlibs`. Anyway, I've just added it and 'll re-package with this change and see where it goes.

**Comment by ericonr** [comment]
> Possibly It's mandatory to add libpipewire0.2 into common/shlibs

You may need to do this if you want the package to detect the `libpipewire` dependency, but it shouldn't make any difference for the header to be found.

**Comment by Logarithmus** [comment]
@ifreund OK, I've fixed `libpipewire0.2`'s template, now headers should be visible.
@ericonr I've added `libpipewire0.2` into `common/shlibs`. Unfortunately, `chromium` still doesn't depend on `libpipewire0.2`. That's because `chromium`'s binary dlopens `libpipewire`, and libpipewire is missing in `ldd /lib/chromium/chromium`

**Comment by ericonr** [comment]
> That's because chromium's binary dlopens libpipewire, and libpipewire is missing in ldd /lib/chromium/chromium.
IMHO that's a bug in xbps.

That's all working as intended. Applications use `dlopen` exactly to allow for optional dependencies, and scanning a binary for what it does open will 1) be fragile and 2) remove the usefulness of dlopening in the first place.

**Comment by Logarithmus** [comment]
> > That's because chromium's binary dlopens libpipewire, and libpipewire is missing in ldd /lib/chromium/chromium.
> > IMHO that's a bug in xbps.
> 
> That's all working as intended. Applications use `dlopen` exactly to allow for optional dependencies, and scanning a binary for what it does open will 1) be fragile and 2) remove the usefulness of dlopening in the first place.

OK, if I'll explicitly include `libpipewire0.2` into `depends` section, in addition to `makedepends`, will it finally work? 
IMHO the right solution to such problems is the support of optional dependencies `xbps`, like `pacman` does.
There's an issue about that https://github.com/void-linux/xbps/issues/1, but unfortunately `xbps` isn't actively developed anymore (I guess that's related to Juan RP's departure).

**Comment by ifreund** [comment]
I still get the same error with the latest commit. I also don't see the include dir for pipewire in the clang++ command line flags, so it seems like pipewire's pkgconfig is not getting used for whatever reason.

**Comment by Logarithmus** [comment]
@ifreund can I ask you to check if `/usr/include/pipewire` directory presents in `libpipewire0.2-devel` package? If it's called `pipewire-0.2` instead, then please rebuild the package.

**Comment by Logarithmus** [comment]
@ifreund can I ask you to check if `/usr/include/pipewire` directory presents in `libpipewire0.2-devel` package? If it's called `pipewire-0.2` instead, then please rebuild the package.

**Comment by ifreund** [comment]
<details>
<summary>
```
$ xls libpipewire0.2-devel
```
```
/usr/include/pipewire/array.h
/usr/include/pipewire/client.h
/usr/include/pipewire/command.h
/usr/include/pipewire/control.h
/usr/include/pipewire/core.h
/usr/include/pipewire/data-loop.h
/usr/include/pipewire/extensions/client-node.h
/usr/include/pipewire/extensions/protocol-native.h
/usr/include/pipewire/factory.h
/usr/include/pipewire/global.h
/usr/include/pipewire/interfaces.h
/usr/include/pipewire/introspect.h
/usr/include/pipewire/link.h
/usr/include/pipewire/log.h
/usr/include/pipewire/loop.h
/usr/include/pipewire/main-loop.h
/usr/include/pipewire/map.h
/usr/include/pipewire/mem.h
/usr/include/pipewire/module.h
/usr/include/pipewire/node.h
/usr/include/pipewire/pipewire.h
/usr/include/pipewire/port.h
/usr/include/pipewire/properties.h
/usr/include/pipewire/protocol.h
/usr/include/pipewire/proxy.h
/usr/include/pipewire/remote.h
/usr/include/pipewire/resource.h
/usr/include/pipewire/stream.h
/usr/include/pipewire/thread-loop.h
/usr/include/pipewire/type.h
/usr/include/pipewire/utils.h
/usr/include/pipewire/version.h
/usr/include/pipewire/work-queue.h
/usr/include/spa/buffer/buffer.h
/usr/include/spa/buffer/meta.h
/usr/include/spa/clock/clock.h
/usr/include/spa/graph/graph.h
/usr/include/spa/monitor/monitor.h
/usr/include/spa/node/command.h
/usr/include/spa/node/event.h
/usr/include/spa/node/io.h
/usr/include/spa/node/node.h
/usr/include/spa/param/audio/format-utils.h
/usr/include/spa/param/audio/format.h
/usr/include/spa/param/audio/raw-utils.h
/usr/include/spa/param/audio/raw.h
/usr/include/spa/param/buffers.h
/usr/include/spa/param/format-utils.h
/usr/include/spa/param/format.h
/usr/include/spa/param/io.h
/usr/include/spa/param/meta.h
/usr/include/spa/param/param.h
/usr/include/spa/param/props.h
/usr/include/spa/param/video/chroma.h
/usr/include/spa/param/video/color.h
/usr/include/spa/param/video/encoded.h
/usr/include/spa/param/video/format-utils.h
/usr/include/spa/param/video/format.h
/usr/include/spa/param/video/multiview.h
/usr/include/spa/param/video/raw-utils.h
/usr/include/spa/param/video/raw.h
/usr/include/spa/pod/builder.h
/usr/include/spa/pod/command.h
/usr/include/spa/pod/event.h
/usr/include/spa/pod/iter.h
/usr/include/spa/pod/parser.h
/usr/include/spa/pod/pod.h
/usr/include/spa/support/log-impl.h
/usr/include/spa/support/log.h
/usr/include/spa/support/loop.h
/usr/include/spa/support/plugin.h
/usr/include/spa/support/type-map-impl.h
/usr/include/spa/support/type-map.h
/usr/include/spa/utils/defs.h
/usr/include/spa/utils/dict.h
/usr/include/spa/utils/hook.h
/usr/include/spa/utils/list.h
/usr/include/spa/utils/ringbuffer.h
/usr/include/spa/utils/type.h
/usr/lib/pkgconfig/libpipewire-0.2.pc
/usr/lib/pkgconfig/libspa-0.1.pc
/usr/lib/libpipewire-0.2.so -> /usr/lib/libpipewire-0.2.so.1
```

</details>

**Comment by Logarithmus** [comment]
> Looks like it's there, still get the same error building chromium though.
> 
> ```
> $ xls libpipewire0.2-devel
> ```

I guess you have to rerun `configure` & `build` stages in order for it to see the headers.

**Comment by ifreund** [comment]
> I guess you have to rerun `configure` & `build` stages for `chromium` in order for it to see the headers.

Looks like you were right, after a `git clean` and several hours it finished building. I should have time to get xdpw/pipewire setup and give this a test later tonight or tomorrow.

**Comment by ifreund** [comment]
Confirmed that this works with #23296 to screenshare on sway x86_64 glibc using the webrtc test page here: https://mozilla.github.io/webrtc-landing/gum_test.html

**Comment by Logarithmus** [comment]
Finally, my changes have been merged (https://github.com/void-linux/void-packages/pull/27060)! Thanks to everyone who were involved.

**Pull request closed without merging**
