### PR TITLE
Update: bCNC to 0.9.15, add  python3-shxparser-0.0.2, python3-svgelements-1.9.6 as dependency

### PR DESCRIPTION
**Pull request by Luciogi**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64_glibc)

###  bCNC 0.9.15 requires new depends
- python3-shxparser
- python3-svgelements

### CODE REVIEW

**Comment by Chocimier** [comment]
Looks neither [system-wide, compiled nor required by other package](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements), or is it?

**Comment by Luciogi** [comment]
> Looks neither [system-wide, compiled nor required by other package](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements), or is it?

bCNC 0.9.15 will require this package

**Comment by ahesford** [comment]
In that case, we can wait to add these packages until bCNC is updated and include them in the update PR.

**Comment by Luciogi** [comment]
PR is read to be merged, Application opens without any errors

**Comment by paper42** [comment]
this PR was not ready for merging, fixed in ed31f3b2c2e40e8a961427d8cae5f16228b0c08e, 86870336d9b935c22af2245c3d36912ae01494ae and 0c63fa97e71dea2faea368652bb2fadba7d733fb

**Comment by Vaelatern** [comment]
Thanks for fixing!

**Pull request merged**
