### PR TITLE
lapce: update to 0.4.2, adopt

### PR DESCRIPTION
**Pull request by voidisnull**
#### Testing the changes
- I tested the changes in this PR: **NO**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures:
  - x86_64-musl

<br/>

@atk could you please review the changes??
And thanks for your time!!

### CODE REVIEW

**Comment by atk** [comment]
If you want to pick up the package, please do. I find it unusable.

**Comment by voidisnull** [comment]
I would adopt the package on a later release
As I have seen new contributors are encouraged to not adopt packages, therefore I won't adopt this package now.

So,
For now, I'll mark this package as orphan

**Comment by classabbyamp** [comment]
you've been contributing enough to adopt

**Comment by voidisnull** [comment]
Thank you @classabbyamp !!
I'll adopt the template when the next update rolls out

**Comment by classabbyamp** [comment]
you can just do it now...

**Pull request merged**
