### PR TITLE
chromium: update to 91.0.4472.77.

### PR DESCRIPTION
**Pull request by Johnnynator**
#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] x86_64
- [x] x86_64-musl
- [x] i686

[ci skip] to make ericonr happy

### CODE REVIEW

**Comment by Johnnynator** [comment]
```
malloc_consolidate(): unaligned fastbin chunk detected
Received signal 6
#0 0x561ce69c7d19 (/usr/lib/chromium/chromium+0x4620d18)
#1 0x561ce69387a3 (/usr/lib/chromium/chromium+0x45917a2)
#2 0x561ce69c78c1 (/usr/lib/chromium/chromium+0x46208c0)
#3 0x7fd9898de900 (/usr/lib/libpthread-2.32.so+0x138ff)
#4 0x7fd985dc6f81 __GI_raise
#5 0x7fd985db0536 __GI_abort
#6 0x7fd985e084f8 __libc_message
#7 0x7fd985e0ff3a malloc_printerr
#8 0x7fd985e10fe4 malloc_consolidate
#9 0x7fd985e117d0 _int_free
#10 0x561ce536236e (/usr/lib/chromium/chromium+0x2fbb36d)
#11 0x561ce535eee4 (/usr/lib/chromium/chromium+0x2fb7ee3)
#12 0x561ce535ef0e (/usr/lib/chromium/chromium+0x2fb7f0d)
#13 0x561ce7d14645 (/usr/lib/chromium/chromium+0x596d644)
#14 0x561ce7d13aec (/usr/lib/chromium/chromium+0x596caeb)
#15 0x561ce6db3f1d (/usr/lib/chromium/chromium+0x4a0cf1c)
#16 0x561ce6db413e (/usr/lib/chromium/chromium+0x4a0d13d)
#17 0x561ce6fd8e92 (/usr/lib/chromium/chromium+0x4c31e91)
#18 0x561ce6fd8c55 (/usr/lib/chromium/chromium+0x4c31c54)
#19 0x561ce6dc5895 (/usr/lib/chromium/chromium+0x4a1e894)
#20 0x561ce6dc6d8d (/usr/lib/chromium/chromium+0x4a1fd8c)
#21 0x561ce6dc6c9c (/usr/lib/chromium/chromium+0x4a1fc9b)
#22 0x561ce6dbbf0e (/usr/lib/chromium/chromium+0x4a14f0d)
#23 0x561ce6f297b6 (/usr/lib/chromium/chromium+0x4b827b5)
#24 0x561ce6f3d3c2 (/usr/lib/chromium/chromium+0x4b963c1)
#25 0x561ce464f999 (/usr/lib/chromium/chromium+0x22a8998)
#26 0x561ce465161d (/usr/lib/chromium/chromium+0x22aa61c)
#27 0x561ce464cd37 (/usr/lib/chromium/chromium+0x22a5d36)
#28 0x561ce690d830 (/usr/lib/chromium/chromium+0x456682f)
#29 0x561ce690d33e (/usr/lib/chromium/chromium+0x456633d)
#30 0x561ce690ab03 (/usr/lib/chromium/chromium+0x4563b02)
#31 0x561ce690b44c (/usr/lib/chromium/chromium+0x456444b)
#32 0x561ce34ee4cc ChromeMain
#33 0x7fd985db1e0a __libc_start_main
#34 0x561ce34ee30a _start
  r8: 0000000000000000  r9: 00007ffde4009720 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007ffde4009990 r13: 0000000000001000 r14: 0000000000000010 r15: 00007fd98039f000
  di: 0000000000000002  si: 00007ffde4009720  bp: 00007ffde4009a70  bx: 00007fd9832bb280
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007fd985dc6f81  sp: 00007ffde4009720
  ip: 00007fd985dc6f81 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```
It seems to get aborted when trying to close it, otherwise seems to run on x86_64 glibc.
Will take a look at it tomorrow.

**Comment by Johnnynator** [comment]
Packages (x86_64, x86_64-musl, i686) for testing available at https://void.johnnynator.dev/chromium-91.0.4472.77/

**Comment by q66** [comment]
i'm getting reports that the ppc64le patches will need heavy changes

**Comment by ericonr** [comment]
Working on x86_64-musl fwiw.

**Pull request closed without merging**
