### PR TITLE
mariadb: add a patch to fix an issue on musl.

### PR DESCRIPTION
**Pull request by CMB**
Sourced from: https://github.com/MariaDB/server/commit/1655053ac1

### CODE REVIEW

**Comment by jnbr** [comment]
Travis-CI failed to build the package, some timed out, some actually failed.
There isn't much we can do on timeouts, but can you check locally if it works and see why cross builds are failing?

**Comment by CMB** [comment]
> There isn't much we can do on timeouts, but can you check locally if it works
> and see why cross builds are failing?

I'm seeing the same failures locally when cross-building for ARM.
The build log wasn't too helpful, so I tried building the current
version of the package that is in Void's repos: mariadb-10.1.30_7.  That
build also failed for ARM.  So it's not a failure introduced by the
patch.

I can keep trying to track down the problem.

**Comment by jnbr** [comment]
Yes, please do. Merging something that fails to build isn't an option, even if the change is unrelated to the failure.
Maybe adding `disable_parallel_build=yes` tp the template helps, it was needed before for mariadb.

**Comment by newbluemoon** [comment]
It seems that the host-built tools to generate some header files are not found.
By moving them into the `build` directory they’re magically found again.
With following changes a cross-build was successful:
```
diff --git a/srcpkgs/mariadb/template b/srcpkgs/mariadb/template
index c0c44217b7..b87e35e49e 100644
--- a/srcpkgs/mariadb/template
+++ b/srcpkgs/mariadb/template
@@ -53,11 +53,11 @@ pre_configure() {

 pre_build() {
        if [ "$CROSS_BUILD" ]; then
-               cp bin.host/comp_err ${wrksrc}/extra
-               cp bin.host/comp_sql ${wrksrc}/scripts
-               cp bin.host/gen_lex_hash ${wrksrc}/sql
-               cp bin.host/gen_lex_token ${wrksrc}/sql
-               export PATH=${PATH}:${wrksrc}/extra:${wrksrc}/scripts:${wrksrc}/sql
+               cp bin.host/comp_err ${wrksrc}/build/extra
+               cp bin.host/comp_sql ${wrksrc}/build/scripts
+               cp bin.host/gen_lex_hash ${wrksrc}/build/sql
+               cp bin.host/gen_lex_token ${wrksrc}/build/sql
+               export PATH=${PATH}:${wrksrc}/build/extra:${wrksrc}/build/scripts:${wrksrc}/build/sql
        fi
        export LD_LIBRARY_PATH=${wrksrc}/build/storage/tokudb/ft-index/portability
        case "$XBPS_TARGET_MACHINE" in
```

**Pull request closed without merging**
