### PR TITLE
ldc: update to 1.26.0.

### PR DESCRIPTION
**Pull request by ericonr**
Also move to llvm12.

@q66

It ends up underlinked, because when I try building corecollector with it I get:

```
Project version: 0.3.5
Error relocating /usr/lib/libdruntime-ldc-shared.so.96: unw_init_local: symbol not found
Error relocating /usr/lib/libdruntime-ldc-shared.so.96: unw_get_proc_name: symbol not found
Error relocating /usr/lib/libdruntime-ldc-shared.so.96: unw_step: symbol not found
Error relocating /usr/lib/libdruntime-ldc-shared.so.96: unw_getcontext: symbol not found
Error relocating /usr/lib/libdruntime-ldc-shared.so.96: unw_get_proc_info: symbol not found

meson.build:1:0: ERROR: Executables created by D compiler ldc2 are not runnable.
```

But running with `LD_PRELOAD=/usr/lib/libunwind.so.1` after installing `llvm-libunwind` makes meson not complain.

Alpine seems to be doing a trick to build with `libunwind` (https://git.alpinelinux.org/aports/tree/community/ldc/APKBUILD): `-DC_SYSTEM_LIBS="unwind;m;pthread;rt;dl"`, which we can probably just appropriate.

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by q66** [comment]
let's do the same as alpine then...

**Comment by ericonr** [comment]
@aurieh ok?

**Comment by q66** [comment]
let's disable make_check probably

**Comment by ericonr** [comment]
Tried adding checkdepends, but it hangs forever >.<

**Comment by ericonr** [comment]
Ugh this was more trouble than I expected. `tilix` is working, at least. It's just a tad ugly.

**Comment by ericonr** [comment]
Ooof, I had built `gtkd` with my `ldc` that hadn't been rebuilt to contain `llvm-unwind-devel`, but it seems `gtkd` requires `libunwind-devel` via `gstreamer1-devel`, and they conflict.

I would really appreciate it if languages stopped shoving external stack unwinding into their stuff >.<

Any idea for a proper fix? Turns out `ldd tilix` still spits out two different `libunwind.so.{8,1}` which offer symbols with the same names, so I would expect things to get ugly.

**Comment by ericonr** [comment]
Alternatively, we could remove backtrace capability from `gstreamer1` using the `libunwind` build option: `option('libunwind', type : 'feature', value : 'auto', description : 'Use libunwind to generate backtraces')`

**Comment by aurieh** [comment]
@ericonr I had a shot at updating ldc to 1.25 a while back but couldn't get past the build hanging. Will test these changes later today.

**Comment by ericonr** [comment]
No worries @aurieh, thanks a lot! I think I will merge in a bit.

**Pull request merged**
