### PR TITLE
jrnl: update to 2.6

### PR DESCRIPTION
**Pull request by ndowens**
superceeds #26398

### CODE REVIEW

**Comment by ericonr** [comment]
https://github.com/jrnl-org/jrnl/releases is it an actual release?

**Comment by ericonr** [comment]
Kind of looks like one, just want to be sure.

**Comment by ndowens** [comment]
> Kind of looks like one, just want to be sure.

if you click more tags it is listed.

**Comment by ericonr** [comment]
Yes, but it's listed only as tag, not as release.

**Comment by ericonr** [comment]
Man, I think 2.6 is an actual release... It's in the changelog and pypi. This package just seems so fragile, I want to avoid fucking it up.

**Pull request merged**
