### PR TITLE
firefox-esr: update to 115.10.0

### PR DESCRIPTION
**Pull request by Zapeth**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc

[ci skip]

### CODE REVIEW

**Comment by biopsin** [comment]
would it be handy to add
`changelog="https://www.mozilla.org/en-US/firefox/${version}/releasenotes/"`

will test it later today.

**Comment by Zapeth** [comment]
rebased and updated (successive builds would fail on python3.11 symbolic link creation without `-f` flag), also added suggested changelog entry

**Comment by biopsin** [comment]
on second thought drop the changelog, its pointless anyways as a variable, mind the fuzz

**Comment by Zapeth** [comment]
rebased and updated to 115.5.0

**Comment by Zapeth** [comment]
rebased, updated to 115.6.0 and briefly tested on x86_64-glibc

@Duncaen is it required to test on other platforms too before this can get merged?

**Comment by tuxliban** [comment]
@Zapeth works for me on [x86_64-musl](https://0x0.st/s/t5_OiFc59bXgp7bV1ppg6Q/H6IO.png).
Thanks!

**Comment by biopsin** [comment]
Version 115.7.0 - tests fine locally on x86_64-glibc

**Comment by Zapeth** [comment]
Rebased and updated to 115.10.0esr, also briefly tested on x86_64-glibc

@Duncaen is this going to get merged at some point, or are esr versions only updated with major releases (ie 128.2esr)?

**Comment by Vinfall** [comment]
Off-topic: very shocked and upset to discover today that I'm using an outdated one that **16 versions behind** as this never gets merged :(

**Pull request closed without merging**
