### PR TITLE
libaccounts-glib: use python3-gobject-devel

### PR DESCRIPTION
**Pull request by q66**
A check that is inside of this specifically asks for python3.

### CODE REVIEW

**Comment by maxice8** [comment]
won't that result in a different binary ?

**Comment by q66** [comment]
no, python-gobject is not carried into dependencies at all

**Comment by q66** [comment]
actually, it is carried into dependencies of the -devel package, so a revbump is in order?

**Comment by maxice8** [comment]
ok

**Comment by maxice8** [comment]
On Sun, Feb 24, 2019 at 11:57:25AM -0800, Daniel Kolesa wrote:
> actually, it is carried into dependencies of the -devel package, so a revbump is in order?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/9138#issuecomment-466810933

yeah sure

**Comment by q66** [comment]
This is because the -devel package has a `depends="${makedepends} ..."` in it

**Comment by q66** [comment]
bumped

**Pull request merged**
