### PR TITLE
rspamd: update to 3.6.

### PR DESCRIPTION
**Pull request by adrian-bl**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)

### CODE REVIEW

**Comment by Bnyro** [comment]
Please read `CONTRIBUTING.md` and follow the described commit style

**Comment by adrian-bl** [comment]
Thanks for the pointer: updated the title - i think the rest of the PR is in line with the contributing rules - please let me know if i missed something else.

Also i tested the current version of the PR locally and it builds on x86_64, x86_64-musl, aarch64, aarch64-musl and armv6l

**Comment by Duncaen** [comment]
The commit title has to be changed, the PR title doesn't matter much as it doesn't appear in the git history.

**Comment by Duncaen** [comment]
The commit title has to be changed, the PR title doesn't matter much as it doesn't appear in the git history.

**Comment by adrian-bl** [comment]
Ah, got it: sorry for that! Updated the commit message

**Pull request closed without merging**
