### PR TITLE
New package: python3-rope-0.14.0.

### PR DESCRIPTION
**Pull request by k4leg**

### CODE REVIEW

**Comment by Chocimier** [comment]
Unusable:
```
>>> import rope.base.project
>>> myproject = rope.base.project.Project('/usr/lib/python3.8/site-packages/rope/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/rope/base/project.py", line 223, in __init__
    self._init_prefs(prefs)
…
  File "/usr/lib/python3.8/site-packages/rope/base/oi/type_hinting/providers/docstrings.py", line 46, in __call__
    type_strs = self._parse_docstring(pyfunc.get_doc(), param_name)
  File "/usr/lib/python3.8/site-packages/rope/base/pyobjects.py", line 224, in get_doc
    isinstance(expr.value, ast.Str):
AttributeError: module 'rope.base.ast' has no attribute 'Str'


```

**Comment by k4leg** [comment]
@Chocimier No the fact is that he needs to create a `.ropeproject` folder and this is a folder that is accessible only to **root** which is why it generated an error.

**Comment by Chocimier** [comment]
Tried in writeable location, same error.

**Comment by k4leg** [comment]
This should work:
```
import rope.base.project

try:
    myproject = rope.base.project.Project('/path/to/folder/')
except AttributeError:
    myproject = rope.base.project.Project('/path/to/folder/')
```
I think there are other methods for creating the `.ropeproject` folder without error, but I am new to python and don't know how to do it differently.

**Pull request closed without merging**
