### PR TITLE
solvespace: update to 3.0

### PR DESCRIPTION
**Pull request by rmc0**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by biopsin** [comment]
Fix lint: missing revision number, new version resets revision to 1

**Comment by paper42** [comment]
@rmc0 If you tested this package update on your computer, could you fill out the PR template?

**Comment by rmc0** [comment]
> @rmc0 If you tested this package update on your computer, could you fill out the PR template?

Sorry, I would just help by starting this PR and not just ask an update

 but it's new for me 

I haven't test or install, I will search more..

**Comment by biopsin** [comment]
@rmc0 also add changelog="https://github.com/solvespace/solvespace/blob/master/CHANGELOG.md"
There are some outstanding changes in v.3, so this will a bit bumbier ride then a straight update.

**Comment by bobertlo** [comment]
#34611 should work

sorry i got a little too busy to update this for a while

**Comment by ericonr** [comment]
Done in #34611

**Pull request closed without merging**
