### PR TITLE
New package: gllock-09102019

### PR DESCRIPTION
**Pull request by RoundDuckKira**
This is a locking program based on slock that has opengl-based lock screens for flashiness. https://github.com/kuravih/gllock/

### CODE REVIEW

**Comment by RoundDuckKira** [comment]
uh oh

2020-10-09-082720_785x98_scrot

**Comment by RoundDuckKira** [comment]
Old problem fixed, here's the new problem:

`/usr/bin/ld: common.c:(.text+0x810): undefined reference to `__glewGenBuffers'
/usr/bin/ld: common.c:(.text+0x81f): undefined reference to `__glewBindBuffer'
/usr/bin/ld: common.c:(.text+0x83b): undefined reference to `__glewBufferData'
/usr/bin/ld: common.c:(.text+0x84a): undefined reference to `__glewBindBuffer'
/usr/bin/ld: common.c:(.text+0x8ad): undefined reference to `glGenTextures'
/usr/bin/ld: common.c:(.text+0x8be): undefined reference to `glBindTexture'
/usr/bin/ld: common.c:(.text+0x8d5): undefined reference to `glTexParameterf'
/usr/bin/ld: common.c:(.text+0x8ec): undefined reference to `glTexParameterf'
/usr/bin/ld: common.c:(.text+0x91e): undefined reference to `glTexImage2D'
/usr/bin/ld: common.c:(.text+0x939): undefined reference to `__glewGetUniformLocation'
/usr/bin/ld: common.c:(.text+0x94c): undefined reference to `__glewGetUniformLocation'
/usr/bin/ld: common.c:(.text+0x969): undefined reference to `__glewVertexAttribPointer'
/usr/bin/ld: common.c:(.text+0x973): undefined reference to `glClear'
/usr/bin/ld: common.o: in function `animate':
common.c:(.text+0x9e7): undefined reference to `__glewUniform1f'
/usr/bin/ld: common.c:(.text+0xa0f): undefined reference to `__glewUniform1f'
/usr/bin/ld: common.c:(.text+0xa1a): undefined reference to `glXSwapBuffers'
/usr/bin/ld: common.c:(.text+0xa22): undefined reference to `__glewEnableVertexAttribArray'
/usr/bin/ld: common.c:(.text+0xa33): undefined reference to `glDrawArrays'
/usr/bin/ld: common.c:(.text+0xa3b): undefined reference to `__glewDisableVertexAttribArray'
/usr/bin/ld: common.c:(.text+0xa8a): undefined reference to `__glewUniform1f'
collect2: error: ld returned 1 exit status
make: *** [Makefile:25: gllock] Error 1
=> ERROR: gllock-09102019_1: do_build: 'make CC=$CC INCS="-I." LIBS="-lX11 -lXext -lcrypt -lXrandr" ${makejobs}' exited with 2
=> ERROR:   in do_build() at srcpkgs/gllock/template:20`

**Comment by pullmoll** [comment]
Take a look at https://github.com/kuravih/gllock/blob/master/config.mk to see what your `LIBS=…` is missing.

**Comment by ericonr** [comment]
I think this one should have `make_use_env=yes` instead of manually listing the `LIBS`.

**Comment by RoundDuckKira** [comment]
ah @ericonr I'll try that

**Comment by RoundDuckKira** [comment]
2020-10-09-092701_886x383_scrot

**Comment by RoundDuckKira** [comment]
still same error

**Comment by RoundDuckKira** [comment]
despite make_use_env

**Comment by RoundDuckKira** [comment]
`/usr/bin/ld: /lib64/libX11.so.6: error adding symbols: DSO missing from command line`

**Comment by RoundDuckKira** [comment]
pushed a new version to review

**Comment by RoundDuckKira** [comment]
@pullmoll I tried following your advice about the LIBS stuff and it didn't work ooof

**Comment by RoundDuckKira** [comment]
@ericonr @pullmoll the newest code shows what I tried to do and well that I'm having trouble with, with the new LIBS and make_use_env and it still failing as I said before

Sorry for being a bit annoying here btw

**Comment by Chocimier** [comment]
make_use_env does nothing if you define own `do_` functions. Use gnu-makefile, and maybe define make_build_args additionally.

Is this package so good it don't need tag?

**Pull request closed without merging**
