### PR TITLE
Xfce switch to python3

### PR DESCRIPTION
**Pull request by sgn**
- xfce: switch all python in its dependencies chain to Python 3

### CODE REVIEW

**Comment by PaperMountainStudio** [comment]
glade3 depends on gnome-doc-utils which depends on python2, you might want to fix it :wink:

**Comment by sgn** [comment]
On December 25, 2019 4:01:33 PM UTC, Paper Mountain Studio <notifications@github.com> wrote:
>glade3 depends on gnome-doc-utils which depends on python2, you might
>want to fix it :wink: 

Ah, I didn't notice it.

Since I tried to removed Python 2 from xfce4, xfce4 depends on libglade3ui, which doesn't depend on gnome-doc-utils.

-- 
Danh

**Comment by sgn** [comment]
> glade3 depends on gnome-doc-utils which depends on python2, you might want to fix it wink

glade3 doesn't depend on gnome-doc-utils

It requires gnome-doc-utils to build documentation only

It doesn't require it for runtime.

Gnome-doc-utils doesn't support python3.

**Comment by sgn** [comment]
Cross CI is failing because of some host dependencies haven't been built

**Comment by xtraeme** [comment]
Yeah, the aarch64 and arm builders are still in staging state, due to obsolete pkgs that need to be removed...

**Comment by q66** [comment]
The python-gobject dependency in libgladeui is wrong, and was always wrong - imo this should be on glade3 itself as that's what ships the python plugin

**Comment by sgn** [comment]
On 2020-01-18 06:03:05-0800, Daniel Kolesa <notifications@github.com> wrote:
> The python-gobject dependency in libgladeui is wrong, and was always
> wrong - imo this should be on glade3 itself as that's what ships the
> python plugin

You're correct, tested with my x86_64 setup.

-- 
Danh

**Comment by sgn** [comment]
I split the python binding out, and added webkit2gtk sub-packages.

**Comment by q66** [comment]
Hm, actually, this may be wrong. I'm looking at how other distributions do it, and they pretty much all put the modules in `libgladeui`; seems like these modules may be used at runtime by GLADE-using applications.

Which means, the right way would be to move the modules into the `libgladeui` package, as well as the python dependencies.

Interestingly, none of them seem to split the modules into subpackages...

**Comment by q66** [comment]
Here's the Fedora list: 

https://src.fedoraproject.org/rpms/glade3/blob/master/f/glade3.spec#_162

So the library should go in there, as well as the modules, and `/usr/share/glade3/{pixmaps,catalogs}`.

**Comment by sgn** [comment]
On 2020-01-20 05:26:08-0800, Daniel Kolesa <notifications@github.com> wrote:
> Hm, actually, this may be wrong. I'm looking at how other
> distributions do it, and they pretty much all put the modules in
> `libgladeui`; seems like these modules may be used at runtime by
> GLADE-using applications.

Hm, I'm not a heavy user of xfce to conform this.
I mostly set it up for my sister.

From my limited time with xfce, libgladeui works fine without those
modules.

However, Arch disagree with your assertment.
They ship all those modules with glade, see:
https://www.archlinux.org/packages/extra/x86_64/glade/files/

and, the usr/lib/libglade-2.0.so with libgladeui, see:
https://www.archlinux.org/packages/extra/x86_64/libglade/files/

> Which means, the right way would be to move the modules into the
> `libgladeui` package, as well as the python dependencies.
> 
> Interestingly, none of them seem to split the modules into subpackages...

I splited those submodules since webkit2gtk dependencies looks too big
to be installed.

However, consider glade is mostly a development package,
I think we can merge it back.

-- 
Danh

**Comment by q66** [comment]
Debian:

https://packages.debian.org/sid/alpha/libgladeui-2-6/filelist
https://packages.debian.org/sid/libgladeui-2-6

all the modules are in `libgladeui` and it depends on both Python and Webkit.

The data files are then present in `libgladeui-common`, I don't think we need to split as much as that.

Since both the python and webkit modules appear to be optional, here is what we could do:

1) Move the modules and appropriate data in `libgladeui3`
2) Create `libgladeui3-python` and `libgladeui3-webkit`, each depending on `libgladeui3`; afterwards, the applications that require those modules could depend on them explicitly (there doesn't seem to be any of those, though)

**Comment by sgn** [comment]
I think those modules are plugins to glade's designed tools.

Our libxfce4ui is depended on libglade3ui because we're shipping a glade3's plugin with xfce:

```
$ xbps-query -Rf libxfce4ui | grep glade
/usr/lib/glade/modules/libxfce4uiglade2.so
/usr/share/glade/catalogs/libxfce4ui-2.xml
/usr/share/glade/pixmaps/hicolor/16x16/actions/widget-libxfce4ui-xfce-titled-dialog.png
/usr/share/glade/pixmaps/hicolor/22x22/actions/widget-libxfce4ui-xfce-titled-dialog.png
```

From libxfce4ui's configure:
```
$ ./configure --help
  --with-gladeui-catalogdir=PATH
                          Specify where to install glade designer catalog
                          files (default=autodetect)
  --with-gladeui-moduledir=PATH
                          Specify where to install glade designer modules
                          (default=autodetect)
  --with-gladeui-pixmapdir=PATH
                          Specify where to install glade designer pixmaps
                          (default=autodetect)
  --with-gladeui2-catalogdir=PATH
                          Specify where to install glade 3.0 designer catalog
                          files (default=autodetect)
  --with-gladeui2-moduledir=PATH
                          Specify where to install glade 3.0 designer modules
                          (default=autodetect)
  --with-gladeui2-pixmapdir=PATH
                          Specify where to install glade 3.0 designer pixmaps
                          (default=autodetect)
```
and configure.ac
```
dnl *********************************************************
dnl *** Optional support for the Glade Interface Designer ***
dnl *********************************************************
dnl Do not try to build gladeui when gtk2 is disabled
```

I think all modules are optional plugins to glade,
and we should split those plugins out of our libxfce4ui

**Comment by q66** [comment]
As far as I can see those modules are not for the interface designer, but rather they contain widget implementations that can be used at runtime by applications *as well as the designer*, same with the xfce plugin.

**Comment by sgn** [comment]
> As far as I can see those modules are not for the interface designer,
> but rather they contain widget implementations that can be used
> at runtime by applications _as well as the designer_, same with the xfce plugin.

I don't think so,
Let's take libxfce4uiglade2.so as an example, it's compiled from a single C source file,
and contains only 3 functions:
```
void       glade_xfce_titled_dialog_post_create        (GladeWidgetAdaptor *adaptor,
                                                        GObject            *object,
                                                        GladeCreateReason   reason);
GtkWidget *glade_xfce_titled_dialog_get_internal_child (GladeWidgetAdaptor *adaptor,
                                                        GtkDialog          *dialog,
                                                        const gchar        *name);
GList     *glade_xfce_titled_dialog_get_children       (GladeWidgetAdaptor *adaptor,
                                                        GtkDialog          *dialog);
```
Which is used by glade
```
<?xml version="1.0" encoding="UTF-8"?>
<glade-catalog version="4.12.0" supports="gtkbuilder" name="libxfce4ui-2" library="xfce4uiglade2" domain="glade3" depends="gtk+" book="xfce4">
  <glade-widget-classes>
    <glade-widget-class name="XfceTitledDialog" generic-name="xfce-titled-dialog" title="Titled Dialog">
      <post-create-function>glade_xfce_titled_dialog_post_create</post-create-function>
      <get-internal-child-function>glade_xfce_titled_dialog_get_internal_child</get-internal-child-function>
      <get-children-function>glade_xfce_titled_dialog_get_children</get-children-function>
      <properties>
        <property translatable="True" ignore="False" id="subtitle" name="Subtitle"></property>
        <property translatable="True" ignore="False" id="title"/>
        <property ignore="True" id="icon"/>
        <property themed-icon="True" ignore="False" id="icon-name"/>
      </properties>
    </glade-widget-class>
  </glade-widget-classes>
  <glade-widget-group name="xfce4-widgets" title="Xfce 4 Widgets">
    <glade-widget-class-ref name="XfceTitledDialog"/>
  </glade-widget-group>
</glade-catalog>
```
as described by: https://developer.gnome.org/gladeui/stable/catalogintro.html

As far as I can tell, those functions are used to tell glade3
 the supported properties of XfceTitledDialog.


> I.e. the modules are loaded and used by `libgladeui`, which exposes them both to the interface designer itself as well as applications with interfaces designed using GLADE.

I strongly believe that the application itself uses the Gtk+ derived Widget,
those modules were there to tell glade their supported properties.

**Comment by q66** [comment]
If you look at how those functions are implemented: https://github.com/xfce-mirror/libxfce4ui/blob/master/glade/libxfce4ui-glade.c

Yes, these functions are used from XML descriptions of UIs. Then when you create a UI using GLADE, the library will build the UI using those descriptions, and use those functions where appropriate, at runtime, as AFAIK you can introspect the structure of the UI, it's not statically generated Gtk UI. See the documentation at https://developer.gnome.org/gladeui/stable/widgetclasses.html

`libgladegtk.so` is needed for gtk applications using GLADE, so it should always be present. I think the others can be made into subpackages like `libgladeui3-python` and `libgladeui3-webkit`, with dependencies on `libglade3`, in order to reduce base dependencies; then things needing those can depend on them as appropriate.

**Comment by sgn** [comment]
On 2020-01-21 19:59:28-0800, Daniel Kolesa <notifications@github.com> wrote:
> If you look at how those functions are implemented:
> https://github.com/xfce-mirror/libxfce4ui/blob/master/glade/libxfce4ui-glade.c

I'd looked at them already,

> Yes, these functions are used from XML descriptions of UIs. Then

Those catalogues aren't XML description of UI.
Let's take xfce4-terminal as a reference, the generated:

    /usr/share/xfce4/terminal/terminal-preferences.ui

doesn't use those functions, and it doesn't refer to glade at all.

> when you create a UI using GLADE, the library will build the UI

The keyword is `create an UI using glade`, which xfce doesn't.
the xfce plugin is merely written to support designer using glade
to design XFCE widget.

And, XFCE doesn't need glade to create widget at runtime.

The real dependency of XFCE to use the glade-generated-xml is
GtkBuilder modules from GTK itself. From https://glade.gnome.org

> The user interfaces designed in Glade are saved as XML, and by using
> the GtkBuilder GTK+ object these can be loaded by applications
> dynamically as needed. 

I think you might confuse between libgladeui and libglade,
the former is the one shipped with glade,
the latter is a former dependency of gtk to use those glade generated
XML-base UI, and it's replaced by GtkBuilder from GTK itself.
See: https://mail.gnome.org/archives/devel-announce-list/2009-May/msg00003.html

-- 
Danh

**Comment by q66** [comment]
It doesn't matter what xfce does. GLADE from version 3 is meant to be modular, and via libgladeui you can access exactly the same stuff the designer application does, which includes the plugins. It's just wrong to restrict the plugins to the designer itself.

**Comment by sgn** [comment]
On 2020-01-30 04:22:30-0800, Daniel Kolesa <notifications@github.com> wrote:
> It doesn't matter what xfce does. GLADE from version 3 is meant to
> be modular, and via libgladeui you can access exactly the same stuff

We don't need anything from glade to use glade-generated-UI.

> the designer application does, which includes the plugins. It's just
> wrong to restrict the plugins to the designer itself.

Here is the answer from #xfce

  JackFrost | libxfce4ui-glade, if it's like the one in Ubuntu, contains glade/modules/libxfce4uiglade2.so and is for working on Xfce projects in glade itself, when
            | they use xfce-titled-dialog.
        sgn | So, it's for developer of XFCE projects only, and it's not meant for end users, right?
 Bashing-om | sgn: ^^ and " sysop@x1804mini:~$ apt depends libxfce4ui-glade >> Depends: libxfce4ui-2-0 also has a list of dependencies.
  JackFrost | sgn: Unless those end users are developing Xfce. :P
  JackFrost | sgn: Is that the GTK2 or GTK3 one?


Anyway, I think a compromised solution may suite your view.
I'll split libgladeui3 as same as Debian and RedHat.
I don't think anyone else would need it, except GTK Designer, themselves.

But, I'll split libxfce4ui-glade out of libxfce4ui.
This libxfce4ui-glade will depend on libgladeui3,
anyone that worry about different UX with designer (which isn't) can install it themselves.
Ubuntu does it that way, Xubuntu is pretty popular and well-tested distribution,
follows their steps look like a sensible choice to me.

-- 
Danh

**Comment by sgn** [comment]
On 2020-01-30 04:22:30-0800, Daniel Kolesa <notifications@github.com> wrote:
> It doesn't matter what xfce does. GLADE from version 3 is meant to
> be modular, and via libgladeui you can access exactly the same stuff

We don't need anything from glade to use glade-generated-UI.

> the designer application does, which includes the plugins. It's just
> wrong to restrict the plugins to the designer itself.

Here is the answer from #xfce
```
  JackFrost | libxfce4ui-glade, if it's like the one in Ubuntu, contains glade/modules/libxfce4uiglade2.so and is for working on Xfce projects in glade itself, when
            | they use xfce-titled-dialog.
        sgn | So, it's for developer of XFCE projects only, and it's not meant for end users, right?
 Bashing-om | sgn: ^^ and " sysop@x1804mini:~$ apt depends libxfce4ui-glade >> Depends: libxfce4ui-2-0 also has a list of dependencies.
  JackFrost | sgn: Unless those end users are developing Xfce. :P
  JackFrost | sgn: Is that the GTK2 or GTK3 one?
```

Anyway, I think a compromised solution may suite your view.
I'll split libgladeui3 as same as Debian and RedHat.
I don't think anyone else would need it, except GTK Designer, themselves.

But, I'll split libxfce4ui-glade out of libxfce4ui.
This libxfce4ui-glade will depend on libgladeui3,
anyone that worry about different UX with designer (which isn't) can install it themselves.
Ubuntu does it that way, Xubuntu is pretty popular and well-tested distribution,
follows their steps look like a sensible choice to me.

**Comment by q66** [comment]
The xfce problem is separate from the Glade problem; libgladeui is not needed to use apps using glade-made UI, but things that do use libgladeui may depend on the plugins. So yes, split off the xfce libgladeui plugin, but do the separation like Debian/RH.

**Comment by q66** [comment]
I will review the PR once you have updated the split, and once it's fine we can merge it.

**Comment by sgn** [comment]
I've splited as the same time as my comment.

On 3 February 2020 17:32:00 GMT+07:00, Daniel Kolesa <notifications@github.com> wrote:
>I will review the PR once you have updated the split, and once it's
>fine we can merge it.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/void-linux/void-packages/pull/17766#issuecomment-581344941

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by q66** [comment]
Move the plugins from `glade3` into `libgladeui3` with `vmove usr/lib/glade/modules`. Also, switch `glade3` to `python3`.

**Comment by sgn** [comment]
On 2020-02-04 04:40:39-0800, Daniel Kolesa <notifications@github.com> wrote:
> Move the plugins from `glade3` into `libgladeui3` with `vmove
> usr/lib/glade/modules`. Also, switch `glade3` to `python3`.

I forgot to change it when merge the python3-glade back into
libglade3ui. configure script was changed before.


-- 
Danh

**Comment by q66** [comment]
looks good now, i will give it a build and merge it later

**Pull request closed without merging**
