### PR TITLE
sioyek: add .desktop file, fix arch

### PR DESCRIPTION
**Pull request by dkwo**
#### Testing the changes
- I tested the changes in this PR: yes.

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-musl)

### CODE REVIEW

**Comment by Duncaen** [comment]
https://github.com/ahrm/sioyek/blob/main/resources/sioyek.desktop instead of vendoring, maybe patch it if required (the latest commit is missing).

**Comment by dkwo** [comment]
@q66 I still think arch should be restricted: perhaps inlcude ppc*?

**Comment by dkwo** [comment]
also, it still depends on gcc, which looks suspicious

**Comment by q66** [comment]
leave archs alone, there is no problem with sioyek on other architectures

it's likely qmake being miscompiled due to cross, which then breaks native systems

in any case tagging archs here is wrong

**Comment by q66** [comment]
also the package cannot be crosscompiled, so removing nocross is wrong always

**Comment by dkwo** [comment]
For sure, it fails to natively build on aarch64 with present Void's setup.
I haven't tried to recompile qmake, so cannot comment.
I've noticed that Alpine also does this
`arch="all !aarch64 !armhf !armv7"  # fails to build`
I can put back no cross. What do you want me to do with arch?

**Comment by paper42** [comment]
If it doesn't even build natively, it should be arch restricted

**Comment by dkwo** [comment]
> probably with a list of supported archa, not a list of unsupported.

Which is what I did previously :) how about archs="i686* x86_64* ppc*" ?

**Comment by paper42** [comment]
I didn't see the comments above... This is tricky, ideally the solution would be to fix qmake, nocross and arch restrictions restrict something that's not broken.

**Comment by dkwo** [comment]
It's now working as expected.
Let me know what the consesus about arch/nocross is, so this can be merged.

**Comment by q66** [comment]
don't add any archs, leave it alone

**Comment by dkwo** [comment]
Can this simple change be merged?

**Comment by dkwo** [comment]
Superseded by https://github.com/void-linux/void-packages/pull/41318

**Comment by dkwo** [comment]
@q66 For the record, you were right: rebuilding natively qt5-qmake let's me build sioyek-2.0.0

**Pull request closed without merging**
