### PR TITLE
rust: update to 1.41.0, cargo: update to 0.42.0

### PR DESCRIPTION
**Pull request by q66**
tested on all ppc... needs testing on x86_64 and crossbuilds to ARM

### CODE REVIEW

**Comment by q66** [comment]
@jnbr

**Comment by q66** [comment]
also need uploading distfiles from https://repo.voidlinux-ppc.org/distfiles/ to the main distfiles location...

the list:

```
cargo-0.41.0-powerpc-unknown-linux-gnu.tar.xz
cargo-0.41.0-powerpc-unknown-linux-musl.tar.xz
cargo-0.41.0-powerpc64-unknown-linux-gnu.tar.xz
cargo-0.41.0-powerpc64-unknown-linux-musl.tar.xz
cargo-0.41.0-powerpc64le-unknown-linux-musl.tar.xz
rust-std-1.40.0-powerpc-unknown-linux-gnu.tar.xz
rust-std-1.40.0-powerpc-unknown-linux-musl.tar.xz
rust-std-1.40.0-powerpc64-unknown-linux-gnu.tar.xz
rust-std-1.40.0-powerpc64-unknown-linux-musl.tar.xz
rust-std-1.40.0-powerpc64le-unknown-linux-musl.tar.xz
rustc-1.40.0-powerpc-unknown-linux-gnu.tar.xz
rustc-1.40.0-powerpc-unknown-linux-musl.tar.xz
rustc-1.40.0-powerpc64-unknown-linux-gnu.tar.xz
rustc-1.40.0-powerpc64-unknown-linux-musl.tar.xz
rustc-1.40.0-powerpc64le-unknown-linux-musl.tar.xz
```

@Gottox @Duncaen @the-maldridge

**Comment by the-maldridge** [comment]
Done.

**Comment by q66** [comment]
great, thanks

that means only testing on x86_64/crossbuilds remains... i'm building firefox with it in the meantime to test something non-trivial

**Comment by jnbr** [comment]
Thanks.
I started builds for x86_64, i686 and arm*/aarch64 here.

**Comment by jnbr** [comment]
all builds passed here. lgtm.

**Comment by q66** [comment]
i'll merge this once the musl builder is back up...

**Pull request merged**
