### PR TITLE
New package: Converseen-0.9.9.0.

### PR DESCRIPTION
**Pull request by Veganizer**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (x86-64-musl)
- [ ] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [ ] aarch64-musl
  - [ ] armv7l
  - [ ] armv6l-musl

### CODE REVIEW

**Comment by Chocimier** [comment]
Please follow comments from previous PR.

**Comment by Veganizer** [comment]
> Please follow comments from previous PR.

Done it. Sorry was a copy paste fail :-)
Do you want to maintenance the package? I tought you are inactive because the PR is old.

**Comment by Chocimier** [comment]
I did not created other PR, just reviewed. You can maintain.

ImageMagick is not required, only libmagick, and that is detected.

(I dislike how it phones home on every run, but at least one can disable that.)

**Comment by Veganizer** [comment]
```bash
Could NOT find ImageMagick (missing: ImageMagick_mogrify_EXECUTABLE)
```
During compiling process, so ImageMagick is needed as makedependency. But I removed it as a dependency and used libmagick instead.

**Pull request closed without merging**
