### PR TITLE
ipv6calc: update to 3.0.0.

### PR DESCRIPTION
**Pull request by ndowens**

### CODE REVIEW

**Comment by Chocimier** [comment]
It fails to build here, could you rebase?

**Comment by ndowens** [comment]
> It fails to build here, could you rebase?

Just rebased, locally builds fine, lets see how it does with GH

**Comment by Chocimier** [comment]
`-Werror -Os` fail but `Werror -O2` passes, weird

**Comment by Chocimier** [comment]
Reported upstream.

**Pull request merged**
