### PR TITLE
minijail: update to v17.

### PR DESCRIPTION
**Pull request by jackloomen**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by leahneukirchen** [comment]
Why remove the patch?

**Comment by jackloomen** [comment]
> Why remove the patch?

Locally I didn't have it and everything worked, but when merging it broke all the builds, all checks failed seemingly on the patch executable choking on the patch.

**Comment by ericonr** [comment]
@jackloomen remember to have a single commit for the update (it should include the patch removal).

@q66 if he wants to check validity before merging.

**Comment by jackloomen** [comment]
no idea how to squash this properly. if you dont want to merge this close it and someone else can update minijail.

**Comment by q66** [comment]
put the patch back so I can see what fails

**Comment by q66** [comment]
well, okay then

**Pull request closed without merging**
