### PR TITLE
haproxy: update to 2.4.8

### PR DESCRIPTION
**Pull request by uhohspaghetios**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by paper42** [comment]
@zdykstra

**Comment by zdykstra** [comment]
Looks good here - nothing in the 2.4.4 -> 2.4.8 changelog stands out here as requiring adjustments in the template.

**Comment by uhohspaghetios** [comment]
> Looks good here - nothing in the 2.4.4 -> 2.4.8 changelog stands out here as requiring adjustments in the template.
> 
> Edit: Can you bump the PR to include the changelog in the template - `https://www.haproxy.org/download/2.4/src/CHANGELOG` ?

Dumb question, perhaps, but how do I do that in the template?  I haven't included the changelog before.

**Comment by zdykstra** [comment]
> > Looks good here - nothing in the 2.4.4 -> 2.4.8 changelog stands out here as requiring adjustments in the template.
> > Edit: Can you bump the PR to include the changelog in the template - `https://www.haproxy.org/download/2.4/src/CHANGELOG` ?
> 
> Dumb question, perhaps, but how do I do that in the template? I haven't included the changelog before.

Add the following on the line after `homepage=...` in the template:

`changelog="https://www.haproxy.org/download/2.4/src/CHANGELOG"`

**Comment by uhohspaghetios** [comment]
> > > Looks good here - nothing in the 2.4.4 -> 2.4.8 changelog stands out here as requiring adjustments in the template.
> > > Edit: Can you bump the PR to include the changelog in the template - `https://www.haproxy.org/download/2.4/src/CHANGELOG` ?
> > 
> > 
> > Dumb question, perhaps, but how do I do that in the template? I haven't included the changelog before.
> 
> Add the following on the line after `homepage=...` in the template:
> 
> `changelog="https://www.haproxy.org/download/2.4/src/CHANGELOG"`

Thanks for that.  Done.

**Pull request merged**
