### PR TITLE
python3-regex: update to 2022.9.13.

### PR DESCRIPTION
**Pull request by skmpz**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by classabbyamp** [comment]
does `/usr/lib/python3.10/site-packages/regex/test_regex.py` need to be installed?

**Comment by sgn** [comment]
> does `/usr/lib/python3.10/site-packages/regex/test_regex.py` need to be installed?

It's unittests.

**Comment by classabbyamp** [comment]
yes, that's why I ask

**Comment by skmpz** [comment]
yeah, sorry for the late response, let me remove it.

**Pull request merged**
