### PR TITLE
kmod: update to 29.

### PR DESCRIPTION
**Pull request by ailiop-git**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Should be ok to add a `make_check=no` with a comment about trying to access the `/lib/modules/$uname/build` directory.

**Comment by ericonr** [comment]
Also @Gottox

**Comment by codingjerk** [comment]
Actually, to support zstd compressed modules it was necessary to add `--with-zstd` too. I created a PR to this PR (https://github.com/ailiop-git/void-packages/pull/1).

Also I tested package on my system and on brand new one — it just works

**Comment by codingjerk** [comment]
And also I can confirm PR checkbox myself:

* [x]  I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me

**Comment by ericonr** [comment]
@codingjerk please create a separate PR for this extra feature?

**Pull request merged**
