### PR TITLE
Remove package: certbot-apache

### PR DESCRIPTION
**Pull request by kartikynwa**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

So I added this package a while back but it doesn't work anymore and I don't plan on maintaining it since I don't use Apache.

Really sorry for pushing a package that I wasn't going to maintain. Will be more careful from now on.

### CODE REVIEW

**Comment by kartikynwa** [comment]
Actually I think it would be better if someone could say whether this works or not. Moving to draft for now. Will test this later today and update or close the PR based on the results.

**Comment by ahesford** [comment]
If you remove this package, please also add it to the `removed-packages` template (alphabetically).

**Comment by kartikynwa** [comment]
So I tried this package today and it works. It requires some setup though:

1. Some Apache modules need to be enabled -- ssl, rewrite and maybe one other.
2. It needs to be run with flags `--apache-ctl /usr/bin/apachectl --apache-server-root /etc/apache`. Looks like this cannot be preconfigured while packaging. Unless we ship it as a patch. I can try filing a PR in the certbot repo for an override file like they have for a bunch of distros ([Arch for example](https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/_internal/override_arch.py))

**Comment by kartikynwa** [comment]
This PR got merged into certbot so after the next release and onwards `certbot --apache` should work almost out of the box.: https://github.com/certbot/certbot/pull/8891

Only caveat is that as a member there notes:

> Otherwise, --apache crashes until you enable the rewrite+ssl+socache modules by hand

Is there anything we can do about this? Feel free to let know if you have any suggestions.

**Pull request closed without merging**
