### PR TITLE
New package: electron24-24.2.0

### LINKED ISSUE #43744: Package request: electron24
### Package name

electron24

### Package homepage

https://www.electronjs.org/

### Description

Electron is a cross platform application framework based on web technologies. It powers applications like Slack, VS Code, etc.

We need the update from v19 for vscode-1.78.0, which will otherwise not render at all.

### Does the requested package meet the package requirements?

Compiled, Required

### Is the requested package released?

Yes

### PR DESCRIPTION
**Pull request by Johnnynator**
#### Testing the changes
- I tested the changes in this PR: **NO**

resolves #43744 

[ci skip]
[skip ci]

### CODE REVIEW

**Comment by atk** [comment]
I get an error when I try to build this: /void-packages/srcpkgs/electron24/template: line 114: cd: /builddir/electron24-24.2.0//builddir/electron24-24.2.0/src/electron: No such file or directory

**Comment by Johnnynator** [comment]
Remove the $wrksrc in the 2nd _git_init invocation. It should build fine for glibc after that. The musl should still fail.

**Comment by atk** [comment]
Thanks, but now I get

```bash
[316/45916] ACTION //chrome/common/extensions/api:generated_api_json_strings_bundle_generator_schema(//build/toolchain/linux/unbundle:default)
ninja: build stopped: subcommand failed.
=> ERROR: electron24-24.2.0_1: do_build: 'ninja ${makejobs} -C out/$_buildtype electron third_party/electron_node:headers' exited with 1
=> ERROR:   in do_build() at srcpkgs/electron24/template:412
```

**Comment by Johnnynator** [comment]
@atk do you have an updated vscode template, would like to test the musl build proper before merging.

**Comment by atk** [comment]
You can just increase the version and remove the ffmpeg-download patch, as it is no longer necessary. I'm currently on my mobile without access to my work station.

**Comment by Johnnynator** [comment]
I just get a 404, but nut sure what it is trying to fetch

```
[09:58:47] 'vscode-linux-x64-min' errored after 4.63 min
[09:58:47] HTTPError: Response code 404 (Not Found)
    at Request._onResponseBase (/builddir/vscode-1.78.0/node_modules/got/dist/source/core/index.js:913:31)
    at Request._onResponse (/builddir/vscode-1.78.0/node_modules/got/dist/source/core/index.js:948:24)
    at ClientRequest.<anonymous> (/builddir/vscode-1.78.0/node_modules/got/dist/source/core/index.js:962:23)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.emit (node:domain:552:15)
    at ClientRequest.origin.emit (/builddir/vscode-1.78.0/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:534:22)
error Command failed with exit code 1.
```

**Comment by atk** [comment]
Thanks for the info, I'll have a look later.

**Pull request merged**
