### PR TITLE
build-style: R-cran: refactor

### PR DESCRIPTION
**Pull request by sgn**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by Chocimier** [comment]
Distfiles are better to define in template, sure.
But what's wrong with makedepends?

**Comment by sgn** [comment]
On 2021-09-11 13:29:22-0700, Piotr ***@***.***> wrote:
> Distfiles are better to define in template, sure.
> But what's wrong with makedepends?

Nothing wrong per se.

However, I would like to drop the whole
common/environment/build-style, so build order can be sorted without
sourcing common/environment/build-style.

-- 
Danh

**Comment by Chocimier** [comment]
Inlining environment makes maintaining templates harder, while isn't enough to make templates sourcable. Harder part is parsing files like `common/build-helper/gir.sh` or conditional build options. How would you approach that?

**Comment by sgn** [comment]
> Inlining environment makes maintaining templates harder, while isn't enough to make templates sourcable. Harder part is parsing files like `common/build-helper/gir.sh` or conditional build options. How would you approach that?

Hm, I don't know, let's just keep *depends manipulation there.

**Pull request closed without merging**
