### PR TITLE
[NEED TESTER] dracut update to 051

### PR DESCRIPTION
**Pull request by sgn**
Since I'm bored, I'll step to be next person who breaks dracut (the other reason is I'm using a patched version of dracut that included by this version).

- This PR would require lot of testing, so I include a separated change to fix for bootchart from #28136 since I expect that one will be merged soon enough.
- From this version, dracut will print warning if `kernel_modules` or `kernel_cmdline` `+=` but not surrounding by whitespace, hence the change to `nvme-cli`
- Also switch distfiles to kernel site, with this distfiles, we have pre-generated manpages, save some time and has version attached.

### CODE REVIEW

**Comment by ahesford** [comment]
On 2021-01-24 at 20:59 (UTC -0500), Đoàn Trần Công Danh wrote:
> @sgn requested review from @void-linux/pkg-committers on: void-linux/void-packages#28137 [NEED TESTER] dracut update to 051.

Works fine for me, both as the ZFSBootMenu initramfs and as the ordinary
initramfs.

**Comment by ahesford** [comment]
The `squash` module now errors out if `systemd-initrd` is not available:
> dracut: dracut-squash only supports systemd bases [sic] initramfs

This is because the `check` function in `/usr/lib/dracut/modules.d/99squash/module-setup.sh` was changed from always returning 255 (which means "only use this module if explicitly requested") to throwing a `derror` message without 
systemd and returning 1 (which means "omit this module"). The error is harmless but could be scary to those unfamiliar with dracut.

I suggest one of three changes:
1. Patch the `check` function to again always return 255 without complaining;
2. Drop the `derror` call in that function; or
3. Include a conf file in `/usr/lib/dracut/dracut.conf.d` that adds `omit_dracutmodules+=" squash "`.

Pick your favorite.

Also, I noticed we have `/usr/lib/dracut/dracut.conf.d/00-void.conf` coming from `base-files` and `/usr/lib/dracut/dracut.conf.d/10-runit-void.conf` coming from `runit-void`. It might be nice to move these files to the `dracut` package itself rather than scattering them around.

**Comment by ericonr** [comment]
Squash makes me think of live systems. Do we have anything to worry about?

**Comment by ahesford** [comment]
Just users being alarmed by new messages when kernels are reconfigured.

**Comment by sgn** [comment]
> 1. Patch the `check` function to again always return 255 without complaining;

I'll pick this route.

> Also, I noticed we have `/usr/lib/dracut/dracut.conf.d/00-void.conf` coming from `base-files`

I think this change could be postponed for a while, I think it's better to not move files around when updating the package, (which potentially break).
Moving file around require updating both package at the same time.

> and `/usr/lib/dracut/dracut.conf.d/10-runit-void.conf` coming from `runit-void`. It might be nice to move these files to the `dracut` package itself rather than scattering them around.

While it's nice to have everything in single location, `runit-void` is maintained in another repo.
I think we'll re-visit the file moving later.

**Review by ahesford — APPROVED** [review]
LGTM. Patched version does not print a useless error with `xbps-reconfigure -f linux5.10`.

**Pull request merged**
