### PR TITLE
pacman: update to 6.0.1

### PR DESCRIPTION
**Pull request by Oreo639**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Given that arch had to import new patches (https://github.com/archlinux/svntogit-packages/commit/45a24c15e9db6cb6ed9b2c43e72eb66deb3ee7ee#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a) I think we should wait for a proper release.

**Comment by Oreo639** [comment]
Yeah, thank you for pointing that out. (I missed that)
Should I leave this open or close it?

**Comment by ericonr** [comment]
I think it's okay to leave it open, we just can't merge yet.

**Comment by ericonr** [comment]
#28217 we can remove the gpg patch then.

**Comment by Oreo639** [comment]
Alright. Thanks for the heads up.

**Comment by ericonr** [comment]
6.0.1 has been released :)

**Pull request merged**
