### PR TITLE
budgie-desktop: update to 10.7.2

### PR DESCRIPTION
**Pull request by chax**
This version bump fixes issue #43400 since the bug was obviously fixed upstream.

#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-LIBC)

### CODE REVIEW

**Comment by JoshStrobl** [comment]
This should have build and rundeps on zenity and given Void is using pre-GTK4 zenity, the configure flag of `-Duse-old-zenity=true` should be set, otherwise Budgie Desktop will use the new flags and functionality like display configuration confirmation dialogs will not function.

This will need to be updated again with some form of a new revision once Void updates zenity as well.

Thanks for the update @chax, much appreciated.

**Comment by chax** [comment]
@JoshStrobl what do you mean pre-GTK4 Zenity. Void has zenity version 3.43, isn't that the same version of zenity that Solus has?

**Comment by JoshStrobl** [comment]
> @JoshStrobl what do you mean pre-GTK4 Zenity. Void has zenity version 3.43, isn't that the same version of zenity that Solus has?

zenity before 3.90 (which ships in Fedora) is ported to GTK4 and libadwaita, changing the CLI flags. Any version before 3.90 needs to use `-Duse-old-zenity=true`

**Comment by chax** [comment]
> > @JoshStrobl what do you mean pre-GTK4 Zenity. Void has zenity version 3.43, isn't that the same version of zenity that Solus has?
> 
> zenity before 3.90 (which ships in Fedora) is ported to GTK4 and libadwaita, changing the CLI flags. Any version before 3.90 needs to use `-Duse-old-zenity=true`

@JoshStrobl Thanks for explanation, i did the changes, it should be good now.

**Comment by paper42** [comment]
to fix the cross builds, add zenity to hostmakedepends, the build system checks for it being available at build time

**Comment by aandmsantos0910** [comment]
I was wondering if there was a ETA for updating Budgie to Ver 10.8.1?

**Pull request merged**
