### PR TITLE
winusb: Use pkexec instead of gksudo for privilege escalation

### PR DESCRIPTION
**Pull request by bugcrazy**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by bugcrazy** [comment]
Patch for frontend-wxgtk: https://github.com/WoeUSB/WoeUSB-frontend-wxgtk/commit/94f1b083dcf64d8cdc95d5c552a24d18b0f32d22

**Comment by classabbyamp** [comment]
that commit has been included in releases, why not just update the package?

**Comment by bugcrazy** [comment]
> that commit has been included in releases, why not just update the package?

There have been no more winusb releases since 2015, the commit is more recent, derived from the code of another with the same code base.

**Comment by classabbyamp** [comment]
then perhaps winusb should be removed

**Comment by bugcrazy** [comment]
> then perhaps winusb should be removed

It can be removed winusb, woeusb is in the repository, it is a fork of winusb, but it is not maintained, woe-cli is a fork of woeusb, there is a more updated project is woeusb-ng, it is not in the repository.

This explains the status of the projects:
https://github.com/slacka/WoeUSB?tab=readme-ov-file

**Comment by sgn** [comment]
Let's remove winusb, and make woeusb provides winusb. Maybe winusb as symlink to woeuse?

**Comment by bugcrazy** [comment]
> Let's remove winusb, and make woeusb provides winusb. Maybe winusb as symlink to woeuse?

There could be a symlink, the command between the two, works the same, just changes the name.

**Pull request closed without merging**
