### PR TITLE
New package: planner-2.2.14

### PR DESCRIPTION
**Pull request by LinArcX**
[Closes](https://github.com/void-linux/void-packages/issues/20825)

### CODE REVIEW

**Comment by LinArcX** [comment]
[What's wrong](https://travis-ci.org/github/void-linux/void-packages/jobs/674166980#L4220)?

**Comment by pullmoll** [comment]
Try with `build_helper="gir"` perhaps.

**Comment by LinArcX** [comment]
> Try with `build_helper="gir"` perhaps.

Still same issues.

**Comment by pullmoll** [comment]
Fixed cross and also the musl problem with `_NL_TIME_FIRST_WEEKDAY` being not defined in `<langinfo.h>`. For musl thus the first weekday is always sunday (0). ;-P

**Pull request closed without merging**
