### PR TITLE
chromium: update to 88.0.4324.182.

### PR DESCRIPTION
**Pull request by pbui**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

[ci skip]

- Built for x86_64, x86_64-musl, i686.
- Tested on x86_64.

- Related blog post: https://chromereleases.googleblog.com/2021/02/stable-channel-update-for-desktop_16.html
- Pre-built packages: https://h4x0r.space

### CODE REVIEW

**Review by ericonr — COMMENTED** [review]
Working cleanly here, thanks for the pre-built packages :)

I got this running configure:

```
The variable "binutils_path" was set as a build argument
but never appeared in a declare_args() block in any buildfile.
```

It was present in a previous version as well, so I don't think it's urgent to fix. Just a heads up though :)

**Comment by pbui** [comment]
I did a pass of the template and removed/updated any deprecated flags: is_desktop_linux, closure_compile, binutils_path, linux_use_bundled_binutils.

Since these were ignored (because they were not declared), the change should not impact the build (I hope).

**Comment by ericonr** [comment]
I'm a tad worried about the flag changes, could you try triggering a build?

**Comment by pbui** [comment]
@ericonr What do you mean by triggering a build?  If you mean re-building the packages locally, then sure, I can do that.

**Comment by ericonr** [comment]
Yes, sorry. I meant rebuilding locally.

**Comment by pbui** [comment]
They all built fine (x86, x86_64-musl, and i686).  Looks like nothing really changed since CCACHE was used extensively.  I uploaded the new packages to https://h4x0r.space.

**Pull request merged**
