### PR TITLE
New package: gn-0.0.20201022

### PR DESCRIPTION
**Pull request by shizonic**

### CODE REVIEW

**Comment by shizonic** [comment]
May one review/merge this so I can continue working on https://github.com/void-linux/void-packages/pull/25436?

**Comment by ericonr** [comment]
@Johnnynator @pbui

**Comment by ericonr** [comment]
That said, it probably makes sense to do this one together with `deno`.

**Comment by shizonic** [comment]
So two pkgs in one PR?

**Comment by ericonr** [comment]
In that case it's fine, because `gn` is a dependency of `deno`.

**Comment by shizonic** [comment]
Okay got it. Will update it asap. Thank you!

**Comment by shizonic** [comment]
Close this because `gn` is now included in `deno` PR: https://github.com/void-linux/void-packages/pull/25436

**Pull request closed without merging**
