### PR TITLE
PrusaSlicer: update to 2.1.1

### PR DESCRIPTION
**Pull request by zlice**

### CODE REVIEW

**Comment by zlice** [comment]
replace https://github.com/void-linux/void-packages/pull/18280

**Comment by Piraty** [comment]
please fix cross compilation

**Comment by zlice** [comment]
i see what happened. deleted my branches accidentally and that closed the other PR for cereal https://github.com/void-linux/void-packages/pull/18279 which was never merged and this depends on

**Comment by Piraty** [comment]
obsoleted by #21825

**Pull request closed without merging**
