### PR TITLE
New package: dante-1.4.2

### PR DESCRIPTION
**Pull request by shtayerc**
I am not sure if license is correct. Also I would need some help with cross compiling.

### CODE REVIEW

**Comment by Chocimier** [comment]
Setting compiler to gcc will always break, because it is native compiler rather than cross.

There is a patch https://git.buildroot.org/buildroot/plain/package/dante/0002-osdep-m4-Remove-getaddrinfo-too-low-checks.patch that together with autoreconf -fi fixes cross build.

**Comment by shtayerc** [comment]
@Chocimier is there anything else that should be fixed?

**Comment by Chocimier** [comment]
Modfying shlibs is not needed, ignore warnings. Linked patch has nice explanation why it is needed.

**Comment by shtayerc** [comment]
Fixed.

**Pull request merged**
