### PR TITLE
qimgv: update to 1.0.1 + add kde build option

### PR DESCRIPTION
**Pull request by FollieHiyuki**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
@travankor ok?

**Comment by travankor** [comment]
You could also add a build option for opencv.

**Comment by travankor** [comment]
Could you please bump to 1.0.2? Otherwise, LGTM.

**Comment by FollieHiyuki** [comment]
Bumped to 1.0.2

**Pull request merged**
