### PR TITLE
babl: update to 0.1.82

### PR DESCRIPTION
**Pull request by ndowens**
@Gottox I tested this update against build of gegl-devel and it built fine even during cross-build.

### CODE REVIEW

**Comment by ericonr** [comment]
On native it can find vapigen, but that fails for cross. Do you know if that can be solved?

> Run-time dependency vapigen found: YES 0.50.0

**Comment by ndowens** [comment]
> On native it can find vapigen, but that fails for cross. Do you know if that can be solved?
> 
> > Run-time dependency vapigen found: YES 0.50.0

Unsure but will try

**Comment by biopsin** [comment]
Only way to satisfy "Run-time dependency vapigen found: YES 0.50.0" when cross build 
is adding vala-devel to makedepends too

**Comment by ericonr** [comment]
Ok, I'm taking this over in #27511

**Pull request closed without merging**
