### PR TITLE
curl: revert to 7.63.0 and apply patches for latest CVEs

### PR DESCRIPTION
**Pull request by jnbr**
libcurl-7.64.0 introduced a bug which causes segfaults on musl

### CODE REVIEW

**Comment by Gottox** [comment]
how can I reproduce this issue?

**Comment by jnbr** [comment]
was triggered by updating cargo: https://github.com/void-linux/void-packages/pull/8230

**Comment by jnbr** [comment]
I used `cargo install cargo-watch` (the crate is arbitrary) to reproduce the issue and bisected it to https://github.com/curl/curl/commit/fb445a1e18d12f577964c9347bc5bca74b37cd08

**Comment by jnbr** [comment]
Opened an issue upstream: https://github.com/curl/curl/issues/3541

**Pull request merged**
