### PR TITLE
inkscape: update to 1.2.2

### PR DESCRIPTION
**Pull request by hervyqa**
add `python3-cssselect` to open "Manage Extensions" dialog.

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64, x86_64-musl)

#### 1.1.2 (x86_64)

image

#### 1.2.1 (x86_64)

Screenshot_20220518_144113

#### 1.2.1 (x86_64-musl)

Screenshot_20220518_090746

### CODE REVIEW

**Comment by hervyqa** [comment]
Success, except x86_64-musl.
cc @ericonr

**Comment by tibequadorian** [comment]
https://gitlab.com/inkscape/inkscape/-/issues/2241

**Comment by hervyqa** [comment]
> https://gitlab.com/inkscape/inkscape/-/issues/2241

yes, I already know about this issue. previous versions of inkscape also failed on the x86_64-musl version (#34478), but it was merged.

**Comment by hervyqa** [comment]
or maybe it's better to wait for the final 1.2 release as well this march.

**Comment by hervyqa** [comment]
Test error. Need help :)

## i686

```
The following tests FAILED: 

2864	 30 - test_lpe (Failed) 

2865Errors while running CTest 

2866ninja: build stopped: subcommand failed. 

2867=> ERROR: inkscape-1.2_1: do_check: '${make_check_pre} ${make_cmd} ${make_check_args} ${make_check_target}' exited with 1 

2868=> ERROR: in do_check() at common/build-style/cmake.sh:119 

2869Error: Process completed with exit code 1.
```

## x86_64-musl

```
The following tests FAILED: 

2258	 3 - test_drag-and-drop-svgz (SEGFAULT) 

2259	 25 - test_svg-extension (SEGFAULT) 

2260	 30 - test_lpe (SEGFAULT) 

2261	 31 - test_lpe64 (SEGFAULT) 

2262Errors while running CTest 

2263ninja: build stopped: subcommand failed. 

2264=> ERROR: inkscape-1.2_1: do_check: '${make_check_pre} ${make_cmd} ${make_check_args} ${make_check_target}' exited with 1 

2265=> ERROR: in do_check() at common/build-style/cmake.sh:119 

2266Error: Process completed with exit code 1.
```

**Comment by ericonr** [comment]
hmm, nice that they managed to fix most of the segfaults on musl

I guess we need to report `test_lpe` to upstream, probably. Or try to look at what it does.

**Comment by hervyqa** [comment]
> I guess we need to report `test_lpe` to upstream, probably. Or try to look at what it does.

LPE (Live Path Effect) is used to manipulate path objects easily. There are many types of LPE, but in this LPE test does not mention which LPE failed to be tested.

```
The following tests FAILED:
	 30 - test_lpe (Failed)
```
Maybe one of them failed the test, but I don't know which one.

Screenshot_20220520_112858

source: https://gitlab.com/inkscape/inkscape/-/blob/master/testfiles/src/lpe-test.cpp

```cpp
// A) FILE BASED TESTS
// TEST_F(LPETest, Bool_multi_px_1_1)                          { run(); }
// TEST_F(LPETest, Bool_multi_mm_1_1)                          { run(); }
TEST_F(LPETest, AttachPath_0_92_5_mixed)                    { run(); }
TEST_F(LPETest, AttachPath_mm_1_0_2)                        { run(); }
TEST_F(LPETest, AttachPath_px_1_0_2)                        { run(); }
TEST_F(LPETest, BoundingBox_mixed_0_92_5)                   { run(); }
TEST_F(LPETest, BoundingBox_mm_1_0_2)                       { run(); }
TEST_F(LPETest, BoundingBox_px_1_0_2)                       { run(); }
TEST_F(LPETest, CloneOriginal_mixed_0_92_5)                 { run(); }
// linked item is broken in 1.0.2 because group cliboard items, use same version of 1.1 but resaved in 1.2 to get comapat in 1.0.1 or before the group clipboard is added
TEST_F(LPETest, CloneOriginal_boken_1_0_2)                  { run(); }
TEST_F(LPETest, CloneOriginal_mixed_px_1_1)                 { run(); }
TEST_F(LPETest, CloneOriginal_mixed_mm_1_1)                 { run(); }
TEST_F(LPETest, ConstructGrid_mixed_0_92_5)                 { run(); }
TEST_F(LPETest, ConstructGrid_mm_1_0_2)                     { run(); }
TEST_F(LPETest, ConstructGrid_px_1_0_2)                     { run(); }
TEST_F(LPETest, Transform2Points_path_0_92_5)               { run(); }
TEST_F(LPETest, Transform2Points_multi_px_1_0_2)            { run(); }
TEST_F(LPETest, Transform2Points_multi_mm_1_0_2)            { run(); }
TEST_F(LPETest, VonCoch_path_0_92_5)                        { run(); }
TEST_F(LPETest, VonCoch_multi_px_1_0_2)                     { run(); }
TEST_F(LPETest, VonCoch_multi_mm_1_0_2)                     { run(); }
TEST_F(LPETest, StitchSubPaths_path_0_92_5)                 { run(); }
TEST_F(LPETest, StitchSubPaths_multi_px_1_0_2)              { run(); }
TEST_F(LPETest, StitchSubPaths_multi_mm_1_0_2)              { run(); }
TEST_F(LPETest, Spiro_mixed_0_92_5)                         { run(); }
TEST_F(LPETest, Spiro_mm_1_0_2)                             { run(); }
TEST_F(LPETest, Spiro_px_1_0_2)                             { run(); }
TEST_F(LPETest, Slice_multi_px_1_1)                         { run(); }
TEST_F(LPETest, Slice_multi_mm_1_1)                         { run(); }
TEST_F(LPETest, Simplify_path_0_92_5)                       { run(); }
TEST_F(LPETest, Simplify_multi_px_1_0_2)                    { run(); }
TEST_F(LPETest, Simplify_multi_mm_1_0_2)                    { run(); }
TEST_F(LPETest, ShowHandles_path_0_92_5)                    { run(); }
TEST_F(LPETest, ShowHandles_multi_px_1_0_2)                 { run(); }
TEST_F(LPETest, ShowHandles_multi_mm_1_0_2)                 { run(); }
TEST_F(LPETest, Ruler_path_0_92_5)                          { run(); }
TEST_F(LPETest, Ruler_multi_px_1_0_2)                       { run(); }
TEST_F(LPETest, Ruler_multi_mm_1_0_2)                       { run(); }
TEST_F(LPETest, RoughHatches_path_0_92_5)                   { run(); }
TEST_F(LPETest, RoughHatches_multi_px_1_0_2)                { run(); }
TEST_F(LPETest, RoughHatches_multi_mm_1_0_2)                { run(); }
// Rougen Test till 1.1 fail because wrong implementation of rand on the LPE
TEST_F(LPETest, Roughen_path_1_1)                           { run(); }
TEST_F(LPETest, EllipseFromPoints_multi_px_1_0_2)           { run(); }
TEST_F(LPETest, EllipseFromPoints_multi_mm_1_0_2)           { run(); }
TEST_F(LPETest, PowerMask_multi_px_1_0_2)                   { run(); }
TEST_F(LPETest, PowerMask_multi_mm_1_0_2)                   { run(); }
TEST_F(LPETest, PowerClip_multi_px_1_0_2)                   { run(); }
TEST_F(LPETest, PowerClip_multi_mm_1_0_2)                   { run(); }
TEST_F(LPETest, PerspectiveEnvelope_mixed_0_92_5)           { run(); }
TEST_F(LPETest, PerspectiveEnvelope_multi_mm_1_0_2)         { run(); }
TEST_F(LPETest, PerspectiveEnvelope_multi_px_1_0_2)         { run(); }
TEST_F(LPETest, Offset_multi_px_1_0_2)                      { run(); }
TEST_F(LPETest, Offset_multi_mm_1_0_2)                      { run(); }
TEST_F(LPETest, Offset_multi_px_1_1)                        { run(); }
TEST_F(LPETest, MirrorSymmetry_path_0_92_5)                 { run(); }
TEST_F(LPETest, MirrorSymmetry_multi_px_1_0_2)              { run(); }
TEST_F(LPETest, MirrorSymmetry_multi_mm_1_0_2)              { run(); }
TEST_F(LPETest, MeasureSegments_multi_px_1_0_2)             { run(); }
TEST_F(LPETest, MeasureSegments_multi_mm_1_0_2)             { run(); }
TEST_F(LPETest, Lattice2_path_0_92_5)                       { run(); }
TEST_F(LPETest, Lattice2_multi_px_1_0_2)                    { run(); }
TEST_F(LPETest, Lattice2_multi_mm_1_0_2)                    { run(); }
TEST_F(LPETest, Knot_path_0_92_5)                           { run(); }
TEST_F(LPETest, Knot_multi_px_1_0_2)                        { run(); }
TEST_F(LPETest, Knot_multi_mm_1_0_2)                        { run(); }
TEST_F(LPETest, JoinType_multi_px_1_0_2)                    { run(); }
TEST_F(LPETest, JoinType_multi_mm_1_0_2)                    { run(); }
TEST_F(LPETest, Interpolate_path_0_92_5)                    { run(); }
TEST_F(LPETest, Interpolate_multi_px_1_0_2)                 { run(); }
TEST_F(LPETest, Interpolate_multi_mm_1_0_2)                 { run(); }
TEST_F(LPETest, InterpolatePoints_path_0_92_5)              { run(); }
TEST_F(LPETest, InterpolatePoints_multi_px_1_0_2)           { run(); }
TEST_F(LPETest, InterpolatePoints_multi_mm_1_0_2)           { run(); }
TEST_F(LPETest, Gears_path_0_92_5)                          { run(); }
TEST_F(LPETest, Gears_multi_px_1_0_2)                       { run(); }
TEST_F(LPETest, Gears_multi_mm_1_0_2)                       { run(); }
TEST_F(LPETest, FilletChamfer_multi_px_1_0_2)               { run(); }
TEST_F(LPETest, FilletChamfer_multi_mm_1_0_2)               { run(); }
// NEED to test on 0.92 no working one here (gnome 40)
// TEST_F(LPETest, FillBetweenStrokes_path_0_92_5)          { run(); }
TEST_F(LPETest, FillBetweenStrokes_path_multi_px_1_0_2)     { run(); }
TEST_F(LPETest, FillBetweenStrokes_path_multi_mm_1_0_2)     { run(); }
// NEED to test on 0.92 no working one here (gnome 40)
// TEST_F(LPETest, FillBetweenMany_multi_0_92_5)               { run(); }
TEST_F(LPETest, FillBetweenMany_multi_px_1_0_2)             { run(); }
TEST_F(LPETest, FillBetweenMany_multi_mm_1_0_2)             { run(); }
TEST_F(LPETest, Ellipse5pts_path_0_92_5)                    { run(); }
TEST_F(LPETest, Ellipse5pts_ellipse_px_1_0_2)               { run(); }
TEST_F(LPETest, Ellipse5pts_ellipse_mm_1_0_2)               { run(); }
TEST_F(LPETest, DashedStroke_multi_px_1_0_2)                { run(); }
TEST_F(LPETest, DashedStroke_multi_mm_1_0_2)                { run(); }
TEST_F(LPETest, RotateCopies_multi_mm_1_0_2)                { run(); }
TEST_F(LPETest, RotateCopies_multi_px_1_0_2)                { run(); }
```

**Comment by ericonr** [comment]
9ac33cf7099aba595fe6b5a3412c795fc9a9313b removed python3-lockfile, we can't depend on it

https://pypi.org/project/lockfile/ says it's deprecated.

**Comment by hervyqa** [comment]
I just found out `python3-lockfile` is included in the removed packages. But it is necessary to open `extension`> `management extension`. Alright, I delete the dependencies. I think the extension is lacking.

**Comment by ericonr** [comment]
IMO, if you're up for it, we can add the package back, just need to increase the revision. Or ask inkscape to not depend on a deprecated package.

**Comment by ericonr** [comment]
At least the LPE test specifically seems to be the same issue plaguing other tests on musl, from my debugging. I guess I should have tested on glibc instead.

**Comment by hervyqa** [comment]
seems fine.
Screenshot_20220528_015113

**Comment by hervyqa** [comment]
Hi @oreo639, is the patch libpoppler 22.06.0 compatible with inkscape 1.2?

**Comment by oreo639** [comment]
All of the poppler patches for inkscape were taken from upstream.

The latest patch does appear to be in inkscape 1.2:
https://gitlab.com/inkscape/inkscape/-/commit/d989cdf1059c78bc3bb6414330242073768d640b

**Comment by hervyqa** [comment]
inkscape 1.2.1 still fail in lpe test. cc @ericonr 
```
The following tests FAILED:
	 30 - test_lpe (Failed)
```

**Comment by paper42** [comment]
@hervyqa I somehow got to the Author field of the commit, but you did all of the work. Could you change it to your name?

**Comment by hervyqa** [comment]
> @hervyqa I somehow got to the Author field of the commit, but you did all of the work. Could you change it to your name?

Oh sorry.. done.

**Comment by dmarto** [comment]
Can not help with the test failing in CI, but wanted to mention that I have been using Inkscape build from this PR, for some days now and everything (or at least the stuff I use) works perfect, that is on x86_64-glibc; and if there is something that I can help with - ping me.

**Comment by hervyqa** [comment]
I hope in version 1.3 later all tests are successful. hope so

**Comment by manfredu** [comment]
I try to build inkscape with this template but without success:
````
=> inkscape-1.2.2_1: installing host dependencies: automake-1.16.5_1 pkg-config-0.29.2_3 libtool-2.4.7_3 intltool-0.51.0_6 gettext-0.21_4 glib-devel-2.74.0_3 perl-XML-Parser-2.46_4 which-2.21_3 cmake-3.25.1_1 ninja-1.11.1_2 ...
=> inkscape-1.2.2_1: installing target dependencies: harfbuzz-devel-5.1.0_2 libsoup-devel-2.74.0_1 gsl-devel-2.7.1_1 pango-devel-1.50.12_1 libatomic_ops-devel-7.6.14_1 double-conversion-devel-3.1.5_1 gc-devel-8.2.2_1 libwpd-devel-0.10.3_1 libcdr-devel-0.1.7_4 libvisio-devel-0.1.7_5 poppler-devel-22.12.0_1 libwpd-devel-0.10.3_1 potrace-devel-1.16_2 gtkmm-devel-3.24.5_1 gdl-devel-3.40.0_1 gtkspell3-devel-3.0.10_3 aspell-devel-0.60.8_5 libxslt-devel-1.1.37_2 libgomp-devel-12.2.0_1 libwpg-devel-0.3.3_1 poppler-glib-devel-22.12.0_1 ...
=> inkscape-1.2.2_1: removing autodeps, please wait...
=> ERROR: inkscape-1.2.2_1: failed to install target dependencies! (error 19)
ncurses-libs-6.2_4 in transaction breaks installed pkg `ncurses-6.3_1'                                                  
Transaction aborted due to unresolved dependencies.
=> ERROR: Please see above for the real error, exiting...
````

What is causing this...?

**Comment by paper42** [comment]
> What could be causing this...?

Something on your side, try rebasing this branch on top of master and deleting hostdir/binpkgs, it could have an old build of ncurses.

**Comment by manfredu** [comment]
> > What could be causing this...?
> 
> Something on your side, try rebasing this branch on top of master and deleting hostdir/binpkgs, it could have an old build of ncurses.

Deleting hostdir/binpkgs did help, thanks!

**Comment by 1is7ac3** [comment]
hello. as it goes, in inkscape almost 100% functional.
checking necessary dependencies on:
https://gitlab.com/inkscape/inkscape-ci-docker/-/raw/master/install_dependencies.sh
I have added the necessary dependencies to build, and that the spell checker and extensions work
I built this PR locally for my native architecture, (x86_64, i686)

hostmakedepends="automake pkg-config libtool intltool gettext
 glib-devel perl-XML-Parser which libmagick-devel"
makedepends="harfbuzz-devel libsoup-devel gsl-devel pango-devel libatomic_ops-devel
 double-conversion-devel gc-devel libwpd-devel libcdr-devel libvisio-devel
 poppler-devel libwpd-devel potrace-devel gtkmm-devel gdl-devel gspell-devel
 aspell-devel libxslt-devel libgomp-devel libwpg-devel poppler-glib-devel
 cairomm-devel hunspell-devel gtkspell3-devel"
depends="desktop-file-utils hicolor-icon-theme python3-appdirs python3-lxml python3-numpy
 python3-scour python3-Pillow python3-cssselect python3-requests"

**Pull request closed without merging**
