### PR TITLE
meta: remove support code for only_for_archs=

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by Chocimier** [comment]
Documentation for only_for_archs was better than for archs. Can you move applicable parts?

**Comment by maxice8** [comment]
On Thu, Mar 14, 2019 at 02:58:04PM -0700, Piotr wrote:
> Documentation for only_for_archs was better than for archs. Can you move applicable parts?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/9837#issuecomment-473081242

I added a little more info to archs, please check the Manual.md against master.

**Comment by Vaelatern** [comment]
lgtm

**Comment by Chocimier** [comment]
:shipit:

**Pull request merged**
