### PR TITLE
[RFC] busybox: add a -big package

### PR DESCRIPTION
**Pull request by Vaelatern**
I want to add more modules to busybox, but not to bloat our busybox. The answer therefore is a new busybox subpackage, one for all the extra modules we might want.

Please, do help re-make the new dotconfig to help enable all the modules we think would fit in this new package. I started with httpd.

@the-maldridge

### CODE REVIEW

**Comment by CameronNemo** [comment]
Why not go the other way -- create a busybox-core package with just the essentials and let the busybox package be the more fully featured option? This has the benefit of the ntpd being in the larger package.

Furthermore, what is the goal or use case of building in httpd? Do any other distros build busybox with httpd? Seems like a niche need, maybe useful for routers, modems, and other embedded devices, but those will likely have specialized configurations anyway.

I'd like to have the package name reflect use case, rather than a description of cost. Anyone can tell how big the package is with xbps-query. It's important to know *why* it is big.

**Comment by Vaelatern** [comment]
`vim-huge`.
But also yes, Ubuntu builds in the httpd module, and I'm sure there are other useful modules.
I would not be too opposed to a `busybox-core` and a `busybox` that provides the smaller binary.

**Comment by CameronNemo** [comment]
Okay good to know another distro ships it. At least we won't be holding the bag should a vulnerability pop up.

I'd like to request `CONFIG_MDEV`, `CONFIG_LOGREAD`, `CONFIG_KLOGD`, and `CONFIG_SYSLOGD` be set.

**Comment by Vaelatern** [comment]
Give me a patch to apply to the PR, and I'll apply it.

**Comment by CameronNemo** [comment]
What to do about the alternatives?

**Comment by maxice8** [comment]
ping

**Comment by Vaelatern** [comment]
pong, no-update

**Comment by maxice8** [comment]
On Mon, Nov 26, 2018 at 11:05:40PM +0000, Toyam Cox wrote:
> pong, no-update
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/4289#issuecomment-441834655

ack

will annoy next month

**Comment by CameronNemo** [comment]
@Vaelatern patch for [mdev](https://raw.githubusercontent.com/void-linux/void-packages/fc2643ee68ae569965e3c9f0a63a4ccce424c9c5/srcpkgs/busybox/files/dotconfig.d/mdev.patch) and the [logging](https://raw.githubusercontent.com/void-linux/void-packages/fc2643ee68ae569965e3c9f0a63a4ccce424c9c5/srcpkgs/busybox/files/dotconfig.d/sysklogd.patch).

**Comment by maxice8** [comment]
I'm late for next month annoyance, sorry.

ping.

**Pull request closed without merging**
