### PR TITLE
Snapper: Update to 0.8.1

### PR DESCRIPTION
**Pull request by sww1235**

### CODE REVIEW

**Comment by maxice8** [comment]
remove thsoe merge commits

rebasing against master should be enough

**Comment by sww1235** [comment]
@maxice8 not exactly sure how to do do that. I just did the edit on github as it was easier for me.

**Comment by sww1235** [comment]
I see what broke. The github file is a tar.gz while the suse ftp file is a tar.bz2.

**Comment by sww1235** [comment]
closing this for now, since I think its pretty clear I screwed something up here. I will try using xbump on a void system and see if that works better

**Pull request closed without merging**
