### PR TITLE
llvm7: switch to python3

### PR DESCRIPTION
**Pull request by purpurrot**

### CODE REVIEW

**Comment by maxice8** [comment]
i'd rather wait until a new version comes along

**Comment by Cogitri** [comment]
+1. Also, only part of the LLVM stack is python3 ready as of now IIRC

**Comment by purpurrot** [comment]
That is probably for the better.

**Comment by maxice8** [comment]
On Thu, Feb 07, 2019 at 01:28:24PM -0800, purpurrot wrote:
> That is probably for the better.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/8265#issuecomment-461602467

Did you verify all components that are built can work with python3 ?

**Comment by purpurrot** [comment]
The build was successful. But clang-analyzer doesn't seem to work yet with python3. Some scripts worked, others didn't.

**Comment by Cogitri** [comment]
Yes, as I mentioned, only part of LLVM is ported to py3 as of now.

**Comment by maxice8** [comment]
This will most probably be done on a llvm release that has **all** components working with python3.

**Pull request closed without merging**
