### PR TITLE
Waybar: update to 0.9.2

### PR DESCRIPTION
**Pull request by ericonr**
Added dbusmenugtk option as default for all situations. libnl now works
for musl.

@DirectorX are you still using Void/having time to maintain this? I can maintain the package, if you'd like.

### CODE REVIEW

**Comment by DirectorX** [comment]
@ericonr feel free to take ownership

**Comment by ericonr** [comment]
CI results: https://travis-ci.org/github/void-linux/void-packages/builds/687604360, I skipped rebuilding just for the maintainer change.

@DirectorX ok, thanks!

**Comment by ericonr** [comment]
@Johnnynator per https://github.com/HowardHinnant/date/pull/538, it's not possible to use a distro wide package for date yet. I could add a patch with that PR's contents, that way we can use it. Seems to be what Arch is doing https://git.archlinux.org/svntogit/community.git/tree/trunk/538-output-date-pc-for-pkg-config.patch?h=packages/chrono-date . Otherwise, it has to be built at the same time.

**Comment by Johnnynator** [comment]
Ok, than just leave it as is for now.

**Pull request merged**
