### PR TITLE
[WIP] New package: deno-1.0.0

### PR DESCRIPTION
**Pull request by toluschr**
#21937

I think the `do_install` function would need to be changed a little, however the cargo build helper throws an error.

### CODE REVIEW

**Comment by q66** [comment]
unless you figure out how to make it not fetch binaries during build, this cannot be accepted

**Comment by toluschr** [comment]
At which step does it fetch binaries? The terminal log mentioned compiling the dependencies

**Comment by Johnnynator** [comment]
The musl log makes it clear: https://travis-ci.org/github/void-linux/void-packages/jobs/688065967#L4665 Also 30min on travis is not close to the time v8 would need to compile.

**Comment by Johnnynator** [comment]
rusty_v8 doc:
> Use V8_FROM_SOURCE=1 cargo build -vv to build the crate completely from source.
https://github.com/denoland/rusty_v8

**Comment by toluschr** [comment]
> rusty_v8 doc:
> 
> > Use V8_FROM_SOURCE=1 cargo build -vv to build the crate completely from source.
> > https://github.com/denoland/rusty_v8

Thanks for the help! I will change the template accordingly.

**Comment by toluschr** [comment]
The musl build is still failing for some reason. I did a little research and found this:
https://github.com/rust-lang/rust/issues/61328
https://github.com/rust-lang/rust/issues/59302
but neither of those two tips fixed the issue. Maybe someone with a little more knowledge can help?

**Comment by atk** [comment]
I'm working on the more recent version, see https://github.com/atk/void-packages/tree/deno-1.1.1 - do you want to team up?

**Comment by toluschr** [comment]
> I'm working on the more recent version, see https://github.com/atk/void-packages/tree/deno-1.1.1 - do you want to team up?

I'm not sure I can help you with that. I tried to create a template for an hour and gave up.

**Comment by atk** [comment]
I found the issue not to be musl itself, but the lack of a gn package (https://gn.googlesource.com/gn/) to be utilized by cargo-gn that is required to build a few of the other internal dependencies.

**Comment by ericonr** [comment]
Superseded by #25436

**Pull request closed without merging**
