### PR TITLE
bfs: update to 2.2.

### PR DESCRIPTION
**Pull request by daniel-eys**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by daniel-eys** [comment]
From CI:
> error: These tests expect filesystem permissions to be enforced, and therefore
> will not work when run as root.

Tests passed on my x86_64.
I guess this is due to the ethereal chroot style of the CI containers.
Is there a way to have the teststage not run as root within CI?

**Comment by tavianator** [comment]
@daniel-eys Enough people have run into this that I added a workaround.  If you apply https://github.com/tavianator/bfs/commit/f2e6186ed0ce9b68362ad25d897f1e3c697728ec the tests will drop the appropriate privileges automatically.

**Comment by tavianator** [comment]
The builds seem to be in an infinite loop of trying and failing to drop capabilities.  I'm guessing this is because the tests don't have `CAP_SETPCAP`, and I overlooked that `capsh --drop` needs it:

```
       --drop=cap-list
              Remove the listed capabilities from the prevailing
              bounding set. The capabilities are a comma-separated list
              of capabilities as recognized by the cap_from_name(3)
              function. Use of this feature requires that capsh is
              operating with CAP_SETPCAP in its effective set.
```

I'll try to fix it.

**Comment by tavianator** [comment]
I'm actually not sure what's going on, I tried with CAP_SETPCAP dropped and got an error instead of an infinite loop.  But you can fold in https://github.com/tavianator/bfs/commit/dbc77fd3b6e48a17eb79f9ff3a5f810b7554bf6f in the meantime to avoid the infinite loop.

**Comment by ericonr** [comment]
@tavianator perhaps `setpriv` behaves better than `capsh`?

**Comment by tavianator** [comment]
I think I figured out what's happening.  The build is happening in a user namespace.  `capsh --drop` silently fails there, which seems like a bug.

`setpriv` seems to do something, but it works a little too well:

```
# setpriv --inh-caps=-dac_override,-dac_read_search --bounding-set=-dac_override,-dac_read_search -- cat foo
cat: error while loading shared libraries: libc.so.6: cannot open shared object file: Permission denied
```

**Comment by tavianator** [comment]
Actually `setpriv` works fine, I just had the wrong ownership of `/` in my container.  But I got `capsh` working too, thanks to this hint from the `setpriv` manpage:

```
              If you drop a capability from the bounding set without
              also dropping it from the inheritable set, you are likely
              to become confused.  Do not do that.
```

It seems like CAP_DAC_{OVERRIDE,READ_SEARCH} are inheritable in a container, so I have to remove them.  Patch coming.

**Comment by tavianator** [comment]
https://github.com/tavianator/bfs/commit/d36ece2ca7498b7ba5485d5010439b57f006c9c8 fixes the tests for me in a `systemd-nspawn -U` container, which I think is similar to the `xbps-uunshare` environment.

**Comment by ericonr** [comment]
@tavianator thanks!

@daniel-eys ping?

**Comment by daniel-eys** [comment]
I included the patch. Let's see what ci thinks about that.

**Pull request merged**
