### PR TITLE
New package: xnotify-0.8.1

### PR DESCRIPTION
**Pull request by natrys**

### CODE REVIEW

**Comment by natrys** [comment]
Alternative is maybe to patch up `config.mk` in ugly ways: https://gist.github.com/natrys/7a6f21699277809464cffd7851479741

Dunno whichever (or if neither) way is more idiomatic.

**Comment by biopsin** [comment]
@natrys Ping & bump to 0.8.1
Would you mind adopt make_build_args from https://github.com/void-linux/void-packages/pull/27763/commits/81f88f21e1383e44cae405befeaffc4a08cd1cfc
and drop the freetype-devel dependency.
Also include "Closes PR https://github.com/void-linux/void-packages/pull/27198"

**Comment by natrys** [comment]
hi @biopsin do you mean:

```
make_build_args="LOCALINC=${XBPS_CROSS_BASE}/usr/include
 LOCALLIB=${XBPS_CROSS_BASE}/usr/lib
 FREETYPEINC=${XBPS_CROSS_BASE}/usr/include/freetype2
 X11INC=${XBPS_CROSS_BASE}/usr/include/X11
 LDFLAGS+=\$(LIBS) CFLAGS+=\$(INCS)"
```

This works but I feel like this is more indirect and implicit than just setting up CFLAGS/LDFLAGS directly which is the desired effect.

```
CFLAGS="-I${XBPS_CROSS_BASE}/usr/include"
CFLAGS+=" -I${XBPS_CROSS_BASE}/usr/include/X11"
CFLAGS+=" -I${XBPS_CROSS_BASE}/usr/include/freetype2"
LDFLAGS="-lfontconfig -lXft -lXinerama -lX11 -lImlib2"
```

Perhaps @ericonr can weigh in.

**Comment by ericonr** [comment]
It avoids having to specify `LDFLAGS` yourself, at least

**Comment by natrys** [comment]
Fair enough, changed to that.

**Pull request closed without merging**
