### PR TITLE
New package: gcc6-6.5.0

### PR DESCRIPTION
**Pull request by q66**
Yes, not a typo. Intorducing the first part of perhaps my most pain in the ass effort so far:

Currently we have a problem that we need binaries to bootstrap java (openjdk) with. This is the first step towards getting rid of that dependency; it introduces gcc6, which is the last gcc to come with the gcj java implementation, in its latest version 6.5.0. This is built in a strictly versioned manner so there aren't any conflicting files with the primary, latest gcc.

The C/C++ frontends work, however, I don't expect anybody to actually use them. They are necessary for gcj to build; it won't build standalone (the C/C++ frontends get implicitly enabled).

The template is intentionally kept simple, with no cross-compilation or bootstrap logic, as this is meant for bootstrapping; for cross-compilation of java, you can use an existing java compiler of the host architecture, without going through all the hassle.

I applied all available+relevant patches from Alpine to allow this to work on musl as well as ppc64le and so on. I haven't tested that yet. The only target I tested on is ppc64le glibc.

This will also not bootstrap openjdk as it is, since gcj implements java 6 and our lowest versioned openjdk is 8. We will need to introduce something like `openjdk7-bootstrap` which will be compiled with this, and that will then compile openjdk8. Once we're at that stage, we can introduce the missing pieces (9 and 10) to bootstrap openjdk11 without binaries as well.

TODO:

- [x] test bootstrapping openjdk7
- [x] test bootstrapping openjdk8 using the built openjdk7
- [x] test ppc64le
- [x] test ppc64le-musl
- [x] test ppc64
- [x] test ppc64-musl
- [x] test ppc
- [x] test ppc-musl
- [x] test x86_64
- [x] test x86_64-musl
- [x] test i686

### CODE REVIEW

**Comment by q66** [comment]
fixed missing files in gcc6-gcj-jdk-compat, bootstrapping openjdk7 should now work out of box

**Comment by q66** [comment]
All hosts tested, this is ready to go.

**Comment by stikonas** [comment]
Note that this process is not binary free. You are still downloading ecj.jar

It's possible to compile that from source too, but bootstrapping process is then quite a bit longer (see what GNU Guix does).

**Comment by q66** [comment]
@stikonas that doesn't really count to me the same as using actual platform-specific binaries, considering it's portable bytecode...

btw, i noticed you're maintaining a gentoo thingy for bootstrapping 11 through 9 and 10, had any luck targeting 32bit systems with 9? So far I've had none...

**Comment by stikonas** [comment]
@q66 no, I don't have any 32-bit systems to test on, so I haven't even tried...

**Comment by q66** [comment]
Looks like `i686` works okay, actually. So it's specific to 32-bit architectures targeting zero, hopefully i can find a workaround...

**Comment by stikonas** [comment]
> @stikonas that doesn't really count to me the same as using actual platform-specific binaries, considering it's portable bytecode...
> 
> btw, i noticed you're maintaining a gentoo thingy for bootstrapping 11 through 9 and 10, had any luck targeting 32bit systems with 9? So far I've had none...

By the way, I actually managed to create add bootstrap path for openjdk 8 too to my Gentoo overlay. And it doesn't involve gcc 6 or precompiled ecj bytecode.

Any gcc (e.g. version 9) can be used to compile fastjar, jikes, gnu-classpath-0.93 and jamvm-1.5.1 to create Java 1.4 environment. From there you can bootstrap other required tools and eventually bootstrap icedtea-7.

**Comment by q66** [comment]
I don't think depending on a project that last had a release in 2005 is any better than depending on gcc6...

besides, jikes doesn't provide support for the assortment of platforms we have. Using `gcj`, Void can now bootstrap all the way to `openjdk11` on `x86_64`, `i686`, `aarch64`, `armv6l`, `armv7l`, `ppc64le`, `ppc64`, `ppc` and their `musl` counterparts, and possibly any other platform that's supported by `gcc6` (once some openjdk is up, it can fallback to zero in the worst case, i tested that for ppc32 and while it's pretty slow, it works, all the way to 11)

**Comment by q66** [comment]
Thanks for the heads up though; but I think I can live with precompiled `ecj` bytecode, from practical standpoint :) As long as it can cover all the platforms without involving unportable binaries, it's acceptable.

**Pull request merged**
