### PR TITLE
fonttools: update to 4.3.0.

### PR DESCRIPTION
**Pull request by svenper**

### CODE REVIEW

**Comment by Chocimier** [comment]
Using python3-devel and setting noarch is likely wrong. Check if it can be build without python3-devel.

**Comment by svenper** [comment]
You're right, I removed it!

**Comment by Chocimier** [comment]
Needs python3-setuptools in depends.

**Comment by svenper** [comment]
[Done!](https://github.com/void-linux/void-packages/compare/1a8d0a015e2a79cbf1bf2d629d441854f9b4e6a0..e4e8fd468f28c0ceaac47ac9d831730c927364b0)

**Pull request merged**
