### PR TITLE
xbps-src: declarative split library and development file

### PR DESCRIPTION
**Pull request by sgn**
@void-linux/pkg-committers

### CODE REVIEW

**Comment by Vaelatern** [comment]
I don't really like this. We currently don't have any other examples of magic where we create magic packagtes (other than -dbg, which is just a build option, and -32bit, same).

**Comment by q66** [comment]
yeah i think this is no good

**Comment by Hoshpak** [comment]
I agree. Too much magic and calling shell functions like that makes the templates harder to read and potentially also makes parsing more difficult.

**Comment by Vaelatern** [comment]
@sgn do you think this should be pursued?

**Comment by Chocimier** [comment]
One thing I found good is guessing what packages to install into -lib and -devel packages.

Maybe that could be reworked as someting like `vgroupinstall devel` inside pkg_install?

**Comment by Anachron** [comment]
^ couldnt xnew be updated in that case?

**Comment by Vaelatern** [comment]
> ^ couldnt xnew be updated in that case?

What do you mean by this question, @Anachron ? How does xnew play into regular package building, unless you mean adding a sample devel package? (and just requiring it be deleted for most packages?)

**Comment by Anachron** [comment]
xnew already has optional subpkgs with -devel support. Isnt that sufficient for new pkgs?

**Comment by travankor** [comment]
@sgn, I think @Chocimier's suggestion is the best way to salvage the useful parts of this PR.

**Comment by sgn** [comment]
> One thing I found good is guessing what files to install into -lib and -devel packages.
> 
> Maybe that could be reworked as someting like `vgroupinstall devel` inside pkg_install?

Yeah, this sounds better, doesn't harm readability and reduce the repeated code for devel and libs.

**Comment by sgn** [comment]
> ^ couldnt xnew be updated in that case?

I think `vgroupinstall` or `vsplit` is better than update `xnew` manually remove/add file.

**Pull request closed without merging**
