### PR TITLE
fuse-mp3fs: update to 1.1.1.

### PR DESCRIPTION
**Pull request by zdykstra**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by zdykstra** [comment]
The mp3fs checks wants mount/unmount capabilities to actually _use_ the FUSE module. Is there a way to allow those permissions in the build environment, or should I stub out / no-op `do_check` ?

**Comment by Piraty** [comment]
either patch relevant tests out or nop `do_test`

**Comment by ericonr** [comment]
`make_check=no` with a comment as to why is preferred ;)

**Comment by zdykstra** [comment]
> `make_check=no` with a comment as to why is preferred ;)

Done!

**Pull request merged**
