### PR TITLE
wlroots: update to 0.11.0

### PR DESCRIPTION
**Pull request by ifreund**
This version has breaking changes, so we need to wait on new releases for the following programs and include bumps in this PR:

- [x] sway
- [x] cage
- [x] hikari
- [x] wayfire

### CODE REVIEW

**Comment by ericonr** [comment]
Thanks for getting started on this! I'm following wayfire.

@ahesford might know something about hikari?

Not sure how it will work out for cage, we already carry a patch to make it work with `0.10.0`.

**Comment by ericonr** [comment]
Or well, 2h old release: https://github.com/Hjdskes/cage/releases/tag/v0.1.2.1

**Comment by ahesford** [comment]
`hikari` seems to build against this update and runs, at least on `x86_64`. Please bump `hikari` and, if it passes CI for the other archs, I'm content.

**Comment by ahesford** [comment]
Given that [Wayfire #595](https://github.com/WayfireWM/wayfire/pull/595/files) was merged, why not just pull the patch into Void's `wayfire` package and wrap up this work?

**Comment by ericonr** [comment]
@ahesford that one was just being explicit about the dependencies. See https://github.com/WayfireWM/wayfire/issues/596

**Comment by ifreund** [comment]
I wrote a trivial patch to make wayfire 0.4.0 build with wlroots 0.11.0 as it looks like we'll be waiting a couple of weeks for a release.

As far as I know this is good to go now.

**Comment by ericonr** [comment]
For wayfire:

```
-makedepends="xcb-util-wm-devel xcb-util-errors-devel glm cairo-devel wf-config-devel"
+makedepends="xcb-util-wm-devel xcb-util-errors-devel glm cairo-devel
+ wf-config-devel wlroots-devel"
```

For wf-config:

```
-makedepends="glm libevdev-devel wlroots-devel xcb-util-errors-devel
- xcb-util-wm-devel libxml2-devel"
+makedepends="glm libevdev-devel libxml2-devel"
```

**Comment by jbeich** [comment]
Did you check Wayfire for crashes on startup? Apply https://github.com/WayfireWM/wayfire/commit/29dcd1387700 if you see the following:
```
Assertion failed: (surface), function wlr_seat_keyboard_notify_enter, file types/seat/wlr_seat_keyboard.c, line 321.
```

See also https://github.com/freebsd/freebsd-ports/blob/c920e5595b6/x11-wm/wayfire/files/patch-wlroots-0.11

**Comment by ifreund** [comment]
I did check that it started up but didn't have any config loaded so it wasn't a great test. Thank's for the tip!

**Comment by ifreund** [comment]
@ahesford good point, done.

**Comment by ahesford** [comment]
Closed in be4834df. I missed the `hikari` commit message (not an update, but a revbump) the first time around but just fixed it for you.

**Pull request closed without merging**
