### PR TITLE
[PR on HOLD] New package: python3-pynitrokey-0.4.50 with a bunch of dependencies

### PR DESCRIPTION
**Pull request by slymattz**
#### UPDATE on this PR
Although this PR works totally fine, pynitrokey 0.5.0 is just around the corner. Long story short, it replaces libusbsio dependency with hidapi. It also removes the need for spsdk which is a bulky dep pulling lots of deps including the non-portable cmsis-pack-manager. These changes upstream will certainly simplify the packaging/updating process.

In my opinion, **this PR can be put on hold**. I've already packaged 0.5.0-rc1 and will create a PR when it gets released.

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture: x86_64-glibc

#### About two problematic packages:
- _libusbsio_ has been fixed with a simple sed command proposed by zlice.
- _python3-cmsis-pack-manager_: I've had no success building it for arches other than x86_64 and i686. Upstream documentation says "[Cross-compilation may be an option but has not been sufficiently investigated.](https://github.com/pyocd/pyOCD/blob/main/docs/installing_on_non_x86.md#cmsis-pack-manager)". I've tried to use:
```
build_helper=rust
(...)
rustup-init -y
source "/host/cargo/env"
rustup target add aarch64-unknown-linux-gnu
(...)
cargo build --release --target=aarch64-unknown-linux-gnu
```
Still it fails for aarch64 so the other archs are likely to be affected, too. For the record, I get:
`error: toolchain 'stable-x86_64-unknown-linux-gnu' does not contain component 'rustc' for target 'aarch64-unknown-linux-gnu'` If anybody can think of something to make it work, I'd appreciate a comment.

Native compilation is also bound to fail since "[wheels are not available for non-x86 systems](https://github.com/pyocd/pyOCD/blob/main/docs/installing_on_non_x86.md#cmsis-pack-manager)" That's why I'm keeping the _archs_ line in the template and not setting the var _broken_ for $CROSS_BUILD.

### CODE REVIEW

**Comment by ahesford** [comment]
1. Generally, we prefer using `$PYPI_SITE` for Python distfiles where possible.
2. Don't redefine `do_build` just to add `--skip-dependency-check`; use `make_build_args` for that purpose.
3. Are the packages that won't build for other architectures broken upstream, or is it just the case that you haven't been able to build them? The `libusbsio` wheel, in particular, seems to ship a bunch of supporting libraries for 32- and 64-bit ARM.

**Comment by slymattz** [comment]
> 1. Generally, we prefer using `$PYPI_SITE` for Python distfiles where possible.
> 
> 2. Don't redefine `do_build` just to add `--skip-dependency-check`; use `make_build_args` for that purpose.
> 
> 3. Are the packages that won't build for other architectures broken upstream, or is it just the case that you haven't been able to build them? The `libusbsio` wheel, in particular, seems to ship a bunch of supporting libraries for 32- and 64-bit ARM.

1. Where it was possible, I used $PYPI_SITE.
2. Done. Thanks for the suggestion.
3. I need to check if there's a way for libusbsio to cross-compile because libusbsio-python3 depends on it.

**Comment by zlice** [comment]
saw you mention this in irc

try this in post extract for cross builds?

```
  vsed -e "s/gcc/$CC/" -i ${wrksrc}/makefile
  vsed -e "s/g++/$CXX/" -i ${wrksrc}/makefile
```

**Comment by slymattz** [comment]
> saw you mention this in irc
> 
> try this in post extract for cross builds?
> 
> ```
>   vsed -e "s/gcc/$CC/" -i ${wrksrc}/makefile
>   vsed -e "s/g++/$CXX/" -i ${wrksrc}/makefile
> ```

Sorry, saw the comment after putting _broken_ in libusbsio. Will test this for sure. Thanks for your input.

**Comment by slymattz** [comment]
> For Python things that build with rust, like `python3-cmsis-pack-manager`, you should be using the `rust` build helper.

Will try that for sure and report back.

**Comment by slymattz** [comment]
> For Python things that build with rust, like `python3-cmsis-pack-manager`, you should be using the `rust` build helper.

OK, added the appropriate line. I haven't been able to cross-compile it but managed to find upstream info on non-x86 archs for this package. The link is in my original comment.

**Pull request closed without merging**
