### PR TITLE
[WIP] chromium: update to 71.0.3578.80.

### PR DESCRIPTION
**Pull request by Cogitri**
[ci skip]

### CODE REVIEW

**Comment by jnbr** [comment]
is this tested?

**Comment by Cogitri** [comment]
Ah, sorry, forgot to add [WIP]

**Comment by huglovefan** [comment]
i get this on x86_64-musl
```
[12382/19369] CXX obj/components/google/core/common/common/google_util.o
FAILED: obj/components/google/core/common/common/google_util.o 
g++ -MMD -MF obj/components/google/core/common/common/google_util.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DNO_TCMALLOC -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_32 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_26 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -I../.. -Igen -Igen/shim_headers/libevent_shim -Igen/shim_headers/libpng_shim -Igen/shim_headers/libwebp_shim -Igen/shim_headers/libdrm_shim -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/protobuf/src -I../../third_party/boringssl/src/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -pthread -m64 -march=x86-64 -Wall -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -fno-delete-null-pointer-checks -Wno-comments -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -fvisibility=hidden -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/nss -I/usr/include/nspr -std=gnu++14 -fno-delete-null-pointer-checks -Wno-narrowing -fno-exceptions -fno-rtti -fvisibility-inlines-hidden     -c ../../components/google/core/common/google_util.cc -o obj/components/google/core/common/common/google_util.o
../../components/google/core/common/google_util.cc: In function 'bool google_util::{anonymous}::IsCanonicalHostGoogleHostname(base::StringPiece, google_util::SubdomainPermission)':
../../components/google/core/common/google_util.cc:120:24: error: call of overloaded 'NoDestructor(<brace-enclosed initializer list>)' is ambiguous
       {GOOGLE_TLD_LIST});
                        ^
In file included from ../../components/google/core/common/google_util.cc:15:
../../base/no_destructor.h:63:3: note: candidate: 'base::NoDestructor<T>::NoDestructor(const base::NoDestructor<T>&) [with T = std::set<std::__cxx11::basic_string<char> >]' <deleted>
   NoDestructor(const NoDestructor&) = delete;
   ^~~~~~~~~~~~
../../base/no_destructor.h:61:12: note: candidate: 'base::NoDestructor<T>::NoDestructor(T&&) [with T = std::set<std::__cxx11::basic_string<char> >]'
   explicit NoDestructor(T&& x) { new (storage_) T(std::move(x)); }
            ^~~~~~~~~~~~
../../base/no_destructor.h:60:12: note: candidate: 'base::NoDestructor<T>::NoDestructor(const T&) [with T = std::set<std::__cxx11::basic_string<char> >]'
   explicit NoDestructor(const T& x) { new (storage_) T(x); }
            ^~~~~~~~~~~~
../../components/google/core/common/google_util.cc: In function 'bool google_util::{anonymous}::IsGoogleSearchSubdomainUrl(const GURL&)':
../../components/google/core/common/google_util.cc:135:45: error: call of overloaded 'NoDestructor(<brace-enclosed initializer list>)' is ambiguous
       {"ipv4.google.com", "ipv6.google.com"});
                                             ^
In file included from ../../components/google/core/common/google_util.cc:15:
../../base/no_destructor.h:63:3: note: candidate: 'base::NoDestructor<T>::NoDestructor(const base::NoDestructor<T>&) [with T = std::set<std::__cxx11::basic_string<char> >]' <deleted>
   NoDestructor(const NoDestructor&) = delete;
   ^~~~~~~~~~~~
../../base/no_destructor.h:61:12: note: candidate: 'base::NoDestructor<T>::NoDestructor(T&&) [with T = std::set<std::__cxx11::basic_string<char> >]'
   explicit NoDestructor(T&& x) { new (storage_) T(std::move(x)); }
            ^~~~~~~~~~~~
../../base/no_destructor.h:60:12: note: candidate: 'base::NoDestructor<T>::NoDestructor(const T&) [with T = std::set<std::__cxx11::basic_string<char> >]'
   explicit NoDestructor(const T& x) { new (storage_) T(x); }
            ^~~~~~~~~~~~
```
i found [this patch](https://github.com/gentoo/gentoo/blob/master/www-client/chromium/files/chromium-71-gcc-0.patch) that's supposed to fix it (edit it to remove `a/` and `b/` from the paths or it fails to apply)

**Comment by Cogitri** [comment]
Uhh...are you sure that you use the latest revision of this PR? This has been fixed for some hours already.

**Comment by Cogitri** [comment]
Since you seem to want to test musl, could you try https://exqa.de/dist/chromium-71.0.3578.80_1.x86_64-musl.xbps?

Should also be install-able via `xbps-install -S --repository="https://exqa.de/dist" chromium` if I got the package signing right this time.

**Comment by huglovefan** [comment]
i installed it and it seems to work fine

**Comment by Cogitri** [comment]
Great. Am compiling i686 right now.

**Comment by Cogitri** [comment]
Works on all platforms @jnbr

**Pull request merged**
