### PR TITLE
monero-gui: update to 0.12.2.0.

### PR DESCRIPTION
**Pull request by Hoshpak**

### CODE REVIEW

**Comment by maxice8** [comment]
please repush to enable travis

**Comment by Hoshpak** [comment]
done

**Comment by Hoshpak** [comment]
Building on aarch64 fails because the signature for xkeyboard-config is invalid, if I rebuild that package locally, monero-gui compiles just fine. I don't know if a revbump for that package would be enough to fix it or something else needs to be done on the servers.

**Comment by maxice8** [comment]
On Wed, Jun 20, 2018 at 03:02:24AM -0700, Helmut Pozimski wrote:
> Building on aarch64 fails because the signature for xkeyboard-config is invalid, if I rebuild that package locally, monero-gui compiles just fine. I don't know if a revbump for that package would be enough to fix it or something else needs to be done on the servers.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/99#issuecomment-398695270

No worries, i believe a bump has been made already, i'll notify #xbps

**Pull request merged**
