### PR TITLE
mbedtls: update to 2.16.10

### PR DESCRIPTION
**Pull request by unspecd**
Also:
- Fix changelog location.
- Use scripts/config.pl instead of sed.

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, x86_64-musl
- [x] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [x] aarch64-musl
  - [ ] armv7l
  - [ ] armv6l-musl

### CODE REVIEW

**Comment by mobinmob** [comment]
Nice @unspecd !
This is un update in the TLS branch, so it should not break API/ABI. I see only a little change in the release notes, but I have no idea of it affects programms in the repo.

**Comment by unspecd** [comment]
@mobinmob
I will check the affected packages.

**Comment by unspecd** [comment]
### Summary

`!` - affected
`^` - update available

| Package                       | Location                                                                                                                                                                                                                 | Reason                                                                                                                                                                                         |
|:------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| bctoolbox<sup>!^</sup>        | [src/crypto/mbedtls.c](https://gitlab.linphone.org/BC/public/bctoolbox/-/blob/4.4.17/src/crypto/mbedtls.c): [1](https://gitlab.linphone.org/BC/public/bctoolbox/-/blob/4.4.17/src/crypto/mbedtls.c#L115-116), [2](https://gitlab.linphone.org/BC/public/bctoolbox/-/blob/4.4.17/src/crypto/mbedtls.c#L289-294) | [violates the contract](https://github.com/ARMmbed/mbedtls/commit/831956980c66b03ab00e2bdc0fbcc55f98bf5f02#diff-f77aa8299db40b4403be0b49ca6eca52ab4ee2a2f00bb200a798e07a89b25850R305-R306) |
| dislocker                     | -                                                                                                                                                                                                                        | -                                                                                                                                                                                              |
| dolphin-emu<sup>!</sup>       | [libcurl](https://github.com/curl/curl/blob/2f33be817cbce6ad7a36f27dd7ada9219f13584c/lib/vtls/mbedtls.c#L272-L298)                                                                                                                                                                                             | [violates the contract](https://github.com/ARMmbed/mbedtls/commit/831956980c66b03ab00e2bdc0fbcc55f98bf5f02#diff-f77aa8299db40b4403be0b49ca6eca52ab4ee2a2f00bb200a798e07a89b25850R305-R306) |
| godot                         | -                                                                                                                                                                                                                        | -                                                                                                                                                                                              |
| hiawatha<sup>!</sup>          | [src/tls.c](https://gitlab.com/hsleisink/hiawatha/-/blob/v10.11/src/tls.c#L279-282)                                                                                                                                   | [violates the contract](https://github.com/ARMmbed/mbedtls/commit/831956980c66b03ab00e2bdc0fbcc55f98bf5f02#diff-f77aa8299db40b4403be0b49ca6eca52ab4ee2a2f00bb200a798e07a89b25850R305-R306) |
| julia<sup>^</sup>             | [libcurl](https://github.com/curl/curl/blob/2f33be817cbce6ad7a36f27dd7ada9219f13584c/lib/vtls/mbedtls.c#L272-L298)                                                                                                                                                                                             | [violates the contract](https://github.com/ARMmbed/mbedtls/commit/831956980c66b03ab00e2bdc0fbcc55f98bf5f02#diff-f77aa8299db40b4403be0b49ca6eca52ab4ee2a2f00bb200a798e07a89b25850R305-R306) |
| obs                           | [plugins/obs-outputs/librtmp/rtmp.c](https://github.com/obsproject/obs-studio/blob/26.1.2/plugins/obs-outputs/librtmp/rtmp.c#L383-L390)                                                                               | [violates the contract](https://github.com/ARMmbed/mbedtls/commit/831956980c66b03ab00e2bdc0fbcc55f98bf5f02#diff-f77aa8299db40b4403be0b49ca6eca52ab4ee2a2f00bb200a798e07a89b25850R305-R306) |
| retroarch<sup>!</sup>         | [libretro-common/net/net_socket_ssl.c](https://github.com/libretro/RetroArch/blob/v1.9.0/libretro-common/net/net_socket_ssl.c#L91-L109)                                                                               | [violates the contract](https://github.com/ARMmbed/mbedtls/commit/831956980c66b03ab00e2bdc0fbcc55f98bf5f02#diff-f77aa8299db40b4403be0b49ca6eca52ab4ee2a2f00bb200a798e07a89b25850R305-R306) |
| rvault<sup>^</sup>            |                                                                                                                                                                                                                          | -                                                                                                                                                                                              |
| shadowsocks-libev<sup>^</sup> |                                                                                                                                                                                                                          | -                                                                                                                                                                                              |
| tpm2-tss<sup>^</sup>          |                                                                                                                                                                                                                          | -                                                                                                                                                                                              |

**Comment by ericonr** [comment]
What does this table mean? Do we need to update/fix these packages for the library update? Or is the issue new? A stable API shouldn't change the contract...

**Comment by unspecd** [comment]
Sorry for the delay.

At first, I thought it might be a leak in the function [mbedtls_ctr_drbg_seed](https://github.com/ARMmbed/mbedtls/blob/v2.16.10/library/ctr_drbg.c#L409), which in turn calls `pthread_mutex_init`, but then I found out that the latter does not allocate any resources.

So there is no need to update or fix these packages.

I'm sorry if I confused you.

**Pull request closed without merging**
