### PR TITLE
element-desktop: update to 1.7.10.

### PR DESCRIPTION
**Pull request by ProjectMoon**

### CODE REVIEW

**Comment by ProjectMoon** [comment]
Initial test of the build shows that encrypted room search has stopped working due to "missing components." Will investigate and fix before setting to ready.

**Comment by ProjectMoon** [comment]
The problem is because Element 1.7.8 upgraded to Electron 10. Downgrading the Electron version to 9.x allows it to work. The only changes in 1.7.8 are actually an upgrade of Electron and a minor version bump to seshat.

**Comment by ProjectMoon** [comment]
Seems like we want to wait for an Electron 10 package.

**Comment by ericonr** [comment]
I believe electron 10 has been merged!

**Comment by ProjectMoon** [comment]
Alright, I will proceed with updating the package.

**Comment by ProjectMoon** [comment]
Building with electron 10 still results in the same error. Maybe some node dependency issue? Will investigate further.

This happens when running from the terminal.

```
node[11161]: pthread_create: Invalid argument
Keytar unexpected error: Error: Module did not self-register: '/tmp/.org.chromium.Chromium.NjTWS6'.
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/element-desktop/resources/app.asar/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
Seshat unexpected error: Error: The module '/tmp/.org.chromium.Chromium.kW8Bq9'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 82. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/element-desktop/resources/app.asar/node_modules/matrix-seshat/lib/index.js:15:16)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
```

**Comment by ProjectMoon** [comment]
Ok, found the issue after checking against Arch PKGBUILD. It seems like by default, element-desktop executes against electron9, and when compiled with 10, you get a node module mismatch. I will update the PR with a script similar to this: https://aur.archlinux.org/cgit/aur.git/tree/element-desktop.sh?h=element-desktop-git

```
#!/bin/bash
exec electron10 /usr/lib/element-desktop/resources/app.asar "$@"
```

**Comment by ericonr** [comment]
We already have a script for it:

```
#!/bin/sh
exec electron9 /usr/lib/element-desktop/resources/app.asar "$@"
```

So I guess just update it?

**Comment by ProjectMoon** [comment]
Yep, don't even know how I didn't see that

**Comment by ProjectMoon** [comment]
Building with Electron 10 and updated the launch script. No more errors, everything working.

**Comment by ProjectMoon** [comment]
Bumped version to 1.7.10.

**Pull request merged**
