### PR TITLE
polkit: add polkitd service

### PR DESCRIPTION
**Pull request by dan-santana**
Continuation of https://github.com/voidlinux/void-packages/pull/14357

This service is useful on setups where D-Bus service activation is not desired (or available).

### CODE REVIEW

**Comment by maxice8** [comment]
add `libtool` to hostmakedepends

**Comment by maxice8** [comment]
add `libtool` to hostmakedepends

**Comment by maxice8** [comment]
Please notify when you made the proposed changes, i don't have telepathy

**Comment by dan-santana** [comment]
I'm sorry, I thought Github sent you a notification on PR modifications. Got it!

**Comment by maxice8** [comment]
On Thu, Sep 20, 2018 at 01:13:40PM -0700, Daniel Santana wrote:
> I'm sorry, I thought Github sent you a notification on PR modifications. Got it!
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/2922#issuecomment-423317474

Only on comments and new commits, since we don't want more commits we just push the old commit modified.

**Pull request merged**
