### PR TITLE
dracut: split dracut package (dracut / dracut-default)

### PR DESCRIPTION
**Pull request by 08A**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

#### Rational

When dracut-053_1 and dracut-uefi-053_1 are installed, there are two kernel hooks that will build two EFI images. This process is slow and will consume twice as much space. There is no reason why both hooks should be installed at the same time. So the user should therefore be able to choose if he wants the default hook.

#### Test

````sh
$ ./xbps-src pkg dracut
$ rm /etc/kernel.d/post-install/20-dracut
$ rm /etc/kernel.d/post-remove/20-dracut
$ xi dracut-uefi
$ tree /etc/kernel.d/ # no 20-dracut file
/etc/kernel.d
├── post-install
│   ├── 10-dkms
│   ├── 20-dracut-uefi
│   ├── 40-sbsigntool
│   ├── 50-efibootmgr
│   └── 50-refind
├── post-remove
│   ├── 20-dracut-uefi
│   ├── 40-sbsigntool
│   ├── 50-efibootmgr
│   └── 50-refind
├── pre-install
└── pre-remove
    └── 10-dkms
$ xi dracut-default
$ tree /etc/kernel.d/
/etc/kernel.d
├── post-install
│   ├── 10-dkms
│   ├── 20-dracut
│   ├── 20-dracut-uefi
│   ├── 40-sbsigntool
│   ├── 50-efibootmgr
│   └── 50-refind
├── post-remove
│   ├── 20-dracut
│   ├── 20-dracut-uefi
│   ├── 40-sbsigntool
│   ├── 50-efibootmgr
│   └── 50-refind
├── pre-install
└── pre-remove
    └── 10-dkms
````

#### PS

If this PR is merged I was thinking about splitting the same way other packages such as refind, efibootmgr, sbsigntools. What do you think ?

### CODE REVIEW

**Comment by Duncaen** [comment]
This breaks everyones setup no?

**Comment by ahesford** [comment]
Absolutely not. This breaks the default dracut behavior and will render every system unbootable unless users take manual action to install the right hook. The only way around this would be to make the regular dracut package depend on this subpackage, rendering the division pointless.

If you don't want to build a standalone image (it's not a bad idea for recovery situations), just use an [XBPS `noextract` pattern](https://man.voidlinux.org/xbps.d#noextract=pattern).

In the long term, I have been thinking about an approach that would unify the handling of kernel hooks so that initramfs generators are switchable, but I am still not happy with the possibilities right now.

**Comment by 08A** [comment]
Another solution (a little bit weird but retro-compatible):

* dracut (the old dracut-default package) [depends: dracut-base]
* dracut-base (the old dracut package)
* dracut-uefi [depends: dracut-base]

What do you think?

**Comment by ahesford** [comment]
There's no value in this. We still need the default dependencies to pull in the full dracut package with hooks or everybody's installation will break. This means you wind up adding `ignorepkg` rules to skip the hooks you don't want. If you have to use `ignorepkg`, you might as well just use `noextract` and cut out the extra package.

Furthermore, if we develop a sensible way for reconciling conflicting hooks for all initramfs generators, we don't need additional package splits complicating the graph.

**Pull request closed without merging**
