### PR TITLE
lvm2: update to 2.02.187.

### PR DESCRIPTION
**Pull request by rmccask**

### CODE REVIEW

**Comment by Anachron** [comment]
Is this tested?

**Comment by rmccask** [comment]
I attached a 2nd virtual drive to my build vm.  I verified I had the new lvm2 installed.  Then I created a lvm partition on the drive.  I used pvcreate, vgcreate, lvcreate and  lvdisplay.  I rebooted and verified the lv is still there.  Is there more I need to try?

**Comment by Anachron** [comment]
Ah good, no, that should suffice. I just realized you updated to another `2.02` release, the `2.03` one doesn't correctly build without modifications: https://github.com/void-linux/void-packages/pull/20188

**Comment by rmccask** [comment]
Yes, I saw your efforts with 2.03 and took the easy one.

**Pull request merged**
