### PR TITLE
ddgtk: fixes for vte, latest meson, py module name, additional deps

### PR DESCRIPTION
**Pull request by reback00**
**Changes:**

1. Added additional dependencies against build warnings [template]
2. Updated for latest meson [patch]
3. Updated for latest python module (instead of deprecated `python3` module, used the new `python` module, according to: [https://mesonbuild.com/Release-notes-for-0-48-0.html#dependencyversion-now-applies-to-all-dependency-types](https://mesonbuild.com/Release-notes-for-0-48-0.html#dependencyversion-now-applies-to-all-dependency-types)) [patch]
4. Fixed breakage of write functionality due to recent changes in Vte python bindings (Explanation here: [https://github.com/Guake/guake/issues/1243#issuecomment-410208659](https://github.com/Guake/guake/issues/1243#issuecomment-410208659)) [patch]

#4 raised an error like this below which has been fixed:

```
Traceback (most recent call last):
  File "/usr/local/share/ddgtk/ddgtk/main.py", line 154, in on_confirm_ok_clicked
    self.dd()
  File "/usr/local/share/ddgtk/ddgtk/main.py", line 125, in dd
    self.terminal.feed_child(clear,-1)
TypeError: Vte.Terminal.feed_child() takes exactly 2 arguments (3 given)
```

### CODE REVIEW

**Comment by Gottox** [comment]
```
... + other changes ...
```
What are those other changes? Please update the commit message :)

**Comment by reback00** [comment]
> ```
> ... + other changes ...
> ```
> 
> What are those other changes? Please update the commit message :)

Oh! I thought adding all of them would make the commit message bigger. So I added them in the pull request message. No problem, this time I added them in the latest commit message. Hope it works. :)
> ddgtk: fixes for recent vte python bindings, added additional deps, updated for latest meson, adjusted to new python module name

**Comment by reback00** [comment]
The 2 builds  `ARCH=x86_64 BOOTSTRAP=x86_64` and `ARCH=armv7l BOOTSTRAP=x86_64` failed because of a `Bad Gateway` error. I did not change any code in my last commit, so it should've passed. Is it an error on Travis CI's end?
Should I do anything further?

log:
```
=> ddgtk-0.1_2: fetching distfile '0.1.tar.gz'...
https://github.com/gort818/ddgtk/archive/0.1.tar.gz: Bad Gateway
=> ERROR: ddgtk-0.1_2: failed to fetch 0.1.tar.gz.
...
Done. Your build exited with 1.
```
[source](https://travis-ci.org/void-linux/void-packages/jobs/551344151)

**Comment by pullmoll** [comment]
@Duncaen wanted you to change the commit message, i.e. the title < 72 chars and the details in the message body. The PR title is more or less irrelevant, but should usually match the first line of the commit message.
In short do a `git commit --amend` and fix the title, leave one empty line, and fille body of the message with what's listed in this PR. The do a `git push -f` to your branch.
HTH :)

**Comment by reback00** [comment]
@pullmoll Thanks. I think I get it now. I have changed the commit message and added a smaller title and also added the list of changes after a blank line. Also, changed the title of the PR according to the first line of the commit message.

I gotta say, you guys are more helpful than the Arch Linux guys! They like to scream at people for not getting things right and link adamantly to wikis without explaining stuff. Happy to be a part of Void Linux.

**Comment by pullmoll** [comment]
I just now saw there were 2 commits. In the future please squash commits to one per package, i.e. `git rebase -i master` and `squash` or `fixup` the 2nd, 3rd etc. commit depending on whether you want to combine and edit the final commit message or not, then do the `git push -f`. You can always `git commit --amend` the latest commit.

**Comment by reback00** [comment]
Ok. Thanks.

**Pull request merged**
