### PR TITLE
valgrind: update to 3.15.0.

### PR DESCRIPTION
**Pull request by pbui**
Drop PPC64 musl patch as it does not apply cleanly.

### CODE REVIEW

**Comment by xtraeme** [comment]
Even if it does not apply cleanly it should not be removed blindly, because this might be still required for ppc64.

@q66

**Comment by pbui** [comment]
Sorry, I meant to add that the dropping the patch should be reviewed by @q66.   I will mark the package as [WIP] until it is determined if the patch is required or not.

**Comment by q66** [comment]
Here's an updated patch https://gist.github.com/q66/ed2b11369861da05cd9d7a0f0effad3c

**Comment by q66** [comment]
Also, please rename the patch from `elfv2-ppc64-musl.patch` to `elfv2-ppc64-be.patch` as this is specifically for big endian and after the recent addition of ELFv2 big endian glibc support it applies to that as well.

**Comment by q66** [comment]
Still doing some rebuilds on my local machine just to make sure.

**Comment by q66** [comment]
It's fine on my side.

**Pull request merged**
