### PR TITLE
firefox-esr: update to 78.10.0

### PR DESCRIPTION
**Pull request by biopsin**
[skip CI]

Currently test building for all arches, it will take me all day.
Let me know if I missed something..

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by biopsin** [comment]
Fail on i686 -> investigating

> 15:07.84    Compiling cubeb-pulse v0.3.0 (https://github.com/djg/cubeb-pulse-rs?rev=70431f444cf164177cb3c0f060698fc35f811be5#70431f44)
> 15:28.59 error: failed to run custom build command for `style v0.0.1 (/builddir/firefox-78.10.0/servo/components/style)`
> 15:28.59 Caused by:
> 15:28.59   process didn't exit successfully: `/builddir/firefox-78.10.0/obj-i686-pc-linux-gnu/release/build/style-3e4357e8f482dd93/build-script-build` (exit code: 101)
> 15:28.59   --- stdout

..moving on to arm7l/-musl

**Comment by ericonr** [comment]
No checksum changes for `i18n`?

**Comment by biopsin** [comment]
@ericonr ops; I'll correct that.

**Comment by ericonr** [comment]
They are using a bunch of intrinsics in i686, and something's failing (maybe missing flag to bindgen??):

```
15:28.60   /usr/lib/gcc/i686-pc-linux-gnu/10.2.1/include/xmmintrin.h:684:19: #: use of u
ndeclared identifier '__builtin_ia32_movlhps', err: true

**Comment by ericonr** [comment]
For the record, this update should be two commits, one for each package. Any advances on the i686 build?

**Comment by biopsin** [comment]
@ericonr ,well I'm biting on more then I can chew here, but testing

> ac_add_options --enable-debug
> ac_add_options --enable-warnings-as-errors
> ac_add_options --disable-optimize

hopefully the log reveals more I can make sense of..

**Comment by ericonr** [comment]
No worries, just wanted to know what you had tested or not already. I will try to make time to debug this.

Maybe we can look if debian or alpine have patches for it already?

**Comment by biopsin** [comment]
On top of that, I'm also see continues spam while browsing on netflix.. (x86_68-glibc)

> Sandbox: seccomp sandbox violation: pid 2376, tid 2376, syscall 28, args 140548189982720 4096 4294967295 34 4294967295 0.
> Sandbox: seccomp sandbox violation: pid 2376, tid 2376, syscall 28, args 140548189982720 4096 18 34 4294967295 0.
> Sandbox: attempt to open unexpected file /sys/devices/system/cpu/online
> Sandbox: attempt to open unexpected file /proc/stat
> Sandbox: attempt to open unexpected file /proc/net/unix
> Sandbox: attempt to open unexpected file /proc/self/maps
> Sandbox: attempt to open unexpected file /proc/self/maps
> Sandbox: attempt to open unexpected file /proc/net/unix
> Sandbox: attempt to open unexpected file /proc/net/unix
looking into this as well

**Comment by biopsin** [comment]
> Maybe we can look if debian or alpine have patches for it already?
did the peek on alpine, but could not se anything added between 78.8. -> 78.10.
https://git.alpinelinux.org/aports/tree/community/firefox-esr?h=master

will build test for 78.9.0 as well see what's happening before.

**Comment by ericonr** [comment]
> On top of that, I'm also see continues spam while browsing on netflix.. (x86_64-glibc)

Are these new? The build seems to have worked on CI, at least, for i686. I think we could go ahead with merging.

**Comment by biopsin** [comment]
@ericonr 
its not not present on 78.8, but videos do play.. however anoying.
Please go ahead and merge.

**Comment by ericonr** [comment]
>  its not not present on 78.8, but videos do play.. however anoying.

Seems some of it is known: https://aur.archlinux.org/packages/firefox-esr

> Also you can low security.sandbox.content.level to 1 as a workaround, so you don't need to disable it completely.

If you have a mozilla bugzilla account, you should be able to report it.

**Pull request merged**
