### PR TITLE
discord: update to 0.0.18.

### PR DESCRIPTION
**Pull request by zlice**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture: **x86_64**

### CODE REVIEW

**Comment by KJ002** [comment]
Worked for me, thank you for saving me from getting the checksum

**Comment by terrybrash** [comment]
Works for me.

**Comment by HarveyB02** [comment]
Works perfectly for me on x86_64

**Comment by classabbyamp** [comment]
tested works for me

**Comment by ThePademelon** [comment]
Works for me too on x86_64.

**Pull request merged**
