### PR TITLE
yaml-cpp: update to 0.6.2. & mongodb: update to 3.4.17

### PR DESCRIPTION
**Pull request by Johnnynator**
needed for #3230

### CODE REVIEW

**Comment by maxice8** [comment]
yaml-cpp dropped boost dependency https://github.com/jbeder/yaml-cpp/releases

**Comment by Johnnynator** [comment]
Ok dropped it. Also added a patch for OpenXcom that i missed to add. In ~2h the Travis builds should be finished.
https://www.travis-ci.com/Johnnynator/void-packages/builds/86428921

**Comment by Johnnynator** [comment]
Everything compiled so far. Only mongodb on aarch64 is missing.

**Comment by Johnnynator** [comment]
Every Arch did compile fine.

**Pull request merged**
