### PR TITLE
bash-completion: update to 2.14.0.

### PR DESCRIPTION
**Pull request by dataCobra**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86_64-musl
  - i686

### CODE REVIEW

**Comment by classabbyamp** [comment]
why are there a bunch of new symlinks to _golangci-lint?

**Comment by dataCobra** [comment]
I don't know.

Should I check with upstream?

**Comment by classabbyamp** [comment]
or look at the git history/contents of the files and figure it out

**Comment by dataCobra** [comment]
As it seems the symlinks are all for fallback reasons.

The commits of the symlinks all give this information: "add 3rd party fallback completion loader".

Do you need more information or is this alright?

**Pull request closed without merging**
