### PR TITLE
podman: Add fuse-overlayfs to depends

### PR DESCRIPTION
**Pull request by kartikynwa**
#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

Related to #29491

### CODE REVIEW

**Review by ericonr — APPROVED** [review]
I'm going to let it sit for a few days so people can raise objections, and merge afterwards. Thanks :D

**Review by ahesford — APPROVED** [review]
See also #29530. We can save a revbump if we coordinate both changes.

**Comment by kartikynwa** [comment]
Maybe you can ask that author to add it to depends in their commit and force push. We can then close this PR and merge the other one.

17-Mar-2021 19:24:29 Andrew J. Hesford ***@***.***>:

**Comment by kartikynwa** [comment]
> break existing installations

Yeah that could be problematic

**Comment by ahesford** [comment]
I'm not a heavy `podman` user and don't have a strong opinion, but it seems like the error is non-destructive. It might be worth the errors if `fuse-overlayfs` solves the excessive space problem. (I assume that, without overlayfs, the `vfs` driver just duplicates each layer to create the next one.)

This is probably worth an `INSTALL.msg` if the error completely prevents containers from starting. People might have configured services to automatically start containers and the reason for a failure might be overlooked.

**Comment by lemmi** [comment]
@ahesford: Thoughts?
`INSTALL.msg`:
```
`fuse-overlayfs` has been added as a runtime dependency to podman.
podman will now prefer this storage driver to the `vfs` driver.

To switch to the new storage driver, podman has to be reset:

   # podman system reset

To keep the `vfs` fallback driver, add this to `/etc/containers/storoage.conf` 
or `~/.config/containers/storage.conf`:

    [storage]
    driver="vfs"

Otherwise podman will display an error and refuses any further operation.

Additionally the `btrfs` storage driver has been enabled. This driver also 
available for rootless operation. Reset podman and add the following to your 
`storage.conf` to switch to this driver:

    [storage]
    driver="btrfs"
```

**Pull request closed without merging**
