### PR TITLE
podman: update to 3.4.4.

### PR DESCRIPTION
**Pull request by daniel-eys**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by daniel-eys** [comment]
Hm so musl builds are failing. I'm having a look into this.

**Comment by daniel-eys** [comment]
https://github.com/containers/podman/issues/12563

**Comment by ericonr** [comment]
Seems to be fixed, importing the patch should be enough?

**Comment by daniel-eys** [comment]
Patch imported and musl builds seem fine again.

**Comment by daniel-eys** [comment]
done with https://github.com/void-linux/void-packages/commit/86115b58fb2bc203e17b3ddc45474128f1b703dc and https://github.com/void-linux/void-packages/commit/fd719025f54ccea67106d66bd8a0bc6a37c98af7

**Pull request closed without merging**
