### PR TITLE
cordless: remove package

### PR DESCRIPTION
**Pull request by tibequadorian**
The maker of cordless is closing it down because its usage apparently leads to a ban due to violation of the ToS
https://github.com/Bios-Marcel/cordless/blob/54865be813e03d1d8357a2c08162b4727aa98201/README.md
>I decided to not work on the cordless project anymore
>I'll be taking down cordless in package managers in hope that no new users will install it anymore without knowing the risks

### CODE REVIEW

**Review by ericonr — APPROVED** [review]
I'm okay with the removal, but I don't know if others prefer we keep the package, at least as long as it's still working.

I also don't use discord, so I don't have strong feelings on it.

**Comment by sburris0** [comment]
If packages leading to ToS bans are to be avoided then perhaps #19576 should be closed? I believe Ripcord also violates the Discord ToS

**Comment by q66** [comment]
we don't need to care, all that's being violated is discord's EULA, and not by us (since we as a distribution are not the end users/never agreed to it in the first place)

but if it's dead, it might as well go, no point in keeping dead software

**Comment by NeelChotai** [comment]
I agree - it's not our responsibility to enforce Discord's ToS. The most we should do is add an INSTALL.msg stating some people have had their account banned for using third-party clients.

There appears to be an active fork if someone finds this pull request in the future and would like to package cordless: https://github.com/0xSteeW/cordless

**Pull request merged**
