### PR TITLE
PulseEffects5

### PR DESCRIPTION
**Pull request by paper42**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

PulseEffects 5 only supports PipeWire, so I made a new package `pulseeffects-legacy` which will stay on the PulseEffects 4. This approach is similar to what other distributions have done. I also added an install message to pulseeffects to let users know about this change.

related issue: #29006

### CODE REVIEW

**Comment by ericonr** [comment]
This looks like a reasonable path forward.

**Comment by ericonr** [comment]
Could you please add an `update` file to the legacy package? That way we can pick up any security updates, if they happen (I believe the dev said they could do security releases).

**Comment by paper42** [comment]
thanks, I also made pulseeffects-legacy conflict with pulseeffects

**Comment by GameWizard5000** [comment]
It looks like it won't launch without `gstreamer1-pipewire`. So that should probably be added as a dependency.

**Comment by ericonr** [comment]
@GameWizard5000 thanks for find. Should be good to merge once that's fixed.

**Comment by ericonr** [comment]
@paper42 if you could mention in the commit for `legacy` that it's basically a copy of "old "`pulseeffects`, I think that'd be nice,

**Comment by paper42** [comment]
@ericonr @GameWizard5000 thank you both for your finds, they should be fixed now. I also reworded INSTALL.msg a bit, so hopefully it's a bit better now.

**Pull request closed without merging**
