### PR TITLE
New package: gfan-0.6.2

### PR DESCRIPTION
**Pull request by tornaria**
Dependency of sagemath

### CODE REVIEW

**Comment by tornaria** [comment]
It seems to be stuck in a test on i686. On my box the test that stalls is:
```
Running command:"cat <testsuite/0602ResultantFanProjection/input|./gfan _resultantfan --vectorinput --projection| grep F_VECTOR -A1>testsuite/0602ResultantFanProjection/outputNew"
```

The whole testsuite takes ~  1m on x86_64 and the test above has been running for 6m+ on my box (and apparently it ran 1h30 on CI).

**Comment by tornaria** [comment]
Summary: two tests fail on i686:
```
testsuite/0009RenderStairCase FAILED!
testsuite/0602ResultantFanProjection FAILED!
```
The first one finishes with failure, and the second one doesn't finish. I'll report them both upstream later.

@leahneukirchen: Do you think we have to delay merging b/c of this? I'll follow up in any case.

**Comment by leahneukirchen** [comment]
I don't mind the test suite failure, but this sounds like it's actually broken on i686 so fixing would be good.

Perhaps someone can try on 32-bit ARM?

**Comment by tornaria** [comment]
> I don't mind the test suite failure, but this sounds like it's actually broken on i686 so fixing would be good.

Sure, but since only one particular application is broken maybe this is still useful. Otherwise we could not package for 32 bits.

**Comment by ericonr** [comment]
Suggested on IRC: have you tried adding `-ffloat-store` to the x86 build to see if it's enough?

**Comment by tornaria** [comment]
> Suggested on IRC: have you tried adding `-ffloat-store` to the x86 build to see if it's enough?

Indeed, this fixes the failure in `0009RenderStairCase` so I'll add it. Unfortunately, `0602ResultantFanProjection` is still looping forever regardless of this option.

**Comment by tornaria** [comment]
I couldn't find an issue tracker for gfan. On the sagemath trac, the same issue was reported 5 months ago in https://trac.sagemath.org/ticket/32088, but there is no clue there.

**Comment by tornaria** [comment]
Also debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=905300. They just disable this test on 32bit.

**Pull request merged**
