### PR TITLE
base-chroot: unified for glibc and musl libc

### PR DESCRIPTION
**Pull request by pullmoll**
I believe that this cannot be merged in the usual way because it is a bootstrap package and our builders depend on base-chroot. Thus it needs to be built manually for native before the cross base-chroot packages can be built by the builders. 
It is meant to allow for bootstrapping `*-musl` architectures like `x86_64-musl` or `ppc64-musl`.
It also removes `archs=noarch` to create per-arch meta packages and avoid problems when forcefully rebuilding. Note that base-chroot-musl already was a per-arch meta package.

### CODE REVIEW

**Comment by xtraeme** [comment]
Hmm maybe add `replaces="base-chroot-musl>=0"`

**Comment by pullmoll** [comment]
It does not yet work right. I think I need to keep the order of depends rather than what `xtrimdeps` made of it.

**Comment by xtraeme** [comment]
Yes, the build order is important.

**Comment by pullmoll** [comment]
Bootstrapping on `x86_64-musl` doesn't find the already built packages. It fails to find the just built `zlib-devel` before trying to build `gcc`. Restarting with `./xbps-src zap;./xbps-src bootstrap` builds the same packages again.

I think there is some hard coded `x86_64{,-repodata}` below `./common` where there should be `$XBPS_ARCH` or perhaps `$XBPS_TARGET_ARCH`.

**Comment by xtraeme** [comment]
@pullmoll is this working as expected?

**Comment by pullmoll** [comment]
It works for me if I specify `XBPS_ARCH=x86_64-musl` for a bootstrap; tested in a VM a couple of days ago. Of course it would be even nicer if `XBPS_ARCH` was set correctly already by `xbps-src` or `common/whatever`.

**Comment by xtraeme** [comment]
This needs to be fixed @pullmoll

**Comment by pullmoll** [comment]
How? I don't see where `XBPS_ARCH` becomes `x86_64` in an environment which is actually `x86_64-musl`.
There is no `${...%-musl}` somewhere in `common/*` as far as I see.

**Comment by xtraeme** [comment]
it's set in xbps-src iirc

**Comment by pullmoll** [comment]
There is a line `export XBPS_ARCH=${XBPS_ARCH:-$(cat $XBPS_MASTERDIR/.xbps_chroot_init)}`  which reads the arch from `.xbps_chroot_init`. Perhaps the problem is there just because of the unsolved #10299 which I think should be fixed by the people who broke it in the first place :)

**Comment by xtraeme** [comment]
Looks like I broke it? heh. ok will look at it :-)

**Comment by xtraeme** [comment]
I'm working on it... as well as some more cleanups to xbps-src, to make it easy to follow its flow execution.

**Comment by xtraeme** [comment]
Not sure who had the fantastic idea to build `gcc` with ada for bootstrap?

**Comment by xtraeme** [comment]
ok, I disabled the `ada` build option if $CHROOT_READY unset.

**Comment by xtraeme** [comment]
Anyway gcc-ada seriously should not be part of base-chroot

**Comment by xtraeme** [comment]
wtf ada? it's not used anywhere...

**Comment by pullmoll** [comment]
It is required because you need an ada compiler to build ada. Since a package cannot depend on itself, gcc-ada had to become installed as part of base-chroot. Otherwise you would always need to build gcc using a 3rd-party gcc-ada.

**Comment by xtraeme** [comment]
Ugh... but do we need 'ada' really?

**Comment by xtraeme** [comment]
the same process could be done via chroot... isn't it?

**Comment by pullmoll** [comment]
Ada is used e.g. by several of our users and is e.g. used to build some of the coreboot files.

**Comment by xtraeme** [comment]
The first bootstrap pass should only provide you a reduced C/C++ compiler, imho.

Once you've built base-chroot, you *should* rebuild gcc with ada support, gcc-ada or whatever.

**Comment by pullmoll** [comment]
But if you don't have gnat (built in the chroot as part of gcc) you cannot compile gcc-ada ;-P

**Comment by xtraeme** [comment]
but you can recompile *gcc* if CHROOT_READY == true

**Comment by xtraeme** [comment]
in fact the generated gcc pkg via bootstrap should always be rebuild by itself in the chroot to have a reproducable result.

**Comment by xtraeme** [comment]
but I'll leave it as is for now, I just disabled ada for testing.

**Comment by xtraeme** [comment]
@pullmoll iirc NetBSD does not build ada support via build.sh, and you can still get it via pkgsrc... so that we should be able to do the same.

**Comment by pullmoll** [comment]
Then gcc-ada would have to be a package independent of gcc and you would always need a 3rd-party gcc, not the void gcc, to build gcc-ada. If you need another argument: LFS builds gcc-ada as part of gcc and AFAICT many Linux distributions also build ada with gcc.

**Comment by xtraeme** [comment]
@pullmoll we'll keep it as is :-)

**Comment by pullmoll** [comment]
*phew* it really took me weeks to solve this somehow. I don't think the + 1/5th of build time for gcc actually matters that much nowadays compared to the trouble of getting it built with 3rd-party toolchains.

**Comment by xtraeme** [comment]
Ok, it works, tested with `xbps-src bootstrap` and `xbps-src -a aarch64-musl -Nt xbps`.

This contains multiple cleanups in xbps-src as well as some packages. I'll make a new branch and will reference this PR.

**Comment by xtraeme** [comment]
@pullmoll please #11282

I only tested in a `musl` host, would be nice if you can test `glibc` even with foreign distribution.

**Comment by pullmoll** [comment]
@xtraeme a x86_64 bootstrap is running here now. I can also test a native ppc64 bootstrap but that will take at least 5 hours to finish :)

**Comment by xtraeme** [comment]
Nice! I think the code is cleaner too... my next pass will be common/

**Comment by pullmoll** [comment]
superseeded by #11282

**Pull request closed without merging**
