### PR TITLE
New package: python3-curio-1.4

### PR DESCRIPTION
**Pull request by ar-jan**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (x86_64)
- [ ] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [ ] aarch64-musl
  - [ ] armv7l
  - [ ] armv6l-musl

### Reason

#28272 keeps getting stuck on CI so I want to see if adding dependencies one by one would pass tests.

### CODE REVIEW

**Comment by ar-jan** [comment]
On CI the following builds succeed:

    aarch64, x86_64
    armv7l, x86_64
    armv6l-musl, x86_64-musl
    aarch64-musl, x86_64-musl

Locally on an `x86_64` system the tests also pass. But for some reason `x86_64, x86_64`, `i686, i686`, and `x86_64-musl, x86_64-musl` run out of time on CI without any reported errors. On #voidlinux channel a CI connectivity problem was suggested as a possible reason. Since it builds successfully on most arches I've disabled tests and added a note.

**Comment by Chocimier** [comment]
Don't send here PRs that you do not want to be merged. To test things, send them to your own fork.

Please do not disable tests that pass locally. Please comment in template instead.

Here, failure in CI is because container have some privileges that https://github.com/dabeaz/curio/blob/1.4/tests/test_network.py#L317 don't expect - please disable that one test with `pytest -k`.

**Comment by ar-jan** [comment]
OK, will do.

I thought the new dependencies might have to be added in separate pull requests because there was no way to proceed with the the original #28272 and find out which specific package was at issue.

> To test things, send them to your own fork.
I wanted to see CI test results for individual packages because it seemed there were no other options to find out what was going on. Are CI tests possible on individual forks, or what do you mean by testing?

> Here, failure in CI is because container have some privileges that https://github.com/dabeaz/curio/blob/1.4/tests/test_network.py#L317 don't expect - please disable that one test with pytest -k.

Aha! Any way I could have discovered that? There were no errors or warnings.

**Comment by Chocimier** [comment]
> Any way I could have discovered that?

When you are logged in, there is a box above comment box at this page. Click "Details" for given architecture, then browse logs. There is a convenient text form of logs under three-dots-menu - "View raw logs".

**Pull request closed without merging**
