### PR TITLE
New package: lbry-desktop-0.45.1

### PR DESCRIPTION
**Pull request by reback00**
[LBRY](https://lbry.com/) is a blockchain based, decentralized, completely open and Free video and content sharing platform. It was [requested](https://github.com/void-linux/void-packages/issues/13413) too. Hope it is useful.

**UPDATE 2020.04.04:** Updated to 0.44.0, updated patch file for new codebase, removed unnecessary npm command. I'm still hoping it gets merged. Waiting since October 2019.

**UPDATE 2020.05.07:** Updated to 0.45.1

**UPDATE 2020.10.16:** Updated to 0.48.1, added a fix for a node-gyp error

### CODE REVIEW

**Comment by ericonr** [comment]
Can this be made to work with system electron?

**Comment by reback00** [comment]
It's been a year already since the first submit. I almost forgot it existed! Thanks for your interest.

Unfortunately, I'm not sure. It seems to rely on `electron-builder`:

```
  • loaded configuration  file=/builddir/lbry-desktop-0.48.1/electron-builder.json
  • loaded parent configuration  file=/builddir/lbry-desktop-0.48.1/node_modules/electron-webpack/out/electron-builder.js
  • packaging       platform=linux arch=x64 electron=9.3.1 appOutDir=dist/electron/linux-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v9.3.1/electron-v9.3.1-linux-x64.zip size=73 MB parts=4
  • downloaded      url=https://github.com/electron/electron/releases/download/v9.3.1/electron-v9.3.1-linux-x64.zip duration=4m11.854s
  • building        target=AppImage arch=x64 file=dist/electron/LBRY_0.48.1.AppImage
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z size=1.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z duration=40.45s
  • building        target=deb arch=x64 file=dist/electron/LBRY_0.48.1.deb
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z size=5.0 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z duration=3m22.283s
Done in 954.99s.
```

[electron-builder](https://github.com/electron-userland/electron-builder) seems to be:

> A complete solution to package and build a ready for distribution Electron app with “auto update” support out of the box

It can build for `AppImage, snap, debian package (deb), rpm, freebsd, pacman, p5p, apk`. These files mention "electron-builder":
```
./package.json
./CHANGELOG.md
./yarn.lock
./build/afterSignHook.js
./.travis.yml
./README.md
./flow-typed/npm/electron-webpack_vx.x.x.js
./flow-typed/npm/electron-builder_vx.x.x.js
```

Also, there is a `electron-builder.json` file on source tree. Maybe if we can remove electron-builder it will be possible to use system electron. But I'm not sure if the package will play nice with the system electron. I've also checked `atom` and `slack-desktop`. They don't use system electron either.

**Comment by ericonr** [comment]
There are other packages using electron-builder, I believe Signal-Desktop is one of them.

**Comment by reback00** [comment]
Oh! I didn't know that.

**Pull request closed without merging**
