### PR TITLE
New package: nng-1.4.0

### PR DESCRIPTION
**Pull request by ruantu**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ahesford** [comment]
Why are you disabling all of this documentation? It can go into a -doc subpackage so people can install it if needed, and we won't need to carry a patch.

**Comment by ruantu** [comment]
> Why are you disabling all of this documentation? It can go into a -doc subpackage so people can install it if needed, and we won't need to carry a patch.
Because there is already a man manual, I think the html document is redundant for linux....

**Comment by ericonr** [comment]
Assuming they are easy to build, it's preferable to just build them and possibly remove in a `post_install` script (or do the subpackage) rather than carry a huge patch.

**Comment by ericonr** [comment]
Hi, did you mean to close this?

**Pull request closed without merging**
