### PR TITLE
New package: pipr-0.0.16

### PR DESCRIPTION
**Pull request by realcharmer**
A tool to interactively write shell pipelines.
<https://github.com/elkowar/pipr>

#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)

### CODE REVIEW

**Comment by realcharmer** [comment]
It seems the package fails to build on anything other that x86-based platforms on current stable 1.64.0 and 1.66.0 as well. Is it acceptable to limit the package for x86 platforms only?

**Comment by paper42** [comment]
This looks fixable, look at the bat template for example

**Comment by realcharmer** [comment]
> This looks fixable, look at the bat template for example

Thanks for the tip, that solved the issue.

**Comment by realcharmer** [comment]
Still waiting for merge.

**Pull request closed without merging**
