### PR TITLE
gifski: update to 1.4.0.

### PR DESCRIPTION
**Pull request by benalb**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
If you don't mind the dependency, we can probably look into enabling video support.

Despite what https://github.com/ImageOptim/gifski#with-built-in-video-support says, we already have all the ffmpeg work done.

**Comment by ericonr** [comment]
This is only if you want it, though. Otherwise we can just go ahead and merge.

**Comment by benalb** [comment]
> This is only if you want it, though. Otherwise we can just go ahead and merge.

I'm on it.

**Comment by ericonr** [comment]
I think you want to use this https://github.com/rust-lang/rust-bindgen#environment-variables to set a `--sysroot` and a `--target`. The  `python3-pyside` template has the values you need to set them to.

**Comment by ericonr** [comment]
Ping?

**Comment by benalb** [comment]
> Ping?

I'm doing my best, but I can't figure out the template. I've tried several combinations of CLANG_OPTIONS, like XBPS_CROSS_TRIPLET, or XBPS_CROSS_BASE, but still getting the "fatal error: gnu/stubs-soft.h: No such file or directory" when cross-compiling for armv7l.

**Comment by ericonr** [comment]
Have you tried `export BINDGEN_EXTRA_CLANG_ARGS="--target=${XBPS_CROSS_TRIPLET} --sysroot=/usr/${XBPS_CROSS_TRIPLET}"`?

**Comment by benalb** [comment]
What is the command the builder uses for armv7l?
With this last template modification, here builds in x86_64, both libc and musl, cross builds for aarch64, armv6l, and armv7l. I've installed the armv7l version package in a raspi, and gifski works ok, so I have no clue what is wrong.

**Pull request merged**
