### PR TITLE
New package: defold-1.2.186

### PR DESCRIPTION
**Pull request by shizonic**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by shizonic** [comment]
Guess this only fails because of a connection error.

**Comment by Chocimier** [comment]
Recompressed binaries are not a good canditates to repository.
This one vendors java, lua, libzip, and who knows what else.

**Comment by shizonic** [comment]
> Recompressed binaries are not a good canditates to repository.
> This one vendors java, lua, libzip, and who knows what else.

So should I close this?

**Comment by shizonic** [comment]
> Unless you are willing to build it from source for more architectures than just x86_64, yes.

Guess it's more a question of being capable than willing but I'll give it a try.

**Pull request closed without merging**
