### PR TITLE
bash: update to 5.0.0.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by maxice8** [comment]
@Gottox needs some testing :D

**Comment by maxice8** [comment]
@chneukirchen please note it down **4** things as breaking due to bash 5.0

**Comment by Gottox** [comment]
Naiv `dracut -f` works for me.

**Comment by Gottox** [comment]
What's the content of `/usr/lib/bash`?

**Comment by Gottox** [comment]
And what is that? :D

**Comment by maxice8** [comment]
?

**Pull request merged**
