### PR TITLE
update: x264, x265

### PR DESCRIPTION
**Pull request by Piraty**
@DirectorX

### CODE REVIEW

**Comment by Piraty** [comment]
@DirectorX objections if i remove `--disable-swscale` ?

**Comment by DirectorX** [comment]
@Piraty Please try to avoid the removal of swscale. It useful for high quality colorspace conversation and image scaling.

**Comment by Piraty** [comment]
> @Piraty Please try to avoid the removal of swscale. It useful for high quality colorspace conversation and image scaling.
I ask for the removal of the configure flag `--disable-swscale` from the template, to actually enable swscale!
```
./configure | grep swscale
--disable-swscale        disable swscale support
```

I didn't dig into the circumstances leading to fd0b122cd50aa3760b4a5b7c51fd3efebae54588, but i didn't find any issue when removing the flag.

**Comment by DirectorX** [comment]
Now to get it. So please do.

**Pull request closed without merging**
