### PR TITLE
New package: subfinder-2.4.5

### PR DESCRIPTION
**Pull request by jsav0**

### CODE REVIEW

**Comment by jsav0** [comment]
Woops. forgot checksum.

**Comment by ericonr** [comment]
Please test your templates and the resulting package locally before opening a PR, unless you require help. Furthermore, don't open and close PRs, just force push into the remote branch.

**Comment by jsav0** [comment]
@ericonr 
Thanks. Will you explain what you mean by "just force push into the remote branch"?

**Comment by ericonr** [comment]
Correct the template, use `git add` then `git commit --amend` to have a single commit with all the changes, then `git push --force origin <branch_name>`

**Pull request closed without merging**
