### PR TITLE
OpenJK, gamemode: orphan; senpai: swap maintainer

### PR DESCRIPTION
**Pull request by kedodrill**
I haven't played video games in awhile, so gamemode isn't really useful to me anymore. OpenJK as well.

I don't use IRC / senpai much either.

### CODE REVIEW

**Comment by realcharmer** [comment]
I'd be willing to adopt `senpai`.

**Comment by kedodrill** [comment]
@realcharmer Sounds good. Might want to check in with @eoli3n since they updated it to 0.2.0 recently.

**Comment by eoli3n** [comment]
Just bumped the version one time, @realcharmer get it if you want ;)

**Comment by realcharmer** [comment]
Thanks @eoli3n , sure thing. @kedodrill, you might as well amend me as the new maintainer of `senpai` to this PR.
`Emil Miler <em@0x45.cz>`

**Comment by kedodrill** [comment]
@realcharmer Great, just changed it! Thanks for taking it over! :)

**Pull request merged**
