### PR TITLE
New packages: phosh + deps (squeekboard, phoc, callaudiod and feedbackd)

### PR DESCRIPTION
**Pull request by jcgruenhage**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

#### TODOs
- [ ] Create a service for phosh
- [ ] Testing

### CODE REVIEW

**Comment by jcgruenhage** [comment]
So, posh now builds correctly with the subprojcets fetched, but at least on my Pinephone it seems not to work yet. I'm not sure what's going on, since the error originates from wlroots, but wlroots works fine on that phone with sway. See the logs:

```
phoc-output-Message: 09:19:27.339: Output 'DSI-1' added ('<Unknown>'/'<Unknown>'/''), 68mm x 136mm
phoc-server-Message: 09:19:27.647: Enabling shell mode
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
dbus[833]: Unable to set up transient service directory: XDG_RUNTIME_DIR "/tmp" is owned by uid 0, not our uid 1000
gnome-session-binary[822]: WARNING: Failed to upload environment to systemd: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.freedesktop.systemd1" does not exist
gnome-session-binary[822]: WARNING: Could not get session id for session. Check that logind is properly installed and pam_systemd is getting used at login.
gnome-session-binary[822]: WARNING: Could not parse desktop file libcanberra-login-sound.desktop or it references a not found TryExec binary

(phosh:843): phosh-osk-manager-WARNING **: 09:19:30.299: Unable to toggle OSK: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name sm.puri.OSK0 was not provided by any .service files
XDG_RUNTIME_DIR (/tmp) is not owned by us (uid 1000), but by uid 0! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)

(phosh:843): Gvc-WARNING **: 09:19:30.621: Failed to connect context: Connection refused

(phosh:843): GLib-GIO-ERROR **: 09:19:30.629: Settings schema 'org.gnome.shell.keybindings' is not installed
gnome-session-binary[822]: WARNING: Application 'sm.puri.Phosh.desktop' killed by signal 5
(EE) failed to read Wayland events: Broken pipe

(phoc:811): phoc-wlroots-CRITICAL **: 09:19:30.673: [backend/drm/drm.c:1594] drmHandleEvent failed
```

I've tried running it on my laptop, where it doesn't crash, but I don't see anything besides a black screen and a mouse cursor, so.. This isn't quite complete yet.

**Comment by jcgruenhage** [comment]
Well, sort-of stale, but I still plan to continue on it.

**Comment by Newbytee** [comment]
You can't use upstream wlroots with Phoc. It does not work. I suggest you copy what we do in Alpine and statically link Purism's fork of wlroots into Phoc: https://git.alpinelinux.org/aports/tree/community/phoc/APKBUILD

**Comment by jcgruenhage** [comment]
I plan on continuing on this once the new 6.1 based megi kernel is out, so no, not stale.

**Comment by jcgruenhage** [comment]
Still planning on continuing this.

**Comment by jcgruenhage** [comment]
@Newbytee feel free to take this over, I don't see myself working on this any time soon, if at all.

**Comment by Newbytee** [comment]
I have no interest in Void Linux personally, so I don't have any interest in taking this over.

**Comment by jcgruenhage** [comment]
ah, then I misunderstood, no worries

**Pull request closed without merging**
