### PR TITLE
nodejs: update to 18.16.0.

### PR DESCRIPTION
**Pull request by paper42**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Blockers
- [x] element-desktop - nodejs 18 not supported upstream
- [x] vscode - nodejs 18 not supported upstream

### CODE REVIEW

**Comment by dkwo** [comment]
element-desktop builds fine here
```
=> Registering new packages to /host/binpkgs
index: added `element-desktop-1.11.24_2' (x86_64-musl).
index: added `riot-desktop-1.11.24_2' (x86_64-musl).
index: 5 packages registered.
```

**Comment by mhmdanas** [comment]
I was able to build Node 18.15.0 successfully with `--enable-lto` passed to `./configure`, so you may want to add that to the template @paper42. Additionally, the package uses some vendored dependencies that are available in the repos (e.g. brotli), so you might want to make the package use those dependencies from the repos instead.

**Comment by paper42** [comment]
> I was able to build Node 18.15.0 successfully with `--enable-lto` passed to `./configure`, so you may want to add that to the template @paper42. Additionally, the package uses some vendored dependencies that are available in the repos (e.g. brotli), so you might want to make the package use those dependencies from the repos instead.

hi, I think that moving this PR forward is more important than this for now, could you open a separate PR?

**Comment by paper42** [comment]
merged in c6d44d3f9a80dd5b5dc672b47fe28864a6af8a89

**Pull request closed without merging**
