### PR TITLE
docker: mount systemd cgroup at startup

### PR DESCRIPTION
**Pull request by aya**
* mount systemd cgroups before running docker to fix error described in [wiki](https://wiki.voidlinux.eu/Docker#Troubleshooting)

### CODE REVIEW

**Comment by maxice8** [comment]
Please bump revision= in the template so the changes are picked up and the package is rebuilt

**Comment by Duncaen** [comment]
I think something like the following would be nicer.
```
mountpoint -q /sys/fs/cgroup/systemd || {
     mkdir -p /sys/fs/cgroup/systemd;
     mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd;
}
```

**Comment by aya** [comment]
Thanks for your advices, I updated code accordingly.

**Comment by Hoshpak** [comment]
please rebase on to of current master to resolve the conflict.

**Pull request merged**
