### PR TITLE
libGL: update to 19.0.1.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by Cogitri** [comment]
wfm on x86_64

**Comment by lemmi** [comment]
Can test in about 6h.

**Comment by lemmi** [comment]
Works on x86_64 with Vega card.
Does this also apply to us?
[https://bugzilla.redhat.com/show_bug.cgi?id=1692426](https://bugzilla.redhat.com/show_bug.cgi?id=1692426)

**Comment by maxice8** [comment]
Apparently not the workaround is https://github.com/mesonbuild/meson/commit/da1bb49787b2f65ca3a4c3c3fb0d9eda822f3275

and we pass -Db_ndebug=true on common/build-style/meson.sh#L124

Saved by explicitly passed all possible arguments that meson can take.

**Pull request merged**
