### PR TITLE
Freecad: Update to 0.19.1

### PR DESCRIPTION
**Pull request by sww1235**
#### Have the results of the proposed changes been tested?
- [X] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me

I tested these changes in a separate branch that I used for testing the FreeCAD master prior to 0.19 being released.

### CODE REVIEW

**Comment by ericonr** [comment]
Please remember to squash the commits :)

**Comment by sww1235** [comment]
I can do that. I wasn't sure if everything should be in one commit, or if the patches should be separate

**Comment by sww1235** [comment]
Squashed and ready to go.

FYI, I am willing to take this package on as a maintainer. Not quite sure the procedure for doing so, since @yopito still seems to be active in the community.

**Comment by yopito** [comment]
I don't agree: version 0.19(.1)  is not yet officially released. last stable remains 0.18.4 (according to https://www.freecadweb.org/downloads.php)
Furthermore, have to review and compare with my own WIP branch.

Regarding maintainership, I have to think about it. 
@sww1235 : are you a CAD guy, contrary of me ? (I don't use FreeCAD, just package and perform basic runtime tests).

**Comment by karl-nilsson** [comment]
> I don't agree: version 0.19(.1) is not yet officially released. last stable remains 0.18.4 (according to https://www.freecadweb.org/downloads.php)

their git repo has a number of releases more recent than 0.18.4
https://github.com/FreeCAD/FreeCAD/releases

the stable PPA is up to v0.19
https://launchpad.net/~freecad-maintainers/+archive/ubuntu/freecad-stable

**Comment by sww1235** [comment]
I do use FreeCAD for CAD related things. I am also getting a bit more involved in the development side of things for FreeCAD, and am following the development progress closely.

And yes, 0.19.1 is officially released, and they are now developing 0.20. We also missed 0.18.5 and 0.18.6, which probably could have been useful for users here. https://github.com/FreeCAD/FreeCAD/releases

**Comment by ericonr** [comment]
I am a bit bothered about 0.19.1, from the release page:

> FreeCAD 0.19.1 Release (WIP)

Do you know why it's listed as WIP?

**Comment by karl-nilsson** [comment]
> Do you know why it's listed as WIP?

I think it's because they haven't uploaded all the release artifacts (windows installers, appimages) to github yet.
Here's an example:
https://github.com/FreeCAD/FreeCAD/releases/tag/0.18.1

**Comment by yopito** [comment]
tag are not sufficient, things might move until official announcement.  
Even release note is still WIP (https://wiki.freecadweb.org/Release_notes_0.19).

Side note: I've already had to deal with this kind: upstream seafile MOVE their tag until official announcement for instance :(

**Comment by yopito** [comment]
Comparing this PR with my freecad.current branch, I've noticed the points below. 
This is a partial review, I have to compare other items (some patches and template file too).

`srcpkgs/freecad/patches/001-remove-python2.patch` is useless: don't need to build with python3.

`srcpkgs/freecad/patches/150-vtk9.patch` : content is out of date. suggestion:
```
Taken from https://github.com/wwmayer/FreeCAD/commit/bb9bcbd51df7c3cb76c5823038e4ea0f7e25a9ff
but removed patch on file src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp : already applied (2021-01-20)
```
missing patch `srcpkgs/freecad/patches/152-cmake-vtk9.patch`:
```
--- cMake/FreeCAD_Helpers/SetupSalomeSMESH.cmake	2020-11-26 15:59:27.000000000 +0100
+++ cMake/FreeCAD_Helpers/SetupSalomeSMESH.cmake	2020-11-26 23:09:12.778262636 +0100
@@ -11,6 +11,8 @@
         set(SMESH_VERSION_TWEAK 0)
 
         #if we use smesh we definitely also need vtk, no matter of external or internal smesh
+        find_package(VTK REQUIRED NO_MODULE)
+        if(${VTK_MAJOR_VERSION} LESS 9)
         set (VTK_COMPONENTS
             vtkCommonCore
             vtkCommonDataModel
@@ -23,18 +25,37 @@
             vtkFiltersSources
             vtkFiltersGeometry
         )
-
-        # check which modules are available
-        if(UNIX OR WIN32)
             find_package(VTK COMPONENTS vtkCommonCore REQUIRED NO_MODULE)
             list(APPEND VTK_COMPONENTS vtkIOMPIParallel vtkParallelMPI vtkhdf5 vtkFiltersParallelDIY2 vtkRenderingCore vtkInteractionStyle vtkRenderingFreeType vtkRenderingOpenGL2)
+        else()
+            # VTK 9 changed its component names
+            set (VTK_COMPONENTS
+                CommonCore
+                CommonDataModel
+                FiltersVerdict
+                IOXML
+                FiltersCore
+                FiltersGeneral
+                IOLegacy
+                FiltersExtraction
+                FiltersSources
+                FiltersGeometry
+            )
+            find_package(VTK COMPONENTS CommonCore REQUIRED NO_MODULE)
+            list(APPEND VTK_COMPONENTS IOMPIParallel ParallelMPI hdf5 FiltersParallelDIY2 RenderingCore InteractionStyle RenderingFreeType RenderingOpenGL2)
+        endif()
+
+        # check which modules are available
             foreach(_module ${VTK_COMPONENTS})
+            if(${VTK_MAJOR_VERSION} LESS 9)
                 list (FIND VTK_MODULES_ENABLED ${_module} _index)
+            else()
+                list (FIND VTK_AVAILABLE_COMPONENTS ${_module} _index)
+            endif()
                 if (${_index} GREATER -1)
                     list(APPEND AVAILABLE_VTK_COMPONENTS ${_module})
                 endif()
             endforeach()
-        endif()
 
         # don't check VERSION 6 as this would exclude VERSION 7
         if(AVAILABLE_VTK_COMPONENTS)
```

**Comment by sww1235** [comment]
The python 2 patch is needed, as otherwise cmake tries to look for python 2.7. not quite sure why, but it didn't build without it

**Comment by yopito** [comment]
For easier comparison, my own branch is here: https://github.com/yopito/void-packages/tree/freecad.0.19
(rebuild on my own currently)

> The python 2 patch is needed, as otherwise cmake tries to look for python 2.7. not quite sure why, but it didn't build without it

alternative: `-DPYTHON_EXECUTABLE=/usr/bin/python3`  in `configure_args` 

> I can add the comment to the vtk9 patch if people would like. Felt it was pretty self explanatory.

patch payload been updated on my side, not just recommented ;)

> Where is patch 152 from? Your own build? Fine with including it, but it didn't seem to be needed to build.

yes, It fixes vtk9 module discovery. Will propose upstream once release will happen (no enough time to track their master branch)
 
> I had been using these same exact patches on my branch of void-packages to build the master branch of freecad and had been using it with no problems.

**Comment by yopito** [comment]
update: 0.19.1 to become the official release according to FreeCAD twitter account : 
https://twitter.com/FreeCADNews/status/1372219104627679235

**Comment by sww1235** [comment]
I am happy with closing this in favor of your branch, or integrating both into this pull request. Did wmayer fix the fixme comments in the vtk patch or is that your doing?

**Comment by yopito** [comment]
yes, I will keep maintainership for this release and I will open another PR.  

But thanks for your work on this one, I know how hard it is, and how it's difficult to ensure a good 
Please feel free to contribute, even without maintainership ;)

I'm currently review all changes and perform additional builds and runtime tests to ensure everything is fine.
Regarding vtk patch: I picked it as it is, no change on my own (just removed already the file that was already fixed). This is one I have to review, to see if additional fix is available.

**Comment by sww1235** [comment]
> Closing in favor of #29580

**Pull request closed without merging**
