### PR TITLE
llvm9

### PR DESCRIPTION
**Pull request by q66**
This adds llvm9, strips down llvm8 to a minimum (and updates it to 8.0.1), and bumps a bunch of other packages that should be bumped.

Platform testing:

- [x] x86_64 **[need help]**
- [x] x86_64-musl **[need help]**
- [x] i686 **[need help]**
- [x] ppc64le
- [x] ppc64le-musl
- [x] ppc64
- [x] ppc64-musl
- [x] ppc
- [x] ppc-musl
- [x] aarch64
- [x] aarch64-musl
- [x] armv7l **[need help]**
- [x] armv6l **[need help]**
- [x] armv7l-musl **[need help]**

To bump + test:

- [x] llvm
- [x] libcxxabi
- [x] libcxx
- [x] llvm-libunwind
- [x] libGL
- [x] beignet **[need help, x86 only]**
- [x] libclc-git
- [x] juCi++
- [x] kdevelop
- [x] rtags
- [x] bcc
- [x] ccls
- [x] clazy
- [x] include-what-you-use
- [x] shiboken2
- [x] codelite
- [x] gnome-builder
- [x] bpftrace
- [x] qtcreator
- [x] qt5 **[to be bumped by 5.13.1 update]**

rebuild but not bump (no target llvm/clang dependency):

- [x] ardour
- [x] afl **[need help, x86 only]**
- [x] blender
- [x] firefox
- [x] firefox-esr
- [x] icecat
- [x] thunderbird
- [x] chromium **[need help, won't build here]**
- [x] godot
- [x] ispc **[need help, x86 only]**
- [x] yosys
- [x]  rdedup
- [x]  pijul

Rust will need to be bumped but we'll do that as a part of the upcoming Rust update to avoid building twice.

### CODE REVIEW

**Comment by q66** [comment]
This will need a few more iterations before it at least builds properly on my machine, so wait with testing until I've done so...

**Comment by q66** [comment]
Also switching llvm to py3 while at it.

**Comment by q66** [comment]
py3 transition done, llvm is now buildable... i think testing can begin

**Comment by q66** [comment]
Added patches fixing `llvm-libunwind` on 32-bit ppc and a subtle `libcxx` fix on `ppc*` in general, added a gcc9 miscompilation backport patch for clang

**Comment by leahneukirchen** [comment]
afl: clang-9: error: unknown argument: '-fstack-clash-protection'

**Comment by leahneukirchen** [comment]
ispc works.

**Comment by q66** [comment]
I suspect afl has been broken all along then since `-fstack-clash-protection` is not a thing in clang8 either, AFAIK it's a hardening flag we add ourselves. Beignet will probably need patching.

**Comment by leahneukirchen** [comment]
AFL bump and fix: https://0x0.st/ztdv.diff

**Comment by leahneukirchen** [comment]
Arch uses a Git snapshot for beignet and a llvm8 patch.

**Comment by q66** [comment]
Added `afl` update into the batch...

**Comment by q66** [comment]
Looks like the Arch llvm8 patch should be the one for beignet

**Comment by leahneukirchen** [comment]
```
/builddir/Beignet-1.3.2-Source/backend/src/llvm/llvm_sampler_fix.cpp: In member 
function 'bool gbe::SamplerFix::visitCallInst(llvm::CallInst*)':
/builddir/Beignet-1.3.2-Source/backend/src/llvm/llvm_sampler_fix.cpp:85:53: erro
r: cannot convert 'llvm::FunctionCallee' to 'llvm::Value*' in initialization
```

**Comment by q66** [comment]
As I see it,

```
Value* samplerCvt = M->getOrInsertFunction("__gen_ocl_sampler_to_int", i32Ty, I->getOperand(0)->getType());
```

will need changing to

```
Value* samplerCvt = M->getOrInsertFunction("__gen_ocl_sampler_to_int", i32Ty, I->getOperand(0)->getType()).getCallee();
```

in two places in that file when compiling for llvm9.

**Comment by leahneukirchen** [comment]
FreeBSD has a complete patchset, but I have other things to do right now: https://bz-attachments.freebsd.org/attachment.cgi?id=206326

**Comment by leahneukirchen** [comment]
Chromium built on x86_64.

**Comment by q66** [comment]
Rebased, and dropped qt5 rebuild as it'll be done by the 5.13.1 update: https://github.com/void-linux/void-packages/pull/14701 - beignet still broken for some reason

**Comment by q66** [comment]
Beignet fixed. I think this makes all the packages

**Comment by q66** [comment]
This is ready to land

**Pull request merged**
