### PR TITLE
[WIP] Hedgewars: update to 1.0.0

### PR DESCRIPTION
**Pull request by Anachron**

### CODE REVIEW

**Comment by Anachron** [comment]
Yep I've realized,- thanks. Hope all is well now.

**Comment by Hoshpak** [comment]
I will look into it and see if I can find another workaround

**Comment by Hoshpak** [comment]
Doing it in `pre_configure` works. It also needs `libatomic-devel` to link on i686. With the following patch against your branch I could successfully compile it: https://owncloud.helmut-pozimski.de/index.php/s/kytLeXX7xcb6HFL

**Comment by Anachron** [comment]
I used your patch but it still threw:

`  error: Could not find compiler "clang" in PATH`

I've manually added `clang` to the `hostmakedepends` and rebuild it right now.

**Comment by Hoshpak** [comment]
Could be that clang was still installed at my machine because xbps-src didn't clean up the masterdir. Wouldn't explicitely adding clang to hostmakedepends for i686 fix that?

**Comment by Anachron** [comment]
Thought so too but no success, same error.

**Comment by Hoshpak** [comment]
I just manually removed my i686 masterdir, binary-bootstrapped again and compiled the package with the patch, it compiled just fine. So it looks to me like it works. We can merge this on my own responsibility if you want.

**Comment by Piraty** [comment]
still WIP?

**Comment by Hoshpak** [comment]
merged manually in 740b148aadf065a7f602f36c2df3cf0c23555966

**Pull request closed without merging**
