### PR TITLE
[DONOTMERGE] Samba: Update to 4.11.2

### PR DESCRIPTION
**Pull request by Anachron**
WIP.

Compiles but throws

```
samba: error while loading shared libraries: libldbsamba-samba4.so: cannot open
shared object file: No such file or directory
```

### CODE REVIEW

**Comment by SirFerdek** [comment]
I am also working on updating samba to 4.x, but without bundling libraries - they also need updating in the repository. Bundling is anti-pattern when you build distribution. I have Samba's dependencies sorted out in 95% in terms of compilation (with fixes for cross compilation and musl included).

I will post pull request soon. Santa's coming!

**Comment by SirFerdek** [comment]
BTW: how do I handle dependencies in form of dynamic libraries in /usr/lib which are part of python bindings? Like, how to package something like libpyldb-util.cpython-36m-x86-64-linux-gnu.so.2 without adding it to common/shlibs?

**Comment by SirFerdek** [comment]
Anyone interested in helping, please take a look at PR #17544

**Comment by Anachron** [comment]
Closing, will reopen as samba-4.12.0 once finished packaging locally.

**Pull request closed without merging**
