### PR TITLE
linux4.17: rebuild for libressl-2.8.

### PR DESCRIPTION
**Pull request by jnbr**
[ci skip]

### CODE REVIEW

**Comment by Vaelatern** [comment]
Does the linux kernel link ssl now? Can't find evidence of that with a quick `xbps-query`.

**Comment by Hoshpak** [comment]
It's not the kernel itself, the kernel headers packae contains the `extract-cert` binary which links against libcrypto.so. However I wonder if it's really worth rebuilding this kernel version since it's EOL so it could just be removed from the repository instead.

**Comment by archfan** [comment]
It's EOL. Why not just remove it?

**Comment by jnbr** [comment]
#5367

**Pull request closed without merging**
