### PR TITLE
unbound: Move libunbound.so.8 to a sub-package

### PR DESCRIPTION
**Pull request by zdykstra**
This is a first try at resolving #19445 . Do I need to bump any other packages that depend on this?

### CODE REVIEW

**Comment by Hoshpak** [comment]
The template changes look good, the following packages need to be revbumped:

```
getdns
gnutls
monero
monero-gui
```

You can check for shlib dependencies with `xrevshlib` from the `xtools` package. Please also adjust the git commit title to fit into the usual scheme.

**Comment by xtraeme** [comment]
Please fix the commit message

**Comment by zdykstra** [comment]
When I revbump the four packages that need the shared library, how do I format each commit message? Do I also tack all four additional commits to this PR?

**Comment by qfwqqtemp** [comment]
Thank you!

**Comment by zdykstra** [comment]
Pulled out my revbumps for the four packages that depend on this. I'm missing something here, as the [build failed](https://travis-ci.org/void-linux/void-packages/jobs/655872666#L1481)

**Comment by qfwqqtemp** [comment]
@zdykstra 
```MISSING: libunbound>=2```
Somehow depedency checked only against revision.

**Comment by zdykstra** [comment]
> @zdykstra
> `MISSING: libunbound>=2`
> Somehow depedency checked only against revision.

I know, that's why I linked that exact line :)

**Comment by zdykstra** [comment]
Just to document the solution, the first depends line I submitted was:

`depends="libunbound>=$version_${revision} libressl-devel libevent-devel"`

The second was:

`depends="libunbound>=${version}_${revision} libressl-devel libevent-devel"`

$version_ is an undefined.

**Comment by qfwqqtemp** [comment]
https://travis-ci.org/void-linux/void-packages/builds/655938516
Looks like everything good.

**Pull request merged**
