### PR TITLE
skalibs: update to 2.7.0.0.

### PR DESCRIPTION
**Pull request by maxice8**
I'm orphaning the invalid maintainer, if the person in question wants to keep maintaining the packages drop a proper maintainer field here

### CODE REVIEW

**Comment by maxice8** [comment]
request for review from maintainer @lemmi @opsaaspo

**Comment by maxice8** [comment]
Here are the file changes

```
>>> execline-devel
>>> execline-doc
>>> execline
>>> s6-portable-utils-doc
>>> s6-portable-utils
>>> s6-rc-doc
>>> s6-rc
>>> s6-linux-utils-doc
4d3
< /usr/share/doc/s6-linux-utils/s6-devd.html
14,15d12
< /usr/share/doc/s6-linux-utils/s6-uevent-listener.html
< /usr/share/doc/s6-linux-utils/s6-uevent-spawner.html
>>> s6-linux-utils
2d1
< /usr/bin/s6-devd
12,13d10
< /usr/bin/s6-uevent-listener
< /usr/bin/s6-uevent-spawner
>>> s6-networking-devel
>>> s6-networking-doc
>>> s6-networking
>>> s6-dns-devel
>>> s6-dns-doc
>>> s6-dns
>>> skalibs-doc
>>> skalibs-devel
42d41
< /usr/include/skalibs/mininetstring.h
83c82
< /usr/lib/libskarnet.so -> /usr/lib/libskarnet.so.2.6
---
> /usr/lib/libskarnet.so -> /usr/lib/libskarnet.so.2.7
>>> skalibs
1,3c1,3
< /usr/lib/libskarnet.so.2.6 -> /usr/lib/libskarnet.so.2.6.4
< /usr/lib/libskarnet.so.2.6.4 -> /usr/lib/libskarnet.so.2.6.4.0
< /usr/lib/libskarnet.so.2.6.4.0
---
> /usr/lib/libskarnet.so.2.7 -> /usr/lib/libskarnet.so.2.7.0
> /usr/lib/libskarnet.so.2.7.0 -> /usr/lib/libskarnet.so.2.7.0.0
> /usr/lib/libskarnet.so.2.7.0.0
```

**Comment by lemmi** [comment]
No complains from me - s6-{dns,networking} are more or less just version bumps themselves.

**Comment by maxice8** [comment]
On Thu, Aug 16, 2018 at 08:33:44AM -0700, lemmi wrote:
> No complains from me - s6-{dns,networking} are more or less just version bumps themselves.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/1827#issuecomment-413587108

There is the possibility of adding nsss http://skarnet.org/software/nsss/index.html support to s6-networking

**Comment by lemmi** [comment]
My guess it that enabling nsss shouldn't interfere with anything unless someone actually enables the daemon. So I'd be fine with enabling it.

**Comment by maxice8** [comment]
On Thu, Aug 16, 2018 at 08:46:43AM -0700, lemmi wrote:
> My guess it that enabling nsss shouldn't interfere with anything unless someone actually enables the daemon. So I'd be fine with enabling it.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/1827#issuecomment-413591803

Ok i'll enable it after i finish packaging piper (see libratbag PR)

**Comment by maxice8** [comment]
@lemmi can you take a look into disabling registered user requirement in #xbps ? i don't have irc access in my uni and i need to use riot.im as a bridge.

**Comment by lemmi** [comment]
@maxice8 i passed it to @Gottox, I don't have op myself.

**Comment by lemmi** [comment]
@maxice8 you can join now.

**Pull request closed without merging**
