### PR TITLE
element-desktop: update to 1.8.4.

### PR DESCRIPTION
**Pull request by teldra**
#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (x68_64-glibc)

https://matrix.org/blog/2021/09/13/vulnerability-disclosure-key-sharing

Important security fix

### CODE REVIEW

**Comment by ericonr** [comment]
Yay it's now back to segfaulting on musl. Not sure how to proceed.

**Comment by teldra** [comment]
> Yay it's now back to segfaulting on musl. Not sure how to proceed.

I made element now depended on electron13 and it runs on x68_64-glibc. Maybe this cures the segfault on musl? Can you check that, @ericonr ?

**Comment by q66** [comment]
why did you change the `do_build`?

**Comment by teldra** [comment]
> why did you change the `do_build`?

Because of this ```ERROR: element-desktop-1.8.4_1: do_build: 'yarn run build:native' exited with 1```, I tried without ```:native``` full of hope, that it works on all arches, @q66.
The same for the ```:64``` and ```:32```
I am open to suggestions..

**Pull request closed without merging**
