### PR TITLE
Build kernels reproducibly

### PR DESCRIPTION
**Pull request by Piraty**
https://www.kernel.org/doc/html/v5.9/kbuild/reproducible-builds.html

[ci skip]

### CODE REVIEW

**Review by fosslinux — APPROVED** [review]

**Comment by Piraty** [comment]
even better to export those on toplevel i think?

**Comment by ericonr** [comment]
Can these be exported as environment variables or do you need to put them in front of make?

**Comment by Piraty** [comment]
export should work

> Can these be exported as environment variables or do you need to put them in front of make?

can be exported. appears more pretty to me, will push a modified version

**Comment by Piraty** [comment]
updated, now exporting on global scope

**Comment by pullmoll** [comment]
Perhaps you can combine this #26882 request with the update?

**Comment by Piraty** [comment]
a8f8e9ad6d65fb67809599f5ca518f9bfbb9c64b
164733c28b4003f455b01799c0dff8e874a0fb56
a3da4905fcac41a415583d4c7019607376cc02ac
70cffc3aa95bf0d2610a9401c5caac3686ba82ad
66cdf165862ecd9844b0df1c3c7c938a0aae3a83
81b42ca88be353d4b8d112d6ab381821d875f443

**Pull request closed without merging**
