### PR TITLE
cargo-edit: update to 0.12.0.

### PR DESCRIPTION
**Pull request by icp1994**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture: **x86_64**

### CODE REVIEW

**Comment by classabbyamp** [comment]
what's the different between cargo's `cargo add` and cargo-edit's `cargo add`

**Comment by icp1994** [comment]
Nothing, was merged in cargo long time ago.

**Comment by classabbyamp** [comment]
it's no longer linking to libgit2: https://github.com/void-linux/void-packages/actions/runs/5219079314/jobs/9420509876?pr=44104#step:9:51

**Comment by icp1994** [comment]
No idea why it's building the vendored code. It worked last time https://github.com/void-linux/void-packages/actions/runs/5039350583/jobs/9037435880?pr=44020#step:7:1071

I wish they would just merge https://github.com/rust-lang/git2-rs/pull/939 - would make life easier.

**Comment by classabbyamp** [comment]
integrated into #43435

**Pull request closed without merging**
