### PR TITLE
yt-dlp: fix depends

### PR DESCRIPTION
**Pull request by icp1994**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture: **x86_64**

### CODE REVIEW

**Review by sgn — APPROVED** [review]
Seems to be correct based on `requirements.txt`

**Comment by dmarto** [comment]
```
Python versions 3.7+ (CPython and PyPy) are supported. Other versions and implementations may or may not work correctly.

While all the other dependencies are optional, ffmpeg and ffprobe are highly recommended
```

From [their README](https://github.com/yt-dlp/yt-dlp#dependencies)

**Comment by icp1994** [comment]
That's fair but as you can see upstream implicitly [enforces](https://github.com/yt-dlp/yt-dlp/blob/2023.03.04/setup.py#L146) these [dependencies](https://github.com/yt-dlp/yt-dlp/blob/2023.03.04/setup.py#L30). You can check it by looking at `/usr/lib/python3.11/site-packages/yt_dlp-2023.3.4-py3.11.egg-info/requires.txt`.

Also from their README
> The standalone release binaries are built with the Python interpreter and the packages marked with * included.

so I guess we have to patch it ourselves if we want a dependency-free installation like [gentoo](https://bugs.gentoo.org/828466) does.

**Comment by dmarto** [comment]
I am not sure what you mean as I have `yt-dlp` and none of the python dependencies, I only have `ffmpeg` and `no_Cryptodome-None, sqlite3-2.6.0`; not sure with all the no/none in the version info, but cryptodome, I think, is the only bundled thing `/usr/lib/python3.11/site-packages/yt_dlp/dependencies/Cryptodome.py` as I don't have anything other by that name on my system. 


yt-dlp --verbose
```
[debug] Command-line config: ['--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.12_1-x86_64-with-glibc2.36 (OpenSSL 1.1.1t  7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 4.4.3 (setts), ffprobe 4.4.3
[debug] Optional libraries: no_Cryptodome-None, sqlite3-2.6.0
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[debug] Loaded 1786 extractors
```

p.s. I often use yt-dlp but only for simple video+audio download. So not sure where this optional dependencies are needed, but `yt-dlp` documentation claims that if they are needed your receive a warning and I have never seen one.

**Comment by icp1994** [comment]
What are the outputs of `xbps-query -x yt-dlp` and `pip3 check` in your machine?

**Comment by dmarto** [comment]
```
$ xbps-query -x yt-dlp
python3>=0
```

and I don't have pip installed (or other global packet mangers), all global stuff is left to xbps (around 40 python3-* pkgs)

**Comment by paper42** [comment]
yt-dlp can be used for downloading from many websites, some require more than what's provided by the standard python library and ffmpeg, but those are optional dependencies and most users won't need them. I don't think we should provide these dependencies in the package, yt-dlp should provide a good error message when they are needed and missing.

**Pull request closed without merging**
