### PR TITLE
pipewire: update to 0.3.32

### PR DESCRIPTION
**Pull request by st3r4g**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
```
[353/592] Compiling C object src/modules/libpipewire-module-rtkit.so.p/module-rtkit.c.o
../src/modules/module-rtkit.c: In function '_gettid':
../src/modules/module-rtkit.c:186:17: warning: implicit declaration of function 'gettid'; did you mean '_gettid'? [-Wimplicit-function-declaration]
  186 |  return (pid_t) gettid();
      |                 ^~~~~~
      |                 _gettid
```

**Comment by ericonr** [comment]
Breaks build on musl; we could do `inline int gettid() { return syscall(SYS_gettid);}`

**Comment by ericonr** [comment]
Or just the patch in https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1422

**Comment by st3r4g** [comment]
Added your patches, thanks

**Pull request merged**
