### PR TITLE
WIP: anki: update to 2.1.26

### PR DESCRIPTION
**Pull request by fosslinux**
This has a wide variety of changes as if you have heard my ranting in #xbps it has turned into a Bad Build System - there is rust, nodejs, python, etc etc, no proper install target...

A few things to note:

- python3-mypy is updated as mypy-protobuf needs the new version, otherwise the build failed.
- same thing with python-protobuf, but for anki and at runtime
- maturin is some weird build system at the intersection of rust and python.
- mypy-protobuf-python is what anki uses for binding python and rust together, partly.
- mypy-protobuf-go is the go implementation of mypy-protobuf-python that I thought should be packaged anywway.
- python-stringcase is a new dependency.
- anki is an archd package (not nocross), because the rust code is obviously platform specific.

Still todo:

- [x] Apply archlinux's aqt_build patch, which stops it from polluting /usr directly (:vomiting_face:)
- [x] Update python3-protobuf - hopefully will fix `AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'`.
- [x] Look into travis musl error. https://github.com/rust-lang/rust/issues/40174. Hopefully, using rust 1.44 as the rust version *should* fix this. What a PITA. I understand that this is because it works when I cross-compile to x86_64-musl from x86_64 but we need it to work native build from x86_64-musl for the builders...
- [x] Get off rustup and onto rust stable. Needs either a) pyo3 to work on stable or b) anki to be patched for rust-cpython.
- [x] Blocked by rust 1.44. Blocked by #22739
- [ ] Travis wth on i686?
- [x] Make it open.
- [x] More extensive runtime testing.
- [ ] Runtime test on musl.

### CODE REVIEW

**Comment by fosslinux** [comment]
I have been using this for the past few hours, it now runs. Don't know if musl will work this time, if it dosen't I'll need to go through nightlys into I find one that builds, one of the crates doesn't build for the newest nightly.

**Comment by fosslinux** [comment]
Well, we can hardly have packages on rust nightly, as I have come to believe after a discussion on IRC, and especially not using rustup.

Luckily I found a patchset for pyo3!

So now it builds on rust stable. Now, this is just waiting on rust 1.44 to come out.

**Comment by fosslinux** [comment]
@stpx Since this has pretty much morphed into a different, much more complex package, would you mind if I took maintainership of this package?

**Comment by stpx** [comment]
Yes

**Comment by fosslinux** [comment]
@q66 maturin (build system anki uses) currently does not support ppc64le (the only ppc* that anki could build on anyway because of webengine). Would you like to block merging this while I get a patch that will fix that on maturin or can we merge this and come back to that later (soonish)?

**Comment by q66** [comment]
why doesn't it?

**Comment by fosslinux** [comment]
After chatting with q66 on irc, figured out I need to patch maturin for musl and ppc.  *sigh*

**Comment by ericonr** [comment]
@fosslinux we supposedly have working maturin in repos now, if you want to try it again?

**Comment by sgn** [comment]
The situation has been changed. Last I check, anki has been moved to bazel, which is another monster.

**Pull request closed without merging**
