### PR TITLE
discord-ptb: update to 0.0.18

### PR DESCRIPTION
**Pull request by fhnxqtsd97wxn**

### CODE REVIEW

**Comment by classabbyamp** [comment]
Not sure how to get the license check to pass for proprietary :woman_shrugging:

**Comment by Piraty** [comment]
use `license="custom:Proprietary"`

**Comment by classabbyamp** [comment]
No license file is included with this software (re: no vlicense)

**Comment by Piraty** [comment]
no idea how to proceed in that case

**Comment by xtraeme** [comment]
If I were the void dictator again I'd do rm -rf *all_restricted_pkgs*

**Comment by Chocimier** [comment]
Removing all restricted packages would only induce adoption of unofficial repos.

Yet I would back up raising requirements mildly to have checksummable license, removing packages that do not have license and turn INSTALL-driven packages like `oracle-jre` to either normal or restricted.

**Comment by abenson** [comment]
Void already has stable `discord`, do we want an alpha/beta branch?

**Comment by Piraty** [comment]
no

**Comment by Chocimier** [comment]
As said above, we do not accept unstable releases.

**Pull request closed without merging**
