### PR TITLE
[waiting on up to date rust] gitui: update to 0.15.0

### PR DESCRIPTION
**Pull request by UsernameRandomlyGenerated**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by FollieHiyuki** [comment]
It will build fine. Just need to wait for `rust` to be updated.

**Comment by UsernameRandomlyGenerated** [comment]
I know, I've changed the title so I won't forget to repush.

**Comment by ericonr** [comment]
Ping :)

**Comment by sgn** [comment]
Move to #31814

**Pull request closed without merging**
