### PR TITLE
nyxt: fix dependencies

### PR DESCRIPTION
**Pull request by egorenar**
* Remove unneeded dependencies
  - curl
  - pkg-config
  - sqlite (bookmarks stored as s-exps now)
  - openssl-devel

* Add runtime dependency libfixposix-devel

Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {1000FB0103}>:
  Error opening shared object "libfixposix.so":
  libfixposix.so: cannot open shared object file: No such file or directory.

* Add enchant2 dependency for spell checking

Signed-off-by: Alexander Egorenkov <egorenar-dev@posteo.net>

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by Chocimier** [comment]
openssl-devel does not seem to be needed

**Comment by ericonr** [comment]
Can't it use enchant2? I'd like to remove enchant at some point.

**Comment by egorenar** [comment]
> Can't it use enchant2? I'd like to remove enchant at some point.

It works with enchant2 too. Replaced as requested.

**Comment by Chocimier** [comment]
> sqlite (bookmarks stored as s-exps now)

Does that mean that people won't be able to open their bookmarks after update?

**Comment by egorenar** [comment]
> > sqlite (bookmarks stored as s-exps now)
> 
> Does that mean that people won't be able to open their bookmarks after update?

Sorry for confusion, but no. SQLite is used no more in Nyxt. Bookmarks were stored in an sqlite db before but since a couple of Nyxt releases, bookmarks are store in a LISP file as S-EXPs.

**Comment by egorenar** [comment]
> > sqlite (bookmarks stored as s-exps now)
> 
> Does that mean that people won't be able to open their bookmarks after update?

SQLite is not used since version 1.3.3, so ages ago.

**Comment by ericonr** [comment]
Fixes #31323, right?

@Chocimier good to go?

**Comment by egorenar** [comment]
> Fixes #31323, right?
> 
> @Chocimier good to go?

It fixes the runtime problem with libfixposix-devel.
Not sure about gst-libav, it works w/o for me. I think webkit should depend on any audio/video playing because
webkit is resposnsible for HTML rendering.

**Pull request merged**
