### PR TITLE
New package: flavours-0.6.1

### PR DESCRIPTION
**Pull request by Newchair2644**
#### Testing the changes
- I tested the changes in this PR: YES

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): YES

#### Local build testing
- I built this PR locally for my native architecture, (x86_64, glibc)

### CODE REVIEW

**Comment by Newchair2644** [comment]
On my machine, I did run xlint on the first commit that used `$wrksrc`, but it didn't catch any errors. I ran `xlint srcpkgs/flavours/template` and `common/travis/xlint.sh srcpkgs/flavours/template`, but neither caught the mistake. My `master` branch was up to date with upstream. Please let me know what I am doing wrong, would appreciate (this is my first package). Thank you!

**Comment by paper42** [comment]
CI uses the newest xlint, on your system you probably have the xlint from the last xtools release.

**Comment by paper42** [comment]
please squash the commits

**Comment by Newchair2644** [comment]
I made a mess! Sorry I know you have better things to do than teach me how to git but I'm not sure how to do this. I tried to run `git rebase -i HEAD~2` but it gave me this output:
```
error: cannot 'squash' without a previous commit
You can fix this with 'git rebase --edit-todo' and then run 'git rebase --continue'.
Or you can abort the rebase with 'git rebase --abort'.
```
So for some reason I decided it was a good idea to merge `master` and this was the result. Sorry about this!

**Comment by Newchair2644** [comment]
Okay so I reverted the branch back to my last commit with `git reset 1aaa6853bb8363cb5d7917ee86074683f8882c7b` and `git push --force` but I am still getting the same error when I try to squash the commits.

**Comment by Newchair2644** [comment]
Nevermind I figured it out. I was using `squash` on both commits when I should have been using `pick` on the first commit and `squash` on the second.

**Comment by Newchair2644** [comment]
Is there anything preventing this PR from being merged? I noticed it has become stale.

**Comment by paper42** [comment]
from me, my lack of interest in this package, but I can't speak for other maintainers

**Comment by Anachron** [comment]
I am using this package for a week now without issues.
In fact, I believe the quality should suffice to be included.

**Pull request merged**
