### PR TITLE
New package: macchina-0.9.2

### PR DESCRIPTION
**Pull request by machadofguilherme**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by Chocimier** [comment]
> In particular, new themes are highly unlikely to be accepted

**Comment by machadofguilherme** [comment]
> > In particular, new themes are highly unlikely to be accepted

That's not a theme. You closed this PR without even checking the content.

**Comment by q66** [comment]
it's <yet another of the many tools to help make fancy screencaps> so it might as well be the same thing

**Comment by eoli3n** [comment]
That's not just to make "fancy screenshots". It could be a kind of mix between conky and neofetch to run it at each login on servers for exemple. To get useful informations, like available upgrades, zfs pool storage percent, etc...
I asked the dev, he liked the idea : https://github.com/Macchina-CLI/macchina/issues/105

So, please reconsider this, I would co-maintain it.
ping @q66 @Chocimier

**Comment by q66** [comment]
just install it with cargo if you want it, that's what rust people want you to do anyway

**Comment by eoli3n** [comment]
python packages needs pip, ruby needs gems, but we wrap those.
If I would compile the package myself, I would use Gentoo.

```bash
void-packages/srcpkgs on master  
➜ grep -ri 'build_style=cargo' | wc -l
134
```

**Comment by grtcdr** [comment]
@q66 So the package was rejected because it mimics other similar programs?

The open source community has been making clones of everything since its inception, but it would be nice if you considered what macchina does differently from its alternatives before quickly dismissing it.

**Comment by q66** [comment]
FWIW, considering rust's overall hostility against distribution packaging (no way to manage dependencies outside of cargo, no dynamic linking of rust libraries, no reasonable way to control fetching of distfiles and so on) i believe the majority of these other rust programs in the repository shouldn't have been packaged either (other distributions in general do not package them)

if there's something we definitely do not need, it's a multitude of *fetch programs that all serve the purpose of making fancy screenshots for /r/unixporn

also fwiw, a program with 158 dependencies and 7.5MB binary size can hardly be considered minimalistic (and regardless of the functionality it implements, it's ridiculous for a *fetch program) and literally noone cares about whether a fetch takes 10ms or 150ms (not to mention that benchmarking against what is literally a shell script - neofetch - is pretty amusing)

so yeah, i still don't see a reason to package every single rust program under the sun especially considering the rust project seemingly does not care for providing reasonable means of packaging them

**Comment by grtcdr** [comment]
I just read the quality requirements for a package to be accepted, and with all due respect, I don't see how your subjective opinion on the matter is a criteria that must be met.

You seem to have a problem with Rust in general, and I really can't help you with that.

**Comment by ahesford** [comment]
It should be exceedingly obvious that getting subjective approval for a new package from at least one member with the authority to approve pull requests is a criterion that must be met. This package failed to gain that approval. At least three project members agree that the value of this package is offset by the maintenance burden. This matter is closed.

**Comment by Chocimier** [comment]
macchina really advertises itself like nothing more than uname's theme (and new themes are not accepted). libmacchina may be nice but is not build by that template, and has no known consumers. Running arbitrary command is not yet there. Add some killer feature to it and come back.

**Pull request closed without merging**
