### PR TITLE
New packages: intel-compute-runtime-bin-21.18.19737_1 and intel-graphics-compiler-bin-1.0.7181_1

### PR DESCRIPTION
**Pull request by mithodin**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

These packages are required to have opencl support for newer intel graphics cards (e.g. UHD Graphics 620) which are not supported by beignet. The templates are based on these arch linux packages:
https://aur.archlinux.org/packages/intel-graphics-compiler-bin/
https://aur.archlinux.org/packages/intel-compute-runtime-bin/

### CODE REVIEW

**Comment by ericonr** [comment]
These packages can be built from source, as seen in #21855

If you want to base yourself off of that PR and update all the packages, we can merge this.

**Comment by ericonr** [comment]
But using the binary packages is not an option, sorry.

**Comment by mithodin** [comment]
Sadly, the docs to build from source are quite lacking... but I'll give it a shot.

**Comment by ericonr** [comment]
There is a working PR already (which I linked). It just needs to be updated.

**Comment by ericonr** [comment]
I will be closing this for now because we aren't interested in binary packages. If you want to build from source, check out https://github.com/void-linux/void-packages/pull/21855#issuecomment-843725307 and try to fix it, I'm not sure how to proceed...

**Pull request closed without merging**
