### PR TITLE
Gnustep 1.28

### PR DESCRIPTION
**Pull request by abenson**

### CODE REVIEW

**Comment by RoundDuckKira** [comment]
is there a possiblity that before this pull request is approved that I can base my pull request for PikoPixel (https://github.com/void-linux/void-packages/pull/21185) on this? Or should I wait until this is approved by the Void maintainers and devs?

**Comment by RoundDuckKira** [comment]
@abenson could I merge PikoPixel with your contributions or should I wait for them to arrive before I can test things with your pull-request

**Comment by abenson** [comment]
No, yours should block until this is merged. They shouldn't be combined, as they are separate efforts.

For what its worth, I have tested [PikoPixel](https://i.imgur.com/o8uDBYz.png) with the fixed and updated gnustep-gui.

**Comment by RoundDuckKira** [comment]
> No, yours should block until this is merged. They shouldn't be combined, as they are separate efforts.
> 
> For what its worth, I have tested PikoPixel with the fixed and updated gnustep-gui, and the icons displayed correctly.

oh alright! I'm still new at this entire thing anyways. Thanks for testing out the package though and seeing that it works fine though :+1: :smiley:

**Comment by abenson** [comment]
Travis is a lying liar. I swear it builds!

**Comment by RoundDuckKira** [comment]
> Travis is a lying liar. I swear it builds!

it says it builds on all platforms except x86_64 musl

is there a way to re-run compilation to test out that platform again?

**Comment by abenson** [comment]
I could trigger travis again, but it failed because it ran out of time.

**Pull request merged**
