### PR TITLE
krita: update to 4.3.0

### PR DESCRIPTION
**Pull request by kartikynwa**
#### EDIT

1. The error message doesn't prevent Krita functioning in any way. Appeared in 4.2.9 as well. Krita detects the `sip` module in `python3-sip-PyQt5` without issues.
2. The only file affected by `python_version` is the highlighter in Scripter tool and it works with `3`.
---

Some problems:

1. On startup, I get this error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sip'
```
But Python plugins included with Krita still work. This message goes away if `python3-sip` is installed. Advice for testing appreciated.

2. `python_version` was earlier set to `2` which I found strange since Python 2 isn't a dep and is being deprecated. I changed it to `3` and the highlighter in the scripter seems to work. If anyone has any input, it would be sweet.

3. musl patch not tested. Will do it soon.

### CODE REVIEW

**Comment by kartikynwa** [comment]
> I would have `python3-sip` as a `depends`, but I don't know if there are any issues with that.

The appimage ships with files provided by `python-PyQt5-devel`. I have asked at the forum and IRC what those files are for. Once I get an answer making a decision should be easy.

**Comment by kartikynwa** [comment]
> I would have `python3-sip` as a `depends`, but I don't know if there are any issues with that.

In the appimage, the module `sip` is provided by `usr/lib/python3.8/site-packages/PyQt5/sip.so`. In Void Linux, this file comes with the package `python3-sip-PyQt5`. Still for some reason Krita doesn't detect it. Could be related to make flags or something like that.

**Comment by ericonr** [comment]
If installing the `sip` package at runtime isn't working, you could try adding it as a build dep.

**Comment by kartikynwa** [comment]
> If installing the `sip` package at runtime isn't working, you could try adding the devel version as a build dep.

Installing `python3-sip` stops the error message. But plugins work without it. In the scripter, if I do:

```
import sip
print(sip__file__)
```
It points to the correct path as provided by `python3-sip-PyQt5`. Maybe the message isn't problematic at all.

**Pull request closed without merging**
