### PR TITLE
biber: update to 2.18.

### PR DESCRIPTION
**Pull request by eljamm**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)
- I built this PR locally for these architectures :
  - armv6l (cross)
  - armv6l-musl (cross)

### CODE REVIEW

**Comment by eljamm** [comment]
I've been too rash. The update is needed for `texlive2022-bin`, but this should wait until `texlive` is updated.

**Comment by eljamm** [comment]
The test failure on i686 is harmless, according to https://github.com/plk/biber/issues/349#issuecomment-729542667

**Comment by sabrinasomething** [comment]
This is incompatible with the currently used BibLaTeX version. see #42251

**Comment by leahneukirchen** [comment]
I reverted it for now. @eljamm please next time mark the PR as draft or change the title to "DO NOT MERGE" if you notice merging it would break anything.

**Comment by eljamm** [comment]
My apologies, I'll be more careful next time.

**Pull request merged**
