### PR TITLE
bfs: update to 2.6.2.

### PR DESCRIPTION
**Pull request by daniel-eys**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by daniel-eys** [comment]
Testsuite passed in my local build, but fails in CI. Will investigate.

**Comment by tavianator** [comment]
I accidentally broke the support for running the tests as root.  Fixed in https://github.com/tavianator/bfs/commit/0c0cbfbc27491dc5a92d875e1a88d2c9ddae2f0b, but I'd recommend not running as root if you can help it.

**Comment by tavianator** [comment]
You can also work around it with `export BFS_TRIED_DROP=""`

**Comment by daniel-eys** [comment]
CI passed now, thanks @tavianator

**Pull request merged**
