### PR TITLE
WIP: Slant

### LINKED ISSUE #4376: Package request: slant
Just found this today and I totally want to have it.

Source: https://github.com/kristapsdz/slant
Homepage: https://kristaps.bsd.lv/slant/

`a minimal open source system monitor for remote UNIX machines `

### PR DESCRIPTION
**Pull request by Anachron**
Closes #4376

Fails for now with

```
/usr/bin/ld: db.o: in function `db_trans_open':
/builddir/slant-0.0.21/db.c:175: undefined reference to `sqlbox_trans_deferred'
/usr/bin/ld: /builddir/slant-0.0.21/db.c:173: undefined reference to `sqlbox_trans_immediate'
/usr/bin/ld: /builddir/slant-0.0.21/db.c:171: undefined reference to `sqlbox_trans_exclusive'
/usr/bin/ld: db.o: in function `db_trans_rollback':
/builddir/slant-0.0.21/db.c:185: undefined reference to `sqlbox_trans_rollback'
/usr/bin/ld: db.o: in function `db_trans_commit':
/builddir/slant-0.0.21/db.c:194: undefined reference to `sqlbox_trans_commit'
/usr/bin/ld: db.o: in function `db_logging_data':
/builddir/slant-0.0.21/db.c:202: undefined reference to `sqlbox_msg_set_dat'
/usr/bin/ld: db.o: in function `db_open_logging':
/builddir/slant-0.0.21/db.c:245: undefined reference to `sqlbox_role_hier_alloc'
/usr/bin/ld: /builddir/slant-0.0.21/db.c:251: undefined reference to `sqlbox_role_hier_sink'
/usr/bin/ld: /builddir/slant-0.0.21/db.c:253: undefined reference to `sqlbox_role_hier_start'
/usr/bin/ld: /builddir/slant-0.0.21/db.c:255: undefined reference to `sqlbox_role_hier_src'
/usr/bin/ld: /builddir/slant-0.0.21/db.c:260: undefined reference to `sqlbox_role_hier_stmt'
/usr/bin/ld: /builddir/slant-0.0.21/db.c:262: undefined reference to `sqlbox_role_hier_stmt'
/usr/bin/ld: /builddir/slant-0.0.21/db.c:264: undefined reference to `sqlbox_role_hier_stmt'
...
```

### CODE REVIEW

**Comment by Anachron** [comment]
Yo guys, I need help here.

**Comment by avoidr** [comment]
musl builds need `sys/queue.h`, which I managed to satisfy with `musl-legacy-compat`.

**Comment by avoidr** [comment]
If I am glancing correctly, sqlbox doesn't build a shared library, so linking dynamically fails. I'd try to link that library into slant statically.

**Comment by abenson** [comment]
Looks like slant didn't use sqlbox until 0.0.24. Updating to that lets it build for me. Also need to add `-ldl` for `LDADD_SLANT_CGI`. Also need to fix the install target.

**Comment by Anachron** [comment]
I'm working on this (again) but I have trouble figuring out where to put the `-ldl` flag because I've seen a lot of different approaches all inside the void-packages tree.

**Pull request closed without merging**
