### PR TITLE
mesa: update to 24.2.6

### PR DESCRIPTION
**Pull request by SpidFightFR**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x64-GlibC)

### CODE REVIEW

**Comment by onlylunix** [comment]
Mesa 24.2.6 released

**Comment by SpidFightFR** [comment]
> Mesa 24.2.6 released

Done.

**Comment by onlylunix** [comment]
Mesa 24.2.7 released, bro

**Comment by SpidFightFR** [comment]
@onlylunix https://github.com/void-linux/void-packages/pull/53050

**Pull request merged**
