### PR TITLE
New package: hakuneko-desktop-6.1.7

### PR DESCRIPTION
**Pull request by machadofguilherme**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by FollieHiyuki** [comment]
Try to build from source if you can.

**Comment by machadofguilherme** [comment]
> Try to build from source if you can.

I tried it in the first place, but I recognize that it is beyond my knowledge. =/
However, after using this method I can say that it is working perfectly here.

**Comment by machadofguilherme** [comment]
> If you want this package to be included into the main repo eventually, it has to be built from source.
> 
> And yes Electron apps are PITA to build xD You can check out templates of other Electron based packages (`vscode` or `element-desktop`).

As it is, would it be possible to merge only void-packages? I appreciate the attention. =3

**Comment by q66** [comment]
nope, you'll have to build it from source

**Pull request closed without merging**
