### PR TITLE
New package: ttop-1.5.3

### PR DESCRIPTION
**Pull request by inv2004**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-libc and armv6l)

### CODE REVIEW

**Comment by abenson** [comment]
What are you trying to do here?

**Comment by inv2004** [comment]
@abenson probably you saw I added submodule by mistake, I fixed few secs ago

**Comment by abenson** [comment]
1. Don't PR from master on your fork, this is going to cause issues down the road, and I'm betting that's what happened to your last PR.
2. The commit message needs to be fixed. It should be "New package: ttop-1.5.3". This is separate from the PR title, which is mostly irrelevant.
3. Your first time contribution is your own project?
4. See my other issues for other fixes before I'll consider running this on CI.

**Comment by abenson** [comment]
This is the issue I was talking about PRing from master. Create a branch and PR from that.

**Pull request closed without merging**
