### PR TITLE
firefox-esr: update to 91.6.0.

### PR DESCRIPTION
**Pull request by tibequadorian**
[ci skip]

Required for #34448

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-musl (crossbuild)
  - x86_64-musl
  - armv7l (crossbuild)
  - i686

### CODE REVIEW

**Comment by KSPAtlas** [comment]
Why was the check skipped?

**Comment by tibequadorian** [comment]
@KSPAtlas https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#continuous-integration

**Comment by KSPAtlas** [comment]
So this should be OK to merge!

**Comment by tibequadorian** [comment]
@Duncaen

**Pull request merged**
