### PR TITLE
spotify-player: update to 0.20.4.

### PR DESCRIPTION
**Pull request by xavierfortier1**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, **x86_64-glibc**
- I built this PR locally for these architectures: 
  - **armv7l (crossbuild)**
  - **armv6l-musl (crossbuild)**

@mdkcore0

### CODE REVIEW

**Comment by mdkcore0** [comment]
Yeah, already tried to build it several times locally here, but armv7l stil failing. Seems it has something to do with disabling lto, but don't have time to take a deep look before the end of the year :/

**Comment by classabbyamp** [comment]
add `cmake` to `hostmakedepends`?

**Comment by mdkcore0** [comment]
@classabbyamp tried it too, it will tell you about rust-bindgen, and finally will fail while invoking it:

```
./xbps-src -a armv7l pkg spotify-player
=> xbps-src: updating repositories for host (x86_64)...
[*] Updating repository `https://repo-fastly.voidlinux.org/current/bootstrap/x86_64-repodata' ...
[*] Updating repository `https://repo-fastly.voidlinux.org/current/x86_64-repodata' ...
[*] Updating repository `https://repo-fastly.voidlinux.org/current/nonfree/x86_64-repodata' ...
[*] Updating repository `https://repo-fastly.voidlinux.org/current/debug/x86_64-repodata' ...
[*] Updating repository `https://repo-fastly.voidlinux.org/current/multilib/bootstrap/x86_64-repodata' ...
[*] Updating repository `https://repo-fastly.voidlinux.org/current/multilib/x86_64-repodata' ...
[*] Updating repository `https://repo-fastly.voidlinux.org/current/multilib/nonfree/x86_64-repodata' ...
=> xbps-src: updating repositories for target (armv7l)...
[*] Updating repository `https://repo-fastly.voidlinux.org/current/bootstrap/armv7l-repodata' ...
[*] Updating repository `https://repo-fastly.voidlinux.org/current/armv7l-repodata' ...
[*] Updating repository `https://repo-fastly.voidlinux.org/current/nonfree/armv7l-repodata' ...
[*] Updating repository `https://repo-fastly.voidlinux.org/current/debug/armv7l-repodata' ...
=> xbps-src: updating software in / masterdir...
=> xbps-src: cleaning up / masterdir...
=> spotify-player-0.20.3_1: removing autodeps, please wait...
=> spotify-player-0.20.3_1: removing autocrossdeps, please wait...
=> spotify-player-0.20.3_1: building with [cargo] [rust] for armv7l...
   [host] pkg-config-0.29.2_3: found (https://repo-fastly.voidlinux.org/current)
   [host] cmake-3.30.1_1: found (https://repo-fastly.voidlinux.org/current)
   [host] rust-bindgen-0.69.4_1: found (https://repo-fastly.voidlinux.org/current)
   [host] cargo-1.82.0_2: found (https://repo-fastly.voidlinux.org/current)
   [host] cargo-auditable-0.6.6_1: found (https://repo-fastly.voidlinux.org/current)
   [target] openssl-devel-3.3.2_1: found (https://repo-fastly.voidlinux.org/current)
   [target] alsa-lib-devel-1.2.12_1: found (https://repo-fastly.voidlinux.org/current)
   [target] dbus-devel-1.14.10_1: found (https://repo-fastly.voidlinux.org/current)
   [target] libxcb-devel-1.16.1_1: found (https://repo-fastly.voidlinux.org/current)
   [target] rust-std-1.82.0_3: found (https://repo-fastly.voidlinux.org/current)
=> spotify-player-0.20.3_1: installing host dependencies: pkg-config-0.29.2_3 cmake-3.30.1_1 rust-bindgen-0.69.4_1 cargo-1.82.0_2 cargo-auditable-0.6.6_1 ...
=> spotify-player-0.20.3_1: installing target dependencies: openssl-devel-3.3.2_1 alsa-lib-devel-1.2.12_1 dbus-devel-1.14.10_1 libxcb-devel-1.16.1_1 rust-std-1.82.0_3 ...
=> spotify-player-0.20.3_1: running do-fetch hook: 00-distfiles ...
=> spotify-player-0.20.3_1: running do-extract hook: 00-distfiles ...
=> spotify-player-0.20.3_1: extracting distfile(s), please wait...
=> spotify-player-0.20.3_1: running do-patch hook: 00-patches ...
=> spotify-player-0.20.3_1: running pre-configure hook: 00-gnu-configure-asneeded ...
=> spotify-player-0.20.3_1: running pre-configure hook: 01-override-config ...
=> spotify-player-0.20.3_1: running pre-configure hook: 02-script-wrapper ...
=> spotify-player-0.20.3_1: running pre_configure ...
=> spotify-player-0.20.3_1: running pre-build hook: 02-script-wrapper ...
=> spotify-player-0.20.3_1: running do_build ...
   Compiling proc-macro2 v1.0.92
   Compiling unicode-ident v1.0.14
   Compiling libc v0.2.167
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.4.0
   Compiling scopeguard v1.2.0
   Compiling memchr v2.7.4
   Compiling log v0.4.22
   Compiling shlex v1.3.0
   Compiling allocator-api2 v0.2.21
   Compiling equivalent v1.0.1
   Compiling foldhash v0.1.3
   Compiling smallvec v1.13.2
   Compiling gimli v0.31.1
   Compiling adler2 v2.0.0
   Compiling object v0.36.5
   Compiling hashbrown v0.15.2
   Compiling lock_api v0.4.12
   Compiling quote v1.0.37
   Compiling syn v2.0.90
   Compiling spin v0.9.8
   Compiling miniz_oxide v0.8.0
   Compiling rustc-demangle v0.1.24
   Compiling jobserver v0.1.32
   Compiling fixedbitset v0.4.2
   Compiling cc v1.2.2
   Compiling indexmap v2.7.0
   Compiling parking_lot_core v0.9.10
   Compiling once_cell v1.20.2
   Compiling getrandom v0.2.15
   Compiling thread-id v4.2.2
   Compiling pin-project-lite v0.2.15
   Compiling bytes v1.9.0
   Compiling itoa v1.0.14
   Compiling futures-core v0.3.31
   Compiling mio v1.0.3
   Compiling petgraph v0.6.5
   Compiling futures-sink v0.3.31
   Compiling socket2 v0.5.8
   Compiling addr2line v0.24.2
   Compiling slab v0.4.9
   Compiling serde v1.0.215
   Compiling fnv v1.0.7
   Compiling thiserror v1.0.69
   Compiling ring v0.17.8
   Compiling untrusted v0.9.0
   Compiling futures-channel v0.3.31
   Compiling subtle v2.6.1
   Compiling futures-task v0.3.31
   Compiling pin-utils v0.1.0
   Compiling typenum v1.17.0
   Compiling version_check v0.9.5
   Compiling futures-io v0.3.31
   Compiling pkg-config v0.3.31
   Compiling zeroize v1.8.1
   Compiling generic-array v0.14.7
   Compiling cmake v0.1.52
   Compiling tracing-core v0.1.33
   Compiling backtrace v0.3.74
   Compiling fs_extra v1.3.0
   Compiling dunce v1.0.5
   Compiling rustversion v1.0.18
   Compiling synstructure v0.13.1
   Compiling parking_lot v0.12.3
   Compiling aws-lc-sys v0.23.1
   Compiling httparse v1.9.5
   Compiling paste v1.0.15
   Compiling stable_deref_trait v1.2.0
   Compiling const-oid v0.9.6
   Compiling rustls-pki-types v1.10.0
The following warnings were emitted during compilation:

warning: aws-lc-sys@0.23.1: Building with: CMake
warning: aws-lc-sys@0.23.1: Symbol Prefix: Some("aws_lc_0_23_1")
warning: aws-lc-sys@0.23.1: CMAKE environment variable set: cmake
warning: aws-lc-sys@0.23.1: Generating bindings - external bindgen. Platform: armv7-unknown-linux-gnueabihf

error: failed to run custom build command for `aws-lc-sys v0.23.1`

Caused by:
  process didn't exit successfully: `/builddir/spotify-player-0.20.3/target/release/build/aws-lc-sys-310ca4f42cf9cc13/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=AWS_LC_SYS_NO_PREFIX
  cargo:rerun-if-env-changed=AWS_LC_SYS_PREGENERATING_BINDINGS
  cargo:rerun-if-env-changed=AWS_LC_SYS_EXTERNAL_BINDGEN
  cargo:rerun-if-env-changed=AWS_LC_SYS_NO_ASM
  cargo:rerun-if-env-changed=AWS_LC_SYS_CFLAGS
  cargo:rerun-if-env-changed=AWS_LC_SYS_PREBUILT_NASM
  cargo:rerun-if-env-changed=AWS_LC_SYS_C_STD
  cargo:rerun-if-env-changed=AWS_LC_SYS_CMAKE_BUILDER
  cargo:rerun-if-env-changed=AWS_LC_SYS_STATIC
  cargo:rerun-if-env-changed=CMAKE
  cargo:warning=Building with: CMake
  cargo:warning=Symbol Prefix: Some("aws_lc_0_23_1")
  cargo:rerun-if-env-changed=CMAKE
  cargo:warning=CMAKE environment variable set: cmake
  cargo:warning=Generating bindings - external bindgen. Platform: armv7-unknown-linux-gnueabihf
  cargo:rerun-if-env-changed=AWS_LC_SYS_INCLUDES

  --- stderr
  Failure invoking external bindgen!

  bindgen-PARAMS: --prefix-link-name aws_lc_0_23_1_ --allowlist-file .*(/|\\)openssl((/|\\)[^/\\]+)+\.h --allowlist-file .*(/|\\)rust_wrapper\.h --rustified-enum point_conversion_form_t --default-macro-constant-type signed --with-derive-default --with-derive-partialeq --with-derive-eq --raw-line
  // Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
  // SPDX-License-Identifier: Apache-2.0 OR ISC
   --generate functions,types,vars,methods,constructors,destructors /host/cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.23.1/include/rust_wrapper.h --rust-target 1.59 --output /builddir/spotify-player-0.20.3/target/armv7-unknown-linux-gnueabihf/release/build/aws-lc-sys-7e26946cc0878b6d/out/bindings.rs --formatter rustfmt -- -I /host/cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.23.1/include -I /host/cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.23.1/aws-lc/include
  bindgen-STDOUT: panicked at bindgen-cli/main.rs:52:36:
  Unable to generate bindings: ClangDiagnostic("/host/cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.23.1/aws-lc/include/openssl/base.h:59:10: fatal error: 'stddef.h' file not found\n")

  bindgen-STDERR: /host/cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.23.1/aws-lc/include/openssl/base.h:59:10: fatal error: 'stddef.h' file not found

  thread 'main' panicked at /host/cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.23.1/builder/main.rs:621:5:
  aws-lc-sys build failed. Please enable the 'bindgen' feature on aws-lc-rs or aws-lc-sys.For more information, see the aws-lc-rs User Guide: https://aws.github.io/aws-lc-rs/index.html
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
=> ERROR: spotify-player-0.20.3_1: do_build: '${make_cmd} build --release --locked --target ${RUST_TARGET} ${configure_args} ${make_build_args}' exited with 101
=> ERROR:   in do_build() at common/build-style/cargo.sh:8
```

any ideas?

**Comment by xavierfortier1** [comment]
On my side , I got the same thing. I'm trying to patch the `Cargo.toml` to add the `bindgen` feature to `aws-lc-sys` as they say in the error. So far, not a great success... It is still failing with the same error : `fatal error: 'stddef.h' file not found`

**Comment by xavierfortier1** [comment]
Is there a way to access lib file that are added with `makedepends` when I cross compile? or do I have to make a new host with `binary-bootstrap` to test that out? 

Here is the current situation: I'm getting really close to have something that work, but I have to use `libclang` and its `LIBCLANG_PATH` because lib files aren't found aren't found at build time (probaly because of the cross compilation).

So, I have this for now: `export LIBCLANG_PATH="${XBPS_MASTERDIR}/usr/lib"`
Is that ok? Should I do a new host with `binary-bootsrap` to test that instead?

**Comment by mdkcore0** [comment]
> @mdkcore0 So, `armv7l` doesn't build at all. There is a problem with `aws-lc-rs`, so I opened an issue [here](https://github.com/aws/aws-lc-rs/issues/632). I'm waiting for their response, will update this PR eventually. I also updated the `rust-bindgen` package since it is now used in this, will push that also.

cool! I saw you managed to build using a custom cflag to aws-lc-rs, we can proceed using this workaround for now, until a proper fix arrive :)

also, many thanks!!

**Pull request merged**
