### PR TITLE
LXQt 1.1.0

### PR DESCRIPTION
**Pull request by Idesmi**
#### Testing the changes
- I tested the changes in this PR: **YES**

Update from installed 1.0.0

#### Local build testing
- I built this PR locally for my native architecture,
  - x86_64
  - x86_64-musl

---
On the pattern, I am not sure of adding `breeze-gtk`: none of the newly introduced palettes matches Breeze colors after all.

Runtime dependency on `lxmenu-data` was moved from pattern to `lxqt-panel`.

### CODE REVIEW

**Comment by tibequadorian** [comment]
@Hoshpak

**Comment by Hoshpak** [comment]
The PR generally looks good to me. However I'm also not sure if adding breeze-gtk as a depedency is the right course of action. Is there any technical reason for that? Otherwise In would think the choice of themes should be left to the user (I use Adwaita with lxqt for instance).

**Comment by Idesmi** [comment]
The default icon theme is now changed to Breeze, and KDE-Plasma is the one theme among the provided which has a GTK+ counterpart (althogh as I mentioned, the "KDE-Plasma" theme by LXQt and the "breeze-gtk" by KDE don't match so well).
But you can use the LXQt desktop even with only Qt programs, so it'd make sense to not require it.

**Comment by Hoshpak** [comment]
Alright, please remove the `breeze-gtk` dependency so we can get this merged.

**Comment by Idesmi** [comment]
ping

**Pull request merged**
