### PR TITLE
volctl: fix dependencies

### PR DESCRIPTION
**Pull request by endigma**
volctl package requires pulseaudio currently, also totally functional with new audio server pipewire's built in pulse server, so the dependency on pulseaudio should be removed.

### CODE REVIEW

**Comment by ericonr** [comment]
Can you try to fix the tests? Might be a matter of adding `python3-yaml` to `depends` (also anything missing from `install_requires` line in https://github.com/buzz/volctl/blob/master/setup.py) + adding `checkdepends="$depends"`

**Comment by endigma-4426** [comment]
I'll look into fixing these tomorrow, currently installing with pulseaudio on an xbps ignore list works.

**Comment by teldra** [comment]
RIght now, I have this https://github.com/teldra/void-packages/pull/new/update-volctl

Test stops with
```
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
error: libpulse.so.0: cannot open shared object file: No such file or directory
```

So which libpulse.so.0 should be put into checkdepends?
And I wonder, if gtk+3 is really needed in depends. In checkdepends, it is needed.

**Comment by endigma-4426** [comment]
> RIght now, I have this https://github.com/teldra/void-packages/pull/new/update-volctl
> 
> Test stops with
> 
> ```
> Unable to init server: Could not connect: Connection refused
> Unable to init server: Could not connect: Connection refused
> error: libpulse.so.0: cannot open shared object file: No such file or directory
> ```
> 
> So which libpulse.so.0 should be put into checkdepends?
> And I wonder, if gtk+3 is really needed in depends. In checkdepends, it is needed.

I suppose pipewire's pulse backend provides this, is there a way for an either-or dependency to be implemented?

**Comment by ericonr** [comment]
Since the main usage is with pulseaudio, I'd also test with it. You might need to add `dbus` to `checkdepends` and run `dbus-run-session python setup.py test` in `do_check`.

**Comment by ericonr** [comment]
You haven't revbumped the template either.

**Pull request closed without merging**
