### PR TITLE
mesa: update to 24.2.3

### PR DESCRIPTION
**Pull request by SpidFightFR**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x64-musl

### CODE REVIEW

**Comment by SpidFightFR** [comment]
`kmsro` doesn't seem to be an available for arm devices, can i remove it / change it to something else or will it break compat ?

**Comment by classabbyamp** [comment]
from the changelog: *meson,ci: remove dead `kmsro` option in `gallium-drivers`*

**Comment by SpidFightFR** [comment]
> from the changelog: *meson,ci: remove dead `kmsro` option in `gallium-drivers`*

 Okay, i'm working on it.

**Comment by SpidFightFR** [comment]
Wow it... Worked? It failed with crosscompiling on aarch64-musl on my side, with an obscure error...

A great surprise, a good one! 😄

**Comment by SpidFightFR** [comment]
#### Testing the changes
- I tested the changes in this PR: **briefly**



#### Local build testing
- I built this PR locally for my native architecture, (x64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x64-musl

**Comment by biopsin** [comment]
Hey, what's the reason for the megadriver patch removal this time?

**Comment by SpidFightFR** [comment]
> Hey, what's the reason for the megadriver patch removal this time?

The changes in the patch were already in upstream.
The patch wasn't required anymore. since 24.2.0

**Comment by SpidFightFR** [comment]
> Hey, what's the reason for the megadriver patch removal this time?

Hey, sorry for the double answer (i had a doubt so i deleted my first answer).

The patch is upstreamed, although written in a tiny different matter

eg:
`os.symlink(os.path.basename(master), abs_driver)`
becomes:

```
basename = os.path.basename(args.megadriver)
[...]
print(f'Installing symlink pointing to {basename} to {abs_driver}')
        os.symlink(basename, abs_driver)
```

**Comment by SpidFightFR** [comment]
@classabbyamp hey sorry for the ping, i hope you're doing well.

May i request a review for mesa, please?

I noticed a slight problem within the waterfall of void builders. I hope everything is okay in the infra...!

**Comment by SpidFightFR** [comment]
#### Testing the changes
- I tested the changes in this PR: **briefly**



#### Local build testing
- I built this PR locally for my native architecture, (x64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x64-musl

Please, may we have a review for mesa 24.2.3? We are 1 major version behind upstream and missing many performance patches...

There was no news on this front for quite some time, do i need to do something in particular that i missed ?
Please ping me if so i'd gladly help.

**Pull request merged**
