### PR TITLE
rustup: generate shell completions for cargo

### PR DESCRIPTION
**Pull request by tranzystorek-io**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by Duncaen** [comment]
This would conflict with the `cargo` package. Wouldn't it be better anyways to generate them using the selected toolchain on your system?

**Comment by tranzystorek-io** [comment]
Aside from the fact that it's surprising that rustup doesn't conflict with cargo and rustc already, I think it's cumbersome to manually create completion scripts and configure the paths.

For reference, arch does this with success and just declares rustup as conflicting with rust and cargo

**Comment by Duncaen** [comment]
I don't see a reason to add a conflict between rust and rustup just for "wrong" (as they don't match the executables) bash completions.

**Comment by tranzystorek-io** [comment]
@Duncaen to be precise, the completion script generated by `rustup completion <shell> cargo` isn't tied to any fixed cargo version, but dynamically sources the script provided by the **current** default toolchain, so in that understanding it's not wrong.

Let's imagine a situation where the `cargo` and `rustup` packages are installed alongside. What is the expected workflow? Should the currently used toolchain depend on the PATH (whether it points to the `$HOME/.cargo/bin`)?

**Comment by Duncaen** [comment]
> @Duncaen to be precise, the completion script generated by rustup completion <shell> cargo isn't tied to any fixed cargo version, but dynamically sources the script provided by the current default toolchain, so in that understanding it's not wrong.

Ok, makes sense.

> Let's imagine a situation where the cargo and rustup packages are installed alongside. What is the expected workflow? Should the currently used toolchain depend on the PATH (whether it points to the $HOME/.cargo/bin)?

IMHO yes, having rustup installed for one user does not mean another user is using it or is having it setup.

Not sure if there is a good solution to this, but making rustup and rust/cargo conflict is not it.

**Comment by Duncaen** [comment]
Maybe we could use our own wrapper script that is loaded after  `/usr/share/bash-completion/completions/cargo` and will overwrite the completions if `rustc --print sysroot` is not `/usr`?

**Comment by tranzystorek-io** [comment]
Seems like whatever this wrapper would be, it would probably have to be independent from the `rustup` or `cargo` packages, like (spitballing) a separate package altogether

**Comment by tranzystorek-io** [comment]
@Duncaen I tried to give this a bit more thought, what if we added cargo completion as a `rustup-cargo-completion` subpackage, and made that subpackage conflict with `cargo`?

**Comment by tranzystorek-io** [comment]
Decided to go this way since I don't see any other solution for the conflict, @Duncaen @jcgruenhage could you see if this makes sense?

**Comment by jcgruenhage** [comment]
LGTM now, would be happy to use this :)

**Comment by CameronNemo** [comment]
Makes sense to me. If someone finds a good way to get the completions in the rustup main package without conflicts, it should not be a challenge making the subpackage a dummy.

**Comment by CameronNemo** [comment]
We could vendor this (in files) to replace the generated cargo.bash, and name the completion cargo-rustup:

```
if command -v rustc >/dev/null 2>&1; then
	if [ "/usr" != "$(rustc --print sysroot)" ]; then
		source "$(rustc --print sysroot)"/etc/bash_completion.d/cargo
	fi
fi
```

Ideally we would monitor the generated code with a checksum...

But that is a lot of effort compared to asking users to install a subpackage.

**Comment by jcgruenhage** [comment]
Considering this has been moving since Feb, I'd say we can merge this as is with the subpackage and if someone wants to build a replacement that doesn't need a subpackage, we can deal with that later. The state as is right now is already an improvement over what we have right now.

**Comment by Duncaen** [comment]
> The whole point of rustup is to fetch one or more versions of the rust toolchain, including cargo, into a local (per-user) environment. We shouldn't be shipping completions for commands that aren't provided expliclty by the package.

This was my concern too, but it just generates a stub completions file that sources the actual completions from the choosen rust toolchain. (see https://github.com/void-linux/void-packages/pull/35768#issuecomment-1061898404)

https://github.com/rust-lang/rustup/blob/feec94b6e0203cb6ad023b1e2c953d058e5c3acd/src/cli/rustup_mode.rs#L1687-L1720

**Comment by ahesford** [comment]
I think we can make this work for zsh without conflicts. Leave the completions in the cargo package `cargo`. In the `rustup` package, ship this file as `/usr/share/zsh/site-functions/_rustup_cargo`:
```sh
#compdef cargo

if command -v rustc >/dev/null 2>&1; then
	_rust_sysroot=$(rustc --print sysroot)

	if [ "$_rust_sysroot" != "/usr" ]; then
		_rust_cargo_comp="${_rust_sysroot}/share/zsh/site-functions/_cargo"
		[ -r "$_rust_cargo_comp" ] && source "$_rust_cargo_comp"
		unset _rust_cargo_comp
	fi
	unset _rust_sysroot
fi
```
If `cargo` is installed, the system `/usr/share/zsh/site-functions/_cargo` file will be processed first. I believe zsh will ignore the definition in `_rustup_cargo` because it seems to pick only the first `#compdef cargo` definition. If `cargo` is not installed, this file will be processed and do the right thing for `rustup` users.

As for bash, I don't really understand the completion system. Even with a custom script, I can't seem to get it to properly complete because the scripts seem to be sourced before the local environment defines the right path to `rustc`.

**Comment by tranzystorek-io** [comment]
I've decided to close due to no apparent consensus.

**Pull request closed without merging**
