### PR TITLE
New package: base-minimal-0.1

### PR DESCRIPTION
**Pull request by Gottox**
This PR adds a new base metapackage that contains only those tools that are useful for running with e.g. docker.

### CODE REVIEW

**Comment by Piraty** [comment]
what about
`base-voidstrap - Void Linux base system meta package for containers/chroots`
?

**Comment by Gottox** [comment]
I find neither the name nor the size of the resulting image justified. But we're using voidstrap on various places so I'm not sure if we can modify it without creating new bugs.

**Comment by chneukirchen** [comment]
Lacks tzdata and contains no editor.

**Comment by Gottox** [comment]
added

**Comment by travankor** [comment]
Why not use busybox instead of coreutils (et al)?

**Comment by arete** [comment]
hi,
for create docker container, the minimal package are
` xbps-triggers coreutils base-files glibc-locales dash grep xbps iana-etc tzdata sed shadow`
https://github.com/arete/docker-images/blob/master/base/Dockerfile

**Comment by CameronNemo** [comment]
@travankor you are certainly free to create your own metapackages using busybox or mawk or whatever you think is or isn't worth it. but the base-minimal package should describe a Void system as you would expect, i.e. glibc or musl, gawk, standard coreutils, and runit.

**Comment by travankor** [comment]
> you are certainly free to create your own metapackages or containers using busybox or mawk or whatever you think is or isn't worth it. 

I already do this, since virtual packages don't work well on xbps. But this begs the question why have so many system meta-packages (voidstrap, chroot, minimal, etc.) on the tree when you're better off rolling your own config for specific use-cases.

> but the base-minimal package should describe a Void system as you would expect, i.e. glibc or musl, gawk, standard coreutils, and runit.

What makes you say that? I would expect that a minimal system designed for containers is similar to what Alpine ships as default, but if I'm in the minority on this one I'll keep quiet. :)

**Comment by Gottox** [comment]
I intend to replace voidstrap with base-minimal, but before I can do that I need to make sure to not introduce new bugs. voidstrap is used in different parts of the system. lxc is one, void-mklive is another. To allow a smooth transition, I need to have both available.

**Comment by maxice8** [comment]
ping, @the-maldridge ok to merge ?

**Comment by DirectorX** [comment]
what about `ca-certificates`?

**Comment by CameronNemo** [comment]
@DirectorX xbps depends on ca-certificates

**Comment by maxice8** [comment]
Any progress need to be made on this or can be merged ?

**Comment by Gottox** [comment]
feel free to merge :+1:

**Pull request merged**
