### PR TITLE
aws-cli: update to 1.22.23

### PR DESCRIPTION
**Pull request by uhohspaghetios**
- I tested the changes in this PR: YES
- I built this PR locally for my native architecture, (amd64-glibc)

### CODE REVIEW

**Comment by bobertlo** [comment]
FYI I have a build of this ready with the dependencies updated also. I was just working on getting some of the tests running still. :)

**Comment by uhohspaghetios** [comment]
> FYI I have a build of this ready with the dependencies updated also. I was just working on getting some of the tests running still. :)

Oh sweet.  I just undertook this one because it was mostly easy and I wanted the latest for an AWS course I started today.  I can close this PR if appropriate.

**Comment by bobertlo** [comment]
I’ll try to get what I’ve got up soon. Just know botocore and s3transfer
are developed together with aws cli so if you run into any issues try
bumping those too. It usually is fine but has broken things before.

I think everything was working at the latest versions I was just working on
tests and seeing how awful the 2.x branch runtime is lol

**Comment by bobertlo** [comment]
#34490

**Pull request closed without merging**
