### PR TITLE
fcft: update to 3.1.5

### PR DESCRIPTION
**Pull request by cinerea0**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by icp1994** [comment]
Looking at the changelog, doesn't this require `harfbuzz>=5.2`?

**Comment by cinerea0** [comment]
This shouldn't be merged until harfbuzz is updated. @paper42, should I wait for duncaen to do that since he's the only one who has historically done so, or is it okay for me to take a crack at it?

**Comment by cinerea0** [comment]
This is still relevant but blocking on harfbuzz.

**Comment by classabbyamp** [comment]
@cinerea0 please rebase

**Pull request merged**
