### PR TITLE
font-iosevka: update to 5.2.1

### PR DESCRIPTION
**Pull request by FollieHiyuki**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by FollieHiyuki** [comment]
I was late :(
But on second thought should we move to use `super-ttc` instead? It contains more variants, spacings while remaining roughly the same file size

**Comment by FollieHiyuki** [comment]
screenshot

@ericonr the author recommends super-ttc as well

**Comment by ericonr** [comment]
Oops :p 

Feel free to open a PR for an improvement to the package. Do show the current package size and the new package size to help with the decision. That said, given that using a system package requires no manual management, I'm not sure it helps *that* much.

**Comment by FollieHiyuki** [comment]
screenshot

Roughly 3MB smaller, worth it?

**Comment by ericonr** [comment]
Assuming all our packages support the format, sure.

**Pull request merged**
