### PR TITLE
gtklock: update to 3.0.0

### PR DESCRIPTION
**Pull request by jovanlanik**
#### Testing the changes
- I tested the changes in this PR: **briefly**

I was unsure if the new dependency should be a separate commit, I can squash if needed.

### CODE REVIEW

**Comment by cinerea0** [comment]
The commit message for gtk-session-lock should be `New package: gtk-session-lock-0.2.0`. Just curious, why is `git` needed in hostmakedepends?

**Comment by jovanlanik** [comment]
Fixed the message and no git wasn't needed.

**Comment by cinerea0** [comment]
And just to make sure, this dependency switch probably won't cause gtklock to stop functioning on any setups it was previously working fine on?

**Comment by jovanlanik** [comment]
I think all major compositors support ext-session-lock-v1 already.

**Pull request merged**
