### PR TITLE
Kill pangox-compat

### PR DESCRIPTION
**Pull request by sgn**

### CODE REVIEW

**Comment by fosslinux** [comment]
I tried to do this... I ran into problems.

`gtkglextmm` has a corresponding API to `gtkglext`'s `gtkglfont` api that needs to be killed off too.
Furthermore `ufoairadiant` breaks with this change as it has an internal library that links against `gtkglfont` for font rendering in `ufoairadiant`.

**Comment by sgn** [comment]
> I tried to do this... I ran into problems.
> 
> `gtkglextmm` has a corresponding API to `gtkglext`'s `gtkglfont` api that needs to be killed off too.

Which one? I couldn't find that.

> Furthermore `ufoairadiant` breaks with this change as it has an internal library that links against `gtkglfont` for font rendering in `ufoairadiant`.

Let me see.

> 
> This patch fixes the `glOrthof` stuff:
> 
> ```
> SDL_opengl.h dosen't have the nessecary headers. GL/gl.h has the parts
> of SDL_opengl.h needed for SDL_opengl_glext.h, then include
> SDL_opengl_glext.h which has the *f functions.
> 
> --- src/client/renderer/r_gl.h  2020-10-08 07:50:29.818581990 +1100
> +++ src/client/renderer/r_gl.h  2020-10-08 07:52:16.805006133 +1100
> @@ -29,7 +29,8 @@
>  #include "../../ports/android/r_gles_android.h"
>  #include <stdlib.h>
>  #else
> -#include <SDL_opengl.h>
> +#include <GL/gl.h>
> +#include <SDL_opengl_glext.h>
>  #endif
> 
>  inline void R_DrawArrays (GLint first, GLsizei count) {
> ```

Excellent! Thanks,


> `src/tools/radiant/libs/gtkutil/glfont.cpp` is the one that uses glfont.

**Comment by sgn** [comment]
Succeed on building `ufoai`, I can play with Campaign but not Skirmish. uforadiant, doesn't work.

**Review by pullmoll — APPROVED** [review]
I'll see if/when I find time to take care of this. The games are IMO nothing which should become show stoppers for repository cleanups.

**Comment by fosslinux** [comment]
Agreed. `ufoai` can go update to some modern APIs, that's not our problem.. it's not a package that is super popular, either.

**Comment by q66** [comment]
looks like anydesk has issues with this https://www.reddit.com/r/voidlinux/comments/jawjm1/soname_libpangox10so0/

**Comment by fosslinux** [comment]
https://github.com/NixOS/nixpkgs/blob/abcdffb6a272de657c3d1a423dda44f9037229b3/pkgs/applications/networking/remote/anydesk/default.nix#L70 a patchelf invocation should fix this

**Pull request merged**
