### PR TITLE
linux5.7: enable BPF type format on x86_64

### PR DESCRIPTION
**Pull request by egorenar**
Required e.g. for opensnoop from bcc-tools to fix the following problem:
libbpf: failed to find valid kernel BTF
libbpf: vmlinux BTF is not found
bpf: Failed to load program: Invalid argument

### CODE REVIEW

**Comment by ahesford** [comment]
According to the issue:
> Note that when using this config, pahole utility becomes a build dependency.
At a minimum, this dependency should be added to the template.

**Comment by leahneukirchen** [comment]
Hm, this works on 5.4 without the flag... do you know why? (It prints the error, but then does the thing.)

**Comment by q66** [comment]
probably a red herring and the warnings are unrelated

**Comment by leahneukirchen** [comment]
Enabling this for x86_64 now, results in ~900k overhead in vmlinuz, but for advanced usage it will probably be a common dependency in the future. Arch has enabled it as well. We'll follow up with other architectures after some testing.

Skipping rebuild for .13 to appear.

**Pull request merged**
