### PR TITLE
Deeping terminal fix build with latest vala and cross compile

### PR DESCRIPTION
**Pull request by sgn**

### CODE REVIEW

**Comment by Piraty** [comment]
since expect is handled in #20605, why have this commit in this branch as well?

**Comment by sgn** [comment]
> since expect is handled in #20605, why have this commit in this branch as well?

Ah, It was there to be able to cross-compile in CI,
IOW, this one is depended on #20605

**Comment by sgn** [comment]
Forced push for 1 fix in cross-misc.patch:

    AC_COMPILE_IFELSE -> AC_LINK_IFELSE

**Comment by sgn** [comment]
Travis is passed.

**Pull request merged**
