### PR TITLE
pinephone-uboot: update to 0.0.20200917.

### PR DESCRIPTION
**Pull request by jjsullivan5196**
Fixes random wifi MAC issue, see this issue for more details:
https://gitlab.com/ubports/community-ports/pinephone/-/issues/225

### CODE REVIEW

**Comment by ericonr** [comment]
@jcgruenhage you had a random CI failure, which is probably what led to lack of attention here. Want to update the PR/rebase on master?

**Comment by jjsullivan5196** [comment]
@ericonr yeah, that's what I figured, no big deal :^) I just did a rebase and fixed a syntax bug that was in the template. There hasn't been any new releases of the pinephone uboot firmware, so this is still up-to-date in a sense.

**Comment by ericonr** [comment]
Could you squash the two commits together, please?

**Comment by jjsullivan5196** [comment]
@ericonr done :+1:

**Pull request merged**
