### PR TITLE
New package: Yaru++ icon theme

### PR DESCRIPTION
**Pull request by gusbemacbe**
Hello!

I am co-author of Yaru++ icons. I am providing it for Void Linux users who want to install quickly without needing to go to my repository.

Thanks to @DarthWound!

### CODE REVIEW

**Comment by gusbemacbe** [comment]
should be less than 72 char, I am confused, why this error?

**Comment by k4leg** [comment]
Change the version.(Instead of v3.0 write 3.0. And add a change to distfiles("${version}" -> "v${version}".)

**Comment by gusbemacbe** [comment]
@k4leg, thank you for figuring and correcting it! It worked now.

**Comment by k4leg** [comment]
Glad I helped! Now you have to combine them.
Sorry I didn’t explain right away: xbps-src is looking for the folder "${pkgname}-${version}", and since the version was v3.0, he looked for a folder that isn’t, because the archive contains "${pkgname}-3.0".

**Comment by gusbemacbe** [comment]
@k4leg, in the afternoon, I have to test again on my Void to understand how to combine.

**Comment by DarthWound** [comment]
Sorry I was sleeping, I work at night :stuck_out_tongue_winking_eye: 

Just as a bonus, in Void I change the orange folder colors to these ones using sed:
`f6b069` -> `96c296`
`f3994a` -> `abc2ab`
`903906` -> `324038`
`491706` -> `292e2c`
`ec7223` -> `478061`

This way I have Void green tints:

Capture d’écran de 2019-10-26 12-39-42

Thank you @gusbemacbe for the package :-)

**Comment by gusbemacbe** [comment]
@k4leg, I tried many ways and it did not work. 

Maybe @DarthWound and @mobinmob which is responsible for Papirus icons theme template, know what happened if they have time and/or want to help a bit.

**Comment by k4leg** [comment]
As I understand it, you could not merge commits?
This is easy enough:
$ export EDITOR="nvim" # Or your other editor(nano, vi, vim & etc.).
~/void-packages | branch: yaru-plus-icon $ git rebase -i HEAD~10
Something like this will appear in the terminal: https://i.imgur.com/g5DnA6g.png
You will need to make something like this out of this: https://i.imgur.com/opo3DhL.png
Save and exit. Next it will appear: https://i.imgur.com/5zxgeUs.png
You should do something like this: https://i.imgur.com/vOdlOq5.png
Everything is ready. Remains only:
~/void-packages | branch: yaru-plus-icon $ git push -f

**Comment by gusbemacbe** [comment]
> ```
> $ export EDITOR="nvim" # Or your other editor(nano, vi, vim & etc.).
> ~/void-packages | branch: yaru-plus-icon $ git rebase -i HEAD~10
> ```

I am a bit confused. Do you mean `export EDITOR="vim" ~/void-packages | branch: yaru-plus-icon && git rebase -i HEAD~10`? From my cloned repo or from this repo?

**Comment by k4leg** [comment]
From your cloned repo. And yes, this is not &&, but $. Sorry for not highlighting normally...
`export EDITOR=nvim` Not required. This is to make it more convenient.

**Comment by k4leg** [comment]
Oh yes, and follow: https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#committing-your-changes

**Comment by gusbemacbe** [comment]
@k4leg and @DarthWound 

I followed the manual you indicated, but I had to follow [another manual](https://github.com/void-linux/void-packages/blob/master/README.md) to compile and test the template. But I received:

```
[*] Unpacking packages
xbps-triggers-0.113_3: unpacking ...
ERROR: xbps-triggers-0.113_3: [unpack] failed to extract file `./var/db/xbps/triggers': Operation not permitted
ERROR: xbps-triggers-0.113_3: [unpack] failed to extract files: Operation not permitted
ERROR: xbps-triggers-0.113_3: [unpack] failed to unpack files from archive: Operation not permitted
Transaction failed! see above for errors.
```

In my Void Linux, I do not have `msgfmt`, `makeinfo`, `xbps-uchroot` and `xbps-uunshare`.

**Pull request closed without merging**
