### PR TITLE
linux5.2: Make some things modules.

### PR DESCRIPTION
**Pull request by thomas-t-w**
I have a laptop that requires i8042 to be unloaded upon suspend. Some people don't have nvme drives.

### CODE REVIEW

**Comment by thomas-t-w** [comment]
should i be making these changes to the ppc kernels as well? I am reluctant to change a kernel without hardware to test my changes.

**Comment by pullmoll** [comment]
Personally I don't like the idea to make these modules, though.

If I see it right then, with this change applied, without a working initrd and the modules available you won't have keyboard input and support for NVME on any system and thus could not even try to e.g. use the `Ctrl+Alt+Shift+SysReq+<X>` keys for debug info, sync, reboot, etc.?

If this is the case, please create your x86_64-dotconfig-custom and roll your own kernel. It's your laptop which requires i8042 as a module and I haven't heard of anyone else asking for this.

**Comment by thomas-t-w** [comment]
That is an excellent point. Since I can't see. i forget that that stuff even works. Usually for me if its not booting into userspace its game over and I have to chroot in to see whats wrong. IN that case, should we go the other direction and also build ahci into the kernel instead of a module for people who have sata drives and not NVME?

**Comment by thomas-t-w** [comment]
also, we should maybe include usbhid in the kernel for usb keyboard and mice?

**Comment by pullmoll** [comment]
I don't think we should change a running system for no apparent reason. @void-linux/pkg-committers ?

**Comment by the-maldridge** [comment]
This change would break multiple known classes of users and therefore is not a candidate for merge to the official repo. If you have hardware that needs custom kernels to work correctly you are encouraged to build it outside the distro provided tree.

**Pull request closed without merging**
