### PR TITLE
[ci skip] FreeCAD: update to 0.18.1

### PR DESCRIPTION
**Pull request by yopito**
Some highlights:
* update to last stable release: 0.18.1
* upgrade all underlying stack to Qt5 and python3
* python3 only since python2 is EOL next year
* personal build and runtime is fine (x86_64/glibc)
* remove `dos2unix` on source code since it makes difficult to work on patches with external sources

Upstream's project indicates that 0.18 and 0.18.1 source code can be considered as stable releases, even if not officially released yet (source: https://forum.freecadweb.org/viewtopic.php?p=299243#top)

ping @Piraty and @karl-nilsson, hope you will enjoy it.

Edit: 0.18.1 is here
I'm out this week-end, hope this PR won't need too much rework.

### CODE REVIEW

**Comment by karl-nilsson** [comment]
@yopito built and tested fine on my system (x64, glibc)

**Comment by maxice8** [comment]
Merged pyside2 myself, please update the PR

**Comment by yopito** [comment]
@maxice8 : here it is

**Comment by maxice8** [comment]
Merged manually. Thank you

**Pull request closed without merging**
