### PR TITLE
kdevelop*: update to 23.08.4

### PR DESCRIPTION
**Pull request by Luciogi**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-GLIBC)

### CODE REVIEW

**Comment by Luciogi** [comment]
Issue: 
=> kdevelop-php-23.08.4_1: libkdevphpduchain.so not found in common/shlibs.
=> kdevelop-php-23.08.4_1: libkdevphpcompletion.so not found in common/shlibs.
=> kdevelop-php-23.08.4_1: libkdevphpparser.so not found in common/shlibs.

Do I need add these libs in `common/shlibs` ?

**Comment by Luciogi** [comment]
why arm failing
is cross dependency not available ?

**Comment by Chocimier** [comment]
The imported target "clangApplyReplacements" references the file

      "/usr/aarch64-linux-gnu/usr/lib/libclangApplyReplacements.a"

So you need to add package containing it to makedepends.

**Comment by Calandracas606** [comment]
an update to kdevelop is part of the llvm17 PR #46935

**Comment by Luciogi** [comment]
> an update to kdevelop is part of the llvm17 PR #46935

does arm builds fail for you?

**Comment by Calandracas606** [comment]
> does arm builds fail for you?

Not sure, since armv6l build is failing for llvm17

**Pull request closed without merging**
