### PR TITLE
dropbox, nautilus-python, seahorse-nautilus: remove package

### PR DESCRIPTION
**Pull request by paper42**
These packages don't work with nautilus 43, this is split from the GNOME 43 PR (#39513) because removing these packages will break shlib checks in xbps if the are not also removed from binary repositories. First, this PR should be merged, then the packages removed from binary repositories and then the GNOME 43 PR should be merged.

#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by coreyberla** [comment]
https://github.com/dropbox/nautilus-dropbox/commit/5587be23bec68281e5d6de2b302dbd2a79ea47aa Nautilus Dropbox supports gnome 43

**Comment by coreyberla** [comment]
https://gitlab.gnome.org/GNOME/nautilus-python/-/tags/4.0 so does Nautilus Python

**Comment by JamiKettunen** [comment]
> [dropbox/nautilus-dropbox@5587be2](https://github.com/dropbox/nautilus-dropbox/commit/5587be23bec68281e5d6de2b302dbd2a79ea47aa) Nautilus Dropbox supports gnome 43

@coreyberla technically true, not tagged though; in that case `seahorse-nautilus` also supports GNOME 43 https://gitlab.gnome.org/GNOME/seahorse-nautilus/-/commit/d4b51676fee6e4d2580506629847cdd88e8ffdbb

**Comment by coreyberla** [comment]
> technically true, not tagged though

I think that's just an oversight. They made a release off the newly pushed commits.

https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-2022.12.05-1.fedora.x86_64.rpm

**Comment by paper42** [comment]
oops, I will fix that later

**Comment by paper42** [comment]
fixed as part of https://github.com/void-linux/void-packages/pull/39513

**Pull request closed without merging**
