### PR TITLE
drawterm: update to 0.0.20200619

### PR DESCRIPTION
**Pull request by q66**
Fixes https://github.com/void-linux/void-packages/pull/23047

@glats the changes i wanted done were too many so I just took the 5 minutes and did them myself, quicker that way

please test

### CODE REVIEW

**Comment by q66** [comment]
hm, why didn't travis run?

**Comment by q66** [comment]
guess i'll just crossbuild them myself...

**Comment by Johnnynator** [comment]
tavis is running: https://travis-ci.org/github/void-linux/void-packages/builds/700108551

**Comment by q66** [comment]
Okay then, looks like it's all pass

**Comment by glats** [comment]
ok. im gonna testing.

**Comment by glats** [comment]
@q66 Yesterday I was talking to someone who is part of the 9front team and saw the previous PR and well she added your patch: look at https://code.9front.org/hg/drawterm/rev/c79996216bb0

**Comment by q66** [comment]
no

**Comment by glats** [comment]
welp, ok!

**Comment by q66** [comment]
well, i guess we can use __atomic_test_and_set but that patch only does it for arm64 so it's useless

**Comment by q66** [comment]
actually, nevermind, from documentation:

```
It should be only used for operands of type bool or char.
```

so their patch is also outright wrong

**Comment by glats** [comment]
ok i tested and works fine.

**Comment by q66** [comment]
since this will actually unbreak aarch64 and nobody has updated it in years, i'll just merge this..

**Pull request merged**
