### PR TITLE
spotify: update to 1.2.50

### PR DESCRIPTION
**Pull request by lassemoldrup**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by classabbyamp** [comment]
looks like this version is already gone

**Comment by Astate** [comment]
This is really the latest version:
https://repository-origin.spotify.com/dists/stable/non-free/binary-amd64/Packages

The download is not really stable, probably an infrastructure problem at Spotify
https://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.2.50.335.g5e2860a8_amd64.deb

**Comment by lassemoldrup** [comment]
I think it is still the newest version. If you look at the CI, it even manages to download most of the file before it fails.

Can someone try rerunning the pipeline?

**Comment by Clos3y** [comment]
[Version 1.2.52 is now available](https://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.2.52.442.g01893f92_amd64.deb)

**Pull request closed without merging**
