### PR TITLE
libomp: update to 8.0.0.

### PR DESCRIPTION
**Pull request by atweiden**

### CODE REVIEW

**Comment by atweiden** [comment]
> There is no need to add the shlib entries as nothing links against these libraries.

What about cryfs? https://github.com/void-linux/void-packages/blob/7e9d9ecd5657b6d77036cfb20d11dab30c726786/srcpkgs/cryfs/template#L10?

**Comment by jnbr** [comment]
Not sure what's going on there but cryfs doesn't link against libomp:

```
$ xbps-query -R -p shlib-requires cryfs
libcurl.so.4
libfuse.so.2
libstdc++.so.6
libgcc_s.so.1
libc.so
```

**Comment by atweiden** [comment]
Upstream [notes](https://github.com/cryfs/cryfs/blob/develop/README.md#troubleshooting) not building against omp "will cause slower file system mount times". This was the impetus for adding the libomp package in the first place.

I think cryfs should be linking against libomp.

Maybe something is going wrong because I'm not including the full `-DOpenMP_CXX_FLAGS='-Xpreprocessor -fopenmp -I/path/to/openmp/include'` as recommend by upstream. IIRC, I left out the `-X` and `-f` opts there because of difficulty passing the whitespaced opts during the build.

**Comment by jnbr** [comment]
Is there a reason to use `libomp` instead of `libgomp` with cryfs?
Replacing `libomp-devel` with `libgomp-devel` and removing all the OpenMP specific configure flags works fine.
`libgomp` is the OpenMP implementation of gcc, as we compile with gcc it makes sense to use it.

**Comment by pullmoll** [comment]
I guess you would take `libomp` in case the system (or your preferred) compiler is `clang` or another `llvm` based compiler which uses OMP. Since we use `gcc` for most of our packages, we should probably add a `-devel` subpackage, make this package conflict with `libgomp-devel`, and move `/usr/lib/libgomp.so` to the `-devel` package.

In case we are ever forced to built a package linking against this `libomp` with one of the `llvm` base compilers, I think both implementations could coexist in a user's installed files, because they have their own `*.so.*` files.

**Pull request closed without merging**
