### PR TITLE
linux5.4: update to 5.4.11

### PR DESCRIPTION
**Pull request by bgkillas**
linux5.4: update to 5.4.11

### CODE REVIEW

**Comment by bgkillas** [comment]
seems that the checks failed ig i dont understand

**Comment by abenson** [comment]
1. Please follow the convention for commit messages: `<pkgname>: update to <version>.`
2. Checksum needs to be updated

**Comment by bgkillas** [comment]
idk how to find checksums i wonder if that was the right thing doesent feel like

**Comment by Duncaen** [comment]
1. The commit message not the PR title has to follow the standard.
1. The checksum is not correct, this comes back to having tested your changes.
1. `revision` needs to be reset to 1.
1. commits need to be squashed.

You should test the things you open a PR for, maybe a simpler template that doesn't require a lot of time to compile would be a better start.

**Comment by bgkillas** [comment]
welp im to lazy giving up time

**Pull request closed without merging**
