### PR TITLE
lxd: update and unbreak build

### PR DESCRIPTION
**Pull request by CameronNemo**

### CODE REVIEW

**Comment by fosslinux** [comment]
Gosh, so many LXD updates :P I will test shortly.

**Comment by CameronNemo** [comment]
LXD updates every other month, and they do not use go modules so the build breaks whenever they do update.

**Comment by fosslinux** [comment]
Silly Travis.. seems to just be a builder glitch.

**Comment by ernierasta** [comment]
@CameronNemo  can you elaborate on that? There is closed issue about using modules, but maybe we should try to convince upstream to use modules if it would help packaging. We can mention this issue there.

**Pull request merged**
