### PR TITLE
New package: hwinfo-21.77

### LINKED ISSUE #32402: Package request: hwinfo
Hardware detection tool from openSUSE
https://github.com/openSUSE/hwinfo

### PR DESCRIPTION
**Pull request by meator**
The current templates are working, but I'd like to make hwinfo cross-compilable.

#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

Closes #32402

### CODE REVIEW

**Comment by meator** [comment]
I have updated both packages and removed a patch that was upstreamed.

**Comment by leahneukirchen** [comment]
Thanks a lot for packaging this. Please add a `hwinfo-devel` package.

**Comment by meator** [comment]
Thanks for your response. I have added the `hwinfo-devel` package, but I'm unsure if it requires any additional dependencies.

**Comment by meator** [comment]
I know the cross building of hwinfo is a little bit hacky, but it requires to run the things it compiles, so I don't see a better solution.

**Comment by leahneukirchen** [comment]
It's ok, we do similar things with other packages.

**Pull request merged**
