### PR TITLE
wayfire: update to 0.7.0.

### PR DESCRIPTION
**Pull request by travankor**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [X] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Do you know if there are new releases coming for the other components?

**Comment by travankor** [comment]
Oh yes, I have updated the other wayfire components.

Wlroots 0.13 is not out yet, but wayfire 0.7.1 will be compatible with wlroots 0.13.

**Comment by ericonr** [comment]
Ok, I have a few issues with this update...

- can't launch wcm:

```
Loading wf-shell plugin: panel
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
fish: 'wcm' terminated by signal SIGABRT (Abortado)
```

- animations are way choppier than with 0.6.x (same config)
- it didn't start properly until I uninstalled `xdg-desktop-portal` and `xdg-destop-portal-wlr`; I got only a black screen, where I could launch a terminal, but waybar or wf-background didn't appear, even though they seemed to be running

All these issues are new with this PR.

**Comment by travankor** [comment]
FWIW I'm running 0.7.0 since it released.

- I can reproduce the wcm crash (I never used wcm which is why I didn't notice that).
- This could be the new grid crossfade effect (Or could you explain in more detail, please?)
- I have `xdg-desktop-portal` installed and `xdg-desktop-portal-wlr` isn't packaged by void yet

**Comment by travankor** [comment]
>animations are way choppier than with 0.6.x (same config)

I think this was mentioned earlier to be caused by the dbus plugin

**Pull request merged**
