### PR TITLE
[WIP] [ci skip] linux: Enable building on ppc

### PR DESCRIPTION
**Pull request by stenstorp**
Got a booting kernel config for 32 bit PowerPC. @newbluemoon did it for 4.18 a while ago and I did a bit of adjusting for 4.19. Let me know if anything needs to be added/removed.

Also, @q66 I wan't able to get the 4.19/20 kernel with your config for ppc64 big endian booted on my G5s. I'll see If I can get the config booting properly.

### CODE REVIEW

**Comment by q66** [comment]
Cool. The big endian ppc64 config is pretty much a big endian version of my little endian kernel, I don't have purely big endian hardware like the G5 around. As for the ppc one, just check and make sure the driver choices (e.g. what is made a module etc) match other archs where arch independent, and we should be good.

**Comment by stenstorp** [comment]
@q66 is there a dafault/master config with all the basic options checked or does that have to be done manually?

**Comment by q66** [comment]
Not as far as I know. What I did was take x86_64 config, rebase it for another arch, go through every single option manually and match it against other distros's generic kernels for correctness and finally reviewed the whole thing, took a couple days total. In your case I wouldn't do that, I'd just take what you have and review it against the x86_64 config.

**Comment by pullmoll** [comment]
FWIW In my [ppc64-gnu branch](https://github.com/pullmoll/void-packages/tree/ppc64-gnu) I have a ppc64-dotconfig for linux4.19 adapted from the Debian unstable kernel, which is also 4.19. With this one the various problems I had before are gone: `dracut -f` no longer segfaults, `windfarm_core` module is really controlling the system fans, Xorg for NVidia (GeForce 6600 LE, aka NV43) working, etc.
There are a lot of differences which I'm not sure if they are good, while for me the kernels (4.19 and 5.0) work fine. Perhaps you want to compare what Debian does different.

**Comment by q66** [comment]
If you could take your config and try to minimize the differences from our ppc64le kernel config (so that the driver set is generally the same, modern POWER platforms are enabled - i'm talking about OPAL/powernv etc.) that'd be nice. Also, I noticed that you've been doing some glibc BE enablement work, but AFAIK glibc has no ELFv2 support on big endian, how does that work?

**Comment by q66** [comment]
I will do some changes into the ppc64le kernel configs next week to bring them closer to yours (there are some key points which i see could be improved in the LE configs, such as enabling more power management stuff etc. which may not be too useful with current state of the firmware on openpower hardware but should be fixable). I have no way to test on a G5, so i'll need you to help with fixing the BE kernel.

**Comment by pullmoll** [comment]
Oh! I didn't know (or want to accept) that glibc has no support for ELFv2. I just ignored that (fact?) and tried and it works. The stuff I built is, as always, at https://repo.voidlinux.de/current. Today I restarted the whole shebang to also generate the debug packages for everything, because I need them to find the reason for crashing `mozjs52` and `firefox` on powerpc64-linux-gnu.

One problem I faced when I used the `common/cross-profiles/ppc64-musl.sh` and modified it for glibc as `common/cross-profiles/ppc64.sh` was I had to remove the `-mlong-double-64` because otherwise some packages later on wouldn't link. I don't remember if it was rust or go or some other language. Without that option I could build more packages.

Another and more annyoing problem is that I cannot cross compile build-helper `gir` enabled packages due to some unknown detail in the setup of `gobject-introspection` and its wrappers. I worked around this by building the relevant packages on the G5 for now.

ppc64-musl is also basically running on the G5 while there are more problems compared to glibc.
I can try your changes here. I have two partitions on the G5, one for glibc and one for musl. They can both use the same kernel and initramfs.

**Comment by q66** [comment]
The 64-bit `long double` thing is musl specific, glibc on power supports 128-bit `long double` (as a composite type of two doubles) while musl does not. As for glibc not supporting elfv2, i can't actually find anything about it right now, it was ~2017 when it was unsupported,

**Comment by pullmoll** [comment]
Heh, things are changing faster than you'd expect :-)
I'll see if I can find the time do a deep comparison of my ppc64-dotconfig vs. ppc64le-dotconfig on monday.

**Comment by q66** [comment]
That would be great. The thing is, I can take your config and start doing changes in it, but chances are it would require many iterations until we got to some kind of expected results, so if you can slim down the baseline diff, we can get things fixed much faster.

By the way, I don't like how we set per-architecture package features depending on their crossability in Void, I've been trying to get rid of this practice over the place (I think packages should be buildable natively with their full featureset regardless of the architecture, and cross limitations should be applied in an architecture independent manner) - I noticed you did this in your branch with some xorg video driver, I think we should strive to avoid that. Especially if I eventually succeed with getting Void a native build server for ppc64/32 (I have the hardware, and I'm willing to give proper access to it, it would be largely dedicated to building Void - it's an 18-core POWER9 machine, so probably faster than any build server we currently have, it could handle native building for both endians and 32/64 bit without any trouble), the packaging templates should be ready for that.

**Comment by q66** [comment]
Also, another thing to keep in mind regarding ELFv2 ABI, if we use that for glibc, it means any existing pre-built ppc64 big endian software will not work on it unless statically linked - but I think if there is the option of going ELFv2 we should, because it's a much cleaner ABI and there are some performance and other benefits as well - compatibility with older binaries can always be done through chroot or whatever if necessary.

Also btw, when dealing with infra stuff in xbps-src for ppc64 BE glibc elfv2, you can just mimic the LE glibc settings, it should be more or less the same in the end. i.e. stuff like compiler flags etc should be unified for both BE and LE on glibc.

**Comment by q66** [comment]
Also one more thing, if you want me to add you into the `void-ppc64` github org so that you can have your working branches there, let me know - for one it would allow you to easily use my staging changes, but there is also the benefit of me being able track your changes more easily as well as having everything in one place so that potential users and testers can make use of it; i'll also be setting up the build server during the next few coming weeks, which will for now experimentally mimic Void's own build infra, so if you want access to that as well for having a bit more building horsepower, I can facilitate that as well.

**Comment by pullmoll** [comment]
Hi @q66 I now have reduced the differences for the ppc64-dotconfig for linux4.19 quite a bit and the kernel still works.
Things to look for are:
+ The windfarm_core module has some additional modules which, if missing, make controlling the system fans and other things not work.
+ The PowerMac G5 needs the CONFIG_PCIEPORTBUS=y and several dependent modules enabled, or the kernel won't detect the PCIE connected cards (Shasta SATA, Graphics, USB OHCI/EHCI controllers)
+ You can't set CONFIG_GEN_RTC=y or the G5 real time clock won't be detected leading to no valid system time and as a consequence errors when trying to use TLS (invalid certificates due to the 1.1.1970 date stamp). Build it as module seems to be ok.
+ There are still some modules on the ppc64le side which I have not (yet) on the ppc64 config. I'll try to do add these in the next step.

Unfortunately trying to use the 4.19 config as a base for 5.0 doesn't work too well: I have to answer lots of questions when configure is run. So the 5.0 ppc64-dotconfig is not as much trimmed down and aligned with ppc64le yet. Perhaps I'd be better of to use the ppc64le config and redo the changes which resemble the 4.19 difference. It's a tedious job anyway.

For your questions and suggestions: sure I can manage the branch at your organization, if you want to add me to void-ppc64. I think we can already replace the `ppc64-musl` with `ppc64*` if it comes after the `ppc64le*` in case statements. Having a powerful machine to build native would certainly help, while I still would like to be able to cross build as much as possible on my own box, a Ryzen Thread Ripper 16core.

I don't think we'll see too many ppc64 elfv1 packages at all so that should not be a big problem.

**Comment by q66** [comment]
Perfect, this is just what I needed to know @ the kernel - I'll update the ppc64le configs according to the suggestions to bring them closer together, and add my remaining bits I wanted to add (they mostly match yours anyway, stuff like hibernation support and so on). Yeah, I don't think so either @ the elfv1 stuff, worst case people can always do something like debootstrap a Debian chroot (ABI is purely a userland thing anyway).

A lot of case statements and so on can be unified, yes - I'll work on that. As for the cross compatibility, i think something like this could be done (or maybe use a build option for it so that it's clearly marked in the package...):

```
case "$XBPS_TARGET_MACHINE" in
    ppc64*|....)
        depends+=" foo"
        if [ ! "$CROSS_BUILD" ]; then
            depends+=" bar"
        fi
    ;;
esac
```

It's not ideal, but probably the cleanest we can get it, allows people to cross their packages while still having fully featured native builders... of course, ideal is to fix nocross packages not to be nocross :)

Also, yes, I definitely want the architecture to be cross-compilable in addition to native, ideally we should be able to cross compile from any arch to any other arch (already generally possible as long as the toolchain is there, like, I regularly cross compile from ppc64le to x86_64-musl here and it works without problems), I can provide access to a POWER9 box anyway in case you need it for testing, just need to finish setting it up (storage HBA recently arrived, new RAM is due to arrive, should be more or less ready after that).

**Comment by q66** [comment]
Anyway, I invited you into the org. Feel free to use it if/however you like

**Comment by q66** [comment]
By the way, do you want to eventually push these glibc big endian target changes into void-packages `master` yourself or should I cherry-pick them and PR them together with my usual stuff? I can do that if you want me to, but these generally look pretty good, so there shouldn't be anything blocking them from being in upstream

**Comment by stenstorp** [comment]
Perhaps there is a more appropriate place to have this discussion, I don't see how it is related to a 32 bit powerpc kernel configuration. In the case of the G5 kernel, were you able to get something better working @pullmoll ? If so, I'll close my PR and just let you do it.

**Comment by q66** [comment]
I think @pullmoll's config should be fine. @pullmoll regarding the 5.0 config, it will ask you a lot of questions but it should be possible to just answer them according to what other 5.0 configs already do - it might take a while to answer them all but I wouldn't expect it to be impossible or take more than 30 minutes... it should not break anything, you will mostly see new features and stuff.

**Comment by stenstorp** [comment]
Should I close my ppc64 kernel config PR then?

**Comment by q66** [comment]
I'd say yes. Also, in order to not pollute this thread, any further comments on that should go in https://github.com/void-ppc64/void-packages/issues/1.

**Comment by stenstorp** [comment]
I've re-based the kernel config off of the debian sid powerpc config, works well on my G4 machine. Unless there's anything obvious that needs changing, I think this is ready to go.
There is less supported hardware in the config but there aren't any 32 bit powerpc machines that would be able to use any of that stuff anyway.

**Comment by pullmoll** [comment]
I did add your changes to the current linux/linux4.19 and successfully cross built the kernel for ppc here.
You may want to give my repo at http://repo.voidlinux.de/current a try for 4.19.37 or perhaps the base-voidstrap or base-system packages.

**Comment by q66** [comment]
Also do the same for 5.0, please

**Comment by pullmoll** [comment]
Sadly 5.0.10 doesn't compile with the defaults based on ppc-dotconfig from 4.19. Has to to with zsmalloc:
```
In file included from ./include/linux/cache.h:5,
                 from ./include/linux/printk.h:9,
                 from ./include/linux/kernel.h:14,
                 from ./include/linux/list.h:9,
                 from ./include/linux/module.h:9,
                 from mm/zsmalloc.c:33:
mm/zsmalloc.c:130:49: warning: right shift count is negative [-Wshift-count-negative]
  MAX(32, (ZS_MAX_PAGES_PER_ZSPAGE << PAGE_SHIFT >> OBJ_INDEX_BITS))
                                                 ^~
./include/uapi/linux/kernel.h:13:40: note: in definition of macro '__KERNEL_DIV_ROUND_UP'
 #define __KERNEL_DIV_ROUND_UP(n, d) (((n) + (d) - 1) / (d))
                                        ^
mm/zsmalloc.c:130:2: note: in expansion of macro 'MAX'
  MAX(32, (ZS_MAX_PAGES_PER_ZSPAGE << PAGE_SHIFT >> OBJ_INDEX_BITS))
  ^~~
mm/zsmalloc.c:148:59: note: in expansion of macro 'ZS_MIN_ALLOC_SIZE'
 #define ZS_SIZE_CLASSES (DIV_ROUND_UP(ZS_MAX_ALLOC_SIZE - ZS_MIN_ALLOC_SIZE, \
                                                           ^~~~~~~~~~~~~~~~~
mm/zsmalloc.c:253:32: note: in expansion of macro 'ZS_SIZE_CLASSES'
  struct size_class *size_class[ZS_SIZE_CLASSES];
                                ^~~~~~~~~~~~~~~
mm/zsmalloc.c:130:49: warning: right shift count is negative [-Wshift-count-negative]
  MAX(32, (ZS_MAX_PAGES_PER_ZSPAGE << PAGE_SHIFT >> OBJ_INDEX_BITS))
                                                 ^~
./include/uapi/linux/kernel.h:13:40: note: in definition of macro '__KERNEL_DIV_ROUND_UP'
 #define __KERNEL_DIV_ROUND_UP(n, d) (((n) + (d) - 1) / (d))
                                        ^
mm/zsmalloc.c:130:2: note: in expansion of macro 'MAX'
  MAX(32, (ZS_MAX_PAGES_PER_ZSPAGE << PAGE_SHIFT >> OBJ_INDEX_BITS))
  ^~~
mm/zsmalloc.c:148:59: note: in expansion of macro 'ZS_MIN_ALLOC_SIZE'
 #define ZS_SIZE_CLASSES (DIV_ROUND_UP(ZS_MAX_ALLOC_SIZE - ZS_MIN_ALLOC_SIZE, \
                                                           ^~~~~~~~~~~~~~~~~
mm/zsmalloc.c:253:32: note: in expansion of macro 'ZS_SIZE_CLASSES'
  struct size_class *size_class[ZS_SIZE_CLASSES];
                                ^~~~~~~~~~~~~~~
mm/zsmalloc.c:253:21: error: variably modified 'size_class' at file scope
  struct size_class *size_class[ZS_SIZE_CLASSES];
                     ^~~~~~~~~~
In file included from ./include/linux/kernel.h:10,
                 from ./include/linux/list.h:9,
                 from ./include/linux/module.h:9,
                 from mm/zsmalloc.c:33:
mm/zsmalloc.c: In function 'get_size_class_index':
mm/zsmalloc.c:130:49: warning: right shift count is negative [-Wshift-count-negative]
  MAX(32, (ZS_MAX_PAGES_PER_ZSPAGE << PAGE_SHIFT >> OBJ_INDEX_BITS))
                                                 ^~
./include/linux/compiler.h:76:40: note: in definition of macro 'likely'
 # define likely(x) __builtin_expect(!!(x), 1)
                                        ^
mm/zsmalloc.c:130:2: note: in expansion of macro 'MAX'
  MAX(32, (ZS_MAX_PAGES_PER_ZSPAGE << PAGE_SHIFT >> OBJ_INDEX_BITS))
  ^~~
mm/zsmalloc.c:540:20: note: in expansion of macro 'ZS_MIN_ALLOC_SIZE'
  if (likely(size > ZS_MIN_ALLOC_SIZE))
                    ^~~~~~~~~~~~~~~~~
```

**Pull request closed without merging**
