### PR TITLE
lf: update version pattern

### PR DESCRIPTION
**Pull request by TeddyDD**

### CODE REVIEW

**Comment by ericonr** [comment]
```diff
diff --git a/srcpkgs/lf/update b/srcpkgs/lf/update
index 48ff1d9d85..42dfad0fb8 100644
--- a/srcpkgs/lf/update
+++ b/srcpkgs/lf/update
@@ -1,2 +1,2 @@
-site='https://github.com/gokcehan/lf/releases'
-pattern='archive/\Kr\d+(?=\.tar\.gz)'
+pattern='\Kr\d+'
+ignore=r95
```

what do you think?

**Comment by ericonr** [comment]
Applied in 22e8730352110565c7059393d8d4d49b4f0f6d1b

**Comment by ericonr** [comment]
Thanks for bringing this up :)

**Comment by TeddyDD** [comment]
```
lf-r22 -> lf-r76
```

:rofl: 

Maybe we will use my pattern after all?

**Comment by ericonr** [comment]
Guh, I didn't get that when I tested it :/

Feel free to fix, then ;p

**Pull request closed without merging**
