### PR TITLE
next: rename to nyxt

### PR DESCRIPTION
**Pull request by egorenar**

### CODE REVIEW

**Comment by ericonr** [comment]
You need to make `next` a sub package of `nyxt` that depends on it, so people who have `next` installed will get the next `nyxt` update.

**Comment by egorenar** [comment]
> You need to make `next` a sub package of `nyxt` that depends on it, so people who have `next` installed will get the next `nyxt` update.

Not the other way around, nyxt a subpackage of next ?

**Comment by fosslinux** [comment]
No, next a subpackage of the renamed package or the "new" package nyxt.

**Comment by sgn** [comment]
Is this abandoned?

**Comment by egorenar** [comment]
not yet, please, i'll update it shortly

**Pull request closed without merging**
