### PR TITLE
libtool: fix include paths when cross compiling

### PR DESCRIPTION
**Pull request by oreo639**
#### Testing the changes
- I tested the changes in this PR: **briefly**

@dkwo Can you test this? (whenever you are available ofc)

### CODE REVIEW

**Comment by dkwo** [comment]
Thanks for looking into this. I've crossbuilt the package, I can install it on my aarch64 machine, but how do I make sure it is used in the build chroot when building ntl? I tried to build ntl in /tmp, but it fails before reaching that point.

**Comment by dkwo** [comment]
Thanks for looking into this. I've crossbuilt the package, I can install it on my aarch64 machine, but how do I make sure it is used in the build chroot when building ntl? I tried to build ntl in /tmp, but it fails before reaching that point.

**Comment by oreo639** [comment]
You can build libtool as cross, then build it as native, then replace the native package with the cross package in your `hostdir/binpkgs` and then try building ntl.

**Comment by dkwo** [comment]
Sure, will do it tomorrow.

**Comment by paper42** [comment]
native builds for aarch64-musl: https://vasilek.cz/repo/libtool/

**Comment by oreo639** [comment]
Thank you.

**Comment by dkwo** [comment]
> You can build libtool as cross, then build it as native, then replace the native package with the cross package in your `hostdir/binpkgs` and then try building ntl.

if I do that, it gives
`ERROR: libtool-2.4.7_2: SHA256 hash is not valid: Numerical result out of range`
Do you know how to fix this?

**Comment by oreo639** [comment]
You need to do `xbps-rindex -fa libtool-2.4.7_1.<arch>.xbps libltdl-2.4.7_1.<arch>.xbps libltdl-devel-2.4.7_1.<arch>.xbps`

**Comment by dkwo** [comment]
Thanks, now it errors out in a different way: https://paste.c-net.org/WedgedMopping

**Comment by oreo639** [comment]
Is this from the latest version of the branch, just checking?

**Comment by dkwo** [comment]
yes, it is.

**Comment by dkwo** [comment]
Shall we try the approach suggesged by @paper42 in https://github.com/void-linux/void-packages/issues/40980 at least for now?

**Comment by paper42** [comment]
> Shall we try the approach suggested by @paper42 in https://github.com/void-linux/void-packages/issues/40980 at least for now?

no, that's a hack that needs modifying xbps-src

**Comment by oreo639** [comment]
Alright, I think I see the issue.
`libtool: link: cc  -fPIC -DPIC -shared -nostdlib /usr/lib/../lib64/crti.o ...` is supposed to be `libtool: link: g++  -fPIC -DPIC -shared -nostdlib /usr/lib/../lib64/crti.o` 

That seems to be due to it being sed'ed to the form of `CC=${CC:=c++}` which is just a regular assignment when compiled natively.

The latest commit works for me, feel free to verify when you are available @dkwo

**Comment by dkwo** [comment]
It works :) Thanks for figuring this out!

**Pull request merged**
