### PR TITLE
fmt: update to 7.0.1

### PR DESCRIPTION
**Pull request by toluschr**

### CODE REVIEW

**Comment by ericonr** [comment]
You are missing a revbump for `kodi`. You can find it with `xrevshlib fmt`, from `xtools`.

**Comment by toluschr** [comment]
Didn't know about the xrevshlib and xrevbump tools.

**Comment by ahesford** [comment]
Please fix the `python_version` failure. The two files affected by `python_version` appear to be
```
/usr/share/kodi/addons/service.xbmc.versioncheck/service.py
/usr/share/kodi/addons/service.xbmc.versioncheck/lib/viewer.py
```
and, at first glance, appear to be compatible with Python 3. In that case, `python_version=3` is probably acceptable. If you know for a fact that these only work with Python 2, then remove the `#unverified` comment.

Looking at the files, it's not clear to me that they will even run; I don't see where the `xbmc`, `xbmcgui` or `xbmcaddon` modules are provided in any Void package. However, I am wholly unfamiliar with kodi.

**Comment by toluschr** [comment]
> Please fix the `python_version` failure. The two files affected by `python_version` appear to be
> 
> ```
> /usr/share/kodi/addons/service.xbmc.versioncheck/service.py
> /usr/share/kodi/addons/service.xbmc.versioncheck/lib/viewer.py
> ```
> 
> and, at first glance, appear to be compatible with Python 3. In that case, `python_version=3` is probably acceptable. If you know for a fact that these only work with Python 2, then remove the `#unverified` comment.
> 
> Looking at the files, it's not clear to me that they will even run; I don't see where the `xbmc`, `xbmcgui` or `xbmcaddon` modules are provided in any Void package. However, I am wholly unfamiliar with kodi.

I'm not sure what I should fix here, since this PR is for updating fmt and not fixing kodi. I don't even know what kodi is and how the template/build process works. Perhaps a new PR should be created.

**Comment by ahesford** [comment]
Since kodi has an shlib dependency on fmt, it is definitely necessary to revbump kodi in this PR. A package committer can decide whether `python_version` should be addressed now or can be deferred to a later kodi update.

**Comment by ericonr** [comment]
@Hoshpak seems to be the maintainer for Kodi

**Comment by ericonr** [comment]
@ahesford actually, https://github.com/void-linux/void-packages/pull/23040

**Comment by ahesford** [comment]
@ericonr, you're right. The right course of action here would be to leave `python_version=2` and remove the `#unverified` comment. Kodi 19 seems to bring py3 support.

**Pull request closed without merging**
