### PR TITLE
New package: linux5.12

### LINKED ISSUE #29394: Regression in Linux5.11? 4k resolution over displayport missing.
Hi! and apologies if this is nowhere near the correct forum to ask this (where might that be?). I noticed that upon upgrading to Linux5.11 from 5.10 that I could no longer use the maximum resolution of my external monitor. I can confirm that it does work on 5.9 and 5.10 (although for 5.10 it didn't once after a point upgrade so it seems a bit flaky).
### System

* xuname:
`Void 5.11.4_1 x86_64 GenuineIntel uptodate rFFF`
* packages: I don't know what may be the culprit so here's a bunch of them!
`linux5.11-5.11.4_1` (incl. headers)
`linux-firmware-intel-20210208_2`
`intel-media-driver-20.4.5_1`
`xf86-video-intel-2.99.917.20200515_1`
The same configuration works just fine on older kernels: `linux5.10-5.10.22_1` and `linux5.9-5.9.16_1`.
* /proc/cmdline if that is helpful
`BOOT_IMAGE=/boot/vmlinuz-5.11.4_1 root=/dev/mapper/void-root ro loglevel=4 init_on_free=1 rd.lvm.vg=void rd.luks.uuid=<uuid> resume=/dev/void/swap`

### Expected behavior
Using `xrandr`, the full resolution (3840x2160) of my external monitor should be visible.
This is how it looks on linux5.10-5.10.22_1.
```sh
xrandr
# snip
DP3 connected primary 3840x2160+0+0 (normal left inverted right x axis y axis) 600mm x 340mm
   3840x2160     60.00*+
   2560x1440     59.95  
   1920x1200     59.88  
   1920x1080     60.00    60.00    50.00    59.94    24.00    23.98  
   1920x1080i    60.00    50.00    59.94
# more output modes...
```

### Actual behavior
```sh
xrandr
# snip
DP3 connected (normal left inverted right x axis y axis)
   2560x1440     59.95  
   1920x1200     59.88  
   1920x1080     60.00    60.00    50.00    59.94    24.00    23.98  
   1920x1080i    60.00    50.00    59.94  
# more output modes...
```

### Steps to reproduce the behavior
Boot Linux5.11 and try to set the monitor resolution.
I have a laptop with a Intel Tiger Lake 1165G7 processor with integrated graphics. It is connected to a Dell P2715Q with Displayport over USB-C.

### PR DESCRIPTION
**Pull request by marmeladema**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

This is very much WIP. I have only updated the x86-64 and aarch64 arch config. I am not sure how to properly update the config for the other architectures. I haven't ported the ppc patches either.

This fixes #29394 for me

### CODE REVIEW

**Comment by marmeladema** [comment]
Updated to 5.12.5

**Comment by ericonr** [comment]
musl is known to be broken, it's a stupid issue with kernel drivers. I have a local fix for it, will send it your way later. I imagine it was accidental, but it should be fine to keep me as maintainer for this, since 5.11 is EOL anyway.

**Comment by marmeladema** [comment]
> I imagine it was accidental, but it should be fine to keep me as maintainer for this, since 5.11 is EOL anyway.
Yeah I just blindly copied the template of 5.11 as a starting point. I was not sure how maintainer-ship of a kernel version are decided.

**Comment by ahesford** [comment]
This package seems to work fine for me on `x86_64` and even supports my OLED backlight. For ZFS users, #31015 is a prerequisite.

**Comment by marmeladema** [comment]
Updated to 5.12.6

**Comment by marmeladema** [comment]
Added the relevant ppc patches from 5.11. Most of them were integrated upstream and only 2 remains.

**Comment by ericonr** [comment]
```
objtool is using the headers provided by kernel-libc-headers, which are kernel version 5.10, so
they use __always_inline instead of inline, and musl doesn't define __always_inline (glibc does)

diff --git a/tools/objtool/Makefile b/tools/objtool/Makefile
index 92ce4fc..d74b931 100644
--- a/tools/objtool/Makefile
+++ b/tools/objtool/Makefile
@@ -30,7 +30,7 @@ INCLUDES := -I$(srctree)/tools/include \
 	    -I$(srctree)/tools/objtool/include \
 	    -I$(srctree)/tools/objtool/arch/$(SRCARCH)/include
 WARNINGS := $(EXTRA_WARNINGS) -Wno-switch-default -Wno-switch-enum -Wno-packed -Wno-nested-externs
-CFLAGS   := -Werror $(WARNINGS) $(KBUILD_HOSTCFLAGS) -g $(INCLUDES) $(LIBELF_FLAGS)
+CFLAGS   := -Werror $(WARNINGS) $(KBUILD_HOSTCFLAGS) -g $(INCLUDES) $(LIBELF_FLAGS) -D__always_inline=inline
 LDFLAGS  += $(LIBELF_LIBS) $(LIBSUBCMD) $(KBUILD_HOSTLDFLAGS)
 
 # Allow old libelf to be used:
```

**Comment by marmeladema** [comment]
Added musl objtool patch

**Comment by marmeladema** [comment]
All configs have been updated. Its now ready for review.

**Comment by ericonr** [comment]
Thanks for working on this!

`x86_64` config is missing:

```diff
diff --git a/srcpkgs/linux5.12/files/x86_64-dotconfig b/srcpkgs/linux5.12/files/x86_64-dotconfig
index 13ca20506e..6252c0aa4f 100644
--- a/srcpkgs/linux5.12/files/x86_64-dotconfig
+++ b/srcpkgs/linux5.12/files/x86_64-dotconfig
@@ -6888,7 +6888,7 @@ CONFIG_HID_PICOLCD_LEDS=y
 CONFIG_HID_PICOLCD_CIR=y
 CONFIG_HID_PLANTRONICS=m
 CONFIG_HID_PLAYSTATION=m
-# CONFIG_PLAYSTATION_FF is not set
+CONFIG_PLAYSTATION_FF=y
 CONFIG_HID_PRIMAX=m
 # CONFIG_HID_RETRODE is not set
 CONFIG_HID_ROCCAT=m
```

**Pull request closed without merging**
