### PR TITLE
mpd: add shoutcast support

### PR DESCRIPTION
**Pull request by lxeiqr**
Enables libshout support in mpd by default

### CODE REVIEW

**Comment by ahesford** [comment]
@daniel-eys do you see any issue with adding a shoutcast build option, on by default?

**Comment by daniel-eys** [comment]
Thanks for tagging, wasn't aware of this pr.
I see no issues here building mpd with shoutcast support by default.
Then, this needs a revbump though.

**Comment by lxeiqr** [comment]
I'm sorry, but I don't use Void Linux on any of my computers at the moment. I can update the version, but someone else will have to check it out.

**Comment by daniel-eys** [comment]
Please update `checksum=` (sha256sum) as well. (and squash the commits into one)
I can confirm 0.21.25 working on x86_64.

**Comment by ahesford** [comment]
I'll finish this up and merge once it passes CI.

**Pull request closed without merging**
