### PR TITLE
New package: mutt-wizard-3.3.1

### PR DESCRIPTION
**Pull request by dataCobra**
#### Testing the changes
- I tested the changes in this PR: **NO**

As requested in issue #35330. I'll contact the person who requested the package and ask if they can test the PR.

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-musl (crossbuild)
  - armv7l (crossbuild)
  - armv6l-musl (crossbuild)

### CODE REVIEW

**Comment by paper42** [comment]
It's just a shell script, NACK from me

**Comment by dataCobra** [comment]
Hey @paper42,

could you explain what "NACK" means?

Prior to this PR there was a closed PR #35697.

**Comment by paper42** [comment]
Negative acknowledgement from networking terminology, it means I am against merging this PR. @classabbyamp seems to agree with me on this, so I will close this PR (and the issue) now.

**Comment by dataCobra** [comment]
Alright, thanks for letting me know. :+1:

**Pull request closed without merging**
