### PR TITLE
Remove package: imlib2-webp-1.0

### PR DESCRIPTION
**Pull request by mustaqimM**
No longer required as it is included since `imlib2-1.6.0` in the November update.

### CODE REVIEW

**Comment by Chocimier** [comment]
Make it transitional subpackage of imlib2.

**Comment by Piraty** [comment]
@mustaqimM ping

**Comment by mustaqimM** [comment]
I had to rebase the latest changes, now how do I remove the first commit so I can squash the rebase with my actual commit, I'm a little lost here

Is the transitional package correctly done?

**Comment by Chocimier** [comment]
> how do I remove the first commit

Use [git rebase -i](https://git-scm.com/docs/git-rebase#_interactive_mode), squash last commit into earlier one.

> Is the transitional package correctly done?

It won't build now because is empty, build_style=meta need to be added. And we want it to be transitional, this means depends on imlib2.

**Comment by Piraty** [comment]
fine to merge @Chocimier ?

**Comment by Chocimier** [comment]
Fine. Thanks @mustaqimM.

Btw, once done with changes, add a comment. Otherwise we don't know about changes, what delays review a lot.

**Pull request merged**
