### PR TITLE
vscode: update to 1.47.0.

### PR DESCRIPTION
**Pull request by GiorgiBeriashvili**
# Description

I had to adjust some settings locally to successfully build the software on my machine (I had `git not found` and other types of errors and had to comment out some lines of the template file), but in the end, it worked.

Since I presume that the official building process will be less error prone compared to mine, I decided to make this pull request.

The software itself runs without any glaring problems.

### CODE REVIEW

**Comment by atk** [comment]
The `git not found` error is due to vscode-1.47.0/build/npm/postinstall.js line 77. It can be removed with the line

```sh
sed -i -E "/cp\.execSync\('git config pull\.rebase true'\);/d" ${XBPS_BUILDDIR}/vscode-${version}/build/npm/postinstall.js
```
in the pre_build() part.

**Comment by GiorgiBeriashvili** [comment]
> The `git not found` error is due to vscode-1.47.0/build/npm/postinstall.js line 77. It can be removed with the line
> 
> ```sh
> sed -i -E "/cp\.execSync\('git config pull\.rebase true'\);/d" ${XBPS_BUILDDIR}/vscode-${version}/build/npm/postinstall.js
> ```
> in the pre_build() part.

Yes, and alongside that line, I also commented out the following:

`yarn install --ignore-engines --arch=x64`

And then it built VS Code locally without errors.

I am unsure if it is correct to uncomment those lines, though...

**Comment by ahesford** [comment]
If you're going to patch files, do the work in `post_patch` and then use relative paths like `build/npm/postinstall.js` because you'll already be inside `${wrksrc}` for `post_patch`.

**Comment by ahesford** [comment]
Also, please reconcile with #23129.

**Comment by GiorgiBeriashvili** [comment]
> Also, please reconcile with #23129.

My bad, I had not seen it before. I will close this PR, then.

**Pull request closed without merging**
