### PR TITLE
openrazer-meta: update to 3.5.1.

### PR DESCRIPTION
**Pull request by z3ntu**
This release contains a fix for a moderate security issue.

#### Testing the changes
- I tested the changes in this PR: **NO**

### CODE REVIEW

**Comment by z3ntu** [comment]
@dmarto As I don't use Void Linux, could you take over maintainer for this package? I see that you updated the package multiple times already.

**Comment by dmarto** [comment]
@z3ntu sure, let me test it and in the meantime feel free to put me (`Martin Dimov <martin@dmarto.com>"`) as maintainer or I can do it on the next release :)

**Comment by dmarto** [comment]
I have finished testing, all works well :)

**Comment by z3ntu** [comment]
Can someone merge this then?

**Pull request closed without merging**
