### PR TITLE
mkinitcpio: update to 30, add mkinitcpio-zfs subpackage

### PR DESCRIPTION
**Pull request by ahesford**
ZFS hooks taken from [1] and modified to include /etc/hostid.

The version bump should be straightforward, but my ZFS-enabled image failed to boot. This needs more testing to make sure we can create usable initramfs images.

[1] https://github.com/archzfs/archzfs/tree/master/src/zfs-utils

### CODE REVIEW

**Comment by ericonr** [comment]
See https://github.com/void-linux/void-packages/pull/29062#issuecomment-786219523

And could we fetch these new files instead of vendoring them in?

**Comment by ahesford** [comment]
Compression is not the issue I'm having. I tried gzip and no compression (`compression=cat`) but haven't yet been able to boot with these images.

I thought about fetching the ZFS hook files rather than keeping them in tree, but I am already patching to pull in `/etc/hostid` and am giving thought to some other changes. (For now, the only definite change I'm thinking about is dropping their `zfs=pool/file/system` syntax for root specifications and moving to the dracut-style `root=zfs:pool/file/system` so that mkinitcpio and dracut images can be interchangeable. As we may evolve these further, it's probably easier just to take ownership.

**Comment by ahesford** [comment]
OK, this now boots my ZFS setup and should be ready to merge.

New changes:
1. ZFS hook recognize `root=zfs:` Dracut syntax.
2. ZFS hook imports pools `rw` by default.
3. Package tests work.
4. Kernel hook sets `umask 0077` because some setups (like that recommended by ZFSBootMenu) may place in the initramfs image secrets that should not be accessible to non-root users.
5. `mkinitcpio-udev` has been dropped and merged with `mkinitcpio`. As upstream strongly advises against disabling the `udev` hook, there is no reason to separate this hook into a standalone package.

**Comment by ahesford** [comment]
I've incorporated changes recommended by @ericonr  in #29062.

@thypon, do you have any objections to the changes in this PR?

**Comment by thypon** [comment]
Newer mkinitcpio removed support for older kernel. It should not be a huge problem, but we were waiting for the update for this reason.

**Comment by ahesford** [comment]
Do you mean with the zstd switch? I added a patch to use gzip by default.

**Comment by thypon** [comment]
Ah, I did not saw the gzip patch. Yep, it should work with that patch.

Do you think that managing mkinitcpio-zfs inside the main package is a good idea? Maybe outside should work too.

**Comment by ahesford** [comment]
What is the benefit of separating the zfs modules? Keeping them in one place is consistent with the other subpackages where we install our own hooks and keeps the versioning consistent.

**Comment by thypon** [comment]
I'm not completely against. But if I'm required to update that package it means I should test on `zfs` which I don't have on my systems.

**Comment by ahesford** [comment]
I'll leave it to you. If you prefer having it separated, I can separate it. Otherwise, let's leave it together.

**Comment by thypon** [comment]
It's ok. I will create a VM to test that particular case, in the future.

**Pull request merged**
