### PR TITLE
cmus: update to 2.11.0

### PR DESCRIPTION
**Pull request by MIvanchev**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (X86_64-GLIBC)

### CODE REVIEW

**Comment by Vinfall** [comment]
~~Does it work for ffmpeg4? I thought #43761 is needed for the update. Upstream has https://github.com/cmus/cmus/pull/1330 to fix ffmpeg.so as well.~~

Never mind, testing this PR and it works just fine.

**Comment by classabbyamp** [comment]
ffmpeg6 is imminent so let's just wait for that

**Comment by classabbyamp** [comment]
ok, this can be switched to ffmpeg6 now

**Comment by MIvanchev** [comment]
>ok, this can be switched to ffmpeg6 now

Builds fine.

**Pull request merged**
