### PR TITLE
perl-PerlIO-utf8-strict: rename to perl-PerlIO-utf8_strict

### PR DESCRIPTION
**Pull request by svenper**
(final dash to underscore)
since #14005 was fixed

### CODE REVIEW

**Comment by Chocimier** [comment]
Provides+replaces won't work. I also think troubles with renaming package are not worth it.

**Comment by svenper** [comment]
I already went through the trouble... :laughing: Unless renames create some additional repo work for you? Why wouldn't provides+replaces work?
```text
# xbps-install --repository=/var/cache/xbps-src/binpkgs/perl-PerlIO-utf8_strict -u

Name                    Action    Version           New version            Download size
perl-PerlIO-utf8-strict remove    0.007_1           -                      -
perl-PerlIO-utf8_strict install   -                 0.007_1                -
```

**Comment by Chocimier** [comment]
Hmm, provides+replaces works good enough for package that is installed as dependency.

**Comment by svenper** [comment]
When would it not work?

```text
$ xbps-query -p automatic-install perl-PerlIO-utf8-strict
no
# xbps-install --repository=/var/cache/xbps-src/binpkgs/perl-PerlIO-utf8_strict -u

Name                    Action    Version           New version            Download size
perl-PerlIO-utf8-strict remove    0.007_1           -                      -
perl-PerlIO-utf8_strict install   -                 0.007_1                -
```

**Comment by Chocimier** [comment]
Package won't be updated if was installed manually. And if it is only ever installed as dependency, name does not matter.

**Pull request closed without merging**
