### PR TITLE
libcec: update to 6.0.2

### PR DESCRIPTION
**Pull request by ndowens**

### CODE REVIEW

**Comment by ericonr** [comment]
There's kodi-rpi as well. Would you mind testing kodi with #25922  ?

**Comment by ndowens** [comment]
> There's kodi-rpi as well. Would you mind testing kodi with #25922 ?

Hmm I can, also I did xbps-query -RX libcec and it only showed kodi, not kodi-rpi, so didn't think it would have to be.

**Comment by ericonr** [comment]
`kodi-rpi` isn't available on x86_64, so it doesn't show up in xbps-query.

**Comment by ndowens** [comment]
> `kodi-rpi` isn't available on x86_64, so it doesn't show up in xbps-query.

gottcha, I will bump it too, but wouldn't be able to test; Currently working on testing out kodi with libcec and your PR

**Comment by ericonr** [comment]
@Hoshpak might be able to do it.

**Comment by ndowens** [comment]
@ericonr tested with your fmt PR and it built fine

**Comment by ericonr** [comment]
Did it also run ok? That's actually the one I was the most worried about :P

**Comment by ndowens** [comment]
> Did it also run ok? That's actually the one I was the most worried about :P
> 
> Sorry for not specifying.

kodi launched for me and from what i can tell is fine. Tested audio on it and played fine and no crash

**Pull request merged**
