### PR TITLE
Update nss to 3.86

### PR DESCRIPTION
**Pull request by crtxcr**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

CC @sgn

### CODE REVIEW

**Comment by sgn** [comment]
Did you run the full test-suite before submitting? Just asking since those commit was made 20 minutes ago!

**Comment by sgn** [comment]
FWIW, I have nss update in my backlog already.

**Comment by crtxcr** [comment]
>Did you run the full test-suite before submitting? Just asking since those commit was made 20 minutes ago!

I admit I didn't run the tests. I must have missed it in the contributions guidelines (where I see now it says it's encouraged, not required), But anyway, as I plan to contribute in the future, I have now set it to XBPS_CHECK_PKGS=yes. Which  isn't =full, but for this template would not make a difference aiui.

I am just new to void trying to help out here and there. So thanks for making me aware of that!

Now, what it do though is perform a basic runtime check with Firefox, Thunderbird simply by using TLS connections.

For what's it worth, I did run the tests now. All of them have have passed. I see they have failed in the CI for x86_64, but that seems normal for NSS juding from prior PRs.

```
Tests summary:
--------------
Passed:             81692
Failed:             0
Failed with core:   0
ASan failures:      0
Unknown status:     2
TinderboxPrint:Unknown: 2
```

>FWIW, I have nss update in my backlog already.

Good to know. I figured this PR could't hurt as nss was 3 versions behind and because this one blacklists a CA.

**Comment by sgn** [comment]
> > Did you run the full test-suite before submitting? Just asking since those commit was made 20 minutes ago!
> 
> I admit I didn't run the tests. I must have missed it in the contributions guidelines (where I see now it says it's encouraged, not required)

NSS is critical security software in modern system, its test suite needs to run in full before submitting (I would prefer if people left it to me).

> Good to know. I figured this PR could't hurt as nss was 3 versions behind and because this one blacklists a CA.

NSS was never 3 versions behind. Only `ca-certificates` uses certificates from 3-version-behind-nss since last 3 versions of nss doesn't update CA certificates list. It's pointless to update them.

**Pull request merged**
