### PR TITLE
New package: dotnet-sdk-bin-3.1.102

### PR DESCRIPTION
**Pull request by tesfaye**
Related #10989

### CODE REVIEW

**Comment by Anachron** [comment]
Please squash your commits.

**Comment by Anachron** [comment]
This package works, we should at least mention in a `INSTALL.msg` file that we need a `DOTNET_ROOT=/usr/lib/dotnet` env variable in order to make DOTNET applications find `dotnet`.

**Comment by tesfaye** [comment]
Instead of setting DOTNET_ROOT, we could could store the install directory in /etc/dotnet/install_location.

https://docs.microsoft.com/en-us/dotnet/core/distribution-packaging

**Comment by Anachron** [comment]
Yes, will you do that?

**Comment by tesfaye** [comment]
Unfortunately, I'm not really able to work on it at the given moment. So, I'll close this and see what others are able to do.

**Pull request closed without merging**
