### PR TITLE
Updated to sway v. 1.0-beta.2

### PR DESCRIPTION
**Pull request by gemath**

### CODE REVIEW

**Comment by maxice8** [comment]
Release notes tells us to not package this release. https://github.com/swaywm/sway/releases

**Comment by gemath** [comment]
Oops, sry. Didn't see that. Works like a charm..

**Comment by gemath** [comment]
BTW: does xbps support some script to be automatically run after package installation?

**Comment by maxice8** [comment]
On Mon, Dec 31, 2018 at 02:03:05PM -0800, gemath wrote:
> BTW: does xbps support some script to be automatically run after package installation?
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/6401#issuecomment-450694139

see install_remove_files on Manual.md

**Pull request closed without merging**
