### PR TITLE
firefox: update to 100.0.2

### PR DESCRIPTION
**Pull request by anscarius**
[ci skip]

This update fixes recently discovered vulnerabilities: https://www.mozilla.org/en-US/security/advisories/mfsa2022-19/

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by voltar13** [comment]
I think that this should be build-tested also for other platforms listed in the last firefox PR from @Duncaen (x86_64-musl aarch64-musl i686).
I'm also working on this but unfortunately, while I'm cross-compiling, I'm having issue with ccache/buildscript, which makes the build fail, even though I was able to build it for my native platform without any issues.
This is a known bug that apparently has been fixed https://bugzilla.mozilla.org/show_bug.cgi?id=1766081. I've tried to locally apply the fix to the `/python/mozbuild/mozbuild/controller/building.py`, but without much luck.

**Comment by anscarius** [comment]
I tried cross compiling as suggested by @voltar13, and got the same ccache/buildscript error, so I applied the linked patch. That seemed to solve that issue, but another one has popped up.

```
13:33.34 error: build failed
13:33.37 make[4]: *** [/builddir/firefox-100.0.2/config/makefiles/rust.mk:425: force-cargo-library-build] Error 101
13:33.37 make[3]: *** [/builddir/firefox-100.0.2/config/recurse.mk:72: toolkit/library/rust/target] Error 2
13:33.37 make[2]: *** [/builddir/firefox-100.0.2/config/recurse.mk:34: compile] Error 2
13:33.37 make[1]: *** [/builddir/firefox-100.0.2/config/rules.mk:352: default] Error 2
13:33.37 make: *** [client.mk:63: build] Error 2
13:33.39 607 compiler warnings present.
 Config object not found by mach.
Configure complete!
Be sure to run |mach build| to pick up any changes
=> ERROR: firefox-100.0.2_1: do_build: './mach build' exited with 2
=> ERROR:   in do_build() at srcpkgs/firefox/template:191
```

**Comment by Duncaen** [comment]
That is not enough context to see the error.

**Comment by anscarius** [comment]
This is the full log of the packaging attempt, I ran it as
`./xbps-src -a x86_64-musl -j$(nproc) pkg firefox`

[firefox-x86_64-musl.log](https://github.com/void-linux/void-packages/files/8791518/firefox-x86_64-musl.log)

**Comment by Duncaen** [comment]
Works fine, you should be using a musl masterdir when cross compiling with musl.

**Comment by anscarius** [comment]
Got it, will keep it in mind for next time. Thanks!

**Pull request merged**
