### PR TITLE
memcached: update to 1.5.19.

### PR DESCRIPTION
**Pull request by ailiop-git**

### CODE REVIEW

**Comment by Piraty** [comment]
can you fix crosscompilation?

**Comment by q66** [comment]
how about not removing patches that still work and are required? `termios.patch` is still necessary and applies perfectly fine.

**Comment by ailiop-git** [comment]
> how about not removing patches that still work and are required? `termios.patch` is still necessary and applies perfectly fine.

Sorry, but it's not clear why the patch is necessary, since the pkg builds cleanly. Not even sure why this was needed there in the first place, as TCGETS is already defined and included via sys/ioctl.h. 

Could you elaborate?

**Comment by q66** [comment]
It's necessary at least on `ppc64le`, for the reason already written in the patch. Not every architecture has the same set of includes everywhere.

**Comment by q66** [comment]
https://github.com/torvalds/linux/blob/master/arch/powerpc/include/uapi/asm/ioctls.h#L21

**Comment by ailiop-git** [comment]
> It's necessary at least on `ppc64le`, for the reason already written in the patch. Not every architecture has the same set of includes everywhere.

Since ppc64le is not officially supported or built, couldn't possibly have guessed that this is necessary. I'd suggest making the reason more explicit in the commit msg and/or patch header to avoid any confusion in the future.

Why also not upstream the fix to memcached? It's clearly not a distro-specific thing.

**Comment by q66** [comment]
Or you could check who added the patch and mention them in your PR when unsure, especially considering they're around all the time and it costs little extra effort ;)

Anyway

https://github.com/memcached/memcached/pull/583

**Comment by ailiop-git** [comment]
> Or you could check who added the patch and mention them in your PR when unsure, especially considering they're around all the time and it costs little extra effort ;)

Since the absence of the patch wasn't causing any failures on any of the official builds (and there was nothing specific in the patch description other than a build failure), there was really no uncertainty for a question to be raised. We have many packages (especially the orphaned ones) that have been unmaintained for a while and include a lot of stale/uncessary patches that should have been removed.

Thank you for submitting the fix upstream! I think we should strive for keeping the srcpkgs as clean and close to upstream as possible in general, and only deviate when absolutely necessary (and temporarily, until upstream releases the fixes).

**Comment by q66** [comment]
When a patch has been added recently enough and it still applies after an update, that's enough of a reason to question it. Especially when it means very little effort from the submitter's side, but saves time for the person who has to deal with the failures later.

Keeping srcpkgs completely clean is impossible. Upstreams will frequently ignore fixes for minority architectures as well as musl libc. Not sure if in this specific case, but it happens a lot otherwise.

**Pull request merged**
