### PR TITLE
libGL: update to 18.1.7.

### PR DESCRIPTION
**Pull request by maxice8**
@q66

### CODE REVIEW

**Comment by newbluemoon** [comment]
Did some testing on x86_64-musl, mesa-ati-dri:

* Xorg, firefox, falkon, mpv, and vlc worked without problems
* some games: teeworlds, tesseract are fine, too
* xonotic segfaults; still after a rebuild (can post a gdb backtrace if required)
* qutebrowser fails: `Fatal Python error: Segmentation fault`
  depends on python3-PyQt5-opengl, so tried a rebuild of python-PyQt5 to no avail

Both xonotic and qutebrowser work with 18.6.1.

**Comment by newbluemoon** [comment]
Yes, I deleted `~/.cache/mesa_shader_cache`.

**Comment by newbluemoon** [comment]
gdb backtrace for qutebrowser (if that’s any help):

```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
__glXSetupForCommand (dpy=0x555555fee840) at ../src/glx/glxext.c:985
985	../src/glx/glxext.c: No such file or directory.
(gdb) bt
#0  __glXSetupForCommand (dpy=0x555555fee840) at ../src/glx/glxext.c:985
#1  0x00007fffe902340a in glx_context_init (gc=gc@entry=0x5555561b0660, psc=psc@entry=0x55555603db20, config=config@entry=0x55555615eb80)
    at ../src/glx/glxcmds.c:262
#2  0x00007fffe903822f in dri3_create_context_attribs (base=0x55555603db20, config_base=0x55555615eb80, shareList=<optimized out>, 
    num_attribs=<optimized out>, attribs=<optimized out>, error=0x7fffffffd434) at ../src/glx/dri3_glx.c:277
#3  0x00007fffe90202ba in glXCreateContextAttribsARB (dpy=0x555555fee840, config=config@entry=0x55555615eb80, share_context=0x0, direct=direct@entry=1, 
    attrib_list=0x5555561b0e38) at ../src/glx/create_context.c:78
#4  0x00007fffd1100e79 in QGLXContext::init (this=0x55555603a580, screen=0x5555560222c0, share=<optimized out>) at qglxintegration.cpp:284
#5  0x00007fffd10fee67 in QXcbGlxIntegration::createPlatformOpenGLContext (this=<optimized out>, context=0x555555a98b60) at qxcbglxintegration.cpp:185
#6  0x00007fffd36aa4e1 in QXcbIntegration::createPlatformOpenGLContext (this=<optimized out>, context=0x555555a98b60) at qxcbintegration.cpp:279
#7  0x00007fffe95eca4f in QOpenGLContext::create (this=0x555555a98b60) at kernel/qopenglcontext.cpp:612
#8  0x00007fffe3da524c in QtWebEngineCore::initialize() () from /usr/lib/libQt5WebEngineCore.so.5
#9  0x00007ffff0d3bab7 in qt_call_pre_routines () at kernel/qcoreapplication.cpp:330
#10 QCoreApplicationPrivate::init (this=this@entry=0x555555ffa600) at kernel/qcoreapplication.cpp:868
#11 0x00007fffe95a9d2f in QGuiApplicationPrivate::init (this=this@entry=0x555555ffa600) at kernel/qguiapplication.cpp:1346
#12 0x00007fffe9da5359 in QApplicationPrivate::init (this=0x555555ffa600) at kernel/qapplication.cpp:576
#13 0x00007fffe6952ba9 in sipQApplication::sipQApplication (this=0x555555fbac00, a0=<optimized out>, a1=<optimized out>, a2=<optimized out>)
    at sipQtWidgetsQApplication.cpp:189
#14 0x00007fffe6952c83 in init_type_QApplication (sipSelf=0x7fffd3dd98b8, sipArgs=<optimized out>, sipKwds=<optimized out>, sipUnused=<optimized out>, 
    sipParseErr=<optimized out>) at /builddir/PyQt5_gpl-5.10.1/pyqt5-3.6/sip/QtWidgets/qapplication.sip:221
#15 0x00007fffed714e84 in ?? () from /usr/lib/python3.6/site-packages/sip.so
#16 0x00007ffff793c7dc in wrap_init (self=<optimized out>, args=<optimized out>, wrapped=<optimized out>, kwds=<optimized out>) at Objects/typeobject.c:5664
#17 0x00007ffff78e4a49 in _PyObject_FastCallDict (func=0x7fffd3d6bb70, args=<optimized out>, nargs=<optimized out>, kwargs=kwargs@entry=0x0)
    at Objects/abstract.c:2331
#18 0x00007ffff78e4ff1 in _PyObject_FastCallKeywords (func=func@entry=0x7fffd3d6bb70, stack=<optimized out>, nargs=nargs@entry=1, kwnames=kwnames@entry=0x0)
    at Objects/abstract.c:2496
#19 0x00007ffff799e3ba in call_function (pp_stack=pp_stack@entry=0x7fffffffda88, oparg=<optimized out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4854
#20 0x00007ffff79a1137 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3328
#21 0x00007ffff799e0b6 in _PyEval_EvalCodeWithName (_co=_co@entry=0x7fffe62b9420, globals=globals@entry=0x7fffed64f1f8, locals=locals@entry=0x0, 
    args=args@entry=0x7fffffffdd30, argcount=argcount@entry=2, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, 
    closure=0x7fffd47acb70, name=0x7ffff7fb8270, qualname=0x7fffe62b6a98) at Python/ceval.c:4159
#22 0x00007ffff79a61d9 in _PyFunction_FastCallDict (func=func@entry=0x7fffd3d84950, args=args@entry=0x7fffffffdd30, nargs=2, kwargs=kwargs@entry=0x0)
    at Python/ceval.c:5063
#23 0x00007ffff78e4b0e in _PyObject_FastCallDict (func=func@entry=0x7fffd3d84950, args=args@entry=0x7fffffffdd30, nargs=nargs@entry=2, 
    kwargs=kwargs@entry=0x0) at Objects/abstract.c:2310
#24 0x00007ffff78e4d1c in _PyObject_Call_Prepend (func=0x7fffd3d84950, obj=<optimized out>, args=0x7ffff3e4a978, kwargs=0x0) at Objects/abstract.c:2373
#25 0x00007ffff78e48d8 in PyObject_Call (func=0x7ffff7fa7948, args=<optimized out>, kwargs=<optimized out>) at Objects/abstract.c:2261
#26 0x00007ffff7943e6c in slot_tp_init (self=<optimized out>, args=0x7ffff3e4a978, kwds=0x0) at Objects/typeobject.c:6407
#27 0x00007ffff79404e2 in type_call (type=<optimized out>, type@entry=0x555555eef0b8, args=args@entry=0x7ffff3e4a978, kwds=kwds@entry=0x0)
    at Objects/typeobject.c:915
#28 0x00007ffff78e4a49 in _PyObject_FastCallDict (func=0x555555eef0b8, args=<optimized out>, nargs=<optimized out>, kwargs=kwargs@entry=0x0)
    at Objects/abstract.c:2331
#29 0x00007ffff78e4ff1 in _PyObject_FastCallKeywords (func=func@entry=0x555555eef0b8, stack=<optimized out>, nargs=nargs@entry=1, kwnames=kwnames@entry=0x0)
    at Objects/abstract.c:2496
#30 0x00007ffff799e3ba in call_function (pp_stack=pp_stack@entry=0x7fffffffdf78, oparg=<optimized out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4854
#31 0x00007ffff79a1137 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3328
#32 0x00007ffff799d6cf in _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=1, globals=<optimized out>) at Python/ceval.c:4912
#33 0x00007ffff799e326 in fast_function (func=<optimized out>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Python/ceval.c:4954
#34 0x00007ffff799e465 in call_function (pp_stack=pp_stack@entry=0x7fffffffe118, oparg=<optimized out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4851
#35 0x00007ffff79a1137 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3328
#36 0x00007ffff799d6cf in _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=0, globals=<optimized out>) at Python/ceval.c:4912
#37 0x00007ffff799e326 in fast_function (func=<optimized out>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Python/ceval.c:4954
#38 0x00007ffff799e465 in call_function (pp_stack=pp_stack@entry=0x7fffffffe2b8, oparg=<optimized out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4851
#39 0x00007ffff79a1137 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3328
#40 0x00007ffff799e0b6 in _PyEval_EvalCodeWithName (_co=_co@entry=0x7ffff7f26810, globals=globals@entry=0x7ffff7f6b048, locals=locals@entry=0x7ffff7f6b048, 
    args=args@entry=0x0, argcount=argcount@entry=0, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, 
    closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:4159
#41 0x00007ffff799e60e in PyEval_EvalCodeEx (_co=_co@entry=0x7ffff7f26810, globals=globals@entry=0x7ffff7f6b048, locals=locals@entry=0x7ffff7f6b048, 
    args=args@entry=0x0, argcount=argcount@entry=0, kws=kws@entry=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:4180
#42 0x00007ffff799e63b in PyEval_EvalCode (co=co@entry=0x7ffff7f26810, globals=globals@entry=0x7ffff7f6b048, locals=locals@entry=0x7ffff7f6b048)
    at Python/ceval.c:731
#43 0x00007ffff79c7740 in run_mod (mod=mod@entry=0x5555557d6538, filename=filename@entry=0x7ffff7ea8390, globals=globals@entry=0x7ffff7f6b048, 
    locals=locals@entry=0x7ffff7f6b048, flags=flags@entry=0x7fffffffe5fc, arena=arena@entry=0x7ffff7f86150) at Python/pythonrun.c:1025
#44 0x00007ffff79c9b11 in PyRun_FileExFlags (fp=fp@entry=0x5555557d58a0, filename_str=filename_str@entry=0x7ffff7f258d8 "/usr/bin/qutebrowser", 
    start=start@entry=257, globals=globals@entry=0x7ffff7f6b048, locals=locals@entry=0x7ffff7f6b048, closeit=closeit@entry=1, flags=0x7fffffffe5fc)
    at Python/pythonrun.c:978
#45 0x00007ffff79c9c5f in PyRun_SimpleFileExFlags (fp=fp@entry=0x5555557d58a0, filename=<optimized out>, closeit=closeit@entry=1, 
    flags=flags@entry=0x7fffffffe5fc) at Python/pythonrun.c:420
#46 0x00007ffff79ca083 in PyRun_AnyFileExFlags (fp=fp@entry=0x5555557d58a0, filename=<optimized out>, closeit=closeit@entry=1, 
    flags=flags@entry=0x7fffffffe5fc) at Python/pythonrun.c:81
#47 0x00007ffff79e05a0 in run_file (p_cf=0x7fffffffe5fc, 
    filename=0x7ffff7878e00 L"\057\165\163\162\057\142\151\156\057\161\165\164\145\142\162\157\167\163\145\162", fp=0x5555557d58a0) at Modules/main.c:340
#48 Py_Main (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:810
#49 0x0000555555554a6e in main (argc=2, argv=<optimized out>) at ./Programs/python.c:69
```

**Comment by maxice8** [comment]
On Sat, Aug 25, 2018 at 10:57:12AM -0700, newbluemoon wrote:
> gdb backtrace for qutebrowser (if that’s any help):
> 
> ```
> Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
> __glXSetupForCommand (dpy=0x555555fee840) at ../src/glx/glxext.c:985
> 985	../src/glx/glxext.c: No such file or directory.
> (gdb) bt
> #0  __glXSetupForCommand (dpy=0x555555fee840) at ../src/glx/glxext.c:985
> #1  0x00007fffe902340a in glx_context_init (gc=gc@entry=0x5555561b0660, psc=psc@entry=0x55555603db20, config=config@entry=0x55555615eb80)
>     at ../src/glx/glxcmds.c:262
> #2  0x00007fffe903822f in dri3_create_context_attribs (base=0x55555603db20, config_base=0x55555615eb80, shareList=<optimized out>, 
>     num_attribs=<optimized out>, attribs=<optimized out>, error=0x7fffffffd434) at ../src/glx/dri3_glx.c:277
> #3  0x00007fffe90202ba in glXCreateContextAttribsARB (dpy=0x555555fee840, config=config@entry=0x55555615eb80, share_context=0x0, direct=direct@entry=1, 
>     attrib_list=0x5555561b0e38) at ../src/glx/create_context.c:78
> #4  0x00007fffd1100e79 in QGLXContext::init (this=0x55555603a580, screen=0x5555560222c0, share=<optimized out>) at qglxintegration.cpp:284
> #5  0x00007fffd10fee67 in QXcbGlxIntegration::createPlatformOpenGLContext (this=<optimized out>, context=0x555555a98b60) at qxcbglxintegration.cpp:185
> #6  0x00007fffd36aa4e1 in QXcbIntegration::createPlatformOpenGLContext (this=<optimized out>, context=0x555555a98b60) at qxcbintegration.cpp:279
> #7  0x00007fffe95eca4f in QOpenGLContext::create (this=0x555555a98b60) at kernel/qopenglcontext.cpp:612
> #8  0x00007fffe3da524c in QtWebEngineCore::initialize() () from /usr/lib/libQt5WebEngineCore.so.5
> #9  0x00007ffff0d3bab7 in qt_call_pre_routines () at kernel/qcoreapplication.cpp:330
> #10 QCoreApplicationPrivate::init (this=this@entry=0x555555ffa600) at kernel/qcoreapplication.cpp:868
> #11 0x00007fffe95a9d2f in QGuiApplicationPrivate::init (this=this@entry=0x555555ffa600) at kernel/qguiapplication.cpp:1346
> #12 0x00007fffe9da5359 in QApplicationPrivate::init (this=0x555555ffa600) at kernel/qapplication.cpp:576
> #13 0x00007fffe6952ba9 in sipQApplication::sipQApplication (this=0x555555fbac00, a0=<optimized out>, a1=<optimized out>, a2=<optimized out>)
>     at sipQtWidgetsQApplication.cpp:189
> #14 0x00007fffe6952c83 in init_type_QApplication (sipSelf=0x7fffd3dd98b8, sipArgs=<optimized out>, sipKwds=<optimized out>, sipUnused=<optimized out>, 
>     sipParseErr=<optimized out>) at /builddir/PyQt5_gpl-5.10.1/pyqt5-3.6/sip/QtWidgets/qapplication.sip:221
> #15 0x00007fffed714e84 in ?? () from /usr/lib/python3.6/site-packages/sip.so
> #16 0x00007ffff793c7dc in wrap_init (self=<optimized out>, args=<optimized out>, wrapped=<optimized out>, kwds=<optimized out>) at Objects/typeobject.c:5664
> #17 0x00007ffff78e4a49 in _PyObject_FastCallDict (func=0x7fffd3d6bb70, args=<optimized out>, nargs=<optimized out>, kwargs=kwargs@entry=0x0)
>     at Objects/abstract.c:2331
> #18 0x00007ffff78e4ff1 in _PyObject_FastCallKeywords (func=func@entry=0x7fffd3d6bb70, stack=<optimized out>, nargs=nargs@entry=1, kwnames=kwnames@entry=0x0)
>     at Objects/abstract.c:2496
> #19 0x00007ffff799e3ba in call_function (pp_stack=pp_stack@entry=0x7fffffffda88, oparg=<optimized out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4854
> #20 0x00007ffff79a1137 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3328
> #21 0x00007ffff799e0b6 in _PyEval_EvalCodeWithName (_co=_co@entry=0x7fffe62b9420, globals=globals@entry=0x7fffed64f1f8, locals=locals@entry=0x0, 
>     args=args@entry=0x7fffffffdd30, argcount=argcount@entry=2, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, 
>     closure=0x7fffd47acb70, name=0x7ffff7fb8270, qualname=0x7fffe62b6a98) at Python/ceval.c:4159
> #22 0x00007ffff79a61d9 in _PyFunction_FastCallDict (func=func@entry=0x7fffd3d84950, args=args@entry=0x7fffffffdd30, nargs=2, kwargs=kwargs@entry=0x0)
>     at Python/ceval.c:5063
> #23 0x00007ffff78e4b0e in _PyObject_FastCallDict (func=func@entry=0x7fffd3d84950, args=args@entry=0x7fffffffdd30, nargs=nargs@entry=2, 
>     kwargs=kwargs@entry=0x0) at Objects/abstract.c:2310
> #24 0x00007ffff78e4d1c in _PyObject_Call_Prepend (func=0x7fffd3d84950, obj=<optimized out>, args=0x7ffff3e4a978, kwargs=0x0) at Objects/abstract.c:2373
> #25 0x00007ffff78e48d8 in PyObject_Call (func=0x7ffff7fa7948, args=<optimized out>, kwargs=<optimized out>) at Objects/abstract.c:2261
> #26 0x00007ffff7943e6c in slot_tp_init (self=<optimized out>, args=0x7ffff3e4a978, kwds=0x0) at Objects/typeobject.c:6407
> #27 0x00007ffff79404e2 in type_call (type=<optimized out>, type@entry=0x555555eef0b8, args=args@entry=0x7ffff3e4a978, kwds=kwds@entry=0x0)
>     at Objects/typeobject.c:915
> #28 0x00007ffff78e4a49 in _PyObject_FastCallDict (func=0x555555eef0b8, args=<optimized out>, nargs=<optimized out>, kwargs=kwargs@entry=0x0)
>     at Objects/abstract.c:2331
> #29 0x00007ffff78e4ff1 in _PyObject_FastCallKeywords (func=func@entry=0x555555eef0b8, stack=<optimized out>, nargs=nargs@entry=1, kwnames=kwnames@entry=0x0)
>     at Objects/abstract.c:2496
> #30 0x00007ffff799e3ba in call_function (pp_stack=pp_stack@entry=0x7fffffffdf78, oparg=<optimized out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4854
> #31 0x00007ffff79a1137 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3328
> #32 0x00007ffff799d6cf in _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=1, globals=<optimized out>) at Python/ceval.c:4912
> #33 0x00007ffff799e326 in fast_function (func=<optimized out>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Python/ceval.c:4954
> #34 0x00007ffff799e465 in call_function (pp_stack=pp_stack@entry=0x7fffffffe118, oparg=<optimized out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4851
> #35 0x00007ffff79a1137 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3328
> #36 0x00007ffff799d6cf in _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=0, globals=<optimized out>) at Python/ceval.c:4912
> #37 0x00007ffff799e326 in fast_function (func=<optimized out>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Python/ceval.c:4954
> #38 0x00007ffff799e465 in call_function (pp_stack=pp_stack@entry=0x7fffffffe2b8, oparg=<optimized out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4851
> #39 0x00007ffff79a1137 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3328
> #40 0x00007ffff799e0b6 in _PyEval_EvalCodeWithName (_co=_co@entry=0x7ffff7f26810, globals=globals@entry=0x7ffff7f6b048, locals=locals@entry=0x7ffff7f6b048, 
>     args=args@entry=0x0, argcount=argcount@entry=0, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, 
>     closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:4159
> #41 0x00007ffff799e60e in PyEval_EvalCodeEx (_co=_co@entry=0x7ffff7f26810, globals=globals@entry=0x7ffff7f6b048, locals=locals@entry=0x7ffff7f6b048, 
>     args=args@entry=0x0, argcount=argcount@entry=0, kws=kws@entry=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:4180
> #42 0x00007ffff799e63b in PyEval_EvalCode (co=co@entry=0x7ffff7f26810, globals=globals@entry=0x7ffff7f6b048, locals=locals@entry=0x7ffff7f6b048)
>     at Python/ceval.c:731
> #43 0x00007ffff79c7740 in run_mod (mod=mod@entry=0x5555557d6538, filename=filename@entry=0x7ffff7ea8390, globals=globals@entry=0x7ffff7f6b048, 
>     locals=locals@entry=0x7ffff7f6b048, flags=flags@entry=0x7fffffffe5fc, arena=arena@entry=0x7ffff7f86150) at Python/pythonrun.c:1025
> #44 0x00007ffff79c9b11 in PyRun_FileExFlags (fp=fp@entry=0x5555557d58a0, filename_str=filename_str@entry=0x7ffff7f258d8 "/usr/bin/qutebrowser", 
>     start=start@entry=257, globals=globals@entry=0x7ffff7f6b048, locals=locals@entry=0x7ffff7f6b048, closeit=closeit@entry=1, flags=0x7fffffffe5fc)
>     at Python/pythonrun.c:978
> #45 0x00007ffff79c9c5f in PyRun_SimpleFileExFlags (fp=fp@entry=0x5555557d58a0, filename=<optimized out>, closeit=closeit@entry=1, 
>     flags=flags@entry=0x7fffffffe5fc) at Python/pythonrun.c:420
> #46 0x00007ffff79ca083 in PyRun_AnyFileExFlags (fp=fp@entry=0x5555557d58a0, filename=<optimized out>, closeit=closeit@entry=1, 
>     flags=flags@entry=0x7fffffffe5fc) at Python/pythonrun.c:81
> #47 0x00007ffff79e05a0 in run_file (p_cf=0x7fffffffe5fc, 
>     filename=0x7ffff7878e00 L"\057\165\163\162\057\142\151\156\057\161\165\164\145\142\162\157\167\163\145\162", fp=0x5555557d58a0) at Modules/main.c:340
> #48 Py_Main (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:810
> #49 0x0000555555554a6e in main (argc=2, argv=<optimized out>) at ./Programs/python.c:69
> ```
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/2094#issuecomment-415986205

oh well, GLX-on-TLS is still broken. i'll do a normal update.

**Comment by maxice8** [comment]
@newbluemoon can you test again ?

**Comment by newbluemoon** [comment]
@maxice8 Sure! :)

**Comment by newbluemoon** [comment]
@maxice8 Same result :( but I’ll double check.

**Comment by maxice8** [comment]
On Sat, Aug 25, 2018 at 11:26:28AM -0700, newbluemoon wrote:
> @maxice8 Same result :( but I’ll double check.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/2094#issuecomment-415987844

oh, if the result is the same there is only 2 more configurations i need testing

**Comment by newbluemoon** [comment]
@maxice8 qutebrowser and xonotic work with 18.1.7 when except version and checksum everything is left as is.

**Comment by maxice8** [comment]
On Sat, Aug 25, 2018 at 11:50:03AM -0700, newbluemoon wrote:
> @maxice8 qutebrowser and xonotic work with 18.1.7 when except version and checksum everything is left as is.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/2094#issuecomment-415989167

I see, i'll just update it, no special changes for musl users.

**Comment by maxice8** [comment]
@newbluemoon can you test if the gallium-nine changes cause any side-effects ?

**Comment by newbluemoon** [comment]
@maxice8 Tested the same programs, no fallout so far. :)

**Comment by maxice8** [comment]
On Sat, Aug 25, 2018 at 11:16:31PM -0700, newbluemoon wrote:
> @maxice8 Tested the same programs, no fallout so far. :)
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/2094#issuecomment-416016759

sounds good, will update with only gallium-nine now enabled for musl

**Comment by newbluemoon** [comment]
I’m about to run some tests on armv7l-musl.

**Comment by maxice8** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=107315

**Comment by newbluemoon** [comment]
armv7l-musl, mesa-vc4-dri works, too. No problems so far. mpv, falkon, qutebrowser, glxgears are fine.
(Note: I use a slightly modified xorg-server which uses the same `configure_args` for armv7l* as for x86_64, etc. to make the RPi really use vc4.)

**Pull request closed without merging**
