### PR TITLE
brother-dcp197c-{cupswrapper,lpr}: remove

### PR DESCRIPTION
**Pull request by abenson**
1. The use of `*-32bit` packages in building is broken now

`=> brother-dcp197c-lpr-1.1.3_6: building ...`
`=> ERROR: brother-dcp197c-lpr-1.1.3_6: runtime dependency 'glibc-32bit' does not exist!`

2. They haven't been updated since 2011
3. They need to be moved to `nonfree` anyway

I recommend they be removed.

### CODE REVIEW

**Comment by Anachron** [comment]
Why was this merged anyway? This was such a specific package that nearly nobody else would use it.

**Comment by boson-at** [comment]
=> ERROR: brother-dcp197c-lpr-1.1.3_6: runtime dependency 'glibc-32bit' does not exist! 

I think that's a bug in xbps-src since then
commit e4984d01ea049e7cde260fc1a05d61fbdd403180
I have the same problem for about 17 hours
<host dependency 'glibc-32bit' does not exist!>
(sorry my english)

**Comment by xtraeme** [comment]
There is no bug here. A pkg shouldn't depend on unexistent or generated packages IMHO.

**Comment by xtraeme** [comment]
Thinking about it I think I could add something to make depending on 32bit pkgs work again.

**Comment by Anachron** [comment]
How is the state on this PR?

**Comment by q66** [comment]
the `-32bit` dependency issue has been solved at very least

**Pull request closed without merging**
