### PR TITLE
yggdrasil: ypdate to 0.5.11

### PR DESCRIPTION
**Pull request by terminaldweller**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86_64-musl

### CODE REVIEW

**Comment by terminaldweller** [comment]
https://github.com/void-linux/void-packages/pull/53207 had the same issue as in the same tests were not passing.
I've ran the tests and they pass on my x86_64-glibc box.
I'm suspecting this is a problem with the runners but I don't know where I can start looking at that. I would appreciate some directions.

**Comment by terminaldweller** [comment]
That specific test is failing because it is being run as root.
@classabbyamp confirmed that runners run the test as root and i tried running the test on my box as root and it failed.
Putting this here for future reference.

**Comment by terminaldweller** [comment]
The test that was failing has been removed: https://github.com/yggdrasil-network/yggdrasil-go/commit/657f7e0db38e9375a75e8a88bac5ba6e3f02537f
Now we wait for a new release
Should I close this now, or keep this until the new yggdrasil release?

**Comment by neilalexander** [comment]
New release is up BTW that includes the fix: https://github.com/yggdrasil-network/yggdrasil-go/releases/tag/v0.5.12

**Comment by terminaldweller** [comment]
I know. I built it and now I'm testing it.

**Comment by terminaldweller** [comment]
closed in favour of https://github.com/void-linux/void-packages/pull/53572

**Pull request closed without merging**
