### PR TITLE
SFML: update to 2.6.1

### PR DESCRIPTION
**Pull request by metaleap**
First-time contribution attempt. Previous version 2.5.1 in `void-packages` is over 5 years old. This one is very recent from 30th October.

#### Removed 1 patch:

No longer needed, the fix is already in the 2.6.1 sources.

#### Testing the changes
I tested the changes in this PR: **briefly**.

- Compiled / built,
- installed,
- did pre-install hooks,
- ~~then `pkg_install` step complains: `cannot stat '/destdir//SFML-2.6.1/usr/share/SFML': No such file or directory`~~
  - resolved now, the whole `./xbps-src pkg SFML` run succeeds. Also tried `i686` and `armv6l` out of curiosity, same.

#### Local build testing
- I built this PR locally for my native architecture, x86_64-glibc, plus also `-a armv6l` and `-a i686`.

### CODE REVIEW

**Comment by Johnnynator** [comment]
There was a different attempt at updating SFML #47454 with a working SFML template, but missing the updates to all the revdeps.

**Comment by metaleap** [comment]
> There was a different attempt at updating SFML #47454 with a working SFML template,

Thanks for _that_ hint! The error I had earlier no longer occurs now, having brought in from #47454 what here was missing. Very nice, hope it'll be the same in the CI/CD pipeline stuff here.

> but missing the updates to all the revdeps.

Not surprised, mine too, I guess? Ctrl+F "revdep" in this repo's 3 `.md`s yields zilch. I haven't got the faintest in the particular context here tbh. Apart from the abbreviation's expanded phrasing itself. Really the plan today was "coding software"... I guess we all know the dynamics of _that_ silly notion in 2023  :grin:

**Comment by metaleap** [comment]
Dunno if anyone is pinged about the re-approvable workflows pending from later force-`push`es but just FYI — good to go and give it another run now from my vantage, my tweaks are done here now  =)

**Comment by metaleap** [comment]
Yeah. Wow. All OK locally even with different archs, all failing in CI/CD. Screw all that... whoever wants to can Close this or take it over, cheers!

**Comment by Johnnynator** [comment]
> All OK locally even with different archs

You probably only build SFML locally?

The failing builds were `SLADE` and `attract` on musl.

**Comment by metaleap** [comment]
Very glad to see you took it over and thus successfully finally landed 2.6.1 in void-packages and thus voidlinux.org/packages and `xbps-install`-ready after all , many thanks @Johnnynator =)

**Pull request closed without merging**
