### PR TITLE
retroarch: update to 1.8.8

### PR DESCRIPTION
**Pull request by foldfree**

### CODE REVIEW

**Comment by Piraty** [comment]
is that your commit?

**Comment by foldfree** [comment]
I only refreshed from the last commit. But that didn't worked. Do you know how to fix it?

**Comment by ericonr** [comment]
If you want to change commiter name, you can do it with `git commit --ammend --author "Name <mail>"`. That's cool as long as you're changing your own commit.

**Comment by foldfree** [comment]
I don't know why I have two names and avatar on github. I don't really use this service. but foldfree and cesar is the same person.

**Comment by ericonr** [comment]
No problem then. You can leave it like this or change it to match your account (it's probably an email thing). Thanks for clarifying.

**Comment by ahesford** [comment]
This seems to be superseded by #24190

**Comment by amak79** [comment]
This is fixed in https://github.com/void-linux/void-packages/pull/24190 and can be closed.

**Pull request closed without merging**
