### PR TITLE
Firefox 110

### PR DESCRIPTION
**Pull request by Duncaen**
[ci skip]

* [x] x86_64-glibc
* [ ] x86_64-musl
* [ ] aarch64-musl
* [ ] i686-glibc

### CODE REVIEW

**Comment by Johnnynator** [comment]
Can you add the zxing-cpp  ( https://github.com/void-linux/void-packages/pull/42335 ) update to this PR, so we only have to recompile libreoffice once.

**Comment by mhmdanas** [comment]
@Johnnynator I think that's a good idea, I'll close my PR for now. Also, @Duncaen don't forget to add [this patch](https://gerrit.libreoffice.org/c/core/+/144874) to `libreoffice`, otherwise it won't compile with the updated `zxing-cpp`.

**Comment by dkwo** [comment]
Would it be possible to also update `thunderbird` to 102.8 ?

**Comment by mhmdanas** [comment]
Note that Firefox 100.0.1 is out now.

**Pull request closed without merging**
