### PR TITLE
slow cow. mess

### PR DESCRIPTION
**Pull request by IT-DEVS-Group**
- I tested the changes in this PR: YES
- I built this PR locally for my native architecture (X86-64 musl, X86_64 glib)

### CODE REVIEW

**Comment by IT-DEVS-Group** [comment]
Mess, commits take so long to process

**Comment by IT-DEVS-Group** [comment]
due to the inaction of the maintainers, there is no way to clean up the packages. Missing XFCE plugins, outdated software versions, slow review of commits. Void was my favorite distro, but due to the inactivity of the maintainers, it looks like one should look for distros with more serious maintainers.

**Comment by IT-DEVS-Group** [comment]
> There is no point in just adding this variable.

https://github.com/void-linux/void-packages/pull/37188

> There is no point in just adding this variable.
See
https://github.com/void-linux/void-packages/pull/37188

**Comment by Duncaen** [comment]
There is also not much point in using the SITE variables, just use the real url, its easier to read and copy.

**Comment by IT-DEVS-Group** [comment]
> There is also not much point in using the SITE variables, just use the real url, its easier to read and copy.

I see gnome packages use variables. We need order and unity, and not to do whatever they want! Then there will be fewer errors and problems! =)

**Pull request closed without merging**
