### PR TITLE
iwd: update to 0.23.

### PR DESCRIPTION
**Pull request by ailiop-git**

### CODE REVIEW

**Comment by ailiop-git** [comment]
depends on ell >= 0.25, pushed in #15758

**Comment by pbui** [comment]
LGTM.

Next time, you can include both iwd and ell in the same PR (separate commits).

**Comment by zdtcd** [comment]
It would be better to rebase this one on top of `ell` to have Travis check.

**Comment by ailiop-git** [comment]
thanks for the reviews, changed & pushed accordingly.

**Pull request merged**
