### PR TITLE
nvidia, nvidia390: restore scripts deleted by mistake

### PR DESCRIPTION
**Pull request by st3r4g**
@xtraeme

### CODE REVIEW

**Comment by xtraeme** [comment]
Please move them to the - dkms subpkg

**Comment by st3r4g** [comment]
done

**Comment by xtraeme** [comment]
Wrong. xbps-src expects them as `srcpkgs/foo/subpkg.INSTALL` see my change from the glvnd branch

**Comment by st3r4g** [comment]
whoops sorry, misread the manual

**Comment by st3r4g** [comment]
they were on the main package before though

**Comment by st3r4g** [comment]
hope that's right this time

**Pull request merged**
