### PR TITLE
New package: evtest-qt

### PR DESCRIPTION
**Pull request by ScrelliCopter**
[Upstream](https://github.com/Grumbel/evtest-qt)
Nice visual util for testing evdev devices.

### CODE REVIEW

**Comment by ndowens** [comment]
You will need to add qt5-qmake and possibly qt5-host-tools to hostmakedepends

**Comment by ScrelliCopter** [comment]
Alright I will give this a look now.

**Comment by ScrelliCopter** [comment]
From my own testing I had to add both to get qmake & moc, hopefully this will be enough to pass the checks.

**Comment by ndowens** [comment]
> From my own testing I had to add both to get qmake & moc, hopefully this will be enough to pass the checks.

Yeah usually when you need to add qmake you have to add the other;

**Pull request merged**
