### PR TITLE
bottom: shell completions

### PR DESCRIPTION
**Pull request by zweimach**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Please use `vcompletion` for new completions.

**Comment by ericonr** [comment]
Also, the PR needs to revbump the package for a new package to be built with the changes.

**Comment by ericonr** [comment]
> /void-packages/srcpkgs/bottom/template: line 17: cd: too many arguments

Any idea how to fix? Happens for all native builds...

Would be nice if Cargo had minimally sane output directories for build artifacts.

**Comment by ericonr** [comment]
Ping?

**Comment by zweimach** [comment]
> > /void-packages/srcpkgs/bottom/template: line 17: cd: too many arguments
> 
> Any idea how to fix? Happens for all native builds...
> 
> Would be nice if Cargo had minimally sane output directories for build artifacts.

Sorry, I know nothing about Rust and Cargo.

**Comment by ericonr** [comment]
You can try using `find` to find (heh) the pages...

**Comment by ericonr** [comment]
Closed by df9082f5e5282ea7c74dd5251432d45767e32d22

**Pull request closed without merging**
