### PR TITLE
python3-click: update to 8.1.3.

### PR DESCRIPTION
**Pull request by Goorzhel**
<details>
<summary>python3-click tests pass</summary>

```
$ git log --oneline --decorate | head -2
72184752a3 (HEAD -> python3-click) python3-click: update to 8.1.3.
fce1ba0a35 (upstream/master, upstream/HEAD, master) riff: update to 2.17.0.
$ ./xbps-src check python3-click
=> xbps-src: updating repositories for host (x86_64)...
[*] Updating repository `https://repo-default.voidlinux.org/current/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/nonfree/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/debug/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/multilib/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/multilib/nonfree/x86_64-repodata' ...
[*] Updating repository `https://repo-us.voidlinux.org/current/x86_64-repodata' ...
[*] Updating repository `https://repo-us.voidlinux.org/current/nonfree/x86_64-repodata' ...
=> xbps-src: updating software in / masterdir...
=> xbps-src: cleaning up / masterdir...
=> python3-click-8.1.3_1: removing autodeps, please wait...
=> python3-click-8.1.3_1: building [python3-module] for x86_64...
   [host] python3-setuptools-62.3.3_1: found (https://repo-default.voidlinux.org/current)
   [check] python3-pytest-7.1.2_1: found (https://repo-default.voidlinux.org/current)
   [target] python3-3.10.5_1: found (https://repo-default.voidlinux.org/current)
   [runtime] python3-3.10.5_1: found (https://repo-default.voidlinux.org/current)
=> python3-click-8.1.3_1: installing host dependencies: python3-setuptools-62.3.3_1 python3-pytest-7.1.2_1 ...
=> python3-click-8.1.3_1: installing target dependencies: python3-3.10.5_1 ...
=> python3-click-8.1.3_1: running do_check ...
============================= test session starts ==============================
platform linux -- Python 3.10.5, pytest-7.1.2, pluggy-1.0.0
rootdir: /builddir/click-8.1.3, configfile: setup.cfg, testpaths: tests
collected 598 items

tests/test_arguments.py ...................................              [  5%]
tests/test_basic.py .................................................... [ 14%]
....                                                                     [ 15%]
tests/test_chain.py ...............x                                     [ 17%]
tests/test_command_decorators.py ...                                     [ 18%]
tests/test_commands.py ........................                          [ 22%]
tests/test_compat.py .                                                   [ 22%]
tests/test_context.py .......................                            [ 26%]
tests/test_custom_classes.py ......                                      [ 27%]
tests/test_defaults.py ...                                               [ 27%]
tests/test_formatting.py ................                                [ 30%]
tests/test_imports.py .                                                  [ 30%]
tests/test_info_dict.py ......................                           [ 34%]
tests/test_normalization.py ...                                          [ 34%]
tests/test_options.py .................................................. [ 43%]
...............................................................          [ 53%]
tests/test_parser.py .......                                             [ 55%]
tests/test_shell_completion.py .....................................     [ 61%]
tests/test_termui.py ...........................................ssssssss [ 69%]
sssssssssssss.................                                           [ 74%]
tests/test_testing.py .......................                            [ 78%]
tests/test_types.py ..................................                   [ 84%]
tests/test_utils.py .................................................... [ 92%]
..........................................                               [100%]

================== 576 passed, 21 skipped, 1 xfailed in 0.97s ==================
```
</details>

<details>
<summary>How I tested each reverse dependency</summary>

```
$ xbps-query -RX python3-click
activityrelay-0.2.1_1
black-21.9b0_2
fava-1.18_2
gandi-cli-1.6_2
khal-0.10.4_2
litecli-1.8.0_1
magic-wormhole-0.12.0_3
pantalaimon-0.8.0_2
papis-0.11.1_2
pgcli-3.4.1_1
platformio-5.2.5_1
python3-Flask-2.0.2_1
python3-click-log-0.3.2_5
python3-click-plugins-1.1.1_4
python3-click-repl-0.1.6_3
python3-click-threading-0.4.4_5
python3-dotenv-0.19.0_2
python3-httpx-0.23.0_1
python3-pgspecial-1.13.1_1
python3-proselint-0.12.0_1
python3-pyinfra-2.1_1
python3-quart-0.17.0_1
python3-shodan-1.25.0_2
python3-tmuxp-1.10.1_1
python3-userpath-1.7.0_2
subliminal-2.1.0_6
termdown-1.17.0_3
vdirsyncer-0.18.0_2
yubikey-manager-4.0.7_1

$ for i in $(xbps-query -RX python3-click); do
  i=${i%-*}  # strip version
  ./xbps-src check $i &> ~Temp/click/$i
done
```
</details>

### Pass
- khal-0.10.4_2
- litecli-1.8.0_1
- pantalaimon-0.8.0_2
- platformio-5.2.5_1
- python3-click-log-0.3.2_5
- python3-click-plugins-1.1.1_4
- python3-dotenv-0.19.0_2
- python3-proselint-0.12.0_1
- python3-pyinfra-2.1_1
- python3-quart-0.17.0_1
- python3-tmuxp-1.10.1_1
- python3-userpath-1.7.0_2
- subliminal-2.1.0_6
- yubikey-manager-4.0.7_1

### Fail
- black-21.9b0_2 (and 22.3.0_1)
- fava-1.18_2
- python3-Flask-2.0.2_1
- python3-click-threading-0.4.4_5
- gandi-cli-1.6_2
- python3-shodan-1.25.0_2
- vdirsyncer-0.18.0_2

### Don't test (`make_check=no`)
- activityrelay-0.2.1_1
- python3-click-repl-0.1.6_3
- pgcli-3.4.1_1
- python3-httpx-0.23.0_1
- python3-pgspecial-1.13.1_1

### Can't test
All of these fail with
> /usr/bin/python3: No module named pip

- magic-wormhole-0.12.0_3
- papis-0.11.1_2
- termdown-1.17.0_3

### CODE REVIEW

**Comment by Goorzhel** [comment]
Blocks #37514 (`python3-hatch`) and #34520 (`black`).

**Comment by Goorzhel** [comment]
Testing the reverse dependencies with the current version, `python3-click-7.1.2_5`, showed that these packages regress with the upgrade:
- fava-1.18_2
- python3-click-threading-0.4.4_5
- vdirsyncer-0.18.0_2

**Comment by Goorzhel** [comment]
`fava` has adopted PEP 517 sometime between 1.18 and 1.21. Updating it leads to another brick wall, however:
<details>
<summary>git diff srcpkgs/fava/template</summary>

```diff
diff --git a/srcpkgs/fava/template b/srcpkgs/fava/template
index 9b0f83e540..87339be552 100644
--- a/srcpkgs/fava/template
+++ b/srcpkgs/fava/template
@@ -3,3 +3,3 @@ pkgname=fava
-version=1.18
-revision=2
-build_style=python3-module
+version=1.21
+revision=1
+build_style=python3-pep517
@@ -9 +9 @@ depends="python3-Babel python3-Cheroot python3-Flask-Babel python3-Flask
- python3-simplejson python3-Werkzeug python3-aiohttp"
+ python3-simplejson python3-Werkzeug python3-aiohttp python3-wheel"
@@ -16 +16 @@ distfiles="${PYPI_SITE}/f/fava/fava-${version}.tar.gz"
-checksum=21336b695708497e6f00cab77135b174c51feb2713b657e0e208282960885bf5
+checksum=d1a1422848e65e7eb275d80d322f6de2bcea1dc37b5412e8cf72c483d6a998d6
```
</details>


```
=> fava-1.21_1: running do_check ...
ImportError while loading conftest '/builddir/fava-1.21/tests/conftest.py'.
tests/conftest.py:19: in <module>
    from fava.application import _load_file
build/lib/fava/application.py:40: in <module>
    from fava import __version__ as fava_version
E   ImportError: cannot import name '__version__' from 'fava' (/builddir/fava-1.21/build/lib/fava/__init__.py)
=> ERROR: fava-1.21_1: do_check: 'PYTHONPATH="$PWD/build/lib" python3 -m pytest tests -k 'not cli and not static_url'' exited with 4
=> ERROR:   in do_check() at srcpkgs/fava/template:20
```

**Comment by leahneukirchen** [comment]
If the test suite can't run from a build dir without installation, just disable it imo.

**Comment by Goorzhel** [comment]
> 0.18.0 claims to fix vdirsyncer

That's the current version, though.

> If the test suite can't run from a build dir without installation, just disable it imo.

Fair. I'll make `fava` `make_check=no`.

**Comment by Goorzhel** [comment]
`xbps-src check vdirsyncer` seems to be working on my machine now, with `upstream/HEAD` at 2cecb1efcc. I rebased upon `fce1ba0a35` (`HEAD` when I started this PR) and...`do_check` succeeds there too. I've also lost whatever output I used to determine that `vdirsyncer` had regressed. 🤡

That's all the regressions dealt with, anyway. I took a shot at the "Can't test" packages but `papis` sent me down a yak trail that sapped all my energy:
* `ModuleNotFoundError: No module named 'pytest'`, so I add it to `checkdepends`
* Then it complained about `whoosh` missing, so I added `python3-Whoosh`
* Then [this](https://0x0.st/oScX.txt) happened

**Comment by ahesford** [comment]
1. `fava` requires `python3-wheel` be added to `hostmakedepends`
2. If you are going to disable the tests, remove the `do_check` function.

**Comment by paper42** [comment]
gandi-cli is deprecated and the test failures are caused by this click update, they used to pass without an issue. I would be in favor of dropping that package

**Comment by leahneukirchen** [comment]
fine by me.

cc @lonwillett

**Comment by icp1994** [comment]
I made a PR for [papis](https://github.com/void-linux/void-packages/pull/37672) with working tests which holds for both `click-7.1.2` and `click-8.1.3` so hopefully we can move that into `Pass` section soon.

**Pull request merged**
