### PR TITLE
jrnl: update to 2.5, add checkdepends.

### PR DESCRIPTION
**Pull request by ashpooljh**

### CODE REVIEW

**Comment by ericonr** [comment]
Do you think you could add all the necessary `checkdepends` so we don't get any warnings like the one below:

```
WARNING: The pip package is not available, falling back to EasyInstall for handling setup_requires/test_requires; this is deprecated and will be removed in a future version. 
```

Build with `./xbps-src -Q pkg jrnl` to check.

**Comment by ashpooljh** [comment]
@ericonr Apparently the `checkdepends` in this case would be the same as `depends`. Should I copy-paste the whole list or is `checkdepends="${depends}"` acceptable? Either way this fixes the warnings your mentioned.

When I run `./xbps-src -Q pkg jrnl`, however, I get [this output](http://sprunge.us/DkhQC0) with an error from `unittest`. Methinks this way of testing this particular package is not supported or is broken, so we shouldn't be worrying about it.

**Comment by ericonr** [comment]
> checkdepends="${depends}" acceptable

Acceptable and preferred :)

**Comment by ericonr** [comment]
I can't open the paste, but I can guess at the output. Might be best to use upstream's suggested method: https://github.com/jrnl-org/jrnl/blob/develop/CONTRIBUTING.md#common-development-commands

`do_check() { make test }`

**Comment by ashpooljh** [comment]
Sorry, I haven't yet found a way to make this work. There's no `Makefile` bundled with the Python module on PyPI.

Things we can try:
- change the upstream to GitHub and build it using the `gnu-makefile` style, not `python3-module`, and use `make test` for checking, or
- figure out why `python3-module`-style `do_check()` fails and patch the package to pass it.

For now, I added the `checkdepends` to fix the warnings, but the check phase remains broken. For anyone who'd like to try fix it, I'll paste the full output of this phase below.

**Comment by ashpooljh** [comment]
```
=> jrnl-2.5_1: running do_check ...
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
creating jrnl.egg-info
writing jrnl.egg-info/PKG-INFO
writing dependency_links to jrnl.egg-info/dependency_links.txt
writing entry points to jrnl.egg-info/entry_points.txt
writing requirements to jrnl.egg-info/requires.txt
writing top-level names to jrnl.egg-info/top_level.txt
writing manifest file 'jrnl.egg-info/SOURCES.txt'
reading manifest file 'jrnl.egg-info/SOURCES.txt'
writing manifest file 'jrnl.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "/builddir/jrnl-2.5/setup.py", line 46, in <module>
    setup(**setup_kwargs)
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.9/site-packages/setuptools/command/test.py", line 232, in run
    self.run_tests()
  File "/usr/lib/python3.9/site-packages/setuptools/command/test.py", line 250, in run_tests
    test = unittest.main(
  File "/usr/lib/python3.9/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.9/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.9/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib/python3.9/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.9/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.9/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/usr/lib/python3.9/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3.9/site-packages/setuptools/command/test.py", line 50, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.9/unittest/loader.py", line 214, in loadTestsFromName
    raise TypeError("don't know how to make test from: %s" % obj)
TypeError: don't know how to make test from: v2.5
=> ERROR: jrnl-2.5_1: do_check: 'python3 setup.py ${make_check_target} ${make_check_args}' exited with 1
=> ERROR:   in do_check() at common/build-style/python3-module.sh:35
```

**Comment by ericonr** [comment]
You can use the tarball from GH and keep the `python3-module`, just redefining the `do_check` function itself.

**Review by ahesford — CHANGES_REQUESTED** [review]
There is no clean way to enable the tests.

The GitHub tarball does not ship `setup.py` so `python3-module` would not work. Normally this would be a good application for the new `python3-pep517` build style, but the PEP517 build for this project relies on Poetry, which we don't have packaged. I don't think supporting `jrnl` alone is with packaging Poetry.

For now, stick with the PyPI sdist tarball to allow installation with `setuptools`. However, the sdist does not include tests, so the right action here is to remove `checkdepends` entirely and define
```bash
do_check() {
	: no tests are provided
}
```
in the template.

**Pull request closed without merging**
