### PR TITLE
waydroid: update to 1.4.1

### PR DESCRIPTION
**Pull request by JamiKettunen**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by JamiKettunen** [comment]
Hm it seems right after update it's not possible to stop an already running `waydroid-container` service, rebooting fixes it... Checking running processes:
```
$ ps aux | grep waydroid
root      1015  0.0  0.0   2528  1228 ?        Ss   12:08   0:00 runsvdir -P /run/runit/runsvdir/current log: : fatal: unable to start ./run: file does not exist runsv waydroid-container: warning: unable to open supervise/pid.new: file does not exist runsv waydroid-container: warning: unable to open supervise/pid.new: file does not exist runsv waydroid-container: fatal: unable to start ./run: file does not exist runsv waydroid-container: warning: unable to open supervise/pid.new: file does not exist 
root     18254  0.0  0.0   2376  1024 ?        Ss   12:57   0:00 runsv waydroid-container
root     18258  0.0  0.0   2496   924 ?        S    12:57   0:00 vlogger -t waydroid-container -p daemon
```

**Comment by JamiKettunen** [comment]
`\\` on `#xbps` mentioned:
> I'm guessing that the supervised process actually terminated but the log process didn't

**Comment by JamiKettunen** [comment]
The bug experienced here now appears to have a proper bug report @ https://github.com/void-linux/runit/issues/25

**Comment by IceAsteroid** [comment]
Looking forward to trying out this new version of waydroid, hope it'll fix the "ERROR: invalid literal for int() with base 10: '['" error when running "sudo proxychains4 waydroid init".

Or, probably, just because of the use of proxychains4. But this issue has also been posted on the waydroid repo, https://github.com/waydroid/waydroid/issues/176

**Comment by JamiKettunen** [comment]
@IceAsteroid I've never seen that so I expect that to be an issue specific to using `proxychains4`. The linked issue doesn't seem related to yours either (it only contains a small part of your error message but otherwise is completely different).

You could build and install the new packages from my fork already (similar to https://github.com/void-linux/void-packages#quick-start) and see if that changes anything but I doubt it. Feel free to make a new issue upstream discussing this and if you can try to debug where it's failing yourself

**Comment by IceAsteroid** [comment]
@JamiKettunen Thank you for replying. After not using proxychains4, I managed to get it completing initialization by the "waydroid init" in a root shell. 

However, a new issue kicked in as the GUI interface woundn't show up at all by "waydroid show-full-ui" in a user shell while "waydroid-container" is running at root. I posted an issue on the waydroid repo: https://github.com/waydroid/waydroid/issues/864

But, yeah, I'll try to figure out by using a custom package based on your fork. So much thank!

**Comment by IceAsteroid** [comment]
@JamiKettunen Also, is there anything more required to run waydroid on voidlinux besides the waydroid package and other packages required to have clipbaord support?

**Comment by illusioon** [comment]
With this new update waydroid now works.

**Comment by JamiKettunen** [comment]
I'll update the packages tomorrow and hopefully get this ready for merge, can't do much about the runit bug anyway other than print workaround messages for post-upgrade as it would happen to anyone that hasn't updated `runit` even after it's already fixed in the future, just annoying...

**Pull request merged**
