### PR TITLE
nextcloud-client: update to 3.7.3

### PR DESCRIPTION
**Pull request by mdkcore0**
#### Testing the changes
- I tested the changes in this PR: **yes**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-lib)
- armv7l (crossbuild)
- i686-libc

Also:
- Add `karchive` as dependency: https://github.com/nextcloud/desktop/pull/4768
- Add patch to revert mandatory WebEngine dependency: https://github.com/nextcloud/desktop/pull/4875

### CODE REVIEW

**Comment by mdkcore0** [comment]
I'm getting this error while trying to build the package on armv7l (cross):
```
-- The following REQUIRED packages have not been found:

 * Qt5WebEngineWidgets (required version >= 5.15.0), Qt5 WebEngineWidgets component.
 * Qt5WebEngine (required version >= 5.15.0), Qt5 WebEngine component.
```
It failed here on Actions as well; seems the `qt5-webengine` package is missing from the armv6l and armv7l taget architectures.

Is it a known issue? Can't find something related in the issues tab (also [the logs from the latest update are not available anymore](https://github.com/void-linux/void-packages/pull/39916/checks))

**Comment by classabbyamp** [comment]
> Is it a known issue?

https://github.com/void-linux/void-packages/blob/master/srcpkgs/qt5-webengine/template#L56

**Comment by mdkcore0** [comment]
> https://github.com/void-linux/void-packages/blob/master/srcpkgs/qt5-webengine/template#L56, but it's weird that it didn't fail successfully

yeah, this is pretty strange as it was working flawlessly in the last time I've [updated ths package](https://github.com/void-linux/void-packages/actions/runs/3968852948/jobs/6802566746); will was on IRC later today

**Comment by mdkcore0** [comment]
they have [made WebEngine mandatory now](https://github.com/nextcloud/desktop/pull/4875), I've asked on their repo for a solution, and will try to figure out a way to remove this dependency in the meantime

**Comment by TimB87** [comment]
You can revert the commit in the meantime like I did for CRUX: https://crux.nu/gitweb/?p=ports/contrib.git;a=commit;h=a3b7ed365b04b37bcbc5390e5a9b0c5c0578bbc2

not the most elegant solution, but oh well.. that wasn't the most elegant commit upstream either

hope that helps 👋

**Comment by mdkcore0** [comment]
> You can revert the commit in the meantime like I did for CRUX: https://crux.nu/gitweb/?p=ports/contrib.git;a=commit;h=a3b7ed365b04b37bcbc5390e5a9b0c5c0578bbc2
> 
> not the most elegant solution, but oh well.. that wasn't the most elegant commit upstream either
> 
> hope that helps wave

yeah, will do that, many thanks @TimB87!

**Comment by ahesford** [comment]
This probably ought to be guarded by a build option, where the default is to not revert the change and depend on `qt5-webengine`, except for those arches where we don't build that package.

**Pull request merged**
