### PR TITLE
onionshare: clean dependencies.

### PR DESCRIPTION
**Pull request by travankor**
Remove unused dependencies.
Deduplicate dependencies.

### CODE REVIEW

**Comment by Chocimier** [comment]
Please remove pycompile_module, it's incomplete. Complete one will be generated automatically. Works otherwise.
Checked that removed depends are either pulled in, not specified in requirements.txt or not used (macholib, pefile).

**Comment by travankor** [comment]
Yes, macholib and pelib are for mac and windows, respectively. 
Can double check [here](https://repology.org/project/onionshare/versions) and see no other distro uses these two.

**Comment by xtraeme** [comment]
I'd like to know why those were added time ago if they aren't relevant for linux... in this case those pkgs can be removed safely.

I wasn't aware of this when I commented yesterday.

**Comment by xtraeme** [comment]
@travankor so that your changes to remove them were ok, my fault.

**Comment by xtraeme** [comment]
but my point still remains, interpreted languages don't get special treatment in xbps-src, and as such, we need to check its dependencies manually... this needs to be automated somehow.

**Pull request merged**
