### PR TITLE
python3-language-server: update to 0.36.2

### PR DESCRIPTION
**Pull request by jgarte**
- python3-language-server: update to 0.36.2

- I tested the changes in this PR: YES

- I built this PR locally for my native architecture, (x86_64)

### CODE REVIEW

**Comment by jgarte** [comment]
Linter is saying:

`srcpkgs/python3-language-server/template:4: revision should be set to 1 on update`

I bumped the revision. Should I really be setting it back to 1?

**Comment by paper42** [comment]
> Linter is saying:
> 
> `srcpkgs/python3-language-server/template:4: revision should be set to 1 on update`
> 
> I bumped the revision. Should I really be setting it back to 1?

Yes, revisions are for making sure the package gets built users can get the update - 1.0.0_2 is newer than 1.0.0_1. When the version is increased, we can reset revision because the update will be detected - 1.0.1_1 is newer than 1.0.0_4.

**Comment by ericonr** [comment]
https://github.com/palantir/python-language-server/issues/935 seems relevant. I wonder if we should package that new one.

**Comment by jgarte** [comment]
> [palantir/python-language-server#935](https://github.com/palantir/python-language-server/issues/935) seems relevant. I wonder if we should package that new one.

@ericonr 

Yup, I agree we should package the new one instead of this PR.

**Comment by jgarte** [comment]
> 

Got it! Thanks for the explanation.

**Comment by jgarte** [comment]
Closing this in favor of #34192

**Pull request closed without merging**
