### PR TITLE
New package: fsearch-0.1beta4

### PR DESCRIPTION
**Pull request by ScrelliCopter**
Still in beta but have been using for 6 or so months fairly regularly with no issues, slated for a 1.0 release when translations are done.

### CODE REVIEW

**Comment by Chocimier** [comment]
Duplicate of #13298. When stable release will appear, please first ask to update that PR.

**Comment by Boebbele** [comment]
Is the package available?  I can't find a template file.

**Comment by ScrelliCopter** [comment]
@Boebbele The template is sill in my own fork, you will have to clone that and check out the `fsearch` branch then build it yourself with xbps-src.

**Comment by Boebbele** [comment]
I did it.  it works perfectly!  Thank you!

**Pull request closed without merging**
