### PR TITLE
New package: ddccontrol-0.4.4

### PR DESCRIPTION
**Pull request by zhengqunkoo**
Making of `gddccontrol` is disabled by `--disable-gnome`.

### CODE REVIEW

**Comment by abenson** [comment]
This needs to be rebased on master

**Comment by abenson** [comment]
This seems to depend on your other PR, can you combine them into a single PR?

**Comment by ericonr** [comment]
There should be a single commit for each package.

**Comment by zhengqunkoo** [comment]
Squashed commits.

**Comment by Duncaen** [comment]
Each package should be one commit:
```
New package: ddccontrol-db-20190825
New package: ddccontrol-0.4.4
```

**Comment by Duncaen** [comment]
`build_style` should be gnu-configure then `--prefix=` should be removed from `configure_args` as it is the default for the buildsyle.

**Comment by zhengqunkoo** [comment]
My bad, somehow thought this PR had only one package. Now there's two commits, and `build_style` and `configure_args` are updated.

**Pull request closed without merging**
