### PR TITLE
New package: docker-cli-compose-2.2.3

### PR DESCRIPTION
**Pull request by paper42**
#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by paper42** [comment]
This needs more investigation, marking as draft for now

**Comment by dm17** [comment]
Looks like docker compose (aka compose v2) has compose v1 compatibility on Arch (by running the old "docker-compose"), but not on Void. I'm also wondering how
```du -sh /usr/libexec/docker/cli-plugins/docker-compose``` could return 8.6M on Void while ```du -sh /usr/lib/docker/cli-plugins/docker-compose``` could return 31M on Arch. That seems like more of a size difference than the wrapper/helper for backward compatibility could account.
Thanks a bunch!

**Comment by paper42** [comment]
> Looks like docker compose (aka compose v2) has compose v1 compatibility on Arch (by running the old "docker-compose"), but not on Void.

If you look at this PR, it was closed by bf7aa5ba4a7783a9d59c1b7ed9686abf02b26262, I decided to go with just updating the package and not creating a new one. We also have a wrapper.

I'm also wondering how
> ```du -sh /usr/libexec/docker/cli-plugins/docker-compose``` could return 8.6M on Void while ```du -sh /usr/lib/docker/cli-plugins/docker-compose``` could return 31M on Arch. That seems like more of a size difference than the wrapper/helper for backward compatibility could account.

I am not sure how you measured this, I see 21MB on aarch64-musl and 13MB on x86_64. I think it's because of stripping, but I am not sure if the difference is this big and if arch doesn't strip go programs.

**Comment by dm17** [comment]
> > Looks like docker compose (aka compose v2) has compose v1 compatibility on Arch (by running the old "docker-compose"), but not on Void.
> 
> If you look at this PR, it was closed by [bf7aa5b](https://github.com/void-linux/void-packages/commit/bf7aa5ba4a7783a9d59c1b7ed9686abf02b26262), I decided to go with just updating the package and not creating a new one. We also have a wrapper.
> 
> I'm also wondering how
> 
> > `du -sh /usr/libexec/docker/cli-plugins/docker-compose` could return 8.6M on Void while `du -sh /usr/lib/docker/cli-plugins/docker-compose` could return 31M on Arch. That seems like more of a size difference than the wrapper/helper for backward compatibility could account.
> 
> I am not sure how you measured this, I see 21MB on aarch64-musl and 13MB on x86_64. I think it's because of stripping, but I am not sure if the difference is this big and if arch doesn't strip go programs.
> 
> EDIT: the size reported by ls is actually 25MB, du reports disk usage

Ah thanks du vs ls shows much less of a difference :)

> We also have a wrapper.

How is this evoked? ```docker-compose disable-v2``` doesn't seem to work.

**Comment by paper42** [comment]
> > We also have a wrapper.
> 
> How is this evoked? `docker-compose disable-v2` doesn't seem to work.

The wrapper I am talking about is /usr/bin/docker-compose, it should be compatible with v1. disable-v2 is an development command and was probably dropped.

**Comment by dm17** [comment]
Nice! So both v1 & v2 seem to be working correctly on void now. And I now realize the standard v1 vs v2 differentiation (across distros) is "docker-compose" vs "docker compose" - thanks!

**Pull request closed without merging**
