### PR TITLE
[WIP] Tracking: FFmpeg 5.0

### PR DESCRIPTION
**Pull request by tibequadorian**
[ci skip]

Depends on:
- https://github.com/void-linux/void-packages/pull/35431
- https://github.com/void-linux/void-packages/pull/36115
- https://github.com/void-linux/void-packages/pull/36361

Currently build successful against ffmpeg-5.0:
- [x] QMPlay2
- [x] alsa-plugins
- [ ] arcan - depends on vlc
- [ ] attract - fixed in master https://github.com/mickelson/attract/commit/c27312be47dfb7370456a878fc6284883650b7f2
- [x] aubio - patched https://github.com/aubio/aubio/commit/8a05420e5dd8c7b8b2447f82dc919765876511b3
- [x] audacious-plugins - patched https://github.com/audacious-media-player/audacious-plugins/commit/f60beb400eeb1e4778bbfd738bc4a4ccef3de539
- [x] baresip
- [ ] blender - depends on openimageio
- [ ] cantata - depends on vlc
- [ ] ccextractor https://github.com/CCExtractor/ccextractor/issues/1418
- [ ] chromaprint https://github.com/acoustid/chromaprint/issues/33
- [ ] chromium
- [x] cmus
- [ ] deadbeef https://github.com/DeaDBeeF-Player/deadbeef/issues/2758
- [x] dolphin-emu
- [x] droidcam
- [ ] electron10
- [ ] electron13
- [ ] ffmpegthumbnailer https://github.com/dirkvdb/ffmpegthumbnailer/issues/212
- [ ] ffmpegthumbs
- [x] ffms2 - patched https://github.com/FFMS/ffms2/pull/380
- [x] freerdp
- [x] gerbera
- [x] goldendict - patched https://github.com/goldendict/goldendict/commit/03bbe01b79a1f07a6780cb60f23a087104c5d77b, https://github.com/goldendict/goldendict/commit/966f4a8b78e6324b930e5a50f2bb930bd87e565e, https://github.com/goldendict/goldendict/commit/8acb288c9e9bdb3c6bf2e803954dd3b6ac273c05
- [x] gst-libav
- [ ] guvcview
- [ ] handbrake
- [ ] hedgewars
- [ ] idjc
- [x] k3b https://invent.kde.org/multimedia/k3b/-/issues/1
- [x] kfilemetadata5
- [ ] kid3 - depends on chromaprint
- [ ] kodi
- [ ] libextractor
- [ ] libopenshot
- [ ] loudgain https://github.com/Moonbase59/loudgain/issues/49
- [ ] mediastreamer
- [x] mgba - patched https://github.com/mgba-emu/mgba/commit/cdc753516798882a805db1d2042dbce8313382bf
- [x] minidlna
- [ ] mlt
- [ ] mlt7 - depends on opencv4
- [ ] moc - unmaintained since 2016
- [x] motion
- [x] mpd
- [x] mpv
- [x] musikcube
- [x] notcurses
- [ ] obs - depends on vlc
- [ ] olive - fixed in master https://github.com/olive-editor/olive/commit/03f0ec9f641ebfdd1c643f4f908ae10fa587e54b
- [ ] opencv/opencv4 https://github.com/opencv/opencv/issues/20147
- [ ] openimageio - fixed in [2.3.13.0](https://github.com/OpenImageIO/oiio/releases/tag/v2.3.13.0)
- [ ] openmw - depends on osg
- [ ] osg https://github.com/openscenegraph/OpenSceneGraph/issues/1111
- [x] pianobar https://github.com/PromyLOPh/pianobar/issues/730
- [ ] ppsspp https://github.com/hrydgard/ppsspp/issues/15308
- [x] pqiv
- [x] qmmp
- [ ] qt5-webengine
- [ ] qtav https://github.com/wang-bin/QtAV/issues/1377
- [x] qtox - patched https://github.com/qTox/qTox/commit/15673a52b6b4805d482b69281e21947fb7096e05
- [x] retroarch
- [x] scrcpy
- [ ] siril - depends on opencv
- [ ] spek-alternative https://github.com/withmorten/spek-alternative/issues/15
- [ ] ssr https://github.com/MaartenBaert/ssr/issues/949
- [ ] sumo - depends on osg
- [ ] synfig - depends on mlt
- [ ] synfigstudio - depends on synfig
- [ ] telegram-desktop - fixed in 3.6.0 https://github.com/telegramdesktop/tdesktop/commit/436622ad7c41d45b8b56873c086d37d2eff4d493
- [x] timg
- [ ] transcode - upstream dead
- [ ] tvheadend
- [ ] unpaper - https://github.com/unpaper/unpaper/commit/584b460279658511d1079411b16d997f7b66d25e https://github.com/unpaper/unpaper/commit/22294ee2bfb35effeda62bf562c2509e0066af5e
- [ ] vba-m https://github.com/visualboyadvance-m/visualboyadvance-m/issues/912
- [ ] vlc - fixed in [4.0](https://code.videolan.org/videolan/vlc/-/merge_requests/1238)
- [x] waypipe
- [ ] wf-recorder https://github.com/ammen99/wf-recorder/commit/47a3905f670fe12ecbdfe4719df654df1cd183e2
- [x] xine-lib
- [ ] xpra - depends on opencv

#### Testing the changes
- I tested the changes in this PR: **YES**|**briefly**|**NO**

### CODE REVIEW

**Comment by Idesmi** [comment]
ffmpeg 5.0.1 bug-fix version has been released. This comment is for the eventuality you haven't noticed, perhaps you want to push it straight away in this PR.

**Comment by tibequadorian** [comment]
> ffmpeg 5.0.1 bug-fix version has been released. This comment is for the eventuality you haven't noticed, perhaps you want to push it straight away in this PR.

This PR is far from complete and more of a tracking PR but thank you for noticing.

**Comment by marmeladema** [comment]
* gst-libav should be fixed now since it has been updated to 1.20.1 in https://github.com/void-linux/void-packages/pull/36605

* k3b should be fixed by https://github.com/void-linux/void-packages/pull/36800

* vlc 3.0.17 has partial support for FFmpeg 5 according to https://code.videolan.org/videolan/vlc/-/merge_requests/1245

**Comment by Idesmi** [comment]
5.1 released

**Comment by zlice** [comment]
Going down this rabbit hole as well (ffmpeg 5.1.2). So far the main blockers seem to be vlc, opencv/4, OpenSceneGraph/osg and OpenImageIO/OIIO (need gcc12? cmake fails to find pthread. Has a few deps as well).

My main concern is what to do about projects like ppsspp that seem to be unlikely to make changes for ffmpeg5?

**Comment by paper42** [comment]
Patch them, remove them or create separate packages with v4 libraries, but I think we might want to wait a bit.

**Pull request closed without merging**
