### PR TITLE
samba update to 4.13.3, cifs-utils update to 6.12

### LINKED ISSUE #27565: Samba aborts on Raspberry Pi 3B
### System

* xuname:  
Void 5.4.68_1 armv7l Unknown notuptodate rdFFF
(Raspberry Pi 3B)
* package:  
samba-4.13.2_3

### Expected behavior
smbd starts normally.

### Actual behavior
smbd aborts at startup, saying it could not open secrets db. Has anybody else seen something similar on Raspberry Pi or ARM?

Log output:
```
2020-12-30T23:36:05.51797 daemon.notice: Dec 31 10:36:05 smbd: smbd version 4.13.2 started.
2020-12-30T23:36:05.51825 daemon.notice: Dec 31 10:36:05 smbd: Copyright Andrew Tridgell and the Samba Team 1992-2020
2020-12-30T23:36:05.58031 daemon.notice: Dec 31 10:36:05 smbd: ===============================================================
2020-12-30T23:36:05.58073 daemon.notice: Dec 31 10:36:05 smbd: INTERNAL ERROR: could not open secrets db in pid 22239 (4.13.2)
2020-12-30T23:36:05.58092 daemon.notice: Dec 31 10:36:05 smbd: If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
2020-12-30T23:36:05.58118 daemon.notice: Dec 31 10:36:05 smbd: ===============================================================
2020-12-30T23:36:05.58130 daemon.notice: Dec 31 10:36:05 smbd: PANIC (pid 22239): could not open secrets db in 4.13.2
2020-12-30T23:36:05.58146 daemon.notice: Dec 31 10:36:05 smbd: BACKTRACE: 0 stack frames:
```

testparm output:
```
# testparm
Load smb config files from /etc/samba/smb.conf
Loaded services file OK.
Weak crypto is allowed
Server role: ROLE_STANDALONE

Press enter to see a dump of your service definitions

# Global parameters
[global]
	bind interfaces only = Yes
	disable spoolss = Yes
	dns proxy = No
	interfaces = eth0
	load printers = No
	log file = /var/log/samba/%m.log
	logging = syslog
	map to guest = Bad Password
	max log size = 50
	printcap name = /dev/null
	server role = standalone server
	server string = Samba Server
	show add printer wizard = No
	idmap config * : backend = tdb
	hosts allow = 192.168.1. 127.
	printing = bsd

...share definitions...
```

Downgrading back to samba-3.6.25_14.armv7l.xbps works okay.

### Steps to reproduce the behavior

1. install samba package
2. set up /etc/samba/smb.conf
3. start the smbd service

### PR DESCRIPTION
**Pull request by ahesford**
It seems my attempt to build in more private libraries in the 4.13.2_2 revbump breaks `smbd`, so I've reverted those library changes.

Closes #27565.

@wangp @Anachron @andry-dev @abenson  please give this a test if you don't mind. Everything works for me on `x86_64`.

### CODE REVIEW

**Comment by andry-dev** [comment]
I created a basic configuration based on the default one and it seems to work. This is the config from `testparm`:
```
[global]
	dns proxy = No
	log file = /var/log/samba/%m.log
	map to guest = Bad User
	max log size = 50
	server role = standalone server
	server string = Samba Server
	idmap config * : backend = tdb

[homes]
	browseable = No
	comment = Home Directories
	read only = No

[public]
	guest ok = Yes
	guest only = Yes
	path = /var/pubsmb
	read only = No
```

I can properly use my home and the public share.

**Comment by wangp** [comment]
Seems fine on Raspberry Pi 3B.

**Comment by Anachron** [comment]
I'm currently cross-compiling between `x86_64` and `aarch64`. Will update this comment once finished testing.

**Comment by Anachron** [comment]
I'm still having issues no matter which config I use. 
One thing I recognized is it spawns 2 processes
```
1 S root     16568     1  0  80   0 - 13473 ep_pol 15:57 pts/0    00:00:00 smbd -F -S --no-process-group
1 S root     16569     1  0  80   0 - 13473 ep_pol 15:57 pts/0    00:00:00 smbd -F -S --no-process-group
```

I'm investigating.

**Comment by ahesford** [comment]
I have five instances of `smbd -F -S`. What is the reason for adding `--no-process-group`?

**Comment by Anachron** [comment]
Well the problem is that `sv` thinks the service is down because it detaches from the parent process. (See the 1 as parent PID)

So it turns out running the service file `once` actually spawns `smbd` and I can try to connect to the server.

**Comment by Anachron** [comment]
While we're at it, is there a reason we don't ship `samba-tool`? We have the manpage already, but not the tool itself.

**Comment by ahesford** [comment]
Yes. `samba-tool` seems to be installed only when `--with-ad-dc` is specified, but this option is experimental when using `--with-system-mitkrb5`, so `--without-ad-dc` is preferred for now.

**Comment by ahesford** [comment]
If you really want to dig into it, you could completely disable the building in of all private libraries, figure out which private libs should be a part of `samba-libs` and which should remain in `samba`, and see if that makes a difference for your problem. (Private libraries that are required by stuff already in `samba-libs` should be in that package to avoid cyclic dependencies between `samba` and `samba-libs`, but other private libs should stay in `samba`.)

However, since the first 4.13.2 package worked for you, I wouldn't think this would be a built-in library issue.

One thing to try is totally purging `/var/{lib,cache}/samba`, `/run/samba` and maybe even `/etc/samba/private` before attempting to launch the new version, but then you'll have to recreate your password database.

Does `testparm` give you anything useful?

**Comment by Anachron** [comment]
I nuked everything and ran `nmbd` and `smbd`, yet it errors out. 

In my syslog:

```
2021-01-04T10:06:45.87226 daemon.notice: Jan  4 11:06:45 smbd: smbd version 4.13.3 started.
2021-01-04T10:06:45.87259 daemon.notice: Jan  4 11:06:45 smbd: Copyright Andrew Tridgell and the Samba Team 1992-2020
2021-01-04T10:06:45.94161 daemon.notice: Jan  4 11:06:45 smbd: main: Failed to setup RPC server: NT_STATUS_UNSUCCESSFUL
2021-01-04T10:06:45.94197 daemon.notice: Jan  4 11:06:45 smbd: exit_daemon: daemon failed to start: Samba cannot setup ep pipe, error code 13
```

Running it in my shell (`smbd -F -S -d 6`) however returns a different error:
```
added interface eth0 ip=192.168.178.20 bcast=192.168.178.255 netmask=255.255.255.0
Netbios name list:-
my_netbios_names[0]="VOID-RPI3"
exit_daemon: daemon failed to start: Failed to create session, error code 1
```

If I add `--no-process-group` when run locally I receive:
```
Finding user nobody
Trying _Get_Pwnam(), username as lowercase is nobody
Get_Pwnam_internals did find user [nobody]!
Security token: (NULL)
Security token: (NULL)
Security token: (NULL)
Security token: (NULL)
Security token: (NULL)
Security token: (NULL)
Security token: (NULL)
svcctl_init_winreg: Could not open SYSTEM\CurrentControlSet\Services - NT_STATUS_INVALID_HANDLE
dcesrv_init_ep_server: Failed to init endpoint server 'svcctl': NT_STATUS_UNSUCCESSFUL
dcesrv_init: Failed to init DCE/RPC endpoint servers: NT_STATUS_UNSUCCESSFUL
main: Failed to setup RPC server: NT_STATUS_UNSUCCESSFUL
exit_daemon: daemon failed to start: Samba cannot setup ep pipe, error code 13
```

Strace: https://gist.github.com/Anachron/191a7377ed8ec35eb597a649e5014710

Following line looks suspicious:
```
newfstatat(AT_FDCWD, "/run/samba/winbindd", 0x7fe3cb2698, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (No such file or directory)
```

**Comment by ahesford** [comment]
I don't think the `winbindd` links are the issue, because I see the same thing when I strace my copy and everything works fine here.

Questions:
1. Are you using the standard `smbd` and `nmbd` services or did you write your own? My `/run/samba/smbd.pid` contains the correct PID and `smbd` is parented by `runsv` as expected.
2. Is `/var/run` a symlink to `/run` on your system? Samba is configured to use `/run/samba`, but `/var/run` should point to that anyway.

I have a few key differences in the `[global]` section of my `smb.conf` file:
1. I do not specify `map to guest`, instead relying on the default `map to guest = Never`.
2. I do not specify `passdb backend`, instead relyong on the default `passdb backend = tdbsam`. The manual page notes that "[s]ome Samba features will not work if [the smbpasswd] backend is used".
3. I have `server min protocol = SMB2`, but I doubt this is responsible for your issue.

The value of `--no-process-group` is still not clear to me.

**Comment by Anachron** [comment]
My cleaning script:

```
#!/bin/sh

sv stop nmbd smbd
! pgrep -f "nmbd -F -S" || kill -9 $(pgrep -f "mbd -F -S")
rm -rf /var/run/samba /var/cache/samba /var/lib/samba
! test -d /etc/samba || mv /etc/samba /etc/samba-$(date +%Y%m%d-%H%M%S).bak
rm /var/service/smbd /var/service/nmbd
xbps-remove -R smbclient samba samba-libs
```

My install script:
```
#!/bin/sh

xbps-install ${@} --repository="${HOME}/pr-27626" samba smbclient
```

Using the default `smb.conf` (minus printers)
```
[global]
   workgroup = MYGROUP
   server string = Samba Server
   server role = standalone server
   log file = /var/log/samba/%m.log
   max log size = 50
   dns proxy = no 
[homes]
   comment = Home Directories
   browseable = no
   writable = yes
```

nmbd is fine:
```
2021-01-04T18:16:35.97146 daemon.notice: Jan  4 19:16:35 nmbd: Samba name server VOID-RPI3 is now a local master browser for workgroup MYGROUP on subnet 192.168.178.20
```

But smbd is still erroring:
```
2021-01-04T18:16:36.30801 daemon.notice: Jan  4 19:16:36 smbd: smbd version 4.13.3 started.
2021-01-04T18:16:36.30821 daemon.notice: Jan  4 19:16:36 smbd: Copyright Andrew Tridgell and the Samba Team 1992-2020
2021-01-04T18:16:36.38221 daemon.notice: Jan  4 19:16:36 smbd: main: Failed to setup RPC server: NT_STATUS_UNSUCCESSFUL
2021-01-04T18:16:36.38247 daemon.notice: Jan  4 19:16:36 smbd: exit_daemon: daemon failed to start: Samba cannot setup ep pipe, error code 13
2021-01-04T18:16:37.70446 daemon.notice: Jan  4 19:16:37 smbd: smbd version 4.13.3 started.
2021-01-04T18:16:37.70471 daemon.notice: Jan  4 19:16:37 smbd: Copyright Andrew Tridgell and the Samba Team 1992-2020
2021-01-04T18:16:37.77915 daemon.notice: Jan  4 19:16:37 smbd: main: Failed to setup RPC server: NT_STATUS_UNSUCCESSFUL
2021-01-04T18:16:37.77944 daemon.notice: Jan  4 19:16:37 smbd: exit_daemon: daemon failed to start: Samba cannot setup ep pipe, error code 13
```

Versions:
```
-bash-5.0# xbps-query -p pkgver samba
samba-4.13.3_1
-bash-5.0# xbps-query -p pkgver smbclient
smbclient-4.13.3_1
-bash-5.0# xbps-query -p pkgver samba-libs
samba-libs-4.13.3_1
-bash-5.0# uname -r
5.4.68_1
```

**Comment by ahesford** [comment]
I populated a USB stick with the Void 20201224 PLATFORMFS image for rpi3 and used it to boot an RPi 3B+. Then, I installed `samba-4.13.3_1` from my repo and was able to launch `smbd` using the default service file. The config looks like yours, except my workgroup is `WORKGROUP`, I dropped the `server role` line (which seems to be the default when no `security` option is provided), `max log size = 1024`, and I left off the `dns proxy` line (which should default to `yes`).

Note that my first attempt to run `smbd` manually was met with the error
> daemon failed to start: Failed to create session, error code 1
which appears to have been caused by a missing `/run/samba`; note that the service file creates this directory if it does not exist.

**Comment by Anachron** [comment]
Found some weird stuff (check the dates) in /var/lock/samba

```
 rpi@void-rpi3 ~ » ls -lisa /var/lock/samba/msg.lock/
insgesamt 20
11351 0 drwxr-xr-x 2 root root 140  4. Jan 23:31 .
11350 0 drwxr-xr-x 3 root root 280  4. Jan 19:16 ..
11103 4 -rw-r--r-- 1 root root  20  1. Jan 1970  291
 7790 4 -rw-r--r-- 1 root root  20  1. Jan 1970  397
18679 4 -rw-r--r-- 1 root root  20  4. Jan 13:52 4869
16089 4 -rw-r--r-- 1 root root  21  4. Jan 13:52 4870
20828 4 -rw-r--r-- 1 root root  21  4. Jan 19:31 5748
```

Will keep investigating tomorrow.

**Comment by Anachron** [comment]
@ahesford pretty sure the issue is local on my end. Do you want to keep for merging this PR?

**Comment by ericonr** [comment]
@Anachron do oyu have an RTC or something of the sort? You can try to enable the fake-hwclock service to see if that's what's causing the issue (it likely is).

**Comment by ahesford** [comment]
I'm making a few adjustments and will merge shortly.

**Comment by ahesford** [comment]
Merged in 92ac0f5fc618b37fb5602190f4628c396ad405da and 6f0dda0a07cd1a6740b8b9ca15140866c6c13195

**Comment by Anachron** [comment]
Heads up! The latest changes work again. Samba now runs. Thanks, @ahesford!

**Pull request closed without merging**
