### PR TITLE
Julia: update to 1.0.0. [ci skip]

### PR DESCRIPTION
**Pull request by non-Jedi**
Unfortunately, Julia 1.0.0 needs a patched llvm to run. All of the patches included here have been submitted to upstream llvm, and as far as I know will be included in llvm 7.0. If patching llvm like this is something we're unwilling to do, the other option would be to allow Julia to vendor in its own copy of llvm...

Is there anything I need to do wrt packages that depend on llvm when I revbump it like this?

Other changes here are a general cleanup of the package template, removal of FFTW as fast fourier transform functionality has been moved outside of base Julia, and move of the julia config from `/etc/julia/juliarc.jl` to `/etc/julia/startup.jl`. Future work is to make this work with void-packages copy of utf8proc since it expects the header to be in a different location than it is.

This was the only package depending on llvm 3.9. Is it okay to include removal of llvm 3.9 in this PR?

### CODE REVIEW

**Comment by non-Jedi** [comment]
For the record since this can't finish in Travis, I have built this locally, and everything seemed to work fine.

**Comment by Chocimier** [comment]
Is `/etc/julia/juliarc.jl` removed on update, or not?

**Comment by non-Jedi** [comment]
Yes. It isn't needed any more. Is there something I should be doing to make that happen?

**Comment by cr6git** [comment]
https://github.com/void-linux/void-packages/pull/1926

**Comment by Chocimier** [comment]
I was interested in modified `/etc/julia/juliarc.jl`. It should not be removed, an in fact it is not, but for another reason: xbps do not remove modified files. That's good.

**Comment by non-Jedi** [comment]
@Cogitri unless 7.0 is a minor version bump in disguise, Julia almost certainly won't work with it, and we'd need to keep a version of llvm 6 around. At least speaking historically, Julia has not worked easily with new llvm major versions.

**Comment by Cogitri** [comment]
Julia compiled just fine for me - I haven't runtime tested it yet though.

Also,
> Unfortunately, Julia 1.0.0 needs a patched llvm to run. All of the patches included here have been submitted to upstream llvm, and as far as I know will be included in llvm 7.0.

Sounds to me as if Julia 1.0.x might work with LLVM 7 as well?

**Comment by non-Jedi** [comment]
If you haven't cherry-picked bdc44e5ff104c11ee866184e838acb21bfe2e621, the existing Julia 0.6.4 template uses llvm 3.9 not the latest llvm, so it wouldn't be affected by the upgrade to LLVM 7 at all. I'm skeptical that Julia would work with llvm 7, but it's definitely worth trying and a much better option than patching llvm 6 if it does work.

**Comment by Cogitri** [comment]
Ah, yeah, my bad, mixed that up. Thanks for testing it with Julia 1.0.0

**Comment by non-Jedi** [comment]
From https://github.com/JuliaLang/julia/pull/28809, there are still a (somewhat smaller) set of patches to be applied to LLVM 7. Going to comment and do some digging to see if I can get some clarity on why those haven't been upstreamed.

**Comment by non-Jedi** [comment]
As an update, llvm 7 still will not work for Julia unpatched. With two exceptions, all necessary patches for llvm 6 have been submitted upstream but have not yet been merged seemingly due to lack of attention on the llvm side. While it may be possible to patch llvm 7 and run Julia with that, it is not yet a solution even the master branch of Julia is ready for, so I would strongly prefer to continue to run Julia with llvm 6. I would also prefer for the aforementioned llvm 6 to be packaged separately from Julia, but since Julia will be the only thing using it anyway, maybe it makes sense to just let the Julia build system vendor in its own patched llvm.

**Comment by non-Jedi** [comment]
Closing in favor of #3242.

**Pull request closed without merging**
