### PR TITLE
go: update to 1.19.

### PR DESCRIPTION
**Pull request by g4s8**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64 - GNU libc)

### CODE REVIEW

**Comment by classabbyamp** [comment]
I think you need to rebase your branch on the latest master, there are conflicts

**Comment by classabbyamp** [comment]
supercedes #38385

**Comment by paper42** [comment]
cc @the-maldridge

**Comment by icp1994** [comment]
https://github.com/golang/go/issues/52919#issuecomment-1206137273 should be relevant for the failed i686 build

**Comment by subnut** [comment]
Failing builds fixed in #38510

**Comment by paper42** [comment]
superseded by #38510

**Pull request closed without merging**
