### PR TITLE
webkit2gtk: update to 2.26.0

### PR DESCRIPTION
**Pull request by q66**
The new stable webkit2gtk series was released today, sooner than expected.

Needed building and testing:

- [x] ppc64le*
- [x] ppc64*
- [x] ppc*
- [x] x86_64
- [x] x86_64-musl
- [x] aarch64 (build)
- [x] armv7l (build)

I particularly need someone to test the x86_64 stuff again, and especially musl. 32-bit ARM builds would be nice too, I don't have any way to do them from there. I can test building aarch64, though

### CODE REVIEW

**Comment by Hoshpak** [comment]
x86_64 builds and runs fine. x86_64-musl and armv7l compile successfully.

**Comment by q66** [comment]
Alright. Just need someone to actually test on musl then... if you've got a binary package somewhere, I can test that myself

**Comment by Hoshpak** [comment]
Sure, the package is here:
https://owncloud.helmut-pozimski.de/index.php/s/os4XXLk2mjWnQme
and the -devel package:
https://owncloud.helmut-pozimski.de/index.php/s/gzpyQa9SKeLpiYT

**Comment by q66** [comment]
Well, appears to be OK in my VM... better testing in a native environment would be good though.

**Comment by q66** [comment]
My findings mostly show that gstreamer is indeed at fault here, more specifically the audio stream. I can seek in the video when paused, but when I try to play it out, it dies; it it dies on not being able play out a stream, completely on the gstreamer side...

So I kinda assume the problem is actually not webkit here... I even managed to get it to play the video for about a second, under some circumstances, before gst aborts the playback.

**Comment by q66** [comment]
Alright. Turns out my suspicion was right, and video playback works on machines with working audio. Most likely gstreamer craps out at getting access to audio device in my VM, which 2.24 ignored but 2.26 no longer ignores (probably because it uses a different gstreamer player abstraction, playbin3, for MSE sources like youtube). Testing by another person with a functional audio setup reveals that youtube playback is in fact completely fine.

Therefore, there are no more blockers from my side.

**Comment by Johnnynator** [comment]
I can't currently help much with that, gstreamer behaves totally borked on my system. But judging by your comment, the issue should be unrelated to Musl and is probably fine.

**Pull request merged**
