### PR TITLE
tiff: build tiff2ps and tiff2pdf

### PR DESCRIPTION
**Pull request by tornaria**
#### Testing the changes
- I tested the changes in this PR: **briefly**

These two very useful tools were declared "unsupported" in the current version of tiff (4.6.0, sep 2023).

See: http://www.simplesystems.org/libtiff/releases/v4.6.0.html#tools-changes

### CODE REVIEW

**Comment by cinerea0** [comment]
Given that upstream has directly stated these tools are unsupported it may be a better idea to move building them behind a non-default build option instead of enabling them for everyone.

**Comment by sgn** [comment]
I think those tools would be built by `tiff5` package instead, no?

**Comment by sgn** [comment]
So, anything unsupported stay with unsupported tiff

**Comment by tornaria** [comment]
Here's one attempt. I'm not sure I have the `conflicts=` line right.

OTOH, I wonder if, even if `tiff2ps` and `tiff2pdf` are "unsupported" in tiff 4.6.0. Is it better to build them from tiff 4.4.0 (linked to old libtiff) or build them from tiff 4.6.0 (linked to new libtiff).

Moreover, it seems that `tiff5` is only kept to support a nonfree / binary only package `wps-office` so it might be dropped at some point.

So, here's an alternative proposal: use `--enable-tools-unsupported`, but move the unsupported tools (`tiff2ps` and `tiff2pdf`) to a separate package `tiff-unsupported`.

Note that upstream differentiates between "unsupported" tools (`tiff2ps` and `tiff2pdf`) which are "easy" to build via a configure switch, and "archived" tools (`fax2ps`, ...) which are not built with a configure switch if I'm not mistaken. See: https://gitlab.com/libtiff/libtiff/-/merge_requests/520.

I can implement the alternative proposal if you agree with it.

**Comment by tornaria** [comment]
Here's the second attempt: this adds a subpkg `tiff-unsupported` which contains the two unsupported tools (which upstream still ships the source in the tarball, even if they don't build or install them by default). I added the man pages from tiff-4.5.1 since they are not in the tarball.

**Review by classabbyamp — CHANGES_REQUESTED** [review]
1. don't vendor manpages like this
2. I agree with sgn that these should be part of tiff5

**Pull request closed without merging**
