### PR TITLE
libcap(-pam): update to 2.64.

### PR DESCRIPTION
**Pull request by skmpz**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by skmpz** [comment]
Supersedes #32796

**Comment by ericonr** [comment]
Am slightly concerned about https://git.kernel.org/pub/scm/libs/libcap/libcap.git/commit/?id=73194f5369286e10c9e19cbd71de59c3b45b5789 because it breaks ABI. Will investigate a bit.

**Comment by tibequadorian** [comment]
new version is 2.63

can you update libcap-pam too? add the `if [ "$CROSS_BUILD" ] ...` section from libcap to fix cross compiling

**Comment by skmpz** [comment]
bumped both libcap and libcap-pam to 2.64.

**Pull request closed without merging**
