### PR TITLE
cross-vpkg-dummy: differentiate between musl and glibc.

### PR DESCRIPTION
**Pull request by xtraeme**
A single pkg that provides musl and glibc and conflicts
with both, this is not a great idea.

Differentiate them to avoid issues like:

https://build.voidlinux.org/builders/armv6l-musl_builder/builds/19727/steps/shell_3/logs/stdio

Signed-off-by: Juan RP <xtraeme@gmail.com>

### CODE REVIEW

**Comment by xtraeme** [comment]
@pullmoll

**Comment by pullmoll** [comment]
This is of course the way to go, i.e. depend on those packages which the libc etc. provides.

**Comment by xtraeme** [comment]
@pullmoll yeah, I'm surprised this worked all this time! heh

**Comment by pullmoll** [comment]
I never thought much about it when adding the entries for the `cross*` sub-packages.

**Comment by pullmoll** [comment]
Can we merge this right away without interfering with libressl dependency updates?

**Comment by xtraeme** [comment]
Should be fine now that cross.sh explicitely requires `cross-vpkg-dummy>=0.30`.

**Comment by xtraeme** [comment]
@pullmoll yeah, should be ok.

**Pull request merged**
