### PR TITLE
spdlog: update to 1.10.0.

### PR DESCRIPTION
**Pull request by skmpz**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by Johnnynator** [comment]
You should always check some dependents of a library when updating it, spdlog did break ABI and therefore nheko, MangoHud, cryfs and gerbera did need to be recompiled.

**Comment by skmpz** [comment]
hm.. correct, but out of curiosity, why aren't those listed with `xbps-query -X spdlog`

**Comment by Johnnynator** [comment]
You need to use -RX to also list packages that aren't installed on your system.

**Comment by skmpz** [comment]
this will also show reverse runtime dependencies though and not build dependencies right ?
```
$ sudo xbps-query -RX spdlog
coeurl-devel-0.1.1_1
```
Just wondering if there's any other way other than just grepping through the srcpkgs folder to find reverse build dependencies..

**Comment by skmpz** [comment]
i guess `xrevshlib spdlog` does exactly that :).. Anyway, thanks for the input and sorry for the trouble caused.

**Comment by skmpz** [comment]
just another question.. when getting 
```
$ xrevshlib spdlog
Bear
coeurl
cryfs
gerbera
MangoHud
nheko
Waybar
```
Is there a way to figure out which packages need to be recompiled?

**Comment by Johnnynator** [comment]
> 

Ideally a package does increase the so version (the number behind `.so` as listed in e.g. `common/shlibs` in xbps-src).
spdlog did not do that in 1.10.0 ( https://github.com/gabime/spdlog/issues/2369 ), but they changed their build system to also include minor version in there, so this specific issue is unlikely to happen again.

> Is there a way to figure out which packages need to be recompiled?

Void currently doesn't have tooling in xbps-src to track symbols, so no automatic way for detecting this.
You (or a script) could in theory just install all of these packages and check if all the symbols do resolve.

**Comment by skmpz** [comment]
ah ok got it.. thanks again..

**Comment by Piraty** [comment]
https://abi-laboratory.pro/index.php?view=abi-tracker comes to mind

**Pull request merged**
