### PR TITLE
gns3-server: update to version 2.2.43.

### PR DESCRIPTION
**Pull request by SpidFightFR**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (X64-GlibC)

Hey lads, i tried to update GNS3 server, as it was an idea i got for a school project, basically, the web ui was broken before version 2.2.40.
However the building process acted weird: it went SUPER FAST, with warnings, sure, but all the way through.
It's weird to me, so i'll make this a draft PR, if someone can confirm me it's a normal behavior, then i'll make it a normal PR, but i think something is wrong here, even tho xbps-src went all way through.

I also removed the importlib patch as the modifications brought by it were already in the distant repo, it was no longer useful.

### CODE REVIEW

**Comment by SpidFightFR** [comment]
Okay so something IS wrong. Yet i managed to build it somehow LOL.
If i get some time to look about it, i'll do it.

**Comment by classabbyamp** [comment]
> Okay so something IS wrong. Yet i managed to build it somehow LOL. If i get some time to look about it, i'll do it.

it worked locally because you didn't run check (i.e. `xbps-src pkg -Q gns3-server`). The error is saying it doesn't have a library it needs, so I would suggest ensuring that `depends` contains [everything necessary](https://github.com/GNS3/gns3-server/blob/v2.2.43/requirements.txt)

**Comment by SpidFightFR** [comment]
> > Okay so something IS wrong. Yet i managed to build it somehow LOL. If i get some time to look about it, i'll do it.
> 
> it worked locally because you didn't run check (i.e. `xbps-src pkg -Q gns3-server`). The error is saying it doesn't have a library it needs, so I would suggest ensuring that `depends` contains [everything necessary](https://github.com/GNS3/gns3-server/blob/v2.2.43/requirements.txt)

Agreed. I'll check once again later on but i don't have much time... So sorry for keeping you waiting 😅

**Comment by SpidFightFR** [comment]
Alright lads hello !
I made some advancements with the template, i added `python3-platformdirs` and `python3-truststore` (new template, btw) as they are new requirements. however, there seems to be issues with the python checks with qemu, but i think it's a GNS3 thing, so i'll go check in the issue tab of the project.

**Comment by SpidFightFR** [comment]
Okay so the truststore dep had issues building on aarch64 & arm platforms so i configured the template accordingly.

But i made mistakes in the process, so i'll take time to finish that.

**Comment by biopsin** [comment]
duplicate of #41472

**Pull request closed without merging**
