### PR TITLE
mixxx: update to 2.3.3.

### PR DESCRIPTION
**Pull request by prez**
#### Testing the changes
- I tested the changes in this PR: Yes*

#### Local build testing
- I built this PR locally for my native architecture (x86_64-glibc)

### CODE REVIEW

**Comment by prez** [comment]
Pinging the maintainer, @Gottox

**Comment by prez** [comment]
No response from @Gottox  in over 2 1/2 months. Claiming maintainership.

**Comment by chilledfrogs** [comment]
I just built this locally, it seems to work, would be great to have it finally merged; could you please rebase it against the current master so that CI passes and perhaps rename the GitHub PR title to match the commit title?

**Comment by chilledfrogs** [comment]
Could you rebase again on the latest master @prez? I tried the failing builds locally and they somehow work so yeah, worth another try

**Pull request merged**
