### PR TITLE
libappindicator, libindicator: remove package

### PR DESCRIPTION
**Pull request by paper42**
uses python2, not maintained since 2012, replaced by libayatana-appindicator

### CODE REVIEW

**Comment by classabbyamp** [comment]
missing removed-packages or a transitional dummy pkg?

**Comment by paper42** [comment]
> missing removed-packages or a transitional dummy pkg?

I don't know if we should do that this time. Removing them has some value - we will be a few packages closer to dropping Python 2, but also people might want libappindicator when they compile something on their own. I didn't add them to removed-packages, so they should be still usable for a while.

**Comment by classabbyamp** [comment]
does ayatana provide a compatible api or would people compiling things need to make some changes to the thing they're compiling?

**Comment by paper42** [comment]
> does ayatana provide a compatible api or would people compiling things need to make some changes to the thing they're compiling?

from what I know, the API is compatible, but the library name is different, so you have to at least fix that in the build system and includes in the sources

**Comment by datleviet** [comment]
Is it safe to create a symlink `libappindicator3.so.1` to `libayatana-appindicator3.so.1`?

**Pull request merged**
