### PR TITLE
New package: wf-recorder-0.2

### PR DESCRIPTION
**Pull request by maybe-one-day-ubermensch**
solves [#14976](https://github.com/void-linux/void-packages/issues/14976)

### CODE REVIEW

**Comment by maybe-one-day-ubermensch** [comment]
It appears that wayland-scanner is only present on x86_64* and i686, I'll restrict the template to only those archs.

**Comment by ndowens** [comment]
> It appears that wayland-scanner is only present on x86_64* and i686, I'll restrict the template to only those archs.

It shouldn't be? Looking at testing on others.

**Comment by maybe-one-day-ubermensch** [comment]
Gotcha, thanks for looking into it! I am a little confused as to why wayland-devel needs to be in both makedepends and hostmakedepends.

**Comment by xtraeme** [comment]
wayland-devel needs to be in hostmakedepends and makedepends because cross compilation needs to both access host and target architecture.

**Comment by maybe-one-day-ubermensch** [comment]
I understand now, thanks for the clarification!

**Pull request merged**
