### PR TITLE
tor: update to 0.4.7.9.

### PR DESCRIPTION
**Pull request by daniel-eys**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by steinex** [comment]
Running fine on my 2 relays.

**Comment by steinex** [comment]
0.4.7.10 is out

**Comment by zcid** [comment]
I made a PR for 0.4.7.10

https://github.com/void-linux/void-packages/pull/38640

**Comment by classabbyamp** [comment]
#38640

**Pull request closed without merging**
