### PR TITLE
[RFC] gc: update to 8.2.0, cleanup.

### PR DESCRIPTION
**Pull request by tornaria**
I was looking for out of date dependencies for sage so I updated `gc` to 8.2.0. After I had already finished I realized that 8.2.0 is experimental; it seems all the `*.*.0` releases are experimental so I added an ignore to the update file.

Even if this is not to merge now (although it might be useful to merge the ignore), I made some cleanup for some things that seem to be old and not needed anymore -- but since I'm not sure I'm asking for comments.

Cleanup 1: for musl, the current template sets `CFLAGS='-D_GNU_SOURCE -DNO_GETCONTEXT -DSEARCH_FOR_DATA_START -DUSE_MMAP -DHAVE_DL_ITERATE_PHDR'` but all of this seems noop except maybe `-DSEARCH_FOR_DATA_START` which I don't understand; it seems originally came from alpine which afaict doesn't use it anymore. In any case I'd argue for using the same CFLAGS for all archs and since this seems to be working without any...

Cleanup 2: there is a `post_install()` which installed headers, in fact it just copied all of the `include` dir in the source which also contains build artifacts. It seems to me the upstream make install works ok. It should be pointed out that some headers are not installed, seemingly those related to c++. But if c++ support is needed, passing `--enable-cplusplus` to configure seems the right way and then it will not only install those headers but also install a couple extra shared libraries so maybe installing just the .h is useless.

My test of the resulting packages (after the cleanup) is to compile and check ecl (using #34175) and while a small number of tests fail it doesn't seem to be the change in gc causing that (I tested on glibc and musl with both 8.0.6 and 8.2.0).

Maybe @ivmai can give us some feedback about these changes, and also please confirm that `*.*.0` is always experimental so it's safe to ignore in the update-check.

### CODE REVIEW

**Comment by leahneukirchen** [comment]
sgtm, but i'd just wait for 8.2.1.

**Comment by ivmai** [comment]
Hi @tornaria,

> After I had already finished I realized that 8.2.0 is experimental; it seems all the *.*.0 releases are experimental so I added an ignore to the update file.

Yes, all *.*.0 releases are experimental (they are marked as Pre-release in Github releases). I'm working on stabilization (but the progress is no so fast as I expected, most probably stable release will merge before Feb 2022).

**Comment by ivmai** [comment]
> Cleanup 1: for musl, the current template sets CFLAGS='-D_GNU_SOURCE -DNO_GETCONTEXT -DSEARCH_FOR_DATA_START -DUSE_MMAP -DHAVE_DL_ITERATE_PHDR' but all of this seems noop except maybe -DSEARCH_FOR_DATA_START which I don't understand; it seems originally came from alpine which in fact doesn't use it anymore. In any case I'd argue for using the same CFLAGS for all archs and since this seems to be working without any...

Yes, I think most of them are no-op as you listed. As for SEARCH_FOR_DATA_START, I have several regular musl jobs on Travis (see (.travis.yml)[https://github.com/ivmai/bdwgc/blob/master/.travis.yml]) w/o this macro defined explicitly - the tests always pass. So, I don't know whether it is needed or not in practice. It look like both approaches are reliable - rely on __data_start or scanning of write-accessible space down from _end in case SEARCH_FOR_DATA_START, or rely on __environ otherwise (the default in upstream).

Up to you but my suggestion: to remove SEARCH_FOR_DATA_START and see if there any bug reports (or search for similar bugs in the past) , if yes then report the bug upstream.

**Comment by ivmai** [comment]
> Cleanup 2: there is a post_install() which installed headers, in fact it just copied all of the include dir in the source which also contains build artifacts. It seems to me the upstream make install works ok. 

Sure. I just haven't tried this in my (PR)[https://github.com/void-linux/void-packages/pull/33426].

**Comment by ivmai** [comment]
> My test of the resulting packages (after the cleanup) is to compile and check ecl (using #34175) and while a small number of tests fail it doesn't seem to be the change in gc causing that (I tested on glibc and musl with both 8.0.6 and 8.2.0

Sure. The experimental status of the release is a message to the downstream package maintainers and other users "a release with new features and significant code changes is prepared, a lot of testing has been done by the upstream maintainer on some major targets like linux/x64, please test it in your environments and/or give your users ability to test this experimental release.

**Comment by tornaria** [comment]
@ivmai: thanks a lot for your comments. Since void linux means to ship only stable releases, we'll skip 8.2.0. I think when a new stable version is released we can proceed with the cleanups outlined in this PR (and also add `*.*.0` to ignore so we know to skip those releases in the future).

Regarding `SEARCH_FOR_DATA_START` and musl, just a note that  that alpine is not currently using it (https://git.alpinelinux.org/aports/tree/main/gc/APKBUILD).

**Comment by ivmai** [comment]
> Regarding SEARCH_FOR_DATA_START and musl, just a note that that alpine is not currently using it

Got it. Thank you

**Pull request closed without merging**
