### PR TITLE
firefox, firefox-esr, thunderbird: fix patch whitespace

### PR DESCRIPTION
**Pull request by foopub**
Needed because of https://github.com/void-linux/void-packages/commit/7b4119df5cbc0cc37348164a10c88a32910009d8 
See also https://github.com/void-linux/void-packages/issues/33915

### CODE REVIEW

**Comment by ericonr** [comment]
Please fix commit title. If you can check it out, `thunderbird` currently has the same patch.

**Comment by foopub** [comment]
> Please fix commit title. If you can check it out, `thunderbird` currently has the same patch.

mmmm I think a lot of packages might have the same problem in general, firefox-esr  seems to have the same specific patch too... I'm not sure what a good systematic way to fix all of these might be.

**Comment by foopub** [comment]
It's probably worth creating an issue for this, but imo the -l option should be retained for specific filetypes which are whitespace insensitive, such as C family langs, etc. 

Or more simply, only apply it to filetypes which are whitespace sensitive, because those tend to be fewer (only python off the top of my head).

Unless someone has a good way of fixing all of these systematically...

**Comment by ericonr** [comment]
Did you see the patch that prompted this? `-l` caused it to be applied in the wrong place.

**Comment by q66** [comment]
yeah, `-l` is absolutely wrong and should never be used there; i anticipated there would be some breakage, but i figured patches can just get reviewed and fixed as they are found (there is no good way around this)

you can probably just copy this updated patch into firefox-esr and thunderbird as it is

**Comment by q66** [comment]
i think the number of bad patches that this breaks should be fairly low though

**Comment by foopub** [comment]
Which patch are you referring to? The firefox one wasn't affected by the whitespace. I'm not sure which patch led to the initial commit to remove `-l`

**Comment by foopub** [comment]
> yeah, `-l` is absolutely wrong and should never be used there; i anticipated there would be some breakage, but i figured patches can just get reviewed and fixed as they are found (there is no good way around this)
> 
> you can probably just copy this updated patch into firefox-esr and thunderbird as it is

Yeah but I just want to be extra sure the builds actually work... You can add more packages to the list https://github.com/void-linux/void-packages/issues/33917

**Comment by foopub** [comment]
No checks are running for `firefox-esr`?

**Comment by q66** [comment]
> Which patch are you referring to? The firefox one wasn't affected by the whitespace. I'm not sure which patch led to the initial commit to remove `-l`

see the commit message for https://github.com/void-linux/void-packages/commit/7b4119df5cbc0cc37348164a10c88a32910009d8 => https://github.com/void-linux/void-packages/commit/be0665ce5890dbae96a7254815b7ffc662f917de (https://gist.github.com/q66/061a35d2a5771ba87376d016dde7c46f)

**Pull request merged**
