### PR TITLE
New package: kak-lsp-5.6.0

### PR DESCRIPTION
**Pull request by skrps**

### CODE REVIEW

**Comment by TeddyDD** [comment]
Weird, it fails to build for me on x86_64
```
kak-lsp-5.2.2_1: running do_build ...
   Compiling num-traits v0.2.5
   Compiling proc-macro2 v0.4.19
   Compiling void v1.0.2
   Compiling unicode-xid v0.1.0
   Compiling num-integer v0.1.39
   Compiling matches v0.1.8
   Compiling unicode-normalization v0.1.7
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "/builddir/kak-lsp-5.2.2/target/release/build/num-traits-2b97e5b6c2c08a57/build_script_build-2b97e5b6c2c08a57.build_script_build0-e0f521057731687cd8328457a71ab228.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-traits-2b97e5b6c2c08a57/build_script_build-2b97e5b6c2c08a57.build_script_build1-e0f521057731687cd8328457a71ab228.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-traits-2b97e5b6c2c08a57/build_script_build-2b97e5b6c2c08a57.build_script_build10-e0f521057731687cd8328457a71ab228.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-traits-2b97e5b6c2c08a57/build_script_build-2b97e5b6c2c08a57.build_script_build11-e0f521057731687cd8328457a71ab228.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-traits-2b97e5b6c2c08a57/build_script_build-2b97e5b6c2c08a57.build_script_build12-e0f521057731687cd8328457a71ab228.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-traits-2b97e5b6c2c08a57/build_script_build-2b97e5b6c2c08a57.build_script_build13-e0f521057731687cd8328457a71ab228.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-traits-2b97e5b6c2c08a57/build_script_build-2b97e5b6c2c08a57.build_script_build14-e0f521057731687cd8328457a71ab228.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-traits-2b97e5b6c2c08a57/build_script_build-2b97e5b6c2c08a57.build_script_build15-e0f521057731687cd8328457a71ab228.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-traits-2b97e5b6c2c08a57/build_script_build-2b97e5b6c2c08a57.build_script_build2-e0f521057731687cd8328457a71ab228.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-traits-2b97e5b6c2c08a57/build_script_build-2b97e5b6c2c08a57.build_script_build3-e0f521057731687cd8328457a71ab228.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-traits-2b97e5b6c2c08a57/build_script_build-2b97e5b6c2c08a57.build_script_build4-e0f521057731687cd8328457a71ab228.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-traits-2b97e5b6c2c08a57/build_script_build-2b97e5b6c2c08a57.build_script_build5-e0f521057731687cd8328457a71ab228.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-traits-2b97e5b6c2c08a57/build_script_build-2b97e5b6c2c08a57.build_script_build6-e0f521057731687cd8328457a71ab228.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-traits-2b97e5b6c2c08a57/build_script_build-2b97e5b6c2c08a57.build_script_build7-e0f521057731687cd8328457a71ab228.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-traits-2b97e5b6c2c08a57/build_script_build-2b97e5b6c2c08a57.build_script_build8-e0f521057731687cd8328457a71ab228.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-traits-2b97e5b6c2c08a57/build_script_build-2b97e5b6c2c08a57.build_script_build9-e0f521057731687cd8328457a71ab228.rs.rcgu.o" "-o" "/builddir/kak-lsp-5.2.2/target/release/build/num-traits-2b97e5b6c2c08a57/build_script_build-2b97e5b6c2c08a57" "/builddir/kak-lsp-5.2.2/target/release/build/num-traits-2b97e5b6c2c08a57/build_script_build-2b97e5b6c2c08a57.crate.allocator.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-nodefaultlibs" "-L" "/builddir/kak-lsp-5.2.2/target/release/deps" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-56e2de1303ab6582.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-8098c8ed98d02cdf.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-3651197de35f6d0e.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-5532778d4a63ae64.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_system-c8d85144919fa19e.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-586097807ea1d9c0.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-316fe893d7fcc5cc.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-44315538ff52cc3f.rlib" "-Wl,--end-group" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-ae2a6290a47be8a5.rlib" "-Wl,-Bdynamic" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util"
  = note: /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-3651197de35f6d0e.rlib(jemalloc.pic.o): In function `malloc_init_hard':
          (.text.malloc_init_hard+0xdf): undefined reference to `pthread_atfork'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `num-traits`.
warning: build failed, waiting for other jobs to finish...
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "/builddir/kak-lsp-5.2.2/target/release/build/proc-macro2-4f4fc92f8427f218/build_script_build-4f4fc92f8427f218.build_script_build0-ad2989474b82f8093b1c814064b4948a.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/proc-macro2-4f4fc92f8427f218/build_script_build-4f4fc92f8427f218.build_script_build1-ad2989474b82f8093b1c814064b4948a.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/proc-macro2-4f4fc92f8427f218/build_script_build-4f4fc92f8427f218.build_script_build10-ad2989474b82f8093b1c814064b4948a.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/proc-macro2-4f4fc92f8427f218/build_script_build-4f4fc92f8427f218.build_script_build11-ad2989474b82f8093b1c814064b4948a.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/proc-macro2-4f4fc92f8427f218/build_script_build-4f4fc92f8427f218.build_script_build12-ad2989474b82f8093b1c814064b4948a.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/proc-macro2-4f4fc92f8427f218/build_script_build-4f4fc92f8427f218.build_script_build13-ad2989474b82f8093b1c814064b4948a.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/proc-macro2-4f4fc92f8427f218/build_script_build-4f4fc92f8427f218.build_script_build14-ad2989474b82f8093b1c814064b4948a.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/proc-macro2-4f4fc92f8427f218/build_script_build-4f4fc92f8427f218.build_script_build15-ad2989474b82f8093b1c814064b4948a.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/proc-macro2-4f4fc92f8427f218/build_script_build-4f4fc92f8427f218.build_script_build2-ad2989474b82f8093b1c814064b4948a.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/proc-macro2-4f4fc92f8427f218/build_script_build-4f4fc92f8427f218.build_script_build3-ad2989474b82f8093b1c814064b4948a.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/proc-macro2-4f4fc92f8427f218/build_script_build-4f4fc92f8427f218.build_script_build4-ad2989474b82f8093b1c814064b4948a.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/proc-macro2-4f4fc92f8427f218/build_script_build-4f4fc92f8427f218.build_script_build5-ad2989474b82f8093b1c814064b4948a.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/proc-macro2-4f4fc92f8427f218/build_script_build-4f4fc92f8427f218.build_script_build6-ad2989474b82f8093b1c814064b4948a.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/proc-macro2-4f4fc92f8427f218/build_script_build-4f4fc92f8427f218.build_script_build7-ad2989474b82f8093b1c814064b4948a.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/proc-macro2-4f4fc92f8427f218/build_script_build-4f4fc92f8427f218.build_script_build8-ad2989474b82f8093b1c814064b4948a.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/proc-macro2-4f4fc92f8427f218/build_script_build-4f4fc92f8427f218.build_script_build9-ad2989474b82f8093b1c814064b4948a.rs.rcgu.o" "-o" "/builddir/kak-lsp-5.2.2/target/release/build/proc-macro2-4f4fc92f8427f218/build_script_build-4f4fc92f8427f218" "/builddir/kak-lsp-5.2.2/target/release/build/proc-macro2-4f4fc92f8427f218/build_script_build-4f4fc92f8427f218.crate.allocator.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-nodefaultlibs" "-L" "/builddir/kak-lsp-5.2.2/target/release/deps" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-56e2de1303ab6582.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-8098c8ed98d02cdf.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-3651197de35f6d0e.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-5532778d4a63ae64.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_system-c8d85144919fa19e.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-586097807ea1d9c0.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-316fe893d7fcc5cc.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-44315538ff52cc3f.rlib" "-Wl,--end-group" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-ae2a6290a47be8a5.rlib" "-Wl,-Bdynamic" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util"
  = note: /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-3651197de35f6d0e.rlib(jemalloc.pic.o): In function `malloc_init_hard':
          (.text.malloc_init_hard+0xdf): undefined reference to `pthread_atfork'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `proc-macro2`.
warning: build failed, waiting for other jobs to finish...
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "/builddir/kak-lsp-5.2.2/target/release/build/num-integer-0f80e2bd9cb00d51/build_script_build-0f80e2bd9cb00d51.build_script_build0-bc02d23a683818f725576281ed5e35bd.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-integer-0f80e2bd9cb00d51/build_script_build-0f80e2bd9cb00d51.build_script_build1-bc02d23a683818f725576281ed5e35bd.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-integer-0f80e2bd9cb00d51/build_script_build-0f80e2bd9cb00d51.build_script_build10-bc02d23a683818f725576281ed5e35bd.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-integer-0f80e2bd9cb00d51/build_script_build-0f80e2bd9cb00d51.build_script_build11-bc02d23a683818f725576281ed5e35bd.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-integer-0f80e2bd9cb00d51/build_script_build-0f80e2bd9cb00d51.build_script_build12-bc02d23a683818f725576281ed5e35bd.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-integer-0f80e2bd9cb00d51/build_script_build-0f80e2bd9cb00d51.build_script_build13-bc02d23a683818f725576281ed5e35bd.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-integer-0f80e2bd9cb00d51/build_script_build-0f80e2bd9cb00d51.build_script_build14-bc02d23a683818f725576281ed5e35bd.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-integer-0f80e2bd9cb00d51/build_script_build-0f80e2bd9cb00d51.build_script_build15-bc02d23a683818f725576281ed5e35bd.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-integer-0f80e2bd9cb00d51/build_script_build-0f80e2bd9cb00d51.build_script_build2-bc02d23a683818f725576281ed5e35bd.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-integer-0f80e2bd9cb00d51/build_script_build-0f80e2bd9cb00d51.build_script_build3-bc02d23a683818f725576281ed5e35bd.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-integer-0f80e2bd9cb00d51/build_script_build-0f80e2bd9cb00d51.build_script_build4-bc02d23a683818f725576281ed5e35bd.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-integer-0f80e2bd9cb00d51/build_script_build-0f80e2bd9cb00d51.build_script_build5-bc02d23a683818f725576281ed5e35bd.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-integer-0f80e2bd9cb00d51/build_script_build-0f80e2bd9cb00d51.build_script_build6-bc02d23a683818f725576281ed5e35bd.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-integer-0f80e2bd9cb00d51/build_script_build-0f80e2bd9cb00d51.build_script_build7-bc02d23a683818f725576281ed5e35bd.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-integer-0f80e2bd9cb00d51/build_script_build-0f80e2bd9cb00d51.build_script_build8-bc02d23a683818f725576281ed5e35bd.rs.rcgu.o" "/builddir/kak-lsp-5.2.2/target/release/build/num-integer-0f80e2bd9cb00d51/build_script_build-0f80e2bd9cb00d51.build_script_build9-bc02d23a683818f725576281ed5e35bd.rs.rcgu.o" "-o" "/builddir/kak-lsp-5.2.2/target/release/build/num-integer-0f80e2bd9cb00d51/build_script_build-0f80e2bd9cb00d51" "/builddir/kak-lsp-5.2.2/target/release/build/num-integer-0f80e2bd9cb00d51/build_script_build-0f80e2bd9cb00d51.crate.allocator.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-nodefaultlibs" "-L" "/builddir/kak-lsp-5.2.2/target/release/deps" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-56e2de1303ab6582.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-8098c8ed98d02cdf.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-3651197de35f6d0e.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-5532778d4a63ae64.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_system-c8d85144919fa19e.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-586097807ea1d9c0.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-316fe893d7fcc5cc.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-44315538ff52cc3f.rlib" "-Wl,--end-group" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-ae2a6290a47be8a5.rlib" "-Wl,-Bdynamic" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util"
  = note: /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-3651197de35f6d0e.rlib(jemalloc.pic.o): In function `malloc_init_hard':
          (.text.malloc_init_hard+0xdf): undefined reference to `pthread_atfork'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `num-integer`.


```

**Comment by Johnnynator** [comment]
@TeddyDD try to update your masterdir `./xbps-src bootstrap-update`

**Comment by maxice8** [comment]
any objections ?

**Comment by maxice8** [comment]
Pushed a version that uses the new `cargo` build_style and is cross-compilable.

see https://github.com/void-linux/void-packages/commit/12c4b2c61b7d50ff38c41f5736eb1783636b8f62

**Pull request closed without merging**
