### PR TITLE
qtcurve: drop qt4 support

### PR DESCRIPTION
**Pull request by maxice8**
Do not merge until all qt4 stuff is thrown into the garbage

### CODE REVIEW

**Comment by Hoshpak** [comment]
Why? As long as there are still qt4 applications in the repository, having the qt4 style is still useful.

**Comment by maxice8** [comment]
On Mon, Oct 01, 2018 at 02:34:58AM -0700, Helmut Pozimski wrote:
> Why? As long as there are still qt4 applications in the repository, having the qt4 style is still useful.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/3266#issuecomment-425845923

They should be ported to qt5 or removed, qt4 upstream is dead and all distros are on different stages of removing it. Leaving it in is just asking to expose the users to security issues which not even debian cares to fix (https://security-tracker.debian.org/tracker/source-package/qt4-x11) so it is safe to assume we don't either.

**Comment by Hoshpak** [comment]
Completely removing qt4 is not feasible yet because there are still applications that are in the process of porting or haven't released a stable version with qt5 support yet. I'm not advocating for keeping qt4 forever but as long as there are applications in the repository that use it, it is useful to have a style for it that allows a somewhat consistent look for applications. I'm using at least one qt4 application (mumble) myself and use the qtcurve style with it. So removing theme support should be the last step after removing applications, not the first one.

**Comment by maxice8** [comment]
i'll mark it as nomerge for now

**Comment by Hoshpak** [comment]
Since qt4 supports using the currently configured GTK style, I could just configure qtcurve as my gtk2 style and tell qt4 to use the gtk2 style. So I withdraw my objection, feel free to merge any time.

**Pull request closed without merging**
