### PR TITLE
New package: colobot-0.2.0

### PR DESCRIPTION
**Pull request by tranzystorek-io**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by classabbyamp** [comment]
both packages seem to come from the same distfile. can the -data package be a subpkg?

**Comment by tranzystorek-io** [comment]
They come from different repositories (colobot vs colobot-data)

**Comment by classabbyamp** [comment]
ah i see now. might want to put a comment about keeping them sychronised if that's necessary

**Comment by tranzystorek-io** [comment]
Hm, the package builds libCBot.so by default (code for the in-game programming language). I'm 99% sure only the `colobot` game binary uses it, so we could probably switch to static lib instead?

**Pull request merged**
