### PR TITLE
common/gnu-configure-args: set exec_prefix to ${prefix}

### PR DESCRIPTION
**Pull request by sgn**
autotools will pass its configure_args to subdir if required,
if we don't init exec_prefix, it will pass --libdir=NONE/lib{32,64} to
subdir configure.

---

Found when fixing openmpi

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by sgn** [comment]
@ahesford And I think we can add `libevent-devel` into `makedepends` for `openmpi`?

**Comment by sgn** [comment]
Anyway, is it correct to move `ompi_monitoring_prof.so` to `-devel`

**Comment by ahesford** [comment]
Yes to adding `libevent-devel` to `makedepends`.

The `ompi_monitoring_prof.so` library is not intended for linking; it is [supposed to be used with LD_PRELOAD](https://github.com/open-mpi/ompi/blob/master/ompi/mca/common/monitoring/monitoring_prof.c#L30-L33). I recommend 
```bash
mv "${DESTDIR}/usr/lib/ompi_monitoring_prof.so" "${DESTDIR}/usr/lib/openmpi"
```
in `post_install` to keep this library out of `/usr/lib` but make it available to those interested in profiling without requiring `openmpi-devel`.

**Review by ahesford — APPROVED** [review]
I'm not sure if there are other packages that might be negatively affected by this change, but it seems reasonable to me. Otherwise, we'll need to move the argument to the openmpi template.

**Comment by sgn** [comment]
`--exec-prefix` is defaulted to `$prefix` anyway and `--prefix` has been set, I think most case should be covered, let's fix it later if anything arise, merging now.
Thanks.

**Pull request merged**
