### PR TITLE
linux4.20: Support for Marvell Espressobin

### PR DESCRIPTION
**Pull request by repk**
Marvell Espressobin boards need to have their SD host controller driver
(CONFIG_MMC_SDHCI_XENON) built-in to be able to boot a rootfs on the SD
card.

[skip ci]

### CODE REVIEW

**Comment by Cogitri** [comment]
Hum, shouldn't it work if you have that module in your initramfs?

**Comment by repk** [comment]
Yes it will work. But with that I don't need an initramfs to boot.

By looking at all the CONFIG_MMC_* it seems that all other supported boards has their SD host controller built-in along with a lot of stuff (USB, ...). So I though it was the spirit for arm64 boards to get their memory controller built in.

I am not strongly against using that in an initramfs but if we do that it would be coherent to do it for all the other boards so espressobin is not unfairly treated, don't you think ?

It also makes bootstrapping way easier.

**Comment by Cogitri** [comment]
Ah, I wasn't aware that this was an usual thing to do for ARM boards, it was just a suggestion from my side :)

**Comment by repk** [comment]
Yes and it was a sane suggestion :), I asked myself the very same thing. The answer above is just the rational that made me think that built in was the way to go.

Let see what the maintainer prefers.

**Comment by Hoshpak** [comment]
I don't have a strong opinion about this. Most configuration options in the arm kernel configurations are just carried over from earlier versions and I don't own any aarch64 hardware myself so input from people running this on actual hardware is always appreciated. The only scenarios I would want to avoid is the kernel image getting too big for some boards or having to create 50+ different kernel flavors because something causes incompatibilities. I don't think either one would be the case here so I would be fine with merging it. If you want the change to end up in the kernel package immediately, the commit also needs to bump the revision of the package. Currently no big rebuilds are going on so I think we could afford rebuilding the kernel once.

**Comment by repk** [comment]
Ok, I have updated kernel version.

**Pull request merged**
