### PR TITLE
evieext: Remove package

### PR DESCRIPTION
**Pull request by mnabid**
Not needed anymore. Replaced by `xorgproto`.

Closes: #22172

### CODE REVIEW

**Comment by mnabid** [comment]
@ericonr

**Comment by ericonr** [comment]
Can you make it clear in the commit message that it missed a revbump? Otherwise the reason for the rebuild isn't very obvious.

**Comment by mnabid** [comment]
@ericonr Done.

**Comment by ericonr** [comment]
Possibly add this to the commit as well, realized it wasn't there:

> Replaced by xorgproto.

Otherwise, looks good to me, now to wait for some void-packager. :)

**Pull request merged**
