### PR TITLE
jupyterlab: update to 4.1.5.

### PR DESCRIPTION
**Pull request by tornaria**
#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by dkwo** [comment]
@cinerea0 Do you mind looking at this one too?

**Comment by tornaria** [comment]
Please wait a bit. There have been a few more updates and I'm working on it.

**Comment by tornaria** [comment]
@dkwo updated to jupyterlab 4.1.5 now, if you want to try.

**Comment by dkwo** [comment]
looks good, thanks.
i also had to disable that test for jupyterlab, otherwise it was failing locally on x86_64 for me.

**Comment by tornaria** [comment]
@cinerea0 could you have a look at this one now? Thanks!

**Pull request merged**
