### PR TITLE
New package: hiddify-next client

### PR DESCRIPTION
**Pull request by hesam-init**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)

### CODE REVIEW

**Comment by tranzystorekk** [comment]
We don't accept repackaging prebuilt `.deb` distributions etc.

**Comment by hesam-init** [comment]
> We don't accept repackaging prebuilt `.deb` distributions etc.

But this package needs flutter to build

**Comment by tranzystorekk** [comment]
That does not change Void policy on repackaging, this PR won't be accepted as is.

**Comment by hesam-init** [comment]
> That does not change Void policy on repackaging, this PR won't be accepted as is.

Are there any guides or build style available for building Flutter packages ?

**Comment by tranzystorekk** [comment]
Looking at #43438 I don't think it's likely.

**Pull request closed without merging**
