### PR TITLE
SuiteSparse: update to 6.0.1.

### PR DESCRIPTION
**Pull request by tornaria**
#### Testing the changes
- I tested the changes in this PR: **briefly**

`SuiteSparse` is used in sagemath through `python3-cvxopt` -- I ran the sagemath testsuite with this update.

### CODE REVIEW

**Comment by tornaria** [comment]
What shall we do about this:
```
SuiteSparse-devel and mongoose-devel conflict for
  /usr/lib/libmongoose.a
  /usr/lib/libmongoose.so
Error: Process completed with exit code 1.
```

**Comment by tornaria** [comment]
The CI failures look harmless:
 - A file conflict that we already have; I don't know how this can be resolved.
```
SuiteSparse-devel and mongoose-devel conflict for
  /usr/lib/libmongoose.a
  /usr/lib/libmongoose.so
```
- Package `igraph` used to depend on a shlib that bumped soname so it would merit a revbump. However, there is #40224 to update  `igraph`, the new version does not depend on SuiteSparse at all.
```
Trying to install dependants of SuiteSparse-devel:
igraph-0.9.8_1: broken, unresolvable shlib `libcxsparse.so.3'
Transaction aborted due to unresolved shlibs.
```

**Comment by tornaria** [comment]
Apologies for the multiple force-push. Just two changes:
 - added more shlibs to `common/shlibs`, they will be used by octave in #40720
 - annotate the conflict between `SuiteSparse-devel` and `mongoose-devel`

Hopefully with these two changes CI will pass.

**Comment by tornaria** [comment]
Now the three CI failures are just the expected `igraph-0.9.8_1: broken, unresolvable shlib `libcxsparse.so.3'` because of the soname change. This will resolve once #40224 is merged, since igraph-0.10.2 does not link to SuiteSparse at all, it seems a waste to revbump igraph here.

**Comment by Piraty** [comment]
of course igraph requires a revbump, in `igraph-0.9.8_1`,  `libigraph.so.0.0.0` links `libcxsparse.so.3`

**Comment by Piraty** [comment]
can you please rebase, so CI runs again

**Comment by tornaria** [comment]
> can you please rebase, so CI runs again

Done, everything passed.

Thanks!

**Pull request merged**
