### PR TITLE
darktable: update to 3.4.0.

### PR DESCRIPTION
**Pull request by lemmi**

### CODE REVIEW

**Comment by lemmi** [comment]
For the brave and CI :)

**Comment by ericonr** [comment]
Immediatelly segfaults at launch on musl :/ 

Backtrace: 
[darktable_bt_UTSIW0.txt](https://github.com/void-linux/void-packages/files/5742704/darktable_bt_UTSIW0.txt)

**Comment by ericonr** [comment]
Patch:

```
diff --git src/bauhaus/bauhaus.c src/bauhaus/bauhaus.c
index a7350bf..ff5a071 100644
--- src/bauhaus/bauhaus.c
+++ src/bauhaus/bauhaus.c
@@ -856,7 +856,7 @@ void dt_bauhaus_slider_enable_soft_boundaries(GtkWidget *widget, float hard_min,
 
 void dt_bauhaus_widget_set_label(GtkWidget *widget, const char *section_orig, const char *label_orig)
 {
-  const char *section = _(section_orig);
+  const char *section = section_orig ? _(section_orig) : NULL;
   const char *label = _(label_orig);
 
   dt_bauhaus_widget_t *w = DT_BAUHAUS_WIDGET(widget);
```

**Comment by ericonr** [comment]
My patch has been pulled into 3.4.1, if you want to wait for that.

**Comment by ericonr** [comment]
Ping

**Comment by lemmi** [comment]
I asked this week about the `3.4.1` release. Sounded like they wanted to cut a release soon. Although they were a little vague. I might just pick your patch and bump it this weekend.

**Review by ericonr — APPROVED** [review]

**Pull request closed without merging**
