### PR TITLE
libinput-debug-gui: update to 1.23.0, add update-check

### PR DESCRIPTION
**Pull request by spiwocoal**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - armv6l

### CODE REVIEW

**Comment by Bnyro** [comment]
I think it would be better if both commits for `libinput-debug-gui` are in a single commit, with a commit message like `libinput-debug-gui: update to 1.23.0, fix update-check`.

**Comment by classabbyamp** [comment]
it should be one commit per package in the pr, and the makedepends line was fine as-is

**Comment by spiwocoal** [comment]
> it should be one commit per package in the pr, and the makedepends line was fine as-is

should I also include the update-check into the same commit as the update to 1.23.0 for libinput-debug-gui then?

**Comment by Bnyro** [comment]
Yes, exactly

**Comment by Bnyro** [comment]
libinput-debug-gui: update to 1.23.0, fix update-check

**Comment by classabbyamp** [comment]
I think you lost the libinput update

**Comment by spiwocoal** [comment]
I'm not sure what you mean?
Libinput hasn't gotten any new version, I just fixed update-check for that package because from version 1.20.0, new updates are no longer listed on their homepage ([https://www.freedesktop.org/wiki/Software/libinput/](https://www.freedesktop.org/wiki/Software/libinput/)), but on their Gitlab releases page.

**Comment by classabbyamp** [comment]
hm it seems libinput was not kept in sync...

**Comment by classabbyamp** [comment]
anyways, the site= in the update files is not needed, it is detected becuase of the distfiles url.

**Comment by Bnyro** [comment]
Wouldn't it have made sense to keep both in the same template and just symlink lininput-debug-gui to libinput?

**Comment by Bnyro** [comment]
(When the package got added initially)

**Comment by classabbyamp** [comment]
no, it needs to be split to ensure a dependency cycle is not created

**Comment by spiwocoal** [comment]
Should be OK now, I wasn't aware that update-check could check for new releases without `site` specified. This makes it unnecessary to fix anything for libinput.

**Comment by classabbyamp** [comment]
yep, the update file is just for overriding defaults

**Pull request closed without merging**
