### PR TITLE
cross-i686 compiler: keep sysroot /lib symlink

### PR DESCRIPTION
**Pull request by sgn**
When packaging Firefox ESR 68.1.0 #14229 , and cross compile i686 from x86_64,
I received this complains:
> 0:06.67 DEBUG: | /usr/lib/gcc/i686-pc-linux-gnu/9.2.0/../../../../i686-pc-linux-gnu/bin/ld: cannot find /lib/libc.so.6 inside /usr/i686-pc-linux-gnu
> 0:06.67 DEBUG: | /usr/lib/gcc/i686-pc-linux-gnu/9.2.0/../../../../i686-pc-linux-gnu/bin/ld: cannot find /lib/ld-linux.so.2 inside /usr/i686-pc-linux-gnu

I didn't run into this complain when packaging aarch64 from x86_64,
I have a different problem when packaging ppc64le from x86_64

### CODE REVIEW

**Comment by Piraty** [comment]
(Unrelated to you actual PR)
You don't need to cross-compile from x86_64* to i686 and are better off using a masterdir with the desired arch instead:
```
./xbps-src -m masterdir-i686 binary-bootstrap i686
./xbps-src -m masterdir-i686 pkg foo
```
That's probably why nobody noticed before

**Comment by zdtcd** [comment]
On September 11, 2019 7:51:08 PM UTC, Piraty <notifications@github.com> wrote:
>(Unrelated to you actual PR)
>You don't need to cross-compile from x86_64* to i686 and are better off
>using a masterdir with the desired arch instead:
>```
>./xbps-src -m masterdir-i686 binary-bootstrap i686
>./xbps-src -m masterdir-i686 pkg foo
>```
>That's probably why nobody noticed before

Well, I knew we can bootstrap i686 in x86_64.
I tested that build in my PR, see first comment.
-- 
Danh

**Comment by zdtcd** [comment]
Ping

**Comment by Piraty** [comment]
I looked into it, but cannot reproduce so far. Crosscompiling various packages from an x86_64 masterdir to i686 didn't show anything unusual. firefox build ongoing though, so it might be a firefox issue alone
```
./xbps-src -m masterdir.pr14401 binary-bootstrap
./xbps-src -m masterdir.pr14401 -a i686 pkg foo
```
Can you please provide a command to show off the issue? Please use a fresh masterdir (`-m`) and a fresh hostdir (`-H`)

**Comment by zdtcd** [comment]
Weird, I can't reproduce the issue anymore.

**Comment by Johnnynator** [comment]
`xbps-src` regenerates this symlink if it is missing, we have a inconsistency in our cross compiler packages, some have it removed some not, So this issue only crops up outside of `xbps-src`, inside it is probably a result of #14476

**Pull request closed without merging**
