### PR TITLE
anydesk: update to 6.0.0

### PR DESCRIPTION
**Pull request by MGlolenstine**
Updated two outdated packages, updated hashes and fixed problems with `discord-ptb` not working.

Feel free to comment on this first PR of mine.

### CODE REVIEW

**Comment by ericonr** [comment]
Please follow the commit format: https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#committing-your-changes

You should have two commits on this PR, one for each package. You might need to rebase your changes for this.

**Comment by MGlolenstine** [comment]
@ericonr You're right! On it!

**Comment by MGlolenstine** [comment]
Here we go. Rebased and split into two commits. Does this fit the commit format?

**Comment by ericonr** [comment]
If these packages are unrelated, it would be best to split one of the commits into another PR. Please do that - leave this one open and open another one. Then you can reword the discord commit to "update to" instead of "updated to".

**Comment by MGlolenstine** [comment]
Updated once again. I hope it's fine now. I'm creating another PR for `discord-ptb` right now.

**Comment by ericonr** [comment]
Thanks!

**Comment by MGlolenstine** [comment]
Thank you for correcting my mistakes and making me a better contributor!

**Comment by MGlolenstine** [comment]
Closing because this PR is a mess and there's been a newer version released.

**Pull request closed without merging**
