### PR TITLE
texlab: update to 5.2.0

### PR DESCRIPTION
**Pull request by subnut**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

@cinerea0

### CODE REVIEW

**Comment by subnut** [comment]
@cinerea0 Sorry if this seemed that way. I just came home on a short medical leave, and thought of trying out LaTeX. So, I installed texlive and texlab. I was just checking out the texlab repo on github, and I saw that there was a new release a few hours ago, and thought of updating it on void-packages. That's it. I promise.

**Comment by subnut** [comment]
And I didn't even notice that you updated any of my packages. Thanks for that! I have been **very** busy for the last few months (you know, college and all...)

In fact, it's only due to my medical leave that I've been creating the update PRs. Otherwise I usually am using Windows all the time I'm in college. Not using void ⇒ not knowing that packages are out-of-date ⇒ not creating PRs to update them

**Comment by subnut** [comment]
Ah, okay. Just now I saw that you've updated the iwgtk package, and I'd mentioned you in #41953.

I am terribly sorry that you felt this way. I honestly didn't even think of that. I am sorry, again. :disappointed:

**Comment by subnut** [comment]
But as I said before, it's pure coincidence that the texlab package is owned by you.

 I was just starting to learn LaTeX and was looking for an LSP for it, and noticed that the texlab LSP had an update just _2 hours ago_, and updated the void-packages template for it immediately. I tried it out, and went to sleep without pushing it (I am unwell, hence the medical leave). As soon as I remembered that I forgot to create a PR, i pushed the template to github and created it, and tagged you because you are the maintainer. Then, I went about the rest of my day without giving it a second thought.

There. I just described you exactly what happened. Please don't think I had any ill intentions whatsoever. I am sorry, again.

**Comment by subnut** [comment]
You know what? Let me just close this PR. I still feel terrible about the way this has gone down. I am very sorry that @cinerea0 felt that this PR was something other than just a PR. So, let me just close it.

**Comment by subnut** [comment]
@cinerea0 Sorry, again.

**Comment by cinerea0** [comment]
Hold on there. First off, I want to apologize for assuming the worst of you. There are many completely innocuous reasons someone could have to open a PR, and I assumed malice where there obviously wasn't any. I reacted with hostility because I connected dots that weren't there, and I'm sorry for doing that.

Having said that, it's up to you whether you want to re-open or re-create this PR. I would have no issue with you doing so.

**Pull request closed without merging**
