### PR TITLE
ecl: update to 21.2.1.

### PR DESCRIPTION
**Pull request by tornaria**
I compiled and doctested sage-9.4 with this PR + other updates and new packages. All working fine.

### CODE REVIEW

**Comment by dkwo** [comment]
You read my mind :)
Should we keep fix-math_fenv_h patch?

**Comment by tornaria** [comment]
> Should we keep fix-math_fenv_h patch?
I removed both patches and it seems to work ok.

There is an issue with cross compilation. I don't think it is ok to use the host system ecl to bootstrap because it creates C files for the host system. Rather one needs to host-compile the ecl with target-system settings, then use ecl that to build the target ecl.

Right now the problem shows in that target-system settings disable `long long` but host-system has `long long` enabled, which results in
```
Error code 1 when executing
(EXT:RUN-PROGRAM "armv7l-linux-gnueabihf-gcc" ("-o" "bin/ecl" "-L/builddir/ecl-21.2.1/build/" "/builddir/ecl-21.2.1/build/eclinit3Pk084.o" "-L./" "-Wl,--rpath,/usr/lib32/" "-Wl,-z,relro" "-Wl,-z,now" "-Wl,--as-needed" "-L/usr/armv7l-linux-gnueabihf/usr/lib" "libecl.so" "-lgc" "-lgc" "-lgc" "-lpthread" "-ldl" ...)):
/usr/lib/gcc/armv7l-linux-gnueabihf/10.2.1/../../../../armv7l-linux-gnueabihf/bin/ld: libecl.so: undefined reference to `ecl_to_ulong_long'
```
This can be fixed by enabling `long long` in target-system (why is it disabled? don't `armv6l` and `armv7l` have a 64 bit `long long`?). Cf https://gitlab.com/embeddable-common-lisp/ecl/-/issues/579 and https://gitlab.com/embeddable-common-lisp/ecl/-/commit/9137c681a8533a11196269d90a99b94a4fbd229c

**Comment by dkwo** [comment]
Regarding one of pullmoll's deleted patches, I've inquired upstream and they suggested to test a reduced version of it: would you mind including in this PR?

https://gitlab.com/embeddable-common-lisp/ecl/-/issues/653#note_675299471

**Comment by tornaria** [comment]
> Regarding one of pullmoll's deleted patches, I've inquired upstream and they suggested to test a reduced version of it: would you mind including in this PR?
> 
> https://gitlab.com/embeddable-common-lisp/ecl/-/issues/653#note_675299471

Do you know what architectures need this? Including the patch seems to be noop for all the archs I can test on, so I wouldn't be able to answer if it works.

**Comment by tornaria** [comment]
> > Regarding one of pullmoll's deleted patches, I've inquired upstream and they suggested to test a reduced version of it: would you mind including in this PR?
> > https://gitlab.com/embeddable-common-lisp/ecl/-/issues/653#note_675299471
> 
> Do you know what architectures need this? Including the patch seems to be noop for all the archs I can test on, so I wouldn't be able to answer if it works.

I tried cross compilation for `mips-musl` and indeed it fails without the patch. With the patch it builds and packages ok (although I haven't tested the binary).

**Comment by tornaria** [comment]
New push:
 - reincluded `fix-math_env_h.patch` in the new version suggested by upstream (https://gitlab.com/embeddable-common-lisp/ecl/-/issues/653#note_675299471)
 - replace the per-arch cross_config files by the 4 different ones `{32,64}{be,le}.conf`. It could also be a template that is substituted in `pre_configure()`, but this seems the easiest way to do it.
 - lint fails just because it doesn't like long lines in the git log message. I will amend.

**Comment by tornaria** [comment]
I batch-tested cross-compiling for all of these
```
aarch64
aarch64-musl
armv5tel
armv5tel-musl
armv6l
armv6l-musl
armv7l
armv7l-musl
i686
i686-musl
mips-musl
mipsel-musl
mipselhf-musl
mipshf-musl
ppc
ppc-musl
ppc64
ppc64-musl
ppc64le
ppc64le-musl
x86_64
x86_64-musl
```

**Comment by tornaria** [comment]
Ping @knusbaum: any comments?

**Comment by knusbaum** [comment]
LGTM, nice work.

**Comment by ericonr** [comment]
This is an awesome PR, thanks!!

**Pull request merged**
