### PR TITLE
New package: flat-remix-gtk

### PR DESCRIPTION
**Pull request by harrisonthorne**
Add the Material-Design-inspired Flat Remix GTK theme

### CODE REVIEW

**Comment by harrisonthorne** [comment]
See related: #24188

**Comment by cinerea0** [comment]
You might want to provide a more detailed explanation of what value the package provides, since themes generally get rejected by the maintainers because of the quality requirements: https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements

**Comment by harrisonthorne** [comment]
Oh dang. Still new here :)

More than anything the package just provides the convenience of making the install easy, but it's nothing more than copying files (though one might argue that this package does have [a `build` rule in its makefile](https://github.com/daniruiz/flat-remix-gtk/blob/master/Makefile), it's just not necessary for the theme to work).

I would like to see the flat-remix suite be included in the Void repo (they're some dang fine themes), but I won't fight for it. I'll let the maintainers make the call at this point.

**Comment by ahesford** [comment]
Because these themes can just be placed in `~/.themes`, they do not meet the packaging criteria.

**Pull request closed without merging**
