### PR TITLE
Seafile client stack: switch to python3

### PR DESCRIPTION
**Pull request by yopito**
switch all underlying dependencies of seafile-client-qt to python3, that leads to update `libsearpc` package to last version 3.0.8.  
`seafile-client-qt` package does not require an update.  
Personal cross-build is fine.

PR reborn from old repo PR https://github.com/voidlinux/void-packages/pull/15011

### CODE REVIEW

**Comment by cr6git** [comment]
@yopito what the fuck?

**Comment by yopito** [comment]
Sorry for late reply, I'm on travel. What's the problem ? I don't know why you revert the changes after merged this PR. Build log on build.voidlinux.eu were fine, no ?

**Comment by yopito** [comment]
@cr6git, @asergi : could you provide additional infos on the need of reverting this PR ? Thanks.

**Comment by cr6git** [comment]
it was the decision of @asergi , not mine. :bear: I was just surprised to see this commit reverted...

**Pull request merged**
