### PR TITLE
Fix some gnu-makefile build style users

### PR DESCRIPTION
**Pull request by ericonr**
Mainly depends on the change from #27003 for CXXFLAGS inclusion.

### CODE REVIEW

**Comment by ericonr** [comment]
`crypto++` only fails on glibc :/

**Comment by ericonr** [comment]
@mvf @thypon ok with changes?

**Comment by mvf** [comment]
Looks good, thanks @ericonr!

Something else to consider with `gnu-makefile`: Maybe `do_build` should also pass `PREFIX=/usr`. Some Makefiles compile in `PREFIX`-based paths, so not having it during `do_build` can cause subtly broken binaries. This has bitten me in the past with `spectrwm` (ae50942849724f9017a389ebec8a37fb3eb9b1ff) and it seems there are `gnu-makefile` templates that set `make_build_args` only for `PREFIX`.

**Comment by ericonr** [comment]
@mvf I've thought the same thing, but haven't tried to actually fix it. We could probably remove `make_build_args` from many templates and avoid weird surprises. I don't know of any objections against it, but I also don't know if it isn't passed because no one had the idea / implemented It or for some specific reason.

**Pull request merged**
