### PR TITLE
wicd: clean up INSTALL.msg

### PR DESCRIPTION
**Pull request by camoz**

### CODE REVIEW

**Comment by paper42** [comment]
* the package revision needs to be increased
* I am not sure how this improves the documentation significantly
* why did you remove mentioning the network group? Is it not relevant anymore?

**Comment by camoz** [comment]
> the package revision needs to be increased

Oh I didn't know that (I'm quite new to void).
Maybe the changes can be bundled with the next update to wicd?

> I am not sure how this improves the documentation significantly

Well the first sentence is semantically wrong ("does not require to have" vs. "requires not to have") so I thought better correct that. I'm not using wicd myself, just saw it on the go.

> why did you remove mentioning the network group? Is it not relevant anymore?

Per void docs the `network` group isn't used anymore: https://docs.voidlinux.org/config/users-and-groups.html#default-groups

**Comment by Duncaen** [comment]
I would vote to just remove `INSTALL.msg`, we don't have them for the other packages that have the same requirement like `NetworkManager` and its sufficiently documented in the handbook.


> Per void docs the network group isn't used anymore: https://docs.voidlinux.org/config/users-and-groups.html#default-groups

The documentation here is wrong, there are packages that use this group, like wicd and networkmanager.

**Comment by camoz** [comment]
Personally, I don't care if this gets merged or `INSTALL.msg` is removed. Removing seems simpler and sounds reasonable to me.

**Comment by ahesford** [comment]
https://github.com/void-linux/void-packages/issues/36116

**Pull request closed without merging**
