### PR TITLE
ilmbase/openexr: update to 2.5.3.

### PR DESCRIPTION
**Pull request by skmpz**
- locally compiled all revbumped packages for all available archs
- luxmark/luxrays packages removed (replaced with meta)

### CODE REVIEW

**Comment by ericonr** [comment]
You can squash the openexr commits into a single one at the top.

**Comment by skmpz** [comment]
> You can squash the openexr commits into a single one at the top.

done, thanks for the feedback.

**Comment by ericonr** [comment]
Hi! Could you try and rebase this PR? I'd like to get it merged :)

**Comment by skmpz** [comment]
let me check when i got some time. I can maybe even try to work on getting the latest version.

**Pull request closed without merging**
