### PR TITLE
libmypaint: update to 1.5.1

### PR DESCRIPTION
**Pull request by teh-jazzman**
Taking over for previous maintainer with permission.

Revision bumps for gimp and opentoonz as they depend on it.

### CODE REVIEW

**Comment by xtraeme** [comment]
There should be 3 commits: one for the update and two more for the revbumps. This way we can know why a pkg was rebuilt.

**Comment by teh-jazzman** [comment]
Reorganized changes into 3 commits.

**Comment by teh-jazzman** [comment]
Is there something else I need to do?

**Comment by xtraeme** [comment]
fix xlint errors and build issues

**Comment by teh-jazzman** [comment]
The xlint error is a false positive. It sees backticks and assumes they imply a command substitution, but they are just part of a sed replacement pattern.

The build issues occur because the building takes longer than the allowed maximum time and so the processes are killed. I don't see what I can do to fix that.

**Pull request merged**
