### PR TITLE
io.elementary.calculator: update to 0.1.5.

### PR DESCRIPTION
**Pull request by CameronNemo**

### CODE REVIEW

**Comment by maxice8** [comment]
i'd rather keep the naming of pantheon-thing if possible

**Comment by CameronNemo** [comment]
Are the dots the problem? I could use io-elementary-thing. Upstream is really keen on switching the branding away from pantheon for everything except the shell components.

**Comment by maxice8** [comment]
On Sun, Sep 02, 2018 at 12:48:10PM -0700, Cameron Nemo wrote:
> Are the dots the problem? I could use io-elementary-thing. Upstream is really keen on switching the branding away from pantheon for everything except the shell components.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/2328#issuecomment-417955243

I just wanted to keep consistency with pantheon-stuff but if upstream plans on changing everything to io.elementary.thing then i think we should do as well.

**Comment by maxice8** [comment]
@void-linux/pkg-committers ^ opinion on the above comment please

**Comment by the-maldridge** [comment]
Is there some documentation of this switch?  And I'm not sure how well dots are supported, dashes might be preferable here.

**Comment by maxice8** [comment]
On Sun, Sep 02, 2018 at 01:47:54PM -0700, Michael Aldridge wrote:
> Is there some documentation of this switch?  And I'm not sure how well dots are supported, dashes might be preferable here.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/2328#issuecomment-417958749

There is python-ruamel.yaml and it seems to work fine but that is all i know about usage of dots

**Comment by maxice8** [comment]
> And I'm not sure how well dots are supported, dashes might be preferable here.

should be fully supported, after all we have linux4.XX, python-backports.XX

**Comment by CameronNemo** [comment]
Here is elementary's tracking project for the RDNN notation: https://github.com/orgs/elementary/projects/4. They have yet to change the debian package name for the calculator, but they do intend to: https://github.com/elementary/calculator/pull/75.

**Comment by the-maldridge** [comment]
Weird choice but sure, why not.  I'm fine with it to change, assuming of course all involved understand the significant pain that comes with renaming and moving packages.

**Comment by CameronNemo** [comment]
I don't mind renaming the two remaining pantheon-* packages, and I don't expect upstream to change their naming pattern anytime soon. I really don't want to hit any snags with tooling, though. As long as we are confident that dots in the package names can be supported, I am happy to move forward.

**Comment by cr6git** [comment]
Note: the binary was already named `/usr/bin/io.elementary.calculator`

LGTM. :+1:

**Pull request merged**
