### PR TITLE
firebird3: update to 3.0.12.33717

### PR DESCRIPTION
**Pull request by onlylunix**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture  (x86_64-LIBC, i686-LIBC, x86_64-musl)

### CODE REVIEW

**Comment by abenson** [comment]
Please don't open and close PRs as that makes it more difficult for us to track issues and needed changes.

In the future, please make the changes by [amending and squashing the existing](https://www.atlassian.com/git/tutorials/rewriting-history) commits and then force pushing to the same branch.

**Comment by sgn** [comment]
The update perm shouldn't be put into `/usr/bin`

**Comment by onlylunix** [comment]
> The update perm shouldn't be put into `/usr/bin`

fixed

**Comment by onlylunix** [comment]
open new PR [ #46672](https://github.com/void-linux/void-packages/pull/46672)

**Pull request closed without merging**
