### PR TITLE
[RFC] pipewire: update, add virtual session manager to pull in wireplumber without build cycle

### PR DESCRIPTION
**Pull request by ahesford**
> **Note:** This is not really intended as an update to 0.3.64; instead, if there is enough support for this proposal, I think https://github.com/void-linux/void-packages/pull/41846 should be merged with an `INSTALL.msg` warning people that pipewire-media-session will be dropped in the next release and that they should make sure they have a working wireplumber configuration before then.

pipewire will not work without a session manager; the previously included pipewire-media-session has long been deprecated and is now abandoned [1]. Making pipewire depend on wireplumber would create a cycle, so the cycle is broken with a rename and a new metapackage:

1. Rename pipewire -> pipewire-utils to clear the pipewire name
2. New pipewire meta depends on pipewire-utils and wireplumber

The rename is a violation of policy but allows existing pipewire users to see the new meta as an update that will pull in an updated real pipewire alongside the now-required wireplumber.

Continuing the work of https://github.com/void-linux/void-packages/pull/38521.

[1] https://gitlab.freedesktop.org/pipewire/media-session/-/releases/0.4.2

### CODE REVIEW

**Comment by ahesford** [comment]
As per IRC discussion, we can avoid the rename and still break the cycle once https://github.com/void-linux/void-packages/pull/39868 is merged by declaring a `pipewire-session-manager` virtual that defaults to some dummy package like `pipewire-session-manager-bootstrap` with `repository=bootstrap`, than make `wireplumber` provide `pipewire-session-manager`.

**Comment by cinerea0** [comment]
I would prefer to avoid the renaming scheme if possible. Would the implementation of the alternate proposal make intuitive sense if you generally understand xbps templates?

**Comment by ahesford** [comment]
This branch has been restructured to use a virtual package to break the pipewire-wireplumber build cycle that would otherwise appear. It should *NOT* be merged until #39868 is merged and we can add `repository=boostrap` to the `pipewire-session-manager-boostrap` template.

**Comment by ahesford** [comment]
I am not inclined to pull a patch that modifies default paths which seem only to appear in comments. Upstream should fix these paths if necessary because they made the decision to abandon pipewire-media-session and render these paths obsolete.

**Comment by ahesford** [comment]
Not stale yet!

**Comment by ahesford** [comment]
Implemented in 43889c8f6bf5a588c16dfc95f8d3bbea85ab446a

**Pull request closed without merging**
