### PR TITLE
calcurse: update to 4.8.0

### PR DESCRIPTION
**Pull request by cinerea0**
#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by cinerea0** [comment]
The failing test: https://github.com/lfos/calcurse/blob/master/test/ical-007.sh. No idea what specifically about musl would cause this to fail.

**Comment by abenson** [comment]
Seems to think CET == UTC.

```
[andrewb@/home/andrewb/Projects/void-packages/masterdirmusl test]$ ./ical-007.sh actual
Import process report: 0018 lines read
3 apps / 0 events / 0 todos / 0 skipped
02/23/15:
 - 06:00 -> 07:00
	CET
 - 06:00 -> 07:00
	UTC
 - 11:00 -> 12:00
	Local time
-- 
Import: TZID=CET
[andrewb@/home/andrewb/Projects/void-packages/masterdirmusl test]$ ./ical-007.sh expected
Import process report: 0018 lines read
3 apps / 0 events / 0 todos / 0 skipped
02/23/15:
 - 05:00 -> 06:00
	CET
 - 06:00 -> 07:00
	UTC
 - 11:00 -> 12:00
	Local time
-- 
Import: TZID=CET
```

**Comment by dkwo** [comment]
Strange, this test seems to pass on Alpine. Could it be our tzdata package?

**Comment by dkwo** [comment]
it's now passing (at least locally for me) `PASS: ical-007.sh`, they probably fixed whatever was broken in Void :)

Also worth noting:
```
checking pkg-config is at least version 0.9.0... ./configure: line 7614: pkg-config: command not found
configure: WARNING: AsciiDoc not found - cannot rebuild documentation!
configure: WARNING: Using pre-built documentation.
configure: WARNING: a2x not found - cannot rebuild man pages!
configure: WARNING: Using pre-built man pages.
```
we could add pkg-config and either add asciidoc or set the option without-asciidoc.
also, i think py3-httplib2 is not needed.

**Comment by dkwo** [comment]
in other words, how about this?
```
diff --git a/srcpkgs/calcurse/template b/srcpkgs/calcurse/template
index aefd36d204..03f84fa135 100644
--- a/srcpkgs/calcurse/template
+++ b/srcpkgs/calcurse/template
@@ -1,16 +1,18 @@
 # Template file for 'calcurse'
 pkgname=calcurse
-version=4.7.1
+version=4.8.0
 revision=1
 build_style=gnu-configure
+configure_args="--without-asciidoc"
+hostmakedepends="pkg-config"
 makedepends="ncurses-devel"
-depends="python3-httplib2"
 short_desc="Text-based calendar and scheduling application"
 maintainer="silvernode <mollusk@homebutter.com>"
 license="BSD-2-Clause"
 homepage="https://calcurse.org"
-distfiles="https://calcurse.org/files/${pkgname}-${version}.tar.gz"
-checksum=0a7c55d07674569d166c0b0e7587b2972d3da8160cdb7d60b1dbd2895803afb0
+changelog="https://calcurse.org/files/changes.html"
+distfiles="https://calcurse.org/files/calcurse-${version}.tar.gz"
+checksum=48a736666cc4b6b53012d73b3aa70152c18b41e6c7b4807fab0f168d645ae32c
 
 post_install() {
        vlicense COPYING
```

**Comment by cinerea0** [comment]
@dwko that test still seems to fail in CI, even more curious. Also, I don't mind re-building the docs, but if it's preferred to switch to the configure arg solution you posted I can switch to that.

**Comment by dkwo** [comment]
Thanks! Either way is fine with me. This is ready to merge.

**Pull request closed without merging**
