### PR TITLE
libmicrohttpd: update to 0.9.73

### PR DESCRIPTION
**Pull request by digitalagedragon**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

This has been in the pipeline for 6 months or so. `libmicrohttpd` 0.9.71 broke some existing C++ code, and by now most of the packages that depend on it have integrated to the new API. I've made sure every package that depends on `libmicrohttpd` compiles against 0.9.73.

### CODE REVIEW

**Comment by digitalagedragon** [comment]
alright `xlint` is going in my pre-commit hooks

**Comment by ericonr** [comment]
Please increase the version in `common/shlibs`, since the newly compiled stuff will depend on the new version and can't use the old one.

**Comment by ericonr** [comment]
I will fold #31218 into this, because they haven't released the version with the build fixes yet :/

**Comment by ericonr** [comment]
Pushed with a6f4c6166b88c0777b941e69f0378fdead65b648, thanks a lot!

**Pull request closed without merging**
