### PR TITLE
python3-urllib3: update to 1.26.15.

### PR DESCRIPTION
**Pull request by Bnyro**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by Bnyro** [comment]
The checks just freeze my machine, weird.

**Comment by mhmdanas** [comment]
For the record, there's already https://github.com/void-linux/void-packages/pull/43699, though that PR bumps the version to 2.x, which doesn't work with some packages yet.

**Comment by Bnyro** [comment]
Oh right, I see.
The failing tests seem to be the same there so the issue introducing them happened somewhere between .12 and .15 apparently.
It probably doesn't make much sense to keep this PR open, or what do you think?

**Comment by Bnyro** [comment]
Closing this as I think it makes more sense to update to the 2.x series directly instead.

**Comment by mhmdanas** [comment]
I'd reopen this, who knows when it'll be possible to bump to 2.x?

**Pull request closed without merging**
