### PR TITLE
gap: update to 4.12.2

### PR DESCRIPTION
**Pull request by fingolfin**
#### Testing the changes
- I tested the changes in this PR: **NO**

CC @tornaria

### CODE REVIEW

**Comment by tornaria** [comment]
Looks an easy upgrade, but it has to be tested with sagemath, i.e. run `sage -tp --all --long` with this package installed. Be warned that there will be a few failures due to deprecation warnings in numpy 1.24 which can be ignored (I already have a patch, I'm planning to revbump sagemath 9.7 with upgraded fplll, gap, giac, igraph, pari and brial rebuilt for boost).

**Comment by tornaria** [comment]
@fingolfin: a minor nitpick, something changed in `make install` for headers. In 4.12.1 it would install a symlink `src -> .` in `/usr/include/gap/`. But in 4.12.2 it actually creates a directory and duplicates all the files. Is there a reason for this change?

The update seems to work ok with our sagemath 9.7.

**Review by tornaria — APPROVED** [review]

**Comment by fingolfin** [comment]
Reason for the change: the Debian maintainer complained about the symlink, implying this would cause all kinds of potential problems... In the end, I really don't care much either way :-). Longterm I hope we can get rid of this hack anyway, perhaps already in GAP 4.13.

**Comment by tornaria** [comment]
> Reason for the change: the Debian maintainer complained about the symlink, implying this would cause all kinds of potential problems... In the end, I really don't care much either way :-). Longterm I hope we can get rid of this hack anyway, perhaps already in GAP 4.13.

Ok, so we might as well `rm -rf` the whole redundant thing (and maybe redo the symlink) in `post_install()`. Or maybe just ignore, gap-4.12.2 is saving 120MB because datafiles are compressed so 1MB of redundant header files is nothing...

**Pull request merged**
