### PR TITLE
[no merge] darktable: update to 3.0.0.

### PR DESCRIPTION
**Pull request by lemmi**
Since this is a rather huge upgrade to darktable and version `3.0.1` is probably not too far out, I'd like to wait until then. So this is PR is more or less a placeholder and the first test if this builds everywhere.

### CODE REVIEW

**Comment by ndowens** [comment]
Here is a little hack of a patch that may help:
https://termbin.com/85h4

**Comment by xtraeme** [comment]
Looks like darktable-3.0.0 gets rid of 32bit archs

**Comment by ndowens** [comment]
Found out how to build this, so far it is build on aarch64, one is to disable openmp, which during compile it gives something like expect a LOT of functionality to be missing. Second is to remove, "include(ConfigureChecks.cmake) from CMakeLists.txt this will disable platform check

**Comment by lemmi** [comment]
I already mentioned this in IRC: I'm not sure I want to keep `32bit` alive for `darktable`. There is a reason upstream drops the support. To be able to do any sort of meaningful work with `darktable` you need ram (and lots of it) and computing power. And you won't get that anymore with `32bit` plattforms.

If there is someone out there depending on `32bit` `darktable`, I'm willing to keep this alive for a bit. Otherwise I'm going with upstream and remove support now as well.

**Comment by ndowens** [comment]
Probably just best to go with upstream in reality. Other option, in which I am sure won't be "ok" is to have the old version around for i686 and the new ones excluding i686. Just a thought, sure it won't be a think :)

**Comment by lemmi** [comment]
Thought about keeping the old version around for a while anyway since `3.0` has an almost completely new processing pipeline. That way you'd also have a safety net if you wanted to grab something from you archive and it isn't supported anymore for some reason.

**Comment by TeddyDD** [comment]
Any progress on this? I compiled Darktable from this PR and it seems to be working fine.

**Comment by lemmi** [comment]
There was supposed to be a 3.1 relatively soon after the 3.0 release, but given how stable it is for me and apparently for other people as well, I'm thinking about merging this as is (and dropping i686 support). I'll decide this week.

**Pull request closed without merging**
