### PR TITLE
gnome-terminal: update to 3.36.1.1

### PR DESCRIPTION
**Pull request by mnabid**

### CODE REVIEW

**Comment by pullmoll** [comment]
The cross build needs fixes.

**Comment by mnabid** [comment]
gnome-terminal 3.36.* needs vte3>=0.60.1. I submitted a PR #20437 .

**Comment by mnabid** [comment]
@xtraeme cross build fixed.

**Comment by xtraeme** [comment]
hold on, I'm pushing new gnome updates

**Comment by xtraeme** [comment]
While you are at it, please change `build_style` to `meson`

**Comment by mnabid** [comment]
`gnome-terminal` doesn't support meson build system, but there's a [discussion](https://gitlab.gnome.org/GNOME/gnome-terminal/issues/227) about it.

**Comment by xtraeme** [comment]
oh ok

**Pull request merged**
