### PR TITLE
New package: scream-3.5

### PR DESCRIPTION
**Pull request by anjandev**
https://github.com/duncanthrax/scream/pull/78#issuecomment-609028661

Old packages were removed upstream. We now have only one file to package and it's much simpler.

### CODE REVIEW

**Comment by Oreo639** [comment]
It would probably be a good idea to provide transitional packages for those who have the other scream-* packages installed.

**Comment by anjandev** [comment]
@Oreo639 any example of this?

**Comment by Oreo639** [comment]
https://github.com/void-linux/void-packages/pull/19241
https://github.com/void-linux/void-packages/blob/c114983ac84ae221ac8bbf781f115e5e4721c7aa/srcpkgs/okteta5/template
Note, that instead of adding `(removed package)` to the end of the description like I did, you would add `(transitional dummy package)`. That was my bad.

**Comment by anjandev** [comment]
@Oreo639 thank you. I have fixed it according to this. I got to learn a little bit of sed too! =)

**Pull request closed without merging**
