### PR TITLE
coin3: update to 4.0.0

### PR DESCRIPTION
**Pull request by sgn**
@yopito

### CODE REVIEW

**Comment by yopito** [comment]
Duplicate of #25607 ...

**Comment by sgn** [comment]
@yopito  Thanks.

**Comment by yopito** [comment]
Nice PR, Have to compare both to take the best of each. I will  check tomorrow

**Comment by sgn** [comment]
@yopito please pick my cross fix into your branch

**Comment by yopito** [comment]
Ok, no problem

**Pull request closed without merging**
