### PR TITLE
[RFC] Add _FORTIFY_SOURCE impl for musl.

### PR DESCRIPTION
**Pull request by ericonr**
Using the `fortify-headers` impl from https://git.2f30.org/fortify-headers/file/README.html , which was recommended in https://wiki.musl-libc.org/open-issues.html#Substitute-for-%3Ccode%3E_FORTIFY_SOURCE%3C/code%3E .

Would definitely require extensive testing, I mostly want to know whether going through this testing is worth it.

### CODE REVIEW

**Comment by q66** [comment]
no, let's not add useless bounds checks and branches all around the stdlib in all our release software please

**Comment by q66** [comment]
looking further at how it works, if we wanted to include this, definitely not in this manner - instead we'd do it like alpine and have the compiler implicitly inject it (with `-isystem` rather than `-I`) as including it in normal flags via `-I` is just asking for trouble (for one we want to treat them like system headers, to avoid potential warnings and so on...)

**Comment by ericonr** [comment]
> with -isystem rather than -I

So like I just changed it?

---

I considered making this PR mostly because dalias said he likes the design, so I didn't expect any huge issues with the impl. Might not be the most optimal, though.

Are your issues more with the idea of having `_FORTIFY_SOURCE` functional on musl, but requiring more bounds checks and binary size than it used to, or with the fact that this lib isn't as well implemented as it could be?

**Comment by q66** [comment]
`XBPS_CROSS_BASE` will not work since the libc is not installed for crossbuilds (it's shipped by crosstoolchains)

I'm not fundamentally opposed to using fortify, the library could use cleaning up (it'd simplify it too, e.g. use `__builtin___memcpy_chk` and so on) and the way you implemented it in the PR is questionable

if we're to add this, the best opportunity is when doing the gcc10 transition

**Comment by sgn** [comment]
Even if we want this merged in, as of it's now, we can't bootstrap from foreign distro.
At least add `bootstrap=yes` to `fortify-headers`.
**And** some code to append those header to bootstrap step.

**Comment by ericonr** [comment]
> XBPS_CROSS_BASE will not work since the libc is not installed for crossbuilds (it's shipped by crosstoolchains)

I know, I have to add them there too. I just didn't want to go through the trouble before I had an ok.

> and the way you implemented it in the PR is questionable

Which part specifically?

> the library could use cleaning up

If you could give me some tips, I would gladly make some changes. Would just have to find out whether upstream is active or if we'd need to fork it under void-linux (?).

> And some code to append those header to bootstrap step.

Any tips on this?

**Comment by q66** [comment]
as i said, this should be patched into gcc itself (i.e. like alpine does it)

i'll close this and you can bring it up when the gcc10 update is being done

**Pull request closed without merging**
