### PR TITLE
[RFC] dhcpcd: fix high cpu usage

### PR DESCRIPTION
**Pull request by pbui**
As reported on IRC, some users are experiencing high CPU usage when
using eduroam and/or suspending/resuming their machines.  This update
includes a few upstream changes that should possibly address this
situation:

1. Runs the STOPPED hook on interfaces when a timeout occurs.

2. Includes an upstreamed musl patch.

3. Validates RTM_DELADDR/RTM_NEWADDR messages for both IPv6 and IPv4.

I believe the last change most directly addresses the high CPU usage
situation.

### CODE REVIEW

**Comment by pbui** [comment]
Hmm... unfortunately, I just experienced the high CPU usage situation with this package... so the patches are no sufficient for solving this problem.  It may be worth reverting back to 8.0.6 until this is resolved.

**Comment by jmai444** [comment]
Happens here with my ThinkPad T470.  Eventually it fails to renew my IP address and I then have no network.  dhcpcd fails to restart or stop if requested through sv command.  I have to reboot.  No interesting messages appear in socklog.

**Comment by flexibeast** [comment]
As another data point, i'm experiencing the same issues as @jmai444 (albeit on an IdeaPad 310).

**Comment by pbui** [comment]
Just revert to 8.0.6 for now... https://github.com/void-linux/void-packages/pull/15885

**Pull request closed without merging**
