### PR TITLE
gitea: update to 1.16.1

### PR DESCRIPTION
**Pull request by zen0bit**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64 libc

### CODE REVIEW

**Comment by paper42** [comment]
Please rebase on top of master to make CI run

**Comment by catdevnull** [comment]
@zen0bit Something like this:

```sh
# Fetch latest changes from upstream
git fetch upstream
# Rebase on top of master
git rebase upstream/master
```

You might need to add the upstream remote:
```sh
git remote add upstream https://github.com/void-linux/void-packages
```

**Comment by catdevnull** [comment]
It seems you got merge commits still. Try this:

```
# Fetch latest changes from upstream
git fetch upstream
# Reset branch to upstream
git reset --hard upstream/master
# Add the upgrade commit on top
git cherry-pick 1512578282a22c0c82d32964c117e7f7a82a50e0
# Force push
git push --force
```

Also, you still haven't replaced the hardcoded version in distfiles. After the previous commands, you could do this:
```
# Do the changes with your favourite editor
# Add the changes to the last commit ("amending")
git commit srcpkgs/gitea/template --amend
# Force push
git push --force
```

**Comment by catdevnull** [comment]
This looks great, @paper42?

**Pull request closed without merging**
