### PR TITLE
terraform: update to 1.0.0

### PR DESCRIPTION
**Pull request by ScOut3R**

### CODE REVIEW

**Comment by ericonr** [comment]
1.0.0 has been released :D 

https://github.com/hashicorp/terraform/releases

@the-maldridge and @thypon

**Comment by ScOut3R** [comment]
Such timing @ericonr :D

I'll try to update my PR tomorrow.

**Comment by ScOut3R** [comment]
> 1.0.0 has been released :D
> 
> https://github.com/hashicorp/terraform/releases
> 
> @the-maldridge and @thypon

@ericonr I am sorry for the delay, I have updated the PR just now.

**Comment by ericonr** [comment]
Moved to 1.0.2, merging.

**Pull request merged**
