### PR TITLE
New package: Webcord-4.8.0

### PR DESCRIPTION
**Pull request by end3r-man**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (`x86_64-glibc`)

### CODE REVIEW

**Comment by end3r-man** [comment]
any update on my PR??

**Comment by meator** [comment]
Shell globs must be properly quoted.

Every use of `${wrksrc}` in your template is unnecessary.

Taking the program directly from a `.deb` file should be avoided. Such packages do not meet the Compiled package requirement. Properly building the thing should be preferred.

**Comment by end3r-man** [comment]
> Shell globs must be properly quoted.
> 
> Every use of `${wrksrc}` in your template is unnecessary.
> 
> Taking the program directly from a `.deb` file should be avoided. Such packages do not meet the Compiled package requirement. Properly building the thing should be preferred.

then getting binary from .deb should be avoided. then only way is getting binary is directly or build from source right??

**Comment by Bnyro** [comment]
> then getting binary from .deb should be avoided. then only way is getting binary is directly or build from source right??
>
The only way to get this package merged by any chance is to build it from source, yes. Binaries won't be accepted, given the fact that it's an electron app chances it'll be accepted are low anyways.

**Pull request closed without merging**
