### PR TITLE
python3-click-(repl;log;threading): update/fix

### PR DESCRIPTION
**Pull request by dotnetfox**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Addendum

These packages are part of `click-contrib`, not `python3-click` itself; which is why I have submitted these changes here as a separate pull request.

### CODE REVIEW

**Comment by ahesford** [comment]
Are you Oliver Kiddle?

**Comment by dotnetfox** [comment]
> Are you Oliver Kiddle?

I am not, although I already suspect what you are trying to foreshadow.

**Comment by ahesford** [comment]
Given his apparent inactivity for the last several years, you could make the case to claim stewardship of these packages. If you aren't going to put your name on them, don't orphan another's packages.

**Comment by dotnetfox** [comment]
> If you aren't going to put your name on them, don't orphan another's packages.

Thank you for this piece of information.

**Pull request closed without merging**
