### PR TITLE
python3-jsonschema: update to 4.16.0.

### PR DESCRIPTION
**Pull request by jcgruenhage**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by classabbyamp** [comment]
do the tests and benchmarks need to be installed?

**Comment by jcgruenhage** [comment]
I doubt it.. I'll look into figuring out how to tell hatchling not to package those and open a PR upstream.

**Comment by jcgruenhage** [comment]
So yeah that was actually fairly easy to do, hatch has just a config section for ignoring things. Upstream PR is at https://github.com/python-jsonschema/jsonschema/pull/1003, verified locally that it excludes those directories as expected and still works.

**Comment by jcgruenhage** [comment]
yeah okay, so upstream wants to install them, we'll just keep our patch locally then?

**Pull request merged**
