### PR TITLE
New package: eid-mw-4.4.1

### PR DESCRIPTION
**Pull request by abenson**
Closes https://github.com/void-linux/void-packages/issues/272

### CODE REVIEW

**Comment by maxice8** [comment]
musl having problems with flock

**Comment by abenson** [comment]
Yeah, should be an easy fix.

**Comment by maxice8** [comment]
On Thu, Jun 21, 2018 at 01:54:21PM +0000, Andrew Benson wrote:
> Yeah, should be an easy fix.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/294#issuecomment-399111673

notify me when you push and i'll merge once travis go green

**Comment by abenson** [comment]
Fixed and green.

**Comment by maxice8** [comment]
need a -devel package for the usr/include and usr/lib/*.so stuff

**Comment by maxice8** [comment]
```
eid-mw-devel_package() {
	depends="eid-mw-${version}_${revision}"
	short_desc+=" - development files"
	pkg_install() {
		vmove usr/include
		vmove usr/lib/pkgconfig
		vmove "usr/lib/*.so"
		vmove "usr/lib/*.a"
	}
}
```

**Comment by abenson** [comment]
Ah, I missed that when I scanned the package contents.

--
AndrewB
Knowing is Half the Battle.

**Comment by abenson** [comment]
Added shlibs entries for those as well.

**Comment by maxice8** [comment]
On Thu, Jun 21, 2018 at 07:05:00PM +0000, Andrew Benson wrote:
> Added shlibs entries for those as well. 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/294#issuecomment-399210459

If no packages use them, please don't add they end up being pollution, add entries as packages start using them and remove when nobody uses them.

**Comment by maxice8** [comment]
also forgot to make symlink on srcpkgs.

**Comment by abenson** [comment]
Fixed symlink (I had made it but got distracted and didn't commit it). Removed the shlibs entries ... I guess they can be added if anyone actually uses the SDK.

**Pull request merged**
