### PR TITLE
[WIP] New package: pcsx2-2.0.2

### PR DESCRIPTION
**Pull request by MIvanchev**
Cooperation with @fvalasiad.

### CODE REVIEW

**Comment by ahesford** [comment]
https://github.com/void-linux/void-packages/issues/51246#issuecomment-2228121493

Also, don't open competing pull requests like this.

**Comment by MIvanchev** [comment]
They were not competing actually but gotcha :+1:

**Comment by MIvanchev** [comment]
Actually I just want to say the main reason for this (and I have done it before with the OCaml fixes) is that CI builds are very convenient and they are not available on private forks unless I'm missing something.

**Comment by chrysos349** [comment]
here is the working template - https://github.com/void-linux/void-packages/issues/51246#issuecomment-2228536931

**Pull request closed without merging**
