### PR TITLE
[WIP] qt5: update to 5.13.1.

### PR DESCRIPTION
**Pull request by Johnnynator**
@q66

Testing repo: https://void.johnnynator.dev/qt-5.13.1/

### CODE REVIEW

**Comment by q66** [comment]
Cool. Let's merge this after https://github.com/void-linux/void-packages/pull/14656 and I'll remove the qt5 bump from the llvm9 PR to avoid having to rebuild twice. I'll test this this evening, probably

**Comment by q66** [comment]
Looks like `qt5dxcb-plugin` needs this:

```
--- a/srcpkgs/qt5dxcb-plugin/template
+++ b/srcpkgs/qt5dxcb-plugin/template
@@ -29,6 +29,11 @@ pre_configure() {
 		msg_red "${_qt5_version%_*} does not match ${_qt5_dep_ver}\\n"
 		exit 1
 	fi
+
+	# no headers for 5.13.1 yet; 5.13.0 headers are the same for this
+	# remove on next version upgrade (after upstream has added them)
+	ln -s ${wrksrc}/platformplugin/libqt5xcbqpa-dev/5.13.0 \
+	      ${wrksrc}/platformplugin/libqt5xcbqpa-dev/5.13.1
 }
 
 if [ "$CROSS_BUILD" ]; then
```

The reason for that is that the headers weren't added for 5.13.1 yet. I diffed the 5.13.0 headers against the ones from 5.13.1 Qt source, and the only change was that 5.13.1 added some non-virtual private method in a place which is irrelevant for this, so for now this is perfectly okay.

Should be removed for next bump afterwards, though.

**Comment by Johnnynator** [comment]
Branch is cleaned up and ready to be merged after the llvm update.

**Comment by q66** [comment]
llvm9 is ready, so pending on that now.

**Pull request merged**
