### PR TITLE
[DO NOT MERGE] distcc: update 3.2rc1 -> 3.3.2

### PR DESCRIPTION
**Pull request by fosslinux**

### CODE REVIEW

**Comment by fosslinux** [comment]
Could I please have some help debugging someone? I am very confused about this error.

**Comment by newbluemoon** [comment]
Per default `wrksrc` is set to `$pkgname-$version`, but the tarball you chose seems to diverge: it extracts to just `distcc`. Try using `wrksrc=$pkgname`.

But I think it’s better to use the first link on github’s release page:
https://github.com/distcc/distcc/releases/download/v3.3.2/distcc-3.3.2.tar.gz
This is the release prepared by the author(s) which has the correct naming scheme inside. The tarball used right now is the github auto-generated one, I think, which actually is also a bit larger in size.

**Comment by fosslinux** [comment]
right, thanks!

**Comment by fosslinux** [comment]
yes I tried to, just realised I was actually building `3.2rc1`. thats why I was confused...

I'll fix it now and open a new PR.

**Pull request closed without merging**
