### PR TITLE
gst-plugins-base1: add sndio support

### PR DESCRIPTION
**Pull request by Kistelini**

### CODE REVIEW

**Comment by CameronNemo** [comment]
Why can this not be included upstream?

**Comment by maxice8** [comment]
Over 1k lines, no way i'm going to merge this if not upstream

**Comment by Kistelini** [comment]
It was removed a long time ago from gst-plugins-bad, don't know why. The patch is just a few lines, the rest are new files. It's trivial to adapt the patch for new versions. @maxice8 You merged portaudio and SDL too. Either this patch or no audio for sndio users.

**Comment by t6** [comment]
When I added sndio support to the FreeBSD ports tree, I pulled the GStreamer sndio sink and source from OpenBSD and put them in https://github.com/t6/gstreamer1-plugins-sndio. That way I didn't have to patch any existing GStreamer ports and could build it out of tree. Users just have to install it.

**Pull request closed without merging**
