### PR TITLE
hplip: Update to 3.21.10

### PR DESCRIPTION
**Pull request by heindsight**
Update hplip to latest upstream version and patch to fix Python 3.10 compatibility.

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by biopsin** [comment]
closes #33700
Thank you

**Comment by biopsin** [comment]
Managed to test PR and unfortunate it breaks xsane (scanner) with
```
Failed to open device hpaio:/net/HP_Neverstop_Laser_MPF_120x?ip=192.168.1.201
Error during device I/O
```
but
```
  ~ $ hp-probe -bcups
HP Linux Imaging and Printing System (ver. 3.21.8)
Printer Discovery Utility ver. 4.1

hp:/net/HP_Neverstop_Laser_MFP_120x?ip=192.168.1.201  
HP_Neverstop_Laser_MFP_120x

Found 1 printer(s) on the 'cups' bus.
```

**Comment by biopsin** [comment]
Please add
changelog="https://developers.hp.com/hp-linux-imaging-and-printing/release_notes"
and bump to version 3.21.10

I will test further issue with xsane this weekend..

**Comment by heindsight** [comment]
@biopsin thanks for testing. Not sure why xsane isn't working for you, it does work for me on my Deskjet 3630. One notable difference is that mine uses the LEDM backend and as far as I can tell the Neverstop MFP 120x models use ESCL, so I suppose it's possible there's been a regression for ESCL scanners.

I'll add the changelog and bump to 3.21.10 as requested.

**Comment by biopsin** [comment]
@heindsight nope Im at loss; cant manage to resolve this, I've compaird hp-scan debug logs between 3.20.9 and 3.21.10, further tested hp-doctor -i outputs, there is just no significant diff between versions.
I will update this comment as I forgot to attach the logs..

**Comment by heindsight** [comment]
@biopsin That's rather strange. Could you rebuild with ` -UNDEBUG -DHPMUD_DEBUG -DESCL_DEBUG` added to the `CFLAGS` set in the template?

Then run:
```
scanimage -T -d hpaio:/net/HP_Neverstop_Laser_MFP_120x?ip=192.168.1.201 --verbose
```
while tailing syslog? That might give some more insight into where things are going wrong.

**Comment by biopsin** [comment]
@heindsight sorry for the delay, I'll see how far I get today..

**Comment by ahesford** [comment]
@biopsin, have you had a chance to dig into the scanner issue?

**Comment by biopsin** [comment]
@ahesford go ahead and merge this, I will fiddle with it in the upcomming hollydays. 
I'll rather open a issue if something is amiss with the template.

**Comment by biopsin** [comment]
[Solved and Note]
After a hplip update, to make the scanner pickup the changes,run `"$ hp-plugin"` again and reinstall the scanner plugin. While the prosess it will complain and  

> warning: void distro is not found in AUTH_TYPES

> error: Unable to recieve key from keyserver

but the plugin will eventually install successfull and xsane works again.

Anyway happy new year !!

**Pull request merged**
