### PR TITLE
mgba: update to 0.10.2

### PR DESCRIPTION
**Pull request by fanyx**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (glibc-x86_64)

### CODE REVIEW

**Comment by fanyx** [comment]
@paper42 Can you rerun the build tasks?
I believe the issue lies on the build machines.

**Comment by classabbyamp** [comment]
1. there's probably no point at the moment, as [the builders are still working](https://build.voidlinux.org/waterfall)
2. you can retrigger the build yourself by force-pushing (you may need to amend first to change the commit hash)

**Comment by fanyx** [comment]
ok, something is stuck on the infrastructure...
builders are all complete but the container still breaks

**Comment by classabbyamp** [comment]
rebase, it's fixed now

**Pull request merged**
