### PR TITLE
julia: update to 1.5.3.

### PR DESCRIPTION
**Pull request by lane-brain**

### CODE REVIEW

**Comment by ahesford** [comment]
Did you try building against `llvm11` instead of `llvm10`? If not, please do; this is one of the last packages forcing us to keep `llvm10` around.

**Comment by lane-brain** [comment]
> Did you try building against `llvm11` instead of `llvm10`? If not, please do; this is one of the last packages forcing us to keep `llvm10` around.

@ahesford after what appeared to be a troubled build process, unfortunately it didn't build with llvm11. I'm attaching the build log.

[julia-llvm11.log](https://github.com/void-linux/void-packages/files/5727105/julia-llvm11.log)

**Comment by ahesford** [comment]
That's unfortunate. I know they merged an LLVM11 patch but that might be on a different patch. Thanks for trying.

**Comment by lane-brain** [comment]
not a problem! interesting that this wouldn't pass the build tests here, I was able to get a working build on my end on x86_64 with a fresh zap + binary bootstrap

**Comment by ahesford** [comment]
Some of these failures are carried over from 1.5.2 (libgit2), while most of the file errors seem related to excessive privilege in the XBPS chroot environment. (The tests expect file operations to fail for regular users, but those operations succeed in the XBPS build environment for the user doing the build.) The socket tests do not appear in my local trials, so it might be some configuration difference in the test machines.

**Pull request closed without merging**
