### PR TITLE
gitea: Add bash dependency

### PR DESCRIPTION
**Pull request by arete**
Signed-off-by: Gerardo Di Iorio <arete74@gmail.com>

### CODE REVIEW

**Comment by xtraeme** [comment]
Probably your change is OK, but you didn't explain why it's necessary

**Comment by xtraeme** [comment]
I'd like to make people contributing random changes why those changes are necessary. This is what the commit log should explain.

**Comment by xtraeme** [comment]
Hope you understand it, cheers

**Comment by arete** [comment]
Hi,
he bas shell is necessary for ssh support.

https://github.com/void-linux/void-packages/blob/748d00b14d5e69f4bb2f73d96e2b2f61ee131f4c/srcpkgs/gitea/template#L39

**Comment by xtraeme** [comment]
I see, thanks for the info.

**Pull request merged**
