### PR TITLE
strawberry: update to 0.9.3.

### PR DESCRIPTION
**Pull request by asymmetros**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by q66** [comment]
fix commit message, also the URL shouldn't be replaced

**Comment by asymmetros** [comment]
fixed the name, and the url (line 17, distfiles)

**Comment by ericonr** [comment]
PR name is different from commit message.

**Comment by asymmetros** [comment]
Sorry for waisting your time. (had built it a few days ago with applying no patch. had built it also with applying patch from https://files.strawberrymusicplayer.org/patches/ )
Sorry again

**Comment by Johnnynator** [comment]
b80014e06475444ffd601f473cd5bec9f0c79214

**Pull request closed without merging**
