### PR TITLE
yad: update to 0.41.0.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by paoloschi** [comment]
16 days have gone and the package is not yet available to the users
 (repo alpha.de.repo.voidlinux.org/current now: yad-0.40.3_2).

has something gone wrong or is it just a matter of waiting?

**Comment by maxice8** [comment]
On Sun, Feb 24, 2019 at 03:59:25AM -0800, paoloschi wrote:
> 16 days have gone and the package is not yet available to the users
>  (repo alpha.de.repo.voidlinux.org/current now: yad-0.40.3_2).
> 
> has something gone wrong or is it just a matter of waiting?
> 
>  
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/pull/8252#issuecomment-466767368

I closed it because i didn't feel like pushing, if you want it you can just make a pull request for it, note that you will need to adapt to the new version.

**Comment by paoloschi** [comment]
I'm not capable of it.. If I were, I would gladly contribute to solving #6309 and #6560 too, which I am very interested in...

**Comment by maxice8** [comment]
You can try getting a good soul on #voidlinux IRC to help you but Void Linux is ultimately a controlled do-ocracy like most free software projects so the most effective way of making change is doing it.

**Comment by paoloschi** [comment]
I didn't know all this, useful clarification, thank you

**Pull request closed without merging**
