### PR TITLE
nheko: update to 0.9.1

### PR DESCRIPTION
**Pull request by Huy-Ngo**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x86-64-musl)

### CODE REVIEW

**Comment by Huy-Ngo** [comment]
Oops, :facepalm: amending the wrong commit

**Comment by ericonr** [comment]
You need to revbump nheko for this.

For related packages like this, please do the update in a single PR.

**Comment by Huy-Ngo** [comment]
OK, I've just added nheko to the branch.

**Comment by ericonr** [comment]
The shlibs commit should be together with the mtxclient one.

**Pull request merged**
