### PR TITLE
gimp: update to 2.10.8

### PR DESCRIPTION
**Pull request by hanspolo**

### CODE REVIEW

**Comment by Cogitri** [comment]
Can't be updated due to https://github.com/void-linux/xbps/issues/14.

**Comment by Oreo639** [comment]
Cogitri, could an INSTALL script be used to work around this, or is that not how it works?

**Comment by luzpaz** [comment]
any progress on this?

**Comment by maxice8** [comment]
ping

**Comment by luzpaz** [comment]
bump

**Comment by maxice8** [comment]
Closing due to lack of response

**Pull request closed without merging**
