### PR TITLE
mpv: update to 0.37.0, libplacebo: update to 6.338.1

### PR DESCRIPTION
**Pull request by zen0bit**
#### Testing the changes
- I tested the changes in this PR: **played movie**

#### Local build testing
- I built this PR locally for my native architecture, (x64 glibc)

### CODE REVIEW

**Comment by daniel-eys** [comment]
vlc needs a rebuilt against the new libplacebo

**Comment by ahesford** [comment]
Unfortunately, VLC doesn't build cleanly with new `libplacebo`. We're blocked until VLC can be patched or `libplacebo` is split.

**Comment by sfan5** [comment]
FWIW arch went and disabled placebo support [in vlc](https://gitlab.archlinux.org/archlinux/packaging/packages/vlc/-/commit/fbf315e2b05e30c520469a23dd58cd639aebc35a) to unblock this situation.

**Comment by zen0bit** [comment]
> FWIW arch went and disabled placebo support [in vlc](https://gitlab.archlinux.org/archlinux/packaging/packages/vlc/-/commit/fbf315e2b05e30c520469a23dd58cd639aebc35a) to unblock this situation.

Should we apply same patch?

**Comment by ahesford** [comment]
If you can describe what VLC does with libplacebo and what we'd be giving up, we can consider building without it.

Another alternative is moving forward with the libplacebo upgrade and adding a legacy package to support VLC.

**Comment by zen0bit** [comment]
Don't know. Using just mpv for long time...
Could investigate eventually, but low prirority

**Comment by ahesford** [comment]
I dropped `libplacebo` from `vlc` in 0e9264156ba2509d5bd66a1ba7be2f3ba2ccf0f1. You are welcome to mark this PR ready for review if you would like to move forward with the `mpv` update.

**Pull request closed without merging**
