### PR TITLE
[WIP] boost: update to 1.72.0.

### PR DESCRIPTION
**Pull request by Johnnynator**

### CODE REVIEW

**Comment by q66** [comment]
i'd probably add explicit `threading=multi runtime-link=shared link=shared,static` to build options, just to be on the safe side (also i think `reading=multi` is actually not default and we've been building boost wrong all along)

also, do we really need 1.69 to be introduced...

**Comment by Johnnynator** [comment]
> also, do we really need 1.69 to be introduced...

Patching everything to work with 1.72 is quite some work. This way a can keep some that are annoying to patch for 1.72 at 1.69 for now. E.g. freeorion would require a rather big patch set or updating to the RC candidate. The easier way for now is to have both version and remove it later.

**Comment by Johnnynator** [comment]
> also i think `threading=multi` is actually not default and we've been building boost wrong all along

Why that? I think multi is what we want. Since threadsafe code should work everywhere albeit with a performance drawback. The alternative would be to just build boost 4 times instead of only 2 times right now (`static/single`, `static/multi`, `dynamic/single`, `dynamic/multi`), but I doubt that it would be worth it.

> threading
>
>    Allowed values: single, multi
>
>    Controls if the project should be built in multi-threaded mode. This feature does not necessary change code generation in the compiler, but it causes the compiler to link to additional or different runtime libraries, and define additional preprocessor symbols (for example, _MT on Windows and _REENTRANT on Linux). How those symbols affect the compiled code depends on the code itself.

**Comment by q66** [comment]
That's my point, we want multi but we haven't been building it as such.

**Comment by Johnnynator** [comment]
> That's my point, we want multi but we haven't been building it as such. (also, I see you added the options for 1.72 but not 1.69, add them for 1.69 also)

Boost is getting built with threading=multi by default, at least boost 1.69 is built with multi threading.

**Comment by q66** [comment]
ok then - it's probably best to specify that explicitly anyway, just in case they decide to be stupid and change the defaults at some point :P

**Comment by Johnnynator** [comment]
4c3b1f9bcd68bc8f9a63bce6069a26d86e235f79

Libreoffice got rebuild with the update to 6.4.0.3

**Pull request closed without merging**
