### PR TITLE
apparmor: fix dnsmasq profile

### LINKED ISSUE #29343: `dnsmasq` not working with `virt-manager`
### System

* xuname:  
  Void 5.10.20_1 x86_64-musl GenuineIntel uptodate rFFF
* package:  
  dnsmasq-2.84_1; libvirt-7.1.0_1

### Expected behavior
Created Virtual Machine with open virbr

### Actual behavior
Segfaults on opening virbr:
Failed to start virtual network “default”：internal error: Child process (VIR_BRIDGE_NAME=virbr0 /usr/bin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper) unexpected exit status 149: Segmentation fault

dnsmasq: lease-init script returned exit code 139

### Steps to reproduce the behavior
 - Create a Virtual Machine by using `virt-manager`

### PR DESCRIPTION
**Pull request by noarchwastaken**
Closes #29343

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Review by ericonr — COMMENTED** [review]
I'd name it `usr.bin.dnsmasq`, for void purposes.

Commit message should include profile origin too. That said, I'd rather not vendor this in, if possible...

**Comment by noarchwastaken** [comment]
> I'd name it `usr.bin.dnsmasq`, for void purposes.
> 
> Commit message should include profile origin too. That said, I'd rather not vendor this in, if possible...

The profile comes from the current default, with the change stated [here](https://github.com/void-linux/void-packages/issues/29343#issuecomment-817241508), and I kept the original naming.

**Comment by noarchwastaken** [comment]
This is actually the first time that I touched apparmor profiles, and I would like to know if there is a better solution.

**Comment by FollieHiyuki** [comment]
We can add rules to `/etc/apparmor.d/local/` if touching the main profile rule is not ideal

**Comment by paper42** [comment]
I think this is a bigger problem that requires a better solution. apparmor's upstream often fixes their profiles[1] when new versions of software require new permissions, but void ships profiles from the last apparmor release which are often broken by the time a new release comes out. The simplest solution right now I can think of would involve creating a new package with apparmor profiles which would track upstream's master.
The best solution may be to create a new void-appamor git repository which would track new versions of software in void[2], because there are often some void specific permissions. This would also allow us to have profiles for more packages than what upstream provides, but this will require dedicating some time to it.

> We can add rules to /etc/apparmor.d/local/ if touching the main profile rule is not ideal

@FollieHiyuki I think `/etc/apparmor.d/local/` is meant for user customizations, so distributions shouldn't touch that if not neccessary (for example nvidia graphics cards may require different permissions than intel or amd).

[[1] many commits to apparmor profiles since the last release 4 months ago](https://gitlab.com/apparmor/apparmor/-/commits/master/profiles/apparmor.d)
[[2] Apparmor profile plumbing issue](https://github.com/void-linux/void-infrastructure/issues/82)

**Comment by Duncaen** [comment]
Instead of vendoring the whole file, patching it would be a lot cleaner and we would actually notice if the vendoring is not necessary or there have been changes in the upstream profile.

**Comment by noarchwastaken** [comment]
I changed it into a patch. Please review.

**Comment by Duncaen** [comment]
A lot better, just change the commit message to `apparmor: fix dnsmaq profile`.

**Review by Duncaen — APPROVED** [review]

**Pull request merged**
