### PR TITLE
[nomerge] wayland-compositors: use elogind

### LINKED ISSUE #20930: Restructure dependencies on elogind
As was agreed when writing the Wayland docs page, elogind is a requirement for a safe wayland session. Therefore, should we make elogind a dependency of the wayland package itself?

Packages like Sway currently have it as a build option, defaulting to a setuid binary instead. Cage, on the other hand, doesn't enable setuid, so it definitely requires elogind (at least in its current state). However, Cage currently doesn't list elogind as a dependency, so if you try to simply install it and run it (without looking at the docs), it will error out due to missing capabilities. Even running as root doesn't work, because then it can't drop privileges properly.

Making elogind a dependency for wayland seems like it would be the best solution for all cases. I would even make a case for an INSTALL message telling the user to enable the service and restart their device (or just log in and out, idk. Whenever I enable elogind I have to reboot for it to work).

Tagging @Duncaen, because you made the case for elogind being a requirement for Wayland.

### PR DESCRIPTION
**Pull request by travankor**
Hopefully fixes #20930

### CODE REVIEW

**Comment by ericonr** [comment]
Looks good to me. Removing setuid feels like the correct path. We should perhaps document that this is the correct way of setting up Wayland compositors (not sure where that would go, though).

@Duncaen Do you think it would be bad to completely remove the elogind option to make it compulsory?

**Comment by ericonr** [comment]
https://github.com/swaywm/sway/wiki/Running-Sway-without-systemd

As a reference: upstream recommends logind or elogind. setuid is the next best solution, with security implications. Capabilities seems to be the worst. As a distro we can, of course, make the choice to use setuid, even if I believe it's far from the best method.

**Comment by travankor** [comment]
Well, I set elogind as the default option, and added setuid so that people can opt-in to setuid. This seems perfectly reasonable to me.

Some reasons I don't like logind off the top of my head:

- Dbus/polkit integration: polkit literally depends on a javascript interpreter and people striving for a KISS desktop don't need these

- Musl is a second class citizen (no upstream support, and elogind has a bus factor of one)

- Xorg is still root by default on Void

- There are nontrivial issues with elogind and ACPI (like crashing after suspend or not suspending at all)

- Code churn and upstream has zero interest in regression testing

- Logind is more LOC than sway+wlroots combined

- If dbus breaks, elogind probably will too

- freedesktop.org specifications are dumb

The only two upsides of logind are 1) it works out of the box and 2) multi-seat, which 95% of people don't use.

setuid on a local machine is less of a concern than say running a web server locally or using ssh agent forwarding.

**Comment by ericonr** [comment]
> Dbus/polkit integration: polkit literally depends on a javascript interpreter and people striving for a KISS desktop don't need these

I think D-Bus is ok, it adds a lot of value, at least from my experience. Polkit I agree has a lot of architectural issues, which is why I only enabled it when I was trying to get flatpak to work.

> Xorg is still root by default on Void

This is, of course, something we can try to change.

> multi-seat, which 95% of people don't use

Good point.

> Logind is more LOC than sway+wlroots combined

Fork elogind and remove multi-seat implementation? Not kidding, I'd be very interested in knowing about a small program for the elogind functionality we need (and if that's even possible). I know ConsoleKit2 was a part of that, but it's unmaintained and seemed quite large still.

> setuid on a local machine is less of a concern than say running a public web server locally or using ssh agent forwarding.

I don't know how to make this judgment. If it's determined not to be a huge risk, I don't have any issue with removing `elogind` as the default option. I mostly want Wayland compositors to have uniform templates.

**Comment by ShinyRice** [comment]
Can't both elogind and setuid options coexist, though? Or maybe I just imagined that happening in Artix? Do correct me if I'm wrong here.

I do have one argument in favour of setuid: one of the things elogind does for you is to correctly set XDG_RUNTIME_DIR and, more importantly, creating that folder in /run/user/$UID, instead of having it in /home/$USER, for security reasons if I'm not mistaken here either. Can't that just be done with a simple service that creates it at boot? Or does elogind offer more functionality for Sway and its wlroots ilk? Otherwise, I can't really fathom having to install elogind just to do that.

**Comment by hippi777** [comment]
hi there! :)

(others: plz correct me in case of need)

@ShinyRice: i believe they can, but that renders elogind useless, as it is a capability based protection right for avoiding setuid, or maybe im wrong here, as most likely it is about what u r already running in case of graphics stuffs, instead of what can be run... setuid is considered to be harmful cuz if the given app has a way to do anything nasty (like when it has a small bug or forgotten corner case), then it will do that with root privileges, and it can reach more stuffs than anything limited by capabilities... otherwise using a system alone (dont forget about special users, like admin for vesta control panel, just for an irrelevant example, as u probably wont have vesta on ur daily driver and u probably wont have graphics on ur server) means that other users wont be an issue for ur security, but if u run anything with ur own privileges that can harm u, then most likely u r already wrecked, as priv escalation have so many ways, and u probably care about ur data, not ur system, and ur data is already in the wrong hands even before a priv escalation :D

**Comment by ericonr** [comment]
@travankor you need to change the `INSTALL.msg` for `wayfire`, because it will either stop requiring elogind or elogind will be installed already.

I support setuid as a solution, btw. Sway, at least, seems to use elogind even with setuid, so it seems to drop privileges pretty quickly.

**Comment by travankor** [comment]
Thanks and fixed.

>Sway, at least, seems to use elogind even with setuid, so it seems to drop privileges pretty quickly.

Using both doesn't make sense.

**Comment by ericonr** [comment]
@travankor I think you need to rebase it again. And what I meant is that even if you install Sway with setuid, if the system has elogind installed, it uses elogind to access the display. At least when I killed the elogind service in my system it killed the compositor's access to DRM immediately.

**Comment by travankor** [comment]
Let's wait for a void-pkgs committer to accept or reject this -- unless there's some ongoing discussion on IRC or something that I'm not a part of? (I don't have a bouncer, so I just join whenever I have questions to ask)

**Comment by travankor** [comment]
>And what I meant is that even if you install Sway with setuid, if the system has elogind installed, it uses elogind to access the display

This is one of the good motivations in favour for this change.

**Comment by ericonr** [comment]
I haven't seen any discussion about this lately on IRC.

Regarding this

> This is one of the good motivations in favour of this change. If you're dual-booting with GNOME, for example, you will want the elogind variant.

You could want the elogind for a smaller risk surface, but the setuid version should be able to coexist peacefully.

**Comment by ericonr** [comment]
But still, depending on elogind seems better. Looks good to me. Do you want to tag anyone to review it?

**Comment by ericonr** [comment]
Want to wait for this patch? https://cgit.freedesktop.org/drm/drm-misc/commit/?id=45bc3d26c95a8fc63a7d8668ca9e57ef0883351c

We could still need setuid/elogind for the input devices, but it's not a certain thing from what I understand.

**Comment by travankor** [comment]
What do you mean by wait? The patch is from the kernel, so it would take a while for it to be available on all supported kernels.

Seems like this works for rootless Xorg, too, which is something void should support at some point.

>We could still need setuid/elogind for the input devices, but it's not a certain thing from what I understand.

udev is supposed to manage input. logind is somewhat new to this area AFAIK. Maybe logind has a better API, but udev has been around for a long time.

**Comment by ericonr** [comment]
@travankor regarding rootless Xorg, I think it's due to the configuration file in `/etc/X11/Xwrapper.config`, which specifies that root rights are needed by default:

```
needs_root_rights = yes
```

It uses a setuid executable in `/usr/libexec/Xorg.wrap`. I have to test if setting it to `auto` is enough for rootless Xorg to work adequately.

I don't know enough udev, so I'm not sure how the handoff is working. What I read from discussions regarding input devices was that you could put the user in the `input` group to allow them to access those devices, but that makes implementing a keylogger extremely trivial as well.

**Comment by travankor** [comment]
>but that makes implementing a keylogger extremely trivial as well.

Can this be solved by running sway as a custom user? Also there are legitimate use cases for people who want to remap keys, etc.

**Comment by ericonr** [comment]
If you need to remap keys I believe you can use `xkb` keymaps, which wlroots can load and use. Doesn't need a daemon for it.

> Can this be solved by running sway as a custom user?

I don't know but I don't think so, running graphical stuff as another user feels weird. I will try to ask over at #sway, though.

I had based my comment off of https://github.com/swaywm/wlroots/commit/906c0766df2fec4bd32c316fd1b0d46fded5fc84 , but it does seem to contrast a bit with the comment you linked to. Will ask about it as well.

**Comment by ericonr** [comment]
#23793 is adding the elogind build option for all of them, but it isn't on by default. So this PR would just toggle that.

**Comment by travankor** [comment]
I think it's better to close this.

**Pull request closed without merging**
