### PR TITLE
bluez: enable deprecated tools

### PR DESCRIPTION
**Pull request by benalb**

### CODE REVIEW

**Comment by CameronNemo** [comment]
Please put them in a subpackage and note that they are deprecated in the short description.

**Comment by benalb** [comment]
Never did the subpkg thing, so, before break something, in the configure_args section, keep the --enable-deprecated flag, and add this to the end of the template
```
bluez-deprecated_package() {
        short_desc="Deprecated tools"
        pkg_install() {
                vinstall /usr/bin/ciptool
                vinstall /usr/bin/hciattach
                vinstall /usr/bin/hciconfig
                vinstall /usr/bin/hcidump
                vinstall /usr/bin/hcitool
                vinstall /usr/bin/rfcomm
                vinstall /usr/bin/sdptool
        }
}

```

Is that ok?

**Comment by maxice8** [comment]
short_desc+=" - deprecated tools"

**Comment by maxice8** [comment]
Don't forget to also add the manpages

**Comment by maxice8** [comment]
Please notify when proposed changes are made.

**Pull request merged**
