### PR TITLE
New Package: scryer-prolog-0.8.123

### PR DESCRIPTION
**Pull request by mkohlhaas**

### CODE REVIEW

**Comment by Chocimier** [comment]
Builds outside of x86_64 when m4 is moved to hostmakedepends. I guess it can build for i686 on i686 host, but don't have hardware nor VM around.

**Comment by mkohlhaas** [comment]
Scryer Prolog uses the [GNU Multiple Precision Arithmetic Library GMP](https://gmplib.org/) as part of the FFI Rust library [gmp-mpfr-sys](https://crates.io/crates/gmp-mpfr-sys). When cross-compiling for i686 the configure script gets confusing information about the platform. It can't really figure out if it is 32 or 64 bit:
 
```
using ABI="64"
...
configure: error: Oops, mp_limb_t is 32 bits, but the assembler code in this configuration expects 64 bits.

```
I think one could solve the issue by specifying:

`configure ABI=32`

according to the [GMP documentation](https://gmplib.org/manual/ABI-and-ISA#ABI-and-ISA).

But how would this be possible with a build type of `cargo`?

**Comment by mkohlhaas** [comment]
When I am compiling for i686 is this actually a cross compile?

Setting up locally a bootstrap environment for i686 I get the same error message as Travis. If it were a cross-compile it would show up in the call to the configure script. See: https://gitlab.com/tspiteri/gmp-mpfr-sys/-/issues/15. But building the project just with `cargo build --release` when change rooting into `master_dir` works just fine. Don't know what the issue is.

**Comment by Chocimier** [comment]
I hate rust toolchain for doing as much as possible to make troubleshooting hard.
If one conditionally state[1][2] ABI=32, it'll likely work. Usually it is just patch. With cargo, one need to publish full fixed source in git repository online, then patch dependency tree[3], if available.
Mentioned gmp-src/configure dissapears after build fails, luckily it is materialized in repo, not generated during build.

If you don't file like patching, just mark `archs="~i686*" # aggresive cpu detection`.

In any case, optionally report upstream.

[1] https://gitlab.com/tspiteri/gmp-mpfr-sys/-/blob/16e0a660/build.rs#L553
[2] https://gmplib.org/manual/ABI-and-ISA
[3] https://github.com/void-linux/void-packages/pull/22534/files#diff-c0a371b0356b2c0ee8ff4b74cc227f4a

**Comment by Chocimier** [comment]
> When I am compiling for i686 is this actually a cross compile?

It is native build. I was talking of i686, because gmp seems to use cpu identification at configure stage. Checked, it builds fine within i686 VM.

**Comment by mkohlhaas** [comment]
> If you don't file like patching, just mark `archs="~i686*" # aggresive cpu detection`.

Ok, that's what I did now. I'm not fully satisfied though. I even tried a version without `build_style=cargo` and just called `cargo` directly. But no success.

Do you think the package can get approved as it stands now?

**Comment by mkohlhaas** [comment]
Thank you!

**Comment by Chocimier** [comment]
Pushed with few changes: added requested comment on why not to build for i686, removed build helper as it is already effective with build style, squashed to single commit.

Prolog implementetion itself is quite unpolished. It ate all memory when asked for 4th solution of p(a, b). p(b, c). p(A,C) :- p(A,B), p(B,C).

**Comment by triska** [comment]
Thank you a lot @Chocimier for merging this!

In several respects, Scryer Prolog is one of the most advanced Prolog systems that currently exists, even though it is still in its early stages of development. For instance, it conforms syntactically to the Prolog ISO standard, it includes extensions for constraint logic programming (CLP), and is the first Prolog system that implements a very compact internal representation of strings as lists of characters. It is an excellent platform to teach Prolog.

For your concrete example, try SLG&nbsp;resolution by adding the following two lines at the start of the program:

<pre>
:- use_module(library(tabling)).

:- table p/2.
</pre>

We then get for the most general query:

<pre>
<b>?- p(A, B).</b>
   A = a, B = b
;  A = a, B = c
;  A = b, B = c
;  false.
</pre>

i.e., all solutions are enumerated, and the query *terminates*.

Thank you a again!

**Comment by Johnnynator** [comment]
This templates fails to build on musl builders. Also it probably should link against system gmp, so we don't run into all these issues we have right now (i686 build failure would probably be also solved by that).

marked it for broken now on musl (and some comments on more things that should change) f0162e98210ab02158a84e0bd559d3de5aacdba2

**Pull request merged**
