### PR TITLE
curl: update to 7.84.0.

### PR DESCRIPTION
**Pull request by MouadCharradi**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, x86-64, glibc
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64

### CODE REVIEW

**Comment by mhmdanas** [comment]
I haven't yet incorporated the patch in this PR into my PR, so I'll be closing my PR in favor of this one.

**Comment by mhmdanas** [comment]
> Please also update chroot-curl so that armv6l-musl, armv7l and aarch64* pass CI.

@JamiKettunen `srcpkgs/chroot-curl` is just a symlink to `srcpkgs/curl`, which means that it's actually already upgraded in this PR.

**Comment by JamiKettunen** [comment]
> @JamiKettunen `chroot-curl` is a subpackage of `curl`, which means that it's actually already upgraded in this PR.

Ah, indeed. I've previously only seen `chroot-*` packages being separate packages with minimal build-time dependencies for bootstrap purposes; not sure what's up with the `libcurl-7.84.0_1 in transaction breaks installed pkg 'chroot-curl-7.83.1_1'` errors then, it looks like previous upgrades worked fine without any additional changes compared to this PR

**Comment by mhmdanas** [comment]
Yeah, I noticed that in my previous PR, it's quite strange.

**Comment by MouadCharradi** [comment]
Regarding the i686 error, I feel like it could be related to [this](https://github.com/curl/curl/issues/9141) problem. A fix has already been submitted, [this patch](https://github.com/curl/curl/pull/9142/commits/8629d5eb19f033be579cb6411461b92896afda86). I'll try it and see if it works, while we find another solution for the arm architectures.

**Comment by ericonr** [comment]
Apologies, I missed this PR and the surrounding discussion. Will import patches all in one go.

>  libcurl-7.84.0_1 in transaction breaks installed pkg 'chroot-curl-7.83.1_1' errors then, it looks like previous upgrades worked fine without any additional changes compared to this PR

This is caused by a funky behavior in how we define shlib dependencies for subpackages, I need to PR a fix for it.

**Comment by ericonr** [comment]
The issue with the i686 build isn't that patch you linked; we should be building a threadsafe version of the library and it shouldn't need that flag either.

**Comment by ericonr** [comment]
There was an issue for arm builds as well, though that's been fixed in my original update commit.

**Comment by ericonr** [comment]
The test is broken on i686 because they are trying to create too many threads. I figured that might be it, but testing locally confirmed it. I'm reporting this bug upstream and merging as is.

https://github.com/void-linux/void-packages/commit/af67bfc9d1db123f1d9c0dc8ff78f84b209c2be1

**Pull request closed without merging**
