### PR TITLE
intellij-idea-community-edition: update to 2023.1

### PR DESCRIPTION
**Pull request by Bnyro**
#### Testing the changes
- I tested the changes in this PR: **YES**

### Local build testing
- I built this PR locally for my native architecture: x86_64

### CODE REVIEW

**Comment by mhmdanas** [comment]
Append ", adopt" to your PR title and commit message.

**Comment by Bnyro** [comment]
Thanks for the hint!
Note that intellij stopped shipping/releasing the versions without jbr included, thus adopting the template is required.

**Comment by mhmdanas** [comment]
Makes sense, but why did you add a `virtual?java-environment` dependency then?

**Comment by Bnyro** [comment]
Oh, that's been a left-over from trying to get it run without the jbr.

**Comment by mhmdanas** [comment]
Actually, testing this locally, and something in the package links to libjvm.so, so the package installs openjdk8-jre anyway. With this in mind, it's probably a good idea to keep `virtual?java-environment`.

**Comment by ahesford** [comment]
Please drop the adoption; we would like to see a history of contributions before adding somebody's name to a package.

**Comment by Bnyro** [comment]
> Please drop the adoption; we would like to see a history of contributions before adding somebody's name to a package.
>
sure, understandable

**Pull request merged**
