### PR TITLE
gfuzz: updated template to match upstream

### PR DESCRIPTION
**Pull request by misuchiru03**
Template updated wrksrc, go_import_path, homepage, and distfiles to gfz.

### CODE REVIEW

**Comment by ericonr** [comment]
Are the contents the same? Should we rebuild?

See #26377

**Comment by the-maldridge** [comment]
I'd like to see this rebuilt.  The source tarballs are different minimally.

**Comment by ericonr** [comment]
This does

```
git clone -- https://github.com/braaaax/gfuzz /builddir/gfz-0.2/_build-gfuzz-xbps/src/github.com/braaaax/gfuzz
```

As the very first build step, which feels very wrong to me...

**Comment by ericonr** [comment]
Done in 18ef8e1d29de4a648a6564c96bf1a9e2a081b893, I somehow completely missed it.

**Pull request closed without merging**
