### PR TITLE
[WIP] qt5: update to 5.13.0

### LINKED ISSUE #12550: qt5-host-tools conflicts with qt5
void-666_1

Found by xbps-0.54:

```
ERROR: qt5-host-tools-5.11.3_7: file `/usr/bin/moc-qt5' already installed by package qt5-5.11.3_7.
[DEBUG] [trans] failed to verify transaction files: File exists
[DEBUG] [pkgdb] released ok.
```

### PR DESCRIPTION
**Pull request by Johnnynator**
Test repo up on https://void.johnnynator.dev/qt5.13/

Qt5-webengine now always requires a 32bit host compiler when cross compiling to a 32bit cross arch (e.g. x86_64 -> arm*), so we have to disable it for now on all 32bit arm* architectures.

Status: qt5-webengine is still broken on musl

Should resolve #12550

### CODE REVIEW

**Comment by Johnnynator** [comment]
@pullmoll Can you review this

**Comment by pullmoll** [comment]
Wow, a lot of changes and certainly a lot of work. Fortunately a lot of removed patches also.
I believe the problem with building qtwebengine from 64 for 32 bit is due to the `v8 snapshot` option.
In case we can disable it (via gn?) cross building from `x86_64` for `arm*` should become possible again.

**Comment by Johnnynator** [comment]
> I believe the problem with building qtwebengine from 64 for 32 bit is due to the `v8 snapshot` option.
> In case we can disable it (via gn?) cross building from `x86_64` for `arm*` should become possible again.

`v8 snapshot` is already disabled. 
Also most of the removed patches are webengine musl related which is nevertheless broken (with our without them). q66 will provide a updated ppc patcheset soon.

**Comment by Johnnynator** [comment]
```
qt5-host-tools and qt5-tools conflict for
/usr/bin/lconvert-qt5
/usr/bin/lrelease-qt5
/usr/bin/lupdate-qt5
```
These still need to be resolved.

**Comment by pullmoll** [comment]
Same problem in `qt5-tools_package()`:
```
if [ -e ${PKGDESTDIR}/usr/bin/${f}-qt5 ]; then
```

BTW I still did not find sufficient time to look closer at this PR.

**Comment by q66** [comment]
ppc64 and ppc64le patches here https://github.com/void-power/void-packages/commit/363859571a4b1ca9e2a3b7415928e4c7e015d48b

**Comment by Johnnynator** [comment]
@pullmoll Do you have an idea how we could fix our qmake build-style/qmake for cross compiling that wouldn't be a tremendous amount of work?

Longer version:
A qmake binary only ever supports one target and has things like `QT_SYSROOT` and `QT_INSTALL_LIBS` hardcoded in the resulting binary so they can't be overwritten at runtime by a config file or flag. There are only 4 options to solve this for Void visivle for me:

- Build qtbase two times for every cross target, once as cross packages as currently and a 2nd with the same config for the host and only grab qmake out of there (wastes a ton of ressources on the builder)
- Add a way for xbps-src to spill out a cross target package and a build arch package (probably quite complex, and would (at least currently) only be needed for qt)
- manually mess with the provided Makefile (probably the easiest way)
`make EXTRA_CXXFLAGS="-I/usr/include/qt5/QtCore/5.13.0/QtCore -I/usr/include/qt5/QtCore/5.13.0 -I/usr/include/qt5/QtCore -I/usr/include/qt5/ -DQMAKE_OPENSOURCE_VERSION" QT_MAJOR_VERSION=5 QT_MINOR_VERSION=13 QT_PATCH_VERSION=0 QT_VERSION=5.13.0 SOURCE_PATH=.. QMAKESPEC=/usr/lib/qt5/mkspecs/linux-aarch64-gnu-g++ BUILD_PATH=. RM_F="rm -rf" EXTRA_LFLAGS="-lQt5Bootstrap"  -f Makefile.unix` gives an unconfigured qmake
- Make the 107 packages that use the qmake build-style nocross

**Comment by pullmoll** [comment]
I know what you mean. The qmake build style is so ugly because of the host's qmake using the hard coded paths. 

How about we modify qmake to respect some of our XBPS_* environment variables, enabled only if some XBPS_QMAKE_MAGIC is defined, and then override its currently hard coded values? If not enabled, qmake would act just like it does now for the regular user, i.e. as a host tool. Otherwise it would accept the build environment's sysroot etc. settings and look for the cross qt5 headers etc. where they are.

To devise such a patch cannot be too hard, and the code to modify is most probably all in a single source file anyway.

I will take a look at qmake's source to see where we can possibly hack it for our case.

**Comment by newbluemoon** [comment]
@Johnnynator  did you try with a `qt.conf` file? See [https://doc.qt.io/qt-5/qt-conf.html](https://doc.qt.io/qt-5/qt-conf.html):

> The qt.conf file can be used to override the hard-coded paths that are compiled into the Qt library. These paths are accessible using the QLibraryInfo class. Without qt.conf, the functions in QLibraryInfo return these hard-coded paths; otherwise they return the paths as specified in qt.conf.
>
> Without qt.conf, the Qt libraries will use the hard-coded paths to look for plugins, translations, and so on. These paths may not exist on the target system, or they may not be accessible. Because of this, you may need qt.conf to make the Qt libraries look elsewhere.

There was an issue in the old repository which sadly is gone now. I tried with this `qt.conf`:
```
[Paths]
Sysroot=
Prefix=/usr
ArchData=/usr/lib/qt5
Data=/usr/share/qt5
Documentation=/usr/share/doc/qt5
Headers=/usr/include/qt5
Libraries=/usr/lib
LibraryExecutables=/usr/lib/qt5/libexec
Binaries=/usr/lib/qt5/bin
Tests=/usr/tests
Plugins=/usr/lib/qt5/plugins
Imports=/usr/lib/qt5/imports
Qml2Imports=/usr/lib/qt5/qml
Translations=/usr/share/qt5/translations
Settings=/etc/xdg
Examples=/usr/share/qt5/examples
HostPrefix=/usr
HostData=/usr/lib/qt5
HostBinaries=/usr/lib/qt5/bin
HostLibraries=/usr/lib
Spec=linux-g++
TargetSpec=linux-g++
```
and think there also had to be made some modifications to `qconfig.pri` and `qmodule.pri`. But something didn’t work out and due to a lack of resources I didn’t pursue it any further.

**Comment by pullmoll** [comment]
@newbluemoon in case this really works it should be the easiest way.
I remember I tried with a `qmake.conf` or `.qmake` file created in the build style and never got it working right - probably because it's `qt.conf` and not `qmake.conf` :-)

**Comment by newbluemoon** [comment]
@pullmoll this would surely be an explanation. ;)

Maybe you remember this issue: I tried to compile some qt5 program natively on my RPi and ran into an issue where the modules in `/usr/lib/qt5/mkspecs/modules/*.pri` weren’t found. With the `qt.conf` from above (and some other minor adjustments) I was able to compile it; i.e. the right paths were used. However, I believe in the end the problem was that when the application used other qt5 modules besides the core it didn’t work because the required `*.pri` files weren’t available in the cross built devel package of the corresponding module. So there was an underlying problem we never got around to solve.

One more thing: the only way I was able to make `qmake` use the `qt.conf` was when both executable and configfile were residing in the same directory.

**Comment by Johnnynator** [comment]
@newbluemoon Can you take a look into this with qt5.13 ? I can't get it convinced to use the qt.conf and do what I want, but maybe i'm just missing something. I have my test repo linked in the first post.

**Comment by newbluemoon** [comment]
I tried with the `fmit` package. The problem was that `qmake` hardcoded the required qt-libraries `fmit` is linked to in the `Makefile` when generating it with a full path (`/usr/lib/...`) which fails, of course, when cross-compiling.

The `qt.conf` has to be in `.../masterdir/usr/lib/qt5/bin/`. For now I just put it there manually. I used the one from above, just changed

    Libraries=/usr/lib

to

    Libraries=/usr/armv7l-linux-musleabihf/usr/lib

and that worked. `qmake` used the right paths in the generated `Makefile` and the package was built successfully. Just haven’t tested it on my RPi, but don’t think there will be a problem.

It would be nice to do the same for the includes so that the required qt-modules don’t have to be added to `hostmakedepends` in the cross-case anymore, but the required `*.pri` files in `/usr/lib/qt5/mkspecs/modules/` are still missing in the cross-devel-packages. The same persisting problem I mentioned above. But we will find a solution one day! ;)

Perhaps it’s best to generate `qt.conf` in the build-style and insert the corresponding target architecture there. Then after the build remove the file.

A sidenote: You can check if `qmake` uses `qt.conf` when you `xbps-src chroot` into the masterdir and run `qmake -query`. The modified values should be displayed.

However, I also tested `zrandr` and there was a problem with `lrelease`. But this could be an entirely different problem. I’ll look into it.

Also, I think it might be a good idea to check all qmake-style packages if other problems arise or if changing that path leads to new ones. Anyway, I’ll try to check some more. :)

**Comment by Johnnynator** [comment]
Thanks @newbluemoon zrandr is probably unrelated to cross compiling and an oversight from my site, I tested this PR with a ton of cmake Projects (mainly KDE stuff) but nearly no qmake one.

**Comment by Johnnynator** [comment]
Mh... with this config qmake still uses the the host .pri files which have the full path to non qt libs hardcoded. Will look into it tomorrow

**Comment by newbluemoon** [comment]
Yes, what I did above just fixes the linking errors.

Do you mean the .pri files in `/usr/lib/qt5/mkspecs/modules`? As far as I can see there are

- qt_lib_multimedia_private.pri
- qt_lib_core_private.pri
- qt_lib_widgets_private.pri
- qt_lib_gui_private.pri
- probably a few more

which use `QMAKE_INCDIR_*` with hardcoded paths to some includes. But it’s the same situation as with 5.11 right now.

Maybe it’s possible to override these variables in `qt.conf`, too, and prepend the cross base (like e.g. read all the paths specified in the variable, prepend the cross base, and set the modified paths). However, `qt.conf` might use different variable names. Or just use brute force and `sed` the cross base?

**Comment by Johnnynator** [comment]
Good news, qmake seems to accept `-qtconf` properly so I can add it in the build-style. qtpass seems to be broken and requires patching, need to look into it.

**Comment by Johnnynator** [comment]
This should be ready to get a review now.

**Comment by pullmoll** [comment]
The main problem for now is `arm*` and we cannot actually do much about it.
The other only obvious thing I saw is the commit title for `qtcreator`: `s/cavnas/canvas/` :-)
Everything else seems in good shape. Thanks for doing this tedious job @Johnnynator !

We should try to separate out `qt5-base` from `qt5` later to solve #12964 .

I hope to find some spare time for fixing, if needed, after this PR is merged.
So IMHO just go merge and let's sort out issues later on.
:+1: as soon as the builders look like they are ready for the task.

**Comment by Johnnynator** [comment]
Goodbye build server 🔨

**Pull request merged**
