### PR TITLE
rust: update to 1.31.1.

### PR DESCRIPTION
**Pull request by Cogitri**
[ci skip]

### CODE REVIEW

**Comment by Cogitri** [comment]
I don't think we need to rebuild/change the dists for this

**Comment by Cogitri** [comment]
@q66 Maybe we can add powerpc support here already?

**Comment by q66** [comment]
It would require shipping custom tarballs for bootstrapping x86, so it's better to wait for 1.32, as that will already have the necessary patches. I will submit PPC support for rust once the actual platform support for xbps-src has landed.

**Comment by jnbr** [comment]
affects only RLS (which we don't build) and netbsd.

**Comment by Cogitri** [comment]
That's according to their RELEASE.md, but looking at the commit history reveals more: https://github.com/rust-lang/rust/commits/stable

**Comment by jnbr** [comment]
I see, go on then

**Comment by Cogitri** [comment]
Alright, this seems good to go to me - but we _could_ wait for LLVM 7 which should be mergeable soon-ish. Otherwise we'll have to rebuild Rust again.

**Comment by Cogitri** [comment]
So...is this going to be merged soon?

**Pull request merged**
