### PR TITLE
[RFC] geda: remove -32bit makedepends

### PR DESCRIPTION
**Pull request by abenson**
@pullmoll This doesn't actually seem necessary to build it. This is related to the discussion at #12982 and #12990.

### CODE REVIEW

**Comment by abenson** [comment]
But it also seems that cross-compile is broken now anyway.

**Comment by pullmoll** [comment]
The dependency was used to ensure the `#include <gnu/stubs32.h>` which is included from `shell.c` generated by `guile-snarf` from `shell.x` is available.
I'm working on a fix for cross compiling. Perhaps due to `guile` or due to me regenerating the configure script (`hostmakedepends+=" automake gettext-devel libtool"` and running `./autogen.sh`) we now also need `makedepends+=" libatomic_ops-devel"`.

Still, without `glibc-devel-32bit` the `<gnu/stubs32.h>` is not found and compiling `shell.c` fails.

**Comment by pullmoll** [comment]
This is the output of the failing build:
```
make[3]: Entering directory '/builddir/geda-gaf-1.8.2/libgeda/shell'
CPP="aarch64-linux-gnu-cpp" guile-snarf -o shell.x shell.c -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I. -I../..   -I./../include -I../.. -I/usr/include -I../../intl  -Wall   -pthread -I/usr/aarch64-linux-gnu/usr/include/guile/2.0 -I/usr/aarch64-linux-gnu/usr/include/glib-2.0 -I/usr/aarch64-linux-gnu/usr/lib/glib-2.0/include -pthread -I/usr/aarch64-linux-gnu/usr/include/gdk-pixbuf-2.0 -I/usr/aarch64-linux-gnu/usr/include/libmount -I/usr/aarch64-linux-gnu/usr/include/blkid -I/usr/aarch64-linux-gnu/usr/include/glib-2.0 -I/usr/aarch64-linux-gnu/usr/lib/glib-2.0/include
In file included from /usr/include/features.h:474,
                 from /usr/include/unistd.h:25,
                 from shell.c:28:
/usr/include/gnu/stubs.h:7:11: fatal error: gnu/stubs-32.h: No such file or directory
    7 | # include <gnu/stubs-32.h>
      |           ^~~~~~~~~~~~~~~~
compilation terminated.
```
Note the most probably wrong `-I/usr/include` in the `CPPFLAGS` passed to `guile-snarf` for a cross compile.
Perhaps we need a build wrapper for `guile-snarf` to replace `/usr` with `${XBPS_CROSS_BASE}/usr`.

**Comment by abenson** [comment]
I can't find that error in either Travis or when I build it myself?

**Comment by pullmoll** [comment]
It's an output of my modified template:
```
# Template file for 'geda'
pkgname=geda
version=1.8.2
revision=7
wrksrc="${pkgname}-gaf-${version}"
build_style=gnu-configure
hostmakedepends="automake desktop-file-utils gettext-devel guile
libtool pkg-config shared-mime-info"
makedepends="gc-devel gtk+-devel guile-devel libatomic_ops-devel"
depends="guile geda-data"
checkdepends="perl"
short_desc="Electronic Design Automation tool"
maintainer="Jürgen Buchmüller <pullmoll@t-online.de>"
license="GPL-2.0-or-later"
homepage="http://www.geda-project.org/"
distfiles="http://ftp.geda-project.org/geda-gaf/stable/v${version%.*}/${version}/geda-gaf-${version}.tar.gz"
checksum=bbf4773aef1b5a51a8d6f4c3fa288c047340cc62dd6e14d7928fcc6e4051b721

pre_configure() {
        vsed -i libgeda/shell/Makefile.am -e "s;\$(snarf_cpp_opts);\$(subst I/usr/include,I${XBPS_CROSS_BASE
}/usr/include,\$(snarf_cpp_opts));"
        NOCONFIGURE=1 ./autogen.sh
}

geda-devel_package() {
        depends="${makedepends} ${sourcepkg}>=${version}_${revision}"
        short_desc+=" - development files"
        pkg_install() {
                vmove "usr/lib/*.so"
                vmove usr/lib/pkgconfig
                vmove usr/include
        }
}
geda-doc_package() {
        archs=noarch
        depends="${sourcepkg}>=${version}_${revision}"
        short_desc+=" - documentation and exmaple files"
        pkg_install() {
                vmove usr/share/doc
        }
}
geda-data_package() {
        archs=noarch
        short_desc+=" - data files"
        pkg_install() {
                vmove usr/share/gEDA
        }
}
```
I can't find the `create new gist` link and am lazy, sorry.

**Comment by pullmoll** [comment]
This is solved for now with the update by creating a dummy `${wrksrc}/gnu/stubs-32.h` empty file.

**Pull request closed without merging**
