### PR TITLE
mu: update to 1.4

### PR DESCRIPTION
**Pull request by emacsomancer**

### CODE REVIEW

**Comment by sgn** [comment]
`xbps-src check` segfault.

**Comment by emacsomancer** [comment]
> `xbps-src check` segfault.

This is odd, because while

`xbps-src check` does produce one failure:
```

make[1]: Entering directory '/builddir/mu-1.4/lib'
make  check-recursive
make[2]: Entering directory '/builddir/mu-1.4/lib'
Making check in utils
make[3]: Entering directory '/builddir/mu-1.4/lib/utils'
make  check-TESTS
make[3]: Leaving directory '/builddir/mu-1.4/lib/utils'
make[2]: Leaving directory '/builddir/mu-1.4/lib'
make[1]: Leaving directory '/builddir/mu-1.4/lib'
Making check in m4
make[1]: Entering directory '/builddir/mu-1.4/m4'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/builddir/mu-1.4/m4'
Making check in man
make[1]: Entering directory '/builddir/mu-1.4/man'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/builddir/mu-1.4/man'
Making check in lib
make[1]: Entering directory '/builddir/mu-1.4/lib'
make  check-recursive
make[2]: Entering directory '/builddir/mu-1.4/lib'
Making check in utils
make[3]: Entering directory '/builddir/mu-1.4/lib/utils'
make  check-TESTS
make[4]: Entering directory '/builddir/mu-1.4/lib/utils'
make[5]: Entering directory '/builddir/mu-1.4/lib/utils'
PASS: test-mu-util
../../build-aux/test-driver: line 107: 20588 Aborted                 "$@" > $log_file 2>&1
FAIL: test-mu-utils
PASS: test-mu-str
PASS: test-sexp-parser
lsPASS: test-command-parser
============================================================================
Testsuite summary for mu 1.4
============================================================================
# TOTAL: 5
# PASS:  4
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
```

Building it by hand on Void and running `make check` passes everything:

```
....
make[5]: Entering directory '/home/slade/Documents/sourcecode/mu/lib/utils'
PASS: test-mu-util
PASS: test-mu-utils
PASS: test-mu-str
PASS: test-sexp-parser
PASS: test-command-parser
============================================================================
Testsuite summary for mu 1.4
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
...
```

The package itself seems to work fine as far as I can tell - I've been using it extensively since yesterday.  Maybe related to https://github.com/djcb/mu/issues/1187 ?

**Comment by sgn** [comment]
It's caused by missing of `tzdata`,

This diff can fix it.
Please check if this is correct.

```diff
diff --git a/srcpkgs/mu/template b/srcpkgs/mu/template
index 51f733e03c..fa04f9d6d3 100644
--- a/srcpkgs/mu/template
+++ b/srcpkgs/mu/template
@@ -3,8 +3,9 @@ pkgname=mu
 version=1.4.1
 revision=1
 build_style=gnu-configure
-hostmakedepends="automake libtool pkg-config emacs texinfo"
+hostmakedepends="automake libtool pkg-config emacs texinfo glib-devel"
 makedepends="xapian-core-devel gmime3-devel libuuid-devel"
+checkdepends="tzdata"
 short_desc="Emacs-based tool for dealing with e-mail stored in the Maildir-format"
 maintainer="Benjamin Slade <slade@jnanam.net>"
 license="GPL-3.0-or-later"
```

**Comment by sgn** [comment]
Here is my final diff on top of your change,
this will enable cross-build for mu and fix the check,
I think you're the maintainer of this package, if it's ok to you,
I'll push this version out.

```diff
diff --git a/srcpkgs/mu/template b/srcpkgs/mu/template
index 51f733e03c..bbe37e1138 100644
--- a/srcpkgs/mu/template
+++ b/srcpkgs/mu/template
@@ -3,8 +3,9 @@ pkgname=mu
 version=1.4.1
 revision=1
 build_style=gnu-configure
-hostmakedepends="automake libtool pkg-config emacs texinfo"
+hostmakedepends="automake libtool pkg-config texinfo glib-devel"
 makedepends="xapian-core-devel gmime3-devel libuuid-devel"
+checkdepends="tzdata"
 short_desc="Emacs-based tool for dealing with e-mail stored in the Maildir-format"
 maintainer="Benjamin Slade <slade@jnanam.net>"
 license="GPL-3.0-or-later"
@@ -12,12 +13,23 @@ homepage="https://www.djcbsoftware.nl/code/mu/"
 distfiles="https://github.com/djcb/mu/archive/${version}.tar.gz"
 checksum=66ae911abb3d7269514fada08e7a13ad61a205e10209055c41df2f9d17568274
 
+if [ ! "$CROSS_BUILD" ]; then
+	subpackages="mu4e"
+	hostmakedepends+=" emacs"
+else
+	# force subpackages to non-empty value,
+	# else xbps-src will generate it.
+	subpackages=" "
+	configure_args+=" --disable-mu4e"
+fi
+
 pre_configure() {
 	sed -i 's,-I${prefix}/include,,' contrib/Makefile.am
 	autoreconf -fi
 }
 
 mu4e_package() {
+	archs=noarch
 	short_desc+=" - Emacs frontend"
 	depends="${sourcepkg}>=${version}_${revision} emacs"
 	pkg_install() {
```

**Comment by emacsomancer** [comment]
@sgn Yes, I think this looks ready to push.

**Pull request closed without merging**
