### PR TITLE
qView: update to 5.0

### PR DESCRIPTION
**Pull request by mustaqimM**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by newbluemoon** [comment]
I haven't updated qView, because I found a little bug which I didn't have the time to investigate, yet: when toggling through a list of pictures (just keep the right or left arrow key pressed) it crashes.
I guess this isn't a show stopper, but it's worth mentioning and not the case with 4.0.

**Comment by mustaqimM** [comment]
@newbluemoon Oh, I see. What do you mean by toggling though? Scrolling next through images? Because I can't reproduce that

**Comment by newbluemoon** [comment]
I mean when I view a picture and there are more pictures in the directory in which the current picture resides I can move to the next or previous one with the arrow keys. When I keep changing to the next, to the next, etc. picture a crash occurs after a while (sooner when you keep the arrow key pressed).

**Comment by notramo** [comment]
@newbluemoon 4.0 is segfaulting on `musl`. I think it should be updated to 5.0. It's better when crashing due to unusual usage than not being able to use it at all.

**Comment by newbluemoon** [comment]
@notramo Did you test 5.0 on musl and verify that the segfault is gone?
I have no objections to updating qView to 5.0, just stated what I found. But it's not in my power to merge this PR ;)

**Comment by notramo** [comment]
5.0 works on musl.

**Comment by notramo** [comment]
Also, I can't reproduce the quick navigating bug (keeping the arrow keys pressed) bug on musl with small and medium (15-20 megapixels) images.

**Comment by notramo** [comment]
I used 4.0 on musl with Wayland (Sway). But I can't test if 4.0 crashes on Xorg too as I have 5.0 installed now.

**Pull request closed without merging**
