### PR TITLE
docker: cross-compile, manual build

### PR DESCRIPTION
**Pull request by sgn**
Their build script attempt to fetch pre-build binary on certain
platform. Build them ourselves.

---
Fix: #18062

### CODE REVIEW

**Comment by jsumners** [comment]
I can confirm that this PR works. I pulled down this fork and did the following on an x86_64 system without error:

```sh
$ ./xbps-src binary-bootstrap
$ ./xbps-src -a aarch64 pkg docker
```

I copied the resulting package over to my Raspberry Pi 4, installed it, and it runs without issue.

**Comment by Anachron** [comment]
Sorry for hijacking, but since you mentioned Void on a RPI 4: How did you do it? Does the kernel for RPI 3 work for 4 as well? Or did you build a template and compile it yourself?

**Comment by jsumners** [comment]
@Anachron https://jrfom.com/posts/2020/08/30/first-rpi-project/#building-a-void-linux-image

**Comment by sgn** [comment]
Look like I can merge this now and take blame for the rest of this month :-p

**Pull request merged**
