### PR TITLE
xbps-src: depuplicate output of setup_pkg_depends

### PR DESCRIPTION
**Pull request by Chocimier**
Issue #21044 raised problem of setup_pkg_depends returning duplicate results after depends of subpackages were included. Specifically, problem was performance and triggering failures of xbps-fbulk.

I was unable to reproduce fbulk's misbehavior, as show_pkg_build_depends deduplicates its output. Yet I don't see reason for listing duplicates here.

Please merge if you find it good.

### CODE REVIEW

**Comment by the-maldridge** [comment]
@Duncaen I am satisfied with this PR, but I would like you to take a look as well.

**Comment by ericonr** [comment]
Ping @Duncaen

**Comment by ericonr** [comment]
Ping

**Comment by ericonr** [comment]
@Chocimier would you like to try merging this?

**Comment by Chocimier** [comment]
Either way is good enough, feel free to merge if you find this useful.

**Pull request closed without merging**
