### PR TITLE
qemu(-user-static): update to 7.1.0.

### PR DESCRIPTION
**Pull request by unspecd**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-musl)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - ppc64le-musl

### Changes
- `configure_args`:
   - https://github.com/qemu/qemu/commit/95f8510ef428f988897176b9585b8ba1432f939f
- `makedepends`:
   - https://github.com/qemu/qemu/commit/83602083b4ada6ceb86bfb327e83556ebab120fc
- fix-compat-glibc-2.36.patch:
   - https://github.com/qemu/qemu/commit/3cd3df2a9584e6f753bb62a0028bd67124ab5532
-  xxx-ppcle.patch:
   - https://github.com/qemu/qemu/commit/cd362defbbd09cbbc08b3bb465141542887b8cef
   - https://github.com/qemu/qemu/commit/ee3eb3a7ce7242735e6fd64cad53482e3df5a5ec

https://wiki.qemu.org/ChangeLog/7.1

### CODE REVIEW

**Comment by unspecd** [comment]
Rebased.

**Comment by dataCobra** [comment]
Hey @unspecd, could you force push this commit again? So we could check if the failed check might be gone?

In the meantime I'll try this PR on my machine. :+1:

**Comment by dataCobra** [comment]
I've tested this PR successfull on x86_64. :+1:

**Comment by unspecd** [comment]
Thanks for testing!

**Pull request merged**
