### PR TITLE
Fix several templates to use HTTPS

### PR DESCRIPTION
**Pull request by sineemore**
Relevant issue: https://github.com/void-linux/void-packages/issues/4943

### CODE REVIEW

**Comment by maxice8** [comment]
homepage changes affect the metadata in the package, bump those

**Comment by Vaelatern** [comment]
I am opposed to this commit.
1) Doesn't use our style guide for commit messages.
2) Doesn't break into many commits.
3) Has something that should be fixed by style checkers.
4) `http` is not a bug, even if it isn't quite as good as `https`.

**Comment by sineemore** [comment]
Revision bumped

**Comment by sineemore** [comment]
Alright, so, the proper way to do this is on per package bases. Anyway, is it even worth doing this, or should it be fixed in the style checker?

**Pull request closed without merging**
