### PR TITLE
New package: yp-tools-4.2.3

### PR DESCRIPTION
**Pull request by ailiop-git**

### CODE REVIEW

**Comment by xtraeme** [comment]
why do you need this? YP has been obsolete for a long while...

**Comment by ailiop-git** [comment]
> why do you need this? YP has been obsolete for a long while...

indeed, but there are certain internal networks that still leverage it instead of ldap for simplicity (e.g. for nfs automount maps), and it's nice to be able to do ypcat to dump the NIS databases. Both yp-tools and ypbind are still maintained so I thought I'd give it a shot, but I'd still need to fix musl compilation.

**Comment by xtraeme** [comment]
Fair enough, note that musl does not support NIS/YP so that you can restrict it to `glibc`.

**Comment by ailiop-git** [comment]
> Fair enough, note that musl does not support NIS/YP so that you can restrict it to `glibc`.

thanks, done, I've also similarly pushed the associated ypbind daemon that is required for syncing the nis db (#19708).

**Pull request closed without merging**
