### PR TITLE
dhcpcd: update to 9.2.0.

### PR DESCRIPTION
**Pull request by CameronNemo**
Working alright for me so far! @sgn

### CODE REVIEW

**Comment by sgn** [comment]
On 2020-09-07 07:54:18-0700, Cameron Nemo <notifications@github.com> wrote:
> Working alright for me so far!

Work for me for 1 and a half days.
Including:
- Connect disconnect with runit service run by old version
- Restart to run new version
- All with wireless only

**Comment by sgn** [comment]
On 2020-09-07 07:54:18-0700, Cameron Nemo <notifications@github.com> wrote:
> Working alright for me so far!

Anyway, you can take over maintainership,
I don't have enough machine to test properly.

I saw you're active on dhcpcd's ml, too.

**Comment by CameronNemo** [comment]
Alright, I adopted the package. I am only able to test on a few devices anyway: x86_64 laptop (wifi and wired), aarch64 laptop (wifi only), aarch64-musl SBC (wired only). Works fine on all of them.

**Comment by sgn** [comment]
Working good so far, merging. Thanks.

**Pull request merged**
