### PR TITLE
mesa: update to 20.1.2

### PR DESCRIPTION
**Pull request by st3r4g**
Tested on sway and xorg with Intel drivers

### CODE REVIEW

**Comment by travankor** [comment]
Is there a reason why Void has the dri files located in `/usr/lib/xorg/modules/drivers` as opposed to `/usr/lib/dri`?

**Comment by st3r4g** [comment]
I was wondering the same, but I've never really investigated. Indeed `/usr/lib/dri` is now the [upstream default](https://gitlab.freedesktop.org/mesa/mesa/-/blob/master/meson_options.txt) and makes sense because the drivers are not xorg-specific anymore. Maybe it's an artifact of the past?

I'd be interested to test this change and see if other templates would have to be modified

**Comment by st3r4g** [comment]
Trying https://gist.github.com/st3r4g/8d6057deb49e54aa5ab92df68ee24e81, works here.

**Comment by q66** [comment]
i don't think anything else uses the path, it's mostly internal to mesa, and to xorg... maybe the xorg ddx drivers will need rebuilding

**Comment by st3r4g** [comment]
Yeah, I asked on `#dri-devel` and they're not aware of anything else that uses it other than xorg... xorg needs it because it has its custom dri loader (for legacy reasons probably). I don't think it changes anything for the DDXs but haven't test yet

**Comment by q66** [comment]
here is fine

**Pull request merged**
