### PR TITLE
bubblewrap: update to 0.5.0.

### PR DESCRIPTION
**Pull request by UsernameRandomlyGenerated**
Musl problem seems to be resolved, tested flatpak steam, runs fine.

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by NoEiBk3** [comment]
bump

**Comment by UsernameRandomlyGenerated** [comment]
Sorry for the delay, I was away for a long time, I'll make PR with patches on the weekend.

**Comment by UsernameRandomlyGenerated** [comment]
@ericonr ping

**Comment by UsernameRandomlyGenerated** [comment]
No idea what that builder is trying to do.

**Comment by paper42** [comment]
> No idea what that builder is trying to do.

on x86_64-musl, it's trying to check if all packages depending on musl can still be installed.

Could you change the homepage of musl to https://musl.libc.org/?

**Comment by UsernameRandomlyGenerated** [comment]
Done, is it okay for it to be in the same commit as musl patches or should I split?

**Comment by q66** [comment]
same commit as the other musl change please

**Pull request closed without merging**
