### PR TITLE
arcan: Add option for hybrid sdl

### PR DESCRIPTION
**Pull request by Gorggg**
This change allows the arcan_sdl binary to be built with a build option, which in turn allows the running of arcan nested within a different display server.

Thank you for looking at this.

Signed-off-by: George Matsumura <gmmatsumura01@bvsd.org>

#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
@Gorggg what do you think about always building `arcan_sdl` but moving it to a subpackage instead?

**Comment by Gorggg** [comment]
@ericonr Sorry for taking to so long to reply.

That seems like a good idea. I have updated the changes to instead create a subpackage. Please let me know if I made any mistakes.

**Comment by ericonr** [comment]
@Gorggg please fix the commit message to reflect reality as well ;)

**Comment by Gorggg** [comment]
@ericonr Ah, sorry about that. It should be fixed now.

**Comment by ericonr** [comment]
The commit body is still wrong :p There's no build option.

I can fix before commiting.

**Comment by Gorggg** [comment]
@ericonr I apologize again. Thank you for your patience.

**Comment by ericonr** [comment]
No worries ;)

**Pull request merged**
