### PR TITLE
 lutris: update to 0.5.8.4.

### PR DESCRIPTION
**Pull request by ThatGeekyWeeb**
#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by paper42** [comment]
@ThatGeekyWeeb the PR was fine, why did you close it?

**Comment by ThatGeekyWeeb** [comment]
I didn't also, it somehow ended up with 5000 files changed??, something broke, idk why

@paper42

**Comment by ThatGeekyWeeb** [comment]
I'll open a new pr and hopefully do it properly this time

**Comment by ThatGeekyWeeb** [comment]
lets try this again @ #32078

**Pull request closed without merging**
