### PR TITLE
metalog: update to 20230707

### PR DESCRIPTION
**Pull request by jovanlanik**
#### Testing the changes
- I tested the changes in this PR: **YES**

Updated and added changelog as asked in #35617 (seems it was only recently changed again)

@teldra Would it also possible be for me to adopt metalog as maintainer? I am a contributor and user of the program so I follow development closely...

### CODE REVIEW

**Comment by jovanlanik** [comment]
Upon further testing it stopped my system from booting...

**Comment by jovanlanik** [comment]
Might have something to do with #42026...

**Comment by jovanlanik** [comment]
Seems like metalog with the `-v` flag outputs all logs to stdout and stdout is logged back to metalog, the message continues getting logged again and again...
```
Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 16:25:06 [metalog] Jul 07 15:47:49 [sudo] pam_unix(sudo:session): session opened for user root(uid=0) by (
```
I can think of a couple of solutions but the most similar result to current package is deleting the log directory :
```
post_install() {
	vsv metalog
	rm -rf "${DESTDIR}/etc/sv/metalog/log"
}
```

@classabbyamp Maybe the `vsv` function could have a flag to opt-out of logging?

@teldra What do you think?

**Comment by classabbyamp** [comment]
i think rm after vsv is a fine way to do it

**Comment by jovanlanik** [comment]
No problems after deleting the log directory.

**Comment by sgn** [comment]
Should we remove `-v` instead?

**Pull request merged**
