### PR TITLE
metalog: fix bleeding logs onto tty1

### PR DESCRIPTION
**Pull request by shahab-vahedi**
This fixes issue #45653 [1].

[1]
https://github.com/void-linux/void-packages/issues/45653

#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture: x86_64-glibc

### CODE REVIEW

**Comment by aryandb** [comment]
I think running it az deamon should fix the tty problem. Just add `-B` option.

**Comment by Duncaen** [comment]
> I think running it as deamon should fix the tty problem. Just add `-B` option.

No runit services are required to run in the foreground.


Just removing this line is probably not the right solution, output redirected to `stdout` will be written to the commandline of the `runsvdir` process as fallback logging mechanism.

This fallback mechanism shouldn't be used as general logging target where everything is logged to, its already bad user experience, but duplicating all syslog messages into it just makes it even more useless.

**Comment by shahab-vahedi** [comment]
I agree with your points @Duncaen . There are a few things to note here:

1. Currently, both `exec 2>&1` and `exec 1>&2` exist in the `run` script.
2. There is a default `-v` passed to the program, which I think is unnecessary. The maintainer [thinks](https://github.com/void-linux/void-packages/issues/45653#issuecomment-1683718365) the same.
3. The `log` part of this daemon is [removed](https://github.com/void-linux/void-packages/blob/master/srcpkgs/metalog/template#L26).

If you help me in the right direction, I want to address them all.

Should I put back the `exec 2>&1` and remove `exec 1>&2`, while replacing `-v` with `-B` as the default parameter as @aryandb [suggested](https://github.com/void-linux/void-packages/pull/45700#issuecomment-1686563601)? Should I put the logging part back in? As it is, it does stop a user from logging into the system.

**Comment by Duncaen** [comment]
Seems like the solution is to discard `stdout` where metalog prints every log line it receives https://github.com/hvisage/metalog/blob/bb7c007cbc0815fd08e9259b26dcef26020217d0/src/metalog.c#L1412.

And to keep the error messges from `err(3)`, either keep stderr open and leave it there so the error messages end up in the fallback mechanism, or redirect them to stdout which makes them end up in `/dev/console` without having a log service.

```
#!/bin/sh
[ -r conf ] && . ./conf
exec metalog ${OPTS} >/dev/null
```

**Comment by shahab-vahedi** [comment]
I've tried this and everything seems to work fine, I even put back the `log` facility.

```
#!/bin/sh
exec 2>&1
[ -r conf ] && . ./conf
exec metalog ${OPTS=-B}
```

If you agree, I'll push my latest changes.

**Comment by Duncaen** [comment]
Do not bring back the log service it makes no sense, if `metalog` writes error messages, then there is probably a bigger issue, sending them back to metalog most likely doesn't work.

**Comment by aryandb** [comment]
> `-B` is completely wrong, do not use `-B` at all.

@shahab-vahedi 
Yes it's true. i was completely wrong and sorry for confusion. If you add `-B` runit just keep spawning `metalog`. do not add that.

**Comment by shahab-vahedi** [comment]
OK @Duncaen I practically took your changes.

**Comment by shahab-vahedi** [comment]
Ping.

**Comment by shahab-vahedi** [comment]
Ping.

**Pull request merged**
