### PR TITLE
firefox-esr: update to 68.9.0

### PR DESCRIPTION
**Pull request by mmnmnnmnmm**

### CODE REVIEW

**Comment by jnbr** [comment]
Have you tried building it? If so, for which architectures?
I expect that you also need `musl-rust.configure.patch` from the firefox patches for armv7l-musl.

**Comment by mmnmnnmnmm** [comment]
> Have you tried building it? If so, for which architectures?
Only x86_64 glibc I'm afraid, don't have access to any other arches.

> I expect that you also need musl-rust.configure.patch from the firefox patches for armv7l-musl.
I pull that in if anyone with armv7l-musl can test it.

**Comment by jnbr** [comment]
All our build servers run on x86 hardware, xbps-src has support for cross compiling for other architectures.

You can test if it builds for armv7l-musl with:

```
./xbps-src -m masterdir-musl
./xbps-src -m masterdir-musl -a armv7l-musl pkg firefox
```

**Comment by mmnmnnmnmm** [comment]
Ah thanks, for some reason I didn't think you could cross-compile firefox.

I'll test the other arches and see if that patch is needed.

**Comment by mmnmnnmnmm** [comment]
I've tested armv7l-musl and it needed the patch to build.  I realise now that firefox-esr shares some of the same patches as thunderbird.

**Comment by fosslinux** [comment]
Yeah, that is because thunderbird is based on firefox-esr :D

**Pull request merged**
