### PR TITLE
s6*: updating the whole stack of packages.

### PR DESCRIPTION
**Pull request by dataCobra**
#### Testing the changes
- I tested the changes in this PR: **Not yet**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - x86_64-musl
  - i686

Setting up an update of all packages s6 related.

### CODE REVIEW

**Comment by dataCobra** [comment]
Since `66` has not stable release yet available for the the current version of s6, I've decided to go with the preprod for testing the build.

**Comment by dataCobra** [comment]
There are only conflicts with a few other packages:
```
66 and runit-void conflict for
  /usr/bin/init
66-doc and erlang conflict for
  /usr/share/man/man1/start.1
66-doc and tree conflict for
  /usr/share/man/man1/tree.1
Error: Process completed with exit code 1.
```

Would like to have some feedback if void team members how we want to go about that.

**Comment by mobinmob** [comment]
> There are only conflicts with a few other packages:
> 
> ```
> 66 and runit-void conflict for
>   /usr/bin/init
> 66-doc and erlang conflict for
>   /usr/share/man/man1/start.1
> 66-doc and tree conflict for
>   /usr/share/man/man1/tree.1
> Error: Process completed with exit code 1.
> ```

I believe that every single one of them should be renamed. The init should also be altered, it will not work ootb - you can also move it to the skel dir, it is a bug to have under /usr/bin by default. I will report it upstream.
I plan to add these to my PR, I hope we can collaborate...

**Comment by mobinmob** [comment]
You can add the following to post_install() to fix the file conflicts:
```
       mv "${DESTDIR}"/usr/bin/init "${DESTDIR}"/etc/66/init
       mv "${DESTDIR}"/usr/share/man/man1/start.1 \
	 "${DESTDIR}"/usr/share/man/man1/66_start.1
	mv "${DESTDIR}"/usr/share/man/man1/tree.1 \
	 "${DESTDIR}"/usr/share/man/man1/66_tree.1
```
The manpages can be all renamed to `66_$manpage` or `66-$manpage`.

**Comment by dataCobra** [comment]
Still missing some of the man-pages provided by flexibeast.

Also it looks like some man-pages are not provided for the current version.

**Comment by dataCobra** [comment]
Another thing that bugs me a little bit is that a some package templates are not really following the same structure as the majority.

So a refactoring needs to be done too. This is especially important with this amount of packages that have a relation to another.

**Comment by dataCobra** [comment]
Today the **66** stable release 0.7.0.0 was released. :tada: 

I took the time not only to update package `66`, but also to add/update the missing packages and generalize all related packages for readability.

The next step should be the test of the packages.

Afterward we can go forward to work on and build PR #45578

**Comment by mobinmob** [comment]
> Today the **66** stable release 0.7.0.0 was released. 🎉
> 
> I took the time not only to update package `66`, but also to add/update the missing packages and generalize all related packages for readability.
> 
> The next step should be the test of the packages.
> 
> Afterward we can go forward to work on and build PR #45578

For anyone who wants  to help (outside of @dataCobra who is aware of this):
The work for PR #45578 is happening on:

1. the [void-66-services gh repo](https://github.com/mobinmob/void-66-services) (services and doc) 
2. the 66[-voidlinux repo on codeberg](https://codeberg.org/mobinmob/66-voidlinux) (templates and helper scripts) and 
3. my fork of boot-66serv repo for adjusting the upstream to voidlinux - [voidlinux-dev branch.](https://git.obarun.org/mobinmob/boot-66serv/-/commits/voidlinux-dev)

PRs/MRs are welcome.

**Comment by leahneukirchen** [comment]
Any interest in getting this updated and merged? I'd like to have new s6 tools...

**Pull request closed without merging**
