### PR TITLE
New packages: {edk2,ovmf-*}-202102

### PR DESCRIPTION
**Pull request by Logarithmus**
Continues https://github.com/void-linux/void-packages/pull/17225
Closes https://github.com/void-linux/void-packages/issues/11243, https://github.com/void-linux/void-packages/issues/27229

#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

#### Does it build and run successfully? 
- [x] I built this PR locally for my native architecture, (x86_64-musl)
- [ ] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [ ] x86_64
  - [x] x86_64-musl
  - [ ] i686

### CODE REVIEW

**Comment by ericonr** [comment]
Please clean up your commit, you have `.rej` and `.orig` files.

**Comment by Xlaits** [comment]
Getting errors attempting to build ovmf-*
```
=> ca-certificates-20210119_1: running pre-pkg hook: 90-set-timestamps ...
date: invalid date ‘@1616622037\n1616622037’
=> ERROR: ca-certificates-20210119_1: pre-pkg_90-set-timestamps: 'date --date "@$SOURCE_DATE_EPOCH"' exited with 1
=> ERROR:   in hook() at common/hooks/pre-pkg/90-set-timestamps.sh:7
=> ERROR:   in run_func() at common/xbps-src/shutils/common.sh:21
=> ERROR:   in run_pkg_hooks() at common/xbps-src/shutils/common.sh:245
=> ERROR:   in main() at common/xbps-src/libexec/xbps-src-prepkg.sh:47
=> ca-certificates-20210119_1: setting mtimes to 
touch: invalid date format ‘@1616622037\n1616622037’
=> ERROR: ca-certificates-20210119_1: pre-pkg_90-set-timestamps: 'xargs -0 touch -h --date "@$SOURCE_DATE_EPOCH"' exited with 123
=> ERROR:   in hook() at common/hooks/pre-pkg/90-set-timestamps.sh:8
=> ERROR:   in run_func() at common/xbps-src/shutils/common.sh:21
=> ERROR:   in run_pkg_hooks() at common/xbps-src/shutils/common.sh:245
=> ERROR:   in main() at common/xbps-src/libexec/xbps-src-prepkg.sh:47

```

**Comment by Logarithmus** [comment]
> Getting errors attempting to build ovmf-*
> 
> ```
> => ca-certificates-20210119_1: running pre-pkg hook: 90-set-timestamps ...
> date: invalid date ‘@1616622037\n1616622037’
> => ERROR: ca-certificates-20210119_1: pre-pkg_90-set-timestamps: 'date --date "@$SOURCE_DATE_EPOCH"' exited with 1
> => ERROR:   in hook() at common/hooks/pre-pkg/90-set-timestamps.sh:7
> => ERROR:   in run_func() at common/xbps-src/shutils/common.sh:21
> => ERROR:   in run_pkg_hooks() at common/xbps-src/shutils/common.sh:245
> => ERROR:   in main() at common/xbps-src/libexec/xbps-src-prepkg.sh:47
> => ca-certificates-20210119_1: setting mtimes to 
> touch: invalid date format ‘@1616622037\n1616622037’
> => ERROR: ca-certificates-20210119_1: pre-pkg_90-set-timestamps: 'xargs -0 touch -h --date "@$SOURCE_DATE_EPOCH"' exited with 123
> => ERROR:   in hook() at common/hooks/pre-pkg/90-set-timestamps.sh:8
> => ERROR:   in run_func() at common/xbps-src/shutils/common.sh:21
> => ERROR:   in run_pkg_hooks() at common/xbps-src/shutils/common.sh:245
> => ERROR:   in main() at common/xbps-src/libexec/xbps-src-prepkg.sh:47
> ```

Please, check now

**Comment by Logarithmus** [comment]
CI passed, tested on x86_64-musl, works fine. Ready for review & merge I think.

**Comment by Xlaits** [comment]
Still having the same issue.

**Comment by Logarithmus** [comment]
> Still having the same issue.

Maybe the issue is your date? Check if it's correct. The package have built successfully both on my laptop and CI/CD.

**Comment by Xlaits** [comment]
Date and time are correct.

**Comment by noarchwastaken** [comment]
The packages built with no problems for me on x86_64-glibc.

**Comment by noarchwastaken** [comment]
I noticed that the VM starts up to a black screen if I have OpenGL enabled for Spice... the VM only starts to display when the OS has booted to a certain point. I'm not sure if it's an upstream issue though.

**Comment by eoli3n** [comment]
up

**Comment by eoli3n** [comment]
> The packages built with no problems for me on x86_64-glibc.

Same here, i will test later.

**Comment by NeonOverflow** [comment]
Please merge this!

**Comment by eoli3n** [comment]
ping @ericonr

**Comment by NeonOverflow** [comment]
@ericonr

**Comment by ericonr** [comment]
I only made a lint comment, and haven't claimed this PR. It's a big package that I'm not in a position to review rn.

**Comment by ahesford** [comment]
I really don't see this being merged without massive upstream work. The template is a jumble of manual steps and questionable vendoring (brotli? openssl???). I suspect the only truly valuable part of this package is the half-dozen firmware blobs and associated JSON descriptors, all of which I just manually unpack from an Arch Linux package and be on my way.

**Comment by ericonr** [comment]
I don't want to involve myself, but from https://github.com/tianocore/edk2/blob/master/CryptoPkg/Library/OpensslLib/OpenSSL-HOWTO.txt it would seem at least openssl is used to provide crypto stuff and it would have to be compiled specially for that, which is why they pull it in.

**Comment by NeonOverflow** [comment]
@ahesford The firmware files are primarily used by GPU passthrough users.

**Comment by ahesford** [comment]
I understand the utility of the firmware files; I use them in all of my VMs. My point is that the template requires a lot of manual effort because the EDK build system isn't sane, and these steps are likely to break from one release to the next. Void is a small team and fragile templates that require a lot of manual work become disproportionate time sinks.

In the meantime, the firmware blobs can be manually extracted from packages of other distributions and used in Qemu/KVM installations in Void with minimal effort.

**Comment by NeonOverflow** [comment]
Understandable. I'll probably just do as you said in the meantime.

**Comment by eoli3n** [comment]
> I understand the utility of the firmware files; I use them in all of my VMs. My point is that the template requires a lot of manual effort because the EDK build system isn't sane, and these steps are likely to break from one release to the next. Void is a small team and fragile templates that require a lot of manual work become disproportionate time sinks.
> 
> In the meantime, the firmware blobs can be manually extracted from packages of other distributions and used in Qemu/KVM installations in Void with minimal effort.

So why not pulling this in the package ?

**Comment by HadetTheUndying** [comment]
> > In the meantime, the firmware blobs can be manually extracted from packages of other distributions and used in Qemu/KVM installations in Void with minimal effort.
> 
> So why not pulling this in the package ?

I would be under the assumption that this is against the package quality requirements since this package would not fall under the `nonfree` packages, it's just a pain to package.

**Comment by Matthew-Tate-Scarbrough** [comment]
> In the meantime, the firmware blobs can be manually extracted from packages of other distributions and used in Qemu/KVM installations in Void with minimal effort.

Would it be a advantageous/within scope of void-packages to just write a script that just steals them from Arch or another popular distro's repos?

**Comment by wael444** [comment]
uh? when?

**Comment by HadetTheUndying** [comment]
> uh? when?

The `qemu` package includes the following:
````
qemu-6.1.0_3	/usr/share/qemu/edk2-aarch64-code.fd
qemu-6.1.0_3	/usr/share/qemu/edk2-arm-code.fd
qemu-6.1.0_3	/usr/share/qemu/edk2-arm-vars.fd
qemu-6.1.0_3	/usr/share/qemu/edk2-i386-code.fd
qemu-6.1.0_3	/usr/share/qemu/edk2-i386-secure-code.fd
qemu-6.1.0_3	/usr/share/qemu/edk2-i386-vars.fd
qemu-6.1.0_3	/usr/share/qemu/edk2-licenses.txt
qemu-6.1.0_3	/usr/share/qemu/edk2-x86_64-code.fd
qemu-6.1.0_3	/usr/share/qemu/edk2-x86_64-secure-code.fd
qemu-6.1.0_3	/usr/share/qemu/firmware/50-edk2-i386-secure.json
qemu-6.1.0_3	/usr/share/qemu/firmware/50-edk2-x86_64-secure.json
qemu-6.1.0_3	/usr/share/qemu/firmware/60-edk2-aarch64.json
qemu-6.1.0_3	/usr/share/qemu/firmware/60-edk2-arm.json
qemu-6.1.0_3	/usr/share/qemu/firmware/60-edk2-i386.json
qemu-6.1.0_3	/usr/share/qemu/firmware/60-edk2-x86_64.json
```

I have tested the x86_64 firmware with GPU passthrough to a Windows VM and can confirm it works.

**Comment by ahesford** [comment]
Because it seems that qemu already ships viable EFI image and EDK2 is such a nightmare to build, let's close this and revisit if there is a compelling need and we can construct a more maintainable template.

**Comment by eoli3n** [comment]
I can't find a way to run that firmware with vagrant-libvirt : https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1443

**Comment by junkminerman** [comment]
Has anyone gotten the EFI images shipped with qemu to work for enabling secure boot and creating a Windows 11 VM?

**Pull request closed without merging**
