### PR TITLE
hledger: update to 1.20.4

### PR DESCRIPTION
**Pull request by bitmeise**
@q66, I often have problems updating this package and they are usually resolved by deleting stack.yaml. My knowledge of the Haskell ecosystem is very limited. Is this file still necessary for anything?

### CODE REVIEW

**Comment by q66** [comment]
the file is necessary to set the proper LTS stackage resolver (i.e. yes, it is necessary)

but i'm not a haskell maintainer nor i particularly know the ecosystem so dunno why ask me

**Comment by bitmeise** [comment]
Because git blame says you have been fiddling with almost all lines of the file, I thought you might know what's happening here in more detail.

Anyway, in IRC I was told that it is fine if the package *builds* without specifying a manual stack.yaml -- which it does on all archs according to the checks.

I should also pin an LTS version. According the manual https://github.com/void-linux/void-packages/blob/master/Manual.md#pkgs_haskell this can happen via a stack.yaml which already comes with the upstream sources. 

As all of the above is the case, I consider this task done.

**Comment by slotThe** [comment]
This looks good, although I will note that, at this point, hledger 1.20.3 just got released; in case you want to directly update to that instead

**Comment by bitmeise** [comment]
Yes, I plan to directly jump to 1.20.3 this weekend. Please stay tuned.

**Comment by bitmeise** [comment]
done

**Comment by bitmeise** [comment]
updated again to 1.20.4

**Pull request closed without merging**
