### PR TITLE
adwaita-icon-theme: remove gtk-update-icon-cache makedep

### PR DESCRIPTION
**Pull request by oreo639**
Fix build cycle described in the form of cmake -> qt6 -> gtk+3 -> adwaita-icon-theme -> gtk4 -> ... -> fftw -> cmake

#### Testing the changes
- I tested the changes in this PR: **briefly**

cc: @sgn

### CODE REVIEW

**Comment by classabbyamp** [comment]
I don't think we want more things to rely on gtk2, as it will be removed eventually

**Comment by oreo639** [comment]
Alternatively, fftw can be made to use cmake-bootstrap. (this is what `build_style=cmake` uses)
However, `PATH="$PATH:/usr/libexec/xbps-src/bin"` needs to get explicitly defined.

**Comment by sgn** [comment]
For `build_helper=cmake`, I think we don't need. Just put `/usr/libexec/xbps-src/bin` into the end of `PATH`. if `cmake-bootstrap` is installed, it's picked up from there, if both `cmake` and `cmake-bootstrap` is installed, it will be picked up from `/usr/bin`.

**Comment by oreo639** [comment]
> Just put `/usr/libexec/xbps-src/bin` into the end of `PATH`. if `cmake-bootstrap` is installed

Where would be the right place to check that out of curiosity?

**Comment by sgn** [comment]
No, I meant we should always append `/usr/libexec/xbps-src/bin` into `PATH` regardless of installation of `cmake-bootstrap`

**Comment by oreo639** [comment]
Alright, thanks.

**Pull request closed without merging**
