### PR TITLE
julia: remove

### PR DESCRIPTION
**Pull request by Piraty**
* FTBFS: https://github.com/void-linux/void-packages/issues/34387
* unmaintained: https://github.com/void-linux/void-packages/pull/35270
* blocks libgit2 update

#### Testing the changes
- I tested the changes in this PR: **YES**|**briefly**|**NO**

### CODE REVIEW

**Review by ahesford — APPROVED** [review]
Although it would be nice in an abstract sense to support Julia on Void, it's library dependencies make it exceptionally difficult to package properly and the desire to vendor a lot of things (including LLVM) means the build cost is high even when we do get it right.

People can always grab the precompiled tarballs from the upstream website. If there is sufficient interest among users, we can always consider a `julia-bin` package.

**Comment by Rabioli** [comment]
The official binaries doesn't work on musl last time I checked, it needs to be compiled on the target machine.

**Comment by ahesford** [comment]
Upstream at least offers a prebuilt tarball for musl. If they can't make it work properly, we certainly aren't going to bend over backwards trying to drag it along.

**Comment by paper42** [comment]
The docker image has a variant based on alpine (which uses musl) and they just download their musl build from the release. If it doesn't work for you on Void for some reason, you could try their docker image.

**Comment by BryceVandegrift** [comment]
Instead of a `julia-bin` package why not just use `juliaup`? It's just like rustup (which is also available on Void) and it's provided by Julia. Although I do agree that a having Julia in the package repo and having a musl version of the package would be nice.

**Pull request merged**
