### PR TITLE
[RFC] requires libgcc_s.so.1 when libpthread.so.0 is required

### PR DESCRIPTION
**Pull request by sgn**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by leahneukirchen** [comment]
sgtm, another option would be glibc depending on libgcc?

**Comment by sgn** [comment]
On 2022-03-20 05:08:24-0700, Leah Neukirchen ***@***.***> wrote:
> another option would be glibc depending on libgcc?

It will make a circular dependencies, libgcc depends on glic already.

-- 
Danh

**Comment by q66** [comment]
xbps should handle circular dependencies just fine

**Comment by leahneukirchen** [comment]
I don't see libgcc depending on glibc?

**Comment by q66** [comment]
it depends on it through shlibs

**Comment by sgn** [comment]
> xbps should handle circular dependencies just fine

But, it would be a problem during bootstrap?

**Comment by sgn** [comment]
I will merge this as-is tomorrow if no-one objects.

**Comment by q66** [comment]
i already objected, this shouldn't be needed

make glibc depend on libgcc instead

**Comment by Chocimier** [comment]
> make glibc depend on libgcc instead

Can you be more specific instead of what? Adding `depends="libgcc"` at glibc template will create build-time cycle.

**Comment by q66** [comment]
just special-case it in some hook (for example the same one as this one is modifying), then there is nothing for xbps-src to complain about...

**Comment by ericonr** [comment]
The advantage of adding the dependency to glibc is that we don't need to rebuild so many libraries.

**Pull request closed without merging**
