### PR TITLE
Use https homepages

### PR DESCRIPTION
**Pull request by mhmdanas**

### CODE REVIEW

**Comment by mhmdanas** [comment]
@r-ricci fair point, should I close this PR?

**Comment by motorto** [comment]
> @r-ricci fair point, should I close this PR?

Yes, I as @r-ricci  stated maybe add a xlint warning

**Comment by paper42** [comment]
> > @r-ricci fair point, should I close this PR?
> 
> Yes, as @r-ricci  stated maybe add a xlint warning 

xlint is currently passive - afaikit doesn't run any commands from the template and doesn't make any network requests, I am not sure if this is in scope of xlint. Maybe this lint could be off by default, but enabled with a cli option?

cc @leahneukirchen

**Comment by paper42** [comment]
> This check could be static (e.g.: grep the string `http://`). Some websites don't support HTTPS, but very few, so we can just ignore false positives.

Unfortunately a lot of mirrors and homepages are http-only. Ignoring the check would make it useless.

> If this is not acceptable, since this isn't a very important issue, then these changes can be done at author/reviewer's discretion when updating the package.

That's how it's done currently.

**Comment by leahneukirchen** [comment]
IMO this is not critical enough to check automatically.

**Pull request closed without merging**
