### PR TITLE
wpa_supplicant: update to 2.7.

### PR DESCRIPTION
**Pull request by leahneukirchen**
This keeps some hunks in libressl.patch.

Works with `key_mgmt=WPA-EAP eap=PWD`, I can't test others easily here.

@svenper please test (#5413)

### CODE REVIEW

**Comment by chneukirchen** [comment]
I found TTLS/PAP to work, but PEAP/MSCHAPV2 was stuck in EAP-PEAPv0 Phase2 method=MSCHAPV2.

**Comment by svenper** [comment]
As you say, PEAP/MSCHAPV2 is the issue. I just tested the real world network of that type with these new changes, which did not work this time either. Could it be a regression in upstream?

**Comment by atweiden** [comment]
@svenper have you seen http://lists.infradead.org/pipermail/hostap/2018-November/038958.html?

If that thread doesn't solve your issue, I'd recommend posting on http://lists.infradead.org/mailman/listinfo/hostap

**Comment by svenper** [comment]
@atweiden My config file does not use `anonymous_identity` so I think there's another issue. When I get to the network I will try to post at their list.

The config file excluding other networks:

```
ctrl_interface=/run/wpa_supplicant
ctrl_interface_group=wheel
eapol_version=1
ap_scan=1
fast_reauth=1
update_config=1

network={
	key_mgmt=WPA-EAP
	eap=PEAP
	scan_ssid=1
	ssid="thenetworkname"
	identity="theusername"
	password=hash:00000000000000000000000000000000
	priority=1
}
```

**Comment by chneukirchen** [comment]
Issue at arch: https://bugs.archlinux.org/task/61246?project=1&string=wpa_supplicant

**Comment by Gottox** [comment]
superseded by #11725

**Pull request closed without merging**
