### PR TITLE
pinebookpro-kernel: update to 5.15.38

### PR DESCRIPTION
**Pull request by CameronNemo**
[skip CI]

[ci skip]

Add patch series for dpaltmode support
Add patch series for gamma adjustment support

#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, aarch64

### CODE REVIEW

**Comment by Johnnynator** [comment]
This still seems to be affected by the problem that fusb302 is not picked up by dracut.
Probably just set `CONFIG_TYPEC_FUSB302=y` in the dotconfig

**Comment by Johnnynator** [comment]
```
[    8.378770] sysfs: cannot create duplicate filename '/devices/platform/ff3d0000.i2c/i2c-4/4-0022/typec/port0/port0.0/partner'
[    8.378792] CPU: 2 PID: 523 Comm: 4-0022 Not tainted 5.15.16_1 #1
[    8.378800] Hardware name: Pine64 Pinebook Pro (DT)
[    8.378805] Call trace:
[    8.378807]  dump_backtrace+0x0/0x1e0
[    8.378824]  show_stack+0x18/0x24
[    8.378832]  dump_stack_lvl+0x68/0x84
[    8.378842]  dump_stack+0x18/0x34
[    8.378848]  sysfs_warn_dup+0x60/0x7c
[    8.378858]  sysfs_do_create_link_sd+0x13c/0x14c
[    8.378865]  sysfs_create_link+0x24/0x4c
[    8.378872]  typec_probe+0x98/0x12c
[    8.378881]  call_driver_probe+0x2c/0x140
[    8.378892]  really_probe+0xb4/0x370
[    8.378899]  __driver_probe_device+0xf8/0x120
[    8.378906]  driver_probe_device+0x40/0x100
[    8.378914]  __device_attach_driver+0x98/0x130
[    8.378919]  bus_for_each_drv+0x78/0xd0
[    8.378926]  __device_attach+0xdc/0x1c0
[    8.378934]  device_initial_probe+0x14/0x20
[    8.378939]  bus_probe_device+0x98/0xa0
[    8.378946]  device_add+0x320/0x4f4
[    8.378952]  device_register+0x20/0x30
[    8.378959]  typec_register_altmode+0x1e8/0x350
[    8.378966]  typec_partner_register_altmode+0x10/0x20
[    8.378972]  tcpm_pd_svdm+0x554/0x594
[    8.378981]  tcpm_handle_vdm_request+0x250/0x34c
[    8.378988]  tcpm_pd_data_request+0xb8/0x544
[    8.378995]  tcpm_pd_rx_handler+0xf4/0x110
[    8.379000]  kthread_worker_fn+0x118/0x260
[    8.379007]  kthread+0x108/0x110
[    8.379012]  ret_from_fork+0x10/0x20
[    8.379058] typec_displayport port0-partner.1: failed to create symlinks
[    8.379066] typec_displayport: probe of port0-partner.1 failed with error -17
```

Did you test dpaltmode? Tested with 2 docks/dongle and it does not seem to work at least for me.

Did not notice anything odd except these two issues.

**Comment by CameronNemo** [comment]
Yeah I keep getting that typec issue too, but it works once in a while -- very inconsistent. I think I will need to revert to the previous altmodedp patch set, or just drop that portion entirely... that said the screen I am staring at is via the typec port with those patches.

**Comment by Johnnynator** [comment]
> Yeah I keep getting that typec issue too, but it works once in a while -- very inconsistent. I think I will need to revert to the previous altmodedp patch set (which worked consistently, but only with the type-c to displayport cable I have, not the dongle with HDMI), or just drop that portion entirely... that said the screen I am staring at is via the typec port with those patches.

It does not seem to affect the other parts of the system, so pick whichever patch you consider "better"/more stable.
I don't have a need for a external display with the pbp, so I'm fine with either decision.

**Comment by Johnnynator** [comment]
Also just had a soft lock due to xorg and panfrost.

<details>
  <summary>Kernel log</summary>

```
2022-01-30T12:13:42.51018 <0>[127104.210367] watchdog: BUG: soft lockup - CPU#5 stuck for 49s! [Xorg:18397]
  drbg
 Modules linked in:
  ansi_cprng
  snd_usb_audio snd_usbmidi_lib
  ecdh_generic
  snd_hwdep
  ecc
  snd_rawmidi
  vfio_iommu_type1
  rfcomm
  vfio
  snd_seq_dummy
  uhid
  snd_hrtimer
  uinput
  xt_mark xt_CHECKSUM
  ppp_generic
  xt_conntrack
  slhc
  ipt_REJECT
  tun
  ip6table_mangle
  loop
  ip6table_nat
  dm_crypt
  ip6table_filter
  trusted
  ip6_tables
  asn1_encoder
  iptable_mangle
  hid_multitouch
  bridge
  rfkill
  bnep
  clk_rk808
  iptable_nat
  rk808_regulator
  xt_MASQUERADE
  rtc_rk808
  nf_nat
  cw2015_battery
  nf_conntrack
  fusb302
  nf_defrag_ipv6
  fan53555
  nf_defrag_ipv4
  rk808
  iptable_filter
  regmap_i2c
  xt_comment
  panfrost
  bpfilter
  gpio_keys
  des_generic
  gpu_sched
  libdes
  rockchipdrm
  8021q
  dw_mipi_dsi
  garp
  dw_hdmi
  mrp
  panel_simple
  stp
  analogix_dp
  llc
  cec
  md4
  drm_dp_aux_bus
  nls_iso8859_1
  drm_kms_helper
  snd_soc_simple_amplifier
  syscopyarea
  snd_soc_rockchip_i2s
  sysfillrect
  snd_soc_rockchip_pcm
  sysimgblt
  dw_wdt
  fb_sys_fops
  hantro_vpu(C)
  drm
  rockchip_vdec(C)
  i2c_rk3x
  rockchip_rga
  drm_panel_orientation_quirks
  v4l2_h264 videobuf2_dma_contig
  i2c_core
  joydev uvcvideo
  pwm_bl
  v4l2_mem2mem
  btrfs
  videobuf2_vmalloc
  blake2b_generic
  videobuf2_dma_sg
  xor
  videobuf2_memops
  xor_neon
  btsdio videobuf2_v4l2
  zstd_compress
  hci_uart videobuf2_common
  raid6_pq
  btqca
 
  videodev
 CPU: 1 PID: 1369 Comm: Xorg Tainted: G      D  C   L    5.15.16_1 #1
  btbcm btintel
 Hardware name: Pine64 Pinebook Pro (DT)
  brcmfmac
 pstate: 20000005 (nzCv daif -PAN -UAO -TCO -DIT -SSBS BTYPE=--)
  brcmutil
 pc : queued_write_lock_slowpath+0xa4/0x200
  snd_soc_es8316
 lr : drm_vma_offset_remove+0x70/0xd0 [drm]
  rockchip_thermal cfg80211
 sp : ffff800014b53540
  snd_soc_hdmi_codec
 x29: ffff800014b53540
  snd_soc_simple_card
  x28: ffff800014b53893
  rockchip_saradc
  x27: ffff80001126c130
  snd_soc_simple_card_utils
 
  i2c_dev
 x26: ffff80001126c128
  snd_seq
  x25: 0000000000000001
  snd_seq_device
  x24: ffff00000a297040
  vhost_vsock
 
  vmw_vsock_virtio_transport_common
 x23: 0000000000000001
  vsock vhost_net
  x22: ffff0000f3fd5c80
  vhost
  x21: ffff0000f3fd5e98
  vhost_iotlb
 
  tap
 x20: ffff0000f2a72818
  hci_vhci
  x19: ffff0000f3c85880
  bluetooth
  x18: 0000000000000000
  jitterentropy_rng
 
  drbg
 x17: 0000000000000000
  ansi_cprng
  x16: 0000000000000000
  ecdh_generic
  x15: 0000000000000000
  ecc
 
  vfio_iommu_type1
 x14: 0000000000000000
  vfio
  x13: 0000000000000000
  uhid
  x12: 0000000000000040
  uinput
 
  ppp_generic
 x11: ffff000001c2c920
  slhc
  x10: 0000000000000000
  tun
  x9 : 0000000000000000
  loop
 
  dm_crypt
 x8 : 0000000000000000
  trusted
  x7 : 0000000000000001
  asn1_encoder
  x6 : 0000000000000001
  hid_multitouch
 
  rfkill
 x5 : ffff0000f3c85884
  clk_rk808
  x4 : 0000000000000000
  rk808_regulator
  x3 : 00000000000000ff
  rtc_rk808
 
  cw2015_battery
 x2 : 0000000000000001
  fusb302
  x1 : 0000000000000000
  fan53555
  x0 : 00000000000001ff
  rk808
 
  regmap_i2c
 Call trace:
  panfrost gpio_keys
  queued_write_lock_slowpath+0xa4/0x200
  gpu_sched rockchipdrm
  drm_vma_offset_remove+0x70/0xd0 [drm]
  dw_mipi_dsi
  drm_gem_object_release+0x40/0x60 [drm]
  dw_hdmi
  drm_gem_shmem_free_object+0x44/0xe4 [drm]
  panel_simple
  panfrost_gem_free_object+0xe0/0x100 [panfrost]
  analogix_dp
  drm_gem_object_free+0x20/0x34 [drm]
  cec
  drm_gem_object_handle_put_unlocked+0xf0/0xf4 [drm]
  drm_dp_aux_bus
  drm_gem_object_release_handle+0x6c/0x8c [drm]
  drm_kms_helper
  idr_for_each+0x68/0xfc
  syscopyarea
  drm_gem_release+0x28/0x40 [drm]
  sysfillrect
  drm_file_free.part.0+0xf4/0x15c [drm]
  sysimgblt
  drm_close_helper.isra.0+0x6c/0x80 [drm]
  fb_sys_fops
  drm_release+0x6c/0x150 [drm]
  drm
  __fput+0x78/0x240
  i2c_rk3x
  ____fput+0x10/0x20
  drm_panel_orientation_quirks
  task_work_run+0xc0/0x220
  i2c_core
  do_exit+0x208/0x3e4
  pwm_bl
  die+0x1d8/0x218
  btrfs
  die_kernel_fault+0x64/0x7c
  blake2b_generic
  __do_kernel_fault+0x9c/0x140
  xor
  do_page_fault+0x1f0/0x410
  xor_neon
  do_translation_fault+0x58/0x80
  zstd_compress
  do_mem_abort+0x44/0xb4
  raid6_pq
  el1_abort+0x40/0x6c
 
  el1h_64_sync_handler+0xb0/0xd0
 CPU: 5 PID: 18397 Comm: Xorg Tainted: G      D  C   L    5.15.16_1 #1
  el1h_64_sync+0x78/0x7c
 Hardware name: Pine64 Pinebook Pro (DT)
  drm_gem_fence_array_add_implicit+0x10/0x144 [drm]
 pstate: 00000005 (nzcv daif -PAN -UAO -TCO -DIT -SSBS BTYPE=--)
  panfrost_job_push+0x138/0x24c [panfrost]
 pc : queued_spin_lock_slowpath+0xf4/0x390
  panfrost_ioctl_submit+0xd0/0x2ac [panfrost]
 lr : queued_write_lock_slowpath+0x114/0x200
  drm_ioctl_kernel+0xc4/0x114 [drm]
 sp : ffff800015fd3b60
  drm_ioctl+0x21c/0x43c [drm]
 x29: ffff800015fd3b60
  __arm64_sys_ioctl+0xa8/0xf0
  x28: ffff800015fd3d48
  invoke_syscall+0x48/0x114
  x27: ffff800015fd3d48
  el0_svc_common.constprop.0+0x44/0xec
 
 x26: 0000000000000042
  do_el0_svc+0x24/0x90
  x25: ffff00003100d200
  el0_svc+0x20/0x60
  x24: 00000000c0186442
  el0t_64_sync_handler+0x1a4/0x1b0
 
 x23: ffff800015fd3d50
  el0t_64_sync+0x1a0/0x1a4
  x22: 0000000000000000 x21: 0000000000004000
 x20: ffff00001e13ac18 x19: ffff0000f3c85880 x18: 0000000000000000
 x17: 0000000000000000 x16: 0000000000000000 x15: 0000ffffeb897140
 x14: 0000000000000000 x13: 0000000000000000 x12: 0000000000000000
 x11: 0000000000000000 x10: 0000000000000000 x9 : 0000000000000000
 x8 : ffff00003698db88 x7 : 0000000000000000 x6 : 0000000000000000
 x5 : ffff0000f3c85884 x4 : 0000000000000001 x3 : ffff0000f3c85884
 x2 : 0000000000000000 x1 : 0000000000000000 x0 : 0000000000000101
 Call trace:
  queued_spin_lock_slowpath+0xf4/0x390
  drm_vma_offset_add+0x80/0xd0 [drm]
  drm_gem_create_mmap_offset+0x24/0x30 [drm]
  __drm_gem_shmem_create+0x6c/0x1c0 [drm]
  drm_gem_shmem_create+0x14/0x20 [drm]
  panfrost_gem_create_with_handle+0x40/0xfc [panfrost]
  panfrost_ioctl_create_bo+0x64/0x100 [panfrost]
  drm_ioctl_kernel+0xc4/0x114 [drm]
  drm_ioctl+0x21c/0x43c [drm]
  __arm64_sys_ioctl+0xa8/0xf0
  invoke_syscall+0x48/0x114
  el0_svc_common.constprop.0+0x44/0xec
  do_el0_svc+0x24/0x90
  el0_svc+0x20/0x60
  el0t_64_sync_handler+0x1a4/0x1b0
  el0t_64_sync+0x1a0/0x1a4
```
</details>

**Comment by CameronNemo** [comment]
@Johnnynator 

* set CONFIG_TYPEC_FUSB302=y in the dotconfig
* updated to 5.15.27

**Comment by CameronNemo** [comment]
Bumped to 5.15.33

**Comment by CameronNemo** [comment]
If anyone is interested in the built package I can provide that.

**Pull request merged**
