### PR TITLE
libraw: update to 0.20.2

### PR DESCRIPTION
**Pull request by TeddyDD**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [x] I generally don't use the affected packages but briefly tested this PR

I build all affected packages on x86_64 glibc and I tested Shotwell

#### Does it build and run successfully? 
(Please choose at least one native build and, if supported, at least one cross build. More are better.)
- [x] I built this PR locally for my native architecture, (x86_64 glibc)
- [x] I built this PR locally for these architectures (if supported. mark crossbuilds):
  - [x] aarch64 cross build
  - [x] x86_64-musl
  - [ ] aarch64-musl
  - [ ] armv7l
  - [ ] armv6l-musl

### CODE REVIEW

**Comment by TeddyDD** [comment]
Not sure about `[ci skip]`, it took a while to rebuild on my machine but I forgot to note the time.

**Comment by TeddyDD** [comment]
I cross-compiled all the packagesfor aarch64 sucesfully. It took 1.4h on my fairly beefy machine so I'm afraid it won't compile on GH CI.

**Comment by ericonr** [comment]
Please don't include `[ci skip]` in commits, it's checked only in the PR title or description.

Can you show the error for `siril`?

**Comment by TeddyDD** [comment]
Weird, it failed once but after zap  it compiles just fine.  Anyway: compilaton error was about missing `libgomp.spec` file.

```
libgomp-devel-10.2.1pre1_3	/usr/lib/libgomp.spec
```

**Comment by TeddyDD** [comment]
Okay, everything builds fine for x86_64-glibc and aar64-glibc. Additionally I build `libraw` and `siril` for x86_64-musl and x86.

I can build other packages on those arch tommorow if that's good idea.

**Comment by ericonr** [comment]
I'm testing this build locally, will push when tested. Will also have to remove `gegl3` from repos.

**Comment by ericonr** [comment]
Also https://raw.githubusercontent.com/LibRaw/LibRaw/master/Changelog.txt should be added as changelog.

**Comment by skmpz** [comment]
This fails to build for aarch64-musl (cross compiled on x86_64-musl).. 
```
=> xbps-src: updating repositories for host (x86_64-musl)...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/x86_64-musl-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/nonfree/x86_64-musl-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/debug/x86_64-musl-repodata' ...
(.....)
/builddir/cross-aarch64-linux-musl-0.34/gcc_build/aarch64-linux-musl/libgomp/../../../gcc-10.2.1_pre1/libgomp/oacc-profiling.c:146:(.text+0x828): dangerous relocation: unsupported relocation
/usr/lib/gcc/aarch64-linux-musl/10.2.1/../../../../aarch64-linux-musl/bin/ld: /usr/aarch64-linux-musl/usr/lib/libgomp.a(oacc-profiling.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `acc_prof_lookup' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/aarch64-linux-musl/usr/lib/libgomp.a(oacc-profiling.o): in function `goacc_profiling_initialize':
/builddir/cross-aarch64-linux-musl-0.34/gcc_build/aarch64-linux-musl/libgomp/../../../gcc-10.2.1_pre1/libgomp/oacc-profiling.c:146:(.text+0x820): dangerous relocation: unsupported relocation
/usr/lib/gcc/aarch64-linux-musl/10.2.1/../../../../aarch64-linux-musl/bin/ld: /usr/aarch64-linux-musl/usr/lib/libgomp.a(oacc-profiling.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `acc_prof_unregister' which may bind externally can not be used when making a shared object; recompile with -fPIC
/builddir/cross-aarch64-linux-musl-0.34/gcc_build/aarch64-linux-musl/libgomp/../../../gcc-10.2.1_pre1/libgomp/oacc-profiling.c:146:(.text+0x824): dangerous relocation: unsupported relocation
/usr/lib/gcc/aarch64-linux-musl/10.2.1/../../../../aarch64-linux-musl/bin/ld: /usr/aarch64-linux-musl/usr/lib/libgomp.a(oacc-profiling.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `acc_prof_register' which may bind externally can not be used when making a shared object; recompile with -fPIC
/builddir/cross-aarch64-linux-musl-0.34/gcc_build/aarch64-linux-musl/libgomp/../../../gcc-10.2.1_pre1/libgomp/oacc-profiling.c:146:(.text+0x828): dangerous relocation: unsupported relocation
collect2: error: ld returned 1 exit status
make: *** [Makefile:1056: lib/libraw.la] Error 1
make: *** Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
make: *** [Makefile:1059: lib/libraw_r.la] Error 1
=> ERROR: libraw-0.20.2_1: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 2
=> ERROR:   in do_build() at common/build-style/gnu-configure.sh:15
```

**Comment by ericonr** [comment]
Oh feck, thanks. I wonder if they are special casing aarch64 in their stuff?

**Comment by ericonr** [comment]
@skmpz are you building from a clean masterdir? I couldn't reproduce...

**Comment by skmpz** [comment]
Erm.. running
```
./xbps-src -m masterdir-x86_64-musl clean
./xbps-src -m masterdir-x86_64-musl -a aarch64-musl -j$(nproc) pkg -f libraw
```

**Comment by ericonr** [comment]
@skmpz I mean a fully clean one, as in remove everything and `binary-bootstrap` it again.

**Comment by skmpz** [comment]
yeah that's what i just did and it works :S

**Comment by ericonr** [comment]
No worries ;)

**Comment by ericonr** [comment]
Pushed in 8e6ed0b7db1c91df7f2321d125ee9a1000d05a39, thanks a lot!

**Pull request closed without merging**
