### PR TITLE
Update libdecor to 0.2.2 and gamescope to 3.14.23

### PR DESCRIPTION
**Pull request by CaitCatDev**
## Update Gamescope and libdecor
I've updated gamescope and libdecor(as new gamescope needs it). This is because I was having issues with the version packaged with Void being the camera in games spinning uncontrollably.

Notes about this update in this time Gamescope has moved to using tagged versions of wlroots and libliftoff so for that purpose I've changed the gamescope build template to pull in the commits that gamescope is looking for and updated the dependencies of gamescope(removed wlroots and libliftoff as they are now built in) and added things such as libinput which used to be pulled in by wlroots.

The disabling "Werror" on libliftoff and wlroots was needed as both of them make use of code that can produce warnings based on compiler version. and the version of GCC shipped in void triggers those warnings. However these warnings are due to unused variables and not anything that is likely to cause major issue.

Please let me know if these would be accepted as is or if you would require me to make any adjustments.

### Summary of changes
libdecor 0.1.1 -> 0.2.2
gamescope 3.14.2 -> 3.14.23

#### Testing the changes
- I tested the changes in this PR: Briefly(Would love to get more people to test on more games)
I attempted to get 3.14.24 to work however was experiencing crashing issues to do with the pointer leaving the gamescope window/surface. So feel back to 3.14.23 (I've tested on the games I have access to Warcraft 3, WoW, Command and Conquer 95-Tib sun)

I've also tested some SDL2 and steam games as I am aware that steam and SDL2 both also pull in libdecor and they also seemed to work fine.

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I've not tested on any other arch's as I do not have access to hardware.

ps. this is my first time packaging anything please let me know if I've made a mistake or misunderstood the system :3

Thanks 
- Cat

### CODE REVIEW

**Comment by CaitCatDev** [comment]
@dexgs Hi just @ you as you show up on as having worked on gamescope for void.
and @classabbyamp  as you show up as having worked on libdecor for void.

**Comment by abenson** [comment]
Please follow the [guidelines](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#committing-your-changes) for commit messages.

**Comment by CaitCatDev** [comment]
Apologies it seems githubs docs on updating a commit message close the request. I'll continue this in a new request.

> Please follow the [guidelines](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#committing-your-changes) for commit messages.

Hi sorry seems githubs docs on updating a commit message leads to the request being forced closed. But I have updated the commit messages to better reflect what has been updated and based them on what's in the CONTRIBUTING.MD file

New request here:
https://github.com/void-linux/void-packages/pull/51339

**Comment by dexgs** [comment]
I didn't package the latest gamescope for a while because gamescope started depending on wlroots 0.18 which didn't have a stable release at the time. Now that it does (and it's packaged in void) It might be possible to get the package working without having to pull in specific revisions of libliftoff and gamescope.

**Pull request closed without merging**
