### PR TITLE
Update template

### PR DESCRIPTION
**Pull request by grim-cypher**
updating to the new version of gradle 7.0

### CODE REVIEW

**Comment by ericonr** [comment]
Please use the correct commit message `gradle: update to 7.0`

**Comment by FollieHiyuki** [comment]
Please squash all your commits into 1 with message `gradle: update to 7.0`.

And don't do all the `wget` and `unzip` ... inside the template, `xbps-src` will handle that. This is not really an installer script either so drop the last line with `do_install` call as well.

Anyways you can always re-read the [manual](https://github.com/void-linux/void-packages/blob/master/Manual.md) and checkout templates for other packages to know how to properly write a template.

**Comment by ericonr** [comment]
I believe there is a misunderstanding here... A template isn't a script that installs a given piece of software on your system, it's instead supposed to be used to create a package (a compressed tarball), which is what the package manager (xbps) will use to install the software. The template did this correctly, but your changes seem to be moving in the direction of making it a script. If you look at the README, you will see that templates aren't supposed to be run directly, but instead that you're supposed to run `./xbps-src pkg gradle` and this will create a gradle package inside `hostdir/binpkgs/` which you can install using `xi gradle` (`xi` being a script from the `xtools` package).

**Comment by ericonr** [comment]
Closing due to inactivity. Feel free to reopen!

**Pull request closed without merging**
