### PR TITLE
claws-mail: unmark noross

### PR DESCRIPTION
**Pull request by ndowens**

### CODE REVIEW

**Comment by ericonr** [comment]
I wonder what changed

**Comment by ericonr** [comment]
Did you confirm the binaries were for the correct arch?

**Comment by ndowens** [comment]
> Did you confirm the binaries were for the correct arch?

Looks like it is using the cc related to the arch

**Comment by ericonr** [comment]
Ah, please fix typo in the commit title: `noross`

**Comment by ndowens** [comment]
> Ah, please fix typo in the commit title: `noross`

Done

**Pull request merged**
