### PR TITLE
New package: metadata-cleaner-2.5.5

### PR DESCRIPTION
**Pull request by chrysos349**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-musl
  - armv7l
  - armv6l-musl

### CODE REVIEW

**Comment by chrysos349** [comment]
bump

**Comment by chrysos349** [comment]
bump

**Comment by chrysos349** [comment]
updated to `2.5.5`

**Comment by xeroxslayer** [comment]
Tested this app in x86_64-musl and i686. Builds fine on the following arches and libcs.

- x86_64-musl (native)
- x86_64 (native)
- i686-musl (native)
- i686 (native)
- aarch64-musl (through x86_64-musl)
- aarch64 (through x86_64)
- armv7l-musl (through i686-musl)
- armv7l (through i686)
- armv6l-musl (through i686-musl)
- armv6l (through i686)

Tested it with a PNG and JPG image, cleaned up metadata (tested afterwards in another application).

**Comment by xeroxslayer** [comment]
@chrysos349 Did any of these get merged in other PRs?

**Pull request closed without merging**
