### PR TITLE
Create Slippi respository

### PR DESCRIPTION
**Pull request by save-buffer**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by abenson** [comment]
How does this compare to `dolphin-emu`?

**Comment by save-buffer** [comment]
This is a fork of dolphin-emu that provides a better type of netcode specifically for Super Smash Bros. Melee.

**Comment by ahesford** [comment]
A fork of a console emulator we already package, designed to improve gameplay in a single game, doesn't seem to be worth the maintenance effort.

**Comment by save-buffer** [comment]
That's a fair point. I do think that SSBM is probably one of the most popular games for Dolphin, so other people might be interested in this package. However, I have no data on this so if it's not worth it we can close this PR :)

**Pull request closed without merging**
