### PR TITLE
ldc: update to 1.31.0

### PR DESCRIPTION
**Pull request by subnut**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by tranzystorek-io** [comment]
Covered in #40821, tilix fails to build: https://github.com/gnunn1/tilix/issues/2151

**Comment by subnut** [comment]
IMO it'd be easier/simpler to update these packages separately from llvm, because they don't depend explicitly on llvm15.

i.e. If this PR is merged now, then the llvm15 PR just needs to revbump them, making that PR easier to review.

(Just my two cents)

**Comment by tranzystorek-io** [comment]
I agree, if this gets merged first, I'll gladly rebase and be done 😊

**Comment by tranzystorek-io** [comment]
LLVM 15 has been merged along with ldc

**Pull request closed without merging**
