### PR TITLE
mesa: update to 21.3.2.

### PR DESCRIPTION
**Pull request by HadetTheUndying**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by HadetTheUndying** [comment]
Okay I've now been testing this for going on 5 days. Stable on x86(_64), aarch64(pinephone), and ppc(64(le)). I had a crash on my Pi 3, but I think that's Kernel related.So i updated my initial commit comment.

**Comment by RicArch97** [comment]
This has been open for some time, are there any specific issues that are keeping this from being merged? It's a big release with performance improvements, would be nice to have!

**Comment by ericonr** [comment]
Not really, just lack of testing from maintainers, I suppose.

Have you tried to run it? Receiving reports from multiple users makes merging such stuff easier.

**Comment by RicArch97** [comment]
I've built Mesa 21.3.2 from the git tag, installed it system-wide and tested some games (Shadow of the tomb raider and Cyperpunk 2077) and just regular desktop usage (browsing on Firefox + watching a video, and using the GPU accelerated Alacritty), and did not run into issues.

**Comment by HadetTheUndying** [comment]
In my opinion this is rea

> Not really, just lack of testing from maintainers, I suppose.
> 
> Have you tried to run it? Receiving reports from multiple users makes merging such stuff easier.

I think this is probably ready for a merge. I tested 21.3.1 for weeks, and 21.3.2 now. I've not noticed any degraded or poor behavior.

**Pull request merged**
