### PR TITLE
New package: python3-niapy 2.0.5 (openpyxl)

### PR DESCRIPTION
**Pull request by firefly-cpp**
#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by classabbyamp** [comment]
is this library needed for some (to be) packaged application? if not, it would probably be better to just use it in a venv

**Comment by firefly-cpp** [comment]
@classabbyamp, I planned to package some other data science packages based on the niapy package. I am motivated to have this package in a repository since Void is one of the distros my students choose to work on practical assignments on my subjects related to data science (niapy is one of the packages). Installing packages directly from the distro is more convenient than conventional ways for installing/running (my personal opinion).

**Comment by classabbyamp** [comment]
ok, I would recommend including this package with a PR for things it depends on then

**Comment by firefly-cpp** [comment]
Shall I close this PR, or can it stay open for now?

**Comment by classabbyamp** [comment]
up to you

**Pull request closed without merging**
