### PR TITLE
New package: tinyramfs-0.1.0

### PR DESCRIPTION
**Pull request by wael444**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)

### CODE REVIEW

**Comment by wael444** [comment]
as this is an alternative to `dracut`, is there anything more i have to do to this package?

`dracut` is a dependency of `linux-base`. it'd have to be set to be an ignored package inorder to use tinyramfs and not have conflicting initramfs'

**Comment by wael444** [comment]
wouldn't it have merge conflicts? It should be merged first before I add the entry.

**Comment by dkwo** [comment]
I don't know, it's been there forever.
Perhaps a new PR just for the initram choice?

**Comment by ahesford** [comment]
Handling of alternative initramfs generators has changed. Please adapt changes from https://github.com/void-linux/void-packages/pull/39284 to make this package use the `initramfs` XBPS alternative group.

**Comment by dkwo** [comment]
@apprehensions are you still interested in this? do you need help adapting it to the alternative mechanism?

**Comment by apprehensions** [comment]
I no longer use void

**Pull request closed without merging**
