### PR TITLE
New package: etesync-dav

### PR DESCRIPTION
**Pull request by ProjectMoon**
Etesync is an end-to-end encrypted contacts, calendar, and tasks synchronization service. The etesync-dav bridge runs a local dav server on your machine to give you access to your contacts and calendars on the desktop. This PR adds the package to Void Linux and the required dependencies which were missing in Void.

### CODE REVIEW

**Comment by ProjectMoon** [comment]
scrypt seems to have some issues building on both ARM32 and ARM64. Is LibreSSL compatible with them? Or maybe I am missing some ARM-specific dependencies...

**Comment by q66** [comment]
`python3-scrypt` is not `noarch`, also your `python3-devel` and `libressl-devel` should go in `makedepends`

**Comment by q66** [comment]
also, fix the wrong empty newlines in your templates, fix lint issues, licenses need to follow SPDX identifiers, etc

**Comment by tasn** [comment]
Hey, upstream maintainer here.
Recent versions of `python3-etesync` can just use the `scrypt` implementation that is part of Python's hashlib (in Python 3.6 or newer), so no need for this dependency.

Also, cool to be seeing EteSync in Void. :)

**Comment by ProjectMoon** [comment]
Removed python3-scrypt, newlines, and fixed one of the licenses having a space in front of it (they are all otherwise valid SPDX identifiers). xlint reports no errors.

**Comment by q66** [comment]
Okay. We will need `python3-scrypt` after all, since our `hashlib` does not have `scrypt` (due to LibreSSL not being compatible with OpenSSL 1.1.x API).

Also, please apply the following diff:

```
diff --git a/srcpkgs/etesync-dav/template b/srcpkgs/etesync-dav/template
index ae9b63d2c1..e96c382855 100644
--- a/srcpkgs/etesync-dav/template
+++ b/srcpkgs/etesync-dav/template
@@ -7,6 +7,7 @@ wrksrc="etesync-dav-${version}"
 build_style=python3-module
 hostmakedepends="python3-setuptools"
 depends="python3-etesync radicale2 python3-Flask python3-Flask-WTF"
+checkdepends="$depends python3-pytest"
 short_desc="CalDAV and CardDAV frontend for EteSync"
 maintainer="projectmoon <projectmoon@agnos.is>"
 license="GPL-3.0-only"
diff --git a/srcpkgs/python3-etesync/template b/srcpkgs/python3-etesync/template
index 5a889c4cea..bd0091c158 100644
--- a/srcpkgs/python3-etesync/template
+++ b/srcpkgs/python3-etesync/template
@@ -10,6 +10,7 @@ depends="python3-appdirs python3-asn1crypto python3-cffi python3-cryptography py
 python3-furl python3-idna python3-packaging python3-peewee python3-py python3-pyasn1
 python3-pycparser python3-parsing python3-pytz python3-requests python3-six
 python3-vobject"
+checkdepends="$depends python3-pytest"
 short_desc="Python3 client library for EteSync"
 maintainer="projectmoon <projectmoon@agnos.is>"
 license="LGPL-3.0-only"
diff --git a/srcpkgs/python3-furl/template b/srcpkgs/python3-furl/template
index 0116a02145..5fc53ba21d 100644
--- a/srcpkgs/python3-furl/template
+++ b/srcpkgs/python3-furl/template
@@ -7,6 +7,7 @@ wrksrc="furl-${version}"
 build_style=python3-module
 hostmakedepends="python3-setuptools"
 depends="python3-six python3-orderedmultidict"
+checkdepends="$depends python3-flake8"
 short_desc="Python 3 URL manipulation made simple"
 maintainer="projectmoon <projectmoon@agnos.is>"
 license="Unlicense"
diff --git a/srcpkgs/python3-orderedmultidict/template b/srcpkgs/python3-orderedmultidict/template
index 1f1ecb518c..e6df82104c 100644
--- a/srcpkgs/python3-orderedmultidict/template
+++ b/srcpkgs/python3-orderedmultidict/template
@@ -6,7 +6,8 @@ archs=noarch
 wrksrc="orderedmultidict-${version}"
 build_style=python3-module
 hostmakedepends="python3-setuptools"
-depends="python3"
+depends="python3 python3-six"
+checkdepends="$depends python3-flake8"
 short_desc="Python 3 ordered multivalue dictionary library"
 maintainer="projectmoon <projectmoon@agnos.is>"
 license="Unlicense"
```

**Comment by q66** [comment]
Here is a `python3-scrypt` that should work:

```
# Template file for 'python3-scrypt'
pkgname=python3-scrypt
version=0.8.13
revision=1
wrksrc="scrypt-${version}"
build_style=python3-module
hostmakedepends="python3-setuptools"
makedepends="python3-devel libressl-devel"
short_desc="Python 3 ordered multivalue dictionary library"
maintainer="projectmoon <projectmoon@agnos.is>"
license="BSD-2-Clause"
homepage="https://bitbucket.org/mhallin/py-scrypt/src/default"
distfiles="${PYPI_SITE}/s/scrypt/scrypt-${version}.tar.gz"
checksum=1377b1adc98c4152694bf5d7e93b41a9d2e9060af69b747cfad8c93ac426f9ea

post_install() {
	vlicense LICENSE
}
```

**Comment by ProjectMoon** [comment]
Diff is applied and scrypt added again.

**Comment by q66** [comment]
looks like CI passes fine now, but there's an accidental lint issue regarding indentation, please fix that and i think after that it's lgtm

**Comment by ProjectMoon** [comment]
Lint should pass now.

**Comment by q66** [comment]
looks good, thanks

**Pull request merged**
