### PR TITLE
[NOMERGE] torbrowser-launcher: fix public key and version string comparison error

### PR DESCRIPTION
**Pull request by tibequadorian**
patches are from the flathub repository

### CODE REVIEW

**Comment by daniel-eys** [comment]
Thanks for this pr, I was hoping upstream would finally fix those issues and tag a new release given the fact that the launcher is currently completely unusable.
Could you please reference the corresponding upstream prs in the commit or as a patchnote? These patches need some context, especially the updated pubkey.

**Comment by tibequadorian** [comment]
> Could you please reference the corresponding upstream prs in the commit or as a patchnote? These patches need some context, especially the updated pubkey.

I added patch notes now

**Comment by Piraty** [comment]
NOMERGE for now. see: https://github.com/void-linux/void-packages/pull/24721/#issuecomment-688846957

**Comment by tibequadorian** [comment]
> NOMERGE for now. see: #24721

this patch is 20K and does not pull a 3.4M binary.
why do you want to keep a broken package?

**Comment by tibequadorian** [comment]
Obtaining the key is described at https://support.torproject.org/tbb/how-to-verify-signature
So the key in `$FILESDIR` can be reproduced like this:
```
$ curl -s https://openpgpkey.torproject.org/.well-known/openpgpkey/torproject.org/hu/kounek7zrdx745qydx6p59t9mqjpuhdf | gpg2 --homedir /tmp/.gnupg --import -
$ gpg2 --homedir /tmp/.gnupg -a --export '4E2C6E8793298290' > tor-browser-developers.asc
```

**Comment by tibequadorian** [comment]
This is ridicolous. People will make it worse if they try to fix it themselves, as they will most likely use the most often mentioned fix https://github.com/micahflee/torbrowser-launcher/issues/481#issuecomment-683722851 with the cursed 3M key, which was probably also the case for #24721

**Comment by ericonr** [comment]
The key looks fine and so does the PR, overall. I'm willing to merge this, but given upstream's lack of response to the key change and the other patch in this PR for version checking, I believe we should seriously consider dropping this. If reasonable, perhaps a restricted torbrowser package?

**Pull request closed without merging**
