### PR TITLE
wine: update to 9.18

### PR DESCRIPTION
**Pull request by fvalasiad**
@Hoshpak

### CODE REVIEW

**Comment by fvalasiad** [comment]
Clean void-i686 install and I can build wine just fine, HMMMM

**Comment by fvalasiad** [comment]
Unfortunately, I am too damn busy this time of the year, so I won't be able to tackle this until I find spare time.

If anyone wants to pick up where I left off, I'd suggest you look at https://gitlab.winehq.org/wine/wine/-/releases/wine-9.18 

There have been some patches to configure.ac and aclocal.m4 regarding the C preprocessor, in particular one patch replaces a define check using the C preprocessor with a standard build-to-test procedure.

Given that I am able to build just fine on a void-i686 install, we can assume its an environment issue.

Best of luck,
F.

**Comment by fvalasiad** [comment]
@Hoshpak After a couple of hours of hairpulling, turned out to be the notorious Y2038 problem.

If I had to make an educated guess, this is the patch that broke it: https://gitlab.winehq.org/wine/wine/-/commit/4f7412005f685e4dcd309078bf2fea199e0ea47e

Is this an upstream fault? Nope, the template was setting `_FILE_OFFSET_BITS=64` in `CFLAGS` but not `CPPFLAGS` resulting to the C preprocessor test in the configured script to fail.

Why did it work before? Because as you can see in the patch wine was handling setting it on its own for WoW64 builds, which affected void's i686 build. As soon as they removed that functionality, chaos ensued. 

Why did it work in a clean void-i686 install but not within the chroot that xbps-src was setting up leading to this confusion? Because i686-pc-linux-gnu-cpp isn't installed as a target in the chroot. Outside the chroot `gcc -E <file` was used which was respecting CFLAGS while in the chroot `cpp` was used which wasn't.

Let me know if there are any problems.
Peace!
F.

**Comment by Hoshpak** [comment]
@fvalasiad thanks for all the effort you put into this!

**Comment by fvalasiad** [comment]
:)

**Pull request merged**
