### PR TITLE
newsboat: update to 2.22.1.

### PR DESCRIPTION
**Pull request by subsonik**

### CODE REVIEW

**Comment by Minoru** [comment]
Hi, Newsboat maintainer again :wave: Please see https://github.com/tibequadorian/void-packages/pull/5#issuecomment-758023098 and https://github.com/tibequadorian/void-packages/pull/5#issuecomment-758023098 (someone else was preparing a PR with an update, and I ended up commenting in their fork).

**Comment by subsonik** [comment]
Thanks for the input @Minoru :)

I've ran the test suite on my machine using an x86_64 chroot and everything passed as an unprivileged user. The x86_64-musl tests fail, as previously noted, but I can confirm that the app itself is working fine on my machine (x86_64-musl).

I'm inexperienced with Void packaging/Travis, unfortunately, so I'm not sure if I can get the tests to run on Travis as an unprivileged user.

I think someone more knowledgeable will need to weigh in here, but in my opinion, besides the musl test failures and Travis running the test suite as a privileged user, this update is good to go. Maybe the test phase should be skipped?

**Comment by ericonr** [comment]
@tibequadorian do you think the changes from `post_patch` in https://github.com/tibequadorian/void-packages/pull/5/files are necessary?

**Comment by tibequadorian** [comment]
> @tibequadorian do you think the changes from `post_patch` in https://github.com/tibequadorian/void-packages/pull/5/files are necessary?

On @Minoru suggestion in https://github.com/tibequadorian/void-packages/pull/5#discussion_r555127025 I set `make_check_target=ci-check` and removed current `do_check` from the template. This fails with "Error opening terminal: unknown."
However the `ci-check` target in the Makefile looks quite similar to what was in the `do_check` function, so I kinda merged the idea in `post_patch()` and checks were indeed successful, but the CI still fails.

**Pull request closed without merging**
