### PR TITLE
riot-desktop: update to 1.7.1, rename to element-desktop.

### PR DESCRIPTION
**Pull request by dawidpotocki**
https://element.io/blog/welcome-to-element/

### CODE REVIEW

**Comment by dawidpotocki** [comment]
Well… I don't think that Electron even supports 32bit Linux?
https://www.electronjs.org/blog/linux-32bit-support

**Comment by ericonr** [comment]
So I guess the `arch` line should be updated, and the broken `case` for `i686*` removed, since it's not going to get support any time soon.

**Comment by jeffverk** [comment]
The repackage looks good to me. There's apparently a small issue with the new client showing "Riot" in it that will require a repackage from upstream, but I'm trying to figure out if that will require them to make a new release in the riot-desktop GitHub repo, or if it was just an error in their Debian package. If they need to make a new release in GitHub, maybe it would be good to wait for that.

**Comment by ProjectMoon** [comment]
The repackage looks good to me. There's apparently a small issue with the new client showing "Riot" that will require a repackage from upstream, but I'm trying to figure out if that will require them to make a new release in the riot-desktop GitHub repo, or if it was just an error in their Debian package. If they need to make a new release in GitHub, maybe it would be good to wait for that.

**Comment by dawidpotocki** [comment]
I didn't notice "Riot" anywhere myself. I know there is some Riot image in
1.7.0 tag of vector-im/riot-desktop, but it looks like something for browser
and we don't explicitly copy it.

**Comment by jeffverk** [comment]
It seems like it was a mistake with the icon. Since the icon is handled directly in the XBPS build, that issue should not affect us.

**Comment by ProjectMoon** [comment]
It seems like it was a mistake with the icon. Since the icon is handled directly in the XBPS build, that issue should not affect us.

**Comment by ProjectMoon** [comment]
Actually one suggestion, making a symbolic link from `riot-desktop` to `element-desktop` is probably a good idea, right?

**Comment by dawidpotocki** [comment]
I don't know how it looked in other packages, but I'm fine with making a symlink.

**Comment by dawidpotocki** [comment]
btw… what's the preferred description for transitional packages? I can see
`(transitional dummy package)`, `- transitional dummy pkg`, `- transitional dummy package`,
`transitional dummy package`, `- dummy transitional package`, `(transitional meta-package)`
and probably more in repository.

**Comment by ProjectMoon** [comment]
Another suggestion: update install message to mention the rename

**Comment by dawidpotocki** [comment]
*sigh* Should I remove previous message about tray or put it next to it?

**Comment by ProjectMoon** [comment]
It makes sense to keep it above the tray message, which can probably be removed after this version.

**Comment by dawidpotocki** [comment]
Okay, hopefully everything is okay now 🙃

**Comment by ProjectMoon** [comment]
Looks  good, yes

**Comment by dawidpotocki** [comment]
Don't merge, preparing new template for 1.7.1 🙃

**Comment by ProjectMoon** [comment]
I have been testing both 1.7.0 and now 1.7.1 using this build for 5 days now. It looks like everything is in working order.

**Pull request merged**
