### PR TITLE
ecl: use system libffi; add target arch *.conf

### PR DESCRIPTION
**Pull request by pullmoll**

### CODE REVIEW

**Comment by pullmoll** [comment]
Cannot select anyone in Reviewers.. it spins forever. Ping @knusbaum .

**Comment by q66** [comment]
should add x86_64 crossfiles too

**Comment by pullmoll** [comment]
But we don't have a `cross-x86_64-linux-{gnu,musl}` package?

**Comment by q66** [comment]
we have both musl and gnu

**Comment by pullmoll** [comment]
Oops.. this addition escaped my attention. The cross file should be the same as then one for musl. Perhaps you can give it a try and add the file or make it a symlink?

**Comment by q66** [comment]
Is there a difference between any of them for musl? Why have them at all?

**Comment by pullmoll** [comment]
I don't think there actually are differences as there's no reference to the _FILEOFFSET_BITS which is or may be 32 for i686, while it's always 64 for i686-musl. That's an anachronism anyway.

So I think we could just remove the `*-musl.conf` files and strip the suffix from the target, i.e. `${XBPS_TARGET_MACHIN%-musl}.conf` in the template.

**Comment by pullmoll** [comment]
Or even better yet: the files could be generated by the template based on our `$XBPS_...` environment AFAICT. I'll give it a try as soon as I find time for Void again... *busybee*

**Comment by q66** [comment]
_FILE_OFFSET_BITS just does not exist on musl, so even when set it makes no diff

**Comment by pullmoll** [comment]
I know, and still some value(s) in depends on this in `common/environment/configure/autoconf_cache/ix86-common`. I remember we had failed cross builds because when the autoconf_cache files are used it is not yet known if `i686` defines `_FILE_OFFSET_BITS=32` or `64`.

Anyway, I can't deal with that now.

**Pull request merged**
