### PR TITLE
New package: switchboard-plug-a11y-2.2.0

### PR DESCRIPTION
**Pull request by LinArcX**
[Related](https://github.com/void-linux/void-packages/pull/20538)

### CODE REVIEW

**Comment by LinArcX** [comment]
[What's wrong](https://travis-ci.org/github/void-linux/void-packages/jobs/670944094#L14223)?

**Comment by Anachron** [comment]
Travis network issue.

**Comment by LinArcX** [comment]
Hmm.. What can i do?
Force push doesn't work :)
> Branch 'switchboard-plug-a11y' set up to track remote branch 'switchboard-plug-a11y' from 'origin'.
Everything up-to-date

**Comment by Anachron** [comment]
Not sure what you can do here to fix travis, sorry.

This works as expected.

**Pull request closed without merging**
