### PR TITLE
wireshark: update to 3.2.2

### PR DESCRIPTION
**Pull request by zlice**

### CODE REVIEW

**Comment by zdykstra** [comment]
You'll need to change the actual git commit title, instead of the GitHub PR title. This can be done in your wireshark322 branch via `git commit --amend`. You can use `xbump` to automatically generate the commit message on your next one.

**Comment by zlice** [comment]
got it. was at work. amended

**Comment by zdykstra** [comment]
> got it. was at work. amended
> 
> hm xbump, void util? haven't really used the void stuff much

xbump is part of xtools. Once you update the template with the new version and source sha, you can just run `xbump wireshark` and it'll formulate the commit message and commit the changes for you.

**Comment by zlice** [comment]
just rtfm on the contrib. sweet thanks

**Pull request merged**
