### PR TITLE
New package: zanshin-22.08.2

### PR DESCRIPTION
**Pull request by hervyqa**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64)

Screenshot_20220802_234217

### CODE REVIEW

**Comment by hervyqa** [comment]
qt5-webengine-devel broken?
https://github.com/void-linux/void-packages/runs/7636627412?check_suite_focus=true#step:7:94
```
=> ERROR: qt5-webengine-devel-5.15.10_1: cannot be built, it's currently broken; see the build log:
=> ERROR: qt5-webengine-devel-5.15.10_1: webengine can be built only if word size matches
```
@Johnnynator @classabbyamp

**Comment by Chocimier** [comment]
Yes, it is explicitly marked as failing build on some archs for mentioned reason.

**Comment by hervyqa** [comment]
required `akonadi*-22.08.1`

**Comment by hervyqa** [comment]
waiting to merge.
zanshin: https://github.com/void-linux/void-packages/pull/38430
lokalize: https://github.com/void-linux/void-packages/pull/38428
sweeper: https://github.com/void-linux/void-packages/pull/38423
kwave: https://github.com/void-linux/void-packages/pull/38388
subtitlecomposer: https://github.com/void-linux/void-packages/pull/38384

**Pull request merged**
