### PR TITLE
New package: q-0.19.2

### PR DESCRIPTION
**Pull request by classabbyamp**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**

### CODE REVIEW

**Comment by Anachron** [comment]
Why not stick to the "Don't pollute the 1 and 2 letter namespace"?

**Comment by classabbyamp** [comment]
there is an open issue upstream about it

**Comment by melroy89** [comment]
They now have `v0.19.2`

**Comment by classabbyamp** [comment]
I'm aware.

**Comment by melroy89** [comment]
> there is an open issue upstream about it: [natesales/q#28](https://github.com/natesales/q/issues/28)

ow.. sorry, you wait on ?

**Pull request merged**
