### PR TITLE
mesa: update to 24.3.0

### PR DESCRIPTION
**Pull request by SpidFightFR**
#### Testing the changes
- I tested the changes in this PR: **briefly**

#### Local build testing
- I built this PR locally for my native architecture, (x64-GlibC)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-musl
  - x64-musl

### CODE REVIEW

**Comment by SpidFightFR** [comment]
I'm aware there's two commits, that's because i'm not sure mesa 23.3.0 will work properly, i keep the second one as a fallback just in case.

**Comment by classabbyamp** [comment]
can we go back to waiting until the `.1` release of each series before merging?

**Comment by SpidFightFR** [comment]
> can we go back to waiting until the `.1` release of each series before merging?

Sorry i completely forgot... yes, for sure!

**Comment by SpidFightFR** [comment]
damn... one moment.

**Comment by SpidFightFR** [comment]
Oh i didn't realize someone already pushed mesa 23.2.7, i was wondering what happened...
Alright i'll check later on for 23.3.1.

**Comment by onlylunix** [comment]
bro, hurry up
`--- a/srcpkgs/mesa/template
+++ b/srcpkgs/mesa/template
@@ -1,12 +1,12 @@
 # Template file for 'mesa'
 pkgname=mesa
-version=24.2.7
+version=24.3.1
 revision=1
 build_style=meson
 _llvmver=19
 #Disable LTO flag should be present, see https://gitlab.freedesktop.org/mesa/mesa/-/issues/6911
 configure_args="-Dglvnd=true -Dshared-glapi=enabled -Dgbm=enabled -Degl=enabled
- -Dosmesa=true -Dgles1=enabled -Dgles2=enabled -Dglx=dri -Ddri3=enabled
+ -Dosmesa=true -Dgles1=enabled -Dgles2=enabled -Dglx=dri
  -Dlmsensors=enabled -Dplatforms=x11$(vopt_if wayland ,wayland)
  -Dllvm=enabled -Db_lto=false -Dcpp_std=gnu++17"
 hostmakedepends="gettext flex pkg-config python3-Mako glslang llvm${_llvmver}
@@ -24,7 +24,7 @@
 homepage="https://www.mesa3d.org/"
 changelog="https://docs.mesa3d.org/relnotes.html"
 distfiles="https://mesa.freedesktop.org/archive/mesa-${version}.tar.xz"
-checksum=a0ce37228679647268a83b3652d859dcf23d6f6430d751489d4464f6de6459fd
+checksum=9c795900449ce5bc7c526ba0ab3532a22c3c951cab7e0dd9de5fcac41b0843af
 
 build_helper="qemu"
 build_options="wayland"

`

**Comment by onlylunix** [comment]
bro, hurry up 
[mesa-24.3.1.PATCH](https://github.com/user-attachments/files/18015867/mesa-24.3.1.PATCH)

**Comment by classabbyamp** [comment]
bro, chill

**Comment by SpidFightFR** [comment]
> Bro, hurry up 
> [mesa-24.3.1.PATCH](https://github.com/user-attachments/files/18015867/mesa-24.3.1.PATCH)
> 

Yo.
I work.
So that will wait.
Take care.

**Comment by SpidFightFR** [comment]
> Bro, hurry up [mesa-24.3.1.PATCH](https://github.com/user-attachments/files/18015867/mesa-24.3.1.PATCH)

https://github.com/void-linux/void-packages/pull/53384

**Pull request closed without merging**
