### PR TITLE
kernel.d: preremove dkms hook now deletes /lib/modules

### PR DESCRIPTION
**Pull request by kingpingu**
#### General
- [x] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by abenson** [comment]
Change the commit to  `base-files: vkpurge deletes initramfs and /lib/modules`

**Review by kingpingu — COMMENTED** [review]
Tested locally by touching dummy files/dirs. Removes dummy files correctly

**Comment by kingpingu** [comment]
Changed commit message to: `base-files: vkpurge deletes initramfs and /lib/modules`

**Comment by Duncaen** [comment]
Why `/lib/modules`, why does it need to remove the initramfs, isn't that the hooks responsiblity?

**Comment by kingpingu** [comment]
@Duncaen It might make more sense to remove the `/lib/modules/"${rmkver}"` dir in the kernel pre-remove hook, although we already have precedent in vkpurge with `/usr/lib/modules/"${rmkver}"`. I don't believe initramfs is the hook's responsibility, vkpurge already deletes every other resource in `/boot`, why should initramfs be exempt?

I'm not an expert on ownership, I'll defer to your judgement if you disagree strongly. Let me know if you think this is blocking.

**Comment by Duncaen** [comment]
`/lib` is a symlink to `/usr/lib`.

The installed initramfs tool generates the initramfs file and is responsible for it and its name, all other files vkpurge removes come from the kernel packages and have the preserve keyword, they are not generated by a separate mechanism, vkpurge is the tool to cleanup the kernel files and run the kernel hooks, which then remove things the kernel hook generate on install hooks.

dracut already deletes the file in its hook and so does mkinitcpio:
`/etc/kernel.d/post-remove/20-dracut` (https://github.com/void-linux/void-packages/blob/master/srcpkgs/dracut/files/kernel-hook-postrm).

**Comment by kingpingu** [comment]
Thanks for the clarification! It's a mystery why (some) of my initramfs were not being removed with the dracut postrm hook, I'll monitor the next few months and see if it happens again. 

Updated the commit to rm `/lib/modules` during dkms prerm hook.

**Comment by Duncaen** [comment]
No why this is also completely unnecessary, vkpurge already deletes the directory, it deletes `/usr/lib/modules/${version}`, `/lib` is a symlink to `/usr/lib`, deleting `/usr/lib/modules/$version` and/or `/lib/modules/$version` deletes exactly the same files.

**Comment by kingpingu** [comment]
Ah I see, strange, will investigate why some of my /lib/modules from past unused uninstalled kernels were not deleted as well.

**Pull request closed without merging**
