### PR TITLE
kde-frameworks: update to 5.50.0

### PR DESCRIPTION
**Pull request by Johnnynator**
Also I adopted all packages that had Denis Revin listed as maintainer.
Edit2: @dutsky Is it ok for you that I take the maintainer ship?
Edit: x86_64 seems to run fine so far.
Edit3: aarch64-musl did also compile fine.

### CODE REVIEW

**Comment by Hoshpak** [comment]
If you need help with testing cross-compilation, I currently have a reasonably powerful VM available I could put to use.

**Comment by Johnnynator** [comment]
@Hoshpak So far only x86_64 and aarch64-musl are compiled. If you want you can test armv7/6 or i686

**Comment by Hoshpak** [comment]
Alright, the VM is currently running a build form armv6l.

**Comment by Hoshpak** [comment]
All packages built successfully for armv6l.

**Comment by Johnnynator** [comment]
i686 also looks fine. Imo you can merge it once the builders have time for it.

**Comment by Hoshpak** [comment]
I agree. Will just wait until they are unstuck. The glibc builders currently lock while registering debug packages until the job times out on the buildbot.

**Comment by Hoshpak** [comment]
merged manually as github wouldn't do it.

**Comment by dutsky** [comment]
lol :man_facepalming:

**Pull request closed without merging**
