### PR TITLE
acpica-utils: update to 20190509.

### PR DESCRIPTION
**Pull request by congdanhqx**
Also rebuild virtualbox and xen due to this bug:
https://github.com/acpica/acpica/issues/462

I don't mind if you want to split this patch into 3 separated patches.
Please tell me if it's better to do so.

Testing with virtualbox-ose is in progress.
Created this PR in order to allow other people test it, too.

### CODE REVIEW

**Comment by congdanhqx** [comment]
Reference #11563

**Comment by Hoshpak** [comment]
Yes, please create 3 separate commits. Also please add `[skip ci]` to the comment of the last commit to disable CI since virtualbox-ose takes way too long to build and will time out.

**Comment by congdanhqx** [comment]
The new virtualbox-ose package works fine for me with the Win7 image from Microsoft.
I don't have the Windows 7 installation ISO in hand to test the setup.

I will try to find it and test it tomorrow, since it's a bit late overhere.

**Comment by pullmoll** [comment]
The installer ISO boots here. Currently restoring a backup of my Win7 VM, but I think we don't have to wait for that to confirm it's working again.

**Pull request closed without merging**
