### PR TITLE
dunst: update to 1.9.1, adopt

### PR DESCRIPTION
**Pull request by mdkcore0**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, x86_64-libc
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - armv7l (crossbuild)
  - i686-libc

### CODE REVIEW

**Comment by biopsin** [comment]
duplicate #42756

**Comment by mdkcore0** [comment]
> duplicate #42756

oh, OK

**Comment by biopsin** [comment]
@mdkcore0 forgot to ask do you want to maintain it, I can put you in my pull?

**Comment by mdkcore0** [comment]
hi @biopsin, it would be great, thanks!

**Pull request closed without merging**
