### PR TITLE
chromium: update to 83.0.4103.116.

### PR DESCRIPTION
**Pull request by pbui**
- Built for x86_64 and x86_64-musl.
- Tested on x86_64.

- Add sndio build option from #22888 

- Turn on vaapi build option by default.  With this build option, the
  chromium package now supports VA-API for Intel and AMD GPUs.

  However, users must opt-in to enabling this feature at run-time by
  enabling "Override software rendering list" in chrome://flags or by
  passing the --ignore-gpu-blacklist to chromium.  Otherwise this
  feature is disabled and not used.

  This has been tested with YouTube on multiple machines with Intel GPUs.

- Add ffmpeg patch to workaround some problems with ffmpeg 4.3:
  https://bugs.chromium.org/p/chromium/issues/detail?id=1095962

- Also update chromium-widevine.

### CODE REVIEW

**Comment by ericonr** [comment]
> Turn on vaapi build option by default. With this build option, the chromium package now supports VA-API for Intel and AMD GPUs.

Do you know if this fixes that issue where chromium compiled with vaapi wouldn't even launch in certain devices? https://github.com/void-linux/void-packages/issues/22877#issuecomment-645307837

**Comment by pbui** [comment]
@ericonr Yes, the old patch which @Duncaen is referring to (and removed in06430645c61fe9ee0b8c052c6d58b0cd0bab4d61) enabled vaapi unconditionally.  As noted in this commit message, this is no longer the case.  First, we no longer have a big vaapi patch; vaapi support is now provided by upstream chromium.  Second, vaapi is OFF by default.  The user must explicitly choose to enable it.  This should address the problem @Duncaen mentioned.

Note, I introduced this build option in 88464d1272e6a98f2a045169c07446a3181f5df9 and have been using it since then for my own machines.  I am requesting to enable it by default because I believe it is stable now.

That said, I've only tested this on machines with Intel GPUs (both with it on and off).  I'd be happy to wait for feedback from users with different devices.

Final note: Arch Linux has enabled vaapi by default in a similar manner as to what I am proposing here: https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/chromium&id=0cbb8c4205a73ceb76066477fef42e55ae5aa394

**Comment by jnbr** [comment]
Would you mind applying https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/chromium/files/chromium-84-mediaalloc.patch?id=fd3c6eeae58085ad2248e99ad67d8eba0f3a25ff as well, so we can move to ffmpeg-4.3?
 
See https://bugs.chromium.org/p/chromium/issues/detail?id=1095962 for further details.

**Comment by pbui** [comment]
@jnbr I have added that patch and have tested on my machine.  It appears to work fine.

**Comment by jnbr** [comment]
Thank you

**Comment by dm17** [comment]
@pbui I have "override software rendering list" enabled and I still see the following in chrome:flags:

```
"Hardware-accelerated video encode
Hardware-accelerated video encode where available. Mac, Windows, Chrome OS, Android
#disable-accelerated-video-encode
Not available on your platform.
```

This is still the indicator that vaapi isn't enabled, right? I'm on Chromium 85.0.4183.83

**Comment by pbui** [comment]
When you enable the "override software rendering list" and check `chrome://gpu`, you should see something like this:

aJq1

When it is disabled, you will see something like this:

djgW

Notice that the "hardware protected video decode" and "video decode" features changed.

Also, once you change the setting, then you will need to restart your browser.

**Comment by dm17** [comment]
Seems a lot of competing information on what qualifies chromium as "vaapi enabled" - maybe this console output in chrome://gpu is a clue?
```
ERROR:shared_image_manager.cc(214)] : SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
ERROR:vaapi_video_decode_accelerator.cc(723)] : Failed to allocate memory for a VaapiPicture
```

**Comment by pbui** [comment]
@dm17 Hmm, might be an issue with your GPU or drivers.  If you are using Intel, did you install the video acceleration drivers as explained here: https://docs.voidlinux.org/config/graphical-session/graphics-drivers/intel.html ?

**Comment by dm17** [comment]
@pbui Yep (installed everything from the docs), and I'm not using anything Intel (just AMD). Also 'gst-inspect-1.0 vaapi' yields nothing. I also have to export LIBVA_DRIVER_NAME=radeonsi in order to get ffmpeg's vaapi features working. If I look at chrome://media-internals, I see youtube videos show "Failed to initialize MojoVideoDecoder" and default to "VpxVideoDecoder"

vaapi seems to work in Firefox (just based on how much faster HD videos switch to full screen - will look into checking how FF does vaapi).

**Pull request merged**
