### PR TITLE
inkscape: update to 1.0.

### PR DESCRIPTION
**Pull request by Gottox**

### CODE REVIEW

**Comment by q66** [comment]
here:

```
diff --git a/srcpkgs/inkscape/template b/srcpkgs/inkscape/template
index 129d866380..cd322cfafa 100644
--- a/srcpkgs/inkscape/template
+++ b/srcpkgs/inkscape/template
@@ -4,7 +4,6 @@ version=1.0
 revision=1
 wrksrc="${pkgname}-INKSCAPE_${version//./_}"
 build_style=cmake
-python_version=3
 hostmakedepends="automake pkg-config libtool intltool gettext-devel
  glib-devel perl-XML-Parser tar which xz"
 makedepends="harfbuzz-devel libsoup-devel gsl-devel pango-devel double-conversion-devel gc-devel libwpd-devel libcdr-devel libvisio-devel poppler-devel libwpd-devel potrace-devel gtkmm-devel gdl-devel gtkspell3-devel aspell-devel libxslt-devel libgomp-devel libwpg-devel poppler-glib-devel"
@@ -18,10 +17,11 @@ distfiles="https://gitlab.com/inkscape/inkscape/-/archive/INKSCAPE_${version//./
  https://gitlab.com/inkscape/extensions/-/archive/${_extension_rev}/extensions-${_extension_rev}.tar.bz2"
 checksum="673a1d8dfff4993917ac560d73ded4cab6edf8360cb97b99703658b14c03031f
  11d573e30d4b0c821e9c59a524c9f98b935dcfdad979066cc65fdf111cf116fe"
+python_version=3
 
-case "$XBPS_TARGET_MACHINE" in
-	arm*|aarch64*) makedepends+=" libatomic_ops-devel" ;;
-esac
+if [ "$XBPS_TARGET_NO_ATOMIC8" ]; then
+	makedepends+=" libatomic-devel"
+fi
 
 pre_configure() {
 	rm -r share/extensions || true
```

**Comment by Gottox** [comment]
@q66 applied, thanks :)

**Comment by q66** [comment]
can you squash that? also is this ready to apply? it looks good to me

**Comment by Gottox** [comment]
squashed, merging

**Pull request merged**
