### PR TITLE
fail2ban: change maintainer

### PR DESCRIPTION
**Pull request by MeganerdNL**
I will maintain this package from now on.
@necrophcodr (old maintainer) will comment here to confirm this - as discussed by e-mail.

### CODE REVIEW

**Comment by necrophcodr** [comment]
I haven't done the best of jobs maintaining this, so great to see someone else pick it up :+1:

**Review by necrophcodr — APPROVED** [review]

**Comment by MeganerdNL** [comment]
> We generally don't want to change maintainer ship for packages to people who are really new, there has a been a history of one-of maintainers adopting packages and then not contributing anymore.

I really do understand that! 
You will have to take my word for it, but that's hard on the internet :).

I have Void installed on several machines now (1 in production but I will add 3 more in the near future). I'm coming from Debian and I recently searched for a rolling release without systemd and with a greater userbase than Artix (which I use for my laptop) and that let me to Void and I'm really enthusiastic about it since. Great documentation too. Fail2ban is a must-have on servers imho, but there was an old version here, so I PR'd for a new one a few days ago (merged)  and that went well and it learned me how the flow is in void-packages as a bonus. 

So a little introduction that can help you decide. I'm also happy to update fail2ban without being the official maintainer for now and than you can decide later. The former maintainer didn't update it in a long time (so he said himself), so that is the alternative. Cheers.

**Comment by necrophcodr** [comment]
> We generally don't want to change maintainer ship for packages to people who are really new, there has a been a history of one-of maintainers adopting packages and then not contributing anymore.

On the other hand, I haven't been maintaining that package. Is it better to keep a maintainer that, for years, hasn't actively contributed?

**Comment by Duncaen** [comment]
> > We generally don't want to change maintainer ship for packages to people who are really new, there has a been a history of one-of maintainers adopting packages and then not contributing anymore.
> 
> On the other hand, I haven't been maintaining that package. Is it better to keep a maintainer that, for years, hasn't actively contributed?

Of course not, they should've been orphaned a long time ago. 

I've been trying to actively remove outdated maintainers, but you commenting/approving the fail2ban PR that I've merged threw me off and I assumed you are active without checking the history.

**Comment by necrophcodr** [comment]
> > > We generally don't want to change maintainer ship for packages to people who are really new, there has a been a history of one-of maintainers adopting packages and then not contributing anymore.
> > 
> > 
> > On the other hand, I haven't been maintaining that package. Is it better to keep a maintainer that, for years, hasn't actively contributed?
> 
> Of course not, they should've been orphaned a long time ago.
> 
> I've been trying to actively remove outdated maintainers, but you commenting/approving the fail2ban PR that I've merged threw me off and I assumed you are active without checking the history.

The real story is that @MeganerdNL contacted me via the email listed, and asked if it could be updated. I replied back that I haven't been active in this community for a long time (and I haven't), so if they wanted to update it and maybe maintain it too, they would have my approval at least (however little that means). One PR merged later, and here we are.

**Comment by classabbyamp** [comment]
please rebase to fix the conflict

**Pull request closed without merging**
