### PR TITLE
gsl: update to 2.8 (with some other minor updates)

### PR DESCRIPTION
**Pull request by tornaria**
Rebuild / update as necessary:

- ~~**giac: update to 1.9.0.99.**~~ (moved to #49571)
- **Clight: Rebuild for gsl**
- **bogofilter: Rebuild for gsl**
- **krita: update to 5.2.2.** (@Johnnynator)
- **calligra: Rebuild for gsl**
- **dieharder: Rebuild for gsl**
- **easyeffects: update to 7.1.6.** (@zen0bit)
- **enblend-enfuse: Rebuild for gsl**
- **guvcview: update to 2.1.0.**
- **igt-gpu-tools: update to 1.28.**
- **lib2geom: Rebuild for gsl**
- **inkscape: Rebuild for gsl**
- **ipe: Rebuild for gsl**
- **python3-cvxopt: Rebuild for gsl**
- **qgis: update to 3.36.3.** (@ar-jan)
- ~~**sagemath: Rebuild for gsl**~~ (moved to #49571)
- **siril: Rebuild for gsl**
- **xsnow: Rebuild for gsl**
- **gnuradio: update to 3.10.10.0.**
- **gnuradio-nrsc5: rebuild for gnuradio**
- **gnuradio-osmosdr: rebuild for gnuradio**
- **gnuradio-rds: rebuild for gnuradio**
- **gqrx: rebuild for gnuradio**

PR #49571 should be merged on top of this one at the same time, so that giac and sagemath are also rebuilt. Indeed, if you look at checks here, everything passes except the repo check complains that giac and sagemath must be rebuilt.

The reason to split these two is that both together take more than 6h to build and test, so gh actions will timeout.

#### Testing the changes
- I tested the changes in this PR: **yes**

Rebuilt and checked everything on x86_64 / x86_64-musl / i686

Cross built everything not nocross on aarch64

Edit: also, there is a failure on CI building gnuradio for armv7l and armv6l-musl. However, this builds fine locally.

### CODE REVIEW

**Comment by ar-jan** [comment]
I think QGIS was intentionally an implicit nocross. Whatever is preferred by Void's maintainers works for me.

**Comment by classabbyamp** [comment]
yes, i'd rather have it not marked nocross if the deps still are, since we can't know if it's cross-compatible without those deps being fixed

**Comment by tornaria** [comment]
Improvements after nice review on irc:
 - bogofilter: much simpler patch, with explanation
 - xsnow: imporved commit message
 - giac: added a comment in the added patch (which I will send to the main developer by email)

**Comment by tornaria** [comment]
About giac: developer tells me the `static` attributes have already been removed so we won't need to carry the patch any further than this release.

About our CI: there's no failure. x86_64 and i686 are cancelled at the 6h mark. The x86_64-musl gave an error due to update of libnice. Everything cross builds fine locally and here. I've fully built and check locally the three nocross architectures.

Maybe it makes sense to merge together with #50295 so we only rebuild sagemath once. But I'd rather have this merged on its own than delay. We can do #50295 later.

**Comment by tornaria** [comment]
For testing purposes, this PR includes everything except update/rebuild of giac + sagemath, because otherwise the check time exceeds 6h.

Ideally, this must be merged together with #49571 which updates (and thus rebuilds for the new gsl) both giac and sagemath.

**Comment by tornaria** [comment]
Note: there's a failure on building gnuradio for armv7 and armv6l-musl. I couldn't reproduce this failure locally (cross-building on x86_64). I don't know what is going on, I think this worked fine before.

**Pull request closed without merging**
