### PR TITLE
mesa: update to 22.1.2.

### PR DESCRIPTION
**Pull request by HadetTheUndying**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)
- I built this PR locally for these architectures (if supported. mark crossbuilds):
  - aarch64-glibc
  - aarch64-musl

### CODE REVIEW

**Comment by abenson** [comment]
Can you incorporate the two fixes from #37581?  I've been waiting for the builders to settle for push it.

**Comment by HadetTheUndying** [comment]
> Can you incorporate the two fixes from #37581? I've been waiting for the builders to settle for push it.

Yeah no worries. Do you want me to squash them all into one commit or add those commit messages too?

**Comment by abenson** [comment]
It doesn't matter to me.

**Comment by HadetTheUndying** [comment]
So i've had a couple days to test this now. and the only reason the builds failed is the CI bugging out. Let me know if there's any more changes you think need to be made.

**Comment by RicArch97** [comment]
Been using this from the moment it came out, works fine for me too 👍🏻

**Pull request merged**
