### PR TITLE
jack: update to 1.9.17.

### PR DESCRIPTION
**Pull request by daniel-eys**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

### CODE REVIEW

**Comment by ericonr** [comment]
Do you know why eigen was disabled for cross builds? Testing locally, it is detected during configure and it builds. Maybe we could just enable for all of them (and mention it in the commit message, of course).

**Comment by ericonr** [comment]
@pullmoll do you remember why it was initially disabled in e2b7963568c666e45233f48302484ad22aac0c7e ?

**Comment by ericonr** [comment]
Ping

**Comment by biopsin** [comment]
@daniel-eys Ping : bump release 1.9.18

**Comment by daniel-eys** [comment]
Updated to 1.9.18 and also added the `zalsa` buildoption which has been introduced with jack 1.9.18.
I also re-added `eigen` to `makedepends` as cross-builds seem to be fine with that.

**Pull request merged**
