### PR TITLE
firefox-esr: update to 68.12.0

### PR DESCRIPTION
**Pull request by mmnmnnmnmm**
This is the final release of 68 branch, next version will be firefox-esr 78.

### CODE REVIEW

**Comment by ericonr** [comment]
I guess we should move straight to 78 now, then?

**Comment by mmnmnnmnmm** [comment]
On Wed, 30 Sep 2020 20:26:10 -0700
Érico Nogueira Rolim <notifications@github.com> wrote:

> I guess we should move straight to 78 now, then?

I meant to open a pull request a while ago for 78.2.0, but I've been
busy with a lot of work recently.  I'll open a new pr for 78.3.0 in
a couple of days hopefully :)

**Comment by ericonr** [comment]
> I'll open a new pr for 78.3.0 in a couple of days hopefully :)

Great, thanks! I don't know much about all the new thunderbird features, so I can only test basic functionality of the new version.

**Comment by fosslinux** [comment]
This does fix the FTBTS for firefox-esr bc of rust.. not a bad idea for this to be merged in the meantime.

**Comment by sgn** [comment]
We're at 78.5.0 now

**Pull request closed without merging**
