### PR TITLE
New package: waynergy-0.0.10

### PR DESCRIPTION
**Pull request by Barbaross93**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### New package
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86-64)

### CODE REVIEW

**Comment by Barbaross93** [comment]
Huh, All of the errors are because `wayland-scanner` can't be found; except its included with `wayland-devel`?

**Comment by dmarto** [comment]
> Huh, All of the errors are because `wayland-scanner` can't be found; except its included with `wayland-devel`?

Make it a `hostmakedepends` ;)

**Comment by paper42** [comment]
> Huh, All of the errors are because `wayland-scanner` can't be found; except its included with `wayland-devel`?

it's a binary that's searched for on host, so it has to be in hostmakedepends for cross to work

**Comment by Barbaross93** [comment]
@dmarto @paper42 Ahhh, I was going by the `*-devel` -> `makedepends` rule of thumb. Thanks for the clarification!

**Pull request closed without merging**
