### PR TITLE
himalaya: update to 0.5.9

### PR DESCRIPTION
**Pull request by edganiukov**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for my native architecture, (x86_64-glibc)

### CODE REVIEW

**Comment by leahneukirchen** [comment]
Please rebase!

**Comment by daniel-eys** [comment]
I did some testing and with this template, I got the checks and cross-builds to work:
(There is already version 0.5.9)

```
# Template file for 'himalaya'
pkgname=himalaya
version=0.5.9
revision=1
build_style=cargo
make_check_args="--lib"
hostmakedepends="pkg-config"
makedepends="openssl-devel"
short_desc="CLI email client"
maintainer="Gadzhi Kharkharov <me@kkga.me>"
license="BSD-3-Clause"
homepage="https://github.com/soywod/himalaya"
changelog="https://raw.githubusercontent.com/soywod/himalaya/master/CHANGELOG.md"
distfiles="https://github.com/soywod/himalaya/archive/v${version}.tar.gz"
checksum=70da5d75354e47b47315938b9cbeca2ec167b8e6bd8ce133eff68ef1638d8c59

post_patch() {
	# fixes an indexmap error when cross compiling
	cargo update --package autocfg --precise 1.1.0
}

post_install() {
	vlicense LICENSE
	vdoc README.md
}
```

**Comment by leahneukirchen** [comment]
Do you want to make a PR that supercedes this one?

**Comment by edganiukov** [comment]
@daniel-eys thanks!
I've updated the PR

**Comment by leahneukirchen** [comment]
Need to rebase again, sorry...

**Comment by edganiukov** [comment]
@leahneukirchen done

**Pull request merged**
