### PR TITLE
rpi-kernel: create build style and use it

### PR DESCRIPTION
**Pull request by ericonr**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [ ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

I'm unsure how picking the upstream commit works? I'd like to document that too...

https://github.com/raspberrypi/linux/commit/7772256a0635f0dd5b03f4736402c6c0d6371f32 is the merge, but there seem to be a bunch of reverts right after that one.

[ci skip]

### CODE REVIEW

**Comment by paper42** [comment]
I have been running 5.10 on my rpi3B with the same patch applied on rpi3-kernel for almost a week without any issues. Do you want to switch only rpi-kernel or also all other variants in this PR?

**Comment by ericonr** [comment]
I think I would switch all of them; will make a proper patch for all.

For testing, if interested, @ahesford @Piraty @pbui @fosslinux @amak79

**Comment by ahesford** [comment]
I don't use `rpi-kernel` but can test `rpi{3,4}-kernel`.

**Comment by ahesford** [comment]
The `rpi-kernel` build style looks great!

**Comment by ftpd** [comment]
I've built rpi4-kernel from this PR and it works fine on my rPi 400 (aarch64). If some specific tests are needed, I'm eager to help.

**Comment by ericonr** [comment]
Thanks all for testing! I've pushed the new kernels to master, and now this PR will only deal with the build style.

**Pull request closed without merging**
