### PR TITLE
mate: update to 1.22.0.

### PR DESCRIPTION
**Pull request by thomas-t-w**

### CODE REVIEW

**Comment by Hoshpak** [comment]
Two more updates are needed before the meta-package can be updated:

```
   [runtime] mate-icon-theme-faenza>=1.22.0: not found.
   [runtime] mate-notification-daemon>=1.22.0: not found.
```

**Comment by xtraeme** [comment]
mate-media as well?

**Comment by xtraeme** [comment]
libmatekbd and mate-media were not updated yet.

**Comment by Gottox** [comment]
I'll fix this later. This doesn't work.

**Pull request closed without merging**
