### PR TITLE
radare2: update to 5.4.2, new package: iaito

### PR DESCRIPTION
**Pull request by heittpr**
#### General
- [ ] This is a new package and it conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)

#### Have the results of the proposed changes been tested?
- [x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- [ ] I generally don't use the affected packages but briefly tested this PR

Radare2 was recently forked as [rizin](https://rizin.re/), which cutter (the old radare2 GUI) now uses as a backend, making radare2 and cutter incompatible. Cutter was also forked as [r2cutter](https://github.com/radareorg/iaito) (now rebranded as iaito), to keep compatibility with radare2.

I packaged iaito and made cutter into a subpackage for now, until we decide to package rizin.

### CODE REVIEW

**Comment by ericonr** [comment]
One issue with the subpackage is that it means packaging cutter in the future will require a bunch of `reverts`, since the version number for iaito seems to be way ahead of cutter's.

**Comment by heittpr** [comment]
> How would you feel about packaging rizin so we can just ship both toolkits and UIs? That would avoid having to deal with this in the future, where it gets more complicated :P

I guess I could give it a try :~)

It should be really similar to radare2 package since the fork is relatively recent and thus much of the codebase is actually the same.

**Comment by Johnnynator** [comment]
https://github.com/void-linux/void-packages/pull/34221

> It should be really similar to the radare2 package since the fork is relatively recent and thus much of the codebase is actually the same.

At least for me auto analysis was extremely slow and unreliable in r2 with at least one case, rizin doesn't have the same problem. (also kinda the reason I never got much into using r2 for like anything).

Could you cleanup the PR to only include iaito as new package and the r2 update?

**Comment by ericonr** [comment]
Since https://github.com/void-linux/void-packages/pull/35901 has been merged, I think we just need a new iaito package, correct?

https://github.com/void-linux/void-packages/pull/35976 is doing a radare2 update, as well.

**Comment by ypsvlq** [comment]
Iaito currently isn't having releases made, and the last release is 1 year old doesn't build against current r2.

**Comment by ericonr** [comment]
Oof, that sucks :/

Would you like to keep the PR open? You can try asking upstream for releases.

**Comment by ypsvlq** [comment]
There will be some eventually, I think its just that iaito isn't stable / consistently being worked on yet.

> [12:12] pancake: Right now iaito is broken because im waiting to release r2-5.7 which will address the thread handling problems that it have right now

**Pull request closed without merging**
